### ISSUE TITLE
Get-Time isn't a PowerShell cmdlet

### ISSUE THREAD

**Issue by JimMoyle** [MicrosoftDocs/PowerShell-Docs#10003]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-7.3#notes

### Summary

In the Notes section the example uses a sample PowerShell cmdlet 'Get-Time' which does not exist. The correct cmdlet is 'Get-Date'

### Details

N/A

### Suggested Fix

Update Get-Time to Get-Date and provide the correct output

PS C:\Users\jimoyle> (Get-Command Get-Date).OutputType

Name            Type            TypeDefinitionAst
----            ----            -----------------
System.String   System.String
System.DateTime System.DateTime

**Comment by michaeltlombardi** [comment]
@JimMoyle That example is building on a [prior example][01], which defines `Get-Time` as:

```powershell
function Get-Time
{
  [OutputType([DateTime])]
  Param (
    [parameter(Mandatory=$true)]
    [Datetime]$DateTime
  )

  $DateTime.ToShortTimeString()
}
```

I'll update the document to use `Get-Date` instead, since it can be missed.

[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_outputtypeattribute#example-3-shows-when-an-actual-output-differs-from-the-outputtype
