### ISSUE TITLE
PowerShell store link many be outdated 

### ISSUE THREAD

**Issue by AndrewBlumhardt** [MicrosoftDocs/PowerShell-Docs#10011]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

### Summary

Microsoft Store link in the following doc appears to be outdated\invalid: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

### Details

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

### Suggested Fix

Correct URL if it is incorrect.

**Comment by michaeltlombardi** [comment]
The link defined here:

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/d79ce533112544b83f7312daf228dbef1e9ac300/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md?plain=1#L181

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/d79ce533112544b83f7312daf228dbef1e9ac300/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md?plain=1#L396

Resolves for me:

```powershell
$TitlePattern = '<meta property="og:title" content="(?<Title>[^"]+)"\s*/>'
$StoreUri     = 'https://www.microsoft.com/store/apps/9MZ1SNWT0N5D'
Invoke-WebRequest -Uri $StoreUri |
    Select-Object -Property StatusCode, StatusDescription, @{
        Name       = 'Title'
        Expression = {
            if ($_.Content -match $TitlePattern) {
                $matches.Title
            }
        }
    } |
    Format-List
```

```
StatusCode        : 200
StatusDescription : OK
Title             : Get PowerShell from the Microsoft Store
```

Can you help me understand where the link takes you instead?

**Comment by sdwheeler** [comment]
The link is correct. The screenshot in the Store is outdated. We don't control that content. The actual version in the store can be behind for a week or two after a release. It takes time to get the store package updated.
