### ISSUE TITLE
Parameters listet for the -Encoding switch in import-csv are wrong

### ISSUE THREAD

**Issue by APACIUS** [MicrosoftDocs/PowerShell-Docs#10045]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-csv?view=powershell-7.3#-encoding

### Summary

In the Documentation you can read the parameters for the Parameter Encoding.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-csv?view=powershell-7.3#-encoding

The list is wrong, the Values UTF8BOM and UTF8NOBOM are no valid parameters for Import-csv cmdlet.

the Value DEFAULT is also missing from the list of valid Values.

### Details

N/A

### Suggested Fix

remove UTF8BOM and UTF8NOBOM from the list of valid Values for the enoding parameter.

add DEFAULT as a valid Parameter for the Encoding Value

**Comment by michaeltlombardi** [comment]
@APACIUS I think you're looking at the wrong version of the documentation for `Import-Csv` - the link in your issue shows that it's for version 7.3, but it seems like you're expecting the values for Windows PowerShell.

In the [documentation for `Import-Csv` in 5.1][01], you can see that `Default` is listed and that neither `utf8BOM` nor `utf8NoBOM` are.

[01]: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-csv?view=powershell-5.1#-encoding
