### ISSUE TITLE
Help Content (cab) seems unavailable

### ISSUE THREAD

**Issue by nyanhp** [MicrosoftDocs/PowerShell-Docs#10051]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

Not a docs issue, but an issue with generated help cabs.

### Summary

It seems like most if not all help content is not available any longer. Example (v5 as well as v7):
```powershell
invoke-restmethod (Get-Module -List Microsoft.PowerShell.Management).HelpInfoUri
```

### Details

Other modules like PSDesiredStateConfiguration appear to be affected as well.

### Suggested Fix

Unclear. Since the error mentions that the storage blob cannot be found, I would start looking at the storage account hosting the help cab/xml.

**Comment by sdwheeler** [comment]
The HelpInfoUri point to the folder not the file. The 404 error is expected for the folder because there is not default file for that Uri and you can't browse the folder.
