### ISSUE TITLE
Please don't use apt-key to add trust chains

### ISSUE THREAD

**Issue by jeff-hiner** [MicrosoftDocs/PowerShell-Docs#10096]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.3#installation-on-debian-11-via-package-repository

### Summary

Installing GPG keys via apt-key adds a trust root across ALL repositories. The trust root should be properly scoped to packages.microsoft.com.

I spent several weeks issuing a writeup about this issue about a year ago. Please update the Debian install documentation accordingly.

https://blog.cloudflare.com/dont-use-apt-key/

### Suggested Fix

Replace the key retrieval and sources.list steps as follows:
```
# Import the public repository GPG keys
curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --yes --dearmor --output /usr/share/keyrings/microsoft.gpg

# Register the Microsoft Product feed
sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list'
```

**Comment by sdwheeler** [comment]
@TravisEz13 Can you comment on this suggestion?

**Comment by eric-desrochers** [comment]
Also note that in modern version of Debian/Ubuntu, `apt-key` is now deprecated and user can see the following warning:

From Ubuntu 22.04 (Jammy) :
`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`
