### ISSUE TITLE
Document the new `GetPSModulePath` API in the release notes

### ISSUE THREAD

**Issue by JamesWTruher** [MicrosoftDocs/PowerShell-Docs#10121]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

documentation of the API created by https://github.com/PowerShell/PowerShell/pull/19422 should be created.

### Summary

a new public API `GetPSModulePath` was created by the referenced PR - it allows developers to easily retrieve information about the various PSModulePaths which are available

### Suggested Fix

the /// should serve well enough

**Comment by sdwheeler** [comment]
Fixed in #10230
