### ISSUE TITLE
`about_Module_Manifests` doesn't include information about experimental features

### ISSUE THREAD

**Issue by michaeltlombardi** [MicrosoftDocs/PowerShell-Docs#10137]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_module_manifests

### Summary

In the [Declaring Experimental Features in Modules written in PowerShell][a1] section of `about_Experimental_Features`, the documentation notes the use of `PrivateData.PSData.ExperimentalFeatures` for declaring experimental features in a module, but this data isn't covered or mentioned in [about_Module_Manifests][a2]. This makes the functionality less discoverable.

[a1]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_experimental_features#declaring-experimental-features-in-modules-written-in-powershell
[a2]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_module_manifests

### Suggested Fix

The `about_Module_Manifests` article should be updated with a short explanation of using PSData for experimental features and link to `about_Experimental_Features` for more information.

**Comment by sdwheeler** [comment]
Crescendo also adds two values to `PrivateData`.
- `PrivateData.CrescendoGenerated` - timestamp of when the module was exported
- `PrivateData.CrescendoVersion` - the version of Crescendo used to export the module
