### ISSUE TITLE
Module manifests allow environment variables

### ISSUE THREAD

**Issue by ThomasNieto** [MicrosoftDocs/PowerShell-Docs#10140]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Modes.md
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Module_Manifests.md

### Summary

Per PowerShell/PowerShell#19747 module manifests allow environment variables via the `$env` variable. This should be added to allowed variables section of those docs.

**Comment by michaeltlombardi** [comment]
Well, this is interesting - I made a `temp.ps1` script with this content:

```powershell
$ExecutionContext.SessionState.LanguageMode = 'RestrictedLanguage'
$ExecutionContext.SessionState.LanguageMode
$env:PROCESSOR_ARCHITECTURE
```

And running the script seems to imply you're correct:

```output
RestrictedLanguage
AMD64
```

But back at my terminal after running the script:

```powershell
$env:PROCESSOR_ARCHITECTURE
```

```output
ParserError: 
Line |
   1 |  $env:PROCESSOR_ARCHITECTURE
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A variable that cannot be referenced in restricted language mode or a
     | Data section is being referenced. Variables that can be referenced
     | include the following: $PSCulture, $PSUICulture, $true, $false, $null.
```

Which is what I would expect from our documentation.

However, I did try a mockup module and manifest:

```powershell
# EnvInManifestTest.psm1
function Get-ModuleDescription {
    [CmdletBinding()]
    param()

    process {
        $PSCmdlet.MyInvocation.MyCommand.Module.Description
    }
}
```

```powershell
# EnvInManifestTest.psd1
@{
    RootModule        = 'EnvInManifestTest.psm1'
    ModuleVersion     = '0.0.1'
    GUID              = '0f10af31-0d75-4867-b84f-138aa8e301d8'
    Description       = $ENV:ModuleDescription
    FunctionsToExport = '*'
    CmdletsToExport   = '*'
    VariablesToExport = '*'
    AliasesToExport   = '*'
}
```

```powershell
ipmo .\EnvInManifestTest.psd1
Get-ModuleDescription
$ENV:ModuleDescription = 'From an environment variable'
ipmo .\EnvInManifestTest.psd1 -Force
Get-ModuleDescription
```

```output

From an environment variable
```

So it does look like you can use environment variables in module manifests, at least. I suspect the weird behavior around the script setting restricted language mode is it not applying in that scope.
