### ISSUE TITLE
Quality: ArgumentCompleter example script lists 3x vegetables that are technically fruits

### ISSUE THREAD

**Issue by thegraffix** [MicrosoftDocs/PowerShell-Docs#10160]
### Prerequisites

- [X] **Existing Issue:**

Search the existing [quality issues][b1] for this repository. If there's an issue that
covers the quality area and articles you want to improve, pick a different quality area
or article set. Don't file a new issue for the same work. Subscribe, react, or comment
on that issue instead.

[b1]: https://github.com/orgs/MicrosoftDocs/projects/15/views/3?filterQuery=repo%3A%22MicrosoftDocs%2FPowerShell-Docs%22+is%3Aissue

- [X] **Descriptive Title:**

Write the title for this issue as a short synopsis. If possible, provide context. For
example, "Quality: Command Syntax in Foo" instead of "Quality: Foo"

### Quality Areas

Spelling

### Article List

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion?view=powershell-7.3#argumentcompleter-script-block

**NOTE** -- This seems incredibly nuanced and picky, but programming is all about getting the details right, so that's the spirit in which this suggestion is being submitted.

The example script in the ArgumentCompleter attribute section includes an array: `Vegetables = @('Tomato', 'Squash', 'Corn')`

Tomatoes, squash and corn are all _technically_ classified as fruit.  Corn is less sturdy in its classification depending on the criteria used to define it -- but it is classified as a fruit in the domain of plant taxonomy.

I'd like to submit some common and easy to spell vegetables in place of `Tomato` `Squash` and `Corn`:

- Carrot
- Celery
- Lettuce
- Onion
- Radish

**Comment by sdwheeler** [comment]
@thegraffix We await your PR.

**Comment by thegraffix** [comment]
PR sent.
