### ISSUE TITLE
Clarify that AppX reparse points do not support listing their targets anymore in v7.2+

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#10168]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_FileSystem_Provider?view=powershell-7.4
* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_FileSystem_Provider?view=powershell-7.3
* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_FileSystem_Provider?view=powershell-7.2

* https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-7.4
* https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-7.3
* https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-7.2

### Summary

Support for determining the targets of AppX reparse points (aka AppExecLinks, such as `winget` / Microsoft Store-installed applications) was removed in v7.3, and, [according to @sdwheeler](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10168#issuecomment-1591957004), back-ported to v7.2

 * See https://github.com/PowerShell/PowerShell/issues/19760#issuecomment-1585718184 for background information.

### Details

The upshot for AppX reparse points in v7.2+ is:

* They no longer print their target after ` -> ` in the formatted output.
  * https://github.com/PowerShell/PowerShell/issues/19794 suggests eventually removing ` -> ` too.

* Their type-native `.LinkTarget` property and their ETS `.LinkType` and `.Target` properties (an alias of `.LinkTarget`) are all `$null`; the type-native `.ResolvedTarget` property now returns the reparse point's own full path.

* _Visually_, the `l` as the first character in the `Mode` column is now the only indicator that the item is a reparse point.

* To _programmatically_ identify an AppX reparse point now requires:

   * `$item.Attributes.HasFlag([System.IO.FileAttributes] 'ReparsePoint') -and $null -eq $item.LinkType`
   * If the ETS properties are present, more simply:
     * `$item.Mode -like 'l*' -and $null -eq $item.LinkType`

### Suggested Fix

It's probably worth mentioning at least a condensed version of the above in the linked topics.

**Comment by sdwheeler** [comment]
This also affects 7.2.11. The change was backported to 7.2 at some point.

**Comment by mklement0** [comment]
Thanks, @sdwheeler - I've updated the title and the initial post accordingly.

**Comment by sdwheeler** [comment]
> To _programmatically_ identify an AppX reparse point now requires:

I talked with @SteveL-MSFT about getting the `.LinkType` member populated.
