### ISSUE TITLE
Say Mandatory attribute implies ValidateNotNull in about_Functions_Advanced_Parameters

### ISSUE THREAD

**Issue by NLZ** [MicrosoftDocs/PowerShell-Docs#10179]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md?plain=1#L330

### Summary

In `about_Functions_Advanced_Parameters` at the `Mandatory` parameter attribute the document could bring to the user's attention that `Mandatory` implicitly validates for non-null parameters, unless explicitly allowed via `AllowNull` and co.

So `Mandatory` together with `ValidateNotNull` is redundant, which is actually said under the `ValidateNotNull` validation attribute section:
>The ValidateNotNull attribute is designed to be used when the parameter is optional (...)

Yet the example of `ValidateNotNullOrEmpty` uses `Mandatory`, which is obsolete:
```pwsh
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string[]]
    $UserName
```
So I would also remove the `Mandatory` from this example.

**Comment by sdwheeler** [comment]
You are comparing the statement about optional parameters from `ValidateNotNull` to the example code for `ValidateNotNullOrEmpty `. Those are different scenarios.

Validating for null or empty on a mandatory parameter is useful when the parameter accepts an array of objects. You can pass an array that contains an empty string. The array object is not null but one of the items is. So you satisfy the `Mandatory` requirement but fail the validation. You get an error with or without the validation, however, the error message with validation is more useful.

For example:
```powershell
function test-validation {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory,ValueFromPipeline)]
        [string[]]$Name
    )
    process {
        $Name
    }
}
```

Notice the error when you don't use validation.

```
PS> $array = "a","b",""
PS> test-validation $array
test-validation: Cannot bind argument to parameter 'Name' because it is an empty string.
```

Now add validation:

```powershell
function test-validation {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory,ValueFromPipeline)]
        [ValidateNotNullorEmpty()]
        [string[]]$Name
    )
    process {
        $Name
    }
}
```

Note the validation error message:

```
PS> $array = "a","b",""
PS> test-validation $array
test-validation: Cannot validate argument on parameter 'Name'. The argument is null, empty, or an
element of the argument collection contains a null value. Supply a collection that does not contain
any null values and then try the command again.

PS> $array | test-validation
a
b
test-validation: Cannot validate argument on parameter 'Name'. The argument is null, empty, or an
element of the argument collection contains a null value. Supply a collection that does not contain
any null values and then try the command again.
```

**Comment by NLZ** [comment]
Thank you, I haven't considered that
