### ISSUE TITLE
Thread jobs and variables example about thread safe variables is to abstract

### ISSUE THREAD

**Issue by DennisL68** [MicrosoftDocs/PowerShell-Docs#10189]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.2, 7.3, 7.4

### Summary

The current example of thread safe variable handling provided is based on a .Net object. I had some issue understanding this example as it uses an unfamiliar object as an example.

Please add a pure PowerShell example as well.

### Details

This is my own example that made me learn how manipulation of variables using threads works.
Feel free to add it to the documentation.

~~~
[Array]$Numbers = @()
$refNumbersVar = Get-Variable Numbers

foreach ($i in 1..10) {
    $Jobs = Start-ThreadJob {
        ($Using:refNumbersVar).Value += $using:i
    }
}

$Jobs | Wait-Job | Remove-Job

$Numbers

1
2
3
4
5
6
7
8
9
10
~~~

### Proposed Content Type

About Topic

### Proposed Title

Use current about_Thread_Jobs

**Comment by sdwheeler** [comment]
@DennisL68 While your example may work most of the time, is not guaranteed to be thread safe. 

The [**System.Collections.Concurrent**](https://learn.microsoft.com/dotnet/api/system.collections.concurrent?view=net-7.0) namespace provides several thread-safe collection classes that should be used in place of the corresponding types in the **System.Collections** and **System.Collections.Generic** namespaces whenever multiple threads are accessing the collection concurrently.

The **System.Collections.Concurrent.ConcurrentDictionary** class uses fine-grained locking to ensure write operations are thread safe. The **Array** class does not.

**Comment by DennisL68** [comment]
So what does that mean in reality. That two thread could try to create the very same item in the array and one would fail?

**Comment by DennisL68** [comment]
That class doesn't seem to be available out-of-the-box in PowerShell 7.2...

~~~
$Numbers = New-Object System.Collections.Concurrent.ConcurrentDictionary
New-Object: Cannot find type [System.Collections.Concurrent.ConcurrentDictionary]: verify that the assembly containing 
this type is loaded.
~~~

**Comment by DennisL68** [comment]
That object doesn't seem to be avialbe out of the box for PowerShell 7.2
~~~
$Numbers = New-Object System.Collections.Concurrent.ConcurrentDictionary
New-Object: Cannot find type [System.Collections.Concurrent.ConcurrentDictionary]: verify that the assembly 
containing this type is loaded.
~~~

**Comment by sdwheeler** [comment]
You can't create it that way. It is a generic. You have to specify the types for the dictionary components. The example in about_Thread_Jobs works.

**Comment by DennisL68** [comment]
Yes, but I don't understand it :)

**Comment by sdwheeler** [comment]
Correction, you can do it with `New-Object`. For example:

```
$stringList = New-Object -TypeName System.Collections.Generic.List[string]
```

**Comment by DennisL68** [comment]
Ok, but will that be the same class as System.Collections.Concurrent.ConcurrentDictionary?
I.e., will the object be thread safe?

**Comment by sdwheeler** [comment]
> $stringList = New-Object -TypeName System.Collections.Generic.List[string]

This is an example of using `New-Object` to create an object from a generic type. That is not a thread-safe type.

Here is an example for ConcurrentDictionary. For this one you need to enclose the type in quotes.
```
PS> $threadSafeDictionary = New-Object 'System.Collections.Concurrent.ConcurrentDictionary[string,object]'
PS> $threadSafeDictionary.GetType().FullName
System.Collections.Concurrent.ConcurrentDictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
```

**Comment by DennisL68** [comment]
Ah, the last part of the name that looks like an argument :)
I find that just a bit confusing ;)

**Comment by DennisL68** [comment]
My example broke...

$i is an integer

When receiving on of the jobs I get:
~~~
InvalidOperation:
Line |
   2 |          ($Using:refNumbersVar).Value += $using:i
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A hash table can only be added to another hash table.
~~~

**Comment by DennisL68** [comment]
I've been reading up some more on the thread safe collection class.

Shouldn't I be using any of the methods AddOrUpdate, GetOrAdd, TryAdd, TryGetValue,TyrUpdate, TryRemove when adding items instead of +=?

as specified in [MS Learn - How to add and remove items from a ConcurrentDictionary](https://learn.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-add-and-remove-items)
