### ISSUE TITLE
Do not mention the default value -1 for the `-TotalCount` parameter of `Get-Content`

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#10183]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.3#-totalcount

### Summary

After https://github.com/PowerShell/PowerShell/pull/19715 got merged, a user won't be able to specify -1 as the value to `-TotalCount`, because now it only accepts a non-negative value. The [Cmdlet WG suggests](https://github.com/PowerShell/PowerShell/pull/19715#issuecomment-1601162381) removing mention of this internal detail.

BTW, the `-Tail` parameter also has -1 as the default value, but [it's not mentioned in the doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.3#-tail), so we should do the same to `-TotalCount`.

### Details

- https://github.com/PowerShell/PowerShell/pull/19715

**Comment by Overruler** [comment]
As of today, [Get-Content -TotalCount](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.5#-totalcount) continues to indicate that negative values (including the previous default value -1) are allowed:
```
-TotalCount
Specifies the number of lines from the beginning of a file or other item. Negative values cause the cmdlet to return the entire contents.
```
