### ISSUE TITLE
New-Item does not list 'Target' parameter

### ISSUE THREAD

**Issue by gaiking-uk** [MicrosoftDocs/PowerShell-Docs#10199]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.3

### Summary

A `New-Item` error message suggested that a parameter `Target` was required, however this does not exist according to the `New-Item` page.

### Details

I got the below error when trying to create a junction with `New-Item`...

```lang=ps
$JuncName = "Foo"
$JuncTarget = "D:\Junction_Target"
> New-Item -ItemType Junction -Name $JuncName -Path $JuncTarget

ERROR: Link "D:\Junction_Target" cannot be created because Target was not specified
```

### Suggested Fix

If the error message is correct and a `Target` parameter is required, please can this listed as a `parameter` and an example usage included in the documentation.

**Comment by sdwheeler** [comment]
@gaiking-uk The error message is unfortunate and probably should be [reported as a bug][1] in the source code repository.

The actual parameter is `-Value`. **Target** is an alias for that parameter. That is documented in the help.

[1]: https://aka.ms/psfeedback

**Comment by gaiking-uk** [comment]
Thanks for the clarification @sdwheeler -- have raised a bug as requested [#19849](https://github.com/PowerShell/PowerShell/issues/19849)
