### ISSUE TITLE
Documentation should mention that `Get-Random -Count` samples without replacement

### ISSUE THREAD

**Issue by wjholden** [MicrosoftDocs/PowerShell-Docs#10204]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-random?view=powershell-7.3

### Summary

If you enter the command `(1..100) | Get-Random -Count 1000 | Measure-Object`, you're practically guaranteed to see 100 as the count. It looks like `GetRandomCommandBase.cs` removes items from the list as it randomly selects them.

This behavior is unexpected for some users. A small note in the documentation would be nice. A `-WithReplacement` flag would be even better.

The workaround I came up with is to do something like this: `(1..1000) | % { (1..100) | Get-Random } | Measure-Object`. This has the effect of sampling with replacement. 

### Suggested Fix

Add something like the following to the examples for `Get-Random`:

```
Example 14: Sample 1000 items from the range (1..100) with replacement.
When using -Count, items are removed from the list once selected.

(1..1000) | % { (1..100) | Get-Random }
```

**Comment by sdwheeler** [comment]
@wjholden The documentation for `-Count` states:

> ... if the value of **Count** exceeds the number of objects in the collection, `Get-Random` returns all the objects in random order.

If you want 1000 items from the range (1..100)

```
Get-Random -min 1 -max 100 -Count 1000
```
