### ISSUE TITLE
Write-Information - Missing Colored output example

### ISSUE THREAD

**Issue by kensel** [MicrosoftDocs/PowerShell-Docs#10214]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-information?view=powershell-7.3

### Summary

Request to add details on the information input object to adjust the output with formatting similar to Write-Host.  From the website [kieranties](https://blog.kieranties.com/2018/03/26/write-information-with-colours) it looks like the object is '[HostInformationMessage]' but I don't see that mentioned in the documentation.

### Suggested Fix

Add an example with something like the following:
```PowerShell
$msg = [System.Management.Automation.HostInformationMessage]@{
        Message         = $MessageData
        ForegroundColor = $ForegroundColor
        BackgroundColor = $BackgroundColor
        NoNewline       = $NoNewline.IsPresent
    }

    Write-Information $msg
```

**Comment by sdwheeler** [comment]
@kensel Thanks for the suggestion. However, the purpose of the cmdlet documentation is to document the parameters and capabilities of the cmdlet. The example you provide works, but has nothing to do with the public interfaces of `Write-Information`.

The `Write-Host` cmdlet provides parameters to handle colors and newline behavior, and it writes to the **Information** stream. Use `Write-Host` instead.
