### ISSUE TITLE
remove extraneous linebreaks

### ISSUE THREAD

**Issue by zjalexander** [MicrosoftDocs/PowerShell-Docs#1025]
Issue Details
-----------------

"we should probably script something up at some point to get rid of all the extraneous line breaks that got caused by too many conversions of content over the years. I can’t think of a reason why we’d ever want more than one empty line at a time in help" - @joeyaiello 

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by zjalexander** [comment]
see also: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/17417143-inputs-and-outputs-section-of-get-help-not-display

**Comment by sdwheeler** [comment]
@zjalexander Is this a PlatyPS issue or do we have work to fix the markdown? Is there an example topic you can link to?

**Comment by MSAdministrator** [comment]
Same with this, if you want some help I can run through these fairly quickly.

**Comment by sdwheeler** [comment]
@MSAdministrator Go for it.

**Comment by MSAdministrator** [comment]
Awesome, I’m working through them as we speak. Scripted some of it, but some is too complex (unless I’m not thinking of something). I should have all versions (3.0 - 6) updated with the same format across the board. :)

**Comment by sdwheeler** [comment]
@MSAdministrator Keep the number of files per PR down to 10 or fewer. That will make it easier to review the changes.

**Comment by MSAdministrator** [comment]
Will do! @sdwheeler I’ll submit a single PR tonight to make sure everyone is cool with it.

**Comment by MSAdministrator** [comment]
@sdwheeler An example of my changes across all the docs is in #2070

**Comment by sdwheeler** [comment]
To anyone who wants to contribute to docs:

The goal of this Issue is to remove unneeded or erroneous extra lines in the articles. Extra lines in the example output blocks are errors. Extra lines in the Markdown paragraphs are unneeded since they will be reduced to a single blank line when rendered on the web page. However, multiple blank lines fills the screen and makes for a poor experience in the console window.

Also, please read the [Contributor's Guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/CONTRIBUTING.md). There have been many changes and updates added recently.

**Comment by sdwheeler** [comment]
Bobby has a tool that does this. He is working on this cleanup.

**Comment by doctordns** [comment]
is this issue still 'live'?

**Comment by sdwheeler** [comment]
@doctordns Yes, it is still active. However, the effort is limited to fixing articles as they are touched for other reasons. So there may not be a need to track this issue.

**Comment by joeyaiello** [comment]
I'd like to leave this open just in case someone does decided to go to the effort of scripting the long tail.

**Comment by MSAdministrator** [comment]
I was working on this for bit but had some technical issues (e.g. I deleted my local branch on accident). I’ll try and get to this soonish if no one else does

**Comment by sdwheeler** [comment]
This has been done in bulk. If there new cases found, please open a new issue for the specific document.
