### ISSUE TITLE
Provide suggestions on how a hashtable can be constructed from two arrays: one being the array of keys, and the other the array of values?

### ISSUE THREAD

**Issue by bzm3r** [MicrosoftDocs/PowerShell-Docs#10285]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

* [Everything you wanted to know about hashtables](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.3) (probably this is where such a comment should go)

* [about_Hash_Tables](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-7.3) (possibly)

### Summary

It is not clear to me, reading the above linked docs, how one could generate a hash table if they have an array of keys, and an array of values. 

In other languages, one typically "zips" the two arrays together into a single array of 2-tuples (where the first item in the tuple comes from the first array, the second item from the second array), and then there is a hashtable constructor that generates a hashtable from an array of 2-tuples. 

Is there corresponding functionality in PowerShell?

### Details

Here's what I could come up with as solutions:

* `LINQ`: zip the arrays as discussed [in this SO answer](https://stackoverflow.com/a/44055098/3486684) and then use the result to sequentially add the zipped key-value pairs to the `$hash` using what is described [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-7.3#adding-and-removing-keys-and-values) --- maybe there is even more `LINQ` magic (I do not know C# at all) one could do to smoothly create a hash table in this way

* `for`: check to see which array is the shortest, then use that to loop through both arrays: `for ($i = 0; $i -lt $MinLength; $i++)` getting the key from the keys array, and the value from the values array, and then again adding it to the hashtable as described [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-7.3#adding-and-removing-keys-and-values)

But I am not sure if there is a better method than the above two.

### Suggested Fix

No solid suggestion yet, as I do not have enough experience with PS. Perhaps one of the solutions I outlined in `Details` above could serve as an addition to the documentation, perhaps not.

**Comment by sdwheeler** [comment]
Using the `for` loop is the only native method of doing this in PowerShell.

Using LINQ works but that is using .NET classes outside of core PowerShell. Nothing wrong with that. There may be other ways with other .NET classes and invoking C# from PowerShell.

At this time, I don't think there is anything to add to the documentation. The docs already explain how to add key-value pairs to a hashtable. How you merge multiple sets of data into one collection can vary greatly depending on your needs. But that doesn't change how you add items to a hashtable.

For more information, you may want to check out these discussions:
- https://github.com/PowerShell/PowerShell/issues/13817
- https://github.com/PowerShell/PowerShell/issues/15848
