### ISSUE TITLE
Installation via direct Ubuntu Package Repository

### ISSUE THREAD

**Issue by rgl** [MicrosoftDocs/PowerShell-Docs#10297]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.2

### Summary

Provide a guide on how to install in Ubuntu via Package Repository alike what is done for Debian at https://learn.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.2#installation-on-debian-11-via-package-repository.

### Details

Having a direct link to the repository is more transparent and easier to understand/troubleshoot than having an indirect `.deb` file that does an indirect installation of the repository.

### Suggested Fix

Add a section like the one in Debian at https://learn.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.2#installation-on-debian-11-via-package-repository that show how to manually configure the repository.

**Comment by sdwheeler** [comment]
We are reviewing the installation instructions for all of the Linux distributions. I expect to have some changes. For now, the documentation reflects the installation methods we support.

**Comment by StevenBucher98** [comment]
@rgl is the instructions in the ubuntu installation page here, https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.2#installation-via-package-repository,  insufficient? Is there a specific scenario you are trying to do that the docs are not covering?

**Comment by rgl** [comment]
@StevenBucher98, please see https://github.com/microsoft/vscode/issues/190960. All the Microsoft .deb package seem to have that same problem.

**Comment by rgl** [comment]
Thanks for the updates!

Were the concerns in this issue actually addressed? Are we now able to prevent the scripts inside `.deb` from messing up the host APT repository configuration? If so, how?

**Comment by sdwheeler** [comment]
The install documentation for Ubuntu, Debian, and RHEL was refactored to show how to install from packages.microsoft.com (aka PMC). This is the supported method. If the packages published to PMC are changing something that they shouldn't, then please [file an issue][1] in the source code repository.

[1]: https://aka.ms/psfeedback

**Comment by rgl** [comment]
Its at https://github.com/PowerShell/PowerShell/issues/20379.
