### ISSUE TITLE
Test-Connection : A parameter cannot be found that matches parameter name 'repeat'.

### ISSUE THREAD

**Issue by billspeers** [MicrosoftDocs/PowerShell-Docs#10292]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7.3

### Summary

Test-Connection : A parameter cannot be found that matches parameter name 'repeat'.

**Comment by michaeltlombardi** [comment]
@billspeers, can you share the snippet of code you're running that raises this error? The **Repeat** parameter is only valid in one of the parameter sets, and can't be used with the **Count** parameter.

```powershell
Test-Connection 8.8.8.8 -Repeat
```

```output
Destination: 8.8.8.8

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 MyComputerName   8.8.8.8                        11         32 Success
   2 MyComputerName   8.8.8.8                        12         32 Success
   3 MyComputerName   8.8.8.8                        11         32 Success
```

**Comment by sdwheeler** [comment]
@billspeers You are using Windows PowerShell 5.1. That version does not have the parameter. The documentation you were looking at was for PowerShell 7.3. You can choose the version of PowerShell documentation from the version picker above the Table of Contents.

[How to use the PowerShell documentation][1], has tips on navigating the documentation.

[1]: https://docs.microsoft.com/powershell/scripting/how-to-use-docs.
