### ISSUE TITLE
Out-file -Width parameter documentation clarification

### ISSUE THREAD

**Issue by si-chan** [MicrosoftDocs/PowerShell-Docs#10309]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-7.3#-width

### Summary

The documentation states:
Specifies the number of characters in each line of output. 

This should be refined to state:
Specifies the MAXIMUM number of characters in each line of output. 

This is because each line in the output can contain either the maximum number of characters specified by -Width or fewer characters.

### Details

See summary.
The observation above probably applies to all PowerShell versions.

### Suggested Fix

See summary

**Comment by michaeltlombardi** [comment]
The paragraph reads, in full:

> Specifies the number of characters in each line of output. Any additional characters are truncated, not wrapped. If this parameter is not used, the width is determined by the characteristics of the host. The default for the PowerShell console is 80 characters. If you want to control the width for all invocations of `Out-File` as well as the redirection operators (`>` and `>>`), set `$PSDefaultParameterValues['out-file:width'] = 2000` before using `Out-File`.

This clarifies the usage to the point where I think the ambiguity is resolved, but I'll add `maximum` to the first sentence.
