### ISSUE TITLE
Could use more information on ErrorAction or pointer to those docs

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/PowerShell-Docs#10332]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

Oh, thought this was auto-filled in like the other doc repositories and was confused why I couldn't submit...

- https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-exceptions?view=powershell-7.3

### Summary

Was looking for more information on ErrorAction, this blog ended up being more helpful: https://devblogs.microsoft.com/powershell/erroraction-and-errorvariable/

Couldn't find the actual official page on these parameters, this page came up first instead, so could be good if it pointed to more resources.

**Comment by sdwheeler** [comment]
Those are common parameters. See [about_CommonParameters](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_commonparameters)
