### ISSUE TITLE
Get-ChildItem documentation missing muliple -Include variation  

### ISSUE THREAD

**Issue by dank8** [MicrosoftDocs/PowerShell-Docs#10331]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://github.com/MicrosoftDocs/PowerShell-Docs/tree/main/reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md

### Summary

A footnote mentions that multiple items are possible for the `-Include` parameter. But this is not described in the main documentation for the `-Include` parameter.

### Details

Update the documentation page of [Get-ChildItem](https://github.com/dank8/PowerShell-Docs/blob/c2bcdf59167b56f560c7d0b8fee7557591d3bf34/reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md)

  1. Add one more variation in **Examples** at the end of **Example 4**
  2. Split and expand the first paragraph for the definition of the `-Include` **Parameter** 

### Suggested Fix

1. Add one more variation in **Examples** at the end of **Example 4**
----
### Example 4: Get child items using the Include parameter
 ```powershell
# When using the -Include parameter, multiple entries are possible
Get-ChildItem -Path C:\Test\* -Include *.txt, *.md
```

```Output
    Directory: C:\Test
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/13/2019     08:55             26 anotherfile.txt
-a----        2/13/2019     08:55             26 Readme.md
-a----        2/12/2019     15:40         118014 Command.txt
-ar---        2/12/2019     14:31             27 ReadOnlyFile.txt
```

2. Split and expand the first paragraph for the definition of the `-Include` **Parameter** 
----
### -Include

Specifies an array of one or more string patterns to be matched as the cmdlet gets child items. Any
matching item is included in the output. 

The `-Path` parameter must include a wild card such as `C:\Windows\*`. Enter a path element or pattern,
such as `"*.txt"`. Wildcard characters `*` or `?`  are permitted. The **Include** parameter is effective only 
when the command includes the contents of an item, such as `C:\Windows\*`, where the wildcard 
character specifies the contents of the `C:\Windows` directory.

**Comment by sdwheeler** [comment]
The type accepted by the **Include** parameter is shown as a string array. You can use any form of an array expression for any parameter that takes an array.

**Comment by michaeltlombardi** [comment]
Closing this issue as the requested documentation is for a general practice (using array parameter values) that is well-documented across the docset, not a special case for the parameter or cmdlet.
