### ISSUE TITLE
PowerShell SDK examples should come with PowerShell language option

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/PowerShell-Docs#10356]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.3

### Summary

Currently, the PowerShell SDK comes with examples in the following languages:

- C++
- C++/CX
- C++/WinRT
- C#
- VB
- F#

But there's no example code available written in PowerShell.

This is frustrating when trying to use the `$PSCmdlet` methods.

### Proposed Content Type

Cmdlet Reference

### Related Articles

https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.shouldcontinue?view=powershellsdk-7.3.0

**Comment by sdwheeler** [comment]
We agree, it would be good to have PowerShell examples for most of the .NET APIs. However, that documentation is autogenerated from ///-comments in the source code. The code examples are either written into the comments or autogenerated by .NET reflection on the API. It's not possible to create the PowerShell the same way.

**Comment by sdwheeler** [comment]
The short answer is no. The tools that generate the content don't have an option to output PowerShell. 

Could it be possible? Sure, but we (the docs team and docs platform) don't own or control the tools. Someone would have to write that code.
