### ISSUE TITLE
Type accelerator List: Add general method on how to get more help/info/syntax for each type accelerator

### ISSUE THREAD

**Issue by Godsfunambulator** [MicrosoftDocs/PowerShell-Docs#10377]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_type_accelerators?view=powershell-7.3

### Summary

The Type accelerator List is very nice but doesn't give any indication as to how to get more information about each type.  Please add general method on how to get more help/info/syntax for each type accelerator.  

### Details

If there is not a general method there should be links to another help page explaining them, or at least add some more info to the table.  For example, the version type is very useful for storing, recalling, and comparing software version but it doesn't say that the syntax is #.#.#.# or anything else about it.  How would someone who looked through this list know how to use this type to know if it is a right fit for what they are doing. Some software doesn't follow this syntax and it may not work, or the user may not realize this was a standard method.  This documentation should help direct the user to get more info about each accelerator type.

This would immensely improve the quality and useability of this article.  Unfortunately, I don't know enough to know how to do this, or if this info is stored anywhere or even where to go to learn now to do this but it seems like it should be possible.  I have been searching on how to find out more about specific types within PS or the learning hub and cannot find it.

### Suggested Fix

Add general method, or link to general method on how the user can get more information about each type accelerator.

**Comment by sdwheeler** [comment]
@Godsfunambulator You have to look at the documentation for each type. I updated the docs to include a link to the docs for each type.

**Comment by Godsfunambulator** [comment]
Thank you very much!  I still consider myself a novice and was searching all over for these pages but didn't know how to find them...even with internet searches and AI searches.  I didn't know enough to know these would be under the .Net section, but understand enough to vaguely understand why they are there. Thank you very much for adding the direct links! Huge improvement to this document!
