### ISSUE TITLE
Quality: 

### ISSUE THREAD

**Issue by enma-01** [MicrosoftDocs/PowerShell-Docs#10387]
### Prerequisites

- [X] **Existing Issue:**

Search the existing [quality issues][b1] for this repository. If there's an issue that
covers the quality area and articles you want to improve, pick a different quality area
or article set. Don't file a new issue for the same work. Subscribe, react, or comment
on that issue instead.

[b1]: https://github.com/orgs/MicrosoftDocs/projects/15/views/3?filterQuery=repo%3A%22MicrosoftDocs%2FPowerShell-Docs%22+is%3Aissue

- [X] **Descriptive Title:**

Write the title for this issue as a short synopsis. If possible, provide context. For
example, "Quality: Command Syntax in Foo" instead of "Quality: Foo"

### Quality Areas

Formatting code samples, Formatting command syntax, Link References, Markdown linting

### Article List

Existing Issue: Search the existing [quality issues](https://github.com/orgs/MicrosoftDocs/projects/15/views/3?filterQuery=repo%3A%22MicrosoftDocs%2FPowerShell-Docs%22+is%3Aissue) for this repository. If there's an issue that covers the quality area and articles you want to improve, pick a different quality area or article set. Don't file a new issue for the same work. Subscribe, react, or comment on that issue instead. *
 Descriptive Title: Write the title for this issue as a short synopsis. If possible, provide context. For example, "Quality: Command Syntax in Foo" instead of "Quality: Foo"

**Comment by michaeltlombardi** [comment]
It looks like this got opened without any of the details being filled out. Please feel free to open another issue or reopen this one and add the missing context.
