### ISSUE TITLE
Parameter "TargetName" does not exist.

### ISSUE THREAD

**Issue by DJChupa13** [MicrosoftDocs/PowerShell-Docs#10391]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7.3

### Summary

The documentation clearly mentions "TargetName" several times, but in my usage, that parameter is called "ComputerName."  Perhaps it was renamed and the docs haven't caught up?

### Details

Running `Get-Help Test-Connection` in PowerShell 5.1.19041.3031 does not return the parameter "TargetName" in any syntax block.

### Suggested Fix

Update documentation to reflect that the parameter is now called "ComputerName" and note any differences between them.

**Comment by michaeltlombardi** [comment]
@DJChupa13 - you linked to the 7.3 version of the documentation.

In the [Windows PowerShell documentation for that parameter][01], there is a note that states:

> The **ComputerName** parameter is renamed to **TargetName** in PowerShell 6.0 and above.

PowerShell maintains version-specific documentation. In the ["Selecting the version of PowerShell" section of the _How to use the PowerShell documentation_ article][02], there's some guidance on how to change the version of the documentation you're reviewing:

> Use the version selector located above the TOC to select the version of PowerShell you want. By default, the page loads with the most current stable release version selected. The version selector controls which version of the cmdlet reference appears in the TOC under the **Reference** node. Some cmdlets work differently in different versions of PowerShell you are using. Be sure you are viewing the documentation for the correct version of PowerShell.

[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.management/test-connection?view=powershell-5.1&preserveView=true#-computername
[02]: https://learn.microsoft.com/powershell/scripting/how-to-use-docs#selecting-the-version-of-powershell
