### ISSUE TITLE
Install instructions should mention the name of the executable

### ISSUE THREAD

**Issue by moritz-t-w** [MicrosoftDocs/PowerShell-Docs#10394]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.3#arch-linux

### Summary

It should be mentioned in the install instructions that once you're finished installing, you can use the `pwsh` command to start powershell.

**Comment by sdwheeler** [comment]
The URL you cited includes an anchor for Arch Linux, but that article doesn't mention Arch Linux. Did you mean https://learn.microsoft.com/en-us/powershell/scripting/install/community-support?view=powershell-7.3#arch-linux?

**Comment by moritz-t-w** [comment]
Oh I didn’t come across the page you linked, and the name of the executable is written there.
