### ISSUE TITLE
Mention ExternalException for Set-Clipboard

### ISSUE THREAD

**Issue by tylermontneyacc** [MicrosoftDocs/PowerShell-Docs#10406]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-clipboard?view=powershell-7.3#notes

### Summary

As this cmdlet is likely wrapping [Clipboard.SetDataObject](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard.setdataobject?view=windowsdesktop-7.0), the user may run into the [clipboard being in-use](https://stackoverflow.com/questions/930219/how-to-handle-a-blocked-clipboard-and-other-oddities). 

### Details

Applies to all versions.

### Suggested Fix

The notes section should include this scenario and instruct the user to retry after a short period.

**Comment by sdwheeler** [comment]
The clipboard code is not using the .NET **Clipboard** class. On Windows it is using the Win32 [SetClipboardData](https://learn.microsoft.com//windows/win32/api/winuser/nf-winuser-setclipboarddata) API.

On non-Windows, it's using native command line tools (`xclip` on Linux, `pbcopy` on macOS).

On all platforms, failures are silently ignored.

**Comment by tylermontneyacc** [comment]
> The clipboard code is not using the .NET **System.Windows.Forms.Clipboard** class. On Windows it is using the Win32 [SetClipboardData](https://learn.microsoft.com//windows/win32/api/winuser/nf-winuser-setclipboarddata) API.

Appreciate the clarification.

> On all platforms, failures are silently ignored.

What does this mean? The user will see no output a failure occurred?

**Comment by sdwheeler** [comment]
> What does this mean? The user will see no output a failure occurred?

Correct, if the API call or the native command fails to set the clipboard, no error is returned.

**Comment by tylermontneyacc** [comment]
If the clipboard is in-use, an error is returned:

```powershell
Set-Clipboard : Requested Clipboard operation did not succeed.
At line:2 char:1
+ Set-Clipboard "abc"
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-Clipboard], ExternalException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.ExternalException,Microsoft.PowerShell.Commands.SetClipbo
   ardCommand
```

**Comment by sdwheeler** [comment]
Yeah, that is a 5.1 behavior that won't be changed. In PowerShell 7+ there are no exceptions defined.

**Comment by tylermontneyacc** [comment]
Right, hence the request to mention the behavior for 5.1's notes. Is this request still denied?

**Comment by sdwheeler** [comment]
> Perhaps a separate issue, not informing the user of failure seems undesirable. (I have corrected my initial post to reflect.)

If you can reproduce a failure scenario in PowerShell 7, you should [file an issue][1] with the PowerShell team.

What are the steps to reproduce the problem in Windows PowerShell 5.1?

[1]: https://aka.ms/psfeedback

**Comment by tylermontneyacc** [comment]
Run this (crude) block in a few 5.1 tabs (Terminal) and you will eventually see failures:

```powershell
for($i=0;$i -lt 999;$i++){
Set-Clipboard "abc"
Start-Sleep -Milliseconds 100
}
```

Since Windows is using the Win32 call for 7, it will fail the same. However, since there are no exceptions you won't know.

**Comment by sdwheeler** [comment]
After much internal digging, I see that Windows PowerShell 5.1 is using the System.Windows.Forms.Clipboard class. 

PowerShell 7 is using the Win32 API directly, which likely won't have the issue because they open and close the clipboard. See [Clipboard.cs#L180-L186](https://github.com/PowerShell/PowerShell/blob/5dd8d53cb225b1aaddf4a33d41abe078d2bc2d4d/src/Microsoft.PowerShell.Commands.Management/commands/management/Clipboard.cs#L180-L186).

I am still considering whether to add a note for 5.1.
