### ISSUE TITLE
Show-NetFirewallRule help contains probably outdated references to Server 2012 in all versions I see

### ISSUE THREAD

**Issue by jsilverm** [MicrosoftDocs/PowerShell-Docs#10402]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/netsecurity/show-netfirewallrule?view=windowsserver2022-ps&redirectedfrom=MSDN#parameters
https://learn.microsoft.com/en-us/powershell/module/netsecurity/show-netfirewallrule?view=windowsserver2019-ps&redirectedfrom=MSDN#parameters
https://learn.microsoft.com/en-us/powershell/module/netsecurity/show-netfirewallrule?view=windowsserver2016-ps&redirectedfrom=MSDN#parameters

### Summary

Having installed PowerShell 7.3 on Windows I updated the help using update-help and checked the help for show-NetFirewallRule.  I saw various references to Windows Server 2012 under the description to -PolicyStore parameter so as usual I checked the online help to see if for some reason local was out of date.
The three links I show in the links section also contain the same references to Windows Server 2012 -- this seems unlikely to be accurate for Server 2016/2019/2022 or Windows 10 or 11.

### Details

I am somewhat uncertain, but I'd imagine that the text should just refer to the version of Windows that the cmdlet is executing against, whatever that may be?

### Suggested Fix

Probably the change to being less specific in wording would be best, possibly there is a general standard for describing "version of Windows OS command is running on" thru-out the docs, if so, it would be good to stay consistent.

**Comment by sdwheeler** [comment]
That cmdlet and documentation is not maintained by the PowerShell team. It is owned by a team in the Windows organization. Please report your issue at https://github.com/MicrosoftDocs/windows-powershell-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20learn.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20a52ef452-126c-ca4b-a534-e135da614476%0A*%20Version%20Independent%20ID%3A%20317e554b-0edf-bc4d-21d9-a518799b0bcf%0A*%20Content%3A%20%5BShow-NetFirewallRule%20(NetSecurity)%5D(https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Fnetsecurity%2Fshow-netfirewallrule%3Fview%3Dwindowsserver2022-ps%26redirectedfrom%3DMSDN%23parameters)%0A*%20Content%20Source%3A%20%5Bdocset%2Fwinserver2022-ps%2Fnetsecurity%2FShow-NetFirewallRule.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-powershell-docs%2Fblob%2Fmain%2Fdocset%2Fwinserver2022-ps%2Fnetsecurity%2FShow-NetFirewallRule.md)%0A*%20Product%3A%20**w10**%0A*%20GitHub%20Login%3A%20%40JasonGerend%0A*%20Microsoft%20Alias%3A%20**jgerend**
