### ISSUE TITLE
-AsPlainText is not a valid option for ConvertFrom-SecureString

### ISSUE THREAD

**Issue by Piscean** [MicrosoftDocs/PowerShell-Docs#10411]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertfrom-securestring

### Summary

The documentation mentions using -AsPlainText to convert back to plain text.  That is not a valid flag.  It generates an error when trying to run your sample code.

### Details

This is the sample code you provide.  It doesn't work...

$secureString = ConvertTo-SecureString -String 'Example' -AsPlainText
$secureString # 'System.Security.SecureString'
ConvertFrom-SecureString -SecureString $secureString -AsPlainText # 'Example'

### Suggested Fix

Update the sample and the doc to something which actually works.

**Comment by michaeltlombardi** [comment]
@Piscean - I suspect you're using Windows PowerShell (v5.1). In that version `ConvertFrom-SecureString` doesn't have the **AsPlainText** parameter, and the parameter isn't documented in the [versioned documentation][01].

However, the documentation in newer versions of PowerShell _does_ include the parameter and its documentation. In the documentation for `ConvertTo-SecureString` for 7.3 (the latest stable release and the default version shown in the docs), the [**AsPlainText** parameter documentation][02] states:

> When set, `ConvertFrom-SecureString` will convert secure strings to the decrypted plaintext string as output.
> 
> This parameter was added in PowerShell 7.0.

[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.security/convertfrom-securestring?view=powershell-5.1&preserveView=true
[02]: https://learn.microsoft.com/powershell/module/microsoft.powershell.security/convertfrom-securestring?view=powershell-7.3&preserveView=true#parameters
