### ISSUE TITLE
Error handling in Compare-Object when calling CompareTo()

### ISSUE THREAD

**Issue by eddie-zalar** [MicrosoftDocs/PowerShell-Docs#10410]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/compare-object?view=powershell-7.3#example-6-comparing-complex-objects-that-implement-icomparable
- https://learn.microsoft.com/en-us/dotnet/api/system.icomparable.compareto?view=net-6.0#exceptions
- 

### Summary

I would like to know how errors are handled when calling Compare-Object and the ReferenceObject implements the IComparable interface.

### Details

As per the description, the CompareTo() method of the ReferenceObject is called by Compare-Object if it implements the IComparable interface. see first link.
But the description of the CompareTo() method states that it may throw exceptions - see second link. But it is not described how Compare-Object handles possible exceptions if the CompareTo() method really throws an ArgumentException.

### Suggested Fix

Please describe what happens if a call to CompareTo() method throws an exception, which basically indicates a difference of the objects.

**Comment by sdwheeler** [comment]
`Compare-Object` does not handle any exceptions. So any exception that occurs in `CompareTo` would be surfaced. See the source code for `Compare-Object` at https://github.com/PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs
