### ISSUE TITLE
Community support for Linux install page has an omission in the Raspberry Pi OS example script

### ISSUE THREAD

**Issue by patheikkinen** [MicrosoftDocs/PowerShell-Docs#10447]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/community-support?view=powershell-7.4

### Summary

The Community support page for Linux page under install contains a ready-made sample script for downloading and compiling PowerShell. The script uses jq but unfortunately it doesn't ensure that it exists in the system.
Caveat: I tried this in Ubuntu, which is a different Debian-based distro... so there's a slight chance that there could be a difference in what gets installed by default between these two distros.

### Suggested Fix

# Install dependencies
sudo apt-get install jq libssl1.1 libunwind8 -y

**Comment by sdwheeler** [comment]
@JamesDBartlett3 Would you like to update this?
