### ISSUE TITLE
`Test-Connection` requires `sudo` on Linux for custom buffer size

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#10458]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

Due to a change in .NET 8 to make it work like the `ping` utility, any non-default buffer requires `sudo`.

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/20369

### Related Source Issues

- https://github.com/PowerShell/PowerShell/issues/17018

**Comment by sdwheeler** [comment]
NOTES: On Linux, if you use the `-BufferSize` parameter, you must have run PowerShell elevated (`sudo pwsh`) or the user must have the `cap_net_raw` capability.

**Comment by SteveL-MSFT** [comment]
I think what should be documented is that any combination of parameters like `-BufferSize` or uses the `MtuSizeDetectParameterSet` parameter set that results in a non-default buffer size of 32 bytes may require `sudo` on Linux.  An exception will have the appropriate message if this is required.
