### ISSUE TITLE
Dead link in "See the winget documentation for ... install instructions" where link is a URL to https://github.com/windows/package-manager/winget

### ISSUE THREAD

**Issue by DGerischTC** [MicrosoftDocs/PowerShell-Docs#10453]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
https://github.com/windows/package-manager/winget

### Summary

Seventh paragraph down is "Install PowerShell using Winget (recommended)".  In that, it says "Note See the [winget documentation](https://github.com/windows/package-manager/winget) for a list of system requirements and install instructions".  Cool, I need to learn how to install winget.  Click on the link and get a 404 This is not the web page you were looking for.

**Comment by sdwheeler** [comment]
Docs at https://learn.microsoft.com/en-us/windows/package-manager/winget/

**Comment by sdwheeler** [comment]
The URL is correct on the published docs site. The links in the markdown source files are relative to the docs site, not to GitHub.
