### ISSUE TITLE
New-FileCatalog -CatalogVersion default value to 2

### ISSUE THREAD

**Issue by ThomasNieto** [MicrosoftDocs/PowerShell-Docs#10487]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

The related PR updates the default value from 1 to 2.

### Articles

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Security/New-FileCatalog.md

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/20428

### Related Source Issues

- https://github.com/PowerShell/PowerShell/issues/19131

**Comment by iSazonov** [comment]
Notice, it is approved breaking change.

**Comment by sdwheeler** [comment]
Fixed in PR #10806
