### ISSUE TITLE
Cant find "Unregister-ScheduledJob" within docs and info on ScheduledJob isn't the best in this version

### ISSUE THREAD

**Issue by Recursivex5137** [MicrosoftDocs/PowerShell-Docs#10482]
### Type of issue

Missing information

### Feedback

In the Documentation Scheduled Jobs docs isn't that great.  Especially when its an alternative to windows task scheduler to run scripts based on this article [https://devblogs.microsoft.com/scripting/use-powershell-to-create-job-that-runs-at-startup/]( https://devblogs.microsoft.com/scripting/use-powershell-to-create-job-that-runs-at-startup/).

I couldn't find the command "Unregister-ScheduledJob" within docs or search. Had to rely on chatgpt to figure this one out. 

After a bit of googling I found this [https://learn.microsoft.com/en-us/powershell/module/psscheduledjob/about/about_scheduled_jobs?view=powershell-5.1](https://learn.microsoft.com/en-us/powershell/module/psscheduledjob/about/about_scheduled_jobs?view=powershell-5.1)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_job_details?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Job_Details.md

### Author

sdwheeler

### Document Id

ce27f4c9-d7b3-a042-0b26-ad71c8a70c4a

**Comment by sdwheeler** [comment]
The referenc for that cmdlet is at https://learn.microsoft.com/en-us/powershell/module/psscheduledjob/unregister-scheduledjob?view=powershell-5.1

The PSScheduledJob module is only available in Windows PowerShell 5.1. It is not compatible with PowerShell 7 or higher. See https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-5.1#modules-no-longer-shipped-with-powershell
