### ISSUE TITLE
If we shouldn't have plural parameter names where possible why is Privileges a recommended parameter name

### ISSUE THREAD

**Issue by JimMoyle** [MicrosoftDocs/PowerShell-Docs#10508]
### Type of issue

Other (describe below)

### Feedback

The relevant PowerShell guidance is here:

https://learn.microsoft.com/en-gb/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-7.3#use-singular-parameter-names

Thaanks

Jim

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/security-parameters?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/developer/cmdlet/security-parameters.md

### Author

sdwheeler

### Document Id

171eba67-ff99-9865-3f37-2d9f626b8dbb

**Comment by sdwheeler** [comment]
Confirmed with PS team. `-Privileges` is outdated guidance.
