### ISSUE TITLE
Enumerating Property Names produce different results , would be good to point out difference

### ISSUE THREAD

**Issue by andyjballgit** [MicrosoftDocs/PowerShell-Docs#10505]
### Type of issue

Missing information

### Feedback

for the Enumerating Property names, the 2 different methods produce different results
Get-Member - will retrieve the fieldnames in alphabetical order 
.psobject  - will retrieve the fieldnames in the ordered they are stored in the object 

this can be important if using this to compose an object , say output to markdown , where you want to preserve the original order of the fields

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-pscustomobject?view=powershell-7.3#enumerating-property-names

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md

### Author

sdwheeler

### Document Id

8e72ce06-198a-ec18-2e87-332697391fee

**Comment by sdwheeler** [comment]
This is documented in `Get-Member`.

**Comment by andyjballgit** [comment]
> This is documented in `Get-Member`.

true enough , but the specific section i am referring to in your doc , suggests the 2 commands do the same thing , which they do sort of , just think a one liner in that section would help
