### ISSUE TITLE
Enhancement: "Which version of PowerShell (Latest or LTS)?" user prompt in Raspberry Pi OS install script

### ISSUE THREAD

**Issue by JamesDBartlett3** [MicrosoftDocs/PowerShell-Docs#10501]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.2, 7.3

### Summary

As a user of [the Raspberry Pi OS install script](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/community-support.md#raspberry-pi-os), I'd like to have the option to choose either the latest stable release or the LTS release when I install PowerShell. 

### Details

@sdwheeler, I have a pretty solid idea of how I'd implement this, so if you assign this issue to me, I'll submit a PR.

### Proposed Content Type

Other / Unknown

**Comment by JamesDBartlett3** [comment]
Thanks for the feedback, @michaeltlombardi!

Yeah, I can definitely put something together for the Community Blog. 👍

Is there any chance you can add the `hacktoberfest` topic to that repo, so contributors can rack up points? 😉

Cheers!

**Comment by michaeltlombardi** [comment]
@JamesDBartlett3 Done!
