### ISSUE TITLE
Horizontal tab - Can default spacing of 8 spaces be overriden?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/PowerShell-Docs#10533]
### Type of issue

Missing information

### Feedback

The information about horizontal tab says "By default, the PowerShell console has a tab stop at every eighth space.".

* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters#horizontal-tab-t

Can it be changed, overridden? If so; how?

I like the default spacing in PowerShell ISE better, seems it's 4 spaces vs. default PowerShell terminal 8.

<img width="679" alt="image" src="https://github.com/MicrosoftDocs/PowerShell-Docs/assets/6450056/b98b364c-45d1-4494-955e-0176d7e91990">

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7.3#horizontal-tab-t

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md

### Author

sdwheeler

### Document Id

470749e3-10d3-1267-aeb7-0c4f25379ce5

**Comment by sdwheeler** [comment]
Tab expansion is a function of the terminal host application. PowerShell just passes the tab character (ASCII 9) to the host for output. The host application expands it. 

Some old hardware terminals (e.g. VT100) and old terminal emulation programs had configuration settings to set the width of the tab or assign tab stops. There is no standard way to change this across terminal host.

Windows Terminal seems to support the same ANSI escape sequences that xterm supports. You can use these escape sequences to change the terminal behavior.

- "`e[3g" - Clears all tab stops
- "`eH" - Sets a tab stop at the current cursor position
- "`ec" - Triggers a full reset of the terminal to its original state

The following command sets 20 tab stops 4-spaces apart.

```powershell
write-host ("    `eH"*20)
```

**Comment by o-l-a-v** [comment]
Thank you for the explanation @sdwheeler. :)
