### ISSUE TITLE
PowerShell examples in C#

### ISSUE THREAD

**Issue by JustinWebDev** [MicrosoftDocs/PowerShell-Docs#10548]
### Type of issue

Other (describe below)

### Feedback

This page is about how to code in PowerShell, but the examples are in C#.  We need PS examples.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-declare-parameter-sets?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/developer/cmdlet/how-to-declare-parameter-sets.md

### Author

sdwheeler

### Document Id

fd265825-af74-898d-8db7-d8136dd4274f

**Comment by sdwheeler** [comment]
@JustinWebDev That documentation is for the PowerShell SDK. It is about using the PowerShell API from C#.
