### ISSUE TITLE
can not import any module

### ISSUE THREAD

**Issue by QingHeSite** [MicrosoftDocs/PowerShell-Docs#10545]
### Type of issue

Code doesn't work

### Feedback

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/96610717/de69b613-39a9-4cd9-8502-46d06aaa8683)
![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/96610717/27ef7f0c-5bd6-4f32-a539-02d71a9dd413)
How should I solve it

### Page URL

https://learn.microsoft.com/zh-cn/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by QingHeSite** [comment]
Import-Module Microsoft.PowerShell.Security

Import-Module: The following error occurred while loading the extended type data file:
, C:\program files\powershell\7\Modules\Microsoft.PowerShell.Security\Security.types.ps1xml: The file was skipped because of the following validation exception: File C:\program files\powershell\7\Modules\Microsoft.PowerShell.Security\Security.types.ps1xml cannot be loaded because its operation is blocked by software restriction policies, such as those created by using Group Policy..

**Comment by sdwheeler** [comment]
The error message seems to provide the answer "operation is blocked by software restriction policies".

However, this repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
