### ISSUE TITLE
Incomplete syntax block in about_Command_Syntax

### ISSUE THREAD

**Issue by tabad** [MicrosoftDocs/PowerShell-Docs#10569]
### Type of issue

Typo

### Feedback

Within the *SYNTAX DIAGRAMS* section, the following is indicated:

> PowerShell uses the following notation for syntax diagrams.
>
> `<command-name> -<Required Parameter Name> <Required Parameter Value Type>`
> `[-<Optional Parameter Name> <Optional Parameter Value Type>]`
> `[-<Optional Switch Parameters>]`
> `[-<Optional Parameter Name>] <Required Parameter Value Type>`

This syntax block should be as following:

> `<command-name> -<Required Parameter Name> <Required Parameter Value Type>`
> `[-<Optional Parameter Name> <Optional Parameter Value Type>]`
> `[-<Optional Switch Parameters>]`
> `[-<Required Parameter Name>] <Required Parameter Value Type>`

because the last line of the block is regarding a _mandatory positional parameter_.

In any case, the original syntax diagram is incomplete because it omits _optional positional parameter_ case. I thing the complete syntax diagram should be this one:

> `<command-name> -<Required Parameter Name> <Required Parameter Value Type>`
> `[-<Required Parameter Name>] <Required Parameter Value Type>`
> `[-<Optional Parameter Name> <Optional Parameter Value Type>]`
> `[[-<Optional Parameter Name>] <Optional Parameter Value Type>]`
> `[-<Optional Switch Parameters>]`

or, because there are parameter sets with *mandatory switch parameters* (see `Get-Help` for example), this another one:

> `<command-name> -<Required Parameter Name> <Required Parameter Value Type>`
> `[-<Required Parameter Name>] <Required Parameter Value Type>`
> `[-<Optional Parameter Name> <Optional Parameter Value Type>]`
> `[[-<Optional Parameter Name>] <Optional Parameter Value Type>]`
> `-<Required Switch Parameters>`
> `[-<Optional Switch Parameters>]`

Best regards,

P.D. The same bug appears in PowerShell 7.2, 7.3 and 7.4 reference.
 

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_syntax?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Syntax.md

### Author

sdwheeler

### Document Id

6e583127-51a7-1adc-ba98-c2ea1e0057bf

**Comment by sdwheeler** [comment]
> because the last line of the block is regarding a _mandatory positional parameter_.

For positional parameters the parameter name is not required. The value may be required if the parameter is mandatory. So the syntax description is accurate.

**Comment by tabad** [comment]
Hello @sdwheeler,

Thanks for your comment. I would like to clarify that I am a PowerShell beginner, so I apologise in advance for the possible lack of overview of PowerShell which may cause me to make some interpretation errors. Having said that, I return to the issue at hand.

You say

> For positional parameters the parameter name is not required. The value may be required if the parameter is mandatory. So the syntax description is accurate.

and I think I understand that. Also I think I understand in general all modifiers that exist when a *cmdlet* is launched but the *syntax* shown here is some confused, at least for me.

If I am not mistaken, a *cmdlet* can be followed by a *required* (or *mandatory*) parameter or an *optional* parameter and these parameters, in turn, can be *positional* or *non-positional* (or *named*), so there are four posibilities.

* *a)* A *mandatory positional* parameter
* *b)* A *mandatory non-positional (named)* parameter
* *c)* An *optional positional* parameter and
* *d)* An *optional non-positional (named)* parameter

Syntactically it could be noted as follows:

* *a)* `[-<parameter name>] <parameter value>`
* *b)* `-<parameter name> <parameter value>`
* *c)* `[[-<parameter name>] <parameter value>]`
* *d)* `[-<parameter name> <parameter value>]`

There is also another one possibility (really others two whether we take into account its optionality) and there is the use of parameters without associated values, that is, the use of *switches*. That is why the previous *syntax* could be extended like following:

* *e)* `[-<parameter name>]` or `[-<switch name>]`
* *f)* `-<parameter name>` or `-<switch name>`

That is why I propose to change the syntax block

```
<command-name> -<Required Parameter Name> <Required Parameter Value Type>`
> `[-<Optional Parameter Name> <Optional Parameter Value Type>]`
> `[-<Optional Switch Parameters>]`
> `[-<Optional Parameter Name>] <Required Parameter Value Type>
```

for

```
<command-name> [-<parameter name>] <parameter value>
               -<parameter name> <parameter value>
               [[-<parameter name>] <parameter value>]
               [-<parameter name> <parameter value>]
               [-<switch name>]
               -<switch name>
```

or something like that. 

Thanks for your time Sean. Best regards,

**Comment by tabad** [comment]
Hello @sdwheeler,

Thank you for your time and patience.
I hope you will hit the right key. As you said, it is not easy.

Best regards,
