### ISSUE TITLE
Specify relation between PowerShell and PowerShell Core and this repository

### ISSUE THREAD

**Issue by eyeinsky** [MicrosoftDocs/PowerShell-Docs#10599]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core

### Summary

Specify relation between PowerShell and PowerShell Core

### Details

The readme for [PowerShell](https://github.com/PowerShell/PowerShell) has a section [Windows PowerShell vs. PowerShell Core](https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core), which seems to imply that the repository itself is PowerShell Core and not PowerShell (which only works on Windows). Whether it is or not, it would help to specify the name better.

### Suggested Fix

Add text that this repository is for PowerShell Core, i.e the cross-platform version of PowerShell.

**Comment by sdwheeler** [comment]
The documentation in this repository covers both Windows PowerShell and PowerShell (core).

This is covered in the documentation in several places. Most notably in https://learn.microsoft.com/powershell/scripting/community/contributing/product-terminology.

See also https://learn.microsoft.com/powershell/scripting/how-to-use-docs
