### ISSUE TITLE
Cannot create $PROFILE as per documentation, PS 7.3.8, Windows 11

### ISSUE THREAD

**Issue by PurpleGranite** [MicrosoftDocs/PowerShell-Docs#10590]
### Type of issue

Code doesn't work

### Feedback

The documentation on the page indicates that:
``` PowerShell
if (!(Test-Path -Path $PROFILE)) {
  New-Item -ItemType File -Path $PROFILE -Force
}
```
Will create a new $PROFILE, and from reading it appears to indicate that this will create any required directories as well as the resulting file.

With PowerShell 7.3.8 on Windows 11 returns `Could not find a part of the path 'C:\Users\MyUser\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'`

Is this a PowerShell 7 bug? Perhaps the documentation needs amended or clarified?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md

### Author

sdwheeler

### Document Id

b175960c-519f-f591-0124-b93f36e8a927

**Comment by sdwheeler** [comment]
We are not able to reproduce the problem. We tested this on Windows PowerShell 5.1 and PowerShell 7.

**Comment by PurpleGranite** [comment]
![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/8159386/f91e71de-bd7e-43a5-ad8c-a147fa4ec58f)

I _am_ able to reproduce on two separate Windows 11 devices with PowerShell 7.3.8 and 7.3.9.

**Comment by sdwheeler** [comment]
You are not using `-Force`. You have to use `-Force` to create the missing folders.

**Comment by PurpleGranite** [comment]
Bad screenshot - same result with and without `-Force` - can repro and grab a fresh capture, but I suspect the reply will be "It's not a documentation issue, closing anyway" - despite being able to trivially replicate on multiple devices.

**Comment by sdwheeler** [comment]
The documentation is correct. There must be something wrong with your environment.

This is not the place for support. I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
