### ISSUE TITLE
virtual environment

### ISSUE THREAD

**Issue by MOH7117** [MicrosoftDocs/PowerShell-Docs#10625]
### Type of issue

Typo

### Feedback

When I activate the virtual environment, I get this problem. I don't know why
![لقطة شاشة 2023-11-12 205310](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/122209156/06f70302-c0c7-47ef-aabc-777f29b08733)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

### Author

sdwheeler

### Document Id

9a273f6f-7dba-1614-cc84-f44f877c1351

**Comment by sdwheeler** [comment]
Your execution policy does not allow running scripts. That policy may be controlled by group policy in your environment. The documentation you were looking at explains what to do.

This repository is for PowerShell core documentation. If you need support, I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by MOH7117** [comment]
how can i solve this problem

**Comment by sdwheeler** [comment]
Have you looked at [Set-ExecutionPolicy](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-5.1)
