### ISSUE TITLE
Properties access in taskbar shortcut

### ISSUE THREAD

**Issue by HarryTheFairy** [MicrosoftDocs/PowerShell-Docs#10624]
### Type of issue

Other (describe below)

### Feedback

"Right-click on the PowerShell shortcut that's now pinned to the taskbar and select properties as shown in Figure 1-9."

In my case should be **Shift + Right-click** 

Not shure if this matter but here is my windows version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19045  0
```
### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/ps101/01-getting-started.md

### Author

sdwheeler

### Document Id

c2a54962-1511-7f87-24c5-f39b61f923bb

**Comment by mikefrobbins** [comment]
@HarryTheFairy, You are correct, <kbd>Shift</kbd> + <kbd>Right-click</kbd>. I made this change to the actual book last month while updating that chapter to Windows 11, and we'll be pushing the updates to our documentation once they're complete. Thank you!
