### ISSUE TITLE
Code with errors in Example 6 of Add-Member

### ISSUE THREAD

**Issue by tabad** [MicrosoftDocs/PowerShell-Docs#10634]
### Type of issue

Code doesn't work

### Feedback

Code of Example 6 of `Add-Member` cmdlet in PowerShell 5.1, 7.2 (LTS), 7.3 and 7.4 (preview) is following

````powershell
 1 $obj = [pscustomobject]@{
 2       Name = 'Doris'
 3       Age = '20'
 4 }
 5 $obj | Add-Member -MemberType AliasProperty -Name 'intAge' -Value age -SecondValue uint32
 6 $obj | Get-Member
 7 $obj
 8 
 9 TypeName: System.Management.Automation.PSCustomObject
10 
11 Name        MemberType    Definition
12 ----        ----------    ----------
13 intAge      AliasProperty intAge = (System.UInt32)age
14 Equals      Method        bool Equals(System.Object obj)
15 GetHashCode Method        int GetHashCode()
16 GetType     Method        type GetType()
17 ToString    Method        string ToString()
18 Age         NoteProperty  string Age=20
19 Name        NoteProperty  string Name=Doris
20 
21 Name   : Doris
22 Age    : 20
23 intAge : 20
24 
25 $obj.Age + 1
26 $obj.intAge + 1
27 
28 201
29 21
````

This code is not sequential, that is, it does not shows the output of cmdlets in its logical order. For example, lines from 8 to 20 should appear after line 6, line 28 should appears after line 25 or line 29 should appears after line 26. On the other hand, lines 21 to 24 do not correspond to the output of `$obj` (line 7) but of `$obj | Format-List`.

Personally I think the code should be as follows.

````powershell
$obj = [pscustomobject]@{
      Name = 'Doris'
      Age = '20'
}
$obj | Add-Member -MemberType AliasProperty -Name 'intAge' -Value age -SecondValue uint32
$obj | Get-Member

TypeName: System.Management.Automation.PSCustomObject

Name        MemberType    Definition
----        ----------    ----------
intAge      AliasProperty intAge = (System.UInt32)age
Equals      Method        bool Equals(System.Object obj)
GetHashCode Method        int GetHashCode()
GetType     Method        type GetType()
ToString    Method        string ToString()
Age         NoteProperty  string Age=20
Name        NoteProperty  string Name=Doris

$obj | Format-List

Name   : Doris
Age    : 20
intAge : 20

$obj.Age + 1
201
$obj.intAge + 1
21
````

in PowerShell 5.1, 7.2 (LTS), 7.3 and 7.4 (preview).

Best regards,

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-member?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md

### Author

sdwheeler

### Document Id

6441c722-b93a-1746-e38a-29a6722fc0a3

**Comment by sdwheeler** [comment]
@tabad Part of the issue is your docs build system makes multiline/multi-command examples hard to present. This causes confusion. We are working on fixed the build system.

For now, we will refactor the example to be clearer.
