### ISSUE TITLE
Naming Help Files is missing module-named files

### ISSUE THREAD

**Issue by juneb** [MicrosoftDocs/PowerShell-Docs#1064]
Naming Help Files (https://msdn.microsoft.com/en-us/library/dn423135(v=vs.85).aspx) hasn't been updated since 2012, so it's missing the new help file name format:

<Module>-help.xml

Please update. Thanks!

**Comment by zjalexander** [comment]
@eslesar i think this is the content you're working on updating, right?

**Comment by eslesar** [comment]
Yes, this is in the developer docs, which can be updated after migration is complete.

**Comment by eslesar** [comment]
@juneb This is not a naming convention known about by the PowerShell team. I have not gotten a response from the teams that are using it. I will re-visit this issue if and when I do.

**Comment by eslesar** [comment]
Re-opening. My previous comment applies to #1067

**Comment by DCtheGeek** [comment]
This was completed at some point.  The current doc is correct: https://docs.microsoft.com/en-us/powershell/developer/module/naming-help-files
