### ISSUE TITLE
I have a question about the calculation in Power Shell

### ISSUE THREAD

**Issue by skanda890** [MicrosoftDocs/PowerShell-Docs#10662]
### My Question

If I entered this " 3+3+333+33+3+3+3+3+3+3+3+3+3+3+3+3+3
>> +33+3+3+3+3+33+3+3+3+3+3+3+3+3+3+3+3+3+3+3+3+3+3+33+3+3+3+3+33+33+3+3" or some other value with ' >>' then why does this answer come "411, 246" only for that equation. My question was why are there two answers? Some things may not be how I want it to be, please try to understand what I mean by this.

**Comment by michaeltlombardi** [comment]
@skanda890 This repository is for documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

If you're looking to understand how math works in PowerShell, you might find the [`about_Arithmetic_Operators`][2] about topic helpful.

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
[2]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_arithmetic_operators

**Comment by skanda890** [comment]
Oh, okay.
