### ISSUE TITLE
_Execution_Policies at https :/go.microsoft.com/fwlink/?LinkID=135170.

### ISSUE THREAD

**Issue by 89253151858** [MicrosoftDocs/PowerShell-Docs#10676]
### Type of issue

Code doesn't work

### Feedback

_Execution_Policies at https
:/go.microsoft.com/fwlink/?LinkID=135170.

### Page URL

https://learn.microsoft.com/ru-ru/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

### Author

@sdwheeler

### Document Id

9a273f6f-7dba-1614-cc84-f44f877c1351

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. If you need support, you can post your questions in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
