### ISSUE TITLE
Last Sentence of First Paragraph under "Long Description" has error

### ISSUE THREAD

**Issue by twitchd8** [MicrosoftDocs/PowerShell-Docs#10673]
### Type of issue

Typo

### Feedback

The last Sentence in the First Paragraph under "Long Description" is the following. However, I'm not completely sure what it's supposed to say exactly.

>"You can also pass a script block to a A script block can accept arguments and return values."

I hope that helps.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_script_blocks?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Script_Blocks.md

### Author

@sdwheeler

### Document Id

ac92bfaf-20ed-5275-f2a2-55b6664e1937

**Comment by sdwheeler** [comment]
Thanks for spotting that. I fixed it.
