### ISSUE TITLE
pas de commande PuwerShelle 

### ISSUE THREAD

**Issue by FTUAHINE** [MicrosoftDocs/PowerShell-Docs#10672]
### Type of issue

Missing information

### Feedback

pas de commande PuwerShelle sur le clic droit de ma souris dans une fenêtre 

### Page URL

https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.archive/?view=powershell-7.3

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md

### Author

sdwheeler

### Document Id

d13adda7-b95a-fd26-3e0a-b2abc3410791

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
