### ISSUE TITLE
Instructions for PSNativeCommandErrorActionPreference Are Incorrect

### ISSUE THREAD

**Issue by RichardMeadowsTC** [MicrosoftDocs/PowerShell-Docs#10680]
### Type of issue

Code doesn't work

### Feedback

PSNativeCommandUseErrorActionPreference cannot be enabled simply by using the Enable-ExperimentalFeature function.

Need to set the variable.
$PSNativeCommandUseErrorActionPreference= $true
And will most need to disable it for native commands that are expected to return non-zero exit code.  Like robocopy.
& {
 $PSNativeCommandUseErrorActionPreference= $false
 robocopy .........
}

And you will likely want to set $ErrorActionPreference = 'Stop'  so that a proper error will be raised when the native app reports a failure.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.4#psnativecommanderroractionpreference

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/experimental-features.md

### Author

sdwheeler

### Document Id

976ee643-597a-6c5e-bee4-bb0b72fe3c5f

**Comment by sdwheeler** [comment]
In Powershell 7.4, the _PSNativeCommandErrorActionPreference_ experimental feature is now mainstream. There is no experiemental feature by that name anymore. The proper variable name is `$PSNativeCommandUseErrorActionPreference`, not `$PSNativeCommandErrorActionPreference`. The `$PSNativeCommandUseErrorActionPreference` variable defaults to `$false`.

**Comment by RichardMeadowsTC** [comment]
As documented, it does not work.  Try this

 PS > Enable-ExperimentalFeature -Name PSNativeCommandUseErrorActionPreference
Enable-ExperimentalFeature: No experimental feature was found that matched the name 'PSNativeCommandUseErrorActionPreference'.

Now to do it properly you need to set 
$PSNativeCommandUseErrorActionPreference = $true

Sorry about the typeo;  $PSNativeCommandErrorActionPreference

**Comment by sdwheeler** [comment]
That's because it is now a mainstream feature, as documented by the note for the 7.4 release. 

When an experimental feature becomes mainstream, there is nothing to enable. The feature is enabled. You just need to set the preference variable. The rest of the information about the feature is accurate. The information is left here for historic reference. We plan to remove it with the 7.4.1 release.

The information about using the preference variable has been updated in https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.4#psnativecommanduseerroractionpreference

**Comment by RichardMeadowsTC** [comment]
@sdwheller .  Thank you for link to new preference variable. That is very helpful.  When I was going through release notes for 7.4.0, I was lead to incorrect documentation that never would have worked.

https://devblogs.microsoft.com/powershell/powershell-7-4-general-availability/
-> https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-74?view=powershell-7.4
  -> https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.4#psnativecommanderroractionpreference
