### ISSUE TITLE
help Get-Content does not have -First parameter (alias of TotalCount) documented

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/PowerShell-Docs#10692]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.2&WT.mc_id=ps-gethelp

### Summary

It appears that the Get-Content command parameter `-First`, an alias of `-TotalCount`, does not appear when the `help` command is used.

### Details

```
PS C:\> help Get-Content -Parameter First
Get-Help:
Line |
  64 |      $help = Get-Help @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No parameter matches criteria First.
PS C:\> help Get-Content -Parameter TotalCount

-TotalCount <System.Int64>
    Specifies the number of lines from the beginning of a file or other item. The default is -1 (all lines).

    You can use the TotalCount parameter name or its aliases, First or Head .

    Required?                    false
    Position?                    named
    Default value                -1
    Accept pipeline input?       True (ByPropertyName)
    Accept wildcard characters?  false




PS C:\> $psversionTable.PSVersion.ToString()
7.3.8
```

**Comment by sdwheeler** [comment]
You get that error from `Get-Help` because **First** is not a parameter, it is an alias. And `Get-Help` doesn't show alias metadata, which is why we have to put it in the description text.

You can see the aliases using the following command:

```
PS> (Get-Command Get-Content).Parameters.TotalCount.Aliases
First
Head
```
But there is no easy way to search for that using `Get-Help`.
