### ISSUE TITLE
Bad descriptions on how to change an execution policy for one session

### ISSUE THREAD

**Issue by GTGeek88** [MicrosoftDocs/PowerShell-Docs#10727]
### Type of issue

Code doesn't work

### Feedback

At this link: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4
you have a topic called Set a Policy for One Session and the claim that executing the command PWSH.EXE followed by some parameters will change the execution policy for that session. All it tells me is that PWSH.EXE does not exist, no matter where I run it from and I started PowerShell with admin rights. I tried from the Command Window, too. It seems you are making lots of assumptions or maybe just providing bad info, but I could not get this command to work at all.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

### Author

@sdwheeler

### Document Id

9a273f6f-7dba-1614-cc84-f44f877c1351

**Comment by GTGeek88** [comment]
FYI to whom it may concern: I was using the reporting feature on the page where I encountered bad information, so it would seem that a report would be allowed. And it seems to have been, but I got an email that says "Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: davidanson/markdownlint-cli2-action@v9, streetsidesoftware/cspell-action@v2, lycheeverse/lychee-action@master, peter-evans/create-issue-from-file@main, step-security/harden-runner@main, kentaro-m/auto-assign-action@master." Not sure why GitHub has a problem with something I did that seemed entirely within the process offered by Microsoft that allows users to submit deficiencies in their documentation.

**Comment by sdwheeler** [comment]
You were looking at the version of the documentation for PowerShell 7.4. The executable for all versions of PowerShell 6 and greater is `pwsh.exe`. The exectuable for Windows PowerShell 5.1 is `powershell.exe`. You are not viewing the correct version of the documentation. You can choose the version of PowerShell documentation from the version picker above the Table of Contents.

[How to use the PowerShell documentation][1], has tips on navigating the documentation.

[1]: https://docs.microsoft.com/powershell/scripting/how-to-use-docs.
