### ISSUE TITLE
Ampersand

### ISSUE THREAD

**Issue by laluha** [MicrosoftDocs/PowerShell-Docs#10732]
### Type of issue

Other (describe below)

### Feedback

How do i find information on the use of the ampersand character on a command line.
I am missing (or can't find) some syntax overview page where the use of special characters are listed. 
Now I need to google for it.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/powershell-commands?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/powershell-commands.md

### Author

@sdwheeler

### Document Id

ca403082-6de4-5675-35e3-88065af5cd42

**Comment by sdwheeler** [comment]
It is not a command it is an operator. See https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.4#call-operator-
