### ISSUE TITLE
windows powershell login ubuntu system as root

### ISSUE THREAD

**Issue by chandlerQJN** [MicrosoftDocs/PowerShell-Docs#10734]
### Type of issue

Other (describe below)

### Feedback

When windows powershell uses the root user and remotely connects to ubuntu through ssh, an error message is displayed: Permission denied, please try again. 

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell.md

### Author

@sdwheeler

### Document Id

8877b05f-1f52-8c75-2d7d-5100cc52c4cb

**Comment by sdwheeler** [comment]
This repository is for PowerShell documentation. You seem to be looking for support, which we can't provide here. I suggest you try posting your issue with context in one of the available [community support forums][1].

If, after troubleshooting your issue, you find an error or omission in the documentation, please open a new issue explaining how the documentation could be improved.

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
