### ISSUE TITLE
/reference/ needs to flow into Get-Help 

### ISSUE THREAD

**Issue by zjalexander** [MicrosoftDocs/PowerShell-Docs#1073]
Right now, changes to the /reference/ content only show up in online help on MSDN. 
Ideally, we should be able to have these changes flow through the updateable help engine so typos and corrections can flow back downlevel to Get-Help reference. 

**Current Status**

- [X]   Changes are built in PlatyPS to create the MAML

- [X] The MAML is packaged into CABs

- [X] The CABs are placed into Azure Blob Storage

** Needs work **

- [ ] Change URLs to point towards the generated CABs on Azure Blob Storage
  * Get-Help calls into a redirected URL that points to the proper location
  * Today, this goes towards the Microsoft Download Center, which are generated through the old process.

**Comment by BernieWhite** [comment]
Even better if Get-Help could pull and read markdown instead. Just a hope.

**Comment by zjalexander** [comment]
While that would be ideal, it wouldn't be feasible to backport changes of that magnitude towards downlevel versions of PowerShell (e.g 3,4,5). Feel free to file an issue on powershell/powershell to see if this would be a good change for version 6 :)

**Comment by joeyaiello** [comment]
@BernieWhite that's my dream too. Then we could light up in-console syntax highlighting for examples. :)

**Comment by zjalexander** [comment]
This is currently hooked up for PowerShell 6 only. 

We are working to bring the contents of this repo to update-help downlevel. This is a service-side change so no action will be needed from users.

**Comment by sdwheeler** [comment]
Linking related issues

- [ ] - #1025 
- [ ] - #1797 
- [ ] - #2027 
- [ ] - #2939 
- [ ] - #2998 
- [ ] - #3031 
- [ ] - #3161 
- [ ] - #3268 
- [ ] - #4218

**Comment by sdwheeler** [comment]
We are now building updateable help for all versions.
