### ISSUE TITLE
Microsoft package source does not contain Powershell packages anymore

### ISSUE THREAD

**Issue by gajanak** [MicrosoftDocs/PowerShell-Docs#10741]
### Type of issue

Outdated article

### Feedback

/ubuntu/23.10/prod/pool/main/p/  in PWC does not contain powershell package anymore.

for older ubuntu version this was.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-ubuntu.md

### Author

@sdwheeler

### Document Id

2405ca72-f9d4-24a5-12a9-304d18a656ce

**Comment by sdwheeler** [comment]
Ubuntu 23.10 is not an LTS release. We don't support it.
