### ISSUE TITLE
About Scalar

### ISSUE THREAD

**Issue by iRon7** [MicrosoftDocs/PowerShell-Docs#10748]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.4

### Summary

The term `Scalar` is used in several PowerShell documents as e.g.:

* [about_comparison_operators](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_comparison_operators)
* [about_booleans](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_booleans#converting-from-scalar-types)
* [about_intrinsic_members](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_intrinsic_members?view=powershell-7.4#array-indexing-scalar-types)

Yet the meaning is quiet ambiguous even within PowerShell, see the [extensive answer from @mklement0](https://stackoverflow.com/a/77687355/1701026) to my StackOverflow question: "What is a `Scalar` in PowerShell".

I think a document about PowerShell's Scalar definition (as e.g. apposed to any other object that is auto-enumerated in a pipeline) based on mklement0's answer might help others to better understand and frame the implication and scope of the `Scalar` term in the related documents and issues (as in #10337 and #2130).

### Proposed Content Type

About Topic

### Proposed Title

About Scalar

**Comment by sdwheeler** [comment]
In common computer science terms: "a scalar data type, or just scalar, is any non-composite value". 

https://wikipedia.org/wiki/Scalar_processor#Scalar_data_type

PowerShell extends that definition to include any non-enumerable value. The information from mklement0 already exists in our documentation.
