### ISSUE TITLE
missing details about errors

### ISSUE THREAD

**Issue by razvanpaul-mielcioiu** [MicrosoftDocs/PowerShell-Docs#10749]
### Type of issue

Missing information

### Feedback

if I run `Get-Service -Name $tool` and the service doesn't exist it will throw an error. There is nothing specified in the documentation about how should I handle that case.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Management/Get-Service.md

### Author

@sdwheeler

### Document Id

da38e71d-c9ac-c21d-8cc2-d90f4a51040f

**Comment by sdwheeler** [comment]
Error handling is documented in the following articles:
- https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_commonparameters#-erroraction
- https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables#erroractionpreference
- https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_try_catch_finally

See also this lengthy discussion: 
- https://github.com/MicrosoftDocs/PowerShell-Docs/issues/1583

**Comment by razvanpaul-mielcioiu** [comment]
Specifically for `Get-Service` often enough people will want to know if a service exists or not, and if the service doesn't exist, it will need to make a separate search in the documentation. Maybe it's easier to add the relevant info in this particular page? Or at least link to the articles above?
