### ISSUE TITLE
Elevating whilst remaining in powershell 7 console

### ISSUE THREAD

**Issue by CrackedGlass83** [MicrosoftDocs/PowerShell-Docs#10756]
### Type of issue

Missing information

### Feedback

I am attempting to elevate powershell 7 (the latest) and I am unable to launch the latest powershell 7 console as an elevated administrator, I have attempted using run, "Start-Process wt powershell -Verb runAs", and mainly my problem is that I cannot see the correct powershell version in my start menu in order to elevate the process before launching it (eg right click exe on start menu and start as administrator) if there is an obvious way to elevate powershell that I have overseen, well good on me then.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4&viewFallbackFrom=powershell-7&WT.mc_id=THOMASMAURER-blog-thmaure

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

@sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by sdwheeler** [comment]
`Start-Process wt powershell -Verb runAs` is running Windows PowerShell 5.1, not PowerShell 7. The executable for PowerShell 7 is `pwsh.exe`.

Also, that command is running Windows Terminal (which then starts PowerShell). You could just run:

`Start-Process pwsh -Verb runAs`. That works on my machine.

**Comment by CrackedGlass83** [comment]
> `Start-Process wt powershell -Verb runAs` is running Windows PowerShell 5.1, not PowerShell 7. The executable for PowerShell 7 is `pwsh.exe`.
> 
> Also, that command is running Windows Terminal (which then starts PowerShell). You could just run:
> 
> `Start-Process pwsh -Verb runAs`. That works on my machine.

Why thank you very much, I'll this a go and it seems this should work 👍
