### ISSUE TITLE
Provide example of EncodedArguments parameter

### ISSUE THREAD

**Issue by tmontney** [MicrosoftDocs/PowerShell-Docs#10751]
### Type of issue

Missing information

### Feedback

This documentation is the only reference I can find to this parameter (not even `powershell.exe -help`), and the functionality of passing parameters using `EncodedCommand`. When trying various iterations, powershell always returns:

> Cannot process the command because the value specified with -EncodedArguments is not properly encoded. The value must be Base64 encoded.

I have tried:

- `[Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes("Hello"))`
- `[Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes('["Hello"]'))`
- `[Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes('{"Message":"Hello"}'))`

The encoded script works fine and has the following parameters:

```PowerShell
[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [String]
    $Message
)
```

If this functionality is implemented, please update the documentation with an example of what PowerShell expects.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md

### Author

@sdwheeler

### Document Id

2a47dda6-5d42-249c-5d48-19ad6fbc7b3c

**Comment by tmontney** [comment]
Here's the solution, which should be added into the docs:

```PowerShell
$args = [System.Collections.ArrayList]::new()
$args.Add("Hello")
$cliXml = [System.Management.Automation.PSSerializer]::Serialize($args)
[Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($cliXml))
```

[test_CommandLineParser.cs#L1013](https://github.com/PowerShell/PowerShell/blob/master/test/xUnit/csharp/test_CommandLineParser.cs#L1013) led me to [PsUtils.cs#L435](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/PsUtils.cs#L435) which led me to [PSSerializer](https://stackoverflow.com/a/70537354/1340075).

**Comment by sdwheeler** [comment]
I investigated the use of `-EncodeArguments` and talked to the dev team. That parameter was never intended to be used by end-users. It is only used internally. I am removing it from the documentation.
