### ISSUE TITLE
Basics - seriously

### ISSUE THREAD

**Issue by deraeler** [MicrosoftDocs/PowerShell-Docs#10765]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-7.4&viewFallbackFrom=powershell-6

### Summary

TRYING to learn powershell. Taking YOUR courses.
I'm behind a corporate firewall, so update-help is useless to me.
So I use get-help set-vm -online.
Not only does it not find anything, but I'm sent to a PowerShell REFERRENCE.   A PowerShell v7.4 REFERENCE!!!!  And yet, if I type in Set-VM in the search, it doesn't find anything. 
Well, actually, it found something like 10000 results all over microsoft or something.
But yet, the simplest attempt to search WITHIN THE REFERENCE I'M SUPPOSEDLY ALREADY IN - IT FINDS NOTHING.
So, once again Microsoft - a GIANT FAIL.
The simplest things become a nightmare with you always.  ALWAYS.
Why can't you provide a simple help engine that ACTUALLY WORKS?
Why is it always necessary for me to come to a forum like this to ask the dumbest conceivable questions for the simplest operations?  If I ask for HELP why can't you actually provide HELP?  All you seem to do is obfuscate, deceive and waste people's time.  WHY??????????????????????????

### Details

you figure it out.

### Suggested Fix

provide a HELP engine that actually provides HELP.

**Comment by sdwheeler** [comment]
`Set-VM` is not part of PowerShell. It comes from the Hyper-V module. You can find the help at https://learn.microsoft.com/powershell/module/hyper-v/set-vm.

You can use the Module Browser to search for modules and cmdlets.
https://learn.microsoft.com/powershell/module/?term=set-vm
