### ISSUE TITLE
The documentation doesn't say anything about users

### ISSUE THREAD

**Issue by davitof** [MicrosoftDocs/PowerShell-Docs#10770]
### Type of issue

Missing information

### Feedback

In case of using this cmdlet on a machine with several users, the documentation does not say if the cmdlet will clear only the contents of the connected user or of all the users.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/clear-recyclebin?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Management/Clear-RecycleBin.md

### Author

@sdwheeler

### Document Id

bb2f2454-4c6c-4785-c167-0b0878954be1

**Comment by sdwheeler** [comment]
Like all commands, they run in the context of the user that invoked them. Windows doesn't allow you to emply the recycle bin of another user.

**Comment by davitof** [comment]
I understand, and this is what I expected. But the documentation states that:

> The Clear-RecycleBin cmdlet deletes the content of a computer's recycle bin. This action is like using Windows Empty Recycle Bin.

The first sentence says "a computer's recycle bin" instead of "the current user's recycle bin". Only when thinking of the implications of the second sentence did I realize that maybe the first sentence was misleading.

**Comment by davitof** [comment]
BTW, your reaction delay was quite impressive!

**Comment by sdwheeler** [comment]
Ah, I see your point now. The problem is "computer" vs. "user" in this context.
