### ISSUE TITLE
Table for Alpine Support should be updated

### ISSUE THREAD

**Issue by J0F3** [MicrosoftDocs/PowerShell-Docs#10774]
### Type of issue

Outdated article

### Feedback

The table for Alpine Linux Support is 1. outdated (Alpine 3.19 is missing) and 2. misleading. 

What should the statement of the first column be? For Alpine 3.18 in the first column there is a green checkmark but then for all PowerShell version it basically says it is not supported. So, does that now mean it is not supported or is it supported?

Furthermore, I think, it would also be interesting to know why exactly it is not supported. As far I know Alpine 3.18, for example, is supported by .NET. So why is it then not supported by PowerShell?

So It think the table should be updated and extended with a bit more context information. 

Thanks!

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-alpine.md

### Author

@sdwheeler

### Document Id

da6c7c79-75ee-f19a-09b5-59dc21139242

**Comment by sdwheeler** [comment]
Waiting on the PowerShell dev team to provide the list of supported versions.

**Comment by sdwheeler** [comment]
When updating the docs, see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10958#issue-2191737766 for inclusion.

**Comment by sdwheeler** [comment]
Refactored OS lifecycle docs
- Updated end-of-life dates
- Removed tables

Docs only include OS versions that we have tested.
