### ISSUE TITLE
The installation instructions do not work anymore on Alpine 3.19

### ISSUE THREAD

**Issue by J0F3** [MicrosoftDocs/PowerShell-Docs#10775]
### Type of issue

Code doesn't work

### Feedback

The installation instructions do not work anymore on the latest Alpine (3.19) version. The package `libssl1.1` is not available anymore but instead `libssl3` mus be installed. 

In additional I think the dependencies should also be more aligned with the dependencies documented by .NET itself as documented here:
https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies

1. The .NET documentation says that for 3.15.x and newer the `libssl3` should be installed. So should say the PowerShell documentation probably also. 
2. Starting with Alpine 3.19 the version of the `lttng-ust` package is now the same for the "stable" 3.19 and edge branch. So I think the packe should not be installed form edge anymore. 
3. Is the list of required packages still correct? Why it is so much more packages that the .NET documentation says? For example is `less` really a requirement for PowerShell? If the list is still correct I think it would also be useful for what the PowerShell needs the additional packages (compared to the .NET dependencies). 

Thanks!

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-alpine.md

### Author

@sdwheeler

### Document Id

da6c7c79-75ee-f19a-09b5-59dc21139242

**Comment by sdwheeler** [comment]
Alpine 3.19 is not supported by us yet.

**Comment by J0F3** [comment]
@sdwheeler 

Ok, fair enough. But for other Apline versions I think the third point is still relevant:

> Is the list of required packages still correct? Why it is so much more packages that the .NET documentation says? For example is less really a requirement for PowerShell? If the list is still correct I think it would also be useful for what the PowerShell needs the additional packages (compared to the .NET dependencies).

The dependencies for a self-contained .NET app (see: https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies) and these for PowerShell are still very different. (regardless of the Alpine version). Are the dependencies for PowerShell and a self-contained .NET app really that different?
