### ISSUE TITLE
nodemon

### ISSUE THREAD

**Issue by nbprajapati** [MicrosoftDocs/PowerShell-Docs#10781]
### Type of issue

Typo

### Feedback

nodemon is not working in powershell

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

### Author

@sdwheeler

### Document Id

9a273f6f-7dba-1614-cc84-f44f877c1351

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
