### ISSUE TITLE
Scopes vs Session States (+ runspaces)

### ISSUE THREAD

**Issue by ohads-MSFT** [MicrosoftDocs/PowerShell-Docs#10797]
### Type of issue

Missing information

### Feedback

The scope docs mention session state but don't explain what it is (or even reference docs to that effect):
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.4

A quick search turned up the following docs (which are titled as to be specific for **Windows** PowerShell):
https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/windows-powershell-session-state?view=powershell-7.4
However, they refer to the session state as a configuration/data/information holder, which doesn't explain how session state can be "linked" to the global scope (to use the language of the above scope docs).  Also, they refer to PowerShell **runspaces** which aren't documented at all as far as I can tell (I could only find this archived blog post: https://devblogs.microsoft.com/scripting/beginning-use-of-powershell-runspaces-part-1/).

Finally, the Import-Module docs (specifically for the `Scope` parameter) are possibly the most confusing of all:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.4
These docs repeatedly mix scopes and session states as if they were interchangeable (which would contradict the other docs). For example:

> By default, when Import-Module cmdlet is called from the command prompt, script file, or scriptblock, all the commands are **imported into the global session state**. You can use the -Scope Local parameter to **import module content into the script or scriptblock scope**.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md

### Author

@sdwheeler

### Document Id

42772fd1-35e3-2672-05b1-3e5cd9c31ecf

**Comment by sdwheeler** [comment]
@ohads-MSFT I think you are trying to make this more complicated than it is. However, I understand some of the confusion. You are not the first to ask for clarification. We need to be more precise with some of the descriptions.

One of the points of confusion is around the definition of a _session_. In the beginning (when most of the documentation was created), the lifetime of a session was the same as the lifetime of the PowerShell host process (powershell.exe). And the process had one Runspace.

Runspaces are an instance of the PowerShell engine that executes code.
- Have a session state (metadata about the state)
- Contain a hierarchy of scopes
  - Scopes contain variables, aliases, functions, etc.
  - Scopes don't contain code - the code is linked to a scope in the hierarchy
  - Modules create parallel scope containers linked to the scope in which they were imported
    - Variables, aliases, functions, etc. exported by the module are available starting at the scope-level in which they are imported
    - Variables, aliases, functions, etc. not exported are only available within the module scope container
    - Functions in the module scope can access items in the scope in which they were imported 
    - Modules have their own session state
- When code running in a runspace references a scoped item, it searches the scope hierarchy it has access to looking for a name match. If it doesn't exist, a new item is created in the current scope. If it finds a match, the item is copied to the current scope.

Things get more complicated because a PowerShell host (pwsh.exe or powershell.exe) can have multiple runspaces. Each runspace has its own session state and scope containers. Session state and scopes can't be accessed across runspace instances.

This `-Scope` parameter of `Import-Module` controls which scope in the hierarchy that the imported module is linked to. By default modules are linked to the global scope of the runspace. Using `-Scope Local` links the module to the caller's current scope.

**Comment by mklement0** [comment]
Let me offer something I've written up for my own notes, which may be helpful to some:

* It aims to provide a top-down ontology of PowerShell's entities.
* It uses both official terminology and introduces a few custom terms that either have no official name yet or as alternatives to the existing names.
* It points out notable pitfalls.

-----

#### PowerShell Ontology

* A _runspace_ is a managed (i.e, .NET) thread that runs PowerShell cmdlets and source code via an instance of the PowerShell engine, the [`System.Management.Automation.PowerShell`](https://learn.microsoft.com/en-US/dotnet/api/System.Management.Automation.PowerShell) .NET class.

 * A given process can host multiple runspaces simultaneously.

 * Any .NET application can host runspaces, via the [_PowerShell SDK_](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/windows-powershell-host-quickstart), available via NuGet packages.

 * A stand-alone PowerShell installation comes with a terminal-based host application that provides an interactive shell as well as support for command line-based execution of PowerShell code; it is known as the _PowerShell CLI_ ([`powershell.exe`](https://learn/.[microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe](http://microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe)) for Windows PowerShell, [`pwsh`](https://learn/.[microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh](http://microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh)) for PowerShell (Core) 7+) 

 * By default, an interactive shell session has only _one_ runspace, but creation of (often transitory) additional ones is possible, most idiomatically and simply via `ForEach-Object -Parallel`  and `Start-ThreadJob` in PowerShell 7+, but also via direct use of the SDK (which is the only built-in option in Windows PowerShell). Additionally, _out-of-process_ runspaces may be communicated with, using background jobs and PowerShell [remoting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Remote), involving XML-based cross-process serialization (CLIXML).

 * Note:
   * The term _session_ is somewhat ambiguous, as it can refer to a PowerShell CLI process as a whole vs. a single runspace:
   * In the stricter sense, _session_ is synonymous with _runspace_; only the latter term is used below.

 * Inside each runspace, code runs inside _scopes_:

   * Each scope is a container for variables, functions, aliases, PowerShell drives, and, on an opt-in basis, imported modules. Note that invoking a _binary_ cmdlet never creates a new scope (but can choose to modify the caller's scope).

    * Note that certain aspects of a runspace are invariably _process-global_, namely environment variables and types loaded from _on-disk_ .NET assemblies as well as those compiled ad hoc with `Add-Type -TypeDefinition`
      * However, PowerShell `class` and `enum` definitions, which are housed in _in-memory_ assemblies, while _technically_ available process-wide, are effectively _hidden_ from non-descendent scopes and other runspaces (this can be worked around, but is only safe to do for `class`es that are decorated with the v7.4+ `[NoRunspaceAffinity()]` attribute)

   * By contrast, the _working directory_, generalized to the concept of a _current location_ in PowerShell (using PowerShell's [provider](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Providers) model that also supports drives that aren't _file-system_ drives), is a _per-runspace_ concept. This amounts to a common pitfall when calling _non-PowerShell in-process APIs_, notably .NET and COM APIs: the latter operate on the _process-level_ working directory, which usually differs from PowerShells; such APIs should therefore always be called with _full paths_.
   
   * The initial scope in which all code execution inside a runspace starts is the one and only _global scope_ (whose elements can be referred to via the `$global:` scope specifier or a `-Scope Global` argument in select cmdlets).
   Its elements are seen runspace-wide, but can be shadowed by elements of the same name in nested scopes.

   * Scopes are organized into _scope domains_ (scope stacks), officially known under the ambiguous name _session states"_ - for a discussion of this term, see #4288

    * There are two types of scope domains:

      * The one and only _global (default, non-module) scope domain_ in which all _non-module_ code runs. 

      * _Module scope domains_, one of which exists for _each loaded module_ (including _dynamic_ modules) and inside of which each module's commands run.

    * The _effective_ root of all scope domains is the single _global scope_: it is the _actual_ root of the _global_ scope domain, whereas it is merely _visible_ (linked) to the _module_ scope domains, which each have their own root scope (using the SDK directly, it is possible to _not_ link modules to the global scope, but that doesn't happen in normal use). 

       * This distinction (actual root vs. linked-to) usually doesn't matter, but does if you try to access the global scope with a _numbered_ `-Scope` argument, which won't work in modules (e.g., `Get-Variable -Scope 1 HOME` from a module's root scope _fails_; `-Scope Global` works as usual, however).
 
       * The upshot is:
           *  The only scope that both non-module and module code share access to is the global one, they otherwise do _not_ see each other's scopes. This has far-reaching consequences, discussed below.
           * Modules can use their root scope to store private state, and making elements visible to outside callers requires _exporting_ them.

    * _Stacks_ (hierarchies) of scopes inside a given scope domain come from invocation of commands implemented in PowerShell code getting run in a _child_ scope by default, possibly recursively; together, these nested child scopes can be called _descendent scopes_ and, conversely, a given scope may have nested _parent_ scopes, which together can be called _ancestral scopes_.

    * Most scopes are _transient_, i.e. they exist only for the duration of a given call; the exceptions are the _global_ scope - which exists for an entire session - and the root scopes of loaded modules - which exists for the remainder of the session, unless modules are explicitly unloaded (with `Remove-Module`).

    * Descendent scopes by default can _use_ (call or read) elements from their ancestral scopes, but _modifying_ or _adding_ elements to ancestral scopes requires _explicit_ cross-scope access, such as via scope specifiers (e.g. `$global:foo`) or the `-Scope` parameter of cmdlets such as `Set-Variable`, `Set-Alias`, `New-PSDrive`, or `Import-Module`.

      * A notable pitfall is that _assigning to_ a variable defined in an ancestral scope without an explicit scope specifier implicitly creates a _local_ variable of the same name, which then _shadows_ its ancestral counterpart(s).

      * Another perhaps surprising aspect is that functions always run in a (child) scope _of their scope-domain of origin_, which may or may not be the same as the caller's; the ramifications are spelled out below.

    * _Inside a given scope domain_, (non-)creation of child scopes works as follows:

      * Invocation of functions and scripts  - either by direct invocation or invocation via `&`, the call operator, creates a _child_ scope of the caller's scope.

      * By contrast, invocation via `.`, the dot-sourcing operator, runs them _directly in the caller's scope_, allowing modifying / adding to its elements - implicitly, this invocation mechanism is used by PowerShell's [profiles](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Profiles) for defining elements directly in the global scope, as well as inside modules to module-globally load helper scripts at import time.
    
    * The logic is _different_ in _cross-scope-domain_ calls to _functions_ (by contrast, a _script file_ getting invoked is always considered to be in the _caller_'s scope domain):

       * Direct innovation / via `&` creates a child scope in the invoked function's _scope domain of origin_. Notably, a non-module caller calling a module's function results in the latter always running in a child scope of _its origin module's root scope_.

       * Similarly, dot-sourcing (`. `) runs directly in the current scope of the function's _scope domain of origin_ (this invocation form rarely makes sense across scope domains).

       * A notable and highly unfortunate consequence is that functions _if they happen to be defined in modules_ typically do _not_ see the current scope of an _outside caller_ (unless they run directly in the _global_ scope, which is _not_ typical), and therefore also do not see the latter's [_preference variables_](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Preference_Variables) (whereas _binary_ cmdlets always do) - see https://github.com/PowerShell/PowerShell/issues/4568 for a discussion.

**Comment by flibustier7seas** [comment]
Hi @sdwheeler ,

You mentioned that: 

> One of the points of confusion is around the definition of a session. In the beginning (when most of the documentation was created), the lifetime of a session was the same as the lifetime of the PowerShell host process (powershell.exe). And the process had one Runspace.

The documentation also states that: 

> - **Global**: The scope that's in effect when PowerShell starts or when you
  create a new session or runspace.

This suggests that a session and a runspace are distinct entities, each with its own scope (and therefore its own session state).

Could you please clarify how a session differs from a runspace and how they are related now?

Thanks in advance!

**Comment by sdwheeler** [comment]
In this context, a "new session" is a new instance of the PowerShell process (`powershell.exe` or `pwsh.exe`) with its default (new) runspace.

As mklement0 described, it is possible to create additional runspaces within the current session (instance of PowerShell).
