### ISSUE TITLE
Which Version of UUID is implemented?

### ISSUE THREAD

**Issue by Gill-Bates** [MicrosoftDocs/PowerShell-Docs#10822]
### Type of issue

Missing information

### Feedback

There are 5 different standardised versions for calculating a UUID. Each additional version is designed to improve the avoidance of collisions in the namespace. It would therefore be useful to know which standard is used in the `New-Guid` cmdlet.

The documentation does not provide any information about this.

https://www.sohamkamani.com/uuid-versions-explained

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-guid?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Utility/New-Guid.md

### Author

@sdwheeler

### Document Id

5952e94c-4978-ac3c-a9cf-8a6418603192

**Comment by sdwheeler** [comment]
The cmdlet creates a Version 4 Universally Unique Identifier (UUID). For more information, see [System.Guid.NewGuid](https://learn.microsoft.com/dotnet/api/system.guid.newguid).
