### ISSUE TITLE
description of splatting is incomprehensible - again

### ISSUE THREAD

**Issue by deraeler** [MicrosoftDocs/PowerShell-Docs#10826]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-02?view=powershell-7.4

### Summary

this is incomprehensible. why do I find myself writing this about almost every page of your documentation.. What exactly is it you're trying to prove? That you can write documents that no one can understand but those blessed with some obscure genius or (more likely) bent that only you people understand?  This explanation of splatting is useless.  I've been writing code for 40 years and this makes absolutely no sense.  What's amazing is that you actually need people to tell you this. You'll probably flag this as inappropriate, further elevating your ivory tower above us paeons.

### Details

$values = 5,3 # put arguments into an array
Get-Power @values

$hash = @{ exponent = 3; base = 5 } # put arguments into a Hashtable
Get-Power @hash

function Get-Power2 { Get-Power @args } # arguments are in an array

Get-Power2 --exponent 3 --base 5 # named arguments splatted named in
@args
Get-Power2 5 3 # position arguments splatted positionally in @args
This is achieved by using @ instead of $ as the first character of the variable being passed. This notation can only be used in an argument to a command.

### Suggested Fix

write something we can understand.  If I had the slightest idea what you're talking about I would suggest an edit.  But I'm honestly that lost - I have no idea what idea you're trying to present.

**Comment by sdwheeler** [comment]
The documentation you were reading is the the Language Specification docs. The purpose of those docs is to describe the grammar of the language, not necessarily show how to use it.

The documentation for how to use splatting is in [about_Splatting](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_splatting).
