### ISSUE TITLE
Importing PSCustomObject changes its PSTypeName

### ISSUE THREAD

**Issue by mm6502** [MicrosoftDocs/PowerShell-Docs#10843]
### Type of issue

Missing information

### Feedback

I cannot find any mention, that using this cmdlet on previously serialized PSCustomObject will change its PSTypeName (itwill be prefixed with 'Deserialized.'.

Proof:
``` PowerShell
$original = [PSCustomObject] @{ PSTypeName = 'before' }
$original.PSObject.TypeNames
$original | Export-CliXml -Path 1.xml
$deserialized = Import-CliXml -Path 1.xml
$deserialized.PSObject.TypeNames
```

Output: 
``` Text
before
System.Management.Automation.PSCustomObject
System.Object
Deserialized.before
Deserialized.System.Management.Automation.PSCustomObject
Deserialized.System.Object
```

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-clixml?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Utility/Import-Clixml.md

### Author

@sdwheeler

### Document Id

0a2e8234-2bd0-2875-7728-78edca932a48

**Comment by sdwheeler** [comment]
The same thing happens in remoting. See https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_remote_variables#serialization-of-variable-values

`Export-CliXml` serialized the object into XML data. `Import-CliXml` deserializes the XML back into a PowerShell object. However, the deserialized object isn't a live object. It's a snapshot of the object at the time of serialization. The deserialized object includes properties but no methods. 

The **TypeNames** property contains the original type name prefixed with **Deserialized**.
