### ISSUE TITLE
Unify the case used for "dynamic param"

### ISSUE THREAD

**Issue by mubed** [MicrosoftDocs/PowerShell-Docs#10840]
### Type of issue

Typo

### Feedback

Two different cases were used for the keyword dynamicParam. Since Pwsh keywords are all in camel case, I think the correct case should be as I mentioned above.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

### Author

@sdwheeler

### Document Id

09f03e1d-5e99-8ca3-e665-6b50d988231b

**Comment by sdwheeler** [comment]
Actually, the agreed standard on the PowerShell team is that keywords are lowercase. Most everything else is Pascal case, not camel case.
