### ISSUE TITLE
`about_Environment_Variables` Incorrectly Asserts Environment Variable Limitations w.r.t. Empty Strings

### ISSUE THREAD

**Issue by brucificus** [MicrosoftDocs/PowerShell-Docs#10850]
### Type of issue

Other (describe below)

### Feedback

`about_Environment_Variables` states:

> Environment variables, unlike other types of variables in PowerShell, are always stored as a string and can't be empty.

and later:

> Because an environment variable can't be an empty string, setting one to $null or an empty string removes it. For example:

Although PowerShell and .NET do not currently support such an operation, environment variables _can_ be set to empty strings, and PowerShell can resolve and list such blank variables.

To verify my assertion, try this from a `cmd.exe` session:

```cmd
C:\Users\Bruce>setx A ""

SUCCESS: Specified value was saved.

C:\Users\Bruce>pwsh -NoLogo -NoProfile -Command "[System.Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::User).ContainsKey('A')"
True
```

It is important to distinguish between PowerShell's _actual_ limitations vs. the surrounding context because empty environment variables are more common outside of Windows and/or in sessions in nested processes with cross-platform tooling.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

### Author

@sdwheeler

### Document Id

dfc13aff-02f5-c1ea-d736-68a55241ab52

**Comment by sdwheeler** [comment]
See my comment in the PR - https://github.com/MicrosoftDocs/PowerShell-Docs/pull/10851#issuecomment-1925477399

**Comment by sdwheeler** [comment]
The `[System.Environment]::GetEnvironmentVariables()` method can see the environment variable `A`, but the PowerShell environment provider can't.

**Comment by sdwheeler** [comment]
The intent documentation is to document the behavior of PowerShell, not the .NET API. Also, the behavior gets a little more complicated when you compare Windows to non-Windows platforms. 

Windows, normally, doesn't allow you to create an environment variable with a null or empty value. You can't do it using the `set` command in `cmd.exe`, nor can you do it in the control panel applet that manages environment variables. Also, the `set` command can't see the null-valued environment variable. It's odd that `setx.exe` allows you to do it.

```cmd
C:\>set TEST
Environment variable TEST not defined

C:\>pwsh -noprofile
PowerShell 7.4.1
PS C:\> [System.Environment]::GetEnvironmentVariables([EnvironmentVariableTarget]::User).ContainsKey('TEST')
True
```

In bash on Linux or zsh on macOS, you can create and export environment variable with a null or empty value. 

In all platforms, the PowerShell environment provider is using the same underlying .NET API to get the list of environment variables. On Windows, that API does not list the null-valued variables. On non-Windows, the API includes the null-valued variables. Windows hides the null-valued variables.

With all that said, I think we can update the docs I will reopen and amend your PR with editorial changes.

**Comment by mklement0** [comment]
Just a few clarifications:

* `setx.exe` doesn't _actually_ work with empty values:
  * Even though it should report an error, it blindly creates an empty `REG_SZ` registry value, which the system _ignores_ when creating the environment block for a _process_ - and the _process_-level environment variables are what matter (in most cases).
  * As a probably accidental side effect of how .NET implements lookup of the _persisted_ environment-variable definitions in the registry, it _does_ surface such broken entries; if you omit the `[EnvironmentVariableTarget]::User` part or specify `[EnvironmentVariableTarget]::Process`, you'll see that variable is _not_ found, i.e. that the process doesn't see it.

* The upshot is that on Windows the _persistent_ definition of empty environment variables is effectively _not_ supported.

* However, the _in-process_ definition of empty environment variables is _de facto_ supported via the Windows API, but this capability - whose intentionality is unclear - is currently not surfaced via .NET APIs, not even on Unix-like platforms, where empty environment variables aren't uncommon, and easily creatable in-process from POSIX-compatible shells.
  
  * See https://github.com/dotnet/runtime/issues/50554, also for a discussion of why this is problematic, including especially for PowerShell.

A PowerShell example that demonstrates that creating empty-value env. vars. in-process is possible on Windows:

```powershell
Add-Type -Namespace Demo -Name WinApiHelper -MemberDefinition @'
  [DllImport("kernel32", CharSet = CharSet.Unicode)]
  public static extern bool SetEnvironmentVariable(string lpName, string lpValue);
'@

if ([Demo.WinApiHelper]::SetEnvironmentVariable('NOVALUE', '')) { 
  'Successfully created $env:NOVALUE with no value (empty string).'
} else {
  throw 'Failed to create $env:NOVALUE with no value (empty string).'
}

# Test the existence of the variable.
Get-Item Env:NOVALUE
```
