### ISSUE TITLE
Documentation of `*`-numbered pipe needs improvement

### ISSUE THREAD

**Issue by tag** [MicrosoftDocs/PowerShell-Docs#10878]
### Type of issue

Missing information

### Feedback

The table of numbered pipes (1=stdout, 2=stderr, etc.) ends with `*` for all pipes. Combined with other examples on the page, this suggests that `*> $null` should work. However, the order of operations associates the `*` with the left-side command rather than the `n>` redirect.

For example, `del foo *> $null` gets interpreted as (`del foo *`) (`> $null`), not (`del foo`) (`*> $null`)

Recommend including examples of using the `*` pipe "number", and mention the limitations of its use,

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7.4&viewFallbackFrom=powershell-7.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Redirection.md

### Author

@sdwheeler

### Document Id

06b97f3e-418c-743b-1ccd-1d14b2c9e035

**Comment by sdwheeler** [comment]
@tag You are mistaken about how PowerShell sees the `*>` token. As you can see from the trace, the parameter binder is only seeing one parameter `xx`, instead of two: `xx` and  `*`.

```powershell
PS> Trace-Command -PSHost -Name ParameterBinderController,ParameterBinding -Expression {del xx *> $null }
DEBUG: ParameterBinderController Information: 0 :  WriteLine   Argument count: 1
DEBUG: ParameterBinding Information: 0 : BIND NAMED cmd line args [Remove-Item]
DEBUG: ParameterBinding Information: 0 : BIND POSITIONAL cmd line args [Remove-Item]
DEBUG: ParameterBinding Information: 0 :     BIND arg [xx] to parameter [Path]
DEBUG: ParameterBinding Information: 0 :         Binding collection parameter Path: argument type [String], parameter
type [System.String[]], collection type Array, element type [System.String], no coerceElementType
DEBUG: ParameterBinding Information: 0 :         Creating array with element type [System.String] and 1 elements
DEBUG: ParameterBinding Information: 0 :         Argument type String is not IList, treating this as scalar
DEBUG: ParameterBinding Information: 0 :         Adding scalar element of type String to array position 0
DEBUG: ParameterBinding Information: 0 :         BIND arg [System.String[]] to param [Path] SUCCESSFUL
DEBUG: ParameterBinderController Information: 0 :  WriteLine   CurrentParameterSetName = Path
DEBUG: ParameterBinding Information: 0 : BIND cmd line args to DYNAMIC parameters.
DEBUG: ParameterBinderController Information: 0 :  WriteLine       The Cmdlet supports the dynamic parameter interface
DEBUG: ParameterBinderController Information: 0 :  WriteLine       Getting the bindable object from the Cmdlet
DEBUG: ParameterBinding Information: 0 :     DYNAMIC parameter object:
[Microsoft.PowerShell.Commands.FileSystemProviderRemoveItemDynamicParameters]
DEBUG: ParameterBinderController Information: 0 :  WriteLine       Creating a new parameter binder for the dynamic
parameter object
DEBUG: ParameterBinderController Information: 0 :  WriteLine   CurrentParameterSetName = Path
DEBUG: ParameterBinding Information: 0 : MANDATORY PARAMETER CHECK on cmdlet [Remove-Item]
DEBUG: ParameterBinding Information: 0 : CALLING BeginProcessing
DEBUG: ParameterBinding Information: 0 : CALLING EndProcessing
```

This is also proven by inspecting the AST of the parsed command:

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/19415881/81ae022c-85f4-47d6-aabb-201537b5adcd)
