### ISSUE TITLE
 Feedback 

### ISSUE THREAD

**Issue by gorkem9940** [MicrosoftDocs/PowerShell-Docs#10873]
### Type of issue

Typo

### Feedback

Looking for help?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md

### Author

@sdwheeler

### Document Id

88f432a7-504e-af9b-291b-59e76dc27649

**Comment by sdwheeler** [comment]
I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
