### ISSUE TITLE
Clarify the - limited - usefulness of `--%`, the stop-parsing token when used with PowerShell commands rather than native programs

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#10888]
### Type of issue

Missing information

### Feedback

Ultimately, use of `--%` only makes sense when calling _native (external) programs_.

* _Direct_ use of `--%` with native programs is by far the most common use case.

* The _only_ scenario in which using `--%` when calling _PowerShell commands_ makes sense is to _relay_ a raw argument list to a native program, using _splatting_.
  * In other words: only PowerShell commands that are _wrappers for external-programs_ can meaningfully support `--%`, where anything following `--%` is to be passed through to the external program _as if `--%` had been used in direct invocation_ of said program.

---

Currently:

* `about_Parsing` makes no mention of the potential use of `--%` for indirect, PowerShell command-mediated calls to external programs.

* `about_Special_Characters` currently uses a PowerShell command _incidentally_ in an effort to illustrate `--%`'s behavior, in a manner that is likely to cause confusion (see #10889).

---

Here's an example of a PowerShell function acting as a wrapper for a native program:

```powershell
function foo {
  $env:SOMEVAR = 1
  # Whatever follows --% in the invocation is captured in a *single* argument, $args[1]
  Write-Verbose -Verbose "`$arg[1]: «$($args[1])»"
  # Note: @args is needed for --% to be relayed properly
  cmd /c echo @args
  $env:SOMEVAR = $null 
}

# Invoke with --%
foo --% a( "x< %SOMEVAR%
```

Output:

```none
VERBOSE: $arg[1]: «a( "x< %SOMEVAR%»
 a( "x< 1
```

Note:

* From the `foo` function's perspective, whatever follows `--%` is passed as a _single, verbatim_ positional argument, in `$args[1]`, as the verbose output demonstrates.

* It is _splatting_ that enables relaying this verbatim content to the native program, relying on splatting recognizing the array element `--%` (`$args[0]`) as the stop-parsing token.
  * Caveat: If that element happens to be situationally `[psobject]`-wrapped, this logic does _not_ work - see https://github.com/PowerShell/PowerShell/issues/21260.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.5#the-stop-parsing-token

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Parsing.md

### Author

@sdwheeler

### Document Id

be402df0-6f04-9a29-5410-c54be1c11926

**Comment by sdwheeler** [comment]
@mklement0 I am making the change you suggested in #10889. 

Are you saying that we need to add the PowerShell-wrapped example to about_Parsing or just add a statement about limiting the use of `--%` to native commands?

**Comment by mklement0** [comment]
Thanks, @sdwheeler.

After making the change proposed in #10898, I feel there's less of a need to spell out a full example in about_Parsing. 

However, I suggest at least _mentioning_ that with PowerShell commands `--%` only makes sense for _wrapper_ commands for native programs, where `$args` (or a sub-array of it) is relayed to a native program _via splatting_ (e.g., `@args`). It is a useful - albeit probably rare in practice - scenario.
