### ISSUE TITLE
So how many objects do satisfy the conditions?!?

### ISSUE THREAD

**Issue by JendaPerl** [MicrosoftDocs/PowerShell-Docs#10884]
### Type of issue

Missing information

### Feedback

OK, so we filter a collection, we store the results in a variable for later processing and we, apart from other things, want to print the number of items found.

Write-Host "Dear user, we found $result.Length matching items"

NOPE! Because some braindead imbecile decided that if there is just one bloody result, then the variable ain't gonna contain an array of one element, but that one single bloody element itself, so if we are lucky, then the script will end with an error. If we are not, the bloody element has a property named Length too. 

Please do add the stupid @() around ALL calls in the docs and if you find that person, slap them over their face with a wet, well matured floor cloth!

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/where-object?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/Where-Object.md

### Author

@sdwheeler

### Document Id

1a25b81b-6f34-481a-ca4c-3371ac01a493

**Comment by sdwheeler** [comment]
What problem are you having. It works as documented.

```powershell
PS> $array = @{key=5}, @{key=1}
PS> $array

Name                           Value
----                           -----
key                            5
key                            1

PS> $array | Where-Object key -eq 5

Name                           Value
----                           -----
key                            5

PS> $result = $array | Where-Object key -eq 5
PS> "Found $($result.Count) items."
Found 1 items.
PS> "Found $($result.Length) items."
Found 1 items.
```

**Comment by JendaPerl** [comment]
Except that we did not find 1 item. We found an item with one key!!!

```
$dict1 = @{
    'Key1' = 5
    'Key2' = 15
    'Key3' = 30
}

$dict2 = @{
    'Key1' = 8
    'Key2' = 14
    'Key3' = 29
}

$array = @($dict1, $dict2)
Write-Host "We have $($array.Count) items in the array, the first one has $($array[0].Count) keys"

$result = $array | Where-Object Key1 -eq 5
Write-Host "We DON'T have $($result.Count) items!"
```

You are the "principal content developer" and you yourself have no idea what your language actually does, because what your language does is absolutely ridiculous!

**Comment by JendaPerl** [comment]
```
$dict1 = @{
    'Key1' = 5
    'Key2' = 15
    'Count' = 'Outrageous'
}

$dict2 = @{
    'Key1' = 8
    'Key2' = 14
    'Count' = 'Incredible'
}

$array = @($dict1, $dict2)
Write-Host "We have $($array.Count) items in the array"

$result = $array | Where-Object Key1 -eq 5
Write-Host "And now have $($result.Count)"

```

```
$array = @("Hello", "world!")
Write-Host "We have $($array.Length) items in the array"

$result = $array | Where-Object Length -eq 6
Write-Host $result
Write-Host "And now have $($result.Length)"

```

The problem is not in types of collections! The type of the elements of the original array is absolutely irrelevant, just like whether hashtables are enumerated or not!

The whole problem is that if there are two or more matching items, you end up with an array and the .Length or .Count is a property of that array giving you the number of matching items. 
On the other hand if there is only one matching item, you do not get an array! Instead the variable contains directly the matching item and if you then access the .Length or .Count property, it's a property of that one matching item!

And it's not a feature of the Where-Object whateveryoucallthatsillything! It's a "feature" of the assignment.

If you run an SQL query using Invoke-Sqlcmd, you end up with the same problem. If there are more rows than one, you get an array and the .Length gives you the number of rows returned. If there's just one row, then the $result will be that row and the .Lenght will either blow up, or return the value of the [Length] column returned by the query!

This is absolutely insane design! Something people ought to be warned about in huge red letters so that they always use `@()` around calls that are supposed to return multiple elements. Otherwise they waste insane amount of time trying to find out why the heck do they sometimes get errors while handling the results of a SQL query or something like that.
