### ISSUE TITLE
Guidance on PowerShell and OneDrive

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/PowerShell-Docs#10883]
### Type of issue

Missing information

### Feedback

"We don't recommend redirecting the Documents folder to a network share or including it in OneDrive."

Please include information on:

1. How to remediate if OneDrive has already captured the  `Documents` directory.
2. How to install OneDrive to avoid capturing PowerShell files.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md

### Author

@sdwheeler

### Document Id

b175960c-519f-f591-0124-b93f36e8a927

**Comment by sdwheeler** [comment]
Go into the **OneDrive Settings** > **Sync and backup** > **Manage backup** and turn off the sync of the **Documents** folders.  The whole Documents folder will no longer sync to OneDrive.  Files that you want to sync to OneDrive can be placed in the OneDrive folder at C:\Users\username\OneDrive.

For more information, consult the [OneDrive documentation](https://learn.microsoft.com/onedrive/).

**Comment by sdwheeler** [comment]
Go into the **OneDrive Settings** > **Sync and backup** > **Manage backup** and turn off the sync of the **Documents** folders.  The whole Documents folder will no longer sync to OneDrive.  Files that you want to sync to OneDrive can be placed in the OneDrive folder at C:\Users\username\OneDrive.

For more information, consult the [OneDrive documentation](https://learn.microsoft.com/en-us/onedrive/).
