### ISSUE TITLE
Join-Path example 7 does not work

### ISSUE THREAD

**Issue by Ark-kun** [MicrosoftDocs/PowerShell-Docs#10898]
### Type of issue

Code doesn't work

### Feedback

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.4#example-7-combine-an-indefinite-number-of-paths

```
> Join-Path a b c d e f g
Join-Path : A positional parameter cannot be found that accepts argument 'c'.
At line:1 char:1
+ Join-Path a b c d e f g
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
```
```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3636
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3636
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I guess it's only supported in PS Core, right?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Management/Join-Path.md

### Author

@sdwheeler

### Document Id

ddfaffd4-1440-857a-21c5-ac66758bc5d0

**Comment by sdwheeler** [comment]
You are not viewing the correct version of the documentation. You are using Windows PowerShell 5.1, which doesn't have the `-AdditionalChildPath` parameter. But you were viewing the PowerShell 7.4 documentation.

You can choose the version of PowerShell documentation from the version picker above the Table of Contents.

[How to use the PowerShell documentation][1], has tips on navigating the documentation.

[1]: https://docs.microsoft.com/powershell/scripting/how-to-use-docs.
