### ISSUE TITLE
Range operator (`..`): make it clear that integer endpoints refers to `[int32]`, specifically

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#10906]
### Type of issue

Missing information

### Feedback

> The range operator can be used to represent an array of sequential integers 

While true, it would should be noted that the endpoints must be (convertible to) `[int32]` numbers, specifically, i.e. 32-bit signed integers. Larger integer values cause an error.

For instance, the following fail:

```powershell
1..([uint32]::MaxValue)

1gb..1tb  # 1tb is [int64]
```

Additionally, the _count of resulting numbers_ is limited to:

* `[int]::MaxValue - 56` when the result is captured in an _array_, as implicitly happens as part of an _expression_; this is due to the fact that said number is the max. count of elements in a .NET array

* `[int]::MaxValue + 1` in _streaming_ processing (where the numbers are created and consumed on demand, one by one)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators?view=powershell-7.4#range-operator-

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md

### Author

@sdwheeler

### Document Id

1ef1d966-3ba7-77aa-abb2-fb255d08da46

**Comment by sdwheeler** [comment]
> * `[int]::MaxValue + 1` in _streaming_ processing (where the numbers are created and consumed on demand, one by one)

@mklement0 I am not sure I understand this statement. I was able to stream the full range of `[int32]` values.

```powershell
[int32]::MinValue..[int32]::MaxValue | %{ $_ }
```

**Comment by mklement0** [comment]
You're right, I forgot about the negative range.

To put it differently: In streaming processing, `..` works fine as long as the endpoints both fit into `[int]` (`System.Int32`),
which amounts to an effective limit of  `[uint]::MaxValue + 1` (`System.UInt32`; `-[int]::MinValue + [int]::MaxValue + 1`), which is `4294967296`

I've updated the previous comment.
