### ISSUE TITLE
merge-pdf error

### ISSUE THREAD

**Issue by radclaant** [MicrosoftDocs/PowerShell-Docs#10916]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1

### Summary

buen dia agradezco su colaboracion. estoy teniendo dificultades, con merge-pdf, cuando intento ejecutar una combinacion me arroja el siguiente error.
![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/161480969/fa895fee-5fe9-4bb0-9121-2a6eb61228e1)

error de asercion: object number out of range en pdfSharp-Pdf.pdfobjectid...ctor(int32 object nuimber, int32 generation number)....continua.
//esto error tiene que ver con el documento pdf que se esta combinando. 
Sin embargo lo combina bien.
_¿puedo silenciar el mensaje de alguna manera?_
tambien seria util quitar la propiedad que falla, ¿puedo hacerlo de alguna manera?
la instruccion es la siguiente:
merge-pdf -Path "\\10.0.10.9\Radicacion Central\CLINICA LA ASUNCION\asdasdas\SANITAS\23446@.pdf" , "\\10.0.10.9\Radicacion Central\CLINICA LA ASUNCION\SANITAS\55119\SOPORTES\23446S.pdf" -outputpath "C:\Users\RADICACION\Desktop\auxm\Nueva carpeta\xxx17.pdf"

```
Name                           Value                                                       
----                           -----                                                       
PSVersion                      5.1.19041.4046                                              
PSEdition                      Desktop                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                     
BuildVersion                   10.0.19041.4046                                             
CLRVersion                     4.0.30319.42000                                             
WSManStackVersion              3.0                                                         
PSRemotingProtocolVersion      2.3                                                         
SerializationVersion           1.1.0.1                                                     
```

### Details

```
merge-pdf -Path "\\10.0.10.9\Radicacion Central\CLINICA LA ASUNCION\asdasdas\SANITAS\23446@.pdf" , "\\10.0.10.9\Radicacion Central\CLINICA LA ASUNCION\SANITAS\55119\SOPORTES\23446S.pdf" -outputpath "C:\Users\RADICACION\Desktop\auxm\Nueva carpeta\xxx17.pdf"
```

### Proposed Content Type

About Topic

**Comment by sdwheeler** [comment]
`Merge-PDF` is not a command published by Microsoft. Contact the owner of that module.
