### ISSUE TITLE
How Do You Save Stop-TimeService.ps1?

### ISSUE THREAD

**Issue by BB92506** [MicrosoftDocs/PowerShell-Docs#10917]
### Type of issue

Missing information

### Feedback

How Do You Save Stop-TimeService.ps1? Up until the instruction to save this file, no instruction has been given as to how to save a file using Powershell.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.5

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/ps101/01-getting-started.md

### Author

@sdwheeler

### Document Id

c2a54962-1511-7f87-24c5-f39b61f923bb

**Comment by sdwheeler** [comment]
A script file is just a plaintext file that contains the commands that you want to run. It can create with any text editor, such as Notepad.
