### ISSUE TITLE
Where do we find "Make-Kit" and "Make-Shell"?

### ISSUE THREAD

**Issue by suprak** [MicrosoftDocs/PowerShell-Docs#10918]
### Type of issue

Missing information

### Feedback

The documentation provides the command line arguments for a "make-shell" tool, but there is no information about where to get it from.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/developer/prog-guide/how-to-create-a-console-shell?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/developer/prog-guide/how-to-create-a-console-shell.md

### Author

@sdwheeler

### Document Id

1453751e-10e2-bcb8-1ee2-0af3756ba1e8

**Comment by sdwheeler** [comment]
That tool is no longer available or supported.
