### ISSUE TITLE
Typo on the translation of LTS in french

### ISSUE THREAD

**Issue by gbaudoin** [MicrosoftDocs/PowerShell-Docs#10930]
### Type of issue

Typo

### Feedback

On the title here:
https://learn.microsoft.com/fr-fr/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.4#install-the-latest-lts-release-of-powershell
The current french translation is wrong: "Installer la dernière version LST de PowerShell"
It should read "Installer la dernière version LTS de PowerShell"

### Page URL

https://learn.microsoft.com/fr-fr/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.4#install-the-latest-lts-release-of-powershell

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md

### Author

@sdwheeler

### Document Id

d025a07e-05e1-ef40-5500-36d3facbcc04

**Comment by sdwheeler** [comment]
Thank you for reporting this problem. I have opened an issue with our translation team.

**Comment by sdwheeler** [comment]
This is fixed now.
