### ISSUE TITLE
Add version specific Language Specification docs

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#10946]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1, 7.2, 7.3, 7.4

### Summary

Originally opened in https://github.com/PowerShell/PowerShell/issues/2254 but I think should be opened here for better tracking as is a docs issue rather than a code issue

Comments in that issue particularly from @lzybkr & @iSazonov @vexx32 as well as the issue author @TimCurwick & others show both the need and desire for this going forward. 

### Details

This may need to have a restructuring of the docs so that version specific docs can be easily reached
Ideally should also have v1, v2 & v4 versions for historical purposes but that's a major stretch goal that IMO would need more people on the team to help make this happen as well as community support to help make it a reality.

### Proposed Content Type

Other / Unknown

### Proposed Title

Language Specification Document

### Related Articles

https://learn.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-01?view=powershell-7.2

**Comment by sdwheeler** [comment]
The PowerShell team has no plans to update the language specification, as stated in the [Introduction](https://learn.microsoft.com/powershell/scripting/lang-spec/chapter-01).

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/19415881/6bb76168-5ed1-4671-ad34-1097873ce7d7)
