### ISSUE TITLE
incorrect location of user profile  in window

### ISSUE THREAD

**Issue by uiolee** [MicrosoftDocs/PowerShell-Docs#10956]
### Type of issue

Code doesn't work

### Feedback

![profile](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/22849383/02f8c648-3c6c-4957-96a2-fcc5b7f7b664)

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4#profile-types-and-locations

In windows' default setting, `$home` is point to 'c:\users\{name}\', and `Documents` folder is located in `c:\users\{name}\documents\`.
In default setting, `$HOME\Documents\PowerShell\` is a correct location.

BUT,
the path of `Documents` folder is modifiable. Users can set `Documents` folder path to `D:/documents` or any other. At that time, `$HOME\Documents\PowerShell\` doesn't work.

I guess `pwsh` is using `Documents\PowerShell\` as profile location, instead of `$HOME\Documents\PowerShell\`

This content mislead me for a while.

If I put profiles in `$home/Documents/Powershell`, they didn't work.
When I put profiles in `Documents/Powershell/`, they actually works.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4#profile-types-and-locations

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md

### Author

@sdwheeler

### Document Id

b175960c-519f-f591-0124-b93f36e8a927

**Comment by sdwheeler** [comment]
These are the default locations. Of course, the location can be changed by OneDrive or other folder redirection solutions.
