### ISSUE TITLE
latest powershell update

### ISSUE THREAD

**Issue by simantbashyal4292** [MicrosoftDocs/PowerShell-Docs#10955]
### Type of issue

Code doesn't work

### Feedback

![Screenshot 2024-03-16 184652](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/114978356/1ade1a3a-c835-4e0a-9ff2-102c642bddd1)

### Page URL

https://learn.microsoft.com/en-gb/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.4#installing-powershell-7

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md

### Author

@sdwheeler

### Document Id

c042b902-bdfb-5eea-f956-87b1c86644a7

**Comment by sdwheeler** [comment]
@simantbashyal4292  What code doesn't work?
