### ISSUE TITLE
Inadequate explanation of terminology

### ISSUE THREAD

**Issue by m-brooks** [MicrosoftDocs/PowerShell-Docs#10961]
### Type of issue

Missing information

### Feedback

This article suffers from an all-too-common malady among documentation that has been written by technical people, which is that it assumes that the reader already knows the underlying concepts. For certain types of documentation that is an appropriate premise, but not for an "about" article - by definition these exist to explain concepts. In the case of the identified page, it discusses how to perform both the installation and importation of modules without explaining what these terms mean. It does state that one cannot use a module until it has been installed, which at least informs the reader that installation is a prerequisite step for use, but it doesn't clearly explain why. It then goes on to discuss how to import a module without explaining what this means or why this step might be necessary. To add further confusion, it also sprinkles the verb "load" (e.g. "autoloading") into the mix - an additional ambiguous term such as this does nothing to aid comprehension.

### Page URL

https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_modules?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md

### Author

@sdwheeler

### Document Id

d37fa5e2-df37-16a9-102c-928def14abec

**Comment by sdwheeler** [comment]
Thanks for the feedback. You can find a definition of a module at: https://learn.microsoft.com/powershell/scripting/learn/glossary#module.

**Comment by m-brooks** [comment]
Thanks, but since my example was on the terms "install" and "import" and these are not covered by the glossary (which isn't referenced from the page in question anyway), I'm not sure that really addresses the issue.

**Comment by sdwheeler** [comment]
I have updated the about_Modules to add definitions and context.
