### ISSUE TITLE
Clarify that `-IsValid` requires a drive being referred to to exist, and that 7+ no longer performs syntax validation

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#10963]
### Type of issue

Missing information

### Feedback

The `-IsValid` description states:

> Indicates that this cmdlet tests the syntax of the path, regardless of whether the elements of the path exist.

That is true _except_ if the path contains a _drive specification_: The referenced drive must exist (whereas any path components need not).

E.g., `Test-Path -IsValid NoSuchDrive:foo` is `$false`

 * Update: See for #10967 a workaround.

Also, in v7+, `-IsValid` _no longer performs syntax validation_, because it relies on a .NET API that removed its own validation in .NET Core 2.1.

This makes the `-IsValid` switch near-useless (the only formal validation that is now performed is to return `$false` if a ``"`0"`` char. is present in the path).

See https://github.com/PowerShell/PowerShell/issues/20847#issuecomment-2004573434 and the subsequent comments for background information.

At this point there's no official feedback on whether documenting the issue alone is sufficient - amounting to an effective deprecation of the switch - or whether syntax validation will be brought back by implementing it on the PowerShell side (which would be fairly easy to do).

_Update_: The WG decision in https://github.com/PowerShell/PowerShell/issues/20847#issuecomment-2010046701 suggests that the functionally will be reinstated with custom code in `Test-Path`

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-7.4&viewFallbackFrom=powershell-7

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Management/Test-Path.md

### Author

@sdwheeler

### Document Id

47f07437-e8a5-7506-4e4a-33a4781d1f1f

**Comment by sdwheeler** [comment]
- Copied from #10967 

> Users may be surprised that `test-path -isvalid z:\abc.txt` returns false if `z:` doesn't exist.
> 
> This is because the cmdlet can't find a provider to perform the validation.
> 
> ### Suggested Fix
> Add an example to explicitly specify the provider:
> 
> test-path -isvalid filesystem::z:\abc.txt
