### ISSUE TITLE
Typo in the "Örnek 4" section

### ISSUE THREAD

**Issue by ozdemiremrah81** [MicrosoftDocs/PowerShell-Docs#10972]
### Type of issue

Typo

### Feedback

There is "Yönetici istrators grubuna" in "Örnek 4" section. Which obviously must be "Yönetici grubuna" or "Yönetici / Administrators grubuna"

### Page URL

https://learn.microsoft.com/tr-tr/powershell/module/microsoft.powershell.core/disable-psremoting?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/Disable-PSRemoting.md

### Author

@sdwheeler

### Document Id

90a5cda5-dd26-ad57-e7c4-a660d3fa667c

**Comment by sdwheeler** [comment]
@ozdemiremrah81 Thank you for reporting this issue. 

I have opened a support ticket with our localization team that handles translation to other languages. Work to fix this is tracked in that request. At this time, I don't know when this will be fixed, but there is nothing I can do to fix it. It must go through our localization pipeline.
