### ISSUE TITLE
$PSCmdlet.ParameterSetName not covered

### ISSUE THREAD

**Issue by DennisL68** [MicrosoftDocs/PowerShell-Docs#10987]
### Type of issue

Missing information

### Feedback

In an instance where you'd like to know what parameter set was used, you can use the variable property `$PSCmdlet.ParameterSetName`.

~~~
function Get-ParamsetNameUsed {

    [CmdletBinding(DefaultParameterSetName = 'Set1')]
    param (
        [Parameter(ParameterSetName = 'Set1')]
        $Var1,

        [Parameter(ParameterSetName = 'Set2')]
        $Var2,

        [Parameter(ParameterSetName = 'Set1')]
        [Parameter(ParameterSetName = 'Set2')]
        $Var3,

        $Var4
    )

    if ($PSCmdlet.ParameterSetName -eq 'Set1') {
        Write-Output 'Paramset 1 used'
    }

    if ($PSCmdlet.ParameterSetName -eq 'Set2') {
        Write-Output 'Paramset 2 used'
    }
    
}

Get-ParamsetNameUsed -Var1 1

~~~

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameter_sets?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

### Author

@sdwheeler

### Document Id

b974f00e-240b-0dd5-b87b-709f92d23633

**Comment by sdwheeler** [comment]
Good idea.
