### ISSUE TITLE
How to extract all data parameters from an event log

### ISSUE THREAD

**Issue by NaouresTahri** [MicrosoftDocs/PowerShell-Docs#10986]
### Type of issue

Missing information

### Feedback

I did not find enough information on how to extract event logs data specifically of "Task Category, Keywords, Operational Code, User"  and many others as string values in the same way are written in the Event Viewer GUI interface.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-eventlog?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Management/Get-EventLog.md

### Author

@sdwheeler

### Document Id

8fd10e62-dee2-56fd-e3c1-07c07f8854a3

**Comment by sdwheeler** [comment]
`Get-EventLog` doesn't provide that information. You need to use `Get-WinEvent`. See the following articles:

- https://learn.microsoft.com/powershell/scripting/samples/creating-get-winevent-queries-with-filterhashtable
- https://learn.microsoft.com/powershell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-5.1
