### ISSUE TITLE
SSL certificate automation power shell script for windows server and websites or related docs

### ISSUE THREAD

**Issue by pratikchamalwar** [MicrosoftDocs/PowerShell-Docs#10993]
### Type of issue

Typo

### Feedback

Hi guys anyone have SSL certificate automation power shell script for windows server and websites or related docs

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Signing.md

### Author

@sdwheeler

### Document Id

1c683f8a-0ee9-15c7-d883-2bc2c0fc26b9

**Comment by sdwheeler** [comment]
Windows has a PKI module. See https://learn.microsoft.com/powershell/module/pki/?view=windowsserver2022-ps
