### ISSUE TITLE
No required configuration foa active directory

### ISSUE THREAD

**Issue by AD705177** [MicrosoftDocs/PowerShell-Docs#11003]
### Type of issue

Typo

### Feedback

Hello,
There no required configuration for active directory on the documentation page.
Could you help me please?

### Page URL

https://learn.microsoft.com/fr-fr/powershell/scripting/learn/ps101/03-discovering-objects?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/ps101/03-discovering-objects.md

### Author

@AD705177!

### Document Id

ace38d3f-9e35-86da-e4dc-ce4a5aca33fd

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
