### ISSUE TITLE
Document not to use `--edge` with the Snap Preview package.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [MicrosoftDocs/PowerShell-Docs#11024]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/7d34367824fd0711eaf3fb2401671fd08dbc8ffd/reference/docs-conceptual/install/install-other-linux.md#installation-via-snap:~:text=To%20install%20a,PowerShell%0Apwsh-preview

### Summary

The aforereferenced URI states:

<blockQuote>

To install a preview version, use the following method:

```sh
# Install PowerShell
sudo snap install powershell-preview --classic

# Start PowerShell
pwsh-preview
```

</blockQuote>

However,

```PS1
sudo snap install powershell-preview --channel=latest/edge --classic
```

hasn't been updated since https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0, per https://github.com/PowerShell/PowerShell-Snap/issues/100#issue-2033877532.

### Suggested Fix

I believe that this discrepancy should be documented, because someone who wants to test the latest version expectedly may choose `--edge` instead of `--stable`.

**Comment by sdwheeler** [comment]
@sdwheeler See reference https://snapcraft.io/docs/channels

**Comment by sdwheeler** [comment]
@RokeJulianLockhart Yes I meant to. It is for my reference. I need to have internal discussions about this. It was not meant to be an answer for you.

**Comment by sdwheeler** [comment]
After conferring with the engineering team, we only support the following channels:

powershell
- latest/stable
- lts/stable

powershell-preview
- latest/stable

The other channels should be ignored. I will get this added to the docs.
