### ISSUE TITLE
Provide instructions on how to force the new version of PowerShell to replace the old version

### ISSUE THREAD

**Issue by beefydog** [MicrosoftDocs/PowerShell-Docs#11029]
### Type of issue

Missing information

### Feedback

After installing PowerShell, it would be nice to show instructions on both how to replace the built-in older version as well as how to actually run the latest version. This would save a lot of time.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

@sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by sdwheeler** [comment]
PowerShell is designed to install side-by-side with Windows PowerShell 5.1. You can remove or update Windows PowerShell 5.1. See [Using PowerShell 7 side-by-side with Windows PowerShell 5.1](https://learn.microsoft.com/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7#using-powershell-7-side-by-side-with-windows-powershell-51).

If you are running a version of PowerShell (6.0 or higher), installing a newer version of PowerShell 7 should replace the older version.
