### ISSUE TITLE
New-SPWebApplicationExtension lacks examples and clarification of formats for parameters

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/PowerShell-Docs#11059]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

 https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/new-spwebapplicationextension?view=sharepoint-server-ps

### Summary

The page needs additional examples and descriptions for the accepted formats of the following parameters:

-AdditionalClaimProvider
-SignInRedirectProvider
-SignInRedirectURL

**Comment by sdwheeler** [comment]
This content is not in our docset. You find the source at https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/New-SPWebApplicationExtension.md. Please file an issue in that repository.
