### ISSUE TITLE
libssl1.1 is not found

### ISSUE THREAD

**Issue by TimNilimaa** [MicrosoftDocs/PowerShell-Docs#11068]
### Type of issue

Code doesn't work

### Feedback

```
sudo apk add --no-cache \
    ca-certificates \
    less \
    ncurses-terminfo-base \
    krb5-libs \
    libgcc \
    libintl \
    libssl1.1 \
    libstdc++ \
    tzdata \
    userspace-rcu \
    zlib \
    icu-libs \
    curl
```

command above does not work as libssl1.1 is not part of main repository. Below works

```
sudo apk add --no-cache \
    ca-certificates \
    less \
    ncurses-terminfo-base \
    krb5-libs \
    libgcc \
    libintl \
    libstdc++ \
    tzdata \
    userspace-rcu \
    zlib \
    icu-libs \
    curl

sudo apk -X https://dl-cdn.alpinelinux.org/alpine/edge/testing add --no-cache \
     libssl1.1
```

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-alpine.md

### Author

@sdwheeler

### Document Id

da6c7c79-75ee-f19a-09b5-59dc21139242

**Comment by sdwheeler** [comment]
We only support Alpine 3.16 (which ends this month), 3.17, and 3.18. We haven't tested 3.19, which is where this error occurs. When we support 3.19 we will update the documentation.
