### ISSUE TITLE
split does not split from end

### ISSUE THREAD

**Issue by comet-crmiller** [MicrosoftDocs/PowerShell-Docs#11083]
### Type of issue

Code doesn't work

### Feedback

"a,b,c,d,e,f,g,h" -split ",", -3 in this article indicates that the string will split starting from the end, and it does not. 
![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/123398499/3563ae81-5054-4710-b314-d682923cd58c)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_split?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Split.md

### Author

@sdwheeler

### Document Id

634c57a3-c4dc-7a04-381e-7ae326b40483

**Comment by sdwheeler** [comment]
You are running the command in Windows PowerShell 5.1 but looking at documentation for PowerShell 7.4.

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/19415881/5082dd81-b67c-4142-9633-97096a8f25dc)
