### ISSUE TITLE
Compress-Archive -Path description does not have wildcard * appearing

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/PowerShell-Docs#11108]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Archive/Compress-Archive.md#-path

### Summary

The wildcard `*` character does not appear when using `help Compress-Archive` for the `-Path` parameter in a PowerShell console.
```
) wildcard. For example: `-Path C:\Reference\ ` - To create an archive that only zips the files in the root directory, use the star-dot-star (` . `)
        wildcard. Subdirectories of the root aren't included in the archive. For example:   `-Path C:\Reference\ . 
```

### Details

```
Caption             : Microsoft Windows 10 Pro
Version             : 10.0.19045
PSVersion           : 7.4.2
DisplayVersion      : 22H2
OSArchitecture      : 64-bit
```

**Comment by sdwheeler** [comment]
This is a known bug in PlatyPS, the tool used to generate the MAML files used by `Get-Help`. PlatyPS is in the process of being rewritten from scratch. We hope to have a new version by the end of the year.
