### ISSUE TITLE
7.3 showing as supported when supported ended May 8th

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#11113]
### Type of issue

Outdated article

### Feedback

Shows 7.3 as supported with green checkboxes even though end of support has passed.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

### Author

@sdwheeler

### Document Id

c138e6a8-fd80-bd64-25ac-24e774e09421

**Comment by sdwheeler** [comment]
@JustinGrote Thanks. I am still working on the updates.
