### ISSUE TITLE
FLUTTER DOSEN'T RECOGONIZE

### ISSUE THREAD

**Issue by asma829** [MicrosoftDocs/PowerShell-Docs#11127]
### Type of issue

Code doesn't work

### Feedback

C:\SDK>FLUTTER CREATE E
'FLUTTER' is not recognized as an internal or external command,
operable program or batch file.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.4#using-powershell-7-side-by-side-with-windows-powershell-51

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md

### Author

@sdwheeler

### Document Id

c042b902-bdfb-5eea-f956-87b1c86644a7

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
