### ISSUE TITLE
Reporting Bugs Against PowerShell Cmdlets

### ISSUE THREAD

**Issue by WilliamDShiell** [MicrosoftDocs/PowerShell-Docs#11134]
### Type of issue

Other (describe below)

### Feedback

Where can we report issues with certain PowerShell cmdlets? I need to open an issue related to the Expand-Archive cmdlet.

Thanks!

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Archive/Expand-Archive.md

### Author

@sdwheeler

### Document Id

7b159e73-de5a-cec9-3a01-eb59e8a09af6

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. Please [file an issue][1] with the PowerShell team.

[1]: https://aka.ms/psfeedback

**Comment by WilliamDShiell** [comment]
Thanks @sdwheeler!

**Comment by sdwheeler** [comment]
There is also a link just be low the link you used to open this issue.

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/19415881/2a4426c3-fcea-42a2-a95d-c538de0188af)
