### ISSUE TITLE
Not work install in 23.10 

### ISSUE THREAD

**Issue by andresgarcia0313** [MicrosoftDocs/PowerShell-Docs#11135]
### Type of issue

Code doesn't work

### Feedback

ndres@lenovoazul:~$ sudo -v
[sudo] contraseña para andres: 
andres@lenovoazul:~$ ###################################
# Prerequisites

# Update the list of packages
sudo apt-get update

# Install pre-requisite packages.
sudo apt-get install -y wget apt-transport-https software-properties-common

# Get the version of Ubuntu
source /etc/os-release

# Download the Microsoft repository keys
wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb 

# Register the Microsoft repository keys
sudo dpkg -i packages-microsoft-prod.deb

# Delete the Microsoft repository keys file
rm packages-microsoft-prod.deb

# Update the list of packages after we added packages.microsoft.com
sudo apt-get update

###################################
# Install PowerShell
sudo apt-get install -y powershell

# Start PowerShell
pwsh
Ign:1 http://linux.dropbox.com/ubuntu mantic InRelease                                     
Des:2 https://packages.microsoft.com/repos/edge stable InRelease [3.590 B]                 
Obj:3 http://archive.ubuntu.com/ubuntu mantic InRelease                                    
Obj:4 http://archive.ubuntu.com/ubuntu mantic-updates InRelease                            
Obj:5 https://download.sublimetext.com apt/stable/ InRelease                               
Des:6 https://packages.microsoft.com/repos/code stable InRelease [3.590 B]                 
Obj:7 http://linux.dropbox.com/ubuntu mantic Release                                     
Obj:8 http://archive.ubuntu.com/ubuntu mantic-backports InRelease
Obj:9 http://archive.ubuntu.com/ubuntu mantic-security InRelease
Descargados 7.180 B en 2s (3.638 B/s)
Leyendo lista de paquetes... Hecho
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
wget ya está en su versión más reciente (1.21.3-1ubuntu1).
fijado wget como instalado manualmente.
software-properties-common ya está en su versión más reciente (0.99.39).
fijado software-properties-common como instalado manualmente.
Se instalarán los siguientes paquetes NUEVOS:
  apt-transport-https
0 actualizados, 1 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 3.966 B de archivos.
Se utilizarán 36,9 kB de espacio de disco adicional después de esta operación.
Des:1 http://archive.ubuntu.com/ubuntu mantic-updates/universe amd64 apt-transport-https all 2.7.3ubuntu0.1 [3.966 B]
Descargados 3.966 B en 0s (10,9 kB/s)          
Seleccionando el paquete apt-transport-https previamente no seleccionado.
(Leyendo la base de datos ... 279805 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../apt-transport-https_2.7.3ubuntu0.1_all.deb ...
Desempaquetando apt-transport-https (2.7.3ubuntu0.1) ...
Configurando apt-transport-https (2.7.3ubuntu0.1) ...
Seleccionando el paquete packages-microsoft-prod previamente no seleccionado.
(Leyendo la base de datos ... 279809 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar packages-microsoft-prod.deb ...
Desempaquetando packages-microsoft-prod (1.1-ubuntu23.10) ...
Configurando packages-microsoft-prod (1.1-ubuntu23.10) ...
Obj:1 http://archive.ubuntu.com/ubuntu mantic InRelease                                                                                                                                    
Obj:2 http://archive.ubuntu.com/ubuntu mantic-updates InRelease                                                                                                                            
Ign:3 http://linux.dropbox.com/ubuntu mantic InRelease                                                                                    
Obj:4 http://archive.ubuntu.com/ubuntu mantic-backports InRelease                                                                      
Obj:5 http://linux.dropbox.com/ubuntu mantic Release                                                                                   
Des:6 https://packages.microsoft.com/repos/edge stable InRelease [3.590 B]      
Obj:7 https://download.sublimetext.com apt/stable/ InRelease                    
Des:8 https://packages.microsoft.com/ubuntu/23.10/prod mantic InRelease [3.606 B]
Obj:9 http://archive.ubuntu.com/ubuntu mantic-security InRelease
Des:11 https://packages.microsoft.com/repos/code stable InRelease [3.590 B]
Des:12 https://packages.microsoft.com/ubuntu/23.10/prod mantic/main all Packages [346 B]
Des:13 https://packages.microsoft.com/ubuntu/23.10/prod mantic/main arm64 Packages [1.247 B]
Des:14 https://packages.microsoft.com/ubuntu/23.10/prod mantic/main armhf Packages [682 B]
Des:15 https://packages.microsoft.com/ubuntu/23.10/prod mantic/main amd64 Packages [18,3 kB]
Descargados 31,4 kB en 2s (13,6 kB/s)  
Leyendo lista de paquetes... Hecho
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete powershell
No se ha encontrado la orden «pwsh», pero se puede instalar con:
sudo snap install powershell
andres@lenovoazul:~$ sudo apt search pwsh
Ordenando... Hecho
Buscar en todo el texto... Hecho
andres@lenovoazul:~$ sudo apt-get install -y powershell
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete powershell
andres@lenovoazul:~$ source /etc/os-releaseç
bash: /etc/os-releaseç: No existe el archivo o el directorio
andres@lenovoazul:~$ source /etc/os-release
andres@lenovoazul:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
andres@lenovoazul:~$ wget -q https://packages.microsoft.com/config/ubuntu/23.10/packages-microsoft-prod.deb
andres@lenovoazul:~$ ls -la
total 820
drwxr-x--x 52 andres andres   4096 may 20 17:04  .
drwxr-xr-x  5 root   root     4096 may  5 18:18  ..
drwxr-xr-x  3 andres andres   4096 may  8 17:54  .anydesk
-rw-rw-r--  1 andres andres     24 may 16 13:19  .aspell.en.prepl
-rw-rw-r--  1 andres andres     37 may 16 13:19  .aspell.en.pws
-rw-------  1 andres andres  20627 may 20 15:45  .bash_history
-rw-r--r--  1 andres andres    220 may  1 01:06  .bash_logout
-rw-r--r--  1 andres andres   3986 may 13 13:52  .bashrc
drwxrwxr-x 55 andres andres   4096 may 20 16:58  .cache
drwxrwxr-x  6 andres andres   4096 may  1 10:15  .clamtk
drwxrwxr-x  3 andres andres   4096 may 10 22:03  Compartida
drwxr-xr-x 42 andres andres   4096 may 20 17:03  .config
-rw-rw-r--  1 andres andres    163 may  1 01:41  cv_debug.log
drwx------  3 andres andres   4096 may  1 17:46  .dbus
drwxrwxr-x 10 andres andres   4096 may 20 15:10  Desarrollo
drwxrwxr-x 53 andres andres   4096 may 19 17:59 'Desarrollo Server'
drwxr-xr-x  2 andres andres   4096 may 12 10:29  Desktop
drwx------  3 andres andres   4096 may 20 14:23  .docker
drwxr-xr-x  5 andres andres   4096 may 17 16:14  Documents
drwxrwxr-x  3 andres andres   4096 may  6 12:07  .dotnet
drwxr-xr-x  8 andres andres   4096 may 20 15:35  Downloads
drwx------  9 andres andres   4096 may 20 15:45  .dropbox
drwx------  4 andres andres   4096 may 20 15:46  Dropbox
drwxrwxr-x  3 andres andres   4096 may 20 15:44  .dropbox-dist
drwxr-xr-x  3 andres andres   4096 may 18 23:40  .eclipse
-rw-r--r--  1 andres andres  14965 may  1 01:06  .face
lrwxrwxrwx  1 andres andres      5 may  1 01:06  .face.icon -> .face
-rw-rw-r--  1 andres andres    151 may 10 16:45  .gitconfig
drwx------  3 andres andres   4096 may  1 01:45  .gnome
drwx------  4 andres andres   4096 may 16 15:46  .gnupg
-rw-rw-r--  1 andres andres    276 may 19 10:56  .gtkrc-2.0
drwxr--r--  2 andres andres   4096 may  6 17:07  .hardinfo
-rw-rw-r--  1 andres andres     16 may 16 13:19  .hunspell_es_CO
-rw-------  1 andres andres      0 may  7 14:13  .ICEauthority
drwxrwxr-x  3 andres andres   4096 may  1 14:40  .icons
drwxr-xr-x  3 andres andres   4096 may 20 10:21  .java
drwxrwxr-x  3 andres andres   4096 may  1 14:59  .kde
drwxr-xr-x  7 andres andres   4096 may  7 17:37  .kodi
-rw-------  1 andres andres     20 may  1 10:08  .lesshst
drwxrwxr-x  4 andres andres   4096 may  1 01:08  .local
-rw-rw-r--  1 andres andres  16374 may  1 20:03  models.json
drwx------  3 andres andres   4096 may  1 14:07  .mozilla
drwxr-xr-x  2 andres andres   4096 may  1 01:08  Music
drwxrwxr-x  5 andres andres   4096 may 14 10:24  .npm
drwxrwxr-x  8 andres andres   4096 may 10 16:40  .nvm
drwxr-xr-x  2 andres andres   4096 may 19 10:54  .ollama
-rw-rw-r--  1 andres andres   4298 mar 13 13:16  packages-microsoft-prod.deb
-rw-r--r--  1 andres andres    355 may  1 17:40  .pam_environment
drwxr-xr-x  3 andres andres   4096 may 18 10:02  Pictures
drwx------  3 andres andres   4096 may  1 01:39  .pki
drwxr-xr-x  3 andres andres   4096 may 14 22:12  Postman
-rw-r--r--  1 andres andres    807 may  1 01:06  .profile
drwxrwxr-x  8 andres andres   4096 may 16 12:18  Programas
drwxr-xr-x  2 andres andres   4096 may  1 01:08  Public
drwxrwxr-x  3 andres andres   4096 may 19 01:51  .quokka
drwxrwxr-x  2 andres andres   4096 may 13 10:29  .redhat
drwxrwxr-x  3 andres andres   4096 may  6 12:11  .rest-client
drwx------  4 andres andres   4096 may 20 13:59  snap
drwxrwxr-x 50 andres andres   4096 may 20 16:51  .sonarlint
drwx------  2 andres andres   4096 may  9 09:45  .ssh
-rw-r--r--  1 andres andres      0 may  1 01:24  .sudo_as_admin_successful
drwxr-xr-x  2 andres andres   4096 may 18 23:43  .swt
drwxr-xr-x  2 andres andres   4096 may  5 20:41  Temp
drwxr-xr-x  2 andres andres   4096 may  1 01:08  Templates
drwxrwxr-x 12 andres andres   4096 may  8 13:53  .themes
drwx------  6 andres andres   4096 may  1 14:07  .thunderbird
drwxr-xr-x  3 andres andres   4096 may  1 11:55  .var
drwxr-xr-x  4 andres andres   4096 may 11 13:16  Videos
drwxrwxr-x  4 andres andres   4096 may  6 12:06  .vscode
drwxrwxr-x  2 andres andres   4096 may 18 20:43  .wallaby
-rw-rw-r--  1 andres andres    308 may 20 17:04  .wget-hsts
-rw-------  1 andres andres 503986 may 19 10:56  .xsession-errors
andres@lenovoazul:~$ sudo dpkg -i packages-microsoft-prod.deb
(Leyendo la base de datos ... 279826 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar packages-microsoft-prod.deb ...
Desempaquetando packages-microsoft-prod (1.1-ubuntu23.10) sobre (1.1-ubuntu23.10) ...
Configurando packages-microsoft-prod (1.1-ubuntu23.10) ...
File /usr/share/keyrings/microsoft-prod.gpg is missing. Installing...
andres@lenovoazul:~$ sudo dpkg -i packages-microsoft-prod.deb
(Leyendo la base de datos ... 279826 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar packages-microsoft-prod.deb ...
Desempaquetando packages-microsoft-prod (1.1-ubuntu23.10) sobre (1.1-ubuntu23.10) ...
Configurando packages-microsoft-prod (1.1-ubuntu23.10) ...
File /usr/share/keyrings/microsoft-prod.gpg is missing. Installing...
andres@lenovoazul:~$ sudo dpkg -i packages-microsoft-prod.deb
(Leyendo la base de datos ... 279826 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar packages-microsoft-prod.deb ...
Desempaquetando packages-microsoft-prod (1.1-ubuntu23.10) sobre (1.1-ubuntu23.10) ...
Configurando packages-microsoft-prod (1.1-ubuntu23.10) ...
File /usr/share/keyrings/microsoft-prod.gpg is missing. Installing...
andres@lenovoazul:~$ sudo apt-get update
Ign:1 http://linux.dropbox.com/ubuntu mantic InRelease                                     
Obj:2 http://archive.ubuntu.com/ubuntu mantic InRelease                                    
Des:3 https://packages.microsoft.com/repos/edge stable InRelease [3.590 B]                 
Obj:4 http://archive.ubuntu.com/ubuntu mantic-updates InRelease                            
Des:5 https://packages.microsoft.com/ubuntu/23.10/prod mantic InRelease [3.606 B]          
Obj:6 https://download.sublimetext.com apt/stable/ InRelease                    
Obj:7 http://linux.dropbox.com/ubuntu mantic Release                                     
Obj:8 http://archive.ubuntu.com/ubuntu mantic-backports InRelease
Des:9 https://packages.microsoft.com/repos/code stable InRelease [3.590 B]
Obj:10 http://archive.ubuntu.com/ubuntu mantic-security InRelease
Descargados 10,8 kB en 2s (5.548 B/s)
Leyendo lista de paquetes... Hecho
andres@lenovoazul:~$ sudo apt-get install -y powershell
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete powershell
andres@lenovoazul:~$ https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb
bash: https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb: No existe el archivo o el directorio
andres@lenovoazul:~$ https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb
bash: https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb: No existe el archivo o el directorio
andres@lenovoazul:~$ 

### Page URL

https://learn.microsoft.com/es-es/powershell/scripting/install/install-ubuntu?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-ubuntu.md

### Author

@sdwheeler

### Document Id

2405ca72-f9d4-24a5-12a9-304d18a656ce

**Comment by sdwheeler** [comment]
Ubuntu 23.10 is an interim release. We don't support interim releases. See https://learn.microsoft.com/powershell/scripting/install/install-ubuntu#supported-versions
