### ISSUE TITLE
HAS MISSING INFO FROM THE GITHUB DESKTOP

### ISSUE THREAD

**Issue by CasP0** [MicrosoftDocs/PowerShell-Docs#11137]
### Type of issue

Missing information

### Feedback

HAS MISSING INFO FROM THE GITHUB DESKTOP

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/object-model/the-powershelltabcollection-object?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/windows-powershell/ise/object-model/The-PowerShellTabCollection-Object.md

### Author

@sdwheeler

### Document Id

4e04e1fc-8738-dc86-5d34-0c6d3f9d33de

**Comment by sdwheeler** [comment]
@CasP0 What information is missing? What does this have to do with GITHUB DESKTOP?

**Comment by CasP0** [comment]
SEEMS THAT IT ISNT HAD A GOOD BEHAVIOR ALL THE WINDOWS SYSTEMS HAS BEEN CRASHING MORE THAN TWICE
