### ISSUE TITLE
Get-SPOSite(Microsoft.Online.SharePoint.PowerShell) when use -Limit parameter "SharingCapability" value is returned correct, not match with the article

### ISSUE THREAD

**Issue by CoralFang** [MicrosoftDocs/PowerShell-Docs#11144]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps 

<img width="482" alt="article issue" src="https://github.com/MicrosoftDocs/PowerShell-Docs/assets/170995314/f47fd1cf-3949-43c6-b04e-d63157d90c88">

### Summary

In document is says -limit parameter cannot populated SharingCapability, but we tried in old version 16.0.20717.12000 and latest version it's all returned. Which make confuse whether it's an improvement or it's happen to work currently.### 

### Suggested Fix

Remove the SharingCapability in this note

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. The documentation you are asking about is not part of this repository.

Use the **Feedback** link at the top of the page to report your issue.

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/19415881/c5ff48a3-dd9e-4182-b27d-bb410394b58b)
