### ISSUE TITLE
idl

### ISSUE THREAD

**Issue by bebra74** [MicrosoftDocs/PowerShell-Docs#11151]
### Type of issue

Typo

### Feedback

[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; 

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/starting-windows-powershell?view=powershell-7.4&viewFallbackFrom=powershell-7.3#with-administrative-privileges-run-as-administrator

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/windows-powershell/Starting-Windows-PowerShell.md

### Author

@sdwheeler

### Document Id

5083230c-498b-4ae2-de46-078d0aff4b83

**Comment by bebra74** [comment]
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; Invoke-Expression (New-Object Net.WebClient).DownloadString("https://gist.githubusercontent.com/Star-Rail-Station/2512df54c4f35d399cc9abbde665e8f0/raw/get_warp_link_os.ps1?cachebust=srs")

**Comment by bebra74** [comment]
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; Invoke-Expression (New-Object Net.WebClient).DownloadString("https://gist.githubusercontent.com/Star-Rail-Station/2512df54c4f35d399cc9abbde665e8f0/raw/get_warp_link_os.ps1?cachebust=srs")

**Comment by sdwheeler** [comment]
This issue and your activity in it violates Microsoft’s Open Source [Code of Conduct(“CoC”)](https://opensource.microsoft.com/codeofconduct/).
