### ISSUE TITLE
`Select-Object` should be explicit that the input object can be modified

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#11198]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Select-Object?view=powershell-7.4
- https://github.com/PowerShell/PowerShell/pull/21328
- https://github.com/PowerShell/PowerShell/issues/21308

### Summary

The `Select-Object` docs do not indicate that there are cases where the input object may be modified which can be surprising to users.  As the WG-Cmdlets has made a decision to NOT change this behavior as we believe it would likely break folks, we need to document this explicitly.

### Details

- See https://github.com/PowerShell/PowerShell/issues/21308

### Suggested Fix

Add details to the docs on when the input object can be modified.
Add example on how to get the same behavior as `ExpandProperty` by simply creating a new PSObject "manually" instead of using `Select-Object`

**Comment by sdwheeler** [comment]
I will add examples to show the behavior and how to work around the behavior 

```
function Test-Select {
    [PSCustomObject]@{
        "name"="admin1"
        "children"=[PSCustomObject]@{
            "name"="admin2"
        }
    }
}

$obj = Test-Select

New-Object PSObject -Property @{Country = $obj.name; Children=$obj.Children}
```
