### ISSUE TITLE
Powershell runs on Slackware64 Linux but there are some missing examples

### ISSUE THREAD

**Issue by DoctorWho8** [MicrosoftDocs/PowerShell-Docs#11206]
### Type of issue

Missing information

### Feedback

I run Slackware Linux as a WSL extension. I find it runs better than any of the cited examples of Linux. However there aren't any examples for properly installing it on Slackware 64 Bit on WSL or probably native as well. And the last time I tried to build release from a tarball there I received a complaint from the mechanism that isn't supported and it stopped there. Slackware _is_ supported by its builders and by its community which numbers in the many past several thousands. 

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/community-support?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/community-support.md

### Author

@sdwheeler

### Document Id

7cc88c70-67a3-5455-cddf-d593e263212f

**Comment by sdwheeler** [comment]
We don't support and have not tested PowerShell on Slackware. The Slackware community will have to figure out how to install PowerShell.
