### ISSUE TITLE
Windows 11 Pro Services seem to change to DISABLED only sometimes after reboot (And not caused by any program or manual intervention)

### ISSUE THREAD

**Issue by unixjohnson** [MicrosoftDocs/PowerShell-Docs#11211]
### Type of issue

Other (describe below)

### Feedback

Running WIndows 11 PRO. 
Device name	DISCOVERY
Processor	Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz   3.70 GHz
Installed RAM	128 GB (128 GB usable)
Device ID	CFC6C8A6-4B2E-4B7A-8A64-1F54B143489F
Product ID	00330-80120-74384-AA201
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Pro
Version	23H2
Installed on	‎1/‎1/‎2023
OS build	22631.3737
Experience	Windows Feature Experience Pack 1000.22700.1009.0

After rebooting many of my main services just automatically which to DISABLED. I have to manually and start them (with  no errors when starting manually).  Many of the INTEL services which to DISABLED (including the TPM Provisioning service), my Macrium Service (backups), Bottom line is MANY just flip to DISABLED and I cannot find WHERE or HOW this is doing that. 
In general the system is running fine, but when something does not start I have to go check the services and see if it is started. 
PLEASE HELP. If you need further logs please let me know. 
I opened a case with Microsoft and they have NO HELP at all.  I do NOT want to re-install windows 11, i have too many programs on them and all seems to run well-----its just these services that auto-disable on reboot, but not consistently either, that is VERY ODD. 
Ken Johnson
kjsys1@gmail.com

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-service?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Management/Set-Service.md

### Author

kjsys1@gmail.com 

### Document Id

a19cd922-12e8-69be-c4e4-c97efd42e106

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. This is not a forum for support for Windows.
