### ISSUE TITLE
powershell example is written /labelled for C#

### ISSUE THREAD

**Issue by jermoo** [MicrosoftDocs/PowerShell-Docs#11221]
### Type of issue

Other (describe below)

### Feedback

wrong code

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-validate-an-argument-set?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/developer/cmdlet/how-to-validate-an-argument-set.md

### Author

@sdwheeler

### Document Id

8190c6eb-4eb9-8fac-53d4-3171f9e656d1

**Comment by sdwheeler** [comment]
The documentation is correct.
