### ISSUE TITLE
powershell reserved words

### ISSUE THREAD

**Issue by cfmx** [MicrosoftDocs/PowerShell-Docs#11229]
### Type of issue

Missing information

### Feedback

I can't use "debug" as an alias because it shows this error:
The parameter 'Debug' cannot be specified because it conflicts with the parameter alias of the same name for parameter 'FlgDbg'

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_reserved_words?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Reserved_Words.md

### Author

@sdwheeler

### Document Id

646e1da1-ff09-1b31-d9a7-b1d3f4778d97

**Comment by sdwheeler** [comment]
Debug is not a reserved word. You can use it as an alias for a command. However, it is a reserved parameter name, which is not documented.
