### ISSUE TITLE
'Remove-Service' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ngbrown** [MicrosoftDocs/PowerShell-Docs#11233]
### Type of issue

Missing information

### Feedback

> Remove-Service : The term 'Remove-Service' is not recognized as the name of a cmdlet, function, script file, or         operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.

This was opened previously as an issue in #4510 and was closed, but either the problem regressed or it wasn't fixed.

The `Remove-Service` cmdlet shows even when the PowerShell documentation is open to version 5.1:

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-service?view=powershell-5.1

Also, nowhere on the page does it say that the cmdlet was introduced in PowerShell 6.0.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-service?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Management/Restart-Service.md

### Author

@sdwheeler

### Document Id

1e7502af-2936-848d-dd88-a4a593eddd80

**Comment by ngbrown** [comment]
Didn't notice that the command changed... sorry.

**Comment by sdwheeler** [comment]
Yeah, according to metadata in this issue, you were viewing the help for `Restart-Service`, not `Remove-Service`.
