### ISSUE TITLE
about_Pwsh.md is missing no-loc terms for CommandWithArgs and clarify cmd.exe error

### ISSUE THREAD

**Issue by ninmonkey** [MicrosoftDocs/PowerShell-Docs#11234]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/7ea0d423c0ac5cd471a0c27cfa75784aa1624f2c/reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/7ea0d423c0ac5cd471a0c27cfa75784aa1624f2c/reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md

### Summary

1] The `no-loc` metadata is missing the Command `-CommandWithArgs` and its alias `-cwa`

2] The example given works, but only when it's launched from a `pwsh.exe` but not `cmd.exe` or `powershell.exe`

I thought the `cmd.exe` and `powershell.exe` cases were common enough to be worth mentioning. 

### Details

For completion here's fixes for all 4 cases:

```powershell
# When ran from cmd.exe
# ( the original throws )
pwsh -CommandWithArgs "$args | % { ""arg: $_"" }" arg1 arg2

# from a pwsh session with default values
# ( the original works )
pwsh -CommandWithArgs '$args | % { "arg: $_" }' arg1 arg2

# ran from a  powershell.exe session 5.1
# ( the original outputs blank ) 
pwsh -CommandWithArgs '"$args | % { ""arg: $_"" }"' arg1 arg2

# from a pwsh session using legacy argument passing
# ( the original outputs blank )
$PSNativeCommandArgumentPassing = 'Legacy'
pwsh -CommandWithArgs '$args | % { ""arg: $_"" }' arg1 arg2
```
Tested using `pwsh 7.4.2` and `powershell 5.1`

### Suggested Fix

Maybe **Part 2** should simplify to the `info` link [about_parsing#passing-arguments-that-contain-quote-characters](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.5#passing-arguments-that-contain-quote-characters) 

- The final example with `Legacy` could be assumed knowledge, and left out. 

I included examples because common cases fail. Some show no errors. That could be confusing for users

----

**Part 3** I am not sure if this is correct behavior or possibly a bug? The lack of syntax error is what originally triggered these tests.

```ps1
# start a new pwsh -nop session, then 
$PSNativeCommandArgumentPassing = 'legacy'
pwsh -nop -CommandWithArgs '$args | % { "arg: $_" }' arg1 arg2
# no errors, no output. 
```

**Comment by sdwheeler** [comment]
> **Part 3** I am not sure if this is correct behavior or possibly a bug? The lack of syntax error is what originally triggered these tests.

Please [file an issue][1] with the PowerShell team.

[1]: https://aka.ms/psfeedback
