### ISSUE TITLE
g

### ISSUE THREAD

**Issue by ghost8181aa** [MicrosoftDocs/PowerShell-Docs#11238]
### Type of issue

Typo

### Feedback

pl

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Linux.md

### Author

@sdwheeler

### Document Id

a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd

**Comment by sdwheeler** [comment]
This feedback is not actionable, which is against our [code of conduct](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/CODE_OF_CONDUCT.md).
