### ISSUE TITLE
Clarify that not providing a `-ParameterName` argument implies the `-Native` switch

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#11248]
### Type of issue

Missing information

### Feedback

`Register-ArgumentCompleter`'s parameter design is unusual in that a _switch_ (`-Native`) is situationally _implied_ (whereas switch parameters normally require _opt-in_).

It's worth mentioning that when a `-ParameterName` argument is (possibly accidentally) not supplied, `-Native` is implied, which fundamentally changes the arguments passed to the `-ScriptBlock` argument and can therefore cause confusion; see:

* https://github.com/PowerShell/PowerShell/issues/24031

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md

### Author

@sdwheeler

### Document Id

e471c27f-aa83-321f-541f-878442638e1b

**Comment by ar-std** [comment]
I would additionally consider to remove the switch `-Native` entirely as

```pwsh
Register-ArgumentCompleter
        -CommandName <String[]>
        -ScriptBlock <ScriptBlock>
        [<CommonParameters>]
```

... , nonetheless, already leads the script block parameters as described for `-Native`. And if providing `$ParameterName` in

```pwsh
Register-ArgumentCompleter
        [-CommandName <String[]>]
        -ParameterName <String>
        -ScriptBlock <ScriptBlock>
        [<CommonParameters>]
```

..., `-Native` is not allowed.
