### ISSUE TITLE
Install-Package help missing install location

### ISSUE THREAD

**Issue by juneb** [MicrosoftDocs/PowerShell-Docs#1124]
The help for Install-Package should tell you where the cmdlet installs the package. If it varies, tell where it gets the location. This can go in the description of the Destination parameter (still TBD), but it's important enough to the user to be included in the cmdlet description and the About topic.

**Comment by sdwheeler** [comment]
@JKeithB Where do packages install? The location parameters have changed over versions and it is unclear how they should be used.

**Comment by JKeithB** [comment]
@juneb @sdwheeler so, the short answer for help is "the installation location varies by provider." The longer answer would probably take a change to packagemanagement APIs, and would not apply unless the provider exposes the data. 
The reason the answer  is non-trivial is the extensibility model: PackageManagement doesn't control the installation target, the provider does. To make matters more difficult, if you write a provider there's no easy way to expose the installation target to users or to PackageManagement.
