### ISSUE TITLE
The $IsWindows variable of about_Automatic_Variables documentation suggests value is all Caps. Running "$IsWindows" in pwsh 7.4 shell proves otherwise.

### ISSUE THREAD

**Issue by bigtone58** [MicrosoftDocs/PowerShell-Docs#11258]
### Type of issue

Typo

### Feedback

PowerShell 7.4.3
PS>$IsWindows
True
Note the returned value is mixed case whereas docs imply all Caps. Equivalent variables $IsMacOS and $IsLinux state mixed case. 
My query/suggestion relates to consistency in documentation. Apologies if this is not appropriate

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

### Author

@sdwheeler

### Document Id

14a5f188-a5dd-fb59-1543-e1f03a692e66

**Comment by sdwheeler** [comment]
PowerShell is case-insensitive for variable names. I'm not sure why it was written this way. I will fix case to be consistent throughout.
