### ISSUE TITLE
Repository installation method doesn't work on WSLv2 for Ubuntu 24.04 LTS (Noble Numbat)

### ISSUE THREAD

**Issue by bandwiches** [MicrosoftDocs/PowerShell-Docs#11257]
### Type of issue

Code doesn't work

### Feedback

[Link to section](https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4#installation-via-package-repository-the-package-repository)

Follow the steps and the end result is

```sh
$ sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package powershell
```

### Notes
- Every time I run the `sudo dkpg ...` command it says `File /usr/share/keyrings/microsoft-prod.gpg is missing. Installing...` despite the fact that it is definitely there.
- `Ubuntu 24.04 LTS (Noble Numbat)` is listed under supported versions.

### Full Steps
```sh
$ sudo apt-get update
Hit:1 https://download.docker.com/linux/ubuntu noble InRelease
Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:3 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease
Hit:4 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:5 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists... Done
$ sudo apt-get install -y wget apt-transport-https software-properties-common
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
wget is already the newest version (1.21.4-1ubuntu4.1).
apt-transport-https is already the newest version (2.7.14build2).
software-properties-common is already the newest version (0.99.48).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ source /etc/os-release
$ wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
$ sudo dpkg -i packages-microsoft-prod.deb
(Reading database ... 41311 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.1-ubuntu24.04) over (1.1-ubuntu24.04) ...
Setting up packages-microsoft-prod (1.1-ubuntu24.04) ...
File /usr/share/keyrings/microsoft-prod.gpg is missing. Installing...
$ rm packages-microsoft-prod.deb
$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu noble InRelease
Hit:6 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease
Reading package lists... Done
$ sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package powershell
$ pwsh
Command 'pwsh' not found, but can be installed with:
sudo snap install powershell
$
```

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-ubuntu.md

### Author

@sdwheeler

### Document Id

2405ca72-f9d4-24a5-12a9-304d18a656ce

**Comment by bandwiches** [comment]
[Direct Install](https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4#installation-via-direct-download)

This method also fails due to dependency `libicu`. Installing `libicu` results in`E: Unable to locate package libicu`. Installing `libicu-dev` works, but installing powershell after just results in the same error (lack of dependency libicuXX not installed). The line `sudo apt-get install -f` (or `sudo apt-get --fix-broken install`) just removes the broken powershell installation.

**Comment by bandwiches** [comment]
[Issue on Powershell Repo](https://github.com/PowerShell/PowerShell/issues/23197)

**Comment by sdwheeler** [comment]
We have a docker image but we haven't published packages for 24.04 to packages.microsoft.com. 24.04 has not been tested yet.

**Comment by bandwiches** [comment]
@sdwheeler does this mean that powershell on ubuntu is only supported via docker?

**Comment by bandwiches** [comment]
Thanks for the response. In that case, does it make sense to list Ubuntu 24.04 as supported if it's not actually supported?


![image](https://github.com/user-attachments/assets/46028494-c599-43ad-b08f-5c3c1520b247)

**Comment by sdwheeler** [comment]
Correction - I checked again and we don't have a 24.04 docker image yet either. So this is definitely not supported. I am updating the docs.

**Comment by bandwiches** [comment]
> Correction - I checked again and we don't have a 24.04 docker image yet either. So this is definitely not supported. I am updating the docs.

Thank you!
