### ISSUE TITLE
Set-Alias -Name restrictions incomplete

### ISSUE THREAD

**Issue by PeteMWilson** [MicrosoftDocs/PowerShell-Docs#11265]
### Type of issue

Missing information

### Feedback

The -Name property says the name can be alphanumeric characters with hyphens and not a number, but `%` and `?` are aliases and you can create your own aliases such as e.g. `??`.

What are the actual allowed characters in an alias?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/set-alias?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Utility/Set-Alias.md

### Author

@sdwheeler

### Document Id

ba07180d-8662-1ec9-4db1-134ff273df8e

**Comment by sdwheeler** [comment]
Technically, an alias name can contain any character. The problem arises when you use characters that are interpreted by the PowerShell parser for other purposes.

For example, you CAN create an alias that is a "number" but it can't be invoked as a number, only a string.

```
PS> Set-Alias -Name 123 -Value Get-ChildItem
PS> 123
123
PS> 123 *.md
ParserError:
Line |
   1 |  123 *.md
     |       ~
     | You must provide a value expression following the '*' operator.
PS> & 123 *.md

    Directory: C:\Git\PS-Docs\PowerShell-Docs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/18/2024  8:07 AM            568 CODE_OF_CONDUCT.md
-a---           9/29/2022 11:11 AM            247 CONTRIBUTING.md
-a---           5/18/2024  8:07 AM           4090 README.md
-a---           5/25/2023 12:22 PM           2798 SECURITY.md
```

You can also use punctuation characters like `{}`.

```
PS> Set-Alias -Name '{}' -Value Get-ChildItem
PS> {} *.md
ParserError:
Line |
   1 |  {} *.md
     |      ~
     | You must provide a value expression following the '*' operator.
PS> & {} *.md
PS> & '{}' *.md

    Directory: C:\Git\PS-Docs\PowerShell-Docs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/18/2024  8:07 AM            568 CODE_OF_CONDUCT.md
-a---           9/29/2022 11:11 AM            247 CONTRIBUTING.md
-a---           5/18/2024  8:07 AM           4090 README.md
-a---           5/25/2023 12:22 PM           2798 SECURITY.md

```

But you should stick to alphanumeric characters and dash.
