### ISSUE TITLE
master au to.com

### ISSUE THREAD

**Issue by smhwangd73** [MicrosoftDocs/PowerShell-Docs#11266]
### Type of issue

Missing information

### Feedback

#11262 #11264 #11263 #11262 #11261 
[README.md](https://github.com/user-attachments/files/16201218/README.md)
``

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

@sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by sdwheeler** [comment]
This issue violates our [Code of Conduct](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/CODE_OF_CONDUCT.md).
