### ISSUE TITLE
The -Action param for the Register-EngineEvent cmdlet has position "101" which is nonsensical

### ISSUE THREAD

**Issue by acarl005** [MicrosoftDocs/PowerShell-Docs#11273]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/register-engineevent?view=powershell-7.4&WT.mc_id=ps-gethelp#-action

### Summary

Argument positions should be a 0-based incrementing integer, e.g. 0, 1, 2, etc. In the help pages for `Register-EngineEvent`, there are a couple of params with incorrect positions. `-Action` says position "101" and [`-SourceIdentifier`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/register-engineevent?view=powershell-7.4&WT.mc_id=ps-gethelp#-sourceidentifier) says "100".

### Suggested Fix

Perhaps the positions should be "0" and "1" instead?

**Comment by sdwheeler** [comment]
Those numbers are correct. That is how the cmdlet was written. You can see this by inspecting the command object.

```
PS> $cmd = Get-Command Register-EngineEvent
PS> $cmd.Parameters.Action.Attributes.Position
101
PS> $cmd.Parameters.SourceIdentifier.Attributes.Position
100
```

You can also see this in the source code: https://github.com/PowerShell/PowerShell/blob/666fdb5d5adb31df6dcb5c76d6775dd688fc5269/src/System.Management.Automation/engine/ObjectEventRegistrationBase.cs#L12-L50

**Comment by sdwheeler** [comment]
There is no requirement that the parameter positions start at 0. The position numbers are relative. When PowerShell binds values to parameters by position, the first positional value is bound to the parameter with the lowest position number.

**Comment by acarl005** [comment]
Thanks for clarifying!
