### ISSUE TITLE
UPRYZIN

### ISSUE THREAD

**Issue by upryzin-productions-company** [MicrosoftDocs/PowerShell-Docs#11281]
### Type of issue

Other (describe below)

### Feedback

Music/Media/Marketing
UPRYZIN PRODUCTIONS

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/what-is-windows-powershell?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/what-is-windows-powershell.md

### Author

@sdwheeler

### Document Id

7d1bfc9f-f36e-c002-06a1-e3ea04e42dee

**Comment by sdwheeler** [comment]
This issue violates our [Code of Conduct](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/CODE_OF_CONDUCT.md).
