### ISSUE TITLE
CanStopAndContinue -> CanPauseAndContinue

### ISSUE THREAD

**Issue by StrikerBadger** [MicrosoftDocs/PowerShell-Docs#11299]
### Type of issue

Typo

### Feedback

In the paragraph, where piping order regarding filtering is discussed there is a typo.
In the text it should be **CanPauseAndContinue**, since this is the property which we are actually looking for in the command.

![image](https://github.com/user-attachments/assets/6133ac6d-851a-4892-b8e2-cf448a239e41)

**CanStopAndContinue** -> **CanPauseAndContinue**

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/04-pipelines?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/ps101/04-pipelines.md

### Author

@sdwheeler

### Document Id

f1b73bba-65d3-3d1e-9f73-1f2e2bac9f97

**Comment by mikefrobbins** [comment]
@StrikerBadger, Thank you for catching this typo and logging an issue. I've submitted a PR to correct it.
