### ISSUE TITLE
test-connection -asjob parameter (powershell 5.1)

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#11303]
### Type of issue

Typo

### Feedback

None of this is true.  -AsJob multithread pings all the computers at once, and a regular user can do it, (unless you mean the remote firewall allows ping?)

"-AsJob

To use this parameter, the local and remote computers must be configured for remoting and, on Windows Vista and later versions of the Windows operating system, you must open PowerShell by using the Run as administrator option."

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md

### Author

@sdwheeler

### Document Id

1cf2ccd2-f099-3f92-b698-36311baa0b81

**Comment by sdwheeler** [comment]
Good catch. The description for `-AsJob` was copied from other cmdlets where those restrictions applied. I will get it fixed.
