### ISSUE TITLE
Change in Sample Code mentioned in the document

### ISSUE THREAD

**Issue by DeepanDB** [MicrosoftDocs/PowerShell-Docs#11315]
### Type of issue

Code doesn't work

### Feedback

There is a issue in the "https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.4&source=docs" under "ValueFromRemainingArguments argument" Sample Code.

When I tried to execute the code I have seen this is not giving expected output.

last line of the code need to be modified. 

from "Test-Remainder first one,two"  To "Test-Remainder first one two"

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.4&source=docs

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

### Author

@sdwheeler

### Document Id

09f03e1d-5e99-8ca3-e665-6b50d988231b

**Comment by sdwheeler** [comment]
You were looking at the example and output in the documentation for PowerShell 7.4. Windows PowerShell 5.1 behaves differently, as shown in the 5.1 version of the documentation:
https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-5.1
