### ISSUE TITLE
Add `DefaultDisplayProperty` example to Types.ps1xml

### ISSUE THREAD

**Issue by santisq** [MicrosoftDocs/PowerShell-Docs#11321]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1, 7.2, 7.3, 7.4

### Summary

Add a basic XML example for `DefaultDisplayProperty` in about Types.ps1xml doc.

### Details

[MemberSet][1] section of the doc shows how to add a `DefaultDisplayPropertySet` but for `DefaultDisplayProperty` it isn't as straight forward, the node has to be in a `NoteProperty` and this isn't entirely clear. There are also no examples that can be easily found by googling (tbh wouldn't have found a way if @SeeminglyScience didn't help 😅).

Proposing to add this simple example:

```xml
<Types>
  <Type>
    <Name>SomeNamespace.SomeType</Name>
    <Members>
      <MemberSet>
        <Name>PSStandardMembers</Name>
        <Members>
          <NoteProperty>
            <Name>DefaultDisplayProperty</Name>
            <Value>SomePropertyName</Value>
          </NoteProperty>
        </Members>
      </MemberSet>
    </Members>
  </Type>
</Types>
```

[1]: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_types.ps1xml?view=powershell-7.4#memberset

### Proposed Content Type

Other / Unknown

### Related Articles

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_types.ps1xml?view=powershell-7.4#memberset

**Comment by michaeltlombardi** [comment]
Thanks for reporting this! I'm going to get an example added and I'm also going to add a new example for defining the `DefaultDisplayProperty` to `Update-TypeData` so folks can use it either way.
