### ISSUE TITLE
Docs wrongfully state ARM version is installed automatically using winget

### ISSUE THREAD

**Issue by fabianlupa** [MicrosoftDocs/PowerShell-Docs#11338]
### Type of issue

Other (describe below)

### Feedback

> ```powershell
> winget install --id Microsoft.Powershell --source winget
> winget install --id Microsoft.Powershell.Preview --source winget
> ```
> On Windows systems using X86 or X64 processor, winget installs the MSI package. __On systems using the Arm64 processor, winget installs the Microsoft Store (MSIX) package.__ For more information, see [Installing from the Microsoft Store](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#msstore).

This seems to have been broken with PowerShell 7.4.4.0 where the ARM installers were removed from the winget package. You now need to manually select the Microsoft Store package with winget as a `winget install microsoft.powershell` or the commands listed above will install the x64 version and emulate it on ARM. It seems to stay that way for some months to come:

> FYI, It seems the PowerShell team won't be adding msi arm installers to winget until 7.5 becomes stable (sometime in Q4, usually November).
> > Note: One can also get the .msi installer for arm for this release from the PowerShell Github release ([link](https://github.com/PowerShell/PowerShell/releases/tag/v7.4.3)). We will include them in winget PowerShell releases (i.e stable releases) once PowerShell 7.5 becomes stable. For now PowerShell 7.5 preview's winget includes the .msi for arm.

_Originally posted by @aisgbnok in https://github.com/microsoft/winget-pkgs/issues/164830#issuecomment-2257244469_

I suggest updating the docs. On ARM devices manually specifying the store source seems to be the easiest workaround `winget install PowerShell --source msstore` (thanks @leejy12).
            

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

@sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by sdwheeler** [comment]
Issues like this should be reported in PowerShell source code repository. Please [file an issue][1] with the PowerShell team.

The msixbundle for Arm was missed during the last release. They are aware of the issue and are updating the package now.

[1]: https://aka.ms/psfeedback

**Comment by anamnavi** [comment]
@fabianlupa thanks for catching this, I've created the PR to add an msixbundle installer for arm: https://github.com/microsoft/winget-pkgs/pull/168273

If you want the msi for arm, named `PowerShell-7.4.4-win-arm64.msi`, you can directly download it here: https://github.com/PowerShell/PowerShell/releases/tag/v7.4.4
