### ISSUE TITLE
Could not find any Profile.ps1 in my home folder

### ISSUE THREAD

**Issue by jockep123** [MicrosoftDocs/PowerShell-Docs#11339]
### Type of issue

Typo

### Feedback

No file named Profile.ps1 exists in my home folder. Is there no such file for the default prompt and I have to create a new one?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md

### Author

@sdwheeler

### Document Id

b175960c-519f-f591-0124-b93f36e8a927

**Comment by sdwheeler** [comment]
Yes, the documentation tells you that you need to create one.

![image](https://github.com/user-attachments/assets/8e3aa134-24a6-4c87-a2e4-b5c71b7bd631)
