### ISSUE TITLE
Does Windows PowerShell support `powershell.config.json`?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/PowerShell-Docs#11349]
### Type of issue

Other (describe below)

### Feedback

I tested using `powershell.config.json` for overriding PSModulePath like described here:

* <https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config#PSModulePath>
* <https://github.com/PowerShell/PSResourceGet/issues/1494#issuecomment-2303632544>

I created the file this resolves to in both pwsh.exe and powershell.exe:

```powershell
[System.IO.Path]::Combine(
    [System.IO.Directory]::GetParent($PROFILE.'CurrentUserCurrentHost').'FullName',
    'powershell.config.json'
)
```

With following content:

```json
{
  "PSModulePath": "%LOCALAPPDATA%\\Microsoft\\PowerShell\\Modules2"
}
```

I then loaded `pwsh.exe -NoProfile`:

```powershell
PowerShell 7.4.5
PS C:\Users\olav.birkeland> $env:PSModulePath.Split(';')
C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules2
C:\Program Files\PowerShell\Modules
c:\program files\powershell\7\Modules
C:\Users\olav.birkeland\scoop\modules
C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules
C:\Users\olav.birkeland\OneDrive - Innovasjon Norge\Documents\PowerShell\Modules

C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PS C:\Users\olav.birkeland>
```

But with `powershell.exe` it does not seem to work:

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\olav.birkeland> $env:PSModulePath.Split(';')
C:\Users\olav.birkeland\scoop\modules
C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules
C:\Users\olav.birkeland\OneDrive - Innovasjon Norge\Documents\PowerShell\Modules

C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PS C:\Users\olav.birkeland>
```

I then found following package on PowerShell Gallery:

* <https://www.powershellgallery.com/packages/PowerProfile.Commands/1.0.0-alpha2/Content/PowerProfile.Commands.PSConfig.psm1>

It has a check that throws and error if not PowerShell Core:

```powershell
if (-Not $IsCoreCLR) {
    throw 'Windows PowerShell does not use powershell.config.json configuration files.'
}
```

So, it seems to me Windows PowerShell / powershell.exe does not support powershell.config.json? 🤔

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-7.4#psmodulepath

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md

### Author

@sdwheeler

### Document Id

91d350cb-6ac3-5a2e-b959-a9c8c1629c12

**Comment by sdwheeler** [comment]
That's correct. Windows PowerShell doesn't support powershell.config.json. That's why the about_PowerShell_Config article doesn't exist in the 5.1 documentation. You were looking at the documentation for PowerShell 7.4.

**Comment by o-l-a-v** [comment]
@sdwheeler Would be nice with a notice in the doc saying that 5.1 doesn't support it.

But thanks for the confirmation anyway. 🙂
