### ISSUE TITLE
Wrong examples using "-Argument"

### ISSUE THREAD

**Issue by apsoft-original** [MicrosoftDocs/PowerShell-Docs#11343]
### Type of issue

Typo

### Feedback

All samples all over the internet are wrong because the arguments name is "Arguments" ("s" on end) and not "Argument"

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-wmiinstance?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Management/Set-WmiInstance.md

### Author

@sdwheeler

### Document Id

f25f1463-83d9-ae55-9abd-7454bd40956d

**Comment by sdwheeler** [comment]
Using `-Argument` works because PowerShell only needs enough characters in the parameter name to uniquely identify the parameter. So `-Ar` would be the minimum. However, for accuracy, I will fix the examples.
