### ISSUE TITLE
Error caused by long samaccountname

### ISSUE THREAD

**Issue by yuzhaninan** [MicrosoftDocs/PowerShell-Docs#11346]
### Type of issue

Other (describe below)

### Feedback

```
failed! Error: Failed to join computer "<Computer Name>" from its current workgroup "WG" to domain
"<Domain Name>", error message: Group name not found.
```
Problem appears in process of re-using computer account (with new computer account no problem revealed) (OUPath parameter was determined)

Reason found
Account name length in credential was longer then 20
Replacing with UserPrincipalName wa helpfull.

additionaly can`t find error description to error  "Group name not found"

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/add-computer?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md

### Author

@sdwheeler

### Document Id

930572e7-c0e2-0885-172f-1b8b4a085f64

**Comment by sdwheeler** [comment]
This cmdlet is working as designed. It only exists in Windows PowerShell 5.1. 

If there is a problem that needs to be addressed you need to report it to the Windows product team. Use the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
