### ISSUE TITLE
move-item -destination MUST be a full path

### ISSUE THREAD

**Issue by awsles** [MicrosoftDocs/PowerShell-Docs#11369]
### Type of issue

Missing information

### Feedback

The powershell v5.1 documentation for the **-Destination** parameter for **move-item** implies that if you put a new name, the file is simply renamed. Unfortunately, it will actually move the file to your default user folder.
### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/move-item?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Management/Move-Item.md

### Author

@sdwheeler

### Document Id

858bf205-cd5f-82c5-82c6-f6d7e4fe6a28

**Comment by sdwheeler** [comment]
That's not what the documentation says:

> **-Destination**
>
> Specifies the path to the location where the items are being moved. The default is the current
> directory. Wildcards are permitted, but the result must resolve to a single location.
>
> To rename the item being moved, specify a new name in the value of the Destination parameter.

Note that it says that the default is the current directory. You can see this in the verbose output.


```
PS D:\temp\lesw> New-Item -Path "$env:USERPROFILE\Desktop\TEST\test.txt" -ItemType "File" -Force


    Directory: C:\Users\USER\Desktop\TEST


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         8/30/2024   9:05 AM              0 test.txt


PS D:\temp\lesw> Move-Item -Path "$env:USERPROFILE\Desktop\TEST\test.txt" -Destination test2.txt -Verbose -Confirm

Confirm
Are you sure you want to perform this action?
Performing the operation "Move File" on target "Item: C:\Users\USER\Desktop\TEST\test.txt Destination:
D:\temp\lesw\test2.txt".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
PS D:\temp\lesw> dir


    Directory: D:\temp\lesw


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         8/30/2024   9:05 AM              0 test2.txt
```
