### ISSUE TITLE
error   At line:1 char:1

### ISSUE THREAD

**Issue by oSlavivna** [MicrosoftDocs/PowerShell-Docs#11388]
### Type of issue

Code doesn't work

### Feedback

.....................nextjs-dashboard> **pnpm dev**
pnpm : File C:\Users\kykys\AppData\Roaming\npm\pnpm.ps1 cannot be loaded because running scripts is disabled on this system. For mo
re information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
**At line:1 char:1
+ pnpm dev
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess**
    
    how fix it?

### Page URL

https://learn.microsoft.com/uk-ua/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

### Author

@sdwheeler

### Document Id

9a273f6f-7dba-1614-cc84-f44f877c1351

**Comment by oSlavivna** [comment]
and this

  Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       **Undefined**
 LocalMachine       Undefined

**Comment by sdwheeler** [comment]
Try setting your Execution Policy to `RemoteSigned`. If you need further assistance, I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by oSlavivna** [comment]
Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser 
seems to have worked
--------------------

 But I don't understand where the /trace path came from
<img width="656" alt="Знімок екрана 2024-09-04 163835" src="https://github.com/user-attachments/assets/0ef2d2e5-bc0b-4ae6-99d5-2a121dae1ff4">
