### ISSUE TITLE
Need support

### ISSUE THREAD

**Issue by Moazzem-Hossain-pixel** [MicrosoftDocs/PowerShell-Docs#11403]
### Type of issue

Missing information

### Feedback

I will be surprised if you can help me in this regard

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/community/community-support?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/community/community-support.md

### Author

@sdwheeler

### Document Id

364e4b5c-219a-3031-3074-9958d17ea37b

**Comment by michaeltlombardi** [comment]
The [Microsoft Open Source Code of Conduct][1], which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help provide a welcoming and inspiring community for all. The content of this issue appears to be out of sync with the code of conduct, so we have closed it.

[1]: https://opensource.microsoft.com/codeofconduct/
