### ISSUE TITLE
Need support for PowerShell

### ISSUE THREAD

**Issue by Moazzem-Hossain-pixel** [MicrosoftDocs/PowerShell-Docs#11402]
### Type of issue

Other (describe below)

### Feedback

I need support for installing PowerShell

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/using-predictors?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/shell/using-predictors.md

### Author

@sdwheeler

### Document Id

a7b1b317-5ff7-e40c-b573-2a7642663324

**Comment by michaeltlombardi** [comment]
This repository is for documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
