### ISSUE TITLE
Wrong Translation in german

### ISSUE THREAD

**Issue by hwschneiders** [MicrosoftDocs/PowerShell-Docs#11415]
### Type of issue

Other (describe below)

### Feedback

Sentence in german:"Beachten Sie, dass der Inhalt einer SecureString pro [DotNet](https://learn.microsoft.com/de-de/dotnet/api/system.security.securestring#remarks) nicht auf Windows-Systemen verschlüsselt ist." Which is highlighted has the oposite meaning of the english orginial: "Note that per [DotNet](https://learn.microsoft.com/en-us/dotnet/api/system.security.securestring#remarks), the contents of a SecureString are not encrypted on non-Windows systems. "
"aber nicht auf Windows-System verschlüßelt" is more or less the oposite of: "not encrypted on non-Windows systems." Please fix it, thnak you

### Page URL

https://learn.microsoft.com/de-de/powershell/module/microsoft.powershell.security/convertto-securestring?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Security/ConvertTo-SecureString.md

### Author

@sdwheeler

### Document Id

797c675b-084b-7d9c-f397-51d0d990dc03

**Comment by sdwheeler** [comment]
@hwschneiders Thanks for the report. I have forwarded this information to our translation team. They will have to fix it in our translation engine.
