### ISSUE TITLE
-Force implementation on ShouldProcess page should be reviewed and changed.

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/PowerShell-Docs#11418]
### Type of issue

Code doesn't work

### Feedback

```powershell
function Test-ShouldProcess {
    [CmdletBinding(
        SupportsShouldProcess,
        ConfirmImpact = 'High'
    )]
    param(
        [Switch]$Force
    )

    if ($Force -and -not $Confirm){
        $ConfirmPreference = 'None'
    }

    if ($PSCmdlet.ShouldProcess('TARGET')){
        Write-Output "Some Action"
    }
}
```

According to my testing `$Confirm` is never present

```powershell
function Test-ShouldProcess {
    [CmdletBinding(
        SupportsShouldProcess,
        ConfirmImpact = 'High'
    )]
    param(
        [Switch]$Force
    )

    Write-Verbose "`$DebugPreference: $DebugPreference"
    Write-Verbose "`$ConfirmPreference: $ConfirmPreference"
    Write-Verbose "`$Confirm: $Confirm"
    Write-Verbose "`$Confirm: $($null -eq $Confirm ? "NULL": "NONNULL")"

    if ($Force -and -not $Confirm){
        Write-Verbose "Changing `$ConfirmPreference"
        $ConfirmPreference = 'None'
    } else {
        Write-Verbose "XXXX"
    }

    Write-Verbose "`$DebugPreference: $DebugPreference"
    Write-Verbose "`$ConfirmPreference: $ConfirmPreference"
    Write-Verbose "`$Confirm: $Confirm"
    Write-Verbose "`$Confirm: $($null -eq $Confirm ? "NULL": "NONNULL")"

    if ($PSCmdlet.ShouldProcess('TARGET')){
        Write-Output "Some Action"
    }
}
```

Earlier ticket/work:
* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6948 / https://github.com/PowerShell/PowerShell/issues/14294
  * => removal of $Confirm: https://github.com/MicrosoftDocs/PowerShell-Docs/commit/00e88da4cb0789f46018b4ee28e59303f6c6b1dc
* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9007
  * => Usage of $Confirm was added back: https://github.com/MicrosoftDocs/PowerShell-Docs/commit/e5fadd7284ad30716bd6dd58924533b1e66ec30e

-------

The example is really hard to understand and it does not work with strict mode.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md

### Author

@sdwheeler

### Document Id

530b7644-3211-0f7c-3c63-d9959a72f541

**Comment by sdwheeler** [comment]
This code works around the Strict Mode issue and should make more sense. The point of testing for `$Confirm` is to cover the case where the user actually supplies the parameter. By using `$PSBoundParameters` you can handle the parameter even though the `$Confirm` variable doesn't exist.

```powershell
function Test-ShouldProcess {
    [CmdletBinding(
        SupportsShouldProcess,
        ConfirmImpact = 'High'
    )]
    param(
        [Switch]$Force
    )

    if (-not $PSBoundParameters.ContainsKey('Confirm')) {
        Write-Verbose "Setting `$Confirm = $false"
        $Confirm = $false
    } else {
        Write-Verbose "Setting `$Confirm = $($PSBoundParameters.Confirm)"
        $Confirm = $PSBoundParameters.Confirm
    }

if ($Force -and -not $Confirm){
        $ConfirmPreference = 'None'
    }

if ($PSCmdlet.ShouldProcess('TARGET')){
        Write-Output "Some Action"
    }
}
```

**Comment by jikuja** [comment]
That's new really pedantic and correct, although I think that checking if user has passed `-Confirm` might be redundant if `ShouldProcess` handles checking `-Confirm` and `-Confirm:$false` internally:

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/MshCommandRuntime.cs#L2974-L3000


Testing:

```Powershell
function Test-ShouldProcess {
    [CmdletBinding(
        SupportsShouldProcess,
        ConfirmImpact = 'High'
    )]

    $ConfirmPreference = 'None'
    if ($PSCmdlet.ShouldProcess('TARGET')){
        Write-Output "Some Action"
    }
}
```

Results:

```
$ConfirmPreference="Medium" ; Test-ShouldProcess

Confirm
Are you sure you want to perform this action?
Performing the operation "Test-ShouldProcess" on target "TARGET".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): s
```

Is there some other use cases to do `$ConfirmPreference = 'None'` when `$Force -and -not $Confirm` I just don't see from the code example?

**Comment by sdwheeler** [comment]
As you point out, `ShouldProcess()` tests `-Confirm` for us so this would be the simpler way of implementing `-Force`. This would prefer the value of `-Confirm` over `-Force` when both are provided, but still allows using `-Force` to replace the longer form `-Confirm:$false`.

```powershell
function Test-ShouldProcess {
    [CmdletBinding(
        SupportsShouldProcess,
        ConfirmImpact = 'High'
    )]
    param(
        [switch]$Force
    )

    if ($Force -and -not $PSBoundParameters.ContainsKey('Confirm')) {
        $ConfirmPreference = 'None'
    }

    if ($PSCmdlet.ShouldProcess('TARGET')) {
        Write-Output "Some Action"
    }
}
```

**Comment by jikuja** [comment]
>  still allows using -Force to replace the longer form -Confirm:$false.

This is the use case I could not see by reading the example code. Might be worth of adding into documentation.
