### ISSUE TITLE
fotos

### ISSUE THREAD

**Issue by Mikyback** [MicrosoftDocs/PowerShell-Docs#11410]
### Type of issue

Code doesn't work

### Feedback

[Backup-codes-mikyback10 - Acceso directo.lnk.zip](https://github.com/user-attachments/files/16956634/Backup-codes-mikyback10.-.Acceso.directo.lnk.zip)
![Screenshot_20240520_151327_com google android gm](https://github.com/user-attachme
[BreeZip.lnk.pdf](https://github.com/user-attachments/files/16956640/BreeZip.lnk.pdf)
nts/assets/91547bcc-4cc6-428f-a3d3-9257029bbc16)

[https   photos..txt](https://github.com/user-attachments/files/16956635/https.pho
[zeep.pdf](https://github.com/user-attachments/files/16956637/zeep.pdf)
tos.txt)

### Page URL

https://learn.microsoft.com/es-es/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

### Author

@sdwheeler

### Document Id

c138e6a8-fd80-bd64-25ac-24e774e09421

**Comment by sdwheeler** [comment]
Contributions to this repository should follow its [contributing guidelines](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/7637bee9a75396d32ca912175177d03ba48018e3/CONTRIBUTING.md), [security policy](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/7637bee9a75396d32ca912175177d03ba48018e3/SECURITY.md), and [code of conduct](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/7637bee9a75396d32ca912175177d03ba48018e3/CODE_OF_CONDUCT.md).

We don't accept unsafe attachments like this.

**Comment by Mikyback** [comment]
![1713777045188](https://github.com/user-attachmhttps://1drv.ms/f/c/6cb45f46f0b2efa5/EvVIduopYLZDva804iJQv3oB4fYZ0RuP0Je78w2M6LNX0Aents/assets/14fed340-0f0b-4923-9baf-611af5669861)

**Comment by Mikyback** [comment]
[System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
