### ISSUE TITLE
Connect-PowerBIServiceAccount -Credential. Return a error when it comes to connecting to PowerBI

### ISSUE THREAD

**Issue by gianstanco** [MicrosoftDocs/PowerShell-Docs#11423]
### Type of issue

Code doesn't work

### Feedback

**This is the error that appears every time you try to create a connection to PowerBI Server from Linux Redhat 8.**

"_Connect-PowerBIServiceAccount: One or more errors occurred. (User and password authentication is not supported in .NET Core or with DeviceCode authentication.)_"

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/install-rhel?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-rhel.md

### Author

@sdwheeler

### Document Id

53869d01-6b5a-9502-079c-516836f213e3

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You are describing a possible issue with a command in the [MicrosoftPowerBIMgmt.Profile](https://learn.microsoft.com/powershell/module/microsoftpowerbimgmt.profile/?view=powerbi-ps) module. You can leave feedback on the [Connect-PowerBIServiceAccount](https://learn.microsoft.com/powershell/module/microsoftpowerbimgmt.profile/connect-powerbiserviceaccount?view=powerbi-ps) page or open a support incident with the PowerBI support team.
