### ISSUE TITLE
If Windows PowerShell is a legacy product, why doesn't Windows replace it with PowerShell?

### ISSUE THREAD

**Issue by rilakuma123** [MicrosoftDocs/PowerShell-Docs#11431]
### Type of issue

Missing information

### Feedback

This article taught me a lot and the further reading section is great but it made me wonder why Windows ships a legacy product. 

I always saw the message telling you to "Install the latest PowerShell for new features and improvements" and wondered why it didn't just update automatically or with Windows. 

People still use CMD, mostly because they don't know any better. Telling those people that there are two PowerShells is sure to confuse them. 

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/what-is-windows-powershell?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/what-is-windows-powershell.md

### Author

@sdwheeler

### Document Id

7d1bfc9f-f36e-c002-06a1-e3ea04e42dee

**Comment by sdwheeler** [comment]
PowerShell isn't allowed to ship in Windows because PowerShell has a different support lifecycle. PowerShell support is based on the lifecycle of .NET, which is about 3 years. The Windows support lifecycle is about 10 years. To be included in Windows, you have to have the same support lifecycle.

**Comment by rilakuma123** [comment]
Thanks. Appreciate the answer. I don't quite fully understand why it's not something that can be updated automatically like Microsoft Edge though. And why is that information unfit for the article?

**Comment by sdwheeler** [comment]
![image](https://github.com/user-attachments/assets/8491fc24-d511-4732-baf0-0600ab814f4e)

**Comment by rilakuma123** [comment]
In my time helping people, I've had them use Windows PowerShell to do certain actions. Something people often point out is the "install the latest PowerShell" message. I always tell them to ignore it and proceed. It'd be nice if I could refer them to a page that explained all this to them. This page is very close but doesn't answer the aforementioned questions. I wish you at least edited in the information you gave me.
