### ISSUE TITLE
Incorrect Overload definition for $PSCmdlet.ShouldProcess

### ISSUE THREAD

**Issue by StewartRyanSony** [MicrosoftDocs/PowerShell-Docs#11430]
### Type of issue

Code doesn't work

### Feedback

This document says that the third overload option for $PSCmdlet.ShouldProcess support 3 parameters 

`"## $PSCmdlet.ShouldProcess('MESSAGE','TARGET','OPERATION')". `

When I attempt to run a function using this overload I get the error, "Cannot find an overload for "ShouldProcess" and the argument count: "3"."

I am running PowerShell Core, Version 7.4.5

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md

### Author

@sdwheeler

### Document Id

530b7644-3211-0f7c-3c63-d9959a72f541

**Comment by StewartRyanSony** [comment]
Nevermind. This was my mistake. 
This is the first time I have attempted to use this overload and one of the parameters was not a string. 
I didn't find anything that would suggest checking that all the parameters were strings, but I figured it out my self.
Please disregard

**Comment by StewartRyanSony** [comment]
Nevermind. This was my mistake.
This is the first time I have attempted to use this overload and one of the parameters was not a string.
I didn't find anything that would suggest checking that all the parameters were strings, but I figured it out my self.
Please disregard

**Comment by sdwheeler** [comment]
Here is the documentation for the API - https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.shouldprocess?view=powershellsdk-7.4.0#system-management-automation-cmdlet-shouldprocess(system-string-system-string-system-string)
