### ISSUE TITLE
package powershell not found in microsoft repo

### ISSUE THREAD

**Issue by SomeMichael** [MicrosoftDocs/PowerShell-Docs#11432]
### Type of issue

Code doesn't work

### Feedback

I tried method 1: Install via repo
but:

```
$ sudo apt-get install -y powershell
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
E: Paket powershell kann nicht gefunden werden.

```
Checking repo using (found [here](https://www.linuxuprising.com/2018/11/how-to-list-all-packages-in-repository.html))
`grep ^Package /var/lib/apt/lists/packages.microsoft.com_ubuntu_24.04_prod_dists_noble_main_binary-arm64_Packages | awk '{print $2}' | sort -u`

lists
```
aadsshlogin
aadsshlogin-selinux
azcopy
aziot-edge
aziot-identity-service
blobfuse2
libmsquic
moby-buildx
moby-cli
moby-compose
moby-containerd
moby-engine
moby-runc
moby-tini
msodbcsql18
msopenjdk-11
msopenjdk-17
msopenjdk-21
mssql-tools18
```

no powershell???

So, I will try method 2...

### Page URL

https://learn.microsoft.com/de-de/powershell/scripting/install/install-ubuntu?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-ubuntu.md

### Author

@sdwheeler

### Document Id

2405ca72-f9d4-24a5-12a9-304d18a656ce

**Comment by sdwheeler** [comment]
https://learn.microsoft.com/de-de/powershell/scripting/install/install-ubuntu?view=powershell-7.4#supported-versions

Ubuntu 24.04 isn't supported yet.

Microsoft unterstützt PowerShell, bis [PowerShell das Ende des Supports](https://learn.microsoft.com/de-de/powershell/scripting/install/powershell-support-lifecycle) erreicht oder die Version von [Ubuntu das Ende des Supports erreicht](https://endoflife.date/ubuntu).

Installationspaketdateien (.deb) sind auch über https://packages.microsoft.com/ verfügbar.

Docker-Images mit PowerShell 7.2, PowerShell 7.4 und PowerShell 7.5-preview für x64 und Arm32 sind in der [Microsoft-Artefaktregistrierung](https://mcr.microsoft.com/product/powershell/tags) für die folgenden Ubuntu-Versionen verfügbar:

Ubuntu 22.04 (Jammy Jellyfish): Der Betriebssystemsupport endet am 01.04.2027.
Ubuntu 20.04 (Focal Fossa): Der Betriebssystemsupport endet am 02.04.2025.
