### ISSUE TITLE
about_Calculated_Properties does not mention expression variables being read-only

### ISSUE THREAD

**Issue by caliniaru** [MicrosoftDocs/PowerShell-Docs#11440]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_calculated_properties?view=powershell-7.4

### Summary

Take this example:

```powershell
function TestExpression
{
    $x = 0;
    Get-Process | Select-Object @{Name = "ProcessID"; Expression = {$_.Id; $x ++;}}
    $x;
}

TestExpression;
```

The output is:

>     1112
>     2884
>     5256
>     0

There is no mention of variables inside `expression` being **read-only**.

**Comment by michaeltlombardi** [comment]
The problem you're running into isn't that variables inside of expressions are read-only, but that you're trying to modify a variable in a child scope. The value of the expression is a scriptblock, and runs in a child scope. In [`about_Scopes`][01], the documentation explains:

> Items that you create or change in a child scope don't affect the parent scope, unless you explicitly specify the scope when you create the items.

It's also worth noting that if you want to perform an action for every item output by a cmdlet, the idiomatic option is to use the [`ForEach-Object`] cmdlet (or a `foreach` loop). Reusing your example, I might write something like:

```powershell
function Test-Example {
    [CmdletBinding()]
    param()
    
    begin {
        $processCount = 0
    }
    
    process {
        Get-Process pwsh | ForEach-Object {
            # Increment the count
            $processCount++
            # Output the item to the pipeline
            [pscustomobject]@{ ProcessID = $_.Id }
        }
    }
    
    end {
        Write-Verbose "Process count: $processCount"
    }
}

Test-Example -Verbose
```

```Output
VERBOSE: Process count: 2

ProcessID
---------
    12388
    17912
```

[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_scopes#parent-and-child-scopes

**Comment by caliniaru** [comment]
Thank you for the prompt response.
