### ISSUE TITLE
The command to create the profile for powershell fails `New-Item -ItemType File -Path $PROFILE -Force` 

### ISSUE THREAD

**Issue by skrabbe001** [MicrosoftDocs/PowerShell-Docs#11441]
### Type of issue

Code doesn't work

### Feedback

The command for creating a profile does not work, when the PowerShell directory does not exist, which it does not when installing the current version of PowerShell:

```
PS C:\Windows\System32> New-Item -ItemType File -Path $PROFILE -Force
New-Item: Could not find a part of the path 'C:\Users\JonesSmith\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'.
```

Why does it not work?

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/creating-profiles?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/shell/creating-profiles.md

### Author

@sdwheeler

### Document Id

c3b21d50-9ab5-ad3c-316a-330a460a5dd0

**Comment by skrabbe001** [comment]
I just created the PowerShell directory and even when all the folders in the path exists, the command still fails.

**Comment by skrabbe001** [comment]
Tested both as admin and as current user.

**Comment by skrabbe001** [comment]
Here are the access rights to the folder:
```
PS C:\Windows\System32> get-acl "C:\Users\JohnSmith\Documents\PowerShell"

    Directory: C:\Users\JohnSmith\Documents

Path       Owner              Access
----       -----              ------
PowerShell AzureAD\skrabbe001 NT AUTHORITY\SYSTEM Allow  FullControl…

PS C:\Windows\System32> (get-acl "C:\Users\JohnSmith\Documents\PowerShell").Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : AzureAD\JohnSmith
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None
```

**Comment by michaeltlombardi** [comment]
This repository is for documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by skrabbe001** [comment]
So if the command in your doc does not work, its not a doc issue?
