### ISSUE TITLE
Feedback Expand-Archive creates folder in system temp called 

### ISSUE THREAD

**Issue by kingma-sbw** [MicrosoftDocs/PowerShell-Docs#11450]
### Type of issue

Missing information

### Feedback

Using Expand-Archive creates two folders in system/temp
remoteIpMoProxy_MicrosoftPowerShellArchive_1.0.1.0_localhost_guid and
remoteIpMoProxy_MicrosoftPowerShellUtility_3.1.0.0_localhost_guid

please elaborate why these folders are created and what the proper ways are to clean them up

**Comment by SteveL-MSFT** [comment]
Perhaps we should consider also documenting that temp scripts get created by PowerShell to test if the system is in lockdown mode as that also comes up.

I think in general, we should just inform users that these temp files (for both cases) are normal and created by PowerShell.

**Comment by sdwheeler** [comment]
Related to https://github.com/PowerShell/PowerShell/issues/24355
