### ISSUE TITLE
Add MD058 rule handling - Blanks around tables

### ISSUE THREAD

**Issue by ArieHein** [MicrosoftDocs/PowerShell-Docs#11459]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/date-and-time-parameters?view=powershell-7.4

### Summary

There are some files across the repo that trigger the MD058 - Blanks around tables rule.
Example in the link.

### Details

When opening the files in VSCode with the markdownlint extension, it reports the MD058 rule issue.
It should probably be added to the markdownlint yaml file to trigger in PR/Build.
I can create a pull request for each single file with that occurrence, but i leave you the configuration of the yaml file.

**Comment by sdwheeler** [comment]
@ArieHein Thanks for pointing this out. There were a couple of new rules that I was not aware of.

We don't use markdownlint in the PR/Build but I added the new rules to our yaml file.
