### ISSUE TITLE
installing /running codes

### ISSUE THREAD

**Issue by FARICJH59** [MicrosoftDocs/PowerShell-Docs#11465]
### Type of issue

Other (describe below)

### Feedback

can not follow paths shows error all the time

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/microsoft-update-faq?view=powershell-7.4&source=recommendations

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/microsoft-update-faq.yml

### Author

@sdwheeler

### Document Id

71fe8e11-21b9-1b98-3529-46553d57127b

**Comment by ArieHein** [comment]
Links on that page work ok on my side. Can you be more specific, as i don't see an issue atm

**Comment by sdwheeler** [comment]
You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
