### ISSUE TITLE
default module locations for Windows PowerShell 5.1

### ISSUE THREAD

**Issue by Gatperst9** [MicrosoftDocs/PowerShell-Docs#11467]
### Type of issue

Typo

### Feedback

Under, "The default locations for Windows PowerShell 5.1 are different from PowerShell 7." it says
"Modules installed in the AllUsers scope are stored in $env:ProgramFiles\PowerShell\Modules."
I believe that should be
$env:ProgramFiles\WindowsPowerShell\Modules

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md

### Author

@sdwheeler

### Document Id

8970be92-55a4-e26f-4d08-7dac88e773e7

**Comment by sdwheeler** [comment]
@Gatperst9 Thanks for the find.
