### ISSUE TITLE
better explanation

### ISSUE THREAD

**Issue by ruderod** [MicrosoftDocs/PowerShell-Docs#11473]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.3

### Summary

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-process?view=powershell-7.4
does not show much on the large objects returned by "get-process select-object *"
What do some of these mean?   It should be easy to tell a kernal/service process from a user process.  It is easy on unix,  not so much here.    Please add some detail to the objects rreturned.   This is very important powershell command (some would argue the most important!).  Wearing my Security hat,  oh yeah,   says for sure!

### Details

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-process?view=powershell-7.4
does not show much on the large objects returned by "get-process select-object *"
What do some of these mean?   It should be easy to tell a kernal/service process from a user process.  It is easy on unix,  not so much here.    Please add some detail to the objects rreturned.   This is very important powershell command (some would argue the most important!).  Wearing my Security hat,  oh yeah,   says for sure!

### Proposed Content Type

Cmdlet Reference

### Proposed Title

fix the docs

**Comment by sdwheeler** [comment]
The OUTPUTS section of the article links to the documentation for each of the types returned.

![image](https://github.com/user-attachments/assets/a23c8021-b7a7-401f-81fc-87e087d83210)
