### ISSUE TITLE
Wrong PowerShell version mentioned in version-specific docs-page

### ISSUE THREAD

**Issue by transmokopter** [MicrosoftDocs/PowerShell-Docs#11475]
### Type of issue

Typo

### Feedback

This article talks a lot about Windows PowerShell. But I have selected version PowerShell 7.4 (LTS), so I think this will need an overhaul to either reference the correct version, or to make whatever in the article is version-independent not mention specific PowerShell versions at all.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/terminating-errors?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/developer/cmdlet/terminating-errors.md

### Author

@sdwheeler

### Document Id

e03e19b5-a1d2-ca75-c69a-5717bd08a269

**Comment by michaeltlombardi** [comment]
The conceptual documentation isn't version specific - the version picker only applies to the reference documentation.

**Comment by transmokopter** [comment]
I don't understand. If the documentation is supposed to be conceptual, why is it referring specifically to Windows PowerShell?
