### ISSUE TITLE
Start-Service.md says "might not have permission" but doesn't say how to give permission

### ISSUE THREAD

**Issue by BenAveling** [MicrosoftDocs/PowerShell-Docs#11470]
### Type of issue

Missing information

### Feedback

The document currently says "If a command does not work correctly, you might not have the required permissions." 

Which is true, but not useful, because it's not obvious how to give it the right permissions. 

The usual "Start-Process -Verb runAs" doesn't quite work, because this is a commandlet.

The simplest thing I could find that sort of worked is to start-process powershell.

e.g.

`Start-Process -verb runas PowerShell "restart-service spooler" -WindowStyle hidden -wait`

And even that's not ideal, because any output from restart-service is lost. (Not having "-WindowStyle hidden" doesn't help, because the window exits as soon as the restart-service finishes.)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-service?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Management/Start-Service.md

### Author

@sdwheeler

### Document Id

c6a4f863-30eb-83e6-4f24-6d24ab1fa638

**Comment by sdwheeler** [comment]
Managing the permissions of a service is a Windows problem, not a PowerShell problem.

By default, only members of the Administrators group can start, stop, pause, resume, or restart a service. If you are a member of the Administrators group, you need to run `Start-Service` from an elevated PowerShell session. Use the **Run as Administrator** option to start PowerShell.

![image](https://github.com/user-attachments/assets/81dd2e58-0549-4bb9-8d73-b09741eb6efd)

If you are not a member of the Administrators group then you need an administrator to add you to the group or grant you permissions on the service.

The following article explains how to grant permissions to manage a service.

https://learn.microsoft.com/troubleshoot/windows-server/windows-security/grant-users-rights-manage-services
