### ISSUE TITLE
Admin ctl 

### ISSUE THREAD

**Issue by FARICJH59** [MicrosoftDocs/PowerShell-Docs#11471]
### Type of issue

Other (describe below)

### Feedback

There is always an Error  message when I try to install dependence on my Admin ctl showing not found.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/community/community-support?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/community/community-support.md

### Author

@sdwheeler

### Document Id

364e4b5c-219a-3031-3074-9958d17ea37b

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. Post you questions to one of the support forums listed on the [Community Support](https://learn.microsoft.com/en-us/powershell/scripting/community/community-support) page.
