### ISSUE TITLE
Clarify extensions used for filtering `Get-Command -CommandType Application`

### ISSUE THREAD

**Issue by santisq** [MicrosoftDocs/PowerShell-Docs#11528]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-7.4#-commandtype

### Summary

`-CommandType Application` states that the cmdlet includes `.txt`, `.exe`, and `.dll` files however this isn't accurate. The extensions used for filtering are those included in `Environment.GetEnvironmentVariable('PATHEXT')` after [some digging][1].

[1]: https://stackoverflow.com/a/79172045/15339544

### Suggested Fix

`Application`: Gets non-PowerShell files in paths listed in the __Path__ environment variable (`$env:Path`), including those files with extensions in __PATHEXT__ environment variable (`$env:PATHEXT`). For more information about the Path environment variable, see [about_Environment_Variables](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4).

**Comment by sdwheeler** [comment]
Good catch. I think that was supposed to be `.bat` not `.txt`. But you are right, it is the extensions in `$env:PATHEXT`.
