### ISSUE TITLE
One more Execution Policy

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/PowerShell-Docs#11520]
### Type of issue

Missing information

### Feedback

It appears that there is an undocumented execution policy. Or can any string be used as Execution Policy ?

I have seen the following code fragment mentioned in various places "PowerShell.exe -ExecutionPolicy BypassInstall-Script -name Get-WindowsAutopilotInfo -Force". First found in "Windows 11 for Enterprise Administrators".

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

### Author

@sdwheeler

### Document Id

cfa0b0d5-be1f-b9d2-533d-61bfa6051292

**Comment by sdwheeler** [comment]
What value do you think is undocumented? `Bypass` is documented. There are no undocumented values. If you found different information in a book not published by Microsoft you need to report the issue to the book publisher.
