### ISSUE TITLE
i can't update my powershell

### ISSUE THREAD

**Issue by MuhammadNouman07** [MicrosoftDocs/PowerShell-Docs#11540]
### Type of issue

Other (describe below)

### Feedback

i can't update my powershell , i try my best but all vain.

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#supported-versions-of-windows

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

@sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
