### ISSUE TITLE
Power Shell

### ISSUE THREAD

**Issue by otaktn** [MicrosoftDocs/PowerShell-Docs#11544]
### Type of issue

Code doesn't work

### Feedback

Instalation Powershell 7 failed - MSI installation
![Clipboard01](https://github.com/user-attachments/assets/31cdbebd-7db4-4de8-ac22-e171a109851f)

### Page URL

https://learn.microsoft.com/cs-cz/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#supported-versions-of-windows

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

@sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by otaktn** [comment]
![Clipboard01](https://github.com/user-attachments/assets/a46aad83-2bd2-4bd8-8c65-4a0793135ab9)

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
