### ISSUE TITLE
erro no PowerShell

### ISSUE THREAD

**Issue by wanderleiADS** [MicrosoftDocs/PowerShell-Docs#11554]
### Type of issue

Other (describe below)

### Feedback

baixei o Node mas quando tento executar o npm da o seguinte erro. poderia me informa o por que?

npm : O arquivo C:\Program Files\nodejs\npm.ps1 não pode ser carregado porque a execução de scripts foi desabilitada
neste sistema. Para obter mais informações, consulte about_Execution_Policies em
https://go.microsoft.com/fwlink/?LinkID=135170.
No linha:1 caractere:1
+ npm
+ ~~~
    + CategoryInfo          : ErrodeSegurança: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

### Page URL

https://learn.microsoft.com/pt-br/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#supported-versions-of-windows

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

### Author

@sdwheeler

### Document Id

c5ccf493-dc82-bb65-830a-d5857048ce26

**Comment by sdwheeler** [comment]
Please read https://learn.microsoft.com/pt-br/powershell/module/microsoft.powershell.core/about/about_execution_policies

This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
