### ISSUE TITLE
Bad filter in "Disable access to Exchange Online PowerShell" document

### ISSUE THREAD

**Issue by tomdan-MSFT** [MicrosoftDocs/PowerShell-Docs#11576]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/exchange/disable-access-to-exchange-online-powershell?view=exchange-ps&preserve-view=true

### Summary

There's a bad filter listed in this article in the PowerShell examples :

https://learn.microsoft.com/en-us/powershell/exchange/disable-access-to-exchange-online-powershell?view=exchange-ps&preserve-view=true

### Details

The PowerShell example listed in the article does not work :

Get-User -ResultSize unlimited -Filter 'EXOModuleEnabled -eq $false'

This is an invalid filter for get-user and needs to be updated.

### Suggested Fix

Please update the example with the correct filter

**Comment by sdwheeler** [comment]
That content is not maintained in this repository. You can find the source of that article at https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md.
