### ISSUE TITLE
Instructions for Uninstallation and  (Complete) Removal of PowerShell from Mac and Linux

### ISSUE THREAD

**Issue by pa-0** [MicrosoftDocs/PowerShell-Docs#11592]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.4

### Summary

After searching the official docs, I still do not have the information needed to perform a competent removal of PowerShell from a Mac system.  I realize that like many Mac apps, most of PowerShell's application files are bundled into a single folder, but I believe that documenting an approved method of complete removal would be a great value to users. 

### Details

As summarized, documentation addressing the removal of an instance of PowerShell should be available along with all other official supporting documentation.  This should include:

- [x] a high-level overview of the steps necessary to uninstall and remove PowerShell
- [x] all undocumented locations where PowerShell writes files by default, i.e., app data, configuration / settings files, and anything else
- [x] any 'gotchas' or warnings addressing any reasonably foreseeable missteps that the average user should avoid in performing the removal.

### Proposed Content Type

Other / Unknown

### Proposed Title

Uninstalling PowerShell

**Comment by Koho80** [comment]
https://docs.flutter.dev/get-started/install/windows

**Comment by sdwheeler** [comment]
It is documented. There is an uninstall section in every article.

See https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.4#uninstalling-powershell
