### ISSUE TITLE
Send-MailMessage  issue 

### ISSUE THREAD

**Issue by githwork3** [MicrosoftDocs/PowerShell-Docs#11607]
### Type of issue

Code doesn't work

### Feedback

Hi,
How can I send an email from a powershell script with a gmail acccount ? I'm getting error with the below powershell. 

Send-MailMessage -To "recipient@gmail.com" -From "sender@gmail.com" -Subject "Test Email" -Body "This is a test email from PowerShell." -SmtpServer "mtp.gmail.com" -Port 587 -Credential (Get-Credential)

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md

### Author

@sdwheeler

### Document Id

d322254e-65a3-8f03-f2ba-5e4b9b0f15d0

**Comment by sdwheeler** [comment]
You didn't include the error message, but your SmtpServer name looks incorrect. 

Please note that that cmdlet is deprecated and may not work with modern email services. Also, the issues in this repository are for reporting problems with the documentation. We don't provide support.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
