### ISSUE TITLE
MethodInvocationException: 

### ISSUE THREAD

**Issue by Avinash1308** [MicrosoftDocs/PowerShell-Docs#11610]
### Type of issue

Other (describe below)

### Feedback

MethodInvocationException: Exception calling "SignData" with "3" argument(s): "A device attached to the system is not functioning."

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/gallery/overview?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/gallery/overview.md

### Author

@sdwheeler

### Document Id

2e6d46ee-f235-14da-df6a-04ffb06027ce

**Comment by sdwheeler** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
