### ISSUE TITLE
IconURL specifications documentation request

### ISSUE THREAD

**Issue by rebro-msft** [MicrosoftDocs/PowerShell-Docs#1172]
PowerShell Gallery documentation.

Create FAQ or documentation section on IconURL specifications.

User questions:
"What are the formats of the icon for the gallery – opening the default, it seems to be 128x128, 32bit png (not ico). Is this correct, or should we be supplied an ico file with multiple sizes.
Also, does the IconURL value have to be to a http/https location, or can it point to a file in the module?"

Response:
".ICO, .PNG and .SVG image formats are supported. Image dimensions should be 32x32.
Https is preferred over http for IconUri.
Icon Uri should not point to a file in the module."

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/en-us/powershell/gallery/concepts/package-manifest-affecting-ui
