### ISSUE TITLE
Add FAQ on how to update PowerShell Gallery profile image

### ISSUE THREAD

**Issue by rebro-msft** [MicrosoftDocs/PowerShell-Docs#1187]
PowerShell Gallery documentation.

Create FAQ or documentation section on how to update the image on the PowerShell Gallery profile.  Alternatively (for PowerShell Gallery dev team), add a link to the profile page to point to the Gravatar website.

Response to user:
The PowerShell Gallery profile images are provided by [Gravatar](https://secure.gravatar.com/site/implement/images/).  To change your profile image, please register with [Gravatar](https://secure.gravatar.com/site/implement/images/) using the same email address as you use to log in to the PowerShell Gallery.

**Comment by sdwheeler** [comment]
This no longer applies.
