### ISSUE TITLE
Add FAQ/Section for Private Gallery set-up options

### ISSUE THREAD

**Issue by rebro-msft** [MicrosoftDocs/PowerShell-Docs#1189]
PowerShell Gallery documentation.

Create FAQ or documentation section outlining options for setting up a private gallery.  Include pointers to documentation and options, and add descriptions of the usefulness of each option.

Email response to user:
Here is a list of documentation on hot to set up a private gallery:

-	[PSPrivateGallery](https://github.com/PowerShell/PSPrivateGallery) uses DSC Resources and Configurations to deploy and manage a private PowerShell Gallery.
-	This [Windows PowerShell Blog post](https://blogs.msdn.microsoft.com/powershell/2014/05/20/setting-up-an-internal-powershellget-repository/) describes how to set up an internal PowerShellGet repository.
-	Since PowerShell Gallery is a NuGet-based repository, [this post](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview) describes how to host your own NuGet feed.

Let me know if you have any further questions.

**Comment by sdwheeler** [comment]
@rebro-msft Does this document cover the information you want? https://docs.microsoft.com/en-us/powershell/gallery/how-to/working-with-local-psrepositories
