### ISSUE TITLE
Get-EventLog has incorrect Wildcard properties

### ISSUE THREAD

**Issue by zjalexander** [MicrosoftDocs/PowerShell-Docs#1258]
Issue Details
-----------------

see #1235 

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document: 5.0, 5.1 5.1 addressed by #1235

**Comment by kiazhi** [comment]
Checked #1235 commit. Is it even possible to accept wildcard for -Newest parameter on [Int] value in Get-EventLog cmdlet?

I had checked that -LogName and -Username parameters for [Str] value does work with wildcard for Get-EventLog in PoSH 5.1 but can't seems to get it work on -Newest parameter.

**Comment by sdwheeler** [comment]
This has been fixed
