### ISSUE TITLE
Documentation for Publish-Module doesn't mention PSData key

### ISSUE THREAD

**Issue by pcgeek86** [MicrosoftDocs/PowerShell-Docs#1378]
Issue Details
-----------------

The `DESCRIPTION` documentation for `Publish-Module` indicates:

> some metadata must be specified in Publish-Module parameters, such as Tag, ReleaseNote, IconUri, ProjectUri, and LicenseUri, because these parameters match fields in a NuGet-based gallery.

It makes no mention of the `PSData` HashTable key that can be defined under the `PrivateData` key in the module manifest. There's more than one way of defining Tag, Release Notes, IconUri, etc.

https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PowershellGet/Publish-Module.md

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

Cheers,
Trevor Sullivan

**Comment by SteveL-MSFT** [comment]
@edyoung can someone on your team get the docs updated for this?
