### ISSUE TITLE
Save-module and catalog files in psgallery guidelines

### ISSUE THREAD

**Issue by p0w3rsh3ll** [MicrosoftDocs/PowerShell-Docs#1423]
Issue Details
-----------------
https://msdn.microsoft.com/en-us/powershell/gallery/psgallery/psgallery-publishingguidelines states that 

> The PowerShellGet publish-module, install-module, save-module, and update-module cmdlets will check the signature to ensure it is valid, then confirm that the hash value for each item matches what is in the catalog.

Looks like the docs do not reflect what Save-Module actually does.

Save-module does not validate the signature, which was deliberate.

You can confirm this by running the commands, and adding –Verbose to your command, as in
```powershell
  Save-Module –name PowerShellGet –Path c:\temp\ -Verbose
```
Then compare with
```powershell
 Install-Module –Name PowerShellGet –Verbose –Force
```
(Force was added so I install over the existing version)

When you compare those results, you will see that we validate the CAT file on Install, but not on Save.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
The docs were updated some time ago. Closing this issue.
