### ISSUE TITLE
Add doc on required servers to be whitelisted in proxy server for installing the modules from PSGallery

### ISSUE THREAD

**Issue by bmanikm** [MicrosoftDocs/PowerShell-Docs#1465]
Here is the list of target servers to be whitelisted in the proxy server for installing the modules from www.powershellgallery.com. 

oneget.org
go.microsoft.com
az818661.vo.msecnd.net
www.powershellgallery.com
devopsgallerystorage.blob.core.windows.net

**Comment by sdwheeler** [comment]
I added this list of endpoints to the Troubleshooting doc in the PowerShell Gallery docs. See the linked PR.
