### ISSUE TITLE
Add behavior if LocalAccountTokenFilterPolicy registry is not set

### ISSUE THREAD

**Issue by zjalexander** [MicrosoftDocs/PowerShell-Docs#1476]
Copying from #1429 by @kaushika-msft

Issue Details
-----------------
If you run the Enable-PSRemoting cmdlet on the server OS on which Windows Management Framework 5.1 is installed, nothing is displayed on the console and the value of the LocalAccountTokenFilterPolicy registry is not set to 1.

This is because the behavior of the Enable-PSRemoting cmdlet has been changed so that the configuration of the WinRM service is skipped if the following settings are made.

The status of WinRM service is set to "Running".
The startup type of the WinRM service is "Automatic".
A value is set in the setting information in the WinRM service.
Firewall rules for WinRM service are enabled.
Workaround 1:

Execute the command prompt as "administrator".
Do one of the following:
Winrm Quickconfig

Workaround 2:

Run "PowerShell as administrator".
Do one of the following:
Set-WSManQuickConfig-Force

Remedy:

Run PowerShell as an administrator.
Do the following and change the LocalAccountTokenFilterPolicy registry value to 1:
New-ItemProperty -Name LocalAccountTokenFilterPolicy -path HKLM: \ SOFTWARE \ Microsoft \ Windows \ CurrentVersion
More information on - https://blogs.msdn.microsoft.com/wmi/2009/07/24/powershell-remoting-between-two-workgroup-machines/

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document: 5.1

**Comment by zjalexander** [comment]
What's the relationship between the workarounds and the remedy? There's too much detail here to fit into the notes, if just running the -force flag is enough I'd rather only include that. 

also, pinging @JKeithB and @KrishnaV-MSFT for potential 5.1 regression?

**Comment by JKeithB** [comment]
Unless this is extremely common (as in, there are changes to the Windows 10 client that have this set by default), this seems best as a KB article, not as a portion of the main documentation.
