### ISSUE TITLE
Add ```powershell``` code fences where appropriate

### ISSUE THREAD

**Issue by chenrylee** [MicrosoftDocs/PowerShell-Docs#1511]
The Powershell docs have been migrated to new place, and now they all became good-look.
I have read some articles, and found the code blocks are not highlighted.
Indeed, this feature is supported.
I picked a block in an article, it's the original style:
```
PS> Get-Command -Name Clear-Host

CommandType     Name                            Definition
-----------     ----                            ----------
Function        Clear-Host                      $spaceType = [System.Managem...
```
if we add the language tag, it shows:
```powershell
PS> Get-Command -Name Clear-Host

CommandType     Name                            Definition
-----------     ----                            ----------
Function        Clear-Host                      $spaceType = [System.Managem...
```
Yes, just add `powershell` following the first 3-grave mark.
> &emsp;&emsp;\`\`\`powershell

Can you please update all code blocks within the articles?

**Comment by joeyaiello** [comment]
We do this generally as we see it. Unfortunately, the syntax highlighting doesn't come out too well in examples like yours where there's output, so that might be why you're not seeing it in certain places.

**Comment by kiazhi** [comment]
Shouldn't the `PS:\>` be excluded.

**_Example below:_**
\```powershell
Get-Command -Name Clear-Host
\```
\```text
CommandType     Name                            Definition
\-----------     ----                            ----------
Function        Clear-Host                      $spaceType = [System.Managem...
\```

**_Output as below:_**
```powershell
Get-Command -Name Clear-Host
```
```text
CommandType     Name                            Definition
-----------     ----                            ----------
Function        Clear-Host                      $spaceType = [System.Managem...
```

**Comment by zjalexander** [comment]
that's what I have in the [Style Guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md), yeah.

**Comment by sdwheeler** [comment]
@chenrylee @zjalexander Now that we have moved the documentation to docs.microsoft.com, we can leave the `PS:\>` prompts in the examples. The copy button on the frame of the text box will remove the prompts when it copies the text to the clipboard. This allows the code to be more 'paste-able' to the command line.

**Comment by kiazhi** [comment]
Hi @sdwheeler,

Its great to know that it omit `PS:\>` in the examples, but does it also omit `PS C:\>` in the examples too? Reason for that question is that there are about ~10000 results in 1437 files that contains `PS C:\>` in examples in this PowerShell-Docs repo.

**Comment by sdwheeler** [comment]
@kiazhi 
It works on any inside a markdown code fence.

**Comment by zjalexander** [comment]
So as per the style guide:
* Omit PS C:/>

The style guide does NOT have the following:

\`\`\`powershell
Get-Command -Name Clear-Host
\`\`\`
\`\`\`text
CommandType Name Definition
Function Clear-Host $spaceType = [System.Managem...
\`\`\`

Given how docs is rendering it, we do prefer that and I will update the style guide. However, instead of \`\`\`text we can use \`\`\`output which Docs recommends. 

We should fix this as we touch individual articles.

**Comment by zjalexander** [comment]
https://github.com/PowerShell/platyPS/issues/294 there is also a related PlatyPS ask to insert this automatically.

**Comment by MSAdministrator** [comment]
@zjalexander  Is this up for grabs?  I can take this and run through the MDs and submit a PR

**Comment by sdwheeler** [comment]
@MSAdministrator This is up for grabs. Please avoid the About_ topics. These were recently reformatted to meet the requirements of changes to our tool chain. Also please read the recently updated Contributors Guide, especially https://github.com/PowerShell/PowerShell-Docs/blob/staging/contributing/FORMATTING-CODE.md.

Thanks for helping out.

**Comment by MSAdministrator** [comment]
In progress, I plan doing PowerShell 3.0 to 6.

**Comment by MSAdministrator** [comment]
@sdwheeler No problem!  Quick question, should I commit each MD and then PR a branch for each version?  Or commit each MD and do 1 big ol' PR? or something else? :)  Almost done with 3.0

**Comment by sdwheeler** [comment]
Minimize the commits but number of commits is not that important. Do a branch for each topic. My suggestion is this - say you are updating Get-Content.md. Update all versions (3/4/5/5.1/6) of Get-Content.md. The updated files can be one or more commits to your branch. PR that branch. See https://github.com/PowerShell/PowerShell-Docs/pull/1969 for an example PR like this.

**Comment by MSAdministrator** [comment]
@sdwheeler Will do!  Thanks for the clarification!

**Comment by MSAdministrator** [comment]
@sdwheeler An example of my changes across all the docs is in #2070
