### ISSUE TITLE
-InputObject needs to be clearly documented as an implementation detail whose purpose is to facilitate pipeline input

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#1515]
For _most_ cmdlets with a _scalar_ `-InputObject` parameter, its direct use makes no sense, because any _collection_ passed to it is processed _as a whole_ rather than getting _enumerated_ (e.g., `Export-Csv`; a counterexample is `Get-Member`, where the distinction between a collection as a whole and the items contained is useful).

While individual cmdlets' help topics have been improved over time with respect to the description of `-InputObject`, there are many that still give the mistaken impression that sending a collection via the pipeline is equivalent to passing it via `-InputObject`.

A detailed treatment of the issue, along with a list of cmdlets whose help topics need updating, can be found in [this issue](https://github.com/PowerShell/PowerShell/issues/4242).

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by zjalexander** [comment]
Tagging this as reference, but this might come back as an about_ topic. Give a holler if that's the case.

**Comment by Sanan1980** [comment]
Sanan
