### ISSUE TITLE
Document `prompt`

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#1582]
Issue Details
-----------------
First need to document the file that currently exists in the 6.0 docset: https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/prompt.md

Then we need to determine what's applicable downlevel and backport the content.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
This is covered in the About_prompts document.
