### ISSUE TITLE
Start use "Applicable tag" platyPS feature to combine all versions into a single doc

### ISSUE THREAD

**Issue by vors** [MicrosoftDocs/PowerShell-Docs#1797]
PlatyPS now supports a way to generate different maml xmls for different versions, all from the same markdown. That means, that we can have just 1 markdown for all versions!
For details see https://github.com/PowerShell/platyPS/blob/master/docs/Merge-MarkdownHelp.md

To give you an idea of how it may look like

## Cmdlet was added in version 4.0

In the cmdlet top metadata, just put
```
Applicable: 4.0
```

## Parameter was added in version 5.1
In the parameter metadata just put
```
Applicable: 5.1
```

## Creating a maml
Let's say that now we have tags for all versions, like 3.0, 4.0, 5.0, 5.1, 6.0
To generate 5.0 help, we will just call 
```
New-ExternalHelp -ApplicableTag @('5.0', '5.1', '6.0')
```
For more details about this call, see
https://github.com/PowerShell/platyPS/blob/master/docs/New-ExternalHelp.md#-applicabletag

There could be some lack of documentation, but I truly think that it's worth the effort of combining the docs for the ongoing mentioning. It's so tedious to update all the docs when you just want to make a typo fix or a formatting change. :)

**Comment by zjalexander** [comment]
Coordinating with the docs team on this - they have their own versioning story and we need to stay in line with them.

**Comment by vors** [comment]
The worth-persuing goal, in my opinion, is to allow community contributors to transparently update all affected versions without duplicating work manually. It may take some other form, but the current story is far from ideal: it's either a) done by the contributor at the same time b) done later by the doc team member.

I think some progress can be made in this direction with the constraints of staying in line with them (who is this docs team btw?). If you want to explore possibilities together, I'd be happy to brainstorm.

**Comment by sdwheeler** [comment]
This would be cool if we could make it work for OPS. But, for now, it doesn't help us.

**Comment by vors** [comment]
@sdwheeler do you see how OPS / platyPS could be altered to make it work?

**Comment by sdwheeler** [comment]
We can't do this because we still need to create updateable help content for each version. So we have to maintain multiple versions separately.
