### ISSUE TITLE
TRANSACTION-ENABLED ELEMENTS command to correct

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/PowerShell-Docs#1817]
Issue Details
-----------------
Under TRANSACTION-ENABLED ELEMENTS the command used to enumerate providers compatible with transaction is wrong. 
It should be replaced by : Get-psprovider | where {$_.Capabilities -like "*transactions*"}

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

**Comment by sdwheeler** [comment]
This is referring to about_Transactions.md. The proper command should be:

get-psprovider | where {$_.Capabilities -like "*transactions"}

**Comment by sdwheeler** [comment]
fixed
