### ISSUE TITLE
Accessibility in ISE and use of breakpoints

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#1818]
The document at: PowerShell-Docs/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md discusses Accessibility in the ISE. The third paragraph starts off discussing the high contrast mode, then starts talking about break points before moving back to accessibility features.  I have no idea what breakpoints have to do with accessibility (and the breakpoint 
I think this paragraph should probably read more like this:

In addition to accessibility features and utilities in Microsoft Windows, the following make Windows PowerShell ISE more accessible for people with disabilities:

Thoughts?

**Comment by zjalexander** [comment]
Breakpoints are primarily represented visually. This paragraph is calling out the ability to set breakpoints programatically with no visual aid. So, it's relevant, but I agree it's structured poorly. 

Yes, restructure the sentence in that way, but I think copy the stuff about breakpoints and paste it later in the article (maybe under its own subheader) and give it a bullet point.

cc @JKeithB, our accessibility expert :)
