### ISSUE TITLE
PS Gallery best practices misses key notes on signing

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/PowerShell-Docs#1899]
Issue Details
-----------------
The best practices doc, section titled "Sign your code" needs 2 notes:
> Install/Update will use the signature on a .PSD1 file if the package is not catalog signed
> Catalog signing does not currently work with PowerShell core, which has gone RC
> Save-module does not validate a signature - docs need to be fixed. 

Version(s) of document impacted
------------------------------
- [ ] Impacts 5.1 document

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you comment on this issue? Where does this need to go in the documentation?

**Comment by SydneyhSmith** [comment]
> Install/Update will use the signature on a .PSD1 file if the package is not catalog signed

should go here: https://docs.microsoft.com/en-us/powershell/gallery/concepts/publishing-guidelines#sign-your-code 
> Catalog signing does not currently work with PowerShell core, which has gone RC 
Should no longer be an issue
>Save-module does not validate a signature
also is a small fix here: https://docs.microsoft.com/en-us/powershell/gallery/concepts/publishing-guidelines#sign-your-code
