### ISSUE TITLE
DSC ReportServer documentation

### ISSUE THREAD

**Issue by Chirishman** [MicrosoftDocs/PowerShell-Docs#1918]
The DSC report server query examples do not work as provided. The most obvious problem is the inconsistent alternation between providing HTTP and HTTPS urls. The HTTP requests do not work, at least in PS 5.1 and using the example pull server stand up script.

Having modified the example URL provided for the `getreport` function,  the following error is thrown

```
PSMessageDetails      : 
Exception             : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing 
                        connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
                           at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
                           at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                           --- End of inner exception stack trace ---
                           at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                           at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
                           --- End of inner exception stack trace ---
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at GetReport, C:\fakepath.ps1: line 11
                        at <ScriptBlock>, C:\fakepath.ps1: line 18
PipelineIterationInfo : {}
```

**Comment by Chirishman** [comment]
Ok, HTTP/HTTPS issue still stands but I did manage to get the query working. I had forgotten that Invoke-WebRequest throws in this way if it doesn't like a cert. Using [this workaround](https://stackoverflow.com/questions/11696944/powershell-v3-invoke-webrequest-https-error) I got the query to work.

Not sure why that would still happen though, I had already added the self signed cert that the IIS Pull server is using to the Trusted Root.

**Comment by zjalexander** [comment]
@mgreenegit mind taking a look?

**Comment by bobbytreed** [comment]
I am not currently seeing this issue as the example code seems to work fine. There is no mixture of http/https under # Getting Report Data in https://docs.microsoft.com/en-us/powershell/dsc/pull-server/reportserver

Are you still having issues?
