### ISSUE TITLE
Register-ArgumentCompleter example doesn't work

### ISSUE THREAD

**Issue by MartinSGill** [MicrosoftDocs/PowerShell-Docs#1979]
Issue Details
-----------------

Copying and pasting the example from the docs into a powershell doesn't actually work.

The final statement in the image should autocomplete with <tab> but nothing happens.

![image](https://user-images.githubusercontent.com/2271740/34274387-a50c668e-e698-11e7-80bc-dd2ee25c94fd.png)

I suspect it's this issue https://github.com/PowerShell/PowerShell/issues/2912 which means the example simply won't work as written.

A note should probably be added to the docs indicating this issue.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by zjalexander** [comment]
Could you please link the URL as well? 
It looks like the example should be changed so its not registering parameters that begin with hyphens as well as a statement about this being a known issue that is fixed in 6.0+

**Comment by MartinSGill** [comment]
Link:  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-5.1

**Comment by bobbytreed** [comment]
closed by #4321
