### ISSUE TITLE
Update the default/acceptable values for Encoding parameter in v6.0

### ISSUE THREAD

**Issue by matt9ucci** [MicrosoftDocs/PowerShell-Docs#2000]
Issue Details
-----------------
According to PowerShell/PowerShell#5080, the default/acceptable values for **Encoding** parameter has been changed since v6.0. But the change is not documented (e.g. [Out-File -Encoding](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Out-File.md#-encoding) and Set/Add-Content).

The followings are the list of cmdlets which have **Encoding** parameter to be updated:
```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> Get-Command | Where-Object { $_.Parameters.Keys -contains 'Encoding' }

CommandType    Name                Version    Source
-----------    ----                -------    ------
Cmdlet         Add-Content         3.1.0.0    Microsoft.PowerShell.Management
Cmdlet         Export-Clixml       3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Export-Csv          3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Export-PSSession    3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Format-Hex          3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Get-Content         3.1.0.0    Microsoft.PowerShell.Management
Cmdlet         Import-Csv          3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Out-File            3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Select-String       3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Send-MailMessage    3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet         Set-Content         3.1.0.0    Microsoft.PowerShell.Management
```

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by MiYanni** [comment]
@sdwheeler Hey Sean,
I ran into this today while doing some Azure PowerShell cmdlet conversions. DataLakeStore uses the pre-NetCore type (`FileSystemCmdletProviderEncoding`). This enum no longer exists in NetCore, so the `Add-Content`, `Get-Content`, and `Set-Content` cmdlet docs for 6.0 are out of date.

Just FYI, the DataLakeStore cmdlets that use this pre-NetCore type (Encoding parameter) are:
- [New-AzureRmDataLakeStoreItem](https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakestore/new-azurermdatalakestoreitem?view=azurermps-4.4.1)
- [Add-AzureRmDataLakeStoreItemContent](https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakestore/add-azurermdatalakestoreitemcontent?view=azurermps-4.4.1)
- [Get-AzureRmDataLakeStoreItemContent](https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakestore/get-azurermdatalakestoreitemcontent?view=azurermps-4.4.1)

**Comment by sdwheeler** [comment]
@davidsmatlak - please edit this comment to add PR references

| cmdlet            | PR of fix    |
| --- | --- |
| Add-Content       |              | 
| ConvertFrom-Csv   | #3519        | 
| ConvertTo-Csv     | #3515, #3519 | 
| Export-Clixml     | #3590        | 
| Export-Csv        | #3515, #3519 | 
| Export-PSSession  |              | 
| Format-Hex        |              | 
| Get-Content       |              | 
| Import-Csv        | #3519        | 
| Out-File          |              | 
| Select-String     |              | 
| Send-MailMessage  |              | 
| Set-Content       |              |

**Comment by davidsmatlak** [comment]
Copyedited the documents and updated the Encoding parameter. Refer to the table for the PR numbers.
