### ISSUE TITLE
Document PSCore6 MSI properties

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#2007]
Issue Details
-----------------
@bergmeister added [new capability](https://github.com/PowerShell/PowerShell/pull/5774#issuecomment-355207020) to the MSI installer for adding context menus.  Users can specify this property with a `/q` quiet install but needs to know the property name a priori.

Should also document other aspects of the installer like it adds pwsh to the system path.

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by bergmeister** [comment]
As discussed in the issue, the new property will only be present in ps 6.1 but it still makes sense to have a general documentation of the current msi

**Comment by bergmeister** [comment]
I see that a lot of installation documentation is in the PowerShell repo (e.g. [here](https://github.com/PowerShell/PowerShell/tree/master/docs/installation)). Do we plan to move it to this repo or is the idea to point it to the release specific branch?

**Comment by bergmeister** [comment]
The referenced PR above added the `ENABLE_PSREMOTING` and `REGISTER_MANIFEST` properties that need to be set to 1 in order to be run.

**Comment by SteveL-MSFT** [comment]
@sdwheeler I think we should consider having the installation docs converted to an about_ topic

**Comment by joeyaiello** [comment]
About_topics need to be reconciled all up with the existing TOC. Let's not mix that effort with the need to write content right now.

**Comment by joeyaiello** [comment]
Also related to #3048
