### ISSUE TITLE
about_Logging.md needs to be updated to include information about script block logging

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#2017]
Issue Details
-----------------
[`about_Logging.md`](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Logging.md) needs to be updated to include the information about script block logging.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

I'm not sure if we have the documentation for script block logging in 5.1, but the file `about_Logging.md` was introduced in PSv6. It may be possible that we should put the information about script block logging in a different file, instead of `about_Logging.md`.

**Comment by dantraMSFT** [comment]
Note that the doc needs to be updated since PR renames PowerShellProperties.json

**Comment by sdwheeler** [comment]
This is fixed
