### ISSUE TITLE
Document powershell.config.json settings.

### ISSUE THREAD

**Issue by dantraMSFT** [MicrosoftDocs/PowerShell-Docs#2053]
Currently, there is no documentation about the format and usage of json file(s), what can be configured and the distinction between user and system-wide settings.

The document should call out what settings are valid in the user and system-wide files, their location, and a notation, for windows, what settings are overridden by group policy.

**Comment by rjmholt** [comment]
This has been partially addressed in https://github.com/MicrosoftDocs/PowerShell-Docs/pull/3238, but the group policy settings need to be documented in the same file now.
