### ISSUE TITLE
PowerShell-Core-Support should say how quickly you have to update to a patch version.

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#2091]
Issue Details
-----------------
https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/docs-conceptual/PowerShell-Core-Support.md should specify how quickly you have to update to a patch version (6.0.1).

My understanding, if a patch is needed, it will be based on the last patch.  So any time will be assuming you don't have a known issue, and if you need a fix, you will need to fully update.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Fixed
