### ISSUE TITLE
Set-StrictMode -Version 3.0 is not documented

### ISSUE THREAD

**Issue by stknohg** [MicrosoftDocs/PowerShell-Docs#2135]
Issue Details
-----------------
From PowerShell 3.0, `Set-StrictMode -Version 3.0` is added to verify an array index access.
But, this is not documented.

```powershell
# PowerShell 3.0 or later
$array = (1,2,3)

# No error, returns null.
Set-StrictMode -Version 2.0
$array[3]

# Error. (IndexOutOfRangeException)
Set-StrictMode -Version 3.0
$array[3]
```

e.g.

```powershell
PS C:\> $array = (1,2,3)
PS C:\> Set-StrictMode -Version 3.0
PS C:\> $array[3]
Index was outside the bounds of the array.
At line:1 char:1
+ $array[3]
+ ~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], IndexOutOfRangeException
+ FullyQualifiedErrorId : System.IndexOutOfRangeException
```

see : 

https://github.com/PowerShell/PowerShell/blob/v6.0.1/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L4337

(The code is version 6.0.1, but this is added from PowerShell 3.0.)

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by DCtheGeek** [comment]
This was fixed in #4684 by @sdwheeler.  Closing.
