### ISSUE TITLE
WMF 5.1 downloads are signed with expired certificate

### ISSUE THREAD

**Issue by gregpakes** [MicrosoftDocs/PowerShell-Docs#2155]
The following page https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.1/install-configure.md has download links to WMF 5.1.

The MSU files in the download are signed, but the certificate has expired meaning they can't be installed.

**Comment by zjalexander** [comment]
also tracking here: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/33393337-bug-the-certificate-for-the-wmf-5-1-setup-has-exp

**Comment by gregpakes** [comment]
Uservoice seems an odd place to report this issue...  Its a bug, not a feature request.

**Comment by zjalexander** [comment]
We maintain both UserVoice and GitHub for tracking bugs. We also explicitly have a policy of keeping UserVoice around for versions of PowerShell which are not open-source, as well as PowerShell-related things (like the Gallery, and DSC). 

Personally, I prefer GitHub, but UserVoice has a lot of historical data ported over from our _previous_ tool, Connect, so I just keep an eye on both :)
