### ISSUE TITLE
Ubuntu 17.04 no longer supported

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#2165]
Issue Details
-----------------

https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS-and-Linux.md
Docs how to install PSCore on ubuntu 17.04 but it no longer works because Ubuntu no longer supports 17.04

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by matt9ucci** [comment]
The PowerShell team is now changing the Ubuntu's package name from 17.04 to 17.10 (PowerShell/PowerShell#6028). It would be nice to update the PowerShell-Docs after it was done.

**Comment by sdwheeler** [comment]
All versions of Ubuntu 17.x are end-of-life. See https://wiki.ubuntu.com/Releases.
