### ISSUE TITLE
In PowerShell 5.1-6.0  does command 'Get-EventLog' permit wildcards?

### ISSUE THREAD

**Issue by BluYous** [MicrosoftDocs/PowerShell-Docs#2172]
Hi everyone,

https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-EventLog.md#-message

这里是不是有个小小的问题？
Is there a small problem?

> -Message
> Specifies a string in the event message that this cmdlet gets event information from. You can use this property to search for messages that contain certain words or phrases. **Wildcards are permitted.**

BUT...

> Accept wildcard characters: **False**

在之前的版本都是支持通配符的。
In the previous version, wildcards are permitted and 'Accept wildcard characters' is true.

英文水平不太好还请见谅！
Please forgive me for not being good at English.

**Comment by sdwheeler** [comment]
See related issue #2179

**Comment by sdwheeler** [comment]
Fixed
