### ISSUE TITLE
A Tale of PowerShell Documentation Woes

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#2213]
Preface: There are some actionable items in this post, but its primary purpose is to shed some light on the frustration users experience with the current state of PowerShell documentation; the text is an excerpt from [this SO answer](https://stackoverflow.com/a/49078856/45375), and comments by other users on the linked page also reflect dissatisfaction.  

The post was written in response to the OP's struggle to find documentation for `Get-Content`'s `-Raw` switch.

---

The central conflict of this tale is the tension between the solid *foundation* of PowerShell's _potentially_ great help system and its shoddy current *content*.  

 * As is often the case, **third parties come to the rescue**, as shown in [gms0ulman's helpful](https://stackoverflow.com/a/49078580/45375) answer.

 * As briantist also points out, however, **[PowerShell's documentation is now open-source](https://github.com/PowerShell/PowerShell-Docs) and welcomes contributions**; he states:  
"I will direct your attention to the [Edit link](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Get-Content.md)
   [for the `Get-Content` help topic on GitHub] [...] so you can actually fix it up and submit something better
   (including examples). I have done it before; they do accept pull
   requests for it."  
The caveat is that while future PowerShell _Core_ versions will benefit from improvements, it's not clear whether improvements will make their way back into _Windows PowerShell_.

Let's ask **PowerShell's _built-in_ help system**, accessible via the standard `Get-Help` cmdlet (the _content_ for which may not be preinstalled; install when prompted, or run `Update-Help` from an *elevated* session):

    Get-Help Get-Content -Parameter Raw

Note how **you can conveniently ask for help on a specific parameter** (`-Parameter Raw`).

On **Windows PowerShell v5.1**, this yields:

<pre>
-Raw <switch>
  Ignores newline characters and returns the entire contents of a file in one string.  
  By default, the contents of a file is returned as a array of strings that is delimited  
  by the newline character.
        
  Raw is a dynamic parameter that the FileSystem provider adds to the Get-Content cmdlet.  
  This parameter works only in file system drives.
        
  This parameter is introduced in Windows PowerShell 3.0.

  Required?                    false
  Position?                    named
  Default value
  Accept pipeline input?       false
  Accept wildcard characters?  false
</pre>

That is indeed what we were looking for and quite helpful (leaving the awkward phrasing "delimited by the newline character" aside and that on Windows a newline is a character _sequence_; also, ["ignored" could lead one to believe that newlines are _stripped_ from the input, which is not true](https://github.com/PowerShell/PowerShell-Docs/issues/2697)).
        
On **Powershell Core v6.0.2**, this yields:

<pre>
-Raw
    
    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     true
</pre>

While the meta-data is more detailed - including a hint that the parameter is _dynamic_ (see below) - it is crucially **missing a _description_ of the parameter**.

**Some provider-cmdlet parameters are _dynamic_**, in that they are **_specific to a given provider_**, so **there is a mechanism to specify the _target provider_** when asking for help, **by passing a provider-specific example path to the `-Path` parameter**.

In the case at hand, let's therefore try (PowerShell Core on Windows):

    Get-Help Get-Content -Parameter Raw -Path C:\

Sadly, the result is the same unhelpful response as before.  

Note that, as long as you're invoking the command from a _filesystem_ location, explicit use of `-Path` should _note_ be necessary, because the provider underlying the _current location_ is implicitly targeted.

---

Now let's take a look at the **_online_ versions of PowerShell's help topics**:

As it turns out, **a given provider cmdlet can have _multiple_ documentation pages**:

* A *generic* one that applies to _all_ providers.

* *Provider-specific* pages that document provider-exclusive behavior and parameters, such as `-Raw` for the filesystem provider.

Sadly, **the generic topics make no mention of the existence of the *provider-specific* ones**, making them **hard to discover**.
 
* ***Googling* `Get-Content`** takes you to https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content, the _generic_ topic, which contains the following misleading statement: `This parameter is not supported by any providers that are installed with Windows PowerShell.`

  * **This is not only unhelpful, but actively _misleading_**, because the PowerShell file-system provider clearly _is_ installed with PowerShell and it _does_ support `-Raw`.  
[Drive] providers are PowerShell's generalization of the filesystem drive metaphor to support targeting other [typically hierarchical] storage systems with a unified set of cmdlets. For instance, Windows PowerShell also ships with the _registry_ drive provider, which allows managing the registry as if it were a drive.

* **The `-Online` switch for `Get-Help`** conveniently allows opening the online version of the requested topic in the **browser**; so let's try that (`Get-Help Get-Content -Online`):

   * Windows PowerShell v5.1: Takes you [a 404 page(!) related to v4](https://docs.microsoft.com/en-us/powershell/module/4.0/microsoft.powershell.core/providers/FileSystem-Provider/Get-Content-for-Filesystem).

   * PowerShell Core v6.0.1: Takes you to the same generic topic that googling does.

There's a sliver of hope, however: The aforementioned 404 page offers a *link* to the filesystem-provider-specific topic: [
Get-Content for FileSystem](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/providers/filesystem-provider/get-content-for-filesystem)

It is there that we finally discover the online version of the truly relevant, provider-specific information, which is the same that `Get-Help Get-Content -Parameter Raw` provides locally, but - as stated - only in _Windows PowerShell_.

**Comment by joeyaiello** [comment]
I appreciate the sentiment here, but I think this has been addressed, as seen in 6.2:

```
C:\Users\jaiello> get-help get-content -Parameter raw

-Raw [<SwitchParameter>]
    Ignores newline characters and returns the entire contents of a file in one
    string with the newlines preserved. By default, newline characters in a
    file are used as delimiters to separate the input into an array of strings.

    `-Raw` is a dynamic parameter that the FileSystem provider adds to the
    `Get-Content` cmdlet  This parameter works only in file system drives.

    This parameter was introduced in Windows PowerShell 3.0.

    Required?                    false
    Position?                    named
    Default value                False
    Accept pipeline input?       False
    Accept wildcard characters?  false
```


The problem now is that new content doesn't make it's way back into Windows PowerShell, but we're still doing some internally to try and address that (no promises, nor ETA unfortunately). Turns out managing those forward links (and all the containers they point to) is hard, especially when the forward links are buried in module manifests in different source control around the company. 

@sdwheeler if you think there's still something actionable here, feel free to re-open and ping me.
