### ISSUE TITLE
Consistently document in what PowerShell version a given cmdlet was introduced.

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#2270]
Commendably, _parameters_ introduced in later versions of existing cmdlets are marked such as in their descriptions. E.g., `This parameter was introduced in Windows PowerShell 3.0.` for `Get-Content`'s `-Tail` parameter.

By contrast, the information as to in what version a _cmdlet as a whole_ was introduced is not _consistently_ present.

E.g., The [topic for `Invoke-WebRequest`](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md), introduced in PSv3, commendably states: `This cmdlet was introduced in PowerShell 3.0.`

By contrast, the [topic for `Get-FileHash`](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md), introduced in PSv4, does not state that information.

All existing cmdlets should be reviewed and the PowerShell version that introduced them should be noted in their help topics.

Please also consider stating the information in a more structured, prominent way, such as in the heading; e.g., instead of `Invoke-WebRequest` the heading could say `Invoke-WebRequest [v3+]`

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
FYI - https://powershellone.wordpress.com/2018/07/20/find-out-in-which-version-a-powershell-cmdlet-was-introduced/

**Comment by mklement0** [comment]
Thanks, @sdwheeler.

Just as the _docs_ should contain the minimum-version information, it would indeed be handy to have a _programmatic_ way to discover the information.

The linked function is interesting, but it uses a hard-coded `Microsoft.PowerShell.Archive`-module-based URL, and therefore doesn't work in most cases.

As it so happens, I tried to solve the same problem with function `Get-MinPsVersionForCmdlet`  available from [this Gist](https://gist.github.com/mklement0/9c494216681c4c25d17abda2b60cdff9):

It is based on examining _this_ repository's URLs and if a v3 topics is found looks for an introduced-in-v3 note in the text.

It tries hard, but it's not foolproof, and it's limited to the cmdlets represented in _this_ repo.

Here's the help text, which has details and examples:

```none

NAME
    Get-MinPsVersionForCmdlet
    
SYNOPSIS
    Determines the minimum PowerShell version required for a given standard cmdlet.
    
    
SYNTAX
    Get-MinPsVersionForCmdlet [-Name] <String[]> [<CommonParameters>]
    
    
DESCRIPTION
    NOTE:
     * v3 or higher is required to run this function.
     * Only cmdlets with help topics defined in the GitHub 
       PowerShell-documentation repository at 
       https://github.com/PowerShell/PowerShell-Docs
       can be examined.
       * In general, this INCLUDES the cmdlets that ship with PowerShell Core.
       * It EXCLUDES:
         * inherently Windows-only cmdlets such as Set-WinSystemLocale
           (some of which are tied to an *OS* version rather than a PowerShell
           version)
         * cmdlets that have not yet or may never be ported to 
           PowerShell Core, such as Set-Culture.
     * If a given cmdlet is not available on this machine, it must be specified
       CASE-EXACTLY.
    
    CAVEATS:
    
    The minimum PowerShell version that supports a given cmdlet (i.e., the version
    in which a give cmdlet was introduced) is derived from the version-specific
    help-topic links at https://github.com/PowerShell/PowerShell-Docs
    
    The lowest version represented there is v3, so in order to determine whether
    a cmdlet was available in v2 already, the text of the v3 help topic must
    be searched for a hint that the cmdlet was introduced in v3.
    From the *absence* of such a hint, this function infers v2 availability, but
    note that this method is not foolproof, because not all cmdlet help topics
    explicitly state in what version they were introduced.
    

PARAMETERS
    -Name <String[]>
        The name of one or more cmdlets whose minimum version requirement to 
        determine.
        Wildcards are supported.
        
        If the cmdlet exists on the local machine, you may also specify an alias
        for it for brevity.
        
        If the cmdlet does NOT exist, you must specify it CASE-EXACTLY.
        
    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216). 
    
    -------------------------- EXAMPLE 1 --------------------------
    
    PS > Get-MinPsVersionForCmdlet Get-FileHash
    
    Name         MinVersion
    ----         ----------
    Get-FileHash 4.0
    
    
    
    
    -------------------------- EXAMPLE 2 --------------------------
    
    PS > Get-MinPsVersionForCmdlet Get-Content
    
    Name        MinVersion Comment
    ----        ---------- -------
    Get-Content 2.0        CAVEAT: v2 availability inferred from absence of version note in v3 topic
    
    
    
    
```

**Comment by sdwheeler** [comment]
@mklement0 - the inclusion of the link was not meant to suggest a solution. It was meant to show that the community wants this information.

**Comment by mklement0** [comment]
@sdwheeler: 

Got it; glad to hear it that there's interest.

My solution actually does succeed in extracting the currently available (but lacking) information from the docs generically, which I find personally helpful - hopefully others do too.
