### ISSUE TITLE
Copy-Item - Conflicting default values for Container flag

### ISSUE THREAD

**Issue by ezillinger** [MicrosoftDocs/PowerShell-Docs#2293]
In Example 2 for Copy-Item it says "The Container parameter is set to true by default." yet below in the Parameters section it says "Default value: None" or "Default value: False", depending on the version. 

Which is correct?

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
See also #2179 and #2271
