### ISSUE TITLE
Expand the Register-ArgumentCompleter topic to clarify its purpose and provide historical context

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#2325]
<sup>Follow-up from #747</sup>

The [Register-ArgumentCompleter](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md) topic is should be expanded to:

* clarify its purpose, notably by mentioning familiar terms such as _tab completion_ and _auto-completion_

* mention that it was introduced in v5

* mention the older mechanism it obsoletes (I presume), namely the `TabExpansion[2]` functions.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell

**Comment by bobbytreed** [comment]
closed by #4321
