### ISSUE TITLE
about_Environment_Variables needs updating for PowerShell 6

### ISSUE THREAD

**Issue by Jaykul** [MicrosoftDocs/PowerShell-Docs#2419]
Issue Details
-----------------

1. This document is not cross-platform, containing lots of examples of PATH variables joined by the Windows-specific `;` which does not work in PowerShell on Linux or Mac.
2. The document constantly says "Windows PowerShell"
3. The section titled "Environment Variables That Store Preferences" shows out-of-date default values for PSModulePath
4. The examples for modifying PSModulePath modify the "Machine" environment, which seems to be ignored in PowerShell 6

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document
Or more correctly, the _same_ document that's incorrect for PowerShell 6+ is correct for Windows PowerShell.

**Comment by matt9ucci** [comment]
> 3. The section titled "Environment Variables That Store Preferences" shows out-of-date default values for PSModulePath
> 4. The examples for modifying PSModulePath modify the "Machine" environment, which seems to be ignored in PowerShell 6

It might be a good idea to remove the `$env:PSModulePath` examples and create a new file "about_PSModulePath.md".

### Reasons
1. `$env:PSModulePath` is a special topic for the PowerShell's module system
2.  `$env:PSModulePath` is sometimes complicated not only for PowerShell users but also for PowerShell developers (I remember the [WMF5 RTM $PSModulePath issue](https://blogs.msdn.microsoft.com/powershell/2015/12/23/windows-management-framework-wmf-5-0-currently-removed-from-download-center/))
3. Currently, the information about `$env:PSModulePath` is scattered in the [about_Environment_Variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-6#long-description) and [about_Modules](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_modules?view=powershell-6#module-and-dsc-resource-locations-and-psmodulepath)
