### ISSUE TITLE
Parameter-set names above syntax diagrams do not show up in the online versions of the help topics

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#2422]
Especially with complex commands that have several parameter sets, it's important to have the parameter-set names shown above the respective syntax diagrams.

In the _source code_ for the help topics that already seems to be the case; e.g.:

*  https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/New-PSSession.md

However, when the online version is rendered in the browser, the names are missing; e.g.:

* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-6

Here's an example:

![image](https://user-images.githubusercontent.com/588825/39928509-81c581ea-5503-11e8-8c83-33a01b75e8a2.png)

Similarly, `Get-Help` / `-?` also doesn't currently show parameter-set names - see https://github.com/PowerShell/PowerShell/issues/6856

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by SteveL-MSFT** [comment]
@sdwheeler since this is marked `Pri-High`, should we consider enabling that feature?

**Comment by Ayanmullick** [comment]
This is awaiting an update to [New-YamlHelp](https://docs.microsoft.com/en-us/powershell/module/platyps/new-yamlhelp?view=ps-modules) before using it in the build pipeline.

**Comment by sdwheeler** [comment]
This is being tracked in https://github.com/PowerShell/platyPS/issues/578
