### ISSUE TITLE
Document that most execution policies require the shell and the system to be ready for an interactive session

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#2440]
Issue Details
-----------------

Document that most execution policies require the shell and the system to be ready for an interactive session

ByPass works without an shell/interactive session
AllSigned works without an shell/interactive session

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@TravisEz13 can you explain what the issue is here? What are we documenting?

**Comment by TravisEz13** [comment]
@sdwheeler If PowerShell Core is run on WindowsServer Core or some other Windows operating system without a shell the execution policies will fail in certain conditions (mainly if you download a file with IE or Edge and try to run it,) because we need a shell component to validate that the file was not downloaded.  There is an issue to change the behavior for 6.1, but the new behavior has not be determined.  The error would look something like this (although this is not the only possible cause of this issue):
```
AuthorizationManager check failed.
At line:1 char:1
+ C:\scrippath\scriptname.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

Other possible causes:
  - The shell isn't ready for the call

**Comment by TravisEz13** [comment]
What are we waiting on here?

**Comment by sdwheeler** [comment]
@TravisEz13 Did anything change in v6.1 or v7? Is that the exact error that occurs? 

When you say "Windows OS without a shell":
-  Do you mean Windows Server Core and Windows Server Nano? Are there others?
- In this context "shell" means the "Windows Desktop" environment (explorer.exe), right?

**Comment by TravisEz13** [comment]
> Do you mean Windows Server Core and Windows Server Nano? Are there others?
Yes

> In this context "shell" means the "Windows Desktop" environment (explorer.exe), right?

yes
