### ISSUE TITLE
Restart-Computer v6 doesn't restart the local computer

### ISSUE THREAD

**Issue by matt9ucci** [MicrosoftDocs/PowerShell-Docs#2652]
Issue Details
-----------------
Restart-Computer.md says:

> ### Example 1: Restart the local computer
> ```
> PS C:\> Restart-Computer
> ```
> 
> This command restarts the local computer.

The example succeeds in PowerShell v5.1. However, it fails in v6.

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> Restart-Computer
Restart-Computer : Failed to restart the computer MYPCNAME with the following error message:
 The client cannot connect to the destination specified in the request.
 Verify that the service on the destination is running and is accepting requests.
 Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM.
 If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig"..
At line:1 char:1
+ Restart-Computer
+ ~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (MYPCNAME:String) [Restart-Computer], InvalidOperationException
+ FullyQualifiedErrorId : RestartcomputerFailed,Microsoft.PowerShell.Commands.RestartComputerCommand
```

I think this error occurs due to lack of prerequisites such as WinRm/WSMan or [WindowsCompatibility](https://github.com/PowerShell/WindowsCompatibility). If so, the prerequisites should be explained in Restart-Computer.md v6.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by doctordns** [comment]
Did you check that WSMAN is running?

**Comment by matt9ucci** [comment]
I am sorry for not explaining my intention sufficiently. I have added more explanation to the Issue Details as following:
> I think this error occurs due to lack of prerequisites such as WinRm/WSMan. If so, the prerequisites should be explained in Restart-Computer.md v6.
