### ISSUE TITLE
The Import-Module help topic needs improvement to make sense to end-users

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#2730]
@sethvs  commendably tried to amend the `Import-Module` help topic in  #2722 based on #2691 and the discussion in https://github.com/PowerShell/PowerShell/issues/5503, but the amendment  - while an improvement in some respects - fell short overall.

https://github.com/PowerShell/PowerShell/issues/5503#issuecomment-407239395 should form the basis of another revision.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x]  Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
Waiting on discussions to be finalized before making further changes.

**Comment by mklement0** [comment]
Thanks for the status update, @sdwheeler.

A quick tangent, while I think of it: I just added the following to the linked comment:

> If importing a module should include its `class` and `enum` definitions as well, use `using module` instead of `Import-Module`, and place it at the very beginning of your script

which reminds me that I think that the `using module/assembly/namespace` statements (introduced in v5, I think) have yet to be documented altogether - correct?

For instance, `about_Modules` makes no mention of `using module`.
