### ISSUE TITLE
docs.microsoft.com has incorrect example for PowerShell.AddArgument

### ISSUE THREAD

**Issue by TylerLeonhardt** [MicrosoftDocs/PowerShell-Docs#2779]
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addargument?view=powershellsdk-1.1.0

The AddArgument function isn't used in the example. It's unclear if that was just a typo or if this doc is referring to AddParameter instead.

**Comment by sdwheeler** [comment]
Submitted PR to fix this and got a build error. Need to investigate how those docs get built.

**Comment by corbob** [comment]
May also want to update the comment here: https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/System.Management.Automation/engine/hostifaces/PSCommand.cs#L352-L376 as it's got the incorrect information as well.

**Comment by tylerl0706** [comment]
@sdwheeler can you link to the PR? Maybe I can help

**Comment by sdwheeler** [comment]
@tylerl0706 https://github.com/MicrosoftDocs/powershell-docs-sdk-dotnet/pull/14

I realize now that the change probably needs to be in the source code and not in this repo.

**Comment by 1RedOne** [comment]
Hi all, I think this is where you need to make the change.  Those docs seem to auto generate from comments within the source files, like this.

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/PSCommand.cs

If you search for 'Add a command to construct a command pipeline' in the above link, you'll find the right place to make the change.

**Comment by DCtheGeek** [comment]
Upstream source appears to have been fixed, so the article now shows the AddArgument function as expected. Closing this issue.  cc / @sdwheeler
