### ISSUE TITLE
Document  ListEntryBuilder.AddItemScriptBlock with itemSelectionCondition

### ISSUE THREAD

**Issue by powercode** [MicrosoftDocs/PowerShell-Docs#2862]
Issue Details
-----------------

https://github.com/PowerShell/PowerShell/pull/7104 adds a new public API for creating formatting entries that aren't display if they are `null`. This may need to be documented.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/en-us/powershell/scripting/developer/format/scriptblock-element-for-itemseclectioncondition-for-controls-for-configuration-format?view=powershell-7
