### ISSUE TITLE
Suggestion: provide online links for all help topics, including the conceptual ones (about_*)

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#2939]
Being able to read the _online_ versions of help topics is always helpful:

* for better visual presentation and a more convenient UI

* to get the latest content (local content may be stale)

While that currently works for _cmdlets_ - e.g. `Get-Help -Online Get-Command` - it doesn't for other types of help content, notably the conceptual `about_*` topics.

It would help if _all_ downloadable help topics had a link to their online version.

**Comment by markroloff** [comment]
I can tackle this. Before I get ahead of myself @sdwheeler, will it interfere with the work being done in #1806?

**Comment by yecril71pl** [comment]
> @markroloff Thank you for the offer. But please wait on this for now. About topics are published differently than the cmdlet help. I am working on getting FWLinks defined for all content.

Any progress?

**Comment by sdwheeler** [comment]
No progress. Because of the way the help system works in PowerShell, there is no HelpURI for about topics. The help system does not support it. It will take a change to PowerShell. We want to get there at some point.

**Comment by yecril71pl** [comment]
I am unable to find the right technical issue for this.

**Comment by SamB** [comment]
@yecril71pl 

> I am unable to locate the right technical issue for this.

It looks like this has since been filed as <https://github.com/PowerShell/PowerShell/issues/13550>.

**Comment by sdwheeler** [comment]
The `online version` metadata has been added to all About_ articles. However, PowerShell's help system has no way to use that information.
