### ISSUE TITLE
Developer documentation only talks about "Windows PowerShell", but applies to PowerShell Core too

### ISSUE THREAD

**Issue by felixfbecker** [MicrosoftDocs/PowerShell-Docs#2945]
E.g. "Writing a Windows PowerShell Format file" should really be "Writing a PowerShell Format file": https://docs.microsoft.com/en-us/powershell/developer/format/writing-a-windows-powershell-formatting-file

Same with "Writing a Windows PowerShell Cmdlet" etc.

It's currently confusing to find resources about how to do these things as a mac/Linux user, as it sounds like these docs explicitly don't apply.

**Comment by sdwheeler** [comment]
Yes, there is a lot of information in these docs that applies to any version of PowerShell, and there is a lot that is Windows specific.

The developer docs are listed as "Legacy" content. We don't have the resources at this time to do the complete update that would be required.
