### ISSUE TITLE
Format-Hex help topic needs several improvements

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#2955]
* The `-Raw` switch:
  * must be documented as _obsolete_ in v6+, given that it is now a _no-op_ - see #1940
  * must have a _description_ added for v5.1 (the version in which it was introduced, also the only version in which it had any functionality) - see https://github.com/PowerShell/PowerShell/pull/3320/files#diff-9d6f8c0ef1420c0a15209f186c5c1f17L227

* `-InputObject` / pipeline input supports only a limited number of input types, which should be documented:

  * The types are `[string]`, `[byte]`/`[byte[]]`, `[int]`,`[int[]]`, and `[long]` / `[long[]]`, as well as `[system.io.fileinfo]` instances for piping from `Get-ChildItem` - see  https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs#L227

  * Any other type causes the following error:
`Cannot convert input of type <type> to hexadecimal. To view the hexadecimal formatting of its string representation, pipe it to the Out-String cmdlet before piping it to Format-Hex."`

* The `-Encoding` parameter:

  * is incorrectly described in general: its true purpose is to control the _output_ encoding whose byte representation to output, and it only applies to input objects received via the _pipeline_ (whereas input read directly from a file is always output as the file's raw byte representation).

    * additionally, it only applies to `[string]` input; with any of the supported _numeric_ types, `-Encoding` has no effect.

  * is incorrectly described as defaulting to _Unicode_; the true defaults are:

     * Windows PowerShell: _ASCII_; note that that means that non-ASCII characters in the input are output as literal `?` chars. (single `0x3F` bytes), resulting in a loss of information.

     * PowerShell Core: _UTF-8_

Additionally, it makes sense to explain the limitations of the right-most column that tries to render the bytes as _characters_:

* Generally, each _byte_ is interpreted as a Unicode code point, which means that:
  * (printable) ASCII[-range] characters are always printed correctly, as themselves.
  * _multi-byte_ UTF-8 characters _never_ render correctly
  * UTF-16 characters render correctly _only_ if their high byte happens be `NUL`.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by iSazonov** [comment]
https://github.com/PowerShell/PowerShell/pull/8191 add support for char and enum (and array of these types).
