### ISSUE TITLE
Online Fwlink for cmdlets do not resolve correctly

### ISSUE THREAD

**Issue by markroloff** [MicrosoftDocs/PowerShell-Docs#2998]
Issue Details
-----------------

Fwlinks for the online version of both of these docs point to the online document for 5.1.

[reference/5.0/PSReadline/Set-PSReadlineOption.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSReadline/Set-PSReadlineOption.md)
[reference/6/PSReadLine/Set-PSReadlineOption.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PSReadLine/Set-PSReadlineOption.md)

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Bad online links
- Register-ArgumentCompleter
- Get-ChildItem
- Install-Module

**Comment by sdwheeler** [comment]
This is fixed now. May need to run `Update-Help -Force` to get the fixed content.
