### ISSUE TITLE
Docs needed for 'added -Stable sort and tests (#7846)'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3021]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7862

**Comment by joeyaiello** [comment]
This doc PR should target `release-62` if it's still in preview

**Comment by anmenaga** [comment]
Duplicate of #3246
