### ISSUE TITLE
Docs needed for 'Add C#-style type accelerators and suffixes for ushort, uint, ulong, and short literals'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3022]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7813

**Comment by joeyaiello** [comment]
Been thinking about where this one should go, it might make sense to build a small topic for about_Type_Accelerators to document all the ones we have so far.

**Comment by sdwheeler** [comment]
This is fixed.
