### ISSUE TITLE
Docs needed for 'Support calling method with ByRef-like type parameters'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3024]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7721

**Comment by joeyaiello** [comment]
Not sure where this one should live, paging @daxian-dbw for thoughts

**Comment by sdwheeler** [comment]
Need some use case examples to know how to document this.
