### ISSUE TITLE
Docs needed for 'Join-String cmdlet for creating text from pipeline input'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3026]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7660

**Comment by powercode** [comment]
So were in the file system should that go?

**Comment by sdwheeler** [comment]
The PR for this change has not been merged.

**Comment by powercode** [comment]
That doesn't prevent me from writing the docs.

**Comment by sdwheeler** [comment]
@powercode Not at all. Please write and submit the docs. We can merge the docs when the code is merged. Looks like this should go in reference/6/Microsoft.PowerShell.Utility/Join-String.md.

**Comment by joeyaiello** [comment]
@powercode you're awesome 🎉

**Comment by joeyaiello** [comment]
This looks done to me.
