### ISSUE TITLE
Docs needed for 'Add ITuple checks to PSGetIndexBinder'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3028]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7633

**Comment by joeyaiello** [comment]
Not sure where this should be captured, but it seems like very useful behavior.

To keep everyone from digging, we've enabled this:

```powershell
$tuple = [Tuple]::Create(1, 'test')
$tuple[0]
$tuple[1]
$tuple[0..1]
$tuple[-1]
```

**Comment by sdwheeler** [comment]
Added in v6.1
