### ISSUE TITLE
Docs needed for 'Add support to experimental features'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3030]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7242

**Comment by joeyaiello** [comment]
I think we need to codify PowerShell/PowerShell-RFC#114 as a new about_Experimental_Features topic /cc @daxian-dbw

**Comment by sdwheeler** [comment]
Fixed
