### ISSUE TITLE
Docs needed for 'Explicitly disallow Basic Auth over HTTP with PSRP on Linux'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3036]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/6779

**Comment by joeyaiello** [comment]
This should probably go into [about_Remote_Requirements](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_requirements?view=powershell-6)

**Comment by sdwheeler** [comment]
Fixed
