### ISSUE TITLE
Docs needed for 'S.M.A.Powershell class :  the contents of the 'IsRunspaceOwner' property change after displaying the instance in the console.'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3041]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/6365

**Comment by joeyaiello** [comment]
The linked (now, closed) issue needs to be spelunked for info, but I believe the primary change will go into this: https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.create?view=pscore-6.0.0#System_Management_Automation_PowerShell_Create

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.isrunspaceowner?view=powershellsdk-7.0.0#System_Management_Automation_PowerShell_IsRunspaceOwner

**Comment by sdwheeler** [comment]
Closing this since the correct Issue exists in the source repo.
