### ISSUE TITLE
Docs needed for 'Make UTF-8 Default Encoding for application/json'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3044]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/6109

**Comment by joeyaiello** [comment]
This should get added to our proposed about_encoding in #3190 as well as the web cmdlet docs.

**Comment by sdwheeler** [comment]
Need to add this to breaking changes doc.
