### ISSUE TITLE
Docs needed for 'Question about System.Span'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3051]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/5897

**Comment by joeyaiello** [comment]
Not sure *where* to doc [this explanation](https://github.com/PowerShell/PowerShell/issues/5897#issuecomment-358042114), but we should.

**Comment by sdwheeler** [comment]
The error message is now explicit about the cause of the exception. I don't think this needs documentation.

```
PS> [char[]]$T=@('a','b','c','d')
PS> [System.ReadOnlySpan[char]]::new($T)
InvalidOperation: Cannot create an instance of the ByRef-like type "System.ReadOnlySpan`1[[System.Char, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]". ByRef-like types are not supported in PowerShell.
```
