### ISSUE TITLE
Docs needed for 'Invoke-RestMethod -FollowRelLink should return a single array of objects'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3062]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/5526

**Comment by joeyaiello** [comment]
This should be noted in the parameter description for `-FollowRelLink` on both web cmdlets

**Comment by mivalsten** [comment]
Created pull request #3658 for this. Only Invoke-RESTMethod is affected as Invoke-WebRequest does not have -FollowRelLink switch and either way is returning response body as a string.

**Comment by sdwheeler** [comment]
Fixed
