### ISSUE TITLE
Docs needed for 'Remove DCOM support from *-Computer cmdlets (replacement for 5152)'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3069]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5277

**Comment by joeyaiello** [comment]
A note of this should be added to each of the *-Computer cmdlet ref topics

**Comment by sdwheeler** [comment]
Not clear what needs to be documented here. What is the impact to the user?

**Comment by SteveL-MSFT** [comment]
So the change here is that the `*-Computer` cmdlets in Windows PowerShell has a `-Protocol` parameter where `DCOM` is an option.  The change is that DCOM support is removed and you can only use WSMan for remoting.
