### ISSUE TITLE
Docs needed for 'a warning should be presented if -AsByteStream and -Encoding are used together'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3071]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/5170

**Comment by sdwheeler** [comment]
Fixed
