### ISSUE TITLE
Docs needed for 'Unify cmdlets with parameter 'Encoding' to be of type System.Text.Encoding'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3076]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5080

**Comment by sdwheeler** [comment]
Fixed
