### ISSUE TITLE
Docs needed for 'correct passing of parameter so args show up as args instead of input'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3082]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/4963

**Comment by joeyaiello** [comment]
I don't know that documentation is actually needed for this, but someone can correct me here.

**Comment by SteveL-MSFT** [comment]
I don't think any specific doc is needed here, this was a bug fix.

**Comment by sdwheeler** [comment]
This is already in the [Breaking Changes](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-6) doc
