### ISSUE TITLE
Docs needed for 'Added BinPath, Description, UserName and Delayed Auto Start to Get-Service'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3083]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/4907

**Comment by joeyaiello** [comment]
This sparked a discussion about "synthetic types" and how/whether we should doc them. 

For context:

```powershell
(get-service)[0].pstypenames
System.Service.ServiceController#StartupType
System.Service.ServiceController#BinaryPathName
System.Service.ServiceController#DelayedAutoStart
System.Service.ServiceController#Description
System.Service.ServiceController#UserName
System.ServiceProcess.ServiceController
System.ComponentModel.Component
System.MarshalByRefObject
System.Object
```

**Comment by SteveL-MSFT** [comment]
I think as part of the [output](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-6#outputs) documentation we should have information about the additional properties that are not part of the ServiceController type.  The new properties are explained in the associated PR.

**Comment by sdwheeler** [comment]
This information has already been added to the cmdlet reference. @joeyaiello open another issue if you think we need to doc synthetic types.
