### ISSUE TITLE
Docs needed for 'S.M.A.PowerShell.HadErrors and $? return false positives when errors are suppressed'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3088]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/4613

**Comment by sdwheeler** [comment]
Overlaps with #3102 which was fixed in #5760
