### ISSUE TITLE
Docs needed for 'Use HTML meta charset attribute value, if present, when the Context-Type header does not specify it.'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3093]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/4338

**Comment by joeyaiello** [comment]
This would need be doc'd in the cmdlet help for `Invoke-WebRequest`/`Invoke-RestMethod`

**Comment by SteveL-MSFT** [comment]
[HTML meta charset](https://www.w3schools.com/tags/att_meta_charset.asp) is a HTML attribute that declares the character set (encoding, like UTF-8) of the content.  The docs should simply state that the web cmdlets will look at the HTML payload and use this for the encoding if `Content-Type` header is not specified.

**Comment by sdwheeler** [comment]
This was fixed in #1543
