### ISSUE TITLE
Docs needed for 'Change New-ModuleManifest encoding to UTF8NoBOM on non-Windows platforms'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3098]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/3940

**Comment by sdwheeler** [comment]
This information exists in the release notes but should be added to the cmdlet ref.
- PS 6.0 on Windows - result UTF16
- PS 6.0 on non-Windows - result UTF8NoBOM
- PS 6.1+ on all platforms - result UTF8NoBOM
