### ISSUE TITLE
Docs needed for 'string.split('') doubt'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3100]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/3809

**Comment by sdwheeler** [comment]
I am not clear on what documentation should be added here.

**Comment by SteveL-MSFT** [comment]
I don't think anything needs to be documented here.  Basically, it's a change in .NET api behavior and not anything in PowerShell.
