### ISSUE TITLE
Docs needed for 'Fix Default/OEM encoding behavior PowerShell Core'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3105]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/3467

**Comment by sdwheeler** [comment]
This is a duplicate of or related to the following issues:

- #3098
- #3076
- #2000
- #1483
- #1101

**Comment by sdwheeler** [comment]
Fixed
