### ISSUE TITLE
Docs needed for 'Porting Enable-PSRemoting and its Tests'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3109]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/2671

**Comment by joeyaiello** [comment]
Should probably be fixed in conjunction with #3118

**Comment by sdwheeler** [comment]
This change 
1. Ports Enable-PSRemoting and Disable-PSRemoting to PowerShell Core
2. Adds side-by-side PowerShell Core remoting support to the PSSessionConfiguration cmdlets and PSRemoting cmdlets.
3. Ports PSSessionConfiguration tests

This change also introduces a behavioral difference. The PSRemoting and PSSessionConfiguration cmdlets are now context-sensitive and only work for endpoints that match the PowerShell type. For example, Get-PSSessionConfiguration, when run in PowerShell Core, will only return PowerShell Core WinRM endpoints. It will only modify PowerShell Core WinRM endpoints and cannot be used to configure Windows PowerShell endpoints.

**Comment by SteveL-MSFT** [comment]
The other important difference is Windows PowerShell creates the Microsoft.PowerShell endpoint pointing to itself.  PSCore6 will create a PowerShell.6 (and version specific PowerShell.6.x.y) endpoint.  PS7 will create a PowerShell.7 endpoint (along with version specific one).

**Comment by sdwheeler** [comment]
@SteveL-MSFT Need to decide on priorities for this work. This backlog for v6 but there are changes coming for v7.

**Comment by PaulHigin** [comment]
Enable-PSRemoting and Disable-PSRemoting documents have been updated for PS6.
