### ISSUE TITLE
Docs needed for 'Add support <Suppress> in Get-WinEvent -FilterHashtable'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3111]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/2506

**Comment by joeyaiello** [comment]
Should probably be fixed in conjunction with #3114

**Comment by sdwheeler** [comment]
See https://github.com/PowerShell/PowerShell/issues/2402 for example.

**Comment by sdwheeler** [comment]
Examples suppressing by EventId and by UserData.
```
$filterSuppress = @{ path = "$eventLogFile";  SuppressHashFilter=@{Id=370}}
$resultsSuppress = Get-WinEvent -filterHashtable $filterSuppress -ea silentlycontinue
$filterSuppress = @{ path = "$eventLogFile";  SuppressHashFilter=@{Param2 = "Windows x64"}}
$resultsSuppress = Get-WinEvent -filterHashtable $filterSuppress -ea silentlycontinue
```
