### ISSUE TITLE
Docs needed for 'Add support W3C Extended Log File Format in Import-Csv'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3112]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/2482

**Comment by joeyaiello** [comment]
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Import-Csv?view=powershell-6

**Comment by sdwheeler** [comment]
Lines starting with '#' are treated as comments and ignored unless the comment starts with "#Fields: " and contains CSV list of column names. In that case, the cmdlet uses those column names. This matches the W3C ELF.
