### ISSUE TITLE
Docs needed for 'Fix Get-WinEvent -FilterHashtable to work with named event data field'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3114]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/2373

**Comment by joeyaiello** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent

**Comment by sdwheeler** [comment]
@joeyaiello It is unclear how to use this new feature. We need some good examples to add to the docs.

**Comment by SteveL-MSFT** [comment]
This looks like a bug fix and not a new capability.  I see a bunch of existing samples for `-FilterHashtable` in the docs already.

**Comment by sdwheeler** [comment]
@SteveL-MSFT I think that this change allows any named field. Previously, `FilterHashtable` only supported a specific list. If that is the case then that is what we need to document. Can you confirm?

**Comment by SteveL-MSFT** [comment]
@sdwheeler the change looks to be fixing a syntax error in the xpath query from square brackets to parenthesis so that the filter works now

**Comment by sdwheeler** [comment]
Closing this as a bug fix where the proper behavior is already documented.
