### ISSUE TITLE
Docs needed for 'WinRM Plugin Registration and Modification'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3118]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/1193

**Comment by joeyaiello** [comment]
Some of this is doc'd in the release notes for 6.1: https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-61?view=powershell-6#enable-psremoting-now-creates-separate-remoting-endpoints-for-preview-versions

But more than anything, we need to rev [this](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/wsman-remoting-in-powershell-core?view=powershell-6) which is outdated.

**Comment by SteveL-MSFT** [comment]
I think the main changes to the doc needed are:

1. In general, they should use `Enable-PSRemoting` when called from pwsh
2. `Install-PowerShellRemoting.ps1` is only needed if enabling PSCore6 remoting from Windows PowerShell (or any version of PSCore6 from a different running instance of PowerShell)
3. The file path needs to be updated, it's just `$env:ProgramFiles\PowerShell\6` and not 6.0.0
4. The remoting endpoint is also just `PowerShell.6` although there is a version specific one `PowerShell.6.2.0`, but for most users, they should use `PowerShell.6`.

**Comment by mklement0** [comment]
@SteveL-MSFT:

Good points, but re 2.:

I'd deprecate `Install-PowerShellRemoting.ps1` altogether - users should use `Enable-PSRemoting` going forward; there's (a) no need to keep the stopgap around and have it potentially diverge from the `Enable-PSRemoting` cmdlet in the future and (b) the name doesn't even indicate that its functionality is _Core_-specific.

Also `Enable-PSRemoting`  is currently still Windows PowerShell-only; needs to be updated to mention the Core session configurations, and especially with your recommendation in 4.

**Comment by sdwheeler** [comment]
@SteveL-MSFT Need to decide on priorities for this work. This backlog for v6 but there are changes coming for v7.
