### ISSUE TITLE
Docs needed for 'Should namespaces should be case perserving/Case-Insensitive?'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3119]
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/706

**Comment by joeyaiello** [comment]
Not sure *where* to doc all this stuff. Possibly need an about_CaseSensitivity or something like that? Open to suggestions

**Comment by sdwheeler** [comment]
Moved to https://github.com/MicrosoftDocs/PowerShell-Docs/wiki/PowerShell-treatment-of-namespaces-is-case-insensitive-but-case-preserving
