### ISSUE TITLE
PSVersionInfo PSVersion and PSEdition docs needed

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#3127]
Issue Details
-----------------
I've submitted a PR to make PSVersionInfo.PSVersion and PSVersionInfo.PSEdition public so that binary assembly authors working with PowerShell can leverage that information efficiently without having to invoke PowerShell to get it and without having to use reflection.

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by joeyaiello** [comment]
This is in the Docs already given that we did a new SDK ref run: [PSEdition](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psversioninfo.psedition?view=pscore-6.2.0#System_Management_Automation_PSVersionInfo_PSEdition) and [PSVersion](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psversioninfo.psversion?view=pscore-6.2.0)
