### ISSUE TITLE
GetSteppablePipeline method documentation needed

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#3128]
Issue Details
-----------------

A PR was submitted to change the visibility of GetSteppablePipeline from internal to public. This PR is to identify the need for documentation for that method.

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [] The documented feature was introduced in selected version of PowerShell
- [X] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.getsteppablepipeline?view=powershellsdk-7.0.0#System_Management_Automation_PowerShell_GetSteppablePipeline
