### ISSUE TITLE
Add S.M.A.PowerShell.InvokeAsync and .StopAsync documentation

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#3129]
Issue Details
-----------------

This issue is to identify the need for documentation for the 5 new InvokeAsync overloads added to PowerShell Core in a PR.

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [X] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Fixed
- https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.stopasync?view=powershellsdk-7.0.0#System_Management_Automation_PowerShell_StopAsync_System_AsyncCallback_System_Object_
- https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.invokeasync?view=powershellsdk-7.0.0
