### ISSUE TITLE
Add docs for EngineIntrinsics property of Runspace class

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#3141]
Issue Details
-----------------
In a PR (referenced below), a public EngineIntrinsics property has been added to the S.M.A.R.Runspace class in the PowerShell SDK to allow developers to access the object exposed by $ExecutionContext in PowerShell without having to invoke PowerShell to get it.

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [X] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
PR was abandoned. Closing this issue.
