### ISSUE TITLE
edit button on page 404s

### ISSUE THREAD

**Issue by TylerLeonhardt** [MicrosoftDocs/PowerShell-Docs#3158]
If you click the edit button on this page:
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addargument?view=pscore-6.0.0

it 404s. It should point to the correct file.

**Comment by sdwheeler** [comment]
Fixing this is blocked by a build error. We are waiting on a new nupkg from Jim to fix the build error.

**Comment by sdwheeler** [comment]
The edit button has been disabled.
