### ISSUE TITLE
Test-Path: Update documentation

### ISSUE THREAD

**Issue by vexx32** [MicrosoftDocs/PowerShell-Docs#3165]
Issue Details
-----------------

Ref: https://github.com/PowerShell/PowerShell/pull/8080

Test-Path is being altered to accept null/empty string input. I believe the behaviour will be as follows:

* For `$null` input: write non-terminating error to error stream
* For empty string `''` input: return `$false`

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by SteveL-MSFT** [comment]
Fixed by #4036
