### ISSUE TITLE
Suggestion: Create a new conceptual topic about character encoding

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3190]
Given that many cmdlets have an `-Encoding` parameter, and that there are now fundamental differences in the default encoding behavior between the editions, it would help to have a new conceptual topic named, say, `about_character_encodings`, rather than to repeat (too much)  information in each cmdlet's topic.

In addition to an enumeration of the supported encodings and a description, such a new topic could: 

* describe the fundamental differences between the editions with respect to the default encoding in more detail, along with the ramifications.

   * [This StackOverflow answer](https://stackoverflow.com/a/40098904/45375) could be a starting point.

* provide more guidance, along the lines of the following:

---

A note re the use of a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) (a.k.a. Unicode signature) with [UTF-8](https://en.wikipedia.org/wiki/UTF-8) and other Unicode encodings:

* In _Windows PowerShell_, `-Encoding utf8` _invariably_ creates a BOM (applies not just to `Set-Content`, but also to other cmdlets that produce file output, such as `Out-File` and `Export-Csv`).

  * Direct use of the .NET framework is required to create BOM-_less_ UTF-8 files. Note that the .NET framework's default encoding has always been BOM-less UTF-8.

* PowerShell _Core_ creates BOM-_less_ UTF-8 files _by default_ (and also when you explicitly use <br>`-Encoding utf8`); you can opt to have a BOM created with `-Encoding utf8BOM`.

For best overall compatibility, BOMs in UTF-8 files should be _avoided_: Unix platforms and Unix-heritage utilities also used on Windows Platforms generally don't know how to handle them.

Similarly, `-Encoding UTF7` should be avoided, because it is not a standard Unicode encoding (and is written _without_ a BOM in both PowerShell editions).

In _both_ PowerShell editions, all other Unicode encodings available with `-Encoding` _do_ create an (encoding-appropriate) BOM: `Unicode` (UTF-16LE), `bigendianunicode` (UTF-16BE), and `utf32` (UTF-32LE).

**Comment by joeyaiello** [comment]
Pasting Sean's list into this one and adding a couple more:

- #3105
- #3098
- #3076
- #2000
- #1483
- #1101
- #3071 
- #3066
