### ISSUE TITLE
Document differing culture-sensitivity between advanced functions and cmdlets, in about_Functions_Advanced_Parameters

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3194]
When you supply strings as arguments to parameters that implicitly convert those strings to the parameter target type (e.g., `[datetime]`):

* _cmdlets_ perform _culture-sensitive_ parsing,
* whereas _advanced functions_ perform _culture-invariant_ parsing.

This surprising discrepancy is likely unintentional, but fixing it may be too much of  a breaking change - see https://github.com/PowerShell/PowerShell/issues/6989 for details.

Either way, it should be documented for the existing versions.

Note that it is the behavior of the advanced functions that is correct here, in line with PowerShell's culture-invariant casting and string interpolation.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
Related to #3193
