### ISSUE TITLE
Get-Content topic: explain the relationship between -Raw and -AsByteStream / -Encoding Byte

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3213]
Combining `-Raw` with `-AsByteStream` / `-Encoding Byte` is actually the simplest way to get the file's content as a raw byte array (`[byte[]]`), output as a _single_ object (as opposed to the bytes streaming one by one, in the absence of `-Raw`).

The description of both parameters should reflect this option.

Note that the currently documented method for getting all bytes as a single array is to combine  <br>`-AsByteStream` / `-Encoding Byte`   with `-ReadCount 0` instead, which works too, but:

* using `-Raw` instead is more obvious and easier to type (assuming you know that [`-Raw` actually means: read the file _as a whole_](https://github.com/PowerShell/PowerShell/issues/7715))
* `-ReadCount 0` outputs an `[object[]]` array rather than a specifically typed `[byte[]]` array (though the difference will rarely matter).

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
See related #3071

**Comment by SteveL-MSFT** [comment]
Agree that there is utility to documenting use of `-Raw` with `-AsByteStream`
