### ISSUE TITLE
The MSDN documentation about the OneGet refences the ShellLink class that doesn't exist

### ISSUE THREAD

**Issue by it-praktyk** [MicrosoftDocs/PowerShell-Docs#3220]
Issue Details
-----------------

At the web page https://msdn.microsoft.com/en-us/library/microsoft.oneget.utility.platform.shelllink%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396 is referenced class that doesn't exist in the code of the OneGet.

I tried to find the file  Microsoft.OneGet.Utility.dll too - it doesn't exist.

I asked also OneGet developers https://github.com/OneGet/oneget/issues/395#issuecomment-434802956 - also received the confirmation that the class doesn't exist.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
That documentation has been retired and is no longer accurate.
