### ISSUE TITLE
VS Code documents are scattered

### ISSUE THREAD

**Issue by matt9ucci** [MicrosoftDocs/PowerShell-Docs#3243]
Issue Details
-----------------
The documents on using VS Code are scattered across the four repos:

1. [PowerShell/PowerShell-Docs](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/vscode/using-vscode.md)
2. [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md)
3. [Microsoft/vscode-docs](https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/powershell.md)
4. [PowerShell/vscode-powershell](https://github.com/PowerShell/vscode-powershell)

They have duplicate descriptions and cross-references.

Suggestion
-----------------
PowerShell/PowerShell-Docs should keep its VS Code docs as simple as possible:
* Update the [using-vscode.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/vscode/using-vscode.md)  in the PowerShell/PowerShell-Docs as it has short description and useful links for VS Code and extension
* Update the Microsoft/vscode-docs and the PowerShell/vscode-powershell docs as they do not have links for the using-vscode.md in the PowerShell/PowerShell-Docs

**Comment by TylerLeonhardt** [comment]
making progress here... 

once #3432 gets deployed I will remove those docs from vscode-powershell.

@SydneyhSmith is cleaning up PowerShell/PowerShell.

Then we'll be down to 2. Both I think are important where they are.

**Comment by TylerLeonhardt** [comment]
This work is finished. We have docs in the PowerShell docs & in the vscode docs. Both of which should stay where they are.
