### ISSUE TITLE
Document changes to -Debug common parameter

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#3255]
As per [this PR](https://github.com/PowerShell/PowerShell/pull/8195), and [this issue](https://github.com/PowerShell/PowerShell/issues/7122), a docs update will be necessary if the PR is approved that explains the new -Debug common parameter behavior (with the PR, it sets $DebugPreference to Continue instead of the antiquated Inquire value it used since PowerShell v1).

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [] This issue only shows up in selected version of the document

**Comment by SteveL-MSFT** [comment]
Fixed by #4048
