### ISSUE TITLE
Multiple parameters for Install-Package don't have descriptions

### ISSUE THREAD

**Issue by terrabitz** [MicrosoftDocs/PowerShell-Docs#3257]
There are several parameters in the Install-Package cmdlet that currently do not have any descriptions. While some seem fairly straightforward, there are some (like "-Destination") that aren't quite as wholly unambiguous. The following still have the {{Fill ___ Description}} descriptions:

-AllowPrereleaseVersions
-ConfigFile
-Contains
-Destination
-ExcludeVersion
-FilterOnTag
-Headers
-SkipValidate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e512130c-870a-77b7-2dda-fdbb1d2acc22
* Version Independent ID: 3b920543-f348-a9a4-93b2-5b3dd01532e8
* Content: [Install-Package (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-package?view=powershell-6#feedback)
* Content Source: [reference/6/PackageManagement/Install-Package.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PackageManagement/Install-Package.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Fixed in #3807
