### ISSUE TITLE
the default encoding is not ascii (5.1) (set-content)

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#3263]
The default encoding is not ascii (set-content in ps 5.1).  This is easy to confirm.  Save a file with a string containing an accent, like 'información'.  If it was ascii, it would replace the accented 'o' with a '?'.  

Note also that powershell 5.1 does not interpret 'utf8 no bom' encoded files correctly.

PS C:\> .\accent.ps1
informaciÃ³n

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe7a24a-702c-a3d9-fb0c-ca525b4a5ccc
* Version Independent ID: e4684775-c0df-ad9a-7eef-135db60ada1b
* Content: [Set-Content (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Set-Content.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Set-Content.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by TylerLeonhardt** [comment]
This is because in Windows PowerShell (5.1) we used CP-1252 as the default output encoding... This was changed to UTF-8 in PowerShell Core.

To prove this, just run, `$OutputEncoding`

**Comment by bobbytreed** [comment]
I just tested this on powershell 5.1 and it is indeed ASCII

$OutputEncoding

IsSingleByte      : True
BodyName          : us-ascii
EncodingName      : US-ASCII
HeaderName        : us-ascii
WebName           : us-ascii
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 20127

**Comment by jszabo98** [comment]
$outputencoding and what set-content saves as are two different things.

**Comment by bobbytreed** [comment]
Currently the Set-Content article states the following:
 **Default** Uses the encoding that corresponds to the system's active code page (usually ANSI).
Is this not correct?

**Comment by jszabo98** [comment]
Yes, it looks like it's been corrected.

**Comment by bobbytreed** [comment]
Thanks!!!, closing this issue
