### ISSUE TITLE
PowerShell about_ help files do not display synopsis due to incompatible formatting

### ISSUE THREAD

**Issue by DarwinJS** [MicrosoftDocs/PowerShell-Docs#3268]
Most powershell core about_* help files are not formatted to support the built in extraction of a synopsis.

Given that the synopsis is the ONLY metadata that can be extracted from the about_ format (which sucks - see #8230 ), these files should be correctly formatted to maximize helpfulness of help using built in features.

Steps to reproduce
------------------

```get-help about_*

```

Expected behavior
-----------------

```about_Scheduled_Jobs              HelpFile                            Describes scheduled jobs and explains how to use and manage
about_Scheduled_Jobs_Advanced     HelpFile                            Explains advanced scheduled job topics, including the file structure
about_Scheduled_Jobs_Basics       HelpFile                            Explains how to create and manage scheduled jobs.

```

Actual behavior
---------------

```about_Try_Catch_Finally           HelpFile
about_Types.ps1xml                HelpFile
about_Type_Operators              HelpFile
about_Updatable_Help              HelpFile
About_Using                       HelpFile

```

Get-Help parses **only the first line** of the SHORT DESCRIPTION into a synopsis.

Most of the about_* files in powershell core are formatted as (**notice blank line after heading**):
```
SHORT DESCRIPTION

    This is the short description
```

for the file synopsis to show up, they should be 

````
SHORT DESCRIPTION
    This is the short description
````

**Comment by DarwinJS** [comment]
Opps I should have restarted pwsh 6.  I was able to get .SYNOPSIS to show up after adding it to an existing about_PSReadLine file.

Seems like .SYNOPSIS in contextual help might work in PowerShell 6, but not 5.x

Hmmm - so the space between the heading at the text is consistent with all headings. If this help is coming from a conversion from source markdown - maybe it is preserving the markdown proper syntax of having a blank line - which is not compatible with get-help. Maybe powershell 6 help parser should be adjusted instead of adjusting the md conversion process.

**Comment by sdwheeler** [comment]
The blank line after the synopsis is not the issue. This appears to be an issue with they way that PlatyPS converts the MD to TXT. The output from PlatyPS if formatted with specific "headers". Get-Help is expecting that format. Since we switched to pandoc for processing the About_ files the TXT files do not have the same "headers".

**Comment by SteveL-MSFT** [comment]
This is also affecting PS7

**Comment by sdwheeler** [comment]
Link to: https://github.com/PowerShell/PowerShell/issues/9208

**Comment by sdwheeler** [comment]
This issue is being tracked in source repo.
