### ISSUE TITLE
about_Pipelines should explain the pipeline's enumeration behavior in more detail

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3285]
A core feature of the pipeline is to _enumerate_ collection-like data structures.

The `One-At-A-Time Processing` section of `about_Pipelines` touches on that, but could use some more detail, notably with respect to what specific data types are considered collections and are therefore enumerated (sent through the pipeline one by one).

From what I gather, the rules are:

* Instances of data types that implement the `IEnumerable` interface are automatically enumerated, but there are exceptions:  
  * Types that also implement `IDictionary`, such as *hashtables*, are _not_ enumerated, and neither are `XmlNode` instances.  
* Conversely, instances of `DataTable` (which doesn't implement `IEnumerable`) _are_ enumerated (as the elements of their `.Rows` collection) 

See the [source code](https://github.com/PowerShell/PowerShell/blob/43e0394d51b7ee8c5fa84f5308e27cec4f942672/src/System.Management.Automation/engine/LanguagePrimitives.cs#L515).

If that is considered too detailed / technical, it's at least worth mentioning that `[hashtable]` instances are _not_ enumerated by default, and that doing so requires a call to `.GetEnumerator()` (a fact that already is mentioned in the hash-table-specific topic, `about_Hash_Tables`).

Additionally it's worth mentioning that (stdout) output from _external programs_ is enumerated _line by line_ in the pipeline.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by TheIncorrigible1** [comment]
I feel like many of these details are addressed in other articles on those specific items inadvertently, but it would be nice to see them in a single location when talking about the pipeline to redirect newer users to learn as suggested by this request.
