### ISSUE TITLE
Add documentation for new ValidateTrustedData parameter attribute 

### ISSUE THREAD

**Issue by PaulHigin** [MicrosoftDocs/PowerShell-Docs#3288]
Issue Details
-----------------
A new input variable tracking feature was added to PSCore 6.1.1.  The appropriate v6 document should be updated to describe what this attribute does.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by daxian-dbw** [comment]
I will add more information about this attribute tomorrow.

**Comment by daxian-dbw** [comment]
### Summary
The attribute `ValidateTrustedDataAttribute` is used on parameters of cmdlets or functions. During the parameter binding, if the powershell session in use `HasEverUsedConstrainedLanguage` and currently it's in `FullLanguageMode`, then the argument specified to that parameter will be validated to make sure that object is trusted.

### How to determine if an object is trusted
As long as a `Global:` variable or a `Script:` variable in a module scope is being set in `ConstrainedLanguageMode`, the value is marked as `UnTrusted`.
When using that variable as the value for a parameter, the tainted mode of the value gets propagated for every conversion happens during the parameter binding. That means, for a untrusted value, if a new object is created as a result of a conversion from it during the parameter binding, the new object is also marked as untrusted.
Eventually, `ValidateTrustedDataAttribute` will kick in and validate if the final to-be-bound value is trusted.

### Why having this attribute
This is the very first iteration of the work to track untrusted value in PowerShell when running in `ConstrainedLangaugeMode`. It only tracks values set to `Global:` and module scope `Script:` variables, and the tainted mode of those values only propagates during parameter binding, no other data manipulation.
By declaring `ValidateTrustedDataAttribute` for parameters of some sensitive cmdlets, it can help to prevent those cmdlets from running in `FullLanguageMode` with data from `ConstrainedLanguageMode`.

**Comment by sdwheeler** [comment]
@SteveL-MSFT Is this ready to be documented in its current state? It seems like this is for internal use only, at this time.

**Comment by PaulHigin** [comment]
I agree that this needn't be documented yet, since variable tracking is only partially implemented.

**Comment by joeyaiello** [comment]
Given our offline conversation, I think we just need a line in https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6 for now that says something like "this attribute is currently used internally by PowerShell itself and is not intended for external usage"
