### ISSUE TITLE
move powershell-beginners-guide.md from powershell repo

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#3300]
move powershell-beginners-guide.md from powershell repo
https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/powershell-beginners-guide.md

**Comment by sdwheeler** [comment]
@TravisEz13 We should move all of the contents of https://github.com/PowerShell/PowerShell/tree/master/docs/learning-powershell to the docs repo. However, some of this duplicates or overlaps existing content. Also, some of the links to external resources are broken or link to very old content that may not be the best choice anymore.

**Comment by TravisEz13** [comment]
Yup, Joey left a review comment.  I filed an issue so we don't lose track of the work.

**Comment by sdwheeler** [comment]
Cutting this. Jason is working on this kind of content. We will track this in new issues.
