### ISSUE TITLE
about_Variables needs to document namespace variable notation

### ISSUE THREAD

**Issue by vexx32** [MicrosoftDocs/PowerShell-Docs#3343]
Issue Details
-----------------

The `about_Variables` file is missing entirely information on the feature whereby a variable name such as `$c:windows` or `${c:\Windows\system.ini}`, among many other available PSDrives, is analogous to calling `Get-Content` on the provided PSDrive-qualified path. 

This could also be mentioned briefly in `about_Scopes` (it is not) but as it is _not_ a true scope and is a fallback feature that (as far as I know) executes after a named scope is not found, it ought to be referenced in `about_Variables` and its behaviour documented thoroughly.

I believe this behaviour was implemented in v3, and I am unable to find any concrete references to it apart from some _very_ misleading information in [`about_Environment_Provider`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_provider?view=powershell-6#navigating-the-environment-drive) which appears to place the responsibility for the feature in the provider's hands. This is entirely incorrect, as it will attempt to be used regardless of provider support for the feature, as can be evidenced by attempting to access, for example, `${hklm:HKEY_LOCAL_MACHINE\DRIVERS}` from a Windows machine. The error message states only that the appropriate interface for the feature has not been implemented for the requested provider / PSDrive.

Important points:

* Use of this syntax to access a PSProvider _only_ works on **non-container** items in most cases, as most providers do not support calling `Get-Content` on a container item.
* The PSProvider responsible for the PSDrive _must_ implement `IContentCmdletProvider` for this to work. As the Windows registry provider does not implement this interface, accessing registry locations in this manner fails.
    * On Windows, both the Registry and Certificate providers do not implement the interface to permit this to work.
* Behaviour on default PSProviders ought to be documented, namely:
    * **Filesystem:** retrieves the _full content_ of the file, with none of its metadata
    * **Function:** retrieves the function's associated ScriptBlock
    * **Alias:** retrieves the full command name the alias refers to
    * **Variable:** surprisingly, this works at all. It does the exact same thing as _not_ prefixing the variable with `$variable:` does; i.e., `$variable:home -eq $home`

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

**Comment by sdwheeler** [comment]
@vexx32 I don't see these psdrive variables you talk about. I get no value returned in your examples.

**Comment by vexx32** [comment]
Try `$function:prompt` or indeed any globally available function. 😄

**Comment by mklement0** [comment]
Thanks for opening this, @vexx32.

The feature is called _namespace variable notation_ and you'll find a summary at https://github.com/PowerShell/PowerShell/issues/2268#issuecomment-283755725.

It is related to _providers_, not to variables or scopes per se (though at least mentioning the feature in the topics for the latter two makes sense).

**Comment by vexx32** [comment]
Appreciate the clarification, thank you! 😄 

I think I've heard the name before, but couldn't recall what it was exactly. The reason I say that it should be mentioned for variables specifically is that it _is_ in many ways tied to their syntax and how variable names are parsed, at least from what I understand of what @Romero126 has told me from his experience in https://github.com/PowerShell/PowerShell/pull/8297 and the surrounding code.

**Comment by mklement0** [comment]
Yes, good point, it uses the _syntactic form_ of variables, so `about_Variables` is a natural entry point.

So the information could either be added there or point to a yet-to-be-created new topic.

Wherever it ends up, `about_Scopes` and `about_Providers` should also point to it.

**Comment by sdwheeler** [comment]
@SteveL-MSFT @BrucePay Can you provide some info we can add to the docs or add the appropriate docs?

**Comment by sql-sith** [comment]
I spent a good amount of time trying to find documentation on this yesterday. I have a PSDrive named `code` and at one point in my morning tab autocompletion suggested `$code`. After spending way too much time coming to the conclusion that I was too inept to find the documentation that must surely exist (in general, the Powershell docs are pretty good!) I gave up and posted on StackExchange. One of the answers helped me a lot, so I'm linking to that to give you info you can consider for the docs.

I will put a command on StackExchange asking the poster if they are OK with the Powershell team using his answer to help build this help topic.

Here's the URL:
https://stackoverflow.com/a/55036515/1236579

**Comment by mklement0** [comment]
Thanks, @sql-sith; I'm the author of the SO answer you link to, and I'm definitely happy for it to serve as the basis for creating this documentation.

**Comment by vexx32** [comment]
Nowhere is safe from @mklement's thorough answers. 😉

**Comment by sql-sith** [comment]
> Nowhere is safe from @mklement's thorough answers.
I have come to see that! Armed with the very useful phrase *Namespace Variable Notation*, I have been reading articles, and the last one I saw had a very good explanation of the topic from none other. Rock star!  :-)
