### ISSUE TITLE
Introduce a new conceptual topic that explains to-Boolean coercion logic ("truthiness")

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3356]
PowerShell can treat any type implicitly as a Boolean, which is generally very handy, but can be problematic if the rules aren't clear.

The rules are summarized below, and I hope they'll become the basis for a new conceptual topic such as `about_Booleans`.

The following topics should then be updated to point to the new topic:

* `about_If`
* `about_While`
* `about_Do`
* `about_Arrays` (the section about the `.Where()` method)
* `Where-Object`
* Others?

---

**To-Boolean conversion summary**:  

* **Among *scalars***:
  * The following are implicitly `$false`: 
     * `''`/`""` (empty string)
     * `$null`
     * `0` (of any numeric type).
  * **Pitfall**: *Any non-empty* string evaluates to `$true`
     * e.g., `[bool] 'False'` is `$true`
     * Note that this differs from *explicit string parsing*: `[bool]::Parse('false')` does return`$false` (and `$true` for `'true'`, but recognizes nothing else).

  * Instances of any other (non-collection) type are implicitly `$true`, including of type `[pscustomobject]`.

* **Among _collections_** such as _arrays_ (more accurately, collection-like types that implement the [`IList`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist) interface - see [the source code](https://github.com/PowerShell/PowerShell/blob/eb92b14433ab62edaf0afe95312d9859170efe1d/src/System.Management.Automation/engine/LanguagePrimitives.cs#L1021)):
  * _Empty_ collections are always `$false`, as is the special "null collection" value indicating the absence of output from a command, `[System.Management.Automation.Internal.AutomationNull]::Value`.  
  * **Pitfall**: *Single-element* collections evaluate to the Boolean value of their one and only element.
  * 2+-element collections are always `$true`.

**Comment by sdwheeler** [comment]
NOTE: Type conversion is covered in detail in Chapter 6 of the PowerShell Language Specification. It may be best to just convert that chapter to docs.
