### ISSUE TITLE
Consider creating a conceptual help topic for calculated properties

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3383]
Calculated properties can be used with many cmdlets (`Select-Object`, `Format-*`, `Sort-Object`, `Group-Object`, `ConvertTo-Html`, possibly others, and, since v6.1, `Measure-Object`).

They're an important concept, yet only mentioned tersely in the context of the `-Property` parameter description.

I think a dedicated conceptual topic that the cmdlet topics can link to would help, along the lines of `about_Calculated_Properties`.

Things that should be covered:

* The hashtable keys need not be spelled out, as long as the specified name prefix is unambiguous, so that `n` can be used in lieu of `Name`, and `e` in lieu of `Expression`.

* You may specify the expression script block _directly_ as an argument (as opposed to specifying it as the `Expression` entry of an enclosing _hashtable_), e.g., `'1', '10', '2' | Sort-Object { [int] $_ }`, which is convenient for cmdlets that do not require (or support) _naming_ a property via the `Name` key, such as `Sort-Object`, `Group-Object` and `Measure-Object`
  * In fact, `Measure-Object`, unlike the other cmdlets, doesn't support passing a hashtable at all, and only accepts a script block, because its `-Property` parameter is `psropertyexpression[]` typed, not `[object[]]` typed.
  * Using this technique with cmdlets that do support a `Name` key for naming the property will automatically use the script block's _stringified content_ as the name.

* Pipeline logic is applied to the output from `Expression` script blocks, which means that outputting a single-element array will cause that array to be unwrapped.

* Errors  inside expression script blocks are quietly ignored.
   * Except in `Sort-Object`, where statement- and script-terminating errors are _output_, but they do not terminate the statement.

* Expression script blocks run in _child_ scopes (meaning that the caller's variables cannot be directly modified).

**Comment by mklement0** [comment]
@matt9ucci, it would help if you clarified your thumbs-down vote; which aspect(s) of the proposal are you objecting to?

* The information detailed in the original post is not currently documented, as far as I'm ware. Do you think it shouldn't be documented? If so, why?

* Are you specifically objecting to creating a _dedicated topic_ for this issue? If so, why, given that the information is clearly a _cross-cmdlet concern_?

**Comment by doctordns** [comment]
I teach PowerShell around the globe, and know that hash-table caculated properties are both an important aspect but also quite complex and confusing.
1. Yes Please for a conceptual help file on this topic. the OP has some key contents. 
2. PLEASE: any examples should use the full hash key name, not the abbreviation. So **NAME=** not **N=**, etc.
3. Please consider having at least one example for every use case.
4. Consider updating about_hashtables to point to this new help text (along the lines of "hash tables can be used to calculate values, see about_.xxx for more information).

**Comment by matt9ucci** [comment]
@mklement0 The former PowerShell-Docs admin [says](https://github.com/PowerShell/PowerShell-Docs/issues/1765#issuecomment-337012017):
> The beauty of being an open sourced community is that everyone can make suggestions; but, most important **everyone can make contributions.**

I would like you to consider writing real documents and PRs before opening issues. For example, [`Format-Custom`](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Format-Custom?view=powershell-6), [`Format-Table`](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Format-Table?view=powershell-6), and [`Select-Object`](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Select-Object?view=powershell-6) in PowerShell v3.0 to v6.1. They look similar but have different key sets.

After the PRs are successfully approved, you will be easily able to push the another PR of the conseptual doc and just say "Hey, I wrote a new conseptual doc. It is a copy of Format-Custom and some additional conseputual descriptions."

I think such combination, real documents and progressive changes, is the most effective solution for smooth discussion and document improvement.

**Comment by mklement0** [comment]
Amen to that, @doctordns.

Re 2:
It's definitely worth recommending that full key names be used _in scripts_, for readability and longterm stability of the code, similar to how aliases should be avoided in scripts.

But as a part of PowerShell's "elastic syntax" for ad-hoc, command-line use, it's worth documenting the `l`/`n` and `e` shortcuts, not least because they're common and convenient.

That said, it would help the stability problem if the `l`/`n` and `e` were locked in as _aliases_ of `label` / `name` and `expression`, so that even introducing keys later that start with the same letters don't break old code - see https://github.com/PowerShell/PowerShell/issues/8429

**Comment by doctordns** [comment]
I see two separate issues:
1. Locking in certain key abbreviations as formal aliases. I am not fully convinced this is helpful. So long as key names are unambiguous in a given hash table, I can't see the value of a formal alias.  
2. How to document the use of hash tables in calculating values for commands. A conceptual help about_calculated properties would be useful.

Re number 2, such a document would be along the lines of:
a) What, in general, is a calculated property and why use one. 
b) how do you create calculated properties (ie using hash tables with pre-defined key names)
c) How to use calculated properties
d) Cmdlet specific valid hashtable key names
e) Examples, examples, examples.

**Comment by mklement0** [comment]
@matt9ucci:

> everyone can make contributions.

Proposing a new topic _is_ a contribution.

> I would like you to consider writing real documents and PRs before opening issues.

How is that related to whether this proposal has merit?

> They look similar but have different key sets.

I don't understand what point you're trying to make: Because they have different key sets they're not fundamentally the same thing? It's too much wok? See table below.

> you will be easily able to push the another PR of the conceptual doc

Again, how is _who_ implements the proposal related to whether it has merit?

> progressive changes

Crucial conceptual information missing from the documentation does not call for _progressive_ changes.

----

### Overview of which cmdlets support what key sets

Note: The information below comes from inspecting [`SetEntries()` calls](https://github.com/PowerShell/PowerShell/blob/a1299cd6d4e649b5e42edbbdc23a5bb1c74d82a0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/select-object.cs#L58) in the _current_ source code. It matches the individual help topics, except for `Format-List` - see #3391
I don't know whether _earlier_ PowerShell versions supported fewer keys.

Cmdlet                      |  Supported Keys | Comment
 ------- | ----------------- | ---------
`Select-Object` | `name` / `label`, `expression`
`Format-Table` | `name` / `label`, `expression`, `formatstring`, `width`, `alignment` | `alignment` must be `'left'` or `'center'` or `'right'`, `width` must be an  integer greater than `0`.
`Format-List` | `name` / `label`, `expression`, `formatstring` | The same set applies to the `-GroupBy` properties for all `Format-*` cmdlets.
`Format-Wide` | `expression`, `formatstring`
`Format-Custom` | `expression`, `depth`
`Group-Object` | `expression`
`Sort-Object` | `expression`, `ascending` / `descending`
`ConvertTo-Html` | `label`, `expression`,  `width`, `alignment` | Note that alias `name` for `label` is currently not supported, and `width` currently has to be a string(!), and specifying an `[int]` - the same way that `Format-Table` _requires_ - is not supported. These issues will go away when https://github.com/PowerShell/PowerShell/pull/8426 is published. 
`Measure-Command` | none, only direct passing of script block | This is an unfortunate inconsistency. While it's simpler anyway to just pass a script block directly, using a hashtable with key `Expression` should also be supported, as with `Group-Object`.

**Comment by mklement0** [comment]
@doctordns: Fully agreed re 2.

> I am not fully convinced this is helpful. So long as key names are unambiguous in a given hash table, I can't see the value of a formal alias.

The problem is _longterm code stability_: with elastic syntax, making your code work _now_ doesn't mean that it will continue to work in _future_ PowerShell versions, because the introduction of new key names could make a previously unambiguous name prefix ambiguous, causing the command to break.

For instance, say you `l` for `label` in your calculated property definitions, which currently works fine.
If a key such as `length` is introduced in the future, your old code that uses just `l` breaks, because `l` now matches _two_ supported keys.

The proposal in https://github.com/PowerShell/PowerShell/issues/8429 would take the keys out of the realm of elastic syntax - which is still useful in the context of parameter names for ad-hoc, one-off use - and guarantee that `l` will _always_ refer to `label`, `e` to `expression`, ...
