### ISSUE TITLE
Section on PsDscAllowPlainTextPassword does not explain how the warning applies to the example

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/PowerShell-Docs#3384]
At https://docs.microsoft.com/en-us/powershell/dsc/configdatacredentials, the example under "Handling Credentials in DSC" generates two errors (expected).  The section paraphrases the first error as "plain text passwords are not recommended".  This explanation creates cognitive dissonance with the example, which never uses a plain text password.  

Specifically, the example uses Get-Credential to obtain a SecureString, so the password is never actually stored in plain text.  Rhetorical questions:  Is the password in plain text in memory?  Is it stored as plain text in the MOF file?  Is it encrypted in the MOF file but in an inherently insecure way?  Explain.  

The threats associated with plain text passwords are obvious, but the threats associated with Get-Credential are less so.  An explanation is necessary to properly understand the implications of using {PSDscAllowPlainTextPassword = $true} when there is no apparent plain text password.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80aaee45-2be4-0716-db87-01f03ba0d2fe
* Version Independent ID: d9e1afad-6055-1da2-e935-6e84e2d08a92
* Content: [Credentials Options in Configuration Data](https://docs.microsoft.com/en-us/powershell/dsc/configdatacredentials)
* Content Source: [dsc/configDataCredentials.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configDataCredentials.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by bobbytreed** [comment]
This is closed by #3495

**Comment by bobbytreed** [comment]
More clarification is needed, so I am reopening this.

**Comment by bobbytreed** [comment]
Closed by #3630
