### ISSUE TITLE
sorting strings as numbers

### ISSUE THREAD

**Issue by qt3m45su0najc7** [MicrosoftDocs/PowerShell-Docs#3399]
Would be nice to have an example on how to coerce strings as numbers for sorts in numeric orders. Ordinarily '12345' would sort before '77', but you may want to have the string coerced or evaluated as a number prior to sorting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9d9d61-86d7-ecd8-efc1-67c66083e184
* Version Independent ID: 4d53643b-68f8-5bd9-1552-d5cea633f284
* Content: [Sort-Object (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Sort-Object.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Sort-Object.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This might be a good addition to the samples.

**Comment by sdwheeler** [comment]
@qt3m45su0najc7 Do you have a specific use case scenario?

**Comment by qt3m45su0najc7** [comment]
A folder contains powershell code and links to data folders.  The code references the lnk files which in trun point to data folders.  Rather than creating scaffolding within the code (is it prod? then do this. is it test?  then do that? is it 'new prod'? then another switch., Simply reporint the lnk to the target data folders.

Is that sufficient?

**Comment by qt3m45su0najc7** [comment]
Use case (this may be addressible @sdwheeler , btw, by casting [int] on the string, which I hadn't thought of):
You are given  a list of numeric product ids.  They range from '0' to '999999'.  Sort in numeric order.
