### ISSUE TITLE
Information missing from the Set-AuthenticodeSignature and Get-AuthenticodeSignature topics

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3408]
Missing from `Set-AuthenticodeSignature`:

* Parameter `-Content` is technically available, but the underlying functionality is _not implemented_, as also indicated by the [source code](https://github.com/PowerShell/PowerShell/blob/5478cf6f6696f467622ebb0c9ab10fe6cfbadcfe/src/Microsoft.PowerShell.Security/security/SignatureCommands.cs#L570-L573); that is, you get error `Set-AuthenticodeSignature : The method or operation is not implemented.`

Missing from `Get-AuthenticodeSignature`:

* Parameter `-Content` only properly processes a byte array [if the bytes represent "Unicode" (UTF-16LE)-encoded characters](https://github.com/PowerShell/PowerShell/blob/5478cf6f6696f467622ebb0c9ab10fe6cfbadcfe/src/Microsoft.PowerShell.Security/security/SignatureCommands.cs#L291-L294). That is, passing the bytes of a file that uses any other encoding (UTF-8, "ANSI", ...) is not supported, and obscurely reports the input as `NotSigned`.

* Description of parameter `-SourcePathOrExtension` is lacking:

> Path to the file or file type of the content, on which digital signature is retrieved.

I can see wanting to supply the file path of the originating script, but when would you use the `OrExtension` ("file type of the content") part?

A [comment in the source code](https://github.com/PowerShell/PowerShell/blob/5478cf6f6696f467622ebb0c9ab10fe6cfbadcfe/src/Microsoft.PowerShell.Security/security/SignatureCommands.cs#L81) cryptically states:

> /// Gets or sets the file type of the byte array containing the content with
        /// digital signature.

Also note that only values ending in `.ps1, psm1, ...` (irrespective of whether they refer to existing files) result in the output object properly reporting the signature status; any other values cause a fixed `NotSigned` status, irrespective of whether the bytes themselves represent code with a valid signature.

In general, it would help if the topics stated what the typical use case for `-Content` + `-SourcePathOrExtension` is.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by abatishchev** [comment]
B
