### ISSUE TITLE
Incorrect Example 2: Copy the contents of a directory to another directory

### ISSUE THREAD

**Issue by anhlqn** [MicrosoftDocs/PowerShell-Docs#3409]
Running Copy-Item "C:\Logfiles" -Destination "C:\Drawings" -Recurse actually copies "Logfiles" directory into C:\Drawings, not just the entire contents of the "Logfiles" directory, unless the "entire contents" implies that the folder itself is also included.

The following command does what the example describes:
Copy-Item "C:\Logfiles\*" -Destination "C:\Drawings" -Recurse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d43a273-8846-1294-e3a0-486f1bfb3d44
* Version Independent ID: 1eace7de-83aa-39a7-7a19-862e9e37b5f7
* Content: [Copy-Item (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by aavdberg** [comment]
Had the same problem, when try your option it's still not working.

Copy-Item "C:\Logfiles\*" -Destination "C:\Drawings" -Recurse

is working.

**Comment by aavdberg** [comment]
Nice site strips \

**Comment by aavdberg** [comment]
Copy-Item "C:\Logfiles\*" -Destination "C:\Drawings" -Recurse

**Comment by aavdberg** [comment]
Copy-Item "C:\Logfiles\\*" -Destination "C:\Drawings" -Recurse
