### ISSUE TITLE
ConvertFrom-Json/ConvertTo-Json help references system.web.script.serialization.javascriptserializer

### ISSUE THREAD

**Issue by FireInWinter** [MicrosoftDocs/PowerShell-Docs#3456]
Issue Details
-----------------
ConvertFrom-Json and ConvertTo-Json have NOTES sections that says they are implemented by using the JavaScriptSerializer class "https://msdn.microsoft.com/library/system.web.script.serialization.javascriptserializer".  However I don't think that PowerShell 6+ is using that.  I believe that PowerShell 6.0 and beyond use Newtonsoft.Json.  The documentation should be changed to reflect that.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by bobbytreed** [comment]
Closed by #4373
