### ISSUE TITLE
Articles exist for 'Installing PowerShell Core' when documentation is viewed for versions 3.0 to 5.1

### ISSUE THREAD

**Issue by xtqqczze** [MicrosoftDocs/PowerShell-Docs#3487]
When documentation is viewed for versions 3.0 to 5.1, there are articles about 'Installing PowerShell Core', which does not make any sense as PowerShell Core builds do not exist for these versions. Additionally, these articles exist for unsupported platforms such as Linux, macOS and ARM.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by doctordns** [comment]
Strictly speaking, there are no PowerShell version specific documents for this page - there is but a single page in the docs-conceptual branch. ANd no matter which version of PowerShell you choose, you should see the same identical document. So this is more a feature than a bug.

I suppose the docs platform team could figure a way to omit the version selection box for conceptual documents like this, but I suspect it a) would be a fair degree of work testing and sorting out the weird edge cases and would probably not be high on the teams' priority list. @joeyaiello might have a view.

**Comment by sdwheeler** [comment]
@doctordns is correct. This is an outstanding work item to fix version-specific docs for conceptual articles.

**Comment by xtqqczze** [comment]
@sdwheeler Is there a Github issue for this work item?

**Comment by sdwheeler** [comment]
Since Windows PowerShell and PowerShell (core) can be installed side-by-side, having the docs side-by-side is not much of an issue.

We may eventually get to versioned conceptual content, but closing this for now.
