### ISSUE TITLE
about_Switch requires fixes and improvements

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#3512]
### Use of an expression vs. a script block as  a branch condition:

> If the condition is an expression or a script block, it is evaluated just before it is compared to the value. The value is assigned to the $_ automatic variable and is available in the expression. The match succeeds if the expression is true or matches the value. The expression is evaluated in its own scope.

Use of an _expression_ vs. use of a _script block_ are distinct use cases that must be documented separately:

* `$_` is only available in a script block, and running it is own scope also only applies to use of a script block.

* While an expression's result must match the input the _input value_, a script block is expected to return a _Boolean_ - see https://github.com/PowerShell/PowerShell/issues/8591

###  The precedence rules if conflicting options such as `-wildcard` and `-regex` are combined are incorrect; e.g.: 

> If you use Wildcard, Regex and Exact are ignored

In reality, whatever option is specified _last_ wins, and any conflicting ones are ignored.

Note the related proposal to prevent conflicts to begin with during parsing: https://github.com/PowerShell/PowerShell/issues/8598

### Improvements

`-exact` should be documented as an option, explicit way to opt into the _default_ behavior that is never _needed_; see https://github.com/PowerShell/PowerShell/issues/8599

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by bobbytreed** [comment]
closed by #4368
