### ISSUE TITLE
Document how to use the PS Core preview binary in VS Code + w/ admin

### ISSUE THREAD

**Issue by colemickens** [MicrosoftDocs/PowerShell-Docs#3536]
As far as I can tell, there is no easily discoverable exact snippet needed to do debugging in VS Code with an admin PowerShell instance. Since this page exists, maybe it would be good if this page documented the changed needed in VS Code for:
  1.  using 'pwsh.exe' as the integrated terminal
  2.  using 'pwsh.exe', as admin, as the integrated terminal
  3.  using 'pwsh.exe' as the debugger
  3.  using 'pwsh.exe', as admin, as the debugger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92497070-504a-7239-dce7-ba7c23426514
* Version Independent ID: eb1fa4c2-2692-df5d-691a-78551edf6abb
* Content: [How to replicate the ISE experience in Visual Studio Code](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/how-to-replicate-the-ise-experience-in-vscode?view=powershell-6)
* Content Source: [reference/docs-conceptual/components/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by tommysundling** [comment]
Since the page describes how you can change the configuration file to modify the behavior of VS Code it would be helpful if the page also let the reader know how to access the configuration file.

Not too hard to find, but it requires searching unless the user is experienced at VS Code already.

**Comment by sdwheeler** [comment]
@TylerLeonhardt Can you respond to this?

**Comment by TylerLeonhardt** [comment]
> As far as I can tell, there is no easily discoverable exact snippet needed to do debugging in VS Code with an admin PowerShell instance.

You should just be able to start VS Code as Admin. Then the PowerShell that gets created inside would be Admin as well. This is no different than launching PowerShell as Admin.

> using 'pwsh.exe' as the integrated terminal
> using 'pwsh.exe', as admin, as the integrated terminal
> using 'pwsh.exe' as the debugger
> using 'pwsh.exe', as admin, as the debugger

I'm not sure I understand the difference between 1 and 3... and 2 and 4...

> Since the page describes how you can change the configuration file to modify the behavior of VS Code it would be helpful if the page also let the reader know how to access the configuration file.

Totally reasonable. I'll send a small PR in a sec for that.

**Comment by sdwheeler** [comment]
Fixed by #5618
