### ISSUE TITLE
Table that explains all supported remoting scenarios

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3546]
Issue Details
-----------------

Motivated by [this Twitter thread](https://twitter.com/markekraus/status/990609783018414081), we could really use a table that outlines which versions/editions of PowerShell support which protocols (and with which limitations). 

Screenshot for posterity:

![image](https://user-images.githubusercontent.com/1255187/51138868-295f8e80-17f7-11e9-9dc0-a86cb8a97720.png)

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
This table does not imply support. 
- Windows-to-Windows remoting using WinRM is the only implementation that supports all of the features of PowerShell remoting. 
- Remoting to/from non-Windows platforms using WinRM+OMI is not supported. 
  - OMI is required by WinRM but it is not supported on all platforms. 
  - OMI is being deprecated
- SSH remoting is also limited but provides the best remoting experience for non-Windows platforms.

## PowerShell remoting table

| From Platform | To Platform | PowerShell Version |  Transport  |                                           Notes                                           |
| ------------- | ----------- | ------------------ | ----------- | ----------------------------------------------------------------------------------------- |
| Windows       | Windows     | PowerShell 2.0+    | WinRM       | Original remoting transport. Supports all features.                                       |
| Linux         | Windows     | PowerShell 6.0+    | WinRM + OMI | Implementation incomplete. Not all platforms supported. Basic authentication.             |
| macOS         | Windows     | PowerShell 6.0+    | WinRM + OMI | Implementation incomplete. Not all platforms supported. Basic authentication.             |
| Windows       | Linux       | PowerShell 6.0+    | WinRM + OMI | Implementation incomplete. Not all platforms supported. Basic authentication.             |
| Windows       | macOS       | PowerShell 6.0+    | WinRM + OMI | Implementation incomplete. Not all platforms supported. Basic authentication.             |
| Windows       | Windows     | PowerShell 6.0+    | SSH         | Implementation incomplete. All platforms supported. SSH must be installed and configured. |
| Windows       | Linux       | PowerShell 6.0+    | SSH         | Implementation incomplete. All platforms supported. SSH must be installed and configured. |
| Windows       | macOS       | PowerShell 6.0+    | SSH         | Implementation incomplete. All platforms supported. SSH must be installed and configured. |
| Linux         | Windows     | PowerShell 6.0+    | SSH         | Implementation incomplete. All platforms supported. SSH must be installed and configured. |
| macOS         | Windows     | PowerShell 6.0+    | SSH         | Implementation incomplete. All platforms supported. SSH must be installed and configured. |
| Linux         | macOS        | PowerShell 6.0+    | SSH         | Implementation incomplete. All platforms supported. SSH must be installed and configured. |
| macOS         | Linux        | PowerShell 6.0+    | SSH         | Implementation incomplete. All platforms supported. SSH must be installed and configured. |

**Comment by sdwheeler** [comment]
We no longer support remoting using WinRM/OMI for non-Windows systems. You must use SSH instead.
