### ISSUE TITLE
Consider adding how to hide the "Debug Console" in VSCode to the ISE Compatibility doc

### ISSUE THREAD

**Issue by TylerLeonhardt** [MicrosoftDocs/PowerShell-Docs#3552]
I just saw this tweet:
https://twitter.com/Tyriar/status/1085183089712685057?s=19

Which shows that you can hide panes at the bottom. 

If the user is only using the PowerShell extension for VSCode (or rather... Is only working on PowerShell scripts in vscode), It might be worth adding a small line or 2 to the ISE Compatibility doc under the vscode section to say:

If you only plan on using VSCode for PowerShell scripting, you can hide the "Debug Console" since it is not used by the PowerShell extension. To do so, right click on "Debug Console" and click on the check mark to hide it.

What we've found is that occasionally users get tripped up while debugging PowerShell scripts by getting confused if they should be using the Debug Console or the PowerShell Integrated Console.

Thoughts?
@rjmholt @rkeithhill @seeminglyscience @Stevel-MSFT @sydneyhsmith

**Comment by rjmholt** [comment]
Yeah this sounds like a good idea to me

**Comment by rkeithhill** [comment]
I wish VSCode had some support for terminal/REPL style debuggers where we could declare our debugger does not use the Debug Console (then VSCode would determine if it should hide that window during a debug session).  Short of that, I guess documenting this is the best we can do.
