### ISSUE TITLE
EditMode details

### ISSUE THREAD

**Issue by dougbreaux** [MicrosoftDocs/PowerShell-Docs#3553]
Could use some details on what the various EditModes are and at least links on information about each.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 801e7046-e140-f89e-6f4e-700c9503107c
* Version Independent ID: 18945940-0df3-1027-612f-2adf6291d22d
* Content: [Set-PSReadLineOption (PSReadLine)](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-6)
* Content Source: [reference/6/PSReadLine/Set-PSReadlineOption.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PSReadLine/Set-PSReadlineOption.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by yobyot** [comment]
This is a good example of what's wrong with the PowerShell doc. It's got info -- but is only useful to those who _already understand the cmdlet_ (essentially, the developers) or those who have enough time to laboriously experiment with each option and blog about it.

Bottom line, a page of "doc" that lists all possible options but doesn't describe any of them isn't especially useful.

**Comment by SteveL-MSFT** [comment]
This is a good issue, but should be opened in the https://github.com/lzybkr/PSReadLine repo

**Comment by SteveL-MSFT** [comment]
@dougbreaux unfortunately it can't be moved because that repo is in a different GitHub org.  PSReadLine is a module we ship in PowerShell, but is owned by @lzybkr

**Comment by lzybkr** [comment]
@SteveL-MSFT - this repo has a fork of the original documentation.

I'm not sure how changes are being managed though. People are making corrections here that don't happen upstream.

**Comment by lzybkr** [comment]
@SteveL-MSFT - pulling docs from here would mean not documenting features until they're released. I think it's better to document features when they're added - I even have automation to enforce that.

**Comment by TylerLeonhardt** [comment]
Does this change now the PSReadLine lives under PowerShell?

**Comment by lzybkr** [comment]
I hope that automation to require documentation doesn't go away, but it could be deferred to release. That might be a mistake though - a contributor is more likely to write some documentation before the feature is merged.

Where that documentation lives is another matter. Docs for a newer version could live in a branch, but that doesn't solve the single source of truth - docs are either in 2 branches, or 2 repos. Some things would be easier with branches (merging changes), but some things would be harder (producing builds and test automation).

**Comment by SteveL-MSFT** [comment]
@sdwheeler can we have a psreadline.vnext type branch here for new docs for features added to next release of PSReadLine?  That way we can use the same process we have for PowerShell which is when new features are added, the documentation PR gets opened here and the two are linked.

**Comment by sdwheeler** [comment]
@SteveL-MSFT @lzybkr I created a release branch and a new milestone for PSReadline vNext.
