### ISSUE TITLE
Add in additional Example that shows for usecases where you are thinking of publishing to the PowerShell Gallery

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#3583]
As per the closing comments in https://github.com/PowerShell/PowerShellGetv2/issues/405 this raises a need to add in some additional details in the help for this command that includes adding a new Example - I will happily write this if needs be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108e9efe-a3e5-2257-3685-2ac7669de6e6
* Version Independent ID: 8a82c347-8653-4cbd-232f-d5018bf76de9
* Content: [New-ModuleManifest (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@kilasuit I welcome your contribution.

**Comment by kilasuit** [comment]
I'll get this done by the end of the weekend 😃

**Comment by sdwheeler** [comment]
@kilasuit Have you had a chance to work on this yet?
