### ISSUE TITLE
Set-Culture does not work in remote server

### ISSUE THREAD

**Issue by quickware** [MicrosoftDocs/PowerShell-Docs#3585]
The following command does not change the UI culture on remote machine.

$server = "xyz"
Invoke-Command -ComputerName $server -ScriptBlock{
            #Requires -RunAsAdministrator
            Set-Culture -CultureInfo en-GB;            
            Set-TimeZone -id "GMT Standard Time"
            Get-UICulture                  
            Get-Culture            
        }

**Comment by doctordns** [comment]
Set-Culture does not seem to work locally either:
```powershell
PS [C:\foo> ]> get-culture                                                                                              
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
PS [C:\foo> ]> set-culture no-nb
PS [C:\foo> ]> get-culture                                                                                              
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
```

**Comment by sdwheeler** [comment]
This issue was moved to PowerShell/PowerShell#8856
