### ISSUE TITLE
Need PSGallery network endpoints for whitelist

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/PowerShell-Docs#3592]
Would this be an appropriate place to share info on how to find and whitelist endpoints for PSGallery in environments with restricted Internet access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27629d2-7baa-8f66-369d-d597d53bb842
* Version Independent ID: 9523376f-b953-a7ec-aa21-3e580c5a4034
* Content: [Get Started with the PowerShell Gallery](https://docs.microsoft.com/en-us/powershell/gallery/getting-started)
* Content Source: [gallery/getting-started.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/getting-started.md)
* Product: **powershell**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by sdwheeler** [comment]
@SydneyhSmith Do we have this information available anywhere?

**Comment by SydneyhSmith** [comment]
This is described in [an issue](https://github.com/PowerShell/PowerShellGet/issues/331#issuecomment-446008624) but out powershellgaller.com and azureedge domains probably should be added to our gallery docs

**Comment by sdwheeler** [comment]
These DNS names listed are the only ones we expect to use for now. 
- psg-prod-eastus.azureedge.net -for CDN hostname
- devopsgallerystorage.blob.core.windows.net - for storage account host

Allowing access to *.powershellgallery.com would be a good idea to future-proof access.
