### ISSUE TITLE
PS 5.1 Get-ChildItem -Depth parameter

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/PowerShell-Docs#3601]
Hi,

I need to create a script to search (and delete in second step) many files but in a specific subfolders depth. I said: Wow, I will can do that with PowerShell without problem because since PS 5.0 it include an option "-depth" to limit the subfolder search to a specific level.

![depth_parameter](https://user-images.githubusercontent.com/17770263/51686657-c328f780-1fbe-11e9-8c69-5a798cc40dc3.PNG)

I tried it and I was surprized that option is not working... The script still scannig more deep (no limit in depth) even with the -depth option.

Chek my screenshot that show the script and the result inside PowerShell ISE:

![sample](https://user-images.githubusercontent.com/17770263/51687004-945f5100-1fbf-11e9-90ec-363ec553b510.PNG)

If this a known issue, let me known if the fix is in progress (or already fixed in version 6.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c805a7fd-13a5-6002-dc57-43d97aee00fd
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@ggbce This is fixed in the current release (v6.1.2). This is a known issue in previous versions. The Depth parameter is ignored when Include or Exclude are used.
