### ISSUE TITLE
Add documentation for new -ReplyTo parameter in Send-MailMessage

### ISSUE THREAD

**Issue by replicaJunction** [MicrosoftDocs/PowerShell-Docs#3602]
Issue Details
-----------------
Pending the acceptance of powershell/powershell#8727, the new `-ReplyTo` parameter in the `Send-MailMessage` cmdlet will need documentation added.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by replicaJunction** [comment]
The linked PR has been merged.

I don't mind working on this if it would be helpful. Is [this](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md) the correct file for documentation for version 6.next?

**Comment by rjmholt** [comment]
@joeyaiello, you might be the best person to ask here
