### ISSUE TITLE
Please provide the complete template template syntax

### ISSUE THREAD

**Issue by lord-saumagen** [MicrosoftDocs/PowerShell-Docs#3615]
Dear Ladies and Gentlemen,

unfortunately I wasn't able to find the complete template syntax in this document. The given examples show some use cases but obviously doesn't reveal the whole power of the template engine. There are some blogs and website which show more advanced use cases but still no complete reference. 
It would be nice to have an official syntax reference in one place. 

Kind regards, Lord Saumagen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad074c15-7b46-6c29-94c3-afa2959ab07d
* Version Independent ID: 74a101f5-692b-432a-7e5a-c19d67311b8f
* Content: [ConvertFrom-String (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-string?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by bobbytreed** [comment]
The official language is Prose, https://microsoft.github.io/prose/documentation/prose/syntax/. What specifically are you looking for? I can add another more detailed example

**Comment by chasewilson** [comment]
Hi @lord-saumagen , thanks for the feedback. This command is no longer supported in the latest version of PowerShell (6 & 7). There seems to be enough info in the basic examples to get started. If you have an example you would like to see, feel free to submit a PR.
