### ISSUE TITLE
Compress-Archive -Update deletes the destination if an empty source

### ISSUE THREAD

**Issue by bchris999** [MicrosoftDocs/PowerShell-Docs#3622]
$items | Compress-Archive -DestinationPath Archive.zip -Update

Assuming Archive.zip is already there, if $items contains filenames (e.g. from Get-ChildItem) it works fine. If $items is empty, it deletes the destination archive instead of adding 0 files to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e67ee59-8a3e-59ad-7c8d-a78605f55b66
* Version Independent ID: 3c8b8ee9-6a97-4eda-d184-49e728abf0a6
* Content: [Compress-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md)
* Product: **powershell**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

**Comment by sdwheeler** [comment]
@SteveL-MSFT Should this also be a product bug?

**Comment by SteveL-MSFT** [comment]
Yes, this is a product bug.  @bchris999 would you mind opening an issue in https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues?

**Comment by sdwheeler** [comment]
Shiproom notes - move to Powershell repo issues

**Comment by sdwheeler** [comment]
This issue was moved to PowerShell/PowerShell#8840

**Comment by bchris999** [comment]
https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/40

**Comment by UrpoKotipalo** [comment]
It seems that -Update parameter has been removed from the PowerShell (PSVersion 5.1.17763.771, Build 10.0.17763.771).
Error: "Compress-Archive : Parameter set cannot be resolved using the specified named parameters."
If this is the case, -Update should be removed from the documentation as well.

**Comment by sdwheeler** [comment]
@UrpoKotipalo The `-Update` parameter is present in PowerShell v5.1. You are get that error if you try to use it with `-Force`.
