### ISSUE TITLE
set-itemproperty: The -type parameter is undocumented for registry keys

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#3626]
The -type parameter is undocumented for registry keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e0a674-a543-23c4-90ae-75e2be70d026
* Version Independent ID: 524c0a7b-a2ef-5679-f6ae-a4a4cd1a10ac
* Content: [Set-ItemProperty (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-itemproperty?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Set-ItemProperty.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Set-ItemProperty.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@jszabo98 See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_registry_provider?view=powershell-6 for more complete documentation on the Registry provider.

**Comment by bobbytreed** [comment]
The cmdlet you reference Set-ItemProperty does not have a -Type parameter.  You cannot change the Type of a registry key with Set-ItemProperty.  New-ItemProperty has a -Type parameter, and a -Force parameter. So if you wanted to change a registry keys type, you could use New-ItemProperty.

**Comment by jszabo98** [comment]
> The cmdlet you reference Set-ItemProperty does not have a -Type parameter. You cannot change the Type of a registry key with Set-ItemProperty. New-ItemProperty has a -Type parameter, and a -Force parameter. So if you wanted to change a registry keys type, you could use New-ItemProperty.

`PS C:\> $a = get-item hkcu:\
PS C:\> $a


    Hive:


Name                           Property
----                           --------
HKEY_CURRENT_USER              name : hi

PS C:\> $a.GetValueKind('name')
String
PS C:\> Set-ItemProperty hkcu:\ name 0 -t DWord
PS C:\> $a


    Hive:


Name                           Property
----                           --------
HKEY_CURRENT_USER              name : 0


PS C:\> $a.GetValueKind('name')
DWord`

**Comment by jszabo98** [comment]
Here's another example of the confusion over this:  https://stackoverflow.com/questions/56566586/registry-key-edited-but-policy-still-disabled

**Comment by sdwheeler** [comment]
@bobbytreed Can you revisit this doc?

**Comment by JulioQc** [comment]
Came here specifically for the TYPE flag and I see it isn't a thing yet... please adjust the doc

**Comment by jszabo98** [comment]
I just learned this.  You can see the -type parameter with get-command.

```powershell
gcm set-itemproperty -args hklm: -syntax

Set-ItemProperty [-Path] <string[]> [-Name] <string> [-Value] <Object> [-PassThru] [-Force] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Type <RegistryValueKind>] [<CommonParameters>]

Set-ItemProperty [-Path] <string[]> -InputObject <psobject> [-PassThru] [-Force] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Type <RegistryValueKind>] [<CommonParameters>]

Set-ItemProperty [-Name] <string> [-Value] <Object> -LiteralPath <string[]> [-PassThru] [-Force] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Type <RegistryValueKind>] [<CommonParameters>]

Set-ItemProperty -LiteralPath <string[]> -InputObject <psobject> [-PassThru] [-Force] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Type <RegistryValueKind>] [<CommonParameters>]
```

**Comment by JulioQc** [comment]
Great, that points me here to check [-Type <RegistryValueKind>] at https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registryvaluekind?view=netframework-4.8
