### ISSUE TITLE
Invoke-RestMethod only returns body information

### ISSUE THREAD

**Issue by RogerBestMsft** [MicrosoftDocs/PowerShell-Docs#3633]
Issue Details
----------------
The documentation doesn't mention that the Invoke-RestMethod only returns the body information.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by markekraus** [comment]
What suggestions do you have to improve the description?

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6#description

```none
PowerShell formats the response based to the data type. For an RSS or ATOM feed, PowerShell returns the Item or Entry XML nodes. For JavaScript Object Notation (JSON) or XML, PowerShell converts (or deserializes) the content into objects.
```
