### ISSUE TITLE
Document String -> Number Conversion Paths & Support

### ISSUE THREAD

**Issue by vexx32** [MicrosoftDocs/PowerShell-Docs#3650]
Issue Details
-----------------

### v6.Next

Going forward, PR https://github.com/PowerShell/PowerShell/pull/8681 has been merged and will most likely end up in the next release of PowerShell Core. This adds missing support for some conversion pathways for recognisable number literals stored as strings to be converted into proper numbers when requested, reliably and consistently. This change in behaviour should be documented.

### Previous Versions (6.0 and below)

The pre-existing behaviour is described in full in https://github.com/PowerShell/PowerShell/issues/7710

A brief summary and explanation is the following:

* `1kb -eq 1024` - returns `$true`
* `[int]"1kb"` - will throw an error
* `("1kb" / 1) -eq 1024` - returns `$true`

In short, when evaluated as part of an _explicitly mathematical_ expression, strings containing either a _multiplier_ or _type_ suffixed numeral (e.g., `"1gb"` or `"100.40d"`) can be converted. However, in an explicit cast, during parameter binding, and in any situations other than a _strictly mathematical expression_ (use of division, modulo, or subtraction operators, or attempting to add such strings to a known numeric LHS value (e.g., `100 + "1gb"`), the casting will _fail_.

This inconsitency has been fixed in the referenced PR and will be changed in v6.Next.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [X] Impacts 3.0 document

As always, if you need any further clarification, please just let me know and I'll try to clear up my phrasing further. 🙂

**Comment by TylerLeonhardt** [comment]
Talked to @joeyaiello about this. The value-add doesn't seem worth it. Closing...
