### ISSUE TITLE
What happens to any resources in the job

### ISSUE THREAD

**Issue by Shawson** [MicrosoftDocs/PowerShell-Docs#3659]
If the job has file system watchers open or event subscriptions, are these properly disposed of when removing the job?  If not, is there a way to catch the stop or remove event from within the job to do some kind of graceful clean up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a795adea-ab25-3201-de65-7380585c668b
* Version Independent ID: 42b59d38-3b16-ff83-99a3-0f71a617edf1
* Content: [Remove-Job (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/remove-job?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Remove-Job.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Remove-Job.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by SteveL-MSFT** [comment]
A PSJob is a new process.  When the job completes, that process goes away.  State for that job exists until Remove-Job is called (or the hosting process itself goes away).  When the process exits, normal cleanup will occur.

**Comment by joeyaiello** [comment]
Agreed with @sdwheeler and @SteveL-MSFT that the proper doc is to inform that we create processes when we create PSJobs, and we remove their state when we run Remove-Job.

Anything out-of-proc is out-of-proc irrespective of PSJobs.

**Comment by Shawson** [comment]
Makes sense- what if the job is stopped before the job is finished, so the process hasn't yet exited?  I'd guess the process is forcibly terminated?

**Comment by SteveL-MSFT** [comment]
Yes, the process is forcibly terminated.
