### ISSUE TITLE
missed parameter 

### ISSUE THREAD

**Issue by Loomb13** [MicrosoftDocs/PowerShell-Docs#3661]
Hello,

Looks liek the -ConnectionUri paramter is missing here:
$S = New-PSSession https://ps.testlabs.com/powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf1a7c0a-f187-4b45-d12a-1a91e2e7ee13
* Version Independent ID: 624c188f-e285-b301-5d59-0e9b94e2d3a9
* Content: [Import-PSSession (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Import-PSSession?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Import-PSSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Import-PSSession.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The `-ConnectionUri` parameter of `New-PSSession` is a positional parameter. That means that the parameter name is not required.
