### ISSUE TITLE
Document changes in default view for FileSystemInfo formatting

### ISSUE THREAD

**Issue by powercode** [MicrosoftDocs/PowerShell-Docs#3665]
Issue Details
-----------------

https://github.com/PowerShell/PowerShell/pull/8789 is removing hardlinks from the rendering of Mode in the default view. It was very expensive to check if each file also was a hard link, so by default, we now only display what can be gathered from the attributes on the FileSystemInfo.

The Mode property has the same behavior as previously, i.e. it still include the hardlink info, but the default table view, `children`, is using a hidden CodeProperty, `ModeWithoutHardlink`, to provide much faster formatting.

A new view was created, `childrenWithHardlink`, that displays the same information that the previous default view, `children`, displayed. `childrenWithHardlink` still uses the slow `Mode` CodeProperty.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by adityapatwardhan** [comment]
Fixes #4044

**Comment by SteveL-MSFT** [comment]
@sdwheeler Looks like #4044 fixes this.  Can we close?
