### ISSUE TITLE
'S' format does not work, 's' format outputs seconds instead of 'S'

### ISSUE THREAD

**Issue by djeedai** [MicrosoftDocs/PowerShell-Docs#3682]
It seems the 'S' format specifier does not display seconds but a literal 'S' character.
Moreover the 's' format specifier does not display Unix epoch (in seconds), but instead the current seconds as 'S' should have according to the current documentation.

PS F:\&gt; get-date -f yyyy-MM-dd_HH-MM-SS
2019-02-10_10-02-SS
PS F:\&gt; get-date -f yyyy-MM-dd_HH-MM-ss
2019-02-10_10-02-39

Windows 10 1803 17134.523
Powershell 5.1.17134.407

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c5a5ea7-858f-5b1e-2c2f-24311876d7ac
* Version Independent ID: 09bab64d-b131-3961-a8c2-10ecf7f3d96b
* Content: [Get-Date (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Get-Date.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
I think you are confusing `-Format` and `-UFormat`. 
- The `-Format` parameter uses .NET format specifiers. See https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings.
- The `-UFormat` parameter uses Unix format specifiers as described in the NOTES section of the article.

```powershell
PS > Get-Date -UFormat "%s"
1549890850.15854
```

**Comment by hennie7863** [comment]
Get-Date -f yyyyMMddHms works but Get-Date -f yyyyMMddHmS will give an S on the end
