### ISSUE TITLE
New-* vs Add-*

### ISSUE THREAD

**Issue by MichelZ** [MicrosoftDocs/PowerShell-Docs#3684]
I've seen it more than once now that there is confusion when to use New-* vs Add-*.
Some trains of thoughts are e.g. like:

"When I can remove a resource, I need to use Add-*, because Remove-* is paired with Add-*"
(See "Common Verbs" -&gt; "Add" in the Documentation)
which for myself should not take precedence over "New-* creates a new resource". 

Can the Documentation be enhanced to make it more clear when to use Add-* vs. New-*?

As a "case study", you can use the VSTeam PowerShell Module, where I created an issue here:
https://github.com/DarqueWarrior/vsteam/issues/139

According to the Documentation here, would you use e.g.   New-VSTeamProject or Add-VSTeamProject to create a new Project?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a81c73-9edf-2815-268d-a7b294fe6bd3
* Version Independent ID: eb63eebc-a28c-be84-fd47-e7573f09e0b0
* Content: [Approved Verbs for PowerShell Commands](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands#common-verbs)
* Content Source: [developer/cmdlet/approved-verbs-for-windows-powershell-commands.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SteveL-MSFT Can you or someone provide some guidance here?

**Comment by sdwheeler** [comment]
The documentation in the approved verbs article is the accurate.

|Verb (alias)|Action|Comments|
|--------------------|------------|--------------|
|[Add](/dotnet/api/System.Management.Automation.VerbsCommon.Add) (a)|Adds a resource to a container, or attaches an item to another item. For example, the `Add-Content` cmdlet adds content to a file. This verb is paired with `Remove`.|For this action, do not use verbs such as Append, Attach, Concatenate, or Insert.|
|[New](/dotnet/api/System.Management.Automation.VerbsCommon.New) (n)|Creates a resource. (The `Set` verb can also be used when creating a resource that includes data, such as the `Set-Variable` cmdlet.)|For this action, do not use verbs such as Create, Generate, Build, Make, or Allocate.|

This has been consistent within PowerShell (the core language) but has not always been consistent across other modules that ship outside of PowerShell.

**Comment by MichelZ** [comment]
@sdwheeler So in this specific case, creating a new AzureDevOps Project, would you use New-VSTeamProject or Add-VSTeamProject?

According to that Documentation, it would be "New-VSTeamProject" because it creates a resource.
But you could also argue that it merely Adds a project to the existing Account ("container")... ?

This is confusing 🗡

**Comment by sdwheeler** [comment]
I would tend toward "New" but I am not VSTS expert. When you did this in the VSTS UI do you "Add" a project or create a "New" project?

**Comment by MichelZ** [comment]
You create a new Project:

![image](https://user-images.githubusercontent.com/1040252/53176472-6dac2e80-35ee-11e9-9834-ec8c7476f742.png)

@DarqueWarrior Are you happy with this to consider renaming them?

**Comment by DarqueWarrior** [comment]
My biggest concern is the download count for the module (255,271) means this is going to impact a lot of people. What we can do is add the New-VSTeam* names as aliaises in the SetVSTeamAliais function.

**Comment by sdwheeler** [comment]
Please resume this conversation in the DarqueWarrior/vsteam#139 thread.
Thanks.
