### ISSUE TITLE
How to get the output of the program

### ISSUE THREAD

**Issue by dariomangoni** [MicrosoftDocs/PowerShell-Docs#3693]
Capturing the output of the program seems quite difficult and requires a dozen lines of code...  
Can you please provide a basic example?

It's quite embarassing that getting the good-old console output becomes a titanic issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a91a81-81dd-f3a9-0106-23db5ee048cb
* Version Independent ID: ab184c39-041b-588c-acde-f715f6d3aee2
* Content: [Start-Process (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Start-Process.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Start-Process.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
You can pipe the output of any console application to a PowerShell cmdlet or you can assign it to a variable. For example, here are two ways to use the output of the net.exe command:

```
PS D:\> net start | Select-String -Pattern 'Windows'

These Windows services are started:
   Windows Audio
   Windows Audio Endpoint Builder
   Windows Connection Manager
   Windows Defender Antivirus Network Inspection Service
   Windows Defender Antivirus Service
   Windows Defender Firewall
   Windows Event Log
   Windows Font Cache Service
   Windows Image Acquisition (WIA)
   Windows License Manager Service
   Windows Management Instrumentation
   Windows Presentation Foundation Font Cache 3.0.0.0
   Windows Process Activation Service
   Windows Push Notifications System Service
   Windows Push Notifications User Service_18605d6
   Windows Search
   Windows Security Service
   Windows Update

PS D:\> $a = net start
PS D:\> $a -split "`n" | where {$_ -like '*Windows*'}
These Windows services are started:
   Windows Audio
   Windows Audio Endpoint Builder
   Windows Connection Manager
   Windows Defender Antivirus Network Inspection Service
   Windows Defender Antivirus Service
   Windows Defender Firewall
   Windows Event Log
   Windows Font Cache Service
   Windows Image Acquisition (WIA)
   Windows License Manager Service
   Windows Management Instrumentation
   Windows Presentation Foundation Font Cache 3.0.0.0
   Windows Process Activation Service
   Windows Push Notifications System Service
   Windows Push Notifications User Service_18605d6
   Windows Search
   Windows Security Service
   Windows Update
```

**Comment by dariomangoni** [comment]
Well, this is not the solution with Start-Process...

**Comment by sdwheeler** [comment]
@dariomangoni Why do you need to use Start-Process? Can you give an example of what you are trying to do?

**Comment by dariomangoni** [comment]
Of course.  
I have a program (OpenModelica compiler) to be called with a long list of arguments, divided by spaces (thus the & call method would force me to split the arguments in multiple pieces).
I have also to call the same program in different folders (I'm sort of batch compiling), so it's nice to use the WorkingDirectory option.
The program is not in `$env:PATH`.

There are [many ways to call a program](https://social.technet.microsoft.com/wiki/contents/articles/7703.powershell-running-executables.aspx#Start-Process_start_saps), but Start-Process seemed to give the most compact and effective approach.

By the way, I see that in PS I get less outputs compared to those that I acquire from calling the same program with CMD, no matter what calling procedure I use.
_Are there particular redirecting features in PS that I'm not aware of?_
I thought it was a Start-Process issue (like the one that is reported [here](https://stackoverflow.com/questions/8761888/capturing-standard-out-and-error-with-start-process))  but it turns out to not be the case.

**Comment by dariomangoni** [comment]
Update: I found out that the output is actually printed when I call the script from a normal PowerShell prompt instead of debugging from VSCode.

I do not know why this is happening.
