### ISSUE TITLE
Dead link:  Amazon Linux dockerfile

### ISSUE THREAD

**Issue by SepehrCloud** [MicrosoftDocs/PowerShell-Docs#3700]
Issue Details: 
The link provided in the page for Amazon Linux dockerfile is dead. This is under the section about Binary Archives - Dependencies.
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by doctordns** [comment]
Any chance you could provide the URL for the page where this error occurs? My search fu is obviously weak this morning and I can not find a page that mentions this! :-)

**Comment by sdwheeler** [comment]
@SepehrCloud Please provide the name of the affected article. Note, if you use the feedback form at the bottom of the page, it creates an issue in GitHub if information about the article you were on.

**Comment by sdwheeler** [comment]
Looks like the article is Installing-PowerShell-Core-on-Linux.md

And the correct link should be: https://github.com/PowerShell/PowerShell/blob/master/docker/community/archlinux/Dockerfile

**Comment by SepehrCloud** [comment]
I believe I did create this issue through the page itself. Anyway, here is the link to the page:

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6

**Comment by sdwheeler** [comment]
Fixed in  PR #3835
