### ISSUE TITLE
It is not clear that the `-match` operator matches only the first occurence

### ISSUE THREAD

**Issue by dariomangoni** [MicrosoftDocs/PowerShell-Docs#3701]
I think it is quite important to say that the $Matches hashtable will only contain the _first_ occurence of the matching pattern.
It is not so obvious, there are no examples regarding this fact and it is not clearly stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1473a9-d19e-26f6-6a90-13d802f0ed35
* Version Independent ID: ac918b8d-aece-5c59-2a88-64c1a91ff5f5
* Content: [about_Regular_Expressions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@bobbytreed Can you take a look at this one?
