### ISSUE TITLE
This page is not about Regular Expressions, but only to `-match` operator

### ISSUE THREAD

**Issue by dariomangoni** [MicrosoftDocs/PowerShell-Docs#3702]
Yes, I saw that there is a clear warning that the article won't show _all_ the syntaxes, but then the title is misleading.

If you don't provide examples with _any other_ operators/cmdlets please either:
- rename the article `About match operator`
- at least provide a link to the other methods *in PowerShell*

A link to the .NET Regular Expression Reference does not make the point, here is why.
There is a big difference between:
1. knowing how to write _a pattern_ with .NET regex syntax
2. knowing how to write _a code_ that makes use of that pattern, that is what we are here for...

A reference to [Regular Expression Language - Quick Reference](https://docs.microsoft.com/it-it/dotnet/standard/base-types/regular-expression-language-quick-reference) is really useful for `1`, but you leave completely unadressed the questions about `2` that is what I would like to find in a PowerShell (not a .NET, not a strictly-speaking Regex) Reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1473a9-d19e-26f6-6a90-13d802f0ed35
* Version Independent ID: ac918b8d-aece-5c59-2a88-64c1a91ff5f5
* Content: [about_Regular_Expressions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@bobbytreed Move -replace/-split/-match content from About_Comparison_Operators to this article and cross link.
