### ISSUE TITLE
Updates coming or no?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/PowerShell-Docs#3703]
Just wondering if this page is planned to be kept up to date or if it is retiring.  Any idea?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4f1ddc-a368-5668-cc15-d4d067a7997f
* Version Independent ID: 400385fb-9f5d-9231-e758-8923e54f4477
* Content: [Product Compatibility Status](https://docs.microsoft.com/en-us/powershell/wmf/5.1/productincompat)
* Content Source: [wmf/5.1/productincompat.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/wmf/5.1/productincompat.md)
* Product: **powershell**
* GitHub Login: @HemantMahawar
* Microsoft Alias: **hemantm**

**Comment by joeyaiello** [comment]
We're not *actively* maintaining this page, but it's likely that you can add a "(or greater)" to every product version listed. That being said, you're better off confirming with support for individual products whether or not they support WMF 5.1. 

We're committed to supporting WMF 5.1 (specifically **WMF**, the installer of Windows PowerShell on downlevel platforms) where high-bar servicing bugs are found, but WMF 5.1 is not being actively validated against new Microsoft products.

That being said, we still actively validate Windows PowerShell 5.1 as a Windows 10 component, but this page has always been specific to WMF, not the latest version of PowerShell available in the latest versions of Windows. Where Windows PowerShell 5.x is inbox (Server 2016/2019, Windows 10, i.e. as opposed to needing WMF), a product's OS support is inclusive of support for Windows PowerShell 5.x
