### ISSUE TITLE
get-childitem skips the properties in the top level registry key

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#3705]
Note

 that get-childitem skips the properties in the top level registry key (key1).  It is like get-childitem skipping the files in the top level folder.  

```
get-childitem hkcu:\key1


get-childitem C:\users\me\folder1
    Directory: C:\users\me\folder1
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/13/2019  11:05 AM              4 file1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c805a7fd-13a5-6002-dc57-43d97aee00fd
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
This is by design. You point out the difference between the Registry Provider and the FileSystem provider. The registry values under a registry key are not the same as files in a folder. Registry values are properties of the Key (item). They are more like attributes of a file in the filesystem. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_registry_provider?view=powershell-5.1

**Comment by jszabo98** [comment]
If a file is like a registry key, then what is a folder like?

**Comment by jszabo98** [comment]
By the way, the insert code button only inserts one backquote instead of three.

**Comment by doctordns** [comment]
@jszabo98 In the registry, A registry key is like a folder. A key can have sub keys, which can have sub keys. Each key can have item properties representing the value entries for that registry key.
