### ISSUE TITLE
Sample doesn't work

### ISSUE THREAD

**Issue by detlefs** [MicrosoftDocs/PowerShell-Docs#3706]
The sample under Dynamic ValidateSet Values doesn't work.
Defining the Class as in the sample, an error is shown:
Unable to find type [System.Management.Automation.IValidateSetValuesGenerator].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb965b0-d3fe-4343-f520-9e24f55ded23
* Version Independent ID: 4eac80f8-61be-4d0f-d657-a007ba81cf53
* Content: [about_Functions_Advanced_Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by SteveL-MSFT** [comment]
@detlefs What version of PowerShell are you using?  That interface is only in PSCore6 which is where that section in the doc only exists.

**Comment by detlefs** [comment]
OK, that explains it. I'm using 5.1, not 6.0 core

**Comment by SteveL-MSFT** [comment]
@sdwheeler I think we can close this
