### ISSUE TITLE
Invalid examples of minor versions under 'Follow SemVer guidelines for versioning'

### ISSUE THREAD

**Issue by fourpastmidnight** [MicrosoftDocs/PowerShell-Docs#3707]
The offending line is:

&gt; Changes to the second number (1.01 to 1.02) indicate feature-level changes, such as adding new cmdlets to a module

According to SemVer (at least 2.0, not sure about 1.0), leading 0's in version components are prohibited. I understand that PowerShell (and NuGet) may accept modules/packages with such version numbers. However, if you are attempting to promote the use of _valid_ SemVer, then the examples should show valid SemVer version numbers and discourage the use of invalid version numbers such as `1.01`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea9a573-6519-ba6d-bf0f-b1851c727eec
* Version Independent ID: bfeef034-ed8a-3116-111b-4905e8b229f5
* Content: [PowerShell Gallery Publishing Guidelines and Best Practices](https://docs.microsoft.com/en-us/powershell/gallery/concepts/publishing-guidelines)
* Content Source: [gallery/concepts/publishing-guidelines.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/gallery/concepts/publishing-guidelines.md)
* Product: **powershell**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by SydneyhSmith** [comment]
@fourpastmidnight good catch, thanks for reporting--should be an easy fix!
