### ISSUE TITLE
how to use multiple assignments in init of for loop

### ISSUE THREAD

**Issue by msftrncs** [MicrosoftDocs/PowerShell-Docs#3708]
The documentation indicates that the init list is a comma separated list, and then shows an example that it says won't work, but doesn't clarify how to use it.  It would be helpful if it will explain that wrapping the assignments with parenthesis is all that is required.

While looking at it, it could also use a 'see also' to 'about_break' and 'about_continue'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7405b64c-cb6f-b3ec-ad28-2537185b319f
* Version Independent ID: 2599323e-b73e-c0e5-54da-f084c92526af
* Content: [about_For](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_for?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_For.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_For.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by joeyaiello** [comment]
So basically, this doesn't work:

```powershell
for ($i = 0; $i -lt 10; $i++) {
  $i
  $j
}
```

But this does:

```powershell
for (($i = 0), ($j = 0); $i -lt 10; $i++) {
  $i
  $j
}
```

Agreed on the related, easy to do. 

It's kind of a low-pri though, would you mind submitting a PR with the change? If not, we'll get around to it at *some* point 😉

**Comment by rjmholt** [comment]
Here's a list of what **doesn't** work:

```powershell
for ($i = 0, $j = 0; $i -lt 10; $i++, $j++) { $i; $j }
```

```powershell
for (($i = 0, $j = 0); $i -lt 10; $i++, $j++) { $i; $j }
```

```powershell
for (($i = 0; $j = 0); $i -lt 10; $i++, $j++) { $i; $j }
```

Here's what **DOES** work:

```powershell
for (($i = 0), ($j = 0); $i -lt 10; $i++, $j++) { $i; $j }
```

**Comment by msftrncs** [comment]
This also works:  :)

```PowerShell
for ($($i = 0; $j = 0); $i -lt 10; $i++, $j++) { $i; $j }
```

**Comment by rjmholt** [comment]
TBH this is the kind of thing it would be nice to address in the parser, but could be error prone to fix

**Comment by msftrncs** [comment]
I understand the reason for why this is different than say C, as the three arguments of the FOR are actually regular PowerShell statements, of which the result value of only the second statement has any affect on the FOR statement.  Using a comma to separate the assignments is merely a coincidental affect of generating an array expression, and the same rules would apply anywhere else in PowerShell as well.  Once a user is aware of this condition, its easy to understand how to make it work for an intended outcome.

Maybe what would be more clear, is to not call the first argument a comma separated list, but `an array of assignment expressions.  For each assignment to be a separate expression in an array expression, they must be individually wrapped in parenthesis.`
