### ISSUE TITLE
about_splatting does not explain how to use a hash table to represent positional parameters

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/PowerShell-Docs#3713]
Section "SPLATTING WITH HASH TABLES" in the first paragraph explains that a hash table can be used for named or positional parameters.  However, the example doesn't illustrate how positional parameters should be communicated, only named.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099bc9aa-5397-0b8a-026e-a20c1bb604a2
* Version Independent ID: e12ddb02-4549-2bee-39fc-e6f902f7da25
* Content: [about_Splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@johndog You can use the hashtable for any parameter (positional or named) but you must use the name. For passing values by position only, you must use an array. This is covered in the article:

> To provide parameter values for positional parameters, in which parameter names are not required, use the array syntax. To provide parameter name and value pairs, use the hash table syntax.

**Comment by johndog** [comment]
It is addressed in a different section.  The hash table section still doesn’t explain how to address positional parameters, it only says it can be done.
Why not just fix the doc?

Sent from my Windows 10 device

________________________________

**Comment by sdwheeler** [comment]
@johndog The change you made in #3716  is not really accurate. The point is, with a hashtable, you can splat any parameter. You just have to use the parameter name because a hashtable requires name/value pairs. For example, say a cmdlet has a positional parameter in position 0, a named parameter, and a switch parameter.

Using Hashtable:
```
$args = @{ 
  NamedParam='value1'
  PositionalParam='value2'
  SwitchParam=$true
}
```
Since they are named in the hashtable they can be in any order.

Using array:
```
$args = 'value2', 'value1',$true
```
