### ISSUE TITLE
Column definitions are in the "Notes" section not the "Additional Notes" section.

### ISSUE THREAD

**Issue by csbuja** [MicrosoftDocs/PowerShell-Docs#3720]
Please correct the statement in Example 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fa6425-a4d6-8767-fe71-921ab63c460d
* Version Independent ID: 08f2c662-66be-6889-27cb-6c4a0320717a
* Content: [Get-Process (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-process?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Get-Process.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Get-Process.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
Fixed in https://github.com/MicrosoftDocs/PowerShell-Docs/pull/3733
