### ISSUE TITLE
-matches should be -match

### ISSUE THREAD

**Issue by a01fe** [MicrosoftDocs/PowerShell-Docs#3721]
The example `"Good Dog" -matches "Dog"` should be `"Good Dog" -match "Dog"`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41417680-da77-6c19-bbd0-522e694e7ff0
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by kaii3** [comment]
-matches is still being used as an operator in the [example on docs.microsoft.com](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6#groups-captures-and-substitutions).
