### ISSUE TITLE
Missing OutsideLoop in Second example of Write-Progress code.

### ISSUE THREAD

**Issue by PeterMTaylor** [MicrosoftDocs/PowerShell-Docs#3722]
I note in the second example of the Write-Progress, there is a term used but not referenced confusing me where this applies. The term is "OutsideLoop" however the -CurrentOperation mentioned OuterLoop.

Where does "OutsideLoop" fits in this picture?

for($I = 1; $I -lt 101; $I++ )
{Write-Progress -Activity Updating -Status 'Progress-&gt;' -PercentComplete $I -CurrentOperation OuterLoop; `
for($j = 1; $j -lt 101; $j++ ) `
{Write-Progress -Id 1 -Activity Updating -Status 'Progress' -PercentComplete $j -CurrentOperation InnerLoop} }
Updating
Progress -&gt;
 [ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]
OutsideLoop
Updating
Progress
 [oooooooooooooooooo                                                   ]
InnerLoop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b93648-92c2-0018-5c3d-95df5618b2ce
* Version Independent ID: 01ff8fbd-8abc-1419-0f9e-d56ddff65429
* Content: [Write-Progress (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-progress?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Write-Progress.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Write-Progress.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Fixed in https://github.com/MicrosoftDocs/PowerShell-Docs/pull/3732
