### ISSUE TITLE
Uninstall-Package not working

### ISSUE THREAD

**Issue by francesco1119** [MicrosoftDocs/PowerShell-Docs#3723]
As you can see by the picture `Get-Package *notepad*` is showing the package but `Get-Package *notepad* | Uninstall-Package -Force` is not removing it. 

![no result](https://user-images.githubusercontent.com/3397477/52939149-52f87080-33c8-11e9-9cb2-c052e027901a.png)

I tried with multiple programs: none was removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a239dc00-9858-91c9-72ed-dbcf99cfc48c
* Version Independent ID: 51100c02-3f5f-98a9-6ba2-62049da4671e
* Content: [Get-Package (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/get-package?view=powershell-6)
* Content Source: [reference/6/PackageManagement/Get-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PackageManagement/Get-Package.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you speak to this issue?

**Comment by SydneyhSmith** [comment]
I've opened an [issue](https://github.com/OneGet/oneget/issues/435) to track/debug this in the oneget repo (@francesco1119). Feel free to close the issue here @sdwheeler -thanks!
