### ISSUE TITLE
Description for -HashAlgorithm is incorrect.

### ISSUE THREAD

**Issue by FrankHeimes** [MicrosoftDocs/PowerShell-Docs#3724]
According to the description, the -HashAlgorithm supports SHA-256 or SHA-1. But when specifying either of these algorithms, they are rejected with 'Cannot sign code. The hash algorithm is not supported'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b32d55d9-df50-4579-e6ff-31904b79a9cf
* Version Independent ID: 0249e978-7402-b03f-e6ba-1bd781a58c26
* Content: [Set-AuthenticodeSignature (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-authenticodesignature?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md)
* Product: **powershell**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by sdwheeler** [comment]
I believe this is by design. The algorithm names are valid. The cmdlet is just calling the underlying API. The OS is blocking the use of those algorithms. However, the user experience is not great.

@SteveL-MSFT @TravisEz13 Can you speak to this?

**Comment by SteveL-MSFT** [comment]
The cmdlet just passes that literal string to the underlying API.  I think the problem is that the current documentation is too specific:

```
For Windows PowerShell 3.0, the default is SHA-256, which is the Windows default hashing algorithm. For Windows PowerShell 2.0, the default is SHA-1. Files that are signed with a different hashing algorithm might not be recognized on other systems.
```

Perhaps we can add a line that the supported algorithm depends on the operating system.

**Comment by FrankHeimes** [comment]
I found out some facts myself.
First of all, the algorithm needs to be specified as 'SHA256' or 'SHA1' (so without a hyphen).
Second, the function does succeed with either algorithm (on Windows 10) using most time servers.
However, it fails for http://sha256timestamp.ws.symantec.com/sha256/timestamp. That time server can only be used successfully with signtool.exe from the Windows SDK.
Fail:
  `Set-AuthenticodeSignature -FilePath 'FooBar.dll' -Certificate $Cert -HashAlgorithm 'SHA256' -TimeStampServer 'http://sha256timestamp.ws.symantec.com/sha256/timestamp'`
Success:
  `Set-AuthenticodeSignature -FilePath 'FooBar.dll' -Certificate $Cert -HashAlgorithm 'SHA256' -TimeStampServer 'http://timestamp.verisign.com/scripts/timstamp.dll'`
  `Set-AuthenticodeSignature -FilePath 'FooBar.dll' -Certificate $Cert -HashAlgorithm 'SHA1' -TimeStampServer 'http://timestamp.verisign.com/scripts/timstamp.dll'`
