### ISSUE TITLE
-Keep argument does not delete output data as documented

### ISSUE THREAD

**Issue by Brain2000** [MicrosoftDocs/PowerShell-Docs#3725]
The -Keep argument does not update the current output stream pointers after running Receive-Job, so you will see the same data twice.  However, even without the -Keep argument, all the streaming messages (output, verbose, warning, etc...) from a job always exists in its entirety and is not deleted, as stated in the documentation.

Example:
```
PS C:\> $s = New-PSSession Computer1
PS C:\> $j = Invoke-Command $s { for($i = 0; $i -lt 100; $i++) { [threading.thread]::Sleep(1000); Write-Output "test"; } } -AsJob
```
Now wait a few seconds then run this a few times.
```
PS C:\> Receive-Job $j
```
You'll see new output that was added when you run the Receive-Job. However, you can still view all the streams, as none of them are deleted, as stated in the documentation.

You can still see ALL the output is still held here:
```
PS C:\> $j.ChildJobs[0].Output
PS C:\> $j.ChildJobs[0].Verbose
PS C:\> $j.ChildJobs[0].Warning
etc...
```

This may not necessary be a bad thing, but the documentation is incorrect. It may be worth noting that the message stream buffer can grow over time to many tens of thousands of entries if you have lengthy scripts with a lots of output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67cacf45-96aa-c034-9157-e044cdc94a41
* Version Independent ID: 041a02c8-a27e-756f-9a9d-5432bf5a52ac
* Content: [Receive-Job (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/receive-job?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Receive-Job.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Receive-Job.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@SteveL-MSFT What is the intended behavior of `-Keep`? Is this a regression?

**Comment by SteveL-MSFT** [comment]
`-Keep` means that the output is preserved with the job which is normally deleted after being read.  You can see it like this:

```powershell
Receive-Job $j -Keep
Receive-Job $j -Keep
Receive-Job $j
Receive-Job $j
```

The first 3 you'll see output, the last one you should not.

If we need to make the text more clear or provide a better example, then we should do that, but it's behaving as designed.

**Comment by sdwheeler** [comment]
@SteveL-MSFT Even after running your example, the content is available using `$j.ChildJobs[0].Output` from the original comment above. Not sure the significance of this.

**Comment by SteveL-MSFT** [comment]
cc @PaulHigin

**Comment by PaulHigin** [comment]
The -Keep parameter switch only applies to *aggregated* output collected from all child jobs, and aggregated data is only exposed via the Receive-Job cmdlet.  You can still access child job stream and output data from the individual job objects, but you can retrieve aggregated output only once if the -Keep switch is not used.  I have no idea why it was designed this way.
