### ISSUE TITLE
Alias to executable with parameter

### ISSUE THREAD

**Issue by marbaa** [MicrosoftDocs/PowerShell-Docs#3731]
How can I make alias to executable which needs parameter to execute and have spaces in path? I tried many ways and still get error. Alias vi should open Far manager with parameter /e and filename from parameter.

function farvi {
	&"C:\Users\xxx\Programs\Far Manager\Far.exe /e" $args
}
Set-Alias vi farvi

PS C:\Users\xxx&gt; vi test.txt
& : The term 'C:\Users\xxx\Programs\Far Manager\Far.exe /e' is not recognized as the name of
a cmdlet, function, script file, or operable program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9decba76-2364-382c-3b58-b0ccb6ee4fc0
* Version Independent ID: 8967bae9-b8d8-e579-dab7-ac253f275aca
* Content: [Set-Alias (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/set-alias?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Set-Alias.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Set-Alias.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by doctordns** [comment]
I just tested this with an editor on my sustem:
```powershell
function x{ 
  c:\windows\notepad.exe $args
}                                                                
```
Then from the PowerShell prompt, 
```powershell

PS [C:\foo> ]> x .\Bytes.ps1                              # and up comes notepad with that file.
```
That error message usually means Windows can not find the file.

**Comment by sdwheeler** [comment]
@marbaa First, you cannot create an alias for an executable with parameters. You have to wrap it in a function. I think the problem you have is that the `/e` is inside the quotes. Try moving it outside the quotes. Try this:

```powershell
function farvi {
  Start-Process "C:\Users\xxx\Programs\Far Manager\Far.exe" -ArgumentList  "/e",$args
}
Set-Alias vi farvi
```

**Comment by marbaa** [comment]
@sdwheeler Yes, I read that I need to put in function. I just didn't know how to put quotes around argument. I had to do little modification because it was giving error Cannot convert from System.Object to System.String. Thank you very much for code. This works for me:

```powershell
function farvi($a) {
    Start-Process "C:\Users\xxx\Programs\Far Manager\Far.exe" -ArgumentList "/e", $a
}
Set-Alias vi farvi
