### ISSUE TITLE
Placeholder tags need to be filled in with good content

### ISSUE THREAD

**Issue by bobbytreed** [MicrosoftDocs/PowerShell-Docs#3740]
reference\5.0\PackageManagement\Find-Package.md
reference\5.0\PackageManagement\Get-Package.md
reference\5.0\PackageManagement\Get-PackageSource.md
reference\5.0\PackageManagement\Install-Package.md
reference\5.0\PackageManagement\Register-PackageSource.md
reference\5.0\PackageManagement\Save-Package.md
reference\5.0\PackageManagement\Set-PackageSource.md
reference\5.0\PackageManagement\Uninstall-Package.md
reference\5.0\PackageManagement\Unregister-PackageSource.md
reference\5.0\PowershellGet\Save-Module.md
reference\5.0\PowershellGet\Uninstall-Module.md
reference\5.1\PackageManagement\Find-Package.md
reference\5.1\PackageManagement\Get-Package.md
reference\5.1\PackageManagement\Get-PackageSource.md
reference\5.1\PackageManagement\Install-Package.md
reference\5.1\PackageManagement\Register-PackageSource.md
reference\5.1\PackageManagement\Save-Package.md
reference\5.1\PackageManagement\Set-PackageSource.md
reference\5.1\PackageManagement\Uninstall-Package.md
reference\5.1\PackageManagement\Unregister-PackageSource.md
reference\5.1\PowershellGet\Find-Command.md
reference\5.1\PowershellGet\Find-DscResource.md
reference\5.1\PowershellGet\Find-RoleCapability.md
reference\5.1\PowershellGet\New-ScriptFileInfo.md
reference\5.1\PowershellGet\Publish-Module.md
reference\5.1\PowershellGet\Save-Module.md
reference\5.1\PowershellGet\Save-Script.md
reference\5.1\PowershellGet\Uninstall-Module.md
reference\5.1\PowershellGet\Uninstall-Script.md
reference\5.1\PowershellGet\Update-Module.md
reference\5.1\PowershellGet\Update-ModuleManifest.md
reference\5.1\PowershellGet\Update-Script.md
reference\5.1\PowershellGet\Update-ScriptFileInfo.md
reference\6\PackageManagement\Find-Package.md
reference\6\PackageManagement\Get-Package.md
reference\6\PackageManagement\Get-PackageSource.md
reference\6\PackageManagement\Install-Package.md
reference\6\PackageManagement\Register-PackageSource.md
reference\6\PackageManagement\Save-Package.md
reference\6\PackageManagement\Set-PackageSource.md
reference\6\PackageManagement\Uninstall-Package.md
reference\6\PackageManagement\Unregister-PackageSource.md
reference\6\PowerShellGet\Find-Command.md
reference\6\PowerShellGet\Find-DscResource.md
reference\6\PowerShellGet\Find-RoleCapability.md
reference\6\PowerShellGet\New-ScriptFileInfo.md
reference\6\PowerShellGet\Publish-Module.md
reference\6\PowerShellGet\Save-Module.md
reference\6\PowerShellGet\Save-Script.md
reference\6\PowerShellGet\Uninstall-Module.md
reference\6\PowerShellGet\Uninstall-Script.md
reference\6\PowerShellGet\Update-Module.md
reference\6\PowerShellGet\Update-ModuleManifest.md
reference\6\PowerShellGet\Update-Script.md
reference\6\PowerShellGet\Update-ScriptFileInfo.md

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@SydneyhSmith here is the list of articles that have placeholder text.

**Comment by davidsmatlak** [comment]
Tables to track PRs for copyedits and style updates of versions 5.0, 5.1, and 6:

| PackageManagement Documents | Pull Request |
| ---------------------- | ------------ |
| Find-Package           |    #4081, #4110  |
| Get-PackageSource      |  #4081, #4110  |
| Register-PackageSource  |  #4098   |
| Save-Package           |   #4106   |
| Set-PackageSource      |  #4106  |
| Get-Package   |     |
| Install-Package |   |
| Uninstall-Package  |   |
| Unregister-PackageSource  |   |


| PowershellGet Documents | Pull Request |
| ----------------------- | ------------ |
| Save-Module |   |
| Find-Command |   |
| Find-DscResource  |  |
| Find-RoleCapability |  |
| New-ScriptFileInfo |  |
| Publish-Module |   |
| Save-Script |  |
| Uninstall-Module |  |
| Uninstall-Script |   |
| Update-Module |   |
| Update-ModuleManifest |  |
| Update-Script |   |
| Update-ScriptFileInfo |   |
