### ISSUE TITLE
Update documentation for line continuance with pipelines

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#3746]
Issue Details
-----------------
PR [8938](https://github.com/PowerShell/PowerShell/pull/8938) adds support for line continuance in pipelines with the pipe at the beginning of a line, with no backticks required. Documentation that describes how line continuance works needs to be updated to describe the additional methods that can be used to wrap a pipeline across multiple lines in a script.

The same documentation also needs to identify that when working interactively in the shell, line continuance with pipelines at the beginning of a line only works with copy paste when using ctrl+v to paste (right-click paste inserts lines one by one and with that method of paste, line continuance with pipes at the beginning of a line is not supported).

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by iSazonov** [comment]
The PR was merged.

**Comment by sdwheeler** [comment]
Duplicate of #4765 which has been closed by PR. Create a new issue if you ever get the additional line continuations added.
