### ISSUE TITLE
MFA enabled account / Modern Authorisation for Powershell Core

### ISSUE THREAD

**Issue by asriznet** [MicrosoftDocs/PowerShell-Docs#3758]
As per title, any updates on whether this is available as yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd8df04a-0972-2339-26eb-1f3f122e04bb
* Version Independent ID: c07dd63a-63fe-694a-b6a9-d0d8d211edc1
* Content: [Installing PowerShell Core on macOS](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-6)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@asriznet I don't understand what you are asking. What does this have to do with this article?

**Comment by asriznet** [comment]
Hi,

Sorry if my question seems unclear.

https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps

According to above article, a global administrator(O365) account that has MFA enabled will need to install a module(Exchange Online Remote PowerShell Module for multi-factor authentication) to manage exchange online using powershell.

This new module can be downloaded from the Exchange Admin Center.

On a windows powershell, running the downloaded file will install the module and able to execute Connect-EXOPSSession cmdlet in powershell to connect to exchange online from an MFA-enabled account.

As such, my question is how do we install modules on powershell core?

I've tried the preview version however running Connect-EXOPSSession cmdlet still gives me error.

Note: for non MFA-enabled account, no issues with connecting to exchange online using the steps in https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps

**Comment by sdwheeler** [comment]
@asriznet Installing modules in PowerShell v6 (Core) is no different than in Windows PowerShell v5.1. This issue you have is with the Exchange Online module. I don't think they have made it compatible with .NET Standard. It requires the .NET Framework. So you will have to use PowerShell 5.1.
