### ISSUE TITLE
Split-Path removes ¨´´ from Service Pathname

### ISSUE THREAD

**Issue by francesco1119** [MicrosoftDocs/PowerShell-Docs#3759]
It´s as simple as that Split-Path is removing the last '"' from every Pathname you query form any service:

```
$service = get-wmiobject -query 'select * from win32_service where name="SQLBrowser"';
Write-output $service.pathname 
Write-output $service.pathname | Split-Path
```

![missing](https://user-images.githubusercontent.com/3397477/53312511-37d2b700-391a-11e9-9bbd-0657a2559bcf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc8b0a5-8130-a6e3-7e95-92495fbcb605
* Version Independent ID: 7871d186-25d2-78eb-9b50-cd04495ad981
* Content: [Split-Path (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/split-path?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Split-Path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Split-Path.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
This is a bug. Moving this issue to PowerShell/PowerShell/Issue

**Comment by sdwheeler** [comment]
This issue was moved to PowerShell/PowerShell#8980
