### ISSUE TITLE
PSGallery SourceLocation should not have a trailing slash

### ISSUE THREAD

**Issue by jberezanski-mdg** [MicrosoftDocs/PowerShell-Docs#3768]
Due to the way the PackageManagementSource resource [is implemented](https://github.com/OneGet/oneget/blob/d7380e48d05761cf29805e7189c83b4f282a3f58/src/Microsoft.PackageManagement.DscResources/MSFT_PackageManagementSource/MSFT_PackageManagementSource.psm1#L70), the PSGallery source must have SourceLocation in the DSC config identical to the value builtin/hardcoded in the operating system. Otherwise the PackageManagementSource resource will fail to find the source and will attempt to register it in each configuration pass (never reachind the compliant state).

The correct value (at least for Server 2019) is:
```
                SourceLocation = 'https://www.powershellgallery.com/api/v2'
```
(no trailing slash)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d942bc-e67b-26d8-7287-1614ff26dc48
* Version Independent ID: 351d8fd8-d410-5719-3bda-d01414f8479a
* Content: [DSC PackageManagement Resource](https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/packagemanagement/packagemanagementdscresource)
* Content Source: [dsc/reference/resources/packagemanagement/PackageManagementDscResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/reference/resources/packagemanagement/PackageManagementDscResource.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by DCtheGeek** [comment]
@jberezanski-mdg I confirmed this on Windows 10 as well.  Will get it updated, thanks!
