### ISSUE TITLE
runasuser missing

### ISSUE THREAD

**Issue by fishbits** [MicrosoftDocs/PowerShell-Docs#3773]
It appears a very useful, but conspicuously absent, verb is missing from this page: RunAsUser. I didn't discover this until trying to invoke the opening command in Example 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a91a81-81dd-f3a9-0106-23db5ee048cb
* Version Independent ID: ab184c39-041b-588c-acde-f715f6d3aee2
* Content: [Start-Process (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Start-Process.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Start-Process.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@SteveL-MSFT Is there a standard list of Verbs for the `-Verb` parameter? And is this a Windows-only feature?
