### ISSUE TITLE
Remove-Service does not remove services

### ISSUE THREAD

**Issue by francesco1119** [MicrosoftDocs/PowerShell-Docs#3775]
I followed [your guide](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-service?view=powershell-6) but even with an elevated shell `Remove-Service` doesn't remove a service: 

![example](https://user-images.githubusercontent.com/3397477/53456978-5c9f6980-3a95-11e9-8262-6620f1d0bc47.png)

I can see the service: 

`Get-Service -DisplayName "Vista Heartbeat Service"
`
But I cannot remove it with: 

`Remove-Service -Name "Vista Heartbeat Service"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4febd11-ae9e-4b34-ca70-5929ee1222fa
* Version Independent ID: fb28372c-479d-c3bd-8f8a-f8c5523ac5cf
* Content: [Remove-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-service?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Remove-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Remove-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
Remove-Service is only available in PowerShell v6.

**Comment by francesco1119** [comment]
So how to remove a service in PowerShell V5? Still `sc delete`?

**Comment by sdwheeler** [comment]
@francesco1119 That would be the easiest way. Another way would be to use the `Delete()` method of the `Win32_Service` class with WMI.
