### ISSUE TITLE
Why does the suggested Powershell remoting setup omit profile loading?

### ISSUE THREAD

**Issue by MathiasMagnus** [MicrosoftDocs/PowerShell-Docs#3776]
Could the article elaborate on the -NoProfile parameter to the subsystem setup? Is it going to bite me in the back if I allow profiles to run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2c72de-1e9f-b263-e9d8-ccebd4c6ab3f
* Version Independent ID: f8beb543-51a4-1258-3dd5-eeccdac53c36
* Content: [PowerShell Remoting Over SSH](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6#set-up-on-linux-ubuntu-1404-machine)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Using `-NoProfile` make session creation faster. It also ensures that you have an unaltered session state (no unexpected modules loaded, aliases changed, etc.) You can always dot source the profile in the remote session if you really want it.

@maertendMSFT Do you have anything to add?
