### ISSUE TITLE
Example uses outdated DSC extension

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/PowerShell-Docs#3784]
Is this document up to date?
The samples reference 2.77 and querying available extensions in UK West returns up to 2.9.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 952e0ff4-0cfa-e2be-6c5d-cfce6ae73d89
* Version Independent ID: c4ba0aa3-cfba-2c58-beb1-2d544012af47
* Content: [Azure DSC Extension Version History](https://docs.microsoft.com/en-us/powershell/scripting/dsc/getting-started/azuredscexthistory)
* Content Source: [dsc/getting-started/azureDscexthistory.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/getting-started/azureDscexthistory.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by DCtheGeek** [comment]
@mgreenegit Can you provide the requested details to @bobbytreed so he can update this doc?  Looks we fell behind keeping it updated.

Thanks for reporting this @OffColour. We'll work on getting the latest details published.

**Comment by mgreenegit** [comment]
We do need to publish 2.77 release notes.  I have a bug to track  it.

2.9 is an older release (not to be confused with 2.90). I actually just recently stepped on this myself.

**Comment by jasonhorner** [comment]
@mgreenegit  do you happen to know where a bug/feature request for the extension itself can be filed? It looks like it uses an older version of the Package Management Resource. It should be updated at least to  1.1.7.0 to support the PackageManagementSourceResource
https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/packagemanagement/packagemanagementsourcedscresource

**Comment by JulienFloris** [comment]
2.78 is out where is the updated Doc's?

**Comment by joshuarmclean** [comment]
Can someone get us the information on the latest available DSC extensions and the OS's that are supported by them?
