### ISSUE TITLE
Invoke-WebRequest: Document behaviour on non-success response codes and handling

### ISSUE THREAD

**Issue by vexx32** [MicrosoftDocs/PowerShell-Docs#3788]
Issue Details
-----------------

As @markekraus mentions in https://github.com/PowerShell/PowerShell/issues/9009, the Invoke-WebRequest cmdlet+ is _designed_ to emit a terminating error when a non-success code is received:

[comment](https://github.com/PowerShell/PowerShell/issues/9009#issuecomment-468488707):
>A non-success HTTP status message throws terminating errors and does not return any output. You must do something like this:
```powershell
try {
    $response = invoke-WebRequest -Uri $Uri -ErrorAction Stop
    $StatusCode = $Response.StatusCode
} catch {
    $StatusCode = $_.Exception.Response.StatusCode.value__
}
```

Something along these lines should be added to the documentation to give clear indication of the behaviour and how to handle it appropriately.
 
Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by markekraus** [comment]
note: this is the behavior in all vesions of the cmdlet and not specific to 6+

**Comment by vexx32** [comment]
Ah, I wasn't aware. Thank you for the clarification! 😊

**Comment by qt3m45su0najc7** [comment]
Thank you for opening this.  I was just writing up the doc enhancement issue today (absolutely true) and found your doc update.   It's odd that iwr does not return anything in some cases and only LOTR and Mark knows where to find the corpse.
