### ISSUE TITLE
Documentation content for writing help is filled with placeholder for multiple sites

### ISSUE THREAD

**Issue by Herrmel** [MicrosoftDocs/PowerShell-Docs#3805]
Content Missing:
https://docs.microsoft.com/en-us/powershell/developer/help/writing-help-for-windows-powershell-providers
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08b4d008-74a8-627c-a1d4-4d6b24e339d4
* Version Independent ID: f77131da-af5a-60d6-fd09-f055e489cd3d
* Content: [Writing Help for Windows PowerShell Providers](https://docs.microsoft.com/en-us/powershell/developer/help/writing-help-for-windows-powershell-providers)
* Content Source: [developer/help/writing-help-for-windows-powershell-providers.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/developer/help/writing-help-for-windows-powershell-providers.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by DCtheGeek** [comment]
Placeholder content was removed (including the specific page linked in this issue) and removed from the Table of Contents. If you see other examples of placeholder content in the developer help area, please let us know.
