### ISSUE TITLE
Example 5 Misleading

### ISSUE THREAD

**Issue by halsey51013** [MicrosoftDocs/PowerShell-Docs#3809]
This code snippet for example 5 is wrong. The snippet I am talking about:
"The first command uses the Get-Content cmdlet to get a list of computers in the domain from the Domain01.txt file. It stores the list in the $s variable.
PS C:\&gt; $s = Get-Content Domain01.txt"

All that does is restart all the computers whose name is in the text file. No where does this example grab all the computers in the domain and put them in the text file.

Suggested Correction:
The title should be, "Example 5: Force restart of all computers in a text file."

The code snippet should say, "The first command uses the Get-Content cmdlet to get a list of the computers in the Domain01.txt file. It stores the list in the $s variable."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b56646b-9f1d-3f94-64b7-1e556c9ad803
* Version Independent ID: c4358932-1228-6e20-37e3-5ded6a469b8a
* Content: [Restart-Computer (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-computer?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Restart-Computer.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Restart-Computer.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by anandta** [comment]
Installed on RedHat. Not seeing "Add-Computer" cmdlet.
Trying to join Linux machine to domain using Add-Computer cmdlet

**Comment by sdwheeler** [comment]
Add-Computer is not included in PowerShell 6.x.. It used APIs that are not available in .NET Core.
