### ISSUE TITLE
Update-Help fails

### ISSUE THREAD

**Issue by AS-at-GitHub** [MicrosoftDocs/PowerShell-Docs#3811]
This command does not update the module I need.  Nothing here explains why or what to do.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8da621a-dd94-e6e6-b789-df6ae6faf14d
* Version Independent ID: 4532edd3-5890-2ab7-a7eb-d366d0462d7e
* Content: [Update-Help (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/update-help?view=powershell-6#outputs)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Update-Help.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Update-Help.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@AS-at-GitHub What errors are you getting?

**Comment by AS-at-GitHub** [comment]
Update-Help : Failed to update Help for the module(s) 'AppBackgroundTask, 
AppLocker, AppvClient, Appx, AssignedAccess, BitLocker, BitsTransfer, BranchCache, 
CimCmdlets, Defender, Dism, DnsClient, HgsClient, HgsDiagnostics, International, 
iSCSI, ISE, Microsoft.PowerShell.Archive, Microsoft.PowerShell.Core, 
Microsoft.PowerShell.Diagnostics, Microsoft.PowerShell.Host, 
Microsoft.PowerShell.LocalAccounts, Microsoft.PowerShell.Management, 
Microsoft.PowerShell.ODataUtils, Microsoft.PowerShell.Operation.Validation, 
Microsoft.PowerShell.Security, Microsoft.PowerShell.Utility, 
Microsoft.WSMan.Management, MMAgent, MsDtc, NetAdapter, NetEventPacketCapture, 
NetLbfo, NetNat, NetQos, NetSecurity, NetSwitchTeam, NetTCPIP, PackageManagement, 
PnpDevice, PowerShellGet, PrintManagement, ProcessMitigations, Provisioning, 
PSDesiredStateConfiguration, PSReadline, PSScheduledJob, PSWorkflow, 
PSWorkflowUtility, ScheduledTasks, SecureBoot, StartLayout, Storage, TLS, 
TroubleshootingPack, TrustedPlatformModule, UEV, WebAdministration, 
WindowsDeveloperLicense, WindowsErrorReporting, WindowsSearch, WindowsUpdate, 
WindowsUpdateProvider' with UI culture(s) {en-US} : Unable to connect to Help 
content. The server on which Help content is stored might not be available. Verify 
that the server is available, or wait until the server is back online, and then try 
the command again.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateH 
   elpCommand

**Comment by AS-at-GitHub** [comment]
Actually, it DOES update SOME files, but not the ones I need, for example Microsoft.Powershell.Core.  Which contains the help for commands like Update-Help and Save-Help and Get-Help.

**Comment by sdwheeler** [comment]
I tested this in PSv6 and PSv5.1 and had no errors. It appears you have a network connection problem. The error you got was:

```
Unable to connect to Help  content. The server on which Help content is stored might not be available. Verify that the server is available, or wait until the server is back online, and then try the command again.
```

**Comment by AS-at-GitHub** [comment]
My version:
PS D:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  590

**Comment by AS-at-GitHub** [comment]
If it is a network connection problem, why are some of the help files updating?  Also, Save-Help did save some of the help (xml) files when I ran it.
====
PS D:\> Update-Help -Verbose
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?LinkId=626871"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/B/9/8/B9800580-744A-48B8-84E2-204CB65BB257/"
VERBOSE: Performing the operation "Update-Help" on target "ConfigCI, Current Version:
 5.0.2.0, Available Version: 5.0.2.0, UICulture: en-US".
VERBOSE: ConfigCI: The most current Help files are already installed.. Culture en-US 
Version 5.0.2.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?Linkid=285546"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/D/6/4/D641E8C1-B0B0-4FCD-B37F-D901F4F29AC2/"
VERBOSE: Performing the operation "Update-Help" on target "DirectAccessClientComponen
ts, Current Version: 4.0.3.0, Available Version: 4.0.3.0, UICulture: en-US".
VERBOSE: DirectAccessClientComponents: The most current Help files are already instal
led.. Culture en-US Version 4.0.3.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=524348"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/F/4/E/F4E3C28B-ACD2-41D7-B67D-D7BB8AE875A4/"
VERBOSE: Performing the operation "Update-Help" on target "EventTracingManagement, Cu
rrent Version: 5.0.0.0, Available Version: 5.0.0.0, UICulture: en-US".
VERBOSE: EventTracingManagement: The most current Help files are already installed.. 
Culture en-US Version 5.0.0.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=216321"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/2/9/7/2970B5D3-769A-463F-89D1-B6A9D2E81F77/"
VERBOSE: Performing the operation "Update-Help" on target "IISAdministration, Current
 Version: 5.0.3.0, Available Version: 5.0.3.0, UICulture: en-US".
VERBOSE: IISAdministration: The most current Help files are already installed.. Cultu
re en-US Version 5.0.3.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390781"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/1/3/8/138B5672-C241-40C2-9A32-B16AD9148697/"
VERBOSE: Performing the operation "Update-Help" on target "Kds, Current Version: 5.0.
0.0, Available Version: 5.0.0.0, UICulture: en-US".
VERBOSE: Kds: The most current Help files are already installed.. Culture en-US Versi
on 5.0.0.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390795"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/4/B/2/4B2AD26C-F732-44A5-81AF-63AF52420C3F/"
VERBOSE: Performing the operation "Update-Help" on target "NetConnection, Current Ver
sion: 5.0.0.0, Available Version: 5.0.0.0, UICulture: en-US".
VERBOSE: NetConnection: The most current Help files are already installed.. Culture e
n-US Version 5.0.0.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?LinkId=285557"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/4/6/3/4632A020-E658-4FCA-BA40-A015C9FCEB67/"
VERBOSE: Performing the operation "Update-Help" on target "NetworkConnectivityStatus,
 Current Version: 4.0.4.0, Available Version: 4.0.4.0, UICulture: en-US".
VERBOSE: NetworkConnectivityStatus: The most current Help files are already installed
.. Culture en-US Version 4.0.4.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=216365"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/0/7/4/074A9960-600E-4EFC-A49D-E86F4793FC73/"
VERBOSE: Performing the operation "Update-Help" on target "NetworkSwitchManager, Curr
ent Version: 5.0.1.0, Available Version: 5.0.1.0, UICulture: en-US".
VERBOSE: NetworkSwitchManager: The most current Help files are already installed.. Cu
lture en-US Version 5.0.1.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?LinkId=285559"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/7/F/B/7FB26A90-C7CF-4738-8C05-8C248129447F/"
VERBOSE: Performing the operation "Update-Help" on target "NetworkTransition, Current
 Version: 4.0.3.0, Available Version: 4.0.3.0, UICulture: en-US".
VERBOSE: NetworkTransition: The most current Help files are already installed.. Cultu
re en-US Version 4.0.3.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390809"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/2/0/0/200AF58C-1050-432E-B4B7-C225056272C7/"
VERBOSE: Performing the operation "Update-Help" on target "PcsvDevice, Current Versio
n: 2.0.0.0, Available Version: 2.0.0.0, UICulture: en-US".
VERBOSE: PcsvDevice: The most current Help files are already installed.. Culture en-U
S Version 2.0.0.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390811"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/7/C/1/7C19C361-919D-42E7-8917-5DA4DCF6699B/"
VERBOSE: Performing the operation "Update-Help" on target "PKI, Current Version: 5.0.
0.0, Available Version: 5.0.0.0, UICulture: en-US".
VERBOSE: PKI: The most current Help files are already installed.. Culture en-US Versi
on 5.0.0.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390827"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/2/4/5/245236CF-D4B7-44A7-854A-BFD7E26E4C5F/"
VERBOSE: Performing the operation "Update-Help" on target "SmbShare, Current Version:
 5.0.1.0, Available Version: 5.0.1.0, UICulture: en-US".
VERBOSE: SmbShare: The most current Help files are already installed.. Culture en-US 
Version 5.0.1.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390828"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/3/E/8/3E8BA4AE-B8E4-426D-B622-036A63694E31/"
VERBOSE: Performing the operation "Update-Help" on target "SmbWitness, Current Versio
n: 5.0.0.0, Available Version: 5.0.0.0, UICulture: en-US".
VERBOSE: SmbWitness: The most current Help files are already installed.. Culture en-U
S Version 5.0.0.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390842"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/1/5/E/15E57BD3-3B46-453B-B475-3820847B55ED/"
VERBOSE: Performing the operation "Update-Help" on target "VpnClient, Current Version
: 5.0.0.0, Available Version: 5.0.0.0, UICulture: en-US".
VERBOSE: VpnClient: The most current Help files are already installed.. Culture en-US
 Version 5.0.0.0
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?linkid=390844"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/4/F/4/4F416EAF-F804-470A-B8F2-67A936D0CA30/"
VERBOSE: Performing the operation "Update-Help" on target "Wdac, Current Version: 5.0
.0.0, Available Version: 5.0.0.0, UICulture: en-US".
VERBOSE: Wdac: The most current Help files are already installed.. Culture en-US Vers
ion 5.0.0.0
Update-Help : Failed to update Help for the module(s) 'AppBackgroundTask, 
AppLocker, AppvClient, Appx, AssignedAccess, BitLocker, BitsTransfer, BranchCache, 
CimCmdlets, Defender, Dism, DnsClient, HgsClient, HgsDiagnostics, International, 
iSCSI, ISE, Microsoft.PowerShell.Archive, Microsoft.PowerShell.Core, 
Microsoft.PowerShell.Diagnostics, Microsoft.PowerShell.Host, 
Microsoft.PowerShell.LocalAccounts, Microsoft.PowerShell.Management, 
Microsoft.PowerShell.ODataUtils, Microsoft.PowerShell.Operation.Validation, 
Microsoft.PowerShell.Security, Microsoft.PowerShell.Utility, 
Microsoft.WSMan.Management, MMAgent, MsDtc, NetAdapter, NetEventPacketCapture, 
NetLbfo, NetNat, NetQos, NetSecurity, NetSwitchTeam, NetTCPIP, PackageManagement, 
PnpDevice, PowerShellGet, PrintManagement, ProcessMitigations, Provisioning, 
PSDesiredStateConfiguration, PSReadline, PSScheduledJob, PSWorkflow, 
PSWorkflowUtility, ScheduledTasks, SecureBoot, StartLayout, Storage, TLS, 
TroubleshootingPack, TrustedPlatformModule, UEV, WebAdministration, 
WindowsDeveloperLicense, WindowsErrorReporting, WindowsSearch, WindowsUpdate, 
WindowsUpdateProvider' with UI culture(s) {en-US} : Unable to connect to Help 
content. The server on which Help content is stored might not be available. Verify 
that the server is available, or wait until the server is back online, and then try 
the command again.
At line:1 char:1
+ Update-Help -Verbose
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateH 
   elpCommand

**Comment by AS-at-GitHub** [comment]
Also, how do I verify that the server is back online?  Where is the server?

**Comment by sdwheeler** [comment]
Ware you going through a proxy or firewall? It could be that they are not allowing all IP addresses for the Microsoft download center. Have you tried running the update while connected to a different network?

**Comment by sdwheeler** [comment]
You can get a list of all of our public IP ranges from https://www.microsoft.com/en-us/download/details.aspx?id=53602

**Comment by AS-at-GitHub** [comment]
This shows that Update-Help works for ConfigCI module but not Microsoft.Powershell.Core module:

PS C:\WINDOWS\system32> Update-Help -Verbose -Force ConfigCI
VERBOSE: Resolving URI: "http://go.microsoft.com/fwlink/?LinkId=626871"
VERBOSE: Your connection has been redirected to the following URI: "http://download.m
icrosoft.com/download/B/9/8/B9800580-744A-48B8-84E2-204CB65BB257/"
VERBOSE: Performing the operation "Update-Help" on target "ConfigCI, Current Version:
 5.0.2.0, Available Version: 5.0.2.0, UICulture: en-US".
VERBOSE: ConfigCI: Updated C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\ConfigC
I\en-US\Microsoft.ConfigCI.Commands.dll-help.xml. Culture en-US Version 5.0.2.0

PS C:\WINDOWS\system32> Update-Help -Verbose Microsoft.Powershell.Core
Update-Help : Failed to update Help for the module(s) 'Microsoft.PowerShell.Core' 
with UI culture(s) {en-US} : Unable to connect to Help content. The server on which 
Help content is stored might not be available. Verify that the server is available, 
or wait until the server is back online, and then try the command again.
At line:1 char:1
+ Update-Help -Verbose Microsoft.Powershell.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateH 
   elpCommand

**Comment by AS-at-GitHub** [comment]
In the case of ConfigCI module -Verbose responds: "You are being redirected..." and the help updates.  In the case of Microsoft.Powershell.Core module, -Verbose doesn't respond and and error occurs.

I tried using a different computer on a different network and for the Microsoft.Powershell.Core module -Verbose responds that "You are being redirected..." (which is different) but then errors and says I have to be an Administrator (I don't have Admin rights on that network.)

**Comment by sdwheeler** [comment]
You don't need Admin rights on the network. You need to run PowerShell as Admin on the machine when you run Update-Help.

**Comment by AS-at-GitHub** [comment]
I don't have Admin rights on that computer or ANY computer connected to THAT network.

**Comment by AS-at-GitHub** [comment]
I am running Update-Help as Administrator on the 1st network where it does not say "You are being re-directed..."  and I get an error saying the server might not be available.  On the 2nd network I get a response (using the -Verbose switch) saying "You are being re-directed..." but then it errors out because I am not the Administrator and it says you need to run PowerShell (ISE) as the Administrator, which I cannot do on any computer on the other (2nd) network.

So it seems on the 2nd network it wants to download the Help but I do not have the privilege.  On the 1st network it is not even saying that it is able to download the Help for the Core module but it does so for the ConfigCI (and other) module(s).

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/update-help?view=powershell-5.1#description

 Important

Update-Help requires administrative privileges.

You must be a member of the Administrators group on the computer to update the help files for the PowerShell Core modules.

To download or update the help files for modules in the PowerShell installation directory ($PSHOME\Modules), including the PowerShell Core modules, start PowerShell by using the Run as administrator option.

You can also update help files by using the Update Windows PowerShell Help menu item in the Help menu in Windows PowerShell Integrated Scripting Environment (ISE).

The Update Windows PowerShell Help item runs an Update-Help cmdlet without parameters. To update help for modules in the $PSHOME directory, start Windows PowerShell ISE by using the Run as administrator option.
