### ISSUE TITLE
How do you re-open a closed issue?

### ISSUE THREAD

**Issue by AS-at-GitHub** [MicrosoftDocs/PowerShell-Docs#3812]
My issue was closed and I don't know how to re-open it.

**Comment by AS-at-GitHub** [comment]
I actually opened this at Microsoft's site, but I guess they are just out-sourcing to GitHub.
But at Microsoft's site the comments don't work.  Firefox keeps saying: "A web page is slowing down your browser."

**Comment by sdwheeler** [comment]
If you continue to use language like this, we will have to report you.
