### ISSUE TITLE
Wrong parameter name: DestinationPath

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/PowerShell-Docs#3817]
The correct parameter name is `Destination`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ca826b-6587-244e-0510-e6d56c6bb650
* Version Independent ID: 3b920543-f348-a9a4-93b2-5b3dd01532e8
* Content: [Install-Package (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-package?view=powershell-5.0)
* Content Source: [reference/5.0/PackageManagement/Install-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.0/PackageManagement/Install-Package.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by Pekka-Kalevi** [comment]
Why parameter -Destination have a cryptic description: 'Specifies a path to an input object.'
