### ISSUE TITLE
Relative links are not supported using New-Item -Type SymbolicLink

### ISSUE THREAD

**Issue by dbut023** [MicrosoftDocs/PowerShell-Docs#3818]
mklink supports the creation of symbolic links that contain relative target paths but as of PS5 New-Item will always create the link with the resolved absolute path.

https://github.com/PowerShell/PowerShell/issues/3500 tracks addition of relative support to PS6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa88dd1-b502-2e1c-1d14-58e0896593f3
* Version Independent ID: c5f0c14e-c3e7-e743-73bc-107207034c53
* Content: [Interact with Symbolic links using improved Item cmdlets](https://docs.microsoft.com/en-us/powershell/wmf/5.0/feedback_symbolic#feedback)
* Content Source: [wmf/5.0/feedback_symbolic.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/wmf/5.0/feedback_symbolic.md)
* Product: **powershell**
* GitHub Login: @HemantMahawar
* Microsoft Alias: **hemantm**

**Comment by HemantMahawar** [comment]
@sdwheeler This new functionality is coming in PS Core only, so WMF tag looks incorrect.

**Comment by sdwheeler** [comment]
@HemantMahawar thanks. I changed the labels.
