### ISSUE TITLE
Output details

### ISSUE THREAD

**Issue by rutuja1304** [MicrosoftDocs/PowerShell-Docs#3819]
There should be a screenshot or text showing outputs of these commands so that we can verify with the expected output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27750c2-c0c4-f34f-2193-ce4e7b96a752
* Version Independent ID: 2ed3f83e-cd15-3edd-d3a4-6190ab92cebe
* Content: [Out-Null (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/out-null?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Out-Null.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Out-Null.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Screenshot of what? There is no output. That is the point of Out-Null.
