### ISSUE TITLE
Error with startdays

### ISSUE THREAD

**Issue by pizzablitz** [MicrosoftDocs/PowerShell-Docs#3820]
The following line must be inserted three lines further down the loop.
$currentDay = $start

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: aad10534-1ef1-4bbd-22b6-d4be469839be
* Version Independent ID: 813242e6-4e92-1b34-bd58-7b3a19ceecd0
* Content: [How to Write a PowerShell Script Module](https://docs.microsoft.com/de-ch/powershell/developer/module/how-to-write-a-powershell-script-module#feedback)
* Content Source: [developer/module/how-to-write-a-powershell-script-module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/developer/module/how-to-write-a-powershell-script-module.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Please submit a PR to make the change you think is necessary.
