### ISSUE TITLE
workflow - sequence examples

### ISSUE THREAD

**Issue by msftrncs** [MicrosoftDocs/PowerShell-Docs#3834]
The examples are not fence-blocked on this topic, and thus are conglomerated with the main text, making it difficult to read.  This includes the syntax block at the top too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ecf53c8-3459-30fb-fb36-172a3da1d49c
* Version Independent ID: 91c1b31a-2bb1-74b5-4ac8-aa6e0f51b423
* Content: [about_Sequence](https://docs.microsoft.com/en-us/powershell/module/psworkflow/about/about_sequence?view=powershell-5.1)
* Content Source: [reference/5.1/PSWorkflow/About/about_Sequence.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PSWorkflow/About/about_Sequence.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Fixed in #3831
