### ISSUE TITLE
Was Compress-Archive updated? 

### ISSUE THREAD

**Issue by bziembicki** [MicrosoftDocs/PowerShell-Docs#3839]
Hello,
Has Compress-Archive been lately updated? It never worked recursively, and I created whole logic for log archiving which would make it work recursively with couple other features. But today I noticed some errors so I run just vanilla command and it works recursively. It destroyed my whole previously prepared logic. Has it been changed ?

**Comment by sdwheeler** [comment]
@bziembicki  What version of PowerShell are you running?

**Comment by sdwheeler** [comment]
No, it has always worked this way. If the -Path value is a folder then it compresses recursively.
