### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by BriceGagnageRenault** [MicrosoftDocs/PowerShell-Docs#3844]
The variable used to retrieve the process id should be 
$event.SourceEventArgs.NewEvent.TargetInstance.ProcessId
instead of
$event.SourceEventArgs.NewEvent.ProcessId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd81e656-7aaf-54a6-f8db-71b1d6407c18
* Version Independent ID: d742e40f-5350-3f58-73b2-396e0e3f198e
* Content: [Register-CimIndicationEvent (CimCmdlets)](https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/register-cimindicationevent?view=powershell-6#feedback)
* Content Source: [reference/6/CimCmdlets/Register-CimIndicationEvent.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/Register-CimIndicationEvent.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@BriceGagnageRenault The example works for me as written.
