### ISSUE TITLE
Copyedits and fix placeholders

### ISSUE THREAD

**Issue by davidsmatlak** [MicrosoftDocs/PowerShell-Docs#3878]
Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

Opened this issue to track updates for several documents.
- Copyedit Find-Module (5.0, 5.1, and 6)
- Fix a typo in Install-Module (5.0, 5.1, and 6)
- 5.0\PackageManagement\Find-Package.md
- 5.0\PackageManagement\Get-Package.md
- 5.1\PackageManagement\Install-Package.md
- 6\PackageManagement\Install-Package.md

**Comment by sdwheeler** [comment]
@davidsmatlak Please fix the placeholders in the following files as part of this issue:

- 5.0\PackageManagement\Find-Package.md
- 5.0\PackageManagement\Get-Package.md
- 5.1\PackageManagement\Install-Package.md
