### ISSUE TITLE
What are the astricks at the end of class names for?

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/PowerShell-Docs#3903]
EX: `System.Management.Automation.Cmdlet.Stopprocessing*` links. Is this intentional or something left over from content migration?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ea0624-acc2-67c6-57fe-bb4c7cf4f266
* Version Independent ID: 3236d6b3-b2da-c9e8-272e-42a30074b9bc
* Content: [Advisory Development Guidelines](https://docs.microsoft.com/en-ca/powershell/developer/cmdlet/advisory-development-guidelines)
* Content Source: [developer/cmdlet/advisory-development-guidelines.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/developer/cmdlet/advisory-development-guidelines.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Yes, this is an artifact of migration. These can be removed from the link text but should remain encoded into the target URL.
