### ISSUE TITLE
Enter-PSSession returns subsystem request failed on channel 0.

### ISSUE THREAD

**Issue by mcorning** [MicrosoftDocs/PowerShell-Docs#3997]
i had such high hopes that remote debugging would be as easy as you tell it. VSC is my favorite IDE, and i'm far enough along my development on the Ubuntu VM that i really want RD to work. Searching for an answer (even on github) has not been fruitful. did i miss a configuration step in the article above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2c72de-1e9f-b263-e9d8-ccebd4c6ab3f
* Version Independent ID: f8beb543-51a4-1258-3dd5-eeccdac53c36
* Content: [PowerShell Remoting Over SSH](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SydneyhSmith @maertendMSFT Any help here?

**Comment by mcorning** [comment]
not yet. as a rookie, i'm foundering in gitter and slack. there, i've been asked if i tried Enter-PSSession in VSC and or PS. and the answer is yes, and failed in both cases.

**Comment by sdwheeler** [comment]
@PaulHigin Can you provide any help here?

**Comment by PaulHigin** [comment]
I need more information about what you are doing, including repro steps.  But in general SSH remoting is a bit difficult to set up.  The reason is that PowerShell relies on SSH and so that needs to be set up first.  Some machines have client SSH but not the SSHD needed to support connecting to a machine (e.g., the endpoint daemon).

So really the best approach is to first get SSH connections working between machines (or on the same machine for testing).  Once this is done, it is just a one line change to the sshd_config (subsystem) to enable PowerShell remoting over the existing SSH connection.

**Comment by mcorning** [comment]
I've been using ssh for months as I code from my Surface Book on my Ubuntu vm on Azure.

So I believe I have met your first prereq.

I'm unaware of any change to ssh_config. Please share your secret and disabuse my rank ignorance. Your timing is right on because I'm returning to remote coding/debugging tomorrow.

^m

Rwap

________________________________

**Comment by PaulHigin** [comment]
Sorry for the late reply.  It's great that SSH connections are already working on your VM.  To enable PowerShell SSH remoting, you just need to add one line to the ssh_config file.  The ssh_config file is in your ssh directory, in my case for Ubuntu it is at /etc/ssh.  You need to add this line to the file:

```
Subsystem	powershell	/opt/microsoft/powershell/6/pwsh -sshs -NoLogo -NoProfile
```
Make sure the /opt/microsoft/powershell/6/pwsh path is correct to the pwsh executable.  What this does is create a powershell subsystem that PowerShell remoting uses as the 'endpoint' to connect to.  Once you've made this change you need to restart the sshd daemon.  On my VM I use:
```
systemctl restart ssh
```
Now PowerShell over SSH should be enabled and you should be able to do the following:
```
$session = New-PSSession -HostName (hostname) -User <userName>
Enter-PSSession -Session $session
```

**Comment by mcorning** [comment]
Thanks for the update.

I have no folders in my opt directory.

How do I search for the pwsh.(exe?)?

Or do I need to install powershell on the vm?

Also, when I run this command in windows powershell or vscode powershell, I get the missing parameter name error I’ve seen before:

PS C:\Users\michael\Documents\GitHub\SovrinSecours> $session = New-PSSession -HostName [myhost] -User azureuser
New-PSSession : A parameter cannot be found that matches parameter name 'HostName'.
At line:1 char:26
+ $session = New-PSSession -HostName [myhost]  ...
+                          ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.NewPSSessionCommand

If memory serves, this is a version issue in powershell, yes? V6.1 or something is what I need?



Rwap
^m

**Comment by mcorning** [comment]
And when I do a git fetch right now I get a not unexpected error:
azureuser@myVM:~/SovrinSecours$ git fetch
/etc/ssh/ssh_config: line 52: Bad configuration option: subsystem
/etc/ssh/ssh_config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.

Is the bad config because the path to pwsh is not right?



Rwap
^m


From: Michael Corning <mcorning@outlook.com>
Sent: Monday, May 6, 2019 4:07 PM
To: MicrosoftDocs/PowerShell-Docs <reply@reply.github.com>; MicrosoftDocs/PowerShell-Docs <PowerShell-Docs@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MicrosoftDocs/PowerShell-Docs] Enter-PSSession returns subsystem request failed on channel 0. (#3997)

Thanks for the update.

I have no folders in my opt directory.

How do I search for the pwsh.(exe?)?

Or do I need to install powershell on the vm?

Also, when I run this command in windows powershell or vscode powershell, I get the missing parameter name error I’ve seen before:

PS C:\Users\michael\Documents\GitHub\SovrinSecours> $session = New-PSSession -HostName [myhost] -User azureuser
New-PSSession : A parameter cannot be found that matches parameter name 'HostName'.
At line:1 char:26
+ $session = New-PSSession -HostName [myhost]  ...
+                          ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.NewPSSessionCommand

If memory serves, this is a version issue in powershell, yes? V6.1 or something is what I need?



Rwap
^m

**Comment by PaulHigin** [comment]
Yes, you need to have powershell installed on the machine you are connecting to.  You also need to have sshd installed in order to connect to it via ssh.  Once sshd and powershell is installed you can update sshd_config to include the powershell subsystem entry as I described previously.  Use `Get-Command` to find the default path to powershell (`Get-Command pwsh | select source`).  Always use the latest version of powershell.

**Comment by bobbytreed** [comment]
@mcorning Did this resolve your issue? Do you think the documentation could be clearer?

**Comment by joeyaiello** [comment]
Closing as this looks answered
