### ISSUE TITLE
Enter-PSSession returns subsystem request failed on channel 0.

### ISSUE THREAD

**Issue by mcorning** [MicrosoftDocs/PowerShell-Docs#3998]
I had such high hopes that remote debugging would be as easy as you tell it. VSC is my favorite IDE, and I'm far enough along my development on the Ubuntu VM that I really want RD to work. Searching for an answer (even on github) has not been fruitful. did I miss a configuration step in the article above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a10e4b2-aca7-4aba-9ad1-d99d1bd7626f
* Version Independent ID: 3ffdba34-e346-e974-3d48-f273a0028ea8
* Content: [Using Visual Studio Code for remote editing and debugging](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode-for-remote-editing-and-debugging?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/components/vscode/Using-VSCode-for-Remote-Editing-and-Debugging.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/Using-VSCode-for-Remote-Editing-and-Debugging.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SydneyhSmith @maertendMSFT Any help here?

**Comment by sdwheeler** [comment]
@PaulHigin Can you provide any help here?

**Comment by bobbytreed** [comment]
Looks like there are recently closed issues on this, we should sync to see if it is still an issue.
https://github.com/PowerShell/PowerShell/issues/5945
https://github.com/PowerShell/Win32-OpenSSH/issues/1296
https://github.com/PowerShell/PowerShell/issues/2466

**Comment by joeyaiello** [comment]
If you're having issues with VS Code doing remote debugging specifically, please file an issue in https://github.com/PowerShell/vscode-powershell. If you're not able to use SSH-based remoting at all (outside of VS Code), please file an issue in https://github.com/PowerShell/PowerShell

**Comment by mcorning** [comment]
for the record, after installing the remote-ssh extensions locally and, most importantly, installing PowerShell on my Azure VM, i am happily remote debugging code.
