### ISSUE TITLE
Documentation about 'Start-Job' should be updated

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#4003]
Issue Details
-----------------

Documentation about 'Start-Job' should be updated due to the following two changes:
https://github.com/PowerShell/PowerShell/pull/9128
https://github.com/PowerShell/PowerShell/pull/9143

For #9128, `Start-Job` doesn't work when powershell core is hosted in an application.
For #9143, `-RunAs32` doesn't work when running a 64-bit `pwsh`.

Both need to be put in the documentation.

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
PowerShell/PowerShell#9128 was addressed in #4068. Changed milestone to Future. Still need to address PowerShell/PowerShell#9143 in a future release.

**Comment by sdwheeler** [comment]
The code PR have been merged. Moved to milestone 7.0.0
