### ISSUE TITLE
Private arg for -Scope in Set-Variable left out

### ISSUE THREAD

**Issue by EanKeen** [MicrosoftDocs/PowerShell-Docs#4004]
Under the `-Scope` subheading for the `Set-Variable` documentation, it describes the following as possible options for the `-Scope`.
> `-Scope`
> Specifies the scope of the variable.The acceptable values for this parameter are:
> - Global
> - Local
> - Script
> - A number relative to the current scope (0 through the number of scopes, where 0 is the current scope and 1 is its parent)
> Local is the default
> For more information, see [about_Scopes](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-6)

However, after following the link to more information about scopes, [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-6#powershell-scopes), it elaborates on private scopes, which were not on the `Set-Variable` documentation. Is it not possible to set private as an argument for -Scope when using Set-Variable, or should the documentation be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d2240fa-8da4-5081-5f5d-880e106530a7
* Version Independent ID: b4545ffe-64bf-ff01-fbcb-a21e17f2091f
* Content: [Set-Variable (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/set-variable?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Set-Variable.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Need to add 'Private' to the list of  accepted `-Scope` values.
