### ISSUE TITLE
[Q] Uninstall-Module - Uninstall multiple versions in one go?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/PowerShell-Docs#4008]
I was just wondering if it's possible to uninstall multiple versions of a module in one go with Uninstall-Module?

The reason I ask is that I've created a script to automagically install and uninstall modules, but uninstalling outdated versions takes a long time, especially if there is multiple outdated versions of a module. This is by far the slowest operation in the script.
* Script available [on GitHub](https://github.com/o-l-a-v/PowerShell-Projects/blob/master/PowerShellModulesUpdater/PowerShellModulesUpdater.ps1) if anyone is interested.

**Scenario / what I tested**
* I got 5 versions of "Az" installed, I only want to keep the newest version.
* Uninstalling one by one version by using "-RequiredVersion" takes a long time.
* Specifying both "-MinimumVersion" and "-MaximumVersion" resulted in only uninstalling one version: The newest one ("-MaximumVersion") specified.
  * Example: Uninstall-Module -Name 'Az' -MinimumVersion ([system.version]$(1.0.1)) -MaximumVersion [system.version]$('1.4.0') -Force
  * Result: Only v1.4.0 got uninstalled

**Question**
Are there any way of specifying multiple versions of a module to uninstall without calling "Uninstall-Module" once for each and every module?
A faster way might be to specify "-AllVersions" if modules to uninstall is greater or equal to 3, then installing the newest module again afterwards. But I'd like to avoid that if I can.

**Comment by sdwheeler** [comment]
@o-l-a-v  Not at this time. Uninstall-Module only uninstalls one version. You can file an issue to request the feature in the [PowerShellGet repo](https://github.com/PowerShell/PowerShellGet/issues). 

/cc: @SydneyhSmith
