### ISSUE TITLE
PowerShell Module Browser 404 everywhere

### ISSUE THREAD

**Issue by NextTurn** [MicrosoftDocs/PowerShell-Docs#4009]
For example

https://docs.microsoft.com/en-us/powershell/module/CimCmdlets/?view=powershell-6
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/?view=powershell-6
https://docs.microsoft.com/en-us/powershell/module/PSReadLine/?view=powershell-6

**Comment by sdwheeler** [comment]
Investigating.

**Comment by sdwheeler** [comment]
Fixed
