### ISSUE TITLE
Document on PSConsoleHostReadLine unclear

### ISSUE THREAD

**Issue by TheIncorrigible1** [MicrosoftDocs/PowerShell-Docs#4022]
The grammar in this article needs work and I'm entirely unclear what it's trying to explain at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a78a0f7-7e92-430d-3ef4-f9574701a347
* Version Independent ID: bd0df562-2552-1d35-2775-f546f262e2a9
* Content: [about_PSConsoleHostReadLine](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psconsolehostreadline?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_psconsolehostreadline.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_psconsolehostreadline.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
I am not sure what is unclear for you. I grant that the example is not very useful. The purpose of the PSConsoleReadLine function is to override the standard console input handler. You can use this to enhance the command line edit experience, manage history, and provide syntax highlighting. This is how the PSReadLine module works. 

So unless you want to make a better PSReadLine module, you would never use this function.

**Comment by joeyaiello** [comment]
@TheIncorrigible1: as @sdwheeler said, I think this is pretty inclusive of the PSConsoleHostReadline function.

Just in case you're trying to get docs on the PSConsoleReadline APIs (which are very useful/extensive and require more documentation), that's here in about_PSReadline: https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-6
