### ISSUE TITLE
$error not described

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/PowerShell-Docs#4023]
There is no information in this article on how to get access to the error information inside a catch block. It mentions that the `$error` variable is set before searching for the catch handler. It then recommends that you read the section called `about_errors`. This section doesn't exist in the TOC nor is it linked in the See Also section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12057801-bca7-e633-5872-1647f2b879ee
* Version Independent ID: 1bda81bf-58e5-93b9-48e7-ff1ec3d465d0
* Content: [about_Try_Catch_Finally](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by SteveL-MSFT** [comment]
The `$error` variable is just a running "log" of all errors.  The text should mention using `$_` or `$PSItem` to access the caught error with some samples.

**Comment by L1ttl3J1m** [comment]
$wc.DownloadFile("http://www.contoso.com/MyDoc.doc") needs a second argument containing a local file name to return an error that will be caught by the first trap

PS C:\temp\processing> $wc.DownloadFile("http://www.contoso.com/MyDoc.doc","c:\temp\test.doc")

Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."

**Comment by jcoutch** [comment]
Just an FYI - If you look in the top right corner, there's an "Edit" button which takes you to the GitHub repo containing this documentation so that you can submit pull requests.  I just submitted one to address this:
https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4107

**Comment by sdwheeler** [comment]
Looks like this was fixed in #4107
