### ISSUE TITLE
What about a "StartupType" value of "System"?

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [MicrosoftDocs/PowerShell-Docs#4051]
In the Windows Registry, setting the startup type of a service to a value of 1 changes the startup type to System in the services control panel, as opposed to any of the other types. However, there is no documentation I can find which details what happens when you do this, and I am uncertain what consequences might occur if somebody does this on any given service.

So, what exactly does the "System" startup type do, and what is an example Windows service where enabling it would be safe? Additionally, can a service be set to use the "System" StartupType value through Powershell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e165924-1ae5-9e65-7660-51676680a63c
* Version Independent ID: 6cffca1e-ef66-505b-d610-1a9f5867e116
* Content: [Set-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-service?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Set-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Set-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
These are the values supported by the cmdlet:

```
Name                           Value
----                           -----
AutomaticDelayedStart          10
Disabled                       4
Manual                         3
Automatic                      2
InvalidValue                   -1
```

There is no "System" Startup type.

**Comment by sdwheeler** [comment]
@Amaroq-Clearwater You may be getting confused with the driver startup type.  See https://docs.microsoft.com/en-us/windows/desktop/CIMWin32Prov/win32-systemdriver for a description of those options.

**Comment by sdwheeler** [comment]
The values for driver Startup Type are:

```
Name            Value
----            -----
Boot            0
System          1
Auto            2
Manual          3
Disabled        4
```

`Get-Service` will get information about a driver but `Set-Service` does not allow you to change the Startup type to "System" or "Boot" for a driver because those values are not supported by the cmdlet.

**Comment by martinzugec-ctx** [comment]
@sdwheeler Sorry, I'm a bit confused why this ticket has been closed. 

I have the same problem, dealing with CSC service (System start up type). Is there any reason why Set-Service does not support value 1 (SYSTEM)? 

In my code, when I encountered "SYSTEM" start up type, I make changes directly to registry instead of using Set-Service and I can confirm that it works just fine, so curious if support for system could be added? 

Thanks

**Comment by sdwheeler** [comment]
This is not a documentation issue. The cmdlet works as documented. It is not designed to work on drivers, only services, even though those are in the same registry location and share many properties and values.

You can file a feature request in the PowerShell product repo at https://github.com/PowerShell/PowerShell/issues.

**Comment by fidaay** [comment]
> @sdwheeler Sorry, I'm a bit confused why this ticket has been closed.
> 
> I have the same problem, dealing with CSC service (System start up type). Is there any reason why Set-Service does not support value 1 (SYSTEM)?
> 
> In my code, when I encountered "SYSTEM" start up type, I make changes directly to registry instead of using Set-Service and I can confirm that it works just fine, so curious if support for system could be added?
> 
> Thanks

I'm also here wanting to know what's the real difference between 1 system and 2 automatic. I couldn't find too much info about it.
