### ISSUE TITLE
Documentation for creating/distributing new versions

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/PowerShell-Docs#4053]
Hello,

I've been looking for articles outlining the process of versioning or updating modules/manifests.  I can't find much other than that the Publish-Module cmdlets article mentions it is recommended to first publish to a private testing repository.  So I could go do trial and error with that.
Is there any official guidance on how to create and distribute versions?

Thanks

**Comment by sdwheeler** [comment]
The PowerShell Gallery allows you to publish and maintain multiple versions of your module. See the documentation at: https://docs.microsoft.com/en-us/powershell/gallery/how-to/publishing-packages/publishing-a-package
