### ISSUE TITLE
Unable to Get Configuration Status

### ISSUE THREAD

**Issue by patrickboe** [MicrosoftDocs/PowerShell-Docs#4056]
Running this quickstart on Windows 10, Powershell 5.1, the `Start-DscConfiguration` command seems to work with the following output:

    Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
    --     ----            -------------   -----         -----------     --------             -------
    13     Job13           Configuratio... Running       True            [my hostname]       Start-DscConfiguration...

but then I get the following error when I run `Get-DscConfigurationStatus`:

    Get-DscConfigurationStatus : No status information available for node [my hostname]. Apply a configuration on the target node and try again.
    At line:1 char:11
    + $Status = Get-DscConfigurationStatus
    +           ~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Get-DscConfigurationStatus], CimException
        + FullyQualifiedErrorId : MI RESULT 1,Get-DscConfigurationStatus

Running the same on another (Windows Server 2012, Powershell 4) machine succeeds and gives me status on the started configuration.

Is this supported on Windows 10? Is there a windows feature that I'm missing or something to get this to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f08cab0-4336-4be4-9ea7-9d509ab0324d
* Version Independent ID: 39a04095-85ab-127e-e670-4306c8e5f0ab
* Content: [Quickstart - Create a website with DSC](https://docs.microsoft.com/en-us/powershell/dsc/quickstarts/website-quickstart#feedback)
* Content Source: [dsc/quickstarts/website-quickstart.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/quickstarts/website-quickstart.md)
* Product: **powershell**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by patrickboe** [comment]
adding the `-Verbose` and `-Wait` parameters to the Start-DscConfiguration helped me determine that the issue was in my winrm setup, and the `winrm quickconfig` command helped me diagnose and resolve the issue.

**Comment by sdwheeler** [comment]
Sounds like you solved your own issue.
