### ISSUE TITLE
Documentation incorrect: Proxy parameters do not exist on 5.1 and earlier

### ISSUE THREAD

**Issue by TheIncorrigible1** [MicrosoftDocs/PowerShell-Docs#4058]
As the title states, the `Install-PackageProvider` (and other) cmdlets in Windows PowerShell do not *have* the associated \*Proxy\* parameters.

Edit: It turns out my issue is actually with `v5.0`.  I do not have access to 5.1 in my environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b71210d-aafb-b78a-7112-9f513115c7cb
* Version Independent ID: 1ca59e2b-35f8-34c8-19ec-609bf8d11527
* Content: [Install-PackageProvider (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-packageprovider?view=powershell-5.1)
* Content Source: [reference/5.1/PackageManagement/Install-PackageProvider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PackageManagement/Install-PackageProvider.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
@TheIncorrigible1 Yes, you need to look at which version of PowerShellGet and PackageManagement you are running. That cmdlet is not available in the version of PackageManagement that shipped with PSv5.0.
