### ISSUE TITLE
Update install instructions for Ubuntu 18.04

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#4063]
See https://github.com/PowerShell/PowerShell/issues/8008 for details

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@SteveL-MSFT Does this need to be fix in v6.1 or is this only for 6.2?

**Comment by SteveL-MSFT** [comment]
I believe we started supporting 18.04 with 6.1

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/issues/8008#issuecomment-476985792 has the details of what needed to be changed (I have not verified.)

**Comment by johlju** [comment]
@TravisEz13 Still get this error in Ubuntu running in WSL that does not have PowerShell previousy installed

```bash
johlju@PC02:/$ sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Followed the docs here:

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804

I will try to reproduce this on another PC just to be sure.

**Comment by johlju** [comment]
I could not reproduce this error on a two other machines, so the problem must be in the specific ubuntu installation on one of my clients.
