### ISSUE TITLE
My Windows 10 1809 Machine only has PowerShell 1.0

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [MicrosoftDocs/PowerShell-Docs#4072]
For some reason, I am unable to find or use Windows PowerShell 5.1 on my machine, despite the fact that it should already be installed. Instead, my system only has PowerShell 1.0 installed, and when I try to use the WMF 5.1 installer, it fails because I am already using Windows 10, version 1809. What is going on, and how do I fix this? I have tried using the "DISM /online /cleanup-image /restorehealth" function, and I have tried using "sfc /scannow." Neither seems to fix the issue. I am also unable to use the "Add or Remove Features" wizard in Windows to get PowerShell 5; the checkbox for it is mysteriously absent.

Not that it seems to matter; the PowerShell application will always either freeze or terminate upon launching, with no discernible cause or error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a41dae4f-37d1-cd70-878d-ced15eabb8a9
* Version Independent ID: 2abfcf1d-d210-824d-83a1-281457180e19
* Content: [Installing Windows PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-6)
* Content Source: [reference/docs-conceptual/install/Installing-Windows-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-Windows-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
How do you know you have PowerShell 1.0 loaded?

**Comment by sdwheeler** [comment]
@Amaroq-Clearwater You have PowerShell 5.1. Only the folder paths you see use the "v1.0" labeling. This was an early design decision that we are stuck with for backwards compatibility. To see what version you have, inspect the `$PSVersionTable` variable:

```powershell
PS C:\Git> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
