### ISSUE TITLE
CimCmdLet link 404

### ISSUE THREAD

**Issue by theking2** [MicrosoftDocs/PowerShell-Docs#4077]
https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/?view=powershell-6 is a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a02df8-d32e-9b35-13f8-144da738bfdd
* Version Independent ID: 18da97d2-8d78-2030-64de-49b5f571234c
* Content: [Sample scripts for system administration](https://docs.microsoft.com/en-us/powershell/scripting/samples/sample-scripts-for-administration?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/samples/Sample-Scripts-for-Administration.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Sample-Scripts-for-Administration.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
The URL: https://docs.microsoft.com/powershell/module/CimCmdlets/ also 404's, for what it's worth - it's not just the ?view=powershell-6  that is not found!

**Comment by DCtheGeek** [comment]
I'm seeing the same, and not just for this module. Appears that many modules are experiencing this.  Will look into it with @sdwheeler.  Thanks for pointing it out!

**Comment by DCtheGeek** [comment]
I've done a republish of the content and all the links appear to be working now.  I'm going to close this, but if it's still broken for you, report back and I'll re-open and we can investigate further. Thanks again for pointing this out!
