### ISSUE TITLE
Install-Module -Scope parameter description is confusing and partially incorrect

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#4082]
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/Install-Module.md currently states:

> When no Scope is defined, the default is set based on the current session:
>
>  * For an elevated PowerShell session, Scope defaults to AllUsers.
>  * For non-elevated PowerShell sessions in PowerShellGet versions 2.0.0 and above, the Scope is CurrentUser.
> * For non-elevated PowerShell sessions in PowerShellGet versions 1.6.7 and earlier, Scope is undefined, and Install-Module fails.

* From what I can tell, the default scope is _not_ related to whether the session at hand is elevated (run as admin) - that is, in v2.x the default is `CurrentUser`, whether or not the session is elevated.

* For 1.x versions, the scope isn't _undefined_, it defaults to `AllUsers` - and therefore requires elevation. Also, mentioning 1.6.7 specifically isn't necessary, since it is the last 1.x version released - doing so only makes people wonder wether there are later 1.x versions that behave differently.

Here's what I suggest:

> When no Scope is defined, the default is set based on the PowerShellGet version:
>
> * In PowerShellGet versions 2.0.0 and above, the default  is `CurrentUser`.
> * In PowerShellGet 1.x versions, the default is `AllUsers`, which means that elevation is required, unless you opt into the current-user scope with `-Scope CurrentUser`.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you speak to this issue?

**Comment by SydneyhSmith** [comment]
Thanks @mklement0 I understand the confusion, what is actually missing from this description is the difference in behavior between Windows PowerShell and PowerShell Core... What you provided is totally correct for PowerShell Core (and also clear and concise), however, for Windows PowerShell in an elevated session the default scope is AllUsers in all versions of PowerShellGet. In other words..For Windows PowerShell (version 5.1 or below), the default scope is AllUsers when running in an elevated session, and CurrentUser at all other times. For PowerShell version 6.0.0 and above, the default installation scope is always CurrentUser. This documentation could use improvement-thanks for bring this up!

**Comment by mklement0** [comment]
I see, @SydneyhSmith; thank you for clarifying the difference in behavior between Windows PowerShell and PowerShell Core - indeed I had focused just on the latter.
