### ISSUE TITLE
Missing argument for section "USING MULTIPLE CATCH STATEMENTS"

### ISSUE THREAD

**Issue by L1ttl3J1m** [MicrosoftDocs/PowerShell-Docs#4089]
$wc.DownloadFile("http://www.contoso.com/MyDoc.doc") will not trigger the first catch without a second argument containing a local filename.

$wc.DownloadFile("http://www.contoso.com/MyDoc.doc","c:\temp\testing.doc") will return the expected Error 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5957eb-39fd-033e-8272-fd7e427df848
* Version Independent ID: 1bda81bf-58e5-93b9-48e7-ff1ec3d465d0
* Content: [about_Try_Catch_Finally](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Fixed in #4092
