### ISSUE TITLE
Setting console colors

### ISSUE THREAD

**Issue by rjhintz** [MicrosoftDocs/PowerShell-Docs#4109]
By using Properties&gt;Colors I can change Screen Text, Screen Background, PopUp Text, and PopUp Background.

However, other colors are in use and it's not clear how to change them and have the changes persist across sessions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95c18b6e-e3ee-4f52-22b3-0548a2920c17
* Version Independent ID: 052688ad-8c1b-e997-5198-640f3c45fc23
* Content: [Getting Started with Windows PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/getting-started-with-windows-powershell?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/getting-started/Getting-Started-with-Windows-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/getting-started/Getting-Started-with-Windows-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
You can change the colors that PowerShell uses via the `$host` variable. Just change the color properties that you want.

```
PS C:\> $host.ui.RawUI

ForegroundColor       : Gray
BackgroundColor       : Black
CursorPosition        : 0,214
WindowPosition        : 0,170
CursorSize            : 25
BufferSize            : 105,9001
WindowSize            : 105,45
MaxWindowSize         : 105,81
MaxPhysicalWindowSize : 240,81
KeyAvailable          : False
WindowTitle           : PowerShell

PS C:\> $host.PrivateData

ErrorForegroundColor    : Red
ErrorBackgroundColor    : Black
WarningForegroundColor  : Yellow
WarningBackgroundColor  : Black
DebugForegroundColor    : Yellow
DebugBackgroundColor    : Black
VerboseForegroundColor  : Yellow
VerboseBackgroundColor  : Black
ProgressForegroundColor : Yellow
ProgressBackgroundColor : DarkCyan
```

**Comment by rjhintz** [comment]
`Screen Text`, `Screen Background`, `PopUp Text`, and `PopUp Background` mappings to the applicable `...RawUI` and `...PrivateData` colors should also be provided.

Also, it should be noted if this method makes the colors persist across sessions. If not, what would make changed colors persist?

**Comment by sdwheeler** [comment]
The changes don't persist but you could put these in your profile script so that they get set every time.

**Comment by sdwheeler** [comment]
There is not a one-to-one mapping of settings in the Properties dialog to the values in $Host. `Screen Text` and `Screen Background` map to $host.ui.RawUI.ForegroundColor  and BackgroundColor. But there is not equivalent for the Popup colors.
