### ISSUE TITLE
Installation of Powershell Core does not work on Katacoda

### ISSUE THREAD

**Issue by hardik2447** [MicrosoftDocs/PowerShell-Docs#4125]
I tried to follow the command for 16.4 but it did not work.

I tried below commands and it worked. Could you please update the same in this document

Install PowerShell Core on Ubuntu 16.04
# Import the public repository GPG keys
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# Register the Microsoft Ubuntu repository
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list

# Update apt-get
sudo apt-get update

# Install PowerShell
sudo apt-get install -y powershell

# Start PowerShell
pwsh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49e6e46-1221-3123-d750-0803e2f08195
* Version Independent ID: 94bd5a5b-a984-7edf-50bd-9f4dc1a020ef
* Content: [Installing PowerShell Core on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by hardik2447** [comment]
It is Ubuntu version 16.04

**Comment by sdwheeler** [comment]
@TravisEz13 Can you confirm this? Is this supported?

**Comment by TravisEz13** [comment]
I can't really find the docs for this distribution.  It would not be officially supported and I don't think we should document every ubuntu 16.04 equivalent distribution.  cc @joeyaiello
