### ISSUE TITLE
NoNewLine parameter is not supported

### ISSUE THREAD

**Issue by FrankHeimes** [MicrosoftDocs/PowerShell-Docs#4126]
The example `"a", "b" | Out-String -NoNewLine` listed above triggers an error in PowerShell 5.1.14393.2828.
The documentation should list the minimum supporting PowerShell version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb8aee2-8cf4-4e68-a9b6-83d57821e575
* Version Independent ID: 1925a288-f947-4a6e-cf91-8b106ef9e493
* Content: [Out-String (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-string?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Out-String.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Out-String.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@FrankHeimes You were looking at the v6 version of the documentation. You can switch to v5.1 documentation at the top of the page.

![image](https://user-images.githubusercontent.com/19415881/55737081-6774e480-59d9-11e9-80eb-6736a42c20f4.png)

See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-string?view=powershell-5.1. You will not that the -NoNewLine paramater does not exist.
