### ISSUE TITLE
Documentation Typo in about_Profiles?

### ISSUE THREAD

**Issue by maelcum** [MicrosoftDocs/PowerShell-Docs#4128]
Documentation of the about_Profiles page says in the first table after heading "THE PROFILE FILES":
```
Description                | Path
Current user, Current Host | $Home\[My]Documents\PowerShell\...
                           |                      ^-this-^
Current User, All Hosts    | $Home\[My]Documents\PowerShell\Profile.ps1
                                                  ^-this-^
```

Isn't it **always** ```...\*Windows*PowerShell\...``` ?
At least that's what ```echo $profile.CurrentUserAllHosts``` and ```echo $profile.CurrentUserCurrentHosts```output on a clean installation of Windows 10 since 160something.
All further references and tables on the about_Profiles page use "WindowsPowerShell", just the two entries above do not. Could this be a typo?

Have a nice day!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cb25e4-83db-3c4b-9805-ec2ef83223e1
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about_Profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
In PowerShell v6 (which is the version of the docs you were looking at), that is the correct path. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1.

**Comment by maelcum** [comment]
I searched for the page via a search engine and was routed here:
 https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6
And when I open this in a browser (Chrome (win), Chrome (mac), Edge (win), Safari (mac)) **all** pages show "PowerShell" not "WindowsPowerShell".
I **am** viewing Version 6 (which you correctly stated), not Version 5.1 (which is the link you were sending).

**Comment by sdwheeler** [comment]
```powershell
# PowerShell v6
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      2      0

PS C:\> $profile | select *user* | fl

AllUsersAllHosts       : C:\Program Files\PowerShell\6\profile.ps1
AllUsersCurrentHost    : C:\Program Files\PowerShell\6\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    : C:\Users\username\Documents\PowerShell\profile.ps1
CurrentUserCurrentHost : C:\Users\username\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

# PowerShell v5.1
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316

PS C:\> $profile | select *user* | fl

AllUsersAllHosts       : C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
AllUsersCurrentHost    : C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    : C:\Users\username\Documents\WindowsPowerShell\profile.ps1
CurrentUserCurrentHost : C:\Users\username\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

**Comment by maelcum** [comment]
Aaah! I finally got it. Thank you for your patience!!
