### ISSUE TITLE
Add documentation for binary literals

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#4143]
Issue Details
-----------------
Also note that now that PowerShell/PowerShell#7993 has been merged, binary literals will need to be mentioned as well. 

0b1011011 -> 91

This is related to issue #2965.

Version(s) of document impacted
------------------------------
- [x] Impacts 7.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by vexx32** [comment]
@sdwheeler it will also need to be noted that that PR also introduced `N` suffix for native BigInteger, which works like the other type suffixes:

```
PS> [bigint]1000000000000000000000000000000
1000000000000000019884624838656
PS> [bigint]"1000000000000000000000000000000"
1000000000000000000000000000000
PS> 1000000000000000000000000000000n
1000000000000000000000000000000
PS> 1000000000000000000000000000000n -is [bigint]
True
```

**Comment by sdwheeler** [comment]
@vexx32 Thanks. Good to know.
