### ISSUE TITLE
No what's new in v6.2 document

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#4146]
Issue Details
-----------------
Missing a what;s new in v6.2 document

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Looks like we are missing a what's new in PowerShell v6.2 from the table in https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6

@joeyaiello / @SteveL-MSFT - can we make sure that for 6.3/7 this is included as part of the pre-release tasks to complete as not to miss this in future?

**Comment by sdwheeler** [comment]
@joeyaiello Any updates on the draft I started?
