### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by benwa** [MicrosoftDocs/PowerShell-Docs#4147]
`HelloWolrd` in the code block under Compile the configuration should be `HelloWorld`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621757fb-71b6-10ae-b4f6-2d444a20de26
* Version Independent ID: 1f81473f-9c15-830f-e6b4-9ba0a5fd75bd
* Content: [Write, Compile, and Apply a Configuration](https://docs.microsoft.com/en-us/powershell/dsc/configurations/write-compile-apply-configuration#compile-the-configuration)
* Content Source: [dsc/configurations/write-compile-apply-configuration.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/configurations/write-compile-apply-configuration.md)
* Product: **powershell**
* Technology: **powershell-dsc**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by sdwheeler** [comment]
This was fixed in #4135. It will be published to live soon.
