### ISSUE TITLE
Change example prompt to something that reflects PowerShell Core's cross-platform presence

### ISSUE THREAD

**Issue by rkeithhill** [MicrosoftDocs/PowerShell-Docs#4150]
Issue Details
-----------------
Right now all of the examples in the PowerShell Core topics use `PS C:\>` as the prompt - **even on Linux** and I assume macOS as well.  Considering the significant majority of PS Core usage on Linux, it seems we should at least try to reflect some platform "neutrality" in the help.  

I propose a simple fix, just change the default prompt in the examples to `PS>`.  This change willl also give more room for the actual command before wrapping and is less visually "distracting".

FWIW I think you could apply this to <= 5.1 help and it would be just fine.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@rkeithhill I cover this in our style guide [here](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/contributing/5-FORMATTING-CODE.md#general-guidelines).

> PowerShell prompts in examples
> 
> PowerShell prompts should only be used in illustrative examples. Prompts should NOT be used in executable examples. For most of these examples, the prompt string should be "PS>". This prompt is independent of OS-specific indicators. Use of the prompt string is discouraged and should be limited to scenarios that are meant to illustrate command line usage. More complex prompt strings are required for examples that illustrate commands that alter the prompt or when the path displayed is significant to the scenario being illustrated. 

So, I agree with you. It is a work in progress. For the most part we are removing the prompts completely. See the full discussion in the linked style guide.

**Comment by bobbytreed** [comment]
Cleaned up prompts in reference/6 with automation. #4334
