### ISSUE TITLE
Mode information should be moved to FileSystem provider page, which should then be linked to from this one

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/PowerShell-Docs#4163]
The examples section gives an overview of the output when using various providers with `Get-ChildItem`. The first example, in particular, defines what the "Mode" fields in the output are when using the [`FileSystem` provider](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_filesystem_provider). This information would be more appropriately located on the `FileSystem` provider's page in a tabular format, and `Get-ChildItem` should then link to that page and section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afee1cf3-2e19-4a97-3794-815d54ef0097
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
We could link to microsoft.powershell.core/about/about_filesystem_provider#attributes-flagsexpression
