### ISSUE TITLE
Possible wrong example

### ISSUE THREAD

**Issue by bapcyk** [MicrosoftDocs/PowerShell-Docs#4165]
When I tried example `Get-ChildItem | Measure-Object -Sum {$_.Length/1MB}`, I got error:

```
PS D:\prj> Get-ChildItem | Measure-Object -Sum {$_.Length/1MB}
Measure-Object : The property "$_.Length/1MB" cannot be found in the input for any objects.
At line:1 char:17
+ Get-ChildItem | Measure-Object -Sum {$_.Length/1MB}
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Measure-Object], PSArgumentException
    + FullyQualifiedErrorId : GenericMeasurePropertyNotFound,Microsoft.PowerShell.Commands.MeasureObjectCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2ca891d-3680-dd96-ed4a-2c5f34e2bc2d
* Version Independent ID: bbf70122-605e-d627-556f-5f368b34378b
* Content: [Measure-Object (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/measure-object?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Measure-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Measure-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This works in PowerShell v6 but does not work in v5.1 and older. For v5.1 you can do the following:

```
Get-ChildItem  Measure-Object -Sum -Property Length |select {$_.Sum/1mb}
```

**Comment by bapcyk** [comment]
yes, true. OK
