### ISSUE TITLE
Unable to install on Kali Linux

### ISSUE THREAD

**Issue by bedimaanik** [MicrosoftDocs/PowerShell-Docs#4169]
Unable to install powershell as per the current instructions in https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#kali on new built kali linux VM

The error messages are as below:

_root@kali01:~# sudo wget http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-9_amd64.deb_
--2019-04-18 09:11:44--  http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-9_amd64.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 64.50.236.52, 64.50.233.100, 208.80.154.15, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-18 09:11:44 ERROR 404: Not Found.

_root@kali01:~# dpkg -i libicu57_57.1-9_amd64.deb_
dpkg: error: cannot access archive 'libicu57_57.1-9_amd64.deb': No such file or directory

**Comment by sdwheeler** [comment]
@TravisEz13 can you comment on this?

**Comment by TravisEz13** [comment]
The libicu url has changed.  See https://github.com/PowerShell/PowerShell-Docker/blob/7e37baae47945b37b1dcb284c76c6b6de9821c1a/release/community-stable/kali-rolling/docker/Dockerfile#L29
The filename would have changed as well.

**Comment by TravisEz13** [comment]
If they want web cmdlets to work, We should also recommend setting this variable
https://github.com/PowerShell/PowerShell-Docker/blob/7e37baae47945b37b1dcb284c76c6b6de9821c1a/release/community-stable/kali-rolling/docker/Dockerfile#L47

and installing these two packages 
https://github.com/PowerShell/PowerShell-Docker/blob/master/release/community-stable/kali-rolling/docker/Dockerfile#L64-L66

**Comment by sdwheeler** [comment]
@TravisEz13 Can you update the article as appropriate?
