### ISSUE TITLE
Issue with WinRM authentication for deploying on IOT 

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#4177]
In the Deploying on IOT, the example says:
```powershell
$s = New-PSSession -ComputerName &lt;deviceIp&gt; -Credential Administrator
```
however unless some configuration is done, this fails with the message:
```powershell
PS [C:\foo]> New-PSSession -ComputerName 10.10.1.3 -Credential administrator
New-PSSession : [10.10.1.3] Connecting to remote server 10.10.1.3 failed with the following error message : The WinRM client cannot process the
request. Default authentication may be used with an IP address under the following conditions: the transport is HTTPS or the destination is in the
TrustedHosts list, and explicit credentials are provided. Use winrm.cmd to configure TrustedHosts. Note that computers in the TrustedHosts list might
not be authenticated. For more information on how to set TrustedHosts run the following command: winrm help config. For more information, see the
about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ New-PSSession -ComputerName 10.10.1.3 -Credential administrator
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
```
I suggest that the example is updated to read:

```powershell
Set-Item -Path WSMan:\localhost\Client\TrustedHosts <deviceip>
$S = New-PSSession -ComputerName <deviceIp> -Credential Administrator
```
This applies to the other example(s) that use IP addresses to connect to a remote PS Session.

If folks agree to this change, I'm happy to do the updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfa3f4fc-5411-0135-c8c2-6615bb5584a1
* Version Independent ID: 0628c7a6-59c3-55cf-f1d3-7e348550281f
* Content: [Installing PowerShell Core on Windows](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@doctordns Go ahead and submit a PR to fix this. We will review. Thanks.
