### ISSUE TITLE
setting the colors don't have to be that hard

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#4185]
Setting the colors don't have to be that hard.  

```powershell
set-psreadlineoption -colors @{
  command            = 'darkyellow'
  number             = 'darkgray'
  member             = 'darkgray'
  operator           = 'darkgray'
  type               = 'darkgray'
  variable           = 'darkgreen'
  parameter          = 'darkgreen'
  continuationprompt = 'darkgray'
  default            = 'darkgray'
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 801e7046-e140-f89e-6f4e-700c9503107c
* Version Independent ID: 18945940-0df3-1027-612f-2adf6291d22d
* Content: [Set-PSReadLineOption (PSReadLine)](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-6)
* Content Source: [reference/6/PSReadLine/Set-PSReadlineOption.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PSReadLine/Set-PSReadlineOption.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by SteveL-MSFT** [comment]
This is great, we should add this as an example to set multiple colors

**Comment by jszabo98** [comment]
This is the way I prefer it in osx actually.  The default is too light for me.
