### ISSUE TITLE
PowerShell 6.0 Reference node goes to 404 page

### ISSUE THREAD

**Issue by EdisonDa** [MicrosoftDocs/PowerShell-Docs#4188]
[Enter feedback here]

1. Open PowerShell Module browser
2. Click PowerShell 6.0
3. Clicks on Cimcmdlets, or other nodes, it goes to
https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/?view=powershell-6
However this is an 404 page
4. If you go to the PowerShell 6.0 page and click on Cimcmdlets node, it will also goes to 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b107c67-3c32-3f32-9d21-bc054f6f6401
* Version Independent ID: b62273fe-e9f9-758f-bf9c-31cef56093f6
* Content: [Remove-CimSession (CimCmdlets)](https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/remove-cimsession?view=powershell-6#feedback)
* Content Source: [reference/6/CimCmdlets/Remove-CimSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/Remove-CimSession.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by DCtheGeek** [comment]
@EdisonDa Thanks for letting us know.  Looks like it's actually all module root pages.  Will investigate.

**Comment by DCtheGeek** [comment]
@EdisonDa I've completed a manual re-publish and all module pages are now loading correctly.  Thanks again for pointing this out!

cc / @sdwheeler

**Comment by doctordns** [comment]
I can confirm it now works from here.
