### ISSUE TITLE
-Filter?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/PowerShell-Docs#4189]
No documentation for the filter parameter. On the individual cmdlets it only say the filter parameters syntax is defined by the provider.  one would think you then would find info on it here...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6fce6b2-f9e8-ddb1-b40c-7a7a5ed628eb
* Version Independent ID: 102c7640-4b05-128b-4a6c-13db8a3ccbe3
* Content: [FileSystem Provider](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_filesystem_provider?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Which cmdlets is it missing from? I see it in [Get-ChildItem](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-6) and others.

**Comment by Bartolomeus-649** [comment]
> The syntax of the filter, including the use of wildcard characters, depends on the provider. Filters are more efficient than other parameters, because the provider applies them when the cmdlet gets the objects. Otherwise, PowerShell filters the objects after they are retrieved.

where is this syntax that is dependent on the provider documented?

**Comment by sdwheeler** [comment]
The -Filter parameter is documented in the cmdlet reference for each cmdlet that uses it. There should be examples for the various providers supported by the cmdlet. If something is missing, submit an issue for that cmdlet.

**Comment by Bartolomeus-649** [comment]
@sdwheeler  have you even read the documentation?

This is what the documentation for Filter looks like for [Get-ChildItems](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-6#parameters)

> -Filter
> **Specifies a filter in the format or language of the provider**. The value of this parameter qualifies the Path parameter.
> 
> **The syntax of the filter, including the use of wildcard characters, depends on the provider.** Filters are more efficient than other parameters, because the provider applies them when the cmdlet gets the objects. Otherwise, PowerShell filters the objects after they are retrieved. 

As far as I can see there's no description of how to specify the `Filter` parameter at all, in the contrary, it very clearly states "**Specifies a filter in the format or language of the provider.** " and "**The syntax of the filter, including the use of wildcard characters, depends on the provider.**".   
This is a very clear indication that there should exist more detailed and explicit documentation on exactly what this "provider dependant" syntax is and looks like.
Perhaps I'm wrong, but it it seems like something that is "provider dependant" should be documented in the place the provider itself is documented.

Should I still submit an issue for this on each individual cmdlet that uses as PSProvider?

**Comment by sdwheeler** [comment]
Ok, fair enough. There were some changes to the provider and the cmdlet docs recently and I thought this had been covered, but the docs could be more explicit. The short answer is that all the providers that ship with PowerShell use the same wildcard pattern. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_wildcards

But since `-Filter` is implemented in the provider, other providers could have different rules.

We will work on making this clearer.
