### ISSUE TITLE
delete (Default) registry value?

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#4206]
How do you delete the (Default) value?  It doesn't seem possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a14a65e0-4f8f-3c82-2f58-88f79dd1c493
* Version Independent ID: 06246ea4-b812-b953-cb6e-740bd328b5bf
* Content: [Remove-ItemProperty (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-itemproperty?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Remove-ItemProperty.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Remove-ItemProperty.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
You cannot remove it but you can clear it using `Clear-ItemProperty`. And you can set it to a new value using 'Set-ItemProperty'

```powershell
PS C:\> Set-ItemProperty -Path HKCU:\Software\SDW -Name '(default)' -Value 'test'
PS C:\> Get-ItemProperty HKCU:\Software\SDW -Name '(default)'

(default)    : test
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Software\SDW
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Software
PSChildName  : SDW
PSDrive      : HKCU
PSProvider   : Microsoft.PowerShell.Core\Registry

PS C:\> Clear-ItemProperty -Path HKCU:\Software\SDW -Name '(default)'
PS C:\> Get-ItemProperty HKCU:\Software\SDW -Name '(default)'

(default)    :
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Software\SDW
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Software
PSChildName  : SDW
PSDrive      : HKCU
PSProvider   : Microsoft.PowerShell.Core\Registry
```
