### ISSUE TITLE
Remove-Service not a name of a Cmdlet

### ISSUE THREAD

**Issue by deeageMu** [MicrosoftDocs/PowerShell-Docs#4211]
On a Windows Server 2019 Remove-Service seems not to be avaiable. I added a Service with New-Service, but Remove-Service cannot be found.Which Server or PowerShell Version is needed for this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4febd11-ae9e-4b34-ca70-5929ee1222fa
* Version Independent ID: fb28372c-479d-c3bd-8f8a-f8c5523ac5cf
* Content: [Remove-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-service?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Remove-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Remove-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
`Remove-Service` was added in PowerShell 6.0. See https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6#cmdlet-updates
