### ISSUE TITLE
Add group policy settings to doc for powershell.config.json

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#4216]
- See related issue #2053
- Add PowerShell Core group policy definitions (PowerShell/PowerShell#10468) for v7

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 913be4e0-c3b5-b792-97c7-dbe49a321dbd
* Version Independent ID: 6d250551-e9f9-9ebc-4906-e4374133bed7
* Content: [about_PowerShell_Config](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by joeyaiello** [comment]
Spoke to @TravisEz13 about this today. Sounds like the GP behavior has changed and been broken a couple times throughout 6.x. We're going to wait until his investigation (tied to [this RFC](https://github.com/PowerShell/PowerShell-RFC/pull/180)) is complete before we decide how to doc this.

**Comment by anmenaga** [comment]
On a related note, [this document that describes policy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_group_policy_settings?view=powershell-6) needs some updates:
1) it describes only 3 out of 6 policies currently supported by PS Core;
2) in the beginning it mentions "Group policy settings in the User Configuration path take precedence over Group Policy settings in the Computer Configuration path." This is *not* what is currently written in the code and described in RFC.

**Comment by sdwheeler** [comment]
@anmenaga Can you submit a PR to fix the documentation?

**Comment by joeyaiello** [comment]
@TravisEz13 let's chat about this one whenever you're around. I think we might need an about_policy or something that lists all env variables, config values, etc (or links out to them).

But as a first step, we should just get this one accurate for 7.0

**Comment by anmenaga** [comment]
I updated the [high level document describing PowerShell Group Policy settings](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_group_policy_settings?view=powershell-6) `about_Group_Policy_Settings.md`. These updates also contain a reference to `PowerShell Core Policy` RFC for low-level details (order of precedence, etc...);

@joeyaiello @TravisEz13 I'm not sure if a separate document is needed; so please re-triage this issue.

**Comment by sdwheeler** [comment]
Marking this as completed. We should open a new issue if more documentation is needed.
