### ISSUE TITLE
very good and proper documentation for this cmdlet

### ISSUE THREAD

**Issue by edwio** [MicrosoftDocs/PowerShell-Docs#4234]
Great Job

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d60b0f68-af00-acfa-45a0-0e27674e884c
* Version Independent ID: 1684343c-50de-7907-ace2-7c39770fa7b7
* Content: [Getting WMI Objects Get WmiObject](https://docs.microsoft.com/en-us/powershell/scripting/samples/getting-wmi-objects--get-wmiobject-?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/samples/Getting-WMI-Objects--Get-WmiObject-.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Getting-WMI-Objects--Get-WmiObject-.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by DCtheGeek** [comment]
Thanks for the positive feedback, we appreciate it!

Tagging @sdwheeler to make sure he sees this.
