### ISSUE TITLE
ConvertTo-Json, ConvertFrom-Json should NOT case insensitive

### ISSUE THREAD

**Issue by linlin-dl** [MicrosoftDocs/PowerShell-Docs#4235]
[Enter feedback here]
I have a json object from Newtonsoft.Json, which has two properties such as "Name" and "name", When calling the cmd ConvertTo-Json and ConvertFrom-Json, it would exception: 
System.InvalidOperationException: Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 'Name' and 'name'.
↵   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

While I think it should not throw such exception since the properties should case-sensitive.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e3cde4-0833-4ffa-973d-53afea65d1ec
* Version Independent ID: 2d459bd3-89d3-098a-c5e6-d4c4073dd035
* Content: [ConvertTo-Json (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This would be a product issue not a docs issue. Please file this issue at https://github.com/PowerShell/PowerShell/issues/new/choose
