### ISSUE TITLE
CLI for -Command and -File is not documented properly

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#4238]
Issue Details
-----------------

Command line parameters -File and -Command is not documented properly:
- -File is not documented at all
- not mentioned that -Command requires redirected stdin input

Related https://github.com/PowerShell/PowerShell/issues/9494#issuecomment-487648892

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Need to update https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-6

**Comment by iSazonov** [comment]
Discussion in PowerShell repo is still open and perhaps we'll need to change a semantic of the parameter.

**Comment by sdwheeler** [comment]
I am updating the docs to speak to the current behavior as best as we can.
