### ISSUE TITLE
No example given in this page

### ISSUE THREAD

**Issue by SavindraSingh** [MicrosoftDocs/PowerShell-Docs#4239]
Can someone please provide an example on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2acce47c-79ad-fe12-fd0b-3c8c41afb2d0
* Version Independent ID: aa4edc10-7fe1-7252-461a-998b6223f02e
* Content: [Out-Default (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/out-default?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Out-Default.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Out-Default.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This has been fixed already.
