### ISSUE TITLE
What is a PSSnapIn?

### ISSUE THREAD

**Issue by joshuaalm** [MicrosoftDocs/PowerShell-Docs#4246]
https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules?view=powershell-6#porting-a-pssnapin

There is no explanation of what a PSSnapIn is here, nor a link to documentation explaining what it is.  Until this point, I don't think I've ever heard of a PSSnapIn, nor why I would want to write (?) one.  If knowing what one is would be essential to the purpose of creating a portable PowerShell module, then I am lost at this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e228a4f-cbf7-4bc5-2579-09a748f98fda
* Version Independent ID: 5343c03a-1bff-65cf-4600-405b904d02dd
* Content: [Writing Portable Modules](https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules?view=powershell-6#porting-a-pssnapin)
* Content Source: [reference/docs-conceptual/learn/Writing-Portable-Modules.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/Writing-Portable-Modules.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Snap-ins have been deprecated and are no longer supported in PowerShell v6. They were essentially the same as modules. The SDK documentation needs to be updated to remove references to snap-ins.
