### ISSUE TITLE
Removal of PSCore 6.3 in lifecycle diagram

### ISSUE THREAD

**Issue by harperse** [MicrosoftDocs/PowerShell-Docs#4248]
With the pending release of PSCore 7.0, shouldn't that succeed PSCore 6.3 in the diagram above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1739eb2-b949-32b5-0089-4606f18d1ee0
* Version Independent ID: 79858126-7fca-e46e-40b9-5051d215fc1e
* Content: [PowerShell Core Support Lifecycle](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/PowerShell-Support-Lifecycle.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Fixed in #4272
