### ISSUE TITLE
Adding to PSModulePath separator

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/PowerShell-Docs#4263]
Issue Details
-----------------

$p = [Environment]::GetEnvironmentVariable("PSModulePath")
$p += "C:\Program Files\Fabrikam Technologies\Fabrikam Manager\Modules\"
[Environment]::SetEnvironmentVariable("PSModulePath",$p)

The added path needs a leading SEMICOLON separator. The first example code is correct. The second is not.

$p += ";C:\Program Files\Fabrikam Technologies\Fabrikam Manager\Modules\"

**Comment by sdwheeler** [comment]
@Liturgist Which document has this issue?

**Comment by Liturgist** [comment]
Sorry. I revised it a couple of times and omitted the URL. It is the second example code.

https://docs.microsoft.com/en-us/powershell/developer/module/installing-a-powershell-module
