### ISSUE TITLE
New-PSSessionOption is not recognized by linux pwsh 6.1.3

### ISSUE THREAD

**Issue by dreyTee** [MicrosoftDocs/PowerShell-Docs#4265]
Is it really so now?
on pwsh 6.2.0 I'm getting an error:
`Invoke-Command : HTTPS on Unix does not currently support CA or CN checks. Use the PSSessionOption -SkipCACheck and -SkipCNCheck if you are certain you trust the server you are connecting to and the network in between.`
So I wanted to add `New-PSSessionOption` statement to script for all versions. got an error:
`New-PSSessionOption : The term 'New-PSSessionOption' is not recognized as the name of a cmdlet, function, script file, or operable program.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba18a094-43ba-5ae6-c744-dbe95fd6336d
* Version Independent ID: c8eefde4-7679-34c2-0491-5244b250d0ba
* Content: [Known Issues for PowerShell 6.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/known-issues-ps6?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/whats-new/known-issues-ps6.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/known-issues-ps6.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@joeyaiello Can you verify this behavior?

**Comment by dreyTee** [comment]
Upd.:
Adding details:
on 6.2.0 I  can't conenct to windows server with no certificate, pwsh advises me to use `PSSessionOption -SkipCACheck and -SkipCNCheck`
On 6.2.0 `PSSessionOption` works fine.
But I wanted an easy way to fix problem for all pwsh versions and add `PSSessionOption` to my scripts without checking pwsh version. On 6.1.3. I got error `New-PSSessionOption : The term 'New-PSSessionOption' is not recognized as the name of a cmdlet, function, script file, or operable program.`

Looks like this command is not implemented on 6.1.3 and we all should use latest available version.
Or check pwsh version and add these options only if pwsh ver>=6.2.0.
Fair enough.
