### ISSUE TITLE
Can you specify what the "NuGet-specific elements from the folder." are? 

### ISSUE THREAD

**Issue by saulcruz** [MicrosoftDocs/PowerShell-Docs#4276]
In the documentation it says:

Delete the NuGet-specific elements from the folder.  I have no clue of what these are. Would you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167cce58-9f50-ff4a-b6d2-72ffef1e506d
* Version Independent ID: 28feb0c7-54f8-1dab-c714-15ad6a8c1192
* Content: [Manual Package Download](https://docs.microsoft.com/en-us/powershell/gallery/how-to/working-with-packages/manual-download)
* Content Source: [gallery/how-to/working-with-packages/manual-download.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/gallery/how-to/working-with-packages/manual-download.md)
* Product: **powershell**
* Technology: **powershell-gallery**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by saulcruz** [comment]
Nevermind, these are the elements and they actually are in the documentation, my bad:

A NuGet package file includes the following NuGet-specific elements that aren't part of the original packaged code:

A folder named _rels - contains a .rels file that lists the dependencies
A folder named package - contains the NuGet-specific data
A file named [Content_Types].xml - describes how extensions like PowerShellGet work with NuGet
A file named <name>.nuspec - contains the bulk of the metadata

**Comment by eeskildsen** [comment]
I know, as @saulcruz (and I, thanks to him) found, the answer is right there in the text, but this seems like a UX opportunity: Busy people are skimming trying to get a module installed. Maybe a "(see above)" could be added to that particular step just as an amenity?

**Comment by davidsmatlak** [comment]
Reopened to make NuGet-specific elements more visible in the document.
