### ISSUE TITLE
about_Scopes is missing an important concept: internal "session states"

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#4288]
There are distinct "scope domains", called "(internal) session states" in the source code, that make up a single PowerShell session, as explained in [this excellent blog post](https://seeminglyscience.github.io/powershell/2017/09/30/invocation-operators-states-and-scopes) by @SeeminglyScience.

Documenting these in about_Scopes and giving them a _descriptive_ official name is important.

The summary is:

* All non-module code runs in a hierarchy of scopes whose root scope is the one and only global scope.

* All module code runs in a module-specific hierarchy of scopes that has its own root scope.
  * However, the global scope's definitions are still visible in module code. 

In other words: the only shared ancestral scope whose definitions are visible to both module and non-module code is the global scope.

I propose _not_ calling these distinct scope hierarchies _session states_, because the latter suggests a concept relating to a session _as a whole_, which is confusing. Additionally, _global session state_ is confusing, because only its _root_ scope is truly global. Finally, it is confusing that the word _scope_ is not in the name at all.

(As far as I know, the concepts aren't currently explained anywhere, but the confusing terms _are_ used in https://docs.microsoft.com/en-us/powershell/developer/module/how-to-write-a-powershell-module-manifest)

I propose the term _scope domain_ for these distinct scope hierarchies, but that is open to debate:

* The global "session state" would be called  _default scope domain_.
* Module-specific "session states" would be called  _module scope domains_.

@SeeminglyScience has voiced concerns in https://github.com/PowerShell/PowerShell/issues/8988#issuecomment-483658560:
> The word domain makes me think of something as Runspace level.

Perhaps _scope stack_ is a better alternative (though, strictly speaking, it can be a _tree_ in that multiple _sibling_ child scopes can exist in a single pipeline).

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by SeeminglyScience** [comment]
> Perhaps scope stack is a better alternative (though, strictly speaking, it can be a *tree* in that multiple sibling child scopes can exist in a single pipeline).

Personally I still like `stack`.  While it's true that multiple scopes can be *live* there can only be one *active* scope, that's the scope of the current command processor. (note "live" and "active" are terms I just made up, there isn't really an equivalent engine term afaik)

That said, `scope tree` works fine too.  Though with the above in mind, it does also make me think it's referring to the `ExecutionContext` (albeit less so)

Ultimately I suggest sticking with the terms used by the engine (e.g. `SessionState`, `SessionStateScope`, and `ExecutionContext`) or at the very least include a link to the real underlying type with every reference.  If someone wants to learn more about the internals by looking at the source, and all they know is the term "Scope Stack" then they'll get no where.

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience.

Given your explanation, I'm leaning towards _stack_ as well.

As for sticking with the internally used terms:

Creating a disconnect between the terminology used in the documentation and the one in the source code is unfortunate, but unavoidable if the priority is to provide descriptive, non-confusing terms to end users (and the source-code terminology doesn't meet that bar) - and I think it should be the priority.

Most end user will likely never look at the source code and therefore needn't know internally used names.

> at the very least include a link to the real underlying type with every reference.

I think it would be sufficient:

*  on the documentation side: to establish this link _only_ in *about_Scopes*, i.e., where these concepts are _introduced_: briefly mention the name of the underlying source-code construct, and optionally link to it.

* on the source-code side: to mention the documentation terms in the comments on the various classes.

**Comment by joeyaiello** [comment]
Deferring to @SteveL-MSFT on this one for more info, but I'm not understanding why "session state" isn't a good term, especially considering it's the historically used and understood term. It's fine to say that session states are scoped, or to describe a runspace as a stack of session states, but I feel like introducing an entirely new term is just setting ourselves up for even more confusion

**Comment by mklement0** [comment]
@joeyaiello 

>  but I'm not understanding why "session state" isn't a good term

To recap from the OP:

> I propose _not_ calling these distinct scope hierarchies _session states_, because the latter suggests a concept relating to a session _as a whole_, which is confusing. Additionally, _global session state_ is confusing, because only its _root_ scope is truly global. Finally, it is confusing that the word _scope_ is not in the name at all.

---

> considering it's the historically used and understood term. 

The term is not (properly) known to the vast majority of users, if I were to guess, given its lack of conceptual documentation and lack of descriptiveness.

Personally, my first encounter with it was quite recent, in the context of https://github.com/PowerShell/PowerShell/issues/5503#issuecomment-407202044
(I may have _seen_ it prior to that, but due to its vague name and lack of proper framing it didn't stick.)

The term is used _without explanation_:

* in https://docs.microsoft.com/en-us/powershell/developer/module/how-to-write-a-powershell-module-manifest, which is not part of the regular help system.

* in the `Import-Module` topic, but only in the description of the `-Global` parameter
  * In the context of that help topic the term is especially confusing, because there are numerous references to _sessions as a whole_, and not at least calling the scope stacks _internal_ session states (as in the source code) completely obscures the fact that we're talking about _part_ of a session.

* in the `New-ModuleManifest` help topic, which relates to an advanced use case (authoring a module)

It is also used with _completely unrelated meaning_ (albeit more descriptively) in the context of _remoting_:

* in the `Get-PSSession` help topic.
* in the `Invoke-Command` help topic.
* in the `about_Remote_Disconnected_Sessions` help topic 
* presumably also In the context of the `about_PowerShell_Config` help topic, though I'm frankly unclear on what the term refers to there.

Finally, the `about_Modules` topic mentions the term _session state API_, again without further explanation, and it sounds like that API also relates to a session _as a whole_.

**Comment by joeyaiello** [comment]
It's great data, and I agree we haven't been clear about the term. But its nomenclature is [well embedded in the API](https://docs.microsoft.com/dotnet/api/system.management.automation.sessionstate), and I believe the right move is to document it better. 

Talked about this one with @JamesWTruher and @BrucePay a couple weeks ago, not sure if either of them might be interested in writing more about session states, but I can see why it's confusing right now. 

> which is not part of the regular help system.

Totally acknowledged, that's a pet peeve of mine. There's tons of good content in that reference documentation, and I still have it on the backlog to figure out how to get it refactored into the "standard" content. It's not a small work item by any means.

**Comment by Kriegel** [comment]
I hope it is allowed to ask an other question here.
I came here in my search figure out what creates a new scope and what not.
There are things that looks like Scriptblocks like the `If(){}` or `Try{}Catch{}` that makes no new scope.
(Thanks to learn from @mklement0 )
And there are things like a binary cmdlets that make NO new scope but i think every body excpect a new scope there. (Thanks to learn from @SeeminglyScience!)

So what creates a new scope?

- Function
- Module
-  ....

**Comment by SeeminglyScience** [comment]
@Kriegel 

Modules *sort of* create a new scope, but not in the same way.  They create a `SessionState`, which has a scope associated with it, but it lives as long as the module does.  That's unlike other scopes that are typically fleeting, usually surviving for only a single command invocation. The `psm1` runs in that long-term scope, so in a way it's more accurate to say that a module is dot sourced.

- A function invocation (when not dot sourced, e.g. `. Invoke-FunctionName` does *not* create a new scope)
- An invocation of a script block (when not dot sourced) e.g. `{}.Invoke()` or `& $varThatHasAScriptBlock`
- Invocations from the `PowerShell.Invoke` API when `AddScript` specifies the parameter `useLocalScope` as `true` (confusing parameter name, `true` means to create a local scope for the invocation, `false` means to work like dot sourcing)
- Invocations from `$ExecutionContext.InvokeCommand.InvokeScript` on overloads with no `useLocalScope` parameter
- Invocations of `ScriptBlock` objects that have been converted into delegates, e.g. `([action]{ Do-Something }).Invoke()`
- Event subscription handlers registered via `Register-ObjectEvent` or similar command

Probably more. it's hard to create a conclusive list.

**Comment by Kriegel** [comment]
Hey @SeeminglyScience thank yo for your answer. (hug)
I think we are talking of different levels of abstraction.
I searched for an helping hand, for PowerShell beginners to better explain Variable Scoping.(essential knowledge for the job to do)
I think PowerShell beginners does not need to take the differences between `SessionState` as Scope and other kind of scopes into account!? (nice to know knowledge for extended use cases)
Maybe we divide the topic `about_Scopes` into separate tracks, Variable scopes and other kinds!?

_(I am new to GitHub Issues. I still do not know if it is OK to discuss this here? Or in a new Issue?)_
