### ISSUE TITLE
Powershell classes docs

### ISSUE THREAD

**Issue by seolog78** [MicrosoftDocs/PowerShell-Docs#4292]
One of the classes advantages is a possibility to reuse once developed classes in the future.
I would like to find in the "Powershell: about classes" text an example of storing classes as separate files and including them by reference in the main ps-script.
The background idea: to collect future capable classes as separate files by script development and save time and notation length using only "includes".
Such an example would have an essential education influence on the readers community.

**Comment by sdwheeler** [comment]
Some of this documentation exists already. See https://docs.microsoft.com/en-us/powershell/wmf/whats-new/class-overview.

But, I agree, we need more than this.
