### ISSUE TITLE
Update docs to explain how commands can be written to span multiple lines

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#4303]
Issue Details
-----------------
[PR 9614](https://github.com/PowerShell/PowerShell/pull/9614) adds two new scenarios where PowerShell scripters can span commands across multiple lines: when using named parameters, and when using splatting. This is very closely related to issue #3746. Documentation should be updated to explain how commands can be written to span multiple lines, as well as what is required to invoke a command whose name starts with a dash in some scenarios.

Version(s) of document impacted
------------------------------
- [X] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@KirkMunro has any part of this feature been merged into the v7 code branch? I see that https://github.com/PowerShell/PowerShell/pull/8938 was merged but I cannot get your examples to work in 7.0.0-preview.3.

**Comment by KirkMunro** [comment]
I'm going to close this for now because some of the direction I was going in on that PR has changed and I'm waiting for more progress/feedback/conclusion on the associated RFC.

Just focus on #3746 because that was merged and works in preview.3. If you can't get that working, let me know -- I know it works because I already use it.
