### ISSUE TITLE
Create an about_obsolete topic to define obsolete

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#4313]
https://github.com/PowerShell/PowerShell-RFC/pull/160#issuecomment-493570551

This is DotNet's definition:
https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?redirectedfrom=MSDN&view=netframework-4.8

**Comment by TravisEz13** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-obsolete

**Comment by joeyaiello** [comment]
Given that this isn't coming again any time soon, I'm going to close this for now. Most of this discussion was handled in the RFC discussion, and we can point to the .NET docs in the meantime, but I'm happy to revive this if it becomes a recurring issue.
