### ISSUE TITLE
ทำๆๆ

### ISSUE THREAD

**Issue by yang980** [MicrosoftDocs/PowerShell-Docs#4319]
[ป้อนคำติชมที่นี่]

$s = Get-CimInstance -Query "Select * from Win32_Service where name like 'Winmgmt'"

Get-CimClass -ClassName *Service* -Qualifier "Association"

$c.CimClasName
Win32_LoadOrderGroupServiceDependencies
Win32_DependentService
Win32_SystemServices
Win32_LoadOrderGroupServiceMembers
Win32_ServiceSpecificationService

Get-CimAssociatedInstance -InputObject $s -Association Win32_DependentService
---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 490c6033-dd6b-93ff-9212-71fd17d1f057
* Version Independent ID: 56a1b9d3-7179-a076-6bed-860a73663af4
* Content: [Get-CimAssociatedInstance (CimCmdlets)](https://docs.microsoft.com/th-th/powershell/module/CimCmdlets/Get-CimAssociatedInstance?view=powershell-6)
* Content Source: [reference/6/CimCmdlets/Get-CimAssociatedInstance.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/Get-CimAssociatedInstance.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by doctordns** [comment]
What is the issue?
