### ISSUE TITLE
Reading file into secure string

### ISSUE THREAD

**Issue by MikeChristensen** [MicrosoftDocs/PowerShell-Docs#4331]
How can we convert a password stored in a plain text file to a secure string?  `$pwd = (ConvertTo-SecureString -Force -AsPlainText (Get-Content $pwdPath))` doesn't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52605c5-6045-d94b-261e-039aaac10063
* Version Independent ID: cf245177-58bc-6ec9-9862-a6dcec398762
* Content: [ConvertTo-SecureString (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertto-securestring?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by sdwheeler** [comment]
```
$pwd =  Get-Content $pwdPath | ConvertTo-SecureString -Force -AsPlainText
```

**Comment by MikeChristensen** [comment]
Ah yes, it wasn't working for me because the file was Unicode with no BOM.  To fix, you'd use `$pwd =  Get-Content -Encoding Unicode $pwdPath | ConvertTo-SecureString -Force -AsPlainText`
