### ISSUE TITLE
Incorrect term used

### ISSUE THREAD

**Issue by ferrarikarthik** [MicrosoftDocs/PowerShell-Docs#4340]
cmdlets term has to be replaced by the term functions. The Microsoft.PowerShell.Archive module contains the functions Compress-Archive and Expand-Archive. 

The CommandType of Compress-Archive and Expand-Archive are Function.
It would be confusing for the readers if we use cmdlets word instead of functions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e771256c-4d17-700f-d50a-62fd64214590
* Version Independent ID: aa1d51f7-ebe2-8d97-aed8-70d3bb5c718c
* Content: [Microsoft.PowerShell.Archive](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

**Comment by sdwheeler** [comment]
The fact that these are functions is an implementation detail. The implementation is subject to change in future versions. By definition, cmdlets defined in scripted modules are implemented as [Advanced Functions](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced).
