### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by rasmusjelsgaard** [MicrosoftDocs/PowerShell-Docs#4341]
I believe there is a mistake in the docs. Where it says 'NotNegative' should be 'NonNegative', as in    [ValidateRange("NonNegative")] instead of [ValidateRange("NotNegative")]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb965b0-d3fe-4343-f520-9e24f55ded23
* Version Independent ID: 4eac80f8-61be-4d0f-d657-a007ba81cf53
* Content: [about_Functions_Advanced_Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by DCtheGeek** [comment]
Looking at the ValidateRangeKind Enum (https://docs.microsoft.com/dotnet/api/system.management.automation.validaterangekind) this looks correct.  Thanks for reporting!
