### ISSUE TITLE
So how do I disable Command precedence?

### ISSUE THREAD

**Issue by Matti-Koopa** [MicrosoftDocs/PowerShell-Docs#4343]
The article doesn't have a global solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2230f0bc-3778-308e-5241-34cfb95f40fa
* Version Independent ID: de508ff7-85fd-b559-9fa5-9252149f9def
* Content: [about_Command_Precedence](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You cannot disable command precedence. You can control which command gets run by using qualified names or prefixes, as described in the article.
