### ISSUE TITLE
Remove-Alias : no such command?

### ISSUE THREAD

**Issue by akurzawa** [MicrosoftDocs/PowerShell-Docs#4345]
Remove-Alias : The term 'Remove-Alias' is not recognized as the name of a cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9940d5-646f-5385-a1b8-af925a94f379
* Version Independent ID: cb2ad8bb-2cf2-3340-5e22-24be80c67cd7
* Content: [Remove-Alias (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/remove-alias?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Remove-Alias.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Remove-Alias.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This is new to PS v6.
```
PS C:\Git> gcm Remove-Alias

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Remove-Alias                                       6.1.0.0    Microsoft.PowerShell.Utility
```
