### ISSUE TITLE
The same as Get-Module?

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/PowerShell-Docs#4348]
Please explain difference with Get-Module command. I know that module can be visible in Get-Module, and not visible in Get-InstalledModule, but I do not see any explanation how that happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1259930-c7f2-c62e-82b8-725ba331d79e
* Version Independent ID: 87643ffc-385e-a865-bb1d-ec3f48d73072
* Content: [Get-InstalledModule (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershell-6)
* Content Source: [reference/6/PowerShellGet/Get-InstalledModule.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/Get-InstalledModule.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
`Get-Module` returns a list of modules loaded in the current session. `Get-Module -ListAvailable` returns a list of all modules installed on the system. `Get-InstalledModule` returns a list of modules installed by PowerShellGet. Also, the returned object is different between the two cmdlets.

**Comment by iricigor** [comment]
I was more referring to technical than declarative differences
- `Get-Module` is searching for `<Name>/<version>/`**`<Name>.psd1`** file and then listing found modules
- `Get-InstalledModule` is searching for `<Name>/<version>/`**`PSGetModuleInfo.xml`** (hidden) file and then listing those results.

But, this is just my finding, I am not sure about it.

**Comment by sdwheeler** [comment]
You are correct. And that difference is due to the fact that `Get-InstalledModule` is part of PowerShellGet and is reporting on modules managed by PowerShellGet. Whereas, `Get-Module` is broader in scope but it does not return any PowerShellGet module information.
