### ISSUE TITLE
Downloads and installs?

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/PowerShell-Docs#4349]
PowerShell modules are just plain text scripts. They are downloaded and unpacked to a specific location on local disk. But then, what it means that second part "installs module"? Can you please give some explanation on that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431fe2e9-4044-277c-d759-133522a53143
* Version Independent ID: f3b7d225-4b62-1930-75c5-fc35e1c402ff
* Content: [Install-Module (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-6)
* Content Source: [reference/6/PowerShellGet/Install-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/Install-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
Not all modules are text scripts. They can be compiled and contain multiple DLL assemblies. `Install-Module` installs the module into a location supported by `$env:PSModulePath`. `Save-Module` downloads a modules but does not install it.
