### ISSUE TITLE
Unable to handle StartupType from (Automatic - Delayed) to (Automatic)

### ISSUE THREAD

**Issue by ylaroche** [MicrosoftDocs/PowerShell-Docs#4354]
It is impossible to handle (Delayed Start) with this command. Even toggling from Automatic to Manual and then back to Automatic, if the services was previously Delayed Start, it will remain Delayed Start after.

Handling the Delayed Start via the registry key [HKLM:\SYSTEM\CurrentControlSet\Services\&lt;ServiceName&gt;\DelayedAutostart] does not work either. Removing the value will not remove the Delayed Start.

Unable to perform either via the Get-CimInstance -ClassName Win32_Service | Where-Object {$_.Name -eq '&lt;ServiceName&gt;'} | Set-CimInstance -Property @{DelayedAutoStart=$False} will report the value is read-only.

Is there no way in Powershell to handle the Delayed Start?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 761556c5-8969-671c-1dc0-89fabadd710b
* Version Independent ID: 6cffca1e-ef66-505b-d610-1a9f5867e116
* Content: [Set-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-service?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Set-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Set-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
There is no supported way to do that in PowerShell 5.1 or older. In PowerShell 6, `Set-Service` supports the `-StartupType AutomaticDelayedStart` option. Outside of PowerShell 6, you can use SC.EXE in a script as follows:

```
sc.exe config <servicename> start= delayed-auto
```
