### ISSUE TITLE
Add support for com object documentation

### ISSUE THREAD

**Issue by nbkalex** [MicrosoftDocs/PowerShell-Docs#4356]
Using typeinfo.GetDocumentation() you easily can add information for com object member

**Comment by sdwheeler** [comment]
@nbkalex Do you have a more complete example that shows an interesting use case?

**Comment by nbkalex** [comment]
I would like to have more information about a com object member:
  - helpstring - https://docs.microsoft.com/en-us/windows/desktop/midl/helpstring
  - argument names (having a function signature with more arguments of the same type might be confusing

**Comment by sdwheeler** [comment]
I get that. Do you have a more complete example of how to do this? Or are you asking for an example?

**Comment by nbkalex** [comment]
![ie_com_members](https://user-images.githubusercontent.com/29368999/58501194-7a5f9600-818c-11e9-9b2d-efa5f97ab655.jpg)

I would like to see more information about function signature: arguments name and help (available in the type library)

**Comment by sdwheeler** [comment]
@SteveL-MSFT This sounds like a feature request. Can you add this to the PowerShell issues?

**Comment by sdwheeler** [comment]
@joeyaiello / @SteveL-MSFT Please move this issue to PowerShell/PowerShell.

**Comment by joeyaiello** [comment]
Opened PowerShell/PowerShell#9768 to track the feature request

**Comment by nbkalex** [comment]
Hi everyone,

I already did a pull request for adding argument name to com method signature.

https://github.com/PowerShell/PowerShell/pull/9858

**Comment by nbkalex** [comment]
Hello guys,

I have more ideas for improvements, like adding com object member documentation and information for arguments passed by reference; add "[ref]" prefix to argument type.

What do you think?


![com_presentation_ideas](https://user-images.githubusercontent.com/29368999/59254210-7033a200-8c38-11e9-983d-c1057ecc4209.jpg)

**Comment by joeyaiello** [comment]
That's another code change, please file issues for code changes in the PowerShell/PowerShell repo. 

Also, I'd look into PSReadline tooltips with Ctrl+Space and see how they might be able to help you better:
![image](https://user-images.githubusercontent.com/1255187/63466371-fc6ffb80-c417-11e9-9652-93a0c42c6614.png)

**Comment by sdwheeler** [comment]
This has been added to release notes.
