### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by myronu** [MicrosoftDocs/PowerShell-Docs#4363]
It would be helpful to have some information on what errors are thrown and how to handle them. Most REST services use the status code to convey information to the caller. For example, I need to invoke a REST service to determine if something exists and I expect a 404 if it doesn't. There is nothing in this document to tell me how I might go about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1d7db7-efcc-e00e-eecd-18b26d2246f3
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Invoke-RestMethod?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The error is returned by the REST API not by the cmdlet. The cmdlet throws an exception for any non-2xx HTTP response.
