### ISSUE TITLE
[Windows.Storage.Istoragefile]

### ISSUE THREAD

**Issue by ZolarV** [MicrosoftDocs/PowerShell-Docs#4365]
Issue Details
-----------------
Unable to call methods contained within the Windows.Storage.IStorageFile 
Get-method returns the appropriate methods but calls to methods return "method not found".

```
[Windows.Storage.IStorageFile]::OpenAsync()
Method invocation failed because [Windows.Storage.IStorageFile] does not contain a method named 'OpenAsync'.
At line:1 char:1
+ [Windows.Storage.IStorageFile]::OpenAsync()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```
When trying to force load the reference assembly: Windows.Storage, assembly is not found

```
add-type -AssemblyName windows.storage
add-type : Cannot add type. The assembly 'windows.storage' could not be found.
At line:1 char:1
+ add-type -AssemblyName windows.storage
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (windows.storage:String) [Add-Type], Exception
    + FullyQualifiedErrorId : ASSEMBLY_NOT_FOUND,Microsoft.PowerShell.Commands.AddTypeCommand
```

Version(s) of document impacted
------------------------------
- [ ] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by ZolarV** [comment]
[Windows.Storage.IStorageFile].GetMembers() | select name

Name                    
----                    
OpenAsync               
get_FileType            
get_ContentType         
OpenTransactedWriteAsync
CopyAsync               
CopyAsync               
CopyAsync               
CopyAndReplaceAsync     
MoveAsync               
MoveAsync               
MoveAsync               
MoveAndReplaceAsync     
ContentType             
FileType

**Comment by sdwheeler** [comment]
What version of PowerShell and Windows are you using?

**Comment by ZolarV** [comment]
$PSVersionTable

Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
PSVersion                      5.1.17134.765                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
BuildVersion                   10.0.17134.765                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                       
SerializationVersion           1.1.0.1   

Windows:  10 Education edition, build 1803

**Comment by sdwheeler** [comment]
Try using Windows.Storage.StorageFile instead. If that does not work for you, then try posting your question to a support forum. For a list of community forums see: https://docs.microsoft.com/en-us/powershell/#pivot=main&panel=community
