### ISSUE TITLE
Missing ModuleVersion Parameter

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#4382]
The Import-DSCResource dynamic keyword also has a parameter of ModuleVersion which is missing from the documentation 

This is often used in configurations to ensure that updates to DSC Resource Modules don't break existing configurations by enforcing usage of a specific version of the Resource Module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be597630-dc52-1ef4-32fc-14d59e2f5ec1
* Version Independent ID: d6467fb8-ee22-1717-c05f-1f5fabf0a3da
* Content: [Using Import-DSCResource](https://docs.microsoft.com/en-us/powershell/dsc/configurations/import-dscresource#feedback)
* Content Source: [dsc/configurations/import-dscresource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/configurations/import-dscresource.md)
* Product: **powershell**
* Technology: **powershell-dsc**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by NReilingh** [comment]
@bobbytreed @sdwheeler Maybe about time to merge this commit?

**Comment by sdwheeler** [comment]
@bobbytreed It looks like you made the change to your private branch but it never got submitted to the staging branch.
