### ISSUE TITLE
Can't find either psedit or Open-EditorFile in remote session

### ISSUE THREAD

**Issue by yobyot** [MicrosoftDocs/PowerShell-Docs#4385]
Hello,

This would be cool if I could get it to work. Is there something "missing" at the remoted machine (an Ubuntu VM in Azure, very much like what the illustrations show.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a10e4b2-aca7-4aba-9ad1-d99d1bd7626f
* Version Independent ID: 3ffdba34-e346-e974-3d48-f273a0028ea8
* Content: [Using Visual Studio Code for remote editing and debugging](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode-for-remote-editing-and-debugging?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/components/vscode/Using-VSCode-for-Remote-Editing-and-Debugging.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/Using-VSCode-for-Remote-Editing-and-Debugging.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by yobyot** [comment]
Here's an image:

![image](https://user-images.githubusercontent.com/14332263/58763896-eea08d80-852e-11e9-8117-dfc8036e272b.png)

**Comment by sdwheeler** [comment]
PSEdit only exists inside of the PowerShell ISE or VS Code.

**Comment by yobyot** [comment]
Thanks. I cropped the image -- but if you look closely at the image, at the top you can see the errors are coming from a terminal session inside vscode. The terminal's options are shown at the top of the screen.

**Comment by sdwheeler** [comment]
Then this is not a doc bug, it is an issue with VS Code. Please file an issue at https://github.com/PowerShell/vscode-powershell/issues.

/cc: @TylerLeonhardt

**Comment by sdwheeler** [comment]
It is supposed to work.

If the feature was removed then this is a doc bug. Waiting for response from @TylerLeonhardt.

**Comment by TylerLeonhardt** [comment]
@yobyot, `psedit` only exists in the PowerShell Integrated Console which is the console provided by the, PowerShell extension. From your screenshot, you are using a regular PowerShell console in vscode which does not have `psedit` available.

**Comment by doctordns** [comment]
PSEdit in the ISE is a function and you can dis-assemble the function using Get-Command. So to replicate this from PowerShell Console, i just adaptaed the funcion and stuck this into my $Profile:

```powershell
Function PSEDIT {
 [CmdletBinding()]
 param([Parameter(Mandatory=$true)]$filenames)
 foreach ($filename in $filenames) {
  ls $filename | where {!$_.PSIsContainer} | %{
   $psISE.CurrentPowerShellTab.Files.Add($_.FullName) > $null }}
}
````

**Comment by yobyot** [comment]
@TylerLeonhardt Thanks.

**Comment by yobyot** [comment]
@sdwheeler Doc should be updated, IMO, to reflect the fact that you _must_ use the integrated console.

**Comment by doctordns** [comment]
PSEdit is a function that exists in the ISE by default. You can replicate this by adding this function definition into the Console's $profile:

```powershell
Function PSEDIT {
[CmdletBInding()]
param([Parameter(Mandatory=$true)]$filenames)
foreach ($filename in $filenames) {
dir $filename | 
  where {!$_.PSIsContainer} |
     %{
        start-process $Pshome\powershell_Ise.exe $filename
      }
   }
}
```

Of course, for those of us using VS Code, you can always just type **Code $filename** and it just works! Another reason I like VS Code.

**Comment by joeyaiello** [comment]
Per conversation with @sdwheeler, there's no way for the non-Integrated Console to be enlightened in VS Code to support `psedit` (it reports as an `xterm` terminal). To that end, we should doc that behavior and suggest usage of `code` as `doctordns` pointed out. (That usage of `code` would work the same as in any non-Code-hosted terminal

**Comment by yobyot** [comment]
I think the simpler answer is: doc that `psedit` _must_ be run in the integrated terminal provided by the PowerShell extension of vscode. That's the doc error, IMHO.

**Comment by TylerLeonhardt** [comment]
Yes, @sdwheeler please go with @yobyot's suggestion. `psedit` does more than what `code` does because it works on remote machines that you've `Enter-PSSession`'d into from the PowerShell Integrated Console.

**Comment by efd7887** [comment]
guys get used to it,  we will always have to fix microsofts shortcomings
