### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by MarkVanDerVoort** [MicrosoftDocs/PowerShell-Docs#4386]
I am missing a simple usage example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef898c5d-f53d-e730-7797-edbb6ebff8d5
* Version Independent ID: a426929a-2af8-1861-f1c0-3bea1399e2d5
* Content: [DSC Script Resource](https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/windows/scriptResource#feedback)
* Content Source: [dsc/reference/resources/windows/scriptResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/reference/resources/windows/scriptResource.md)
* Product: **powershell**
* Technology: **powershell-dsc**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by bobbytreed** [comment]
There are two examples in this document.  Is there a example type you are looking for?

**Comment by huzzeytech** [comment]
@MarkVanDerVoort I'm working on an example to publish a custom certificate template to a new CA. Will create a PR after I test it. There is also one here: https://blogs.technet.microsoft.com/ashleymcglone/2016/07/21/powershell-dsc-101-using-the-script-resource-to-enable-the-windows-firewall/
