### ISSUE TITLE
Querying Win32_product Class can create issues on some systems. This should be mentioned.

### ISSUE THREAD

**Issue by JustMatthew** [MicrosoftDocs/PowerShell-Docs#4388]
Win32_product Class is not query optimized. Queries such as “select * from Win32_Product where (name like 'Sniffer%')” require WMI to use the MSI provider to enumerate all of the installed products and then parse the full list sequentially to handle the “where” clause. This process also initiates a consistency check of packages installed, verifying and repairing the install. With an account with only user privileges, as the user account may not have access to quite a few locations, may cause delay in application launch and an event 11708 stating an installation failure.

https://support.microsoft.com/en-us/help/974524/event-log-message-indicates-that-the-windows-installer-reconfigured-al

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b9bd592-8fde-88fe-cd33-b8dc057fd179
* Version Independent ID: 33e9f1ae-458e-98ca-b410-a71b8be929fa
* Content: [Working with Software Installations](https://docs.microsoft.com/en-us/powershell/scripting/samples/working-with-software-installations?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/samples/Working-with-Software-Installations.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Working-with-Software-Installations.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@JustMatthew So what would you want changed in this article?

**Comment by JustMatthew** [comment]
Linking KB974524 ( https://support.microsoft.com/en-us/help/974524/event-log-message-indicates-that-the-windows-installer-reconfigured-al ) is all. That way if someone were to cut and paste "Get-WmiObject -Class Win32_Product" from the sample and run it against all of their Windows servers they may be aware of the risk.
