### ISSUE TITLE
Missing Cmdlet documentation

### ISSUE THREAD

**Issue by TurtleBeach** [MicrosoftDocs/PowerShell-Docs#4393]
It is bad enough that MS gratuitously saw fit to make syntax/cmdlet name changes. It is inexcusable that cmdlets are not fully documented.

Specifically, `select-azsubscription` does not appear in any "Chapter" in the reference section, nor is there an immediately obvious description of what the "Context" parameter is supposed to be.

It is both aggravating and frustrating to waste hours trying to determine how to perform a simple action - set the default subscription for a PS **6** command line session. Plenty of examples for older PS, but they don't work with PS 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86a0e8f4-0bdf-9f7f-14b7-0ef71bea2ba5
* Version Independent ID: 3d44b181-ee0c-e549-4855-05583f7481eb
* Content: [What's New in PowerShell Core 6.2](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-62?view=powershell-6)
* Content Source: [reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-62.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-62.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The Az cmdlets are not part of PowerShell core so the documentation is not in this location. You can find the documentation at https://docs.microsoft.com/powershell/azure/overview.
