### ISSUE TITLE
Please add one example of how to use this to call an Azure rest method using AAD authentication

### ISSUE THREAD

**Issue by mattneerincx** [MicrosoftDocs/PowerShell-Docs#4398]
Please please please add a single example explaining how to use this powershell function to call an Azure REST API using AAD authentication, there are simply no good examples anywhere I can find that make any sense!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27fb99c-9218-34c5-9952-65bee8c91b66
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
That documentation does not belong in this docset. I agree that there needs to be a good example of this but it should be in the REST API docs for Azure.
