### ISSUE TITLE
-ReplyTo parameter not supported

### ISSUE THREAD

**Issue by ckey1** [MicrosoftDocs/PowerShell-Docs#4406]
This article lists -ReplyTo as one of the parameters of the Send-MailMessage cmdlet in powershell. But in fact, that parameter is not valid. Searching around online, there are many people requesting such a parameter, but to the best of my knowledge it has not yet been added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c83231-92d9-9871-953b-17f701454830
* Version Independent ID: c6c8dfc2-ec43-2231-908a-3a7ac67aeb0b
* Content: [Send-MailMessage (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This parameter was added in v6.2. See the [Release Notes](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-62?view=powershell-6#general-updates-and-fixes)
