### ISSUE TITLE
execution of scripts is disabled

### ISSUE THREAD

**Issue by VaSquirrel** [MicrosoftDocs/PowerShell-Docs#4410]
I did an in-place upgrade Win2008R2EE to Win2012R2DC.
Power Shell script that was running fine began throwing error "...execution of scripts is disabled..."
Script is a step in a SQL 2008R2 SQL Agent job run as Type = PowerShell.
I tried Set-Execution Policy Unrestricted for various scopes but still got the error.
Machine Configuration - "Turn on Script Execution" was not configured.
I changed it to "Enabled" and "Allow all scripts".
The script stopped throwing the error.
I am not sure this is the preferred configuration but it will work for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac74a162-5426-ae3b-4e65-961a92513171
* Version Independent ID: ca5b7bf8-43a8-5efa-b56a-fa9d97cd2ed3
* Content: [about_Group_Policy_Settings](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_group_policy_settings?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
That is a group policy issue in your environment.

**Comment by VaSquirrel** [comment]
Thanks
I know what it is.  The description of how the setting works is, at best misleading.  It implies, that if the value is not configured then it is not applied, or not checked, or not effective, or ignored.
In practice, if the value is "not configured" then none of my scripts would run.  When I changed the value to enabled, then all the scripts would run.


Thanks,
Ray Herring
Cell 214-924-9498
