### ISSUE TITLE
Output format could be confusing vs. Find-Module

### ISSUE THREAD

**Issue by holyavengerone** [MicrosoftDocs/PowerShell-Docs#4412]
Executing ``Find-Module -Name "PowerShellGet"`` yields an output indistinguishable from the output of ``Get-InstalledModule -name "PowerShellGet"`` which is confusing and could be error-prone.

![https://i.imgur.com/I7f4CEY.png](https://i.imgur.com/I7f4CEY.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f7a02a-406c-8997-64b8-c7eb563fda7e
* Version Independent ID: 87643ffc-385e-a865-bb1d-ec3f48d73072
* Content: [Get-InstalledModule (PowershellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/PowershellGet/Get-InstalledModule.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PowershellGet/Get-InstalledModule.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
This is not a documentation issue. Please file an issue at https://github.com/powershell/powershellgallery/issues/new. Include what you would want changed to avoid confusion.

cc: @SydneyhSmith, @SteveL-MSFT

**Comment by holyavengerone** [comment]
Ahhh good point, my apologies for that. Haven't used Github in a little while and I must say the web of links and resources with everything Microsoft related is a tad dazzling to the uninitiated ;)

Thanks!
