### ISSUE TITLE
wow, where are all these -replace 2nd argument codes documented? (about_comparison_operators doc)

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#4417]
-replace has a lot of codes for the 2nd argument

$number Substitutes the last submatch matched by group number.
${name} Substitutes the last submatch matched by a named capture of the form
(?&lt;name&gt;).
$$ Substitutes a single "$" literal.
$& Substitutes a copy of the entire match itself.
$` Substitutes all the text from the argument string before the matching portion.
$' Substitutes all the text of the argument string after the matching portion.
$+ Substitutes the last submatch captured.
$_ Substitutes the entire argument string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41417680-da77-6c19-bbd0-522e694e7ff0
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
It is not the goal of this article to document regular expressions. We briefly talk about it in the About_regular_expressions article. But regex is a function of the underlying .NET. We link to the .NET documentation in About_regular_expressions. The information you are looking for is at: https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#substitutions

**Comment by jszabo98** [comment]
That regular expression page is not linked from the "about comparison operators" help page  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-6.  

This shorter one is:  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6

**Comment by jszabo98** [comment]
These aren't regular expressions.
