### ISSUE TITLE
LCM States

### ISSUE THREAD

**Issue by scott1138** [MicrosoftDocs/PowerShell-Docs#4432]
Wouldn't it be good to describe the output of this command and link to where ever the things like possible state values is documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a48b772e-de7d-5d03-7696-9d8418373996
* Version Independent ID: bec63c19-344e-1ce8-7257-86c7a99977a7
* Content: [Get-DscLocalConfigurationManager (PSDesiredStateConfiguration)](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/get-dsclocalconfigurationmanager?view=powershell-5.1)
* Content Source: [reference/5.1/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @nitinbps
* Microsoft Alias: **nitingup**

**Comment by chasewilson** [comment]
Hi @scott1138 , Thanks for the feedback! 

I agree with you on both counts. I'll put in a snippet showing the default output and a link to the [Configuring the Local Configuration Manager](https://docs.microsoft.com/en-us/powershell/scripting/dsc/managing-nodes/metaconfig?view=powershell-6#basic-settings) basic setting section where there is more information on each of the settings returned from the cmdlet. 

I'll be working to resolve this quickly and will let you know when it's resolved!
