### ISSUE TITLE
Examples for Character ranges and Numbers are reversed.

### ISSUE THREAD

**Issue by anolting** [MicrosoftDocs/PowerShell-Docs#4436]
Examples for Character ranges and Numbers are reversed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1473a9-d19e-26f6-6a90-13d802f0ed35
* Version Independent ID: ac918b8d-aece-5c59-2a88-64c1a91ff5f5
* Content: [about_Regular_Expressions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@anolting This looks correct to me. Am I missing something? Both examples are matching numeric characters but using different methods.

#### Character ranges

A pattern can also be a range of characters. This can be alphabetic
`[A-Z]`, numeric `[0-9]`, or even ASCII-based `[ -~]` (all printable
characters).

```powershell
# This expression returns true if the pattern matches any 2 digit number.
42 -match "[0-9][0-9]"
```

#### Numbers

The `\d` character class will match any decimal digit.  Conversely, `\D`
will match any non-decimal digit.

```powershell
# This expression returns true if it matches a server name.
# (Server-01 - Server-99).
"Server-01" -match "Server-\d\d"
```
