### ISSUE TITLE
Highlight console in "The Profile Files"

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/PowerShell-Docs#4445]
I kept looking at [The Profile Files](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6#the-profile-files) and wondering what "Current Host" meant out of the context of an actual host. I was obviously skimming, but kept missing that this was **an example** of the _PowerShell console_. I think this section could be renamed as "Example: Console Profile Files"

I think these sections could be reorganized as 

- Profile Priority (or maybe this just merges in with "The $Profile Variable")
- The $Profile Variable
- Example: Console Profile Files
    - In this table, I would switch the first column of "Description" to "Name" (i.e. use "$Profile.AllUsersAllHosts" instead of "All Users, All Hosts")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cb25e4-83db-3c4b-9805-ec2ef83223e1
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about_Profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
I think it is clear as written.

**Comment by MisinformedDNA** [comment]
Congratulations, but just because you think it's clear doesn't mean it can't be improved. Maybe try listening to your customers instead of instantly shutting them down. Not many people make me feel unwelcome on GitHub, but congrats on being one of the few.

Adding @SteveL-MSFT for exposure sake.

**Comment by sdwheeler** [comment]
I think the changes in #4444 should be sufficient.

**Comment by MisinformedDNA** [comment]
Ah, I hadn't seen that yet. I think that does improve things. Thanks.

**Comment by sdwheeler** [comment]
This is fixed in PR #4444.
