### ISSUE TITLE
Why are all the sections capitalized?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/PowerShell-Docs#4446]
Having all the sections capitalized is unusually for MS Docs. Is there a reason this page does it differently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cb25e4-83db-3c4b-9805-ec2ef83223e1
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about_Profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6#the-profile-files)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
It is legacy formatting. We are changing the style as we update files. But it takes time.

**Comment by MisinformedDNA** [comment]
Is there another issue tracking this? Otherwise, this issue should remain open.

**Comment by sdwheeler** [comment]
This is fixed in PR #4448.
