### ISSUE TITLE
MVA has been retired.

### ISSUE THREAD

**Issue by charliearcuri** [MicrosoftDocs/PowerShell-Docs#4452]
The links under "Video Training" are re-routed to a new "Learning" site that doesn't appear to have any PowerShell content.  Bing'ing for "mva powershell", I found a note stating: "To simplify your tech training journey, we are consolidating our learning resources and retiring Microsoft Virtual Academy on June 10, 2019."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c74737d3-06fb-ab7f-9bea-4188e64631fe
* Version Independent ID: 1cf2d970-2d8d-1651-63a3-134217178c15
* Content: [More PowerShell learning](https://docs.microsoft.com/en-us/powershell/scripting/learn/more-powershell-learning?view=powershell-6)
* Content Source: [reference/docs-conceptual/learn/more-powershell-learning.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/more-powershell-learning.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
We are in the process of moving the old MVA content to Channel 9.  Here are the new locations:

Course | MVA URL | Channel 9 URL
-- | -- | --
Getting Started with Microsoft PowerShell | https://mva.microsoft.com/en-US/training-courses/getting-started-with-microsoft-powershell-8276 | https://channel9.msdn.com/Series/Getting-Started-with-Microsoft-PowerShell
Testing PowerShell with Pester | https://mva.microsoft.com/en-US/training-courses/testing-powershell-with-pester-17650 | https://channel9.msdn.com/Series/Testing-PowerShell-with-Pester
Getting Started with PowerShell Desired State Configuration (DSC) | https://mva.microsoft.com/en-US/training-courses/getting-started-with-powershell-desired-state-configuration-dsc-8672 | https://channel9.msdn.com/Series/Getting-Started-with-PowerShell-DSC
Advanced PowerShell Desired State Configuration (DSC) and Custom Resources | https://mva.microsoft.com/en-US/training-courses/advanced-powershell-desired-state-configuration-dsc-and-custom-resources-8702 | https://channel9.msdn.com/Series/Advanced-PowerShell-DSC-and-Custom-Resources
Advanced Tools & Scripting with PowerShell 3.0 Jump Start | https://mva.microsoft.com/en-US/training-courses/advanced-tools-scripting-with-powershell-30-jump-start-8277 | https://channel9.msdn.com/Series/Advanced-Tools-and-Scripting-with-PowerShell-3.0-Jump-Start
SharePoint Automation with DSC | https://mva.microsoft.com/en-US/training-courses/sharepoint-automation-with-dsc-17843 | https://channel9.msdn.com/Series/SharePoint-Automation-with-DSC

**Comment by CorgiDev** [comment]
> We are in the process of moving the old MVA content to Channel 9. Here are the new locations:
> 
> Course	MVA URL	Channel 9 URL
> Getting Started with Microsoft PowerShell	https://mva.microsoft.com/en-US/training-courses/getting-started-with-microsoft-powershell-8276	https://channel9.msdn.com/Series/Getting-Started-with-Microsoft-PowerShell
> Testing PowerShell with Pester	https://mva.microsoft.com/en-US/training-courses/testing-powershell-with-pester-17650	https://channel9.msdn.com/Series/Testing-PowerShell-with-Pester
> Getting Started with PowerShell Desired State Configuration (DSC)	https://mva.microsoft.com/en-US/training-courses/getting-started-with-powershell-desired-state-configuration-dsc-8672	https://channel9.msdn.com/Series/Getting-Started-with-PowerShell-DSC
> Advanced PowerShell Desired State Configuration (DSC) and Custom Resources	https://mva.microsoft.com/en-US/training-courses/advanced-powershell-desired-state-configuration-dsc-and-custom-resources-8702	https://channel9.msdn.com/Series/Advanced-PowerShell-DSC-and-Custom-Resources
> Advanced Tools & Scripting with PowerShell 3.0 Jump Start	https://mva.microsoft.com/en-US/training-courses/advanced-tools-scripting-with-powershell-30-jump-start-8277	https://channel9.msdn.com/Series/Advanced-Tools-and-Scripting-with-PowerShell-3.0-Jump-Start
> SharePoint Automation with DSC	https://mva.microsoft.com/en-US/training-courses/sharepoint-automation-with-dsc-17843	https://channel9.msdn.com/Series/SharePoint-Automation-with-DSC

I noticed a bunch of the videos under _Testing Powershell with Pester_ appear to have been removed. Are they just being updated? or is there a different set of videos that would be better for me to view?

**Comment by sdwheeler** [comment]
@theJasonHelmick do you know of any Pester videos we can link to?
