### ISSUE TITLE
Please explain how to get the response body when an exception is thrown.

### ISSUE THREAD

**Issue by hroe** [MicrosoftDocs/PowerShell-Docs#4456]
We need this for better error handling for POST requests to https://api.powerbi.com/v1.0/myorg/groups.
For http 400 errors, Fiddler revealed that response body has useful explanation, such as:
- {'error':{'code':'DuplicateGroupNameError','pbi.error':{'code':'DuplicateGroupNameError','parameters':{},'details':[]}}}
- {'error':{'code':'ADGraphGroupOperationFailedQuotaExceeded','pbi.error':{'code':'ADGraphGroupOperationFailedQuotaExceeded','parameters':{},'details':[],'exceptionCulprit':1}}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27fb99c-9218-34c5-9952-65bee8c91b66
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
You have to wrap it in a try/catch block. You may have to dig a few layers deep in the exception to find the root cause.

```
try {
    Invoke-RestMethod ... your parameters here ... 
} catch {
    # Dig into the exception to get the Response details.
    Write-Host "StatusCode:" $_.Exception.Response.StatusCode.value__ 
    Write-Host "StatusDescription:" $_.Exception.Response.StatusDescription
}
```

**Comment by sdwheeler** [comment]
@markekraus Is the body of the response available in the exception record?

**Comment by FISHMANPET** [comment]
@sdwheeler that code will output the code and the (generic) error message that gets printed to the console.  For a 400 error for example, that will get you "Bad Request"  But REST APIs generally send additional data in the body, which is what @hroe is referring to.
Because a non 2xx return code generates an exception, the cmdlet eats the data the API sends back (I would consider this a bug but this isn't the place for that).

The returned data is in the $error but you have to work to get at it:
```
$reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
$reader.BaseStream.Position = 0
$reader.DiscardBufferedData()
$reader.ReadToEnd() | ConvertFrom-Json
```

**Comment by hroe** [comment]
@fishmanpet @sdwheeler, 
thanks for pointing this out.
I had to drop the `|ConvertFrom-Json` as this results in `@{error=}`
With only `$reader.ReadToEnd` I get access to the response body, e.g.:
`{"error":{"code":"AddingAlreadyExistsGroupUserNotSupportedError","pbi.error":{"code":"AddingAlreadyExistsGroupUserNotSupportedError","parameters":{},"details":[]}}}`

Thanks, Herman

**Comment by FISHMANPET** [comment]
for what it's worth, after doing some more digging, I discovered that in PS6 that data is properly read and included directly in the error, so you only need to do that to get the error data on 5.1 and below.

**Comment by ojgarciab** [comment]
@FISHMANPET is right:

```
try {
    Invoke-RestMethod ... your parameters here ... 
} catch {
    # New in PS6
    Write-Error -Message $_.ErrorDetails.Message
    $error = $_.ErrorDetails.Message | ConvertFrom-Json
}
```

**Comment by msrinivascharan** [comment]
> @sdwheeler that code will output the code and the (generic) error message that gets printed to the console. For a 400 error for example, that will get you "Bad Request" But REST APIs generally send additional data in the body, which is what @hroe is referring to. Because a non 2xx return code generates an exception, the cmdlet eats the data the API sends back (I would consider this a bug but this isn't the place for that).
> 
> The returned data is in the $error but you have to work to get at it:
> 
> ```
> $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
> $reader.BaseStream.Position = 0
> $reader.DiscardBufferedData()
> $reader.ReadToEnd() | ConvertFrom-Json
> ```

Thank you @FISHMANPET , it worked.

**Comment by Jaykul** [comment]
Nowadays this is even easier. in 7.4 you can use `-SkipHttpErrorCheck` if you know the API will return an error response you can parse, or just check the `.Message` on the error by simply doing something like this:


```PowerShell
irm -Method Post http://localhost:8000/api/example -Err Fail
|| ConvertFrom-Json $Fail.Message
```
