### ISSUE TITLE
Restricted - "The default execution policy for Windows client computers."

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/PowerShell-Docs#4462]
This does not appear to be true. My windows home PC has all scopes as "Undefined" except Local machine, which is set as AllSigned.

I know it depends on the version of windows (7, 8,8.1, 10) as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b625828f-e35f-25e6-698f-1469d4817d6f
* Version Independent ID: cfa0b0d5-be1f-b9d2-533d-61bfa6051292
* Content: [about_Execution_Policies](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
That is not the result I get.
