### ISSUE TITLE
How to Connect from Mac to Windows PowerShell Remote 

### ISSUE THREAD

**Issue by gowrishcode** [MicrosoftDocs/PowerShell-Docs#4467]
Please help ?
```
PS /> Enter-PSSession -HostName 192.168.1.136 -UserName gowrish@outlook.com -SSHTransport
gowrish@outlook.com@192.168.1.136's password: 
Enter-PSSession : The SSH client session has ended with error message: The SSH transport process has abruptly terminated causing this remote session to break.
At line:1 char:1
+ Enter-PSSession -HostName 192.168.1.136 -UserName gowrish@outlook.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerShell.Commands.EnterPSSessionCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2c72de-1e9f-b263-e9d8-ccebd4c6ab3f
* Version Independent ID: f8beb543-51a4-1258-3dd5-eeccdac53c36
* Content: [PowerShell Remoting Over SSH](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by tej190691** [comment]
i am also facing same issue when i am trying to connect Linux(Ubuntu)  to windows 
 Enter-PSSession -HostName 18.209.7.14 -UserName Administrator -SSHTransport
The authenticity of host '18.209.7.14 (18.209.7.14)' can't be established.
ECDSA key fingerprint is SHA256:d8/rLil7DuJMO784blEpwUK3+3THBckxcQnbNaRo3PI.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '18.209.7.14' (ECDSA) to the list of known hosts.
Administrator@18.209.7.14's password:
Enter-PSSession : The SSH client session has ended with error message: The SSH transport process has abruptly terminated causing this remote session to break.
At line:1 char:1
+ Enter-PSSession -HostName 18.127.4.14 -UserName Administrator -SSHTra ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerShell.Commands.EnterPSSessionCommand

**Comment by sdwheeler** [comment]
Please take a look at the Open-SSH wiki at https://github.com/PowerShell/Win32-OpenSSH/wiki. If you still have problems, open an issue there.
