### ISSUE TITLE
S.M.A.PowerShell.AddScript() doc issues

### ISSUE THREAD

**Issue by vexx32** [MicrosoftDocs/PowerShell-Docs#4472]
Issue Details
-----------------

Refer to https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addscript?view=pscore-6.2.0#System_Management_Automation_PowerShell_AddScript_System_String_System_Boolean

I'm not sure if this doc is maintained in this repo, but I can't think of a better place to notify about doc issues. Note the mis-formatted examples. 🙂 

Version(s) of document impacted
------------------------------
- [ ] Impacts 7 document
- [X] Impacts 6 document
- [X] Impacts 5.1 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Transferred this issue to https://github.com/PowerShell/PowerShell/issues/15537
