### ISSUE TITLE
Format specifier for months and minutes are wrongly mentioned.

### ISSUE THREAD

**Issue by Divaksh** [MicrosoftDocs/PowerShell-Docs#4476]
Correct format specifier for the months is 'M' and for the minutes is 'm' but in the format specifier table, both are wrongly mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c5a5ea7-858f-5b1e-2c2f-24311876d7ac
* Version Independent ID: 09bab64d-b131-3961-a8c2-10ecf7f3d96b
* Content: [Get-Date (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Get-Date.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The documentation is correct. For the Unix format (`-UFormat`):
- `%M` is minutes
- `%,` is month

For the .NET format (`-Format`), see [DateTimeFormatInfo](https://docs.microsoft.com/dotnet/api/system.globalization.datetimeformatinfo) Class. 
- `M` is for month
- `m` is for minutes

**Comment by sdwheeler** [comment]
@davidsmatlak Link to https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings?view=netframework-4.8
