### ISSUE TITLE
Add information about how to address errors around required 'PackageManagement' and 'Provider' tags

### ISSUE THREAD

**Issue by SeanKilleen** [MicrosoftDocs/PowerShell-Docs#4477]
On a Server 2019 machine with no access to the internet, I have successfully added the nuget package provider file as described here (copied from a machine that was connected to the internet and ran the command successfully). 

Running `Get-PackageProvider -ListAvailable` shows the Nuget package provider v`2.8.5.208` available. However, running `Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force` results in the error:

> Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.

All I can find on the internet has to do with proxy settings (not applicable as no internet on this server) and TLS configuration (have tried with multiple configurations).

This appears to be a common issue when working with this package provider; mentioning it here so someone can update when the answer is found (or I can add it myself).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6406ad6-0e13-daf8-98fa-dfba63dcd0c2
* Version Independent ID: 3979cfab-57d0-d112-3be0-d285c9a79b92
* Content: [Bootstrapping NuGet](https://docs.microsoft.com/en-us/powershell/gallery/how-to/getting-support/bootstrapping-nuget#feedback)
* Content Source: [gallery/how-to/getting-support/bootstrapping-nuget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/gallery/how-to/getting-support/bootstrapping-nuget.md)
* Product: **powershell**
* Technology: **powershell-gallery**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by SeanKilleen** [comment]
I think I see the issue here. After copying, the provider is already available, so I need to import it, rather than install it; two different commands.

Since I've solved this issue for myself, let me know if you feel this would be a worthwhile contribution to the docs and I'm happy to write it up.

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you comment on this?

**Comment by SydneyhSmith** [comment]
@SeanKilleen thanks for opening this issue--if it helped you I am sure it would help others, we would appreciate the contribution!
