### ISSUE TITLE
The Get-UpTime cmdlet is not documented

### ISSUE THREAD

**Issue by glawrence** [MicrosoftDocs/PowerShell-Docs#4487]
Issue Details
-----------------
The `Get-UpTime` CmdLet has not been documented since PowerShell Core was introduced, no idea how I spotted this. I did consider doing a PR but the learning curve seemed a bit steep so hopefully someone experienced can pick this up? If not, then I will need some help!

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by glawrence** [comment]
Thank you very much for picking this up so quickly! I see there is a PR for putting this live as well, which is brilliant

**Comment by sdwheeler** [comment]
Try disabling quick boot.

```powershell
Powercfg -h off
Shutdown -r -t 20

## rebooting .....

Get-Uptime
```

This is a Windows-specific behavior. PowerShell is just returning the timestamp stored by Windows. That timestamp is not updated if quick boot is enabled.
