### ISSUE TITLE
How to list all the abbreviations regarding Alias

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/PowerShell-Docs#4488]
I see there's examples, but how to find the whole list?

| Noun or Verb | Abbreviation |
|--------------|--------------|
| Get          | g            |
| Set          | s            |
| Item         | i            |
| Location     | l            |
| Command      | cm           |
| Alias        | al           |
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49e9564d-9f60-34e9-0999-a28884358fb8
* Version Independent ID: d6ca56b9-7e77-fbaa-23ef-9081a316f296
* Content: [Using Familiar Command Names](https://docs.microsoft.com/en-us/powershell/scripting/learn/using-familiar-command-names?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/learn/Using-Familiar-Command-Names.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/Using-Familiar-Command-Names.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
There is no official list. These are the original common abbreviations that were implemented. Use the `Get-Alias` cmdlet to see the aliases that have been defined.
