### ISSUE TITLE
The documentation for the '-MaxTriggerCount' could be improved.

### ISSUE THREAD

**Issue by lxsocon** [MicrosoftDocs/PowerShell-Docs#4490]
It could do with at least 1 line explaining what is the meaning & intent of this parameter. The rest of the text appears to have been copied & pasted from the text for the '-Action' parameter, so could be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e9668c-933b-545f-985f-db892e5626a7
* Version Independent ID: 935f4b3f-3680-6230-77ca-22101a4b78dd
* Content: [Register-ObjectEvent (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/register-objectevent?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Register-ObjectEvent.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Register-ObjectEvent.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This is being addressed in #4491
