### ISSUE TITLE
UseSSL doesn't set firewall rules in Server 2019

### ISSUE THREAD

**Issue by jschpp** [MicrosoftDocs/PowerShell-Docs#4499]
As far as I understand this documentation
`Set-WSManQuickConfig` always sets the needed firewall rules.
At least in Server 2019 it doesn't set them if the switch `-UseSSL` is used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae86e2c-ebdc-6397-eb0d-43adedd1a1f1
* Version Independent ID: 1f4af9b9-c28d-9d95-4f7a-fe85d9047a0f
* Content: [Set-WSManQuickConfig (Microsoft.WSMan.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.wsman.management/set-wsmanquickconfig?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.WSMan.Management/Set-WSManQuickConfig.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.WSMan.Management/Set-WSManQuickConfig.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @PaulHigin
* Microsoft Alias: **paulhi**

**Comment by sdwheeler** [comment]
@PaulHigin Can you confirm or explain?

**Comment by PaulHigin** [comment]
I am unfamiliar with that cmdlet, but @manojampalam should be able to help.

**Comment by jschpp** [comment]
Just to specify this. It doesn't set the HTTPS-In rules to allow traffic to port 5896.
I haven't tested if it sets the HTTP-In rules.

**Comment by manojampalam** [comment]
AFAIR, it toggles HTTP rules (that are the only ones configured by default). you'll need to setup HTTPs rules manually.

**Comment by jschpp** [comment]
Ok. Then the documentation should be updated to reflect this.

**Comment by joeyaiello** [comment]
We'll talk to @manojampalam about this, but it's likely it won't be fixed (and certainly not any time soon), so it should be updated in documentation to reflect this.

**Comment by joeyaiello** [comment]
Should probably just link to this from our docs there: https://support.microsoft.com/en-us/help/2019527/how-to-configure-winrm-for-https
