### ISSUE TITLE
RequiresShellIDInvalidForSingleShell

### ISSUE THREAD

**Issue by bcdady** [MicrosoftDocs/PowerShell-Docs#4508]
[about_Requires](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7/Microsoft.PowerShell.Core/About/about_Requires.md) does not indicate any type of dependency between `-ShellID` parameter and `-PSSnapin`. Yet, if `-ShellID` is used in the #Requires statement (in this case, in my $Profile), then the following error is displayed:

``` pwsh
. : A #requires statement has specified only a shellID. #Requires statements must specify a required Windows PowerShell snap-in when running in Windows PowerShell.
At line:1 char:3
+ . '...\WindowsPowerShell\Microsoft.Powe ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Microsoft.PowerShell_profile.ps1:String) [], ScriptRequiresException
    + FullyQualifiedErrorId : RequiresShellIDInvalidForSingleShell

```

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

**Comment by SteveL-MSFT** [comment]
`-ShellId` was intended for `minishells` which never took off.  Since Windows PowerShell does require these two params to be used together, the docs should be updated to reflect this.  For PS7, we should consider removing these params altogether.
