### ISSUE TITLE
'Remove-Service' is not recognized as the name of a cmdlet, 

### ISSUE THREAD

**Issue by IdkwantandID** [MicrosoftDocs/PowerShell-Docs#4510]
Remove-Service : The term 'Remove-Service' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4febd11-ae9e-4b34-ca70-5929ee1222fa
* Version Independent ID: fb28372c-479d-c3bd-8f8a-f8c5523ac5cf
* Content: [Remove-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-service?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Remove-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Remove-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
This cmdlet was added in PS v6. See https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6#cmdlet-updates.

**Comment by IdkwantandID** [comment]
so put that requirement at the top of the page.  It should say require
powershell 6 somewhere on the page.  how else am i supposed to know that!

**Comment by sdwheeler** [comment]
There is a version selector at the top-left of the page. You were viewing the v6 documentation. You can select the version of PowerShell you are using to see the version-specific documentation.

**Comment by IdkwantandID** [comment]
remove  version  selector.  I was never there for windows version.

**Comment by dmckee-ebsco** [comment]
I agree with @IdkwantandID in that the required version **_should_** be listed on the doc pages. I swear I've seen "added in v6" on some of the doc pages, but maybe I haven't. Maybe that's not the standard. However, it would be **_very_** helpful if that was added somewhere on the page.

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6#new-cmdlets

**Comment by dmckee-ebsco** [comment]
Right, we get that it's explained in the 6.0 docs, but when you look at ANY doc page for a given command, the default is 6.0 (the latest). So how is anyone to know the versions supported for a given command?

For `New-Service` version support, do you expect everyone to go look at each version in the dropdown option to know which version it was added in? How does someone lookup version support for a cmdlet?

So you're link isn't helpful in my situation, because I'm looking at the command page and wondering what versions support it. IMO, then **_command_** help page needs version info. This one: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-service?view=powershell-6

**Comment by jdgregson** [comment]
I agree that it was abundantly unclear that this feature was introduced in PowerShell 6. PowerShell 5.1 is the default version installed on the most current Windows version -- there should be a big banner saying "this probably isn't applicable to you yet".

**Comment by devnuhl** [comment]
The Cmdlets' documentation should absolutely have "Added in v6" or "Available since 6.0". Additionally, depending on how you look at your Powershell, it can report that it is several different versions, until you hunt down the command to get it to spit out the version within the console. It will tell you to check out the cross-platform core6 when you open it, but not tell you the version you're running, which may be older than that.

**Comment by sdwheeler** [comment]
I added a note about being released in v6. But please see https://docs.microsoft.com/en-us/powershell/scripting/how-to-use-docs to make sure you are looking at the correct version of the documentation.

**Comment by MarkPflug** [comment]
If the Powershell docs could use a similar approach to the dotnet API docs, that would be really helpful. For example System.Span shows what versions it is available in:

Applies to
.NET Core
3.1 3.0 2.2 2.1
.NET Standard
2.1

**Comment by sdwheeler** [comment]
The doc already says `The Remove-Service cmdlet was introduced in PowerShell 6.0.`

**Comment by MarkPflug** [comment]
I'm aware. I'm just suggesting that it would be nice if the powershell docs were consistent in their layout with how the dotnet APIs are constructed, such that there is a section that contains version availability.

**Comment by chadbaldwin** [comment]
> I'm aware. I'm just suggesting that it would be nice if the powershell docs were consistent in their layout with how the dotnet APIs are constructed, such that there is a section that contains version availability.

Agreed. SQL docs are the same way. I just ran into this issue. I went to the PowerShell docs looking for Remove-Service but I'm used to looking for that banner across the top and I missed the note in the description which led me here. Sure, it's my fault for missing that, but it's also inconsistent.

For example, see CONCAT_WS for SQL Server:
https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql?view=sql-server-ver15

As soon as you open the page, at the very top you know exactly which versions of SQL server the function can be used for.

**Comment by egorpavlikhin** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-install-and-uninstall-services

- No version select dropdown on that page
![image](https://user-images.githubusercontent.com/1160707/91942599-8dbdc180-ed3e-11ea-90bc-d3a27f66499d.png)
- No mention of PowerShell v6

**Comment by Jacrys** [comment]
> I added a note about being released in v6. But please see https://docs.microsoft.com/en-us/powershell/scripting/how-to-use-docs to make sure you are looking at the correct version of the documentation.

The fact you have to have documentation on how to use your documentation proves your documentation system is fundamentally flawed. If your documentation (which arguably should be the most intuitive part of a program) is unintuitive enough to require a full document on how to read and use your documentation, users have no hope of understanding your applications.

**Comment by Korb** [comment]
```
Remove-Service : The term 'Remove-Service' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Remove-Service -Name "(...)"
+ ~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (Remove-Service:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
Microsoft Windows 10.0.19042.1110
Windows PowerShell **10**.0.1 Э041.546

**Comment by browolf** [comment]
version 5.1 lets me add the service but there's no way to remove it unless upgrade to version 6?
