### ISSUE TITLE
Send-MailMessage : Service not available, closing transmission channel. The server response was: #4.x.2 Too many   messages for this session

### ISSUE THREAD

**Issue by jasminewu229** [MicrosoftDocs/PowerShell-Docs#4514]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-6

I use send-mailmessage in my Azure Automation Runbooks, and every 16 send-mailmessage cmdlets, I get error: 
`Send-MailMessage : Service not available, closing transmission channel. The server response was: #4.x.2 Too many`

How do I dispose the session and start a new one?

**Comment by sdwheeler** [comment]
You would have to create a new PowerShell session. I don't know if can control that in Azure Automation.
