### ISSUE TITLE
SetSeed does not use System Clock?

### ISSUE THREAD

**Issue by MysticRyuujin** [MicrosoftDocs/PowerShell-Docs#4515]
The documentation states `By default, Get-Random uses the system clock to generate a seed value.` However, the actual source code for Get-Random (https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs) seems to suggest that by default (meaning, SetSeed is not provided as a parameter) it uses `System.Security.Cryptography.RandomNumberGenerator`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e654863e-148f-52a6-507b-3cd642d89c4e
* Version Independent ID: a3fd43f5-d4b9-d282-93bb-b0dce28b2fb0
* Content: [Get-Random (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-random?view=powershell-6#notes)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Get-Random.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Get-Random.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Verified that PSv5.1+ uses RandomNumberGenerator. Will update docs.
