### ISSUE TITLE
Missing the `-Assembly` parameter in about_Requires

### ISSUE THREAD

**Issue by travis-c-lagrone** [MicrosoftDocs/PowerShell-Docs#4518]
Issue Details
-----------------

The [About Requires] help file is wholly missing the `-Assembly` parameter of the `#Requires` directive, which is implemented by the .NET [`ScriptRequirements.RequiredAssemblies` Property].

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

The `-Assembly` parameter is missing from all versions of [About Requires], but I do not know whether it existed before 5.1. **Would you please help me to verify whether or not the `-Assembly` parameter was implemented in any/all of PowerShell 5.0, 4.0, and 3.0?**

[About Requires]:
<https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires>
'About Requires'

[`ScriptRequirements.RequiredAssemblies` Property]:
<https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.language.scriptrequirements.requiredassemblies#System_Management_Automation_Language_ScriptRequirements_RequiredAssemblies>
'ScriptRequirements.RequiredAssemblies Property'

**Comment by sdwheeler** [comment]
Current syntax:
```
#requires -Assembly path\to\foo.dll
#requires -Assembly "System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
```

@SteveL-MSFT When was this added?

**Comment by joeyaiello** [comment]
@SteveL-MSFT and I agree that this was *probably* added in 5.0 (at the latest), and we shouldn't backport it to earlier docs.

**Comment by xtqqczze** [comment]
Does `#Requires -Assembly` have any effect in Windows PowerShell 5.1 or earlier?

**Comment by sdwheeler** [comment]
@xtqqczze Yes, it is supported in PowerShell 5.1

**Comment by xtqqczze** [comment]
@sdwheeler I could not verify this functionality in Windows PowerShell 5.1, see https://github.com/PowerShell/PowerShell/issues/11098#issuecomment-624382575
