### ISSUE TITLE
Copy-paste error

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/PowerShell-Docs#4520]
In the output section, `Register-EngineEvent` is mentioned, but this should be `Register-ObjectEvent`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e84010d-cc3f-89d4-3f1c-e19d807d49c6
* Version Independent ID: 935f4b3f-3680-6230-77ca-22101a4b78dd
* Content: [Register-ObjectEvent (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/register-objectevent?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Register-ObjectEvent.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Register-ObjectEvent.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This is fixed in the source. It just has not be published live yet.
