### ISSUE TITLE
No link to MatchInfo

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/PowerShell-Docs#4525]
Can't see any link to the MatchInfo object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c82b0f-a14a-f62c-ab41-8952fd517462
* Version Independent ID: 86cda1f5-a5bf-45bd-d7d4-aa1a16134c7d
* Content: [Select-String (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Select-String.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
You can find that information at: https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.matchinfo?view=pscore-6.2.0
