### ISSUE TITLE
Suggestion: Enhance page structure to streamline navigation to pertinent instructions

### ISSUE THREAD

**Issue by bcdady** [MicrosoftDocs/PowerShell-Docs#4527]
Instead of organizing installation instructions by discrete Linux distribution and version, the options for installing PowerShell on Linux could be simplified to instructions per package manager, and optional manual steps for popular distribution families.
In lieu of elaborating in this description, I will submit a pull request for suggest alternative layout for this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49e6e46-1221-3123-d750-0803e2f08195
* Version Independent ID: 94bd5a5b-a984-7edf-50bd-9f4dc1a020ef
* Content: [Installing PowerShell Core on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
There is some redundant information. However, there can be differences in prereqs between versions and distros.
