### ISSUE TITLE
UseMinimalHeader available only from v6.2.1 onwards

### ISSUE THREAD

**Issue by srikcgaa2** [MicrosoftDocs/PowerShell-Docs#4551]
If there are additional parameters added to the command in the newest version of the stable release, there should be an indication which version onwards it is available.  I had 6.1.2 and going by this page, I used -UseMinimalHeader parameter and the script failed.  After I upgraded to 6.2.1, it started working.   The documentation should include such differences (Something like 6.2.1 and above) within a major release 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61f8b565-4cc3-6a77-94e6-15b97ebcbca7
* Version Independent ID: afe03c1f-3dbf-62f7-722a-d845777cadbd
* Content: [Start-Transcript (Microsoft.PowerShell.Host)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Host/Start-Transcript.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Host/Start-Transcript.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This information is in the release notes for 6.2 but I will get it added to the cmdlet reference.
