### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by JGCreator** [MicrosoftDocs/PowerShell-Docs#4557]
There are no examples for how to access the capture groups of matches returned when the input is non-scalar. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1473a9-d19e-26f6-6a90-13d802f0ed35
* Version Independent ID: ac918b8d-aece-5c59-2a88-64c1a91ff5f5
* Content: [about_Regular_Expressions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@JGCreator What do you mean by "non-scalar"? Can you provide an example you are trying to use?

Do you mean [Named captures](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-6#named-captures)?

**Comment by JGCreator** [comment]
As per the [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-5.1#-match) 

> When the input is scalar, it populates the $Matches automatic variable.
. . . 
If the input is a collection, the -match and -notmatch operators return the matching members of that collection, but the operator does not populate the $Matches variable.

Then there are several examples for how to use the `-match` operator. There are only 1.5 examples of using the `-match` operator on a collection and none of them indicate how to address the **capture group** results of the regex pattern.

There is an example for how to address **capture groups** if the input is scalar (ie. `"this is scalar" -match "^.+?(scalar)"`)

>PS> "Sunday", "Monday", "Tuesday" -match "sun"
Sunday
>
>PS> $Matches
PS>

But how would I access the capture groups if my example were as follows:

```
PS> $result = "Sunday", "Monday", "Tuesday" -match "s(un)"
PS> Write-Host $result
Sunday
```

**Comment by sdwheeler** [comment]
Ah, I see what you are asking now. The issue is that when you pass a collection, `$Matches` is not set. Therefore, there is no match object created that contains the capture group.

Try this:

```powershell
PS> "Sunday", "Monday", "Tuesday" | %{if ($_ -match "s(un)") {$Matches.1} }
un
```

You have to run `-match` on each object in the collection. Then you can get the capture group of the match.

**Comment by JGCreator** [comment]
It would be helpful to have a note in the documentation explaining that
-match doesn't respect regex capture groups on arrays and that $array |
String-Select -pattern $regex -AllMatches OR $array | %{ $_ -match $regex }
should be used.

Thanks

**Comment by sdwheeler** [comment]
The `-match` operator does respect the capture groups for the **purpose of comparison** matching. It just does not return a capture group when you compare a collection. That is documented. `Select-String` is the better choice when you need a match object with capture groups.
