### ISSUE TITLE
Out-Host makes the ANSI Color works

### ISSUE THREAD

**Issue by wzgy** [MicrosoftDocs/PowerShell-Docs#4567]
The document says that
Because Out-Host is the default, you do not have to specify it unless you want to use its parameters to change the display.

But without the "Out-Host", ANSI Color can not work.
I wanna know what the "Out-Host" does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3585e6a9-5868-ee46-e3ce-8fab9730728a
* Version Independent ID: bbb2cac0-8573-82e4-9b8d-d3de71835959
* Content: [Out-Host (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/out-host?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Out-Host.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@wzgy `Out-Host` is not really meant to be run by an end user. You can run it if you want to use the **Paging** parameter. `Out-Host` is automatically appended to every command that is executed. It passes the output of the pipeline to the host executing the command. It has nothing to do with the ANSI escape sequences. Those are handled by the host. `Out-Host` passes those escape sequences through to the host without trying to interpret or change them.
