### ISSUE TITLE
Ubuntu 14.04 is no longer supported

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#4576]
Ubuntu 14.04 is no longer supported and the instruction are inaccurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49e6e46-1221-3123-d750-0803e2f08195
* Version Independent ID: 94bd5a5b-a984-7edf-50bd-9f4dc1a020ef
* Content: [Installing PowerShell Core on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1604)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by davidsmatlak** [comment]
@TravisEz13 When PR #4581 was submitted to remove Ubuntu 1404 from Installing-PowerShell-Core-on-Linux, broken links were created in SSH-Remoting-in-PowerShell-Core. To resolve, the link and header were changed from Ubuntu 1404 to Ubuntu 1604.

**Comment by TravisEz13** [comment]
That should be fine.

**Comment by TravisEz13** [comment]
cc @PaulHigin
