### ISSUE TITLE
OutputTypeAttribute - Collections/Enumerations

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/PowerShell-Docs#4579]
What is the best practice when using the `OutputType` attribute on a cmdlet that may return zero, one or more values of type `T`?

`T`
`T[]`
`IEnumerable&lt;T&gt;`

Some combination?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f34dec8-4efb-f5e4-cbc8-c668b558d1a4
* Version Independent ID: 63e16527-901e-cff6-5f7c-8cf0ae6a2304
* Content: [about_Functions_OutputTypeAttribute](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-3.0)
* Content Source: [reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
If you are writing a scripted module or function, you should use `T[]`. If you are writing a compiled module, see: https://docs.microsoft.com/en-us/powershell/developer/cmdlet/outputtype-attribute-declaration
