### ISSUE TITLE
Add-Type's -ReferencedAssemblies documentation is inaccurate for PowerShell Core

### ISSUE THREAD

**Issue by irisxzhou** [MicrosoftDocs/PowerShell-Docs#4585]
Currently, in PowerShell Core, default references are included only if -ReferenceAssemblies is not specified (see linked issues below). However, the documentation states that "The assemblies that you specify by using this parameter are referenced in addition to the default assemblies."

https://github.com/PowerShell/PowerShell/issues/3779
https://github.com/PowerShell/PowerShell/issues/9599

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f33c4115-cf84-2571-c7bd-8f1e1f669239
* Version Independent ID: b550e1f5-2481-7908-1d62-607923d09a2b
* Content: [Add-Type (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Add-Type.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Add-Type.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@joeyaiello / @SteveL-MSFT This is a bug. How do you want to document this?

**Comment by joeyaiello** [comment]
Sounds like we need some language "On PowerShell 6+, `-ReferenceAssemblies` does not include the default .NET assemblies, so you must include a specific reference to them in the value passed to this parameter."
