### ISSUE TITLE
Add documentation for new ForEach-Object -Parallel parameter set

### ISSUE THREAD

**Issue by PaulHigin** [MicrosoftDocs/PowerShell-Docs#4590]
Issue Details
-----------------
This is associated with RFC: https://github.com/PowerShell/PowerShell-RFC/pull/194

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by iSazonov** [comment]
From @PaulHigin 
> I'll work on creating a blog that I hope will help make clear when using foreach -parallel is beneficial.

It would be nice to have this in documentation too.

**Comment by PaulHigin** [comment]
Document has been updated with PR: #4796
