### ISSUE TITLE
This page seems very out of date

### ISSUE THREAD

**Issue by ScottHutchinson** [MicrosoftDocs/PowerShell-Docs#4591]
It does not address Windows 10 or installing Windows PowerShell SDK 5.1.0.0. And I can't find a page that covers that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62f8acf-8682-9173-8f43-9c441d881a78
* Version Independent ID: 2ede62ff-463c-3e32-6d74-a5f8d95f4fa2
* Content: [Installing the Windows PowerShell SDK](https://docs.microsoft.com/en-us/powershell/developer/installing-the-windows-powershell-sdk)
* Content Source: [developer/installing-the-windows-powershell-sdk.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/developer/installing-the-windows-powershell-sdk.md)
* Product: **powershell**
* Technology: **powershell-developer**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is legacy documentation and is not being maintained.

**Comment by ScottHutchinson** [comment]
"And I can't find a page that covers that."

@sdwheeler  So where is the non-legacy page that covers that, please?

**Comment by sdwheeler** [comment]
There isn't a new downloadable SDK package like the one created for Windows PowerShell. There are new articles that describe developing cross-platform modules.

See the following:

- https://docs.microsoft.com/powershell/scripting//dev-cross-plat/choosing-the-right-nuget-package
- https://docs.microsoft.com/powershell/scripting//dev-cross-plat/create-standard-library-binary-Module
- https://docs.microsoft.com/powershell/scripting//dev-cross-plat/resolving-dependency-conflicts
- https://docs.microsoft.com/powershell/scripting//dev-cross-plat/Writing-Portable-Modules
