### ISSUE TITLE
$PSCulture follows CurrentThread.CurrentCulture

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#4594]
Issue Details
-----------------

Now $PSCulture is not constant and shows actual value of current culture for every runspace.
https://github.com/PowerShell/PowerShell/pull/10138

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@SteveL-MSFT How much should this be documented and where? Is this for the release notes or is there specific article that needs updating?

**Comment by davidsmatlak** [comment]
Discussed this with Steve and the guidance is to update **about_Automatic_Variables** that `$PSCulture` reflects the culture of the current runspace. And, to request @iSazonov to review the pull request.

**Comment by davidsmatlak** [comment]
@iSazonov please review PR #5098 and post an update to approve or request changes. Thank you.
