### ISSUE TITLE
Good help

### ISSUE THREAD

**Issue by IPlayZed** [MicrosoftDocs/PowerShell-Docs#4597]
Pretty clear explanation, thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bc5a9a-76fe-42f6-f11f-17e59af93f4f
* Version Independent ID: 8d0ef725-578d-bd63-8b4a-5a14a54f7dd4
* Content: [Installing PowerShellGet](https://docs.microsoft.com/en-us/powershell/gallery/installing-psget#feedback)
* Content Source: [gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-gallery**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by davidsmatlak** [comment]
Thanks for the feedback.
