### ISSUE TITLE
Customize Prompt Instructions

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#4601]
This page says you can customize the debug prompt, but provides no explanation as to how. Editing the prompt function doesn't seem to work, so more detail on that is needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f33c06a-b232-b202-9dfd-6ed3ccae6d96
* Version Independent ID: d82b3b88-19df-39cc-699f-2d1121ec409f
* Content: [about_Debuggers](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_debuggers?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Debuggers.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Debuggers.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_prompts for information about customizing the prompt.
