### ISSUE TITLE
Set-StrictMode -Off... Global or not?

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/PowerShell-Docs#4609]
The article says "Unlike the Set-PSDebug cmdlet, Set-StrictMode affects only the current scope and its child scopes."

But for the "-off" switch, it also says:

  [-off]  Indicates that this cmdlet turns strict mode off. This parameter also turns off Set-PSDebug -Strict.

The use of "also" indicates that turning strict mode off is somehow insufficient, that it also must also explicitly turn off Set-PSDebug -strict.  Does that mean Set-StrictMode impacts Set-PSDebug -strict globally?  If yes, clarification should be given.

If not, I would eliminate mention of Set-PSDebug for -off, as the article already establishes the equivalence between Set-PSDebug -strict and Set-StrictMode.  If it doesn't mention Set-PSDebug -strict for the -version option, it needn't do it for the -off option either.

Alternatively, make it say "[-off] Indicates that this cmdlet turns strict mode off. The effect is the same as turning off Set-PSDebug -Strict for current and child scopes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 085e9e8e-0df3-9bc3-4b3a-a213f6e63c3f
* Version Independent ID: 5d75ec72-b3dd-25c5-7ab8-27bc380be279
* Content: [Set-StrictMode (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Set-StrictMode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Set-StrictMode.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@daxian-dbw  Can you help out here?

**Comment by daxian-dbw** [comment]
`Set-PSDebug -strict` and `Set-PSDebug -off` affects all scopes, while `Set-StrictMode -off` affects only the current scope and child scopes. So `Set-StrictMode -off` impacts `Set-PSDebug -strict` only in the current scope and child scopes, not in any parent scopes.

Examples:
```powershell
Set-PSDebug -Strict
Write-Verbose $noexist -Verbose
& { Set-StrictMode -Off; Write-Host $noexist -Verbose }
Write-Verbose $noexist -Verbose
```
Running the above code will generate 2 errors about `$noexist` not being set.
