### ISSUE TITLE
OutputType for a function that doesn't return anything

### ISSUE THREAD

**Issue by JohnLBevan** [MicrosoftDocs/PowerShell-Docs#4612]
Please could you add a note on what should be done when a function has no return type?

i.e. In such a case is it best to omit OutputType completely, to provide `OutputType` with no types listed (i.e. `[OutputType()]`), or to define the output type as System.Void (i.e. `[OutputType( [System.Void] )]`), or something else?

My instinct is to go with `[OutputType( [System.Void] )]`, as this allows the option to include a parameter set name (e.g. ``[OutputType( [System.Void], ParameterSetName = 'Quiet' )]``); but I couldn't find documentation to confirm this.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a990181-b9f8-d212-41dd-afbe0b6442ce
* Version Independent ID: 63e16527-901e-cff6-5f7c-8cf0ae6a2304
* Content: [about_Functions_OutputTypeAttribute](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@SteveL-MSFT can you comment?

**Comment by joeyaiello** [comment]
@SteveL-MSFT agrees that that's probably a good best practice

**Comment by JohnLBevan** [comment]
FYI: noticed that though this issue's been closed, the documentation hadn't been amended.  I've made a change which I think should be appropriate; including both the `[System.Void]` piece discussed above, and additional info on non .Net types (since what's said about null seemed incorrect; i.e. the standard functions providing empty lists, and PS supporting the ability to define custom types or use "hash notation" for WMI management objects).  

Please let me know if you're happy with the suggested changes, and I'll then amend the related articles for v3 onwards, before submitting a pull request.  
If you're not fans of my suggested changes, please provide feedback and I'll amend or drop my changes, as per your preference.

**Comment by sdwheeler** [comment]
@SteveL-MSFT / @joeyaiello Can you have someone review the changes proposed here: https://github.com/JohnLBevan/PowerShell-Docs/commit/0849db9d499586eda9651cc24dd41a4ee3e00c6a?

**Comment by sdwheeler** [comment]
@JohnLBevan Thanks for your input. Please submit a PR for those changes. I will have the team review it. At first glance, your additions look to be on point but they should probably be added to the EXAMPLES section of the article.
