### ISSUE TITLE
Example 3: Encrypt an exported credential object

### ISSUE THREAD

**Issue by haaranenjarmo** [MicrosoftDocs/PowerShell-Docs#4614]
This example should clearly say that this only work in Windows Os, not in Linux or MacOs. Because this could lead an security breach. Everyone can import other users credentials in Linux and MacOs if they have access to the xml file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fd5191-d369-2d64-5766-d4910b752593
* Version Independent ID: cdbc31a6-1fee-22d3-3777-c47666a9aaa8
* Content: [Export-Clixml (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-clixml?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@SteveL-MSFT Does `Export-Clixml` still use DPAPI on Windows in v6+?

**Comment by joeyaiello** [comment]
Agreed with @SteveL-MSFT and @sdwheeler that the fix here is to add a note that these "encrypted" credentials will be exported in plaintext on macOS/Linux

**Comment by matt199x** [comment]
I do not get plain text when using it in macOS. The password string is way shorter than the string I get in Windows, but still not plain text.

**Comment by sdwheeler** [comment]
@matt199x That sounds like a bug. 
Please file an issue at https://github.com/PowerShell/PowerShell/issues/choose

/cc: @SteveL-MSFT
