### ISSUE TITLE
Names from Get-LocalGroupMember are not compatible with Get-LocalUser -Name <string>

### ISSUE THREAD

**Issue by HenkPoley** [MicrosoftDocs/PowerShell-Docs#4622]
You would expect these two to "speak the same language".

Get-LocalGroupMember outputs 'COMPUTERNAME\username'
Get-LocalUser expects the format 'username', and doesn't understand the above.

It would be nice if this simple incompatibility was resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b2ee7c8-0c9e-7389-49d8-184380bc2d79
* Version Independent ID: 91e03223-25be-f177-b279-9199cc265137
* Content: [Get-LocalGroupMember (Microsoft.PowerShell.LocalAccounts)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/get-localgroupmember?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Please file a feature request at https://github.com/PowerShell/PowerShell/issues
