### ISSUE TITLE
Clarify `Using Module`

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/PowerShell-Docs#4630]
What is defined as a module as a parameter of the "using" keyword.  I'm assuming it's not a PowerShell module, since we're primarily talking about a keyword recycled from C#, but the documentation is a little light on what that is.  The note in the short description doesn't make it sound any different from a namespace, and the example `using module CardGames` would be a custom module, so it doesn't give me a reference point for how it's different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee0c5b0-8465-adcc-be1b-9e6aafa4199d
* Version Independent ID: bc27ba48-5641-d363-7fc4-06ea01efa9e2
* Content: [about_Using](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/About_Using.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/About_Using.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The docs already state:

> The using statement, for modules, is intended to surface the classes in the module. If the module isn't loaded, the using fails.

I am not sure what else there is to say about the module case. The difference is the source of the namespace. In the example, the classes `[Deck]` and `[Card]` are implemented in a PowerShell module, not a .NET assembly. The name `CardGames` is referencing a PowerShell module.

Is there some other point of confusion?

**Comment by aydeisen** [comment]
I must be missing something, because I can't envision any scenario where a PowerShell module (the type that would be loaded with Import-Module) would contain callable classes instead or, or even in addition to, functions and cmdlets, that wouldn't otherwise be tied to a .NET Namespace.  What's special about `CardGames` that it's a module, and not the name of a .NET Namespace?  I don't see what differentiates the two.

**Comment by sdwheeler** [comment]
Classes written in PowerShell in a module do not get imported by `Import-Module`. You must use the `using` statement.

**Comment by aydeisen** [comment]
I apologize, I'm getting the impression that there's some prerequisite knowledge I don't have that's preventing me from being able to clarify or even explain how much I'm not understanding why or when I would use using module, even after reading the about_using document.  I assume it's primarily because, while I have a decent working knowledge of PowerShell, I can't say the same for C#.

I've used PowerShell classes before, but they've always been defined in the script I'm using it in.  I've never had to use a `using` statement to separately call the class in the script.

I guess I should also point out that there's no mention of `using module` in the [about_Classes](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-6#syntax) document under the heading that says `Classes are instantiated using either of the following syntaxes`.  Is that just an error that's missing from the document?

**Comment by sdwheeler** [comment]
I am in the process of adding this information to the docs. You can always use the classes within the script or module in which they are defined. You only need to use the `using` statement when importing classes from a module for use in a script outside of the module.

**Comment by aydeisen** [comment]
> You only need to use the using statement when importing classes from a module for use in a script outside of the module.

Can I take this to mean that there's a way to create a PowerShell file with PowerShell classes similar to a class library, and that using module would be used to call the classes in the library?  I wasn't aware that was a possibility.

**Comment by sdwheeler** [comment]
Yes, you can define classes in a module and use them outside of the module. You can have a module that only contains classes, if you want.
