### ISSUE TITLE
Copy-Item when destination folder doesn't exist

### ISSUE THREAD

**Issue by darwinguz** [MicrosoftDocs/PowerShell-Docs#4631]
Issue Details
-----------------
**I have these folders:**
C:\Test
│   test.txt
│
└───SubTest
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;subtest.txt

**and:**
C:\TestCopy
No subfolders exist

**When I run this command with "NewFolder" that doesn't exist:**
`Copy-Item -Path 'C:\Test\*' -Destination 'C:\TestCopy\NewFolder' -Recurse`

**The result is:**
C:\TestCopy
└───NewFolder
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        subtest.txt
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        test.txt

**The expected result is:**
C:\TestCopy
└───NewFolder
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│   test.txt
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└───SubTest
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;subtest.txt

Off course, when "NewFolder" exists it'll work well but if not, it should be throw an exception.

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
Please file an issue in the source repo at https://github.com/PowerShell/PowerShell/issues.
