### ISSUE TITLE
Error importing the module after manual upload with Azure REST API

### ISSUE THREAD

**Issue by krysickij1** [MicrosoftDocs/PowerShell-Docs#4640]
Issue Details
-----------------
After uploading a module downloaded from [Powershell Gallery](https://powershellgallery.com) to automation account I'm receiving this error:
**Error importing the module AzureRM.DataFactoryV2. Import failed with the following error: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.**

Steps to reproduce
------------------------------
1. Download package from [Powershell Gallery](https://powershellgallery.com)
2. Change file extension to .zip and change the file name to be the same as in the gallery i.e. AzureRM.DataFactoryV2.zip
3. Remove nuget files
4. Upload .zip file to blob to get proper content link
4. Make a REST Request with a content link as described in [Azure REST API Documentation](https://docs.microsoft.com/en-us/rest/api/automation/module/createorupdate)

The response code from REST API Request is 200 and I can see the package uploaded to automation account but during the importing this error appears.

**Comment by sdwheeler** [comment]
Please file an issue at https://github.com/azure/azure-powershell/issues.
