### ISSUE TITLE
Add documentation for the ternary operator

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#4648]
Issue Details
-----------------

I'm adding the ternary operator to the PowerShell language. Documentation needs to be updated or added to cover the ternary operator. This is related to https://github.com/PowerShell/PowerShell/pull/10367

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
## Syntax

```none
<condition> ? <if-true> : <if-false>
```

Two basic design points:

- Ternary operator produces an expression, just like the binary and unary operators
- Ternary operator has lower precedence order than the binary operator

The ternary operator behaves like the simplified if-else statement.
The `condition-expression` will always be evaluated,
and its result will be converted to boolean to determine which branch will be evaluated next:

- `if-true-expression` will execute if the condition's result is evaluated as `true`
- `if-false-expression` will execute if the condition's result is evaluated as `false`
