### ISSUE TITLE
Enter-PSSession : A parameter cannot be found that matches parameter name 'HostName'.

### ISSUE THREAD

**Issue by fredx30** [MicrosoftDocs/PowerShell-Docs#4651]
The examples on this page are just wrong.
This is returned by get-help Enter-pssession

NAME
    Enter-PSSession
    
SYNTAX
    Enter-PSSession [-ComputerName] &lt;string&gt; [-EnableNetworkAccess] [-Credential &lt;pscredential&gt;] [-ConfigurationName &lt;string&gt;] [-Port &lt;int&gt;] [-UseSSL] [-ApplicationName 
    &lt;string&gt;] [-SessionOption &lt;PSSessionOption&gt;] [-Authentication {Default | Basic | Negotiate | NegotiateWithImplicitCredential | Credssp | Digest | Kerberos}] 
    [-CertificateThumbprint &lt;string&gt;]  [&lt;CommonParameters&gt;]
    
    Enter-PSSession [[-Session] &lt;PSSession&gt;]  [&lt;CommonParameters&gt;]
    
    Enter-PSSession [[-ConnectionUri] &lt;uri&gt;] [-EnableNetworkAccess] [-Credential &lt;pscredential&gt;] [-ConfigurationName &lt;string&gt;] [-AllowRedirection] [-SessionOption 
    &lt;PSSessionOption&gt;] [-Authentication {Default | Basic | Negotiate | NegotiateWithImplicitCredential | Credssp | Digest | Kerberos}] [-CertificateThumbprint &lt;string&gt;] 
     [&lt;CommonParameters&gt;]
    
    Enter-PSSession [-InstanceId &lt;guid&gt;]  [&lt;CommonParameters&gt;]
    
    Enter-PSSession [[-Id] &lt;int&gt;]  [&lt;CommonParameters&gt;]
    
    Enter-PSSession [-Name &lt;string&gt;]  [&lt;CommonParameters&gt;]
    
    Enter-PSSession [-VMId] &lt;guid&gt; [-Credential] &lt;pscredential&gt; [-ConfigurationName &lt;string&gt;]  [&lt;CommonParameters&gt;]
    
    Enter-PSSession [-VMName] &lt;string&gt; [-Credential] &lt;pscredential&gt; [-ConfigurationName &lt;string&gt;]  [&lt;CommonParameters&gt;]
    
    Enter-PSSession [-ContainerId] &lt;string&gt; [-ConfigurationName &lt;string&gt;] [-RunAsAdministrator]  [&lt;CommonParameters&gt;]
    

ALIASES
    etsn
    

REMARKS
    Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help.
        -- To download and install Help files for the module that includes this cmdlet, use Update-Help.
        -- To view the Help topic for this cmdlet online, type: "Get-Help Enter-PSSession -Online" or 
           go to https://go.microsoft.com/fwlink/?LinkID=135210.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6bec4d3-9abe-d74d-cb6b-085d3cba7030
* Version Independent ID: 5bc062a1-9f01-41f6-189e-691e655f962c
* Content: [Enter-PSSession (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enter-pssession?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by SteveL-MSFT** [comment]
Need more details here.  `-HostName` was added for PSCore6 which is this doc.  The content in the body of the comment above doesn't show `-HostName` parameter set which implies they ran it on 5.1 which doesn't support this.
