### ISSUE TITLE
Example 4: Run a script as a background job (with parameter)

### ISSUE THREAD

**Issue by ericmoses** [MicrosoftDocs/PowerShell-Docs#4652]
Can the script to be executed in the background take a parameter? If yes, what is the syntax?

#This works as advertised
Start-Job -FilePath "c:\scripts\sample.ps1"

#I can't get this to work
Start-Job -FilePath "c:\scripts\sample.ps1 -param myparam"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21072008-b858-e850-c930-535d56dbece7
* Version Independent ID: 4cd839bc-6755-c611-5961-3d971255f931
* Content: [Start-Job (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/start-job?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/Start-Job.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/Start-Job.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Yes, as stated in the documentation:

> -ArgumentList
> Specifies an array of arguments, or parameter values, for the script that is specified by the FilePath parameter.
>
>Because all of the values that follow the ArgumentList parameter name are interpreted as being values of ArgumentList, specify this parameter as the last parameter in the command.
