### ISSUE TITLE
Correct or remove information about REPORTERRORSHOW* variables from about_Automatic_Variables

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#4654]
about_Automatic_Variables describes `REPORTERRORSHOW*` variables as being obsolete, but also states:

> `Get-Variable` gets them, but they do not contain valid data.

However, as of at least PowerShell Core 7.0.0-preview.2, these variables are _not_ predefined. (`Get-Variable REPORTERRORSHOW*` returns nothing.)

Not sure in what version they were removed, however.

There are two options:

(a)  Simply remove the entire "REPORTERRORSHOW VARIABLES" chapter for all versions where these variables are no longer predefined.

(b) Correct the claim that these variables are predefined.

Given that these variables have been obsolete since at least v3 and aren't widely known, (a) may be the better choice.

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by sdwheeler** [comment]
@SteveL-MSFT Do you know when these variables were removed?

**Comment by SteveL-MSFT** [comment]
I don't know when they were removed.  They are clearly not in 5.1+.  I don't have older versions handy.  I would suggest we remove this section from 5.1+ versions of the doc.  If someone verifies the variables don't exist in v3 and v4, we can remove from those docs as well.

**Comment by mklement0** [comment]
@SteveL-MSFT: I can confirm that the variables neither exist in v3 nor in v4.
