### ISSUE TITLE
Example NOT correct.

### ISSUE THREAD

**Issue by wenmin92** [MicrosoftDocs/PowerShell-Docs#4658]
Example 12: Use the Count parameter.
```
Get-Random -Maximum 10 -Count 3
```
Both in PowerShell 5.0 and 6.0, output error:
```
Get-Random : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided. 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e654863e-148f-52a6-507b-3cd642d89c4e
* Version Independent ID: a3fd43f5-d4b9-d282-93bb-b0dce28b2fb0
* Content: [Get-Random (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-random?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Get-Random.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Get-Random.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by tonesandtones** [comment]
As an alternative, I've used `1..3 | foreach { Get-Random -Maximum 10 }`
