### ISSUE TITLE
Rename "Comment" field in verb tables

### ISSUE THREAD

**Issue by alexbuzzbee** [MicrosoftDocs/PowerShell-Docs#4664]
The "Comment" field in the verb tables is almost exclusively used for "For this action, do not use (verbs|a verb) such as..." As such, it could be relabeled with "Verbs not to use" or "Deprecated synonyms" or a similar name that would be 1) more accurate and 2) more succinct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a81c73-9edf-2815-268d-a7b294fe6bd3
* Version Independent ID: eb63eebc-a28c-be84-fd47-e7573f09e0b0
* Content: [Approved Verbs for PowerShell Commands](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands)
* Content Source: [developer/cmdlet/approved-verbs-for-windows-powershell-commands.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md)
* Product: **powershell**
* Technology: **powershell-developer**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The comment column is more than just "actions". Eventually this article will be updated and moved into the main docset. Won't fix the existing article until then.
