### ISSUE TITLE
Powershell Core pay support

### ISSUE THREAD

**Issue by akshaybabloo** [MicrosoftDocs/PowerShell-Docs#4668]
When you say `You can also pay for assisted support for PowerShell Core by filing a support request for your problem.`, what option do I have to select from assisted support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1739eb2-b949-32b5-0089-4606f18d1ee0
* Version Independent ID: 79858126-7fca-e46e-40b9-5051d215fc1e
* Content: [PowerShell Core Support Lifecycle](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-6)
* Content Source: [reference/docs-conceptual/PowerShell-Support-Lifecycle.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
You can engage any of the paid support plans that Microsoft offers. See https://support.microsoft.com/en-us/hub/4343728/support-for-business.

**Comment by akshaybabloo** [comment]
Which one do I choose for powershell from the drop down list? I am not able to find it.

**Comment by sdwheeler** [comment]
It would be covered under Windows Support.
