### ISSUE TITLE
Parameters not actually available

### ISSUE THREAD

**Issue by jnhaffey** [MicrosoftDocs/PowerShell-Docs#4669]
The documentation says that the Get-Culture cmdlet has several parameters yet in the latest version of the cmdlet these parameters are not available.  In fact, the only parameters available are the common ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eda36ff-c87b-db19-405e-fa1eeadd1835
* Version Independent ID: 14c36087-d407-88e6-510e-91931c9ff342
* Content: [Get-Culture (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-culture?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Get-Culture.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Get-Culture.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
You are viewing the help for PowerShell v6. In PowerShell v5.1 (and older) `Get-Culture` has no parameters. You will see that if you switch to the proper version of the documentation at the top of the page.
![image](https://user-images.githubusercontent.com/19415881/63451423-059da000-c3f9-11e9-9d20-9b95312a451f.png)
