### ISSUE TITLE
'Credential' parameter should be 'PsDscRunAsCredential'?

### ISSUE THREAD

**Issue by kjhosein** [MicrosoftDocs/PowerShell-Docs#4671]
Although code written with the Credential param name does not throw any syntax errors, it did not work and I received invalid credentials error messages. Switching to PsDscRunAsCredential worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef898c5d-f53d-e730-7797-edbb6ebff8d5
* Version Independent ID: a426929a-2af8-1861-f1c0-3bea1399e2d5
* Content: [DSC Script Resource](https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/windows/scriptresource#feedback)
* Content Source: [dsc/reference/resources/windows/scriptResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/reference/resources/windows/scriptResource.md)
* Product: **powershell**
* Technology: **powershell-dsc**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by sdwheeler** [comment]
@mgreenegit Can you comment on this?
