### ISSUE TITLE
Example 1 URL

### ISSUE THREAD

**Issue by hngr18** [MicrosoftDocs/PowerShell-Docs#4674]
Needs to be updated to 
https://www.bing.com/search?q=how+many+feet+in+a+mile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1103bfa9-3680-14bb-2992-b992ff3c2297
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@hngr18 It works either way.

**Comment by hngr18** [comment]
Redirects, which doesn't work on system with following $psversiontable

Appreciate that this could be the wrong repository for an issue like this

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
