### ISSUE TITLE
Hash table keyname ' * ' and finding specific text 

### ISSUE THREAD

**Issue by didwi** [MicrosoftDocs/PowerShell-Docs#4689]
Hi,
Thank you for the nice samples. It would be nice to have a sample on how to use the ' * ' keyname of the hash table. I couldn't find any related information here or on the Internet.
Lastly, another nice sample would be on how to find/search for specific keyword in the &lt;eventdata&gt; field.
Regards,
Didier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fd0ecd-dfc1-04d9-a88d-d2e1958e92cd
* Version Independent ID: 18091f4a-cb9f-a792-c659-fffeb5606d99
* Content: [Creating Get-WinEvent queries with FilterHashtable](https://docs.microsoft.com/en-us/powershell/scripting/samples/creating-get-winevent-queries-with-filterhashtable?view=powershell-5.1#feedback)
* Content Source: [reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by didwi** [comment]
Hi,
I'm trying this out ... but it fails and I don't why?
Is it limited to powershell core 6 ?
Get-WinEvent -FilterHashtable @{LogName='Security'; 'TargetUserName'='ABC123'}
Get-WinEvent : No events were found that match the specified selection criteria.
At line:1 char:1
+ Get-WinEvent -FilterHashtable @{LogName='Security'; 'TargetUserName'= ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingEventsFound,Microsoft.PowerShell.Commands.GetWinEventCommand

Here is a sample of the xml data:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
  <EventID>4740</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>13824</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8020000000000000</Keywords> 
  <TimeCreated SystemTime="2019-10-25T10:52:23.175168500Z" /> 
  <EventRecordID>21267584</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="696" ThreadID="11016" /> 
  <Channel>Security</Channel> 
  <Computer>dc-3.gouv.etat.lu</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="TargetUserName">ABC123</Data> 
  <Data Name="TargetDomainName">TEST</Data> 
  <Data Name="TargetSid">S-1-5-21-1234567-2345454-2432424-37776</Data> 
  <Data Name="SubjectUserSid">S-1-5-18</Data> 
  <Data Name="SubjectUserName">DC-3$</Data> 
  <Data Name="SubjectDomainName">TEST</Data> 
  <Data Name="SubjectLogonId">0x3e7</Data> 
  </EventData>
  </Event>

**Comment by didwi** [comment]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
  <EventID>4740</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>13824</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8020000000000000</Keywords> 
  <TimeCreated SystemTime="2019-10-25T10:52:23.175168500Z" /> 
  <EventRecordID>21267584</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="696" ThreadID="11016" /> 
  <Channel>Security</Channel> 
  <Computer>dc-3.gouv.etat.lu</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="TargetUserName">ABC123</Data> 
  <Data Name="TargetDomainName">TEST</Data> 
  <Data Name="TargetSid">S-1-5-21-1234567-2345454-2432424-37776</Data> 
  <Data Name="SubjectUserSid">S-1-5-18</Data> 
  <Data Name="SubjectUserName">DC-3$</Data> 
  <Data Name="SubjectDomainName">TEST</Data> 
  <Data Name="SubjectLogonId">0x3e7</Data> 
  </EventData>
  </Event>

**Comment by sdwheeler** [comment]
@didwi You don't have to put TargetUserName in quotes but it works either way. 

Accessing the Security event log requires Admin privilege. You must run this from an elevated session. It works for me when I do this.

**Comment by didwi** [comment]
I think I found my problem .... I didn't notice earlier, it is a new feature on powershell 6?! ... indeed, it works on powershell 6, I was using it on windows 2016 server with powershell 5.1.
I guess that does resolve my problem/question.
