### ISSUE TITLE
Adding persistent value writes expanded values back to registry

### ISSUE THREAD

**Issue by cmconti** [MicrosoftDocs/PowerShell-Docs#4691]
The default value of PSModulePath ( at least on Windows 10 1903) is actually: %ProgramFiles%\WindowsPowerShell\Modules;%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules

The instructions about using GetEnvironmentVariable/SetEnvironmentVariable will overwrite the values with already-expanded values.

I don't know if there is a better powershell way of dealing with REG_EXPAND_SZ, but this would probably resolve the issue:

$key = get-item 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
$path = $key.GetValue('PSModulePath','','DoNotExpandEnvironmentNames')
$path += ';C:\Program Files\Fabrikam\Modules' # or '%ProgramFiles%\Fabrikam\Modules'
$key.SetValue('PSModulePath',$path,[Microsoft.Win32.RegistryValueKind]::ExpandString)

The note would also need to be updated with text similar to:
To add the path to the user PSModulePath environment variable, use the key 'HKCU:\Environment' and do not prepend ';' to your path if the existing path is empty.

---
#### Document Details

ΓÜá *Do not edit this section. It is required for docs.microsoft.com Γ₧ƒ GitHub issue linking.*

* ID: dfd2e74d-932f-8e43-dab5-82796a54077e
* Version Independent ID: 8a54a46b-715d-ab7d-f500-7dd41c29634c
* Content: [Modifying the PSModulePath Installation Path - PowerShell](https://docs.microsoft.com/powershell/scripting//developer/module/modifying-the-psmodulepath-installation-path)
* Content Source: [reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by cmconti** [comment]
sorry- copy paste error.
the first line should open a writable key:
$key = (get-item 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\').OpenSubKey('Environment', $true)

and for the User it would be:
$key = (get-item 'HKCU:\').OpenSubKey('Environment', $true)

**Comment by JamesWTruher** [comment]
I'm trying to understand the concrete problem here. The behavior seems consistent between powershell and cmd where the variables are expanded. Is it that there isn't a way to retrieve the unexpanded? This also seems to be the way that the .NET `Environment` object works (automatically expand variables).

I think the low friction way to get the unexpanded value is:
```powershell
PS# $envPath = 'hklm:/system/currentcontrolset/control/session manager/environment'
PS# (get-item $envPath).GetValue("TEMP","","DoNotExpandEnvironmentNames")
%SystemRoot%\TEMP
```

**Comment by sdwheeler** [comment]
@JamesWTruher 
The problem is that the way the example is written in the article changes the values stored in `$env:PATH` to the expanded values. But we really want to store the unexpanded values. I will update the example using the workaround to fix this.

Using your EnvironmentVariableCmdlets module should also avoid expansion, correct?

**Comment by cmconti** [comment]
On a clean 1903 system:
```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
PSModulePath (REG_EXPAND_SZ) = %ProgramFiles%\WindowsPowerShell\Modules;%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules
```
Following the instructions from https://docs.microsoft.com/en-us/powershell/developer/module/modifying-the-psmodulepath-installation-path :
```
$CurrentValue = [Environment]::GetEnvironmentVariable("PSModulePath", "Machine")
[Environment]::SetEnvironmentVariable("PSModulePath", $CurrentValue + ";C:\Program Files\Fabrikam\Modules", "Machine")
```

Now:
```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
PSModulePath (REG_EXPAND_SZ) = C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Fabrikam\Modules
```

See how the preexisting unexpanded path values have been replaced with expanded values in addition to adding the ';C:\Program Files\Fabrikam\Modules'
