### ISSUE TITLE
More precision on $ErrorActionPreference variable scope

### ISSUE THREAD

**Issue by EmilianoElMariachi** [MicrosoftDocs/PowerShell-Docs#4698]
It might interesting to specify that PowerShell modules have their own scope/variable for at least $ErrorActionPreference variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccfd7b1-efb2-d49b-f3e1-cc7c7b36530a
* Version Independent ID: 02b20737-f11c-b6ce-5e32-9bf8781c01f6
* Content: [about_Preference_Variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Can you give me a scenario that you have in mind for this? I don't understand what your question is.

**Comment by sdwheeler** [comment]
Module scope is covered in the about_Modules article.
