### ISSUE TITLE
Please add the timezones you can use or say how you display them

### ISSUE THREAD

**Issue by whyiseverythingmadesocomplicated** [MicrosoftDocs/PowerShell-Docs#4712]
[System.TimeZoneInfo]::GetSystemTimeZones()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53253c10-eda9-7d12-456c-764fda300a53
* Version Independent ID: 1ec0a357-b6e9-335f-df55-ec2bc6332d25
* Content: [Set-TimeZone (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-timezone?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Set-TimeZone.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Set-TimeZone.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by DCtheGeek** [comment]
The information about getting timezones is in the related cmdlet (linked from the Set-TimeZone article), `Get-TimeZone`: https://docs.microsoft.com/powershell/module/microsoft.powershell.management/get-timezone
