### ISSUE TITLE
os-arch?? where are the valid values

### ISSUE THREAD

**Issue by largeDachshund** [MicrosoftDocs/PowerShell-Docs#4715]
Come on.  Skip this page, if you're going to neglect defining parameters for the installation.  I'd expect this from an open source library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfa3f4fc-5411-0135-c8c2-6615bb5584a1
* Version Independent ID: 0628c7a6-59c3-55cf-f1d3-7e348550281f
* Content: [Installing PowerShell Core on Windows](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#installing-the-msi-package)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by NReilingh** [comment]
I don't think that's meant to be a "parameter" — it looks like it's just a placeholder for whatever file you end up downloading from the [releases](https://github.com/PowerShell/PowerShell/releases) page (scroll down to the end of the release notes to expand the "Assets" list, and you'll see all available architectures).

**Comment by sdwheeler** [comment]
@NReilingh is correct. That is a placeholder for the versions available on the releases page.
