### ISSUE TITLE
@using:VariableName doesn't work in DSC

### ISSUE THREAD

**Issue by NReilingh** [MicrosoftDocs/PowerShell-Docs#4718]
I was trying to define a parameter hashtable outside of the script block and then splat those parameters to a cmdlet inside the script block with `@using:HashtableVar`, but this didn't appear to work. When I copied the hashtable var to a local variable inside the scriptblock first, and splatted that, it worked fine. I know there are other limitations to $using, like being unable to access array indices a la `$using:array[1]` — should these be documented better here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef898c5d-f53d-e730-7797-edbb6ebff8d5
* Version Independent ID: a426929a-2af8-1861-f1c0-3bea1399e2d5
* Content: [DSC Script Resource](https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/windows/scriptresource#feedback)
* Content Source: [dsc/reference/resources/windows/scriptResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/reference/resources/windows/scriptResource.md)
* Product: **powershell**
* Technology: **powershell-dsc**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by sdwheeler** [comment]
@NReilingh This should work. At least it does work with `Invoke-Command` to pass a local variable to a remote session using splatting.

Can you provide examples of what didn't work? This may need to be a bug filed in the PowerShell/PowerShell repo.

**Comment by NReilingh** [comment]
Hey @sdwheeler — I think you may have overlooked that I submitted this issue in reference to the [DSC Script Resource](https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/windows/scriptresource#feedback) page. Here's an example of a configuration that exhibits the issue:

```powershell
Configuration DSCTesting
{
    Node localhost
    {
        $Params = @{
            Path = "C:\Something"
            PathType = 'Container'
        }
        Script TestUsingSplat
        {
            GetScript = {
                return @{
                    Result = "Hey, I'm a value."
                }
            }
            TestScript = {
                Test-Path @using:Params
            }
            SetScript = {
                # No-op
            }
        }
    }
}
```

After compiling the configuration and inspecting the localhost.mof file, you can see that it has no reference to the two argument values in the `$Params` variable. If you rewrite TestScript to be something like `$Params = $using:Params; Test-Path @Params` and then recompile the MOF, you can see that it is properly including the $Params hashtable as serialized XML in the MOF file.

**Comment by sdwheeler** [comment]
@NReilingh Thanks for the example. I saw that your issue was with the DSC docs. That is why I wanted an example. I have a colleague researching this now.

**Comment by sdwheeler** [comment]
I don't have an easy way to test this right now. Can you try using brace notation: `Test-Path @{using:Params}`?

**Comment by sdwheeler** [comment]
@mgreenegit / @bobbytreed Can either of you comment on this? Is this a bug that needs to be filed?

**Comment by sdwheeler** [comment]
@NReilingh After further consultation with the product team - DSC was not really designed to use splatting. 

To better explain what is happening:

The problem you are seeing in your example is that `$Params` is not defined within the resource. The variable must be defined within the resource or pulled in with `$using:` so that it gets serialized into the MOF file. Your workaround pulls the variable into the resource so that it gets compiled into the MOF. That is expected behavior.

I am working on several updates to the docs on variables and scopes. I will include some information about splatting in DSC.

**Comment by NReilingh** [comment]
@sdwheeler Sounds great, thanks for the clarification! I'll assume you'll close this issue when your updates go up.

**Comment by sdwheeler** [comment]
Yes. Working on those updates now.
