### ISSUE TITLE
Nested configurations don't appear to work within composite resources

### ISSUE THREAD

**Issue by NReilingh** [MicrosoftDocs/PowerShell-Docs#4719]
I was trying to use nested configurations as described in this document to cut down on duplicated code within a configuration that I was going to export as a composite resource. This didn't appear to be possible, and I ended up refactoring the nested child configuration as a separate resource within my composite resource module (this worked, strangely). But, I was also mostly using [ConvertTo-CompositeResource](https://github.com/microsoft/CompositeResource) to generate the composite resource module, so this could potentially be a bug with that tool.

Is it expected that nested configurations should be supported within composite resources? The main issue appeared to be that nested configurations require that both the parent and child are defined in the same file, whereas composite resources appear to assume that a `.schema.psm1` file will contain just a single resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf97f7e-41dc-fe9b-8124-17cb20e2d71a
* Version Independent ID: 24b2e99d-0122-e329-2d63-fc904c11a117
* Content: [Nesting configurations](https://docs.microsoft.com/en-us/powershell/dsc/configurations/compositeconfigs)
* Content Source: [dsc/configurations/compositeConfigs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/dsc/configurations/compositeConfigs.md)
* Product: **powershell**
* Technology: **powershell-dsc**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by sdwheeler** [comment]
@bobbytreed @mgreenegit Can either of you comment on this?

**Comment by mgreenegit** [comment]
We don't currently support nesting composite resources within composite resources, or composite configurations within composite resources.

**Comment by NReilingh** [comment]
I'll submit a PR to the docs to this effect unless someone tells me otherwise.

**Comment by sdwheeler** [comment]
@bobbytreed Per our discussion, please clarify the what we support with composite configs.
