### ISSUE TITLE
Example using begin/process/end

### ISSUE THREAD

**Issue by chriskuech** [MicrosoftDocs/PowerShell-Docs#4725]
It is unclear how to combine advanced parameters and advanced methods to properly use begin/process/end.  Specifically, it is unclear how to reference only the current pipeline element inside the process block.  Please add an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c421d42f-513f-dad9-6511-34536ebb5421
* Version Independent ID: 7669fc70-4179-f569-574b-862a2529741a
* Content: [about_Functions_Advanced_Methods](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_methods?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The automatic variable `$_` or `$PSItem` contains the current object in the pipeline for use in the Process block.
