### ISSUE TITLE
BUG: WMF 5.1 breaks SFC on Windows 8.1 and Server 2012 R2 in non-English systems

### ISSUE THREAD

**Issue by jdev15** [MicrosoftDocs/PowerShell-Docs#4733]
There is no acknowledgement of this bug by Microsoft anywhere, and it affects the ability to effectively diagnose the Component Store of either Windows 8.1 or Server 2012 R2.
After installing WMF 5.1 in Windows 8.1/Server 2012 R2, running SFC integrity scan reports and "repairs" a couple of localized DSCResources files, but it actually replaces new WMF 5.1 files with inbox DSCResources files, which might breaks DSC on non-english systems.
This happens because the files are referenced (shared) in two different WinSxS components in inbox Windows 8.1/2012 R2. The files are contained in "Microsoft.PowerShell.DSC.Resources" but in WMF 5.1 they are now contained in "Microsoft.PowerShell.DSCResources.Resources", hence the inbox files are not considered superseded, and SFC tries to restore them.
This has already been reported here, but no feedback was given: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/32515291-bug-wmf-5-1-breaks-sfc-on-windows-8-1-and-sfc-mi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fbe38-df3a-bf49-8409-6f27280912f2
* Version Independent ID: 0af33ae1-cbe3-968a-b3f0-3f88158578a9
* Content: [Known Issues in WMF 5.1](https://docs.microsoft.com/en-us/powershell/wmf/known-issues/known-issues-51#feedback)
* Content Source: [wmf/known-issues/known-issues-51.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/wmf/known-issues/known-issues-51.md)
* Product: **powershell**
* Technology: **powershell-wmf**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by joeyaiello** [comment]
I'll follow up on the product side, but given the age and severity of this bug, it's unlikely we're going to service it. That being said, this repo is for doc bugs, so I'm closing this one out.
