### ISSUE TITLE
sudo apt-get install requires confirmation, making copy paste a bit problematic

### ISSUE THREAD

**Issue by Zerowalker** [MicrosoftDocs/PowerShell-Docs#4748]
I noticed that on Debian 9 for example, the commands to install says:

sudo apt-get install curl gnupg apt-transport-https
but it later says
sudo apt-get install -y powershell

My point being the "-y", i believe it's a miss as both should have that to allow a simple copy paste of the entire code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49e6e46-1221-3123-d750-0803e2f08195
* Version Independent ID: 94bd5a5b-a984-7edf-50bd-9f4dc1a020ef
* Content: [Installing PowerShell Core on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by TravisEz13** [comment]
-y should make copy and paste easier.
