### ISSUE TITLE
VisibleExternalCommands Wildcard Option

### ISSUE THREAD

**Issue by shields478** [MicrosoftDocs/PowerShell-Docs#4756]
The VisibleExternalCommands "Accept wildcard characters:" show True on this page, however the shell help show it being false. Also, testing seems to indicate that it does not accept wildcards either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc76b8b-13e9-a75c-ee3a-fb5ddfb1595a
* Version Independent ID: 341dcd3d-b8e7-414f-55fb-649dd50b77a2
* Content: [New-PSRoleCapabilityFile (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-psrolecapabilityfile?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@SteveL-MSFT Can someone confirm the correct behavior here?
