### ISSUE TITLE
Parameter -Title deprecated?

### ISSUE THREAD

**Issue by Backspaze** [MicrosoftDocs/PowerShell-Docs#4757]
The parameter -Title seems to have been deprecated.

"Get-Credential : A parameter cannot be found that matches parameter name 'Title'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4beb23ca-5a88-8cc3-4121-d062b49f74f3
* Version Independent ID: c98699f2-814c-63b8-edf5-3293ea1aa99f
* Content: [Get-Credential (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-credential?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Security/Get-Credential.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/Get-Credential.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by DCtheGeek** [comment]
@Backspaze It's not deprecated and is still in 6.2.2 and 7.0.0-preview.3:

```output
C:\Temp> Get-Command -Name Get-Credential -Syntax

Get-Credential [[-Credential] <pscredential>] [<CommonParameters>]

Get-Credential [[-UserName] <string>] [-Message <string>] [-Title <string>] [<CommonParameters>] 
```

What OS and version of PowerShell are you using?

**Comment by Backspaze** [comment]
Windows 10 Pro
Version: 1803
OS-version: 17134.950

PowerShell
PSVersion                                     5.1.17134.858
PSEdition                                      Desktop
PSCompatibleVersions                 {1.0, 2.0, 3.0, 4.0...}
BuildVersion                                 10.0.17134.858
CLRVersion                                   4.0.30319.42000
WSManStackVersion                    3.0
PSRemotingProtocolVersion        2.3
SerializationVersion                     1.1.0.1

**Comment by DCtheGeek** [comment]
@Backspaze Ahhh, that's the reason.  The parameter didn't exist in 5.1. You can see from the 5.1 version of that page (https://docs.microsoft.com/powershell/module/microsoft.powershell.security/get-credential?view=powershell-5.1) there is no **Title** parameter. You were viewing the 6 version of that page, which does have the parameter. Thanks!
