### ISSUE TITLE
MaximumSize requirement not clear - KB vs KiB

### ISSUE THREAD

**Issue by stuboydl** [MicrosoftDocs/PowerShell-Docs#4762]
Can you either make the "MaximumSize" calculation documentation more explicit or allow entry of KB for log size.
eg It says the value must be divisible by 64 KB (Kilobyte). However, the Windows10 (data) calculator defines 65536 bytes as a KiB (Kibibyte)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 189a746f-35af-0892-b32b-a0259786c44d
* Version Independent ID: fb725405-5635-a8d7-c937-54a1a8172064
* Content: [Limit-EventLog (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-au/powershell/module/microsoft.powershell.management/limit-eventlog?view=powershell-3.0)
* Content Source: [reference/3.0/Microsoft.PowerShell.Management/Limit-EventLog.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Limit-EventLog.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
In PowerShell, KB is always 1024.

```powershell
PS> 1kb,64kb,1mb,1gb,1tb,1pb                                                     

1024
65536
1048576
1073741824
1099511627776
1125899906842624
```

**Comment by stuboydl** [comment]
Thanks - probably should have just asked for the argument to accept a human friendly suffix that could accept a multiple of 64 as in "-MaximumSize 768K", that would set the maximum size to 786432 bytes. The value entered would reflect the "Get-EventLog -List" Max(K) column values.

**Comment by sdwheeler** [comment]
The requirement to be a multiple of 64KB is a Windows requirement. The notation of using "KB" is specific to PowerShell. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_numeric_literals?#numeric-multipliers
