### ISSUE TITLE
Inputobject paramater

### ISSUE THREAD

**Issue by OrnluWolf** [MicrosoftDocs/PowerShell-Docs#4771]
Inputobject parameter should have an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b632a124-eb2e-96b5-81b8-0f7161ffe1fe
* Version Independent ID: 6f0d5c88-4d91-e080-5f21-c6876c6c2fc6
* Content: [Show-ControlPanelItem (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Show-ControlPanelItem?view=powershell-5.0)
* Content Source: [reference/5.0/Microsoft.PowerShell.Management/Show-ControlPanelItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Management/Show-ControlPanelItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by DCtheGeek** [comment]
@OrnluWolf Example #2 is for the `-InputObject` parameter since it accepts pipeline input.  A more verbose example which includes explicit use of `-InputObject` would be:

```powershell
$objCP = Get-ControlPanelItem -Name "*Firewall"
Show-ControlPanelItem -InputObject $objCP
```

Using the pipeline is more succinct and cleaner.  Hope that helps!  Thanks!
