### ISSUE TITLE
Class parameter

### ISSUE THREAD

**Issue by Xoph** [MicrosoftDocs/PowerShell-Docs#4793]
The documentation on the Class parameter is incorrect. It's actually the ClassName parameter, with an alias of Class, not the other way around. This confused me when trying to mock the command for Pester testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4916c4f-c22a-f26e-f5c8-4116a4cdd2ce
* Version Independent ID: 625696e5-1792-4c3b-6726-8c6927614fa1
* Content: [Get-WmiObject (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-wmiobject?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@Xoph What version of PowerShell are you using? Please provide the output of $PSVersionTable.

**Comment by sdwheeler** [comment]
The documentation for PowerShell v5.1 is correct.

```powershell
PS C:\Git> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145

PS C:\Git> (gcm Get-WmiObject | select -exp Parameters)['Class']

Name            : Class
ParameterType   : System.String
ParameterSets   : {[query, System.Management.Automation.ParameterSetMetadata], [list,
                  System.Management.Automation.ParameterSetMetadata]}
IsDynamic       : False
Aliases         : {ClassName}
Attributes      : {query, System.Management.Automation.AliasAttribute, list}
SwitchParameter : False
```

**Comment by sdwheeler** [comment]
I checked this on versions 3/4/5.0/5.1. The documentation is correct.
