### ISSUE TITLE
Document Proxy-usage

### ISSUE THREAD

**Issue by glatzert** [MicrosoftDocs/PowerShell-Docs#4798]
I think there should be a section about how Invoke-WebRequest automatically handles proxy-servers. E.g. WinINet vs. WinHTTP, Server Core vs. Server, HTTP_PROXY env-variables in unix, etc. pp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1103bfa9-3680-14bb-2992-b992ff3c2297
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@markekraus Do you have any notes on this?

**Comment by sdwheeler** [comment]
The web cmdlets rely on .NET proxy services. See https://docs.microsoft.com/en-us/dotnet/framework/network-programming/accessing-the-internet-through-a-proxy

**Comment by glatzert** [comment]
That's a good start for windows machines with a gui, but eg. Windows Server Core has no settings for WinINet-Proxies (at least not that I know of) and linux and macOS also won't be able to read their proxy settings from Internet-Explorer Settings.

**Comment by glatzert** [comment]
Any update on systems where WinINet is not available?

**Comment by sdwheeler** [comment]
@glatzert Bottom line is that PowerShell is only depending on the underlying services of .NET Core. So the scope of the support is based on what .NET Core provides. Here are some references:

Implement global proxy configuration for HttpClient · Issue #36553 · dotnet/corefx · GitHub
https://github.com/dotnet/corefx/issues/36553 

Allow uppercase HTTP_PROXY and NO_PROXY variables · Issue #37200 · dotnet/corefx · GitHub
https://github.com/dotnet/corefx/pull/37200 

 Fix issue with uppercase HTTP_PROXY and NO_PROXY · Issue #35887 · dotnet/corefx · GitHub
https://github.com/dotnet/corefx/pull/35887

**Comment by sdwheeler** [comment]
See related issue #5530
