### ISSUE TITLE
Link does not work PackageManagement MSI

### ISSUE THREAD

**Issue by FlorianGrimm** [MicrosoftDocs/PowerShell-Docs#4801]
all said

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bc5a9a-76fe-42f6-f11f-17e59af93f4f
* Version Independent ID: 8d0ef725-578d-bd63-8b4a-5a14a54f7dd4
* Content: [Installing PowerShellGet](https://docs.microsoft.com/en-us/powershell/gallery/installing-psget#feedback)
* Content Source: [gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-gallery**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by sdwheeler** [comment]
That old MSI package is unsupported and is no longer available for download. The instructions are valid for users that had installed that MSI. However, there is no need to reinstall that MSI package, so the link is not needed.

**Comment by Stick97** [comment]
So the only supported method of using PowerShellGet on older Windows versions is to use Windows Management Framework 5.0 or newer?

**Comment by sdwheeler** [comment]
@Stick97 No, not quite. You are encouraged to get upgraded to WMF 5.1 (5.0 is no longer supported). However, you can still run WMF 3.0 or WMF 4.0. See https://docs.microsoft.com/en-us/powershell/wmf/overview for a table of OS compatibility.

The article was linking to an old "Preview" version of the PackageManagement modules. The instructions were specifically for how to remove the preview version and install the current release.
