### ISSUE TITLE
Set-TimeZone: Specifying -Name versus -Id produces different results

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/PowerShell-Docs#4803]
Looks like that despite both `-Name` and `-Id` accepting a string of the name of the time zone, different behavior is exhibited depending on _what_ time zone you pass.

Example:
`Set-TimeZone -Name "Russian Standard Time"` 
❌ Fails with error _"The time zone name 'Russian Standard Time' was not found on the local computer"_
`Set-TimeZone -Id "Russian Standard Time"`
✔️Succeeds

`Set-TimeZone -Name "Eastern Standard Time"` 
✔️ Succeeds
`Set-TimeZone -Id "Eastern Standard Time"` 
✔️ Succeeds

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4419468-81ff-ca55-0bc5-d908cc30305c
* Version Independent ID: 1ec0a357-b6e9-335f-df55-ec2bc6332d25
* Content: [Set-TimeZone (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-timezone?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Set-TimeZone.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Set-TimeZone.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@eponerine This is a product issue. Please file an issue at https://github.com/PowerShell/PowerShell/issues.

**Comment by BronsonMagnan** [comment]
Name and ID are not the same thing, it is just a coincidence for some of the time zones, like EST. A list of Time zone IDs can be found on the system by running ```tzutil.exe /l``` changing to the provided time zone and running get-timezone will show 
```Id                         : Russian Standard Time
DisplayName                : (UTC+03:00) Moscow, St. Petersburg
StandardName               : Russia TZ 2 Standard Time
DaylightName               : Russia TZ 2 Daylight Time
BaseUtcOffset              : 03:00:00
SupportsDaylightSavingTime : True``` 
You can use ```Set-TimeZone -Name "Russia TZ 2 Standard Time"``` to set the time. Or use the -ID parameter with "Russian Standard Time"

**Comment by eponerine** [comment]
@BronsonMagnan - thanks for the input, and yes, you're absolutely correct. And this also seems to extend to `Name` being tied to `StandardName`

@sdwheeler - perhaps we can get some better clarification on the Docs other than "`-Id` is the ID!" and "`-Name` is the name!". Something a little more specific? Maybe also include a link to a list of supported time zones? 

FWIW - This seems to be a comprehensive list, but only for Id, not standardized names: https://support.microsoft.com/en-us/help/973627/microsoft-time-zone-index-values

**Comment by sdwheeler** [comment]
Agreed. I am working on an update to the article.
