### ISSUE TITLE
Unclear required syntax around background colors

### ISSUE THREAD

**Issue by JoshuaBaert** [MicrosoftDocs/PowerShell-Docs#4804]
I'm trying use the example in the -colors area to change the background color of my text. Example previously I would do a command like this `Set-PSReadlineOption -TokenKind Comment -BackgroundColor Gray` while the rest of my background colors are black. Any help on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 801e7046-e140-f89e-6f4e-700c9503107c
* Version Independent ID: 18945940-0df3-1027-612f-2adf6291d22d
* Content: [Set-PSReadLineOption (PSReadLine)](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-6#feedback)
* Content Source: [reference/6/PSReadLine/Set-PSReadlineOption.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PSReadLine/Set-PSReadlineOption.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
To set foreground and background colors you have to set the value using an ANSI escape sequence. So to set the color to black text on gray background:

```
Set-PSReadLineOption -Colors @{ "Comment"="`e[30;47m"}
```

**Comment by sdwheeler** [comment]
What version of PSReadline and PowerShell are you using? The syntax you show is not the current syntax for `Set-PSReadlineOption`.

PowerShell 5.1 shipped with PSReadline 1.2. PowerShell 6 shipped with PSReadline 2.0. The syntax changed between versions.

**Comment by JoshuaBaert** [comment]
I have Powershell version 5.1
