### ISSUE TITLE
Typo in Description - "Windows PowerShell 6.1"

### ISSUE THREAD

**Issue by ScottMetzel** [MicrosoftDocs/PowerShell-Docs#4809]
In the description of this cmdlet, "This cmdlet was introduced in Windows PowerShell 6.1" is mentioned; should this be "PowerShell 6.1" or "PowerShell Core 6.1"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd41662b-c800-4e77-fb70-407a19913130
* Version Independent ID: 3749eef8-2406-df1d-2f3b-3e4a91c97225
* Content: [Test-Json (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/test-json?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Test-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Test-Json.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
PowerShell 6.1 is PowerShell Core. Eventually we will be dropping "Core" from the name. However, "Windows PowerShell 6.1" is not a thing. I will fix that.

See https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/contributing/3-STYLE-GUIDE.md#product-terminology

**Comment by ScottMetzel** [comment]
Awesome, thank you sir. Yes, I'm aware of the planned name change to simply "PowerShell", but regardless, thank you!
