### ISSUE TITLE
Get-Service | Get-Member cmdlet returns error

### ISSUE THREAD

**Issue by bukandu1** [MicrosoftDocs/PowerShell-Docs#4830]
```
PS Azure:\> Get-Service | Get-Member
```

When the above item is copied into PowerShell, it returns the following message:

```
"Get-Service : The term 'Get-Service' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-Service | Get-Member
+ ~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-Service:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException"
```

Please either update the instructions or update the command itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f4c58ad-f9a8-451c-04c4-7e5071a2103a
* Version Independent ID: 7021eece-9563-59f7-b502-9409c87ed7c5
* Content: [PowerShell Scripting](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/overview.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Sound like you are running in Cloud Shell? Cloud Shell is running PowerShell in a Linux container. That cmdlet is not available on Linux. See https://docs.microsoft.com/en-us/powershell/scripting/whats-new/known-issues-ps6?view=powershell-6#command-availability
