### ISSUE TITLE
SideIndicator Omitted for Object-Compare -PassThru with Singular Result

### ISSUE THREAD

**Issue by Tyrolious** [MicrosoftDocs/PowerShell-Docs#4832]
I'm comparing 2 Get-ADGroupmember arrays:
$DiffMems = (Compare-Object $users1 $users2 -PassThru) 
If the results contain more than one user I get a SideIndicator of => or <=.
![image](https://user-images.githubusercontent.com/55765434/65547792-02ea0b00-decf-11e9-956a-f47ea09e18f8.png)
If the results contain only a single user I get no side indicator the field drops to the bottom of the list and I have a WriteErrorStream field with no value. 
![image](https://user-images.githubusercontent.com/55765434/65547814-0d0c0980-decf-11e9-9746-8271ae377ff2.png)
I unfortunately need to use the side indicator to tailor an email with the results of the group comparison. 

What am I missing?

Thanks,
Ty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7615306-98e3-0b79-ac87-58bb191b4349
* Version Independent ID: 85f1e969-8216-bed4-2204-409cbd9befd4
* Content: [Compare-Object (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/compare-object?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Compare-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Compare-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@JamesWTruher can you help explain?

**Comment by Tyrolious** [comment]
I'm thinking it has to do with something similar to the issue described here:
https://github.com/PowerShell/PowerShell/issues/6512
The issue only occurs when the Object-Compare has a single result, It plays differently with the wrapper. I could not reproduce the behavior with simple examples though
I rewrote the whole thing in c# because I couldn't find a solution.

**Comment by JamesWTruher** [comment]
I can't seem to replicate what you're seeing with regard to a single result vs multiple results, but when using the `-passthru` parameter it passes the _original_ objects which are different, rather than the object which contains the side indicator (which is what I believe you're looking for).

If you want the SideIndicator, don't use `-passthru`. You can still get to the original object in the output of `Compare-Object` with the `InputObject` member of the custom object which `Compare-Object` returns.
