### ISSUE TITLE
Paths to current user profiles are incorrect

### ISSUE THREAD

**Issue by lsmith130** [MicrosoftDocs/PowerShell-Docs#4837]
The document indicates the paths are `$Home\[My ]Documents\PowerShell\Profile.ps1` and `$Home\[My ]Documents\PowerShell\
Microsoft.PowerShell_profile.ps1` for the`Current User, All Hosts` and `Current User, Current Host` respectively, but this was not working for me. I checked my `$PROFILE.CurrentUserAllHosts` and `$PROFILE.CurrentUserCurrentHost` variables, and they point to `$Home\Documents\WindowsPowerShell\Profile.ps1` and `$Home\Documents\WindowsPowerShell\
Microsoft.PowerShell_profile.ps1`. I moved my profile to `$Home\Documents\WindowsPowerShell\profile.ps1` and it started running automatically when powershell starts up, as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cb25e4-83db-3c4b-9805-ec2ef83223e1
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about_Profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You are looking at the PowerShell v6 docs. That information is correct. But you are using PowerShell v5.1.

```
PS C:\> $PSVersionTable.PSVersion
>> $PROFILE | select *host* | fl
>>

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      2      3


AllUsersAllHosts       : C:\Program Files\PowerShell\6\profile.ps1
AllUsersCurrentHost    : C:\Program Files\PowerShell\6\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    : C:\Users\sewhee\Documents\PowerShell\profile.ps1
CurrentUserCurrentHost : C:\Users\sewhee\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

PS C:\> $PSVersionTable.PSVersion
>> $PROFILE | select *host* | fl
>>

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145




AllUsersAllHosts       : C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
AllUsersCurrentHost    : C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    : C:\Users\sewhee\Documents\WindowsPowerShell\profile.ps1
CurrentUserCurrentHost : C:\Users\sewhee\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

**Comment by sdwheeler** [comment]
I just noticed an error in the PS 5.1 and older docs. I am fixing it in #4840
