### ISSUE TITLE
Error: Get-WmiObject : User credentials cannot be used for local connections

### ISSUE THREAD

**Issue by KrupalJoshi** [MicrosoftDocs/PowerShell-Docs#4843]
[Enter feedback here]

Error: Get-WmiObject : User credentials cannot be used for local connections

Getting above error while running Get-WmiObject command **on local computer (for the local computer) with "-Credential"** parameter. This local machine is part of Active Directory. 

Note:

1. Used AD and local admin user in -Credential parameter, but failed with both the cases.
2. Used "localhost", only "hostName", Host name with AD domain name i.e. "HostName"."AD Domain". But failed with all the cases.

Is this not allowed to use "-Credential" parameter with "Get-WmiObject" command while running the command for local computer?

Ex: Get-WmiObject -Class Win32_Process -ComputerName "hostName"."AD domain" -Namespace Root\CIMV2 -Credential "AD Domain"\"UserName".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4916c4f-c22a-f26e-f5c8-4116a4cdd2ce
* Version Independent ID: 625696e5-1792-4c3b-6726-8c6927614fa1
* Content: [Get-WmiObject (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-wmiobject?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by KrupalJoshi** [comment]
Thank you @sdwheeler . Just wanted to confirm that the changes has been made in document only i.e. "Credentials cannot be used when targeting the local computer.", right?

**Comment by sdwheeler** [comment]
@KrupalJoshi That is correct.

**Comment by sadiqueurfarbaz** [comment]
@sdwheeler  Can we now use the -Credential parameter for local connection as well?
