### ISSUE TITLE
Missing documentation on the second parameter set

### ISSUE THREAD

**Issue by discombobulater** [MicrosoftDocs/PowerShell-Docs#4866]
SYNTAX
    Restart-Computer [[-ComputerName] &lt;String[]&gt;] [[-Credential] &lt;PSCredential&gt;] [-AsJob] [-Confirm] 
    [-DcomAuthentication {Default | None | Connect | Call | Packet | PacketIntegrity | PacketPrivacy | 
    Unchanged}] [-Force] [-Impersonation {Default | Anonymous | Identify | Impersonate | Delegate}] 
    [-ThrottleLimit &lt;Int32&gt;] [-WhatIf] [&lt;CommonParameters&gt;]
    
    Restart-Computer [[-ComputerName] &lt;String[]&gt;] [[-Credential] &lt;PSCredential&gt;] [-Confirm] 
    [-DcomAuthentication {Default | None | Connect | Call | Packet | PacketIntegrity | PacketPrivacy | 
    Unchanged}] [-Delay &lt;Int16&gt;] [-For {Wmi | WinRM | PowerShell}] [-Force] [-Impersonation {Default | 
    Anonymous | Identify | Impersonate | Delegate}] [-Protocol {DCOM | WSMan}] [-Timeout &lt;Int32&gt;] [-Wait] 
    [-WhatIf] [-WsmanAuthentication {Default | Basic | Negotiate | CredSSP | Digest | Kerberos}] 
    [&lt;CommonParameters&gt;]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b56646b-9f1d-3f94-64b7-1e556c9ad803
* Version Independent ID: c4358932-1228-6e20-37e3-5ded6a469b8a
* Content: [Restart-Computer (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-computer?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Restart-Computer.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Restart-Computer.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
You are looking at the documentation for PowerShell v6. `Restart-Computer` only has one parameter set in v6. There are [two parameter sets](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/restart-computer?view=powershell-5.1#syntax) in PowerShell v5.1. 

Please see https://docs.microsoft.com/en-us/powershell/scripting/how-to-use-docs
