### ISSUE TITLE
Indexer for .NET types that implement IDictionary<TKey, TValue> prevents exceptions for non-existent keys, unlike the underlying type's indexer

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#4868]
Probably not too many people will run into this, but it's worth documenting _somewhere_:

As detailed in https://github.com/PowerShell/PowerShell/issues/10655, PowerShell doesn't call a type's true indexer (implemented as a parameterized `.Item` property) for types that implement the generic `IDictionary<TKey, TValue>` interface - instead, when given a key, it quietly tests that key's existence with `TryGetValue()` and returns `$null` if it doesn't exist (irrespective of the effective strict mode).

By contrast, if you call the type's true indexer _directly_, via `.Item(<key>)`, an exception may be thrown (note that _in C#_ using `[...]` would also throw the exception).

The following snippet illustrates the difference.

```powershell
PS> [Collections.Generic.Dictionary[string, int]]::new()['nosuchkey']
# No output ($null)

PS> [Collections.Generic.Dictionary[string, int]]::new().Item('nosuchkey')
Exception getting "Item": "The given key 'nosuchkey' was not present in the dictionary."
At line:1 char:1
+ [Collections.Generic.Dictionary[string, int]]::new().Item('nosuchkey' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], GetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenGetting
```

**Comment by sdwheeler** [comment]
@SteveL-MSFT / @joeyaiello Is this an implementation detail we want to document?

**Comment by sdwheeler** [comment]
This belongs in the SDK docs. Need to find the right place for this information.

**Comment by mklement0** [comment]
I don't think the SDK docs are the right place, @sdwheeler, because the issue is unrelated to the PowerShell SDK.

The people most likely to be surprised by this behavior are programmers who have experience with working such types in C#.

**Comment by sdwheeler** [comment]
We discussed this in our shiproom meeting with @joeyaiello and @SteveL-MSFT. The behavior of returning null values for  properties or keys that don't exist is documented behavior for scripters.

The consensus is that this only applies to C# developers writing PowerShell modules. Module developers need to implement this behavior so that their modules work as expected in PowerShell.

**Comment by mklement0** [comment]
> only applies to C# developers writing PowerShell modules

Agreed (in terms of their _expectations_), though not just for writing _modules_ - they also need to be aware of this when writing scripts and simple functions - so that they're not surprised by the resulting behavior.

> need to implement this behavior so that their modules work as expected in PowerShell.

No, they don't, because the behavior is imposed by PowerShell, so if your code outputs objects that implement `IDictionary<TKey, TValue>` (regardless of whether the module is implemented in C# or PowerShell), accessing them _from PowerShell with `[...]`_ will _invariably_ ignore non-existent keys - regardless of what your type does in its true indexer.

>  behavior of returning null values for properties or keys that don't exist is documented behavior for scripters.

While this may be a common _expectation_ and _widely known_, I see it documented in neither `about_Properties` nor in `about_Hash_Tables`.

However, now that I think about it, the behavior _is_ worth mentioning in `about_Hash_Tables`.

**Comment by mklement0** [comment]
To attempt a succinct summary:

* The issue is one of letting C# developers - more generally, developers who are accustomed to compiled .NET languages - know that PowerShell exhibits different behavior.

* This is an issue of _general_ awareness that applies to whatever such a developer does - whether writing PowerShell code for themselves or authoring modules, whether in PowerShell or C#. As stated, there are no _implementation_ considerations, because PowerShell applies its different behavior _invariably_.

* Aside from  a note in `about_Hash_Tables` - the closest thing to `IDictionary<T1,T2>` when using PowerShell's standard features - it's worth creating a new conceptual help topic that summarizes _all_ ways in which compiled-.NET-language users may be surprised by PowerShell's behavior, which should additionally include such features such as _casts_ in PowerShell and the (current) inability to call  _extension methods_, and the limitations with respect to calling _generic_ methods.

**Comment by sdwheeler** [comment]
@mklement0 Good discussion. I would welcome a PR on this subject.

**Comment by sdwheeler** [comment]
Moved to https://github.com/MicrosoftDocs/PowerShell-Docs/wiki/PowerShell-prevents-exceptions-for-non-existent-keys-for-types-that-implement-IDictionary-TKey,-TValue-
