### ISSUE TITLE
What does -force do for each provider? 

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/PowerShell-Docs#4870]
When looking at the "-force" parameter documentation:

The suggested "about_Providers" page is not helpful. All I want, as a reader, is to know what happens if I use itemtype directory and -force and a directory already exists.  Common workflow.  But I'm sent "go look in about_providers", which doesn't mention that "directory" is part of the filesystem provider, and has no links to the filesystem provider.  About providers is more of a high-level overview of the concept of providers, and not really helpful when looking for which provider would handle "directory" and how it implements "new-item".

When I look in the filesystem provider (by sheer guesswork) it has no mention of -force, and the link back to new-item is just the main new-item and not their provider-specific implementation that it *specifically directs me to go look for*.

So the problems are multiple - no obvious link to the filesystem provider when working with directories, and the filesystem provider provides none of the promised information about force, which is described as having provider-defined implementation here.

That's an incredible amount of inside baseball and navigation for the simple question "what does mkdir -force do".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9f560d-e1c9-274d-80bf-85eb8490b548
* Version Independent ID: 609a9efd-598e-050b-c9b8-91402dcc8e87
* Content: [New-Item (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/New-Item?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/New-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/New-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @Pxtl, Thanks for the feedback. 

So, it states in the documentation:
"Forces this cmdlet to create an item that writes over an existing read-only item"

I know implementation may var from provider to provider but the basic premise behind that statement is still that. 

Force cannot get around security restrictions but it can overwrite pre-existing items with Read-Only attribute set. 

The link to the providers is to give context around what providers exist and what new "Items" can be created and means that the _how_ the **Force** parameter does what it does may vary.

**Comment by Pxtl** [comment]
@chasewilson the confusion I had (and I've had to reassure numerous of my colleagues when they review my code) is that there's concern that `-force` on `mkdir` will possibly have side-effects - like it would drop-and-recreate the folder, thus deleting its contents and/or reset ACLs.  Since in so many things, `-force` is generally seen as a risky action - eg `git push`

Since "create this folder or do nothing if it does not exist" is such a common workflow, a line of authoritative text explaining that `mkdir -force` is suitable for this purpose would be helpful.

**Comment by chasewilson** [comment]
I see your issue here. Sorry for the confusion and the late response. I'm going to be testing the behavior in different providers to see if I can update in this doc. If they behave diffrently, I'll update elsewhere and link to it in this doc.

for the FileSystem provider, the `-Force` switch will act as follows:
If a Directory with then specified name currently exists,, New-Item` will simply return the Directory object the currently exists and not overwrite it. and the "create this folder or do nothing if it does not exist" scenario will work when using mkdir as it calls `New-Item`. 

I'll update this thread again when I have a PR ready to go. Feel free to provide more feedback on that as well or just reach out if you have any more questions.
