### ISSUE TITLE
Overload resolution does not look for more specific matches among the members of explicitly implemented interfaces

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#4871]
This is a behavior that few people will bump into, but perhaps it should be documented somewhere (the closest candidate topic would be `about_Methods`):

The scenario is as follows:

* A given type has a _direct member_ whose parameter is `object`-typed.

* The same type also has an _explicit_ interface implementation that has a member of the same name, but with a more specifically typed parameter, say, `int`.

In this scenario, PowerShell only ever uses the direct-member `object`-typed overload and never even consults potentially more specific matches among the members of explicitly implemented interfaces.

The workaround is to explicitly cast to the interface in question first.

See also: https://github.com/PowerShell/PowerShell/issues/10654

A quick demonstration:

```powershell
Add-Type -TypeDefinition @'

   // Interface
   public interface IFoo {
     string Bar(int p);
   }

   // Type that implements the interface
   public class Foo : IFoo {

    // Direct member method named 'Bar'
     public string Bar(object p) { return $"object: {p}"; }

     // *Explicit* implementation of IFoo's 'Bar' method().
     string IFoo.Bar(int p) {
       return $"int: {p}";
     }

    }
'@

[Foo]::new().Bar(1)  # -> 'object: 1'
# !! That is, the less specific `object` overload was chosen,
# !! because the explicit `IFoo` implementation was never consulted.

'---'

# Workaround:
# Cast to `IFoo`
([IFoo] [Foo]::new()).Bar(1)  # -> 'int: 1' - OK
```

**Comment by sdwheeler** [comment]
Closing this since the related PowerShell issue is closed.

**Comment by mklement0** [comment]
@sdwheeler: 

This issue was created _precisely because the related issue was closed_:

* A decision was made not to change the current behavior.

* _Since the current behavior constitutes a pitfall - if an obscure one - it is worth documenting_.

**Comment by SteveL-MSFT** [comment]
`about_Methods` is probably ok to document this.  @sdwheeler what we should document is that when calling .NET methods, if a method takes an object but has an overload via an interface taking a more specific type, the default method to be called is the one that accepts the object unless you explicitly cast it to that interface.  I think an example is sufficient.

**Comment by mklement0** [comment]
I appreciate the clarification, @SteveL-MSFT  and thanks for reopening, @sdwheeler.

Just to reiterate one subtlety about the behavior (hopefully the OP makes it clear enough): the problem only occurs if the more specific member is part of an _explicitly_ implemented interface.
