### ISSUE TITLE
Add documentation about the new release notification feature

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#4881]
Issue Details
-----------------
The update notification feature:
Code PR: https://github.com/PowerShell/PowerShell/pull/10689
RFC PR: https://github.com/PowerShell/PowerShell-RFC/pull/162

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by joeyaiello** [comment]
Going to start on this one right now, may hand off to @daxian-dbw later today

**Comment by daxian-dbw** [comment]
@joeyaiello I can take over this one.
