### ISSUE TITLE
Document support for testing for `$null` using `-is` and `-isnot` in Where-Object parameter documentation as well as about_Comparison_operators

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#4890]
Issue Details
-----------------
[PowerShell PR #10704](https://github.com/PowerShell/PowerShell/pull/10704) adds support for testing for `$null` using `-is` and `-isnot` operators, as well as testing for `$null` using `-is` and `-isnot` parameters in `Where-Object`. For these changes, the about_Comparison_Operators documentation should be updated, as well as the documentation for the `-Is` and `-IsNot` parameters in `Where-Object`.

Also, once #4891 is merged, the about_Operators section that talks about `-is` and `-isnot` should be updated to refer to these operators in 7+ as "type or null comparison operators" instead of just "type comparison operators".

Version(s) of document impacted
------------------------------
- [X] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
PR has been closed without merge.
