### ISSUE TITLE
Add documentation for .NET Global Tool installation

### ISSUE THREAD

**Issue by kapsiR** [MicrosoftDocs/PowerShell-Docs#4906]
Issue Details
-----------------
Add documentation for the [PowerShell as .NET Global Tool](https://www.nuget.org/packages/PowerShell/) installation to:
 - New link in [Installing-PowerShell](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
 - New doc /PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-as-dotnet-global-tool.md

I'd like to submit a PR, if applicable.

Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@joeyaiello / @SteveL-MSFT I am not sure this doc belongs here. What is your opinion?

**Comment by sdwheeler** [comment]
Shiproom notes - need to add this to all three setup docs. Consider putting it at the top of the article.

**Comment by kapsiR** [comment]
@sdwheeler Thanks for clarification. 
Should I add a new page anyway and add notes to all three docs? (with links to the new page)

**Comment by sdwheeler** [comment]
@kapsiR Not a new doc. I will be adding notes to the existing documentation.

**Comment by kapsiR** [comment]
@sdwheeler Would it be ok, if I submit a PR?

**Comment by sdwheeler** [comment]
Yes, you can submit a PR. It should be short with a single example. Add the same information to each of the install articles. There is not enough info for a separate document at this time.
