### ISSUE TITLE
A GREAT Article about this topic on FireEye

### ISSUE THREAD

**Issue by Kriegel** [MicrosoftDocs/PowerShell-Docs#4911]
See [https://www.fireeye.com/blog/threat-research/2016/02/greater_visibilityt.html](https://www.fireeye.com/blog/threat-research/2016/02/greater_visibilityt.html)

I think the article on FireEye has more insides and is better structured than this about_Logging_Windows article.
Perhaps we should Link it or taken over the distinction structure about Module, srciptblock and Transcription Logging.

and with that I think we should have 3 articles.

- about_Logging (description of common things)
- about_Logging_Windows
- about_Logging_non_Windows

the 3 Articles should link to each other
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852ebb1f-a48c-85a2-527e-67b32b625f8f
* Version Independent ID: 044aedf8-3132-7928-c38f-e140669f1c99
* Content: [about_Logging-Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logging_windows?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Logging_Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Logging_Windows.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
I think this information is covered now.
