### ISSUE TITLE
Is it available in PowerShell Core

### ISSUE THREAD

**Issue by victorwoo** [MicrosoftDocs/PowerShell-Docs#4928]
Is it available in PowerShell Core? Or is there a schedule?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8b0e06c3-1c2f-eb5c-7123-a76a8b246e5e
* Version Independent ID: e09aba3d-8acf-12cf-2ac2-02f710a4c0f6
* Content: [New-WebServiceProxy (Microsoft.PowerShell.Management)](https://docs.microsoft.com/zh-cn/powershell/module/Microsoft.PowerShell.Management/New-WebServiceProxy?view=powershell-5.1&redirectedfrom=MSDN&viewFallbackFrom=powershell-7#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
This cmdlet is not available in PowerShell Core. It is dependent on APIs that are not available in .NET Core and are not likely to become available. See https://github.com/PowerShell/PowerShell/issues/9838 for a full discussion of the issue.
