### ISSUE TITLE
Document new common parameters in about_commonparameters

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/PowerShell-Docs#4929]
# Documentation Issue

[PowerShell PR #10238](https://github.com/PowerShell/PowerShell/pull/10238) adds the following new common parameters to PowerShell:

* `-DebugAction`
* `-DebugVariable`
* `-ProgressAction`
* `-ProgressVariable`
* `-VerboseAction`
* `-VerboseVariable`

These will need to be documented in about_commonparameters once that PR has been merged.

## Details of the issue

- URL to the article (Docs or GitHub URL): [/reference/7/Microsoft.PowerShell.Core/About/about_CommonParameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/e6d5c858b8514d22ee083d5d8927912e0ac4e02e/reference/7/Microsoft.PowerShell.Core/About/about_CommonParameters.md)
- Is the issue version specific (Y/N - include version info) :
  - [X] Impacts 7 document
  - [ ] Impacts 6 document
  - [ ] Impacts 5.1 document
  - [ ] Impacts 5.0 document
  - [ ] Impacts 4.0 document
  - [ ] Impacts 3.0 document
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

**Comment by sdwheeler** [comment]
PR has been closed without merge.
