### ISSUE TITLE
Add IgnoreNullValue parameter to ConvertTo-Json documentation

### ISSUE THREAD

**Issue by mdalepiane** [MicrosoftDocs/PowerShell-Docs#4930]
# Documentation Issue
[PowerShell PR #10787](https://github.com/PowerShell/PowerShell/pull/10787) adds the `-IgnoreNullValue` parameter to ConvertTo-Json.

These will need to be documented in reference/7/Microsoft.PowerShell.Utility/ConvertTo-Json once that PR has been merged.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content
  - [ ] Version 5.0 content
  - [ ] Version 4.0 content
  - [ ] Version 3.0 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

**Comment by sdwheeler** [comment]
Code PR was closed without merging. Closing this issue.
