### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/PowerShell-Docs#4932]
Your example shows "-TargetName" and that does not work fro me running 1903, I have to use "-ComputerName"
It also show "-IPv4" as a parameter which fails for me and does not appear to work anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e68a7a-10e0-2ae5-b20a-517716367894
* Version Independent ID: 1cf2ccd2-f099-3f92-b698-36311baa0b81
* Content: [Test-Connection (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Test-Connection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Test-Connection.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
You are looking at the help for PowerShell v6. `-TargetName` is a valid parameter in PowerShell v5.1. Be sure you have selected the correct version of the documentation.

See https://docs.microsoft.com/en-us/powershell/scripting/how-to-use-docs?view=powershell-6
