### ISSUE TITLE
AZ Data RC1 dont install AZData_Cli  got below error

### ISSUE THREAD

**Issue by sneevand** [MicrosoftDocs/PowerShell-Docs#4935]
7))
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
ERROR: sfctl 8.0.0 has requirement knack==0.5.2, but you'll have knack 0.6.1 which is incompatible.
ERROR: azure-cli 2.0.74 has requirement knack>=0.6.3,~=0.6, but you'll have knack 0.6.1 which is incompatible.
ERROR: azure-cli 2.0.74 has requirement six~=1.12, but you'll have six 1.11.0 which is incompatible.
ERROR: azure-cli-core 2.0.74 has requirement knack~=0.6.2, but you'll have knack 0.6.1 which is incompatible.
Installing collected packages: six, setuptools, urllib3, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, PyYAML, kubernetes, decorator, ply, jsonpath-ng, jsonpointer, jsonpatch, knack, azdata-cli-core, azdata-cli, azdata-cli-app, azdata-cli-cluster, pywebhdfs, tqdm, azdata-cli-hdfs, ipython-genutils, traitlets, jupyter-core, pyzmq, tornado, jupyter-client, ptyprocess, pexpect, wcwidth, prompt-toolkit, pickleshare, parso, jedi, backcall, ipython, ipykernel, pandocfilters, webencodings, bleach, more-itertools, zipp, importlib-metadata, pyrsistent, attrs, jsonschema, nbformat, mistune, defusedxml, entrypoints, testpath, nbconvert, terminado, prometheus-client, Send2Trash, notebook, jupyter-console, qtconsole, widgetsnbextension, ipywidgets, jupyter, markdown, mdv, azdata-cli-notebook, azdata-cli-profile, azdata-cli-spark, pymssql, humanize, backports.csv, terminaltables, cli-helpers, argparse, configobj, sqlparse, click, mssql-cli, azdata-cli-sql
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/__pycache__/six.cpython-35.pyc'
Consider using the `--user` option or check the permissions.

**Comment by sdwheeler** [comment]
This is not a PowerShell issue.
