### ISSUE TITLE
Document `$OutputPreference`

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#4947]
# Summary of the new document or enhancement

Document new `$OutputPreference` variable related to https://github.com/PowerShell/PowerShell/pull/10814 added in PS7

**Comment by mklement0** [comment]
A decision was made _not_ to include this in v7.0:

Quoting @SteveL-MSFT  from https://github.com/PowerShell/PowerShell/issues/10811#issuecomment-543926695:

> More thinking is needed on this which is why it won't make it into PS7, but something we can target for next release.

As an aside: more thinking is not only needed with respect to the implementation, but also with respect to the _name_ of the new preference variable.
