### ISSUE TITLE
nxFileLine will remove empty lines

### ISSUE THREAD

**Issue by paratz** [MicrosoftDocs/PowerShell-Docs#4952]
Hello, I'm using this configuration to replace a line in a configuration file for the nagios client on RHEL 7.7:
        nxFileLine ConfiguraAllowedHosts
        {
            FilePath = "/etc/nagios/nrpe.cfg"
            ContainsLine = 'allowed_hosts=127.0.0.1,192.168.1.1,::1'
            DoesNotContainPattern = 'allowed_hosts=127.0.0.1,::1'
            DependsOn = '[nxPackage]nrpe'
}

The configuration is properly applied and the default line is removed, and the new one is appended, however all the "empty" lines are removed as well, I'm attaching screenshot of the original file, and how it looks after the configuration is applied.

Before Configuration: https://paratz.blob.core.windows.net/pubparatz/before_configuration.png

After Configuration: https://paratz.blob.core.windows.net/pubparatz/after_configuration.png

Thanks for your comments,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eddac90-5561-2a63-b254-44a4550eaafe
* Version Independent ID: 5416fbac-7726-34eb-65d3-2ac253d6845d
* Content: [DSC for Linux nxFileLine Resource - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/linux/lnxfilelineresource?view=powershell-6)
* Content Source: [reference/docs-conceptual/dsc/reference/resources/linux/lnxFileLineResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/reference/resources/linux/lnxFileLineResource.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is a product issue. You should probably open a support ticket so that this can get routed to the right people that can update the resource.

/cc: @mgreenegit

**Comment by sdwheeler** [comment]
@paratz You can file an issue here: https://github.com/microsoft/PowerShell-DSC-for-Linux/issues
