### ISSUE TITLE
Misinformation about passing Booleans to [switch] parameters with -File

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#4964]
Note: Both `about_pwsh` and `about_powershell.exe` are affected.

Said topics state:

> In rare cases, you might need to provide a Boolean value for a switch parameter. To provide a Boolean value for a switch parameter in the value of the File parameter, enclose the parameter name and value in curly braces, such as the following: `-File .\Get-Script.ps1 {-All:$False}`.

(a) A workaround is no longer necessary in PowerShell _Core_, because the values `$true`/ `$false` or `true`/ `false` now _are_ accepted.

(b) The - syntactically awkward - `{-All:$False}` _Windows PowerShell_ workaround _doesn't work_ (as an aside: `{-All:$False}` from  _within_ PowerShell mistakenly triggers translation of this argument into an `-encodedCommand` argument) 

The following Pester tests demonstrate that:

* you now _can_ use `$true` and `$false` as switch-parameter values in PowerShell _Core_

* the workaround for  _Windows PowerShell_ does _not_ work.

Note: The tests, which must be run on Wndows, shell out to `cmd.exe`, because calling the PowerShell CLI from the outside is the typical use case.

```powershell
Describe "Pass Boolean to a [switch] parameter with -File" {
  BeforeAll {
    Push-Location testdrive:\    
    # Create a script with switch -foo that echoes the switch's value.
    '[CmdletBinding()] param([switch] $foo) $foo.IsPresent' > test.ps1
  }
  It "PS Core: Value '$true' is recognized." {
    # OK.
    cmd /c 'pwsh -noprofile -file ./test.ps1 -foo:$true' | Should -Be 'True'
  }
  It "WinPS: '{-foo:$true}' can be used as a workaround" {    
    # !! FAILS
    cmd /c 'powershell.exe -noprofile -file ./test.ps1 {-foo:$true}' | Should -Be 'True'
  }
  AfterAll {
    Pop-Location
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f08b4383-a316-c14c-fffb-beef46ac1cca
* Version Independent ID: 4320a570-6740-fb56-3076-0fd93bf19fae
* Content: [about_pwsh - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
HI @mklement0, As always, thank you very much for the great feedback. 

As to this case, when running in PowerShell, the `{}` gets interpreted incorrectly as it's still under the powershell interpreter. Even in your examples in running with the `cmd.` in the powershell session. 
If you run it the actual `cmd` terminal, the example will work.

However, this isn't exactly clear in the docs and I'm adjusting to clarify as well as adding a workaround for the powershell command line that actually works. Although it does require the use of the **Command** parameter. 

Thanks again and if you have anything [else to add, feel free to comment in the linked PR

**Comment by mklement0** [comment]
Thanks, @chasewilson, but I'm confused: something like `{-foo:$false}` does _not_ work from `cmd.exe`, as the above test demonstrates.

To my knowledge, there isn't a workaround for Windows PowerShell with `-File` from `cmd.exe` - you must resort to `-Command`, which changes the syntax requirements (no mere script file names allowed) and also how arguments are parsed.

(From _inside_ PowerShell, enclosing an _entire command_ in `{ ... }` makes sense and is the most robust way to pass a command, due to behind-the-scenes-use of  Base64 encoding via `-EncodedCommand`, but needing to call another PowerShell instance via its CLI from inside PowerShell is rare to being with.)

**Comment by sdwheeler** [comment]
Here is what I get.

In PowerShell 7:

```
PS> pwsh -noprofile -f .\testscript.ps1 -All:$false
The value of $All=False
PS> powershell -noprofile -f .\testscript.ps1 -All:$false
C:\temp\testscript.ps1 : Cannot process argument transformation on parameter 'All'. Cannot convert value
"System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept only Boolean values
and numbers, such as $True, $False, 1 or 0.
    + CategoryInfo          : InvalidData: (:) [testscript.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,testscript.ps1

PS> powershell -noprofile -f .\testscript.ps1 {-All:$false}
The value of $All=False
```

In Powershell 5.1:

```
PS> pwsh -noprofile -f .\testscript.ps1 -All:$false
The value of $All=False
PS> pwsh -noprofile -f .\testscript.ps1 {-All:$false}
The value of $All=False
PS> powershell -noprofile -f .\testscript.ps1 {-All:$false}
The value of $All=False
PS> powershell -noprofile -f .\testscript.ps1 -All:$false
C:\temp\testscript.ps1 : Cannot process argument transformation on parameter 'All'. Cannot convert value
"System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept only Boolean values
and numbers, such as $True, $False, 1 or 0.
    + CategoryInfo          : InvalidData: (:) [testscript.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,testscript.ps1
```

In CMD.EXE on Windows 10:

```
C:\temp>pwsh -noprofile -f C:\temp\testscript.ps1 -All:$false
The value of $All=False

C:\temp>pwsh -noprofile -f C:\temp\testscript.ps1 {-All:$false}
The value of $All=False

C:\temp>powershell -noprofile -f C:\temp\testscript.ps1 -All:$false
C:\temp\testscript.ps1 : Cannot process argument transformation on parameter 'All'. Cannot convert value
"System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept only Boolean values
and numbers, such as $True, $False, 1 or 0.
    + CategoryInfo          : InvalidData: (:) [testscript.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,testscript.ps1


C:\temp>powershell -noprofile -f C:\temp\testscript.ps1 {-All:$false}
The value of $All=False
```

**Comment by mklement0** [comment]
@sdwheeler, please note that I included Pester tests for a reason:

They gives a shared reference point whose behavior we can easily verify, simply by running the tests.

If you run the tests, you'll see that they fail for the `{-foo:$true}` from `cmd.exe` test - or do they really not fail for you?

---

You don't show the contents of `testscript.ps1`, but I strongly suspect that the tests _ostensibly_ succeeded, because you didn't make the script an _advanced_ script, via either a `[CmdletBinding()]` attribute or a `[Parameter()]` attribute.

If you do that, `{-All:$False}` will be passed _verbatim_, as a _positional argument_ to the target script. Thus, any declared `-All` parameter will be unaffected, which means that _the test isn't valid_.

If you don't want to run the Pester tests, here's a more direct repro:

In PowerShell, create file `test.ps1` as follows:

```powershell
# Create an advanced script that accepts no undeclared parameters and
# echoes the value of the -foo switch parameter.
'[CmdletBinding()] param([switch] $foo) $foo.IsPresent' > test.ps1
```

The run `cmd` to enter an interactive `cmd.exe` session in the same directory, and run the following:

```powershell
powershell -file test.ps1 {-foo:$false}
```

You'll see that it fails with:

```
A positional parameter cannot be found that accepts argument '{-foo:$false}'
```

**Comment by sdwheeler** [comment]
@mklement0 Thanks, I now see what is going on. We will update the doc.
