### ISSUE TITLE
Selecting Version PowerShell 5.1 just come back to THIS page

### ISSUE THREAD

**Issue by jcbottorff-marvell** [MicrosoftDocs/PowerShell-Docs#4969]
I was looking for the command Remove-Alias, which apparently does not exist in PS 5.1. When I select the version dropdown to give the PS 5.1 page, it stays on this page. It should give a page saying command does not exist in PS 5.1. It does give a line that says "The requested page is not available for PowerShell 5.1. You have been redirected to the newest product version this page is available for.", but that's not saying Remove-Alias does not exist for PS 5.1, just there is no doc page for it. If I set a filter for PS 5.1, it should show a page saying "That command does not exist on the selected version".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9940d5-646f-5385-a1b8-af925a94f379
* Version Independent ID: cb2ad8bb-2cf2-3340-5e22-24be80c67cd7
* Content: [Remove-Alias (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/remove-alias?view=powershell-6&viewFallbackFrom=powershell-5.1)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Remove-Alias.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Remove-Alias.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@jcbottorff-marvell This is by design. However, we could add information to the article to say that this cmdlet was introduced in PowerShell v6. That information is in the release notes but on here.

**Comment by davidsmatlak** [comment]
Tracking updates for cmdlets that were added in PS 6.x

| Cmdlet | Pull Request |
| ---- | ---- |
| Remove-Alias | #4995 |
| Get-Uptime | #4995 |
| Remove-Service | #4995 |

**Comment by davidsmatlak** [comment]
Added notes for cmdlets and parameters that were added in PowerShell 6.1. For the complete list of changes, see [What's New in PowerShell Core 6.1](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-61).

| Pull Request | Cmdlet |
| ---- | ---- |
| #5043 | ConvertFrom-Markdown, Get-PfxCertificate, Show-Markdown |

**Comment by davidsmatlak** [comment]
Added notes for cmdlets and parameters that were added in PowerShell 6.2. For the complete list of changes, see [What's New in PowerShell Core 6.2](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-62).

| Pull Request | Cmdlet |
| ---- | ---- |
| #5044 | about_pwsh, ConvertFrom-Json, ConvertTo-Json, Enter-PSHostProcess, Send-MailMessage  |
| #5047 | Format-Hex, Get-Culture, Get-PSHostProcessInfo, Join-String, Disable-ExperimentalFeature, Enable-ExperimentalFeature |
