### ISSUE TITLE
Doc is incorrectly referencing function that does not exists

### ISSUE THREAD

**Issue by hecflores** [MicrosoftDocs/PowerShell-Docs#4972]
This doc seems to be incorrect or improperly designed. In the last coding section, there is a call to a method called "GetIndexOfEntry" but that method is nowhere to be found... What does that method do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99c09958-17f0-ba87-3c42-dc5716ef3f00
* Version Independent ID: 174cab3b-c73e-0523-530a-322fd0c480d8
* Content: [Creating a constrained runspace - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/creating-a-constrained-runspace?view=powershell-6)
* Content Source: [reference/docs-conceptual/developer/hosting/creating-a-constrained-runspace.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/hosting/creating-a-constrained-runspace.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
GetIndexOfEntry is shown in https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/windows-powershell01-sample. These articles are built around a set of sample codes in SDK download package. https://www.microsoft.com/en-us/download/details.aspx?id=2560
