### ISSUE TITLE
Compress-Archive path separator does not follow standard

### ISSUE THREAD

**Issue by jaykay-design** [MicrosoftDocs/PowerShell-Docs#4975]
# Product Issue

When adding files to an archive the path to the file inside the archive is separated with backslashes instead of forward slashes.

Related to this: https://stackoverflow.com/questions/1825585/determine-installed-powershell-version

**Comment by sdwheeler** [comment]
@jaykay-design I looked at the stackoverflow post and I don't see how it relates to what you are reporting. Also, it is unclear exactly what the issue is. Please answer the following questions:

- What behavior are you getting?
- What behavior are you expecting?
- What version of PowerShell are you using on what OS? (provide the output of `$PSVersionTable`)

**Comment by jaykay-design** [comment]
Sorry for the useless report. I also linked the wrong article, should have been [this one](https://superuser.com/questions/1382839/zip-files-expand-with-backslashes-on-linux-no-subdirectories), it references [ZIP File Format reference section](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) 4.4.17.1.

When, for example, compressing this directory structure:

example.txt
- directory1\example.txt

The path inside the compressed archive is stored as directory\example.txt instead of directory/example.txt

I was stung by this "bug" as the application which uses the archive created with Compress-Archive can't recognize the folder structure in it ([SqlPackage](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15)).  

I'm using:
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by sdwheeler** [comment]
OK, this is a product issue. Please file an issue at: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues.
