### ISSUE TITLE
Install using Chocolatey

### ISSUE THREAD

**Issue by scottgolightly** [MicrosoftDocs/PowerShell-Docs#4986]
I noticed that Powershell Core is available on Chocolatey to install. It doesn't look to be an official Microsoft account that has posted the package but any chance you could make it official and then document how to install using Cocolatey on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfa3f4fc-5411-0135-c8c2-6615bb5584a1
* Version Independent ID: 0628c7a6-59c3-55cf-f1d3-7e348550281f
* Content: [Installing PowerShell Core on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by joeyaiello** [comment]
Given that it's not a supported installation method, it shouldn't be doc'd here, and unfortunately we don't have any plans right now to make that an official installation method. Sorry about that
