### ISSUE TITLE
Doc changes to Test-Connection

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#4987]
# Documentation Issue

@vexx32 is making large changes to the behavior of `Test-Connection`. The output is changing. See https://github.com/PowerShell/PowerShell/pull/10478

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by vexx32** [comment]
@sdwheeler though I'm unsure of exact timing and if we want it in v7 or following from that, you may want to reference https://github.com/PowerShell/PowerShell/pull/10697 as well. 🙂

**Comment by sdwheeler** [comment]
@vexx32 you just did ;-) Thanks, I am going through the change logs and creating docs issues. I knew you had a lot in the pipeline on this. We need to document what makes it into GA.

**Comment by vexx32** [comment]
👍 I'm hoping a bit more makes it into GA, but I don't know for sure, so we'll see! 🙂

**Comment by vexx32** [comment]
@sdwheeler made it in after all. I hope there should be enough detail in the PR description to give you plenty to work with, but if you need a hand just give me a shout and point me at the files you need me to address! 😊

**Comment by joeyaiello** [comment]
Agree on the priority. Given that this is basically changed back to the Windows PowerShell behavior plus a couple extra bonuses, we can probably copy over the 5.1 content and start from there. 

@vexx32 any chance you might want to jump on this one? We're getting a big list for pre-GA ;)

**Comment by vexx32** [comment]
I may take a look this evening. As you say, it's on the surface somewhat similar to `Test-Connection` was in 5.1 (though I suppose it takes many ideas from `Test-NetConnection` as well) so writing the documentation should be reasonably straightforward.
