### ISSUE TITLE
Document changes to DSC for v7

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#4989]
# Summary of the new document or enhancement

New experimental feature in v7-preview.4

Update PSDesiredStateConfiguration module version to 2.0.3 and bring new tests; enable compilation to MOF on non-Windows and use of Invoke-DSCResource without LCM (PowerShell/PowerShell#10516)

Details of requested document:

- Proposed title:
- Propose location in the TOC:
- Target audience:
- Purpose or scenario:
  _or_
  Proposed changes/additions to existing article:
- List of related articles to link to:

**Comment by mrhockeymonkey** [comment]
Perhaps this documentation could resolve my issue here: https://github.com/PowerShell/PowerShell/issues/10183 

I have tried to compile a MOF on a non-windows OS as demonstrated in the [Powershell 7 Preview 4 blog](https://devblogs.microsoft.com/powershell/powershell-7-preview-4/) with little success. 

The error I receive is:
```powershell
WARNING: Embedded resources are not support on Linux or macOS.  Please see https://aka.ms/PSCoreDSC for more details.
Configuration: /mount/test.ps1
Line |
   1 | Configuration ScriptTest {
     | ^ The term 'PSModule' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

InvalidOperation: /opt/microsoft/powershell/7-preview/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1
Line |
3745 |     throw $ErrorRecord
     |     ^ Errors occurred while processing configuration 'ScriptTest'.
```

I don't expect a technical solution here but any documentation that can help me figure out how to do this and what is or is not supported would be greatly appreciated
