### ISSUE TITLE
Document VT control sequences in console host

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#4990]
# Summary of the new document or enhancement

As a PowerShell developer I want to know the formatting capabilities of the console with respect to VT/ANSI escape sequence so that I can add colors and emphasis in my output.

Need document implementation details like:
- Update console host to support XTPUSHSGR/XTPOPSGR VT control sequences that are used in composability scenarios. (PowerShell/PowerShell#10208)

Details of requested document:

- Proposed title: about_ANSI_console_support
- Propose location in the TOC: 
- Target audience:
- Purpose or scenario:
  _or_
  Proposed changes/additions to existing article:
- List of related articles to link to:

**Comment by joeyaiello** [comment]
We need something like an `about_Terminals` to say the following:
* we don't parse VT100 / ANSI codes, they get passed to your terminal
* link to VT100 / ANSI spec for how those get used where they're supported
* considerations to Windows terminals, link out to documentation (hopefully provided by @bitcrazed)

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/windows/console/console-virtual-terminal-sequences

**Comment by bitcrazed** [comment]
What @sdwheeler [said ](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4990#issuecomment-713053973)😜

This said, I do think it would be worth adding some docs demonstrating how to generate VT Sequences from PowerShell, how to escape the VT sequences for color, and also how to explicitly emit Unicode glyphs by id ... kinda like [this little gist](https://gist.github.com/bitcrazed/346b166067c9d9bf5d43bd2c100daff0) I put together.

![image](https://user-images.githubusercontent.com/961950/96920035-7effab00-1461-11eb-9e26-176be281bde6.png)

Such a doc should link to the aforementioned [Console VT docs](https://docs.microsoft.com/windows/console/console-virtual-terminal-sequences) which documents the VT sequences supported by Console and provides code samples for enabling VT mode etc.,

**Comment by sdwheeler** [comment]
Closed by #7921
