### ISSUE TITLE
Document New-PSBreakpoint & new -Breakpoint parameter for Debug-Runspace

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#4994]
# Summary of the new document or enhancement

New New-PSBreakpoint cmdlet & new -Breakpoint parameter for Debug-Runspace (PowerShell/PowerShell#8923)

Details of requested document:

- Proposed title:
- Propose location in the TOC:
- Target audience:
- Purpose or scenario:
  _or_
  Proposed changes/additions to existing article:
- List of related articles to link to:

**Comment by joeyaiello** [comment]
@TylerLeonhardt we also need to document the stuff in https://github.com/PowerShell/PowerShell/pull/11312 assuming it makes it in

**Comment by TylerLeonhardt** [comment]
There is no New-PSBreakpoint or -Breakpoint parameter. And that PR only affects API so no new cmdlets/parameters need documentation

**Comment by theJasonHelmick** [comment]
Checked with @TylerLeonhardt and verified there is no need for documentation as we went a different direction and there is no New-PSBreakpoint or -Breakpoint on Debug-Runspace.
