### ISSUE TITLE
Doc Out-Gridview, Show-Command and Get-Help -ShowWIndow for PS7

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#5002]
Out-GridView and Show-Command haven't changed (unless Show-Command doc mentions workflow which is not supported).  Get-Help -ShowWindow was removed and added back and working now.

## Context of the issue

- URL to the article (Docs or GitHub URL): Pending PR https://github.com/PowerShell/PowerShell/pull/10899
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [X] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
I need to add `Show-Command` to this PR.
