### ISSUE TITLE
Example 7 Doesn't Work:

### ISSUE THREAD

**Issue by DMoonesinghe** [MicrosoftDocs/PowerShell-Docs#5004]
[Enter feedback here]

Example 7:  It creates a new file.  But doesn't insert process data into the newly created csv file.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9fc1c7-ddcc-8573-780b-b3a6f52c6787
* Version Independent ID: 217c0b18-24d5-6e58-506b-0cd849fa956c
* Content: [Out-GridView (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-gridview?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Out-GridView.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Out-GridView.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by davidsmatlak** [comment]
@DMoonesinghe Example 7 works, but I'll update the document. The **PassThru** parameter description mentions how to select items from the `Out-GridView` window and send the objects down the pipeline.

**Comment by davidsmatlak** [comment]
The `Out-GridView` document was updated on PR #5015.
