### ISSUE TITLE
Structured archives, -Path parameter and piping

### ISSUE THREAD

**Issue by rendmath** [MicrosoftDocs/PowerShell-Docs#5008]
It would be useful to specify under which conditions the files are "flattened" at the root of the archive vs. an archive with a directory structure inside. According to my tests, a structured archive is created only when the -Path parameter is used with a folder or wildcard path. I couldn't find a way to get a structured archive through piping.

Ideally, the cmdlet should take a -RootPath parameter to resolve the path of each file inside the archive, thereby allowing the creation of structured archives from a pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e67ee59-8a3e-59ad-7c8d-a78605f55b66
* Version Independent ID: 3c8b8ee9-6a97-4eda-d184-49e728abf0a6
* Content: [Compress-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

**Comment by sdwheeler** [comment]
@rendmath The cmdlet is working as designed. We will update the docs to be more explicit about the behavior. 

I agree that there is room for improvement with the Archive cmdlets. You can file a feature request at https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues.
