### ISSUE TITLE
PowerShell module browser has wrong link for ConfigurationManager

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/PowerShell-Docs#5010]
[Originally reported on Twitter](https://twitter.com/AriSaastamoinen/status/1188719241417166848)

https://docs.microsoft.com/powershell/module/
Search for `configu`
- The link for **ConfigurationManager** goes to `https://docs.microsoft.com/en-us/powershell/module/ConfigurationManager/`
- The actual link is https://docs.microsoft.com/en-us/powershell/module/configurationmanager/configurationmanager?view=sccm-ps

The article name is `configurationmanager` so the link needs that included as well to work
(Unless you can tell me how to fix that target so it's the default page for that folder. I went down that path a few months ago and never got a clear answer...)

**Comment by sdwheeler** [comment]
You need to add a redirect for /sccm-ps/ConfigurationManager/index.md to point to https://docs.microsoft.com/en-us/powershell/module/configurationmanager/configurationmanager?view=sccm-ps
