### ISSUE TITLE
Set working directory to current directory in Start-Job

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#5012]
# Documentation Issue

After https://github.com/PowerShell/PowerShell/pull/10920 we will have a breaking change - Start-Job will start in current directory.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/start-job
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No

## Detailed description of the issue

Before: Start-Job starts in current user home directory.
After: Start-Job starts in current (for current runspace) directory.

**Comment by sdwheeler** [comment]
@iSazonov Can you please fill out the Issue template?

**Comment by iSazonov** [comment]
@sdwheeler Sorry, I lost my modifications. It seems a page was refreshed before post:-(.
