### ISSUE TITLE
Confusing paragraph about Disable-PSRemoting

### ISSUE THREAD

**Issue by rendmath** [MicrosoftDocs/PowerShell-Docs#5014]
"Disable-PSRemoting blocks remote access to all PowerShell session configurations on the local computer. This prevents remote users from creating temporary or persistent PowerShell sessions to the local computer. Disable-PSRemoting does not prevent remote users from creating PowerShell sessions to the local computer."
The third phrase seems to contradict the second one. This is either wrong, or poorly worded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a599d016-ab8f-e3e2-1985-d963a3b3c487
* Version Independent ID: 601907dd-f6c2-0540-5189-43c2d57308d3
* Content: [Disable-PSRemoting (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/disable-psremoting?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Disable-PSRemoting.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Disable-PSRemoting.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@rendmath What it is trying to say is that the remote endpoints are disabled for remote access over the network. However, if you are logged on locally to the machine you can create a "remote" session to the local machine via a loopback connection. This is, in fact, how the Windows Compatibility module works. PowerShell Core on Windows connects to a Windows PowerShell endpoint to run commands in "compatibility mode".
