### ISSUE TITLE
Bring back doc for `Get-Counter` cmdlet for PS7

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#5020]
# Documentation Issue
`Get-Counter` is coming back for PS7 (note that Import-Counter and Export-Counter are NOT): https://github.com/PowerShell/PowerShell/pull/10933

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Win

**Comment by iSazonov** [comment]
@SteveL-MSFT @sdwheeler The Get-Counter code was cleaned up for compliance. Should we update the documentation too?

**Comment by sdwheeler** [comment]
@iSazonov If the compliance changes affected the function, then we need to document it. What were the changes?

**Comment by iSazonov** [comment]
@sdwheeler I think @SteveL-MSFT or @TravisEz13 could add more information.
