### ISSUE TITLE
Document Read-Host new parameter called MaskInput

### ISSUE THREAD

**Issue by davinci26** [MicrosoftDocs/PowerShell-Docs#5021]
# Documentation Issue

Add documentation for the new parameter of `Read-Host` that was introduced in https://github.com/PowerShell/PowerShell/pull/10908

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [x] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by iSazonov** [comment]
From @PaulHigin 
>  This will be unsupported over remoting for now, since it involves protocol changes.
