### ISSUE TITLE
OpenSSH issue with spaces

### ISSUE THREAD

**Issue by CaryJ** [MicrosoftDocs/PowerShell-Docs#5024]
A better recommendation, that comes from the comments of the GitHub issue linked to from this page, is to use the 8.3 shortpath in the config file, e.g. `C:\PROGRA~1\POWERS~1\6\pwsh.exe`.  Unfortunately, Powershell does not have an easy way to determine the shortpath.  You can find it from cmd dir /X, or using the pscx cmdlet Get-ShortPath.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2c72de-1e9f-b263-e9d8-ccebd4c6ab3f
* Version Independent ID: f8beb543-51a4-1258-3dd5-eeccdac53c36
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
You can get the 8.3 folder name with WMI:

```
Get-CimInstance Win32_Directory -Filter 'Name="C:\\Program Files"' | select EightDotThreeFileName 
```
