### ISSUE TITLE
Could you provide an option in powershell to Add-Verb in approved list of verbs?

### ISSUE THREAD

**Issue by PramodKumarYadav** [MicrosoftDocs/PowerShell-Docs#5036]
Many a time, while building our test framework, I and my buddy find that we don't have the right verb for the job in hand. We try to adjust to the verbs available (since we dont like those warnings), but we know that another verb would have been a better choice in helping us remember what exactly does that function do. Should you provide an option to users to add new verbs in the approved list so that we don't get warnings (as shown in vscode for ex?). I am sure as end-users there are more people who would love to name their command's as they find most appropriate for them rather than a restrictive list that cannot be extended. Sort is one example, Download is another, list goes on depending on what we want to do with a function. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39395c79-9e25-552c-5f91-279ae84cf4a3
* Version Independent ID: 8f02efa2-a748-8d78-f6e6-83aaaa228b78
* Content: [Get-Verb (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/functions/get-verb?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/Functions/Get-Verb.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/Functions/Get-Verb.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Please file a feature request at https://github.com/PowerShell/PowerShell/issues
