### ISSUE TITLE
Doc new pwshw.exe for PS7

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#5039]
# Documentation Issue

Waiting on PR https://github.com/PowerShell/PowerShell/pull/10962

## Context of the issue

For PS7 we add a pwshw.exe along with pwsh.exe for Windows.  pwshw.exe is built as a WinExe which means it won't pop up a console window (which also means you can't use it interactively).  It's for admins to run PS7 scripts without popping up a console window on user's desktop.  pwshw.exe takes the same command line arguments as pwsh.exe.

  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Win

**Comment by sdwheeler** [comment]
Code PR is close without merging. Closing this issue.

**Comment by mdnava** [comment]
Is this ever happening ?

Running a script without popping up a console window is a necessary feature for PowerShell.
Param -WindowStyle Hidden just doesn't cut it.
