### ISSUE TITLE
Code Samples

### ISSUE THREAD

**Issue by North2Alaska** [MicrosoftDocs/PowerShell-Docs#5040]
Why are the code samples for C#.  This is a PowerShell page, talking about PowerShell and how to write a PowerShell function and how to declare a PowerShell parameter.  Why are the examples in C# and not PowerShell.  This makes this documentation almost worthless...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ddfc145-6c24-3be3-2e2e-91e777e6c0c7
* Version Independent ID: fdddafa1-8152-da7a-357e-89debcd12c87
* Content: [How to Declare Cmdlet Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-declare-cmdlet-parameters?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-declare-cmdlet-parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-declare-cmdlet-parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
You are looking at the SDK documentation. This is how to write compiled cmdlets. For scripted modules see https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters
