### ISSUE TITLE
feature request : add an option Set-PSReadLineKeyHandler to not display the extra stuff

### ISSUE THREAD

**Issue by ratatoeey** [MicrosoftDocs/PowerShell-Docs#5045]
please see https://github.com/Moeologist/scoop-completion/issues/11#issuecomment-548936695 and the following screenshot
![scoop-completion](https://user-images.githubusercontent.com/57241146/68052611-04012a00-fd10-11e9-881b-8c195d967b65.PNG)

add a option to not display the extra stuff or menu. it is marked roughly by the red lines. 
for me the stuff is just useless and takes up space without providing value.

this request is not properly fleshed out. just a minimal report. this has been a thorn in my side for a long time using scoop-completion.

---

regards ratatoeey

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8a4d7-73ea-ae61-7c14-81b8bb892e0e
* Version Independent ID: 0cdc56fa-0b7d-4375-6a00-fe204da8d45c
* Content: [Set-PSReadLineKeyHandler (PSReadLine)](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler?view=powershell-6)
* Content Source: [reference/6/PSReadLine/Set-PSReadlineKeyHandler.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PSReadLine/Set-PSReadlineKeyHandler.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by Moeologist** [comment]
Extra stuff was caused by MenuCompletion.Set-PSReadLineKeyHandler only set shortcut.

**Comment by sdwheeler** [comment]
@ratatoeey Please file this feature request in the PSReadLine source repo: https://github.com/powershell/psreadline/issues
