### ISSUE TITLE
feature request: make Set-PSReadLineKeyHandler apply only for specific command, not every command

### ISSUE THREAD

**Issue by ratatoeey** [MicrosoftDocs/PowerShell-Docs#5046]
please see https://github.com/Moeologist/scoop-completion/issues/11, specifically from this part

>also, now importing scoop-completion also show completions for gc(get-content) and iwr (Invoke-WebRequest) and others that I can't recall yet.

I think if its scoop-completion, it should not modify behavior for other commands. assuming that's not due to scoop-completion specifically.

---

regards ratatoeey

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8a4d7-73ea-ae61-7c14-81b8bb892e0e
* Version Independent ID: 0cdc56fa-0b7d-4375-6a00-fe204da8d45c
* Content: [Set-PSReadLineKeyHandler (PSReadLine)](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler?view=powershell-6)
* Content Source: [reference/6/PSReadLine/Set-PSReadlineKeyHandler.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PSReadLine/Set-PSReadlineKeyHandler.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@ratatoeey Please file this feature request in the PSReadLine source repo: https://github.com/powershell/psreadline/issues

**Comment by ratatoeey** [comment]
i guess this issue can't be moved to that repo from the github interface. so, no problem. and thanks.

---

regards ratatoeey
