### ISSUE TITLE
What's a "solution"?

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/PowerShell-Docs#5050]
> Create a binary PowerShell solution

Okay, but what's a "solution"? I don't suppose you mean a Visual Studio solution, because there is no Powershell solution in the workloads of either [Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019) or [2017](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2017). I don't suppose you mean a liquid solution either.

So far, the only Microsoft-support way of starting a PowerShell binary module project that I've found is: <https://github.com/PowerShell/PowerShellStandard/tree/master/src/dotnetTemplate>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd17c79e-61a2-4a6f-20b5-bb853c5eb6d8
* Version Independent ID: 8966196f-bfdb-49e6-8106-6745cf957bc3
* Content: [How to Write a PowerShell Binary Module - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-binary-module?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/developer/module/how-to-write-a-powershell-binary-module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/module/how-to-write-a-powershell-binary-module.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
We aren't updating the old SDK content, but there is a new article that show how to use the newer PowerShell templates. See https://docs.microsoft.com/powershell/scripting/dev-cross-plat/writing-portable-modules

**Comment by skycommand** [comment]
@sdwheeler Thanks a lot for fixing the issue by moving it under the "Legacy SDK" section and adding up-to-date contents. 👍 From my point of view, "fixed" is the proper tag here, but if some corporate rule forces you to use the "wont-fix" tag, I'm fine. 😉

By the way, of all the Microsoft people I know, I like you the most. And of all the Microsoft teams, I like PowerShell's team the most.

**Comment by sdwheeler** [comment]
@skycommand Thanks for understanding. I leave it as `wont-fix` because I really want us to fix the legacy content. But there just aren't the resources to do it properly.

Our strategy for developer content is:
- Cherry-pick the best bits of the legacy content to pull them into the main content
- Create new, cross-platform developer content
- Eventually retire/archive the legacy content

It is just going to take time to get there.
