### ISSUE TITLE
Installing the PowerShell Extension on Restricted Systems - incorrect switch?

### ISSUE THREAD

**Issue by Wooterino** [MicrosoftDocs/PowerShell-Docs#5053]
"You are prompted with "Do you want to run software from this untrusted publisher?" Type R to run the file."
https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems

Using "R" did not solve the allsigned problem. It started working properly after I ran the command and used "A" switch (Always Run), which then always trusts this MS certificate.

It was also said to use "Always run" by rjmholt in his last comment about this issue:
https://github.com/PowerShell/vscode-powershell/issues/1048#issuecomment-453685767

**Comment by sdwheeler** [comment]
@TylerLeonhardt Is this expected behavior?

**Comment by TylerLeonhardt** [comment]
@sdwheeler this should be changed to `A`, yes.

**Comment by sdwheeler** [comment]
@TylerLeonhardt Thanks. We will fix it.

**Comment by AndrewDavidoff** [comment]
This is incorrect assignment. I have no association with this project.

Please reassign.

Andrew
