### ISSUE TITLE
dsc extension versions out of date

### ISSUE THREAD

**Issue by josh-mclean** [MicrosoftDocs/PowerShell-Docs#5061]
It looks like azure vm dsc extension 2.80 is available, what OS's does it support?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 732fbb37-dc6d-de63-a106-05171b6554d5
* Version Independent ID: 3b9ed1f8-1650-c2b1-bd21-bef8359e0502
* Content: [Azure DSC Extension Version History - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/getting-started/azuredscexthistory?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/dsc/getting-started/azureDscexthistory.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/getting-started/azureDscexthistory.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@mgreenegit Can you update this information?

**Comment by chasewilson** [comment]
@josh-mclean  thank you for the feedback. There is already an [issue open](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3784) about this and I will be addressing this soon. I'm closing this Issue for now, but feel free to reach out if you have any questions or concerns
