### ISSUE TITLE
Add-type Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by MartinHBA** [MicrosoftDocs/PowerShell-Docs#5063]
Hello,
BACKGROUND:
I always used in Powershell System.Data.SqlClient. But now .NET team decided this will not receive any more feature updates. They decided to work on separate package Microsoft.Data.SqlClient following CORE strategy of loading needed packages. 
Now when I want to work with new namespace Microsoft.Data.SqlClient, I am able to download it using Nuget as package provider, I can do install-package with powershell, but I can't use namespace unless I do Add-Type, however this package has 3 other assemblies dependency (when using .NET46)
ISSUE:
add-type cannot add this assembly with all dependencies automatically. We need PowerShell to keep the pace with .NET and if they decide that future is separate packaging we need PowerShell to support it and PowerShell must be able to load desired package with all dependencies automatically. Otherwise it's dead end for Powershell and it's default .NET namespaces. Because .NET devs decided to go with CORE philosophy.

**Comment by sdwheeler** [comment]
@MartinHBA Product feeback like this should be filed in the PowerShell Source repo at https://github.com/PowerShell/PowerShell/issues/new/choose. 

I think this is a known issue. See the following issues.
- https://github.com/PowerShell/PowerShell/issues/3779
- https://github.com/PowerShell/PowerShell/issues/9599
