### ISSUE TITLE
Make it clear that $using is also needed for background jobs (not just in remoting)

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5068]
The`$using:` scope is needed not just in remoting, but also when running background jobs (both  with `Start-Job`  and `Start-ThreadJob`), and when using `ForEach-Object -Parallel`.

This fact should be mentioned in this help topic.

Also, the `See also` section should link to `about_Variables`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46fa829f-4c8c-f82b-24d0-22da319656be
* Version Independent ID: 7fe490eb-b9aa-66bf-0e58-4c8400321a9c
* Content: [about_Remote_Variables - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_variables?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Remote_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Remote_Variables.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by mklement0** [comment]
https://stackoverflow.com/a/60012780/45375 now contains the kind of summary that I wish the docs offered (it is a bit dense, but hopefully can serve as a starting point).

**Comment by Jawz84** [comment]
I'm working on a PR for this.
