### ISSUE TITLE
Clarify that a $using: reference is just a *value*, not a *variable object*

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5070]
> You can use local variables in remote commands

More accurately, a variable reference such as `$using:var` expands to the _value_ of variable `$var` from the caller's context.

That is, you do not get access to the caller's _variable object_, and can therefore not _assign_ to such variables.

Without this clarification, users may be tempted to think they can do something like the following, which fails:

```
# NOT supported.
PS> $foo = 'in'; Start-Job { $using:foo = 'out' } | Receive-Job -Wait -AutoRemove
The assignment expression is not valid. 
The input to an assignment operator must be an object that is able to accept assignments, such as a variable or a property.
```

That is, you cannot assign to `$using:` "variables" in an attempt to change their value in the caller's scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d918461b-f625-8e6d-f43d-3197075f1c06
* Version Independent ID: 7fe490eb-b9aa-66bf-0e58-4c8400321a9c
* Content: [about_Remote_Variables - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_variables?view=powershell-7)
* Content Source: [reference/7/Microsoft.PowerShell.Core/About/about_Remote_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7/Microsoft.PowerShell.Core/About/about_Remote_Variables.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by kamsalisbury** [comment]
I would like to add some clarifying verbiage, please assign to me.
