### ISSUE TITLE
-Exact switch description is misleading

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5073]
> Indicates that the match clause, if it is a string, must match exactly. If the match clause is not a string, this parameter is ignored.

The above is incorrect:

`-Exact` is the _default_ switch and effectively amounts to `-eq` comparison. There's nothing special about using it with strings.

Sadly, the name `-Exact` suggests case-sensitivity, which is _not_  the case:

```powershell
PS> switch -Exact ('foo') { 'FOO' { $true } } # same as *omitting* -Exact
True
```

If you do want case-sensitivity, you must (also) use `-CaseSensitive` and is only _that_ switch that is specific to strings (and also applies in combination with `-Regex` and `-Like`).

It would make sense to provide guidance along the following lines:

You never need `-Exact` - it only exists for symmetry with `-Regex` and `-Like`, as an explicit way to signal the intent to perform (case-insensitive-by-default) _equality_ comparison, as contrasted with wildcard and regex matching.

However, given the switch' misleading name, it is best not to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551d8f22-bebe-169c-4cc4-a6347a925088
* Version Independent ID: 557adc8a-2c41-5c92-ae2b-c22df22cb201
* Content: [about_Switch - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_switch?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Switch.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Switch.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
@mklement0 Thank you for the feedback. We do have a portion of the docs mentioning the default:

"If no parameters are used, Switch performs a case-insensitive exact match for the value. If the value is a collection, each element is evaluated in the order in which it appears."

It is still part of the switch statement syntax and I believe worth documenting, but I agree that I could add some clarity to your quoted section to ensure a user is explicitly aware that `-exact` is case in-sensitive and the default. However, it is still how the switch statement works that if the condition is an expression or a number, even if the `-explicit` switch is used, because the condition is not a string, it's ignored and should be know in my opinion.

It can also be good for clarity as PowerShell is pretty good at that. For instance in the following example, someone may be looking for specific strings and catching them with an implicit -exact and another user adjusting the code could read it and think it's looking for a Wildcard:

```PowerShell
switch ('foobar')
{
    'foobar'
    {
        'This is foobar'
    }
    'foo*'
    {
        'This is not foobar but we still need it for some strange reason'
    }
}
``` 
Vs:
```PowerShell
switch -Explicit ('foobar')
{
    'foobar'
    {
        'This is foobar'
    }
    'foo*'
    {
        'This is not foobar but we still need it for some strange reason'
    }
}
``` 

While it may not be often, it can be useful to be as explicit and clear as possible. 

@sdwheeler do you have anything to add or would like to see differently?

**Comment by mklement0** [comment]
Thanks, @chasewilson, but to be clear:

> even if the `-explicit` [I assume you meant `-exact`] switch is used, because the condition is not a string

Again, there's nothing string-specific here; it is ignored in the sense that **if you use `-Exact`** (without the conflicting `-Regex` / `-Wildcard` switches) **you've effectively needless opted-in to the default behavior (`-eq`-like, _irrespective of data type_).**

While sometimes making something this is implicit explicit for the sake of conceptual clarity, this is _not_ one of those cases, given the poor naming of the switch.

**Comment by mklement0** [comment]
Thank you, @chasewilson.

My apologies if I confused matters with my previous, since-deleted comment:
It was based on the - mistaken - assumption that `-Exact` does _not_ coerce non-string input to strings - in fact, it does.

This means:

* **`-Exact`  is _not_ ignored for _non-string_ input**: instead, it **_coerces_ non-string inputs to  strings**, as if the input had been used inside an expandable string (`"..."`); that is, `switch -Exact ($foo) ...` is effectively the same as `switch ("$foo") ...`
  
  * This needs to be documented as such.

  * Example: `switch -exact ($PSVersionTable) { 'System.Management.Automation.PSVersionHashTable' { $true } }` returns `$true`, because `"$PSVersionTable"` yields string `System.Management.Automation.PSVersionHashTable`

* Note that, similarly - and consistently -  **`-Wildcard` and `-Regex` too coerce inputs to strings**

---

The upshot is:

* `-Exact` needs to be documented as to-string-coercing.

* It needs to be made clear that `-Exact` doesn't actually mean _exact_, it means _literal_ comparison, but _without respect to case_, the same way that `-eq` operates with string operands.

  * For case-_sensitive_ comparison, `-CaseSensitive` must be used, which _even by itself_ triggers to-string coercion and implies `-Exact` in the absence of `-Regex` / `-Wildcard`.

---

To avoid confusion going forward due the poor naming of `-Exact`, the following would make sense (which would require changing the source code):

* Introduce `-Literal` as an alias for `-Exact` and primarily document the former, mentioning the latter only as a legacy alias.

**Comment by mklement0** [comment]
Let me attempt a pragmatic summary:

* `-Exact` only makes sense with input that either _already is a string_ or that you want _automatically converted to one_ (although it's probably clearer to make the to-string conversion explicit, e.g., `switch ("$foo") ...`, in which case `-Exact` isn't needed).

  * With already-a-string input, `-Exact` is never _needed_, but you can use it to make your intent explicit, namely to indicate that you're performing neither wildcard (`-Like`) nor regex (`-Regex`) matching.

* Despite its name, `-Exact` doesn't perform _exact_ string comparison, but the usual, case-sensitive (and culture-invariant) comparison that `-eq` also performs; think of it as `-Literal` or `-Equal` (with to-string coercion).
