### ISSUE TITLE
Documentation Issue: Remove-Computer Flag --PassThru not Recognized

### ISSUE THREAD

**Issue by ppdac** [MicrosoftDocs/PowerShell-Docs#5077]
# Documentation Issue

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-computer?view=powershell-5.1
- Issue affects the following content (check all that apply): 
  
  **Cmdlet reference & about_ topics**
  - [ ] Version 7 content
  - [ ] Version 6 content
  - [x] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):
Windows Server 2019 (Version 1809 Build 17763.6787)

## Detailed description of the issue
When trying to unjoin domain, I enabled --PassThru as the docs seem to imply that without it the command won't output the result. However, the `--PassThru` flag in documentation does not seem to apply to PS 5.1:

```
PS C:\Windows\system32> Remove-Computer -UnjoinDomainCredential (Get-Credential) --PassThru --Verbose

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Remove-Computer : A positional parameter cannot be found that accepts argument '--PassThru'.
At line:1 char:1
+ Remove-Computer -UnjoinDomainCredential (Get-Credential) --PassThru - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Computer], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveComputerCommand

PS C:\Windows\system32> Get-Host


Name             : ConsoleHost
Version          : 5.1.17763.592
InstanceId       : b0d99203-5730-48a9-a86c-7e2e5c43579d
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

```

**Comment by sdwheeler** [comment]
@ppdac The parameters are `-PassThru` and `-Verbose` with a single hyphen. Not `--PassThru`.

**Comment by ppdac** [comment]
Oops, thank you.
