### ISSUE TITLE
Easier on premises installation with a permalink to the latest stable release for each architecture

### ISSUE THREAD

**Issue by Bjego** [MicrosoftDocs/PowerShell-Docs#5080]
Hey guys,
I'm going to prepare an on premises "Azure Devops Agent" - I'm going to install powershell as well.
It would be super helpful, if you could provide a permanent link to the latest powershell version, which I can download via script. Maybe you could use Azure Artifacts for it.. :) 

https://docs.microsoft.com/de-de/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops

**Comment by sdwheeler** [comment]
Thanks for the feedback, but this is not a Docs issue. Please file a feature request at https://github.com/PowerShell/PowerShell/issues/choose
