### ISSUE TITLE
Reference How to Move Module to Offline Location and Use It

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/PowerShell-Docs#5081]
Please add a reference section with links to the correct articles about how to move the saved module to an offline environment and get it working there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6f4277e-46bd-cb23-90c9-1dfcb35d1d61
* Version Independent ID: 37ef46a2-ac77-f540-03c1-77a20a0d4fa6
* Content: [Save-Module (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/save-module?view=powershell-6)
* Content Source: [reference/6/PowerShellGet/Save-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/Save-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
All you do is copy the module to the offline system. How you do that depends on your environment. Once copied you run Install-Module and point at the saved folder.
