### ISSUE TITLE
-TargetName

### ISSUE THREAD

**Issue by chall324** [MicrosoftDocs/PowerShell-Docs#5086]
```
\ $ Test-Connection -Source [**************] -TargetName [***************]
Test-Connection : A parameter cannot be found that matches parameter name 'TargetName'.
At line:1 char:37
+ Test-Connection -Source vaxsrvdc-sc -TargetName vaxsrvpdc-bham
+                                     ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-Connection], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.TestConnectionCommand
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e68a7a-10e0-2ae5-b20a-517716367894
* Version Independent ID: 1cf2ccd2-f099-3f92-b698-36311baa0b81
* Content: [Test-Connection (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Test-Connection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Test-Connection.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
The correct parameter is `-ComputerName`. The example is correct but the description in the text needs to be fixed.
