### ISSUE TITLE
Install-PackageProvider example fails

### ISSUE THREAD

**Issue by marckassay** [MicrosoftDocs/PowerShell-Docs#5089]
```
C:\WINDOWS\system32> Install-PackageProvider -Name NuGet -Force
Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
```

```powershell
C:\WINDOWS\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18990
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

C:\WINDOWS\system32> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18990
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-6#get-the-latest-version-from-powershell-gallery)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you help?

**Comment by marckassay** [comment]
For what it's worth, I have created gists that contains output from:
- [`Get-PackageProvider`](https://gist.github.com/marckassay/6fd3ff8464b66b6168378903434e0eeb) 

- [`Get-Module -All`](https://gist.github.com/marckassay/a0b11e37d7fe14b6eac9ebafd7099d84)

(_Those commands are hyper-links_)

**Comment by SydneyhSmith** [comment]
@marckassay thanks for opening this issue, unfortunately this is a known issue that we are tracking in the Package Management repo [with this issue ](https://github.com/OneGet/oneget/issues/477)

**Comment by sdwheeler** [comment]
Closing this issue. Please follow the issue in https://github.com/OneGet/oneget/issues/477
