### ISSUE TITLE
Need documentation for WinCompat functionality

### ISSUE THREAD

**Issue by anmenaga** [MicrosoftDocs/PowerShell-Docs#5092]
# Summary of the new document or enhancement
As a user I need a document about WinCompat functionality in PS Core so that I can use Windows PowerShell modules in PS Core.

Details of requested document:

- Proposed title: Importing Windows PowerShell modules in PowerShell Core
- Propose location in the TOC: somewhere close to Import-Module docs
- Target audience: PS Core users that need to use Windows PS modules
- Purpose or scenario: Importing Windows PowerShell modules in PowerShell Core

**Comment by doctordns** [comment]
I would argue that a document for PowerShell Core (aka PowerShell 6.x), BUT one for PowerShell 7.  is certainly important. I also think a canonical list of commands/modules supported with PowerShell 5.x that are not supported directly, which ones can be used fully by way of Windows Compatability module, and those that are not going to work in PowerShell 7 (eg WSUS).

**Comment by sdwheeler** [comment]
@joeyaiello Is working on this. We intend to have this document when we release PowerShell v7.

**Comment by anmenaga** [comment]
Also will need to document another breaking change related to this:
`-PSVersion` parameter on `Start-Job` cmdlet previously was ignored (was always starting PS Core `pwsh`)
After this change, on Windows, `Start-Job -PSVersion 5.1` will start a Windows PowerShell process (`powershell.exe`)

**Comment by joeyaiello** [comment]
@anmenaga I want to provide a table to you this month that outlines which modules are natively compatible vs. requiring this feature. 

Don't block behavioral content on me, but it should probably be tied in to this doc.

**Comment by joeyaiello** [comment]
@anmenaga if you're around today, can you give this one a first-pass? I'm happy to do a cleanup/additive run after that

**Comment by anmenaga** [comment]
@joeyaiello yup, doing it right now.
