### ISSUE TITLE
Starting PowerShell Core

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/PowerShell-Docs#5093]
I believe PowerShell Core (version 6 and above) must be started with the command "pwsh.exe", or am I wrong? Can you adjust the documentation on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda35299-e29f-3773-ebf0-3f2118b19268
* Version Independent ID: 26ae945f-3dec-bb1c-3565-00c64926d15a
* Content: [Starting Windows PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/starting-windows-powershell?view=powershell-6)
* Content Source: [reference/docs-conceptual/getting-started/Starting-Windows-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/getting-started/Starting-Windows-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
That page references WINDOWS PowerShell, which is PowerShell.exe.  
Powershell Core/PowerShell 7 is a different product with a different executable name.

**Comment by sdwheeler** [comment]
@doctordns is correct. **Windows PowerShell** is `powershell.exe`. **PowerShell Core** is `pwsh`. With the release of PowerShell v7, the name and brand will just be **PowerShell**. The fact is documented. But we are still working on our rebranding effort to make these changes in the documentation the default.

**Comment by cveld** [comment]
If you really want to document the instruction in order to start PowerShell Core somewhere else; then I would advise you to include a reference on this page. And just for you to know, at the top of the page I have selected version 6 of PowerShell. Quite confusing :-)

**Comment by doctordns** [comment]
A couple of points?
1. The article IMHO does a good job identifying WINDOWS PowerShell - although the opening sentence could begin with _Windows_ Powershell and not PowerShell. 
2. @CVELD point suggests that this document could usefully have a small note added along the lines:

This article describes Windows PowerShell and not the open-source cross-platform product PowerShell 7.  PowerShell 7 is intended to replace Windows PowerShell as the automation tool and platform for IT Professionals. For more details on PowerShell 7 see xxx, and for details on Starting PowerShell 7 see yyy

If that would help I could make those edits.

**Comment by sdwheeler** [comment]
The longer term plan (for the PSv7 release) is to rebrand and refocus the content to be PowerShell 7 first and link out to legacy articles for Windows PowerShell.

However, I would welcome a PR from anyone who would like to submit one. I agree having a link to the PowerShell Core articles would be useful for the short term.
