### ISSUE TITLE
Get-Container?

### ISSUE THREAD

**Issue by marckassay** [MicrosoftDocs/PowerShell-Docs#5095]
In the description for ContainerId parameter, it mentions about Get-Container. However, it seems that this cmdlet does not exist. The only reference I found was in the, now deprecated, Docker-PowerShell module.

If changes are needed; this boilerplate description can be found by: Get-Command -ParameterName ContainerId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295c37c0-2feb-76bf-427a-b5f10b4930c9
* Version Independent ID: ccdd5a9c-5230-20de-db28-39e53a795ce3
* Content: [New-PSSession (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/New-PSSession.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Here is how you get the ContainerId.

```
docker run -it microsoft/windowsservercore powershell
docker ps --no-trunc # to get full container id
Enter-PSSession -ContainerId $theContainersId
```

**Comment by marckassay** [comment]
@sdwheeler Now I understand, thanks!

For anyone, Docker needs to be running for Window Containers, I believe. In the Docker Desktop context menu, select "Switch to Windows Containers…" if you are currently running Docker with Linux Containers. And also, it took me about ~30 mins to pull and run, using the code below. Perhaps using Nano is a faster alternative.

@sdwheeler also, why is 'powershell' needed for this to work and not 'pwsh'? And also, I don't think that repo exists anymore, as it seems that Microsoft is using 'mcr' prefix (unless that is an internal container registry for Microsoft). So, I needed up using the following code to match my laptop's Window version (since that is mentioned in some container descriptions by Microsoft on Docker Hub):
```
docker pull mcr.microsoft.com/powershell:windowsservercore-1903
docker run -it mcr.microsoft.com/powershell:windowsservercore-1903 powershell
$ContainerId = docker ps --filter "ancestor=mcr.microsoft.com/powershell" --format "{{.ID}}" --no-trunc
Enter-PSSession -ContainerId $ContainerId
```

**Comment by doctordns** [comment]
One issue is that you can not, presently, install Docker inside Windows Server 2019 using just PWSH. It just does not work. This has been reported and, IIRC, is an issue that is not likely to get fixed prior to PWSH 7 being released.
