### ISSUE TITLE
Which version does this apply to?

### ISSUE THREAD

**Issue by JakeQZ** [MicrosoftDocs/PowerShell-Docs#5107]
I get the following error:

> The term 'Get-Clipboard' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c39aad74-e9bc-5deb-9232-a7809ddd5334
* Version Independent ID: 05ac0026-b61e-929d-3760-a9a5d2bd4327
* Content: [Get-Clipboard (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-clipboard?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Get-Clipboard.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-Clipboard.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
You were reading the v5.1 version of the documentation. So that is what it applies to.

This cmdlet is not available in PowerShell 6. It is being added back into the next release of PowerShell 7.
