### ISSUE TITLE
Clarify that -AllMatches cannot be combined with -SimpleMatch

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5108]
`-AllMatches` cannot be meaningfully combined with `-SimpleMatch`, because `-SimpleMatch` doesn't capture matches at all (the `.Matches` property is `$null`).

In effect, `-AllMatches` is quietly ignored if you also specify `-SimpleMatch`.

That fact is worth mentioning.

On a related note:

https://github.com/PowerShell/PowerShell/issues/11091 asks for `Select-String` to declare the parameters as mutually exclusive, which would make it obvious to users that these parameters cannot be combined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53576140-f2d3-1b67-b55e-4ca74e92d8a2
* Version Independent ID: 86cda1f5-a5bf-45bd-d7d4-aa1a16134c7d
* Content: [Select-String (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7)
* Content Source: [reference/7/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7/Microsoft.PowerShell.Utility/Select-String.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by iSazonov** [comment]
I pulled PR to fix PowerShell behavior.

I think the docs could be updated for old PowerShell versions too.

**Comment by mklement0** [comment]
Good point, @iSazonov.

A thought as to why users may be tempted to use `-AllMatches` needlessly (both with and without `-SimpleMatch`):

Even though the `-AllMatches` behavior is clearly documented (sans the warning re combination with `-SimpleMatch`, which is what this issue is about), the generic name of the switch can make users mistakenly think that `-AllMatches` is necessary to find all matches in a _file_ (which happens by default), whereas in reality it is used to find all matches on each _line_.

**Comment by mklement0** [comment]
It would also help if the `-SimpleMatch` parameter description pointed out that if capturing of matches is desired (for instance, to capture the exact case of a match and/or with `-AllMatches`, to count the number of matches)), `-Pattern` must be used, with the literal search string escaped with `[regex]::Escape()`.

For instance:

```powershell
PS> 'FO|O bar' | Select-String -Pattern ([regex]::escape('fo|o')) | ForEach-Object { $_.Matches.Value }
FO|O
```
