### ISSUE TITLE
-Include parameter trailing asterisk with -Path

### ISSUE THREAD

**Issue by Hrxn** [MicrosoftDocs/PowerShell-Docs#5126]
See Example number four on the *Get-ChildItem* documentation page.

> When the Include parameter is used, the Path parameter needs a trailing asterisk (`*`) wildcard to specify the directory's contents. For example, `-Path C:\Test\*`.

Is this information still correct?
Because it seems to work if I only specify "`E:\Test\`", for example, without the trailing asterisk.
Seems to work, don't know why. Maybe this is a bit outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afee1cf3-2e19-4a97-3794-815d54ef0097
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-6#examples)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by Hrxn** [comment]
Ah, wait.

I think I've figured it out.

It's working when using
`Get-ChildItem -LiteralPath "E:\Test\" -Include "*Example*"`

Should be mentioned, I think.
Also, if I do this:
`Get-ChildItem -Path "E:\Test\*" -Include "V*"`

I don't get a directory starting with "V" inside that path.

But
`Get-ChildItem -LiteralPath "E:\Test\" -Include "V*"`
works, I get the directory starting with the char "V" as well as the file.

**Comment by sdwheeler** [comment]
Yes, it is required with `-Path`.

**Comment by carnotan** [comment]
No, it is not. And it's not even working consistently within the same system. Within the same machine, one domain user returns the expected according to documentation (nothing)

<code>Get-ChildItem "\\serv-f001\FichCUC\Pre2017\cargados\" -Include "*" </code>

But another domain user, the one logged at the machine, returns the contents of the folder : 


<code> 

PS C:\Users\expl3> Get-ChildItem "\\serv-f001\FichCUC\Pre2017\cargados\" -Include "*"


    Directorio: \\serv-f001\FichCUC\Pre2017\cargados


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       04/04/2020      0:00         230173 20200403060017332582.xml
-a----       06/04/2020      6:02         230046 20200405123711635466.xml
-a----       06/04/2020      6:04         229865 20200405133830248164.xml
-a----       14/02/2020      3:00         212002 20200214012807049166.xml
-a----       14/02/2020      3:00         213448 20200214012827252980.xml
-a----       14/02/2020      3:00         209139 20200214012847430240.xml
-a----       14/02/2020      3:00         222520 20200214012907624926.xml
-a----       14/02/2020      3:00         212369 20200214012927858585.xml
-a----       14/02/2020      3:00         206940 20200214012948036735.xml
-a----       14/02/2020      3:00         215495 20200214013008230646.xml
-a----       14/02/2020      3:00         209835 20200214013028502902.xml
-a----       14/02/2020      3:00         211384 20200214013048761406.xml
-a----       14/02/2020      3:00         204116 20200214013108959460.xml
-a----       14/02/2020      3:00         213491 20200214013129170849.xml
-a----       14/02/2020      3:00         207452 20200214013149358241.xml
</code>

Something is broken here. Or I'm not understanding how this should behave.

**Comment by 20-EverGreen-2** [comment]
I have same problems.

```
PS G:\> Get-ChildItem -LiteralPath "G:\" -Exclude "System Volume Information" -Hidden


    Directorio: G:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-rhs-        08/12/2021      7:28                boot
d-rhs-        08/12/2021      7:28                EFI
d-rhs-        27/09/2020     23:36                GRUB
d-rhs-        26/11/2015      3:25                I386
d-rhs-        14/01/2022     11:28                IMG
d--hs-        01/12/2010      8:23                System Volume Information  <<--- WTF??? I filtered above
-a-hs-        31/03/2020     14:16             48 BOOTDISK.KEY
-arhs-        30/10/2015     16:19         400228 bootmgr
-arhs-        30/10/2015     16:19        1147736 bootmgr.efi
-arhs-        31/03/2009     22:20         217769 grldr
-arhs-        31/03/2009     22:20           9216 grldr.mbr
-a-hs-        31/03/2020     14:16            164 _bootDisk.ini
```

```
PS G:\> Get-ChildItem -Path "G:\*" -Exclude "System Volume Information" -Hidden


    Directorio: G:\boot


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-hs-        03/04/2020     12:09          65536 bcd.LOG
-a-hs-        04/08/2016     21:15              0 bcd.LOG1
-a-hs-        04/08/2016     21:15              0 bcd.LOG2


    Directorio: G:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-hs-        31/03/2020     14:16             48 BOOTDISK.KEY
-arhs-        30/10/2015     16:19         400228 bootmgr
-arhs-        30/10/2015     16:19        1147736 bootmgr.efi
-arhs-        31/03/2009     22:20         217769 grldr
-arhs-        31/03/2009     22:20           9216 grldr.mbr
-a-hs-        31/03/2020     14:16            164 _bootDisk.ini
```

^--- MISSING A LOT OF DIRECTORIES

```
PS G:\> Get-ChildItem -Path "G:\*" -Hidden


    Directorio: G:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-rhs-        08/12/2021      7:28                boot
d-rhs-        08/12/2021      7:28                EFI
d-rhs-        27/09/2020     23:36                GRUB
d-rhs-        26/11/2015      3:25                I386
d-rhs-        14/01/2022     11:28                IMG
d--hs-        01/12/2010      8:23                System Volume Information
-a-hs-        31/03/2020     14:16             48 BOOTDISK.KEY
-arhs-        30/10/2015     16:19         400228 bootmgr
-arhs-        30/10/2015     16:19        1147736 bootmgr.efi
-arhs-        31/03/2009     22:20         217769 grldr
-arhs-        31/03/2009     22:20           9216 grldr.mbr
-a-hs-        31/03/2020     14:16            164 _bootDisk.ini
```

Very similar command without -Exclude get all directories. 


I think this cmdlet needs more test of developers this cmdlet is very BUGY!!!

**Comment by sdwheeler** [comment]
@20-EverGreen-2 
Please file an issue at https://aka.ms/psfeedback
