### ISSUE TITLE
Can I use -like and -or together?

### ISSUE THREAD

**Issue by RamazanInce** [MicrosoftDocs/PowerShell-Docs#5127]
instead of this two lines
           if($service -like "*&lt;!DOCTYPE HTML&gt;*" ) {"UNIQUE_EXCEPTION: Incorrect Credentials"; exit(0)}
             elseif ($service -like "*Invalid automation secret*") {"UNIQUE_EXCEPTION: Incorrect Credentials"; exit(0)}

I want to use 

if($service -like {"*&lt;!DOCTYPE HTML&gt;*" -or "*Invalid automation secret*"}) {"UNIQUE_EXCEPTION: Incorrect Credentials"; exit(0)}

how Can I do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41417680-da77-6c19-bbd0-522e694e7ff0
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
First off `-like` is for matching with wildcard patterns. Since you are not using wildcards, it is the same as using `-eq`. If you want to use the `-or` then you can't do it that way. But there is a way.

```
if ($service | select-string -pattern "\<!DOCTYPE HTML\>", "Invalid automation secret") { 
  "UNIQUE_EXCEPTION: Incorrect Credentials"
  #exit(0)
}
```
