### ISSUE TITLE
Minimum User Rights Assignment Needed

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/PowerShell-Docs#5128]
Please add details on least-privilege rights assignment needed to run a PowerShell job, especially for least-privilege domain-user, MSA, or gMSA account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63f85ff-2bf2-10bd-e6f8-63652a21aff6
* Version Independent ID: 8a65651d-484d-ff29-55fb-6d76489164f5
* Content: [about_Remote_Jobs - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_jobs?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
There are no specific rights required to run a job. The required permissions depends on the ACLs required to access the remote system and the cmdlets being used. As long has you have rights to access the system remotely you can create the job. The code running on the remote system runs in your user context, so if the script code accesses some resource on the remote system, you have to have rights to that resource.
