### ISSUE TITLE
RHEL 8 / CentOS 8 support

### ISSUE THREAD

**Issue by MarcoJanse** [MicrosoftDocs/PowerShell-Docs#5129]
When will CentOS 8 and RHEL 8 be supported for PowerShell Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a43d3-9571-389c-56ab-7d42a53bf5b1
* Version Independent ID: c138e6a8-fd80-bd64-25ac-24e774e09421
* Content: [PowerShell Core Support Lifecycle - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-6)
* Content Source: [reference/docs-conceptual/PowerShell-Support-Lifecycle.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Support is coming in PSv7. Documentation will be updated at release.
