### ISSUE TITLE
Doc: `-AsPlainText` switch added to `ConvertFrom-SecureString`

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#5136]
https://github.com/PowerShell/PowerShell/pull/11142 adds a `-AsPlainText` switch to `ConvertFrom-SecureString` to convert a SecureString back to plain text.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by rjmholt** [comment]
Closed in https://github.com/MicrosoftDocs/PowerShell-Docs/pull/5300#issuecomment-573222489
