### ISSUE TITLE
Question: Is PowerShell ISE actually no longer in developement?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/PowerShell-Docs#5138]
Hello, I see it being said on a lot of blogs, which tend to favor VSCode, example:
https://adamtheautomator.com/how-to-make-visual-studio-code-look-and-behave-like-the-powershell-ise/

But I'm struggling to find any official statement to back this.  Are you able to confirm whether or not the ISE is no longer being worked on? 

The reason I ask is that the debugging and integrated console experiences are still night and day better with ISE.  I do like VS Code, but the PowerShell extension pales in comparison to ISE for stability and performance, but most notably with debugging and the integrated console.  VS Code wins in other areas such as PSScriptAnalyzer, for example, but where there is overlap, PowerShell ISE seems to win.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91aaa090-5d02-dfce-f23d-4d37925175bb
* Version Independent ID: 5220c32c-b163-7cef-860b-194ea52d646d
* Content: [Introducing the Windows PowerShell ISE - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/ise/introducing-the-windows-powershell-ise?view=powershell-6)
* Content Source: [reference/docs-conceptual/components/ise/Introducing-the-Windows-PowerShell-ISE.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/ise/Introducing-the-Windows-PowerShell-ISE.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by mklement0** [comment]
From https://docs.microsoft.com/en-us/powershell/scripting/components/ise/introducing-the-windows-powershell-ise#support (emphasis added):

"
Support

The ISE was first introduced with Windows PowerShell V2 and was re-designed with PowerShell V3. 

The  ISE is **supported in all supported versions of Windows PowerShell up to and including Windows PowerShell V5.1.** 
The ISE, however, is **in maintenance mode and no new features are likely to be added.** 
Additionally, there is **no support for the ISE with PowerShell v6 and beyond.** 
Users wanting a graphical tool with which to manage PowerShell scripts, etc, should **consider Visual Studio Code.**
"

**Comment by JeremyTBradshaw** [comment]
Thank you very much.

**Comment by joeyaiello** [comment]
The PowerShell ISE is no longer in active feature development, but as a shipping component of Windows, it will continue to be officially supported for security and high-priority servicing fixes. We currently have no plans to remove the ISE from Windows.

**Comment by joeyaiello** [comment]
Thanks for the response, @mklement0! I hit "Comment" before I saw your update. 

@sdwheeler still wants to make sure we document this in the docs, so I'm reopening here.

**Comment by JeremyTBradshaw** [comment]
Thanks again.  Glad the official status of ISE is still OK.
