### ISSUE TITLE
Effect on Domain Controller

### ISSUE THREAD

**Issue by SanFlan** [MicrosoftDocs/PowerShell-Docs#5139]
When renaming a Domain Controller with Rename-Computer do you still have to update the FRS  Replication member object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126b9faa-4616-b4f9-7038-a20867369e6b
* Version Independent ID: 8b3bed2f-95f1-6840-d27f-2209ca737095
* Content: [Rename-Computer (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-computer?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Rename-Computer.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Rename-Computer.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
`Rename-Computer` only renames the machine and nothing else.
