### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by dazlari** [MicrosoftDocs/PowerShell-Docs#5141]
For a page that recommends writing help with Examples, I find it ironic that the help writing page has no examples.
&lt;Brain Explosion&gt;
daz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f3a4141-3fb8-8df7-82e9-51df8f1e5840
* Version Independent ID: c84b5c58-e605-6056-c779-01ee1bf0510b
* Content: [Writing Help for Windows PowerShell Modules - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/writing-help-for-windows-powershell-modules?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/developer/module/writing-help-for-windows-powershell-modules.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/module/writing-help-for-windows-powershell-modules.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is an introductory article that is just the first in a series of articles you must read to understand the help system in PowerShell. Continue reading the rest of the articles in the Table of Contents in that section.
