### ISSUE TITLE
Documentation relating to upgrading PowerShell

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/PowerShell-Docs#5145]
There is zero information on upgrading a PowerShell install. It would be useful to include this in the Installation guidance pages

For Windows,
- Should you simply download and run a new MSI?
- What it you are using the newer MSIX packages?
- Can this be done from the CLI?
- What about different version for v6 and v7? 
- Other method of install, do they require different upgrade procedures?

For other OS:
- Re-install the package?
- Use a package manager?

etc....

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell Core on Windows - PowerShell](https://docs.microsoft.com/en-gb/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
For best results, you should use the same install method (MSI, MSIX, CLI, package manager etc.) to upgrade an installed version of PowerShell. Each method can install PowerShell in a different location. So the same method should be used for upgrades.

When you install a package that has the same Major Version but a higher Minor Version than the current install, the installer upgrades the current installed version. When you install a package that has a higher Major Version, the installer installs the new version side-by-side with the previous version. So you can continue to run PowerShell v6.x or PowerShell 7.x.

**Comment by sdwheeler** [comment]
TO DO Items
- Explain results of different install methods
- Explain the upgrade experience
- Document manual uninstall steps

**Comment by cseas** [comment]
I installed PowerShell Core using the below command:
```sh
dotnet tool install --global PowerShell
```

How do I replace the default PowerShell with PowerShell Core?

And how do I add PowerShell Core as an option to the Windows Terminal?

**Comment by doctordns** [comment]
Assuming it's WIndows 10 click start, then type PWSH and up it shoul come,

**Comment by gitfool** [comment]
> Explain results of different install methods

@sdwheeler I'm leaning towards using the msix install, but unsure of the differences / implications. (I'm on Windows 10.)

Also, will there be an auto-updating distribution via Microsoft Store, like with Windows Terminal?

**Comment by sdwheeler** [comment]
The MSIX package, once it is available, will be in the Microsoft Store.

**Comment by sdwheeler** [comment]
See related https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5538

**Comment by sdwheeler** [comment]
Reopening - linked in error from unrelated PR

**Comment by CraigHead** [comment]
How does one remember how they installed it? Is there a table of folders for referencing "how it was installed" so that it can be upgraded correctly?
