### ISSUE TITLE
Link labels have inconsistent casing, list is sorted case-sensitively

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5153]
Most link labels are camel-cased (e.g., `about_Variable_Provider`), whereas a few are all-lowercase (e.g., `about_simplified_syntax`).

Since the sorting of the links is apparently case-_sensitive_, the all-lowercase link labels do not appear where they're expected to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 438b4b5d-65ae-9e14-744c-c956d4521bea
* Version Independent ID: 10376fbc-664d-e09d-d6ca-9a4a610dedba
* Content: [About](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/?view=powershell-7)
* Content Source: [reference/7/Microsoft.PowerShell.Core/About/About.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7/Microsoft.PowerShell.Core/About/About.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
reference\5.1\Microsoft.PowerShell.Core\About\about_desiredstateconfiguration.md
reference\5.1\Microsoft.PowerShell.Core\About\about_dsclogresource.md
reference\5.1\Microsoft.PowerShell.Core\About\about_hidden.md
reference\5.1\Microsoft.PowerShell.Core\About\about_logical_operators.md
reference\5.1\Microsoft.PowerShell.Core\About\about_pipelines.md
reference\5.1\Microsoft.PowerShell.Core\About\about_simplified_syntax.md
reference\5.1\Microsoft.PowerShell.Core\About\about_windows_powershell_5.1.md
reference\6\Microsoft.PowerShell.Core\About\about_hidden.md
reference\6\Microsoft.PowerShell.Core\About\about_logical_operators.md
reference\6\Microsoft.PowerShell.Core\About\about_pipelines.md
reference\6\Microsoft.PowerShell.Core\About\about_pwsh.md
reference\6\Microsoft.PowerShell.Core\About\about_simplified_syntax.md
reference\7\Microsoft.PowerShell.Core\About\about_hidden.md
reference\7\Microsoft.PowerShell.Core\About\about_logical_operators.md
reference\7\Microsoft.PowerShell.Core\About\about_pipelines.md
reference\7\Microsoft.PowerShell.Core\About\about_pwsh.md
reference\7\Microsoft.PowerShell.Core\About\about_simplified_syntax.md
