### ISSUE TITLE
"Special Operators" section needs an entry - and name - for parentheses

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5154]
Parentheses (`(...)`) should be considered an operator in their own right, and therefore be given a _name_ and be _described_.

Note: The most logical name would be _subexpression operator_, but that name is already taken by `$(...)` (for which it is an unfortunate name). Perhaps _grouping operator_ is an option.

As in other languages, `(...)` serves to override operator precedence in expressions (e.g., `(1 + 2) / 3`)

However, in PowerShell additional behaviors apply, which aren't obvious and require documenting:

* `(...)` allows you to let output from a _command_ participate in an expression; e.g. (`(Get-Item *.txt).Count -gt 10`)

* When used as the first segment of a pipeline, wrapping `(...)` around a command or expression:
  * invariably causes _enumeration_ of the expression result
  * if the `(...)` wrap a _command_, it is _run to completion first_, with all output _collected in memory_, before the results are sent through the pipeline.

* Before PowerShell 7, wrapping a command in `(...)` invariably caused `$?` to be rest to `$true`, even if the enclosed command itself set `$?` to `$false`; e.g., `(Get-Item /Nosuch); $?` unexpectedly yields true in Windows PowerShell and PowerShell Core 6.x

It is also worth making clear that in most cases use of `(...)` is sufficient and preferable to `$(...)`, especially given that the latter has side effects - see #5031

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b7a29c-a7a8-cd5c-19c6-eb97fb16ec12
* Version Independent ID: 5fcd4430-a6b8-0438-73c9-29749b804323
* Content: [about_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7)
* Content Source: [reference/7/Microsoft.PowerShell.Core/About/about_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7/Microsoft.PowerShell.Core/About/about_Operators.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The old PowerShell Language Specification document referred to this as "Grouping Parentheses". So I think "grouping operator" would be appropriate. See §7.1.1
