### ISSUE TITLE
Why doesn't ThreadJob Module appear in the module explorer?

### ISSUE THREAD

**Issue by Silver-Fang** [MicrosoftDocs/PowerShell-Docs#5155]
https://docs.microsoft.com/en-us/powershell/module/threadjob
This module is invisible at https://docs.microsoft.com/en-us/powershell/module
Newcomers who don't know its existence won't have a chance to encounter it.

**Comment by sdwheeler** [comment]
This is fixed now. Fixed configuration error in moniker mapping and rebuilt the indexes for the module browser.
