### ISSUE TITLE
Samples in this documentation do not work by default either on Windows 7 or Windows 10

### ISSUE THREAD

**Issue by oco27** [MicrosoftDocs/PowerShell-Docs#5156]
Samples in this documentation do not work by default either on Windows 7 or Windows 10.

"The WMI command-line tool (Wmic) is deprecated. Use PowerShell cmdlets instead."

My goal is to anticipate deprecation of WMIC, but it looks like, so far, that PowerShell cmdlets is just a complicated way to do simple things...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db0d2c60-0cf8-37bd-9cbb-6dc84b8fecb4
* Version Independent ID: f6b2ad17-db47-ce18-ec97-ca44466bf534
* Content: [Collecting Information About Computers - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/samples/collecting-information-about-computers?view=powershell-6)
* Content Source: [reference/docs-conceptual/samples/Collecting-Information-About-Computers.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Collecting-Information-About-Computers.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
PowerShell is much. much more than a simple replacement to WMIC. WMIC was a command-line tool to look into WMI. PowerShell allows you to manage storage, networking, AD, Exchange and a whole lot more. WMIC is a great command-line tool but doesn't scale. PowerShell is designed to scale easily into the enterprise.

 I suggest taking a look at  Don Jone's book Learn Windows PowerShell in a Month of Lunches. 

Don's advice: Learn PowerShell or Learn golf.

**Comment by oco27** [comment]
It looks like i have installed powershell 6 long time ago and was using that instead of default one...

**Comment by sdwheeler** [comment]
@oco27 Which examples don't work for you? These should all work in PowerShell 5.1 or PowerShell 6.

**Comment by oco27** [comment]
"Get-CimInstance -ClassName Win32_Desktop -ComputerName" in a PowerShell console for instance (first example in the page) do not work on Windows 7 and Windows 10.

In fact, it was "Get-WmiObject win32_bios" that do not work only on powershell 6.0.0 on Windows 7 from this other page : https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-powershell-1.0/ee176860(v=technet.10)?redirectedfrom=MSDN.

This is what i will probably use for my case.

Maybe i should really follow the advice and learn golf ;-) I am not a sysadmin so i rarely need PowerShell, except today !

**Comment by sdwheeler** [comment]
The cmdlets with WMI in the name were removed from PowerShell 6 and are no longer supported. The WMI functionality is provided by the CIMCmdlets module.

The example you cited works on my Windows 10 machine. Note, in your comment above you are missing the trailing period after `-ComputerName`. The correct command is:

```
Get-CimInstance -ClassName Win32_Desktop -ComputerName .
```
