### ISSUE TITLE
-EscapeHandling is not recognized as a parameter

### ISSUE THREAD

**Issue by diering5** [MicrosoftDocs/PowerShell-Docs#5160]
# Support Question
I am writing a powershell script which reads in a json file, I manipulate it, and then I write it back to a json file. The problem is that when I write the values to a file the html characters are not escaped. For example, the character ">" is getting written as "\u003e".

When converting to json I tried using this in my code:
$jsonOut = $navJson | ConvertTo-Json -Depth 50 -EscapeHandling EscapeHtml

However, I keep receiving the error:
A parameter cannot be found that matches parameter name 'EscapeHandling'

This is very confusing because it is clearly a parameter based on the Microsoft docs:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6

**Comment by sdwheeler** [comment]
That parameter does not exist in PowerShell 5.1. You are looking at the help for PowerShell 6.
