### ISSUE TITLE
No link to Microsoft.PowerShell.Commands.BasicHtmlWebResponseObject

### ISSUE THREAD

**Issue by dlech** [MicrosoftDocs/PowerShell-Docs#5161]
The Outputs section just says "Microsoft.PowerShell.Commands.BasicHtmlWebResponseObject", but there is no link to any information on what this means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1103bfa9-3680-14bb-2992-b992ff3c2297
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6#outputs)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.basichtmlwebresponseobject?view=pscore-6.2.0

**Comment by sdwheeler** [comment]
Duplicate issue - Tracking this in #5221
