### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by pierrecoach** [MicrosoftDocs/PowerShell-Docs#5168]
I copied the statements as they are in the page and at the command Start-DscConfiguration I get an error "The client cannot connect to the destination specified in the request". 
Troubleshooting as first steps is not the best way to encourage using DSC!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6899bee9-ef7a-7447-0807-62ab30ae9606
* Version Independent ID: 6160bf0d-b5bb-003d-df4c-a42e590d3866
* Content: [Get started with Desired State Configuration (DSC) for Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/getting-started/wingettingstarted?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/dsc/getting-started/winGettingStarted.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/getting-started/winGettingStarted.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @pierrecoach. Thanks for the feedback. In copying the snippets, did you edit any of the content? 
I don't have any issues running the code as is in a windows 10 environment. Can you tell me a little about the environment you ran the snippets in?

**Comment by pierrecoach** [comment]
Dear,

My computer was missing the remoting
Set-WSManQuickConfig fixed it, but let me suggest to add (if only in comment) the command in the example code.

Greetings


Pierre

________________________________
De : Chase Wilson <notifications@github.com>
Envoyé : lundi 9 décembre 2019 22:51
À : MicrosoftDocs/PowerShell-Docs <PowerShell-Docs@noreply.github.com>
Cc : Pierre <pierre169518185@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/PowerShell-Docs] Does not work (#5168)


Hi @pierrecoach<https://github.com/pierrecoach>. Thanks for the feedback. In copying the snippets, did you edit any of the content?
I don't have any issues running the code as is in a windows 10 environment. Can you tell me a little about the environment you ran the snippets in?
