### ISSUE TITLE
more information regarding tags. 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/PowerShell-Docs#5170]
Note: The referenced article ( New-ModuleManifest) only describes that Tags are an array of strings... 
that is not to much to go on in order to understand the intended use.

can you add some better & clear examples and explain the intent ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532d1052-9a1e-04e9-bc21-9f0f64a23f29
* Version Independent ID: ec82c5c6-2d59-f274-f043-e645493a5aa1
* Content: [Write-Information (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-information?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Write-Information.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Write-Information.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The tags are used by the PowerShell Gallery. See https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/package-manifest-affecting-ui?view=powershell-6#tag-details

**Comment by Josverl** [comment]
thanks for the clarification, 
that would be quite useful to add to the article.
