### ISSUE TITLE
Doc: Stop-Computer for non-Windows

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#5171]
# Documentation Issue

@brendandburns implemented `Stop-Computer` for non-Windows, we need to doc the differences where most parameters are Windows only

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
@SteveL-MSFT Need details about which parameters are Windows-only and other platform-specific details (eg. depency on native exes?).

**Comment by SteveL-MSFT** [comment]
`Stop-Computer` on non-Windows doesn't have any parameters or switches.  It depends on the `/sbin/shutdown` command.
