### ISSUE TITLE
Pattern - what are the defaults? Examples?

### ISSUE THREAD

**Issue by pierrecoach** [MicrosoftDocs/PowerShell-Docs#5172]
Is the regex by default case sensitive or not?
Which options should be used to make the pattern case sensitive or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfe380d4-17fd-9850-6caf-79854fa4fd7f
* Version Independent ID: eaf9b582-ab99-8a52-65f7-f775f2937983
* Content: [ValidatePattern Attribute Declaration - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/validatepattern-attribute-declaration?view=powershell-6)
* Content Source: [reference/docs-conceptual/developer/cmdlet/validatepattern-attribute-declaration.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/validatepattern-attribute-declaration.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-6#validatepattern-validation-attribute
