### ISSUE TITLE
Document the ProviderCmdlet property

### ISSUE THREAD

**Issue by george-chakhidze** [MicrosoftDocs/PowerShell-Docs#5174]
What is `ProviderCmdlet` property used for? Comment from source code says this:

```
    /// Attributes implemented by a provider can use:
    ///     [OutputType(ProviderCmdlet='cmdlet', typeof(...))]
    /// To specify the provider specific objects returned for a given cmdlet.
```

Is it for public consumption or internal usage only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a990181-b9f8-d212-41dd-afbe0b6442ce
* Version Independent ID: 63e16527-901e-cff6-5f7c-8cf0ae6a2304
* Content: [about_Functions_OutputTypeAttribute - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by SteveL-MSFT** [comment]
This attribute is for providers working with cmdlets.  It indicates the outputtype for a given provider operation (like get-item, or push-location).  You can see examples here: https://github.com/PowerShell/PowerShell/search?q=providercmdlet&unscoped_q=providercmdlet
