### ISSUE TITLE
How do you import a prerelease version of a module?

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/PowerShell-Docs#5177]
The `Install-Module` cmdlet allows you to install a prerelease version of a module by using `-AllowPrerelease` and `-RequiredVersion`, but the `Import-Module` does not have the `-AllowPrerelease` parameter, and when trying to use a prerelease version number in the `-RequiredVersion` it throws an error like the following:

> FormatException: Input string was not in a correct format.
>     PSInvalidCastException: Cannot convert value "1.0.66-ci20191121T214736" to type "System.Version". Error: "Input string was not in a correct format."
>     ParameterBindingException: Cannot bind parameter 'RequiredVersion'. Cannot convert value "1.0.66-ci20191121T214736" to type "System.Version". Error: "Input string was not in a correct format."

Prerelease version numbers typically follow the naming convention #.#.#-Words, but that's not valid for the `System.Version` type that `Import-Module` expects. How can we import a pre-release version of a module?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa36bf0-fdee-c77e-51fe-27b6ad4a9d29
* Version Independent ID: ade5a7a7-929d-065a-f448-b6afe3750be2
* Content: [Import-Module (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Import-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You have to import it using the full path name.

**Comment by deadlydog** [comment]
Thanks @sdwheeler , but that has not fixed the issue. When using the `FullyQualifiedName` parameter like this:

```
[hashtable] $fullyQualifiedName = @{
	ModuleName = 'MyModule'
	ModuleVersion = '1.0.66-ci20191121T214736'
}
Import-Module -FullyQualifiedName $fullyQualifiedName -Global -Force
```

I get this similar error:

> "Cannot bind parameter 'FullyQualifiedName'. Cannot convert value "System.Collections.Hashtable" to type "Microsoft.PowerShell.Commands.ModuleSpecification". Error: "Cannot convert value "1.0.66-ci20191121T214736" to type "System.Version". Error: "Input string was not in a correct format."""

Can you please reopen this issue? Thanks.

**Comment by sdwheeler** [comment]
No, not the FullyQualifiedName, the fully qualified `-Name` (path).

```
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\MyModule\1.0.66\MyModule.psm1
```

**Comment by deadlydog** [comment]
Ah, thanks @sdwheeler . That's not an ideal solution since it involves manually probing the file system to see if a file/directory exists in a special location and loading it only if it does. If that's the solution though, I'll roll with it. I think it would still be worth reopening this issue though so a blurb could be added to the docs about it. As PowerShell continues to become more powerful and popular, there will be more people leveraging the prerelease package capabilities.

**Comment by sdwheeler** [comment]
Yes, I think there is some documentation that can be added. I will add that to your other open issue requesting examples.

Part of the issue around the version is that .NET does not have a class for Semantic Versions. The existing version class does not handle the prerelease portion like Semantic Versioning does. There is an open feature request to add it it to .NET but that will not likely happen until .NET Standard v5 (the next major release after the current v3.x).

You can get the location of the module using `Get-Module`. Here is an example showing a prerelease module on my system:

```
PS> Get-Module posh-git | select path                                          

Path
----
C:\Users\sewhee\Documents\PowerShell\Modules\posh-git\1.0.0\posh-git.psm1

PS> (Import-PowerShellDataFile C:\Users\sewhee\Documents\PowerShell\Modules\posh-git\1.0.0\posh-git.psd1).PrivateData.PSData                                                                      
Name                           Value
----                           -----
ProjectUri                     https://github.com/dahlbyk/posh-git
Tags                           {git, prompt, tab, tab-completion…}
ReleaseNotes                   https://github.com/dahlbyk/posh-git/blob/v1.0.0-beta3/CHANGELOG.md
Prerelease                     beta3
LicenseUri                     https://github.com/dahlbyk/posh-git/blob/v1.0.0-beta3/LICENSE.txt
```

**Comment by deadlydog** [comment]
Ah, neat, using `Get-Module moduleName -ListAvailable | Select Path` will be much nicer than manually checking different path locations like I was 👍

You probably already know this, but I also discovered that `Install-Module`  doesn't include the prerelease part of the version in the directory that it creates, or in the Version of the module. That would be good info to add to the docs as well.

![image](https://user-images.githubusercontent.com/1187140/69993296-248bf200-1511-11ea-8279-a4114a792c43.png)

So it seems that `Import-Module` truly doesn't know anything about prerelease versions because `Install-Module` makes it look exactly like a stable version, and to truly know if you're using a Prerelease version you need to inspect the module manifest like you've shown above.

Thanks, and I look forward to the docs updates 🙂
