### ISSUE TITLE
Incorrect module installation directory paths are given in the examples

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/PowerShell-Docs#5181]
In the examples it mentions that global modules will be installed to `$env:ProgramFiles\PowerShell\Modules` and user scoped modules to `$home\Documents\PowerShell\Modules`. On my Windows 10 computer with PowerShell 5 though, they get installed to `$env:ProgramFiles\WindowsPowerShell\Modules` and `$home\Documents\WindowsPowerShell\Modules`.

I'm guessing that maybe the paths in the docs are applicable to unix systems, or PowerShell Core modules? Could the docs get updated to show the correct paths (maybe mention both paths if it's platform dependent). Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431fe2e9-4044-277c-d759-133522a53143
* Version Independent ID: f3b7d225-4b62-1930-75c5-fc35e1c402ff
* Content: [Install-Module (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-6)
* Content Source: [reference/6/PowerShellGet/Install-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/Install-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
No, you are reading the docs for PowerShell v6. The location changed in v6. Please see https://docs.microsoft.com/powershell/scripting/how-to-use-docs.

**Comment by deadlydog** [comment]
Ah, that makes sense. I can't believe I didn't notice that PS version drop-down box before. Thanks!
