### ISSUE TITLE
Include object for TCP Test result

### ISSUE THREAD

**Issue by chrispiasecki** [MicrosoftDocs/PowerShell-Docs#5182]
Currently when specifying the -TCPPort argument in Test-Connection, the result is always a boolean. It would be nice to have the option to return a result object similar to Test-NetConnection that includes source/destination IP, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e68a7a-10e0-2ae5-b20a-517716367894
* Version Independent ID: 1cf2ccd2-f099-3f92-b698-36311baa0b81
* Content: [Test-Connection (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Test-Connection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Test-Connection.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
This is product feedback and not an issue with documentation. PowerShell behavior issues and feature requests should be filed at https://github.com/PowerShell/PowerShell/issues/new/choose.

However, note that there are significant changes coming to the `Test-Connection` cmdlet for PowerShell v7. See https://github.com/PowerShell/PowerShell-RFC/pull/172/files
