### ISSUE TITLE
Create a note about ensuring the latest version of PowerShellGet is installed to avoid errors

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/PowerShell-Docs#5192]
I recently ran into an issue where the `Find-Module -Name 'MyModule' -AllowPrerelease` command worked fine on some computers, but not on others. My first thought was to check which version of PowerShell they had installed, and they all had 5.1 installed. The problem turned out being that some computers were still running v1.0.0.1 of PowerShellGet, which didn't have the `AllowPrerelease` parameter yet, while the same command ran fine on computers with v2.2.1 installed.

It think it is worth calling out in the docs to ensure that the latest version of PowerShellGet is installed, whether that be in the general description section, or in the parameters section to specify which version of PowerShellGet each parameter was introduced in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02eb2db-16fe-135a-b4e9-2c7400ad2cac
* Version Independent ID: 33f38b29-e0bb-4158-e4ed-cbe071a8bffb
* Content: [Find-Module (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/find-module?view=powershell-6)
* Content Source: [reference/6/PowerShellGet/Find-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/Find-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
Again, you are viewing the docs for PowerShell v6. The version of PowerShellGet that shipped in PowerShell v6 supports that parameter.

**Comment by deadlydog** [comment]
Bah, sorry @sdwheeler . I actually read through the PowerShell v5.1 page, but must've clicked the button to report the issue on the v6 page. This is in fact an issue in the v5.1 docs that could get addressed.
