### ISSUE TITLE
Documentation for LocalAccounts module missing from PowerShell 7 

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#5193]
# Documentation Issue
If you attempt to get online help (either Search Engine assisted or via Get-Help -Online from within PowerShell), the help text for all commands in the Microsoft.PowerShell.LocalAccounts is missing from the PowerShell 7 documentation.

These need, IMHO, to be added prior to PowerShell 7 hitting RTM (and preferably for testing at RC1 if possible).

I _think_ is's a "simple matter" of copying the 5.1 help text over. 

## Context of the issue

PowerShell has a feature allowing you to open a browser window with the on-line help version of the PowerShell help text. For many, the layout (particularly the way parameters are displayed and where examples are placed) is much better than using the built-in help (i.e. Get-Help -Show)
  
  **Cmdlet reference & about_ topics**
  - [x] Version 7 content
  - [x] Version 6 content
  - [ ] Version 5.1 content

5.1 help text if fine. And given that 7.0 is imminent - skipping Version 6 might be acceptable.

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
Microsoft.PowerShell.LocalAccounts does not ship in PowerShell 6 or PowerShell 7. So it is not included in the documentation.

**Comment by joeyaiello** [comment]
As @sdwheeler said, this is technically a 5.1 module that's being picked up by 7 on the Windows image. There are a bunch of modules that fall into this bucket that still belong correctly in the 5.1 (and it's also correct for 7 to receive 5.1 updateable help, which is also working correctly). 

That being said, this is a confusing thing, and we agree that we should have an article talking about Windows back compat all up.
