### ISSUE TITLE
Native dll resolver

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#5196]
# Summary of the new document or enhancement

After https://github.com/PowerShell/PowerShell/pull/11032 (relasted issue https://github.com/PowerShell/PowerShell/issues/9488) PowerShell 7.* will can find and load native dlls based on current OS architecture.

We need a document for module developers with description how the native dll resolver works and how create right directory tree for nuget package.

Details of requested document:

- Proposed title: no ideas
- Propose location in the TOC: no ideas
- Target audience: module developers, advanced users
- Purpose or scenario:
  _or_
  Proposed changes/additions to existing article:
- List of related articles to link to:
https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/publishing-packages/publishing-a-package?view=powershell-6
https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/publishing-guidelines?view=powershell-6

**Comment by joeyaiello** [comment]
Related to #4249
