### ISSUE TITLE
get-help get-childitem -Parameter filter does not define syntax of filter

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#5201]
# Documentation Issue
```
update-help
get-help get-childitem -Parameter filter
```

quote from customer

>Get-Help does not define the syntax of the Filter parameter, other than it being a string. In fact, I could ONLY find an explanation on StackOverflow. In this lab, telling a pwsh novice to use help to distinguish the behavior of these parameters would be frustrating. I think the provider documentation for FileSystem should define how it uses the Filter parameter, and Get-ChildItem docs should at least point to that explanation for the Filter parameter.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):
  
  **Cmdlet reference & about_ topics**
  - [ ] Version 7 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
This is fixed in the markdown but they haven't run `Update-Help -Force` in PowerShell 6. If they are running PowerShell 5.1, then we haven't published updated cab files for help. See my blog post about updating the help for 5.1 and older. https://devblogs.microsoft.com/powershell/updating-help-for-older-versions-of-powershell/

**Comment by TravisEz13** [comment]
Please not the repro includes Update-Help.  I verified the issue.

**Comment by TravisEz13** [comment]
verified.
