### ISSUE TITLE
Mention / introduce the term "escape sequence"; reframe the stop-parsing symbol

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5210]
At least mentioning the well-established term _escape sequence_ would be helpful to newcomers, and is arguably the better term even for PowerShell. (The "escape" in "escape sequence" doesn't literally have to refer to the ESC char., just to the fact that normal parsing is "escaped" when the _escape character_ (which is `` ` `` in PowerShell) is encountered; i.e. that the following character(s) are interpreted differently. 
It is also confusing that what is called a _special character_ is composed of at least _two_ characters.

`--%` is only indirectly related to the escape sequences otherwise discussed in this topic, which all have the following commonality, as stated in the "Long description" section:

> PowerShell's special characters are only interpreted when they're enclosed in double-quoted (`"`) strings.

Syntactically, `--%` is very different, and it relates to escape sequences only in the following way, which should be clearly stated:

When you use `--%` to pass arguments to external programs, interpretation of escape sequence is _deactivated_; e.g., ``echoArgs.exe --% "`a"`` passes ``"`a"`` _verbatim_ to the executable rather than interpreting `` `a `` as the alert (bell) character.

Otherwise I think it's sufficient to link to `about_Parsing` and its discussion of `--%`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12c7a74-94ff-72b8-f2cd-576886b0f0f7
* Version Independent ID: 03f20403-cc8c-f3b2-f704-8eaa433fdd7c
* Content: [about_Special_Characters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7)
* Content Source: [reference/7/Microsoft.PowerShell.Core/About/about_Special_Characters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7/Microsoft.PowerShell.Core/About/about_Special_Characters.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Fixed in https://github.com/MicrosoftDocs/PowerShell-Docs/pull/5236
