### ISSUE TITLE
powershell examples?

### ISSUE THREAD

**Issue by MarkZweig** [MicrosoftDocs/PowerShell-Docs#5216]
Where are the powershell examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce9c320-4bff-ffcc-fea2-13f890d43537
* Version Independent ID: 7527e0eb-deb1-80fd-4492-2ee14eb54df5
* Content: [Cmdlet Parameter Sets - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/developer/cmdlet/cmdlet-parameter-sets.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/cmdlet-parameter-sets.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
I think you probably are looking for https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?#parametersetname-argument

**Comment by VectorBCO** [comment]
are we in powershell-docs repo?
