### ISSUE TITLE
Online versions of cmdlet help topics should link to the documentation for their output types in the "Outputs" section

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5221]
Many cmdlets output complex .NET types that require consulting their documentation to take full advantage of them.

`Select-String`'s [MatchInfo](https://docs.microsoft.com/en-US/dotnet/api/Microsoft.PowerShell.Commands.MatchInfo) output type is a good example.

It would be helpful if the "Outputs" section in all cmdlet help topics consistently linked the listed types to their documentation.
(Sometimes there's a link elsewhere on the page, but that's not easy to discover.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c82b0f-a14a-f62c-ab41-8952fd517462
* Version Independent ID: 86cda1f5-a5bf-45bd-d7d4-aa1a16134c7d
* Content: [Select-String (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Select-String.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
I agree. But there is a limitation in our publishing system the prevents this from working. It is on the list of enhancements we want to add in the next year.

**Comment by sdwheeler** [comment]
The .NET API cross-reference service is now enabled for this docset. Types are linked automatically. If there is a type not linked then it could be resolved. Need to open individual issues for unlinked types.
