### ISSUE TITLE
Shipping tests?

### ISSUE THREAD

**Issue by weq** [MicrosoftDocs/PowerShell-Docs#5224]
When you mention tests in this article do you mean that one should ship the module with tests INCLUDED? Or just "please use pester when developing" ? Considering this is about publishing and not BP development the wording can be sorta misunderstood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f709ba35-400c-4d8d-9f6d-921eb4d8d6c6
* Version Independent ID: 08031b25-634d-7965-d59f-2aab0c681dc5
* Content: [PowerShell Gallery Publishing Guidelines and Best Practices - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/publishing-guidelines?view=powershell-6#include-tests)
* Content Source: [reference/docs-conceptual/gallery/concepts/publishing-guidelines.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/concepts/publishing-guidelines.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by SydneyhSmith** [comment]
@weq thanks for your question, we recommend that module owners ship the module with the tests included...the rationale for this is described [here](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/concepts/publishing-guidelines.md#include-tests)
