### ISSUE TITLE
Splatting Command Parameters does not mention it doesn't work with cmdlets/modules

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/PowerShell-Docs#5227]
I wasted a bit of time today trying to use the $Args parameter in a module I am developing. I kept running into the error `A parameter cannot be found that matches parameter name '[ParameterName]'` when calling my function. It seems that you are not able to use $Args in a module if that function takes any parameters; although it looks like it is allowed if the function does not define any parameters. This seems kind of weird; possibly something that was missed in the design?

Also, if you add `[CmdletBinding()]` to a function, that breaks the functionality as well. For example, if you add the that line to the example in the docs to make it:

```powershell
function Get-MyCommand
{
	[CmdletBinding()]
	Param ([switch]$P, [switch]$C)
	if ($P) { Get-Process @Args }
	if ($C) { Get-Command @Args }
}

Get-MyCommand -P -C -Name PowerShell
```

Then instead of running as expected, it will return the error:

> Get-MyCommand : A parameter cannot be found that matches parameter name 'Name'.

Having some documentation around these restrictions would be useful. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d8886cd-e2cc-66c3-bb04-58e94d1f9d23
* Version Independent ID: e12ddb02-4549-2bee-39fc-e6f902f7da25
* Content: [about_Splatting - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-5.1&source=docs#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This is expected behavior. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_automatic_variables#args

> `$args`
>
> Contains an array of values for **undeclared parameters** that are passed to a function, script, or script block. 

When you use `[CmdletBinding()]` you are required to declare parameters.

**Comment by deadlydog** [comment]
Ahh, yeah, and I just [found this as well](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute?view=powershell-6#long-description).

> The $PSCmdlet automatic variable is available to functions with the CmdletBinding attribute, but the $Args variable is not available.

I still think it might be worth adding a short sentence to the $Args section on this page though (that maybe links to the page you or I provided above) to call it out specifically. Thanks!

**Comment by sdwheeler** [comment]
@deadlydog Agreed. We could provide more context here. Thanks for the feedback.
