### ISSUE TITLE
ScriptBlock wording

### ISSUE THREAD

**Issue by ambrosektal** [MicrosoftDocs/PowerShell-Docs#5230]
Please reword the write-up for ScriptBlock.  And example re-write would be:
"Enclose the commands in both parenthesis and braces ( { } )..."
I just spent an hour troubleshooting my script and this was the only issue.  
The issue came when I was passing in an object, while using this with powercli.  At first it was a VIObject, but I reverted down to a variable containing a string.  The string was not being passed even when using the -InputObject.
I took the write-up at its word when it only stated "braces".  I thought the parenthesis in the explanation where there to identify the braces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ab025d-7841-b922-9e06-2944a3c0dd0e
* Version Independent ID: a3c2b715-deae-5d13-5eb6-315cdf19e2b4
* Content: [Start-ThreadJob (ThreadJob)](https://docs.microsoft.com/en-us/powershell/module/threadjob/start-threadjob?view=powershell-6#feedback)
* Content Source: [reference/6/ThreadJob/Start-ThreadJob.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/ThreadJob/Start-ThreadJob.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**

**Comment by sdwheeler** [comment]
Parentheses are not required. So I don't understand the problem you had. Can you provide a simplified example of the problem you had?
