### ISSUE TITLE
2 GB Size Limit - Which File?

### ISSUE THREAD

**Issue by ebmgithub** [MicrosoftDocs/PowerShell-Docs#5242]
Does the 2 GB size limit apply to the Path (source) file or the Destination (.zip) file ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e67ee59-8a3e-59ad-7c8d-a78605f55b66
* Version Independent ID: 3c8b8ee9-6a97-4eda-d184-49e728abf0a6
* Content: [Compress-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

**Comment by chasewilson** [comment]
@ebmgithub Thanks for the question. The limit is on the source file. The .NET API has a limitation on the file stream size to the compression. 

Does this answer your question?

**Comment by chasewilson** [comment]
Closing this issue for now. Feel free to reach out with any questions and concerns

**Comment by KalleOlaviNiemitalo** [comment]
Confirmed that `Compress-Archive` on a 64-bit PowerShell 7.0.0-rc.2 is able to create a 6 GB zip file from many small files, but fails if a single input file is that large, regardless of whether `-CompressionLevel NoCompression` is used.

```
MethodInvocationException: C:\program files\powershell\7-preview\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:845
Line |
 845 |  …                     $destStream.Write($buffer, 0, $numberOfBytesRead)
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Write" with "3" argument(s): "Stream was too long."
```

A request to remove this limitation has been filed at <https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/19>.
