### ISSUE TITLE
Mention the ConfirmImpact attribute in this topic

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/PowerShell-Docs#5248]
With the information here as it stands, ShouldProcess has no apparent effect - presumably because the default ConfirmImpact level doesn't exceed the level to show the prompt from ShouldProcess. By adding SupportsShouldProcess = true and ConfirmImpact = ConfirmImpact.High, ShouldProcess will show its prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e23442f-0198-0ad4-930a-0fdf59664475
* Version Independent ID: a4ca5f86-50c3-961f-b1f4-1acfb3880651
* Content: [How to Request Confirmations - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-request-confirmations?view=powershell-6#to-request-confirmation)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-request-confirmations.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-request-confirmations.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
See also related issue #5492
