### ISSUE TITLE
ComputerName Parameter

### ISSUE THREAD

**Issue by PrometheanHeir** [MicrosoftDocs/PowerShell-Docs#5257]
There is no parameter for Test-Connection named 'TargetName'. There is a parameter called 'ComputerName'. This might just be a typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e68a7a-10e0-2ae5-b20a-517716367894
* Version Independent ID: 1cf2ccd2-f099-3f92-b698-36311baa0b81
* Content: [Test-Connection (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Test-Connection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Test-Connection.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @PrometheanHeir thanks for the feedback! The `-ComputerName` parameter was updated to `-TargetName` in PowerShell Version 6 which is where you have this issue linked :) You can check out the [PowerShell v 5.1 documentation](https://docs.microsoft.com/powershell/module/microsoft.powershell.management/test-connection?view=powershell-5.1) for that syntax. 

I'll be closing this issue for now but if you have any more issues or questions, feel free to reach out!

**Comment by PrometheanHeir** [comment]
Alright, thanks for the update.
