### ISSUE TITLE
Missing Error Handling Information

### ISSUE THREAD

**Issue by tydaeus** [MicrosoftDocs/PowerShell-Docs#5265]
Need to mention how Invoke-Expression handles errors in the invoked expression, because conventional PowerShell error-handling (`if ($?)`) will not work and there is no configuration option for specifying a passthrough. 

Experimentation appears to show that:

* If the invoked expression (powershell or command) exits with a non-zero status, `$?` is set to true and `$LASTEXITCODE` is set to the status code (atypical)
* If the invoked expression (powershell) exits without specifying status, `$?` is set to true and `$LASTEXITCODE` is not updated (typical)
* If the invoked expression throws an uncaught exception (powershell) it must be caught to handle it (typical)
* If the invoked expression is invalid, an exception is thrown (typical)

There doesn't appear to be a scenario where `$?` will be set to false, without an exception being thrown and thus bypassing any `$?` checking.

For successful error handling, it looks like the best option is set `$LASTEXITCODE` to 0 prior to running any command, so that it will be possible to rely on its value, and also to wrap the call in a try-catch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d669d38f-7692-bbaa-2c88-ba1b1d2bb4c1
* Version Independent ID: 9d592d60-e29c-84e6-2e43-078e2a69fb97
* Content: [Invoke-Expression (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by tydaeus** [comment]
Correction: best option is set `$global:LASTEXITCODE` to 0.

**Comment by sdwheeler** [comment]
We have an issue tracking this already. See https://github.com/MicrosoftDocs/PowerShell-Docs/issues/1583 for a comprehensive discussion. We plan to get this information added but there is a lot of work to do.
