### ISSUE TITLE
Why is the 'FileInfo' bold text not a hyperlink?

### ISSUE THREAD

**Issue by barrypicker** [MicrosoftDocs/PowerShell-Docs#5266]
Why is the 'FileInfo' bold text not a hyperlink?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb9df3dc-9807-cf35-8826-f792da6d44b8
* Version Independent ID: 612094b4-801d-5b3d-2442-42a4ac18170d
* Content: [New-TemporaryFile (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-temporaryfile?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/New-TemporaryFile.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/New-TemporaryFile.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hi @barrypicker thanks for the question. It doesn't look like that's standard compared to other cmdlet helps. Is there a reason you think it would be a hyperlink?

**Comment by barrypicker** [comment]
Hi Chase, 
Thanks for the response.
My expectations for this hyperlink are not based on any standards or previous experience with the site in general.  Rather, this is a missed opportunity to build a better knowledge base with features to make learning easier.




    On Friday, January 3, 2020, 07:45:56 AM PST, Chase Wilson <notifications@github.com> wrote:  
 
 
Hi @barrypicker thanks for the question. It doesn't look like that's standard compared to other cmdlet helps. Is there a reason you think it would be a hyperlink?

**Comment by sdwheeler** [comment]
We are working on improvements to the way our help is built. Linking the input and output types to the .NET reference is a planned enhancement.

**Comment by sdwheeler** [comment]
Duplicate of #5221
