### ISSUE TITLE
Log Size Limit?

### ISSUE THREAD

**Issue by geektbee** [MicrosoftDocs/PowerShell-Docs#5267]
For "Start-Transcription", is there anyway to limit the file size of the Transcription log? Say it needs to never go over 100MB; but needs to keep appending, like a scrolling log of sorts..... I would think there is a "--MaxSize 100MB" parameter available, but I'm seeing no indication of such a feature. Are there any alternatives?

**Comment by chasewilson** [comment]
@geektbee Thanks for the question. It doesn't appear to be available currently and I can't find any requests for it in the [PowerShell Repo](https://github.com/PowerShell/PowerShell). If you would like to see that, you can put in a request in the PowerShell Repo and the team will take a look at it.

**Comment by sdwheeler** [comment]
Please file a feature request at https://github.com/PowerShell/PowerShell/issues/new/choose
