### ISSUE TITLE
Sample doesn't work

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/PowerShell-Docs#5268]
One problem I had with this sample is that it requires 32 bit PowerShell (for the ODBC driver), which is fine, but should be in the instructions. Another problem is that it requires an older-format Access DB (2003 format), which isn't called out. A much better sample would be to avoid all of that and make a sample file system provider, which is unnecessary since it already exists, but would be an easier to understand demonstration. The instructions also don't explain that you need to do a new-psdrive command to start the provider and connect it to the MDB file.

With those fixes I can do a 'dir' to see the tables, but I can't dir or CD to a specific table (GetParentPath crashes looking for a '\' that doesn't exist).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9a9516-b3b0-d759-20d0-791ca4f88b40
* Version Independent ID: 381b4413-8c02-47cf-f390-b51319c49793
* Content: [AccessDbProviderSample05 Code Sample - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/prog-guide/accessdbprovidersample05-code-sample?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/developer/prog-guide/accessdbprovidersample05-code-sample.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/prog-guide/accessdbprovidersample05-code-sample.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
These samples are old and no longer maintained.

If you are looking to create a PSProvider, take a look at the SHiPS project https://github.com/powershell/ships.
