### ISSUE TITLE
Need to quote script name and parameters

### ISSUE THREAD

**Issue by Yuyiya** [MicrosoftDocs/PowerShell-Docs#5269]
Following the installation step "4. Run the Install-WMF5.1.ps1 script in that folder, …", you may get an error message to the effect that PowerShell doesn't automatically trust scripts in that folder (the one to which the .ZIP archive had been extracted).  However, you can overcome this hiccup by quoting the script name and any parameters you're using.  For example, entering (WITH quotation marks!)  "Install-WMF5.1.ps1 /NoRestart /AcceptEula" will automatically and silently accept the EULA, and NOT restart, postponing the installation of WMF 5.1 until after you restart Windows manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48f24cb0-8445-7f2d-65e2-32ea16847525
* Version Independent ID: 72775454-5392-6a4f-81c9-6f978b929247
* Content: [Install and configure WMF 5.1 - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/wmf/setup/install-configure?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/wmf/setup/install-configure.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/wmf/setup/install-configure.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@Yuyiya The error message has to do with your ExecutionPolicy. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_execution_policies

**Comment by Yuyiya** [comment]
@sdwheeler Thanks for the heads-up!  I'd appreciate some guidance on using the **ExecutionPolicy** _intelligently_.  On a Windows client computer, rather than quoting _every_ script and its parameters individually (as I found worked in my case), would it be better to set the **ExecutionPolicy** to **RemoteSigned** in the registry?

**Comment by sdwheeler** [comment]
@Yuyiya You don't have to edit the registry. Just use the `Set-ExecutionPolicy` cmdlet. See https://docs.microsoft.com/powershell/module/microsoft.powershell.security/set-executionpolicy

**Comment by Yuyiya** [comment]
@sdwheeler Thanks; I understand that I _could_ use the `Set-ExecutionPolicy` cmdlet.  But wouldn't I need to do so _every time_ I want to run a script?  And what's the downside to using the registry to set the user **ExecutionPolicy**?  (Besides the usual caveats on the dangers of editing the registry, of course!)

**Comment by sdwheeler** [comment]
@Yuyiya No. You only need to set the policy once.

**Comment by Yuyiya** [comment]
@sdwheeler **Perfect!**  Thank you :-) - everything is now clear as day!
