### ISSUE TITLE
Powershell Installation Instructions Are Missing The Installation of libicu55 

### ISSUE THREAD

**Issue by bordenit** [MicrosoftDocs/PowerShell-Docs#5270]
Tested installation instructions with Ubuntu 18.04. Installation fails as written here:
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804

Add installation of libicu55 as shown here:
https://askubuntu.com/a/939367

**Comment by sdwheeler** [comment]
@TravisEz13 Can you verify and correct?

**Comment by TravisEz13** [comment]
we don't use libicu55 on Ubunutu18.04.  This is not correct.
