### ISSUE TITLE
A call operator multiple parameter example

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#5274]
```powershell
$prog = 'Get-Service'
$myargs = '-Name','Spooler'
& $prog $myargs
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b91092-e3fa-5b16-7c5c-b26b40eed874
* Version Independent ID: 5fcd4430-a6b8-0438-73c9-29749b804323
* Content: [about_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Operators.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@jszabo98 Is there a question here?

**Comment by jszabo98** [comment]
I just think it should be added as an example.

**Comment by sdwheeler** [comment]
That is not a valid example. It throws an error.

```
Get-Service : Cannot find any service with service name '-Name'.
At line:1 char:1
+ & $prog $myargs
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Name:String) [Get-Service], ServiceCommandException
+ FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
```

If you have a working, more useful example that you can explain, I would welcome a PR.

**Comment by jszabo98** [comment]
Hmm, this works.  Powershell commands act differently:

```powershell
$prog = 'cmd'
$myargs = '/c','dir'
& $prog $myargs
```
