### ISSUE TITLE
Both links on home page for (powershellgallery.com) are broken

### ISSUE THREAD

**Issue by vinyar** [MicrosoftDocs/PowerShell-Docs#5278]
Clicking on both information links on home page takes users to 404 pages.

Broken - "What is PowerShell Gallery?"
  404 - https://docs.microsoft.com/en-us/powershell/gallery/overview

Broken - "Getting started"
  404 - https://docs.microsoft.com/en-us/powershell/gallery/getting-started

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b83cac-48eb-d254-b541-76a77bfc1854
* Version Independent ID: ca0eb566-b8bc-4f87-f8fa-2f9074bef107
* Content: [The PowerShell Gallery - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/overview?view=powershell-6)
* Content Source: [reference/docs-conceptual/gallery/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/overview.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
New build of powershellgallery.com fixes the broken links.
