### ISSUE TITLE
Tooling .ps1 links

### ISSUE THREAD

**Issue by VLoub** [MicrosoftDocs/PowerShell-Docs#5283]
Hello,

on this page, links for Tooling (#tooling) scripts end up at 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da1632e9-27b0-e76d-d655-6e4b17162d23
* Version Independent ID: 338bd98a-c08c-65a9-e684-878dfa01198d
* Content: [DSC Pull Service - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/pullServer?view=powershell-6#tooling)
* Content Source: [reference/docs-conceptual/dsc/pull-server/pullServer.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/pull-server/pullServer.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The script has moved to https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/master/source/Modules/DscPullServerSetup/DscPullServerSetupTest/DscPullServerSetupTest.ps1

**Comment by chasewilson** [comment]
Hi @VLoub thanks for letting us know. The links have been appropriately updated and you should see them live within 24 hours.
