### ISSUE TITLE
about powershell remoting and WinRM

### ISSUE THREAD

**Issue by razos** [MicrosoftDocs/PowerShell-Docs#5308]
hello
I would like to know whats the difference between a PSSession and winrm
and thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a43d3-9571-389c-56ab-7d42a53bf5b1
* Version Independent ID: c138e6a8-fd80-bd64-25ac-24e774e09421
* Content: [PowerShell Core Support Lifecycle - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-6)
* Content Source: [reference/docs-conceptual/PowerShell-Support-Lifecycle.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
See https://docs.microsoft.com/powershell/scripting/learn/remoting/winrmsecurity and https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_pssessions

WinRM is a protocol for accessing remote PSSessions.
