### ISSUE TITLE
32 bit versus 64 bit powershell

### ISSUE THREAD

**Issue by MusiqueGraeme** [MicrosoftDocs/PowerShell-Docs#5314]
I tried running the same command "Get-LocalUser" in powershell and in powershell (x86) , the latter attempt failed saying - 
"Get-LocalUser : The term 'Get-LocalUser' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Trying Get-WinEvent worked in both places - so it seems that there is a difference between the 32 bit version and the 64 bit version which I believe should be noted here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29cac8d5-4a4d-e515-6899-67b3b44d86c6
* Version Independent ID: 74bfb393-1031-c1f8-3ccd-b3864c4c6c71
* Content: [Get-LocalUser (Microsoft.PowerShell.LocalAccounts)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/get-localuser?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by SteveL-MSFT** [comment]
It's correct that there isn't a 32-bit version of the LocalAccounts module on 64-bit Windows.  Perhaps just a Note is sufficient.
