### ISSUE TITLE
How to get a raw hex string out of Format-Hex ?

### ISSUE THREAD

**Issue by beppe9000** [MicrosoftDocs/PowerShell-Docs#5319]
How do I get "68656C6C6F" as the output ?
"hello" | Format-Hex 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003e647f-a9a5-791f-cd59-dc61f4e7cfef
* Version Independent ID: 17518c3b-829a-bb20-8b3a-f82349d64762
* Content: [Format-Hex (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-hex?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Format-Hex.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Format-Hex.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
There is no way for the cmdlet to give you the raw hex string like that. You can do this:

```
(('hello' | format-hex).bytes | %{ '{0:X2}' -f $_ }) -join ''
68656C6C6F
```

**Comment by beppe9000** [comment]
Thanks!
