### ISSUE TITLE
How to create help for Modules 

### ISSUE THREAD

**Issue by mvadu** [MicrosoftDocs/PowerShell-Docs#5325]
# Documentation Issue
Current [article on Portable Modules](https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules?view=powershell-7) does not mention how to provide the help section for the custom portable modules.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules?view=powershell-7
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [X] Version 7.x preview content
  - [X] Version 7.0 content
  - [X] Version 6 content
  - [X] Version 5.1 content

## Detailed description of the issue
In the old days we were encouraged to document scripts/modules [using comments based help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7). In the new way f binary modules we can't use same method since C# comments use different structure. Can we please document how to provide documentations for binary modules?

**Comment by sdwheeler** [comment]
The PowerShell help files are in an XML format known as MAML. [PlatyPS](https://www.powershellgallery.com/packages/platyPS/0.14.0) is the easiest way to create the help.l

**Comment by mvadu** [comment]
@sdwheeler good to know. I think MAML and it's best practice should be part of the binary module documentation. So when it shows how to write our first standard module (`dotnet new psmodule`) it should also tell us how to get that module work with `get-help`.
