### ISSUE TITLE
How is this supposed to be used in a profile to permanently set the colors?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/PowerShell-Docs#5328]
THe same command that works in the console does not work when used in the profile.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8794a7a9-ae86-bbde-626f-da91b0d1b491
* Version Independent ID: 18945940-0df3-1027-612f-2adf6291d22d
* Content: [Set-PSReadLineOption (PSReadline)](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-5.1)
* Content Source: [reference/5.1/PSReadline/Set-PSReadlineOption.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PSReadline/Set-PSReadlineOption.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@StingyJack What error do you get from your profile?

**Comment by StingyJack** [comment]
None. It just doesn't work. I placed it before a function that's already in the profile script and then after. The new ps window I opened after each attempt still had the wrong colors but the function still worked

**Comment by sdwheeler** [comment]
@StingyJack What version of PSReadline are you running? Run the following command:

`Get-Module -list PSReadline`

Also please provide the sample code you are trying to make work.

**Comment by sdwheeler** [comment]
@StingyJack Note that PowerShell 6 and higher installs PSReadLine v2. You can also install this from the PowerShell Gallery. The syntax for setting colors changed in v2. You were viewing the documentation for the PSReadline (v1.2) that shipped in PowerShell 5.1. Make sure you know which version of PSReadline is actually being used.

**Comment by doctordns** [comment]
@sdwheeler Another issue caused by this documentation confusion. Can we update ALL the PSReadline documentation to reflect what the PowerShell team has done to ensure users do not get confused. 

IMHO, I should be able to come to docs.microsoft.com and find the right documentation for PS Readline easily. an IT Pro should no_ be required to navigate over to github to find this documentation.

Can we get a holistic solution?

**Comment by StingyJack** [comment]
@sdwheeler   I'm on the correct page. PS6 isn't going to be my primary version until it's able to use the bunch of modules I already have without a bunch of messing about on my part (if this is already possible, then this is where the docs are lacking IMHO) or it's included in Windows, replacing 5.1.

I'd have to check on my work computer for the actual commands, but the commands I put into the profile are commands that work at the console but only for that session.

I've used this before on win7 and on an earlier win 10 version, but I don't have access to it. A working example of how to use this in a profile would be appreciated.

**Comment by sdwheeler** [comment]
We have the correct version of the on docs.microsoft.com. When you are viewing PS5.1 content you get the PSReadline v1.2 docs. When you view PS6 or newer you see the PSReadline 2.x docs. That is how we shipped the product. This issue is that you have to know which version of PSReadline you have because there are other ways you could have upgraded.

We can't help troubleshoot problems without more specific details.

**Comment by doctordns** [comment]
@StingyJack For all intents and purposes, PowerShell 6 is pretty much legacy. If you want to move on, you'll find that PowerShell 7 RC is a LOT more compatible. The compatibility mechanism that is now built-in simplifies things. But it;'s not 100%. I suggest you look more closely at RC2 (or better yet the daily build).

**Comment by StingyJack** [comment]
For the record, PSReadline is v 1.2 and the commands would be something like 
```
Set-PSReadlineOption -TokenKind Parameter -ForegroundColor DarkCyan
Set-PSReadlineOption -TokenKind Number -ForegroundColor Gray
Set-PSReadlineOption -TokenKind String -ForegroundColor Gray
```

I just now tried resetting the command window color defaults to black background, bright green text, rebooted and tried to open a powershell prompt and the colors now show up so that I can see them.  Not sure if it was the cmd window color or the reboot (tried rebooting before) or the combination but its now working. 

@doctordns - I'll take a look at 7. For as Xplat as v6 was supposed to be, they sure forgot about windows =/
