### ISSUE TITLE
How to Debug Portable Modules (psmodule) using VSCode

### ISSUE THREAD

**Issue by mvadu** [MicrosoftDocs/PowerShell-Docs#5330]
# Summary of the new document or enhancement
As a new developer starting with psmodules using .net core, I need a document about debugging a binary module created using the steps given in [writing-portable-modules](https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules?view=powershell-7)  to aid in the development process.

Details of requested document:

- Proposed title: Debugging Portable Modules (psmodule)
- Propose location in the TOC: https://docs.microsoft.com/en-us/powershell/scripting/learn
- Target audience: Developers
- Purpose or scenario: Debugging a module during development
- List of related articles to link to: 
  a. https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules

**Comment by mvadu** [comment]
I have called out vscode in the title given official stance of the powershell team suggesting to use vscode for v6+ powershell development.

**Comment by sdwheeler** [comment]
@mvadu You can start with this article: https://docs.microsoft.com/powershell/scripting/components/vscode/using-vscode-for-remote-editing-and-debugging

This is only a starting place. It probably doesn't have all you want to cover.

**Comment by mvadu** [comment]
@sdwheeler I am using vscode for remote runspace debugging already. The problem is with binary modules since the source code is kind of decoupled with a dll (after `dotnet build` and `import-module`), and I don't see any straight way of using a break point in my source and be able to debug forward. 
I am trying to port few of my log parsers (e.g. https://github.com/AdysTech/PowerScripts/tree/master/AccessLogParser) to get compiled code performance. But without a proper debugging support its little tricky, since once the module is imported its not easy to unload the dll, which basically complicates your development workflow.

**Comment by sdwheeler** [comment]
@TylerLeonhardt Do you have any pointers you can add here?

**Comment by TylerLeonhardt** [comment]
The gist is that you want to use the [C# extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) and attach to the PowerShell process that the binary module is loaded into.

**Comment by mvadu** [comment]
sorry to drag this issue away from documentation into usage, I tried your approach @TylerLeonhardt , the psmodule has `BeginProcessing()`, and I want to break into at a specific line inside that function. I added a process level debugging in launch.json. 
` "version": "0.2.0",
    "configurations": [        
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]`

However c# process debugging does not support function beak points. And without them are we suppose to use a hack like waiting for debugger? 

`
  while (!System.Diagnostics.Debugger.IsAttached)
            {
                System.Threading.Thread.Sleep(100);
            }
`

**Comment by TylerLeonhardt** [comment]
Any reason you can't:

Attach to PowerShell process,
Add breakpoints,
Execute cmdlet inside PowerShell process

That should break into the debugger to the breakpoints you have set.

**Comment by mvadu** [comment]
Adding the breakpoints in the source does not make it to break at that line when i run the PS module command being developed.  I also see an error in the UI about `No symbols have been loaded for this document` when I add the break point after `import-module`.  Can you try this approach with the same module code given in [writing-portable-modules](https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules) article?

**Comment by TylerLeonhardt** [comment]
Here's a video of me getting it working: https://youtu.be/cSbIXmlkr8o?t=2636

make sure you start at 43:56.

> I also see an error in the UI about No symbols have been loaded for this document

This is an error that usually means that the code you have loaded in PowerShell is not the same as the code in your editor. If you've modified _any_ of the code after loading in the module, you're gonna get that. And since binary modules can't be unloaded or reimported into the same session, you have to start a new PowerShell process and import it again.

**Comment by mvadu** [comment]
Thank you for that video Tyler, nice talk by the way. I think what was missing in your talk which occurred to me later was using `pwsh.exe` and not depending on the default PS version on Windows. Man, with the v6 this can be confusing. Your method does not work on default powershell v5 on any of the Windows server versions (tried 2012 and 2016 server SKUs). But works beautifully on pwsh. Another reason to document it and share it.

**Comment by TylerLeonhardt** [comment]
If you want to use Windows PowerShell, you need to make sure that the C# debugger is using the .NET Framework debugger and not the .NET Core debugger because Windows PowerShell is a .NET Framework application.

**Comment by mvadu** [comment]
you just reminded me of 10 year younger me laughing at Java developers struggling with different JVM  vendors and versions and having to optimize their code for one vs other :) Never thought we will have same situation in .Net world. You are right, that was my bad, once I added the clr type to launch.json I am able to use the default one too.

**Comment by fsackur** [comment]
I've just gone thru this same process and would be willing to PR to the docs. Do we feel happy with the specifics of the answer I posted in https://stackoverflow.com/a/64414019/6274530 ? Obviously I'll make it follow the proper documentation style.

This approach takes a step out of Tyler's posted video.

I don't have it working in Windows PowerShell.

**Comment by sdwheeler** [comment]
@fsackur I would welcome the contribution. If you got it in this month it would qualify for #hacktoberfest.

**Comment by fsackur** [comment]
Oops - I have flooded the issue with commits! I noted that sdwheeler linked in a commit message, so picked up on that.

**Comment by fsackur** [comment]
@mvadu You mentioned the DLL getting locked. Ultimately, I took it this note out of the PR, but see https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6775/commits/7aa444b6e6cb4ac6bdf5209b4c3c48a24f511f3f - the launch config creates a single-use shell. File is unlocked when you stop debugging.

**Comment by mvadu** [comment]
@fsackur the dll getting locked was an issue mentioned in the stackoverflow question you linked. But I agree that will be a problem probably many will face. See the that question, I added my answer there too, I used a launch json with both traditional powershell and new v7 options. In corporate environments we will have to deal with V5 for many more years before V7 (or whatever then current version) becomes more widely deployed. 

Please see if you can use the multi target launch config can be integrated in your guide. my launch.json can be found [here](https://github.com/AdysTech/PowerScripts/blob/master/AccessLogParser/.vscode/launch.json)

**Comment by fsackur** [comment]
Great thanks @mvadu , your opening comments led me to the solution I needed, and your feedback has helped to bring about https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode-for-debugging-compiled-cmdlets

**Comment by mvadu** [comment]
@fsackur you are a very kind man! thank you a great guide, I wish I had this in Jan :)
