### ISSUE TITLE
Set-Location page needs updating for PowerShell 7

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#5332]
In PowerShell 7, set-location has a new pair of parameters + and - so you can do this:

```powershell
PS C:\> cd \foo
PS C:\foo> cd cert:
PS Cert:\CurrentUser\> cd HKLM:\SOFTWARE\
PS HKLM:\SOFTWARE\> cd $env:systemroot
PS C:\Windows> #  then
PS C:\Windows> CD -
PS HKLM:\SOFTWARE\> CD -
PS Cert:\CurrentUser\> ###  and
PS Cert:\CurrentUser\> CD +
PS HKLM:\SOFTWARE\> cd +
PS C:\Windows>
```
This functionality works by default, but does not seem to use default location stack noted in the notes section..

This page needs to be updated for PowerShell 7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f0e6cc-aaa6-78c1-866e-65fa468e15f4
* Version Independent ID: dec46093-f0e6-7148-2f9f-b59caae40069
* Content: [Set-Location (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-location?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Set-Location.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Set-Location.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @doctordns thanks for the feedback. As I read the documentation and understand the usage you mentioned above, this is what I've come up with. 

The `-` and the `+` are used and documented with the **Path** Parameter. I don't see any issue with the documentation there. 

Neither of those characters use the default stack. Rather, when the session is started, a BoundedStack Linked List is created to store a 20 item location history. The `-` and `+` navigate that (for all intents and purposes) list. That's the reason it's not mentioned in the stack section. It's not used as a stack it's used as a list.

**Comment by doctordns** [comment]
Two suggestions:
1. Add an example showing Set-Location in the examples for PowerShell 7 showing CD -/+. I'd like to see something like this

```PowerShell
PS C:> Set-Location -Path $ENV:\Systetemroot
PS C:\Windows> Set-Location -Path Cert:
PS Cert:> cd -                          # using Set-Location -Path - using aliases
PS C:\Windows>
```
This could mention that using aliases and implied parameter names, id using **CD -** or **CD +** is useful particularly at the console

2. Mention in the notes that with PowerShell an additional mechanism is available, then described the unnamed stack as noted in the reply to my comment. Using the older stack mechanism and the new path -/+ are fully interoperable. The stacks mechanism seems to rely on Push/Pop-Location. 

3. It would be nice (although this may be an issue with the implementation) to have some way to see the contents of this history list. But I suspect that that is not our problem here! :-).

**Comment by chasewilson** [comment]
1. I've added another example to highlight navigating the history using the alias and the `-`/`+` characters. 

2. My understanding is that these stacks aren't fully interoperable. They are completely separate and serve different purposes. While the history list does use `Push`/`Pop` methods, it's done implicitly and you can't control it. It simply tracks your working location no mater where in the file system or what PSProvider you navigate to. While using `Push-Location` and `Pop-Location` rely on the default, or a named stack. 

```
# Add items to the default stack
C:\Program Files> Push-Location 'C:\Program Files\PowerShell\'
C:\Program Files\PowerShell> Push-Location 'C:\Program Files\WindowsPowerShell\'
C:\Program Files\WindowsPowerShell> Push-Location 'C:\Program Files\PowerShell\6\'
C:\Program Files\PowerShell\6>

# Navigate back using the history list
C:\Program Files\PowerShell\6> cd -
C:\Program Files\WindowsPowerShell> cd -
C:\Program Files\PowerShell> cd -
C:\Program Files>

# Pop the last item off the default stack
C:\Program Files> Pop-Location
C:\Program Files\WindowsPowerShell>

# Using cd - ignores the default stack and goes back to the previous working location
C:\Program Files\WindowsPowerShell> cd -
C:\Program Files> 

# Pop-Location has maintained it's place in the default stack and pops the last location off the stack
C:\Program Files> Pop-Location
C:\Program Files\PowerShell>  
```

You can see that the stacks are completely separate and that `cd -` ignores the default stack. This is the same for a named stack as well. 

3. Currently, there is no way to view the history list. Although, I agree, it would be pretty nice to be able to view it. I've updated the **Path** parameter section just a bit to clear things up a little I hope.

Putting in a PR. Feel free to leave any feedback there as well.

**Comment by doctordns** [comment]
Fantastic.

**Comment by mklement0** [comment]
Re:

> It would be nice (although this may be an issue with the implementation) to have some way to see the contents of this history list.

Even better, it would be nice to be able to _select_ from that list interactively - see https://github.com/PowerShell/PowerShell/issues/11688

**Comment by mklement0** [comment]
See also:

#5360

#5361
