### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by DaveMtb** [MicrosoftDocs/PowerShell-Docs#5334]
The following command in the article doesn't seem to work:
Get-ChildItem -Path C:\WINDOWS\System32 | Out-Host -Paging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f489578-426b-85d6-ed85-b39eee3b7282
* Version Independent ID: 7931dc47-66a8-af08-e0fc-87f3c84ddecc
* Content: [Understanding PowerShell pipelines - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/understanding-the-powershell-pipeline?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/learn/Understanding-the-PowerShell-Pipeline.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/Understanding-the-PowerShell-Pipeline.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @DaveMtb thanks for the feedback. I've checked all Versions of PowerShell and it doen't seem to have any issues. Do you mind giving me some more details? 
What version ove PowerShell you are using? 
What host are you running the command on? E.g. Terminal, ISE, VSCode?

**Comment by sdwheeler** [comment]
@DaveMtb Are you doing this in the PowerShell ISE? If so, paging is not supported. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/out-host?view=powershell-6&WT.mc_id=ps-gethelp#notes

**Comment by DaveMtb** [comment]
Yep! It was through the ISE. Problem solved…  Thx…
