### ISSUE TITLE
PowerShell Documentation Link Redirects to BestBuy

### ISSUE THREAD

**Issue by bubnick** [MicrosoftDocs/PowerShell-Docs#5335]
# Documentation Issue

Error messaged provided by powershell provides link to non-existent documentation

## Context of the issue

- URL to the article (Docs or GitHub URL):
https:/go.microsoft.com/fwlink/?LinkID=13517 (sic)

- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [ ] Version 7.x preview content
  - [X] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Unknown - Unable to verify error in macOS/Linux

## Detailed description of the issue

Attempting to run a script on a machine that has running powershell scripts disabled returns the following error:

`.\foo.ps1 : File C:\foo.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\foo.ps1
+ ~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess`

When navigating to that link it redirects to https://bestbuy.com.

It also appears the url is missing a forward slash, but does not appear to be the cause of the issue.

**Comment by bubnick** [comment]
I just now realized that I missed a 0 when copying the link 😳. Closing issue.

**Comment by tenshi0xx** [comment]
> I just now realized that I missed a 0 when copying the link 😳. Properly copying, redirects to the proper site.
> 
> Closing issue, although unsure if missing forward slash or redirection in general is worth investigating.

5 years later, this happened to me too XD
