### ISSUE TITLE
Missing Content on Setting Transcription via runtimeconfig.json file - v6/7/7.1 content

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#5337]
This page doesn't highlight that transcription logging can be managed via the runtimeconfig.json file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a8b1f5-d7ef-df21-4e86-438f1a721357
* Version Independent ID: 3796d8f1-788a-bb21-8238-30d35f82281f
* Content: [about_Logging - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logging?view=powershell-5.1&viewFallbackFrom=powershell-7.x)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
See also #4216  - need to address both issues when we update the docs for release.

**Comment by sdwheeler** [comment]
@kilasuit  Is this the configuration information you are looking for? https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logging_non-windows?view=powershell-7#configuring-logging-on-a-non-windows-system

If not, can you provide more details?

**Comment by sdwheeler** [comment]
This is documented already.
