### ISSUE TITLE
Need more documentation for call operator, which optionally takes a module

### ISSUE THREAD

**Issue by jazzdelightsme** [MicrosoftDocs/PowerShell-Docs#5340]
The call operator optionally takes a module, which then executes the specified command in the scope of the specified module.

You can probably come up with a better example, but here's one that demonstrates that there are module-private commands available in one of the built-in modules (works in 5.1): 

```
PS C:\> $allCommands = get-command
PS C:\> $inside= & (Get-Module Microsoft.PowerShell.Utility) { get-command }
PS C:\> $allCommands.count
2051
PS C:\> $inside.count
2158
PS C:\>
```

Note that [the about_Scopes page](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7) says "the module does not have its own scope", so my terminology may be incorrect... but the gist of this Issue is that the call operator can accept a module as the first parameter, and a command/scriptblock as a second parameter, which gets executed "inside" the specified module, however you refer to that if it's not "scope".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273225bd-bd1f-478f-6040-098bce77920c
* Version Independent ID: 5fcd4430-a6b8-0438-73c9-29749b804323
* Content: [about_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Note to self - document syntax shown above. Explain module privacy "scope" better.

**Comment by sdwheeler** [comment]
@jazzdelightsme I did some more research and talked with @JamesWTruher about this. We do have an error about module scope that I will fix. But I got clarification for the scenario you describe above.

The invocation operator does not have a parameter as you describe it. What is happening is that `Get-Module` is returning a **ModuleInfo** object and the operator is calling the **Invoke()** method of that object. This allows you to reach into the module's scope and see items that are not exported by the module.

You can do that same operation without using the invocation operator:

```powershell
PS> $mi = Get-Module Microsoft.PowerShell.Utility
PS> (Get-Command).count
2253
PS> $mi.Invoke({Get-Command}).count
2363
```

This is not a special syntax for the invocation operator. So it should not be documented for this operator. And this is considered an anti-pattern that we don't really want to document. If it were to be documented anywhere, it should be documented in the SDK for the [PSModuleInfo.Invoke()](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psmoduleinfo.invoke?view=pscore-6.2.0) method.

**Comment by jazzdelightsme** [comment]
Thanks for the explanation, and the doc updates!
