### ISSUE TITLE
Describe the flow-control / error-display behaviors at the top, fix the code snippets / descriptions

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5348]
The pragmatic summary of how errors are surfaced and how control flows is this:

* _displaying_ the error (_after_ processing the `trap` script block)  and _continuing_ execution (default behavior, without a flow-control statement in the `trap` script block)

* _displaying_ the error and _aborting_ execution (with `break` in the script block)

* _silencing_ the error, but _continuing_ execution (with `continue` in the script block)

If you want to _both_ silence and abort, the only thing that gets you _close_ to is to use `exit` or `return` in the script block, but that doesn't guarantee that processing aborts _overall_.

A few sample commands to illustrate the behaviors:

```powershell
& { trap { "Error found." } 1/0; 'ok' }; 'after'

& { trap { "Error found."; continue } 1/0; 'ok' }; 'after'

& { trap { "Error found."; break } 1/0; 'ok' }; 'after'

& { trap { "Error found."; return } 1/0; 'ok' }; 'after'
```
---

I suggest providing a similar overview  in the "Long description" section and to mention `break` and `continue` in the "Syntax" section explicitly.

Furthermore, the code snippets in "Trapping all terminating errors" don't (fully / meaningfully) reflect the behaviors outlined above and should be fixed.

---

Additionally, it's worth mentioning that `trap`s defined in code that is  _dot-sourced_ do not take effect; to borrow @SeeminglyScience's example from https://github.com/PowerShell/PowerShell/issues/11665#issuecomment-577814339:

```powershell
. { trap { 'something'; continue } }
throw
# Throws normally
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 547896dc-5bba-7844-1852-88f4b0d359b0
* Version Independent ID: 780bf958-3add-6a30-d5b9-ea2ed719e0b5
* Content: [about_Trap - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Trap.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Trap.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
We need to be clearer about the effect of using `break` and `continue`. 

@mklement0 We have addressed the topic of dot-sourced code in the article already. I would argue that dot-sourced trap DO take effect. But, in @SeeminglyScience's example, the trap has already gone out of scope when `throw` happens.

```powershell
PS> . { trap { 'something'; continue }; throw }
something
```

**Comment by mklement0** [comment]
Thanks, @sdwheeler, I hadn't noticed the existing note about dot-sourcing.

Yes, traps take effect in _their_ script, which is fine, but what @SeeminglyScience's example shows is that you cannot _import_ traps into your scope via dot-sourcing.

While that is _implied_ by the current wording, perhaps it couldn't hurt to be more explicit about what that means in practice (for traps in scripts, not functions):

You cannot have a single script with a shared `trap` definition meant to be dot-sourced from multiple other scripts - which is something I've attempted myself, only to realize it doesn't work.

**Comment by mklement0** [comment]
To restate the previous point with hopefully more conceptual clarity:

The primary purpose of dot-sourcing is to import constructs _for later use_ (typically, functions) rather than code that executes _during the act of dot-sourcing_.

Traps loosely fall into that category: just like dot-sourcing a function, it is reasonable to expect to be able to import a trap into your scope in order for it to take effect when the scope's remaining code runs.

It is worth pointing out that this reasonable expectation isn't met.
