### ISSUE TITLE
Prominently advertise the + / - navigation options, emphasize them over the rarely used, too-complex location stacks

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5361]
My sense is that location _stacks_ have seen little adoption, owing to their conceptual complexity and the fact that they're spread across _multiple cmdlets_.

By contrast, the (PS Core-only) `-` / `+` method of navigating back and forth within a _list_ of the 20 most recently visited locations deserves to be prominently featured in the "Description" section, either _before_ mentioning `StackName` or, preferably, _instead_ of it.

Given that the `-` / `+` history is _automatically_ maintained and requires no additional effort, it is far more convenient, more flexible, and far more likely to see widespread adoption than the overly complex location-_stack_ architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f0e6cc-aaa6-78c1-866e-65fa468e15f4
* Version Independent ID: dec46093-f0e6-7148-2f9f-b59caae40069
* Content: [Set-Location (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-location?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Set-Location.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Set-Location.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by doctordns** [comment]
+1 to @mklement0 's comment. Although I am hardly a new PowerShell user, I never knew about named location stacks in PowerShell until just recently when looking at the help files (with the intention of doing just what Michael asks - improving the visibility of this feature.

An update of this page for Pwsh 7 would be useful:

Update the Description on this page to mention the concept of location navigation based on past locations.  Mention that there are two in PWSH 7 -Path +/- or the older named/default navigation stack. That description should note that the PWSH 7 scheme is automatic, whereas the name stack approach requires the use of Pushd/Popd.

The example looks good - and is probably at the right place in the list.

The notes section needs updating too.  It needs to mention the concept of navigation stacks and note that PowerShell 7 has two: one that was in Windows PowerShell, the other new. Then it needs to explain -Path -/- and then follow that by the existing discussion of the older mechanism (most of that existing text is fine..
