### ISSUE TITLE
SVG or other vector version

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#5364]
There should be a SVG, AI, or other vector based version of the powershell hero available for use in presentations and other high resolution areas where the dithering/antialiasing in the jpg format is not desired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73e2e43a-c97d-6a7f-67f6-fffd6cb91610
* Version Independent ID: 0655cb6d-e184-6563-a559-f59da447962f
* Content: [PowerShell Digital Art - PowerShell](https://docs.microsoft.com/en-us/powershell/digital-art)
* Content Source: [reference/digital-art.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/digital-art.md)
* Product: **powershell**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
There is: https://github.com/PowerShell/PowerShell/blob/master/assets/Avatar.svg

Lots of other useful images in that assets folder.
