### ISSUE TITLE
Launching PowerShell

### ISSUE THREAD

**Issue by MarkMcDonald** [MicrosoftDocs/PowerShell-Docs#5366]
After using 'dotnet tool install --global PowerShell' to install how do you launch PowerShell Core by default?

Any search in the search bar or pinned icons just open Windows Powershell, which I then have to use the pwsh command in, which seems a step more than is necessary. The PowerShell Core doesn't appear in the search results.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell Core on Windows - PowerShell](https://docs.microsoft.com/en-gb/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by kleinux** [comment]
After installing I got the message:
```
dotnet tool install --global PowerShell
You can invoke the tool using the following command: pwsh
Tool 'powershell' (version '6.2.4') was successfully installed.
```

I was able to set pwsh as a profile in windows terminal and it just worked
```
{
    // Make changes here to the cmd.exe profile
    "guid": "{0caa0dad-35be-5f56-a8ff-afcee1aa6101}",
    "name": "pwsh",
    "commandline": "pwsh",
    "hidden": false
}
```

Hope this helps

**Comment by MarkMcDonald** [comment]
Not sure I understand, so do I have to launch PowerShell Core from cmd or Windows PowerShell? I can't just have a shortcut in my task bar to launch it directly? Seems a bit odd.

**Comment by kleinux** [comment]
You can launch pwsh directly. I just created a shortcut on my desktop where all i typed into the location field was "pwsh" and that shortcut will launch Powershell Core. You can then pin that anywhere you'd like. Of course, you can also launch it by typing "pwsh" in a command shell or a regular Powershell terminal too.

**Comment by doctordns** [comment]
1. Assuming Windows 10/Server - click on Start, then type PWSH. Assuming you installed using the MSI this starts it just fine.
2. Once you have it installed and running, just create a new taskbar item. OR - cheat.

See bit.ly/Pwsh-install-1 and bit.ly/Pwsh-install-2. The first installs PowerShell 7 and VS Code. The second does some configuration

**Comment by tedonmain** [comment]
I also installed powershell core (pwsh) using the command: dotnet tool install --global PowerShell and pwsh does work. But no matter where I place profile.ps1 it isn't being sourced. This is true also in VSCode where I have set pwsh as my default terminal shell. Where does powershell core always look in Windows for profile.ps1? Funny: this is not a problem on my Mac where I have installed powershell using the same exact command. On my Mac the profile.ps1 is in ~\.config\powershell\Profile.ps1 and it works great if I start powershell (pwsh) at the zsh terminal also also in the integrated terminal in VSCode. So strange that Windows is having such a hard time supporting powershell core. It's sweet running on my Mac.

**Comment by sdwheeler** [comment]
See https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools


Global Tools can be installed in the default directory or in a specific location. The default directories are:

OS | Path
-- | --
Linux/macOS	| $HOME/.dotnet/tools
Windows	| %USERPROFILE%\.dotnet\tools

These locations are added to the user's path when the SDK is first run, so Global Tools installed there can be called directly.

The Global Tools are user-specific, not machine global. Being user-specific means you cannot install a Global Tool that is available to all users of the machine. The tool is only available for each user profile where the tool was installed.

Also note, the global tool name is "PowerShell" but the executable to run is `pwsh`.

**Comment by sdwheeler** [comment]
@tedonmain The profile script is not named `profile.ps1`.  See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_profiles

**Comment by MarkMcDonald** [comment]
Having installed using 'dotnet tool install --global PowerShell' on Windows 10 clicking start and typing 'pwsh' does offer it up, so it's good to know this is a difference between using the MSI and dotnet tool install.

Creating a shortcut and setting the location to 'PWSH' did work, which was nice, doesn't get a nice icon though.

I see references in docs, and some of the linked scripts, mentioning a path of $env:ProgramFiles\PowerShell\ or C:\Program Files\PowerShell\ - I don't seem to have that path so is it installed elsewhere when using the dotnet tool install command?

**Comment by MarkMcDonald** [comment]
Thanks for the help, in this instance I decided to uninstall using the dotnet command and use the MSI instead - nice that the MSI installer also gives you options to add to explorer content menu.

Not sure I fully understand the case for using the dotnet tools install for something like PowerShell.

**Comment by sdwheeler** [comment]
@MarkMcDonald See my previous note. The dotnet tool installs PowerShell in a different location. It does add that to your path. But the currently open session was started before that path was added. You should be able to run it from a new session or from the Start->Run box.
