### ISSUE TITLE
Get-WinEvent file in use error.

### ISSUE THREAD

**Issue by favendanoc** [MicrosoftDocs/PowerShell-Docs#5370]
[Enter feedback here]
Hola, estoy usando Get-WinEvent con varios archivos evtx Filterhashtable y luego realizo un SELECT y un EXPORT-CSV, después de eso intento hacer un REMOVE-ITEM de los archivo evtx y me indica que el archivo esta en uso, como puedo eliminar el bloqueo que genera el Get-WinEvent. 

Hello, I'm using Get-WinEvent with multiple Filterhashtable evtx files and then I perform a SELECT and an EXPORT-CSV, after that I try to make a REMOVE-ITEM of the evtx files and it tells me that the file is in use, as I can remove the lock generated by the Get-WinEvent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c774abdc-a0f9-6392-4ba4-95968f723467
* Version Independent ID: c3049b3f-f46c-b334-d778-69ae9d50257c
* Content: [Get-WinEvent (Microsoft.PowerShell.Diagnostics)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@favendanoc  Can you provide a code example?

**Comment by favendanoc** [comment]
if (Test-Path "logs\EvtAppError_NS.csv") {Remove-Item "logs\EvtAppError_NS.csv"}
Get-WinEvent -FilterHashtable @{Path="logs\*.evtx";Level=2} | Select MachineName, TimeCreated, LogName, ProviderName, Id, Level, @{l='Message';e={$_.Message -replace "[\r\n]"," "}} | Export-CSV "logs\EvtAppError_NS.csv"
Remove-Item "logs\*.evtx" -ErrorAction Stop

**Comment by favendanoc** [comment]
When we have 4 files, the locks during 10 seconds, when process 34 files, cannot get a time of release files.

**Comment by favendanoc** [comment]
I try to retry with this code.

While (Test-Path("logs\*.evtx")) {
Try{
    Remove-Item "logs\*.evtx" -ErrorAction Stop
} Catch {
    Write-Host "File locked, trying again in 5"
    Start-Sleep -seconds 5
}
}

**Comment by favendanoc** [comment]
Each evt. file has between size of 1 and 3 mb, I take the information 7 days ago from 8 different servers. same version.

**Comment by sdwheeler** [comment]
I was able to reproduce your problem in PowerShell 5.1. This problem does not exist in PowerShell 6 and higher. PowerShell 5.1 is maintained by the Windows team but it is not actively being updated. You can report this issue through the Windows Feedback Hub or you can [open a support incident](https://support.microsoft.com/hub/4343728/support-for-business).

**Comment by favendanoc** [comment]
Ok, I will try on PS6, if work, I will upgrade the framework. Thanks.
