### ISSUE TITLE
Add docs about WinCompat DenyList

### ISSUE THREAD

**Issue by anmenaga** [MicrosoftDocs/PowerShell-Docs#5373]
# Documentation Issue
Add info about deny list setting of WinCompat.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [X] Version 7.x preview content
  - [x] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by Richard-LJ** [comment]
added the issue-question label 9 days ago
