### ISSUE TITLE
Does not parse valid json, which contains array

### ISSUE THREAD

**Issue by gogbg** [MicrosoftDocs/PowerShell-Docs#5375]
# The provided [example](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/test-json?view=powershell-7#examples) in docs.microsoft.com is wrong
specifically:
```powershell
"{'name': 'Ashley', 'age': 25}" | Test-Json
```
is treated as valid json whereas it should no be, because single quotes are not valid characters in json.

the valid example should be:
```powershell
'{"name": "Ashley", "age": 25}' | Test-Json
```

# json starting as array cannot be parsed
Example:
```powershell
'[{"name": "Ashley", "age": 25}]' | Test-Json
```
fails with error:
```powershell
Test-Json : Cannot parse the JSON.
At line:1 char:37
+ '[{"name": "Ashley", "age": 25}]' | Test-Json
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9eea7f1-76e8-242f-dde3-cd3a0ec36b46
* Version Independent ID: 3749eef8-2406-df1d-2f3b-3e4a91c97225
* Content: [Test-Json (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/test-json?view=powershell-7&source=docs#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Test-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Test-Json.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@gogbg This is a product issue. Please file an issue  at https://github.com/PowerShell/PowerShell/issues/choose


/cc: @SteveL-MSFT
