### ISSUE TITLE
Example 2 - Bad Splat

### ISSUE THREAD

**Issue by VLoub** [MicrosoftDocs/PowerShell-Docs#5388]
Hi,

you have too many quotes for Property parameter.
Please change it to:
$SplatParam = @{
  Name = 'WindowsProcess'
  ModuleName = 'PSDesiredStateConfiguration'
  Method = Test
  Property = @{
	Path = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
	Arguments = ''
  }
}

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8356fa4-2206-ebf6-6d78-19568f9de1de
* Version Independent ID: 2daf854d-fd76-365d-5954-cf52ea03141b
* Content: [Invoke-DscResource (PSDesiredStateConfiguration)](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/invoke-dscresource?view=powershell-7#feedback)
* Content Source: [reference/7.0/PSDesiredStateConfiguration/Invoke-DscResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PSDesiredStateConfiguration/Invoke-DscResource.md)
* Product: **powershell**
* GitHub Login: @nitinbps
* Microsoft Alias: **nitingup**

**Comment by sdwheeler** [comment]
Fixed
