### ISSUE TITLE
Missing step in quick setup

### ISSUE THREAD

**Issue by thejoecode** [MicrosoftDocs/PowerShell-Docs#5398]
OSX 10.14.6
After running: dotnet tool install --global PowerShell
VS Code could not find powershell with the error: The terminal shell path "/usr/local/bin/pwsh" does not exist
pwsh was installed at ~/.dotnet/tools/pwsh
Creating a link fixed the error: sudo ln -s ~/.dotnet/tools/pwsh /usr/local/bin/pwsh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cac030d-de88-9bf0-5ea8-7213b5d7f088
* Version Independent ID: d025a07e-05e1-ef40-5500-36d3facbcc04
* Content: [Installing PowerShell Core on macOS - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The dotnet tool installer should add  ~/.dotnet/tools to your PATH. The problem is the currently running shell does not have the newly added PATH. Any new shell gets the new PATH. You should be able to start PowerShell from a new shell by typing `pwsh`.

**Comment by chasewilson** [comment]
There is also an open issue in the VsCode repo for the PowerShell not loading the path. It currently say s Windows, however, if you are on OSx, your input would be valuable in assessing the issue. I know you found a fix but if it does happen again, feel free to add on to the thread in the issue:
https://github.com/microsoft/vscode/issues/89747
