### ISSUE TITLE
Not available on MacOS

### ISSUE THREAD

**Issue by roberttoups** [MicrosoftDocs/PowerShell-Docs#5399]
This pages provides the impression that PowerShell 6 supports CMS encryption on non-Windows platforms as it doesn't specifically mention this limitation. The Microsoft.PowerShell.Security module in PowerShell 6 on MacOS does not include the *CMS* cmdlets. It only includes a subset of cmdlets from the Microsoft.PowerShell.Security module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4a5a803-cc58-effe-3d91-5dbceb36847a
* Version Independent ID: 528da8a2-2382-5314-17a0-d9fbdec3fff4
* Content: [Protect-CmsMessage (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Security/Protect-CmsMessage?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Security/Protect-CmsMessage.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/Protect-CmsMessage.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by TravisEz13** [comment]
There is a PR open to bring this to Linux and macOS in 7.1

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/pull/11643

**Comment by roberttoups** [comment]
I appreciate that version 7 will support CMS on MacOS and Linux (stoked actually) but just to cut down confusion, a tech note of some sort should point out in the PowerShell 6 documentation that the related cmdlets are not available for MacOS and Linux.

**Comment by TravisEz13** [comment]
Already done and mentioned in this Issue:  https://github.com/MicrosoftDocs/PowerShell-Docs/commit/8ae3ad6f0952e4d2bd6ef2e4c07eb3a0fea0abb2#diff-83d492a1a9be738c550ae453b853f3caR161
