### ISSUE TITLE
Set-Location docs seriously confusing for people doing a quick&dirty translation from anything non powershell

### ISSUE THREAD

**Issue by loreb** [MicrosoftDocs/PowerShell-Docs#5400]
# Documentation Issue

Moving to a directory via Set-Location or cd does not change the process directory as one would expect from 1. the "cd" alias, and 2. the docs not mentioning it

## Context of the issue

- URL to the article (Docs or GitHub URL):
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-location?view=powershell-7
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [ ] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

I was translating a fairly simple script from linux to powershell (nothing serious); the script changes its current directory and does some simple things in there, but having many instances running in the same directory would confuse it.
Under linux I run the script under setlock or equivalent - lockfile, flock... any utility which locks a file and runs a program with the file locked.

A quick search tells me that to lock a file you're supposed to use
`	[System.IO.File]::Open($path, $mode, $access, "None")`
but passing the lockfile as "lock.txt" (without the full path) creates the lock file in the directory I was in when I launched the script, not the new directory.

Some more searching brought up https://stackoverflow.com/a/4725090 which explains the issue and how to fix it; imho that should be explained in the Set-Location docs, and it should be in such a way that it's difficult to miss, because:
- it's a big break from expectation for anyone that doesn't use powershell often.
- if I can call it "cd", I expect it to work like "cd"
- it's such a basic concept that people unfamiliar with powershell will likely briefly glance at the docs

Linking to why that happens would be nice - at least personally when I discovered that you can eg `cd Env:` or other similar "directories" I quickly went from "powershell sucks" to "wow, neat!"

**Comment by sdwheeler** [comment]
@loreb The problem here is that you are not using PowerShell to create your lock file. You are calling a .NET class directly. In that case you are subject to the mechanics of how the `[System.IO.File]::Open()` method works.

If you created a file using the cmdlet `New-Item`, the file is created in the current folder. For example, consider the following script.

```powershell
'Running script: ' + $MyInvocation.MyCommand.Path
"Current directory: $PWD"
'Creating a new temp folder'
md .\temp
'Set-Location to the new temp folder'
cd .\temp
"Current directory: $PWD"
'Create new file'
new-item lock.txt
cd ..
```

The script creates a new directory and changes into it. The new file is create in the current location. I am starting in `D:\test`. The script is in `D:\test\scripts\doit.ps1`.  When I run this script I get the following output.

```
PS D:\test> .\scripts\doit.ps1 
Running script: D:\test\scripts\doit.ps1
Current directory: D:\test
Creating a new temp folder


    Directory: D:\test

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----          2/3/2020  7:46 PM                temp
Set-Location to the new temp folder
Current directory: D:\test\temp
Create new file

    Directory: D:\test\temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----          2/3/2020  7:46 PM              0 lock.txt

PS D:\test>                                    
```

**Comment by loreb** [comment]
I guess my excessive rambling made my post unclear; sorry if it sounded like a question, I know this is not a powershell support group (thank you for the kind explanation anyway), let me try to explain better.

- I know what is happening ("Some more searching brought up https://stackoverflow.com/a/4725090 which explains the issue and how to fix it")
- I'm using System.IO because I'm creating a file not for its contents but as a lockfile, and searching how to do that in powershell brings up pages such as https://stackoverflow.com/questions/21086051/locking-the-file-while-writing-in-powershell which use .NET
- assuming that using .NET is needed to get an advisory lock, I know how to fix that by setting the current directory in the environment; if I didn't know that I would have just joined $PWD and the lock file name to get an absolute path.

My problem is that the issue is clearly explained eg in https://ss64.com/ps/set-location.html ("PowerShell Location is not the same as...") but the MSDN docs completely omit the subject, so I assume that `cd` works just as in the posix shell, or perl, or cmd.exe,  - that's it.

I trust the issue is explained somewhere else, but if I'm not a powershell person the page describing `Set-Location` is **the** place where I expect an explanation for this kind of gotcha (a short note + a link to the proper explanation).

Does it make more sense?

**Comment by rjmholt** [comment]
It sounds like we should document the fact that `Set-Location` (and others) don't set `$env:CurrentDirectory` by design. See https://github.com/PowerShell/PowerShell/issues/9829 for some discussion there.

It might also be opening an issue in the PowerShell repo to request a cmdlet to lock files

**Comment by UberKluger** [comment]
Regarding the "fix" to the documentation:

> PowerShell supports multiple runspaces per process. Each runspace has its own current directory. This is not the same as [System.Environment]::CurrentDirectory. This behavior can be an issue when calling .NET APIs or running native applications without providing explicit directory paths.

> Even if the location cmdlets did set the process-wide current directory, you can't depend on it because another runspace might change it at any time. You should use the location cmdlets to perform path-based operations using the current working directory specific to the current runspace.

I would suggest completely eliminating the linking of runspaces with the phrase "current directory" (changes italicised).

> "PowerShell supports multiple runspaces per process. Each runspace has its own current *location*. This is not the same as *the process current directory (available in [System.Environment]::CurrentDirectory) and might not even be a file system location (e.g. HKLM:\HARDWARE)*. This *distinction* can be an issue when calling .NET APIs *(either directly or via a constructor when using `New-Object`). As far as the kernel is concerned, APIs are invoked by "the process" and so utilise the process current directory if called* without providing *full* directory paths.

(Deleted reference to native applications since these are separate processes which are started using the current location as the path represented by . when searching for the application and setting the application's initial current directory to the current, or most recent file system, location as would be expected.)

> Even if the location cmdlets did set the process-wide current directory, you *couldn't* depend on it because another runspace might change it at any time *without any indication because it would not affect any runspace's current location (and thus also not any corresponding prompt string)*. *Where possible*, you should use cmdlets to perform *relative*-path based operations *as they will use* the current *location* specific to the runspace *in which they are invoked*. *If the use of .NET APIs is necessary (or just desired), all relative file paths should be prefixed with the runspace's current location (available in `$pwd`) to create the desired absolute path, e.g. to access .\local_directory\sub_file use `"$pwd\local_directory\sub_file"`. Of course, this requires that the current location is actually a file system directory.*
