### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by VectorBCO** [MicrosoftDocs/PowerShell-Docs#5404]
[Link](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets?view=powershell-7) contain paragraph "Multiple parameter sets" with a pickture that describe parameter sets that will not work (left side)
In case if in "Valid parameter set" would be exist parameter set D it will replace all other parameter sets in this block

Example: 
[Parameter (ParameterSetName = 'A', ParameterSetName = 'D')]$param1 
[Parameter (ParameterSetName = 'B', ParameterSetName = 'D', ParameterSetName = 'E')]$param2
[Parameter (ParameterSetName = 'C', ParameterSetName = 'D')]$param3

if $param1 would be selected PSN = 'D' would be walid so $param2 and $param3 could be selected also and this have no sence for parameter sets A, B, C and E

**Comment by sdwheeler** [comment]
In that article, "A", "B", "C", "D" are parameters not parameter sets. The illustration is showing which parameters are in which sets.

**Comment by VectorBCO** [comment]
this is not clear 
how this illustration would looks like in a code?
