### ISSUE TITLE
Need PowerShell examples for parameter sets

### ISSUE THREAD

**Issue by VectorBCO** [MicrosoftDocs/PowerShell-Docs#5406]
page https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7#parametersetname-argument contain next note "For more information about parameter sets, see Cmdlet Parameter Sets." and forward users to this page that does not contain any proper examples for powershell

example: i have module with some number of custom functions, where can I found how to setup default parameter set name per function? ok, per module?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce9c320-4bff-ffcc-fea2-13f890d43537
* Version Independent ID: 7527e0eb-deb1-80fd-4492-2ee14eb54df5
* Content: [Cmdlet Parameter Sets - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/cmdlet/cmdlet-parameter-sets.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/cmdlet-parameter-sets.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
For script-based modules, see https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute

**Comment by VectorBCO** [comment]
is it possible to add cross links?

**Comment by sdwheeler** [comment]
@VectorBCO Yes. There is a gap in the information here. So the fix is more than just cross-linking topics. We will work on improving this information.

**Comment by VectorBCO** [comment]
@sdwheeler thanks
I also reised this ticket through github https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5404 
but looks like it`s joined to incorrect "ticket type"

**Comment by blackmamba-k** [comment]
haha great
