### ISSUE TITLE
Description of cryptographic hash algorithm is inaccurate.

### ISSUE THREAD

**Issue by davidmayo** [MicrosoftDocs/PowerShell-Docs#5412]
The -Algorithm parameter includes this sentence: "A cryptographic hash function includes the property that it is not possible to find two distinct inputs that generate the same hash values."

This is not accurate. Practical collisions have been generated for at least MD5 and SHA1. I would suggest a rewrite to something like "A cryptographic hash function includes the property that it is infeasible to find two different files with the same hash value."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0be20ca-3996-7ff9-04ba-f2cc473513ad
* Version Independent ID: 8f5975ef-d031-8254-bc66-252f44964dee
* Content: [Get-FileHash (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Get-FileHash.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@davidmayo Thanks for the feedback. We would welcome a PR to change the description.
