### ISSUE TITLE
How to scroll up?

### ISSUE THREAD

**Issue by kid1412621** [MicrosoftDocs/PowerShell-Docs#5413]
is possible to scroll backwards?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3585e6a9-5868-ee46-e3ce-8fab9730728a
* Version Independent ID: bbb2cac0-8573-82e4-9b8d-d3de71835959
* Content: [Out-Host (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/out-host?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Out-Host.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@kid1412621 I am not sure I understand your question. What does this have to do with `Out-Host`?

**Comment by kid1412621** [comment]
@sdwheeler sorry, I mean `Out-Host` with `-paging`.

**Comment by sdwheeler** [comment]
No way to scroll back to the previous page with `Out-Host -Paging`.
