### ISSUE TITLE
Use of CodeSigningCert requires private key

### ISSUE THREAD

**Issue by EEaglehouse** [MicrosoftDocs/PowerShell-Docs#5414]
The instructions in the Example 1 section states the CodeSigningCert parameter to using Get-ChildItem in the Cert: store limits the certificates retrieved to those with code-signing authority. Omitted was that if the certificate does not have a private key, that it will not be returned in the results, even if it does have code-signing authority.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f1f8a2-c6c0-fece-1f45-b676f31d2c0c
* Version Independent ID: 0249e978-7402-b03f-e6ba-1bd781a58c26
* Content: [Set-AuthenticodeSignature (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-authenticodesignature?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md)
* Product: **powershell**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by sdwheeler** [comment]
@SteveL-MSFT Is this by design or is this "bug".

**Comment by TravisEz13** [comment]
@EEaglehouse The intent of this is to find certificates that can actually sign, which requires the certificate have a private key.  So, this is by design.

**Comment by EEaglehouse** [comment]
This cost me several hours trying to debug what I thought I was doing wrong in order to work around this unintuitive behavior. Thank you for confirming the information.
Web articles about Code signing is a black-box area and consists overwhelmingly of poor documentation, noise, and incomplete examples. In part, this is due to the terribly complicated nature of certificates. In an effort to save others the pain that I went through, would you perhaps have someone add a one-line statement documenting this "design" of the CodeSigningCert option to circumvent that rabbit-hole.
A single sentence like the following would have immediate benefits: "Certificates without private keys will not be included."
