### ISSUE TITLE
Suggested improvements to how the -replace (replacement operator) is documented

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5416]
#4417 and #5415 show that it currently isn't easy to find the relevant information about the syntax of the `<substitute>` (replacement text  / expression) operand:

* The link to the `about_Regular_Expression` topic at the bottom is generally easy to miss and feels like an afterthought.
* More importantly:  Clicking on `about_Regular_Expression` is not conceptually obvious, given that _the substitution operands  are _not_ regular expressions themselves_, and the language used _is a convention that .NET chose_ that applies in _no other context than `-replace`_. 
* Finally, linking to the regex topic _as  a whole_ is not specific enough.

This could be helped as follows:

* Provide a link to the _specific section_ inside `about_Regular_Expressions`
* _in context_
* of a - new - example commands that demonstrate the substitution syntax briefly.

Something like the following:

---

The `<substitute>` operand is allowed to contain placeholders that reference the results of the matching operation, such as `$&` to refer what was matched as a whole, and `$1` to refer to the first capture group's match (use `$$` to represent a _literal_ `$`); e.g.:

```powershell
"book" -replace 'b', '($&)'
```

```Output
(b)ook
```
For more examples and information about what other placeholders are supported, see
[Substitutions in Regular Expressions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions#substitutions-in-regular-expressions).

---

Additionally, consider the following:

**Conceptually, we have 3 fundamental forms of `-replace`, which are worth contrasting succinctly in the "Replacement Operator" section**:

* With _what the user intends to be_ string _literals_; to be able to do that, users need to know the following:
    * To treat the `<original>` operand as a literal (this name is confusing, incidentally), regex metachars. must be individually `\`-escaped, or `[regex]::Escape()` must be applied to the whole value.
  * To treat the `<substitute>` operand as a literal, `$` chars. must be individually _doubled_, or `.Replace('$', '$$')` must be applied to the whole value.

* With a substitution string that contains _placeholders that reference matching results_ (covered above).

* With a _script block_ that allows _fully dynamic substitutions_. 
   * This form is currently described in a separate section, which I suggest folding into the "Replacement Operator" section, so as to contrast these 3 fundamental forms directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50bd0dc3-279b-baea-5c19-823e0bc44534
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
PR submissions would be helpful.
