### ISSUE TITLE
Make regex example commands use single-quoted strings

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5417]
Unless PowerShell's string expansion is truly required, it's good habit to form and recommend to other to use _single-quoted_ strings for:

* _regex_ operands (`-match`, `-replace`, ...)
* the `-replace` operator's _substitution operand_.

The reason is that `$` is a metacharacters in these constructs, and using `"..."` may result in confusion over who interprets `$`-prefixed tokens: is it PowerShell, up front, or is the _regex engine_ that processes the resulting strings?

The linked topic and `about_Comparison_Operators` currently contain numerous example commands that needlessly use `"..."` rather than `'...'`.
I suggest changing them all to using single-quoting (except perhaps for one to demonstrate the pitfalls).

For instance, a current example command is:

```powershell
# Should be:
#     'Gobble' -replace 'Gobble', '$& $&'
"Gobble" -replace "Gobble", "$& $&"
```

This _happens_ to work, because `&` isn't a valid PowerShell variable identifier, so it leaves the `$&` alone, and the regex engine receives it as-is.

A somewhat contrived example to show that `"..."` can have unexpected side effects:

```powershell
$1 = 'hi' # I've seen such variable names in the wild
'Gobble' -replace 'Go(bb)le', "$& $1"  # !! $1 is expanded *by PowerShell*
```

That is, instead of returning `Gobble bb` (which is what would happen with `'...'` quoting), `Globble hi` is returned, because `$1` was recognized as a variable reference by PowerShell and therefore expanded.

If expansion _is_ needed before the regex engine sees the result, the pass-through instances should be `` ` ``-escaped; e.g.:

```powershell
$var = 'hi'
'Gobble' -replace 'Go(bb)le', "`$& $var `$1"  # -> 'Gobble hi bb'
```

In general, I suggest using quoting consistently in _all_ examples:

* Always use `'...'` for verbatim content
* Use `"..."` only if expansion is needed (or perhaps to make embedded `'` chars. easier).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e504278a-f2e0-17c9-12ca-a86b56cba215
* Version Independent ID: ac918b8d-aece-5c59-2a88-64c1a91ff5f5
* Content: [about_Regular_Expressions - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by PLogFinder** [comment]
Unfinished business - this (example in the Warning section of the doc):
'Hello World' -replace '(\w+) \w+', '`$1 Universe'

should be offering these two options:
'Hello World' -replace '(\w+) \w+', "`$1 Universe"
'Hello World' -replace '(\w+) \w+', '$1 Universe'
That is, EITHER: use double quotes, and backtick (escape) the dollar; OR use single quotes on the whole replace string - NO backtick in this second case.
If you need to substitute other variables, use the first; if you don't, the second is easier to read.
