### ISSUE TITLE
Script Can't load

### ISSUE THREAD

**Issue by he852100** [MicrosoftDocs/PowerShell-Docs#5423]
[Enter feedback here]

# Steps to reproduce

```powershell
Install-Script -Name iwr-tests 
sh> get-command Invoke-Endpoint

```

# Expected behavior

```none

```

# Actual behavior

```none
Get-Command: The term 'Invoke-Endpoint' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

# Environment data

```none
PSVersion                      7.0.0-daily.20200201
PSEdition                      Core
GitCommitId                    7.0.0-daily.20200201
OS                             Linux 4.9.112-perf #1 SMP PREEMPT …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5395e4d6-0468-52b9-d318-7121ec9a98a7
* Version Independent ID: 4d337f43-8ebe-ccd3-e7fd-c6324a5be09e
* Content: [Install-Script (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-script?view=powershell-7)
* Content Source: [reference/7.0/PowerShellGet/Install-Script.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PowerShellGet/Install-Script.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
`Install-Script` downloaded the file `Iwr-tests.ps1`. You did not run that script. You tried to run a function defined in that script but that function is not loaded in your current session. You need to dot-source the script to get that function loaded. For example:

```powershell
Install-Script -Name iwr-tests 
. $home\Documents\PowerShell\Scripts\iwr-tests.ps1
get-command Invoke-Endpoint

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Invoke-Endpoint
```
