### ISSUE TITLE
How to filter

### ISSUE THREAD

**Issue by he852100** [MicrosoftDocs/PowerShell-Docs#5426]
[Enter feedback here]

> Specifies a filter based on the PackageManagement provider-specific search syntax. For NuGet modules, this parameter is the equivalent of searching by using the Search bar on the PowerShell Gallery website.

how to use?

-name xxx -filter 'PackageTypes=Windows' ?

-filter 'PackageTypes=Windows&Categories=function' ?
![Screenshot_20200208_183248](https://user-images.githubusercontent.com/26913892/74083645-a6fcd900-4aa1-11ea-9ad7-d8401d4c073d.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de1480ca-427b-b0f1-0ef1-99ae5f7e524a
* Version Independent ID: 33f38b29-e0bb-4158-e4ed-cbe071a8bffb
* Content: [Find-Module (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/find-module?view=powershell-7)
* Content Source: [reference/7.0/PowerShellGet/Find-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PowerShellGet/Find-Module.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by chasewilson** [comment]
Hi @he852100. Thanks for the question. As the doc states in example 8:

"For a NuGet-based repository, the Filter parameter searches through the name, description, and tags for the argument."

So all you have to do is add a string to the filter param that can be found in a module name, description, or tag and it will find those modules. 

```powershell
Find-Module -Filter AppDomain
```
```Output
Version    Name              Repository           Description
-------    ----              ----------           -----------
1.0.0.0  AppDomainConfig     PSGallery            Manipulate AppDomain configuration...
1.1.0    ClassExplorer       PSGallery            Quickly search the AppDomain for classes...
```

**Comment by he852100** [comment]
```powershell
/sh> find-module -name 'psreadline' -filter 'Windows'                                                                   Find-Package: /root/.powershell-daily/Modules/PowerShellGet/PSModule.psm1:8873                                                              Line |                                                                8873 |          PackageManagement\Find-Package @PSBoundParameters | Microsoft …                                                                  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          | No match was found for the specified search criteria and            | module name 'psreadline'. Try Get-PSRepository to see all           | available registered module repositories.
```

**Comment by sdwheeler** [comment]
@he852100 The PSReadLine module does not have 'Windows' in any of those fields.
