### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by af7567** [MicrosoftDocs/PowerShell-Docs#5434]
The link in the Binary Archives installation section doesn't exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell Core on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Can you be more specific? I don't see a problem with any links there.

**Comment by af7567** [comment]
Yes, sorry. It's the following line in the Installation - Binary Archives section
```
# Download the powershell '.tar.gz' archive
curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.0.0/powershell-7.0.0-linux-x64.tar.gz
```

**Comment by sdwheeler** [comment]
Ok, that will be the correct path when PowerShell 7 releases next week. If you want the latest RC build use https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.2/powershell-7.0.0-rc.2-linux-x64.tar.gz.

**Comment by Speedfreak1** [comment]
#
![4b3b134217bac2871581342693374](https://user-images.githubusercontent.com/60798471/74253556-e3c20d80-4cf7-11ea-9aba-c634d338fe75.jpg)https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5434#issue-562934209

**Comment by Speedfreak1** [comment]
> ![4b3b134217bac2871581342693374](https://user-images.githubusercontent.com/60798471/74253556-e3c20d80-4cf7-11ea-9aba-c634d338fe75.jpg)[#5434 (comment)](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5434#issue-562934209)

**Comment by Speedfreak1** [comment]
![15814367720945408955026982491770](https://user-images.githubusercontent.com/60798471/74253885-5a5f0b00-4cf8-11ea-82b6-93c7d6853f19.jpg)
M
