### ISSUE TITLE
ForEach-Object -Parallel cmdlet needs clarification about using variable scope

### ISSUE THREAD

**Issue by PaulHigin** [MicrosoftDocs/PowerShell-Docs#5436]
# Documentation Issue
This is related to Issue (PowerShell/PowerShell#11817).  Using variables can be used in nested ForEach-Object -Parallel calls, but need to be defined in each scope.  This needs to be made clear in the documents (and also about_Concurrency document when it is written).

Waiting on https://github.com/PowerShell/PowerShell/pull/14548

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [x] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
Copied from https://github.com/PowerShell/PowerShell/issues/11065

> This is the by design behavior of the PowerShell eventing. The C# event is triggered on a background thread, but that event handler is not the Action script block you specified here, but a handler generated by PowerShell to queue an event in the session. That queued event will trigger the script block action to run on the pipeline thread, so when the pipeline thread is blocked, the action won't be executed.
