### ISSUE TITLE
Update the PowerShell lifecycle document for libmi support for various linux distros

### ISSUE THREAD

**Issue by adityapatwardhan** [MicrosoftDocs/PowerShell-Docs#5437]
# Documentation Issue
The powershell lifecycle document needs to be updated for libmi related support for linux distros.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [ ] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Linux

## Detailed description of the issue

---
#### Document Details

 *Do not edit this section. It is required for docs.microsoft.com  GitHub issue linking.*

* ID: 0d9a43d3-9571-389c-56ab-7d42a53bf5b1
* Version Independent ID: c138e6a8-fd80-bd64-25ac-24e774e09421
* Content: [PowerShell Core Support Lifecycle - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7)
* Content Source: [reference/docs-conceptual/PowerShell-Support-Lifecycle.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/docs-conceptual/PowerShell-Support-Lifecycle.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by TravisEz13** [comment]
@adityapatwardhan What distros have the issue?

**Comment by adityapatwardhan** [comment]
I believe libmi has issues on Alpine, linux-Arm32, linux-Arm64, centOS 8, Debian 10 & 11.

**Comment by TravisEz13** [comment]
and all snap installs regardless of distro, I'm not sure how the dotnet tool install would behave.

**Comment by TravisEz13** [comment]
Ubuntu 20.04 won't work with libmi

**Comment by sdwheeler** [comment]
Fixed in #8148
