### ISSUE TITLE
mandatory parameters

### ISSUE THREAD

**Issue by chrisj-au** [MicrosoftDocs/PowerShell-Docs#5438]
Zero information about using splatting with mandatory parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5319c2f0-656f-d2a6-577b-4d3e81ecf79f
* Version Independent ID: e12ddb02-4549-2bee-39fc-e6f902f7da25
* Content: [about_Splatting - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Splatting.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Splatting.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
@chrisj-au thanks for the feedback. Is there some information that should be added other than what is known? I don't believe splatting changes the interaction for mandatory parameters?

**Comment by chasewilson** [comment]
Hey @chrisj-au I'm going to close this issue for now. Feel free to respond with more information and we can revisit as needed.
