### ISSUE TITLE
Get-services for  remote servers

### ISSUE THREAD

**Issue by NikhilRajNR** [MicrosoftDocs/PowerShell-Docs#5453]
What is new changes to get services from remote servers as for powershell 5.1 it is "Get-service -ComputerName "xyz" -Credential $cred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da4762f-af6c-6050-f245-7eea3c2c1793
* Version Independent ID: 52b4131a-0ccb-3942-1b13-7b57faf329d5
* Content: [Get-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-7.x#feedback)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @NikhilRajNR , Thanks for the question. As far as I know, there is no `-Credential` parameter. If you are wanting to run the command on remote servers, you can check out the [PowerShell Remoting section](https://docs.microsoft.com/powershell/scripting/learn/remoting/running-remote-commands) of the docs to find the best option for your situation.

If I'm misunderstanding your questions, I apologize and if you wouldn't mind clarifying your question that would be helpful.

**Comment by chasewilson** [comment]
@NikhilRajNR, I'll be closing this issue for now. Feel free to open a new issue with more information or respond here and we will do our best to help.
