### ISSUE TITLE
GA Dates?

### ISSUE THREAD

**Issue by SeanCLeavitt** [MicrosoftDocs/PowerShell-Docs#5456]
Could you please provide a table as to when the various PowerShell Core versions became generally available?  This can help us prioritize when we should start moving up to the latest versions and how old our currently used versions are.  Thank you!

PowerShell Version              Date
PowerShell 7.1                     YYYY/MM/DD
PowerShell 7.0                     YYYY/MM/DD
PowerShell 6.0                     YYYY/MM/DD
PowerShell 5.1                     YYYY/MM/DD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
PowerShell Version | Date
--  | --
PowerShell 7.1 | currently in development
PowerShell 7.0 | TBD - target mid-March 2020
PowerShell 6.2.4 | 2020-01-27
PowerShell 6.2.0 | 2019-03-28
PowerShell 6.1.0 | 2018-09-13
PowerShell 6.0.0 | 2018-01-10
PowerShell 5.1 |  2017-01-19
