### ISSUE TITLE
Changing shell versions

### ISSUE THREAD

**Issue by KevinLeeBuchan** [MicrosoftDocs/PowerShell-Docs#5458]
I ran across this when I was trying to figure out how to debug a Posh script that used a 32-bit DLL.  Saved my sanity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919fe42a-edb9-c950-1405-ae723bb6a48e
* Version Independent ID: 781d1d43-834f-7e39-cc60-8905d5803f9b
* Content: [Using Visual Studio Code for PowerShell Development - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/components/vscode/using-vscode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/using-vscode.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Thanks for the feedback. I am glad it helped.
