### ISSUE TITLE
Default timeout when SMTP "Quit" is sent?

### ISSUE THREAD

**Issue by keschnei42** [MicrosoftDocs/PowerShell-Docs#5461]
We have noticed that the send-mailmessage powershell command doesn't immediately send an SMTP "Quit" command until 60 or more seconds later.  Is this by design and what is the maximum wait it can have?

**Comment by TravisEz13** [comment]
This command is obsolete and these .NET will not make these types of fixes.

**Comment by sdwheeler** [comment]
This is by design. The cmdlet doesn't actually manage the SMTP session. The cmdlet uses the (now deprecated) [SmtpClient](https://docs.microsoft.com/dotnet/api/system.net.mail.smtpclient.dispose) class. 

> The SmtpClient class implementation pools SMTP connections so that it can avoid the overhead of re-establishing a connection for every message to the same server. An application may re-use the same SmtpClient object to send many different emails to the same SMTP server and to many different SMTP servers. As a result, there is no way to determine when an application is finished using the SmtpClient object and it should be cleaned up.

Eventually the **Dispose()** method is called, which send the **QUIT** message.

**Comment by keschnei42** [comment]
Thanks, that is what we suspected.  We reached the github comment page from the Powershell page for the command.  It looks like the current suggestion is to use mailkit instead.  It appears someone tried to make a new send-mailmessage based on mailkit but it was shutdown:
https://github.com/PowerShell/PowerShell/pull/10246

**Comment by TravisEz13** [comment]
@keschnei42 I don't see where it was shut down.  They were just asked to use the current development model for new modules.

**Comment by keschnei42** [comment]
@TravisEz13  Sorry, I may have my terms wrong.  I meant more that it sounds like the Powershell committee is pending a decision on if it will ship with later Powershell:

"@PowerShell/powershell-committee reviewed this, we appreciate this work, but ask that this be a module published to PSGallery. A decision whether this ships in PowerShell will be decided later."

**Comment by TravisEz13** [comment]
@keschnei42 This is the development model we are trying to take when we can.  The cmdlet is developed independently.  Only once it's developed, is the decision to include it in PowerShell made.  No decision is currently Pending.
