### ISSUE TITLE
Documentation Issue -- misses mentioning SLES12SP3 from SuSe

### ISSUE THREAD

**Issue by DoctorWho8** [MicrosoftDocs/PowerShell-Docs#5464]
# Documentation Issue

Ideally the information for OpenSuse will work, but ideally SLES12SP3 should also be included. And Version Seven is still being tested, so most would grab 6.2.4 would use that, so the versioning should be agnostic.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [X] Version 7.x preview content
  - [x] Version 7.0 content
  - [X] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Yes-Linux or WSL

## Detailed description of the issue

I run Suse SLES12SP3 as part of the WSL methods here.  And naturally I needed to tweak the information for 6.2.4 to make it work, in this case replacing the 7 in the directory creation to the 6 instead. Same with making the soft link for the pwsh to /usr/bin/ entry.

**Comment by sdwheeler** [comment]
@TravisEz13 Can you comment on our support of this distro?

**Comment by TravisEz13** [comment]
This is an interesting problem.  We no longer have the ability to test the equivalent of SLES 12 SP 3, but it's still supported by the distribution maintainer and .NET Core

OpenSUSE 42.3 is EOL and no longer supported.

cc @joeyaiello 

In the mean item @DoctorWho8, I'd recommend you file a distribution support request:  https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Distribution-Request&template=Distribution_Request.md&title=Distribution+Support+Request

**Comment by sdwheeler** [comment]
Closing this issue pending product testing or changes.
