### ISSUE TITLE
Powershell: naming convention for bool functions

### ISSUE THREAD

**Issue by realrubberduckdev** [MicrosoftDocs/PowerShell-Docs#5465]
This had been discussed at [stackoverflow](https://stackoverflow.com/questions/39913481/powershell-naming-convention-for-bool-functions) but I do not see any approved verb on the official list.

The suggested ones:
`Assert-IsApple` implies fail if not apple, think in lines of existing NUnit convention.
`Test-IsApple` implies it is a unit test, again NUnit convention.

So what is the convention for writing a boolean returning function like `IsApple()`?
`Is-Apple` shows `uses unapproved verb` warning on vscode. Not having a hyphen separated case makes this method stand out in our code base.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edfbab86-9144-1866-2765-938a5cc68ed7
* Version Independent ID: b4035200-8b55-c70c-7a29-4de085c87e1c
* Content: [Approved Verbs for PowerShell Commands - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.x)
* Content Source: [reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@realrubberduckdev `Assert` or `Test` are the correct verbs to use. Which one you use probably doesn't matter. Your choice might depend on the context of use. Does the use case map to a Diagnostic test or a Lifecycle test?

```
PS> Get-Verb Assert,Test                                                                        
Verb   AliasPrefix Group      Description
----   ----------- -----      -----------
Test   t           Diagnostic Verifies the operation or consistency of a resource
Assert as          Lifecycle  Affirms the state of a resource
```
