### ISSUE TITLE
Get-Verb not Windows-only, available in 6 and 7

### ISSUE THREAD

**Issue by rjmholt** [MicrosoftDocs/PowerShell-Docs#5466]
```
> Get-Verb | select -first 1

Verb AliasPrefix Group  Description
---- ----------- -----  -----------
Add  a           Common Adds a resource to a container, or attaches an item to another item

/Users/rjmholt
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

(Also tried it with 6 on my Mac)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78a06ee-5b1b-94d1-dc09-5059cd78444f
* Version Independent ID: fae67694-743a-5e4e-eef7-dd45eb8decf4
* Content: [Release history of modules and cmdlets - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions?view=powershell-7)
* Content Source: [reference/docs-conceptual/whats-new/cmdlet-versions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/cmdlet-versions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Get-Verb is listed twice. In PS5.1 it was a function in M.P.Core. It moved to M.P.Utility for 6.0+. I fixed the doc.
