### ISSUE TITLE
Need to document new second hop behavior for interactive remote sessions

### ISSUE THREAD

**Issue by PaulHigin** [MicrosoftDocs/PowerShell-Docs#5468]
# Documentation Issue
This is related to PR: https://github.com/PowerShell/PowerShell/pull/11920

Interactive remoting second hop has been restricted to work only form within a WinRM session, but now works for any interactive remoting session.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [x] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
From https://github.com/PowerShell/PowerShell/pull/11920
> Interactive session second hop support was added a while ago, but current behavior is to restrict
> a second hop to work only from a WinRM remote session. This is an unnecessary restriction and
> this PR allows both Enter-PSSession and Enter-PSHostProcess to work from within any interactive
> remote session.

@chasewilson Can you add a note for "New in 7.1" in the SSH article?
