### ISSUE TITLE
Common parameters action in nested calls

### ISSUE THREAD

**Issue by metablaster** [MicrosoftDocs/PowerShell-Docs#5470]
# NOTE
To make this short and focused I'll only mention WarningAction and WarningVariable but it applies to errors and infos as well.

# Documentation says:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7#warningvariable

**Note**
**The WarningVariable parameter does not capture warnings from nested calls in functions or scripts.**

Unless I'm wrong this means that warnings from nested calls do not get captured into a warning variable?

# Steps to reproduce and test the above statement
**NOTE: I named these functions "recursive", but these are nested calls ofc.**

```powershell
function Test-WarningRecursiveInternal
{
	[CmdletBinding()]
	param ()

	Write-Debug -Message "[$($MyInvocation.InvocationName)] Warning preference is: $WarningPreference"

	Write-Warning -Message "$($MyInvocation.MyCommand.Name)"
}

function Test-WarningRecursive
{
	[CmdletBinding()]
	param ()

	Write-Debug -Message "[$($MyInvocation.InvocationName)] Warning preference is: $WarningPreference"

	Test-WarningRecursiveInternal

	Write-Warning -Message "$($MyInvocation.MyCommand.Name)"
}
```

 # Test case 1
```powershell
Write-Debug -Message "[$($MyInvocation.MyCommand.Name)] Warning preference is: $WarningPreference"
Test-WarningRecursive -WV wv -WA "SilentlyContinue"
```

## Expected output (only nested call is shown since WV is not used)
```powershell
DEBUG: [Resume-Warning.ps1] Warning preference is: Continue
DEBUG: [Test-WarningRecursive] Warning preference is: SilentlyContinue
DEBUG: [Test-WarningRecursiveInternal] Warning preference is: SilentlyContinue
Test-WarningRecursiveInternal
```

## Actual output (nested call is affected as well)
```powershell
DEBUG: [Resume-Warning.ps1] Warning preference is: Continue
DEBUG: [Test-WarningRecursive] Warning preference is: SilentlyContinue
DEBUG: [Test-WarningRecursiveInternal] Warning preference is: SilentlyContinue
```

# Test case 2
```powershell
Write-Debug -Message "[$($MyInvocation.MyCommand.Name)] Warning preference is: $WarningPreference"
Test-WarningRecursive -WV wv -WA "SilentlyContinue"

Write-Information -MessageData "Show variable contents:"
$wv
```

## Expected output (nested call is not captured into WV, but shown!)
```powershell
DEBUG: [Resume-Warning.ps1] Warning preference is: Continue
DEBUG: [Test-WarningRecursive] Warning preference is: SilentlyContinue
DEBUG: [Test-WarningRecursiveInternal] Warning preference is: SilentlyContinue
Test-WarningRecursiveInternal
Show variable contents:
Test-WarningRecursive
```

## Actual output (nested call is captured, nested call is shown "before" the variable)
```powershell
DEBUG: [Resume-Warning.ps1] Warning preference is: Continue
DEBUG: [Test-WarningRecursive] Warning preference is: SilentlyContinue
DEBUG: [Test-WarningRecursiveInternal] Warning preference is: SilentlyContinue
Show variable contents:
Test-WarningRecursiveInternal
Test-WarningRecursive
```

Basically all nested calls are being captured into a variable, this is good, and I really like this, but misleading documentation makes me think that I'm dealing with a bug and that my code may not work as expected in the future if the docs are right.

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307b69cd-d651-db61-3ab0-6a357105c791
* Version Independent ID: f83b7011-1b36-45aa-93ff-e1b03536378d
* Content: [about_CommonParameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
@metablaster thank you for pointing this out! The information was incorrect and the docs are being updated. You should see the updates within 24 hours or you can check out the pr when it is linked. 

Thanks again!
