### ISSUE TITLE
-AcceptLicense missing from cmdlet

### ISSUE THREAD

**Issue by dgauthier99** [MicrosoftDocs/PowerShell-Docs#5475]
When I add the -AcceptLicense parameter to Install-Module,
    Install-Module : A parameter cannot be found that matches parameter name 'AcceptLicense'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76b3f8b-5a1d-d3c1-42eb-f104c229a148
* Version Independent ID: c5db528f-5b8a-e677-6af0-1162166034bc
* Content: [Modules Requiring License Acceptance - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/module-license-acceptance?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/gallery/concepts/module-license-acceptance.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/concepts/module-license-acceptance.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@dgauthier99 You are not running the latest version of PowerShellGet. The version (1.1) that ships with PowerShell 5.1 does not have that feature.

**Comment by vazome** [comment]
@sdwheeler I think the article must be edited, it genuinely shows such option in version 5.1

https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-5.1

**Comment by sdwheeler** [comment]
[Update PowerShellGet for Windows PowerShell 5.1](https://learn.microsoft.com/powershell/gallery/powershellget/update-powershell-51)
