### ISSUE TITLE
Your persistent drive examples leave out "-Scope Global"

### ISSUE THREAD

**Issue by trboomer** [MicrosoftDocs/PowerShell-Docs#5477]
You examples are faulty. If you don't include "-Scope Global" along with "-Persist" the drives will not persistent beyond the powershell session. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc35d6c-d927-8fa2-3817-086e9eb770fa
* Version Independent ID: a45957af-1dfa-226b-c4d4-2a84b0e82962
* Content: [New-PSDrive (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @trboomer, thanks for the feedback. As far as my testing and understanding goes, those are two separate outcomes for a PSDrive.

If you use the **Persist** parameter, a new Letter Drive is created and is accessible as a network drive regardless of how many sessions you open. 

When using the **Scope** parameter, you are creating a temporary PSDrive that is accessible to the scope you define. If you write a function the creates a temporary PSDrive, If you don't define **Scope** as "Global", it won't be accessible outside that function. The **Scope** scope parameter is intended more for programmatic action, whereas the **Persist** parameter is meant for long term  requirements.

@sdwheeler feel free to correct me if I'm wrong.

**Comment by chasewilson** [comment]
@trboomer , after some further testing, we found out that when you run a script, your described action is needed. We will adjust the docs to make sure this is known. Thank you for pointing this out.
