### ISSUE TITLE
search all logs example

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#5481]
An example to search all logs, something you can't even do in event viewer.  For some reason there's a 256 limit to the number of lognames, so foreach-object is needed.  I don't know why that would matter over the pipe, but it does.

```powershell
get-winevent -listlog * | foreach { get-winevent @{ logname = $_.logname; starttime = '2/25' } -ea 0 } | where message -match error
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c774abdc-a0f9-6392-4ba4-95968f723467
* Version Independent ID: c3049b3f-f46c-b334-d778-69ae9d50257c
* Content: [Get-WinEvent (Microsoft.PowerShell.Diagnostics)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hi @jszabo98, thanks for the feedback. I'm guessing this is a request for an example to be added. I just wanted to clarify though. Do you mind clarifying what you mean by the 256 limit?

**Comment by jszabo98** [comment]
Yes, I thought that would be a good example.  If you pass more than 256 names of logs to get-winevent, it errors out.  The error message is better in Powershell 7.

```powershell
get-winevent -ListLog * | get-winevent
Get-WinEvent: Log count (445) is exceeded Windows Event Log API limit (256). Adjust filter to return less log names.

get-winevent -ListLog * | select -first 256 | get-winevent
```

**Comment by chasewilson** [comment]
@jszabo98 Thanks again for your feedback. We took a look at all the current examples and think we have pretty good range to show the capabilities. However, you did point out the Windows API limit. We've update the docs to reflect that and show the work around you with the `foreach` loop. If you want to take a look at the PR  and provide any feedback on it, it's linked above

**Comment by jszabo98** [comment]
Oh, I see.  It's a note under -LogName.  It's definitely an improvement.
