### ISSUE TITLE
We should document PowerShell-IoT module

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#5484]
# Documentation Issue

This is published on the gallery and repo is here:
https://github.com/powershell/powershell-iot

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [ ] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

## Detailed description of the issue

cc @anmenaga

**Comment by sdwheeler** [comment]
@SteveL-MSFT Is this planned to ship in 7.1? If not then we should ship the MAML in the Gallery package.
