### ISSUE TITLE
Microsoft.PowerShell.Commands.PSRepositoryItemInfo not documented

### ISSUE THREAD

**Issue by yobyot** [MicrosoftDocs/PowerShell-Docs#5487]
Microsoft.PowerShell.Commands.PSRepositoryItemInfo not documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 772e6089-efe5-95ff-b863-b9ce622239a6
* Version Independent ID: 87643ffc-385e-a865-bb1d-ec3f48d73072
* Content: [Get-InstalledModule (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershell-7)
* Content Source: [reference/7.0/PowerShellGet/Get-InstalledModule.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PowerShellGet/Get-InstalledModule.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by chasewilson** [comment]
@yobyot Thanks for notifying us about this. This type doesn't exist anymore. We are updating the docs to be more accurate. 

Thanks again!

**Comment by james-garriss** [comment]
It's listed as the output of Install-Module:

https://learn.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershellget-3.x#outputs
