### ISSUE TITLE
Language specification

### ISSUE THREAD

**Issue by scriptingstudio** [MicrosoftDocs/PowerShell-Docs#5500]
It is time to update Language specification. It has not updated since V3.

**Comment by doctordns** [comment]
This has never been a priority. And given the team's focus, not sure there is much urgency in an update.  Although I agree that an update would be.nice.

Given that this repo is open source I am sure any efforts to do the update would be welcome. Is that an offer?

**Comment by sdwheeler** [comment]
I have a side project to work on converting the exist v3 specification to Markdown so that it can be published here. That project is low priority for me. But the goal is to get it converted so that it could be maintained by the community.
