### ISSUE TITLE
Array Location Error

### ISSUE THREAD

**Issue by JordanTheITGuy** [MicrosoftDocs/PowerShell-Docs#5505]
In the example: 
`$i=0
$varB = 10,20,30,40
foreach ($val in $varB) {
  $i++
  if ($val -eq 30) {
    break
  }
}
Write-Host "30 was found in array position $i"`

The code states that the location in the array is position 3. That is technically incorrect, as arrays start at position 0. The COUNT needs to not increment on the first loop, or start at -1 so that on the first increment it is the TRUE starting position. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d6714f-5609-52c2-987c-b0522d038b2b
* Version Independent ID: e5c77926-c030-4723-9273-5415f1d9e723
* Content: [about_Break - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_break?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Break.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Break.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
@JordanTheITGuy I agree with you. It could be interpreted that the message is showing a more human understanding of the position in the list, but I'm with you and think we should show index position rather than a list position. I will update the docs accordingly
