### ISSUE TITLE
Online install from windows server core

### ISSUE THREAD

**Issue by softlion** [MicrosoftDocs/PowerShell-Docs#5510]
Explain how to install powershell core using the powershell on a fresh install of windows server, without copying any file manually on windows server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell Core on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by softlion** [comment]
From https://www.thomasmaurer.ch/2019/03/how-to-install-and-update-powershell-6/:
iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
wget -O - https://aka.ms/install-powershell.sh | sudo bash

**Comment by SteveL-MSFT** [comment]
The install script we have in our repo is intended for developers only and not for deployment of PowerShell.  We're working on a solution to make it easier to install PowerShell on Windows including Server Core.  Nothing to announce at this time, but the current solution using the aka.ms link is not intended to be used in production so we won't be documenting it.

**Comment by softlion** [comment]
> The install script we have in our repo is intended for developers only and not for deployment of PowerShell. We're working on a solution to make it easier to install PowerShell on Windows including Server Core. Nothing to announce at this time, but the current solution using the aka.ms link is not intended to be used in production so we won't be documenting it.

It works perfectly though.
