### ISSUE TITLE
msix package notes are incorrect. 

### ISSUE THREAD

**Issue by ebmarquez** [MicrosoftDocs/PowerShell-Docs#5519]
Looking at the release notes, the MSIX package does not exist like the document claims.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell Core on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?WT.mc_id=THOMASMAURER-blog-thmaure&view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Its coming soon.

**Comment by CraigHead** [comment]
How does one remember how they installed it? Is there a table of folders for referencing "how it was installed" so that it can be upgraded correctly?

**Comment by sdwheeler** [comment]
The MSIX package is not supported at this time. We continue to build the package for internal testing purposes only.
