### ISSUE TITLE
Need to document that Out-GridView is only available on Windows

### ISSUE THREAD

**Issue by rjmholt** [MicrosoftDocs/PowerShell-Docs#5522]
The Out-GridView document does not mention that it's only available on Windows.

It should do that, and ideally mention [Microsoft.PowerShell.GraphicalTools](https://www.powershellgallery.com/packages/Microsoft.PowerShell.GraphicalTools/0.2.0) as the cross-platform option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2442949-6488-2ef1-f5d3-fa99b97658cd
* Version Independent ID: 217c0b18-24d5-6e58-506b-0cd849fa956c
* Content: [Out-GridView (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-gridview?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Out-GridView.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Out-GridView.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Actually the doc does say that it is Windows only but I can add a link to the GraphicalTools module.
