### ISSUE TITLE
Document new(?) usage of http_proxy on Windows

### ISSUE THREAD

**Issue by jgardsentry** [MicrosoftDocs/PowerShell-Docs#5530]
# Documentation Issue
It is my experience that PS 5 and 6 used IE's browser proxy configuration by default, unless you explicitly passed `-Proxy` type parameters.  Now, PS 7 uses `$env:http_proxy` and `$env:no_proxy` variables if they exist.

## Context of the issue

- I'm not sure where, or if, this perceived change in behavior should be documented.

  **Cmdlet reference & about_ topics**
  - [ ] Version 7.x preview content
  - [X] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform: Yes, the previous behavior of utilizing IE proxy configuration will only apply to Windows.

## Detailed description of the issue
`Invoke-WebRequest`, for example, on PS 5/6 uses IE proxy configuration and bypass list.  PS 7 uses environment variables `http_proxy`, `no_proxy` if they exist.

**Comment by markekraus** [comment]
Looks like dotnet/corefx#37238 is responsible for this change. The change to SocketsHttpHandler to support environment variables is made in .NET Core 3.0. That means this change bubbles up starting with PowerShell 7.

PS 7 on Windows will honor environment variables and then fall back to IE settings.

**Comment by markekraus** [comment]
As for where to document... it should be updated in the 7.0 and 7.1 Invoke-WebRequest and Invoke-RestMethod docs. The notes section includes a link to https://docs.microsoft.com/en-us/dotnet/framework/network-programming/accessing-the-internet-through-a-proxy which is not accurate or updated for .NET Core.

Ideally, proxy auto-discovery by corefx should be documented in corefx and we could link to it.
Unfortunately, I can't find similar documentation for corefx. 
Closest I can find is https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.proxy?view=netcore-3.1#System_Net_Http_HttpClientHandler_Proxy but it is not complete.
