### ISSUE TITLE
Missing parameter?

### ISSUE THREAD

**Issue by olivier65** [MicrosoftDocs/PowerShell-Docs#5531]
It seems that this function accepts the Raw parameter but it is not documented above, especially its incompatibility with Delimiter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bbc358-71c3-6802-b812-26184aafc741
* Version Independent ID: bb898313-9408-325a-1c36-2544ee3be1c1
* Content: [ConvertFrom-StringData (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-stringdata?view=powershell-7.x#feedback)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
I don't see a `-Raw` parameter. How are you seeing that parameter?

PowerShell 5.1

```powershell
PS> gcm ConvertFrom-Str*                                                                      
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          ConvertFrom-String                                 3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          ConvertFrom-StringData                             3.1.0.0    Microsoft.PowerShell.Utility

PS> gcm ConvertFrom-Str* -Syntax                                                              
ConvertFrom-String [-InputObject] <string> [-Delimiter <string>] [-PropertyNames <string[]>] [<CommonParameters>]

ConvertFrom-String [-InputObject] <string> [-TemplateFile <string[]>] [-TemplateContent <string[]>] [-IncludeExtent] [-UpdateTemplate] [<CommonParameters>]


ConvertFrom-StringData [-StringData] <string> [<CommonParameters>]
```

PowerShell 6.2.4

```powershell
PS> gcm convertfrom-str*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          ConvertFrom-StringData                             6.1.0.0    Microsoft.PowerShell.Utility

PS> gcm convertfrom-str* -Syntax

ConvertFrom-StringData [-StringData] <string> [<CommonParameters>]
```

PowerShell 7.0

```powershell
PS> gcm ConvertFrom-Str*
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          ConvertFrom-StringData                             7.0.0.0    Microsoft.PowerShell.Utility

PS> gcm ConvertFrom-Str* -Syntax

ConvertFrom-StringData [-StringData] <string> [[-Delimiter] <char>] [<CommonParameters>]
```

**Comment by olivier65** [comment]
I found it in a blog post and ConvertFrom-StringData does not reject it. Furthermore, as I already wrote, if you use both Raw and Delimiter you are told they are incompatible.

**Comment by sdwheeler** [comment]
The error I get is:

```
ConvertFrom-StringData: A parameter cannot be found that matches parameter name 'Raw'.
```

If you are not getting that error then you are not running the cmdlet we shipped. `Get-Command` should show you the module that contains the cmdlet. What does it show you?

**Comment by olivier65** [comment]
Sorry, that was with an older PowerShell version. Now with 7.0 I get the same error message as you.  Get-Command shows:
```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          ConvertFrom-StringData                             7.0.0.0    Microsoft.PowerShell.Utility
```

**Comment by sdwheeler** [comment]
The documentation does not list a `-Raw` parameter. So that is an expected error message.
