### ISSUE TITLE
Not able to use Method SetDefaultPrinter

### ISSUE THREAD

**Issue by derik0709** [MicrosoftDocs/PowerShell-Docs#5532]
I am not able to use Get-CimInstance to set the default printer because the Method does not exist in the cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df92b55-9cf1-e7c5-284a-55b0cec250be
* Version Independent ID: 8d3d0a16-8189-f97f-b955-386a1f019ba8
* Content: [Working with Printers - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/samples/working-with-printers?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/samples/Working-with-Printers.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Working-with-Printers.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Yeah, we need to fix that.

```
$printer = Get-CimInstance -Class Win32_Printer -Filter "Name='HP LaserJet 5Si'")
Invoke-CimMethod -InputObject $printer -MethodName SetDefaultPrinter
```
