### ISSUE TITLE
Discussion under Windows PowerShell Module is no longer valid

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#5551]
With PowerShell 7 RTM, the WindowsPSModulePath discussion is not relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a43d3-9571-389c-56ab-7d42a53bf5b1
* Version Independent ID: c138e6a8-fd80-bd64-25ac-24e774e09421
* Content: [PowerShell Core Support Lifecycle - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/PowerShell-Support-Lifecycle.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Linking related issues 
- https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5437
- https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5549
