### ISSUE TITLE
Hardlink

### ISSUE THREAD

**Issue by gyj-hub** [MicrosoftDocs/PowerShell-Docs#5552]
创建硬链接的时候，若是文件名称含有空格，则会报错:
“New-Item : 找不到路径“.\Chapter 15 配置服务器存储和群集 [兼容模式].pdf”，因为该路径不存在。”
同样的路径，同样的名称，我使用fsutil.exe hardlink create命令，则能够成功创建hardlink。
 fsutil.exe hardlink create "E:\temp\Chapter14 配置Windows Media服务 [兼容模式].pdf" ".\Chapter14 配置Windows Media服务 [兼容模式].pdf"
为 E:\temp\Chapter14 配置Windows Media服务 [兼容模式].pdf &lt;&lt;===&gt;&gt; E:\数据\OneDrive - Platinum\学习\服务器教程\2008\2008服务器教程全套\MCSE2008网络基础架构\网络构架PPT\Chapter14 配置Windows Media服务 [兼容模式].pdf 创建了硬链接。

但是使用fsutil.exe hardlink create则不利于我在PowerShell中使用错误重定向和输出重定向等功能。

可否改进或者指出我使用New-Item命令的不当方式？谢谢你们。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed41112-a613-80a9-223c-d207279898d1
* Version Independent ID: 609a9efd-598e-050b-c9b8-91402dcc8e87
* Content: [New-Item (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/New-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/New-Item.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@gyj-hub This is a known issue. For a full explanation see https://github.com/PowerShell/PowerShell/issues/6232.

**Comment by sdwheeler** [comment]
I updated the documentation to better explain the **Name** and **Path** parameters.

**Comment by gyj-hub** [comment]
> @ gyj-hub这是一个已知问题。有关完整说明，请参见[PowerShell / PowerShell＃6232](https://github.com/PowerShell/PowerShell/issues/6232)。

谢谢您，我已经明白如何做了。
