### ISSUE TITLE
Unable to run Powershell commands in MACOS after installing it.

### ISSUE THREAD

**Issue by raghesh20002000** [MicrosoftDocs/PowerShell-Docs#5553]
After following below step I am unable to access PowerShell commands in MAC Catalina OS
followed below steps to install it.

```
# Download the powershell '.tar.gz' archive
curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/powershell-6.2.0-osx-x64.tar.gz

# Create the target folder where powershell will be placed
sudo mkdir -p /usr/local/microsoft/powershell/6.2.0

# Expand powershell to the target folder
sudo tar zxf /tmp/powershell.tar.gz -C /usr/local/microsoft/powershell/6.2.0

# Set execute permissions
sudo chmod +x /usr/local/microsoft/powershell/6.2.0/pwsh

# Create the symbolic link that points to pwsh
sudo ln -s /usr/local/microsoft/powershell/6.2.0/pwsh /usr/local/bin/pwsh

Install OpenSSL (https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7#install-openssl). OpenSSL is needed for PowerShell remoting and CIM operations.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cac030d-de88-9bf0-5ea8-7213b5d7f088
* Version Independent ID: d025a07e-05e1-ef40-5500-36d3facbcc04
* Content: [Installing PowerShell on macOS - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@raghesh20002000 What error do you get when you try to start `pwsh`?

**Comment by raghesh20002000** [comment]
When I type pwsh. Getting command not recognized.

**Comment by sdwheeler** [comment]
If you followed the steps correctly and received no errors during those steps, it should work. 

Try asking your questions in one of the community forums. See https://docs.microsoft.com/powershell/scripting/community/community-support for a list of forums.
