### ISSUE TITLE
F7 does not seem to work on PS 7

### ISSUE THREAD

**Issue by ccronemberger** [MicrosoftDocs/PowerShell-Docs#5559]
I have just installed the latest version available in the GitHub release page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1777470c-18a0-e5e6-2a51-7f432d8e18fd
* Version Independent ID: 936ffb0f-739d-e58c-360e-e05a9129b186
* Content: [about_History - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_history?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_History.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_History.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The key bindings listed are correct when the PSReadLine module is not loaded. However, the PSReadLine module loads by default. With PSReadLine, <kbd>F7</kbd> is not bound to any function. I don't know if PSReadLine has an equivalent function.

**Comment by ccronemberger** [comment]
This script can do it:

https://stackoverflow.com/a/50382377/1071971

**Comment by ccronemberger** [comment]
Another option:

https://github.com/omniomi/AdvancedHistory

**Comment by SteveL-MSFT** [comment]
F7 which brings up the history is handled by the terminal, not by PSReadLine.  You can follow the discussion about it here: https://github.com/PowerShell/PSReadLine/issues/620
