### ISSUE TITLE
Syntax fix quotes/escape in hello world example

### ISSUE THREAD

**Issue by PLogFinder** [MicrosoftDocs/PowerShell-Docs#5568]
Unfinished business - this (example in the Warning section of the doc):
'Hello World' -replace '(\w+) \w+', '`$1 Universe'

should be offering these two options:
'Hello World' -replace '(\w+) \w+', "`$1 Universe"
'Hello World' -replace '(\w+) \w+', '$1 Universe'
That is, EITHER: use double quotes, and backtick (escape) the dollar; OR use single quotes on the whole replace-with string - NO backtick in this second case.
If you need to substitute other variables, use the first; if you don't, the second is easier to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e504278a-f2e0-17c9-12ca-a86b56cba215
* Version Independent ID: ac918b8d-aece-5c59-2a88-64c1a91ff5f5
* Content: [about_Regular_Expressions - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
@PLogFinder Thanks for the catch! got an update in the PR linked above if you want to take a look. 

Thanks again and have a great one
