### ISSUE TITLE
Discrepancies in page

### ISSUE THREAD

**Issue by boBHHSC** [MicrosoftDocs/PowerShell-Docs#5574]
Two problems:
1) Get-PSDrive does not show network path of mapped drives; the Root column just shows drive paths.

2) The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38d46aa2-fa2f-c200-09c4-aa0669279b69
* Version Independent ID: de2cff8a-e09e-65bd-b937-29f6eebc6d21
* Content: [Get-PSDrive (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-psdrive?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-PSDrive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-PSDrive.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @boBHHSC, thanks for the feedback. 
 1. Mine currently shows all my mapped drives and my network mapped drive I created by `New-PSDrive`. See `P` Drive Root column.
```
Name           Used (GB)     Free (GB) Provider      Root                                               CurrentLocation
----           ---------     --------- --------      ----                                               ---------------
A                                      FileSystem    A:\
Alias                                  Alias
C                   6.22         25.21 FileSystem    C:\                                            Users\Administrator
Cert                                   Certificate   \
D                   3.25          0.00 FileSystem    D:\
Env                                    Environment
Function                               Function
HKCU                                   Registry      HKEY_CURRENT_USER
HKLM                                   Registry      HKEY_LOCAL_MACHINE
P                   7.04         24.39 FileSystem    \\POSH-DC\Test
Variable                               Variable
WSMan                                  WSMan
```

Have you created a mapped network drive that would show up there? 
 2. If you are getting this error, I'm assuming you are working in a unix based system which doesn't support the [\*-Cim\* cmdlets](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions?view=powershell-7#cimcmdlets)

**Comment by boBHHSC** [comment]
1)      Must be a version difference, cause mine just shows letter-based paths in that column.  Had to use Get-WmiObject  to get the network paths (in ProviderName oddly enough).

[cid:image002.png@01D5F70C.CFF5D340]

Everything from J: to Z: is a mapped network drive, as shown here:
[cid:image001.png@01D5F70D.11DD50D0]


2)      Bad assumption, I’m on a Windows 7 machine.


boB
