### ISSUE TITLE
Latest version uses different steps to configure workspace debugging

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/PowerShell-Docs#5576]
The first step, involves re-reading the previous paragraph because the steps don't work till a folder has been opened. Also, there is no more gear? Lastly, it forces me to choose one launch option, then opens the launch.json file for editing.

Follow these steps to create your debug configuration file:

1. From the File menu using Open Folder.... select a folder. (CTRL-O)
2. Open the Debug view on Windows or Linux by pressing Ctrl+Shift+D. On macOS, press Cmd+Shift+D.
3. Click the link to "create a launch.json file"
4. VSCode prompts you to Select Environment. Choose PowerShell.
5. Select one of the configurations listed. You can add additional configuration options once the file is created. Here's a launch.json with all the configurations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919fe42a-edb9-c950-1405-ae723bb6a48e
* Version Independent ID: 781d1d43-834f-7e39-cc60-8905d5803f9b
* Content: [Using Visual Studio Code for PowerShell Development - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-7)
* Content Source: [reference/docs-conceptual/components/vscode/using-vscode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/using-vscode.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@TylerLeonhardt Can you update the VSCode articles?

**Comment by TylerLeonhardt** [comment]
PR sent
