### ISSUE TITLE
HTTP URLs for WebDAV servers?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/PowerShell-Docs#5581]
Does this cmdlet still not support HTTP URLs like NET USE?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc35d6c-d927-8fa2-3817-086e9eb770fa
* Version Independent ID: a45957af-1dfa-226b-c4d4-2a84b0e82962
* Content: [New-PSDrive (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
Correct. New-PSDrive does not support URLs. But is does support WebDAV.

```
PS C:\Git> net use x: https://live.sysinternals.com/tools
PS C:\Git> New-PSDrive -Root \\live.sysinternals.com\tools -Name Y -PSProvider FileSystem
PS C:\Git> Get-PSDrive -Name X,Y

Name           Used (GB)     Free (GB) Provider      Root                                               CurrentLocation
----           ---------     --------- --------      ----                                               ---------------
x                 259.06       1595.80 FileSystem    \\live.sysinternals.com@SSL\DavWWW…
X                 259.06       1595.80 FileSystem    \\live.sysinternals.com@SSL\DavWWW…
Y                                      FileSystem    \\live.sysinternals.com\tools
```
