### ISSUE TITLE
Lifecycle of PowerShell 7+

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#5588]
# Documentation Issue

1. We need to remove all about 6.0, 6.1 versions from the 7.0 version document. Currently only 6.2 and 7.0 is in support.
2. After MSFT team blog post about next milestone we need to update support policy. See https://github.com/PowerShell/PowerShell/issues/12057. Main idea is "PowerShell 7+ releases are supported for as long as .NET LTS and non-LTS support exists".

## Context of the issue

- URL to the article (Docs or GitHub URL):  https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [ ] Version 7.x preview content
  - [x] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [x] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by joeyaiello** [comment]
Hey @iSazonov, good catch. We actually just revved this document pretty significantly with info on the 7.0 lifecycle, is there anything you think is missing right now on that front? 

With regards to the 6.0/6.1 info: we agreed that we want to keep the historical dates, hopefully you're okay on that front. Are you asking that we simply remove the 6.x section and state the date? I could see an argument for that, but I want to know what @sdwheeler, @SteveL-MSFT, or @chasewilson think about that. I could also see an argument that says we should just leave that alone until 6.2 goes out of support, upon which we remove it completely and just leave the historical dates in the table. 

Thoughts?

**Comment by sdwheeler** [comment]
@joeyaiello I agree we should just leave the 6.x info until it is out of support.

The real question that @iSazonov is getting at is what happens when .NET has a new "Current" release? Will we release a new "Current" release with the updated .NET at the same time? If not, then our support windows will not be in sync. How do we document that?

**Comment by iSazonov** [comment]
> With regards to the 6.0/6.1 info: we agreed that we want to keep the historical dates, hopefully you're okay on that front.

I agree to keep dates in a table but support description for 6.0/6.1 could be removed, only for 6.2 makes sense. This simplify the document and understanding. Also users could see old version of the document if needed.

> If not, then our support windows will not be in sync. How do we document that?

My understanding of that @SteveL-MSFT [said](https://github.com/PowerShell/PowerShell/issues/12057) - PowerShell 7+ support ends with underlying .Net Core version support ends.

**Comment by sdwheeler** [comment]
@iSazonov Yes, PowerShell support ends with the end of support for the underlying .NET Core version. We will address the specifics of that in the doc when 7.1 releases.
