### ISSUE TITLE
Remove obsolete Install-PowerShellRemoting.ps1 information

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5597]
* `Enable-PSRemoting` now works in the latest 6.x release too, and the _stopgap_ `Install-PowerShellRemoting.ps1`  script is no longer needed (and no longer distributed with 7.0)

* Also worth calling out explicitly that due to the WinRM-specific nature of `Enable-PSRemoting`, the cmdlet isn't available on Unix-like platforms (as of v7.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94e422f4-87cc-16fb-9dc4-8358acb2f96a
* Version Independent ID: 63f2f307-8cb7-7be6-2837-e5aeaf1882c5
* Content: [WS-Management (WSMan) Remoting in PowerShell Core - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/wsman-remoting-in-powershell-core?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/remoting/WSMan-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/WSMan-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@PaulHigin Can you comment?

**Comment by PaulHigin** [comment]
I remember @SteveL-MSFT  saying we were keeping it around for some edge scenario, but I don't recall the details.

**Comment by SteveL-MSFT** [comment]
`Install-PowerShellRemoting.ps1` is needed specifically for the scenario where you can use remote PowerShell to an endpoint, install the latest PowerShell, and setup a remoting endpoint to that new PowerShell.  This was initially needed for Nanoserver and Windows IoT which has WinPS 5.1 and was headless so you could only remote into it.  I don't know if it's needed now.  I'm also not sure why we didn't just tell people to run: `pwsh -c enable-psremoting` which should have been equivalent.  Perhaps it really isn't needed anymore.

**Comment by sdwheeler** [comment]
Leaving the documentation as-is for now. We can change this when we decide to remove the script.
