### ISSUE TITLE
The cmdlet creates the file in your $Env:Temp folder.

### ISSUE THREAD

**Issue by Jasonthurston** [MicrosoftDocs/PowerShell-Docs#5598]
When I change $env:TEMP in my powershell session to a different folder New-TemporaryFile still writes to the original location.
When I change $env:TMP it does write to the new location.
But this document implies that $env:TEMP is what it uses.

PS C:\Users\fuser&gt; $env:TEMP
C:\Users\fuser\AppData\Local\Temp

PS C:\Users\fuser&gt; $env:TMP
C:\Users\fuser\AppData\Local\Temp

PS C:\Users\fuser&gt; $env:TEMP='.'

PS C:\Users\fuser&gt; $env:TMP  #left unchanged
C:\Users\fuser\AppData\Local\Temp

PS C:\Users\fuser&gt; $env:TEMP #confirm change
.
PS C:\Users\fuser&gt; $a=new-temporaryfile

PS C:\Users\fuser&gt; $a.FullName #still old location
C:\Users\fuser\AppData\Local\Temp\tmp420B.tmp

PS C:\Users\fuser&gt; $env:TMP='.'

PS C:\Users\fuser&gt; $a=new-temporaryfile

PS C:\Users\fuser&gt; $a.FullName  #new location taken affect
C:\Users\fuser\tmpC11F.tmp

Name                           Value                                                                          
----                           -----                                                                          
PSVersion                      5.1.18362.628                                                                  
PSEdition                      Desktop                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                        
BuildVersion                   10.0.18362.628                                                                 
CLRVersion                     4.0.30319.42000                                                                
WSManStackVersion              3.0                                                                            
PSRemotingProtocolVersion      2.3                                                                            
SerializationVersion           1.1.0.1                                                                        

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfdbb56c-b755-2841-d632-52be530045da
* Version Independent ID: 612094b4-801d-5b3d-2442-42a4ac18170d
* Content: [New-TemporaryFile (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-temporaryfile?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/New-TemporaryFile.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/New-TemporaryFile.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This cmdlet uses the **Path.GetTempPath** Method. This method checks for the existence of environment variables in the following order and uses the first path found:

On Windows
1. The path specified by the TMP environment variable.
2. The path specified by the TEMP environment variable.
3. The path specified by the USERPROFILE environment variable.
4. The Windows directory.

On Linux: The path specified by the TMPDIR environment variable.
