### ISSUE TITLE
Document Request: native building

### ISSUE THREAD

**Issue by kylesferrazza** [MicrosoftDocs/PowerShell-Docs#5601]
# Summary of the new document or enhancement
It would be great to have a document outlining how to build PowerShell without a self-hosted copy available. Maintaining the [AUR package](https://aur.archlinux.org/packages/powershell) becomes more difficult for me every time the build system changes between versions with no document or script explaining the changes. All of the current documentation assumes a previously installed version of PowerShell.

Details of requested document:

- Proposed title: Building natively
- Propose location in the TOC: under `Install`
- Target audience: people who want to build from source on Linux without a self-hosted copy
- Purpose or scenario: help package maintainers write [build scripts](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=powershell) that don't rely on powershell being installed
- List of related articles to link to:
  - .NET Core dependencies and requirements

**Comment by TravisEz13** [comment]
This should be filed as a feature request in PowerShell/PowerShell not a doc issue.  It is a requirement that you have a previously built PowerShell to build PowerShell.  We can't really doc how to do something that is not truly possible.

**Comment by kylesferrazza** [comment]
Ok, moved to https://github.com/PowerShell/PowerShell/issues/12151.
