### ISSUE TITLE
Example is C# when it should be PowerShell

### ISSUE THREAD

**Issue by Jonathan-Quilter** [MicrosoftDocs/PowerShell-Docs#5607]
The example shown for assigning a PowerShell cmdlet parameter alias should be in PowerShell
Currently it is:
![image](https://user-images.githubusercontent.com/61971284/77079469-024eaf00-69f0-11ea-8cbc-c8d7af096b19.png)

but should be 
```
param(
    [parameter()]
    [alias('Variable']
    [string]$Var
)
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55af845f-e3aa-8e4b-1669-5410c936c9a6
* Version Independent ID: bd920c9e-0c3d-2aab-cc5a-bfd5531d3e11
* Content: [Parameter Aliases - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/parameter-aliases?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/developer/cmdlet/parameter-aliases.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/parameter-aliases.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This article is part of the PowerShell SDK. All examples are intended to be written in C#.

**Comment by tendersoft-mjb** [comment]
still, it looks weird and the docs should at least provide a PowerShell version as well

**Comment by sdwheeler** [comment]
That information is in the scripting documentation. https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters#alias-attribute

**Comment by Jonathan-Quilter** [comment]
Would be great to have that link in the See Also section.
