### ISSUE TITLE
Add documentation for Tee-Object -Encoding Parameter 

### ISSUE THREAD

**Issue by Peter-Schneider** [MicrosoftDocs/PowerShell-Docs#5612]
# Documentation Issue
Pending [PowerShell/PowerShell#12135](https://github.com/PowerShell/PowerShell/pull/12135)
Update Tee-Object cmdlet documentation to include the new '-Encoding' parameter.

## Context of the issue

- URL to the article (Docs or GitHub URL): 
[Tee-Object Documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/tee-object?view=powershell-7)

- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles

**Comment by iSazonov** [comment]
The PR was merged.
