### ISSUE TITLE
Examples should be fixed and amended 

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5623]
> `Get-WindowsFeature`

Worth mentioning that this particular command is only available in _server editions_ of Windows.

Perhaps a better example command is `Get-AppLockerPolicy -Local`, which implicitly imports the WinPS-only `AppLocker` module, which is also available on _workstation editions_ (Windows 10).

---

`'{"DisableImplicitWinCompat" : "False"` should be: `'{"DisableImplicitWinCompat" : true`

That is, the logic is currently reversed (the example is about _disabling_), and the data type is (conceptually) incorrect.

Also, the example shows writing to a _custom_ configuration file (`"$PSHOME\DisableWinCompat.powershell.config.json"`), that must be loaded _explicitly_ via the CLI, with `-settingsFile`, and does so _without explanation_, which raises the following questions:

* Is using a custom configuration file recommended?
* Why not modify the standard `"$PSHOME\powershell.config.json"` file to disable _by default_?

---

> `$s = Get-PSSession -Name WinPSCompatSession`
> `Invoke-Command -Session $s -ScriptBlock {"Running in Windows PowerShell version $($PSVersionTable.PSVersion)";<#Get-WinPSLiveObject | Set-WinPSLiveObject#>}`

It looks like `;<#Get-WinPSLiveObject | Set-WinPSLiveObject#>` was left in there by accident - otherwise, _preferably_, the example command needs to be amended to show an actual (two+-segment) _pipeline_.

Also, it should be mentioned that the example will only work if the background WinPS 5.1 session (named `WinPSCompatSession`) _happens to_ have already been established in the session.

Unfortunately, there is currently no _dedicated_ way to ensure that this session has already been created.

While running the example command suggested above (`Get-AppLockerPolicy -Local`) does - implicitly - create the session, the obvious side effect is that _its module is imported_ (via the compatibility layer), which adds commands to the current session.

---

The topic is missing a few definite articles ("the"; was the topic authored by a native Russian speaker)?

> you can use `DisableImplicitWinCompat` setting
> or when PowerShell process exits.
> imports this proxy module into current PowerShell session

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbc51fd-1d49-74dd-4ab6-1fe62fdbc619
* Version Independent ID: 1c1d6e04-a3f5-d174-b6c6-68b9cdfdd6c0
* Content: [about_Windows_PowerShell_Compatibility - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Some of this I had already addressed in an unfinished PR. I added other changes based on this issue.
