### ISSUE TITLE
Update powershell for Debian 10

### ISSUE THREAD

**Issue by ebmarquez** [MicrosoftDocs/PowerShell-Docs#5624]
Added the following
```
# Install system components
sudo apt-get update
sudo apt-get install -y curl gnupg apt-transport-https

# Import the public repository GPG keys
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# Register the Microsoft Product feed
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-buster-prod buster main" &gt; /etc/apt/sources.list.d/microsoft.list'

# Update the list of products
sudo apt-get update

# Install PowerShell
sudo apt-get install -y powershell

# Start PowerShell
pwsh
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@TravisEz13 Can you comment on this suggestion?

**Comment by ebmarquez** [comment]
I checked the packages URI and the resources are present and functional for buster.

**Comment by TravisEz13** [comment]
```
# Download the Microsoft repository GPG keys
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb

# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb

# Update the list of products
sudo apt-get update

# Install PowerShell
sudo apt-get install -y powershell

# Start PowerShell
pwsh
```

**Comment by sdwheeler** [comment]
@TravisEz13 @ebmarquez I am unclear what the action is here. What needs to change in the documentation? Can you just submit a PR if there is an update needed?

**Comment by ebmarquez** [comment]
I would be happy to but I don’t have the necessary permissions to push my branch.

C:\repos\github\PowerShell-Docs [users/emarq/buster +0 ~1 -0 !]>     git push --set-upstream origin users/emarq/buster
remote: Permission to MicrosoftDocs/PowerShell-Docs.git denied to ebmarquez.
fatal: unable to access 'https://github.com/MicrosoftDocs/PowerShell-Docs.git/': The requested URL returned error: 403

**Comment by sdwheeler** [comment]
@ebmarquez You can push directly. You have to fork the repo. Make the change to your fork and push from there.

**Comment by ebmarquez** [comment]
Thanks, I just figured this out.  I’m used to branching directly from the project vs forking…
