### ISSUE TITLE
near duplicate 'syntax' sections on this page

### ISSUE THREAD

**Issue by qt3m45su0najc7** [MicrosoftDocs/PowerShell-Docs#5625]
copy-item has nearly duplicate sections on the doc page, the difference being '-literalpath' without explanation as to why there are two sections.  I wondered if it is a difference in versions without identifying which versions support the verb.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c539af4f-3ef4-21c3-04f5-df6401ce4bdc
* Version Independent ID: 1eace7de-83aa-39a7-7a19-862e9e37b5f7
* Content: [Copy-Item (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7#syntax)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
-LiteralPath

Specifies a path to one or more locations. The value of LiteralPath is used exactly as it's typed. **No characters are interpreted as wildcards.** If the path includes escape characters, enclose it in single quotation marks. Single quotation marks tell PowerShell not to interpret any characters as escape sequences.

-Path

Specifies, as a string array, the path to the items to copy. **Wildcard characters are permitted.**
