### ISSUE TITLE
Script resource example

### ISSUE THREAD

**Issue by craig-martin** [MicrosoftDocs/PowerShell-Docs#5626]
Would be useful to mention the Script resource is not supported without the workaround from this Issue:
https://github.com/PowerShell/DscResources/issues/276

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea347ad-ed24-0760-8b3f-90ac72ddcec9
* Version Independent ID: b9a46e46-9263-f8e8-54b6-ab9a618819cc
* Content: [Securing the MOF File - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/securemof?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/pull-server/secureMOF.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/pull-server/secureMOF.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hey @craig-martin , Thanks for the feedback. 
Would you mind expanding on what should be added to our documentation? There are a few things in the linked issue and I just want to be clear on what you would like to see.

**Comment by craig-martin** [comment]
Hey @chasewilson, I think the 'Securing the MOF File' content could point out that the Script resource is not able to use the secured credentials.  If it tries to use the credential the variable will have no value when the LCM runs the resource.  There is a workaround outlined in the linked issue.  If the 'Securing the MOF File' article mentioned the issue then it could save others lots of troubleshooting and debugging.

**Comment by craig-martin** [comment]
Thanks!

**Comment by chasewilson** [comment]
@craig-martin , thanks for taking the time to submit an issue, not only on the powershell side of things but the doc! It's a huge help and feel free to open a new issue if you have more feedback! Have a great day!
