### ISSUE TITLE
Establish the term "automatic member" for built-in methods and properties available on objects of any type, and create a conceptual topic for them

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5627]
The engine automatically provides a number of members (methods and properties) on objects of _any_ type: `.ForEach()`, `.Where()`, `.Count` / `.Length`, as well as _indexing_ `[<n>]` (on scalars).

These are vital to PowerShell's (very useful) unified treatment of scalars and collections; a quick demonstration:

```powershell
PS> $v = 42; $v.Count; $v.Length; $v[0]; $v.ForEach({ $_ + 1 })
1
1
42
43
```

Additionally, there are automatic members that provide _reflection info_:  `.psobject`, `.pstypenames`, `.psbase`, `.psextended`, and `psadapted`.

These members are:

* not documented as such (`.ForEach()` and `Where()` are documented as _array methods_, even though they're available on _collections of any type_ and _even on scalars_).

* not even _programmatically discoverable_ via `Get-Member` (with the exception of the reflection-info members, which can be discovered with `-Force`), which is the subject of https://github.com/PowerShell/PowerShell/issues/11798

---

I suggest:

* establishing an _official name_ for these members:

  * Following the pattern of _automatic variable_ - i.e., something that is _built in_ and _automatically available_ - I propose _automatic [type] member_ (which can be an _automatic method_, an _automatic property_  or the _automatic indexer_)

  * Note: The [`Get-Member` topic](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-member) uses the term _intrinsic member_, but only with respect to the _reflection-related_ members. My concern is that it's not clear what _intrinsic_ refers to; given that _intrinsic member_ isn't widely known, from what I can tell, whereas the concept of _automatic_ is, namely from automatic variables, my vote is for using the term _automatic member_; that said, what matters at the end of the day is that we _have_ an official term, and that that term is _comprehensively_ documented in a _single location_.

* dedicating a conceptual topic to them `about_Automatic_Members` - see suggestions below.

---

The new topic should list all the members, discuss their behavior, and note that they can be _shadowed_ by type-native members, and can situationally be unavailable.

Notable pitfalls:

* `System.Collections.Generic.List<T>` has a `.ForEach()` method that shadows the automatic method and behaves differently in that `$_` isn't available in script blocks you pass to it, and doesn't return any value

  * `([System.Collections.Generic.List[object]] (1, 2)).ForEach({ write-verbose -vb "[$_]"; return 42 })`, prints verbose message `[]` for each element and returns nothing.
  
* `IEnumerable` instances such as returned by LINQ methods aren't collections per se, and calling `.Count` on them triggers enumeration and returns a `.Count` property value from each enumerated element instead (which defaults to `1`).

  * `[Linq.Enumerable]::Range(1,3).Count` returns array `1, 1, 1` instead of `3`.

* With `Set-StrictMode -Version 2` or higher in effect, accessing the `.Count` and `.Length`  properties causes statement-terminating errors - see https://github.com/PowerShell/PowerShell/issues/2798:

  * `Set-StrictMode -Version 2; $v = 42; $v.Count` _fails_ instead of returning `1`.
  *  I do wish this would get fixed, however, so that _automatic_ members are never subject to script-mode checks.

* A type-native indexer preempts the automatic indexer - surprisingly even in cases where it only supports a _non-numeric_ argument, such as with `XmlElement`

  * `([xml] '<foo><bar id="1"/></foo>').foo.bar[0].id` doesn't return `'1'`, but quietly returns `$null`, because indexing into scalar `XmlElement` `.bar` uses the type-native indexer that takes an _element name_ (a string); by contrast, `([xml] '<foo><bar id="1"/><bar id="1"/></foo>').foo.bar[0].id` works as expected, because `.bar` then returns an _array_.

  * See https://github.com/PowerShell/PowerShell/issues/11189 for a proposal to enable the automatic indexer in case when it _doesn't have to_ conflict with type-native indexer, due to distinct argument types.

The reflection-info members should be explained as well.

`about_Properties`, `about_Methods`, and `about_Arrays` should briefly introduce the relevant automatic members and also link to the new topic.

**Comment by iSazonov** [comment]
Extended and Adapted properties are mentioned in 
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-member?view=powershell-7
- https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/extending-properties-for-objects?view=powershell-7

I'd expect that we consolidate all these docs.

**Comment by SeeminglyScience** [comment]
Automatic variable makes sense because other variables are manual, the user needs to set them. That distinction doesn't make as much sense for these methods, the user will almost never be constructing any other methods either.  The name makes me think of events, like a method that runs automatically.

Is there a word for "intrinsic to the environment"?

**Comment by mklement0** [comment]
> Is there a word for "intrinsic to the environment"?

_Built-in_ (_builtin_) is the term that POSIX-like shells use for commands implemented by the shell itself, for instance; `cmd.exe` talks (less descriptively, to me) about _internal_ commands.

I think _built-in_ would have been a better name for what we call _automatic_ variables, but that ship has sailed a long time ago.

If we conceive of _automatic_ as "automatically _available_ (without extra effort), always there",  I think that would work for both variables and the members being discussed here.

Just like approved verbs are of necessity abstractions that aren't a perfect fit for every situation, _automatic_ is an abstraction that I think could work in the sense described above.

Since it is safe to say that the term _automatic variables_  won't go away, I'd rather stick with _one_ term rather than introduce another that isn't _fundamentally_ different.

**Comment by joeyaiello** [comment]
@mklement0 is there a particular area where you feel this term is required in order to provide clarity? We discussed this amongst the team, and we're not sure that creating a brand new term actually provides new information to users.

**Comment by mklement0** [comment]
@joeyaiello 

Since the core of this proposal is to create a new conceptual help topic for these members, they need to be given a name.

While sticking with _intrinsic_ is one option, for simplicity and consistency my recommendation is _automatic_, as argued above.

Whatever name is chosen, I think it's important to create this topic and thereby establish the name.

**Comment by sdwheeler** [comment]
I would stick with _intrinsic_. To me, the difference is that automatic variables do not exist _intrinsically_. They are created _automatically_ by the engine. These members are defined in the classes, therefore, they are _intrinsically_ available.

I would welcome a PR for `about_Intrinsic_Members`.
