### ISSUE TITLE
MaxString Negative Number Option for Split

### ISSUE THREAD

**Issue by Techno-Critter** [MicrosoftDocs/PowerShell-Docs#5631]
This page lists an example as such: "a,b,c,d,e,f,g,h" -split ",", -3
However, I am unable to get this function to work. Using a negative number return the maximum available breaks using the delimiter. Is this a flaw?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce5aa4a-3a31-0d27-387b-39c4b1724ead
* Version Independent ID: dab449ae-a570-5320-dbc3-95a9cf3e54fb
* Content: [about_Split - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_split?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Split.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This is a new feature that was added in PowerShell 7. You are looking at the docs for PowerShell 7. It is not supported in any previous version.

```powershell
PS> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      0      0

PS> "a,b,c,d,e,f,g,h" -split ",", -3
a,b,c,d,e,f
g
h
```
