### ISSUE TITLE
so.. where exactly is the API for the child-items of a directory documented?

### ISSUE THREAD

**Issue by torbjorn** [MicrosoftDocs/PowerShell-Docs#5641]
From searching around elsewhere I have come to learn that I can iterate over files using syntax like:

    Get-ChildItem "some\path" | Foreach-Object {
        echo $_.FullName
        echo $_.BaseName
     }

Aparently the object that I get to work with in each iteration have `.FullName` and `.BaseName` attributes, which seems nice and useful.

There is a link to things that it exposes if I understand correctly. FileInfo seems relevant. Yet nothing there on .BaseName, (though I do find FullName!) 

So.. the search goes on.

Only it doesn't.

At that point I was annoyed that I wrote this text.

So please, someone who has a sliver of pride in the text that goes into these manual pages, How should I have been reasoning to be able to arrive at the manual page that tells me what attributes I have on the child items of a directory. Get-ChildItem obviously is a nice starting page. That's what I have in my code. Moving on to FileSystem provider is.. I guess ok.. but I had to read that wall of text, for something that is a very very common use.

I still haven't found where .BaseName is documented. Searching for BaseName in top right search field yields nothing useful.

At the time someone reads (and who knows - cares?) I will likely long ago have found my answer on stackexchange or some other place. 

It's just that...this is super super basic stuff. You need to have documented APIs. It's just wrong that being able to find the attributes of a File object is this hard. And yeah well.. guess I flipped a little.

Now if only there was a page listing these... So googling for Get-ChildItem and powershell took me straight to the Get-ChildItem manual here. Great.

Now surely the dominating use of Get-ChildItem must be for accessing path elements.  Yet I had to plow a wall of text only to arrive at a list of providers for which Get-ChildItem applies, and FileSystem aparently is only one of them. Fine, guess I can suffer that.

Now the FileSystem entry didn't link to the FileSystem manual page. No choice. Have to suffer that as well. So I type FileSystem in the top right search field and lo and behold it takes me to info on FileSystem.

Nothing here on .BaseName and .FullName or anything resembling a list of attributes I cat get from file objects in my foreach loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5662d38b-7a4b-c80e-3a55-d4bf85dae867
* Version Independent ID: 102c7640-4b05-128b-4a6c-13db8a3ccbe3
* Content: [FileSystem Provider - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_filesystem_provider?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
We are working on improvements to our docs publishing system that will allow us to easily link to the .NET type documentation for any object type. That would make some of this discovery easier. I understand the frustration. It is a long-standing issue that we are working to resolve.

`Get-ChildItem` returns [System.IO.FileInfo](https://docs.microsoft.com/dotnet/api/system.io.fileinfo?view=netcore-3.1) and System.IO.DirectoryInfo objects. Some of the properties are inherited from the base class System.IO.FileSystemInfo. Other properties are added by the FileSystem Provider in PowerShell. 

PowerShell can help you discover the information you need. The easiest way to see information about an object is to pipe it to `Get-Member`. For example:

```powershell
PS> Get-ChildItem .\README.md | Get-Member

   TypeName: System.IO.FileInfo

Name                      MemberType     Definition
----                      ----------     ----------
LinkType                  CodeProperty   System.String LinkType{get=GetLinkType;}
Mode                      CodeProperty   System.String Mode{get=Mode;}
ModeWithoutHardLink       CodeProperty   System.String ModeWithoutHardLink{get=ModeWithoutHardLink;}
Target                    CodeProperty   System.String Target{get=GetTarget;}
AppendText                Method         System.IO.StreamWriter AppendText()
CopyTo                    Method         System.IO.FileInfo CopyTo(string destFileName), System.IO.FileInfo CopyTo(str…
Create                    Method         System.IO.FileStream Create()
CreateText                Method         System.IO.StreamWriter CreateText()
Decrypt                   Method         void Decrypt()
Delete                    Method         void Delete()
Encrypt                   Method         void Encrypt()
Equals                    Method         bool Equals(System.Object obj)
GetHashCode               Method         int GetHashCode()
GetLifetimeService        Method         System.Object GetLifetimeService()
GetObjectData             Method         void GetObjectData(System.Runtime.Serialization.SerializationInfo info, Syste…
GetType                   Method         type GetType()
InitializeLifetimeService Method         System.Object InitializeLifetimeService()
MoveTo                    Method         void MoveTo(string destFileName), void MoveTo(string destFileName, bool overw…
Open                      Method         System.IO.FileStream Open(System.IO.FileMode mode), System.IO.FileStream Open…
OpenRead                  Method         System.IO.FileStream OpenRead()
OpenText                  Method         System.IO.StreamReader OpenText()
OpenWrite                 Method         System.IO.FileStream OpenWrite()
Refresh                   Method         void Refresh()
Replace                   Method         System.IO.FileInfo Replace(string destinationFileName, string destinationBack…
ToString                  Method         string ToString()
PSChildName               NoteProperty   string PSChildName=README.md
PSDrive                   NoteProperty   PSDriveInfo PSDrive=C
PSIsContainer             NoteProperty   bool PSIsContainer=False
PSParentPath              NoteProperty   string PSParentPath=Microsoft.PowerShell.Core\FileSystem::C:\Git\PS-Docs\Powe…
PSPath                    NoteProperty   string PSPath=Microsoft.PowerShell.Core\FileSystem::C:\Git\PS-Docs\PowerShell…
PSProvider                NoteProperty   ProviderInfo PSProvider=Microsoft.PowerShell.Core\FileSystem
Attributes                Property       System.IO.FileAttributes Attributes {get;set;}
CreationTime              Property       datetime CreationTime {get;set;}
CreationTimeUtc           Property       datetime CreationTimeUtc {get;set;}
Directory                 Property       System.IO.DirectoryInfo Directory {get;}
DirectoryName             Property       string DirectoryName {get;}
Exists                    Property       bool Exists {get;}
Extension                 Property       string Extension {get;}
FullName                  Property       string FullName {get;}
IsReadOnly                Property       bool IsReadOnly {get;set;}
LastAccessTime            Property       datetime LastAccessTime {get;set;}
LastAccessTimeUtc         Property       datetime LastAccessTimeUtc {get;set;}
LastWriteTime             Property       datetime LastWriteTime {get;set;}
LastWriteTimeUtc          Property       datetime LastWriteTimeUtc {get;set;}
Length                    Property       long Length {get;}
Name                      Property       string Name {get;}
BaseName                  ScriptProperty System.Object BaseName {get=if ($this.Extension.Length -gt 0){$this.Name.Remo…
VersionInfo               ScriptProperty System.Object VersionInfo {get=[System.Diagnostics.FileVersionInfo]::GetVersi…
```

**Comment by sdwheeler** [comment]
Duplicate of #5221

**Comment by torbjorn** [comment]
That's a nice tip, thanks, I'll remember that.

And thanks for answering, sorry for the tone.
