### ISSUE TITLE
Clarification request for second inheritance example

### ISSUE THREAD

**Issue by mdorantesm** [MicrosoftDocs/PowerShell-Docs#5644]
Hi.

[1] Could you please clarify the main use cases for your second example under the title "Example using simple inheritance syntax" (under the section entitled "Inheritance in PowerShell classes" * ).

* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7#inheritance-in-powershell-classes

[2] Besides, that second example says: "This example shows inheritance with an interface declaration coming after the base class.", but it is unclear if this syntax adds a new interface (and then the ".Interface" part is a reserved syntactic keyword) or how this second example relates to the first example.

Thank you very much in advance for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65304a8f-89f7-f1f9-cad8-6cb0d36c5634
* Version Independent ID: a5651d52-5618-47e4-67df-6191278f0ad5
* Content: [about_Classes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7#inheritance-in-powershell-classes)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by rjmholt** [comment]
That example doesn't look right.

Here's a better (but still not great) example:

```powershell
# Simple object inheritance

class MyArrayList : System.Collections.ArrayList
{
}

$list = [MyArrayList]::new()
$list.Add(1)
$list.Add('Hi')
$list # Shows 1, 'Hi'

# Interface implementation
class MyDisposableArrayList : System.Collections.ArrayList, System.IDisposable
{
    Dispose()
    {
        $this.Clear()
    }
}

$list = [MyDisposableArrayList]::new()
$list.Add(1)
$list.Add('Hi')
$list.Dispose()
$list
```

**Comment by rjmholt** [comment]
> Besides, that second example says: "This example shows inheritance with an interface declaration coming after the base class.", but it is unclear if this syntax adds a new interface (and then the ".Interface" part is a reserved syntactic keyword) or how this second example related to the first example.

The second example should be corrected to show something like a `System.IDisposable`, so you can see there's no special syntax/keyword involved. Inheriting from multiple types is as simple as giving their full names after the `:`, separating those names with a `,`, just like in C#.

```powershell
class MyObject : BaseClass, IInterface1, IInterface2
{
}
```

**Comment by mdorantesm** [comment]
Thank you. @rjmholt .
Understood.
On a related side of this, there is no way to define or declare a new interface with PowerShell syntax, right?

Thank you very much in advance for any comment about that or about plans to add support for new interface declarations in PowerSell.

Best regards.

**Comment by rjmholt** [comment]
> On a related side of this, there is no way to define or declare a new interface with PowerShell syntax, right?

Yeah, that's not yet supported. It's tracked in https://github.com/PowerShell/PowerShell/issues/2223.

**Comment by mdorantesm** [comment]
Hi, @rjmholt .

If I have a .NET Standard 2.1 class library (mylib) with a defined interface `mylib.IMyInterface`.
I need to implement it with a PowerShell Core 7 like this:

```
class MyPowerShell7Class : mylib.IMyInterface
{
   #. . .
}
```

Could you please point to the PowerShell Core 7 documentation that explains how to do that?

Thank you very much in advance for your help or any clarification.
Best regards.
