### ISSUE TITLE
Upgrade table missing PS 6.0

### ISSUE THREAD

**Issue by bcpardo** [MicrosoftDocs/PowerShell-Docs#5654]
The table that lists the versions of PowerShell to upgrade to is missing 6.0+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67872723-9d70-6dd3-29fb-a66505cb98fb
* Version Independent ID: 7bb17de5-a42e-21ad-fac0-2ee40722b30c
* Content: [Installing Windows PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-Windows-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-Windows-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This article is specifically about installing and upgrading to Windows PowerShell 5.1.
