### ISSUE TITLE
Example URL

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#5656]
The URL in the examples points to a real Web site which appears to be some kind of scam. Please change the examples to contoso or example.com. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0e06c3-1c2f-eb5c-7123-a76a8b246e5e
* Version Independent ID: e09aba3d-8acf-12cf-2ac2-02f710a4c0f6
* Content: [New-WebServiceProxy (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-webserviceproxy?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by doctordns** [comment]
At one time, www.webservicex.net used to run a bunch of cool web services. Then they disappeared. The company was originally based in the UK but having tried, I can't manage to work out what happened to them. It looks like they let their domain registration lapse and it's been taken over by scammers. OR, their site lives on but has been hacked. 

When the site was live, this example was a cool one you could make work. So if the URI was changed to www.contoso.net, the reader loses that opportunity. Is there any good web service, say at MSFT, we could use. Something that would give a real result?

**Comment by sdwheeler** [comment]
Changing this to contoso.net until we can find a suitable replacement.

**Comment by sdwheeler** [comment]
Closed by #5668

**Comment by doctordns** [comment]
I wonder - would creating a real example of a web service be useful here??

**Comment by sdwheeler** [comment]
I would love to have a web service I could count on. I haven't found one yet. And WSDL has mostly been replaced by REST these days.
