### ISSUE TITLE
Get-Service ComputerName Parameter

### ISSUE THREAD

**Issue by saitheodore** [MicrosoftDocs/PowerShell-Docs#5665]
Get-Service cmdlet
Where did the ComputerName parameter disappear to? This cmdlet was extremely useful when it could query remote servers and get the services from there. Is this not supported anymore? That is really sad. With my current set-up I think I will have to stay with v5 as upgrading to 7 will wreck the current scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: affd5eed-a6cf-ed3c-572d-869c974dde51
* Version Independent ID: 52b4131a-0ccb-3942-1b13-7b57faf329d5
* Content: [Get-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by doctordns** [comment]
This is by design. The Get-Service command made use of DCOM and such functionality is removed in PowerShell 7.

You can remote the command easily enough:
```powershell
Invoke-Command -Computername XXX -Scriptblock {Get-Service | where status -eq 'started;}
```

**Comment by sdwheeler** [comment]
See https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-7#remove--computername-from--service-cmdlets-5090

**Comment by saitheodore** [comment]
> This is by design. The Get-Service command made use of DCOM and such functionality is removed in PowerShell 7.
> 
> You can remote the command easily enough:
> 
> ```powershell
> Invoke-Command -Computername XXX -Scriptblock {Get-Service | where status -eq 'started;}
> ```

No sir. That's not an option for me as I can't execute remote PS on those machines. We are executing this in a tight ACL.

**Comment by saitheodore** [comment]
> See https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-7#remove--computername-from--service-cmdlets-5090

It's a bummer. Unfortunately remote execution is not an option for me. Looks like it's time to look elsewhere than PS

**Comment by doctordns** [comment]
> > This is by design. The Get-Service command made use of DCOM and such functionality is removed in PowerShell 7.
> > You can remote the command easily enough:
> > ```powershell
> > Invoke-Command -Computername XXX -Scriptblock {Get-Service | where status -eq 'started;}
> > ```
> 
> @doctordns No sir. That's not an option for me as I can't execute remote PS on those machines. We are executing this in a tight ACL.

You can use JEA. You can create a specific ACL-protected remoting endpoint that can JUST do get-service and if you want, can only get service if the service name is "'xxx".  If you are allowed to execute get-service over DCOM, then JEA will give you the capability of doing the same thing. JEA works great btw with PowerShell 7 and Windows 10/Server 2019. 

A neat feature of JEA is automatic transcripts so you can see ANYTHING that EVERY remote user has done and the results. Seems to me your organisation would find that advantageous. 

And you can always use Windows PowerShell where there are no limitations. Use PowerShell 7 where you want to take advantage of it's improved performance or to use the new features and use Windows PowerShell where you have to. Simply chucking out PowerShell totally seems sub-optimal.

**Comment by saitheodore** [comment]
@doctordns Will definitely check that out. Thanks for the suggestion

**Comment by doctordns** [comment]
I am writing a book on PowerShell 7 and have scripts for that! 

Here is one that can help: <https://github.com/doctordns/Wiley20/blob/master/03%20-%20Managing%20AD/3.7%20-%20Implementing%20Just%20Enough%20Administration.ps1>

**Comment by saitheodore** [comment]
@doctordns That's really helpful. Thanks once again.
