### ISSUE TITLE
Get-CredsFromCredentialProvider Appears in Release History

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#5678]
Related to https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5383  The entry for Get-CredsFromCredentialProvider on this page is what caused me to look it up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78a06ee-5b1b-94d1-dc09-5059cd78444f
* Version Independent ID: fae67694-743a-5e4e-eef7-dd45eb8decf4
* Content: [Release history of modules and cmdlets - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/whats-new/cmdlet-versions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/cmdlet-versions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Yes, and I have closed that issue with the same root cause. `Get-CredsFromCredentialProvider` was never intended to be exported. I got confirmation of this today from the PM.
