### ISSUE TITLE
Example 1 doesn't work.

### ISSUE THREAD

**Issue by Slogmeister** [MicrosoftDocs/PowerShell-Docs#5687]
```
Error: 
New-WSManInstance : The WS-Management service cannot process the request because the request did not contain all required selectors. 
At line:1 char:1
+ New-WSManInstance -ResourceURI winrm/config/listener -SelectorSet @{T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-WSManInstance], InvalidOperationException
    + FullyQualifiedErrorId : WsManError,Microsoft.WSMan.Management.NewWSManInstanceCommand
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c52b1f-53d8-469d-b81b-ef71fa2fccf3
* Version Independent ID: 63e05b06-d085-5b19-6e37-2719e0630274
* Content: [New-WSManInstance (Microsoft.WSMan.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.wsman.management/new-wsmaninstance?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.WSMan.Management/New-WSManInstance.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.WSMan.Management/New-WSManInstance.md)
* Product: **powershell**
* GitHub Login: @PaulHigin
* Microsoft Alias: **paulhi**

**Comment by sdwheeler** [comment]
@Slogmeister Try this:

`New-WSManInstance winrm/config/Listener -SelectorSet @{Transport='HTTPS'; Address='*'} -ValueSet @{Hostname="HOST";CertificateThumbprint="XXXXXXXXXX"}`
