### ISSUE TITLE
Provide information about connection throttling

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5700]
CIM sessions, like PSSessions, can target multiple computers in parallel.

PSSessions have a built-in throttling mechanism to limit the number of concurrent connections to remote machines, and the `-ThrottleLimit` parameter can be used to change the default number of 32.

The article should note:

* whether there is an equivalent mechanism for CIM sessions, and, if so, what its defaults are and how they can be overridden, if at all.

* if throttling isn't supported at all, PSSessions should be recommended for targeting large sets of computers.

Linking to this information from those CIM cmdlets that accept a `-ComputerName` parameter, notably `New-CimSession`, would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23068c21-66aa-7d9d-35c7-64fa9fb72cd6
* Version Independent ID: abac965f-226c-959a-aa82-df00f0481557
* Content: [about_CimSession - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_CimSession?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_CimSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_CimSession.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@SteveL-MSFT can you research the throttlelimit story here?

**Comment by SteveL-MSFT** [comment]
The default throttlelimit can be defined within the CDXML for a cmdlet.  However, if it's not there, then it defaults to 15.  This is only for `-CimSession` and `-ThrottleLimit` on CDXML based cmdlets.

**Comment by mklement0** [comment]
Good to know, @SteveL-MSFT, but note that none of the in-box `*-Cim*` commands are CDXML-based (advanced) functions.

Instead, they are (compiled) _cmdlets_, and none of them support `-ThrottleLimit`.

Can you confirm that the default of `15` applies to them, and that it does so _invariably_?

**Comment by SteveL-MSFT** [comment]
@mklement0, the `*-Cim*` cmdlets are independent of the CDXML based cmdlets.  They are related in they both use CIM, but different in that the CIM cmdlets are for interacting with CIM objects directly whereas CDXML cmdlets are implemented as WMI classes and exposed as cmdlets.  From that perspective, `-ThrottleLimit` is not a parameter for the CIM cmdlets and so the default doesn't apply to them as there isn't any throttling.  CDXML cmdlets have an automatic `-CimSession` parameter that can take an array of cimsessions, hence throttling is required.

**Comment by sdwheeler** [comment]
@mklement0 We looked at the code to confirm, the CimCmdlets just iterate through the computernames serially, so no throttling is needed since it doesn't fan out anyways

**Comment by mklement0** [comment]
Thanks, @sdwheeler  and @SteveL-MSFT.

@SteveL-MSFT, please note that the `*-Cim*` cmdlets too support a `-CimSession` parameter (and that even a _single_ `CimSession` can target _multiple_ computers), and that the `-ComputerName` parameter is array-valued.

In other words: **throttling is also required for `*-Cim*` cmdlets**, if they connect to the target computers in _parallel_, which they indeed appear to do (and if they didn't, that would be a serious limitation that we should fix):

While I haven't looked at the source code myself, experimenting with the following command shows that in repeated runs the output objects from the two targeted computers arrive in varying order, implying that parallel connections are indeed used:

```powershell
# Run this repeatedly to see unpredictably varying output order.
(Get-CimInstance win32_volume -ComputerName $computer1, $computer2).PSComputerName
```

In light of that:

* Is there a default throttling limit in effect somehow? If not, it would prevent using the `*-Cim*` cmdlets with large computer sets.

* Shouldn't we implement `-ThrottleLimit` on all `*-Cim*` cmdlets too?
