### ISSUE TITLE
Missing link to CDXML topic

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5701]
A link to information about the CIM-based Cmdlet Definition XML (CDXML) format is missing: 

I found https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/cdxml-overview, but it is marked as no longer being updated - is this method of authoring CIM-based cmdlets (advanced functions) no longer supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d5316a-b169-272e-e79c-02f9b59d8142
* Version Independent ID: 4d303559-7069-6d5f-eb9a-c227ffe73666
* Content: [New-CimSession (CimCmdlets)](https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/new-cimsession?view=powershell-7)
* Content Source: [reference/7.0/CimCmdlets/New-CimSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/CimCmdlets/New-CimSession.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
That documentation is not being updated but CDXML is still supported.
