### ISSUE TITLE
Escaped Double Quote Not Passed to Executable

### ISSUE THREAD

**Issue by francis36012** [MicrosoftDocs/PowerShell-Docs#5702]
An escaped double quote in a double-quoted string doesn't seem to get passed to executables. For example if I want to pass this string: `('|")` to a program, I should be able to do this (according to this page): ```program "('|`")"``` or `program "('|"")"`. This is however not working, the program only gets `('|)` in both scenarios. Note that I get the expected output from the built-in echo cmdlet - ```"('|`")"``` and `"('|"")"` give me the expected output of `('|")`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608b6436-c72e-56de-c79b-fae6fb3e722c
* Version Independent ID: 61c4ba2e-b08d-089b-74bc-70d6306523e5
* Content: [about_Quoting_Rules - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Try using the stop-parsing symbol `--%`. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_parsing

For example:

```
program --% "('|")"
```

**Comment by francis36012** [comment]
Using the stop-parsing symbol works for me.
