### ISSUE TITLE
Windows to Linux example is not provided

### ISSUE THREAD

**Issue by ducttapecoder-vt** [MicrosoftDocs/PowerShell-Docs#5703]
You have examples for how to Linux-Linux, Linux-Windows, and Windows-Windows remote but nothing for how to connect to Linux from Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e79ea6-1d79-6147-aa3e-362b04bc7528
* Version Independent ID: 8877b05f-1f52-8c75-2d7d-5100cc52c4cb
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Once you have SSH set up on both sides, connecting to a remote session is the same.

`New-PSSession -HostName <targethost> -UserName <username>`
