### ISSUE TITLE
Copy action in examples doesnt copy executable code

### ISSUE THREAD

**Issue by Jonathan-Quilter** [MicrosoftDocs/PowerShell-Docs#5705]
When pressing the Copy button 
![image](https://user-images.githubusercontent.com/61971284/78373198-2dc1c400-75c2-11ea-8efd-6b8c9640017c.png) the code from the example is placed into the clipboard. When pasted into a PowerShell session and executed this results in an error as the PS prompt 'PS >' shown in the example is not executable but is placed in the clipboard

I think it would be better to avoid the 'PS >' reaching the clipboard, even if this means removing it also from the displayed examples 
![image](https://user-images.githubusercontent.com/61971284/78373577-b04a8380-75c2-11ea-9ad1-62b8aa1c4487.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74ebbb86-05e8-a3cb-cc44-0f92bd5bf530
* Version Independent ID: a878cf0b-136e-26ca-9710-7fe6cbe3d865
* Content: [about_Language_Modes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@Jonathan-Quilter This is a known issue that is on our roadmap to fix. There are two approaches to fixing it. 

1. Change the copy feature to filter out the prompts - this is being investigated
2. Remove prompts from example - this is a work in progress as we update the content. This requires a lot of manual editing. 

We do have guidance in our [style guide](https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide#avoid-using-powershell-prompts-in-examples). But we have a lot of existing technical debt to fix.

**Comment by Jonathan-Quilter** [comment]
Hi Sean, would it be likely that if I fork the docs repo and make the change that a PR cleaning this up would be accepted? Happy to help out where I can if its going to be positively received ..
J

**Comment by sdwheeler** [comment]
Absolutely. Please read the contributor guide I linked to. I created that specifically to encourage public contributions.
