### ISSUE TITLE
Dont assume everyone knows which file to edit

### ISSUE THREAD

**Issue by awooga** [MicrosoftDocs/PowerShell-Docs#5706]
&gt;Also, add the following setting so that your extension version doesn't update automatically:

Where what file is this talking about - am new comer to vsc no idea what file where ? poor form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919fe42a-edb9-c950-1405-ae723bb6a48e
* Version Independent ID: 781d1d43-834f-7e39-cc60-8905d5803f9b
* Content: [Using Visual Studio Code for PowerShell Development - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/components/vscode/using-vscode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/using-vscode.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This value is in the `settings.json` file used by VSCode. You can edit the file directly or use the setting interface in VSCode.

**Comment by awooga** [comment]
thanks sean for super fast response - thats great. so article should detail this file - in the example where the json first appears - did i miss this ?

2nd issue is writing
New file:
write-host "hello world!"
Save as hello.ps1
run (f5)
Get error "Could not find this tabl 'build' messagebox, with "configur task" ? or "open launch.json" ???? or cancel ???

no clue how to proceed - is this not a common error , and should have known simple solution - as page intro - good if it nails this common issue



awooga

________________________________
