### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by wi-fr** [MicrosoftDocs/PowerShell-Docs#5711]
### System Details

Windows PowerShell 5.1
PowerShell 7.0
PowerShell 7.1 Preview 1

### Issue Description

A gramatically incorrect error message is returned when the length of a string
parameter's argument exceeds the range specified by a ValidateLengthAttribute.

```
Function Test-ValidateLength {
    param(
        [ValidateLength(1,5)][string]$Text
    )
}
Test-ValidateLength '123456'

```

#### Expected Behaviour

"Cannot validate argument on parameter 'Text'. The character length (6) of the argument is
too long. Shorten the character length …"

#### Actual Behaviour

"Cannot validate argument on parameter 'Text'. The character length of the 6 argument is
too long. Shorten the character length …"

**Comment by sdwheeler** [comment]
Thanks for the feedback. This is a product issue.  Please file an issue at https://github.com/PowerShell/PowerShell/issues/choose
