### ISSUE TITLE
PowerShell

### ISSUE THREAD

**Issue by paulolamorea** [MicrosoftDocs/PowerShell-Docs#5712]
Olha o que está aparecendo para mim:

WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Por que aparece isso?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b770965-4cc8-203e-5332-26bb9ee99220
* Version Independent ID: 1ac2554b-bf6a-2da6-3708-2d63af435e1e
* Content: [PowerShell Scripting - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/overview.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is not a PowerShell problem. The error message is coming from Python.
