### ISSUE TITLE
Multiple conditions in 'Comparison statement' format

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/PowerShell-Docs#5716]
Is it technically possible to use multiple conditions in the `Comparison statement` syntax?

`Get-Module -ListAvailable | where Name -notlike 'Microsoft*' -and Name -notlike 'PS*'`

Ref: 'All PowerShell comparison operators are valid in the script block format. For more information about comparison operators'
Is there a list of operators not available in the `Comparison statement` format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a890d0e4-ac9d-1217-35d6-84045c64fda3
* Version Independent ID: dff1f69c-82c5-68dc-663d-f459f7c79cf3
* Content: [Where-Object (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/where-object?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/Where-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Where-Object.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
When you use `Where-Object` without a script block, the "comparison operators" are actually parameters not operators. So you cannot use multiple comparison parameters. When you use a script block then you can do multiple comparisons.

```powershell
Get-Module -ListAvailable | Where-Object { 
   $_.Name -notlike 'Microsoft*' -and $_.Name -notlike 'PS*'
}
```
