### ISSUE TITLE
Need to update WinCompat docs

### ISSUE THREAD

**Issue by anmenaga** [MicrosoftDocs/PowerShell-Docs#5724]
Need to add info about module DenyList and NoClobber import.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [X] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

- Is the issue specific to a platform: *Y* - *Win*

**Comment by sdwheeler** [comment]
Update [about_windows_powershell_compatibility](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility)

This article already documents the Deny List. Update list as necessary.
