### ISSUE TITLE
NuGet intall error fix (Win2012R2)

### ISSUE THREAD

**Issue by denrzh** [MicrosoftDocs/PowerShell-Docs#5725]
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Install-PackageProvider -Name NuGet -Force

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
See also https://support.microsoft.com/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi
