### ISSUE TITLE
Missing Parameters

### ISSUE THREAD

**Issue by Stofferl** [MicrosoftDocs/PowerShell-Docs#5728]
There are missing Parameters:
-Protocol
-Impersonation
-ThrottleLimit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 529d43fd-7d7c-a6d3-c027-f7210f0c34cc
* Version Independent ID: 56dd2ebe-131e-0968-9df4-b0a772baaf3f
* Content: [Stop-Computer (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/stop-computer?view=powershell-7.x)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Stop-Computer.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Stop-Computer.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
Those parameters only apply to [PowerShell 5.1](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/stop-computer?view=powershell-5.1). You were looking at version 7.1.
