### ISSUE TITLE
incomplete guides

### ISSUE THREAD

**Issue by ashishonce** [MicrosoftDocs/PowerShell-Docs#5733]
I feel a lot of documentation doesn't really work because we leave it halfway. Particularly in this example, there is  no reference as how person is going to invoke the cmdlet. this is like leaving user with a boat, without a paddle. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98fbc73-0a8c-aa2c-81c9-ff6b7c703649
* Version Independent ID: 978f08b0-5917-7592-a5bc-a3a82a574bb1
* Content: [How to Write a Simple Cmdlet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-write-a-simple-cmdlet?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-write-a-simple-cmdlet.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-write-a-simple-cmdlet.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
I am not sure what you are looking for in this article. The intent of the article is to show the minimal C# code to implement a cmdlet. 

Cmdlets are invoked by their name. The first paragraph says that the cmdlet is `Send-Greeting`.
