### ISSUE TITLE
No match was found for package name "Nuget"

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/PowerShell-Docs#5743]
When I run:
`Find-PackageProvider -Name "Nuget" -AllVersions` I suddenly get an error message of:
> Find-PackageProvider: No match was found for the specified search criteria and package name 'Nuget'. Try Get-PackageSource to see all available registered package sources.

in PowerShell core on linux and
![image](https://user-images.githubusercontent.com/2544867/78893253-4e2eca00-7a6b-11ea-9f32-724974d4f647.png)
in the Windows PowerShell

because of this our deploymentscript currently fails, it was working for a very long time, but now suddenly stopped working...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d14c05e-599a-e908-0bcc-e1a5d7ef961c
* Version Independent ID: 1ca59e2b-35f8-34c8-19ec-609bf8d11527
* Content: [Install-PackageProvider (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-packageprovider?view=powershell-7#feedback)
* Content Source: [reference/7.0/PackageManagement/Install-PackageProvider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PackageManagement/Install-PackageProvider.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
This looks like a network connection problem on your end. Also, make sure that you are using TLS 1.2. Run the following command then try again:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

See also

- https://support.microsoft.com/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi
- https://docs.microsoft.com/security/engineering/solving-tls1-problem

If you still have problems, try posting your problem in a community support forum.  For a list of community forums see: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by agowa338** [comment]
:facepalm: Ok, that works. Somehow I missed it in that specific script I have it in all the other ones...

**Comment by esarabadani** [comment]
> This looks like a network connection problem on your end. Also, make sure that you are using TLS 1.2. Run the following command then try again:
> 
> `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
> 
> See also
> 
> * https://support.microsoft.com/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi
> * https://docs.microsoft.com/security/engineering/solving-tls1-problem
> 
> If you still have problems, try posting your problem in a community support forum. For a list of community forums see: https://docs.microsoft.com/powershell/scripting/community/community-support

Thank you. Running this command worked for me:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
