### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by silverbackbg** [MicrosoftDocs/PowerShell-Docs#5749]
The search engine sent me here after looking "how to upgrade powershell from powershell" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67872723-9d70-6dd3-29fb-a66505cb98fb
* Version Independent ID: 7bb17de5-a42e-21ad-fac0-2ee40722b30c
* Content: [Installing Windows PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-Windows-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-Windows-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
It all depends on what version you want to upgrade from. The short answer is to install the newer version using the same method you used to install the previous version. 

Windows is the special-case scenario. If you are talking about upgrading from Windows PowerShell 5.1 to the latest, that answer is the same, install the latest package. The difference is that PowerShell v6 and higher installs side-by-side with Windows PowerShell 5.1. Windows PowerShell is not removable. 

If you want to upgrade PowerShell v6 to PowerShell v7, just install PowerShell v7 using the same package method used to install v6 (for example, the MSI package).
