### ISSUE TITLE
Add-LocalGroupMember is not recognized on windows server 2012 64 bit

### ISSUE THREAD

**Issue by aniruddha-git** [MicrosoftDocs/PowerShell-Docs#5753]
Add-LocalGroupMember is not recognized on windows server 2012 version. Is there a alternative way to execute the command or a similar method to add domain user to local admin group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 770f601f-0c0c-96a3-edf5-355d31ce2bee
* Version Independent ID: df1510c6-6f59-84ef-1532-aa228570a815
* Content: [Add-LocalGroupMember (Microsoft.PowerShell.LocalAccounts)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/add-localgroupmember?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.LocalAccounts/Add-LocalGroupMember.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.LocalAccounts/Add-LocalGroupMember.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You can always use the `net localgroup` command. But `Add-LocalGroupMember` should be available in PowerShell 5.1 on Server 2012.
