### ISSUE TITLE
Incorrect output in $ErrorActionPreference example

### ISSUE THREAD

**Issue by mhobbs-ibm** [MicrosoftDocs/PowerShell-Docs#5755]
The last output section in the $ErrorActionPreference example shows:
`Write-Error 'Hello World' ; Write-Host 'Hello World' : Hello World`

That does not line up with the input given, which was:
`Write-Error -Message 'Test Error' ; Write-Host 'Hello World'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc9c9b1-8eb7-3bf8-1ec7-13e5d01c31d6
* Version Independent ID: 02b20737-f11c-b6ce-5e32-9bf8781c01f6
* Content: [about_Preference_Variables - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by dqewdede** [comment]
@

[>](

- 

- [ ] url

)
