### ISSUE TITLE
Workflow feature on PowerShell Core 7

### ISSUE THREAD

**Issue by mdorantesm** [MicrosoftDocs/PowerShell-Docs#5762]
Hi. Could you please clarify if Workflow feature is actually available on PowerShell Core 7?

This page clearly says: "PSWorkflow Module" and also says: "Version PowerShell 7".

Yet, the CommandTypes Enum lacks Workflow value on PowerShell Core 7:
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.commandtypes

Thank you very much in advance for any clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2da5c334-7995-5486-32e3-4b4b9fd8ae1a
* Version Independent ID: a4d23abd-7b14-dac1-d690-48fc193efc52
* Content: [workflows guide - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/workflows-guide?view=powershell-7&source=docs#feedback)
* Content Source: [reference/docs-conceptual/components/workflows-guide.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/workflows-guide.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Workflows are only available Windows PowerShell 5.1. The page does not actually say that it is supported in PowerShell 7. In fact it only mentions "Windows PowerShell". But, because of a limitation in our docs version system, I can't filter the conceptual documentation by version. We are working fixing that problem.

**Comment by mdorantesm** [comment]
Hi, @sdwheeler . Thank you for your response.
Understood.
Thank you very much for the clarification.
