### ISSUE TITLE
Interfaces cannot be declared, only implemented.

### ISSUE THREAD

**Issue by oising** [MicrosoftDocs/PowerShell-Docs#5765]
The language above implies that interfaces can be defined (declared) but this is not the case.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7#interfaces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65304a8f-89f7-f1f9-cad8-6cb0d36c5634
* Version Independent ID: a5651d52-5618-47e4-67df-6191278f0ad5
* Content: [about_Classes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7#interfaces)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by rjmholt** [comment]
The current wording here is:

> The syntax for declaring interfaces is similar to C#. You can declare interfaces after base types or immediately after a colon (:) when there is no base type specified. Separate all type names with commas.

But we don't (currently) support interface *declaration*, only inheritance. It sounds like the wording would be better as something like:

> ### Inheriting from interfaces
> PowerShell classes can implement an interface by using the same inheritance syntax (`:`) used to extend base classes. Because interfaces allow multiple inheritance, a PowerShell class implementing an interface may inherit from multiple types, by separating the type names after the colon (`:`) with commas (`,`). A PowerShell class that implements an interface must implement all the members of that interface; not implementing interface members will cause a parse-time error in the script.
>
> > [!NOTE]
> > PowerShell does not currently support declaring new interfaces in PowerShell script.
