### ISSUE TITLE
some features are not documented

### ISSUE THREAD

**Issue by i-m-here** [MicrosoftDocs/PowerShell-Docs#5766]
some features are not documented

Hi,

```
PS WALID> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0




```
### (1) -not operator

its possible to chaining this operators:

with this feature its possible t convert an expression/statement to a booelean or to evaluaate the opposite of one expression $true became $false and $false became $true

```
PS WALID> -not $true
False
PS WALID> -not -not $true
True
PS WALID> !!$true
True
PS WALID> !0
True
PS WALID> !(1..5 -eq 3)
False
PS WALID> !!(1..5 -eq 3)
True
PS WALID> !!!!!!1
True
PS WALID> !!!!!1
False

```

### (2) -replace operator

the documentation about_Regular_Expressions miss some feature to -replace operators, only the special variable **${subset}, $1, $&** are documented but there are many others...

```
# $1,$2,..: Contains the subpattern from the corresponding set of capturing parentheses from the last successful pattern match
PS WALID> 'powershell' -replace '(power)(shell)','$2 $1' 

# ${var} : Contains the named subpattern from the corresponding set of capturing parentheses from the last successful pattern match
PS WALID> 'powershell' -replace '(?<first>power)(?<second>shell)','${second} ${first}' 

# $0 : The string matched by the last successful pattern match
PS WALID> '123456789' -replace '5','($0 $0)' 

# $& : The string matched by the last successful pattern match
PS WALID> '123456789' -replace '5','($& $&)' 

# $_ : contains all input data 
PS WALID> '123456789' -replace '5','($_)'        

# $` : The string preceding whatever was matched by the last successful pattern match 
PS WALID> '123456789' -replace '5','($`)'

# $' : The string following whatever was matched by the last successful pattern match
PS WALID> '123456789' -replace '5',"($`')"     

# $+ : The text matched by the highest used capture group of the last successful search pattern. It is logically equivalent to the highest numbered capture variable ($1 , $2 , ...) which has a defined value
PS WALID> '123456789' -replace '^(.)(.)(.)(.)','($+)' # '^(.)(.)(.)(.)','($4)'


```
### (3) ternary operators

the documentation forgot to mention that the ternary operator can be nested:

```
PS WALID> $n = 3
PS WALID> 1 -eq $n ? 1 : 2 -eq $n ? 2 : 3 -eq $n ? 3 : 4
#  use parentheses for operation precedence
PS WALID> 1 -eq $n ? 1 : ( 2 -eq $n ? 2 : (3 -eq $n ? 3 : 4))
```

**Comment by sdwheeler** [comment]
@i-am-here There is nothing specific to the operators that allows or prevents "chaining" or "nesting" as you describe it. This behavior is described by the [grouping operator](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_operators#grouping-operator--).

For the `-replace` operator, the intent of that documentation is to explain the operator, not the complete set of possible ways to use regular expressions. We have a separate article on [regular expressions](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_regular_expressions). And that article links the [more detailed articles](https://docs.microsoft.com/dotnet/standard/base-types/regular-expression-language-quick-reference#substitutions) in the .NET documentation.
