### ISSUE TITLE
wrong directory name

### ISSUE THREAD

**Issue by alan-isaac** [MicrosoftDocs/PowerShell-Docs#5767]
The user profile needs to be in `WindowsPowerShell` not `PowerShell`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f16e6db-f237-8271-e158-50038a662a67
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about_Profiles - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
That is true for Windows PowerShell 5.1. You were looking at the help for PowerShell 7. The correct folder name is `PowerShell` for PowerShell 6 and higher.
