### ISSUE TITLE
New UseNewEnvironment parameter behavior of Start-Process cmdlet on Windows

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#5774]
# Documentation Issue

Need to update docs after https://github.com/PowerShell/PowerShell/pull/10830

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Windows only

**Comment by sdwheeler** [comment]
@iSazonov What was the final behavior implemented by the code PR?

**Comment by iSazonov** [comment]
From the PR description:
> The PR effects only Windows behavior.
- With UseNewEnvironment parameter Start-Process run a child process with environment variables without modifications in current session (state before the session start).
See #4671 and PowerShell Committee conclusion #10745 (comment)
- Without UseNewEnvironment parameter Start-Process run a child process with current environment variables from current session. (This allow us easily to add -Environment parameter late)

By default Start-Process creates new process which inherits all env variables including added/modified in current pwsh process.
With UseNewEnvironment Start-Process _takes env variables from system_ and so ignores all changes which was made in pwsh and in ancestor processes.

Follow behavior preserved - If Start-Process creates new process with another user credentials then env variables is created as it is created at the user logon.
