### ISSUE TITLE
Remove information about conhost.exe keyboard shortcuts, link to PSReadline

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5777]
At least for the PowerShell versions that ship with `PSReadLine` (v5+?), there is no point in listing the `conhost.exe` (Windows console-window) keyboard shortcuts, because `PSReadLine` preempts them - ditto in Unix terminal emulators and Windows Terminal.

By now, `PSReadLine` is loaded by default in all major PS hosts: consoles / terminals and the Visual Studio Code PowerShell Integrated Console.

Linking to the `PSReadLine` documentation is therefore important.

It is also worth pointing out that `PSReadLine` maintains its own, persistent history, while the built-in history is limited to the current session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c514067-a622-fd8b-9d64-3034a7485e95
* Version Independent ID: 936ffb0f-739d-e58c-360e-e05a9129b186
* Content: [about_History - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_history?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_History.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_History.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
We have to document them because PSReadLine is optional. You can unload it.

**Comment by mklement0** [comment]
Please see #5780.
