### ISSUE TITLE
Reframe the topic to focus on the default behavior with respect to keyboard shortcuts

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5780]
I suggest reversing the framing of the topic:

It is `PSReadLine` that controls keyboard shortcuts, including history-related ones.

In the major hosts  - the `ConsoleHost` for running in console windows / terminals, as well as the PowerShell Integrated Console in Visual Studio - `PSReadLine` is _loaded by default_, so that will be the default experience for most users.

**While it's possible to _opt-out_ by _manually unloading_ `PSReadLine` _focusing_ on that opt-out experience, the way the topic currently does,  is confusing** - not least because it is limited to the behavior of `conhost.exe` (Windows console windows).

Therefore:

* Stress the default behavior (`PSReadLine`).

  * Listing _`PSReadLine`'s_ history-related default key bindings would be helpful (in addition to the existing link to the `PSReadLine` documentation).

* Clearly state that the key bindings currently listed:

   *  (a) apply to _`conhost.exe`_ windows on _Windows only_ with _`PSReadLine` manually unloaded_
   * and that (b) it is then generally _up to whatever host program is running PowerShell_ to provide history-related keyboard shortcuts, _if any_ (Windows Terminal and the Unix terminals don't offer any, from what I can tell).

Honestly, given that there's little reason _not_ to use `PSReadLine`, **I'm not sure that documenting the `conhost.exe` keyboard shortcuts is even necessary** - a link to the `conhost.exe` documentation would suffice, and perhaps a note to `cmd.exe` user that the keybindings they're used to won't work (but could be configured to work similarly via `PSReadLine`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1777470c-18a0-e5e6-2a51-7f432d8e18fd
* Version Independent ID: 936ffb0f-739d-e58c-360e-e05a9129b186
* Content: [about_History - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_history?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_History.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_History.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
There is no documentation for `conhost.exe`. The key bindings are in PowerShell code for the hosts we ship. `Conhost.exe` is a Windows component, not a PowerShell component.

See key bindings in:
https://github.com/powershell/powershell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs

**Comment by mklement0** [comment]
@sdwheeler, the file you link to contains none of the history-related `conhost.exe` bindings, and that these key bindings are _not_ part of PowerShell is evidenced by the fact that, after unloading `PSReadLine`, for instance, <kbd>F7</kbd> doesn't work in any other terminal emulator, notably neither in Windows Terminal nor the terminal emulators on macOS and Linux.

That `conhost.exe` is indeed a Windows-specific component - and as such not worth documenting in PowerShell - was part of the motivation for opening this issue.

Official documentation for the `conhost.exe` keyboard shortcut indeed seems to be lacking:

* https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts, under "Command Prompt keyboard shortcuts" does _not_ mention them.

* Fortunately, a third-party site comes to the rescue: https://ss64.com/nt/syntax-keyboard.html, under "CMD shell Command History shortcuts", does list them (despite misclassifying them as `cmd.exe` shortcuts).

**Comment by mklement0** [comment]
I found the official documentation: it is part of the `doskey.exe` documentation.

Given that no `doskey` _process_ run in a `conhost.exe` console window, I'm unclear on the exact mechanism, but it is clear that it is the source of the functionality discussed:

> Doskey.exe is always available for all character-based, interactive programs (such as program debuggers or file transfer programs), and it maintains a command history buffer and macros for each program that it starts. 

See https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/doskey#remarks
