### ISSUE TITLE
Two Localhost mof files in config folder  localhost.mof & mycomputername.mof

### ISSUE THREAD

**Issue by Jasonthurston** [MicrosoftDocs/PowerShell-Docs#5783]
From the documentation I can't see what would happen if I ran:
Set-DscLocalConfigurationManager -Path "C:\DSC\Configurations\"  where I have two mof files, one with the actual hostname and the other with 'localhost'....Do they both get applied?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c233a73-f2d2-a27e-4c0f-baf5e4076b5f
* Version Independent ID: 2b81adca-6b3c-ef25-5c25-c543c5ee04bd
* Content: [Set-DscLocalConfigurationManager (PSDesiredStateConfiguration)](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/set-dsclocalconfigurationmanager?view=powershell-5.1)
* Content Source: [reference/5.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @nitinbps
* Microsoft Alias: **nitingup**

**Comment by chasewilson** [comment]
I don't see that this should normally be the case  unless you intentionally place them in the same directory. When you compile your meta mof, a folder with the name of the configuration is created and the mof is compiled in the new folder. 

However, if you did place another compiled meta mof within the  same folder manually,  or you named another configuration the same as the initial configuration, when you run `Set-DscLocalConfigurationManager` it will run the first listed configuration. The LCM will attempt to run for all mofs located in the folder, but you will get the error below:

```Output
Cannot invoke the Set-DscLocalConfigurationManager cmdlet. The Set-DscLocalConfigurationManager cmdlet is in progress   and must return before Set-DscLocalConfigurationManager can be invoked. Use -Force option if that is available to       cancel the current operation.                                                                                               + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException                     + FullyQualifiedErrorId : MI RESULT 1                                                                                   + PSComputerName        : TestComputer 
```

If you use the `-Force` parameter switch, you will get the following error with the first mof still being applied:

```Output
The current configuration was cancelled.                                                                                    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException                     + FullyQualifiedErrorId : MI RESULT 1                                                                                   + PSComputerName        : localhost
```
I will add a note to the page summarizing this. .

Feel free to reach out if you have any questions.
