### ISSUE TITLE
psremoting works to any server except localhost unless running as elevated

### ISSUE THREAD

**Issue by Jasonthurston** [MicrosoftDocs/PowerShell-Docs#5793]
I don't see how to allow psremoting to localhost without being elevated.   Often I've got to a large set of hosts to psremote to and it's not always easy to know when one happens to be the hostname or an alias of the local machine.  So it's hard to handle the localhost differently if you are not certain it even is the localhost in bulk processing.    So I'm trying to figure out how to configure the domain such that all users (or just administrators) can psremote to the localhost without running powershell in an elevated shell....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d245dc8-295a-cf6b-3756-d26c0fe229ca
* Version Independent ID: a76fca56-4886-3479-600b-4f3775e42c5c
* Content: [about_Remote_Troubleshooting - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_troubleshooting?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Have you tried granting permissions as described here? https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_remote_troubleshooting?view=powershell-6#how-to-enable-remoting-for-non-administrative-users
