### ISSUE TITLE
AzureAD\users?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/PowerShell-Docs#5794]
Does this cmdlet properly support removing AAD users who have signed into a Windows computer?

e.g. A device/global admin signed into somebody's computer to conduct administrative adjustments (like system time), and won't ever need to sign back in again. So can it remove the local AzureAD\admin user account and folders?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb1803a6-a0d1-b101-ebc4-6dd7dad45295
* Version Independent ID: 04f38843-6190-49c4-0f0f-00772045d642
* Content: [Remove-LocalUser (Microsoft.PowerShell.LocalAccounts)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/remove-localuser?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalUser.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalUser.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This cmdlet has nothing to do with the user profile. This is for managing accounts in the local computer's security database. You can delete a profile using the Win32_UserProfile WMI class. This blog post as a good example: https://adamtheautomator.com/powershell-delete-user-profile/
