### ISSUE TITLE
The command is not running on my win8.1 system

### ISSUE THREAD

**Issue by melli79** [MicrosoftDocs/PowerShell-Docs#5795]
Are there any requirements for this to work, e.g. previously install a system component?  Also is that supported by PowerShell on windows 8.1 Enterprise? And beside the bare name `Compress-Archive` should I specify anything else, e.g. a package?

The exact error message is:
`2020-04-16T14:14:53.0793866Z ##[error]Compress-Archive : The term 'Compress-Archive' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.`

The calling line (from a *.ps1 script) is:
`  Compress-Archive -DestinationPath "$imageArchive" -Path "$images"`
where the variable $imageArchive contains a file name (ending in .zip) and $images is a Get-Items result (with at least 1 entry).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291a173d-9b76-2912-f6d8-fcb2c9183052
* Version Independent ID: 3c8b8ee9-6a97-4eda-d184-49e728abf0a6
* Content: [Compress-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Archive/Compress-Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Archive/Compress-Archive.md)
* Product: **powershell**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

**Comment by sdwheeler** [comment]
@melli79  What version of PowerShell are you using? These cmdlet were added in PowerShell 5. Windows 8.1 shipped with PowerShell 4.0.

**Comment by melli79** [comment]
That's it, the installed version is 4.0 (still here).  Could you leave a comment somewhere on this site stating "available from PowerShell version 5"?

Thanks

**Comment by sdwheeler** [comment]
It's listed in the release notes: https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-windows-powershell-50#new-features-in-windows-powershell

**Comment by OZ1** [comment]
Required PowerShell version should be mentioned in cmdlet's documentation.
