### ISSUE TITLE
SHA extensions

### ISSUE THREAD

**Issue by 1337cypher** [MicrosoftDocs/PowerShell-Docs#5801]
Does Get-FileHash use Hardware Accelerated SHA Extensions automatically on systems with CPUs that support it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0be20ca-3996-7ff9-04ba-f2cc473513ad
* Version Independent ID: 8f5975ef-d031-8254-bc66-252f44964dee
* Content: [Get-FileHash (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Get-FileHash.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
I don't think so. PowerShell is using the [HashAlgorithm.ComputeHash](https://docs.microsoft.com/dotnet/api/system.security.cryptography.hashalgorithm.computehash?view=netcore-3.1#System_Security_Cryptography_HashAlgorithm_ComputeHash_System_IO_Stream_) method in .NET Core. So this is more of a .NET question.
