### ISSUE TITLE
Wrong alias for -Milliseconds?

### ISSUE THREAD

**Issue by LinqLover** [MicrosoftDocs/PowerShell-Docs#5803]
The description of the `-Milliseconds` parameter says:
&gt; The parameter can be abbreviated as `m`.

However, in the table, the alias `ms` is mentioned.

On my machine, only the first version (`-m`) works. Does the table contain the wrong alias?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8084403-8fd5-d347-882f-53644f02eba5
* Version Independent ID: a874cf88-e612-8833-188e-9afdcc541cd7
* Content: [Start-Sleep (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/start-sleep?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The alias is `ms` in PowerShell 6 and higher. The value in the table is incorrect for v5.1.

**Comment by LinqLover** [comment]
Great, thank you!
