### ISSUE TITLE
Explain return

### ISSUE THREAD

**Issue by reinierk** [MicrosoftDocs/PowerShell-Docs#5805]
Article describes the "return statement" but not how to return values....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcec64ef-b2cf-860a-746e-4dd564dc7162
* Version Independent ID: c7397f10-91d3-c735-244f-bfaa1072545a
* Content: [about_Functions - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The `return` statement is documented in [about_Return](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_return), which is linked in this article.

While `return` works with functions it is most useful in PowerShell Class methods where it is the only way of returning values from the method.

In functions you can return any object/value using `Write-Output` or the equivalent variable reference.

**Comment by reinierk** [comment]
Hallo Sean,The suggestion is of cause about the documentation. Not the technology... Where *in this* (technical) *document* is explained how to return something to the caller?Kind regards, Reinier Kleipool Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Sean Wheeler <notifications@github.com> Datum: 20-04-20  18:12  (GMT+01:00) Aan: MicrosoftDocs/PowerShell-Docs <PowerShell-Docs@noreply.github.com> Cc: Reinier Kleipool <reinier@OpenSourceAcademy.eu>, Author <author@noreply.github.com> Onderwerp: Re: [MicrosoftDocs/PowerShell-Docs] Explain return (#5805) 
The return statement is documented in about_Return, which is linked in this article.
While return works with functions it is most useful in PowerShell Class methods where it is the only way of returning values from the method.
In functions you can return any object/value using Write-Output or the equivalent variable reference.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5805#issuecomment-616655023",
"url": "https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5805#issuecomment-616655023",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
