### ISSUE TITLE
Named Parameters

### ISSUE THREAD

**Issue by reinierk** [MicrosoftDocs/PowerShell-Docs#5806]
What are valid values for the optional [TYPE] of a named parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcec64ef-b2cf-860a-746e-4dd564dc7162
* Version Independent ID: c7397f10-91d3-c735-244f-bfaa1072545a
* Content: [about_Functions - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions?view=powershell-5.1#see-also)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Parameters can be any .NET type.

**Comment by reinierk** [comment]
Please augment documentation to reflect this.Kind regards, Reinier Kleipool Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Sean Wheeler <notifications@github.com> Datum: 20-04-20  18:14  (GMT+01:00) Aan: MicrosoftDocs/PowerShell-Docs <PowerShell-Docs@noreply.github.com> Cc: Reinier Kleipool <reinier@OpenSourceAcademy.eu>, Author <author@noreply.github.com> Onderwerp: Re: [MicrosoftDocs/PowerShell-Docs] Named Parameters (#5806) 
Parameters can be any .NET type.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5806#issuecomment-616656425",
"url": "https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5806#issuecomment-616656425",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
