### ISSUE TITLE
Is this command different then just  

### ISSUE THREAD

**Issue by jargule** [MicrosoftDocs/PowerShell-Docs#5809]
Is this command `New-PSSession -HostName WinVM2 -UserName PSRemoteUser`
different from just `ssh -l UserName Hostname`?
Is it better is some way?
I am ssh-ing to a linux computer 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e79ea6-1d79-6147-aa3e-362b04bc7528
* Version Independent ID: 8877b05f-1f52-8c75-2d7d-5100cc52c4cb
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
`New-PSSession` creates a remote PowerShell session. It can connect to an interactive shell on the remote PowerShell using `Enter-PSSession` or you can run PowerShell commands in the remote session from the local computer.

The `ssh` connects to the default shell on the remote session. This is usually not PowerShell.
