### ISSUE TITLE
What's the scope?

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/PowerShell-Docs#5814]
It would be helpful if you'd clarify the scope/duration of the effect of this command.  Does the command affect:
- This PS window only, or all open PS windows?  Do I need to reopen other PS windows?
- Future login sessions, or only this session?  Will I need to run it again in the future after I reboot my computer?
- Only my user account, or all users on my computer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 556b2007-7007-93bc-3b0c-f0e02ea9dd36
* Version Independent ID: 7c51859b-a7e9-33b9-e3fb-b795802b98f5
* Content: [Set-PSRepository (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/set-psrepository?view=powershell-7)
* Content Source: [reference/7.0/PowerShellGet/Set-PSRepository.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PowerShellGet/Set-PSRepository.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
The setting is global and persistent. It affects all users.
