### ISSUE TITLE
Update default location where its stored.

### ISSUE THREAD

**Issue by seanatcsaa** [MicrosoftDocs/PowerShell-Docs#5817]
What is the default location? Could it be updated to say where that is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41859818-aed1-0b92-eaf5-5d8fb84d3e0e
* Version Independent ID: afe03c1f-3dbf-62f7-722a-d845777cadbd
* Content: [Start-Transcript (Microsoft.PowerShell.Host)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Host/Start-Transcript.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Host/Start-Transcript.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This information is in the article:

### -Path
Specifies a location to the transcript file. Enter a path to a .txt file. Wildcards are not permitted.

If you do not specify a path, `Start-Transcript` uses the path in the value of the `$Transcript` global variable. If you have not created this variable, `Start-Transcript` stores the transcripts in the `$Home\My Documents` directory as `\PowerShell_transcript.<time-stamp>.txt` files.
