### ISSUE TITLE
a more common compare two sets of objects example 

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#5824]
I'm surprised there's not already an example like this comparing two sets of objects.  This is a common point of confusion .  You usually need to specify -property when comparing objects.
```powershell
$a = [pscustomobject]@{name='joe'}
$b = [pscustomobject]@{name='joey'}

compare-object $a $b  # no output

compare-object $a $b -property name

name SideIndicator
---- -------------
joey =>
joe  <=
```

Actually, I don't even think this is true:

> The result of the comparison indicates whether a property value appeared only in the reference object (<=) or only in the difference object (=>). If the IncludeEqual parameter is used, (==) indicates the value is in both objects.

```powershell
$a = [pscustomobject]@{name='joe';address='here'}   
$b = [pscustomobject]@{name='joey'}              
compare-object $a $b  # no output
```

It looks to me that example 4 is just converting each array to strings, and then comparing the string versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75188614-c25b-02bf-f3bc-da5ab0aa1e30
* Version Independent ID: 85f1e969-8216-bed4-2204-409cbd9befd4
* Content: [Compare-Object (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/compare-object?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Compare-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Compare-Object.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
You are half right about the string comparison. If you compare two complex objects without specifying one or more properties, the cmdlet tries several different methods to do the comparison. It checks for an IComparable interface, it checks for object-specific Equals methods. When those fail, it resorts to comparing the ToString() results of the objects.

**Comment by jszabo98** [comment]
> You are half right about the string comparison. If you compare two complex objects without specifying one or more properties, the cmdlet tries several different methods to do the comparison. It checks for an IComparable interface, it checks for object-specific Equals methods. When those fail, it resorts to comparing the ToString() results of the objects.

True, but objects having a meaningfull .compareto() or .equals() method seem rare.  The only common example I can come up with is a datetime object.

**Comment by jszabo98** [comment]
Note also that when comparing text files, compare-object sorts them first.  So two files with lines in a different order will come out equal.

```powershell
$file1 = 'line one','line two','line three'
$file2 = 'line three','line two','line one'
compare-object $file1 $file2 -IncludeEqual

InputObject SideIndicator
----------- -------------
line two    ==
line one    ==
line three  ==
```

**Comment by jszabo98** [comment]
I still think this document is confusing.  This statement is patently false, unless the -property parameter is being used.

"The result of the comparison indicates whether a property value appeared only in the reference object (<=) or only in the difference object (=>)."

**Comment by sdwheeler** [comment]
@jszabo98 Would you be willing to submit a PR with the changes you would like to see?
