### ISSUE TITLE
Sshd configuration note regarding path to powershell

### ISSUE THREAD

**Issue by scabon** [MicrosoftDocs/PowerShell-Docs#5830]
The steps regarding the sshd configuration on the remote host use this path to the Powershell executable:
Subsystem powershell /usr/local/bin/pwsh -sshs -NoLogo -NoProfile
In my case, powershell was installed as a .net global tool, and the correct configuration is user/system dependent:
Subsystem powershell /home/mysername/.dotnet/tools/pwsh -sshs -NoLogo -NoProfile

If the path to the powershell executable is incorrect nothing will happen when trying to open the remote session (no error is sent back to the client).

I think a note should be added that '/usr/local/bin/pwsh' is the default installation path but that it might vary and require modification when updating the sshd configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e79ea6-1d79-6147-aa3e-362b04bc7528
* Version Independent ID: 8877b05f-1f52-8c75-2d7d-5100cc52c4cb
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by majkinetor** [comment]
```ps1

$pwsh_path = Get-Command pwsh | % Path
$fso = New-Object -ComObject Scripting.FileSystemObject
$pwsh_path = $fso.getfile($pwsh_path).ShortPath

"
PasswordAuthentication yes
Subsystem powershell $pwsh_Path -sshs -NoLogo -NoProfile
" | Out-File $env:ProgramData\ssh\sshd_config
```
