### ISSUE TITLE
Document the limitation that elements of arrays of mutable value types cannot be modified

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5833]
See https://github.com/PowerShell/PowerShell/issues/12411#issuecomment-619065783 for technical background.

In short: 

* If you create a _strongly typed_ array using a _mutable_ value type (which isn't common), attempts to modify properties of its elements are quietly ignored.

* The workaround is to create an `[object[]]` array instead.

To demonstrate the problem:

```PowerShell
Add-Type 'public struct Foo { public int x; }' # create mutable value type
$arr = [Foo[]]::new(1)  # define a 1-element array of that value type.
$arr[0].x = 1 # Try to modify the 1st element  - THIS IS EFFECTIVELY A NO-OP
$arr[0].x # -> !! 0 - value was NOT changed
```

The workaround is to create an `[object[]]` array (which is less efficient):

```PowerShell
Add-Type 'public struct Foo { public int x; }' # create mutable value type
# Workaround: create the array as [object[]]
[object[]] $arr = [Foo[]]::new(1)  # define a 1-element array of that value type.
$arr[0].x = 1 # Modifying the 1st element now succeeds.
$arr[0].x # -> 1 - OK
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da50f473-b315-4af8-ee5c-a37abb01f19e
* Version Independent ID: ab878bfa-19e1-2011-aaf8-37456f420ddb
* Content: [about_Arrays - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by vexx32** [comment]
> quietly ignored

Not really, no. It's just how value types work and interact with PowerShell's practically omnipresent boxing behaviours; they get copied when you try to index them. It's a very rare edge case, and while I agree we should document it, I don't think we should misrepresent it.

Is it surprising? Well, that really depends. The recommendations for structs is explicitly to _not_ create mutable structs unless you have a real need to. By the time you get into that territory, you're more or less on your own. PowerShell is so far from that territory it almost seems not worth documenting.

But if we are, it needs to be documented carefully; mutable value types are very confusing if you're looking at them from a typical PowerShell user's viewpoint.

**Comment by mklement0** [comment]
> Not really, no.

Of course I meant: _effectively_ ignored, _from the perspective of the user's intent_.

That is _technically_ not ignored is of little consequence, and the details of _that_ are not worth documenting (at least not in the conceptual help topics).

> Is it surprising? 

Yes - and that's why it should be documented.

As you know, people do run into this (#12470, which @iSazonov just linked to).

**Comment by mklement0** [comment]
To put it differently: It is precisely because you normally need _not_ worry even about the distinction between value types and reference types in general that these edge cases are worth mentioning:

As a PowerShell user, you should be able to use .NET types as transparently as possibly, without having to worry about these distinctions -  whether you came across a mutable value type via third-party code or even if you created one yourself.

Without intimate knowledge of PowerShell internals and advanced .NET knowledge you won't be able to make sense of the behavior.

**Comment by mklement0** [comment]
As for how common mutable value types are, to quote @SeeminglyScience from https://github.com/PowerShell/PowerShell/issues/12411#issuecomment-618745152:

> Of course that doesn't mean there are zero reasons to define a mutable struct. They're great in incredibly performance sensitive code and interop, but without intimate knowledge of their behavior they're confusing for everyone.

C# language support for high-performance code was introduced only fairly recently, so it's not unlikely that more mutable value types will start to appear.

**Comment by SeeminglyScience** [comment]
> Of course I meant: _effectively_ ignored, _from the perspective of the user's intent_.
> 
> That it is _technically_ not ignored is of little consequence, and the details of _that_ are not worth documenting (at least not in the conceptual help topics).

It's not a technicality though, it's by design behavior.  I get where you're coming from with the wording but the tone is very negative, like you're describing a mistake.

> Yes - and that's why it should be documented.

I don't really think that documenting the differences between reference types and value types is within the scope of PowerShell's responsibility.

> C# language support for high-performance code was introduced only fairly recently, so it's not unlikely that more mutable value types will start to appear.

Some additional tools were added to make it easier, but it's very unlikely you'll see an increase in *public* mutable structs.  Even if you do, it's likely going to involve `Span<T>`, other byref-like types, `ref` return values or unmanaged pointers (none of which PowerShell can support).

**Comment by mklement0** [comment]
> but the tone is very negative

I chose to word it from the  perspective of the user's intent, and from that perspective it's a fair characterization - not a value judgment.
But I'm not attached to the particular wording.

> I don't really think that documenting the differences between reference types and value types is within the scope of PowerShell's responsibility.

I agree - and it's certainly not what this issue is requesting.

> Even if you do, it's likely going to involve Span<T>, other byref-like types, ref return values or unmanaged pointers (none of which PowerShell can support).

Good to know.
It's a tangent, but I'm curious how that relates to your proposal in https://github.com/PowerShell/PowerShell/issues/11768

**Comment by SeeminglyScience** [comment]
> It's a tangent, but I'm curious how that relates to your proposal in [PowerShell/PowerShell#11768](https://github.com/PowerShell/PowerShell/issues/11768)

`Memory<T>` support is easy because it represents something that lives on the heap (for the most part) from which you can obtain a `ref` to *on demand*.  It doesn't hold an actual managed pointer like `Span<T>` does.  Also even with my proposal you wouldn't be able to *save* the span.

**Comment by mklement0** [comment]
> Memory<T> support is easy because it represents something that lives on the heap

So do arrays of mutable value types, as in the example in the OP.

As shown in your proposal, you want to support `$memory[0] = 1` or perhaps `$memory.Span[0] = 1` -  is `$memory[0].x = 1` then still not an option?

> Also even with my proposal you wouldn't be able to _save_ the span.

Saving a span is neither a requirement for the use case in this issue, nor in the one in #5834, at least not from the user's perspective.

---

Either way, the gist of this issue (and also #5834) is that end users need to be told the following:

"Here's something you may try and it won't work as you expect.
It isn't supported for (good) technical reasons."

_Briefly_ mentioning the specific circumstances (see OP) in which the problem occurs is enough, perhaps along with a quick test (problem happens if `[Foo].IsValueType` /  `$arr[0].GetType().IsValueType` is `$true`), with a _link_ to more information, for those who want to understand _why_ - not everyone will.
Linking to [your explanation here](https://github.com/PowerShell/PowerShell/issues/12411#issuecomment-619065783) may be enough.

Once the official non-support for these uses case is documented, users can discover the information themselves, or can easily be pointed to it.

**Comment by SeeminglyScience** [comment]
> So do arrays of mutable value types, as in the example in the OP.

Yeah, and you can interact with them in the same way you would be able to with `Memory`.

> As shown in your proposal, you want to support `$memory[0] = 1` or perhaps `$memory.Span[0] = 1` - is `$memory[0].x = 1` then still not an option?

`$memory[0] = 1` would work just like `$array[0] = 1` works. Likewise `$memory[0].x = 1` would not work if you are expecting it to alter the location in memory that the index is referring to.

Also this will still work just fine as it does with arrays:

```powershell
$item = $memoryOrArray[0]
$item.x = 10
$memoryOrArray[0] = $item
```

> Saving a span is neither a requirement for the use case in this issue, nor in the one in #5834, at least not from the user's perspective.

I didn't mean to imply it was, I was explaining why the proposal you linked doesn't conflict with anything I've posted.  That said, it certainly would help make that use case possible, because if you could safely save a span then you could probably save a managed pointer.  While that wouldn't outright solve the problem, it'd be a big step towards making it feasible (it would also bring about general instability and performance degradation though, or at least that's what is claimed in the EMCA spec).

**Comment by mklement0** [comment]
I appreciate the clarifications, @SeeminglyScience.

**Comment by sdwheeler** [comment]
After discussion in Shiproom, it was decided to move this information to the wiki: https://github.com/MicrosoftDocs/PowerShell-Docs/wiki/Variables-can-be-assigned-values-as-part-of-an-expression-(with-limitations)
