### ISSUE TITLE
Document the ability use variable assignments as part of expressions, mention pitfall with mutable value types

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5834]
PowerShell allows you to use assignments as part of expressions by enclosing the assignment in `(...)`, which passes the assigned value through; e.g.:

```powershell
# In an `if` conditional
if ($foo = Get-Item /) { "$foo exists" }  # -> "C:\ exists"

# Property access
($profileFile = Get-Item $PROFILE).LastWriteTime 

# You can even *assign* to such expressions, but that doesn't always work (see below).
($profileFile = Get-Item $PROFILE).LastWriteTime = Get-Date
```

This should be documented.

Additionally, it should be documented that the _assignment_ case doesn't _always_ work, and that when it doesn't, the assignment is quietly ignored.

See https://github.com/PowerShell/PowerShell/issues/12411#issuecomment-619065783 for technical background.

In short:

* If you create an instance of a _mutable_ value type, which isn't common) and attempt to both save the instance in a variable and modify one of its properties in the same expression, the assignment is quietly discarded.

* The workaround is to create the instance and save it in a variable first, and then assign to the property via the variable:

```powershell
Add-Type 'public struct Foo { public int x; }' # create mutable value type
# Create an instance, store it in a variable, and try to modify its property.
($var = [Foo]::new()).x = 1 # This assignment is effectively IGNORED.
$var.x # -> !! 0 
```

Workaround:

```powershell
Add-Type 'public struct Foo { public int x; }' # create mutable value type
# Create an instance and store it in a variable first
$var = [Foo]::new()
# ... and then modify its property via the variable.
$var.x = 1 # OK
$var.x # -> 1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0ee120-7f4d-31e2-c50d-f4822814f99b
* Version Independent ID: 8065724f-44e5-a0a4-0875-2a1ed03139d8
* Content: [about_Variables - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Variables?view=powershell-7&viewFallbackFrom=powershell-7.1)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Variables.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
After discussion in Shiproom, it was decided to move this information to the wiki: https://github.com/MicrosoftDocs/PowerShell-Docs/wiki/Variables-can-be-assigned-values-as-part-of-an-expression-(with-limitations)
