### ISSUE TITLE
Need to run commands on power shell with run as administrator privilege

### ISSUE THREAD

**Issue by iamamanbhardwaj** [MicrosoftDocs/PowerShell-Docs#5839]
I am trying hard to run a script with #Require RunAsAdministrator statement.
I am using System.Management.Automation aka Microsoft.PowerShell.5.ReferenceAssemblies.**

i am failing to run the script when my Visual studio is not running as administrator.  Help!! 

i want to deploy share this with team @ covid crisis

**Comment by sdwheeler** [comment]
`#Require -RunAsAdministrator` does not elevate the script. It is there to prevent script execution if the script is run without elevation. You must elevate the process that is running the script.

**Comment by iamamanbhardwaj** [comment]
I am asking , how to elevate the power shell instance in SDK to run the script as administrator ? 

I tried setting execution policy , but was not successful. 

Any input on how to achieve this will be appreciated

**Comment by sdwheeler** [comment]
There lots of examples of how to do this on the web. Basically, they all relaunch the program in Admin mode. You can do that in the script or in C# for the host process. But you still get prompted by UAC. 

Here is an example in C# - https://systemoutofmemory.com/blogs/the-programmer-blog/c-force-net-application-to-run-as-administrator
