### ISSUE TITLE
How to install PS Core on WLS2 on Ubuntu?

### ISSUE THREAD

**Issue by whihathac** [MicrosoftDocs/PowerShell-Docs#5846]
How to install PS Core on WSL2 on Ubuntu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by whihathac** [comment]
Snapd doesn't seem to be working in WLS2

**Comment by sdwheeler** [comment]
What version of Unbuntu are you using? These versions are not officially supported.

- Ubuntu 18.10 is an interim release that's community supported.
- Ubuntu 19.04 is an interim release that's community supported.

**Comment by sdwheeler** [comment]
See https://github.com/PowerShell/PowerShell/issues/12051
