### ISSUE TITLE
Add info about using the semicolon operator to separate statements in script block and sub-expression

### ISSUE THREAD

**Issue by M0sc** [MicrosoftDocs/PowerShell-Docs#5847]
Add info about semicolon operator (;) to description of [Special Operators](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators?view=powershell-7#special-operators) type (same as for example about [Comma operator `,`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators?view=powershell-7#comma-operator-)).

Examples of using semicolon (;) to separate statements / commands:
```
# Additional commands in the script block on one line.
Invoke-Command -ScriptBlock {$objShell = New-Object -COMObject "Shell.Application"; $objShell.ToggleDesktop()}

# Use a semicolon (;) to separate the key/value pairs in hash table.
$hash = @{Number = 1; Shape = "Square"; Color = "Blue"}

# Additional commands in the statement list on one line.
while ($val -ne 3) {$val++; Write-Host $val}

# Sub-expression using the semicolon (;) to separate statements.
for ($($i = 0; $ j = 0); $i -lt 10; $($i++; $j++))
{
    "`$i:$i"
    "`$j:$j"
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273225bd-bd1f-478f-6040-098bce77920c
* Version Independent ID: 5fcd4430-a6b8-0438-73c9-29749b804323
* Content: [about_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Semicolon is not an operator. It is a statement terminator. We do mention it in [about_Functions](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions) and [about_parsing](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_parsing).

**Comment by M0sc** [comment]
Yes, it is mentioned not only there, for example in [About For](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_for?view=powershell-7)->[Support for multiple operations](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_for?view=powershell-7#support-for-multiple-operations), [About For](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_for?view=powershell-7)->[Examples](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_for?view=powershell-7#examples) and in [About While](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_while?view=powershell-7). But there is no separate "About" section. Maybe worth adding paragraph in [Using Script Blocks](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_script_blocks?view=powershell-7#using-script-blocks)?
