### ISSUE TITLE
Debian 10 dependency error (libssl1.0.0 and libicu60)

### ISSUE THREAD

**Issue by jitdor** [MicrosoftDocs/PowerShell-Docs#5852]
I have followed the guide over at [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7) diligently up till installing the .deb package and apt update. After that, installing of powershell fails with the following dependency error:

```
# apt install powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libssl1.0.0 but it is not installable
              Depends: libicu60 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

It is a fresh install of Debian 10 minimal:

```
#lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by sdwheeler** [comment]
@TravisEz13 Can you comment on this?

**Comment by TravisEz13** [comment]
Can you please list the full repro step that you followed?

It looks like you followed instructions for another distribution.

**Comment by sdwheeler** [comment]
@jitdor I tested the install steps on Debian 10. It works for me. Make sure you are using the correct instructions for the version of Debian you are using.
