### ISSUE TITLE
PowerShell 6 view showing v7 installation commands

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/PowerShell-Docs#5855]
When viewing the supposed PowerShell 6 version of this page, it is still showing instructions for installing PowerShell 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is a known issue in our docs publishing system. At this time, the version selector only applies the the **Reference** content for the cmdlets and About_ topics.

**Comment by sdwheeler** [comment]
Closing this for now. The current publishing system does not allow for versioning of conceptual content in this docset.  We will address this as soon as the publishing system allows it. Hopefully by end of the year.
