### ISSUE TITLE
Kerberos Constrained Delegation support for second hop

### ISSUE THREAD

**Issue by DamianWiese** [MicrosoftDocs/PowerShell-Docs#5861]
The first paragraph under "Kerberos Constrained Delegation" has the following text:
"You can use legacy constrained delegation (not resource-based) to make the second hop. Configure Kerberos constrained delegation with the option "Use any authentication protocol" to allow protocol transition."

The first bullet point under cons for "Kerberos Constrained Delegation" states:
"Does not support the second hop for WinRM"

These statements appear to conflict each other, can you please update the document to either clarify the support, or so that both of these sections have the same information?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91ef023-c0c5-aa50-6f93-b7bbdbdaa2f9
* Version Independent ID: 8ad909bd-55bb-e3a6-2292-b94c298efe26
* Content: [Making the second hop in PowerShell Remoting - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ps-remoting-second-hop?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@PaulHigin Can you clarify these points?

**Comment by PaulHigin** [comment]
I am uncertain about this.  CredSSP allows second hop but is not recommended for security.  I believe constrained delegation does not support second hop but you will need to check with the WinRM folks.

**Comment by sdwheeler** [comment]
@DamianWiese  "Does not support the second hop for WinRM" is correct. That is a limitation of WinRM. See https://docs.microsoft.com/windows/win32/winrm/multi-hop-support
