### ISSUE TITLE
The documentation here is not platform independent

### ISSUE THREAD

**Issue by Zephilim** [MicrosoftDocs/PowerShell-Docs#5864]
"Installing a PowerShell Module" is something that needs to be done on all platforms, so it would be helpful if the documentation was platform independent too. Assuming the path separator character is semicolon for windows is not very useful. Instead I would like to see examples for universal functionality provide solutions that work on all platforms, so in this case using [System.IO.Path]::PathSeparator would be better than assuming it should be windows specific ';'. Similar applies to building path strings. Using Resolve-Path/Join-Path and [System.IO.Path]::DirectorySeparatorChar is better than literal paths with embedded back slashes. Since Powershell went multi-platform, it would have been good to see all documentation be updated to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b6d5a3-7072-d3fe-ed97-472df9b0e925
* Version Independent ID: 4ab75a2c-831e-37c5-d98d-873874d2ec47
* Content: [Installing a PowerShell Module - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/developer/module/installing-a-powershell-module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/module/installing-a-powershell-module.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
These SDK docs have not been updated since they were written for Windows PowerShell. Many of the concepts are the same but many of the details are different. We haven't had the time and resources to update this content. We know it needs to updated but we don't have a timeline for completing this update.

We do accept PRs with changes, if you would like to submit an update.
