### ISSUE TITLE
Redirect to about_Pwsh for 6, 7, 7.1

### ISSUE THREAD

**Issue by bmkaiser** [MicrosoftDocs/PowerShell-Docs#5866]
Is it possible to have this page redirect to the about_Pwsh article when switching to newer versions? Is it also possible to have about_Pwsh redirect to this page when switching the version to PowerShell 5.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776d0240-b9cb-fdb3-be53-eb72434040de
* Version Independent ID: 2a47dda6-5d42-249c-5d48-19ad6fbc7b3c
* Content: [about_PowerShell_exe - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/About/about_PowerShell_exe?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
It might me possible. I will investigate.
