### ISSUE TITLE
Document the attributes of our security features

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#5872]
# Documentation Issue

We should document the attributes of our security features:

- Defense in depth vs security boundary
- intent to service

here is how windows documents:
https://www.microsoft.com/en-us/msrc/windows-security-servicing-criteria

|feature| type | intent to service |
|-------|------| ------------------|
|execution policy| defense in depth | no |
|system lockdown - with applocker | defense in depth | no | 
|system lockdown - with WDAC | Security Feature | yes | 

cc @PaulHigin  for review

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [ ] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [x] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
@TravisEz13 where should this information go? Is there an existing document you think it should be added to or is this a new document?

**Comment by PaulHigin** [comment]
I don't see where security servicing is part of #5918.  Can someone point me to it?
