### ISSUE TITLE
This page is out of date.  -StartupType AutomaticDelayedStart does not exist anymore

### ISSUE THREAD

**Issue by derekables** [MicrosoftDocs/PowerShell-Docs#5876]
I'm not sure why it is even here, but I am trying to find how to set a service to Automatic Delayed Start and the answer here does not work.  

Get-Service -Name MSSQLSERVER | Set-Service -StartupType AutomaticDelayedStart

fails because of the StartupType. This needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01fbd51e-0953-0394-1b70-3d509058e483
* Version Independent ID: 6cffca1e-ef66-505b-d610-1a9f5867e116
* Content: [Set-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-service?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Set-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Set-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
AutomaticDelayedStart Works in PowerShell 6 and higher. It is not available in PowerShell 5.1. You were reading the PS7 documentation. If you switch to the PS5.1 docs, AutomaticDelayedStart it not listed.
