### ISSUE TITLE
Make Startjob usable with anny language script or program.

### ISSUE THREAD

**Issue by NicTanghe** [MicrosoftDocs/PowerShell-Docs#5878]
Make Startjob usable with anny language script or program.

for instance.
Start-Job -filePath .\Documents\dev\python\WeatherDesk\WeatherDesk.py
or
Start-Job -filePath nvim

**Comment by doctordns** [comment]
Why Not use Invoke-Command and just invoke it -AsJob?

**Comment by NicTanghe** [comment]
```
invoke-command -FilePath .\Documents\dev\python\WeatherDesk\WeatherDesk.py -asjob
Invoke-Command: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```
even if it whould work it is inelequent and illogical to require an extra step.
i can c if they did that for security reasons but then it shouldn't work in anny form.

**Comment by sdwheeler** [comment]
The `.py` file is not an executable. You have to run the Python executable and pass the script file as a parameter.

This is not a documentation issue.  Please file a feature request at https://github.com/PowerShell/PowerShell/issues/choose
