### ISSUE TITLE
Parameter Attributes do not require the "=$true" since PSv3

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#5885]
A note should be included that:
[Parameter(Mandatory)]
is a valid alternative to
[Parameter(Mandatory=$true)]

for later versions of Powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c38cef-73fb-7c5f-ecd3-66a344dff335
* Version Independent ID: 4eac80f8-61be-4d0f-d657-a007ba81cf53
* Content: [about_Functions_Advanced_Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by JustinGrote** [comment]
@DCtheGeek thanks for the fast turnaround!

**Comment by DCtheGeek** [comment]
Thank @sdwheeler! I just reviewed and merged it, he did the real work. :)
