### ISSUE TITLE
Include Alternate valid syntax for Parameter Attributes

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#5886]
See https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5885

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d809585-0a9c-52ec-ea1a-d670310ede69
* Version Independent ID: 2d556523-e140-96cc-68ea-8d9956165b3f
* Content: [Parameter Attribute Declaration - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/parameter-attribute-declaration?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/cmdlet/parameter-attribute-declaration.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/parameter-attribute-declaration.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This article is talking about C# syntax. So the shorthand syntax is not valid.
