### ISSUE TITLE
first object

### ISSUE THREAD

**Issue by PeNeu** [MicrosoftDocs/PowerShell-Docs#5892]
Hi, How to manage this? "Export-CSV organizes the file based on the properties of the first object that you submit." Let's say I run get-aduser -properties * and the msexch attributes will appear to users later. How do I get them there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20d9d627-128b-8421-d488-eedef3db50cf
* Version Independent ID: e9ed8d14-c120-3e61-68f5-cce542d30be3
* Content: [Export-Csv (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-csv?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Export-Csv.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
If properties are added after you export, you have to run `Get-ADUser` again and re-export to CSV.

**Comment by PeNeu** [comment]
> If properties are added after you export, you have to run `Get-ADUser` again and re-export to CSV.

No, it's not a solution. You have users in AD that are not mailbox enabled so they do not have msesch properties at all. I am looking for a solution how to read all properties of all selected objets and after this prepare properties for wanted export.

**Comment by sdwheeler** [comment]
I am still unclear about what you are trying to do. But `Export-CSV` can only create columns for the properties that exist on the object. If some of the objects returned by `Get-ADUser` have the properties you want then `Export-CSV` will create columns for those properties. For an object that does not have that property, the column will be empty for that object.

But, this is not the right forum for these kind of questions.  Try posting your problem in a community support forum. For a list of community forums see: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by PeNeu** [comment]
There is a NOTE in the description.

> When you submit multiple objects to Export-CSV, Export-CSV organizes the file based on the properties of the **first object that you submit.** If the remaining objects do not have one of the specified properties, the property value of that object is null, as represented by two consecutive commas. If the remaining objects have additional properties, those property values are not included in the file.

My question is, how to make an Export-CSV with all the properties, that shows later.

**Comment by chasewilson** [comment]
If I'm correct, you might have to do some scripting to make something like that. I would suggest a custom funtction to allow you to do what you need to do as I don't see an option within the cmdlet. 

You could create a pscustom object for each user and even if there is no value for a property you need, you could us a place holder. 
e.g 

```powershell
foreach ($number in 1..30)
{
    if ($number -in 1..15)
    {
        $export = [PSCustomObject]@{
            Testvalue = $number
            ValueTest = $number
            AdditionalValue = 'NA'
        }

        Export-Csv -InputObject $export -Path C:\test.csv -Force -Append
    }
    else
    {
        $export = [PSCustomObject]@{
            Testvalue = $number
            ValueTest = $number
            AdditionalValue = $number
        }

        Export-Csv -InputObject $export -Path C:\test.csv -Force -Append
    }
```
