### ISSUE TITLE
Set-Clipboard needs a delay

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#5896]
# Documentation Issue

It is an edge case on Windows. Set-Clipboard cmdlet can create new thread to do work (switching MTA to STA mode) and waits the thread finish but underlying API continue to process async. As result if user immediately run Get-Clipboard one does not get expected value. User should make short delay (~1 ms) to get right value.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-clipboard?view=powershell-7
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [x] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Windows

**Comment by sdwheeler** [comment]
@iSazonov Is there a related issue in the source repo?

**Comment by iSazonov** [comment]
Yes, https://github.com/PowerShell/PowerShell/issues/12066
