### ISSUE TITLE
Use -is Operator to Check for Null

### ISSUE THREAD

**Issue by DrakeLambert** [MicrosoftDocs/PowerShell-Docs#5905]
In C# we can test if an object is null by doing `obj is null`. Testing this way has the benefit of skipping the underlying type's implementation of Equals().

Does PowerShell support using the -is operator to test for null?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bbd3e14-403a-a077-d95b-cca8efd2004a
* Version Independent ID: 3ffcae97-8929-ba86-2f7b-a525916f966a
* Content: [about_Type_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_type_operators?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
No, the `-is` operator cannot be used that way. There is a feature request and a code change waiting for approval to change that. See https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4890
