### ISSUE TITLE
Missing install instructions for Ubuntu 20.04

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#5906]
As issue title we are missing Ubuntu 20.04 install instructions

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-gb/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#ubuntu-1804)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@TravisEz13 Do we support Ubuntu 20.04?

**Comment by TravisEz13** [comment]
No one has filed a [distribution support request](https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Distribution-Request&template=Distribution_Request.md&title=Distribution+Support+Request).  That would be the first step @kilasuit

**Comment by kilasuit** [comment]
@sdwheeler not as of yet - though I'd be happy to update the docs to mention that 20.04 is not yet supported so that others (like me) can see that it's possibly coming

**Comment by sdwheeler** [comment]
@kilasuit Thanks for the PR.
