### ISSUE TITLE
Date of original file

### ISSUE THREAD

**Issue by jmg69** [MicrosoftDocs/PowerShell-Docs#5911]
Hi.
When we create a symlink, is it possible that the lastwrite is the same as the original file? If yes how to do?

Thank you for your answer.

Best regards

Jean-Marc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed41112-a613-80a9-223c-d207279898d1
* Version Independent ID: 609a9efd-598e-050b-c9b8-91402dcc8e87
* Content: [New-Item (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/New-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/New-Item.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
I don't believe so. The symbolic link is a separate object from the linked file and then FileSystem handles it under the covers. 

Just FYI, this is a FileSystem question and the documentation here is complete, I'm closing this issue. 

Thanks for your feedback and feel free to open a new issue if you see any issues with the PowerShell documentation.
