### ISSUE TITLE
How do I display search bar on (PREVIEW) POWERSHELL COMMAND EXPLORER: 

### ISSUE THREAD

**Issue by aquakool** [MicrosoftDocs/PowerShell-Docs#5913]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92497070-504a-7239-dce7-ba7c23426514
* Version Independent ID: eb1fa4c2-2692-df5d-691a-78551edf6abb
* Content: [How to replicate the ISE experience in Visual Studio Code - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/how-to-replicate-the-ise-experience-in-vscode?view=powershell-7)
* Content Source: [reference/docs-conceptual/components/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by aquakool** [comment]
How do I display search bar on (PREVIEW) POWERSHELL COMMAND EXPLORER: in VS Code.

**Comment by chasewilson** [comment]
The PowerShell Command Explorer is still in preview and in development. You can "Search" by typing when you are focused on the command explorer panel but it is not fully fleshed out. 

I hope this helps.
