### ISSUE TITLE
I think Save-Module is not included on PowerShell 3.0 and 4.0

### ISSUE THREAD

**Issue by dariomws** [MicrosoftDocs/PowerShell-Docs#5915]
I tried to run these steps on Windows 2012 R2 with PowerShell 4.0 and the Save-Module cmdlet wasn´t recognized.

Also, I think the following issue/fix could be added to the document: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5725. I see more people with the same issue on Windows 8.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-5.1#feedback)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
These steps cannot be run from PowerShell 4.0. You must download PowerShellGet and PackageManagement using `Save-Module` on another machine. Then copy the saved module to your PowerShell 4.0 system.

For the TLS issue, we are working on a fix.
