### ISSUE TITLE
I think this works on all platforms with graphical windows -- the notes should reflect this

### ISSUE THREAD

**Issue by jsilverm** [MicrosoftDocs/PowerShell-Docs#5928]
I believe that someone worked hard to make this now work on all platforms with any GUI's.  So, not in remote sessions, not on Nano Server, but YES on Linux and MacOs for the first time.  I believe I heard someone rave about this in a video, but from the help it should be clear if it is one of the many things that was brought back only for Windows platforms, one of the fewer things that was brought back for Windows with GUI available, or is in the category I think -- if you have GUI you have this.  It is not clear at all which places this works on.  The same goes for the -ShowWindow parameter for help and Out-GridView cmdlet.  These three nifty commands are great to have, and the help should make it clear whether or not they are available.  It was understandable when we had to give them up for a while, but eventually most new users are going to be working with PowerShell 7+ and it would be a shame, especially for them, to have them available but think they don't.  A LOT of sources mentioned "these are gone in .Net Core, say goodbye" -- I don't have an installation to check the availability in 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b6b9a5-ab49-e371-f5a0-3bf3b66425b3
* Version Independent ID: 1b776a31-d524-82b0-c4c4-365ea66c1c72
* Content: [Show-Command (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/show-command?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Show-Command.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Show-Command.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Please see https://docs.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions.

This is the best information we have about version and platform availability. Eventually, we want to get this information into the individual cmdlet articles. But that is part of a larger project.
