### ISSUE TITLE
3.0 isn't very relevant anymore -- update the notes

### ISSUE THREAD

**Issue by jsilverm** [MicrosoftDocs/PowerShell-Docs#5929]
The 5.1 docs will be frozen in time forever, I guess, but the online help for versions 6, 7 and above really don't need all the stale references to 3.0 and 4.0.
For instance, 
"Beginning in PowerShell 3.0, the modules that come with the Windows operating system don't include help files. To download or update the help files for a module in PowerShell 3.0, use the Update-Help cmdlet."
There should be a sentence clearly stating which versions this applies to -- I believe ANY fresh install of PowerShell Core (now just called PowerShell) has no help files -- including ones downloaded and installed by the users, and not just on Windows?

"Beginning in PowerShell 3.0, if Get-Help doesn't find help in the fallback locale, it looks for help articles in English, en-US, before it returns an error message or displaying autogenerated help."
I believe that for modern versions of the docs, we can just delete the words "Beginning in PowerShell 3.0" to best effect.

I think this prominent note can just be deleted at this time, if it can't, I'd remove the references to the old versions which is confusing to those who will never run 3.0 or 4.0:
" Note

In PowerShell 3.0 and PowerShell 4.0, Get-Help can't find About articles in modules unless the module is imported into the current session. This is a known issue. To get About articles in a module, import the module, either by using the Import-Module cmdlet or by running a cmdlet that's included in the module."
As it is, it is very unclear whether this holds in 5.1, 6.* and 7.*

Same here:
"Only the conceptual articles that have help files installed on your computer are displayed. For information about downloading and installing help files in PowerShell 3.0, see Update-Help."
I think we can just delete "in PowerShell 3.0" to be less confusing.

Lastly, "PowerShell 3.0 doesn't include help files. To download and install the help files that Get-Help reads, use the Update-Help cmdlet"
I think there too, just deleting the 3.0 will be the most useful.

These seem like teeny little OCD things, but we all know that new users will be the far biggest readers of this help-on-help, and even I who have been using PowerShell on and off for years am not quite sure where these apply -- it would be nice to fix these to ensure happy noob experiences for the new PowerShell users of tomorrow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29396400-85e0-7466-7d17-89e82cde1852
* Version Independent ID: 4ac1ae97-081c-4b9b-d218-97f0519ee6fc
* Content: [Get-Help (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-help?view=powershell-7&WT.mc_id=ps-gethelp)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/Get-Help.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Get-Help.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@jsilverm The cmdlet reference for PowerShell 3.0, 4.0, and 5.0 has been moved to https://docs.microsoft.com/en-us/previous-versions/powershell/scripting/overview. That was the first step to get clean up old version information in the docs. 

We need to go through all of the docs and decide what can or should be removed. This is no small task. However, we have also had feedback from other users that ask to know when a feature was added.

Also worth noting is that Microsoft still has to support those older versions of PowerShell. So some documentation has to be maintained until those version fall out of support.

**Comment by jsilverm** [comment]
Thanks.  I was presuming that even 5.1 was now a dead-horse, and was only suggesting it for PowerShell 7 version (or possibly 6.2)....I've been using Visual Studio since forever, and am very careful not to assume Version X of documentation applies to Version Y without checking it by choosing the drop-down...Thanks again.
