### ISSUE TITLE
On which PowerShell platforms is this available?

### ISSUE THREAD

**Issue by jsilverm** [MicrosoftDocs/PowerShell-Docs#5930]
My favorite (not very) old PowerShell book describes this feature as "Windows-Only".  I came to the help to see if it is still true and it is a little dicey from what I see.  Many of us are still saying "Dot Net Framework" to mean the Windows-Only .Net Framework, but increasingly the language has been changing of late to just calling .Net 5+ "Dot Net" and not distinguishing the no-longer existent difference between "Full Framework" and "Core" in that context.
What all this means is that the language of "Microsoft .NET Framework" and ".NET Framework" dog-whistles to me that this is possibly Windows-only.  If it is, a clear note near the top and in the brief help should clarify that.  If not, we should consider changing the wording to be more consistent with the other ConvertTo-* functionality, where they just talk about converting objects without the D.N.F. qualifiers.  I'm not suggesting which the correct change is because it is still not clear to me whether this works on Mac and Linux as well right now.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51278317-ac19-fdb2-0a88-ba8d6ac9b9f6
* Version Independent ID: a2575b0d-d0ff-30fb-bf4d-3d79eec57f15
* Content: [ConvertTo-Html (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-html?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Html.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Html.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Please see https://docs.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions.

This is the best information we have about version and platform availability. Eventually, we want to get this information into the individual cmdlet articles. But that is part of a larger project.
