### ISSUE TITLE
This works on all flavors of PowerShell, right?

### ISSUE THREAD

**Issue by jsilverm** [MicrosoftDocs/PowerShell-Docs#5932]
There is wording in both ConvertTo-HTML and here (more in ConvertTo-HTML) that dog-whistles to me that this might not work on platforms other than Windows.
"The ConvertTo-Xml cmdlet creates an XML-based representation of one or more Microsoft .NET Framework objects. "
The Json and CSV ConvertTo- command help does not refer to "Dot Net Framework" as a qualifier of objects.  Because I saw other places suggesting that ConvertTo-HTML was Windows-only at the time of writing, in a famous and popular book, I expected the help for the cmdlet to clarify my confusion, it was not explicit.

Is there a meaningful reason to specify "Microsoft .Net Framework" objects in PowerShell 7's help for this cmdlet?  I would make it clear and explicit if this only works on Windows, if it works everywhere, having that qualifier here but not on the CSV and JSON flavors simply introduces confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66c2d0e2-a89e-887d-6010-6f95d656ef58
* Version Independent ID: df52e589-e043-a0f2-f48d-3f9c2e331030
* Content: [ConvertTo-Xml (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-xml?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@jsilverm PowerShell 6 and above use .NET Core. So if a cmdlet is documented for PowerShell 6 and above it must be using .NET Core and not .NET Framework. I understand that references to .NET Framework could be confusing to some and we are trying to clean these up as we go. However, that has nothing to do with whether or not a cmdlet is Windows-only. Please refer to https://docs.microsoft.com/powershell/scripting/whats-new/cmdlet-versions.
