### ISSUE TITLE
Rendering issues in windows 10 console for -include and -exclude in -full help

### ISSUE THREAD

**Issue by jsilverm** [MicrosoftDocs/PowerShell-Docs#5935]
The explanations associated with the -include and -exclude parameters for this get-childitem cmdlet look just great on this page and are super-helpful.

On my freshly installed PowerShell 7(LTS) in console, they don't seem to be rendering properly, *'s are disappearing.  I don't know if it is some markdown artifact or what.  I tried a couple of fonts.  "-ShowWindow" didn't contain all the text seen wrongly in -full in Console and seen correctly on this page.

Was this just fixed so recently that "Update-Help" doesn't see the changes yet in PowerShell 7 or is there a formatting issue somewhere causing a difference in the rendering in console and here on the webpage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f472bbb8-79d6-dea4-703b-0a86ec536585
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7&WT.mc_id=ps-gethelp)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
First, you should run `Update-Help -Force` to ensure that PowerShell actually downloads the latest help. That could be part of the problem.

However, I do see the rendering problem you are describing. The console-based help and the webpages are built from the same Markdown source. It looks like the tool that converts the Markdown to MAML (console help) is not converting properly. I will take a look at the problem.

**Comment by sdwheeler** [comment]
There is a bug in the markdown parser in PlatyPS. We are working on an update to PlatyPS. The markdown parsing engine will be replaced with markdig. Markdig is the library used by the Markdown cmdlets in **Microsoft.PowerShell.Utility** and OPS, which builds the docs site.

No ETA yet on the fix.

**Comment by jsilverm** [comment]
Thanks for not closing this.  Is there an ETA on this fix?  I seemed to still see it in Version          : 7.1.3

**Comment by sdwheeler** [comment]
Closing this since it is already ported to PlatyPS issue.
