### ISSUE TITLE
Add Create & Remove as LifeCycle Verbs

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/PowerShell-Docs#5938]
```Create``` should also be included as a lifecycle verb.  ```Build``` is more appropriate for binary artefacts (e.g., *build* from source code), while ```Create``` is better suited for document artefacts (e.g., *create* a report). 

```Create``` is logically paired with ```Remove``` which would be used to remove an artefact.

I'm sure this has previously been debated, but how *Create* keeps getting passed over for a verb is a mystery.  It was once stated in the Microsoft PowerShell blog that the considerations when deciding whether to add a new verb include:

- Little or no overlap with existing approved verbs (debatable depending on context)
- Broadly applicable to multiple technologies - must be domain agnostic
- Used consistently with similar meaning across multiple contexts
- Pairing with an opposite is good, but not required

The existing ```New```, ```Build```, and ```Add``` are not nearly as definitive as ```Create```.  I "create" a report is MUCH better than I "Add/Build/New" a report. Its about time that *Create* gets added to the repertoire.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edfbab86-9144-1866-2765-938a5cc68ed7
* Version Independent ID: b4035200-8b55-c70c-7a29-4de085c87e1c
* Content: [Approved Verbs for PowerShell Commands - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is a product feature request.  Please file a feature request at https://github.com/PowerShell/PowerShell/issues/choose.
