### ISSUE TITLE
Module manifest elements state wrong PowerShell version

### ISSUE THREAD

**Issue by peetrike** [MicrosoftDocs/PowerShell-Docs#5942]
This document has a table with module manifest elements.  Some of them (like _PreRelease_ and _ExternalModuleDependencies_) state, that they have been added in Powershell 7.  I have been using them with PowerShell 5.1 (and _ExternalModuleDependencies_ even with Powershell 2, IIRC).

IIRC, some of these parameters depend on PowerShellGet module version (which can also be installed and loaded in PowerShell 3.0), not on PowerShell version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6248373c-599b-9a97-d5f4-de4df06054da
* Version Independent ID: 4ffb4231-1d59-294b-1f7c-d6116140b204
* Content: [How to Write a PowerShell Module Manifest - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-module-manifest?view=powershell-5.1#feedback)
* Content Source: [reference/docs-conceptual/developer/module/how-to-write-a-powershell-module-manifest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/module/how-to-write-a-powershell-module-manifest.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@chasewilson See https://github.com/PowerShell/PowerShellGetv2/blob/development/CHANGELOG.md. We need to sync up the docs with the changes in the Changelog.
