### ISSUE TITLE
Wrong information in Get-Credential Notes section

### ISSUE THREAD

**Issue by peetrike** [MicrosoftDocs/PowerShell-Docs#5943]
The document states, that authentication prompt appreas in dialog box.  That's not true for Powershell 7.

In addition there is description of **ConsolePrompting** registry entry, but no information of entry type.  As the value assigned is 'True' or 'False', and registry doesn't have boolean entries, it may be assumed that the type should be _String_.  It would also be worth of checking, if PowerShell 7 uses that entry at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a90db4-010c-c7cf-d561-fd03d9686ade
* Version Independent ID: c98699f2-814c-63b8-edf5-3293ea1aa99f
* Content: [Get-Credential (Microsoft.PowerShell.Security)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-credential?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md)
* Product: **powershell**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by chasewilson** [comment]
@peetrike , thanks for the feedback!
You are right on the dialog box. This changed in PowerShell 6 and we will update all docs from that version up to refelect that. as well as the removal of the registry values. 

As for the Registry value handling in PowerShell 5.1, when you input the Boolean in the parameter, under the covers, it converts, it to to a String Value and is set correctly.
