### ISSUE TITLE
Cross-platform PowerShell https://aka.ms/pscore6

### ISSUE THREAD

**Issue by EdSeymore** [MicrosoftDocs/PowerShell-Docs#5944]
Why am I getting a recommendation to try a new shell? I see no reason given why that is my responsibility. What are the advantages? Why is not not added to my copy of Windows 10 if it is a good idea? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
PowerShell 6 and above does not ship in Windows. It can be installed separately. And it can be installed side-by-side with Windows PowerShell 5.1 (which does ship in Windows).

Actually, you should install PowerShell 7. See https://devblogs.microsoft.com/powershell/announcing-powershell-7-0/
