### ISSUE TITLE
Are you really running the 2 commands concurrently?

### ISSUE THREAD

**Issue by yanxurui** [MicrosoftDocs/PowerShell-Docs#5970]
Isn't this sequential?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7f2a9ff-80e5-ac1b-e83e-2d7c90b571ba
* Version Independent ID: 1afd49df-2712-faf6-2887-15f37ec7262a
* Content: [RemoteRunspacePool01 Sample - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/remoterunspacepool01-sample?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/hosting/remoterunspacepool01-sample.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/hosting/remoterunspacepool01-sample.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The sample code creates two runspaces in a pool. Each command is run in a separate runspace, allowing them to run concurrently.
