### ISSUE TITLE
-credentials != -Verb Runas

### ISSUE THREAD

**Issue by MHilpert** [MicrosoftDocs/PowerShell-Docs#5971]
Hi, I am trying to start powershell with following command (from a script wich has no priviledge rights, but the Admin Account is stored in de $cred variable): 

start-process 'powershell.exe' -ArgumentList "-noexit -command $scriptblock" -Credential $Script:cred -WorkingDirectory "C:\Windows"

In the new powershell window I see the correct user when I type $env:username, but I dont have the permission of that account.

if I do the same with the command 

start-process 'powershell.exe' -ArgumentList "-noexit -command $scriptblock" -Verb RunAs

and then I type in the same credentials, I have the correct permission of my admin account.

Can someone help?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4b8de4-3ea1-4210-4562-b084b0a51c0d
* Version Independent ID: ab184c39-041b-588c-acde-f715f6d3aee2
* Content: [Start-Process (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7#feedback)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Start-Process.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Start-Process.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
This is expected behavior. What do you need help with?

Try posting your problem in a community support forum. 
For a list of community forums see: https://docs.microsoft.com/powershell/scripting/community/community-support
