### ISSUE TITLE
None of these commands seem to work without TLS1.2

### ISSUE THREAD

**Issue by bilinear** [MicrosoftDocs/PowerShell-Docs#5978]
Had to use the following on systems out of box in order to get them to connect to the PSRepository. Recommend either allowing other protocols to connect to the repository either through command switch or allowing others to connect:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
Otherwise I would always get, no matter what package used:
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2/'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'PowerShellGet'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
About a month ago we released PowerShellGet 2.2.4 which allows machines on lower versions of TLS to still interact with the Gallery.

So update PowerShellGet or use `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`.
