### ISSUE TITLE
Add Restart-Computer for Un*x and macOS

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#5979]
# Documentation Issue
See PowerShell/PowerShell#11319 - added in 7.1.0-preview.1

## Context of the issue

- URL to the article (Docs or GitHub URL): https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Restart-Computer.md
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
  - [ ] Community articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): new to non-Windows

**Comment by chasewilson** [comment]
In addition to this, `Stop-Computer` has been implemented for Unix as well. See [PowerShell PR](https://github.com/PowerShell/PowerShell/pull/11151)

I'll be wrapping both of these additions into a single PR
