### ISSUE TITLE
`trap` is missing as a statement to which `break` applies; `trap`-related example is flawed

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#5992]
* `trap` supports `break` as well and should be mentioned at the top: adding `break` effectively turns the error into a runspace-terminating one.

* Therefore, the following example isn't correct:

> You break out of the other looping statements in the same way you break out of the Foreach loop. In the following example, the Break statement exits a While statement when a DivideByZeroException exception is trapped using the Trap statement.
```powershell
$i = 3
while ($true) {
  trap [DivideByZeroException] {
    Write-Host 'divide by zero trapped'
    break
  }
   1 / $i--
}
```

The `break`, due to being inside the `trap` script block, exits the entire runspace - it is unrelated to the enclosing `while` loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 276062b7-b784-adb4-f78c-67cbe4e8f655
* Version Independent ID: e5c77926-c030-4723-9273-5415f1d9e723
* Content: [about_Break - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Break?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Break.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Break.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You are correct. This is probably a better example:

```powershell
function test {
  trap [DivideByZeroException] {
    Write-Host 'divide by zero trapped'
    break
  }

  $i = 3
  'Before loop'
  while ($true) {
     "1 / $i = " + (1 / $i--)
  }
  'After loop'
}
```

**Comment by mklement0** [comment]
Indeed; note that the `'After loop'` is never reached; perhaps we should remove the entire example to avoid confusion and only mention that `break` applies to `trap` as well at the top, along with a link to `about_Trap`.
