### ISSUE TITLE
Nothing at all about SSH?

### ISSUE THREAD

**Issue by jsilverm** [MicrosoftDocs/PowerShell-Docs#5993]
There is zero in this about mentioning SSH, not even a link to another page?  There should probably be something here.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9e0042-6fd8-150a-daf7-50bb7e84a51e
* Version Independent ID: f10fe1de-6a2c-a893-a45a-6803417939b8
* Content: [about_Remote_FAQ - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_faq?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@jsilverm You are right. This needs an update. It is very old content. Do you have a list of questions you would like to see added?

**Comment by jhoffmann271** [comment]
You could add [PowerShell remoting over SSH](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core) to the 'See also' links at the bottom or maybe incorporate concepts from the page directly into [about_Remote_FAQ](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_faq) docs.
