### ISSUE TITLE
Clarify the clear text nature of credentials for Export-Clixml on non-Windows

### ISSUE THREAD

**Issue by matt199x** [MicrosoftDocs/PowerShell-Docs#5997]
# Documentation Issue

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-clixml?view=powershell-7

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): macOS

## Detailed description of the issue

The documentation says - "Export-Clixml only exports encrypted credentials on Windows. On non-Windows operating systems such as macOS and Linux, credentials are exported in plain text."

When I run the following commands on macOS it is not plain text.
$Creds = Get-Credential 
$Creds | Export-Clixml -Path ~/creds.xml

It is a string of numbers in the password section of the xml file. The string is a lot smaller than the string that is created on Windows but it definitely isn't in plain text.

**Comment by sdwheeler** [comment]
@matt199x That sounds like a bug in the product. 
Please file an issue in the Product repositiory at: https://github.com/PowerShell/PowerShell/issues/choose

cc: @SteveL-MSFT - if this not a bug then tell me how to update the docs.

**Comment by matt199x** [comment]
How is it a bug if it is doing what it is supposed to do? I am encrypting and decrypting fine on macos with these commands. I was instructed by someone else to encrypt and decrypt on macos like this.

**Comment by sdwheeler** [comment]
I just got clarification from the dev team. 

>This is by design because there is no DPAPI support on non-Windows machine for .NET SecureString to use.  It is still considered better than nothing since it is kept as a char array rather than a string type, and so the plain text is not apparent.  We will need to update the docs to carefully make this clear.

I will add a working example and update the docs.

**Comment by sdwheeler** [comment]
```powershell
PS> $cred = Get-Credential

PowerShell credential request
Enter your credentials.
User: sean
Password for user sean: ********

PS> $cred | Export-Clixml ./cred2.xml
PS> gc ./cred2.xml
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Management.Automation.PSCredential</T>
      <T>System.Object</T>
    </TN>
    <ToString>System.Management.Automation.PSCredential</ToString>
    <Props>
      <S N="UserName">sean</S>
      <SS N="Password">700061007300730077006f0072006400</SS>
    </Props>
  </Obj>
</Objs>
```

Note that the password is stored in the XML file as a Unicode character array as proven by `Format-Hex`.

```powershell
PS> 'password' | Format-Hex -Encoding unicode

   Label: String (System.String) <52D60C91>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 70 00 61 00 73 00 73 00 77 00 6F 00 72 00 64 00 p a s s w o r d
```

So the information is "plain text", meaning not encrypted.

**Comment by sdwheeler** [comment]
> How is it a bug if it is doing what it is supposed to do? I am encrypting and decrypting fine on macos with these commands. 

Actually you are not encrypting/decrypting. You are deserializing to CLIXML and reserializing back  to **PSCredential**, then extracting the **SecureString** member using `-AsPlainText`, which all works as expected.
