### ISSUE TITLE
SWITCH -REGEX matches a substring

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/PowerShell-Docs#6001]
# Documentation Issue

It is undocumented that patterns in SWITCH -REGEX match a substring. 
## Context of the issue

- URL to the article (Docs or GitHub URL): [Syntax](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Switch.md#syntax)
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [X] Version 7.x preview content
  - [X] Version 7.0 content
  - [X] Version 6 content
  - [X] Version 5.1 content

  **Conceptual articles**
  - [X] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
  - [ ] Community articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

> Regex - Performs regular expression matching of the value to the condition.

⚠ As I see it, _matching_ means that the value _matches_, not that the value _contains a match_.
````powershell
$target = 'https://bing.com'
switch -Regex ($target)
{
    'ftp\://.*' { "$_ is an ftp address"; Break }
    '\w+@\w+\.com|edu|org' { "$_ is an email address"; Break }
    '(http[s]?)\://.*' { "$_ is a web address that uses $($matches[1])"; Break }
}
````
Here the authors actually confused themselves.  Try this with target 'xhttps://bing.com'.

**Comment by sdwheeler** [comment]
Regex always matches a substring unless you specifically construct the closed regex pattern. Maybe a better pattern for the example would be `^(http[s]?)\://.*$`. 

![image](https://user-images.githubusercontent.com/19415881/82669177-d1594900-9bef-11ea-8fa4-944a848e2d8a.png)
