### ISSUE TITLE
suggesting improvement

### ISSUE THREAD

**Issue by kingdavid72** [MicrosoftDocs/PowerShell-Docs#6009]
[Enter feedback here]
This is a minor thing but ..
unlike bash shells on Linux or MAC OS
PowerShell has not refreshed itself after installing something..
For example.
On VS code terminal or Powershell
install NodeJS and npm package
if I type node -v or pm -v, error pops up
have to save all the opening and reopen Powershell or VS code
then it works.

that simple thing kills uptrends a lot... I have to close down so many windows
Any suggestion?
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
That sounds like a PATH issue and a difference in how the package installers work on Windows vs. macOS/Linux.

When you install a new package on Windows, most applications are not installed into a location that is already in your PATH environment variable. The installer adds the application to the system or user PATH variable but the new value is not available in the current session. It is available to any new session. You can avoid restarting your session by manually adding the new app location to your PATH in the current session.
