### ISSUE TITLE
Apt-get upgrade instructions need tweaking

### ISSUE THREAD

**Issue by rkeithhill** [MicrosoftDocs/PowerShell-Docs#6014]
`apt-get upgrade powershell` is not what you want.  That will upgrade **all** packages.  The instructions should be changed to `apt-get install powershell` since that will upgrade an already existing install.  Source: https://askubuntu.com/questions/44122/how-to-upgrade-a-single-package-using-apt-get

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#ubuntu-1804)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@TravisEz13 Do you agree with this suggested change?

**Comment by chasewilson** [comment]
This does match up with current documentation for the `apt-get` tool. 
Upgrade upgrades all packages defined in the distros package index files. 

Using `apt-get install` will only upgrade the specified package or install it if it doesn't exist. In addition to this, you won't have to precede this command with the `apt-get update` command.

**Comment by TravisEz13** [comment]
Agree with the original proposed change

**Comment by rkeithhill** [comment]
@sdwheeler The `sudo` is needed.  So leave that.
