### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by endofdata** [MicrosoftDocs/PowerShell-Docs#6015]
The following link to legacy powershell setup page is broken:
  
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by jhoffmann271** [comment]
I have created a pull request to resolve this issue:
https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6012
