### ISSUE TITLE
Thanks to authors

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/PowerShell-Docs#6022]
Just now I entered those commands on windows 10 2004_19041.264, all commands are worked, outputs come out as explained in the article.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b770965-4cc8-203e-5332-26bb9ee99220
* Version Independent ID: 1ac2554b-bf6a-2da6-3708-2d63af435e1e
* Content: [What is PowerShell? - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7)
* Content Source: [reference/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/overview.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Thanks for the feedback.
