### ISSUE TITLE
Expand-Archive: DestinationPath or OutputPath?

### ISSUE THREAD

**Issue by tommymaynard** [MicrosoftDocs/PowerShell-Docs#6030]
This page includes several references to a `DestinationPath` parameter, when it likely meant to reference the `OutputPath` parameter. I believe the `7.0.0` version may include the wrong parameter, as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35bc01da-ad2f-cf48-c7e6-ab496ccdba94
* Version Independent ID: 0a5e7f63-6363-af13-a2ca-79190f459d40
* Content: [Expand-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Archive/Expand-Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Archive/Expand-Archive.md)
* Product: **powershell**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

**Comment by tommymaynard** [comment]
Sorry, my mistake. I wasn't viewing the proper cmdlet/function; I didn't notice soon enough that I was viewing the Pscx's `Expand-Archive`.

**Comment by sdwheeler** [comment]
@tommymaynard Cheers! 👍
