### ISSUE TITLE
PowerShell is still sometimes called "Monad" or "MSH"

### ISSUE THREAD

**Issue by alexbuzzbee** [MicrosoftDocs/PowerShell-Docs#6043]
# Documentation Issue

SDK docs (possibly others) sometimes call PowerShell "Monad" or "MSH," its old names.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet et al.
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [X] Version 7.x preview content
  - [X] Version 7.0 content
  - [X] Version 6 content
  - [X] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [X] SDK articles
  - [ ] Community articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

In some places, the PowerShell SDK documentation, and possibly other documentation, though I haven't checked thoroughly, still refers to "Monad" or "MSH," PowerShell's previous names during its original development. This has the potential to confuse programmers who are not aware of PowerShell's history.

As particular examples, this can be seen in [Cmdlet](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet)'s and [RuntimeException](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runtimeexception)'s SDK documentation, but it also occurs in many other documents.

Much or all of this documentation is in the form of `///` doc-comments in the PowerShell codebase itself, so it may make more sense to move this issue to [PowerShell/PowerShell](/PowerShell/PowerShell). However, I opened this issue on [MicrosoftDocs/PowerShell-Docs](/MicrosoftDocs/PowerShell-Docs) as it is a documentation problem, not a bug in PowerShell.

**Comment by sdwheeler** [comment]
@alexbuzzbee You are correct. This documentation comes from the `///` comments in the source code and that is where is must be fixed. So this is a "code" bug and not a docs bug. It cannot be fixed in the documentation repository. Also note, that some of the internal code structures still use "monad" and "msh" terms, so some of the documentation may not be incorrect.

Please file a product issue at https://github.com/PowerShell/PowerShell/issues/choose

Thanks

**Comment by doctordns** [comment]
In the past, where documentation has been generated programmatically (and was later found to be incorrect) we just make the documentation correct. Since we have the ability to make the documentation more accurate, why not do so?

**Comment by sdwheeler** [comment]
@doctordns Because, if the change isn't made in the source code then the docs get overwritten in the next release. So the fix needs to be made in the source.

**Comment by doctordns** [comment]
Is that documentation ONLY updateable by updating the code? I know I have seen other documentation pages that were generated from code, were wrong and were fixed and those errors did not return.
