### ISSUE TITLE
SSH Options: Add documentation for the Options parameter in PowerShell remoting over SSH

### ISSUE THREAD

**Issue by BrannenGH** [MicrosoftDocs/PowerShell-Docs#6046]
# Documentation Issue

The `Options` parameter for the PowerShell remoting over SSH will need to be documented.
Please see:
* Issue: https://github.com/PowerShell/PowerShell/issues/12762
* Pull Request: https://github.com/PowerShell/PowerShell/pull/12802

## Context of the issue

- URL to the article (Docs or GitHub URL): https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md

Add an `-Options` parameter to pass SSH options:

- Options parameter added to Invoke-Command
- Options parameter added to New-PSSession
- Options parameter added to Enter-PSSession
- Options parameter added to SSHConnection Hashtable

- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [X] Version 7.x preview content
  - [ ] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
  - [ ] Community articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

The above issue/pull request allows passing [OpenSSH options](https://man.openbsd.org/ssh#o) to the `Invoke-Command`, `Start-PSSession`, and `Enter-PSSession` cmdlets. These options should be documented in the docs as well.

**Comment by sdwheeler** [comment]
This issue is over a year old. We can reopen this issue if the PR ever gets merged.

**Comment by floh96** [comment]
@sdwheeler fyi the pr was merged

**Comment by sdwheeler** [comment]
@BrannenGH What happens when the user specifies `-Port 2143 -Options @{Port=22}`? Which value gets used? The code change should really check for duplicate values passed via parameter. 

My preference would be for explicit parameters to override the **Options** hashtable. That matches the current splatting behavior.

cc: @SteveL-MSFT, @PaulHigin

**Comment by SteveL-MSFT** [comment]
@sdwheeler looking at the PR, this is simply passing the values to `ssh -o name=value`, so maybe we can borrow some of the text from https://www.man7.org/linux/man-pages/man1/ssh.1.html

**Comment by SteveL-MSFT** [comment]
@PaulHigin other than `port`, I'm not sure what validation can be done since sshd_config could add more options in the future or remove some.  if `-port` takes precedence, perhaps we just document that

**Comment by PaulHigin** [comment]
@SteveL-MSFT  Good point.  I agree to documenting it.

**Comment by sdwheeler** [comment]
The `ssh` executable obtains configuration data from the following sources in the following order:

1. command-line options
1. user's configuration file (~/.ssh/config)
1. system-wide configuration file (/etc/ssh/ssh_config)

The following cmdlet parameters get mapped into `ssh` parameters and options:

|      Cmdlet parameter      |          ssh parameter          |            -o option            |
| -------------------------- | ------------------------------- | ------------------------------- |
| `-KeyFilePath`             | `-i <KeyFilePath>`              | `-o IdentityFile=<KeyFilePath>` |
| `-UserName`                | `-l <UserName>`                 | `-o User=<UserName>`            |
| `-Port`                    | `-p <Port>`                     | `-o Port=<Port>`                |
| `-ComputerName -Subsystem` | `-s <ComputerName> <Subsystem>` | `-o Host=<ComputerName>`        |

For more information about `ssh_config` files, see
[ssh_config(5)](https://man.openbsd.org/ssh_config.5).

**Comment by sdwheeler** [comment]
Reopening now that code PR is merged.

**Comment by sdwheeler** [comment]
Fixed in #8515
