### ISSUE TITLE
Add mention of gotchas when converting a Hashtable to JSON: depth and script blocks.

### ISSUE THREAD

**Issue by konrad-jamrozik** [MicrosoftDocs/PowerShell-Docs#6055]
Consider:

**Gotcha 1: the default conversion depth is 2.**

`@{ a = @{ b = @{ c = @{ d = "e" }}}}  | ConvertTo-Json`

Results in

```
{
  "a": {
    "b": {
      "c": "System.Collections.Hashtable"
    }
  }
}
```

Fix: `@{ a = @{ b = @{ c = @{ d = "e" }}}}  | ConvertTo-Json -Depth 3`

**Gotcha 2: Script blocks don't play well with conversion**

`@{ a = { Write-Host "aha" } } | ConvertTo-Json`

Results in:

```
{
  "a": {
    "Attributes": [],
    "File": null,
    "IsFilter": false,
    "IsConfiguration": false,
    "Module": null,
    "StartPosition": {
      "Content": "{ Write-Host \"aha\" }",
      "Type": 19,
      "Start": 7,
      "Length": 20,
      "StartLine": 1,
      "StartColumn": 8,
      "EndLine": 1,
      "EndColumn": 28
    },
    "DebuggerHidden": false,
    "Id": "e7a1c2bb-938b-4fb0-ab3d-d51c29da8aa3",
    "Ast": {
      "Attributes": "",
      "UsingStatements": "",
      "ParamBlock": null,
      "BeginBlock": null,
      "ProcessBlock": null,
      "EndBlock": "Write-Host \"aha\"",
      "DynamicParamBlock": null,
      "ScriptRequirements": null,
      "Extent": "{ Write-Host \"aha\" }",
      "Parent": "{ Write-Host \"aha\" }"
    }
  }
}
```

Fix: I don't know an easy fix.

**As of:**

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51a14cf-e9db-6463-141c-2e6498e4e527
* Version Independent ID: a23755f9-7ded-991a-9675-57d3beb268ec
* Content: [Everything you wanted to know about hashtables - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7#converting-json-to-hashtable)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@konrad-jamrozik I don't know why you would do that with a script block, but the workaround is to dot source it.

```
@{ a = (. { Get-ChildItem }) } | ConvertTo-Json
```

**Comment by konrad-jamrozik** [comment]
@sdwheeler thank you for the workaround! To answer your question about my use case for script blocks in a hashtable: consider a knowledge graph with some of the leaf nodes representing operations, like `$knowledgeGraph.car.engine.inspect`. I represent such graph as a deeply-nested hashtable, and use script blocks for the operations, like `inspect` here.
