### ISSUE TITLE
it tells us a lot of things but how to install a module

### ISSUE THREAD

**Issue by nicknameyu** [MicrosoftDocs/PowerShell-Docs#6062]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b6d5a3-7072-d3fe-ed97-472df9b0e925
* Version Independent ID: 4ab75a2c-831e-37c5-d98d-873874d2ec47
* Content: [Installing a PowerShell Module - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/module/installing-a-powershell-module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/module/installing-a-powershell-module.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The answer is in the first paragraph of the article:

> Generally speaking, this consists of copying the module files (ie, the .psm1, or the binary assembly, the module manifest, and any other associated files) onto a directory on that computer.

I am not sure what you think is missing. Do you have a specific question?
