### ISSUE TITLE
Update Documentation for Broken Tags

### ISSUE THREAD

**Issue by helen3141** [MicrosoftDocs/PowerShell-Docs#6063]
updating tags this way doesn't work. Please post the workaround
https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/192

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf727e1-5ccb-2844-fd6b-d0a00568c3ee
* Version Independent ID: 28f7f22d-c3a6-ea62-c77b-672d7e16fc80
* Content: [ConvertFrom-Json (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@helen3141 This article does not have any examples using the VSTS REST API. Unless I am mistaken, I think you commented on the wrong article. Am I missing something?

**Comment by helen3141** [comment]
If you try updating the “tags” it will return a response but won’t update. Other keys will update though.

There is no indication it was broken/no documentation so I struggled with this for some hours. The item I linked is a workaround that worked for me, personally. I thought it’d be good to indicate this to other people to save them time/frustration.

**Comment by dichternebel** [comment]
@sdwheeler Why is this closed? It never worked properly and it should be fixed!
The workaround is not working anymore btw...

**Comment by sdwheeler** [comment]
@dichternebel This issue was closed because it is not a PowerShell or PowerShell documentation issue.

**Comment by dichternebel** [comment]
Thanks for the fast response... so where do we report Azure DevOps API bugs then? Can't seem to find the right channel.
