### ISSUE TITLE
Web crawling broken

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#6080]
Non-Bing search engines have dropped docs.microsoft.com for common queries like "get childitem" 

DuckDuckGo
https://i.imgur.com/wNn2PVg.png

Startpage
https://i.imgur.com/fhiwvA5.png

Google
https://i.imgur.com/XvRo401.png

Bing
https://i.imgur.com/jDrUk6P.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b770965-4cc8-203e-5332-26bb9ee99220
* Version Independent ID: 1ac2554b-bf6a-2da6-3708-2d63af435e1e
* Content: [What is PowerShell? - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7)
* Content Source: [reference/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/overview.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Unfortunately, this is the way it as always been. I am working with our SEO specialist to figure out if there is a way to improve this.

**Comment by juvtib** [comment]
Not true. 

I do these searches regularly. And I believe something must have changed around the time I reported this issue. 

For example

get childitem now works on DuckDuckGo as I expect 
https://i.imgur.com/p5MkvYB.png

but other searches, which I recall, are not working
https://i.imgur.com/T1cHuH1.png

I will add that I reported the issue to DuckDuckGo and things like Get-ChildItem started working the same day while other search engines remained the same. 

I don't have any expectations. I'm only putting a stake in the ground and saying this is when it started. 

Regards,

**Comment by sdwheeler** [comment]
Thanks for the context. I am trying to improve things from my end too.

**Comment by juvtib** [comment]
I think the page titles might have changed. Now I see 
```XML
<title>Join-Path</title>
```
whereas I remember longer names like _Join-Path | Microsoft Docs_ or something. 
I noticed because I use a bookmarklet to create references. And I don't have to edit the result now.

**Comment by juvtib** [comment]
Here's an old note
```xml
<a href="https://docs.microsoft.com/en-us/azure/automation/automation-dsc-overview" target="_blank" rel="noopener">Azure Automation State Configuration overview | Microsoft Docs</a>
```

**Comment by juvtib** [comment]
Here is the title for the about registry provider doc right now
```xml
<title>Registry Provider - PowerShell | Microsoft Docs</title>
```
This might help to explain why DuckDuckGo was treating that differently after Get-ChildItem
```xml
<title>Get-ChildItem</title>
```
[started working](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6080#issuecomment-641506697).

**Comment by juvtib** [comment]
ex <a href="https://docs.microsoft.com/en-us/powershell/scripting/dsc/overview/authoringadvanced?view=powershell-7" target="_blank" rel="noopener">Understanding DSC's role in a CI/CD pipeline - PowerShell | Microsoft Docs</a>

**Comment by sdwheeler** [comment]
Google is now returning the correct results. I am closing this issue but keeping an eye on the results. I did notice that the page titles are missing the "PowerShell | Microsoft Docs" suffix for reference content. I am not sure when that changed. I have reported this issue to the build team. That could certainly affect SEO results.

**Comment by sdwheeler** [comment]
Could have been related to https://searchengineland.com/google-confirmed-indexing-issues-causing-some-stale-results-335496
