### ISSUE TITLE
Typo in help content for parameter LiteralPath

### ISSUE THREAD

**Issue by WillParry** [MicrosoftDocs/PowerShell-Docs#6081]
Help Content for parameter LiteralPath includes two sentences which contradict each other:

1. If the path includes escape characters, enclose it in single quotation marks.
2. Single quotation marks tell PowerShell not to interpret any characters as escape sequences.

Which one should be single quotations and which should be double quotation marks? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca3a20d2-c106-2ecf-aac6-16996ea19b73
* Version Independent ID: 1ef1a1f1-1bb5-727e-edce-c4c15aa5a3d4
* Content: [Test-Path (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Test-Path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Test-Path.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
It is probably better to say this: If the path included characters that could be interpreted by PowerShell as escape sequences, you must enclose the path in single quotes so that they are interpreted.
