### ISSUE TITLE
some servers this does not work without forcing TLS 1.2

### ISSUE THREAD

**Issue by lachlann562** [MicrosoftDocs/PowerShell-Docs#6083]
When attempting to run Install-Module Powershell get on some servers/workstations you get the error:
S C:\Windows\system32> update-module powershellget
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package provider 
requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider

Attempting to install nuget also fails:
PS C:\Windows\system32> Install-PackageProvider nuget
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
Install-PackageProvider : No match was found for the specified search criteria for the provider 'nuget'. The package provider requires 
'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At line:1 char:1
+ Install-PackageProvider nuget
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider

then it works:

PS C:\Windows\system32> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

PS C:\Windows\system32> Install-PackageProvider nuget

Name                           Version          Source           Summary                                                                           
----                           -------          ------           -------                                                                           
nuget                          2.8.5.208        https://onege... NuGet provider for the OneGet meta-package manager                                

PS C:\Windows\system32> Update-Module powershellget
Update-Module : Module 'powershellget' was not installed by using Install-Module, so it cannot be updated.
At line:1 char:1
+ Update-Module powershellget
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (powershellget:String) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : ModuleNotInstalledUsingInstallModuleCmdlet,Update-Module
 

PS C:\Windows\system32> install-Module powershellget -Force

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d14c05e-599a-e908-0bcc-e1a5d7ef961c
* Version Independent ID: 1ca59e2b-35f8-34c8-19ec-609bf8d11527
* Content: [Install-PackageProvider (PackageManagement)](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-packageprovider?view=powershell-7)
* Content Source: [reference/7.0/PackageManagement/Install-PackageProvider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PackageManagement/Install-PackageProvider.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
Please see our announcement at https://devblogs.microsoft.com/powershell/powershell-gallery-tls-support/

Also note that is was patched in the latest release https://www.powershellgallery.com/packages/PowerShellGet/2.2.4.1

**Comment by lachlann562** [comment]
While this does explain it, if you are starting with a new server this is still a problem (e.g. win 2012). its probably worth adding a comment to the documentation that it may be necessary to force TLS 1.2. using the commands i shared above.
