### ISSUE TITLE
Parameter Encoding missing "byte"?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/PowerShell-Docs#6085]
Hello, 

New-CsCallQueue and Set-CsCallQueue list the following example for WAV files:
`$File = Get-Content $MusicOnHoldAudioFileName -Encoding byte -ReadCount 0`

Get-Content does not reference "byte" as a valid parameter, however, the command works (at least with WAV files for me,... I think I am trying to import MP3s that are too big once decompressed.

Thanks,
David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da93ebc7-58c3-78e3-ab48-e0c145f22e95
* Version Independent ID: 6ccfc309-9783-aadd-717d-671dcbd454ed
* Content: [Get-Content (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-Content.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-Content.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @DEberhardt, thanks for the feedback. The **Encoding** parameter accepts the value "Byte" in PowerShell version 5.1 but not in 6.x and above. In those versions, you will use `-AsByteStream`. I'm going to assume you are using PowerShell 5.1 and are lookign at the 7.0 documentation. 

I hope this clears things up. I'm closing this for now but if there is more information, feel free to write back and I will take a look again. 

Have a great day!

**Comment by DEberhardt** [comment]
Ah! That explains something, thanks :)
I might need to factor that into my script then.

**Comment by chasewilson** [comment]
No Worries :) Glad it is all working. Thanks again for the feedback and feel free to open new issues if you see anything else :)
