### ISSUE TITLE
Learning How To Use commands 

### ISSUE THREAD

**Issue by smiley40806** [MicrosoftDocs/PowerShell-Docs#6088]
[Enter feedback here] Im appreciating how easy it is to find all the resources that are available. Not any real issues yet I
am using tutorials to learn from them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7810d618-3bd1-d1de-d09b-8c760a3da705
* Version Independent ID: 3f7679df-9f48-8aae-81dc-0980db7f0b17
* Content: [Managing Current Location - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/samples/managing-current-location?view=powershell-7)
* Content Source: [reference/docs-conceptual/samples/Managing-Current-Location.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Managing-Current-Location.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Thanks! You may also want to check out the new PowerShell 101 content at https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/00-introduction?view=powershell-7
