### ISSUE TITLE
PSRemoting message encryption

### ISSUE THREAD

**Issue by jborean93** [MicrosoftDocs/PowerShell-Docs#6089]
Under the section `Encryption and transport protocols` it states

> Regardless of the transport protocol used (HTTP or HTTPS), PowerShell Remoting always encrypts all communication after initial authentication with a per-session AES-256 symmetric key.

Then once again under `Ongoing Communication`

> Once initial authentication is complete, the PowerShell Remoting Protocol encrypts all ongoing communication with a per-session AES-256 symmetric key.

This does not seem to be true, I've never seen anything in the docs that seem to indicate MS-PSRP does any encryption through it's protocol except through the transport layer. This transport layer is done through other protocols like MS-WSMV (WSMan), SSH, named pipes, etc and the level of encryption it offers can vary, i.e.

* WSMan Basic auth offers no encryption
* WSMan NTLM auth only uses an RC4 cipher with at most a 128-bit key
* WSMan Kerberos is dependent on the etype in the TGS ticket but is most likely AES on modern systems
* WSMan CredSSP is based on the TLS cipher suite that was negotiated in the handshake
* SSH, not sure how the mechanism works but I'm sure it's quite robust due to the use of SSH in the nix world

As for the "per-session AES-256 symmetric key", I believe this may be referring to the session key as documented by [this event](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-psrp/53964536-b10e-4437-a8f3-c77dbaca2199). But this key seems to only be used when serializing SecureStrings and not as a blanket encryption done over every PSRP packet sent across the wire.

While I'm happy to be proven wrong, the fact the docs say the ongoing communication is encrypted using AES-256 does not seem to match with either what I've seen get sent across the wire or whatever is in the MS-PSRP documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bec5359-d295-32ba-6703-825e470a77fd
* Version Independent ID: e346c53e-7a10-93d9-5819-6f3c3eab5dff
* Content: [WinRMSecurity - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/winrmsecurity?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/remoting/WinRMSecurity.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/WinRMSecurity.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@jborean93 Thanks for pointing this out. You are correct about the session key used for SecureStrings. We are fixing the docs.

Bottom line is that WinRM does the encryption at the transport layer. PSRP only uses encryption for the SecureStrings.

**Comment by jborean93** [comment]
@sdwheeler I apologise but I don't think https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6113 really fixes the docs in a better way. It still states that encryption is always used but that isn't the case.

**Comment by sdwheeler** [comment]
Encryption is always used for data transport. That is separate from session setup and authentication.

**Comment by jborean93** [comment]
> Encryption is always used for data transport. That is separate from session setup and authentication.

That isn't true, if you are using Basic auth over HTTP there is no data encryption at all. While you do need to change a setting to allow that on the service side it is possible to do. When you use NTLM auth through WinRM then the encryption used is based on an RC4 with at most a 128 bit key which by [Microsoft's own admission](https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2013/2868725?redirectedfrom=MSDN) is a weak cipher with known weaknesses.

If I had a poorly set up Kerberos environment then I could also be using a DES or RC4 encryption and not AES for the encryption mechanism. My main point is that the docs seem to give a false sense of security that using PSRemoting is always going to be encrypted hence secure when in fact it may not be. In Microsoft's defence they do make it hard to shoot yourself in the foot by disabling Basic auth and plaintext messages by default, requiring a TrustedHosts entry for NTLM auth, and making sure Kerberos uses AES by default on newer systems but that is not always a given.

**Comment by sdwheeler** [comment]
You are talking about encryption of authentication, not encryption of the PSRP stream transported by WinRM.

**Comment by jborean93** [comment]
The message encryption of WinRM itself is based on the authentication message used https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wsmv/58421aa4-861a-4410-831a-c999f094cdb7. The WinRM layer encrypts the WSMan envelop to be sent using the [EncryptMessage](https://docs.microsoft.com/en-us/windows/win32/api/sspi/nf-sspi-encryptmessage) function which is highly dependent on the algorithm defined by the authentication package. This all happens post authentication because you can't encrypt messages through SSPI without an authentication context being set up.

I haven't seen anything in the wild or in the protocol docs that shows PSRP has another layer of encryption on top of what the transport provides.

**Comment by sdwheeler** [comment]
The transport is encrypted with a 256-bit session key after authentication. It is possible to turn off the encryption but you have to work at it. See this article about that: https://devblogs.microsoft.com/powershell/compromising-yourself-with-winrms-allowunencrypted-true/

**Comment by jborean93** [comment]
> The transport is encrypted with a 256-bit session key after authentication

This is the part I don't believe, I've never seen this mentioned in the MS-PSRP docs and a brief walkthrough in https://github.com/PowerShell/PowerShell doesn't show me anything that does this encryption. The only 256-bit session key that is ever mentioned is the one created for SecureString serialization but that is only 1 specific object type. Isn't that what we just determined in https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6089#issuecomment-642868435.

I happy to share a Wireshark capture and even step through some code that deals with this type of encryption that shows the encryption is done on the WSMan layer which is dependent on the authentication protocol that was used and not something in PSRP.

> It is possible to turn off the encryption but you have to work at it

Yes that is true but

* This is a WinRM setting so only ever relevant if you are using PSRP over WinRM, other transports have their own rules and settings
* If you are using NTLM authentication then while it is encrypted it's encrypted using a weak cipher (RC4) with only a 128 bit key. Nothing will ever change this as it's a limitation of the encryption offered by the NTLM protocol
* If you are using Kerberos authentication it's dependent on the etypes that is configured, default on most setups these days is AES but it can use RC4 or DES encryption which are weak
* If you are using CredSSP authentication it's dependent on the schannel TLS settings, things like TLS 1.0 could still be used or a weak cipher suite negotiated by the client and server

These buts are what concerns me about the wording in the docs. It states 

> Regardless of the transport protocol used (HTTP or HTTPS), WinRM always encrypts all PowerShell remoting

Based on those buts either that is not true (see Basic auth over HTTP) or the encryption that is used is weak and should honestly not be used at all. The most common example of this would be using NTLM auth. If someone is trying to use a PSRemoting session using a local account, or connect to a server using an IP address and not the dns name then they will ultimately be using NTLM authentication. This means the encryption that is used to protect wrap the PSRP data that goes across the wire is encrypted using and RC4 cipher with 128 bit encryption which is known to be weak. It's basically saying that using a https site is secure even when it only offers TLS 1.0 and not TLS 1.2+ as a protocol.

**Comment by sdwheeler** [comment]
The bottom line is that PSRP does not do any encryption (except for the SecureString case). PowerShell relies on the encryption provided by the transport: WinRM or SSH. That is what this article is saying. All of my sources tell me that WinRM encrypts session traffic with a 256-bit symmetric encryption key.

**Comment by jborean93** [comment]
> All of my sources tell me that WinRM encrypts session traffic with a 256-bit symmetric encryption key.

And what I'm saying is I don't believe that to be correct so the docs shouldn't indicate that to be the case. At least having a warning saying on a default system things are encrypted but the strength of encryption is dependent on other factors like x, y, z. The docs right now can give a false sense of security.

**Comment by sdwheeler** [comment]
I appreciate your passion and I understand your concern. I am not trying to publish misinformation. But unless you can show me evidence that the data is not encrypted, the doc stands.

**Comment by jborean93** [comment]
From the encryption aspect I agree it is encrypted by default you need to explicitly disable the encryption check to get that to occur. As per https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6089#issuecomment-642940782 what would be good to have on the docs is

> at least having a warning saying on a default system things are encrypted but the strength of encryption is dependent on other factors like x, y, z

This would at least indicate to people reading the docs who are interested in the security aspects that the situation is a lot more complicated and not think, ok PSRemoting is encrypted therefore secure. I've seen plenty of people link back to these docs to back up their claims that using NTLM auth, or even disabling that encryption check is ok because PSRemoting has it's own encryption that is independent to that.

**Comment by sdwheeler** [comment]
Still investigating internally to find authoritative source material.

**Comment by jborean93** [comment]
In case it helps, I've created a python script [winrm_decrypt.py](https://gist.github.com/jborean93/d6ff5e87f8a9f5cb215cd49826523045#file-winrm_decrypt-py) that can take the Wireshark capture of a PSRemoting exchange and decrypt the WSMan data if you provide either the plaintext password or NT hash of the password. There's also an example output of an exchange I did which I used for testing.

In any case you can see that for NTLM authentication it's not a 256-bit symmetric key but rather a 128-bit (at max) RC4 stream cipher where the key is based on the authentication exchange. The signing and sealing keys are derived [here](https://gist.github.com/jborean93/d6ff5e87f8a9f5cb215cd49826523045#file-winrm_decrypt-py-L87-L102) and the RC4 cipher used as the seal handle is then used to encrypt/decrypt the messages [here](https://gist.github.com/jborean93/d6ff5e87f8a9f5cb215cd49826523045#file-winrm_decrypt-py-L111-L126).

Kerberos and CredSSP work on a similar mechanism to encrypt the data, i.e. based on the auth context, but because those protocols are newer or at least updated recently, they can utilise better algorithms. That's could still be configured to use an older algorithm based on the OS settings though but by default they should be ok. Because basic auth has no security context negotiated, it's handled directly by the WinRM service, it cannot offer the wrapping/unwrapping functions that the others can.

**Comment by sdwheeler** [comment]
OK, I finally tracked down what I was looking for. I have updated the article.

**Comment by jborean93** [comment]
Thanks looks good.
