### ISSUE TITLE
Official definition of `cmdlet`

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#6105]
# Documentation Issue
[Discussion on Twitter](https://twitter.com/thorstenbutz/status/1270010735041658882) about the definition of `cmdlet`.  There seems to be some confusion on when `cmdlet` is used generally and when it means `binary cmdlet`.  PS-Committee discussed this and agreed that the original intent of the word `cmdlet` is a command that participates in the pipeline semantics of PowerShell.  This includes binary (C#) cmdlets, advanced script functions, CDXML, and Workflows.  Simple functions are not cmdlets.  When there is a need to specifically refer to binary/C# cmdlets, they should be called `binary cmdlets`.  There is no intent to fix inconsistencies in the code with this definition nor any parameters/members/etc... (like `CmdletsToExport` vs `FunctionsToExport` in psd1).

Work to be done:

- [ ] Officially define `cmdlet` in the documentation
- [ ] Update usage of `cmdlet` to `binary cmdlet` where it is only talking about C#

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [x] Version 7.0 content
  - [x] Version 6 content
  - [x] Version 5.1 content

  **Conceptual articles**
  - [x] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
  - [ ] Community articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by kilasuit** [comment]
@bergmeister think C# methods for why you have simple and advanced script based functions as for c# devs (& also other languages) simple functions make more sense coming to PowerShell from other languages and advanced functions, as well as binary cmdlets, are more advanced language features.

**Comment by sdwheeler** [comment]
Related to #6082
