### ISSUE TITLE
CentOS 8 and Red Hat 8 not listed?

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/PowerShell-Docs#6106]
The documentation lists CentOS and RHEL 7, but the latest stable version of both is 8. 

I'm fairly certain the command syntax is either identical or very similar for version 8, so it might be worth either simply renaming the current sections to include both version numbers (e.g. "CentOS 7 and 8") or just make a new section for the new version if there are slight differences, similar to how each Ubuntu major version has its own section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@jeffreymcclain It is a question of what we have tested and support.

@TravisEz13 Can you comment on this?

**Comment by TravisEz13** [comment]
We have on onboarding task.
https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ADistribution-Request
The package was named wrong for generic support.  We need to fix that so you don't have to update the docs twice.

**Comment by TravisEz13** [comment]
I update the powershell issue with my thoughts:  https://github.com/PowerShell/PowerShell/issues/10632

**Comment by sdwheeler** [comment]
I am closing this issue since these are not officially supported yet. @TravisEz13 has the tracking item to update the docs when these are supported.
