### ISSUE TITLE
about_PowerShell_exe now redirects to about_Pwsh

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6114]
Was this intentional, so as to only have to maintain a single help topic for both editions?

If so, the topic must be extended:

* Mention that Windows PowerShell uses a different executable name, `powershell.exe`

* Mention which parameters are _not_ supported in Windows PowerShell, plus the one that is supported _only_ in Windows PowerShell (`-PSConsoleFile`, even though it is virtually obsolete there as well)

Here's a command that shows the edition-specific parameters (must be run on Windows; output as of v7.0):

```powershell
PS> Compare-Object ((powershell -? | out-string -stream) -match '^-' -replace ',? .*' | Sort-Object) ((pwsh -? | out-string -stream) -match '^-' -replace ',? .*' | Sort-Object)

InputObject       SideIndicator
-----------       -------------
-CustomPipeName   =>
-Interactive      =>
-Login            =>
-SettingsFile     =>
-WorkingDirectory =>
-PSConsoleFile    <=
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 691419d7-6ba7-39a9-6e7d-c484a8d5cce0
* Version Independent ID: 4320a570-6740-fb56-3076-0fd93bf19fae
* Content: [about_Pwsh - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@mklement0  The change was intentional but it is not working as intended. I will take a look at it.
