### ISSUE TITLE
Installing PowerShell on macOS - Include Homebrew Tap method?

### ISSUE THREAD

**Issue by peterlewis** [MicrosoftDocs/PowerShell-Docs#6121]
# Documentation Issue

Update documentation to installation of binaries via Homebrew (i.e. `brew install powershell/tap/powershell`).

## Context of the issue

- URL to the article (Docs or GitHub URL):

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7

- Issue affects the following content (check all that apply):

  **Cmdlet reference & about_ topics**
  - [x] Version 7.x preview content
  - [x] Version 7.0 content
  - [ ] Version 6 content
  - [ ] Version 5.1 content

  **Conceptual articles**
  - [ ] Fundamental conceptual articles
  - [ ] Script sample articles
  - [ ] DSC articles
  - [ ] Gallery articles
  - [ ] JEA articles
  - [ ] WMF articles
  - [ ] SDK articles
  - [ ] Community articles
- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

Y - macOS

## Detailed description of the issue

Current installation instructions only include `brew cask` install. Is there scope to include the Homebrew Tap method of `brew install powershell/tap/powershell` as well?

I note that lower-down in the article you include instructions for 'Installing binary archives on macOS'. I'd suggest that including this method, here, could be a user-friendly way to allow people to install binary archives as easily as they would `brew cask install`.

Thanks!

Peter

**Comment by sdwheeler** [comment]
@TravisEz13 We we support tap installs?

**Comment by peterlewis** [comment]
Yup, [it appears so](https://github.com/PowerShell/Homebrew-Tap)!

**Comment by TravisEz13** [comment]
The stable and LTS are supported...
The preview and daily are community supported...

caveats about the formulas:

- the app that launches `pwsh` in a terminal is missing
  - This is theoretically fixable although, the app would be put in the users Application folder.
- https://github.com/PowerShell/Homebrew-Tap/blob/7acd5d0f3b026f9b12809c85c4bef521fec108fb/Formula/powershell.rb#L31-L36 
  - These I cannot fix for the user.  The goal of the formula is to run without sudo.  And not creating a conflicting link, is just a default brew behavior.
  >       If you also have the Cask installed, you need to run the following to make the formula your default install:
  >         brew link --overwrite powershell
  >      If you would like to make PowerShell you shell, run
  >        sudo echo '#{bin}/pwsh' >> /etc/shells
  >        chsh -s #{bin}/pwsh
cc @joeyaiello @SteveL-MSFT

**Comment by peterlewis** [comment]
Ah, super! Thanks, all (@chasewilson, @sdwheeler and @TravisEz13) for adding those instructions, so quickly! It's much appreciated! :)
