### ISSUE TITLE
Where is the default module storage folder defined?

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/PowerShell-Docs#6125]
The article refers to `$env:ProgramFiles\WindowsPowerShell\Modules` but that does not seem right.

Our Pwsh 7 installation is in the following path:
`C:\Program Files\PowerShell\7` 

But `Install-Module` tries to store modules into:
`C:\Program Files\PowerShell\Modules`
This fails with an exception: `Administrator rights are required to install modules in 'C:\Program Files\PowerShell\Modules'`.

We would like to repair our Pwsh 7 installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @cveld, thank you for the feedback. If you look at the headers for the articles, all references, for `$env:ProgramFiles\WindowsPowerShell\Modules` fall under a section for "For computers running PowerShell 3.0 or PowerShell 4.0". In the instructions for using the latest versions (v 5.0 and above) it is already installed and is scoped to installing PowerShellGet. Not installing packages. 

If you are looking for more information on those topics, I would look at [Install-Module](https://docs.microsoft.com/powershell/module/powershellget/install-module?view=powershell-7) and specifically, the [Notes section of Install-Module](https://docs.microsoft.com/powershell/module/powershellget/install-module?view=powershell-7#notes). This references locations for download and is specific to the version of PowerShell documentation.

**Comment by cveld** [comment]
For future reference: we were able resolve the issue by reinstalling
PowerShell 7.

Op di 16 jun. 2020 om 15:40 schreef Chase Wilson <notifications@github.com>:
