### ISSUE TITLE
Note is not accurate?

### ISSUE THREAD

**Issue by SDedik** [MicrosoftDocs/PowerShell-Docs#6127]
Quoting one of the notes on this page:

> The LCM starts the ConfigurationModeFrequencyMins cycle based on:
> - A new metaconfig is applied using Set-DscLocalConfigurationManager

However, my experiments show that this is not accurate. Lets say I have following LCM meta configuration script:
```
[DscLocalConfigurationManager()]
Configuration LCMConfig {
    Settings {
        ActionAfterReboot               = "ContinueConfiguration"
        AllowModuleOverwrite            = $true
        ConfigurationMode               = "ApplyAndMonitor"
        ConfigurationModeFrequencyMins  = 15
        DebugMode                       = "None"
        RebootNodeIfNeeded              = $true
        RefreshMode                     = "Pull"
        RefreshFrequencyMins            = 120
    }

    ConfigurationRepositoryWeb PullSrv {
        ServerURL                       = "https://pullsrv/PSDSCPullServer.svc"
        RegistrationKey                 = "$guid"
        ConfigurationNames              = @("named_config")
    }

    PartialConfiguration named_config {
        ConfigurationSource             = @("[ConfigurationRepositoryWeb]PullSrv")
    }
}
```
`localhost.meta.mof` has been generated and applied. Named configuration is also on the pull server and has been applied successfully. According to the `ConfigurationModeFrequencyMins` value, current configuration is checked every 15 minutes, which can be confirmed by the event log messages from Applications and Services Logs -> Microsoft-Windows-Desired State Configuration/Operational -> Event ID 4312:
```
The DscTimer is running LCM method PerformRequiredConfigurationChecks with the flag set to 1.
```
Those events are registered every 15 minutes as expected.

Now, what happens if in the middle of of this interval I invoke `Set-DscLocalConfigurationManager` with the same `localhost.meta.mof` as before? According to documentation, this should reset the timer because "new" configuration has been applied. However, it doesn't happen, the timer keeps working without interruption:
```
Get-WinEvent Microsoft-Windows-DSC/Operational | Where-Object {$_.id -eq 4312}

   ProviderName: Microsoft-Windows-DSC

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
6/16/2020 11:56:32 AM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
6/16/2020 11:41:32 AM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
<---- THIS IS WHERE Set-DscLocalConfigurationManager has been invoked at 11:30 ---->
<---- Next expected event is at 11:45 ---->
6/16/2020 11:26:35 AM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
```

Ok, maybe documentation's `new metaconfig` means literally `new`. Lets try to change one of the parameters and generate new `localhost.meta.mof`.
Following parameter has been changed from 120 to 240:
```
[DscLocalConfigurationManager()]
Configuration LCMConfig {
    Settings {
        ...
        RefreshFrequencyMins            = 240
    }
...
```
New meta.mof has been generated and applied at 12:05. But the timer has not been affected again! Events are still registered as if timer has not been reset!
```
6/16/2020 12:56:32 PM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
6/16/2020 12:41:32 PM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
6/16/2020 12:26:32 PM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
6/16/2020 12:11:32 PM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
<---- THIS IS WHERE Set-DscLocalConfigurationManager has been invoked at 12:05 ---->
<---- WITH CHANGED meta.mof ---->
<---- Next expected event is at 12:20 ---->
6/16/2020 11:56:32 AM         4312 Information      The DscTimer is running LCM method PerformRequiredConfigurationC...
```
---

Clarification is required which EXACT events and conditions lead to timer being reset. Documentation has to be corrected to be 100% TECHNICALLY ACCURATE!

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6986f2-ea24-1bcd-7bba-04f18cac63ff
* Version Independent ID: 41a9cf31-b59c-4845-37c2-0e9cb6c19b23
* Content: [Configuring the Local Configuration Manager - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/managing-nodes/metaconfig?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/dsc/managing-nodes/metaConfig.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/managing-nodes/metaConfig.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @SDedik. Thank you for the detailed feedback and your testing!

I have submitted a PR and you should see the changes in the documentation within the next 24 hours. 

In practice, updating the MOF will act much the same as if applying another configuration. The DSC engine will check a target to see if the configuration matches the current state. If the state matches the configuratioin, no changes are made. This reduces resource usage and risk. I believe this is why the time doesn't reset when reapplying a configuration, or applying a new configuration where the **ConfigurationModeFrequencyMins** is not adjusted. 

I can definitely see how the Note could cause confusion and this is a great catch. 
Thank you again and feel free to open an issue if you see any other areas that could be improve!
