### ISSUE TITLE
Add docs for 3rd-party installs and installers

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#6130]
# Summary of the new document or enhancement

From @SteveL-MSFT 
> Since we already have a list of Community supported Linux distros, it seems appropriate to have a
> section on Community supported installers with appropriate disclaimer. In which case, Chocolatey
> should also be mentioned.

Need to decide if this is separate article or added to existing.

From PR #6123 
```
## Install Powershell via 3rd party modules

### Requirements
- Change of Execution policy, for the time of installation and use of the module
- NuGet Module will install with the process
- Internet connection

### Installation of PowerShell 7 via PSReleaseTools
Set-ExecutionPolicy -RemoteSigned

Install-Module PSReleaseTools

Import-Module PSReleaseTools

### Install PowerShell 7 Release via PSReleaseTools
Install-PowerShell

[PSReleaseTools Reference by Jeff Hicks:](https://github.com/jdhitsolutions/PSReleaseTools)
```

@joeyaiello Can you comment on this? Should we go forward with docs around 3rd-party tools like this?

**Comment by joeyaiello** [comment]
I'm not sure I want to open the door without a hard line on what should go in and what shouldn't. Otherwise, we could end up "doc'ing the whole world" so to speak wherever something in the community improves some experience we ship. 

And I don't know that that line is definable....

**Comment by sdwheeler** [comment]
Closing as "wont-fix".

**Comment by Karl-WE** [comment]
Thanks for your thoughts I understand the concerns.
Perhaps we should remove community content from the PR template? It was the reason that tempted me.
