### ISSUE TITLE
Please provide further explanation of the interaction with system sleep/power modes

### ISSUE THREAD

**Issue by NeilMacMullen** [MicrosoftDocs/PowerShell-Docs#6131]
It's unclear from the documentation how start-sleep interacts with OS power-modes. For example, if I call -start-sleep -seconds 7200 and the PC later  enters sleep mode (S1 or higher) shortly afterwards...
- will sleep mode exit 2 hours after the command was issued?
- if sleep mode is not automatically exited, and the user wakes up the computer after 90  minutes, does the command complete after a further 30 minutes, or 2 hours after the wakeup ?  (Or some other value?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1b0e88-70b7-a078-f913-745ebfa9a922
* Version Independent ID: a874cf88-e612-8833-188e-9afdcc541cd7
* Content: [Start-Sleep (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/start-sleep?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Start-Sleep.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Start-Sleep.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hi @NeilMacMullen, Thank you for the feedback. Please correct me if I'm misunderstanding. 

I don't believe clarification needs to be added in this document. It wont change the reaction or state of your session any differently than a normal session will when your machine goes into a sleep state. 

This doc is reference material specific to the cmdlet and as it doesnt' react differently than a normal session, i dont believe it is relevant to this doc. 

I'll be closing this issue for now but if you feel like I'm wrong or I'm misunderstanding, feel free to repond and I'll reevaluate. 

Thanks again!

**Comment by chasewilson** [comment]
@NeilMacMullen while we won't be makingh changes to the doc, I wanted to test and see what the result was to ansewr your question. 

I ran a script to start sleeping and then manually put my machine in a sleep. The PowerShell session was stopped completely and started when i brought the machine out of sleep. 

Result: When your machine goes into sleep, the sleep timer in PowerShell will also stop, pausing the counter keeping track of the sleep time. It will resume again when the machine is awake from where it was paused.
