### ISSUE TITLE
Documentation Issue New-NetFirewallRule  vs Set-NetFirewallRule 

### ISSUE THREAD

**Issue by GaryLBaird** [MicrosoftDocs/PowerShell-Docs#6132]
# Documentation Issue
Set-NetFirewallRule -Name 'WINRM-HTTP-In-TCP-PUBLIC' -RemoteAddress Any

Should be: For Windows 10 it doesn't exist by name and thus you need to use New not Set.
New-NetFirewallRule -Name 'WINRM-HTTP-In-TCP-PUBLIC' -RemoteAddress Any -DisplayName 'WINRM-HTTP-In-TCP-PUBLIC'  

## Context of the issue

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enable-psremoting?view=powershell-7
- Example 3: Allow remote access on clients

Just a simple change to the document.

"Set-NetFirewallRule -Name 'WINRM-HTTP-In-TCP-PUBLIC' -RemoteAddress Any"

Should be: For Windows 10 it doesn't exist by name and thus you need to use New not Set.

"New-NetFirewallRule -Name 'WINRM-HTTP-In-TCP-PUBLIC' -RemoteAddress Any -DisplayName 'WINRM-HTTP-In-TCP-PUBLIC' "

**Comment by chasewilson** [comment]
Hi @GaryLBaird, thanks for the feddback. 

I'm sorry but I'm not clear on what you are asking for here. The commands work as they are written on my machine (Windows 10). 

I may be misunderstanding what you are asking for so if i am feel free to provide more information.

**Comment by chasewilson** [comment]
@GaryLBaird, sorry for the confusion I see where the issue is now. I will be taking the issue and will have a PR linked to this issue.
