### ISSUE TITLE
Encoding parameters list should match case of implementation

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/PowerShell-Docs#6136]
The list of values for the -Encoding parameter should use the same case as the implementation uses.

The current documentation page lists:
```
ASCII
BigEndianUnicode
OEM
Unicode
UTF7
UTF8
UTF8BOM
UTF8NoBOM
UTF32
```
But, the auto-completed validated set when used at the console is:
```
ascii
bigendianunicode
bigendianutf32
oem
unicode
utf7
utf8
utf8BOM
utf8NoBOM
utf32
```
This is using 7.1.0-preview.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5296b2d4-9030-c84f-95ad-40574181d958
* Version Independent ID: e4684775-c0df-ad9a-7eef-135db60ada1b
* Content: [Set-Content (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Set-Content?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Set-Content.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Set-Content.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @Liturgist , Thanks for the feedback. The doc you referenced is for PowerShell v 7.0. If you switch the version to 7.1, you will see the complet list of encoding types you have listed. There are new types only available in the latest release of PowerShell 7.1. 

I hope this clears things up! This was great attention to detail and if you see any other areas we need to improve, I hope you'll open a new issue. 

Thanks again and have a great rest of the day!

**Comment by Liturgist** [comment]
@chasewilson - The 7.1 documentation has the list of encodings using different cases (UPPER CASE and LOWER CASE) letters than appears when using the PowerShell Console. The use of UPPER CASE and LOWER CASE letters should be consistent across the product. Consistency makes a product easier to use and easier to be successful with.

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Set-Content.md

**Comment by Liturgist** [comment]
There is yet another, different set of cases used in the code of .\PowerShell\src\System.Management.Automation\utils\EncodingUtils.cs

```
    internal sealed class ArgumentEncodingCompletionsAttribute : ArgumentCompletionsAttribute
    {
        public ArgumentEncodingCompletionsAttribute() : base(
            EncodingConversion.Ascii,
            EncodingConversion.BigEndianUnicode,
            EncodingConversion.BigEndianUtf32,
            EncodingConversion.OEM,
            EncodingConversion.Unicode,
            EncodingConversion.Utf7,
            EncodingConversion.Utf8,
            EncodingConversion.Utf8Bom,
            EncodingConversion.Utf8NoBom,
            EncodingConversion.Utf32
        )
        { }
    }
```
