### ISSUE TITLE
Missing two distributions of Linux

### ISSUE THREAD

**Issue by DoctorWho8** [MicrosoftDocs/PowerShell-Docs#6147]
Hello!
Okay you're missing Slackware Linux which is used by more developers than any except Red Hat and Suse. And you're missing SuSe SLES12 which is now at their SP4. I have a WSL installed release of SLES12SP3 which has PowerShell installed into the dotnet tools.

And once upon a time I was able to install PowerShell for Linux onto Slackware-14.2 on X64 using both a app package and from a tarball.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#binary-archives)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
We haven't tested those. You need to file a distribution support request in the PowerShell repo.
[Distribution Support Request](https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Distribution-Request&template=Distribution_Request.md&title=Distribution+Support+Request)
