### ISSUE TITLE
Document the specific constraints of the stop-parsing symbol (--%)

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6149]
It is worth clarifying the following limitations, notably the one with respect to what causes `--%` to stop parsing (see https://github.com/PowerShell/PowerShell/issues/12975):

* `--%` supports only _one_ command, which an unquoted `|`, `||` or `&&` on the same line, if present, implicitly ends; this allows you to pipe / chain such a command to / with other commands.

  * However, using `;` in order to unconditionally place another command on the same line is _not_ supported; the `;` is passed through verbatim.

  *  `--%` reads (at most) to the _end of the line_ so spreading a command across multiple lines with line-continuation chars. is NOT supported

* Other than `%...%` *environment*-variable references, you cannot embed any other dynamic elements in the command; that is, **you cannot embed regular PowerShell variable references or expressions**.
   * Escaping `%` characters as `%%` (the way you can do inside batch files) is _not_  supported; `%<name>%` tokens are _invariably_ expanded, if `<name>` refers to a defined environment variable (if not, the token is passed through as-is). 

* You **cannot use stream redirections** (e.g., `>file.txt`), because they are passed _verbatim, as arguments_ to the target command.

  * For _stdout_ output you can work around that by appending `| Set-Content file.txt` instead, but there is no direct PowerShell workaround for _stderr_ output.

  * However, if you invoke your command _via `cmd`_, you can let `cmd` handle the (stderr) redirection (e.g., `cmd --% /c nosuch 2>file.txt`)

#4963 discusses why, specifically, `--%` is virtually useless on _Unix-like platforms_ (the `about_Parsing` topic now mentions that, but just in the abstract ("The stop-parsing symbol only intended for use on Windows platforms.")).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60e7291-d3a7-bf51-c945-ff5ef5f4d570
* Version Independent ID: b9957906-f58b-86de-7907-cc2f94174af3
* Content: [about_Parsing - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Adding links to related issues:
- #2361  Document the need for additional \-escaping of double quotes (") when calling external programs
- #5152 Introduce a conceptual help topic about calling external programs (native applications)
