### ISSUE TITLE
Foreach-Object -Parallel examples of how to report progress

### ISSUE THREAD

**Issue by scott1138** [MicrosoftDocs/PowerShell-Docs#6160]
It would be great if we could get more examples of some complex scenarios using the -Parallel parameter.  Recently I wanted to use Write-Progress, but as I had assumed, it doesn't work across runspaces.  I resorted to using the concurrent bag collection to add objects at the start of the runspace and then get the count of items and then over-write the same line with "x of n completed" sort of thing.  If there is a better way to do this I would love to see some examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da56c3ce-409c-dd44-888b-6a875e93d4a4
* Version Independent ID: 7ba53b91-ed64-cc24-0cf0-a5dc3f3dc9d0
* Content: [ForEach-Object (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@PaulHigin Any ideas here?

**Comment by WithHolm** [comment]
I have tested a solution using synced hashtable.
The thing with synced hashtable is that its persistent over several runspaces or threads, so a value you set in the runspace can be read by the parent session using this object.

Combine that with the `-asjob` parameter, you get to start the processing and then read the progress output from the synced hashtable.

this required you to define a `[int]$ID` for each object in the `|foreach`, so the correct progess is written to. 

https://gist.github.com/WithHolm/74b833a328c8881c51081b84a356bfc3

let me know if this could help you :)

**Comment by scott1138** [comment]
@WithHolm That's a really interesting idea!  I hadn't thought to start the process as a job and then watch it using the threadsafe variable.  Thanks for the help!

**Comment by chasewilson** [comment]
@PaulHigin this looks like a pretty viable solution. What are your thoughts and are there any more options you would like to see?

**Comment by chasewilson** [comment]
@WithHolm , Your example is a great resource and we have a new article in which we'd love to use your example. You can review the [PR here](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6411) and as long as you are ok with it, we will go ahead and publish it.

**Comment by WithHolm** [comment]
I'm glad to hear it benefits the community! You may use it
