### ISSUE TITLE
UFormat specifier %F does not work properly in PowerShell 5.1

### ISSUE THREAD

**Issue by johnkberry** [MicrosoftDocs/PowerShell-Docs#6168]
UFormat specifier %F does not work properly in PowerShell 5.1:

PS > Get-Date -UFormat "%F"
F

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb115dd-268a-bb87-e080-7fe2d9194136
* Version Independent ID: 09bab64d-b131-3961-a8c2-10ecf7f3d96b
* Content: [Get-Date (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Thanks. I think that was copied by mistake from the v6 version of the article.
