### ISSUE TITLE
Why doesn't Get-Service return the trigger info for services that have triggers?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/PowerShell-Docs#6173]
Get-ScheduledTask returns trigger info. Why doesn't Get-Services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: affd5eed-a6cf-ed3c-572d-869c974dde51
* Version Independent ID: 52b4131a-0ccb-3942-1b13-7b57faf329d5
* Content: [Get-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
The short answer is that PowerShell can only return what is made available by WMI. This is not a PowerShell issue. See https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-service

But I don't know what triggers you mean. There aren't any triggers that I know of.

**Comment by BrianCatlin** [comment]
Just like tasks can be triggered, services can be triggered
https://docs.microsoft.com/en-us/windows/win32/services/service-trigger-events

**Comment by sdwheeler** [comment]
OK. Those aren't exposed by WMI so PowerShell has no way to get that information.

**Comment by BrianCatlin** [comment]
So, how do we solve this problem? Can you post an internal bug on WMI?

**Comment by sdwheeler** [comment]
It appears that the information is only available using Windows APIs. It would be a feature request in Windows to add that information to Win32_Service. I don't have a way to create that request. Besides, it needs to come from you, the customer, with a supporting business case. I don't know know where you would file that kind of request except through a support incident.

Can you get the information you need from `sc.exe qtriggerinfo [service name]`? That is my suggestion. If you need it in PowerShell then you could parse the output into the object you want.

**Comment by BrianCatlin** [comment]
Couldn't the your team make the request on my behalf, so that Get-Service works equivalently to Get-ScheduledTask?

**Comment by sdwheeler** [comment]
That would be a feature request for the cmdlet. This is not a docs issue. You can file a feature request at https://aka.ms/psfeedback. It would be up to the product team to determine if it is worth pursuing. 

I don't have high hopes for that. If the WMI team added the information then the PowerShell team might be more interested in a change to support it.

This change needs to happen WMI. For that you can file a request through [Uservoice](https://windowsserver.uservoice.com/forums/295047-general-feedback).

**Comment by BrianCatlin** [comment]
Done, and done
Thanks
