### ISSUE TITLE
Script is missing the actual "invoke" to create the MOF file

### ISSUE THREAD

**Issue by aaronfury** [MicrosoftDocs/PowerShell-Docs#6176]
In the code sample provided, after the code block defining the "HelloWorld" configuration, you need to then _invoke_ the configuration by executing HelloWorld. That way, when the script is run, it will load the Configuration object and then actually invoke it to create MOF file; otherwise nothing happens after running the PS1 script. See the bottom two lines of the script below (EDIT: apparently I don't know how to markdown).

```
Configuration HelloWorld {...}

HelloWorld
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 980b6aa3-93f6-9a8c-7688-356693fc81e1
* Version Independent ID: 183254f6-d5b6-04e0-6d99-b9e090a01358
* Content: [Write, Compile, and Apply a Configuration - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/write-compile-apply-configuration?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/configurations/write-compile-apply-configuration.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/configurations/write-compile-apply-configuration.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by joeyaiello** [comment]
I think it's called out via dot-sourcing in the `Compile` header just below: https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/configurations/write-compile-apply-configuration.md#compile-the-configuration

That being said, it might be worth calling out another example where the function is called in the same script, as that's probably more common in the real world. (But I do think the way we have it now is probably more instructive/learning-oriented.)

**Comment by aaronfury** [comment]
Argh. I guess I misinterpreted the documentation. I see now that it is called after the dot-sourcing; without formatting I didn't register that those were separate commands. My bad. I see the update to the comment to mention that the call can be appended to the bottom of the script; I think that will help clarify it. Thanks!
