### ISSUE TITLE
about_Comparison_Operators: use cases for -match are slightly misleading

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [MicrosoftDocs/PowerShell-Docs#6187]
In the [-match operator section](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7#match), the second paragraph says:

> The match operators search only in strings. They cannot search in arrays of integers or other objects.

They cannot search in arrays of integers? It works as if they can:

```
PS C:\> 10..20 -match '[2468]$'
12
14
16
18
```

So either that is incorrect, or it's trying to communicate some other point which isn't coming through clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50bd0dc3-279b-baea-5c19-823e0bc44534
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7#match)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hi @HumanEquivalentUnit. This is really great feedback. The doc is a little unclear on it's intent in that sentece and I can see how it oculd be read that way. 

I believe waht the doc is meaning is that PowerShell won't populate the `$Matches` variable when working with arrays or collections. It talks about this in the section below your quoted sentence. But that sentence is a little confusing. 

So, If you want to find out if an array has a match in it, you can run your example, and as you saw, it will return the matching items. However, the `$Matches` var will be empty so you won't be able to access that object. 

I'll still be updating the docs to try dand clarify that a little be so thanks for pointing that out!

**Comment by HumanEquivalentUnit** [comment]
@chasewilson That makes sense; I guess I don't think of regex and `$matches` as "searching", and I think of what they do as "filtering" an array, rightly or wrongly.

Anyway, thank you for explaining, and updating :)
