### ISSUE TITLE
Update Write Custom DSC Resource Docs for updated Design patterns. 

### ISSUE THREAD

**Issue by chasewilson** [MicrosoftDocs/PowerShell-Docs#6216]
# Documentation Issue

A [PR](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6128) was raised pointing out that good design practices need to be updated for current recommendations. 

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/powershell/scripting/dsc/resources/authoringResource
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [x] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
The DSC content is mostly static at this point. The DSC Community is driving innovation around patterns and practices. We will let them own this kind of content.
