### ISSUE TITLE
Get-Date -UFormat %F does not work

### ISSUE THREAD

**Issue by alphanimal** [MicrosoftDocs/PowerShell-Docs#6224]
The %F placeholder for the -UFormat parameter does not work.
According to the documentation, `Get-Date -UFormat "%F"` should return the date in ISO8601 format, for example 2020-07-01, but it does not in the current version of PowerShell.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5080ef0e-f37a-54f2-9e5d-bf9728feb0dc
* Version Independent ID: 09bab64d-b131-3961-a8c2-10ecf7f3d96b
* Content: [Get-Date (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Date?view=powershell-7&viewFallbackFrom=powershell-3.0)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The `%F` format does not work in PowerShell 5.1. The `%F` format was added in PowerShell 6. You are looking at documentation for PowerShell 7. 

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> Get-Date -UFormat "%F"
2020-07-01
```
