### ISSUE TITLE
Should Example commands include the Powershell prompt?

### ISSUE THREAD

**Issue by asears** [MicrosoftDocs/PowerShell-Docs#6238]
As the prompt is not valid syntax or part of the command, should remove the PS> prompt from the examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b645ad54-613d-3163-cca4-ddef7056fe88
* Version Independent ID: 2937718a-ad0f-9224-2eb3-5f3498c1266b
* Content: [Examples of Comment-Based Help - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/help/examples-of-comment-based-help?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/help/examples-of-comment-based-help.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/help/examples-of-comment-based-help.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
In some cases, yes. Some no. It depends on the intent of the code sample. Is the example used to illustrate a concept or be a usable sample? 

See our style guide. https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide#markdown-for-code-samples

I would say that those examples are more illustrative, so the prompt is OK.
