### ISSUE TITLE
Invoke-History functionality change

### ISSUE THREAD

**Issue by thomasrayner** [MicrosoftDocs/PowerShell-Docs#6250]
# Summary of the new document or enhancement

- List of articles that need to be updated: [Invoke-History on docs.microsoft.com](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Invoke-History.md)
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: PowerShell/PowerShell/pull/12998
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: PowerShell/PowerShell/issues/12488

## Description of what changed

Summary: The `-Id [string]` parameter for `Invoke-History` is changed to `-Id [String[]]` which accepts an array of strings.

Pursuant to PowerShell/PowerShell/pull/12998 (once merged), `Invoke-History`'s `-Id` parameter now takes a collection of IDs instead of only single IDs or a string (representing a partial match of a prior command). [Example 4](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Invoke-History.md#example-4-run-a-sequence-of-commands-from-the-history) and [example 5](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Invoke-History.md#example-5) are outdated, and the [description for the `-Id` parameter](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Invoke-History.md#-id) needs to be updated.

**Comment by sdwheeler** [comment]
Closing this issue since the linked code PR was closed with out merging.

@thomasrayner Let me know when you fix the code and we can reopen this issue.
