### ISSUE TITLE
Documentation outdated - suggests MacPorts which conflicts with Brew

### ISSUE THREAD

**Issue by kierandelaney** [MicrosoftDocs/PowerShell-Docs#6270]
Hi,

The documentation has a section referring to OpenSSL being installed by MacPorts - MacPorts and Homebrew don't get along - it is strongly encouraged by both sets of developers to not install both at the same time.

The documentation should suggest OpenSSL is installed via Brew instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cac030d-de88-9bf0-5ea8-7213b5d7f088
* Version Independent ID: d025a07e-05e1-ef40-5500-36d3facbcc04
* Content: [Installing PowerShell on macOS - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md)
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@TravisEz13 Can you comment on this?

**Comment by TravisEz13** [comment]
The one from brew won't work.  Personally, I'm happy to cut the MacPorts part and say the features is not supported.

**Comment by TravisEz13** [comment]
cc @SteveL-MSFT

**Comment by kierandelaney** [comment]
The documentation could at least be better laid out - it currently reads, to me at least, that the dependencies are required even when installing from Homebrew (the heading for Installing Dependencies is the same weight as the installation via Brew).

It is not clear from the docs, when you might _actually need to install_ the dependencies - Brew Install, Direct Download, Binary Archive, none of the above?
