### ISSUE TITLE
Looking for PowerShell Hero in Orange as wallpaper.

### ISSUE THREAD

**Issue by johnnliu** [MicrosoftDocs/PowerShell-Docs#6277]
I'm looking for a high res version of the Orange version of the PowerShell Hero as a standalone screenshot.

she is on the second page of PowerShell_Poster.pdf

![image](https://user-images.githubusercontent.com/1279372/87500295-739d2680-c69f-11ea-8d1e-eff84914dd05.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4af16b8c-9b33-d53b-fcc8-ecabe6d0385a
* Version Independent ID: cc9d8f99-6f2f-24e9-d724-9746e0201182
* Content: [PowerShell Digital Art - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/community/digital-art?view=powershell-7)
* Content Source: [reference/docs-conceptual/community/digital-art.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/community/digital-art.md)
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The PDF is the only version of the image that is available.
