### ISSUE TITLE
Need info on getting a verb added

### ISSUE THREAD

**Issue by sharpninja** [MicrosoftDocs/PowerShell-Docs#6278]
We need a link to somewhere we can request having a verb added to the approved list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c285b90-bf7e-60c8-2eef-3ba0a57e06cb
* Version Independent ID: 19b205d5-c044-389c-f887-946123130034
* Content: [Get-Verb (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-verb?view=powershell-6&WT.mc_id=ps-gethelp)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Get-Verb.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Get-Verb.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Please file a feature request at https://aka.ms/psfeedback
