### ISSUE TITLE
No Download PDF option for PowerShell 7 documentation

### ISSUE THREAD

**Issue by neilsteyn** [MicrosoftDocs/PowerShell-Docs#6283]
Hi

There is no download pdf option for the powershell 7 documentation. It would be nice to have the download pdf option for it like on other docs, example: https://docs.microsoft.com/en-gb/gaming/xbox-live/get-started/join-dev-program/live-dev-program-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b770965-4cc8-203e-5332-26bb9ee99220
* Version Independent ID: 1ac2554b-bf6a-2da6-3708-2d63af435e1e
* Content: [What is PowerShell? - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/overview.md)
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The `Download PDF` feature does not work with the PowerShell-Docs content. I have raised an issue internally about this. Don't know when or if this will be fixed.
