### ISSUE TITLE
ubuntu 20.04 support

### ISSUE THREAD

**Issue by magixus** [MicrosoftDocs/PowerShell-Docs#6284]
docs page need to be updated concerning ubuntu 20.04 support since the repo does support 
[official prod 20.04 ](https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@TravisEz13 What is our support statement for Unbuntu 20.04?

**Comment by sdwheeler** [comment]
I see that this is supported now - https://github.com/PowerShell/PowerShell/issues/12626#issuecomment-653131660

@TravisEz13 can you update the documentation?

**Comment by sdwheeler** [comment]
@magixus That link is not the PowerShell package. They are still working on updating the build pipeline to include a package for Ubuntu 20.04. Docs will be updated as part of that work.

**Comment by magixus** [comment]
alright @sdwheeler , just passed by, and wanted to install PS on my Ubuntu 20.04.
I was looking for official .DEB, but didn't found support for my OS, then I found that link and install it.  
Since the docs will be updated based on updating the build pipeline this issues should be closed.
thank you.
