### ISSUE TITLE
winget install requires "-e" exact match parameter

### ISSUE THREAD

**Issue by EdAlexander** [MicrosoftDocs/PowerShell-Docs#6285]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7#installing-the-msi-package)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
@EdAlexander thanks for the feedback.  There was an issue with the syntax, which I am fixing. However, I can't replicate the necessity for the exact match parameter? 

What issue are you getting?

**Comment by EdAlexander** [comment]
Without -E it reported multiple matches

Sent from my Windows 10 device

**Comment by chasewilson** [comment]
@EdAlexander I found when you tried to use the version previousy on PowerShell 7 preview, it worked. but when trying to install PowerShell 7, it would find the multiple matches. I've updated the docs to use -e and remove versions. Thank you again for the feedback.
