### ISSUE TITLE
Reconcile page content with `Get-Verb`

### ISSUE THREAD

**Issue by sharpninja** [MicrosoftDocs/PowerShell-Docs#6298]
The page currently is incongruent with the output of `Get-Verb` in PS 7.0.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edfbab86-9144-1866-2765-938a5cc68ed7
* Version Independent ID: b4035200-8b55-c70c-7a29-4de085c87e1c
* Content: [Approved Verbs for PowerShell Commands - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @sharpninja thanks for the feedback. Would you mind giving some more specific details as to what you mean by incongruent?

**Comment by sdwheeler** [comment]
@chasewilson We need to add this one:

```
Verb   AliasPrefix Group  Description
----   ----------- -----  -----------
Resize rz          Common Changes the size of a resource
```

**Comment by sdwheeler** [comment]
@sharpninja This page will always contain more information and guidance than what is provided in the output of `Get-Verb`. However, it needs to contain all of the information. We are adding the missing verb.
