### ISSUE TITLE
Several docs missing

### ISSUE THREAD

**Issue by Allexxann** [MicrosoftDocs/PowerShell-Docs#6307]
# Documentation Issue

Several help articles cannot be updated - server returns 404. Definitely missing Russian localisation, presumably English as well.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Version 7.1 preview content
- [x] Version 7.0 content
- [x] Version 6 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue
When I use Update-Help, it fails to update several articles on several cmdlets: ConfigDefender, PSDesiredStateConfiguration, PSReadline, ThreadJob, WindowsUpdateProvider. Server throws 404. Other stuff updates just fine.
I work in Russian environment, but when I ran suggested 'Update-Help -UICulture en-US', result was exactly the same.

Issue is present in some form since Windows Powershell 5.1 and persists until the current version. Cannot remember when exactly it started, some sort of gallery reorganization, I think, but not sure.
Exact list varied with time, initially I saw reports only on WindowsUpdateProvider (or the process initially failed on it and did not go further).
If listed cmdlets are deprecated, removed or renamed, and thus have no articles, there also should be some way to clear them and their help from my computer in centralised fashion.

**Comment by sdwheeler** [comment]
PowerShell 7.1 updateable help is not being published yet.

Cmdlet reference is not being localized so it is only available in English. 

The PSDesiredStateConfiguration, PSReadline, and ThreadJob modules are known issues that we are working to fix. We hope to have most of this fixed by end of September.

ConfigDefender and WindowsUpdateProvider are not part of this docset, they are in the Windows docset. This problem is already been reported to the Windows team to fix.

**Comment by sdwheeler** [comment]
The PSDesiredStateConfiguration and ThreadJob modules should be fixed now.
