### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by Allexxann** [MicrosoftDocs/PowerShell-Docs#6308]
# Documentation Issue

Several help articles cannot be updated - server returns 404. Definitely missing Russian localisation, presumably English as well.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [* ] Version 7.1 preview content
- [ *] Version 7.0 content
- [ *] Version 6 content
- [ *] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue
When I use Update-Help, it fails to update several articles on several cmdlets: ConfigDefender, PSDesiredStateConfiguration, PSReadline, ThreadJob, WindowsUpdateProvider. Server throws 404. Other stuff updates just fine.
I work in Russian environment, but when I ran suggested 'Update-Help -UICulture en-US', result was exactly the same.

Issue is present in some form since Windows Powershell 5.1 and persists until the current version. Cannot remember when exactly it started, some sort of gallery reorganization, I think, but not sure.
Exact list varied with time, initially I saw reports only on WindowsUpdateProvider (or the process initially failed on it and did not go further).
If listed cmdlets are deprecated, removed or renamed, and thus have no articles, there also should be some way to clear them and their help from my computer in centralised fashion.

**Comment by sdwheeler** [comment]
Duplicate of #6307
