### ISSUE TITLE
Add a note that Powershell needs to be manually enabled on Windows Server 2008 R2 Core edition

### ISSUE THREAD

**Issue by onekz** [MicrosoftDocs/PowerShell-Docs#6314]
Hello,

The current version of the page says the following:
> `In all Core editions, when you log to the server you get a Windows command prompt window.
Type powershell and press ENTER to start PowerShell inside the command prompt session.`

This is not entirely true, as on Windows Server 2008 R2 SP1 Core you need to enable Powershell via sconfig before it can be used (sconfig.cmd -> 4) Configure Remote Management -> 2) Enable Windows PowerShell -> reboot). Would be great if you can add this note.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67872723-9d70-6dd3-29fb-a66505cb98fb
* Version Independent ID: 7bb17de5-a42e-21ad-fac0-2ee40722b30c
* Content: [Installing Windows PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/windows-powershell/install/Installing-Windows-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/windows-powershell/install/Installing-Windows-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
While you are correct, Windows Server 2008 R2 is no longer supported.
