### ISSUE TITLE
Feature Request Add property startname

### ISSUE THREAD

**Issue by leifdavisson** [MicrosoftDocs/PowerShell-Docs#6324]
Can we add all the attrib/properties of services to the get-services?  I need to get startname but have to use WMIObject to get that info. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f066f0-a853-8a3a-fd53-269b52d8263a
* Version Independent ID: 52b4131a-0ccb-3942-1b13-7b57faf329d5
* Content: [Get-Service (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hi @leifdavisson, i think you are wanting to make a feature request [here](https://github.com/PowerShell/PowerShell/issues/new/choose). 

I'm closing this for now but if you have more feedback, feel free to respond and we'll take another look.
