### ISSUE TITLE
Different behavior of stderr redirection based on ErrorActionPreference is not described

### ISSUE THREAD

**Issue by INRIX-Mark-Gershaft** [MicrosoftDocs/PowerShell-Docs#6326]
It seems that redirecting error stream may be affected by ErrorActionPreference value.  I.e. when ErrorActionPreference is 'Stop' 2>&1 or 2>file appear to produce nothing (0 bytes), but when ErrorActionPreference is 'Continue' redirection works as described in the article.

It would be helpful to add this caveat to documentation as it can cause confusion when redirection does not appear to be working as documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1512081-65ba-8e37-47bd-ea658e21f984
* Version Independent ID: 2d6a2602-4480-d4d2-d63d-739c4d93e4b1
* Content: [about_Redirection - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-5.1&redirectedfrom=MSDN)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Here is a test.ps1 script.

```powershell
$ErrorActionPreference = 'Continue'
$ErrorActionPreference > log.txt
get-item /not-here 2>&1 >> log.txt

$ErrorActionPreference = 'SilentlyContinue'
$ErrorActionPreference >> log.txt
get-item /not-here 2>&1 >> log.txt

$ErrorActionPreference = 'Stop'
$ErrorActionPreference >> log.txt
Try {
    get-item /not-here 2>&1 >> log.txt
}
catch {
    'catch' >> log.txt
}
$ErrorActionPreference = 'Ignore'
$ErrorActionPreference >> log.txt
get-item /not-here 2>&1 >> log.txt

$ErrorActionPreference = 'Inquire'
$ErrorActionPreference >> log.txt
get-item /not-here 2>&1 >> log.txt

$ErrorActionPreference = 'Continue'
```

Here is the output

```
PS C:\temp> gc .\log.txt
Continue

Get-Item: C:\temp\test.ps1:2
Line |
   2 |  get-item /not-here 2>&1 >> log.txt
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\not-here' because it does not exist.

SilentlyContinue
Stop
catch
Ignore
Inquire

Get-Item: C:\temp\test.ps1:22
Line |
  22 |  get-item /not-here 2>&1 >> log.txt
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\not-here' because it does not exist.
```

The results from `Inquire` can vary depending on how you answer the question.

**Comment by INRIX-Mark-Gershaft** [comment]
Great example! It should be in the article IMHO.  Article has quite an extensive information about redirection, yet it all depends on ErrorActionPreference.  Not mentioning it leads to confusion why actual behavior is different.
