### ISSUE TITLE
The powershell source can‘t download

### ISSUE THREAD

**Issue by XuHeng1021** [MicrosoftDocs/PowerShell-Docs#6332]
[Enter feedback here]

I want to update my PowerShell2.0 on my computer.So I found the source on the guthub.But the source is not aviliable.I'm in china chengdu.I do holp you to deal with this problem.Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @XuHeng1021, What Operating system are you using?

**Comment by XuHeng1021** [comment]
windows 10

**Comment by chasewilson** [comment]
You should be able to download this one and install

[Download Link](https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x64.msi)

**Comment by XuHeng1021** [comment]
I can't download the source，but I think it's not my operating system cause that.

**Comment by XuHeng1021** [comment]
And it's unavilable too.

**Comment by XuHeng1021** [comment]
I'm go crazy.

**Comment by chasewilson** [comment]
if you are on a non personal network, that might prevent unauthorized downloads? I can't replicate the issue and it's not a widespread issue. I'll be closing the issue as there is nothing wrong with the documentation. I'll still be responding to you hear though to try and help resolve if possible or at least point to where you can find some help.

**Comment by XuHeng1021** [comment]
If you come to china and you can find many people is facing the same issue.You can BaiDu "github下载不了" or “github下载一个软件居然要几十天”.Not only the source of powershell can't download,but also many other source.But this editor isn't able to send picture or I'll let you know we are facing many issues about github.

**Comment by XuHeng1021** [comment]
You can't find the problem,it dosen't mean that problem dosen't exist.
