### ISSUE TITLE
I can't download this source.I am in China ChengDu.

### ISSUE THREAD

**Issue by XuHeng1021** [MicrosoftDocs/PowerShell-Docs#6336]
[Enter feedback here]
I can't download this source. My web browser tell I need more than 3 days to download this source. But just 30 minutes later ,the web browser tells me mission failed. I have tried more than 15 times, but never success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
We have employees that work in China that have no problem downloading the PowerShell installation packages. This is not a documentation issue. If you have problems with the PowerShell product please file an issue at https://aka.ms/psfeedback. However, we cannot control what content is being blocked in China for your network connection.
