### ISSUE TITLE
HELP ABOUT_EXIT not found

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/PowerShell-Docs#6347]
# Documentation Issue

There is no separate help file for EXIT keyword.
## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [X] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

Proposition 1. `EXIT` is a language statement.
```powershell
HELP about_Language_Keywords -S
```

> `Exit`           Described in this topic

Proposition 2:  Language statements merit separate help articles about them.
```powershell
HELP ABOUT_RESERVED -S
```

> For more information about language statements, including `Foreach`, `If`, `For`,
and `While`, type "`Get-help`", type the prefix "`about_`", and then type the
name of the statement.

Corollary: A help page about `EXIT` should be available.

Refutation:
```powershell
HELP ABOUT_EXIT -S
```

> Get-Help could not find ABOUT_EXIT in a help file in this session.

**Comment by sdwheeler** [comment]
Not every language keyword merits its own article. The `exit` statement is documented in about_Language_Keywords. There is nothing more to say about it. The other keywords that have about_ articles are more complex and merit a separate article.

**Comment by yecril71pl** [comment]
That means that Proposition 2 is wrong, and the documentation about language keywords is wrong accordingly.

**Comment by yecril71pl** [comment]
This issue is aggravated by the fact that the result of `HELP EXIT` is irrelevant and you need to command `HELP EXIT -CATEGORY:HELPFILE` to get some information after waiting for the whole text search to finish, and then you have to guess.  You should really try it.

**Comment by yecril71pl** [comment]
Well, thanks for adding the note.  The UX that results from following the instruction remains terrible though.  Maybe it would be better if we could search by indexed keywords and then not every article containing `EXIT` anywhere would have it in the keywords.

**Comment by sdwheeler** [comment]
Agreed. May be worth a feature request in the source repo.

**Comment by yecril71pl** [comment]
https://github.com/PowerShell/PowerShell/issues/13271#issue-665362125
