### ISSUE TITLE
 adding example

### ISSUE THREAD

**Issue by svarog-be** [MicrosoftDocs/PowerShell-Docs#6363]
add manifest creation for an existing module with a parameter RootModule
from the documentation it seems that this is an optional parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a858807b-12a1-d252-d411-1542d6c60773
* Version Independent ID: ade5a7a7-929d-065a-f448-b6afe3750be2
* Content: [Import-Module (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Import-Module.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Creating module manifests is documented here: https://docs.microsoft.com/powershell/module/Microsoft.PowerShell.Core/New-ModuleManifest.

**Comment by svarog-be** [comment]
I made a mistake in the link. in New-ModuleManifest it would be nice to add what I wrote about.

**Comment by sdwheeler** [comment]
The **RootModule** value is only necessary when:
- You have nested modules OR
- The name of the PSM1 file does not match the name of the module OR
- The module is not a PSM1 file (could be a DLL or CDXML file)
