### ISSUE TITLE
ConvertFrom-SecureString : A parameter cannot be found that matches parameter name 'AsPlainText'

### ISSUE THREAD

**Issue by beowulf005** [MicrosoftDocs/PowerShell-Docs#6367]
The Code in Example 4 as written has two issues. 
1. ConvertTo-SecureString : The system cannot protect plain text input. To suppress this warning and convert the plain text to a SecureString, reissue the command specifying the Force parameter. For more information ,type: get-help ConvertTo-SecureString.

2. ConvertFrom-SecureString : A parameter cannot be found that matches parameter name 'AsPlainText'.

Reason for this post it seems like the parameter AsPlainText has been deprecated. Updated system to latest ver of PowerShell and still do not have the AsPlainText option. I would not be surprised that from a security stance that it was removed but this is causing issues with other documentation on this site. 

Can it be confirmed that the parameter has been deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e07f536-5137-2fb3-eeae-263316c46d25
* Version Independent ID: 7583c631-cc38-01b0-e4b1-1f6b7d3ef54d
* Content: [ConvertFrom-SecureString (Microsoft.PowerShell.Security) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertfrom-securestring?view=powershell-7&source=docs)
* Content Source: [reference/7.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md)
* Product: **powershell**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by sdwheeler** [comment]
The `-AsPlainText` parameter was added in PowerShell 7.0. It is not available in any prior version.
