### ISSUE TITLE
typo for path provided to set profiles

### ISSUE THREAD

**Issue by hobbes188** [MicrosoftDocs/PowerShell-Docs#6379]
Hi,

The page is referencing some path that are not accurate (anymore ?) :
**PowerShell** folder references should be replaced by **WindowsPowerShell** in various path listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f16e6db-f237-8271-e158-50038a662a67
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about_Profiles - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The article is accurate for the version you were viewing. You were viewing the v7.0 documentation. The **WindowsPowerShell** folder changed to **PowerShell** in version 6.
