### ISSUE TITLE
Potential issue with help flag

### ISSUE THREAD

**Issue by WilldotNET** [MicrosoftDocs/PowerShell-Docs#6383]
Hi - Total newbie to Powershell here, so be patient.

I've just read " Since PowerShell automatically parses and processes the command line, the -? parameter always means "show me Help for this command".

So, this works out fine for say (random command) -- 

>Get-AdlAnalyticsComputePolicy -?

But for say az rest (again another random pick)

>az rest -h 
works, but
>az rest -?
doesn't

Probably an issue with me, but wondered if the doc was still correct?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b770965-4cc8-203e-5332-26bb9ee99220
* Version Independent ID: 1ac2554b-bf6a-2da6-3708-2d63af435e1e
* Content: [What is PowerShell? - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7)
* Content Source: [reference/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/overview.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
`-?` works for all PowerShell cmdlets. But when you run a non-PowerShell command (native EXE, non-PS script, etc.) the command-line options are passed to command for processing. The `az` command does not support `-?`.
