### ISSUE TITLE
Explanation on how to understand the syntax

### ISSUE THREAD

**Issue by Srigan1986** [MicrosoftDocs/PowerShell-Docs#6384]
A crosslink on how to read the documentation is needed for whoever who starts with a new programming/scripting language.
Powershell has a lot of self explanatory commandlets. When I read the commandlets, the first thing I try to decipher is a way to read the syntax of the commandlets ---understand the arguments with different overloads.

So this should explained in the section " How to use this documentation" and not stacked somewhere below as Appendix

https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/appendix-a?view=powershell-7

Atleast a crosslink on the related topics should be shown on the side.

Thank you
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe6956d-5391-1174-d4de-ba0e251da152
* Version Independent ID: c71a824d-0d60-dcbd-e18d-9798966f37a8
* Content: [How to use the PowerShell documentation - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/how-to-use-docs?view=powershell-7)
* Content Source: [reference/docs-conceptual/how-to-use-docs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/how-to-use-docs.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The article you want is https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_command_syntax
