### ISSUE TITLE
In place upgrade instructions

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/PowerShell-Docs#6405]
It would really, really help if there were instructions on the repository landing page for how to upgrade Powershell from within a terminal window (e.g., Windows Terminal) rather than having to download an installer package and install it.

Searches for how to do that online are currently swamped by "how to upgrade to Powershell 7", which was such a big change that it couldn't (as I recall) be done "in place" within a Powershell window.

**Comment by chasewilson** [comment]
Hi @markolbert, thanks for the feedback. Do you mean the PowerShell/PowerShell repository landing page?

**Comment by markolbert** [comment]
Yes. I should’ve been clearer about that. Since one can upgrade in place from within a shell it would be helpful for the directions on how to do that be near the other ways of updating.

Sent from my iPad

On Aug 2, 2020, at 1:42 PM, Chase Wilson <notifications@github.com> wrote:

﻿

Hi @markolbert<https://github.com/markolbert>, thanks for the feedback. Do you mean the PowerShell/PowerShell repository landing page?

**Comment by chasewilson** [comment]
We don't manage the documentation directly in the source page. You can [submit an issue](https://github.com/PowerShell/PowerShell/issues/new/choose) with them there to request a change. We have the commands to install from a terminal on the appropriate pages within the docs So I will be closing this issue for now. If there is more to add feel free to respond here or create a new issue and we'll go from there.
