### ISSUE TITLE
Import manifest with nested modules in devops pipelines

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/PowerShell-Docs#6415]
[Enter feedback here]

Hello,

I have created a manifest file that is using **nested modules**. I want to use this module in my yaml pipeline, so I am copying all the files to agent destination folder. In another task I'm listing items in this folder to check if all is copied correctly.

In next task I'm trying to Import this module, this operation fails. It is weird because the first command outputs the manifest information but I can't import it.
```
  - pwsh: |
        Get-Module -name moduleName -ListAvailable
        Import-Module moduleName
        Get-Module -name moduleName
```
Here are logs from this error:
```
2020-08-03T09:31:57.8095095Z Generating script.
2020-08-03T09:31:57.8100407Z ========================== Starting Command Output ===========================
2020-08-03T09:31:57.8130132Z [command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/9f4ea4b6-b581-4730-a0bb-8a00b72ea3ad.ps1'
2020-08-03T09:31:58.4687148Z 
2020-08-03T09:31:58.4687451Z 
2020-08-03T09:31:58.4687846Z     Directory: /home/vsts/.local/share/powershell/Modules
2020-08-03T09:31:58.4688029Z 
2020-08-03T09:31:58.4688252Z ModuleType Version    PreRelease Name                                PSEdition
2020-08-03T09:31:58.4689250Z ---------- -------    ---------- ----                                ---------
2020-08-03T09:31:58.4689599Z Manifest   1.0.0                 moduleName                            Desk     
2020-08-03T09:31:58.7450220Z [91mImport-Module: [0m/home/vsts/work/_temp/9f4ea4b6-b581-4730-a0bb-8a00b72ea3ad.ps1:3
2020-08-03T09:31:58.7451804Z [96mLine |
2020-08-03T09:31:58.7452489Z [96m   3 | [0m [96mImport-Module moduleName[0m
2020-08-03T09:31:58.7453103Z [96m     | [91m ~~~~~~~~~~~~~~~~
2020-08-03T09:31:58.7454244Z [91m[96m     | [91mThe given assembly name or codebase was invalid. (0x80131047)
2020-08-03T09:31:58.7454655Z [0m
2020-08-03T09:31:58.7548467Z 
2020-08-03T09:31:58.7621249Z ##[error]PowerShell exited with code '1'.
```

Interesting fact is that when I want to import a module, that is connected to only one root module, it works great. But with above case, when there are several nested modules, it fails.

Hope there is an answer for that 👍
Let me know if you need any more information from me.
Rafal
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b6d5a3-7072-d3fe-ed97-472df9b0e925
* Version Independent ID: 4ab75a2c-831e-37c5-d98d-873874d2ec47
* Content: [Installing a PowerShell Module - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/module/installing-a-powershell-module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/module/installing-a-powershell-module.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@roofiq The module you listed is in `/home/vsts/.local/share/powershell/Modules` but the module you are trying to import is in `/home/vsts/work/_temp`.

**Comment by roofiq** [comment]
Thanks for answer @sdwheeler. 
My folder that I have copied to one of the environment paths looks like this:
```
- ModuleName
  -ModuleName.psd1
  -Module2
     -Module2.psm1
     -Module2.psd1
  -Module3
      -Module3.psm1
      -Module3.psd1
```
ModuleName has NestedModules defined that consist of Module2 and Module3.

Below I'm importing one of the sub modules, which works good:
```
  - pwsh: |
        Get-Module -name ModuleName.Module2 -ListAvailable
        Import-Module $(modulepath)/Module2
```
Taks output:
```
Generating script.
========================== Starting Command Output ===========================
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/b4866971-7c16-4ea4-a74b-efee866b416f.ps1'

ModuleType Version    PreRelease Name                                ExportedCo
                                                                     mmands
---------- -------    ---------- ----                                ----------
Script     1.0                   Module2                          {Get-SoSt…
```

But when I'm doing same operation but for my main module (ModuleName) it throws this error:
```
Generating script.
========================== Starting Command Output ===========================
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/78f57756-612b-4010-85ab-70be88b11171.ps1'


    Directory: /home/vsts/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Manifest   1.0.0                 SO                                  Desk     
Import-Module: /home/vsts/work/_temp/78f57756-612b-4010-85ab-70be88b11171.ps1:3
Line |
   3 |  Import-Module /home/vsts/.local/share/powershell/Modules/SO
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The given assembly name or codebase was invalid. (0x80131047)
```
Indeed it looks like it's trying to import it from different directory. But then why it works in the first example?
Do you have any advice on how can I solve this issue?

**Comment by sdwheeler** [comment]
This is a DevOps pipeline issue, not a PowerShell issue. I don't know how to help you with that. Have you checked the documentation for Azure DevOps? https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops
