### ISSUE TITLE
Please clarify the platform-specific constraints on the use of -OutputType

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6417]
It seems that using `-OutputType` to intentionally create persistent assemblies only works on _Windows_ at the moment and there only in _Windows PowerShell_ - at least when it comes to `-OutputType ConsoleApplication` - not sure about `-OutputType Library` (whereas `-OutputType WindowsApplication` is self-evidently Windows-only).

Please clarify in the topic which combinations are supported in PowerShell _Core_ and on non-Windows platforms, if any.

(If it turns out that only Windows PowerShell is supported, we should look into modifying / extending `Add-Type` accordingly.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90513733-758f-faf3-b117-3fbfc4e065ab
* Version Independent ID: b550e1f5-2481-7908-1d62-607923d09a2b
* Content: [Add-Type (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-7.1&WT.mc_id=ps-gethelp)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Add-Type.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Add-Type.md)
* Product: **powershell**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
This sounds like a product bug. Waiting on the product team to respond before deciding on the documentation changes.

**Comment by daxian-dbw** [comment]
I don't think ConsoleApplication and WindowsApplication curentlly work in PowerShell 7. And I doubt if they actually work in .NET Core. They both can produce an executable on Windows, neither works when running the executable.

For 'ConsoleApplication':

```
PS> Add-Type -TypeDefinition 'public class Foo { public static void Main() { System.Console.WriteLine("Hello World!"); } }' -OutputAssembly c:\blah.exe -OutputType ConsoleApplication
PS> C:\blah.exe
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

For 'WindowsApplication':

```
PS> Add-Type -TypeDefinition 'public class Foo { public static void Main() { System.IO.File.Create(@"C:\arena\tmp\daxian"); } }' -OutputAssembly c:\zoo.exe -OutputType WindowsApplication
PS> C:\zoo.exe
PS> Test-Path C:\arena\tmp\daxian
False
```
@mklement0 Are you able to successfully use `-OutputType` with either `ConsoleApplication` or `WindowsApplication`?

**Comment by mklement0** [comment]
@daxian-dbw, I've only tried with `ConsoleApplication` - please see https://github.com/PowerShell/PowerShell/issues/13344

We need to understand what _should_ work in PS Core  - and make that work - and for what _cannot be expected to work_ we need to (a) document the limitation and (b) make `Add-Type` error out _before_ producing a broken binary.

**Comment by sdwheeler** [comment]
Tested this on v6.2.7 and got the same results.

**Comment by sdwheeler** [comment]
The behavior was changed in Powershell/PowerShell#13430

**Comment by mklement0** [comment]
@sdwheeler, I think you meant to link to https://github.com/PowerShell/PowerShell/pull/13440

**Comment by sdwheeler** [comment]
Docs updated
