### ISSUE TITLE
about_CommonParameters link in cmdlets help

### ISSUE THREAD

**Issue by sethvs** [MicrosoftDocs/PowerShell-Docs#6429]
# Documentation Issue
@sdwheeler 
In #6420 you mentioned that the fwlink for `about_CommonParameters.md` is enforced by PlatyPS https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6420#discussion_r464630366
But for many cmdlets there are relative link `../Microsoft.PowerShell.Core/About/about_CommonParameters.md`
For example, in `New-CimInstance.md` https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/CimCmdlets/New-CimInstance.md

What the PlatyPS enforcement is and should we bring the link to consistency in different files?

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Version 7.1 preview content
- [x] Version 7.0 content
- [x] Version 6 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No

**Comment by sdwheeler** [comment]
At one time we attempted to change the link for about_CommonParameters to be a relative link, like `../Microsoft.PowerShell.Core/About/about_CommonParameters.md`. However, PlatyPS changes it back to the FWLink markdown when we run it to update. Both are valid. But, since PlatyPS changes it back to the FWLink, we have standardized on using that link.

**Comment by sethvs** [comment]
Thanks.
