### ISSUE TITLE
Need for download PDF offline

### ISSUE THREAD

**Issue by rekaerst** [MicrosoftDocs/PowerShell-Docs#6445]
We need this feature because some of us have very limited internet access or work offline and an offline PDF which usually offered by other MSDocs (e.g. [Download PDF](https://docs.microsoft.com/en-us/dotnet/opbuildpdf/csharp/toc.pdf?branch=live) at CSharp Docs). This could be very helpful.

Thanks

**Comment by sdwheeler** [comment]
The PDF feature is not supported for PowerShell reference content. 
Duplicate of #6283
