### ISSUE TITLE
4-digit millisecond

### ISSUE THREAD

**Issue by GlenAppleton** [MicrosoftDocs/PowerShell-Docs#6453]
The following phrase is present twice on the document for the PowerShell Get-Date function, which is incorrect given the maximum digits for millisecond parameter is three:

Phrase: "4-digit millisecond"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27f0aaa-16e3-ad1c-6610-facb952cc0ab
* Version Independent ID: 09bab64d-b131-3961-a8c2-10ecf7f3d96b
* Content: [Get-Date (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hi @GlenAppleton thank you for the feedback! 

In this case, it isn't using the **MIllisecond** parameter. While the parameter is based in limited to three digits to represent milliseconds, when using the **Format** parameter, you aren't limited to three digits. You can choose to use to use as little as one character to represent milliseconds (`HHmmssf`) to as many as seven (`HHmmssfffffff`). 

Please let me know if you have any questions or more feedback. For now, I will be closing the issue. However, if you feel changes should be made, feel free to respond here and I'll be keeping an eye on it and will reopen if necessary. 

Thanks again and have a great weekend!

**Comment by GlenAppleton** [comment]
Yep, looks like I took that phrase out of context while searching for the parameter example.  There is a use case for providing an example using the -Millisecond parameter for a date range, so I'll submit a PR for your consideration.  Thanks for the quick response!
