### ISSUE TITLE
Language keywords should be wrapped in backtick characters

### ISSUE THREAD

**Issue by xtqqczze** [MicrosoftDocs/PowerShell-Docs#6458]
# Documentation Issue

Not all PowerShell language keywords are wrapped in backtick characters, in violation of the [PowerShell-Docs style guide](https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide#formatting-command-syntax-elements):

> Language keywords, cmdlet names, functions, variables, native EXEs, file paths, and inline syntax examples should be wrapped in backtick (`) characters.

**Additional question**: PowerShell language keywords are written in lowercase (including foreach and dynamicparam)<sup>[1](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style-Guide/Code-Layout-and-Formatting.md#capitalization-conventions)</sup> but casing is not consistent in documentation. For example see [#6305](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6305/files), where casing is a mixture of `if` and `If`.

## Context of the issue

Follow-up to #6305.

**Comment by sdwheeler** [comment]
@xtqqczze Thanks for this issue, but it is too general. The style guide has evolved over time. So there is a lot of existing content that needs to be addressed. We fix articles as we work on them. 

When you see an article that needs a style edit you can submit an issue for that article or a PR to fix it (as you have done previously).
