### ISSUE TITLE
Variable renaming from "response" to "Response"

### ISSUE THREAD

**Issue by kesadae11** [MicrosoftDocs/PowerShell-Docs#6460]
In the example 7 the code contains ```$response``` in lowercase for first time, but the second time when you use it it looks like ```$StatusCode = $Response.StatusCode```. By the way it's works, but a little bit inconsistent. 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7#example-7--catch-non-success-messages-from-invoke-webrequest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a904dd-01ea-76c7-9e65-902c8e5ffd41
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
PowerShell is not case-sensitive, but consistency would be clearer.
