### ISSUE TITLE
Common parameters formatting

### ISSUE THREAD

**Issue by sethvs** [MicrosoftDocs/PowerShell-Docs#6462]
# Documentation Issue

In most help files the **Common Parameters** section is like this:
```
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
-InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose,
-WarningAction, and -WarningVariable. For more information, see
[about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```
but in `Set-Location` it is:
```
This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`,
`-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`,
`-Verbose`, `-WarningAction`, and `-WarningVariable`. For more information, see [about_CommonParameters](../Microsoft.PowerShell.Core/About/about_CommonParameters.md).
```
Although it is stated in **PowerShell-Docs style guide** that parameters with dash should be enclosed in backticks

>When referring to a parameter by name, the name should be bold. When illustrating the use of a parameter with the hyphen prefix, the parameter should be wrapped in backticks. For example:

>The parameter's name is **Name**, but it is typed as `-Name` when used on the command
>line as a parameter.

I believe that **Common parameters** is a special case.

Should we bring it to the common format?

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Version 7.1 preview content
- [x] Version 7.0 content
- [x] Version 6 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No

**Comment by sdwheeler** [comment]
Common Parameters is a special case. The formatting of it is hard-code in PlatyPS. Any change to that section gets overwritten by PlatyPS when you run `Update-MarkdownHelp`. So we are going to keep the hard-coded format but wrap it to fit in 100 columns:

```
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
-InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose,
-WarningAction, and -WarningVariable. For more information, see
[about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

**Comment by sethvs** [comment]
Thanks.
