### ISSUE TITLE
Clarify what "PackageManagement Preview" means, add the missing Save-Module PackageManagement command

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6464]
> Computers with the PackageManagement Preview installed

I suggest explaining what "PackageManagement Preview" is, especially given that it refers to a download that is no longer available, from what I can tell (used to be at https://www.microsoft.com/en-us/download/details.aspx?id=51451)

I suggest telling users to run `Get-Command Save-Module` to test if the preview is installed.

Also, the instructions for the machines _with_ the preview are missing a _second_ `Save-Module` command, given that the subsequent instructions presume that _both_ `PowerShellGet` and `PackageManagement` were downloaded:

```powershell
Save-Module -Name PackageManagement -Path C:\LocalFolder -Repository PSGallery
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
After reviewing this article, no changes are necessary. `Save-Module` downloads both the PowerShellGet and is dependency (PackageManagement) with the one command. The article does not link to the non-existent download. The purpose of this article is to provide instructions for users that may have an old system that had installed the PackageManagement preview.
