### ISSUE TITLE
Clarify what "PackageManagement Preview" means, make it clear that Save-Module PowerShellGet also downloads its dependency, PackageManagement

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6469]
Follow-up to https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6464#issuecomment-671655872:

> `Save-Module` downloads both the `PowerShellGet` and is dependency (`PackageManagement`) with the one command.

That's good to know. Now _you and I_ know - but I suspect few other people who are likely to read the instructions _first_, before trying them (as was the case for me).

If something is likely to raise a question in the reader's mind, it's best to address it - rather than relying on their unquestioning following of the instructions provided.

> The article does not link to the non-existent download.

All the more reason to explain _what the term refers to_ and _how to determine whether the component is present_.

If you come to this article as someone who has to maintain legacy systems while having no awareness of once-available, obsolete downloads, confusion will ensue.

**Comment by sdwheeler** [comment]
You either have the Preview installed or you don't. The article includes instructions for either scenario. That is all you need to know. The versions of PowerShell and Windows documented here are not really supported anymore. If you feel it is important enough to change you could submit a PR.

**Comment by mklement0** [comment]
Please see #6485.
