### ISSUE TITLE
Update docs related to DscClassCache and MOF->JSON transition for DSC resources

### ISSUE THREAD

**Issue by anmenaga** [MicrosoftDocs/PowerShell-Docs#6470]
Most of this should be covered by DSC documentation;
However PS Core exposes several public APIs whose behavior was changed; need to make sure it is up-to-date.
For example this one.
Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache class
https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.desiredstateconfiguration.internal.dscclasscache?view=powershellsdk-7.0.0

However this looks like auto-generated from XML comments in source code.

**Comment by sdwheeler** [comment]
@anmenaga You are correct. The .NET API docs are generated from the comments in the source code. So those comments need to be updated in the source. So this issue belongs in the source repo.

The API docs get auto-generated when we release the new version of PowerShell.
