### ISSUE TITLE
DeleteKey seams sufficient 

### ISSUE THREAD

**Issue by baannee** [MicrosoftDocs/PowerShell-Docs#6471]
[Enter feedback here]

I try this and it can't find DeleteKey. I successfully remove an expired certificate after removing this key.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 422db22d-198d-d6fe-1ad7-a2fb1af056b8
* Version Independent ID: 7e4fded2-df3e-5ae4-f5c3-ab6d8aaff537
* Content: [Certificate Provider - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by chasewilson** [comment]
Hi @baannee thank you for the feedback. Would you mind clarifying what you think should be updated in the doc?

**Comment by chasewilson** [comment]
I'm closing this issue for now, feel free to respond with more information and I will review.

**Comment by baannee** [comment]
`$expired = Get-ChildItem cert:\LocalMachine\WebHosting -ExpiringInDays 0
$expired | Remove-Item **-DeleteKey**`

To remove DeleteKey. It doesn't work in PS 5.1. You may test it on your side.
