### ISSUE TITLE
New Tls13 value in WebSslProtocol

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#6481]
# Documentation Issue

After https://github.com/PowerShell/PowerShell/pull/13409 WebSslProtocol type gets new 'Tls13' value in PowerShell 7.1.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- List of articles that need to be updated:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.websslprotocol?view=powershellsdk-7.0.0
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7

- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by NAYWIN890** [comment]
IT policies,contact,hour and support location current job openings Admin login , power by open scholar.

**Comment by NAYWIN890** [comment]
IT policy contact hour , and support location current job openings Admin longin powered by openschol ar[![Uploading 90002443...]]()

**Comment by NAYWIN890** [comment]
[![Uploading 90002503...]]()

**Comment by NAYWIN890** [comment]
#It policies, contact hour and support location current job openings openings Admin lounging power buy openscholar![Uploading 90002752...]

**Comment by iSazonov** [comment]
The PR was merged.

Tls 1.3 support is based on underlying OS support. Currently all OS-s have limited Tls 1.3 support.
