### ISSUE TITLE
InputObject parameter is not accessible as $input within the script block. 

### ISSUE THREAD

**Issue by pdhimate** [MicrosoftDocs/PowerShell-Docs#6488]
When I try to access a property e.g. $input.MyRESTUrl inside the script block, I get null.

This is what I am basically trying to do within a function app:
```

Write-Output "Invoke a fire and forget REST request"
Start-ThreadJob -InputObject $MyRESTInputObject -ScriptBlock {
    Invoke-RestMethod -Method Post -Body $input.MyRESTBody -Uri $input.MyRESTUrl -ContentType 'application/json'
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af8c69f6-1775-af37-b7cd-00bfbc17fca7
* Version Independent ID: a3c2b715-deae-5d13-5eb6-315cdf19e2b4
* Content: [Start-ThreadJob (ThreadJob) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/threadjob/start-threadjob?view=powershell-7)
* Content Source: [reference/7.0/ThreadJob/Start-ThreadJob.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/ThreadJob/Start-ThreadJob.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @PaulHigin
* Microsoft Alias: **paulhi**

**Comment by sdwheeler** [comment]
This works for general objects. Have you verified your input?

Run the following code to verify that you are getting the object you expect.

```
$job = Start-ThreadJob -InputObject $MyRESTInputObject -ScriptBlock {
    $input | Get-Member
}
$job | Receive-Job
```

**Comment by sdwheeler** [comment]
This other issue is that you are using `$input` more than once. Once it is used it cannot be used again because it is an enumerator type. Try this:

```
Write-Output "Invoke a fire and forget REST request"
Start-ThreadJob -InputObject $MyRESTInputObject -ScriptBlock {
    $restObject = $input.
    Invoke-RestMethod -Method Post -Body $restObject.MyRESTBody -Uri $restObject.MyRESTUrl -ContentType 'application/json'
}
```

**Comment by pdhimate** [comment]
@sdwheeler I've already tried that, the Uri and Body still remain null. For now I have used this work around: https://stackoverflow.com/questions/63376930/azure-data-factorys-web-hook-activity-times-out-after-1-minute/63388120#63388120
