### ISSUE TITLE
This page refers to -Properties and -Parameter arguments which are not valid and do not exist in PS 5.1

### ISSUE THREAD

**Issue by ssolomon** [MicrosoftDocs/PowerShell-Docs#6489]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51a14cf-e9db-6463-141c-2e6498e4e527
* Version Independent ID: a23755f9-7ded-991a-9675-57d3beb268ec
* Content: [Everything you wanted to know about hashtables - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This article is not meant to be version specific. Unfortunately the version picker only applies to the cmdlet reference and about_* topics.
