### ISSUE TITLE
Update PSReadline documentation for new color options.

### ISSUE THREAD

**Issue by MartinGC94** [MicrosoftDocs/PowerShell-Docs#6493]
# Summary of the new document or enhancement

- List of articles that need to be updated:
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PSReadLine/Set-PSReadLineOption.md
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PSReadLine/Get-PSReadLineOption.md
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo:
https://github.com/PowerShell/PSReadLine/pull/1724
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed
Set-PSReadLineOption.md:
Add the 3 new valid color keys

Get-PSReadLineOption.md:
Update the example output to show the new colors.

**Comment by sdwheeler** [comment]
Linked PR over a year old. We can reopen this issue if the PR ever gets merged.
