### ISSUE TITLE
Change `Add-Type -OutputType` to not support `ConsoleApplication` and `WindowsApplication`

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#6499]
# Summary of the new document or enhancement

- List of articles that need to be updated: The help content for `Add-Type`.
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/13440
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/issues/13344

## Description of what changed

This is related to #6417

The output assembly type `ConsoleApplication` and `WindowsApplication` doesn't work with `Add-Type -OutputType` today.
Per the conclusion of the powershell committee, this PR changes `Add-Type -OutputType` to throw terminating error when either `ConsoleApplication` or `WindowsApplication` is used.

**Comment by chasewilson** [comment]
@daxian-dbw It seems as iff in PowerShell 6 and 7 docs, the user should be warned that it won't produce a working output and PowerSHell 7.1 will write a warning? 

Please correct me if I'm wrong. Thanks!

**Comment by daxian-dbw** [comment]
@chasewilson Yes, that sounds correct. Thanks for updating the doc!
