### ISSUE TITLE
Add check for ubuntu version

### ISSUE THREAD

**Issue by awf** [MicrosoftDocs/PowerShell-Docs#6502]
As following the ubuntu 16.04 instructions on ubuntu 18 causes an error which leads to an old and grumpy thread (https://github.com/PowerShell/PowerShell/issues/8008), add a version check at the start of the install script

```
# Add this line
grep 'Ubuntu 16.04' /etc/issue || ( echo "WARNING: Not on ubuntu 16.04" ; sleep 365d )

# Download the Microsoft repository GPG keys
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
I can see the merrit here, and reading that thread was quite a way to start the week lol, but I would also say we have the information pretty clear on the docs. It's under the specific header with all instructions clarifying the versions. 

As well as that only coming in at the very last of the thread and corrected by just letting the user know they had made a mistake in the version.

**Comment by awf** [comment]
I know, but I also skim-read the instructions, and didn't notice the version number...  I agree that the extra check makes the script more verbose, but it's not super clear how big a downside that is.

**Comment by sdwheeler** [comment]
The instructions are correct as they are written. If the instruction were a script, it would be a good thing to add a check. But since they are manual steps, it is the user's responsibility to know what they are doing.
