### ISSUE TITLE
More information on ConvertFrom-Json and comments

### ISSUE THREAD

**Issue by Dirk-Manderin** [MicrosoftDocs/PowerShell-Docs#6503]
Could we please get more information regarding this statement - "Beginning with PowerShell 6, this cmdlet supports JSON with comments."?  Specifically around the syntax PowerShell considers a comment, and possibly an example?  I know there are a few different methods for for JSON comments.  # and _comment come to mind.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 951e77ee-6cb8-0722-f9dd-58aee6346b0e
* Version Independent ID: 28f7f22d-c3a6-ea62-c77b-672d7e16fc80
* Content: [ConvertFrom-Json (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
This is confusing and I had to do a bit of digging to find the correct answer. 

From what I could find, normal JSON comments are as you mentioned, typically a data attribute and can be filtered out but still exist as data by something like: `_comment`. This comment isn't referencing that. 

It may be "new" or just not common, but you can use a double foward slash (`//`) to write a comment in a JSON file (I know it is common usage in Azure Resource Manager (ARM) Templates at least). Prior to PowerShell 6, this wasn't accepted and would throw an error. In PowerShell 6 and above, the comment is ignored and only the data is in the created object

```json
{
  "Test": "PowerShell 5.1" // This would throw an error in PowerShell 5.1
  "Test2": "PowerShell 6+" // This just wouldn't show up in the object created.
}
```

I'll be updating to clarify.

**Comment by Dirk-Manderin** [comment]
Thank you.  This is exactly what I was looking for.
