### ISSUE TITLE
GitHub link is dead?

### ISSUE THREAD

**Issue by awf** [MicrosoftDocs/PowerShell-Docs#6511]
# Documentation Issue
Github page for this repo looks like this:
![image](https://user-images.githubusercontent.com/128119/90516375-cf097b00-e15b-11ea-8f69-37a8bc6247a0.png)

I believe the link bottom right should be to docs.microsoft.com/powershell

See below for current landing page in my geo

## Context of the issue

- https://github.com/MicrosoftDocs/PowerShell-Docs
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):
No, possibly locale though, I am en-gb

## Detailed description of the issue

![image](https://user-images.githubusercontent.com/128119/90516556-1263e980-e15c-11ea-8be1-36bdfc4d7d92.png)

**Comment by sdwheeler** [comment]
Fixed
