### ISSUE TITLE
Powershell for MacOS - 7.0.3 need MacOS 10.13.x (not 10.12.x)

### ISSUE THREAD

**Issue by justinianho** [MicrosoftDocs/PowerShell-Docs#6519]
Powershell for MacOS - 7.0.3 need MacOS 10.13.x (not 10.12.x)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cac030d-de88-9bf0-5ea8-7213b5d7f088
* Version Independent ID: d025a07e-05e1-ef40-5500-36d3facbcc04
* Content: [Installing PowerShell on macOS - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
@SteveL-MSFT can anyone confirm this?
