### ISSUE TITLE
Example code incorrect for 

### ISSUE THREAD

**Issue by robharman** [MicrosoftDocs/PowerShell-Docs#6521]
The code in the section Null-conditional operators ?. and ?[]  is incorrect.  Each of the $a and ${a}? should be $a? and ${a?} respectively. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273225bd-bd1f-478f-6040-098bce77920c
* Version Independent ID: 5fcd4430-a6b8-0438-73c9-29749b804323
* Content: [about_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The documentation is correct. Is this experimental feature not working for you?

**Comment by robharman** [comment]
The experimental feature works fine; my understanding of the documentation that needs to be corrected. Sorry!
