### ISSUE TITLE
Windows 1603

### ISSUE THREAD

**Issue by padlock780** [MicrosoftDocs/PowerShell-Docs#6523]
Under Client Operating System Windows 10 1603 is mentioned. I don't believe this is correct. Do you mean 1703?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9d17d-3eea-9e41-3e86-68117e1145e6
* Version Independent ID: a524e4f6-7beb-d95a-e163-edd28142c14d
* Content: [JEA Prerequisites - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/jea/prerequisites?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/remoting/jea/prerequisites.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/jea/prerequisites.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
No, 1603 is correct. It was an intermediate release.
