### ISSUE TITLE
unclear documentation

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/PowerShell-Docs#6528]
Please make it brutally clear that testscript has to return false to run the setscript.  I burnt way to much time on this.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114b8b70-1c63-21f3-9e6b-df616ef52ef5
* Version Independent ID: 1419e56e-ad6c-feae-939d-dd73e0475678
* Content: [DSC Script Resource - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/scriptresource?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @SquirrelAssassin , thanks for the feedback. 

I think that the docs make it abundantly clear is is referenced pretty strongly in both the TestScript and SetScript sections.

"TestScript is executed by DSC to determine if SetScript should be run. If TestScript returns $false, DSC executes SetScript to bring the node back to the desired state. It must return a boolean value. A result of $true indicates that the node is compliant and SetScript should not executed." - [TestScript Section](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/scriptresource?view=powershell-7#testscript)

"It is called by DSC if the TestScript script block returns $false." - [SetScript Section](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/scriptresource?view=powershell-7#setscript)

I'm going to close this for now, feel free to respond and we can go from there.
