### ISSUE TITLE
DirectoryCopy Recuse Needs to be better documented

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/PowerShell-Docs#6529]
If you do not set recurse = $true nothing from the root of the folder would be copied which is not what recursion is, recursion is from that folder down.  If you set recurse to $false only the folder will be created with nothing in the directory which is not as expected.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e51cc75-7d9e-2153-e9fa-72a4e7034b9a
* Version Independent ID: abc447b0-62e9-c402-5f40-d3ab5ee62bc2
* Content: [DSC File Resource - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/fileresource?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/reference/resources/windows/fileResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/reference/resources/windows/fileResource.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
@SquirrelAssassin  thanks for the feedback. I didn't miss your point. I understand that the property name can cause some confusion. If you looked at the PR linked above your comment, I've made changes to clarify. Thanks again and have a good one.
