### ISSUE TITLE
What type of binary should PowerShell cmdlets be in.

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/PowerShell-Docs#6540]
This tutorial dives right in with the C# code. But before this it should really cover what sort of project you would need to create. Are we creating a .dll or an .exe? Is is a console application or something else?

Also are any dependencies required? If I've installed Visual Studio is that enough? Do I need to install an SDK as well? 

I'm sure I can find answers to these questions on the internet, but I would expect it to be covered in the getting started tutorial that this page is claiming to be. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0078052e-522d-859e-7015-1ace5e3d0a17
* Version Independent ID: 0d5045ce-941b-6419-90e8-da0a5569bb63
* Content: [Creating a Cmdlet without Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/creating-a-cmdlet-without-parameters?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/cmdlet/creating-a-cmdlet-without-parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/creating-a-cmdlet-without-parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This information is covered in https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/writing-portable-modules?view=powershell-7#installing-the-powershell-standard-module-template.
