### ISSUE TITLE
RHEL 8 needs to be added as an officially supported release

### ISSUE THREAD

**Issue by msLinuxNinja** [MicrosoftDocs/PowerShell-Docs#6542]
As per https://github.com/PowerShell/PowerShell/issues/12984 PowerShell is supported on RHEL 8.

This document needs to be updated to add RHEL 8 as an officially supported release, plus the instructions needed for the install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by TravisEz13** [comment]
All steps for support aren't done.   This issue will be opened when support is ready to be documented.
