### ISSUE TITLE
Get-Date -UFormat %u Example is incomplete / misleading

### ISSUE THREAD

**Issue by Andrei-Paul** [MicrosoftDocs/PowerShell-Docs#6546]
# Documentation Issue
Example just states Monday = 1

## Context of the issue

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Version 7.1 preview content
- [x] Version 7.0 content
- [x] Version 6 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):
N

## Detailed description of the issue

Example states Monday = 1
In "my culture" weeks start with Monday.
This made me think "ok, great, so Tuesday = 2 ... Sunday = 7", when, in fact Sunday = 0.
In my opinion, this should be better documented, as weeks start with Monday (1) and end with Sunday (7) according to ISO 8601.

**Comment by chasewilson** [comment]
Hi @Andrei-Paul thanks for the feedback. 

Do you think something like this would work better? 

Numbered day of the week                                                                   1 = Monday
