### ISSUE TITLE
Document Request: `-Runspace` parameter on Debugging cmdlets is no longer Experimental

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#6560]
The Experimental Features doc needs to be updated to reflect that this feature is no longer Experimental.  The debugging cmdlets docs needs to be updated with this new parameter.

# Summary of the new document or enhancement

- List of articles that need to be updated:
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/13527
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

**Comment by chasewilson** [comment]
The PR this issue is linked to hasn't been completed. It was closed by stalebot and has not been integrated with powershell yet.

**Comment by sdwheeler** [comment]
The was fixed in https://github.com/PowerShell/PowerShell/pull/15864
