### ISSUE TITLE
location of default views

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#6562]
[Enter feedback here]

"Beginning in PowerShell 6, the default views for objects are defined in PowerShell source code."

I'm not sure this is correct.  I've had the opposite experience with get-winevent.  In powershell 5.1, the default view was defined in a dll, and couldn't be redefined in a ps1xml file, but in powershell 7, I could edit the event.format.ps1xml file and change the default view.  That file was moved to a subdirectory under $PSHOME.  https://stackoverflow.com/questions/63548555/get-winevent-changing-format-file-to-groupby-logname-has-no-effect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce7319e-0b83-dae5-6f52-290e5ff56604
* Version Independent ID: e363027f-b76b-edbb-22dc-02d5924cfcb9
* Content: [about_Format.ps1xml - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
@jszabo98 Thanks for the feedback! The original definitions are still defined in the source code as of PowerShell 6. As the article says you can create your own custom files or edit the existing ones. But the original definitions are still written in c# in the source code. 

I'll be closing this for now but watching for response if you feel like there is an update to be made.

**Comment by jszabo98** [comment]
Well the view for EventRecord for get-winevent is defined in $pshome\Modules\Microsoft.PowerShell.Diagnostics\Event.format.ps1xml.  But I can't find the view for FileInfo for get-childitem, so I guess it varies.
