### ISSUE TITLE
ISE experience in Visual Studio 2019 Professional

### ISSUE THREAD

**Issue by mikewwood** [MicrosoftDocs/PowerShell-Docs#6571]
Not finding any documentation on use PowerShell 7.x in ISE "mode" in my Visual Studio 2019 Professional (for Windows) app.  Everything points to a VS Code extension that cannot be found in the Professional Market Place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92497070-504a-7239-dce7-ba7c23426514
* Version Independent ID: eb1fa4c2-2692-df5d-691a-78551edf6abb
* Content: [How to replicate the ISE experience in Visual Studio Code - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/how-to-replicate-the-ise-experience-in-vscode?view=powershell-7)
* Content Source: [reference/docs-conceptual/dev-cross-plat/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dev-cross-plat/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Visual Studio Professional and Visual Studio Code are different products. There is no ISE mode for Visual Studio Professional, only for Visual Studio Code.
