### ISSUE TITLE
get a single item from registry

### ISSUE THREAD

**Issue by kberlin86** [MicrosoftDocs/PowerShell-Docs#6572]
The document did not show how to get exactly one entry from the registry.  An example would be: $temp = get-itemproperty -path HKCU:\environment -name path

This command returns the Path, PSPath, PSParentPath, PSChildName, PSDrive, PSProvider.  I just want the path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3287510f-90cf-5f9d-9394-79af0ac63d32
* Version Independent ID: 29c57334-5f68-ca33-4d31-34e341102930
* Content: [Working with Registry Entries - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/samples/working-with-registry-entries?view=powershell-7)
* Content Source: [reference/docs-conceptual/samples/Working-with-Registry-Entries.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Working-with-Registry-Entries.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
This does explains the behavior of the cmdlet stating that it returns all of the PowerShell properties including the requested one. This is the behavior of the cmdlet and there isn't a way to filter out the result using that commdlet exaclty. However, with PowerShell being object oriented, the behavior of PowerShell allows you to do that fairly easily. 

You can do something as simple as wrapping the command in parenthesis (`()`) and get the specify the property you want to use:
```powershell
 (Get-ItemProperty -Path HKCU:\Environment\ -Name Path).Path
```

Or, you could store the result in a variable and get the property from there while maintaining access to the other values provided.
```powershell
$propertyPath = Get-ItemProperty -Path HKCU:\Environment -Name Path
$proprtyPath.Path
```

The doc also gives you reference to another tool to use (`Reg`) that can get the property without the extra. This is right under the section you are talking about in a Note.

I'm closing this issue but feel free to respond and i'll be keeping an eye if we need to discuss further.
