### ISSUE TITLE
Document implicit Get- prefixing of commands 

### ISSUE THREAD

**Issue by rjmholt** [MicrosoftDocs/PowerShell-Docs#6576]
# Summary of the new document or enhancement

From https://github.com/PowerShell/PowerShell/issues/13554.

When PowerShell does not resolve a command immediately, it will prepend `Get-` and try again, creating an implicit `Get-` prefix alias mechanism.

I can't find any mention of this in documentation and I'm not sure if we have any established terminology for it. Ideally we could give this a name (mainly so it resolves nicely in search and can be discussed easily) and find somewhere to document it in existing documentation.

**Comment by chasewilson** [comment]
@rjmholt  Do you have a specific place where you think this behavior could be documented? I don't see it necessrily fitting into about aliases or anything like that.

**Comment by rjmholt** [comment]
Hmmm. Do we have anywhere we talk about command resolution? Like about how it goes aliases, functions, cmdlets, native commands?

**Comment by mklement0** [comment]
The name I've heard used in the past is _default verb_.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Command_Precedence seems like an appropriate place.

However, we should also _discourage_ use of this feature, for the following reasons:

* command lookup is much slower (see below)
* external programs with the same name quietly preempt the verb-less names (e.g. `date` on Unix).
* `Get-Help` and `Get-Command` do not know the verb-less names - see https://github.com/PowerShell/PowerShell/issues/3987

Quoting @lzybkr from https://github.com/PowerShell/PowerShell/issues/3987#issuecomment-308279494:

> It [the default verb feature] is also very expensive - we first search normally (including the PATH), and if that fails, we repeat the search prepending Get-.

> Personally, I'd rather remove this misfeature than formalize it.

> We could provide a handler for `$ExecutionContext.InvokeCommand.CommandNotFoundAction` for folks that are unwilling to fix old scripts that rely on this odd feature.

**Comment by rjmholt** [comment]
> We could provide a handler for $ExecutionContext.InvokeCommand.CommandNotFoundAction for folks that are unwilling to fix old scripts that rely on this odd feature.

This would be extremely useful

**Comment by chasewilson** [comment]
Thank to both of you @mklement0 @rjmholt, This is a huge help and that article really seems like the only fit for something like this. It's not a perfect fit but I think it will do and this extra information is perfect. Thank you again.
