### ISSUE TITLE
Parameter validation behavior's documentation is incomplete/unclear

### ISSUE THREAD

**Issue by tiborebner** [MicrosoftDocs/PowerShell-Docs#6578]
There are a few issues with the docs regarding parameter validation:

- It is not clear how validation works in case of mandatory parameters. E.g the example given for `NotNull` validation attribute is explicitly wrong (for PS 5.1 at least) as mandatory string parameters cannot ever take a `$null` value. The `$null` argument is converted to an empty string before validation kicks in. The empty string, either passed directly or resulting from `$null` coercion, is rejected for mandatory string parameters as if `ValidateNotNullOrEmpty` were applied implicitly to the parameter (and, similarly, `ValidateNotNull` were applied to "nullable" parameters, i.e. parameters of type that accept the $null value) . This behavior should be documented. To demonstrate the problem (also note the misleading error message):
```PowerShell
> function AllowNullParam { param ([Parameter(Mandatory=$true)][AllowNull()][string]$p) { $p } }
> AllowNullParam $null
AllowNullParam : Cannot bind argument to parameter 'p' because it is an empty string.
At line:1 char:16
+ AllowNullParam $null
+                ~~~~~
    + CategoryInfo          : InvalidData: (:) [AllowNullParam], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,AllowNullParam
````
- The second issue is that the documentation states (emphasis is mine): "You can also use _some_ of the validation attributes to restrict the values that users can specify for variables." Now, as far as I can tell, all of the validation attributes can be applied to variables as well. For example
```PowerShell
 [ValidateNotNull()][object]$o = $null
```
will throw an exception although the docs don't state it explicitly that this attribute also works for variables.
- For `ValidateLength` this example is given: 
```PowerShell
[Int32][ValidateLength(1,10)]$number = 01
````
One thing is that the example correctly is
```PowerShell
[Int32][ValidateLength(1,10)]$number = '01'
```
which is a formatting issue, although a significant one. The other thing is, the description fails to mention the the order of the attributes matter in this case:
```PowerShell
[ValidateLength(1,10)][Int32]$number = '01'
```
won't work. In my opinion, this behavior is not obvious to the user, therefore should be noted.
- In the "ValidateNotNull validation attribute" section the doc says
>The ValidateNotNull attribute is designed to be used when the type of the parameter value isn't specified or when the specified type accepts a value of $null. If you specify a type that doesn't accept a $null value, such as a string, the $null value is rejected without the ValidateNotNull attribute, because it doesn't match the specified type.

This is true but ambiguous. The main point is that the `ValidateNotNull` is only meaningful in case of optional parameters. Otherwise the parameter, typed or untyped, won't accept `$null`. It could be inferred from the above that it is possible to declare a mandatory parameter that accepts `$null` (e.g. of type `[object]`) which is not the case, of course.
- It should be made clear that validation won't happen neither for default values of parameters, nor for unbound parameters (i.e. arguments missing for optional parameters).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fdd3909-4005-b224-0395-364445d4d4b6
* Version Independent ID: 4eac80f8-61be-4d0f-d657-a007ba81cf53
* Content: [about_Functions_Advanced_Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hey @tiborebner, thanks for the great, detailed feedback!

To your first point, I'm updating the example and adding a note to warn about the behavior and suggest to use the **AllowEmptyString** attribute for that scenario. 

To your second point, I'm updating it to recognice that you can use all the attributes. 

I'm updating the doc to highlight the syntax requirements and the example for the type converter and validation attribute combination as well as add a note about the **ValidateLength** attribute when defining integers. 

I would that if it didn't work with an undefined type with a mandatory parameter, it would make sense to add that. However, if you have a type that accepts a null value, like **int**, it can still run. e.g.:
```powershell
function Test-Function{
    param
    (
        [Parameter(Mandatory = $true)]
        [int]
        $TestParam
    )

    if ($TestParam){ Write-Host $TestParam }
    else { Write-Host "It works" }
}
Test-Function -TestParam $null
```
The above example will run without interferance. However, if the type is undefined, it won't run so I will update the language there. 

To be honest I'm not clear on your last point. Would you mind clarifying form me? 

Thanks again. These are really good changes and will help the docs a ton!

**Comment by tiborebner** [comment]
Hi @chasewilson, thank you for your prompt reactions! I'll try to clarify the things you mentioned.

To be clear, I'm not a PS expert by any means. I'm a developer well versed in .NET, C# and the C family of languages (and programming in general), now trying to grasp key concepts of PS to build up an accurate mental model of its (inner) workings and decide on a suitable programming style for my tasks at hand. My impression of the language has been so far that it is very powerful and has some nice features, yet there are a quite some corner cases and gotchas using it because a lot of things happen under the hood that are either not well documented, very complex, or both. One of those areas is (automatic) type conversion, parameter binding and validation.

**Comment by chasewilson** [comment]
@tiborebner No problem! I'm very glad to be able to help and thankful to people like yourself who constantly help to improve the docs.

These are some interesting behaviors. This spreads a bit in scope. Including to about_Parameters_Default_Values. I'm going to create a new issue to cover that behavior and tag you there to continue if that's alright with you.  I'll finish the current pr with the changes to about_Functions_Advanced_Parameters now and move forward.

**Comment by tiborebner** [comment]
EDIT: You work fast! Thanks :) I was in the process of writing the comment below when I saw you have closed the ticket. I nevertheless post my findings so that you can decide on how and where (if at all) to include this in the doc in some form.

Regarding the `ValidateNotNull` attribute: I argue that for mandatory parameters the attribute has no effect. To support that argument, let's look at these cases:
```powershell
function Test-Function{
     param
     (
         [Parameter(Mandatory = $true)]
         [object]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
Test-Function : Cannot bind argument to parameter 'TestParam' because it is null.
At line:1 char:15
+ Test-Function $null
+               ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Function], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-Function

function Test-Function{
     param
     (
         [Parameter(Mandatory = $true)]
         [ValidateNotNull()]
         [object]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
Test-Function : Cannot validate argument on parameter 'TestParam'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At line:1 char:15
+ Test-Function $null
+               ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Function], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Test-Function
```
`object` is supposed to be a type that accepts `$null` since it is a reference type and has no associated type converter (unlike `string`), yet `$null`  it is apparently not accepted for the mandatory `$TestParam` parameter. The kind of exception thrown differs in the two cases: one is a binding error, the other, when the attribute is present, a validation error, but the end result is the same. `$null` is simply not an acceptable argument for mandatory parameters of reference types. `string` is special case in that the empty string is disallowed by default as well, and, as far as I understand, the type converter first converts the `$null` value to an empty string which then falls through the null check.
```powershell
function Test-Function{
     param
     (
         [Parameter(Mandatory = $true)]
         [string]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
Test-Function : Cannot bind argument to parameter 'TestParam' because it is an empty string.
At line:1 char:26
+ Test-Function -TestParam $null
+                          ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Function], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Test-Function

function Test-Function{
     param
     (
         [Parameter(Mandatory = $true)]
         [ValidateNotNull()]
         [string]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
Test-Function : Cannot bind argument to parameter 'TestParam' because it is an empty string.
At line:1 char:26
+ Test-Function -TestParam $null
+                          ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Function], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Test-Function
```
For value types like `int` or `float` things are a bit different, however, the validation attribute still makes no difference whatsoever:
```powershell
function Test-Function{
     param
     (
         [Parameter(Mandatory = $true)]
         [int]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
0

function Test-Function{
     param
     (
         [Parameter(Mandatory = $true)]
         [ValidateNotNull()]
         [int]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
0
```
Let's have a look at the case of optional parameters:
```powershell
function Test-Function{
     param
     (
         [Parameter(Mandatory = $false)]
         [int]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
0
> TestFunction
0

function Test-Function{
     param
     (
         [Parameter(Mandatory = $false)]
         [ValidateNotNull()]
         [int]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
0
> TestFunction
0

function Test-Function{
     param
     (
         [Parameter(Mandatory = $false)]
         [object]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null    # no output ($TestParam is $null)
> TestFunction    # no output ($TestParam is $null)

function Test-Function{
     param
     (
         [Parameter(Mandatory = $false)]
         [ValidateNotNull()]
         [object]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null
Test-Function : Cannot validate argument on parameter 'TestParam'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At line:1 char:26
+ Test-Function -TestParam $null
+                          ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Function], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Test-Function
> TestFunction    # no output (validation bypassed, $TestParam is $null)
```
For completeness, the same test cases for `string` are:
```powershell
function Test-Function{
     param
     (
         [Parameter(Mandatory = $false)]
         [string]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null    # empty line output ($TestParam is empty string)

> TestFunction    # empty line output ($TestParam is empty string)


function Test-Function{
     param
     (
         [Parameter(Mandatory = $false)]
         [ValidateNotNull()]
         [string]
         $TestParam
     )

     $TestParam
 }
> TestFunction -TestParam $null    # empty line output ($TestParam is empty string)

> TestFunction    # empty line output ($TestParam is empty string)

```
The only case in which a validation exception had been thrown that, had the `ValidateNotNull` attribute been not applied, would have not been thrown is the optional `object` parameter. To generalize that: the attribute is only effective for optional parameters of reference types with a type converter that passes through `$null`. I hope I put it correctly as I'm not a native speaker.

**Comment by tiborebner** [comment]
@chasewilson There's one more observation I've just made about the behavior of parameter validation. As I remarked earlier, the order of the validation and type converter attributes matters but only at variable definition. The attributes are applied from right to left. For the recommended ordering this means the value to be assigned is first validated and then converted to the desired type. At assignment, on the other hand, always the type converter executes first, and validation is carried out on the converted value. This has the consequence that some type and validation attribute combinations not work as expected. For example, it may seem at first that it is possible to prevent null-assignment to a `string` variable, but the effect is not permanent:
```powershell
> [string][ValidateNotNull()]$s = $null
The attribute cannot be added because variable s with value  would no longer be valid.
At line:1 char:1
+ [string][ValidateNotNull()]$s = $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
> [string][ValidateNotNull()]$s = ''
> $s = $null    # this is valid
```
Another example is when the `ValidateLength` attribute is combined with `int` variables. This example is in the documentation and I've already made a remark about a mistake that you fixed since. Unfortunately, that example use case is crippled in practice due to the attribute interactions I alluded to above:
```powershell
> [int][ValidateLength(1,3)]$number = '01'
> $number = 2
The variable cannot be validated because the value 2 is not a valid value for the number variable.
At line:1 char:1
+ $number = 2
+ ~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
> $number = '5'
The variable cannot be validated because the value 5 is not a valid value for the number variable.
At line:1 char:1
+ $number = '5'
+ ~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
```
The variable can be defined but every attempt to reassign its value fails because the type converter ensures that the value to be assigned is coerced to `int` and an `int` value cannot be validated by the `[ValidateLength]` [attribute](https://docs.microsoft.com/hu-hu/powershell/scripting/developer/cmdlet/validatelength-attribute-declaration?view=powershell-5.1).

I think these are traps users should better be warned about. I don't know if the underlying mechanism is like I described it. This is only my best shot at coming up with a reasonable explanation for the behavior I observed, based on what I've come to learn about Powershell. A developer could perhaps provide more information.

I hope this helps.

**Comment by chasewilson** [comment]
@tiborebner  This might take me a while to respond to but don't worry I'm going to take a look and make sure we come to a good solution. Just didn't want to leave you hanging. These are great notes!

**Comment by tiborebner** [comment]
@chasewilson Thanks! I'm glad I could be of some service and in case anything needs more clarification I'm happy to provide it.
