### ISSUE TITLE
Output in examples are from a different version for About_Trap

### ISSUE THREAD

**Issue by kvprasoon** [MicrosoftDocs/PowerShell-Docs#6580]
# Documentation Issue
Output for examples mentioned in about_trap help file for 5.1 are actually from PowerSehll 7.x with new error view.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-5.1
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [x] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [x] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by chasewilson** [comment]
CLosed in PR #6581
