### ISSUE TITLE
-FORM doesn't exists on the 

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/PowerShell-Docs#6594]
Inside:
```Powershell
Invoke-RestMethod -Uri $Uri -Method Post -Form $Form
```

-FORM doesn't exist

it must be changed to -Body

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ac7780-af59-1176-1c0a-ec821902c2f8
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hey @j0rt3g4, thanks for the feedback. I belive you might be operating on PowerShell 5.1 and the docs you are looking at are for 7.0. 7.0 does have the **Rorm** parameter. You can change the version of the docs on the page itself. 

I'm going to close this for now but feel free to respond here and I'll do my best to help you in any way I can.
