### ISSUE TITLE
Emphasize the information that Write-Output is normally not needed, clarify when it is useful, use a better example

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6598]
> This cmdlet is typically used in scripts to display strings and other objects on the console. However, because the default behavior is to display the objects at the end of a pipeline, it is generally not necessary to use the cmdlet. For instance, `Get-Process | Write-Output` is equivalent to `Get-Process`.

All of this is correct, but I suggest:

* highlighting the paragraph with `[!NOTE]` formatting

* using a better example for the benefit of users coming from traditional shells such as `cmd.exe` and `bash`: 
  * Point out that the built-in alias of `Write-Output` is `echo`, and that commands such as 
`echo "Home directory: $HOME"` can be written as simply `"Home directory: $HOME"` - no need for `echo` / `Write-Output`.

* adding the one - rare - use case where `Write-Output` _is_ useful: to output a collection _as a whole_ to the pipeline; e.g., `Write-Output -NoEnumerate 1, 2, 3 | ForEach-Object { "Array: $_ " }` (the more efficient, but more obscure, expression-mode alternative is `, (1, 2, 3)  | ForEach-Object { "Array: $_ " }`

`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ae9a63-c445-5453-7e8c-93121b8fcea8
* Version Independent ID: f0d97751-59f2-7dcb-5c9c-11fa9e557e1b
* Content: [Write-Output (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/write-output?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Write-Output.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Write-Output.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hey @mklement0 , thanks for the feedback. 

- I agree that this section can be wrapped in a **NOTE**, I'll add this. 
- I think `echo` can be an important reference as it's important in the other shells and could give context to it. Let me know if you think this section fits your suggestions and con be improved in the linked PR.
  - However, you might be able to answer a question for me. Is the behavior similar to echo in other shells as in, does `echo` display the output from the end of a pipeline and include objects or similarly typed things in other shells? 
- I don't think your point is completely necessary to this as the behavior for **NoEnumerate** is explained and that concept can be used as the use sees fit. 

Feel free to respoind here and I will request your review on the PR as well if I have it up before you get to respond here. Thanks!

**Comment by mklement0** [comment]
Thanks, @chasewilson.

As for:

> However, you might be able to answer a question for me. Is the behavior similar to echo in other shells as in, does echo display the output from the end of a pipeline and include objects or similarly typed things in other shells?

In `cmd.exe` and POSIX-compatible shells such as `bash`, `echo` only accepts _text_ (strings).
Essentially, these shells know just two types (and no _objects_): text and binary data.

**Comment by chasewilson** [comment]
> Thanks, @chasewilson.
> 
> As for:
> 
> > However, you might be able to answer a question for me. Is the behavior similar to echo in other shells as in, does echo display the output from the end of a pipeline and include objects or similarly typed things in other shells?
> 
> In `cmd.exe` and POSIX-compatible shells such as `bash`, `echo` only accepts _text_ (strings).
> Essentially, these shells know just two data types (and no _objects_): text and binary data.

Thanks @mklement0, I had specific terminology that leaned more towards PowerShell behavior mirroring other shell behavior. I updated it based on your feedback. I just didn't want to give the impression that other shells would behave the way PowerShell does.
