### ISSUE TITLE
Clarify the purpose of Write-Host, contrast it with Write-Output; document stringification behavior

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6599]
Given that `Write-Host` is often mistakenly used when `Write-Output` (or _implicit_ output) should be used, I think a clarification along the following lines would be helpful in the "Description" section:

* `Write-Host`'s primary purpose is to produce _for-(host)-display-only_ output, such as printing colored text, e.g., in the context of prompting the user for input.
* By contrast, to output _data_, to the _pipeline_, use `Write-Output` or implicit output.

---

Also, it is worth noting how `Write-Host` _stringifies_ its arguments for display:

Unlike the related `Out-Host` cmdlet, which uses PowerShell's output formatting system, `Write-Host` uses simple .NET `.ToString()` stringification instead; the elements of collections are printed on the _same_ line, separated by a single space each by default (unaffected by `$OFS`), which can be overridden with `-Separator`.

With non-primitive data types (objects with properties), the results can be unexpected, because instances of such types typically do not have meaningful `.ToString()` representations:

```powershell
PS> Write-Host @{ a=1; b=2} (Get-Process -id $PID)
System.Collections.DictionaryEntry System.Collections.DictionaryEntry System.Diagnostics.Process (pwsh)
```

There's also a subtle pitfall: While the argument-less .NET`.ToString()` method is expected to respect the _current culture_ (for types that implement culture-sensitive representations), PowerShell preempts this in the following case:

A (bareword) argument that would otherwise be parsed as a number literal is _not_ reformatted for the current culture, because PowerShell deliberately retains the original text representation in that case (this original representation is available via the hidden `.psobject` property - and, technically, it is `.psobject.ToString()`, not `.ToString()` directly that `Write-Host` calls in such cases):

```powershell
& {
  $origCulture = [cultureinfo]::CurrentCulture
  [cultureinfo]::CurrentCulture = 'fr-FR'

  & { $num = 1.23; Write-Host $num 1.23 }

  [cultureinfo]::CurrentCulture = $origCulture
}
```

The above yields `1,23 1.23` -  note how only the _first_ formatted number uses the culture-appropriate decimal mark, `,`. In the case of the literal argument, the input representation was preserved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a1089d-8246-bb9d-dc60-f548e451230b
* Version Independent ID: aac3a47a-db82-f3af-cef0-44676619bd08
* Content: [Write-Host (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Write-Host?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Write-Host.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Write-Host.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hmm Im with you all the way up until the culture issue. I'm not seeing the same result in any version of PowerShell. All instances for me are: `1,23 1,23`.

**Comment by mklement0** [comment]
If I paste the code from above verbatim into my `en-US` console, I get `1,23 1.23` - in both PS editions.

For easier testing, consider use of the [`Use-Culture` function](https://gist.github.com/mklement0/d80c80c5ee9b627cbecfccc4ce073c3b):

```powershell
PS> Use-Culture fr-FR { $num = 1.23; Write-Host $num 1.23 }
1,23 1.23
```

**Comment by chasewilson** [comment]
I get that output when I use your function. Could there be a problem with your function?

**Comment by mklement0** [comment]
The function works reliably for me, but depending on how the original form of the code above is pasted, you would get comma _twice_, which is probably connected to the bug described in https://github.com/PowerShell/PowerShell/issues/4557.

To reproduce the _bug_, execute this:

```powershell
& {
  $origCulture = [cultureinfo]::CurrentCulture
  [cultureinfo]::CurrentCulture = 'fr-FR'

  # Changing the culture inside the *same scope* isn't recognized 
  # due to an overzealous optimization.
  $num = 1.23; Write-Host $num 1.23

  [cultureinfo]::CurrentCulture = $origCulture
}
```

->  `1,23 1,23`, unexpectedly.

Note that this execution scenario is exotic, and therefore not likely to be encountered by users in practice.

Executing the `Write-Host` call in a _child_ scope avoids the bug and shows the true behavior, as previously described:

```powershell
& {
  $origCulture = [cultureinfo]::CurrentCulture
  [cultureinfo]::CurrentCulture = 'fr-FR'

  # OK - executing `Write-Host` in a child scope works as expected.
  & { $num = 1.23; Write-Host $num 1.23 }

  [cultureinfo]::CurrentCulture = $origCulture
}
```
->  `1,23 1.23`, as expected.

**Comment by mklement0** [comment]
To summarize, @chasewilson: My original description of `Write-Host`'s behavior stands, the different behavior you saw was the result of an unrelated bug that few people will ever run into.

**Comment by chasewilson** [comment]
Gotcha. My current guidance for bugs, especially low impact bugs is to not document them (with rare exception like 5.1 write-output where it's no longer being developed and will always exist) the issues created document the bugs.
