### ISSUE TITLE
Instructions for Microsoft Azure VM do not work, despite being sent here via PowerShell.

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/PowerShell-Docs#6604]
This document is factually incorrect.

So, I create a Windows VM.

Our DevOps guy creates a drive for us.

I try to attach it using the script that Microsoft provided.

Wont' run.

Ok, it's locked down. I get it. I followed the link.

Lovely article. 

EXCEPT IT DOESN'T WORK.

So I have a VM that is perfectly useless.

PLEASE update this article to indicate how to get files in and out of this VM.

We'll be asking for a credit because the service you have provided is unusable. 

And please don't say "this is documented somewhere else" ... if  I follow basic steps, log in, try to run a script that YOU gave me, I can buy that it won't work, but then the link that you send me to SHOULD. Two strikes. 

This has wasted a lot of billable time.

Sorry for the rant, it's been a long day and I just needed to copy some setup files up.

Thank you for listening! 

        == John ==

Details, after following the steps provided:

```
PS C:\WoWTest>  .\WebFileMount.ps1
.\WebFileMount.ps1 : File C:\WoWTest\WebFileMount.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:2
+  .\WebFileMount.ps1
+  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\ProdTest> Get-ExecutionPolicy -Scope CurrentUser
Undefined
PS C:\ProdTest>
```

The article says setting it to "Undefined" will allow the script to run. There's no other way that I see to attach the drive. Doing a file copy via RDP is kind of absurd. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ad4103-af4a-a7bc-d268-d26f4dabf892
* Version Independent ID: cfa0b0d5-be1f-b9d2-533d-61bfa6051292
* Content: [about_Execution_Policies - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
@jgwinner thanks for the feedback. I understand the frustration and I will do my best to help you out here. 

According to the output you pasted, your execution policy is set to `Undefined`. [According to this doc](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_execution_policies#undefined): "If the execution policy in all scopes is Undefined, the effective execution policy is Restricted for Windows clients and RemoteSigned for Windows Server."
This means if you are trying to run it on a Windows Client(VM), the policy is set to `Restricted` and won't be able to run scripts. If you are running it on Windows Server(VM), this means it is set to `RemoteSigned` meaning you won't be able to run it unless it is digitally signed. 

If you want to run the script, you can run: `Set-ExecutionPolicy -ExecutionPolicy Unrestricted`. This should fix your problem.

I don't believe there is an issue with the documentation here so I will close this issue for now. If you have any more issues, feel free to write back here and I will be notified of your respnse and work with you through this.

**Comment by jgwinner** [comment]
Well that's embarrassing. I keyed on this statement:

**Remove the execution policy**

_To remove the execution policy for a particular scope, set the execution policy to Undefined._

I guess I thought "Remove the execution policy" meant remove whatever was blocking the script - as the message seemed to indicate some blocking policy was *on*

And yup - the exact same document mentions 'unrestricted' later on. Sorry to trouble you!

        == John ==

**Comment by chasewilson** [comment]
Don't worry about it. I'm glad that it worked and I hope the rest of your work goes a lot smoother :) Have a great one!
