### ISSUE TITLE
Excellant run down of arrays

### ISSUE THREAD

**Issue by mxdog** [MicrosoftDocs/PowerShell-Docs#6606]
You might mention somewhere that what you commonly see on the screen might not be the actual array contents for instance
$disks=get-physicaldisk will return Number as a column heading but the actual array value is DeviceId
I was scratching my head on that until I ran across your $disk | get-member remark later in the article and I could see 
the actual list of the object.  I am sure this happens often when assigning variables from command output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99e524d-54e5-4119-9ebf-4fdbb7626122
* Version Independent ID: 271e2b41-af42-d4b5-3fdb-139aa5114b11
* Content: [Everything you wanted to know about arrays - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hey @mxdog , Thanks for the feedback. I'm not 100 percent positive I understand what you would like to see but I'll give it a shot and feel free to respond if I'm incorrect. 

You think that the **DeviceId** property is the array index identifier and the article doesn't describe this behavior? 

If this is your contention, this may be a coincidental outcome. In most arrays, the indes isn't tied to a property unless you write the code to make it so. The index is just the order of the array as it comes out of the pipeline. 

I'll be closing this for now, however, if you think there is more to add, feel free to respond here and I'll reevaluate :) 

Thanks again and have a great rest of the day!
