### ISSUE TITLE
Target property is valid property?

### ISSUE THREAD

**Issue by tksh164** [MicrosoftDocs/PowerShell-Docs#6607]
The Target property of Environment DSC resource is valid property?

> The member 'Target' is not valid. Valid members are 'DependsOn', 'Ensure', 'Name', 'Path', 'PsDscRunAsCredential', 'Value'.

VS Code with PowerShell extension:
![image](https://user-images.githubusercontent.com/1618784/92564866-d03e4b80-f2b4-11ea-8543-370d7e074754.png)

Azure Automation State Configuration:
![image](https://user-images.githubusercontent.com/1618784/92565325-6c685280-f2b5-11ea-8bac-8a4db23195e4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce1333c-cef3-cf6c-960b-cbbf275a7803
* Version Independent ID: 0aa33a23-27a9-4d7e-c7ea-c0e9c165750f
* Content: [DSC Environment Resource - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/environmentresource?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/reference/resources/windows/environmentResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/reference/resources/windows/environmentResource.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hey @tksh164, I'm sorry for your issue. This doc is correct. You might want to try using the PSDscResources which is the currently supports module holding dsc resources.

**Comment by tksh164** [comment]
@chasewilson - Thank you for your confirmation. I confirmed at [MSFT_EnvironmentResource.schema.mof](https://github.com/PowerShell/PSDscResources/blob/7064eda52d939a4a3ce40e1f38756cfe6a09acfd/DscResources/MSFT_EnvironmentResource/MSFT_EnvironmentResource.schema.mof#L8)

If so, the correct data type is string[] right? Because the definition of Target property is the array of string.

docs: 
```
[ Target = [string] { Process | Machine } ]
```

PSDscResources repo:
```
[Write, Description("Indicates the target where the environment variable should be set."), ValueMap{"Process", "Machine"}, Values{"Process", "Machine"}] String Target[];
```

P.S.
The Description property of  Group resource is the same (opposite). That data type is mismatched with the definition.

https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/groupresource

```
[ Description = [string[]] ]
```

https://github.com/PowerShell/PSDscResources/blob/7064eda52d939a4a3ce40e1f38756cfe6a09acfd/DscResources/MSFT_GroupResource/MSFT_GroupResource.schema.mof#L7

```
[Write, Description("The description the group should have.")] String Description;
```
