### ISSUE TITLE
The code inside example is outdate with Powershell 5.1

### ISSUE THREAD

**Issue by seal2002** [MicrosoftDocs/PowerShell-Docs#6614]
When I try the code examples, the string replace function is can not run with PowerShell 5.1
Ex: String -replace $pattern $value should be
String.replace($pattern, $value)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a8798d6-ed43-d6eb-44b2-237aa6d5c65d
* Version Independent ID: af4923e4-f78e-68b6-7f3b-e68dccf6037d
* Content: [Everything you wanted to know about variable substitution in strings - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-string-substitutions?view=powershell-6)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@seal2002 You need a comma between $pattern and $value. The following works in all versions:

```
PS> "hello" -replace 'l', 'L'
heLLo
``
