### ISSUE TITLE
Job Control Known Issue and Use of PowerShell Jobs as an Alternate

### ISSUE THREAD

**Issue by hankwojteczkodki** [MicrosoftDocs/PowerShell-Docs#6617]
[Enter feedback here]
I found that the Linux shell job control is still required even when using Powershell Jobs per referenced link. I am specifically referring to use of the Start-Job CMDLET when calling my custom CMDLET. I have worked around this issue by using Ansible CLI to start my long running job with ANSIBLE making a call to the CMDLET as in ansible NWMSUNGOP01 --become --become-user ansible -a "pwsh /home/ansible/myscript.ps1"

I do hope that Microsoft will modify PowerShell Core to be able to run multi-threaded background jobs in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba18a094-43ba-5ae6-c744-dbe95fd6336d
* Version Independent ID: c8eefde4-7679-34c2-0491-5244b250d0ba
* Content: [Known Issues for PowerShell 6.0 - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/known-issues-ps6?view=powershell-7)
* Content Source: [reference/docs-conceptual/whats-new/known-issues-ps6.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/known-issues-ps6.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@hankwojteczkodki I don't quite understand what the issue is that you are trying to describe. What are trying to run as a multi-threaded job? How are you trying to run it?

Have you see `ForEach-Object -Parallel` in PowerShell 7?
