### ISSUE TITLE
Remove-Item : Cannot remove item : The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by troyboy14k** [MicrosoftDocs/PowerShell-Docs#6625]
I have been trying to figure out how to resolve using Remove-Item and it errors with file is in use by another process.
 
I am writing the contents of a Hash table array ($folderOutput) into a file ($OutputFile).
$folderOutput.GetEnumerator() | sort-Object Value | Select-Object -Property Name, Value | Export-Csv $OutputFile 

I then attach and email the $Output file using common new-object System.Net.Mail.MailMessage Powershell code.  

After emailing I attempt to delete the $Output file, but it fails. 

```
Remove-Item $OutputFile -Force

Error:
Remove-Item : Cannot remove item C:\admin\Scripts\foldersize\ProfilesUSA-Size.20200914-1708.csv: The process cannot access the file 
'C:\admin\Scripts\foldersize\ProfilesUSA-Size.20200914-1708.csv' because it is being used by another process.
At C:\Admin\Scripts\foldersize\Get-ProfilesUSA-FolderSize.ps1:95 char:1
+ Remove-Item $OutputFile -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\admin\Script...200914-1708.csv:FileInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
--
```

When I run Get-SmbOpenFile at the prompt, there are no files in use. 

If I manually run Remove-Item $OutputFile -Force after my script completes the command works. 

Is there something I need to do within the script to close the file or remove objects?
I haven't been able to find a solution.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701c49d0-1949-61b8-2edd-651ab2714f09
* Version Independent ID: 0b18157a-a191-4733-90db-7dfceda2c99f
* Content: [Remove-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
It is likely that the System.Net.Mail.MailMessage object has an open handle to the file still. When the script exits, the object is released and the handle goes away. Thus allowing you to delete the file outside of the script. Try releasing the object within the script before deleting the file.

**Comment by troyboy14k** [comment]
That did it.  Disposing the mailmessage object before removing the file resolved.   Thank you.
