### ISSUE TITLE
Type conversion of parameter values doesn't work as described

### ISSUE THREAD

**Issue by John-Hofmann** [MicrosoftDocs/PowerShell-Docs#6626]
# Documentation Issue

The example code provided to create a cmdlet that uses culture-sensitive parsing to convert parameter values doesn't work.
## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-5.1
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Not sure. I have replicated the issue on Win 10 1709, 1903, and 1909

## Detailed description of the issue
The reference states:

In this example, we create a cmdlet and a script function that take a [datetime] parameter. The current culture is changed to use German settings. A German-formatted date is passed to the parameter.

>### PowerShell
```
# Create a cmdlet that accepts a [datetime] argument.
Add-Type @'
  using System;
  using System.Management.Automation;
  [Cmdlet("Get", "Date_Cmdlet")]
  public class GetFooCmdlet : Cmdlet {

    [Parameter(Position=0)]
    public DateTime Date { get; set; }

    protected override void ProcessRecord() {
      WriteObject(Date);
    }
  }
'@ -PassThru | % Assembly | Import-Module

[cultureinfo]::CurrentCulture = 'de-DE'
$dateStr = '19-06-2018'

Get-Date_Cmdlet $dateStr
```

>### Output
`Dienstag, 19. Juni 2018 00:00:00`

The actual behavior in practice is that this fails with 'Cannot process argument transformation on parameter 'Date'. Cannot convert value "19-06-2018" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."', just like any other function would.

![image](https://user-images.githubusercontent.com/65559354/93252049-fce5dd80-f762-11ea-98c7-084eb0546af7.png)

**Comment by sdwheeler** [comment]
This is expected behavior for all current versions of PowerShell. Type conversion for [datetime] expects _cultureinvariant_ formatting. There is an existing issue in the source repository: https://github.com/PowerShell/PowerShell/issues/8129

**Comment by John-Hofmann** [comment]
Maybe I'm misunderstanding, but if that's the case, shouldn't the documentation reflect that, rather than contradicting it?
