### ISSUE TITLE
The term 'Remove-EventLog' is not recognized

### ISSUE THREAD

**Issue by samboustani** [MicrosoftDocs/PowerShell-Docs#6628]
```
Remove-EventLog: The term 'Remove-EventLog' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

ModuleType Version    PreRelease Name                                      ExportedCommands
----------      -------      ---------- ----                                            ----------------
Manifest      7.0.0.0       Microsoft.PowerShell.Management       {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest      3.1.0.0       Microsoft.PowerShell.Management       {Add-Content, Clear-Content, Clear-Item, Clear-It…
Script           2.0.2         PSReadLine                                             {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a8520c-3bd0-ba00-e453-8150542567c6
* Version Independent ID: 74390d3a-c104-8654-5c1e-0a49b2f78785
* Content: [Remove-EventLog (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-eventlog?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Remove-EventLog.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Remove-EventLog.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
What version of PowerShell are you running? You were looking at the documentation for PowerShell 5.1. That cmdlet is only available in PowerShell 5.1.
