### ISSUE TITLE
Updates on Using DSC on Nano Server?

### ISSUE THREAD

**Issue by rs38** [MicrosoftDocs/PowerShell-Docs#663]
did nothing change from TP4 to current RTM Nano in regards to the DSC Module?

**Comment by HemantMahawar** [comment]
@zjalali and @amitsara Can you take a look?

**Comment by DCtheGeek** [comment]
Nano Server, as of Windows Server 1709, is now a container image.  We need to evaluate and update a few articles:

/powershell/dsc/nanodsc
/powershell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6#deploying-on-nano-server
/windows-server/get-started/powershell-on-nano-server
[NEW] /powershell/scripting/setup/using-powershell-core-in-docker-images

**Comment by mgreenegit** [comment]
Correct, no new updates have been released for Nano server + DSC.
