### ISSUE TITLE
Conceptual docs missing social sharing image

### ISSUE THREAD

**Issue by Windos** [MicrosoftDocs/PowerShell-Docs#6639]
# Documentation Issue

Sorry if this isn't the right forum for this issue, but it does seem to me limited to the PowerShell content set.

The conceptual (or at least non-reference docs) are missing social sharing images. This should normally be the Msft logo based on what I've seen from other content sets.

## Detailed description of the issue

Take [Product Compatibility Status](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/whats-new/compatibility?view=powershell-7) as an example.

Running it through the [Twitter Card Validator](https://cards-dev.twitter.com/validator) is a touch bland:

![Example card with no social image](https://user-images.githubusercontent.com/6955786/93418634-ee342d80-f8fe-11ea-9776-0dd868a56920.png)

The reference doc, [Enter-PSSession](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enter-pssession?view=powershell-7), is an example of docs with an image.

![Reference doc with social image](https://user-images.githubusercontent.com/6955786/93418768-33585f80-f8ff-11ea-916d-27d857869aff.png)

This is coming from two additional meta tags:

```html
<meta property="og:image" content="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" />
<meta property="og:image:alt" content="Microsoft Logo" />
```

But I'm not sure if there's any way in the markdown for the conceptual docs to trigger them.

As an aside, [Azure conceptual docs](https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages?WT.mc_id=AZ-MVP-5003460) do have a social image.

![Azure docs for completeness](https://user-images.githubusercontent.com/6955786/93418909-88947100-f8ff-11ea-8885-987fea48f564.png)

It would be awesome if all the PowerShell docs had some sort of image on them (either the standard Msft logo, or even the PS logo) as this makes it more visually engaging when sharing out content on Twitter and other platforms.

_n.b. I've noticed a lot of pages missing descriptions as well, but that's something I plan on chipping in and helping with as that I can see how it's sorted in the Markdown._

**Comment by sdwheeler** [comment]
@Windos Thanks. I will look into this. This is some kind of hidden configuration in our system. I am trying to find where this gets set.

**Comment by Windos** [comment]
Awesome, thanks @sdwheeler

**Comment by sdwheeler** [comment]
@Windos I finally got the information about how this works. The articles that don't display an icon do not have a description. So adding descriptions will fix that. I also found out how to change the icon that is used. So I will update the icon.

**Comment by Windos** [comment]
Makes sense (in a "that's a weird way of doing it" sort of way 😅).

I'll chip in and add some descriptions when I get some time. It might also be a good Hacktoberfest activity for a few people.

**Comment by sdwheeler** [comment]
@Windos I updated the icon.
![image](https://user-images.githubusercontent.com/19415881/93830065-cc0b1a00-fc34-11ea-9cef-ff84546eea48.png)

**Comment by Windos** [comment]
So cool!
