### ISSUE TITLE
Update Code Signing Documentation

### ISSUE THREAD

**Issue by jimbo8098** [MicrosoftDocs/PowerShell-Docs#6640]
Within the "Create Self Signed Certificate" section of the [about_signing article](https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7#create-a-self-signed-certificate) the section goes through creating the certificate manually using makecert instead of the "new" method. I am of the opinion that the people using pre-2012 OSs are dwindling.

I would suggest that this article is amended to include information for new users wishing to create a new certificate using the `New-SelfSignedCertificate` cmdlet instead or pehaps adding a tab-style example for each type (since it will undoubtedly be helpful).

I created my own self signed certificate using the code below:

```
$cert = New-SelfSignedCertificate -DnsName "jim.speir@serialaffinity.co.uk" -Type CodeSigningCert -CertStoreLocation Cert:\CurrentUser\My\
Export-Certificate -Cert $cert -FilePath ./codesigning.crt
Import-Certificate -FilePath .\codesigning.crt -Cert Cert:\CurrentUser\Root
# Click yes to trust the certificate
Import-Certificate -FilePath .\codesigning.crt -Cert Cert:\CurrentUser\TrustedPublisher
Set-AuthenticodeSignature .\profile.ps1 $cert
```

**Comment by sdwheeler** [comment]
@jimbo8098 The `New-SelfSignedCertificate` is part of the PowerShellCookbook, which is not created, shipped, or supported by Microsoft. I am sure that this cmdlet works well but we have to document methods that we can support.
