### ISSUE TITLE
Visual display of Write-Progress is undocumented

### ISSUE THREAD

**Issue by travis-c-lagrone** [MicrosoftDocs/PowerShell-Docs#6641]
The visual display of `Write-Progress` status bars is undocumented. Specifically, there are no images/screenshots/examples of the `Write-Progress` status bar is displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84c8478d-661c-6aca-99c6-6349618394dd
* Version Independent ID: 01ff8fbd-8abc-1419-0f9e-d56ddff65429
* Content: [Write-Progress (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Write-Progress?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Write-Progress.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Write-Progress.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
Example #2 shows an example of the progress:

```
Updating
Progress ->
 [ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]
OuterLoop
Updating
Progress
 [oooooooooooooooooo                                                   ]
InnerLoop
```

This is the best we can do in the cmdlet reference.
