### ISSUE TITLE
passing boolean values

### ISSUE THREAD

**Issue by tberta** [MicrosoftDocs/PowerShell-Docs#6649]
About passing boolean values from command line, see this page for 2 solutions:
https://stackoverflow.com/questions/5079413/how-to-pass-boolean-values-to-a-powershell-script-from-a-command-prompt
Using -Command instead of -File
Or with -File argument, specify boolean parameter and value as this : {-SomeBoolParameter:False}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776d0240-b9cb-fdb3-be53-eb72434040de
* Version Independent ID: 2a47dda6-5d42-249c-5d48-19ad6fbc7b3c
* Content: [about_PowerShell_exe - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by mklement0** [comment]
For context: Currently, the topic states:

> In rare cases, you might need to provide a Boolean value for a switch parameter. It is not possible to pass an explicit boolean value for a switch parameter when running a script in the way.

It's definitely worth pointing to `-Command` as an alternative.

Also, "in the way" should be "in this way", and, strictly speaking, the problem applies to _any_ Boolean value, not just one passed to a switch parameter.

Note that `{-SomeBoolParameter:False}` does _not_ work: there is no workaround in Windows PowerShell - see #4964
