### ISSUE TITLE
Point out that ConvertTo-Xml is virtually useless.

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6676]
The topic should provide guidance based on the following information:

* `ConvertTo-Xml` lacks a `ConvertFrom-Xml` counterpart and is incompatible with CLIXML (the latter part is already documented).
* Without a _de_-serializing counterpart, it is virtually useless, unless you're willing to write your own deserializer - which would be based on _guesswork_, given that the specific serialization algorithm isn't documented and given that documenting it isn't planned - see #6612.

Pragmatically speaking, we should tell users (in friendlier language): This cmdlet is a dead end - do not use it.
Another way of looking at it: we could call it deprecated.

Looking into the future: Implementing properly paired in-memory CLIXML-processing cmdlets - `ConvertTo/From-CliXml` - has been green-lighted, but no one has tackled it: see https://github.com/PowerShell/PowerShell/issues/3898

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9919328f-ba37-c93a-0d59-ab380de05b27
* Version Independent ID: df52e589-e043-a0f2-f48d-3f9c2e331030
* Content: [ConvertTo-Xml (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-xml?view=powershell-7.1&WT.mc_id=ps-gethelp)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
We document what the cmdlet does. Discussion of the usefulness should be done in the PowerShell source repo.

**Comment by mklement0** [comment]
Documenting what the cmdlet means documenting _what the cmdlet is used / useful for_.

You're doing users a disservice if you don't tell them (a) about a cmdlet's limited utility, (b) what the limitations are, and (c) that these limitations won't be remedied.

Honestly, I'm baffled by your response - it shows a worrisome disconnect from what is important to users.
 
There's nothing to discuss in the source repo, as there are clearly neither plans to document `ConvertTo-Xml`'s output format nor to implement a matching `ConvertFrom-*` cmdlet.
