### ISSUE TITLE
What is the purpose of -Path?

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/PowerShell-Docs#6681]
Per documentation, all the examples include `-Path` parameter.
I'm using Powershell 5.1 and the cmdlet appears to be working as expected without specifying this parameter, e.g. `Get-Content filename`, where filename is at either absolute or relative location.
Please clarify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477effec-a944-c2fb-6d1b-28f85d88cde2
* Version Independent ID: 6ccfc309-9783-aadd-717d-671dcbd454ed
* Content: [Get-Content (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-Content.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-Content.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by doctordns** [comment]
In PowerShell, parameter values can be specified without adding in a parameter name, in some cases but not all. The trick is to read the help text showing the syntax.  Look at the help text for Get-ChildItem (or it's aliases LS, or DIr):

```powershell
SYNTAX
    Get-ChildItem [[-Path] <String>]  etc
```
That says that you can specify the path with or without the parameter name.

**Comment by I-gor-C** [comment]
@doctordns Thanks a lot for the quick answer!
