### ISSUE TITLE
More detail on removing items from Arrays

### ISSUE THREAD

**Issue by jfcomst** [MicrosoftDocs/PowerShell-Docs#6685]
I was looking for details about removing items from Arrays, but didn't see it here.  On the PowerShell arrays there is a method "RemoveAt) that I attempted to use, but it returns an error indicating that arrays can't be modified.  Is this method supposed to be available?  If so, how should it be used?  Also, what about the Remove method?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99e524d-54e5-4119-9ebf-4fdbb7626122
* Version Independent ID: 271e2b41-af42-d4b5-3fdb-139aa5114b11
* Content: [Everything you wanted to know about arrays - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Arrays in PowerShell are .NET `[System.Array]` objects. By definition, they have a fixed size. The Add and Remove* methods are not supported.

See https://docs.microsoft.com/en-us/dotnet/api/system.array?view=netcore-3.1#remarks and https://docs.microsoft.com/en-us/dotnet/api/system.array.system-collections-ilist-remove?view=netcore-3.1#remarks

PowerShell implements the addition operator (`+`) for arrays. When you add arrays using the operator, the results are copied to a new array and the "old array" is deleted. PowerShell does not implement a subtraction operation. Removing items from a fixed size array would require the same sort of copy process. This does not scale well.

If you want a flexible alternative to an array, you need to use a generice List[] object.  See https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7#generic-list
