### ISSUE TITLE
Add a page about user groups under the community section

### ISSUE THREAD

**Issue by roberthstrand** [MicrosoftDocs/PowerShell-Docs#6694]
Right now, the only official list of PowerShell User Groups is the one over at [technet wiki](https://social.technet.microsoft.com/wiki/contents/articles/19959.powershell-user-groups.aspx) which can be a hassle to get updated. There are references to websites that don't exists anymore, or that have completely unrelated content.

For instance, it took a while to get the Norwegian one up there and when it did my name was (as usual) miss-spelled. I'm sure that it wouldn't be too difficult to get the right permissions to update the wiki myself but it would be more natural to have this list here.

If others agree, I can make the first initial edit and populate it with the information from technet.

**Comment by sdwheeler** [comment]
I agree that the technet wiki is not the ideal experience. And, like the rest of MSDN and TechNet, it will be retired at some point. However, the docs site is not designed for this kind of content. I am not sure where we could or should host this kind of content.

This repository has a Wiki. I would consider opening that up to host this information. But that is not a great user experience either. May be able to do something with GitHub pages. But we need a solution that the community can maintain with extremely minimal involvement from the Docs team.

I will also try to find out what the plan is for the TechNet wiki and if there is a replacement being planned.

**Comment by roberthstrand** [comment]
With the docs already referencing user groups, and have plenty of content that could be argued that the docs aren't designed for, I feel that it actually fits as is. With docs being the official place to host information in regards to PowerShell, and to help promote the community, I'd would be a good choice.

I agree that the community should be able to maintain it with minimal involvement. A solution there is to have a repository that is less restrict on who can approve, for instance give certain community members the right to approve PR. The community could make and maintain an organization on GitHub. To be honest, I might do something like this anyway. Not that I don't have enough projects😅

**Comment by sdwheeler** [comment]
Our docs platform is not designed for this kind of content. For now, the TechNet Wiki is the only solution we have at Microsoft to host this information.
