### ISSUE TITLE
Powershell Gallery IconURI should be 85x85, not 32x32

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#6695]
The docs here say that a Powershell Gallery Icon should be 32x32, however the images are displayed in 85x85 on the powershell gallery site and thus the recommended size should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd3f37dc-412c-60d6-07fe-f583036d7778
* Version Independent ID: 08d2ef8b-9faf-57a6-5cd1-480a6e934dae
* Content: [Package manifest values that impact the PowerShell Gallery UI - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/package-manifest-affecting-ui?view=powershell-7)
* Content Source: [reference/docs-conceptual/gallery/concepts/package-manifest-affecting-ui.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/concepts/package-manifest-affecting-ui.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you comment/confirm this?

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote gave this a look and you are correct--we can update the documentation accordingly.
