### ISSUE TITLE
Typo/unclear notebox

### ISSUE THREAD

**Issue by eptn** [MicrosoftDocs/PowerShell-Docs#6697]
[Enter feedback here]
In this note
![image](https://user-images.githubusercontent.com/71384666/94893830-5ac73480-0488-11eb-99f7-eeda69adc555.png)
it seems that "in PowerShell is: @{<name>=<value>; <name>=<value>; ...}" is written twice and that it should not be. That is all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099bc9aa-5397-0b8a-026e-a20c1bb604a2
* Version Independent ID: e12ddb02-4549-2bee-39fc-e6f902f7da25
* Content: [about_Splatting - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by doctordns** [comment]
hopefully that fixes this issue - well spotted.
