### ISSUE TITLE
Property test syntax incorrect

### ISSUE THREAD

**Issue by jcoryatjr** [MicrosoftDocs/PowerShell-Docs#6699]
[Enter feedback here]
This line:
`if( $myobject.psobject.properties.match('ID') )`
actually doesn't work as expected.

If there is a match it will return true, but if there isn't a match it still returns true.  This is because it returns an empty ReadOnlyPSMemberInfoCollection object which will evaluate to true since it is not null, an empty string or zero.
Using your code:
`$myObject = [PSCustomObject]@{
    Name     = 'Kevin'
    Language = 'PowerShell'
    State    = 'Texas'
}

if( $myobject.PSObject.Properties.Match( 'ID' ) ) {
    Write-Output 'True'
} else {
    Write-Output 'False'
}
`
This is due to the Match() function returning an empty ReadOnlyPSMemberInfoCollection object.

If you add the Count property, it does work:
`$myObject = [PSCustomObject]@{
    Name     = 'Kevin'
    Language = 'PowerShell'
    State    = 'Texas'
}

if( $myobject.PSObject.Properties.Match( 'ID' ).Count ) {
    Write-Output 'True'
} else {
    Write-Output 'False'
}`

Thought you would like to have your documentation correct.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86c9d989-17c8-2a16-5c39-232e3dade004
* Version Independent ID: 8e72ce06-198a-ec18-2e87-332697391fee
* Content: [Everything you wanted to know about PSCustomObject - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-pscustomobject?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@jcoryatjr Thanks for pointing this out. Do you want so submit a PR to fix the example?

**Comment by jcoryatjr** [comment]
What is a PR?




Jim







On Fri, Oct 2, 2020 at 10:57 AM -0400, "Sean Wheeler" <notifications@github.com> wrote:















@jcoryatjr Thanks for pointing this out. Do you want so submit a PR to fix the example?

**Comment by jcoryatjr** [comment]
Sorry, doh!  Sure I will update this weekend.




On Fri, Oct 2, 2020 at 10:57 AM -0400, "Sean Wheeler" <notifications@github.com> wrote:















@jcoryatjr Thanks for pointing this out. Do you want so submit a PR to fix the example?
