### ISSUE TITLE
 Provide documentation to the command line switch -sshs (as used in sshd_config)

### ISSUE THREAD

**Issue by eabase** [MicrosoftDocs/PowerShell-Docs#6702]
Please document the command line switch **`-sshs`** that is referred to everywhere related to `sshd_config`.

* https://github.com/PowerShell/Win32-OpenSSH/issues/1672

Some of the sources related to this can be found in [this search](https://github.com/PowerShell/PowerShell/search?q=sshs).

**Comment by sdwheeler** [comment]
The `-sshs` parameter of `pwsh` is only used for running PowerShell as an SSH subsystem. It is not intended or supported for any other use.

This is documented in https://docs.microsoft.com/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core#set-up-on-a-windows-computer.

**Comment by eabase** [comment]
@sdwheeler 
Hi Sean,

> The `-sshs` parameter of `pwsh` is only used for running PowerShell as an SSH subsystem. It is not intended or supported for any other use. This is documented in ....

That was only half clear since yesterday (and after several days messing around with dysfunctional settings and MS instructions), when I finally was pointed to the code here. Certainly not from any type of *"documentation"*. I understand this is a bit of a borderline case, as it seem only used in conjunction with *OpenSSH* (sshd) Server.

So, I was trying to get the *popular* line (always given as): 
`Subsystem powershell c:/progra~1/powershell/7/pwsh.exe -sshs -NoLogo`
to also respect the `-NoProfile` flag, but with zero success. It was only after having set the registry values back to using the old powershell I managed to avoid my `Microsoft.PowerShell_profile.ps1` profile from running, using: 

```powershell
Set-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShellCommandOption -Value "-NoProfile -c" -PropertyType String -Force
```

So it seem that the `sshd_config` is totally ignoring these items: 
```sshd
# To enable SSH "remoting" (for using Apps remotely):
#Subsystem powershell c:/progra~1/powershell/7/pwsh.exe -sshs -NoLogo
#Subsystem pwsh "c:/progra~1/powershell/7/pwsh.exe -NoLogo -NoProfile"
#Subsystem powershell c:/progra~1/powershell/7/pwsh.exe -sshs -NoLogo -NoProfile
Subsystem pwsh c:/progra~1/powershell/7/pwsh.exe -sshs -NoLogo -NoProfile
```
