### ISSUE TITLE
Documentation Issue : Command worked fine 

### ISSUE THREAD

**Issue by Alphasaurs** [MicrosoftDocs/PowerShell-Docs#6703]
The command depicted below works fine : 
Powershell version :  5.1.19041.1

![1](https://user-images.githubusercontent.com/50196057/95075211-70a95380-072d-11eb-843e-24f5c7887bc7.PNG)

![2](https://user-images.githubusercontent.com/50196057/95075306-959dc680-072d-11eb-9c8c-0a21c1bed061.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9ce399-c725-2430-bbd0-b8887d1beda6
* Version Independent ID: 61c4ba2e-b08d-089b-74bc-70d6306523e5
* Content: [about_Quoting_Rules - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You used double-quotes. The error occurred with single quotes in PowerShell 5.1. However, the behavior has changed a little since the documentation was written.

```
PS> "Use a quotation mark (`") in a string"
Use a quotation mark (") in a string
PS> 'Use a quotation mark (`") in a string'
Use a quotation mark (`") in a string
```

Now instead of an error, it displays the string with the backtick character.
