### ISSUE TITLE
Mof reserved keywords

### ISSUE THREAD

**Issue by SDedik** [MicrosoftDocs/PowerShell-Docs#6708]
Apparently *.schema.mof files cannot have property named `Method` like so:
```
[ClassVersion("1.0.0.0")]
class myResource : OMI_BaseResource
{
  ...
  [Write, Description("Notification dismissal method"), ValueMap{"Auto","UserAction"}, Values{"Auto","UserAction"}] string Method;
  ...
};
```
With such schema file in place, Invoke-DscResource (and likely DSC engine) fails to find resource and complains that ModuleName has to be specified even though it has been provided clearly
```
Invoke-DscResource -Name myResource -Method Test -ModuleName myModule -Property @{IsSingleInstance = "Yes"; ...}
Invoke-DscResource : Resource myResource was not found as one of the builtin resources. Please add -ModuleName parameter to include external resources.
```

As soon as the `Method` property is renamed to anything else, resource starts working as it should.

This behavior has to be documented along with list of other keywords which are reserved and can't be used by resource developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f431b7e7-383a-c543-5ef9-0a67c70110c1
* Version Independent ID: f3c530e3-27de-6e32-42e7-a22362b11fac
* Content: [Writing a custom DSC resource with MOF - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/resources/authoringresourcemof?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/resources/authoringResourceMOF.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/resources/authoringResourceMOF.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@mgreenegit Who can confirm this information and any other reserved words?

**Comment by sdwheeler** [comment]
Here is the list of Mof reserved keywords 
 
"TRUE", "FALSE", "NULL", "BOOLEAN", "SINT8", "UINT8", "SINT16", "UINT16", "SINT32", "UINT32", "SINT64", "UINT64", "REAL32", "REAL64", "DATETIME", "CHAR16", "STRING", "REF", "SCOPE", "CLASS", "ASSOCIATION", "INDICATION", "QUALIFIER", "PROPERTY", "REFERENCE", "METHOD", "PARAMETER", "ANY", "FLAVOR", "ENABLEOVERRIDE", "DISABLEOVERRIDE, "RESTRICTED", "TOSUBCLASS", "TRANSLATABLE", "INSTANCE", "OF", "AS", "TOINSTANCE"
