### ISSUE TITLE
The Powershell executable filename is incorrect in these instructions

### ISSUE THREAD

**Issue by TonyG99** [MicrosoftDocs/PowerShell-Docs#6713]
The instructions on this page state that the executable for making exceptions to execution policies is called 'pwsh.exe', but on my system at least, it is 'powershell.exe'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ad4103-af4a-a7bc-d268-d26f4dabf892
* Version Independent ID: cfa0b0d5-be1f-b9d2-533d-61bfa6051292
* Content: [about_Execution_Policies - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The documentation is correct. The name of the executable was changed to `pwsh.exe` for the release of PowerShell v6 (and higher). You were reading the documentation for PowerShell v7.

**Comment by TonyG99** [comment]
Sean -- I was reading the documentation that my (presumably < v6)
version of Powershell directed me to in order to resolve an execution
policy issue.

**Comment by sdwheeler** [comment]
Please see https://docs.microsoft.com/powershell/scripting/how-to-use-docs. This explains the how to use the version picker for docs.

If you were directed to the wrong version then you probably need to update your help. Run: `Update-Help -Force`. The **Force** parameter is important.

Regardless, the documentation is correct for the version displayed. Note that you can have PowerShell 5.1, v6.x, and v7.x installed on the same machine.

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> dir $PSHOME\*.exe

    Directory: C:\Program Files\PowerShell\7

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           7/15/2020 10:13 PM         312192 pwsh.exe

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.7
PSEdition                      Core
GitCommitId                    6.2.7
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> dir $PSHOME\*.exe


    Directory: C:\Program Files\PowerShell\6

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         7/15/2020 10:30 PM         276352 pwsh.exe

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


[Tue 06:36:32PM]
PS C:\> dir $PSHOME\*.exe


    Directory: C:\Windows\System32\WindowsPowerShell\v1.0


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         12/7/2019   3:10 AM         452608 powershell.exe
-a----         12/6/2019  11:05 AM         212992 powershell_ise.exe
```
