### ISSUE TITLE
Very good examples

### ISSUE THREAD

**Issue by maurog69** [MicrosoftDocs/PowerShell-Docs#6721]
I liked the examples that you gave.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b4866af-35b6-b7e7-1423-2d4f76fd9f0b
* Version Independent ID: 08f2c662-66be-6889-27cb-6c4a0320717a
* Content: [Get-Process (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-process?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Get-Process.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-Process.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@maurog69 Thanks!
