### ISSUE TITLE
Description cut off into multiple cells

### ISSUE THREAD

**Issue by chandranelluri** [MicrosoftDocs/PowerShell-Docs#6728]
[Enter feedback here]
Minor formatting issue. Description of some table fields like "-like" and "-match" split into multiple cells. It feels as if text is cut off. If possible make description in one single line or make it multi-line in same cell for better reading experience.

If it is expected behaviour, feel free to close this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50bd0dc3-279b-baea-5c19-823e0bc44534
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This is by design due to a limitation on how about_ files are processed for the help system.
