### ISSUE TITLE
How to use with managed service accounts

### ISSUE THREAD

**Issue by StephenBethke** [MicrosoftDocs/PowerShell-Docs#6729]
This page offers no help for creation of services using managed service accounts.  Please could you make this part of the remarks section perhaps?  If it's not possible to use New-Service with managed service accounts, please state that clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b33e075a-32ea-b62d-a192-ad64996c85c3
* Version Independent ID: 4c55287b-3830-69b1-3eb7-33824b6181db
* Content: [New-Service (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/New-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/New-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
The documentation for Managed Service Accounts (MSA) can be found at https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd548356(v=ws.10).

The `New-Service` cmdlet does not have any special handling for MSAs. It only attempts to configure the logon credentials you provide. Assuming you have configured and installed the account properly, you should be able to create a PSCredential object for the MSA with a blank password.

**Comment by StephenBethke** [comment]
Thanks for the info.
