### ISSUE TITLE
Example of filtering for Export-Counter 

### ISSUE THREAD

**Issue by jknowldenic** [MicrosoftDocs/PowerShell-Docs#6732]
'Example 4: Re-log existing data' does not work.  
The $LowSpace variable is only being assigned a single property of $All.  This results in an object of type 'PerformanceCounterSample' whereas Export-Counter expects an input of type 'PerformanceCounterSampleSet'.

The intuitive approach to change 
`$LowSpace = $All.CounterSamples | where {$_.CookedValues -lt 15}`
to
`$LowSpace = $All | where {$_.CounterSamples.CookedValues -lt 15}`
doesn't help.  That results in capturing the entire sample set as though no filtering had been performed.

I for one would love to know how to accomplish this task of filtering counters and exporting the subset into the standard file format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e6a8ff9-8fd8-9bcb-56a4-aff60515eaab
* Version Independent ID: 97aac461-036b-107f-31b3-4bc8dc2cff55
* Content: [Export-Counter (Microsoft.PowerShell.Diagnostics) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/export-counter?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Diagnostics/Export-Counter.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Diagnostics/Export-Counter.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
It should be `CookedValue` - singluar.  I did a test creating a quick log file of processor time. This example works on that log:

```
$all.CounterSamples | where { $_.Path -like '*% processor time*' -and $_.CookedValue -gt 10}
```

**Comment by jknowldenic** [comment]
Good catch on that typo.  The issue I was trying to point out however was not with the filtering, rather that the results cannot be passed to Export-Counter.

Extending that example one step further:
`$all.CounterSamples | where { $_.Path -like '*% processor time*' -and $_.CookedValue -gt 10} | Export-Counter -Path LowDiskSpace.blg`
will throw an error for each sample
`Export-Counter : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that 
take pipeline input.`

**Comment by sdwheeler** [comment]
Ok, I got this to work:

```
$all | where { $_.CounterSamples.Path -like '*% processor time' -and $_.CounterSamples.CookedValue -gt 10} | Export-Counter C:\temp\test.blg
```
