### ISSUE TITLE
Measure example not working in Powershell 5.1

### ISSUE THREAD

**Issue by guerraga** [MicrosoftDocs/PowerShell-Docs#6736]
This code in this page is not woking in Powershell versión 5.1.19041.1

```
1..10 | Measure-Object -Property {($_ % 3) -eq 0} -Sum
Measure-Object : No se encuentra la propiedad "($_ % 3) -eq 0" en la entrada de ningún objeto.
En línea: 1 Carácter: 9
+ 1..10 | Measure-Object -Property {($_ % 3) -eq 0} -Sum
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Measure-Object], PSArgumentException
    + FullyQualifiedErrorId : GenericMeasurePropertyNotFound,Microsoft.PowerShell.Commands.MeasureObjectCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b144603-b8b3-8c0d-d053-fd2736c64631
* Version Independent ID: aade244f-3f86-b43f-c12d-7805f58d12bb
* Content: [about_Calculated_Properties - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_calculated_properties?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
You are right. `Measure-Object` does not support this in v5.1.
