### ISSUE TITLE
"Launch Quick Open on Windows..."

### ISSUE THREAD

**Issue by RixtaLu** [MicrosoftDocs/PowerShell-Docs#6739]
Hello,

Did not know where else to go, I googled what Quick Open was and no other mention of it except on this Powershell Doc.  I know this isn't support but I haven't found anything on it in support, but it's ctrl+P in Linux and cmd+P in mac.  What is it and how do I launch it on Windows?

Thanks,
R.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919fe42a-edb9-c950-1405-ae723bb6a48e
* Version Independent ID: 781d1d43-834f-7e39-cc60-8905d5803f9b
* Content: [Using Visual Studio Code for PowerShell Development - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode?view=powershell-7)
* Content Source: [reference/docs-conceptual/dev-cross-plat/vscode/using-vscode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dev-cross-plat/vscode/using-vscode.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
It is the same in Windows, as the article says. You can see this by looking at the Key Bindings.

![image](https://user-images.githubusercontent.com/19415881/95655431-dcdcdc00-0acc-11eb-9d2f-932eb5193dbf.png)
