### ISSUE TITLE
Example command in the note section of "Computers with the PackageManagement Preview installed"

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/PowerShell-Docs#6747]
I believe the note that reads:

> PackageManagement Preview was a downloadable component that made PowerShellGet available to PowerShell versions 3 and 4, but it is no longer available. To test if it was installed on a given computer, run Get-Module -ListAvailable PowerShellGet.

Should be `Get-Module -ListAvailable PackageManagement` instead of `PowerShellGet`. Do you agree?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The PackageManagement Preview contained both PowerShellGet and PackageManagement. So the command provided is enough to determine if the preview version is installed.
