### ISSUE TITLE
Target is an invalid member

### ISSUE THREAD

**Issue by robharman** [MicrosoftDocs/PowerShell-Docs#6760]
For the DSC Environment resource, any time I specify `Target = "Machine"` I receive an invalid member error:

For the following code:
```
Configuration TestConfig {
    Node LocalHost {
        Environment HomeScriptAssets {
            Ensure              =   'Present'
            Name                =   'HomeScriptAssets'
            Value               =   "$HomeScriptAssets"
            Target              =   "Machine"
        } 
    }
}
```

I receive the error in PS Core 7.1:
```
ParserError: C:\source\PowerShell\WindowsServer\0_InitialState.ps1:57
Line |
  57 |              Target              =   "Machine"
     |              ~~~~~~
     | The member 'Target' is not valid. Valid members are 'DependsOn', 'Ensure', 'Name', 'Path',
     | 'PsDscRunAsCredential', 'Value'.

```
I receive the equivalent error message on Windows PS4, Windows PS5.1. I unfortunately do not have a PS5.0 machine to test on. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce1333c-cef3-cf6c-960b-cbbf275a7803
* Version Independent ID: 0aa33a23-27a9-4d7e-c7ea-c0e9c165750f
* Content: [DSC Environment Resource - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/environmentresource?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/reference/resources/windows/environmentResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/reference/resources/windows/environmentResource.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The version of the the `Environment` resource that ships in Windows does not include the **Target** property. It was added in an update available in the PowerShell Gallery. See https://github.com/PowerShell/PSDscResources/blob/dev/README.md for more information about the updated module.

**Comment by sdwheeler** [comment]
@shiproom We need to decide which version needs to be documented here.

**Comment by robharman** [comment]
Thanks for the link.  Should the rest of documentation for the built-in resources be treated the same? As in, check against the PSDscResources module? Or is the recommended implementation for DSC scripts the module, rather than the resources that ship with Windows?
