### ISSUE TITLE
Warning missing that usage of this command corrupts manifest file

### ISSUE THREAD

**Issue by jformacek** [MicrosoftDocs/PowerShell-Docs#6767]
Hello,
Usage of this command on existing module manifest breaks it's content. I wanted to use this command inside build pipeline to update ModuleVersion attribute, but found at least 2 things that got broken on my manifest module:
- **RequiredAssembles** attribute: I have something like below in my manifest file, and `Update-ModuleManifest` removes this attribute completely
```
RequiredAssemblies = if($PSEdition -eq 'Desktop') {@('lib\net45\someAssembly.dll')} else {$null}
```
- **PrivateData** attribute: I have added additional content as hashtable `Messages` to module's `PrivateData `as addtional hashtable aside from `PSData `as shown below, however, `Update-ModuleManifest` changes the `Messages `hashtable to `Messages = 'System.Collections.Hashtable'`, which breaks the logic of module
```
PrivateData = @{
    Messages = @{
        NotInitialized = 'Call Initialize-Module before running other cmdlets.'
    }
    PSData = @{
    # ... standard content
    }
```

---
Would be great to update the command so as it does not change the attributes that are not passed from command line, or at least document here what gets changed/reset when command is run, so as users are not surprised after running it.

Thank you,
Jiri

---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b6c2e3-f28a-c1a7-7e78-6c0d26001eea
* Version Independent ID: 304167af-fdd4-e3aa-c3e3-79a912844e8a
* Content: [Update-ModuleManifest (PowerShellGet) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/powershellget/update-modulemanifest?view=powershell-7)
* Content Source: [reference/7.0/PowerShellGet/Update-ModuleManifest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PowerShellGet/Update-ModuleManifest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
@SydneyhSmith What is the expected behavior here? We should file an issue. Which repo do you want this in?

**Comment by SydneyhSmith** [comment]
@sdwheeler it would be best to move this issue to https://github.com/PowerShell/PowerShellGetv2

**Comment by sdwheeler** [comment]
@jformacek Can you submit an issue in https://github.com/PowerShell/PowerShellGetv2/issues?

**Comment by sdwheeler** [comment]
After reviewing the source code, it appears that `Update-ModuleManifest` supports single values or arrays for extra data. See https://github.com/PowerShell/PowerShellGetv2/blob/f45bfe1a66df7063aa8de10fc4f147fdc23639af/src/PowerShellGet/private/functions/Get-PrivateData.ps1#L61-L79

**Comment by sdwheeler** [comment]
I copied this issue to the PowerShellGet repo.
