### ISSUE TITLE
Incorrect command for restarting ssh service on Ubuntu

### ISSUE THREAD

**Issue by lahell** [MicrosoftDocs/PowerShell-Docs#6769]
According to this documentation, the command for restarting ssh server on Ubuntu is `sudo service sshd restart`, but it should be `sudo service ssh restart`.

Would also be helpful if the docs could include how to generate keys (`sudo /usr/bin/ssh-keygen -A`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e79ea6-1d79-6147-aa3e-362b04bc7528
* Version Independent ID: 8877b05f-1f52-8c75-2d7d-5100cc52c4cb
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
http://manpages.ubuntu.com/manpages/xenial/man1/ssh-keygen.1.html
