### ISSUE TITLE
Add note about ability to bypass confirmation

### ISSUE THREAD

**Issue by mpietihsm** [MicrosoftDocs/PowerShell-Docs#6770]
It might be useful to add a note at the bottom about how to bypass the confirmation prompt. This is taken from the Remove-ADUser cmdlet:

To bypass prompting for confirmation before removal, you can specify -Confirm:$False when using this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a04bbb7-f6d0-c2a3-298a-fdb0090583ce
* Version Independent ID: a352c3ec-59c4-0417-a46e-c47ebd4b5db1
* Content: [Clear-RecycleBin (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/clear-recyclebin?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Clear-RecycleBin.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Clear-RecycleBin.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
Example #3 covers that information.
