### ISSUE TITLE
The `maml:title` grouping works per `maml:alertSet`, not `maml:alert`

### ISSUE THREAD

**Issue by thedavecarroll** [MicrosoftDocs/PowerShell-Docs#6776]
"The following XML shows an `<maml:alertset>` node with two notes. Notice that each note has an optional `<maml:title>` tag (titles can be used to group any set of `<maml:alert>` tags), and that each note has a blank line following the content for spacing."

After performing some testing, it appears that the `<maml:title>` tag grouping only works when one such tag is used per `<maml:alertSet>` not per `<maml:alert>`.

The example from the document
```xml
<maml:alertSet>
  <maml:title>title for Note 1</maml:title>
  <maml:alert>
    <maml:para> Note 1</maml:para>
    <maml:para></maml:para>
  </maml:alert>
  <maml:title>title for Note 2</maml:title>
  <maml:alert>
    <maml:para> Note 1</maml:para>
    <maml:para></maml:para>
  </maml:alert>
</maml:alertSet>
```

produces this output.

```console
NOTES
    {title for Note 1, title for Note 2}

        Note 1

        Note 1
```

When the following is used, the proper grouping occurs.

```xml
<maml:alertSet>
  <maml:title>title for Note 1</maml:title>
  <maml:alert>
    <maml:para>Note 1</maml:para>
    <maml:para>Note a</maml:para>
  </maml:alert>
</maml:alertSet>
<maml:alertSet>
  <maml:title>title for Note 2</maml:title>
  <maml:alert>
    <maml:para>Note 2</maml:para>
  </maml:alert>
</maml:alertSet>
```

```console
NOTES
    title for Note 1

        Note 1

        Note a

    title for Note 2

        Note 2

```

Note that I removed the leading space in the `<maml:para>` values and I removed the empty `<maml:para></maml:para>` tag.

The following shows `MamlCommandHelpInfo#alertSet` for the updated example.
 
```powershell
PS> $info.alertSet
```
```console

title for Note 1

    Note 1

    Note a

title for Note 2

    Note 2

```
```powershell
PS> $info.alertSet[0]
```

```console

title for Note 1

    Note 1

    Note a

```
```powershell
PS> $info.alertSet[1]
```

```console
title for Note 2

    Note 2

```
```powershell
PS> $info.alertSet[0] | Format-List
```

```console
title : title for Note 1
alert : {@{Text=Note 1
        }, @{Text=Note a}}
```
```powershell
PS> $info.alertSet[1] | Format-List
```

```console
title : title for Note 2
alert : {@{Text=Note 2}}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d699605f-1f1c-0e8b-49da-57a91cd654de
* Version Independent ID: 4375fee9-b612-ad07-7ebc-3329e8c1c63f
* Content: [How to Add Notes to a Cmdlet Help Topic - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/help/how-to-add-notes-to-a-cmdlet-help-topic?view=powershell-7)
* Content Source: [reference/docs-conceptual/developer/help/how-to-add-notes-to-a-cmdlet-help-topic.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/help/how-to-add-notes-to-a-cmdlet-help-topic.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by thedavecarroll** [comment]
Does this merge signify that multiple `<maml:alertSet>` will not be supported, even though they appear to work?

The `<maml:title>` tag appears to be per `<maml:alertSet>`. The intent of this issue was not to squash or restrict the use of `<maml:title>`, but rather to provide an example of how to use multiple `<maml:alertSet>` correctly.

Having the option for multiple `<maml:alertSet>` and, by extension `<maml:title>`, as in the example provided in this issue, could be beneficial for some help writers.

Thank you.

**Comment by sdwheeler** [comment]
MAML Supports multiple `<maml:alertSet>` elements. But the PowerShell help system (PlatyPS mostly) only supports one.
