### ISSUE TITLE
Link to Documentation is incorrect

### ISSUE THREAD

**Issue by df2k2** [MicrosoftDocs/PowerShell-Docs#6777]
# Documentation Issue

The link configured to the documentation is incorrect in the github settings:

>**About**
>
> The official PowerShell documentation sources
>
> docs.microsoft.com**.com**/powershell 

![image](https://user-images.githubusercontent.com/4868368/96546010-7ea3bc00-1277-11eb-8c6a-b930c5effd01.png)

## Context of the issue

- URL to the article (Docs or GitHub URL): **https://github.com/MicrosoftDocs/PowerShell-Docs**
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No

## Detailed description of the issue

The URL to the docs from the github repo settings is incorrect, as it includes an extra `.com`, which invalidates the URL and leads to confusion.

**Comment by sdwheeler** [comment]
Fixed
