### ISSUE TITLE
PromptForCredential example has username and password flipped

### ISSUE THREAD

**Issue by mbourgon** [MicrosoftDocs/PowerShell-Docs#6789]
PromptForCredential example says it's (..... "","UserNameNS"), when the syntax is the other way around (...."UserNameNS","")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 222ad025-64b3-9b20-fef2-b1745166fdef
* Version Independent ID: c98699f2-814c-63b8-edf5-3293ea1aa99f
* Content: [Get-Credential (Microsoft.PowerShell.Security) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-credential?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @TravisEz13
* Microsoft Alias: **tplunk**

**Comment by sdwheeler** [comment]
The example is correct

```
PS C:\Git> $host.ui.PromptForCredential

OverloadDefinitions
-------------------
pscredential PromptForCredential(string caption, string message, string userName, string targetName)
pscredential PromptForCredential(string caption, string message, string userName, string targetName,
  System.Management.Automation.PSCredentialTypes allowedCredentialTypes,
  System.Management.Automation.PSCredentialUIOptions options)
```

In this example:
- caption = "Need credentials"
- message = "Please enter your user name and password."
- userName = ""
- targetName = "NetBiosUserName"
