### ISSUE TITLE
Error types?

### ISSUE THREAD

**Issue by BentChainRing** [MicrosoftDocs/PowerShell-Docs#6797]
Looking up error types returned by Remove-item cmdlet and there is no reference to them on this page. Not even a link? 

How do you expect to encourage people to write scripts if you do not include Error recovery-related info in the cmdlet description. 

Ugh. Such a waste of my time. Now I have to do more searching.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701c49d0-1949-61b8-2edd-651ab2714f09
* Version Independent ID: 0b18157a-a191-4733-90db-7dfceda2c99f
* Content: [Remove-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
I created an feature request in the PowerShell repo to add an attribute that would allow us to discover the errors returned by a cmdlet so that it could be reflected into the docs.  See PowerShell/PowerShell#13882.
