### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jmedfo** [MicrosoftDocs/PowerShell-Docs#6799]
Probably been asked a million times but is there anyway a simpleton can download the 'docs' from Microsoft re things e.g. learning Azure or Powershell so they can be viewed off line? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
For PowerShell, the cmdlet reference can be downloaded using `Update-Help -Force`. Then you use `Get-Help` to view the help topics. But this does not include the "conceptual" articles. Some documentation sets on docs.microsoft.com have a `Download PDF` button in the bottom left corner of the page. The PowerShell docs do not support this feature. 

You can download the Markdown source files for the documentation from GitHub:
![image](https://user-images.githubusercontent.com/19415881/97184981-84b10580-176d-11eb-8c73-8ffaf29588bd.png)

The PowerShell documentation source is at: https://github.com/MicrosoftDocs/PowerShell-Docs
