### ISSUE TITLE
about_Functions_Advanced_Parameters: Does not mention [SupportsWildcards()]

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/PowerShell-Docs#6803]
While I was working with Visual Studio Code, I ran into the following code snippet:

```PowerShell
    # Specifies a path to one or more locations. Wildcards are permitted.
    [Parameter(Mandatory=$true,
               Position=Position,
               ParameterSetName="ParameterSetName",
               ValueFromPipeline=$true,
               ValueFromPipelineByPropertyName=$true,
               HelpMessage="Path to one or more locations.")]
    [ValidateNotNullOrEmpty()]
    [SupportsWildcards()]
    [string[]]
    $ParameterName
```

The third line from the bottom reads: `[SupportsWildcards()]`. I cannot find any mention of this attribute in `about_Functions_Advanced_Parameters`. [I could only confirm that it is valid](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.supportswildcardsattribute?view=powershellsdk-7.0.0).

But what does it do? Is it purely informative?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c38cef-73fb-7c5f-ecd3-66a344dff335
* Version Independent ID: 4eac80f8-61be-4d0f-d657-a007ba81cf53
* Content: [about_Functions_Advanced_Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
It is mostly informative, but it can be discovered. Which is useful for knowing if a parameter supports wildcards. PlatyPS uses the attribute when creating the documentation for a parameter.

**Comment by sdwheeler** [comment]
Here is an example. This cmdlet is part of the PlatyPS module:

```
PS C:\Git> (Get-Command Get-MarkdownMetadata).Parameters.Path.Attributes

TypeId
------
System.Management.Automation.SupportsWildcardsAttribute
System.Management.Automation.ParameterAttribute
System.Management.Automation.ArgumentTypeConverterAttribute
```

**Comment by skycommand** [comment]
PlatyPS? I'm not sure what it is. (PS is PowerShell obviously, and "platy" probably means "braided". Something that braids PowerShell and makes it pretty? :shrug:) But it's repo says "Use markdown as the source of truth and remove other types of help"; boy, I'm all for that.

But I digress. I guess the takeaway from this discussion is that I haven't ran into [deep magic](https://en.wikipedia.org/wiki/Magic_(programming)#Variants), am I right? And if that's correct, I believe we can safely document it in two lines and close the case. Or just remove its mention in other About_ pages.

**Comment by sdwheeler** [comment]
Short answer - yes we can add it to the documentation.

We use PlatyPS to create the documentation. I chose it as an example because it has cmdlets that actually use that attribute. There is an issue in PowerShell (https://github.com/PowerShell/PowerShell/issues/4716) to get SupportsWildcards added to the PowerShell cmdlets.
