### ISSUE TITLE
instructions not clear for 3rd party certs

### ISSUE THREAD

**Issue by james-nesbitt** [MicrosoftDocs/PowerShell-Docs#6813]
This page clarifies how to use self-signed certificates, with the signing process being centered on that option.  Early in the page, two options are specified for the signing cert, the latter, which is the more professional, is then ignored.

What a sysadmin/DevOps person like me wants to know is "how can I sign a script with my official cert/key".  What I would really want to be able to do is sign a script without leaving my cert in any environment (as a part of an automation pipeline.)

This doc is playground focused.  If it is to be taken as serious, it should meet production use-cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d846aff2-0c3a-bbd3-94de-c7e496fe8ec7
* Version Independent ID: 5d218683-79ce-326b-31bf-4dfa836b8ba6
* Content: [about_Signing - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The purpose of this article is to explain the code signing features of PowerShell. The mechanics of using a 3rd-party certificate for signing is the same as using a self-signed certificate. Explaining certificate management in a CI/CD pipeline is out of scope for this article and for PowerShell docs in general.
