### ISSUE TITLE
Is there a way to submit a new article translated to the PowerShell documentation?

### ISSUE THREAD

**Issue by SilkyFowl** [MicrosoftDocs/PowerShell-Docs#6832]
# Documentation Issue

I want to help improve Powershell's Japanese Help in any way I can.
So I read about this period and decided to fork and clone the repository of translated articles and create a new blanch from `staging`.

>All pull requests should target the `staging` branch. Changes should never be submitted to the live branch. Changes made in the `staging` branch get merged into live, overwriting any changes made to live.

However, the `staging` branch was last updated three years ago.

![image](https://user-images.githubusercontent.com/16532218/97851000-215c4000-1d38-11eb-994d-6be1428ba7c2.png)

So I searched the Document for other guidelines for translated articles, but I couldn't find any articles that I thought might be valid.
Let me know if there is a Document I should read if I want to create a translated article.
Or do I have to start by updating the `staging` blanch for three years if I want to PullRequest a translated article?

![image](https://user-images.githubusercontent.com/16532218/97849740-5798c000-1d36-11eb-9e88-e91998f67c21.png)

## Context of the issue

- URL to the article (Docs or GitHub URL):[How to submit pull requests](https://docs.microsoft.com/en-us/powershell/scripting/community/contributing/pull-requests?view=powershell-7#target-the-correct-branch) , [MicrosoftDocs/powerShell-Docs.ja-jp](https://github.com/MicrosoftDocs/powerShell-Docs.ja-jp/tree/staging)
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
The guidelines published in the Contributor Guide do not apply to the localized repositories. All new article contributions need to be made in English to this repository. Documentation is then translated into 17 different languages. If you find a problem that is factual or technical, you need to start in the English repository. All translations flow from here. 

If you find a problem with a translation (grammar or word choice) then you should open an issue in the localized repository. You can suggest an alternate translation in the issue. Our localization team reviews the issues and makes any changes as necessary. You can submit a PR to the `live` branch in the localized repository with the changes you want. But start with an issue explaining the problem and link the PR to the issue.

Is there something specific you want to change?
