### ISSUE TITLE
Doc new `-Raw` switch to `ConvertTo-Json`

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#6847]
# Summary of the new document or enhancement

- List of articles that need to be updated: ConverTo-Json cmdlet help
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/13989
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/issues/5797

**Comment by sdwheeler** [comment]
The PowerShell Committee decided not to do this. Closing.
