### ISSUE TITLE
Relations between ConfigurationModeFrequencyMins and RefreshFrequencyMins parameters is not documented comprehensively

### ISSUE THREAD

**Issue by SDedik** [MicrosoftDocs/PowerShell-Docs#6848]
At first reading about `ConfigurationModeFrequencyMins` and `RefreshFrequencyMins` parameters relations seems straightforward.
The node is configured to use Pull server. It queries it for updated configuration every `RefreshFrequencyMins`. If new configuration is discovered it gets applied immediately. If no new configuration is discovered, nothing happens. Every `ConfigurationModeFrequencyMins` the current configuration is checked and applied.
However, **in reality it doesn't work this way!**

#### Note number one
There is this [article](https://devblogs.microsoft.com/powershell/understanding-meta-configuration-in-windows-powershell-desired-state-configuration), which dwells on a requirement for `ConfigurationModeFrequencyMins` to be a multiplication of `RefreshFrequencyMins`. Is this still true for PowerShell 5.1 (latest builds of Windows 10 / Server 2019)?

#### Note number two
According to observation, the real behavior is that `RefreshFrequencyMins` triggers current configuration being checked and applied without any regard to `ConfigurationModeFrequencyMins` whatsoever.
Consider following LCM configuration:
```
[DscLocalConfigurationManager()]
Configuration LCMConfig {
    Settings {
        ConfigurationMode               = "ApplyAndAutoCorrect"
        ConfigurationModeFrequencyMins  = 120
        DebugMode                       = "None"
        RefreshMode                     = "Pull"
        RefreshFrequencyMins            = 30
    }
...
```
Note that `DebugMode` is set to None and should not affect LCM engine behavior. Partial Configurations are **not used**! This is plain and simple Named Configuration setup - there is a single mof file for the node on the pull server.
Expected behavior is that node will query pull server every 30 minutes. Assuming there are no updates on pull server, node will do nothing. Once every 2 hours it should run consistency check and bring all resources back to compliance status.
However, I can clearly see that every 30 minutes my node checks for any updated configurations against pull server AND applies current configuration:
```
The DscTimer is running LCM method PerformRequiredConfigurationChecks with the flag set to 5.

Job {3F1DE355-1F40-11EB-882B-005056B8DD81}: 
Operation Consistency Check or Pull started by user sid S-1-5-20 from computer NULL.

Job {3F1DE355-1F40-11EB-882B-005056B8DD81} : 
WebDownloadManager for AgentId 056340BE-AF94-11E9-87E7-00155D653FB6 Do-DscAction command, GET call result: Ok.

Job {3F1DE355-1F40-11EB-882B-005056B8DD81} : 
Running consistency engine.
```
And then I can see how every resource defined for my node is being applied. I can even verify that by manually changing a setting governed by node's configuration to something else. The setting is reverted back to compliance status every 30 minutes instead of every 2 hours!

Every 2 hours as per configuration settings I see:
```
The DscTimer is running LCM method PerformRequiredConfigurationChecks with the flag set to 1.

<Configuration being applied...>

Job {BCC4C19F-1F1D-11EB-882B-005056B8DD81} : 
Consistency engine was run successfully.
```

Summarizing, this means two things:
1. `ConfigurationModeFrequencyMins` setting is completely irrelevant, because consistency check using cached local configuration is always triggered whenever `RefreshFrequencyMins` occurs.
2. Whenever `ConfigurationModeFrequencyMins` and `RefreshFrequencyMins` events are happening at the same time, the node ends up applying configuration twice, which is plain waste of time and resources (note timestamps):
```
Get-ChildItem -Path 'C:\Windows\system32\Configuration\ConfigurationStatus' | Sort-Object -Property LastWriteTime

    Directory: C:\Windows\system32\Configuration\ConfigurationStatus

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        11/5/2020  10:58 AM         169922 {4ECC5A75-1F4D-11EB-882C-005056B8DD81}-0.details.json <---- node booted
-a----        11/5/2020  10:58 AM          57664 {4ECC5A75-1F4D-11EB-882C-005056B8DD81}-0.mof
-a----        11/5/2020  11:27 AM         169920 {7F8DB37E-1F51-11EB-882C-005056B8DD81}-0.details.json <---- RefreshFrequencyMins
-a----        11/5/2020  11:27 AM          57664 {7F8DB37E-1F51-11EB-882C-005056B8DD81}-0.mof
-a----        11/5/2020  11:57 AM         169920 {B08DFA37-1F55-11EB-882C-005056B8DD81}-0.details.json <---- RefreshFrequencyMins
-a----        11/5/2020  11:57 AM          57664 {B08DFA37-1F55-11EB-882C-005056B8DD81}-0.mof
-a----        11/5/2020  12:27 PM         169920 {E184C3B1-1F59-11EB-882C-005056B8DD81}-0.details.json <---- RefreshFrequencyMins
-a----        11/5/2020  12:27 PM          57664 {E184C3B1-1F59-11EB-882C-005056B8DD81}-0.mof
-a----        11/5/2020  12:57 PM         169920 {12704ACE-1F5E-11EB-882C-005056B8DD81}-0.details.json <---- RefreshFrequencyMins
-a----        11/5/2020  12:57 PM          57664 {12704ACE-1F5E-11EB-882C-005056B8DD81}-0.mof
-a----        11/5/2020  12:58 PM         168426 {1F58735F-1F5E-11EB-882C-005056B8DD81}-0.details.json <---- ConfigurationModeFrequencyMins
-a----        11/5/2020  12:58 PM          57664 {1F58735F-1F5E-11EB-882C-005056B8DD81}-0.mof
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6986f2-ea24-1bcd-7bba-04f18cac63ff
* Version Independent ID: 41a9cf31-b59c-4845-37c2-0e9cb6c19b23
* Content: [Configuring the Local Configuration Manager - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/managing-nodes/metaconfig?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/managing-nodes/metaConfig.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/managing-nodes/metaConfig.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@mgreenegit Can you confirm the behavior?

**Comment by SDedik** [comment]
Any comments on this issue?

**Comment by chasewilson** [comment]
Hello @SDedik , Thanks for the feedback here. So from what I've gathered is the real use case for these settings should be reversed in your situation unless there are extenuating circumstances.

The ConfigurationModeFrequency will check the local configuration and ensure the encironment matches it. and make changes if necessary.

The refresh frequency will check with the pull server to see if there are any configuration updates from the Pull Server, then it will check the local environment to ensure accuracy for the configuration.  A normal situatuation will have this interval at a longer period to save on network traffic. Since most configurations stored on the pull server wont be changed all the time, except in niche circumstances, you would want the ConfigurationModeFrequency time to be the main driver in maintaining the environment. 

When the two times do match up, they will run twice but it should only run the check and shouldn't be a big resource drain.  Especially when configuration times are set to run during low traffic times like off work hours. 

Feel free to leave more feedback or questions. I will be updating the article to make it clear that this is the typical use case.

**Comment by SDedik** [comment]
Hello @chasewilson, thank you for your reply.

Let me define the premise first so that we are discussing the same

### The premise
Typical company network, nothing particular, no specifics, just most typical imaginary case. This network has some amount of Windows machines, which provide various services and are managed by DSC (because this is what we are discussing). Machines are long-running, deployed long time ago and providing the service ever since. There is a DSC pull-server in the network and machines are configured to poll it and apply configuration. Again, nothing fancy, just plain and simple Named Configurations setup.
Let's make this a baseline for our discussion.

### The part I fully agree with
> The ConfigurationModeFrequency will check the local configuration and ensure the encironment matches it. and make changes if necessary.

Yes, this is clear as day from the documentation. For the sake of our discussion I would also add that whenever `ConfigurationModeFrequencyMins` timer triggers, the node do not attempt to contact pull-server whatsoever.

### The confusing part
> The refresh frequency will check with the pull server to see if there are any configuration updates from the Pull Server, then it will check the local environment to ensure accuracy for the configuration.

There are two possible outcomes whenever the `RefreshFrequencyMins` triggers:
- There is an updated configuration on the pull-server. In which case your statement is absolutely correct. The node downloads fresh configuration and applies it immediately
- There is no updated configuration on the pull-server. This is where it gets confusing. From the documentation point of view and from logical point of view this should be the end of the process. No new configuration - end of the line, `RefreshFrequencyMins` job is done. However, on practice I see that this is not true (see initial post in this discussion). So the primary question here is - when there are no updates on the pull-server, should the `RefreshFrequencyMins` re-apply existing configuration? Is it expected behavior or...?

> A normal situatuation will have this interval at a longer period to save on network traffic. Since most configurations stored on the pull server wont be changed all the time, except in niche circumstances, you would want the ConfigurationModeFrequency time to be the main driver in maintaining the environment

This is where I disagree completely. In general, the natural desire of every administrator is to be able to make a change in configuration and let it propagate across the environment within a reasonable amount of time. What is reasonable amount of time? Well, it depends, but generally it is as low so that few of such intervals can fit into a working day. Why is that? Well, because whenever I make a change to configuration, I want it to be in effect while I'm still at work and can react to things, while I can monitor if my change is behaving according to plan. Last thing I want is to make a change in the morning only to discover next day that something went wrong in the middle of the night. There are other arguments for that case, but I will not dwell into that unless you ask me to.
Another reason why I want `RefreshFrequencyMins` to be lower than `ConfigurationModeFrequencyMins` is because the former is expected to be much less expensive than latter.

### Expensive vs inexpensive operations
- To poll pull-server for an update is inexpensive (cheap) operation: only a few web-requests.
- To apply configuration is expensive operation. And it gets more expensive the bigger configuration itself gets.

Further on, you think that running `ConfigurationModeFrequencyMins` saves on network traffic? Not really, no. The pull-server isn't queried, which is true, but what about configuration status reporting? It is still happening. What about all network related activities defined in the configuration itself? Domain users being members of the local groups, files are of up-to-date versions - all of that is still happening. Yes, this is highly dependent on particular configuration, but let's be realistic - that traffic does exist and by making `ConfigurationModeFrequencyMins` main driver you are saving miniscule amount to pull-server, but causing more traffic elsewhere.

In this light you absolutely correctly said that _most configurations stored on the pull server wont be changed all the time_ making `RefreshFrequencyMins` much preferable because it is much less expensive overall (cpu + memory + disk + network) compared to `ConfigurationModeFrequencyMins`.

### Summary
- `RefreshFrequencyMins` is expected to be lower than `ConfigurationModeFrequencyMins`.
- `RefreshFrequencyMins` applying cached configuration when there are no updates on the pull-server looks like a bug.

**Comment by SDedik** [comment]
> When the two times do match up, they will run twice but it should only run the check and shouldn't be a big resource drain.

On contrary. This is how much time checks are taking on most of my nodes because of configuration size and some resource implementations (Firewall resource in NetworkingDsc module, I'm looking at you):
```
Measure-Command {Start-DscConfiguration -UseExisting -Wait} | Select TotalSeconds

TotalSeconds
------------
   12,8837624
```
I can assure you that there was no drift and all resources stayed only within the Test- function block.
Here is plain pull-server poll for comparison:
```
Measure-Command {Update-DscConfiguration -Wait} | Select TotalSeconds

TotalSeconds
------------
   0,6533572
```

**Comment by SDedik** [comment]
Yes, correct. The `Update-DscConfiguration` behaves absolutely correctly and according to documentation - it checks for updates on the pull-server and exits if there are none or downloads and applies them immediately if there are updates. The same is expected from the `RefreshFrequencyMins` timer.
To draw the parallels:
`RefreshFrequencyMins` timer event is expected to be the equivalent of `Update-DscConfiguration`
`ConfigurationModeFrequencyMins` timer event is expected to be the equivalent of `Start-DscConfiguration -UseExisting`

Instead, the `RefreshFrequencyMins` currently is a sum of `Update-DscConfiguration` + `Start-DscConfiguration -UseExisting`
Which makes the very existence of `ConfigurationModeFrequencyMins` redundant.

**Comment by chasewilson** [comment]
I have updated the documentation in the linked pull request to describe the current behavior of the `RefreshGrequencyMins` and adjusted my added note to reflect the intent of these settings. 

I can only update the documentation but if you want to leave product feedback you can see submit a request [here](https://windowsserver.uservoice.com/forums/301869-powershell). 

Thank you for pointing this out here. I know it doesn't exactly address everything but again, I can only update documentation. If you would like, you can review the [PR for this issue](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/7007) and we can work to accurately describe the behavior. 

Thanks again.

**Comment by SDedik** [comment]
@chasewilson thank you for all your efforts. I created a post on uservoice as suggested https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/42200929-bug-refreshfrequencymins-timer-should-not-apply-c
Hope it will be noticed and looked into.
