### ISSUE TITLE
How to Use Profiles page doesn't state which execution policy to set

### ISSUE THREAD

**Issue by aksh1618** [MicrosoftDocs/PowerShell-Docs#6851]
IMHO the page should state which execution policy to set to make the profile load, or probably link directly to [RemoteSigned policy](RemoteSigned), if that is the recommended profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad21936-979d-c070-5aa0-ac51450cfa33
* Version Independent ID: f2a97164-ddeb-0d2e-e2fa-33883578fd99
* Content: [How to Use Profiles in Windows PowerShell ISE - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/how-to-use-profiles-in-windows-powershell-ise?view=powershell-6)
* Content Source: [reference/docs-conceptual/windows-powershell/ise/How-to-Use-Profiles-in-Windows-PowerShell-ISE.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/windows-powershell/ise/How-to-Use-Profiles-in-Windows-PowerShell-ISE.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The default Execution Policy setting varies by OS type (client vs. server) and version. It can also depend on group policy settings in your environment. This is better explained in  see about_Execution_Policies, which is linked in this article.
