### ISSUE TITLE
Use of "credential"

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#6855]
The use of the word credential/s is confusing here. The topic is "Securing the MOF File". And I think this version of DSC has the concept of encrypting configurations at rest. Encrypting configurations at rest makes sense. 

But this document repeatedly uses phrases like "To successfully encrypt the credentials" and "the private key used to decrypt credentials in the MOF" which don't make sense. 

The author appears to use "credential" where "file" or "file contents" are meant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea347ad-ed24-0760-8b3f-90ac72ddcec9
* Version Independent ID: b9a46e46-9263-f8e8-54b6-ab9a618819cc
* Content: [Securing the MOF File - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/securemof?view=powershell-7)
* Content Source: [reference/docs-conceptual/dsc/pull-server/secureMOF.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/pull-server/secureMOF.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Agreed, it can be confusing. Since the credentials are stored in the MOF, the intent the article is to explain how to provide encryption to secure the credentials. Changing the article would be a major rewrite. Would you consider submitting a PR?

**Comment by juvtib** [comment]
Where are the docs for PRs?

**Comment by sdwheeler** [comment]
@juvtib Yes, start with that doc.

**Comment by sdwheeler** [comment]
@juvtib Yes, start with that doc.
