### ISSUE TITLE
Add ${ } 

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#6857]
Please add a section for "${ }" which qualifies variable names. 

If you read the whole article you'll see: 

> Since PowerShell allows ? to be part of the variable name, formal specification of the variable name is required for using these operators. So it is required to use {} around the variable names like ${a} or when ? is part of the variable name ${a?}.

And there is the [Variable names that include special characters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_variables?view=powershell-7#variable-names-that-include-special-characters) article. 

But nowhere can you search for the "${ }" *operator* and get a result in the same way you can search for $( ) or @( ). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273225bd-bd1f-478f-6040-098bce77920c
* Version Independent ID: 5fcd4430-a6b8-0438-73c9-29749b804323
* Content: [about_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
`${}` is not an operator. It is syntax for variable names. However, we could add some more description and cross-link articles to make it more discoverable. I am working on an update for that.

**Comment by juvtib** [comment]
What makes sense to me is I would come to the article filled with punctuation to look for punctuation. If I was new, I would not necessarily parse the difference between ${ } and @( ).
