### ISSUE TITLE
Install-PackageProvider ignores Force -ForceBootstrap, always prompts for confirmation

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/PowerShell-Docs#6868]
No matter what parameters I pass, e.g.:

```powershell
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -ForceBootstrap -Verbose
```
It always prompts for confirmation:

```
Would you like PackageManagement to automatically download and install 'nuget' now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
```
What makes impossible to use it fully programmatically. This is a blocking issue for us (Internal Microsoft team) and this article says nothing about this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa2a5400-8e29-2cb7-971e-b8b06846d025
* Version Independent ID: 24d49a13-873e-489d-0057-f0ce27e2a267
* Content: [Bootstrapping NuGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/getting-support/bootstrapping-nuget?view=powershell-7)
* Content Source: [reference/docs-conceptual/gallery/how-to/getting-support/bootstrapping-nuget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/getting-support/bootstrapping-nuget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Have you tried using `-Confirm:$false`? Let me know your results.

**Comment by sdwheeler** [comment]
@abatishchev Have you opened a product issue? If not, add one at https://github.com/OneGet/oneget/issues

**Comment by abatishchev** [comment]
@sdwheeler hi, you're right, I should've open the product issue first. Just did.

For the doc, can you please see if it can be improved? It's in the top for [Google search](https://www.google.com/search?q=Would+you+like+PackageManagement+to+automatically+download+and+install+%27nuget%27+now) for the prompt text but doesn't says how to avoid this prompt.

**Comment by abatishchev** [comment]
`Confirm:$false` doesn't do anything either (when the script is ran programatically)

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you comment on this?

@abatishchev This may be a "bug". There may not be way around this issue at this time.

**Comment by SydneyhSmith** [comment]
Sure-- I asked for some additional information in the linked issue https://github.com/OneGet/oneget/issues/496

**Comment by sdwheeler** [comment]
Closing. This issue is being tracked in the source repo.
