### ISSUE TITLE
Document Asp.Net Core 5.0 behavior on BinaryFormatter with Microsoft.PowerShell.SDK

### ISSUE THREAD

**Issue by fMichaleczek** [MicrosoftDocs/PowerShell-Docs#6879]
# Summary of the new document or enhancement

- Link(s) to related issue(s) in the PowerShell/PowerShell repo: [#14032](https://github.com/PowerShell/PowerShell/issues/14032)

## Description of what changed

Starting net5.0, if you use the PowerShell SDK in an Asp.Net Core application, PSRemoting is broken because of the BinaryFormatter long-term obsoletion plan.

To re-enable BinaryFormatter to let PSRemoting works, you have add a property EnableUnsafeBinaryFormatterSerialization set to true in your csproj  : 

```
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.PowerShell.SDK" Version="X.X.X" />
	</ItemGroup>
</Project>

```

**Comment by fMichaleczek** [comment]
@sdwheeler I'm not an english native, so it's better if I don't write the documentation 😅. It's my first issue in this repo, let's me know if you need more informations.

**Comment by SteveL-MSFT** [comment]
Our plan is to remove dependency on BinaryFormatter in 7.2 (.NET 6) timeframe.  So this only applies to 7.1 which is only supported for a year.  The existence of this issue might be sufficient?

**Comment by fMichaleczek** [comment]
@SteveL-MSFT yes, the error message is clear, the issue is referenced on github. But we can also try set EnableUnsafeBinaryFormatterSerialization to true in the SMA/PowerShell.SDK 7.1.1+ and see if it works in Asp.Net

**Comment by FSharpCSharp** [comment]
Thanks for the solution, it was my life saver today! Ran into similar behavior related to ASP.NET and PowerShell execution. Then in a roundabout way I came across this solution. Is this now permanently to see, is already almost 2 years old, and unfortunately you still need the setting.
