### ISSUE TITLE
Incomplete Allowed Types list

### ISSUE THREAD

**Issue by iRon7** [MicrosoftDocs/PowerShell-Docs#6884]
There is (at least) one type missing from the Allowed Types list under [CONSTRAINED LANGUAGE (Constrained Language)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7#constrained-language-constrained-language).
See also StackOverflow question and comments: [Automatically retrieve Allowed Types for Constrained Language mode](https://stackoverflow.com/q/64805592/1701026)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74ebbb86-05e8-a3cb-cc44-0f92bd5bf530
* Version Independent ID: a878cf0b-136e-26ca-9710-7fe6cbe3d865
* Content: [about_Language_Modes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hi @iRon7 . Thanks for the feedback. 

As far as I can tell, the list is accurate unless you can find specifics. The following is what I ran to test:

```powershell
# Temporarily change the language mode for a session. 
$ExecutionContext.SessionState.LanguageMode = "ConstrainedLanguage"

$test = [System.Collections.Specialized.OrderedDictionary]::new()
```

```Output
InvalidOperation: Cannot create type. Only core types are supported in this language mode.
```

I'll be closing this for now but if you have more to add, I'll be keeping an eye on the issue and reopen if necessary.

**Comment by iRon7** [comment]
Hmm,
I think there is actually a bug:
```PowerShell
$ExecutionContext.SessionState.LanguageMode = "ConstrainedLanguage"
$test = [Ordered]@{a=1}
$Test.PSTypeNames
System.Collections.Specialized.OrderedDictionary
System.Object
```

**Comment by chasewilson** [comment]
What version are you working with. 

For me, in version 7, I can't even create it. However, in V5 and 6, I can create it and access it but can't do anything method based... 

Ordered is an alias for the type, they are are same. I'll do some digging.

**Comment by iRon7** [comment]
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chasewilson** [comment]
So, according the the PowerShell team. This isn't expected behavior and the official positions for things like this is not to document them and they will be reviewing the behavior to see if there is a fix needed. 

This is a good find and if there is more information coming my way, I'll make sure to pass it on to you. 

Thanks again!

**Comment by iRon7** [comment]
Thanks, shall I create a formal issue at: https://github.com/PowerShell/PowerShell/issues ?

**Comment by chasewilson** [comment]
It would'nt hurt and would give you a good avenue to add info or communicate with the devs

**Comment by iRon7** [comment]
Linked: [In RestrictedLanguage mode, an instance of a given type cannot be created with a cast, but can be created with New-Object #14071](https://github.com/PowerShell/PowerShell/issues/14071)
