### ISSUE TITLE
Accidental "KEYWORDS" section?

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#6887]
The topic contains the following section:

```
## KEYWORDS

- about_ConstrainedLanguage
- about_FullLanguage
- about_NoLanguage
- about_RestrictedLanguage
```

Given that there are no such `about_*` topics and that a `KEYWORDS` section seems to be unusual in general: is this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c8057d-0e24-0396-2eb9-b0182c7056c3
* Version Independent ID: a878cf0b-136e-26ca-9710-7fe6cbe3d865
* Content: [about_Language_Modes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
TBH I'm not sure about this. If you search these with get help it will pull up the about language modes but there aren't any keyword properties that I can see from the stored help file. Sean is out for the weekend so I will follwo up with him when he gets back to get an answer for this.

**Comment by sdwheeler** [comment]
The keywords section is intentional. It is part of the Help specification. But it is rarely used anymore. There are a few articles that still have the keywords section. Most of those are older articles that we have not touched in a long time. We have been removing them as we edit those articles.

**Comment by chasewilson** [comment]
I'll take this as an opportunity to remove the section then. Thanks @sdwheeler
