### ISSUE TITLE
Provider screenshot of the UI for better understanding

### ISSUE THREAD

**Issue by jeffrey008** [MicrosoftDocs/PowerShell-Docs#6889]
Just learning how to use PowerShell ISE. Would be very helpful if the doc has a screenshot of the UI to show which part is which.

Also found a small bug on chrome
![image](https://user-images.githubusercontent.com/11265387/99021964-c549b500-259c-11eb-8f7b-a9a18cb85df6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f833db-b6d4-7a4e-4c2c-d2a81dff1f60
* Version Independent ID: c9512d37-ac40-d9e2-91f1-22b4a32f9c0b
* Content: [Exploring the Windows PowerShell ISE - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/exploring-the-windows-powershell-ise?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/windows-powershell/ise/Exploring-the-Windows-PowerShell-ISE.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/windows-powershell/ise/Exploring-the-Windows-PowerShell-ISE.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @jeffrey008 , Thanks for the feedback. I'll take a look at possibly adding some screenshots. It's not normal for this doc set but will discuss with the team. 

In the meantime, I would suggest switching from ISE to VSCode for PowerShell Scripting. This is the official reccomendation. 

Thanks again and will post again here when a decision is reached.

**Comment by chasewilson** [comment]
Hey @jeffrey008, We will not be adding screenshots to this page as the ISE is depricated. As I suggested before, check out VSCode for future PowerShell Programming and you can see the documentation for PowerShell in VSCode [here](https://code.visualstudio.com/docs/languages/powershell)
