### ISSUE TITLE
Update affected docs for Experimental Features that are now mainstream

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#6897]
The following features are now mainstream and need to be documented as mainstream in the proper articles:

- PSTempDrive (mainstream in PS 7.0+)
- PSUseAbbreviationExpansion (mainstream in PS 7.0+)
- PSNullConditionalOperators (mainstream in PS 7.1+)
- PSUnixFileStat (non-Windows only - mainstream in PS 7.1+)

# Summary of the new document or enhancement

- List of articles that need to be updated: TBD
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo:
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

Review https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/experimental-features.md 
- Make sure that existing docs contain the descriptions of the new behavior.
- Make sure to know when the feature went mainstream

**Comment by chasewilson** [comment]
PSTempDrive  -  about_FileSystemProvider of about_psProvider, 
PSUseAbbreviationExpansion - Learn using Tab exansion.
PSUnixFileStat - Get-Item and Get-ChildItem
