### ISSUE TITLE
The default install path should be $env:ProgramFiles/WindowsPowershell", not "$env:ProgramFiles\PowerShell\Modules. "

### ISSUE THREAD

**Issue by genlin** [MicrosoftDocs/PowerShell-Docs#6906]
I just checked in my server and laptop. The PowerShell modules were installed into  "$env:ProgramFiles/WindowsPowershell" . There is not folder called "PowerShell" under the ProgramFiles folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda75e3d-c305-638d-94f3-1a9f78d8a319
* Version Independent ID: f3b7d225-4b62-1930-75c5-fc35e1c402ff
* Content: [Install-Module (PowerShellGet) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-7.1)
* Content Source: [reference/7.1/PowerShellGet/Install-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PowerShellGet/Install-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
That is true for Windows PowerShell 5.1, but not so for PowerShell 6 and higher. You were viewing the 7.1 documentation.

**Comment by genlin** [comment]
@sdwheeler Thanks for the information!
