### ISSUE TITLE
"Installing from the Microsoft Store" Documentation Issue

### ISSUE THREAD

**Issue by Vixb1122** [MicrosoftDocs/PowerShell-Docs#6909]
# Documentation Issue

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply):

**Conceptual content**
- [x] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

## Detailed description of the issue

> For more information, see
[Understanding how packaged desktop apps run on Windows]\(/windows/msix/desktop/desktop-to-uwp-behind-the-scenes).

↓

[Understanding how packaged desktop apps run on Windows]\(https://github.com/MicrosoftDocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-behind-the-scenes.md).

location: https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md#using-the-msix-package

**Comment by chasewilson** [comment]
There is no issue here. The current link will take the user to the published documentation.
