### ISSUE TITLE
Non working code sample

### ISSUE THREAD

**Issue by metablaster** [MicrosoftDocs/PowerShell-Docs#6913]
In the section for `$MaximumHistoryCount`, the docs say to use `(Get-History).Count` to get a count of commands stored in history, however it should be `(Get-History).Length`

```powrshell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5385fe0-0beb-32f9-1d4a-b44bad77b8a0
* Version Independent ID: 02b20737-f11c-b6ce-5e32-9bf8781c01f6
* Content: [about_Preference_Variables - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Both Length and Count work.

```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> (Get-History).Length
53
PS> (Get-History).Count
54
PS> (Get-History).psbase

Length         : 55
LongLength     : 59
Rank           : 1
SyncRoot       : {sync-branch, cd .\PS-Docs\PowerShell-Docs\reference\, sync-branch, checkout…}
IsReadOnly     : False
IsFixedSize    : True
IsSynchronized : False
Count          : 55
```

**Comment by metablaster** [comment]
That's odd, because it indeed works now, but too bad I didn't take a screenshot of the error first time.
