### ISSUE TITLE
Lots of typos in examples

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#6916]
For instance, in the AlcModuleAssemblyLoadContext,
_depdendencyDirPath should be _dependencyDirPath
and
s_dependencyDirPath should be _dependencyDirPath

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68697a0c-5330-a30d-90e5-cdf29a6462f7
* Version Independent ID: 7c143e41-3830-2065-0ba5-a75d3902036f
* Content: [Resolving PowerShell module assembly dependency conflicts - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@rjmholt Can you fix these errors?

**Comment by rjmholt** [comment]
PR fixes the typos mentioned. Please let me know about any others so I can fix them.
