### ISSUE TITLE
Failed to mention to setup security protocol to Tls12

### ISSUE THREAD

**Issue by Enmebaragezi** [MicrosoftDocs/PowerShell-Docs#6924]
I have tried to register the package source on Windows Server 2012 R2. I get the following error:
The location "https://www.nuget.org/api/v2" is not valid.
Could you update the article to point that in 5.1 Powershell it is important to set security protocol type to Tls12 before trying to reach this location? I haven't tried this with 7.0 yet, so I don't know if that applies there as well.
The same problem applies to powershell gallery registration.

Security protocol type setup:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6029fb-8243-0c0f-9098-0bafddc35783
* Version Independent ID: eb3dde9c-03e3-bccb-2609-5513038f45df
* Content: [Register-PackageSource (PackageManagement) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/register-packagesource?view=powershell-7.1&viewFallbackFrom=powershell-7.2)
* Content Source: [reference/7.1/PackageManagement/Register-PackageSource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PackageManagement/Register-PackageSource.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
We announced this requirement on the PowerShell blog - https://devblogs.microsoft.com/powershell/powershell-gallery-tls-support/

I will see about getting this added to the docs.
