### ISSUE TITLE
!NOTE, !IMPORTANT, etc. in Cmdlet Documentation

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/PowerShell-Docs#6927]
As !NOTE, !IMPORTANT, and so on do not render in PowerShell, for cmdlet help (`Get-Help cmdlet`), we have been editing any PRs which include this special markdown syntax.

Is it intended that these be used in cmdlet help? If so, they will ultimately render in PowerShell as "> [!NOTE]" which I don't think was intended.

Thoughts? Would it be possible to get a note on this page indicating they should not be used in cmdlet help?

@dariomws @get-itips

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3f704dc-0a44-16a2-cf25-106e0a21cb2b
* Version Independent ID: 193c7fc5-5c23-f08c-dfa7-bcaf9efb3ffa
* Content: [PowerShell-Docs style guide - PowerShell](https://docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/powershell-style-guide?view=powershell-7.1#markdown-extensions-supported-by-open-publishing)
* Content Source: [reference/docs-conceptual/community/contributing/powershell-style-guide.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/community/contributing/powershell-style-guide.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by dariomws** [comment]
@tseward @get-itips I think we can suggest a PR to see if it's approved. What do you think?

Or maybe @sdwheeler could give us his thoughts.

**Comment by sdwheeler** [comment]
The markdown is written as intended. The rendering from Get-Help in the console is not ideal but still readable. Eventually, we are planning to change the help system to use markdown rather than MAML. Get-Help will be changed to render the markdown.

**Comment by doctordns** [comment]
@sdwheeler what is the time scale for this? Are you looking at Pwsh 7.2??

**Comment by sdwheeler** [comment]
That is up to @SteveL-MSFT. It is on the roadmap but I don't think they have committed to a timeline yet.

**Comment by tseward** [comment]
Is this taking into consideration platforms that are restricted to .NET Framework, i.e. SharePoint Server? Are these markdown changes being back-ported?

If not, should we have a per-repository policy based on the capabilities of running on modern PoSh?

**Comment by sdwheeler** [comment]
The changes to the Help system would be 7.x+ changes. It would not be backported. But part of the problem with the !NOTE, etc. blocks is how PlatyPS renders them during conversion to MAML. We are also working on changes to PlatyPS. I will make sure that we address this rendering issue.

Bottom line is, we are working on improvements to the tools we use to create help and to the help system itself. There are multiple pieces to this puzzle and it will be an iterative process.
