### ISSUE TITLE
File parameter wrong information about cmd batch files

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/PowerShell-Docs#6934]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-file----filepath-args

_Similarly, if you want to execute the same command from a Batch script, you would use %~dp0 instead of .\ or $PSScriptRoot to represent the current execution directory: powershell.exe -File %~dp0test.ps1 -TestParam %windir%. **If you instead used .\test.ps1, PowerShell would throw an error because it cannot find the literal path .\test.ps1**_

This is not true at all

Try:

D:\temp\test.ps1
`Write-Host "test"`

D:\temp\test.cmd
`powershell.exe -file .\test.ps1`

From cmd window:
```
D:\temp>test.cmd

D:\temp>powershell.exe -file .\test.ps1
test

D:\temp>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776d0240-b9cb-fdb3-be53-eb72434040de
* Version Independent ID: 2a47dda6-5d42-249c-5d48-19ad6fbc7b3c
* Content: [about_PowerShell_exe - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@vedipen The documentation is accurate. In your example, it only works if you are in the same location. If you are in a different location if fails. Here is the full example in CMD.

```cmd
C:\temp>dir test.*
 Volume in drive C is OSDisk
 Volume Serial Number is 72C1-A47B

 Directory of C:\temp

11/19/2020  04:11 PM                40 test.cmd
11/19/2020  04:04 PM                19 test.ps1
               2 File(s)             59 bytes
               0 Dir(s)  168,709,406,720 bytes free

C:\temp>type test.cmd
powershell -noprofile -file .\test.ps1

C:\temp>type test.ps1
Write-Host "test"

C:\temp>test.cmd

C:\temp>powershell -noprofile -file .\test.ps1
test

C:\temp>cd ..

C:\>c:\temp\test.cmd

C:\>powershell -noprofile -file .\test.ps1
The argument '.\test.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

C:\>type c:\temp\test.cmd
powershell -noprofile -file %~dp0test.ps1

C:\>c:\temp\test.cmd

C:\>powershell -noprofile -file c:\temp\test.ps1
test
```

**Comment by velden** [comment]
I tend to disagree. 
You're right, but that's how relative and absolute paths work (%~dp0 just renders to an absolute path) and current working directory etc. It has nothing to do with Powershell.

IMO it shouldn't be mentioned as a 'powershell' thing but just general practice.

Thanks for your explanation.
