### ISSUE TITLE
Page needs to demostrate how to make the cmdlet

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#6937]
This page has a nice short example cmdlet. In C#

The details of how to turn this into an actual cmdlet and load it into PowerShell would be very useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98fbc73-0a8c-aa2c-81c9-ff6b7c703649
* Version Independent ID: 978f08b0-5917-7592-a5bc-a3a82a574bb1
* Content: [How to Write a Simple Cmdlet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-write-a-simple-cmdlet?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-write-a-simple-cmdlet.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-write-a-simple-cmdlet.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
That article is part of a series of articles that is more reference oriented. We cover creating, loading, and testing a cmdlet in the tutorials: https://docs.microsoft.com/powershell/scripting/developer/cmdlet/tutorials-for-writing-cmdlets.

**Comment by doctordns** [comment]
Well - just checked out one of those tutorials: https://docs.microsoft.com/en-gb/powershell/scripting/developer/cmdlet/creating-a-cmdlet-without-parameters?view=powershell-7.1. IN the Building the CMdlet section, it points to 
https://docs.microsoft.com/en-us/previous-versions//ms714644(v=vs.85)
Snap-ins are not supported in PowerShell 7.  This tells you how to create a snap-in. 

Somewhere, there should be a simple example of how to turn this code into a working cmdlet with PowerShell 7. And with a few as possible add-ins. I still dream of just being able to use Add-Type, but that is another story.

We need two things: First an up to date example of building the cmdlet, And second, THIS page needs to either include that information or point to the page showing how to do it.

**Comment by sdwheeler** [comment]
I agree, the SDK docs need to be modernized. We are putting those modern articles in the dev-cross-plat folder. I welcome submissions of articles like that.

**Comment by doctordns** [comment]
So, thanks to Twitter, I have discovered just how to do that. I even wrote a blog post: https://tfl09.blogspot.com/2020/11/creating-powershell-cmdlet-using-c-and.html

I would be happy to:
1. Add a link from this article to my blog post with an explanation "for details on how to do this, see the blog post.
2. Extend this page with that information and examples.
3. Have two articles  - the first this page about writing the cmdlet and pointing to a second page, "Building the Cmdlet". I am not quite sure how to do that but I can probably figure that out. ;-)

Comments??

**Comment by sdwheeler** [comment]
Have you seen these two articles?
- https://docs.microsoft.com/powershell/scripting/dev-cross-plat/create-standard-library-binary-module
- https://docs.microsoft.com/powershell/scripting/dev-cross-plat/writing-portable-modules

I haven't fully read your article yet, but after a quick scan it looks like there is a lot of the same information in these articles.

**Comment by doctordns** [comment]
I have worked out how to do this and published a blog article showing it: https://tfl09.blogspot.com/2020/11/creating-powershell-cmdlet-using-c-and.html

I would like to suggest the following changes to this page:
1. Retitle it "How to write and create a cmdlet" 
2. In the 1st para - update the text to note this page shows how to create the cmdlet.
3. Before the See Also section, add a section called "Creating your cmdlet" - in this section repurpose my blog post as instructions for this page.
4. Show loading the 'binary module' and refer the reader to other text showing how to create a real module.
5. Possibly - update any pages that reference this page to reflect this page now shows how to compile the cmdlet.


If there is an agreement to this approach, I would be happy to create a draft of this updated content for consideration.

**Comment by sdwheeler** [comment]
Adding this information to this article is out of scope for the intent of the article. Building the module is covered in other documents. Closing this issue.
