### ISSUE TITLE
$env or $Env ?

### ISSUE THREAD

**Issue by Kebap** [MicrosoftDocs/PowerShell-Docs#6939]
Which is the suggested standard?
The documentation seems to switch..!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f1531e-1843-aee4-d58a-3147f86280ae
* Version Independent ID: f050d890-be59-7c58-124e-d6121d861b75
* Content: [about_Environment_Variables - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
As with most things in PowerShell, variable names are not case sensitive. Both work.
