### ISSUE TITLE
A code snippet from the page produces an error with strict mode.

### ISSUE THREAD

**Issue by ZonderP** [MicrosoftDocs/PowerShell-Docs#6948]
Hello!

For me the following code snippet which can be found on this page doesn't work when I call it like:
'Test-ShouldProcess -Force'.

```
function Test-ShouldProcess {
    [CmdletBinding(
        SupportsShouldProcess,
        ConfirmImpact = 'High'
    )]
    param(
        [Switch]$Force
    )

    if ($Force -and -not $Confirm){
        $ConfirmPreference = 'None'
    }

    if ($PSCmdlet.ShouldProcess('TARGET')){
        Write-Output "Some Action"
    }
}

```
At least with 'Set-StrictMode -Version:Latest' I get an error that the variable $Confirm doesn't exist.

Tested with newest Windows Powershell version 5.1.
The same code snippet can also be found for Powershell Core 7.1.
Didn't test it on 7.1 though, but I assume this will be the same there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953c600a-59d4-09aa-5dce-b41559a4c697
* Version Independent ID: 530b7644-3211-0f7c-3c63-d9959a72f541
* Content: [Everything you wanted to know about ShouldProcess - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This looks like a bug between CmdletBinding and Strict Mode. I opened https://github.com/PowerShell/PowerShell/issues/14294 to track this bug.

**Comment by sdwheeler** [comment]
So this is not a bug but an error in the article. `$Confirm` is not created by `SupportsShouldProcess` so the example is wrong.

**Comment by ZonderP** [comment]
Sorry for the confusion - I probably should have stated more clearly that it is a documentation issue, not a Powershell issue.
Although - I thought that the error reporting offered on that page would automatically be related to documentation issues.
But then I think that quite some people will report Powershell bugs this way...

Please - if somebody will fix this documentation issue:
Maybe it's worth to dig a little bit deeper into this documentation, since for me this whole chapter about an additional '-Force' parameter doesn't really make too much sense and is more confusing that helping.
I think the same behavior could be accomplished by an end user of a function, which supports ShouldSupport, via passing in '-Confirm:$False.

**Comment by powercode** [comment]
It would be nice with a similar page for cmdlet writers - there seem to be somewhat different rules there.
