### ISSUE TITLE
New-Guid - I would like to know what information is used for GUID generation

### ISSUE THREAD

**Issue by franpb90** [MicrosoftDocs/PowerShell-Docs#6952]
Hi,

I would like to know what information is used for GUID generation. Something like timestamp, random number, hardware serial numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94cf7fb-c27e-168e-ecd4-ae3c9b17ffb5
* Version Independent ID: d989b9f3-d404-58d3-0047-8ceec626ec10
* Content: [New-Guid (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-guid?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/New-Guid.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/New-Guid.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The cmdlet call the .NET [NewGuid](https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid?view=net-5.0) method.
