### ISSUE TITLE
Wrong profile location for current user on latest Windows 10

### ISSUE THREAD

**Issue by ultimaweapon** [MicrosoftDocs/PowerShell-Docs#6953]
In the document it said `$Home\[My ]Documents\PowerShell` but this does not work when I put `Profile.ps1` here. It works when I moved to `$Home\[My ]Documents\WindowsPowerShell`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e5abcb-b1a4-ea80-a4a9-41beaf018fae
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about_Profiles - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
That profile location is correct for PowerShell v6+. You were reading the doc for PowerShell 7.1. The location that worked for you is for PowerShell 5.1.

**Comment by ultimaweapon** [comment]
I see. Thank you for information.

**Comment by ultimaweapon** [comment]
I think it is better to put some notes there to let users know it is changed since 7.1. It will be even better if it is also tell the users that version shipped with Windows 10 is not 7.1.
