### ISSUE TITLE
"Get-Process -Name PowerShell" is not working with PS7.1

### ISSUE THREAD

**Issue by stephenrgentry** [MicrosoftDocs/PowerShell-Docs#6954]
Hello,

Per Windows recommendation I upgraded PowerShell 5.1 to 7.1, and now the "Get-Process -Name PowerShell" command does not work with PS 7.1.  
Output = Get-Process: Cannot find a process with the name "PowerShell". Verify the process name and call the cmdlet again.

However, if I run that same command in PS 5.1 the output looks great, and if I leave the PS 5.1 command prompt open the command also then runs great in PS 7.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061f0355-2faf-5d78-b4ee-828e80aab7d5
* Version Independent ID: ace38d3f-9e35-86da-e4dc-ce4a5aca33fd
* Content: [Discovering objects, properties, and methods - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/03-discovering-objects?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/ps101/03-discovering-objects.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/ps101/03-discovering-objects.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
The PowerShell executable is pwsh.exe, now powershell.exe.

```powershell
PS C:\Foo> Get-Process -Name PWSH

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
    147   264.09     269.32     937.47   16212   1 pwsh
     62    54.72      56.90      46.28   16364   1 pwsh
     68    58.33      67.28      35.44   26304   1 pwsh
     78    57.34      80.91      14.47   26884   1 pwsh
```

Please close this issue.

**Comment by stephenrgentry** [comment]
That was easy.  Thank you.
