### ISSUE TITLE
Get-ADUser -Identity mike | Get-Member

### ISSUE THREAD

**Issue by stephenrgentry** [MicrosoftDocs/PowerShell-Docs#6956]
Hello again,

The example command "Get-ADUser -Identity mike | Get-Member" in the Active Directory section is not working for me. 
Error = Get-ADUser: Unable to find a default server with Active Directory Web Services running.

Is "mike" supposed to be added in Active Directory?  

Please advise,
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061f0355-2faf-5d78-b4ee-828e80aab7d5
* Version Independent ID: ace38d3f-9e35-86da-e4dc-ce4a5aca33fd
* Content: [Discovering objects, properties, and methods - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/03-discovering-objects?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/ps101/03-discovering-objects.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/ps101/03-discovering-objects.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
That error is an iidcation that something is wrong in your DC architecture.

The AD commands, when you run them on a client, communicate with a web service running on the DC. In your case, the client can not find the web service or can not find a DC. THere are numerous causes - DNS is always the first thing to check.

This is not an issue with the doccumentaiton.

**Comment by stephenrgentry** [comment]
Thanks for your help, but it's not clear what "DC" means.  Is that a Data Center?  I'm running on my PC at home.  My internet provider is Comcast. 
Also, your command to check the service on the DC is confusing.  Where does your prompt end and the command begin?  Is there two commands? 
Thank you.

**Comment by sdwheeler** [comment]
DC is "Domain Controller". You would have to set up your own Windows Active Directory domain (locally or online in Microsoft 365).  This is not a service that Comcast provides. The `Get-ADUser` cmdlet is in the **ActiveDirectory** module. That module is used to manage Active Directory computer and user accounts.

The point of the example is to show you how to use `Get-Member` to discovers the properties and methods of any object. And that the object you get back may not contain all of the properties available unless you request them.

**Comment by doctordns** [comment]
A DC is a domain controller. You need an Active Directory domain and a domain controller to run this command. 

This is not a problem with either the command or the documentation - can you close this.
