### ISSUE TITLE
[PSReadLine] DeleteLineToFirstChar behaviour change

### ISSUE THREAD

**Issue by springcomp** [MicrosoftDocs/PowerShell-Docs#6958]
# Summary of the new document or enhancement

Related to [PSReadLine#1751](https://github.com/PowerShell/PSReadLine/issues/1751).

## Description of what changed

Using <kbd>d</kbd><kbd>^</kbd> currently deletes the entire selection from the first non blank character in the buffer up to the cursor position. However, when using multiline input, it should delete only from the first non blank character in the current logical line instead.

**Comment by sdwheeler** [comment]
Waiting on https://github.com/PowerShell/PSReadLine/pull/2001

**Comment by daxian-dbw** [comment]
PowerShell/PSReadLine#2001 was merged.
