### ISSUE TITLE
Missing package from Linux installation notes

### ISSUE THREAD

**Issue by MathiasMagnus** [MicrosoftDocs/PowerShell-Docs#6962]
The command `add-apt-repository` resides in package `software-properties-common` which isn't installed on Ubuntu Server images. Please add to instructions to make them failsafe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@TravisEz13 Can you confirm and fix the docs?

**Comment by 4172580636** [comment]
#> ![image](https://user-images.githubusercontent.com/50898103/101432686-eb7a2080-38ce-11eb-9a8f-6066a2a3820f.png)

**Comment by sdwheeler** [comment]
Copy the instructions from this .NET doc - https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

**Comment by MathiasMagnus** [comment]
@sdwheeler I don't see in that article reference to the missing part. The fix isn't huge btw, currently the PS install docs read:
```
# Update the list of packages
sudo apt-get update
# Install pre-requisite packages.
sudo apt-get install -y wget apt-transport-https
# Download the Microsoft repository GPG keys
wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb
# Update the list of products
sudo apt-get update
# Enable the "universe" repositories
sudo add-apt-repository universe
# Install PowerShell
sudo apt-get install -y powershell
# Start PowerShell
pwsh
```
But the problem is that the command `add-apt-repository` isn't installed in ubuntu-server images by default. It resides in the package:
```
mate@MATTY-GL702ZC:~$ apt-file search add-apt-repository
software-properties-common: /usr/bin/add-apt-repository
```
Therefore, just adding this one line should do the trick:
```
# Update the list of packages
sudo apt-get update
# Install pre-requisite packages.
sudo apt-get install -y wget apt-transport-https software-properties-common
# Download the Microsoft repository GPG keys
wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb
# Update the list of products
sudo apt-get update
# Enable the "universe" repositories
sudo add-apt-repository universe
# Install PowerShell
sudo apt-get install -y powershell
# Start PowerShell
pwsh
```
It really is a minor deal. People stumbling upon this are notified by bash. I happened to come across this when installing PS in a docker image based on `FROM ubuntu:20.04` which AFAIK is Canonical's cloud image.
