### ISSUE TITLE
Missing something really basic (Almost intuitive) - Please provide a single example

### ISSUE THREAD

**Issue by marcelo-melendez-by** [MicrosoftDocs/PowerShell-Docs#6968]
It's really intuitive if you come from almost ANY language if it assumes you already program, but **additional parameters are comma separated**, and **all examples have only one parameter** and the _parameters modifier_ doesn't need coma which gives the sense that commas aren't needed.

Single Parameter:
```powershell
    param (
        [Parameter(Mandatory)] #<--- no coma needed
        [string]$ComputerName
    )
```
Multiple parameters:
```powershell
    param (
        [Parameter(Mandatory)] #<-- no coma needed
        [string]$ComputerName, #<-- Multiple parameters (no examples provided) are coma-separated
        [string]$HelloWord
    )
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f934b99-7214-c3d2-a197-d2f58df18b7c
* Version Independent ID: cb5bec10-7bfe-0421-509c-48525de3695b
* Content: [Functions - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/09-functions?view=powershell-7.1#parameters)
* Content Source: [reference/docs-conceptual/learn/ps101/09-functions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/ps101/09-functions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by Cwilson-dataselfcom** [comment]
Good point

**Comment by sdwheeler** [comment]
@mikefrobbins Do you have an opinion?

**Comment by mikefrobbins** [comment]
Teaching the concept of multiple parameters isn't the intent of chapter 9. The recommended reading section provides a link to [about_Functions_Advanced_Parameters](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters) for those who are interested in learning more about parameters.
