### ISSUE TITLE
Needs precise definition of 'Module' -- especially for .ps1 files in arbitrary folders

### ISSUE THREAD

**Issue by Cwilson-dataselfcom** [MicrosoftDocs/PowerShell-Docs#6970]
-Name
Specifies the names of the modules to import. Enter the name of the module or the name of a file in the module, such as a .psd1, .psm1, .dll, or .ps1 file.

Import-Module ought to fail with an error when a .ps1 file is named that isn't formally part of a 'module'.

But in reality it seems that Module is a term with a VERY loose definition in PS.   Or it it?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52fda2d7-8d64-210b-ee01-8bc6d15f8448
* Version Independent ID: ade5a7a7-929d-065a-f448-b6afe3750be2
* Content: [Import-Module (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/Import-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Modules are described in the following docs
- https://docs.microsoft.com/powershell/scripting/developer/module/understanding-a-windows-powershell-module
- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_modules

In short, the main file of a module can be a .DLL, a .PSD1 (manifest), or a .PSM1 file.

**Comment by Cwilson-dataselfcom** [comment]
Pointing to references that describe Modules seems to be non-responsive to the idea of adding a hyperlink to those references.

**Comment by Cwilson-dataselfcom** [comment]
"In short, the main file of a module can be a .DLL, a .PSD1 (manifest), or a .PSM1 file."

So why can a .ps1 file contained in any folder be referenced in the -Name parm of a Import-Module?

**Comment by Cwilson-dataselfcom** [comment]
"In short, the main file of a module can be a .DLL, a .PSD1 (manifest), or a .PSM1 file."

It's also true that:
"In short, a module can consist of a single  .DLL, a .PSD1 (manifest), or a .PSM1 file."  ??

**Comment by sdwheeler** [comment]
Yes, it is possible to import any arbitrary .PS1 file as a module. But not every script file is written to function as a module. Typically, a script module is in a .PSM1 file.

I am not trying to be non-responsive. I am trying to point you to the resources you need. I haven't closed this issue because I think you are correct that there are some things that need better explanations and we can add links.
