### ISSUE TITLE
Missing an approach?

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/PowerShell-Docs#6986]
Should this topic also describe how to invoke a script from the PS command shell?

```powershell
.\{SCRIPT NAME}.ps1
```

... and can it clarify if forward and backslashes are permitted? ...

```powershell
./{SCRIPT NAME}.ps1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c91c4ba-49ad-cba5-570e-bf7c82290242
* Version Independent ID: b856319e-a7c8-95da-6b07-da648871d427
* Content: [How to Write and Run Scripts in the Windows PowerShell ISE - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/how-to-write-and-run-scripts-in-the-windows-powershell-ise?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/windows-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/windows-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This article is specifically about the script pane of the ISE. Information about how to invoke scripts in a console is covered elsewhere.

**Comment by guardrex** [comment]
>  covered elsewhere

Do you have a link for that? I don't see it. The only mention is an example (backslash version) at ...

https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.1#execution-policy

... and there's no text dedicated to the act of calling a script in a command shell (or calling out if forward slashes are correct for non-Windows platforms). I'm asking because I need to check for an ASP.NET Core document that I'm working on ... just need to confirm that backslashes are xplat or if I need to call out forward slashes for non-Windows platforms. I think it should be in a section *somewhere*, but I don't know where it's called out in PS docs.

Also, ISE has a shell in it, right? ... Can't scripts be called in that pane of the ISE using the `.\{SCRIPT NAME}.ps1` syntax? If so, then this topic would be a place where the coverage *could live*.

**Comment by guardrex** [comment]
Ah ... I see what you mean ......

https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/how-to-use-the-console-pane-in-the-windows-powershell-ise?view=powershell-7.1

... well ... then why not move this issue to that topic (change the metadata) and consider it for that topic?

... or merely provide a link to where it's covered for a PS command shell as an additional resource for that topic? It would take seconds to cross-link from the other topic, and I'd be willing to send the PR if you can help me find the explanation that I'm looking for.

**Comment by sdwheeler** [comment]
The ISE is deprecated. If you want to add link to the ISE Console Window article I would consider your PR.

Script invocation is covered in:
- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_scripts

Path syntax is covered in:
- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_path_syntax

That article mentions that you can use forward slash. But I don't think is should be mentioned more than that for PowerShell 5.1. While PowerShell supports it, native commands that you may run from PowerShell may not support it.

**Comment by guardrex** [comment]
I see. That's what I was looking for ... and it's understandable why that isn't easy to find. PowerShell searches today (e.g., Google) lead to the main landing page and then the batch of docs where the only mention is that one spot in the *Execution policy* section (and merely as an example without specific guidance).

This won't be for a cross-link to anything from ASP.NET Core docs. I was just wondering if I needed to be concerned about it in xplat scenarios where we show invoking a script with a command shell. I see that I don't need to sweat it. We'll just continue to show a backslash.

I'm good now. Thanks again for your help.
