### ISSUE TITLE
 Syntax Misleading  [<CommonParameters>] seemed to be ignored

### ISSUE THREAD

**Issue by CortlandtW** [MicrosoftDocs/PowerShell-Docs#6987]
I tried:
Set-StrictMode -version 3.0  -Verbose  -InformationAction Stop -WarningAction Stop -ErrorAction stop

on a script.   I saw  that the -Verbose  -InformationAction Stop -WarningAction Stop -ErrorAction stop
had no visible impact.

My guess was that -InformationAction Stop -WarningAction Stop -ErrorAction stop
might stop the script after the first issue was detected.     That guess seems wrong.

If the common parameters have any impact that impact is not intuitive and needs to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74aedae3-9bd3-9475-0b68-616070759bef
* Version Independent ID: 80b0cb8d-c328-4479-9db3-93bb67b32416
* Content: [about_Modules - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_modules?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Those parameters only apply to the cmdlet they are used with. That is the difference between the preference variables and the common parameters. See the following documentation:
- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables
- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_commonparameters
