### ISSUE TITLE
Little to no help about the "KeyFilePath" argument

### ISSUE THREAD

**Issue by ERGeorgiev** [MicrosoftDocs/PowerShell-Docs#6990]
I spent a while wondering what the "KeyFilePath" argument is supposed to be, and sadly there is no info saying what kind of file this argument requires. I know now that it's assumed anyone running this command would have knowledge of RSA files, but a hint would have been helpful and would have saved me some time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d36d08-cdb0-08d2-6eba-7fad917791f6
* Version Independent ID: ccdd5a9c-5230-20de-db28-39e53a795ce3
* Content: [New-PSSession (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/New-PSSession.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
As described in the article, the file should contain SSH keys. Remoting over SSH is covered in https://docs.microsoft.com/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core.

For more information about  SSH keys, see https://docs.microsoft.com/windows-server/administration/openssh/openssh_keymanagement
