### ISSUE TITLE
Indicate how the member information can be used

### ISSUE THREAD

**Issue by bradallanmclaren** [MicrosoftDocs/PowerShell-Docs#7012]
So for me a powershell novice I used get-member and found the property I wanted but then could figure out how to use it :-).

Be good if this help indicated to use, for e.g., Select cmd-let use a property found.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600efcb9-7af9-bc99-1316-e7ac3630e219
* Version Independent ID: 45960b24-974a-113b-b0df-8055da108b92
* Content: [Get-Member (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Member?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Get-Member.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Get-Member.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hi @bradallanmclaren. Thanks for the feedback. 

So, this content is reference content to document the cmdlet specifically. Not exactly use cases for it but there are examples of capabilities the cmdlet has to show you how it can be used to get members in a specific ways. What you do with those members is dependent on what you are trying to accomplish. Documenting the use of members is out of scope. 

If you are just getting started, I would suggest taking a look at the Learning PowerShell section and for your questions about members and methods, I would take a look at [Discovering objects, properties, and methods](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/03-discovering-objects).

I'm going to close this for now, but feel free to respond if you think there should be documentation added to the reference doc or you have any more questions.
