### ISSUE TITLE
Requires Assembly path relative to module directory?

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/PowerShell-Docs#7016]
The documentation does not mention to what the assembly path is relative to. Is it relative to the module directory?
e.g. does `#Requires -Assembly myassembly.dll` reference a file named `myassembly.dll` in the same directory as the script/module? Aka. Is it equivalent to `Add-Type -Path "$PSScriptRoot/myassembly.dll`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfccf22-a7e5-a409-1ebe-5a875bbfa6d9
* Version Independent ID: 49650e70-7f7f-f891-5821-2de296a1a6fb
* Content: [about_Requires - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Requires.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Requires.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
It does not say that it is a relative path. It it the path to the DLL file.

**Comment by agowa338** [comment]
So it requires an absolute path than?

**Comment by sdwheeler** [comment]
Yes, absolute path works.

I don't know if relative path works. If it does, it would be relative to the location of the script that contains the `#requires -assembly` statement.

**Comment by agowa338** [comment]
> I don't know if relative path works. If it does

This is exactly what needs some clarification.

**Comment by sdwheeler** [comment]
OK, I did some more research on this and I will need to update the documentation.

See https://github.com/PowerShell/PowerShell/issues/11098 for more details.

Short answer: `#requires -assembly` doesn't actually do anything. The supporting code was never implemented.
