### ISSUE TITLE
The name 'criticalProcessNames' does not exist in the current context

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/PowerShell-Docs#7020]
[Enter feedback here]

I think there is something missing in this tutorial. There is a call to variable `criticalProcessNames` which is not defined anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74fc06d9-fd1e-6c91-d154-5bb43f586e2c
* Version Independent ID: f93cafc4-c318-846c-c292-f8c208cfdac0
* Content: [Creating a Cmdlet that Modifies the System - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/creating-a-cmdlet-that-modifies-the-system?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/creating-a-cmdlet-that-modifies-the-system.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/creating-a-cmdlet-that-modifies-the-system.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is only a partial example. The full example is in https://docs.microsoft.com/powershell/scripting/developer/cmdlet/stopprocesssample01-sample
