### ISSUE TITLE
Why is there no VM(M) column in my run of Get-Process?

### ISSUE THREAD

**Issue by yingang** [MicrosoftDocs/PowerShell-Docs#7023]
The output on my 1809 win10 laptop is like:

PS C:\Users\gang.yin> Get-Process

```
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    698      54    28148      45048       3.70   8648   1 AcroRd32
    949     115   390116     404040      26.27  13720   1 AcroRd32
    181      12     4060       8916       0.73   6068   0 AdaptiveSleepService
    282      12     6324       8740       1.22   4488   0 AdminService
    450      51    20828      35356       3.55   9884   1 ApplicationFrameHost
    265      21     5148      12096       3.59   8892   1 atieclxx
    216      12     4436       8612       0.70   2224   0 atiesrxx
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b81eb127-4bd7-7593-0ac9-f2e4e28b3bb8
* Version Independent ID: 08f2c662-66be-6889-27cb-6c4a0320717a
* Content: [Get-Process (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-process?view=powershell-7.1#outputs)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-Process.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-Process.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
The VM property is available. It is just not displayed by default.

`Get-Process | Select-Object VM`

**Comment by yingang** [comment]
Thanks, following your comment I find out there is already an 'Example 5' which shows how to add VM(M) into the output.

However, I still suggest to update the following description in the 'Notes' section since it's not displayed by default:

> The default display of a process is a table that includes the following columns.
