### ISSUE TITLE
Product end of life for 7.1 is before 7.0?

### ISSUE THREAD

**Issue by Mirend** [MicrosoftDocs/PowerShell-Docs#7030]
I noticed this section regarding PowerShell 7 support. Is that a typo? Seems weird that 7.0 would be supported longer than 7.1. Is 7.0 supposed to be December of 2021?

7.1 | mid-February 2022 (projected)
-- | --
7.0 | December 3, 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a43d3-9571-389c-56ab-7d42a53bf5b1
* Version Independent ID: c138e6a8-fd80-bd64-25ac-24e774e09421
* Content: [PowerShell Core Support Lifecycle - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/PowerShell-Support-Lifecycle.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
That is correct. The support lifecycle is based on .NET's lifecycle. See https://dotnet.microsoft.com/platform/support/policy/dotnet-core
