### ISSUE TITLE
Catch does not run before Finally as documented

### ISSUE THREAD

**Issue by sethrandall** [MicrosoftDocs/PowerShell-Docs#7034]
The Long Description states (emphasis added):
PowerShell then searches for a Catch block to handle the error. **If the Try statement does not have a matching Catch block, PowerShell continues to search for an appropriate Catch block or Trap statement in the parent scopes. After a Catch block is completed or if no appropriate Catch block or Trap statement is found, the Finally block is run**. If the error cannot be handled, the error is written to the error stream.

Testing the below code (in both 7.1 and 5.1) show that the Finally block is run before the Catch statement in a parent block instead of after. Is the documentation incorrect or is PowerShell not producing the expected behavior? (In my mind, Catch should always be handled before Finally).

Code:
```
try
{
    try {
        1/0
    }
    finally
    {
        Write-Host "cleaning up ..."
    }
}
catch [DivideByZeroException]
{
    Write-Host "Divide by zero exception"
}
```

Output:
```
PS U:\WindowsPowerShell> .\TryCatchTest.ps1

cleaning up ...
Divide by zero exception
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309d895e-d3e2-4281-5d06-9b9c217f153c
* Version Independent ID: 1bda81bf-58e5-93b9-48e7-ff1ec3d465d0
* Content: [about_Try_Catch_Finally - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This is expected behavior.  The article states:

> PowerShell runs the Finally block before the script terminates or **before the current block goes out of scope**.

The `try` blocks are nested. So the inner `try/finally` runs before the outer catch can run.
