### ISSUE TITLE
Update-Module: A parameter cannot be found that matches parameter name

### ISSUE THREAD

**Issue by Rob-S** [MicrosoftDocs/PowerShell-Docs#7037]
[Enter feedback here]

For the documentation on Update-Module https://docs.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-5.1

At least in PowerShell 5.1, there are no "-Scope", "-AllowPrerelease", "-AcceptLicense" or "-PassThru" parameters ("-PassThru" may have been added later.

Trying to use any of those parameters results in the message: A parameter cannot be found that matches parameter name ...

The Get-Help syntax shows:

Update-Module [[-Name] <String[]>] [-Confirm] [-Credential <PSCredential>] [-Force] [-MaximumVersion <Version>] [-Proxy <Uri>] [-ProxyCredential <PSCredential>] [-RequiredVersion <Version>] [-WhatIf] [<CommonParameters>]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd534e69-b7d9-8562-c224-b6bb4a200b21
* Version Independent ID: da21d631-936e-8754-a4ba-6932276efd8f
* Content: [Update-Module (PowerShellGet) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-5.1)
* Content Source: [reference/5.1/PowershellGet/Update-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PowershellGet/Update-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by chasewilson** [comment]
Hi @Rob-S . Thanks for the feedback. All of these parameters appear to exist in PowerShell 5.1 and above. If you run the following code You should see what I've got:

```powershell
(Get-Command Update-Module).Parameters.Keys
```

```Output
Name
RequiredVersion
MaximumVersion
Credential
Scope
Proxy
ProxyCredential
Force
AllowPrerelease
AcceptLicense
PassThru
Verbose
Debug
ErrorAction
WarningAction
InformationAction
ErrorVariable
WarningVariable
InformationVariable
OutVariable
OutBuffer
PipelineVariable
WhatIf
Confirm
```

You can double check your PowerShell version to make sure you are looking at the correct documentation by examining the `$PSVersionTable` 

I'm closing this for now, but feel free to respond with questions or any further findings. 

Thanks again.

**Comment by rdebath** [comment]
This is WRONG, the version of Powershell is almost irrelevant to this issue.
The module then needs to be updated is `PoserShellGet`.

**Comment by chasewilson** [comment]
Correct which is included in my edit and called out in the documentation itself. Hope this satisfies your concern here.
