### ISSUE TITLE
typo in ForEach-Object description

### ISSUE THREAD

**Issue by MikeMKH** [MicrosoftDocs/PowerShell-Docs#7041]
line has: "Using continue inside a pipeline, such as a ForEach-Object script block, not only exits the pipeline, **tt** potentially terminates the entire runspace."

it should be: "Using continue inside a pipeline, such as a ForEach-Object script block, not only exits the pipeline, **it** potentially terminates the entire runspace."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070aa957-c96a-ec60-cb6a-7fe5f3bad820
* Version Independent ID: 898c8336-37f1-296d-768c-60397c723ba2
* Content: [about_Continue - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_continue?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Continue.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Continue.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by doctordns** [comment]
Attempted to resolve this in PR #7402
