### ISSUE TITLE
Is there a file size limit when transcription in use?

### ISSUE THREAD

**Issue by b-dasass** [MicrosoftDocs/PowerShell-Docs#7043]
Hi there,

Is there any file size limit in Windows PowerShell affecting how big a transcript file can grow? 
Is there any difference between interactive transcripts (started by the user) and transcripts enforced by policy (HKLM:\Software\Policies\Microsoft\Windows\PowerShell\Transcription)? 

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ed158eb-29d5-5000-8ec1-4865f4a22dd3
* Version Independent ID: afe03c1f-3dbf-62f7-722a-d845777cadbd
* Content: [Start-Transcript (Microsoft.PowerShell.Host) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hi @b-dasass , these are great questions! 
- There is no file size limit other than any other file on your machines. The file is held open long enough to write the output to it as the script or command runs.  
- The policy is the same as running `Start-Transcript` so they will work the same as if you ran the command with the configuration you have in your policy. 

I'll be closing this for now. Feel free to reach out with any further questions.
