### ISSUE TITLE
Add documentation on how to disable UAC popup

### ISSUE THREAD

**Issue by blockchainOSINT** [MicrosoftDocs/PowerShell-Docs#7047]
The section, "Getting Started with PowerShell" describes the process of pinning PowerShell to the task bar and setting it to "Run as Administrator" every time it's opened.

> You'll never have to worry about finding PowerShell or whether or not it's running as an administrator again.

This is great, however it created a new issue - every time I start PowerShell, the UAC popup asks "Do you want to allow this app to make changes to your device?"

Of course I do. Just like the last time, and the time before that. This is an admin account. I don't want this message every time I open PowerShell.

There are [articles ](http://woshub.com/how-to-disable-uac-for-specific-applications/) about disabling the UAC popup for specific applications, however it seems that you cannot both disable the UAC popup AND run as admin. This is profoundly annoying.

If I am missing something, please forgive me, and kindly direct me to the proper way to do this. Otherwise, please add documentation in this section on how to disable the UAC popup and run PowerShell as admin on launch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80cd27-6cd2-2154-7a5f-8e4bc51b222d
* Version Independent ID: c2a54962-1511-7f87-24c5-f39b61f923bb
* Content: [Getting Started with PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/ps101/01-getting-started.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/ps101/01-getting-started.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
This is not really a problem with PowerShell as such. I think you will find that with UAC, any time you want to run Pwsh as admin, you get promoted. I know I do here. 

So the solution is either to live with UAC's nagging or turn it off.

**Comment by sdwheeler** [comment]
I agree with @doctordns. This is not a PowerShell issue and out of scope for these docs.
