### ISSUE TITLE
4.5 reserved word used as local variable name

### ISSUE THREAD

**Issue by nardnob** [MicrosoftDocs/PowerShell-Docs#7061]
Naming IAsyncResult local variable with reserved keyword "async" in the example for #invoking-a-pipeline-asynchronously.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c8e280-7c9e-1436-a8e8-d952c237ee81
* Version Independent ID: afab858f-633f-826b-db4b-15e105d2bc3e
* Content: [Adding and invoking commands - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/adding-and-invoking-commands?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/hosting/adding-and-invoking-commands.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/hosting/adding-and-invoking-commands.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hey @nardnob. Thanks for the feedback here!

 I don't see an issue in changing the example for absolute clarity and thanks to @doctordns for the PR, but `async` isn't a reserved keyword, it's actually a [contextual keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/#contextual-keywords) and this example should work.

**Comment by doctordns** [comment]
I thought it made sense to change the example and remove any potential confusion.

**Comment by chasewilson** [comment]
@doctordns, I think it's a good move as well. it accomplishes the goal of simplicity. Just adding info to clarify here :)

**Comment by nardnob** [comment]
Thanks @chasewilson. I didn't realize contextual keywords were a thing. Very interesting.
