### ISSUE TITLE
Document Request - Make it clear that PowerShell is on Windows Store

### ISSUE THREAD

**Issue by Zingam** [MicrosoftDocs/PowerShell-Docs#7066]
Make it clear in all documentation that PowerShell can be installed from Windows Store.
Also it is not clear which is the preferred way to install it but I guess Windows Store could be it.

**Comment by sdwheeler** [comment]
This is already documented:
- https://docs.microsoft.com/powershell/scripting/install/installing-powershell-core-on-windows#installing-from-the-microsoft-store
- https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-powershell-71#microsoft-store-installer-package
