### ISSUE TITLE
Add Instructions for Native Install

### ISSUE THREAD

**Issue by eightbit** [MicrosoftDocs/PowerShell-Docs#7067]
Suggestions for upgrading the native install would be helpful. If that is not a good idea, then suggesting the most efficient parallel install would be helpful.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
PowerShell 5.1 cannot be "upgraded". Installing PowerShell core is always a side-by-side installation. You can have both versions installed and use either. In fact. PowerShell 7 has a Windows Compatibility mode that uses the PowerShell 5.1 instance on your machine.  See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility

**Comment by eightbit** [comment]
Thanks for the quick reply. I'd recommend putting this info on the page for which this ticket was opened.
