### ISSUE TITLE
What is a module?

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/PowerShell-Docs#7068]
[Enter feedback here]Assumptions seem to be made about existing knowledge.  This does not help me understand what Powershellget is.  In order to do that, I need to know what a module is in this context?  Why should I already know this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15de6ba-1b16-d49d-6c9f-1ac84522a464
* Version Independent ID: eb7513e2-3636-d0bc-0eb5-e707fbd03e21
* Content: [PowerShellGet Module - PowerShell](https://docs.microsoft.com/en-us/powershell/module/powershellget/?view=powershell-7.1)
* Content Source: [reference/7.1/PowerShellGet/PowerShellGet.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PowerShellGet/PowerShellGet.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
The page you referencing is the index page for the cmdlet reference. The purpose of that page is to list available cmdlet, not to provide an explanation of the core concepts. For that see the following:

- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_modules
- https://docs.microsoft.com/powershell/scripting/learn/ps101/10-script-modules
- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_psmodulepath
