### ISSUE TITLE
Artiicle should state where Powershell stored the state of experimental feature

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#7075]
If you enable and experimental feature, PowerShell stores that information somewhere so that the next time you start PowerSHell that feature is now available. 

The article could usefully explain where this information is stored. I had thought it might be in $PSHome\PowerShell.Config.Json, but that does not seem to be the case in 7.1.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685c4662-4f42-ddbf-8f9a-f79241f063df
* Version Independent ID: 976ee643-597a-6c5e-bee4-bb0b72fe3c5f
* Content: [Using Experimental Features in PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/experimental-features.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/experimental-features.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This is documented tin https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_experimental_features

**Comment by doctordns** [comment]
I was suggesting it be noted on THIS page.
