### ISSUE TITLE
PassThru not supported

### ISSUE THREAD

**Issue by canufrank** [MicrosoftDocs/PowerShell-Docs#7078]
using Microsoft.PowerShell.Archive\Expand-Archive

Expand-Archive : A parameter cannot be found that matches parameter name 'PassThru'.
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Expand-Archive

**Comment by doctordns** [comment]
You do not have to use this statement to use a cmdlet.

What were you trying to do?

**Comment by mklement0** [comment]
[`Expand-Archive`](https://docs.microsoft.com/powershell/module/microsoft.powershell.archive/expand-archive) only has a `-PassThru` switch in PowerShell _Core_, as of (at least) v7.0 - it sounds like you're using _Windows PowerShell_ (or, possibly, a version of PowerShell Core that is no longer supported), where this switch isn't supported (and won't be added).

As the issue template advises, this repo is PowerShell Core only.

**Comment by chasewilson** [comment]
Hey @canufrank, thanks for the feedback and thank you @mklement0 and @doctordns for answering this. 

@mklement0 is right and this appears to be a version issue. I'll be closing this for now but keeping an eye on it if you feel like there is more to add. 

Thanks again and have a good one everyone!
