### ISSUE TITLE
information on this page is incorrect

### ISSUE THREAD

**Issue by msfreaks** [MicrosoftDocs/PowerShell-Docs#7080]
I'm having trouble signing in for weeks now, and have contacted the admins to get assistance.

Since I am getting 0 response to my requests the information on this page on how to get support must be outdated or simply wrong.

Please provide the correct methods for contacting support regarding sign-in issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b89b1dd-5b9f-6aec-72dd-e37981d0632e
* Version Independent ID: 1e85a3e1-b97f-3d18-3018-965510fb2e49
* Content: [Contact Gallery administrators - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/getting-support/contacting-administrators?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/gallery/how-to/getting-support/contacting-administrators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/getting-support/contacting-administrators.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment]
It seems you are able to login to Github. 

We cant really help you as this is not a place for ps gallery admin issues. 

Have you resent your password?

**Comment by msfreaks** [comment]
Hi doctordns,

My password is fine, my account is fine.
I'm posting this issue as it relates to the microsoft docs page "reference/docs-conceptual/gallery/how-to/getting-support/contacting-administrators.md" on which is explained how to get assistance.
Clearly the information in that page is wrong, since that seems to be a black hole: requests go in, nothing comes out.

So there's a problem with the information on that page and it needs to be fixed or removed entirely.
If nog support is to be gotten, then don't tell people how to get support.

Thank you for your response and your time.
I don't have an issue with my credentials (I know they are fine), there's an issue with that microsoft docs page as it presents mis-information.

Regards

**Comment by doctordns** [comment]
I just checked.  The email address works fine.

I suggest this is a user problem and not a doc issue. Thus, can this get closed?

**Comment by msfreaks** [comment]
Hi doctordns,

Good to hear the email address works fine. I guess it's just a case of the people reading the mails having a backlog or something.
I'll wait for responses to my mails to that address then.

Again, thanks for your time

Regards,
Arjan
