### ISSUE TITLE
Deep clone of a Hashtable

### ISSUE THREAD

**Issue by RasmusAaen** [MicrosoftDocs/PowerShell-Docs#7081]
You can do a deep clone of an object by serializing/deserializing it:

```
function Get-DeepClone($obj) {
    $_TempCliXMLString = [System.Management.Automation.PSSerializer]::Serialize($obj, [int32]::MaxValue)
    return [System.Management.Automation.PSSerializer]::Deserialize($_TempCliXMLString)
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51a14cf-e9db-6463-141c-2e6498e4e527
* Version Independent ID: a23755f9-7ded-991a-9675-57d3beb268ec
* Content: [Everything you wanted to know about hashtables - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@RasmusAaen When would you need to use this and where does this fit in the context of the article you are commenting on?

The only place this article mentions the depth of an object is specifically related to conversion from JSON for deeply nested JSON objects. The depth problem is specific to the JSON conversion and not specific to hash tables.

**Comment by RasmusAaen** [comment]
@sdwheeler The comment was in regard to the deep copy part of the article (https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.1#deep-copies), not nested objects.
The solution in the article only handles hash tables and seems complicated compared to the serialize/deserialize method.
