### ISSUE TITLE
Get-LocalUser not found return

### ISSUE THREAD

**Issue by BobWilkes** [MicrosoftDocs/PowerShell-Docs#7087]
This page needs info (& an example) of what is returned if the specified user name isn't found and how to process it.
e.g. If (-not Get-LocalUser -Name "JohnDoe") ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8851f25-fa7e-e981-bc2b-c684ed3b1b41
* Version Independent ID: 74bfb393-1031-c1f8-3ccd-b3864c4c6c71
* Content: [Get-LocalUser (Microsoft.PowerShell.LocalAccounts) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/get-localuser?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by doctordns** [comment]
I am not sure I agree with this, although I can see your point. If you take your suggestion to a logical conclusion, you would be asking for just about every ``Get-* `` cmdlet to be updated to show what happens when the object is not found by the cmdlet.

The error message "user <username> not found" is pretty clear. If a user is not found, then how you process that is not really a PowerShell issue. In my view!

**Comment by chasewilson** [comment]
@BobWilkes Thanks for the feedback here! I agree with @doctordns on this. This page is reference material for a specific cmdlet. It's purpose is to document the cmdlets behavior. 

If there is information that is missing in the doc that is causing the issue, we can talk about that. However, the docs purpose isn't to tell you how to write your code for your specific purpose. 

If you do need help in handline errors, you might take a look at [about_try_catch_finally](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally)

I'm closing this issue for now but I'll be keeping an eye on it so you can respond here if you feel there is more to discuss.
