### ISSUE TITLE
Defining a parameter set with no parameters at all

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/PowerShell-Docs#7089]
According to the `about_Parameter_Sets.md` page:

> Each parameter set must have at least one unique parameter. If possible, make this parameter a mandatory parameter.

Alright. In that case, how the following cmdlet and its parameter sets have been defined?

```PowerShell
Get-WsusServer [<CommonParameters>]
Get-WsusServer [-Name] <String> [-UseSsl] -PortNumber <Int32> [<CommonParameters>]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf182c4-c9fc-20d5-62b9-ab84d7810719
* Version Independent ID: e0a2ba15-cff9-4560-35a9-cd4440ef1d84
* Content: [about_Parameter_Sets - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameter_sets?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
There is a default parameter set and in that case, It happens to be the common params. I'm updating the wording in the linked PR to try and clarify a bit more about unique parameter sets. 

Your input there would be appreciated as well if you want to take a look.
