### ISSUE TITLE
Docs content doesnt show from within PowerShell session when using Get-Help

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/PowerShell-Docs#7091]
From a PowerShell session it should be possible to access the Docs content for Import-PowerShellDataFile ([here](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/import-powershelldatafile?view=powershell-7.1&viewFallbackFrom=powershell-5.0&source=docs)) via the command

`Get-Help Import-PowerShellDataFile `

However when running that command the output is 

> Synopsis
>   
> Description
>   
> Parameters
>
>     -LiteralPath <String[]>
>         
> 
>         Required?                    false
>         Position?                    named
>         Default value                None
>         Accept pipeline input?       True (ByPropertyName)
>         Accept wildcard characters?  false
> 
>     -Path <String[]>
>         
> 
>         Required?                    false
>         Position?                    0
>         Default value                None
>         Accept pipeline input?       False
>         Accept wildcard characters?  false
> 
> 
> 
> Syntax
>     Import-PowerShellDataFile [-LiteralPath <String[]>] [<CommonParameters>]
> 
>     Import-PowerShellDataFile [[-Path] <String[]>] [<CommonParameters>]
> 
> 
> Notes
>     
> 
> Examples
>     1:
>     PS C:\>

    
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7048f843-1f5b-4773-98b7-fcebbad8d1df
* Version Independent ID: 589d7d4e-5a40-8fec-4409-c98a001b81b8
* Content: [Import-PowerShellDataFile (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/import-powershelldatafile?view=powershell-7.1&viewFallbackFrom=powershell-5.0&source=docs)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hey @fatherjack , thanks for your question here. Have you updated your help files for your current version of PowerShell with `Update-Help`?

**Comment by fatherjack** [comment]
Yes

**Comment by chasewilson** [comment]
This doesn't apper to be a docs issue. if you want use this command to make sure all help files are updated
```powershell
Update-Help * -Force -ErrorAction SilentlyContinue
```

This will force an update of all your help files and prevent your terminal being overcrowded with errors.

If you are still having an issue after that, you can [submit and issue to the PowerShell Team](https://github.com/PowerShell/PowerShell/issues/new/choose). 

I'll be closing this for now but you can feel free to respond and I'll be keeping an eye on it to see if I can help any further or if something does show to be a docs issue, I'll reopen and go from there.
