### ISSUE TITLE
Missing really important information about single item arrays and the complications of multiple dimensions

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/PowerShell-Docs#7092]
On the whole the article is useful and helpful. But one of the worst characteristics of PowerShell is Arrays and there is no mention in this article about the rotten pitfalls of single item arrays and the nightmare it presents even if you're familiar with the trap doors. The problems of single item arrays has a knock on effect of making working with multi dimensional arrays a real pain. I see this as such a serious issue in PowerShell that I have sworn never to use multi dimensional arrays ever and have re-written a lot of my code to not use multiple dimension directly. Multi dimensional arrays are not complex in other languages. The single item array problem however, makes working with multiple dimensions in PowerShell disproportionally complex. This is because there is not enough documentation about the pitfalls of single item arrays/multi-dimension. Even when you know about using the comma op for single item arrays, if you have a code base which is trying to use multi-dimensions in complex scenarios, it's very difficult to debug thiese types of issues (hence me having to engineer out the direct use of md arrays because of the issue of single item arrays.

This article needs to explain this, in fact I can't believe this is missing, because other than this, I think this article is great and I have learnt a lot from it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99e524d-54e5-4119-9ebf-4fdbb7626122
* Version Independent ID: 271e2b41-af42-d4b5-3fdb-139aa5114b11
* Content: [Everything you wanted to know about arrays - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7.1&source=docs)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The definitive source of information about arrays in PowerShell is found in Chapter 9 of the [PowerShell Language Specification](https://www.microsoft.com/en-us/download/details.aspx?id=36389). That document is old and there is no plan to update it. But it is accurate for the information it includes.

I will look at what we can add to this article.

**Comment by plastikfan** [comment]
> 
> 
> The definitive source of information about arrays in PowerShell is found in Chapter 9 of the [PowerShell Language Specification](https://www.microsoft.com/en-us/download/details.aspx?id=36389). That document is old and there is no plan to update it. But it is accurate for the information it includes.
> 
> I will look at what we can add to this article.

That link is so old that it doesn't exist anymore

**Comment by sdwheeler** [comment]
I updated the link. I don't know what was wrong with that one. The correct link is: https://www.microsoft.com/download/details.aspx?id=36389

**Comment by plastikfan** [comment]
Actually, in addition to more examples, we need to know how to prevent automatic flattening that is he cause of so many issues when dealing with multi-dimensional arrays.

**Comment by sdwheeler** [comment]
@plastikfan There is no way to prevent flattening. You would have to write your own function to join to dissimilar arrays.

**Comment by plastikfan** [comment]
Ok that's fine, that's the kind of information we need instead of it being hidden.
