### ISSUE TITLE
Friendlier docs for object creation

### ISSUE THREAD

**Issue by er2** [MicrosoftDocs/PowerShell-Docs#7095]
This page ends too soon. It should show how to create the object successfully and the successful output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef149c3-473c-9f6c-a12b-4f8b252a02e0
* Version Independent ID: a31eed43-ac22-07d4-640d-5c4396dd9671
* Content: [Repeating a Task for Multiple Objects ForEach Object - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/samples/repeating-a-task-for-multiple-objects--foreach-object-?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/samples/Repeating-a-Task-for-Multiple-Objects--ForEach-Object-.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Repeating-a-Task-for-Multiple-Objects--ForEach-Object-.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
I am not sure what you think is missing from the examples in this article. What objects need creating? This article is demonstrating WMI object. Those objects are created by the WMI service. The `Get-CimInstance` cmdlet is just retrieving the objects that already exist.

What more are you looking for?

**Comment by er2** [comment]
At the end it _says that_ you can create an object with `Select-Object`. I think it would be better to _show how_ to create an object with `Select-Object`. I don't know why it ends by showing you how to run into an error. If it's not going to show how to use `Select-Object` it should at least link to that particular doc page.

**Comment by sdwheeler** [comment]
@er2 Thanks for the feedback. The more I look at this article the more I question its value. There is nothing in it that is not already covered in the help for `ForEach-Object`. 

And, as for the statement about creating objects with `Select-Object`, that is not accurate. `Select-Object` cannot create objects but it can alter the shape of objects passing through the pipeline.

```powershell
PS> "Hello" | select Length,@{n='a';e={1}},@{n='b';e={2}},@{n='c';e={3}} | Get-Member

   TypeName: Selected.System.String

Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
a           NoteProperty System.Int32 a=1
b           NoteProperty System.Int32 b=2
c           NoteProperty System.Int32 c=3
Length      NoteProperty int Length=5
```
