### ISSUE TITLE
Please document the issues encountered when working with classes particularly inside modules

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/PowerShell-Docs#7096]
Please document the following issues

- the read only nature of class definitions and the implications this has
- what are the available work arounds both in a powershell session and in VSCode
- when can "import module" be used and when can using module be used and the pros and cons of each
- document the inexplicable errors that currently make no sense to the user:
eg a message like this:

> Cannot process argument transformation on parameter ...... Cannot convert the "CosmosDbDatabase" value of type "CosmosDbDatabase" to type "CosmosDbDatabase".

really doesn't make any sense, until you know what the problem actually is (this is caused by the read only nature of classes).
- what difference it makes when a class is defined and meant to be used external to the module as opposed to a class that is internal only.
- best practices to employ when using classes including when you're using modules
- if you import a module in your profile and that module is one that you're currently working on and rebuilding, then the import in the profile should be removed. Please explain why this is so

I've taken to defining a separate class module that can be used by client modules purely to get around the issue of being able to access class types properly. I don't know if this is wise, but it does resolve some of these isses, but creates more friction as now functionality that should be bundled together are now separated by module borders.

All this information should be documented in Microsoft docs. Users shouldnt have to read 3rd party blog sites for this fundamental information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcd71bfb-1b7a-f31b-f618-d12823b84c3f
* Version Independent ID: a5651d52-5618-47e4-67df-6191278f0ad5
* Content: [about_Classes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@plastikfan There is a lot to unpack in this issue.  This first thing you should know about script-based classes is that they were designed for and only intended for use in DSC. Though they can be used in any arbitrary script or module, there are some limitations to their behavior.

> * the read only nature of class definitions and the implications this has

I don't know what you mean to by the "read only nature of classes".  What is the use case that is not working for you?

> * when can "import module" be used and when can using module be used and the pros and cons of each

`Import-Module` does not import the classes. They can only be imported by the `using` keyword. 

> * document the inexplicable errors that currently make no sense to the user:

I agreed that the error message is not helpful. It needs to be fixed. Please [file an issue](https://github.com/PowerShell/PowerShell/issues/choose) in the source code repository.
 
> * what difference it makes when a class is defined and meant to be used external to the module as opposed to a class that is internal only.

There isn't a way to make script-based classed (ones defined by the `class` keyword) "private" to the module. Any class you define in a module is available to the code inside the module. If you load the module with the `using` keyword, all of the defined classes are available outside the module.

> * if you import a module in your profile and that module is one that you're currently working on and rebuilding, then the import in the profile should be removed. Please explain why this is so

When you import a module within your profile, it is automatically loaded in every session. If you are making changes to the module and you have multiple sessions running, the module file could be locked by other sessions. So you may not be able to write your changes to the module files. When want to run the updated version of the module you must use `Remove-Module` to unload the current version from the current session. Then use `Import-Module` to load the new version. However, I don't think this unloads the classes imported by the `using` statement. So you need a new session. Also, if your module loads assemblies, those assemblies are not unloaded. So you must start with a new, clean session.

**Comment by plastikfan** [comment]
Thanks for your response @sdwheeler. Classes are a nightmare. Even when you think you know what you're doing, surprises still crop up. The lastest one is that I can't import a class from an external module with the using module statekment, even though I've done this many times before. This is really infuriating.

I have more comments to make regarding your response, but I want/need to fix this problem first.

**Comment by plastikfan** [comment]
I found this article: [Using Statement: Import PowerShell Classes from Modules](https://info.sapien.com/index.php/scripting/scripting-classes/import-powershell-classes-from-modules):


Rules (and Gotchas) for the Using Module Statement

Here are the rules for the Using Module statement:

- Using module statement can be used in a script or module, or run interactively in the console.
- In a script or module, the Using module statement must be the first statement. No uncommented statement can precede it, including parameters.
- Its value can be a string (module name or path to module file) or a ModuleSpecification hashtable.
- Using module imports classes from the root module (ModuleToProcess) of a script module or binary module. The Using statement does not (consistently) import classes defined in nested modules or classes defined in scripts that are dot-sourced into the module. (These classes are, of course, available in module scope without the Using statement.) (Thanks to Brandon Olin for the info about scripts.)
- Using module statement cannot include any variables. Its values must be static.


The point I'm interested in is 4th point, but I don't exactly know what it means, perhaps you could elaborate, it may be what's causing my import issue.

What are the requirements of a class definition so that importing that class from another module is reliable.

```powershell

class Operant { }

class Undo : Operant { }

class UndoRename : undo { }
```

All these are defined in a module Elizium.Klassy

In my client module, I have:

> using module Elizium.Klassy;

but I still can't access class type UndoRename.

I've done this before is other code, and it's worked fine. I can't see the difference.

In thar article, the worrying statement is:

> The Using statement does not (consistently) import classes defined in nested modules ...

What does this mean, and how am I supposed to handle this?

**Comment by plastikfan** [comment]
Oh and I'd just like to say, I appreciate your help and assistance with these issues, but the reason I raised this issue is that I want to see all this information properly documented in the Microsoft docs rather than just lingering around in github issue comments, where it will be near to impossible to find.

**Comment by plastikfan** [comment]
> 
> @plastikfan There is a lot to unpack in this issue. This first thing you should know about script-based classes is that they were designed for and only intended for use in DSC. Though they can be used in any arbitrary script or module, there are some limitations to their behavior.
> 
> > * the read only nature of class definitions and the implications this has
> 
> I don't know what you mean to by the "read only nature of classes". What is the use case that is not working for you?

What I mean here is, anytime the work-around for an issue is to restart the session, that is what I mean by read-only.
So when I'm developing a class, if I make changes to the class definition, then go to re-run the pester test, the test will almost always fail with an error message of the form:

> Cannot process argument transformation on parameter ...... Cannot convert the \<class-name\> value of type \<class-name\> to type \<class-name\>.

like I said in my original post text. What's even worse is that if that class makes a call to a function whose implementation has changed, not only does that change not get picked up, but if that is the only change that has occurred (ie the class defintion is still un-changed, but the function it calls has been modified), you still get that strange argument transformation error. I was stuck on this issue for days, not knowing how to fix this problem, and really doubting my knowledge of OO programming (which after many years of OO programming in many different languages, was a real shocker). The only way to fix this is to restart your session. This is what I mean by read only nature of class definitions, ie, their implementation is locked in a session and can't be updated. Now I know this is not strictly true, because there are caveats to this. I'm not 100% sure of the finer and more subtler details which is why this needs to be properly documented, because it is not intuitive.

> There isn't a way to make script-based classed (ones defined by the `class` keyword) "private" to the module. Any class you define in a module is available to the code inside the module. If you load the module with the `using` keyword, all of the defined classes are available outside the module.
> 

Now this point is a very contentious issue. You say that any class you define in a module is available to the code inside the module. I would contest that point. The class is NOT available to be used by other code in the module unless they are in the same file. classes only have file scope, because in powershell, there is no import/include facility like there is in other languages (the using module statement doesnt count, because that is only applicable to code that crosses module boundaries.

A common pattern for module development is to have a build process that concatenates all source ps1 files into a generated psm1 file. So inside the psm1 file, the classes would indeed be available to all the other code in the module, because they have been compiled into the same file. Since it isnt very scalable to code in a single file I prefer to code 'normally' into separate files using a build script to concatenate all the sources, but doing so makes class not available. What I do to get around this, is have a single .class file which contains all class definitions, creating factory functions where appropriate. Classes can refer to each for inheritance/composition purposes and although the factory functions can return the typed instances, inside the module you can't define variables to be of that class type, so for example this does not work:

```powershell
[bucket]$bucket = New-Bucket -Colour 'blue' -Size 'large'
```

but we can do this:

```powershell
$bucket = New-Bucket -Colour 'blue' -Size 'large'
```

The only way the first example would work is if that code resides in the same file as the class.

I generally don't like having non typed variables, which is the reason why I have started to use an alternative strategy where I create a new class library module, in this example BucketModule would contain the bucket class and the factory function New-Bucket and then in my client module, it would contain a using module BucketModule and then be able to use the bucket type so "[bucket]$bucket = New-Bucket -Colour 'blue' -Size 'large'" should work.

However having said this, I have two code scenarios which look to be indentical to this situation, but 1 works and the other doesn't and I have no idea why. This is the issue I'm currently trying to solve. Clearly, the working situation was developed first which encouraged me to repeat the technique, but I failed so far in the second scenario.

> > * if you import a module in your profile and that module is one that you're currently working on and rebuilding, then the import in the profile should be removed. Please explain why this is so
> 
> When you import a module within your profile, it is automatically loaded in every session. If you are making changes to the module and you have multiple sessions running, the module file could be locked by other sessions. So you may not be able to write your changes to the module files. When want to run the updated version of the module you must use `Remove-Module` to unload the current version from the current session. Then use `Import-Module` to load the new version. However, I don't think this unloads the classes imported by the `using` statement. So you need a new session. Also, if your module loads assemblies, those assemblies are not unloaded. So you must start with a new, clean session.

I'll need you to clarify this. When a session loads a module as a result of the import-module statement (PS, I know that classes are not loaded via import-module), then that module is loaded into memory for that session only (or does it, please clarify this). If I then start another session which goes to import the same module, is the module loading process aware of other sessions that have loaded that module and then descide not to load another one because it can share the existing one loaded into another session? Or do sesssions get their own private version of the module?

Let's say that a module is in my module path, eg it is in my documents/powershell/modules/my-module directory and the session loads that module into memory. If I am also developing that very same module, but it is in my dev souce location, eg lets say I develop that module at ~/dev/src/my-module and my test case imports the developed module, will the loader see that my-module has already been loaded into another session from the module path (ie from my documents, the wrong version) and not load the currently in development version causing errors? If I attempt to load the classes via using statement, where will it load the class from? Will it be the module that is in the module path (ie the one in documents/powershell/modules) or the module under development ie, from ~/dev/src/my-module? I suspect that it would load from the module path which in this case would be wrong.

This is an example of best practices. If you developing a module that also happens to be in the module path, then first un-install that module.

Can you clarify where using module statement loads the module from? Can it only load modules that are in the module path and if you're developing a module how do you get it to load that one if its not in the module path?

This process needs to be described in non ambiguous comprehensive form, because the errors that occur are in-explicable.

**Comment by plastikfan** [comment]
PS: I'm not expecting to provide answers to my questions in this issue. I'm expecting the 'about classes' document to be updated drammatically with all the useful information you have provided and my questions answered there.

**Comment by sdwheeler** [comment]
@plastikfan Yes, I agree. The about_Classes article needs improvements. It is good to hash out the questions here before we make any cahnges. I am still reviewing all of your comments and will follow up with more information or questions.

**Comment by sdwheeler** [comment]
@plastikfan Yes, I agree. The about_Classes article needs improvements. It is good to hash out the questions here before we make any changes. I am still reviewing all of your comments and will follow up with more information or questions.

**Comment by plastikfan** [comment]
By the way, I found the issue of my not being able to access the class type, but the resolution was found by accident to bears no resemblance to classes. What I found was that the .psd1 in my class module didnt have the RootModule property defined. I set it to the .psm1 file and things started working. I've got no idea why that should make a dffierence to accessing classes. When I now run Get-Module to list the loaded modules, I noticed that the module type was now set to _Script_ and before it was _Manifest_.

Go figure!

**Comment by sdwheeler** [comment]
> I'll need you to clarify this. When a session loads a module as a result of the import-module statement (PS, I know that classes are not loaded via import-module), then that module is loaded into memory for that session only (or does it, please clarify this). If I then start another session which goes to import the same module, is the module loading process aware of other sessions that have loaded that module and then decide not to load another one because it can share the existing one loaded into another session? Or do sessions get their own private version of the module?

Each session has it's own session state for a module. If the module is loaded in multiple sessions from the same location. .NET optimizes the DLL loading so that the DLLs are shared to minimize memory duplication. Modules loaded from a different location get loaded separately from the other sessions. You must use the full path to the module when importing or in the `using` statement to ensure that you load the version you intend. If you don't specify the full path, the module is loaded from the PSModulePath location.

**Comment by plastikfan** [comment]
Thanks @sdwheeler
