### ISSUE TITLE
Скрыт раздел Reference в меню

### ISSUE THREAD

**Issue by LutAle** [MicrosoftDocs/PowerShell-Docs#7110]
В меню справки русской версии не отображается разделы со справкой, в английской оtображаются

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b770965-4cc8-203e-5332-26bb9ee99220
* Version Independent ID: 1ac2554b-bf6a-2da6-3708-2d63af435e1e
* Content: [What is PowerShell? - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/overview.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
If you are having problems with the Russian content please file an issue at: https://github.com/MicrosoftDocs/PowerShell-Docs.ru-ru/issues

**Comment by LutAle** [comment]
Ok, i be use english version. But it problem get difficult promotion this technology (PoweShell) in russian speake user area
