### ISSUE TITLE
How do you clear the clipboard?

### ISSUE THREAD

**Issue by rhscjohn-dev** [MicrosoftDocs/PowerShell-Docs#7111]
In Windows PowerShell 5.x you can clear the clipboard by Set-Clipboard -Value $null.  In PowerShell 7.1.0., I have tried

1. Set-Clipboard -Value $null
2. Set-Clipboard -Value ''
3. Set-Clipboard -Value ""

None of the above cleared the contents of the clipboard.  What is the proper way to clear the clipboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8fe754d-9c7c-007f-db41-f387df478be5
* Version Independent ID: 0efcc112-2660-68d4-30ea-b6c633baa2a2
* Content: [Set-Clipboard (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Set-Clipboard?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Set-Clipboard.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Set-Clipboard.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hey @rhscjohn-dev this is a great question. I've reached out to the PowerShell team and they've told me it's a regression. If you would be able to [put in an issue](https://github.com/PowerShell/PowerShell/issues) that would help them track it and take care of it. 

In the meantime the suggested workaround is; `Set-Clipboard ' ' `. This isn't a one to one fix but it will clear any sensitive information. The one caveate is you still have a space in your clipboard. I hope this helps.

**Comment by chasewilson** [comment]
@rhscjohn-dev  The PowerShell team already has a pull request open due to your feedback so when that get's merged in and and released in the latest version of PowerShell! 

Thanks for the great find here. You can check out the pull request from the link above this comment.
