### ISSUE TITLE
Powershell command examples fail with double quotes and spaces

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/PowerShell-Docs#7120]
The examples given on this page https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-itemproperty?view=powershell-7.1
will not work if the registry path has a space in it.

For example:

powershell Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"

Fails with Get-ItemProperty : Property NT\CurrentVersion\AppCompatFlags\Layers does not exist at path

However, using single quotes works.
powershell Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers'

Please change the examples to use single quotes.

**Comment by sdwheeler** [comment]
The examples are correct. They are intended to be run within a PowerShell session, not as a command string passed to `powershell.exe` from `cmd.exe`. When you run the command from `cmd.exe` as in your example, the double-quotes are removed by `cmd.exe` before being passed to `powershell.exe`.
