### ISSUE TITLE
Comment-based Help Example code syntax consistency

### ISSUE THREAD

**Issue by wsmelton** [MicrosoftDocs/PowerShell-Docs#7121]
# Documentation Issue
Going through various pages on documentation around Comment-Based Help syntax I found example docs that use `C:\PS>` and others that just use `PS>`. 

It would be nice if:

1. It was consistent across all articles
2. It used the common nomenclature found in a Windows PowerShell or PowerShell prompt, `PS C:\>` (with space).

## Context of the issue

- URL to the article (Docs or GitHub URL):
https://docs.microsoft.com/en-us/powershell/scripting/developer/help/examples-of-comment-based-help
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help

- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [x] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

**Comment by wsmelton** [comment]
Is there a reason they were changed to just `PS>`?

**Comment by wsmelton** [comment]
The change on those PRs don't address this use at all.

**Comment by chasewilson** [comment]
These are changes we've been making as we have been editing docs. It's been a gradual change. Since they are used in non usable examples (examples you don't want to copy and paste into your terminal or script.) it's a bigger investment than what we are going to take on right now. There are a lot of examples and we will have to verify that changing the prompt won't change the purpose of the example. Like if the example is meant to highlight a terminal change or provider change or something along those lines. 

We are moving to the generic `PS>` prompt so it's not platform dependent but it's something we will keep editing as we go.

**Comment by doctordns** [comment]
Chase, can we have a consistent guideline on this across all Microsoft docs? I tried changing this in another repo and was rebuffed.

Can we please have consistency (and better docs)??

**Comment by wsmelton** [comment]
I can see the benefit of going to just `PS>`. It would be nice though if it was a syntax inherited across all doc teams.

Once docs inherit it can drive the community as well, or at least help.

**Comment by doctordns** [comment]
Personally, I prefer
```powershell
PS C:\>  {stuff}
```
But whatever we use, can we please decide on the ONE way, then let the community loose to fix the many occurrences of all the other variations?

**Comment by sdwheeler** [comment]
@doctordns I have published this guidance in the our [Style Guide](https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide#coding-style-rules) . The difficulty is getting the rest of the docs teams in Microsoft to follow this guidance.

**Comment by chasewilson** [comment]
We are working internally to reach out to other teams and @sdwheeler especially has been pushing for consistency across Microsoft Docs. It is slow but there is movement. We will continue to work on it and appreciate the patience as well.

**Comment by doctordns** [comment]
@chasewilson Sean has done a great job and in most of the places I visit, the approach is broadly consistent. But as we know, consistency has never been a strong suit at Redmond! :-) 

The move from technet/msdn to docs.microsoft.com has, in my view, been one of the best things Microsoft has ever done. It has enabled so many "silly" bugs to be resolved quickly and easily. It has been a huge amount of, largely unsung, work. So of course we can wait!  Is it possible to have an overarching "best practice" document at the 'root' of docs.microsoft.com which set out the standards? That way when I, or anyone else, submits a PR to any doc repo, we can point to that as justification for the change?

**Comment by sdwheeler** [comment]
@doctordns We have a public Contributor Guide for all of docs.microsoft.com. In that guide, there is product-specific guidance. The PowerShell [guidance](https://docs.microsoft.com/contribute/powershell-overview) page there links back to my contributor guide. The problem isn't having published guidance. The problem is getting the content owners to follow it. There is no formal enforcement. I am trying to drive a cultural change from within.

**Comment by wsmelton** [comment]
@sdwheeler I'm okay with submitting PRs when I find it and then linking back to that guide for justification. If that would be acceptable?

**Comment by sdwheeler** [comment]
That works for me.

**Comment by doctordns** [comment]
> @doctordns We have a public Contributor Guide for all of docs.microsoft.com. In that guide, there is product-specific guidance. The PowerShell [guidance](https://docs.microsoft.com/contribute/powershell-overview) page there links back to my contributor guide. The problem isn't having published guidance. The problem is getting the content owners to follow it. There is no formal enforcement. I am trying to drive a cultural change from within.

Thanks. I forgot that this was in place. It works for me - and I will use in my next PRs.
