### ISSUE TITLE
Platform.SelectProductNameForDirectory does not exist on Windows but has a docs page

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/PowerShell-Docs#7123]
# Documentation Issue

PowerShell SDK 7.0 describes Platform.SelectProductNameForDirectory and Platform.XDG_Type, which do not exist on Windows.

## Context of the issue

- URL to the article (Docs or GitHub URL): <https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.platform.selectproductnamefordirectory?view=powershellsdk-7.0.0> and <https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.platform.xdg_type?view=powershellsdk-7.0.0>
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [X] Scripting and development
  - [X] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

* Is the issue specific to a platform (Y/N - Win/macOS/Linux): Y - Win

## Detailed description of the issue

PowerShell SDK 7.0 describes the Platform.SelectProductNameForDirectory method and the Platform.XDG_Type nested type. However, those exist only in `UNIX` builds of PowerShell 7.1 (and presumably 7.0) and not in Windows builds. The documentation should warn about this difference or not describe those members at all.

The members are defined within `#if UNIX`: <https://github.com/PowerShell/PowerShell/blob/fa01333bfeef5dd7769143e2b4ec7ffdb70c62c8/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L222-L247>

The members were changed from internal to public in <https://github.com/PowerShell/PowerShell/pull/1721>.

**Comment by KalleOlaviNiemitalo** [comment]
Those members are part of the reference assembly in <https://www.nuget.org/packages/System.Management.Automation/7.1.0>, as well. Does that mean the issue should be moved to <https://github.com/PowerShell/PowerShell>?

**Comment by chasewilson** [comment]
This is the [dotnet documentation](https://github.com/dotnet/docs). You can start with them and then if they tell you it's a mistake or have a correction, they will be able to point you in the right direction. 

I'll be closing this for now but free to follow up with more information.

**Comment by gewarren** [comment]
> This is the [dotnet documentation](https://github.com/dotnet/docs).

That page is coming from https://github.com/MicrosoftDocs/powershell-docs-sdk-dotnet. To find the repo for an article, you can right-click, choose "View page source", then look for the "original_content_git_url" metadata value.
