### ISSUE TITLE
System.Management.Automation.Remoting.PSRemotingTransportException: 'Connecting to remote server localhost failed with the following error message : Access is denied.   

### ISSUE THREAD

**Issue by wingers999** [MicrosoftDocs/PowerShell-Docs#7124]
Trying to use the sample on the page below but get error below on line  remoteRunspacePool.Open();

Any thoughts please?

Same on example on https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/remoterunspace01-sample?view=powershell-7.1too

System.Management.Automation.Remoting.PSRemotingTransportException: 'Connecting to remote server localhost failed with the following error message : Access is denied.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0269519a-c125-1f2b-96a3-044471f1fc09
* Version Independent ID: 7043f7ce-6ab9-4db9-d6ce-421804f2365c
* Content: [Creating remote runspaces - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/creating-remote-runspaces?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/hosting/creating-remote-runspaces.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/hosting/creating-remote-runspaces.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
This example creates a WSManConnectionInfo for `http://localhost/` the default credentials, default server life time and default open timeout. The default shellname Microsoft.PowerShell will be used. Have you set up PowerShell remoting on the local machine?

See the following:
- https://docs.microsoft.com/powershell/module/microsoft.powershell.core/enable-psremoting
- https://docs.microsoft.com/powershell/scripting/learn/remoting/wsman-remoting-in-powershell-core

**Comment by wingers999** [comment]
Hi, yes I have run Enable-PSRemoting -Force and winrm qc - both completed okay

**Comment by wingers999** [comment]
Okay, got it working for localhost, two issues firstly I wasn't running Visual Studio as admin, and secondly the account I was logging on with didn't have a password.

So not to get it to connect to remote machine, but issues with that as for some reason my main machine gives me error about public network e.g.

WinRM firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.

Even though I am definitely set to private

PS C:\Windows\system32> Get-NetConnectionProfile


Name             : Network 2
InterfaceAlias   : Ethernet
InterfaceIndex   : 16
NetworkCategory  : Private
IPv4Connectivity : Internet
IPv6Connectivity : Internet

**Comment by sdwheeler** [comment]
Sounds like you got it working. This network, firewall, and account permissions required to make this work are requirements of WinRM and not PowerShell. Get WinRM working first.
