### ISSUE TITLE
Can we get some guidance here on what happens if a module is not installed.

### ISSUE THREAD

**Issue by grimley517** [MicrosoftDocs/PowerShell-Docs#7131]
So this may be the wrong command for what I'm trying to do.  But there isn't any guidance here on what occurs if a module is not found.  Should it raise an error? Should it return a particular message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f205680-23a9-9c57-8b95-e68be88088c7
* Version Independent ID: 87643ffc-385e-a865-bb1d-ec3f48d73072
* Content: [Get-InstalledModule (PowerShellGet) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershell-7.1)
* Content Source: [reference/7.1/PowerShellGet/Get-InstalledModule.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PowerShellGet/Get-InstalledModule.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment]
This cmdlet is part of PowerShellGet and its purpose of this cmdlet is to show you the modules installed by PowerShellGet.

If you run it without parameters, it lists the modules that have been in stalled by PowerShellGet.

If you run it with a module name and that module was not installed by PowerShellGet (or does not exist) you get an error.

```
PS C:\temp> Get-InstalledModule Microsoft.PowerShell.Management
Get-Package: C:\Program Files\PowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9445
Line |
9445 |          PackageManagement\Get-Package @PSBoundParameters | Microsoft. …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module names
     | 'Microsoft.PowerShell.Management'.
```

If you want to see all of the modules installed on the system want to use the `Get-Module -ListAvailable` command.

**Comment by chasewilson** [comment]
I'll be closing this issue for now. If you have anything more to add here, We'll still be monitoring and open for more discussion.
