### ISSUE TITLE
Add a parameter in comment-based help

### ISSUE THREAD

**Issue by MartinBGShell** [MicrosoftDocs/PowerShell-Docs#7134]
Bonjour/Hello

Bonjour. 

J'aimerais vous mentionner que mon anglais n'est pas très bon. Par contre, comme je suis un programmeur depuis 20 ans, je suis en mesure de lire l'anglais et d'écrire des FOR, THIS, IF, NEXT..., mais je suis moins bon en écriture de texte. Alors je vous prie de m'excuser si certaines phrases sont mal écrites. Je vais laisser la version en français (Au besoin).

<-- I would like to tell you that my English is not very good. On the other hand, since I have been a programmer for 20 years, I am able to read English and write FOR, THIS, IF, NEXT ..., but I am less good at writing text. So I apologize if some sentences are poorly written. I will leave the French version (As needed). -->

Depuis que je programme en PowerShell, j'ai toujours eu un problème avec la partie d'aide d'un programme en PowerShell et je vais vous l'expliquer.

Dans mon entreprise, nous avons décidé de programmer plusieurs fonctions portables qui ont un usage unique. À titre d'exemple, une fonction qui va juste extraire les données d'un fichier de type CSV ou une fonction qui va faire une requête SQL, par la suite les programmes vont retourner le résultat au programme parent. La fonction sera utilisé par des programmes parents d'automatisation des système. Le programme ConsoleServices.ps1 contient une section qui peut faire l'appel de l'une de ses fonctions, si l'événement est déclenché par l'utilisateur. Cette façon de procédé permet de ne pas refaire la même programmation à plusieurs reprises. Je crois que beaucoup d'entreprises fonctionnent comme nous. 

Alors, quand je fais un programme, j'aimerais vraiment pouvoir donner dans l'aide les prérequis dont la fonction aura besoin pour exécuter sa tâche jusqu'à la fin. Donc, il serait utile d'ajouter le mot clé ".PREREQUISITE" selon moi.

Ça ne changera pas le monde, mais ça va l'améliorer!

English version --------------------------

Since programming in PowerShell, I've always had a problem with the help part of a program in PowerShell and I'll explain it to you.

In my company, we have decided to program several portable functions which have a single use. For example, a function which will just extract data from a CSV type file or a function which will make an SQL query, subsequently the programs will return the result to the parent program. The function will be used by parent system automation programs. The ConsoleServices.ps1 program contains a section that can make a call to one of its functions, if the event is triggered by the user. This way of proceeding makes it possible not to repeat the same programming several times. I believe a lot of businesses operate like us.

So when I make a program, I would really like to be able to give in the help the prerequisites that the function will need to perform its task until the end. So, it would be useful to add the keyword ".PREREQUISITE" according to me.

It won't change the world, but it will improve it!

Exemple/Example :

Function VerbMaFonction
{
    <#
    .SYNOPSIS
        Returns a list of services that are set to start automatically, are not
        currently running, excluding the services that are set to delayed start.

    .DESCRIPTION
        Get-MrAutoStoppedService is a function that returns a list of services from
        the specified remote computer(s) that are set to start automatically, are not
        currently running, and it excludes the services that are set to start automatically
        with a delayed startup.

    .PARAMETER ComputerName
        The remote computer(s) to check the status of the services on.

    .PARAMETER Credential
        Specifies a user account that has permission to perform this action. The default
        is the current user.

    .EXAMPLE
         Get-MrAutoStoppedService -ComputerName 'Server1', 'Server2'

    .INPUTS
        String

    .OUTPUTS
        PSCustomObject

    .PREREQUISITE
		-Put the prerequisites for this function here.
		-Mettre les conditions préalables à cette fonction.
		Example : Verb_MyFunction_Requis or Beginning in PowerShell 3.0

    .NOTES
        Author:  Mike F Robbins
        Website: http://mikefrobbins.com
        Twitter: @mikefrobbins
    #>
}

Martin Benoit-Goyette

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 208e74df-f0c4-2841-82f9-8c9ff22e8b31
* Version Independent ID: 3ae6b0ce-e9bb-a441-92b2-cf12402e1f97
* Content: [about_Comment_Based_Help - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@MartinBGShell Thank you for the feedback. My French is worse than your English 😄. I agree that this would be good information to include, but it is not currently supported.  Please file a feature request at https://aka.ms/psfeedback.

**Comment by MartinBGShell** [comment]
(My French is worse than your English 😄)😄 I followed your advice. Thanks for your response and take care of yourself Mike.
