### ISSUE TITLE
Add a Character Ruler to Script Pane in PowerShell ISE

### ISSUE THREAD

**Issue by ShadetreeSam** [MicrosoftDocs/PowerShell-Docs#7136]
A ruler or line character count in the PowerShell ISE Script Pane would be very useful because many of the error messages specify a script source line number and character offset at which the error occurred. Some script source lines can be very long, and using an optional ruler or line character counter of some kind would be much more efficient than counting the characters manually.

**Comment by sdwheeler** [comment]
There is a line and column indicator in the status bar near the bottom right of the window frame.
![image](https://user-images.githubusercontent.com/19415881/104859283-c45d3880-58e9-11eb-934e-827aaeb5c49d.png)
