### ISSUE TITLE
Am I able to install the microsoft.wsman.management on my macbook?

### ISSUE THREAD

**Issue by johnthompson365** [MicrosoftDocs/PowerShell-Docs#7137]
I can't seem to find any guidance on whether this will work on MacOS or not. Can you advise? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6edb97e4-d40d-b820-0faa-fb9e5049c0f8
* Version Independent ID: 7cdd5770-9073-6983-a930-de019b410a0e
* Content: [Microsoft.WSMan.Management Module - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.wsman.management/?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.WSMan.Management/Microsoft.WSMan.Management.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.WSMan.Management/Microsoft.WSMan.Management.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @PaulHigin
* Microsoft Alias: **paulhi**

**Comment by sdwheeler** [comment]
No. That module is Windows-only. See https://docs.microsoft.com/powershell/scripting/whats-new/cmdlet-versions
