### ISSUE TITLE
Is it possible to audit Enter-PSHostProcess?

### ISSUE THREAD

**Issue by b-dasass** [MicrosoftDocs/PowerShell-Docs#7140]
Greetings,

Is it possible to audit the use of Enter-PSHostProcess on Windows machines, possibly without turning on the logging of all scrip blocks?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cf52cd-b944-0ff0-5a89-461cf459a980
* Version Independent ID: 859b90f9-d089-785a-c048-6cdd927a165e
* Content: [Enter-PSHostProcess (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enter-pshostprocess?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/Enter-PSHostProcess.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/Enter-PSHostProcess.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
No. Scriptblock logging is the only way.

**Comment by doctordns** [comment]
This seems an (almost) reasonable request. @sdwheeler is of course correct (naturally) that this  is not how it works, currently

That said, why not open an issue in Powershell\Powershell and ask for this. I suspect the answer will still be no, but at least the PowerShell team can say no, vs the doc team

:-)

**Comment by b-dasass** [comment]
Thank you!

Right now I only needed confirmation. Also, I'd expect that Windows PowerShell would receive an update, unless this becomes a critical security issue. 

I might submit a request, I'm not saying no to day :)
