### ISSUE TITLE
Additional note for get-date -UFormat specifier %j

### ISSUE THREAD

**Issue by pavel-a** [MicrosoftDocs/PowerShell-Docs#7143]
[Enter feedback here]

Please add a note for -UFormat specifier %j:

Leading zeros are removed from the day number. This differs from GNU coreutils `date +%j` which always returns 3 characters, prepending leading zeros if needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a992ec4-8b28-0023-a74d-7ae543358531
* Version Independent ID: 09bab64d-b131-3961-a8c2-10ecf7f3d96b
* Content: [Get-Date (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Date?view=powershell-7.1&viewFallbackFrom=powershell-3.0)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Get-Date.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@pavel-a I will update the docs. This sounds like a bug. 
Please file an issue at https://aka.ms/psfeedback
