### ISSUE TITLE
Automatic Variables missing OFS

### ISSUE THREAD

**Issue by jborean93** [MicrosoftDocs/PowerShell-Docs#7147]
The about_Automatic_Variables page is missing documentation of the `$OFS` variable which changes the default output field separator. It is mentioned in [about_Preference_Variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.1#long-description)  but only what the default is and not what it does

```powershell
$array = 1, 2, 3
"$array"

> 1 2 3

$OFS = ';'
"$array"

> 1;2;3
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c08e06-a43b-4cff-e8cd-f40fe12612b2
* Version Independent ID: 901506c9-d895-9a5b-331f-7b332fc5e827
* Content: [about_Automatic_Variables - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The full description of `$OFS` is in about_Preference_Variables at https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables#ofs
