### ISSUE TITLE
Description of Out-String's -Stream switch is incorrect.

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#7153]
# Documentation Issue

## Context of the issue

- URL to the article (Docs or GitHub URL): [`Out-String`](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/out-string)
- 
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Preview content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No

## Detailed description of the issue

PR #7133, prompted by #7133,  amended the description of `Out-String`'s `-Stream switch as follows:

> When the **Stream** parameter is used, the cmdlet outputs a separate string for
each input object. 

This is not correct, as the following example demonstrates:

```powershell
PS> (Get-Date | Out-String -Stream).Count
3
```

That is, _3_ strings were output for the single `[datetime]` instance, because the lines of the _formatted representation_ of the instance were output one by one.

The only exception to this are input objects that happen to be _multiline strings_, which are passed through as-is, as explained in https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7133#issuecomment-761865952:

```powershell
PS> (@'

Wednesday, January 20, 2021 9:42:47 AM

'@ | Out-String -Stream).Count
1
```

Again, this exception is obscure and unhelpful, so it may be removed in the future: see https://github.com/PowerShell/PowerShell/issues/14638

Also note that the non-exceptional behavior cannot really be explained at the level of the individual input objects, because the entire set of input objects is often formatted _together_, notably when _tabular_ format (`Format-Table`) is implicitly used, such as printing a common header only before the first object, with subsequent ones represented as single-line data rows only.

**Comment by mklement0** [comment]
P.S.: The multi-line string exception has now been reclassified as a _bug_ - see https://github.com/PowerShell/PowerShell/issues/14638

**Comment by chasewilson** [comment]
So here's what I found because I started seeing more counts than lines in objects and was curious. 

```powershell
 PS> Get-Date | Out-String -stream | ForEach-Object {$i = 1;Write-Output "Streamed Line: $_"}
Streamed Line:
Streamed Line: Wednesday, January 20, 2021 10:02:46 AM
Streamed Line:
```
So it's still going line by line and the date time is still one line but the representation is taking above an below "Items" and streaming them as well. 

Curious if you think this changes things at all for the documentation?

**Comment by mklement0** [comment]
All 3 lines - including the blank ones - comprise the formatted string representation of the `[datetime]` instance - and these lines are output individually.

The simplest way to conceptualize it: print a command to the console, take its output _as a whole, across all input objects_, split it into lines, and emit them one by one, blank lines, headers, grouping headings, and all.

That multi-line strings among the input objects are _not_ split is the unhelpful exception that has now been recognized as a _bug_ and labeled "up for grabs" - we'll see who volunteers to fix the problem and when.

For the purposes of the documentation I'd say something like (not verbatim):

* `Out-String` by default emits a single multi-line string that is the formatted string representation of all of its input, as you would see it in the console, including a trailing newline (which arguably shouldn't be added, but that's a separate discussion - see https://github.com/PowerShell/PowerShell/issues/14444).

* If you add `-Stream`, the lines of this string are output one by one - except if multi-line strings happen to be among the input objects, which are _not_ split into their lines (they are output as is); this is a bug for which a fix is pending.

**Comment by chasewilson** [comment]
@mklement0 I can get behind something like this. @sdwheeler is there anything I'm missing and need to take into consideration? 

I think the documentation should reflect the current behavior even though it's a bug since that's the behavior that will exist. Then update future docs once the bug is fixed in a new version.
