### ISSUE TITLE
Debugging using REPL

### ISSUE THREAD

**Issue by tasaif** [MicrosoftDocs/PowerShell-Docs#7162]
I ended up on this document because I was looking for a PowerShell equivalent of Ruby's `binding.pry`

This is what I ended up using:
while ($true){ $input = Read-Host -Prompt "repl"; if ($input -eq "exit"){ return 0 }; Invoke-Expression $input }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1155ca99-ad61-5aae-a2c1-0e5ea30e903d
* Version Independent ID: a2dc0231-76bf-19a5-d846-08635a7ca66f
* Content: [How to Debug Scripts in Windows PowerShell ISE - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/how-to-debug-scripts-in-windows-powershell-ise?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/windows-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/windows-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
@tasaif, do you have a question or a doc request here?

**Comment by chasewilson** [comment]
Ok, if you are talking about debugging your code, there are several options. You can [set a break point in VSCode](https://docs.microsoft.com/visualstudio/debugger/using-breakpoints), you can use [Set-PSBreakpoint](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/set-psbreakpoint), or you can use the [$ErrorActionPreference Variable](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables#erroractionpreference) `Break` and that will break into debugging mode if your code errors. 

I hope this helps and if you have anymore questions, feel free to write back here or open a new issue if it's unrelated. I'll be closing this for now but if you feel the docs need to change, we can reopen if needed.

P.S. PowerShell ISE is no longer the reccomended for PowerShell Development. VSCode Should be used if possible. :)
