### ISSUE TITLE
Invoke-WebRequest exception handling seems to use non

### ISSUE THREAD

**Issue by TimothyDJewell** [MicrosoftDocs/PowerShell-Docs#7163]
# Documentation Issue
In #3788, documentation was added to Invoke-WebRequest like:
>```
>try
>{
>    $Response = Invoke-WebRequest -Uri "www.microsoft.com/unkownhost" -ErrorAction Stop
>    # This will only execute if the Invoke-WebRequest is successful.
>    $StatusCode = $Response.StatusCode
>}
>catch
>{
>    $StatusCode = $_.Exception.Response.StatusCode.value__
>}
>$StatusCode
>
>404
>```
>The command calls `Invoke-WebRequest` with an **ErrorAction** of **Stop**, which forces `Invoke-WebRequest` to throw a terminating error on any failed requests. The terminating error is caught by the `catch` block which retrieves the **StatusCode** from the **Exception** object.

In my own usage, however, I haven't been able to find any need for the `-ErrorAction Stop`, since `Invoke-WebRequest` already throws a terminating error on any failed requests.  I haven't used PowerShell past version 5.1, so maybe this behavior changed?  I'm just trying to figure out why I would want to specify an extra parameter here for my own use.  I'm happy to put up a PR to remove if that would be helpful.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [X] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
@TimothyDJewell It seems that `-ErrorAction Stop` is not required. It was at one time. I don't know when that changed. Having it there does not affect the example.

**Comment by sdwheeler** [comment]
If you want to submit a PR to change that, please make the change to all versions. It works the same for all versions of PowerShell.
