### ISSUE TITLE
PowerShell Gallery - Troubleshooting - Required network endpoints section needs update/review

### ISSUE THREAD

**Issue by IanJDan** [MicrosoftDocs/PowerShell-Docs#7168]
Please verify the "Required network endpoints" section is updated and accurate. 

onegetcdn.azureedge.net came up as an additional endpoint while testing, but that domain is not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f89457b-839e-d865-be6e-5bc1690a0ce0
* Version Independent ID: 9ff93024-adda-659a-222e-260c1e346d79
* Content: [Troubleshooting cmdlets - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/getting-support/troubleshooting-cmdlets?view=powershell-7.1#required-network-endpoints)
* Content Source: [reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you comment?

**Comment by alerickson** [comment]
Yes, can verify that this is true.  'onegetcdn.azureedge.net' is needed for bootstrapping the NuGet Provider within PowerShellGet/PackageManagement, so while it's not necessarily needed all the time, there certainly may be moments where it is (particularly with fresh machines or while testing).
