### ISSUE TITLE
Document Request: Get-Date -UFormat %u ISO8601 standard (1-7)

### ISSUE THREAD

**Issue by brianary** [MicrosoftDocs/PowerShell-Docs#7180]
# Summary of the new document or enhancement

- List of articles that need to be updated: /reference/7._?_/Microsoft.PowerShell.Utility/Get-Date.md
- New articles that need to be created: _(none)_
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/14549
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/issues/4750

## Description of what changed

Parameter behavior changed so that Sundays return a `7` rather than a `0`, as specified in [ISO8601 week dates](https://en.wikipedia.org/wiki/ISO_week_date).

This will also require a change to the description of `%w`, which currently claims to be the same as `%u`, but is 0-6 (see [C's `strftime`](https://en.cppreference.com/w/c/chrono/strftime)).

**Comment by sdwheeler** [comment]
Fixed in #7183
