### ISSUE TITLE
"Recurse parameter in Remove-Item has a known issue" still true in PS7.1 docs?

### ISSUE THREAD

**Issue by esoltys** [MicrosoftDocs/PowerShell-Docs#7188]
In "Example 4: Delete files in subfolders recursively" it says "Because the Recurse parameter in Remove-Item has a known issue".

I believe it was an issue in PS5, but is this still true for the PS7.1 documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca41c7e-6796-5d87-0794-29fcaba7524c
* Version Independent ID: 0b18157a-a191-4733-90db-7dfceda2c99f
* Content: [Remove-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
Yes, the issue still exists. There are a few issues with recursion in `Remove-Item`.
- https://github.com/PowerShell/PowerShell/issues/8211
- https://github.com/PowerShell/PowerShell/issues/11721
- https://github.com/PowerShell/PowerShell/issues/9246
- https://github.com/PowerShell/PowerShell/issues/3674
