### ISSUE TITLE
Whatif

### ISSUE THREAD

**Issue by Stofferl** [MicrosoftDocs/PowerShell-Docs#7194]
Whatif does not work with the force parameter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7222f499-c9f6-583d-c00a-0619f4a6ac40
* Version Independent ID: a352c3ec-59c4-0417-a46e-c47ebd4b5db1
* Content: [Clear-RecycleBin (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/clear-recyclebin?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
Please file an issue at https://aka.ms/psfeedback
