### ISSUE TITLE
Examples or link to New-SelfSignedCertificate would be helpful

### ISSUE THREAD

**Issue by johnmreynolds** [MicrosoftDocs/PowerShell-Docs#7196]
This document gives detailed instructions for the old-style way of creating self-signed certificates using makecert, but strangely not for the newly recommended New-SelfSignedCertificate. Nor does it link to any documentation on that which might give examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dccbd2c2-b400-b5ab-5eb7-4b75c04e78c9
* Version Independent ID: 5d218683-79ce-326b-31bf-4dfa836b8ba6
* Content: [about_Signing - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
https://docs.microsoft.com/powershell/module/pkiclient/new-selfsignedcertificate

**Comment by johnmreynolds** [comment]
Yeah, it's easy enough to find the documentation by search; I was just noting it was surprising there wasn't at least a link, given the more extensive documentation on the older solution.

**Comment by sdwheeler** [comment]
Yeah, we reference the cmdlet in a few articles. Need to update all of them.
