### ISSUE TITLE
Forms field of Invoke-Webrequest response

### ISSUE THREAD

**Issue by Ardus-Petus** [MicrosoftDocs/PowerShell-Docs#7200]
Whenever I try to run any of the examples mentioned in the InvokeRequest documentation using the Forms response field, I get the following error:
   3 |  $Form = $R.Forms[0]
     |  ~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.

The documentation about HtmlWebResponseObject does mention a Forms property.

I am puzzled.

-- 
LR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76163247-141b-51ba-2178-cf4ff485077b
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Invoke-WebRequest?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
You are reading the article for PowerShell 5.1. Those examples only work in PowerShell 5.1.
