### ISSUE TITLE
No descriptions for PropertyCountForTable element in SDK

### ISSUE THREAD

**Issue by TerryMasenko** [MicrosoftDocs/PowerShell-Docs#7210]
There's no content for this page.
Just column headings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc70499-2cd8-b84b-a315-99a12dc90a05
* Version Independent ID: 641099b0-147e-491e-431e-2e89b388bc9d
* Content: [PropertyCountForTable Element (Format) - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/format/propertycountfortable-element-format?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/format/propertycountfortable-element-format.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/format/propertycountfortable-element-format.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Same problem in defining-common-configuration-features.md

This content was never created (only placeholders). We are trying to find someone who can fill in the information.

**Comment by sdwheeler** [comment]
The schema for the formatting XML can be found in the source code at https://github.com/PowerShell/PowerShell/blob/master/src/Schemas/Format.xsd. This provides some information about PropertyCountForTable.

```xml
      <xs:element default="4" minOccurs="0" name="PropertyCountForTable" maxOccurs="1" type="xs:nonNegativeInteger">
        <xs:annotation>
          <xs:documentation>Optional element. Specifies the minimum number of properties that an object must have to display the object in a table view.</xs:documentation>
        </xs:annotation>
      </xs:element>
```
