### ISSUE TITLE
If you want to re-enable it, run 'Import-Module PSReadLine'.

### ISSUE THREAD

**Issue by Almamun1740** [MicrosoftDocs/PowerShell-Docs#7211]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d3aa80-2921-cbfd-35cc-28a99cbe3091
* Version Independent ID: 49c16033-516f-92a6-2aeb-ce6002dced71
* Content: [PSConsoleHostReadLine (PSReadLine) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/psreadline/psconsolehostreadline?view=powershell-7.1)
* Content Source: [reference/7.1/PSReadLine/PSConsoleHostReadLine.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PSReadLine/PSConsoleHostReadLine.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
I'm not sure what you are asking for here. If you have some more feedback, feel free to respond or update the issue and I'll revisit. For now, I'll be closing this issue but will monitor it for any more feedback.

**Comment by Almamun1740** [comment]
How to re-enable “Import-module PSReadLine”?  Please let me know which cmd typing in powershell Sent from Mail for Windows 10 From: Chase WilsonSent: Friday, February 5, 2021 11:48 PMTo: MicrosoftDocs/PowerShell-DocsCc: Al Mamun Khan; AuthorSubject: Re: [MicrosoftDocs/PowerShell-Docs] If you want to re-enable it, run 'Import-Module PSReadLine'. (#7211) Closed #7211.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chasewilson** [comment]
I'm verry sorry you're having an issue, but I need more information. 

What version of PowerShell are you using? 
Do you have PSReadline installed? 
What error are you getting when you run `Import-Module PsReadline`?

**Comment by Almamun1740** [comment]
PSVersion : 5.1.19041.610PSReadline not installed how to do this?All error message are attached please see it. Sent from Mail for Windows 10 From: Chase WilsonSent: Saturday, February 6, 2021 1:09 AMTo: MicrosoftDocs/PowerShell-DocsCc: Al Mamun Khan; AuthorSubject: Re: [MicrosoftDocs/PowerShell-Docs] If you want to re-enable it, run 'Import-Module PSReadLine'. (#7211) I'm verry sorry you're having an issue, but I need more information.What version of PowerShell are you using?Do you have PSReadline installed?What error are you getting when you run Import-Module PsReadline?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chasewilson** [comment]
I don't see your error messages here.

To install PSReadline: `Install-Module PSReadline`

**Comment by Almamun1740** [comment]
After this cmd I have same warning.How can I re-enable it?  Sent from Mail for Windows 10 From: Chase WilsonSent: Saturday, February 6, 2021 1:34 AMTo: MicrosoftDocs/PowerShell-DocsCc: Al Mamun Khan; AuthorSubject: Re: [MicrosoftDocs/PowerShell-Docs] If you want to re-enable it, run 'Import-Module PSReadLine'. (#7211) I don't see your error messages here.To install PSReadline: Install-Module PSReadline—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chasewilson** [comment]
If you are responding on email, can you please move to the [GitHub interface here](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7211)? I am getting a lot of extra text and don't get the error messages if you are attaching them there?

**Comment by Almamun1740** [comment]
![Screenshot 2021-02-06 020402](https://user-images.githubusercontent.com/67066348/107085948-6efab400-6823-11eb-8e69-7ef22b2075e1.png)
![Screenshot 2021-02-06 020454](https://user-images.githubusercontent.com/67066348/107085952-715d0e00-6823-11eb-849c-8f6d4b9b1d45.png)

After this cmd I have same warning. How to solve it?

**Comment by chasewilson** [comment]
check out to see if [this solution](https://github.com/PowerShell/PowerShell/issues/11751#issuecomment-600120959) works.

Another suggestion from that thread is to check to see if the registry key `Computer\HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access` is set to 1 and if it it, turn change it to 0 and that seemed to fix it.

**Comment by Almamun1740** [comment]
Thank you so much @chasewilson

**Comment by Almamun1740** [comment]
Thank you so much.. Sent from Mail for Windows 10 From: Chase WilsonSent: Saturday, February 6, 2021 3:29 AMTo: MicrosoftDocs/PowerShell-DocsCc: Al Mamun Khan; AuthorSubject: Re: [MicrosoftDocs/PowerShell-Docs] If you want to re-enable it, run 'Import-Module PSReadLine'. (#7211) check out to see if this solution works.Another suggestion from that thread is to check to see if the registry key Computer\HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access is set to 1 and if it it, turn change it to 0 and that seemed to fix it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LakshmiNarayana34** [comment]
Warning: PowerShell detected that you might be using a screen reader and has
         disabled PSReadLine for compatibility purposes.
         If you want to re-enable it, run 'Import-Module PSReadLine'.

**Comment by LakshmiNarayana34** [comment]
![Uploading Screenshot 2024-02-29 102200.png…]()

**Comment by LakshmiNarayana34** [comment]
![Screenshot 2024-02-29 102200](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/141719976/90c7a4ce-67d1-4e50-a049-f2bec66abe82)
