### ISSUE TITLE
Missing '='

### ISSUE THREAD

**Issue by MarkLessard** [MicrosoftDocs/PowerShell-Docs#7231]
Example #4 line 'DisplayName "Test Service"' should contain an '=' for example 'DisplayName = "Test Service"'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e395479-0940-a518-a318-6df0ec7b5f30
* Version Independent ID: 4c55287b-3830-69b1-3eb7-33824b6181db
* Content: [New-Service (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/New-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/New-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hey @MarkLessard, Thanks for the feedback. I'm not sure I'm seeing any missing `=` though? All the example look like they are in order? If I'm missing something please feel free to point it out to me. I'll be closing this for now but I'll be monitoring the issue and will reopen if we need to. 

Thanks again.
