### ISSUE TITLE
Get-LocalGroupMember -Group 'Administrators' fails with error Get-LocalGroupMember : Failed to compare two elements in the array.

### ISSUE THREAD

**Issue by alokshan** [MicrosoftDocs/PowerShell-Docs#7236]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e680dd34-b877-94eb-7a69-c9279f3fc739
* Version Independent ID: 91e03223-25be-f177-b279-9199cc265137
* Content: [Get-LocalGroupMember (Microsoft.PowerShell.LocalAccounts) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/get-localgroupmember?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by alokshan** [comment]
Get-LocalGroupMember -Group 'Administrators'

Get-LocalGroupMember : Failed to compare two elements in the array.

**Comment by chasewilson** [comment]
Hey @alokshan, thanks for the feedback.

The documentation and example are correct. They have been verified to work. You can [submit a product bug here](https://github.com/PowerShell/PowerShell/issues). I hope you find the issue with the command and thanks again for the feedback.

**Comment by chasewilson** [comment]
As a Follow up, you can also check out [this issue here](https://github.com/PowerShell/PowerShell/issues/2996). 

Also, you can check to make sure there are no unresolved users in your administrators group and get rid of them if there are. That might be the source of your issue. 

Good luck!
