### ISSUE TITLE
Provided example is incorrect when not used for filenames.

### ISSUE THREAD

**Issue by sabuncu** [MicrosoftDocs/PowerShell-Docs#7245]
The provided information is incorrect when the first entry in the table (for the asterisk character) is used in a comparison, for example with `-match`:

`'banana' -match 'a*'`

returns True when it's indicated otherwise in the table.

The solution would be to be specific about where the example pattern should be applied.

If applied as `Get-ChildItem a*`, the example would indeed not match a filename of banana.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bbff6ce-1c3d-2d1b-ffd4-3fb8d34ebc52
* Version Independent ID: 9d3dd8b9-9284-768d-47cd-ea3e84042d95
* Content: [about_Wildcards - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Wildcards.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
@sabuncu This article is about wildcard expressions not regular expressions. The `-match` operator uses regular expressions. Wildcard expressions are used mostly to match names of items exposed by a PSDrive, like a filesystem or the registry.

**Comment by sabuncu** [comment]
I wasn't aware of the difference b/w -like and -match until this point.  Thank you.  Sorry that I created a hassle for you, on a Saturday to boot.

**Comment by sdwheeler** [comment]
@sabuncu No worries. I updated the article to point out the difference between wildcards and regex. You can see the change in GitHub. It will publish to the docs site on Monday afternoon.
