### ISSUE TITLE
This page even fails to explain how to call a function with parameters ...

### ISSUE THREAD

**Issue by FlightControl-User** [MicrosoftDocs/PowerShell-Docs#7249]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f934b99-7214-c3d2-a197-d2f58df18b7c
* Version Independent ID: cb5bec10-7bfe-0421-509c-48525de3695b
* Content: [Functions - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/09-functions?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/ps101/09-functions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/ps101/09-functions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
There is more than one example showing how to call a function with parameters.

```powershell
Get-MrParameterCount -ParameterName ComputerName, Computer, ServerName, Host, Machine
```

It is the same as using a cmdlet.
