### ISSUE TITLE
LogName cannot be piped to Clear-EventLog cmdlet

### ISSUE THREAD

**Issue by RichMath** [MicrosoftDocs/PowerShell-Docs#7251]
Both the cmdlet Help and web page state that **Logname** value "Accept pipeline input:  True".

The "Inputs" section, however, states "You cannot pipe objects to Clear-EventLog".

The following bit of code fails with the diagnostic "Clear-EventLog : Object reference not set to an instance of an object." which seems to contradict the "Accept pipeline input: True", and agree with the Inputs section's "You cannot pipe objects to Clear-EventLog"

Get-EventLog -LogName * |
   Select-Object @{n=’LogName’; e={$_.Log}} |
     Clear-EventLog

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a336c2bb-2f33-4257-d4bb-2b468f687c51
* Version Independent ID: 6c984d7b-72f0-2691-92ae-364ffd8a1332
* Content: [Clear-EventLog (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/clear-eventlog?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Clear-EventLog.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Clear-EventLog.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
This appears to be a bug. The LogName parameter is supposed to take pipeline input by name but it is not working.
