### ISSUE TITLE
PSDesiredStateConfiguration v3 module allows Get-DscResource, Invoke-DscResource and DSC configuration compilation on all platforms using class-based DSC resources

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#7267]
# Summary of the new document or enhancement

- List of articles that need to be updated: tbd
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/13399
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

PSDesiredStateConfiguration v3 module allows Get-DscResource, Invoke-DscResource and DSC configuration compilation on all platforms using class-based DSC resources

**Comment by chasewilson** [comment]
Steve put [an issue](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7373) in after this one and that's the one I followed up with and have a few notes in. I'll close this one even though it was the OG issue.
