### ISSUE TITLE
Quantifier bug in PowerShell 7.1

### ISSUE THREAD

**Issue by kmranrg** [MicrosoftDocs/PowerShell-Docs#7269]
# Quantifier bug in PowerShell 7.1

In PowerShell-7.1 Regular Expressions, the quantifier `{n}` doesn't work properly.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-7.1
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [x] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [x] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [x] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

### The following example has been given on the Official Microsoft Documentation:
`'111-222-3333' -match '\d{3}-\d{3}-\d{4}'`
The above code works fine, do doubt in this. But we we try to execute the following statement it doesn't work the way it should.
`'111-222-333333333' -match '\d{3}-\d{3}-\d{4}'  # this code gives the output as True`
The above command gives `True` after executing in PowerShell 7.1, but according to the official Microsoft documentation, \d{4} should only check for exactly 4 digits but it is basically checking for atleast 4 digits.

Thanks & Regards
Kumar Anurag
Am and will always be a Well-Wisher of Microsoft

**Comment by chasewilson** [comment]
Hey @kmranrg, thatnks for the feedback here. 

So it does actually work the way it's supposed to although it does look like it's not unless you do a little deeper investigation.

The quantifier is only matching the specified number and if you are selecting that string, it will only return the actual match even if there are more. 

```powershell
$test = '111-222-333333333' | Select-String '\d{3}-\d{3}-\d{3}'
$test.Matches.Value
```

```Output
# Output
111-222-333
```

If the string didn't match it at all like `'1-22-333' -match '\d{3}-\d{3}-\d{3}'`, this will return `False`.

Please feel free to reach out if you feel there is more to this. I'll be closing for now but will monitor and reopen it if I need to:) 

Thanks again and have a great rest of your day.

**Comment by kmranrg** [comment]
Got it. Thanks @chasewilson.
