### ISSUE TITLE
Incomplete procedure: Manually bootstrapping the NuGet provider on a machine that is not connected to the Internet

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/PowerShell-Docs#7273]
The procedure listed in the section "Manually bootstrapping the NuGet provider on a machine that is not connected to the Internet" suggest copying the folder structure of C:\Program Files\PackageManagement\ProviderAssemblies\ from a connected and 'prepared' machine to the disconnected host.  After which, on the disconnected host, one should execute Import-PackageProvider -Name NuGet.  This attempt will fail and the host will attempt to attempt to access a default Internet URI.

`Import-PackageProvider -Name NuGet`
`WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»`
`WARNING: Unable to download the list of available providers. Check your internet connection.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa2a5400-8e29-2cb7-971e-b8b06846d025
* Version Independent ID: 24d49a13-873e-489d-0057-f0ce27e2a267
* Content: [Bootstrapping NuGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/getting-support/bootstrapping-nuget?view=powershell-7.1#manually-bootstrapping-the-nuget-provider-on-a-machine-that-is-not-connected-to-the-internet)
* Content Source: [reference/docs-conceptual/gallery/how-to/getting-support/bootstrapping-nuget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/getting-support/bootstrapping-nuget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you comment on this?

**Comment by alerickson** [comment]
@aricbernard are you trying to install the latest version of PackageManagement (1.4.7)?  If so, try placing PackageManagement in your modules path ('C:\Users\<username>\Documents\PowerShell\Modules') and then opening a fresh session of PowerShell so that the module gets loaded.

**Comment by sdwheeler** [comment]
No response from submitter.
