### ISSUE TITLE
"Get-Package -Scope CurrentUser" returns packages in AllUsers/ system context

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/PowerShell-Docs#7274]
```Get-Package -Name '<ModuleName>' -Scope 'CurrentUser'``` returns a package installed in system context/ for all users.
Yes, technically ```%ProgramW6432%\WindowsPowerShell\Modules``` can be read by users without admin permissions, but the package itself is not installed in user context per se, which by default for PowerShell modules is ```%USERPROFILE%\Documents\WindowsPowerShell\Modules```.

This is using ```PackageManagement``` v1.4.7 on Windows PowerShell in PowerShell ISE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2bb6a51-3dc8-caa6-5b02-5c47c5806972
* Version Independent ID: 51100c02-3f5f-98a9-6ba2-62049da4671e
* Content: [Get-Package (PackageManagement) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/get-package?view=powershell-5.1)
* Content Source: [reference/5.1/PackageManagement/Get-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PackageManagement/Get-Package.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by o-l-a-v** [comment]
Created an issue inside oneget repo as well

* https://github.com/OneGet/oneget/issues/499

**Comment by sdwheeler** [comment]
Closing this issue to track it in the OneGet repo. We will adjust the docs when there is a resolution.
