### ISSUE TITLE
Illegal arguments

### ISSUE THREAD

**Issue by TechWriter975** [MicrosoftDocs/PowerShell-Docs#7280]
Seems that some characters are invalid parameters. Can't replace plus- sign using Rename-Item.

Rename-Item : The input to the script block for parameter 'NewName' failed. The regular expression pattern + is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d5a5181-203e-836c-a7bc-62d35c76acc2
* Version Independent ID: 0e1d944b-6c55-89ed-8e9a-5e5532dba818
* Content: [Rename-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Rename-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Rename-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hey @TechWriter975, thanks for the feedback here. I want to make sure that I'm understanding you correctly and have a doc issue to correct. Would you mind sharing an example of what you are talking about?

**Comment by TechWriter975** [comment]
Hi, Chase

Just thought I'd mention, Rename failed for me because I had documents with + signs in the filenames. Those were not renamed and returned the error message about an illegal parameter (not an argument, sorry).

Example: 20 documents with prefixes of "TECH+" will not be renamed, but will return the error message I quoted ("Rename-Item : The input to the script block for parameter 'NewName' failed. The regular expression pattern + is not valid.)

Other files will be renamed.

There's probably a section on legal/illegal parameters in powershell that I didn't have time to check out...

Joan Maltese
Technical Writer, Compliance and Risk | Enterprise Health & Safety
Pacific Gas and Electric Company
77 Beale St. 1513, San Francisco, CA 94105
760 420-3463

**Comment by TechWriter975** [comment]
Chase,

I should have mentioned, I was trying to remove the + sign:

Get-ChildItem *.pdf | Rename-Item -NewName { $_.Name -replace '+',' ' }

For files with a prefix of TECH+


Hi, Chase

Just thought I'd mention, Rename failed for me because I had documents with + signs in the filenames. Those were not renamed and returned the error message about an illegal parameter (not an argument, sorry).

Example: 20 documents with prefixes of "TECH+" will not be renamed, but will return the error message I quoted ("Rename-Item : The input to the script block for parameter 'NewName' failed. The regular expression pattern + is not valid.)

Other files will be renamed.

There's probably a section on legal/illegal parameters in powershell that I didn't have time to check out...

Joan Maltese
Technical Writer, Compliance and Risk | Enterprise Health & Safety
Pacific Gas and Electric Company
77 Beale St. 1513, San Francisco, CA 94105
760 420-3463

**Comment by chasewilson** [comment]
Ahh i see the issue here. This is because the `+` symbol is a symbol used by the regex engine. This should fix your issue:

```powershell
Get-ChildItem *.pdf | Rename-Item -NewName { $_.Name -replace '\+',' ' }
```

the `\` will let the regex engine know that it wants to interpret it as a literal string and not a regex operator. 

you can run some testing to make sure it will work but I've tested it on my side and everything looks to work. let me know if you have any more issues or you think there needs to be a doc change :) I'll close this for now but be monitoring it for anymore feedback you have.

**Comment by TechWriter975** [comment]
Joan Maltese
Technical Writer, Compliance and Risk | Enterprise Health & Safety
Pacific Gas and Electric Company
77 Beale St. 1513, San Francisco, CA 94105
760 420-3463

**Comment by TechWriter975** [comment]
Success! Thanks. Issue resolved.

Joan Maltese
Technical Writer, Compliance and Risk | Enterprise Health & Safety
Pacific Gas and Electric Company
77 Beale St. 1513, San Francisco, CA 94105
760 420-3463
