### ISSUE TITLE
Error in an example

### ISSUE THREAD

**Issue by LaurentXhrouet** [MicrosoftDocs/PowerShell-Docs#7281]
Hi,
In the "-eq and -ne" chapter, in the following example:
$a = 1, 2, $null, 4, $null, 6
$null -ne $a

The returned value of the second command is True, not False as illustrated.

OR

The example should be …
$null –eq $a

Kr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc199c1f-4ae0-c474-f2d3-bad43022109c
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about_Comparison_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hey @LaurentXhrouet, thanks for the feedback and this is a great catch :) 

I'll be updating the doc and you'll see the PR linked here. 

Thanks again and have a good one!
