### ISSUE TITLE
GitHub URL for the CssUri parameter

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/PowerShell-Docs#7285]
Does `-CssUri` expect the `.css` file to be in any specific syntax when it's loaded from an online source? I'm unable to get the parameter to work for an online location.

<details>

<summary>This CSS content works when in a local file.</summary>

```
<style>
BODY {font-family:verdana;}
TABLE {border-width: 1px; border-style: solid; border-color: black; border-collapse: collapse;}
TH {border-width: 1px; padding: 3px; border-style: solid; border-color: black; padding: 5px; background-color: #3F7AAE;}
TD {border-width: 1px; padding: 3px; border-style: solid; border-color: black; padding: 5px}
</style>
```
</details>

The cmdlet below is working

` Get-Process|select -First 2 -Property ProcessName,CPU,WS,Id | ConvertTo-Html -CssUri 'C:\Temp\test.css'|    Out-File proc.html; 
  Invoke-Item proc.html`

However, the same file content when loaded from an online location doesn't work.

`Get-Process|select -First 2 -Property ProcessName,CPU,WS,Id | ConvertTo-Html -CssUri 'https://raw.githubusercontent.com/Ayanmullick/AzPaaS/master/test.css'|Out-File proc.html;   Invoke-Item proc.html`

How could one consume a GitHub-hosted CSS file while creating an HTML report in PowerShell? Does the `type` need to be different in the `link` tag?

`<link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/Ayanmullick/AzPaaS/master/test.css" />`

<details>

<summary>$PSVersionTable</summary>

| Name                      | Value                        |
|---------------------------|------------------------------|
| OS                        | Microsoft Windows 10.0.19042 |
| PSVersion                 | 7.1.1                        |
| WSManStackVersion         | 3                            |
| PSCompatibleVersions      | {1.0, 2.0, 3.0, 4.0…}        |
| PSRemotingProtocolVersion | 2.3                          |
| PSEdition                 | Core                         |
| SerializationVersion      | 1.1.0.1                      |
| GitCommitId               | 7.1.1                        |
| Platform                  | Win32NT                      |

</details>

<details>

<summary>Get-Module -ListAvailable Microsoft.PowerShell.Utility|select ModuleType,Version,CompatiblePSEditions,Name</summary>

| ModuleType | Version | CompatiblePSEditions                             | Name                         |
|------------|---------|--------------------------------------------------|------------------------------|
| Manifest   | 7.0.0.0 | System.Collections.Generic.List`1[System.String] | Microsoft.PowerShell.Utility |
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe1f26d-62bb-8421-be81-7b6a0c68c810
* Version Independent ID: a2575b0d-d0ff-30fb-bf4d-3d79eec57f15
* Content: [ConvertTo-Html (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-html?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Html.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Html.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The cmdlet is producing the proper output. The issue is in the browser. The browser is not loading the CSS. I think this a cross-site security issue. When the browser loads the page from the local file system it does not load the CSS from a remote location. This should work if proc.html is hosted on a webserver or if the CSS file is available locally.

**Comment by Ayanmullick** [comment]
@sdwheeler , The document should state that the `CssUri` parameter argument needs to be a local file path only, not an online URI.

@ststimac, @kypflug, Could I work with someone to identify a workaround to this browser issue?

**Comment by sdwheeler** [comment]
@Ayanmullick I am not sure I agree. The cmdlet is creating the correct HTML. It is up to the browser to render it. I did some more research on this. This appears to be more of a GitHub problem. The type of the stylesheet is `text/css` but GitHub's raw URLs are serving `text/plain` content. If you search around StackOverflow and other sites you will find a lot of tools to work around this problem. Here are just a few:

- jsDelivr
- GitHub Pages
- CodeSandbox
- unpkg

**Comment by Ayanmullick** [comment]
@sdwheeler , Thanks for pointing it out.
 Yes, it's working from other sources. But I'm limited to ADO or GitHub. I wish the cmdlet did a `type` conversion for GitHub URL's at runtime. :smile:

**Comment by Ayanmullick** [comment]
FYI, GitHub has been tracking a `content-type mismatch` related bug since 2017. However, there is no ETA.
https://github.community/t/cannot-upload-zip-file-to-issues-on-windows-due-to-unusual-content-type-header/132447
