### ISSUE TITLE
Maybe disable every powershell telemetry version check by default (and not vice-versa) 

### ISSUE THREAD

**Issue by roelrens** [MicrosoftDocs/PowerShell-Docs#7292]
Software should not call home (no there is a new version, no telemetry) by default.

I still didn't find why there is still a version check (not needed we want to disable custom upgrades)
and why should we waste time with telemetry ? for every pwsh.exe started.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cef898a-9a16-9158-e3bb-de16a5b9df8c
* Version Independent ID: b42a2780-77cd-fd1d-32b4-371a84b63177
* Content: [Microsoft.PowerShell.Core Module - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
I'm sorry if I'm misunderstanding your question. Is there a documentation issue here? If you have a question or product issue you, you can submit and [issue here](https://github.com/PowerShell/PowerShell/issues/new/choose).
