### ISSUE TITLE
documentation is for powershell example is C#

### ISSUE THREAD

**Issue by T2MWorks-Mitch** [MicrosoftDocs/PowerShell-Docs#7294]
documentation is for powershell example is C#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55af845f-e3aa-8e4b-1669-5410c936c9a6
* Version Independent ID: bd920c9e-0c3d-2aab-cc5a-bfd5531d3e11
* Content: [Parameter Aliases - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/parameter-aliases?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/parameter-aliases.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/parameter-aliases.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@T2MWorks-Mitch This document is part of the PowerShell SDK documentation. The SDK documents explain how to create PowerShell cmdlets using C#.

**Comment by T2MWorks-Mitch** [comment]
thanks sean - I see that now - 
FYI it was the first hit when searching for "parameter aliases powershell" 
seems to me that the docs for "developing for powershell using C#"  should be clearly differentiated from the docs for "using powershell" but its lumped in with scripting ..

thanks
