### ISSUE TITLE
Formatting problems in Compare-Object examples

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/PowerShell-Docs#7295]
I think the example didn't render correctly for this one.

dog         <= squirrel=""><>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb91b5a-80ec-a598-39b5-bc58820f7293
* Version Independent ID: 85f1e969-8216-bed4-2204-409cbd9befd4
* Content: [Compare-Object (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/compare-object?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Compare-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Compare-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
@stephenc01 Thanks for pointing this out. The markdown source is correct, but our build system is rendering it incorrectly. I have filed a bug but don't know when it will be fixed.

**Comment by sdwheeler** [comment]
This is fixed now.
