### ISSUE TITLE
"Legacy" doc doesn't link to non-legacy version

### ISSUE THREAD

**Issue by JakeLunn** [MicrosoftDocs/PowerShell-Docs#7298]
This is under a "Legacy" header - can the Overview page display a Note and link to the non-legacy version?

![image](https://user-images.githubusercontent.com/11328029/109339683-97c40700-782d-11eb-9a74-a62095a7463f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2947bcac-713d-4498-c72e-ab16e39e8d48
* Version Independent ID: 12605f0f-a614-349d-be81-840f1aef0614
* Content: [Windows PowerShell SDK - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/windows-powershell?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/windows-powershell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/windows-powershell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hey @JakeLunn, 
As of right now, There isn't a non legacy version. This area is focused on PowerShell 5.1. We are planning on creating a new doc set  but not sure when this will be high enough on the queue. 

I'll be closing this for now but if you more, I'll be monitoring this and can reopen as needed.
