### ISSUE TITLE
Link to Broken Partial Article : Switch Parameter

### ISSUE THREAD

**Issue by skyhoshi** [MicrosoftDocs/PowerShell-Docs#7299]
Under the section : https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch?view=powershell-7.1#parameters
the outLink to: 
https://www.powershellmagazine.com/2013/12/20/using-powershell-switch-vs-boolean-parameters-in-sma-runbooks/
points to an article that is kinda broken. missing images. 

Could we get a newer example or summerize the points of the article in the MS Doc? it's not clear as to what the article is intended to do DUE to the missing Images. (Code as images are not great examples. I get "Code Copyright" but in this case, when using it as a teaching tool it's 100% broken.) 

I'm happy to provide additional feedback on this issue should clareification be needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57dde8fa-e186-29f3-ff07-57884ee157c0
* Version Independent ID: 9c03bc13-a80c-0a4c-0537-81235d4a849c
* Content: [Everything you ever wanted to know about the switch statement - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-switch.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-switch.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hey @skyhoshi, thanks for the feedback! 

I don't think the link is a good resource for the content of the article anyways as the link is talking about the switch parameter. I'll remove the link. The parameters for the switch statement are listed below where you found the link and have a explanation. I'll have the PR linked to this issue. 

Thanks again!
