### ISSUE TITLE
Doc new $PSStyle.Progress.UseOSCIndicator setting

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#7304]
# Summary of the new document or enhancement

- List of articles that need to be updated:
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/14927
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

This is enabled behind `PSAnsiProgress` experimental feature.  Defaults to `$false`.  When `$true`, it will use the sequences defined in https://github.com/microsoft/terminal/issues/6700 to show progress information in the terminal window (if supported).  I'm only aware of conemu and Windows Terminal supporting this sequence.  iTerm2 on MacOS doesn't support this.

**Comment by sdwheeler** [comment]
Closed by #7372
