### ISSUE TITLE
Format-Hex example 2 is incorrect

### ISSUE THREAD

**Issue by r-palgesci** [MicrosoftDocs/PowerShell-Docs#7314]
[the example 2 is incorrect as there is no -count parameter for the cmdlet Format-hex,  Please amend this example - I am surprised you have not been contacted about this before
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c68978a3-93f6-51de-3714-efa6a2c7f453
* Version Independent ID: 17518c3b-829a-bb20-8b3a-f82349d64762
* Content: [Format-Hex (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-hex?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Format-Hex.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Format-Hex.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hey @r-palgesci thanks for the feedback here. It looks like you are looking at the PowerShell 7.1 documentation which doesn have the `-Count` param but the [PowerShell 5.1 documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-hex?view=powershell-5.1) is accurate for that version which I believe is the version you are probably using? 

Let me know if this is the case or if there is something else going on :) Thanks again

**Comment by r-palgesci** [comment]
Apologies for my mistake.  Thank you for  contacting me.  I was unaware that I was running version 5.1;  not the latest 7.1 version. I feel pretty silly for posting it now.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chasewilson** [comment]
No apologies needed :) It happens and we're happy that people like yourself that are willing to let us know about things they find in our docs. Feel free to reach out anytime!
