### ISSUE TITLE
Address confusion around 'Persist" parameter name with net use /persistent

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/PowerShell-Docs#7316]
**Scenario**
I'm familiar with net use, and map network drives frequently. net use uses "persistent" to keep drive mappings across reboots. Azure Files provides a powershell snipit for mapping a file. I want to map a drive but not keep it between reboots.

When I look at the powershell snipit provided by Azure it includes the "Persist" switch. I assume that Microsoft is using the term in powershell in the same way the use it in net use. To preserve drive mapping between reboots. Boy was I wrong!

Was on the phone with a member of the azure files team troubleshooting why drive mapping wasn't showing up as a drive letter, and they too were unaware that the -persistent behavior in this command behaves differently from net use.

**Goal**
Share feedback that the New-PSDrive parameters created a misunderstanding that I spent at least an hour trying to troubleshoot due to this misunderstanding. And, that the current documentation doesn't appear to acknowledge this shift in meaning between the two commands.

Reading through the description of net use /persistent, it clearly says it preserves mapping between reboot.
Reading through the article for New-PSDrive I see no indication how to make drives persist across reboot or only the current _session_. Current _windows session_ was my assumption, but experience tells me it is the current _powershell session_.

How do have a New-PSDrive persist, and not persist between reboots?

**Recommendations**
Update the parameter description to specify poweshell session.

Update the top paragraph about the new "Persist" switch and add a statement along the lines of
> Drives mapped using New-PSDrive -Persist are not restored at next login, use (new powershell method? or "net use /persist") to create a drive mapping that is restored at next login.

**Notes**
net use /persistent
> /persistent: {yes \| no} | Controls the use of persistent network connections. The default is the setting used last. Deviceless connections are not persistent. Yes saves all connections as they are made, and restores them at next logon. No does not save the connection being made or subsequent connections. Existing connections are restored at the next logon. Use /delete to remove persistent connections.

Summary: drives mapped using net use are always manageable using standard windows tools. Use /persistent for the mapped drive to appear in standard windows tools after a reboot.

New-PSDrive -Persist
>You can use the Persist parameter of New-PSDrive to create Windows mapped network drives. Unlike temporary PowerShell drives, Windows mapped network drives aren't session-specific. **They're saved in Windows and they can be managed by using standard Windows tools, such as File Explorer and net use.** Mapped network drives must have a drive-letter name and be connected to a remote file system location. When your command is scoped locally, no dot-sourcing, the Persist parameter doesn't persist the creation of a PSDrive beyond the scope in which the command is running.
>
>Mapped network drives are saved in Windows on the local computer. They're persistent, not session-specific, and can be viewed and managed in File Explorer and other tools.

Summary: drives mapped using New-PSDrive can be managed using standard windows tools by using the -Persist switch. No comment on how to have mapped drives appear in standard windows tools after a reboot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12dc4c83-a2cf-5baf-8881-cc94ceb7a97f
* Version Independent ID: a45957af-1dfa-226b-c4d4-2a84b0e82962
* Content: [New-PSDrive (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/New-PSDrive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/New-PSDrive.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@jonwbstr Can you provide a link to the Azure documentation you mention? I want to understand what that documentation is saying. 

I think you ran into an issue of scope and we probably need to make that clearer in the docs.

**Comment by jonwbstr** [comment]
This issue has the source document in the ticket details.

The net use documentation is here
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/gg651155(v=ws.11)

Is that what you are looking for?

**Comment by sdwheeler** [comment]
> When I look at the powershell snipit provided by Azure it includes the "Persist" switch.

@jonwbstr Where are you getting this Azure snipit?

**Comment by jonwbstr** [comment]
Oh that part.
Azure portal > storage account > file share > [share name] > connect to
share

It's a dynamicly generated snippit written for the specific storage account
and azure files file share.

This article outlines the steps, however
https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-windows#mount-the-azure-file-share

After configuring azure ad ds authentication the generated snippit changes
to what is shown in this article

https://docs.microsoft.com/en-us/azure/storage/files/storage-files-identity-auth-active-directory-domain-service-enable?tabs=azure-portal#mount-a-file-share-from-a-domain-joined-vm

**Comment by chasewilson** [comment]
It looks like the issue here is that the script provided doesn't have the **Scope** parameter set to `Global`.

As it says in the doc. Even with the **Persist** switch, if the scope isn't set to `Global` it won't persist outside the scope where the command was run. 

I realize this isn't provided in the Azure script and should probably be addressed with an issue. I'll do some digging and see where you might be able to submit a request if this is in fact the issue you are having. 

I'll close this for now but monitor it for response if you feel the documentation is incorrect.

**Comment by jonwbstr** [comment]
Hello, would you share where in the description of the "scope" parameter it indicates using a scope of "global" will cause the drive mapping to persist between reboots? In my experience even global variables are cleared when the powershell session is terminated.

My feedback was to put something in the article that explains how to get the drive to be persistent between reboots, and until it does so, I will consider the documentation incomplete.

I also suggested referencing the previous way to perform the same operation to help readers that are familiar with the legacy method identify  "this is the new method"

I gave suggestions of edits that could make this transition from the legacy method to the new method more graceful. If you don't like any of them, might I suggest adding another Example that calls out this specific scenario?

> Example 5: Create persistent and temporary drives that persist between reboots
> This example shows how to create a drive mapping that persists between reboots, similar to 'net use Z: <path> /persisitant'
> [PS] C:\> ---- example command ----
