### ISSUE TITLE
Document that the process-level current directory, as seen by .NET, differs from PowerShell's

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#7318]
Since PowerShell supports multiple runspaces in a single process, and each runspace must be able to maintain its own _current location_, PowerShell cannot use the _process-level_ current (file-system) directory, which is the one that .NET APIs see and use - see https://github.com/PowerShell/PowerShell/issues/3428

That is, `[Environment]::CurrentDirectory` (the process-level current directory) is generally _not_ in sync with PowerShell's `Get-Location` / `$PWD` (the runspace-specific current location).

This constitutes a pitfall when passing _relative_ file-system item paths to .NET methods, as they will be interpreted relative to the _process-level_ directory, not to PowerShell's.

This pitfall, which can have destructive consequences (e.g., deleting files from the wrong directory)  is worth documenting; the upshot is: In PowerShell:

* Don't use `[Environment]::CurrentDirectory`  - use `Get-Location` / `$PWD` and generally stick to using PowerShell cmdlets; using .NET APIs directly is an advanced use case.
 
* Always use full, native paths when referring to file-system items in .NET method calls; see #7319

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e26f3d1-13e4-5d8b-41be-e5abc4156117
* Version Independent ID: 362d9a19-f0b2-2cc8-9ee7-e3da1dda9354
* Content: [about_Locations - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_locations?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Core/About/about_Locations.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Core/About/about_Locations.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
This is covered in [Get-Location](https://docs.microsoft.com/powershell/module/microsoft.powershell.management/get-location) but should probably added here and in about_Automatic_Variables for `$PWD`.
