### ISSUE TITLE
How to Support Jobs - Type Casting Question

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#7320]
Why does the *job* class use `PSObject.AsPSObject()` to cast `pl`? 

```
Output.Add(PSObject.AsPSObject(pl));
```

* [PSObject.AsPSObject(Object) Method](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psobject.aspsobject?view=powershellsdk-7.0.0)

### - versus -

Why does the *cmdlet* class use `new PSObject()`? 

```
job.ChildJobs[0].Output.Add(new PSObject(pl));
```

* [PSObject(Object) Constructor](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psobject.-ctor?view=powershellsdk-7.0.0#System_Management_Automation_PSObject__ctor_System_Object_)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c13d87-511f-c9f3-ded2-4d546570bad8
* Version Independent ID: ddfef008-6b0f-6d6b-64f5-e0319fb728c0
* Content: [How to Support Jobs - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by SteveL-MSFT** [comment]
`AsPSObject()` simply uses the constructor internally so the two are equivalent.  It's simply a preference for the developer which one they want to use.

**Comment by juvtib** [comment]
Ok. I thought there might be some nonobvious reason for the change. As far as I'm concerned, I'm satisfied with this explanation.

**Comment by sdwheeler** [comment]
Actually, after further discussion, there is a difference.

`PSObject.AsPSObject()` should be preferred because it does what the constructor can't, which is to return the input if it was already a PSObject. If you use the constructor around something that's already a **PSObject**, it will doubly wrap it. `AsPSObject()`, on the other hand, is idempotent, so calling it multiple times won't give you a deeper and deeper object.
