### ISSUE TITLE
How to Support Jobs - What creates a child job

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#7321]
What creates a child job? 

Does the SDK automatically create a child job for each `Job` object? 

> If the work is performed as a job, add child job to the job.

```
job.ChildJobs[0].Output.Add(new PSObject(pl));
```
`Add()` [is a method](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psdatacollection-1.add?view=powershellsdk-7.0.0) for `PSDataCollection`. 

`Output` [is a property](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.job.output?view=powershellsdk-7.0.0) of `Job`. 

`ChildJobs` [is a property](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.job.childjobs?view=powershellsdk-7.0.0) of `Job`. 

> List of child jobs contained within this job. 

* [Child Jobs | about_Job_Details](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_job_details?view=powershell-7.1#child-jobs)
* [... Child Jobs ... | Background Jobs](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/background-jobs?view=powershell-7.1#background-jobs-child-jobs-and-the-job-repository)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c13d87-511f-c9f3-ded2-4d546570bad8
* Version Independent ID: ddfef008-6b0f-6d6b-64f5-e0319fb728c0
* Content: [How to Support Jobs - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
There are no plans to update these docs. If anyone can come up with a better working example and wants to submit code and an article, we would consider taking the submission.
