### ISSUE TITLE
How to Support Jobs - Redundant Methods

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#7322]
- [ ] Why does `void DoProcessLogic(bool asJob)` exist if `ProcessRecord()` uses `job.ProcessJob()`? 

Alternatively, is it best practice to always create `private SampleJob job = new SampleJob("Get-ProcAsJob")` and use `job.ProcessJob()` even when `asjob == false`? 

```
    private SampleJob job = new SampleJob("Get-ProcAsJob");

    protected override void ProcessRecord()
    {
      if (asjob)
      {
        JobRepository.Add(job);
        WriteObject(job);
        ThreadPool.QueueUserWorkItem(WorkItem);
      }
      else
      {
        job.ProcessJob();
        foreach (PSObject p in job.Output)
        {
          WriteObject(p);
        }
      }
    }
```

It doesn't seem like [#5441](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5441) is resolved. 

- [ ] Step 5 might need to be updated. 

> 5. If the cmdlet performs the work, call the System.Management.Automation.Cmdlet.WriteObject method to return a process object to the pipeline. If the work is performed as a job, add child job to the job. 

- [ ] [Writing a Cmdlet That Runs as a Background Job](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/background-jobs?view=powershell-7.1#writing-a-cmdlet-that-runs-as-a-background-job) might be impacted. 

> Return the appropriate objects, depending on whether the cmdlet is run as a background job.

- [ ] The SDK might be affected. 

> // To load this cmdlet, create a module folder and copy the GetProcessSample06.dll
> // assembly into the module folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c13d87-511f-c9f3-ded2-4d546570bad8
* Version Independent ID: ddfef008-6b0f-6d6b-64f5-e0319fb728c0
* Content: [How to Support Jobs - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
There are no plans to update these docs. If anyone can come up with a better working example and wants to submit code and an article, we would consider taking the submission.
