### ISSUE TITLE
How to Support Jobs - Example Members Not Implemented

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#7325]
We are looking at example code, but several common members return `NotImplementedException()`. Are these documented elsewhere? 

```
public override string StatusMessage
{
  get { throw new NotImplementedException(); }
}

public override string Location
{
  get { throw new NotImplementedException(); }
}

public override void StopJob()
{
  throw new NotImplementedException();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c13d87-511f-c9f3-ded2-4d546570bad8
* Version Independent ID: ddfef008-6b0f-6d6b-64f5-e0319fb728c0
* Content: [How to Support Jobs - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
There are no plans to update these docs. If anyone can come up with a better working example and wants to submit code and an article, we would consider taking the submission.
