### ISSUE TITLE
Doc supported TERM env var values

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#7326]
# Summary of the new document or enhancement

- List of articles that need to be updated:
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/14969
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/issues/14964

## Description of what changed

Respect TERM env var where:

`dumb` set SupportsVirtualTerminal = false
`xterm-mono` set `$PSStyle.OutputRendering = PlainText`
`xtermm` set `$PSStyle.OutputRendering = PlainText`

if `$env:NO_COLOR` exists, set `$PSStyle.OutputRendering = PlainText`

Note that if you try this interactively, PSReadLine doesn't respect these two values so on screen output will be hard to read as it still emits colors and cursor movements. Created PowerShell/PSReadLine#2277 to track this.

This works on all platforms including Windows.

**Comment by yaxye8123** [comment]
That is a good idea
