### ISSUE TITLE
Installation via Package Repository - Ubuntu 20.04 procedure does not work on a freshly installed, ARM64-based Ubuntu Server

### ISSUE THREAD

**Issue by Crono1981** [MicrosoftDocs/PowerShell-Docs#7333]
I've followed the procedure line by line and yet when I get to installing powershell I get the following error:

```
E: Unable to locate package powershell
```

I'm using an ARM64 architecture but I was [led to believe that this would not be an issue](https://docs.microsoft.com/en-us/powershell/scripting/install/powershell-core-on-arm?view=powershell-7.1).

Is the documentation still accurate?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
The instructions for installing Ubuntu 20.04 are for the amd64 package, not the Arm package. The only Arm package available is powershell-7.1.2-linux-arm64.tar.gz. I will see if we can get some instructions for installing on Arm.

**Comment by sdwheeler** [comment]
@Crono1981 Have you tried these instructions https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation---binary-archives ?

**Comment by Crono1981** [comment]
@sdwheeler Actually yes, I came across those almost immediately after posting. And it did work. 👍 

I just hoped there would be something about a package that I had missed.

Thanks for your help!
