### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by unichaun** [MicrosoftDocs/PowerShell-Docs#7344]
if( $myobject.psobject.properties.match('ID').Count )

Above doesn't work:

Missing statement block after if ( condition ).
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingStatementBlock

Update:  
Ah, missing curly brackets:
if( $myobject.psobject.properties.match('ID').Count ) {"do something here"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86c9d989-17c8-2a16-5c39-232e3dade004
* Version Independent ID: 8e72ce06-198a-ec18-2e87-332697391fee
* Content: [Everything you wanted to know about PSCustomObject - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-pscustomobject?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
@unichaun glad it works now :)
