### ISSUE TITLE
Error when using -ContentType 'application/json'

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/PowerShell-Docs#7345]
When using:
        $body = @{    
            Manager  = "spmigrationuser@contoso.com" #$item.PMEmail
            Name     = "some name"
            Number   = "Some number"
            Practice = "Some Practice"
        } 
$response = Invoke-RestMethod -Method Post -Uri $Url  -Body $body -ContentType 'application/json' # -Headers $Headers  
Or
$response = Invoke-WebRequest -Method 'POST' -Uri $Url  -Body $body -ContentType 'application/json' # -Headers $Headers  

Neither ContentType 'application/json' 
Nor
$Headers = @{'Content-Type' = 'application/json' }
-Headers $Headers  
Works

The error is always:
"Invoke-WebRequest : {"error":{"code":"InvalidRequestContent","message":"The request content is not valid and could not be deserialized: 'Error parsing NaN value. Path '', line 1, position 1.'."}}"

The same call works in 

I am using PS 5.1 and I must have -ContentType 'application/json' otherwise PS works but the service fails 

What can be the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5053dee-ceef-0af8-3abf-0d4c7ca2e51d
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hey @Ofer-Gal, thanks for the question. It might be because you need to convert your hashtable to json with `ConvertTo-Json`. 

Let me know if this helps

**Comment by chasewilson** [comment]
Hey @Ofer-Gal, thanks for the question. It might be because you need to convert your hashtable to json with `ConvertTo-Json`. 

Let me know if this helps

**Comment by chasewilson** [comment]
I'll be closing this for now but monitoring if you need anything more and  can reopen if necessary

Thanks again and have a great weekend.

**Comment by Ofer-Gal** [comment]
I tried with  -Body ($body | ConvertTo-Json)  and had the same issue

**Comment by sdwheeler** [comment]
The error message returned says that some value you sent is NaN (Not a number). It looks like the content of `$body` is not valid for the REST endpoint.
