### ISSUE TITLE
Syntax Doesn't Seem to Document Running a Script as an Unnamed Argument

### ISSUE THREAD

**Issue by johnslattery** [MicrosoftDocs/PowerShell-Docs#7356]
It doesn't seem the syntax described on the page includes running a script as `powershell .\script.ps1` though it clearly works. Why is that?

My testing seems to suggest this invocation is the same as `powershell -Command .\script.ps1`. Is that true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776d0240-b9cb-fdb3-be53-eb72434040de
* Version Independent ID: 2a47dda6-5d42-249c-5d48-19ad6fbc7b3c
* Content: [about_PowerShell_exe - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
Undocumented feature. Yes it works. But it is better to use the full syntax.

I am not sure which parameter it is binding to. It results are the same for `powershell -Command .\script.ps1` and `powershell -File .\script.ps1`. But it is probably binding to the `-Command` parameter.
