### ISSUE TITLE
Mention that -Option is a flag-based enumeration and therefore accepts *multiple* values

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#7357]
The parameter name - `Option` (singular) - doesn't indicate that the type is a _flag_-based enumeration (one decorated with [`System.FlagsAttribute`](https://docs.microsoft.com/en-US/dotnet/api/System.FlagsAttribute)), and even though the type name is a plural ( [`ScopedItemOptions`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.ScopedItemOptions)), the fact that isn't declared as an _array_ (which isn't required) makes it non-obvious that _combinations_ of values may be passed, so I suggest the following:

* Mention explicitly that an _array_ of the supported enumeration values may be passed, which are implicitly bit-ORed behind the scenes (see example below).

* Show at least one example of passing multiple values.

It isn't obvious, but multiple values can actually passed as an _array_ (not just a _single string_ containing a comma-separated list of names).

For instance, the following works fine:

```powershell
New-Variable foo bar -Option ReadOnly, AllScope
```

It is the more convenient equivalent of:

```powershell
New-Variable foo bar -Option 'ReadOnly, AllScope'
```

and the most verbose:

```powershell
New-Variable foo bar -Option ([System.Management.Automation.ScopedItemOptions]::ReadOnly -bor [System.Management.Automation.ScopedItemOptions]::AllScope)
```

The array-based way of passing multiple values is the one that should be recommended, because:

* it is the simplest to type
* you get the benefit of tab-completion for individual values

On a related note, https://github.com/PowerShell/PowerShell/issues/15058 suggests having the syntax diagrams reflect flag-based enumerations as such.

---

Note: The same applies to `Set-Variable`, and I suggest reviewing *all* cmdlets that have flag-based enumeration parameters:

The following is the list of cmdlets that have flag-based enumeration parameters, with the relevant parameters flagged with a trailing `+`

```none
Cmdlet            EnumParams                              EnumTypes
------            ----------                              ---------
Add-Member        {MemberType+}                           System.Management.Automation.PSMemberTypes
Export-PSSession  {CommandType+}                          System.Management.Automation.CommandTypes
Get-Command       {CommandType+}                          System.Management.Automation.CommandTypes
Get-Member        {MemberType+, View+}                    {System.Management.Automation.PSMemberTypes, System.Management.Automation.PSMemberViewTypes}
Import-PSSession  {CommandType+}                          System.Management.Automation.CommandTypes
Invoke-RestMethod {Method, Authentication, SslProtocol+}  {Microsoft.PowerShell.Commands.WebRequestMethod, Microsoft.PowerShell.Commands.WebAuthenticationType, Microsoft.PowerShell.Commands.WebSslProtocol}
Invoke-WebRequest {Authentication, SslProtocol+, Method}  {Microsoft.PowerShell.Commands.WebAuthenticationType, Microsoft.PowerShell.Commands.WebSslProtocol, Microsoft.PowerShell.Commands.WebRequestMethod}
New-Alias         {Option+}                               System.Management.Automation.ScopedItemOptions
New-Variable      {Option+, Visibility}                   {System.Management.Automation.ScopedItemOptions, System.Management.Automation.SessionStateEntryVisibility}
Send-MailMessage  {DeliveryNotificationOption+, Priority} {System.Net.Mail.DeliveryNotificationOptions, System.Net.Mail.MailPriority}
Set-Alias         {Option+}                               System.Management.Automation.ScopedItemOptions
Set-TraceSource   {Option+, ListenerOption+}              {System.Management.Automation.PSTraceSourceOptions, System.Diagnostics.TraceOptions}
Set-Variable      {Option+, Visibility}                   {System.Management.Automation.ScopedItemOptions, System.Management.Automation.SessionStateEntryVisibility}
Trace-Command     {Option+, ListenerOption+}              {System.Management.Automation.PSTraceSourceOptions, System.Diagnostics.TraceOptions}
Update-TypeData   {MemberType+}                           System.Management.Automation.PSMemberTypes
```

It seems that at least _some_ topics mention multiple values, but:

* some don't specify _how_ to pass multiple values 

* at least one (`Trace-Command`) recommends the _string_-based way of passing them:
> To specify multiple options, separate them with commas, but with no spaces, and enclose them in quotation marks, such as "ProcessID,ThreadID".

I suggest changing that to recommend the _array_-based way, and to mention that in _all_ relevant parameter descriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 713ba92b-294e-19a3-755e-88076c7451c1
* Version Independent ID: 2ac0d6e6-85d2-4a10-0a1f-9296983b1dc8
* Content: [New-Variable (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-variable?view=powershell-7.1&WT.mc_id=ps-gethelp)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/New-Variable.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/New-Variable.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by mklement0** [comment]
@SeeminglyScience points out that not all parameters that accept a flag-based `enum` type instance necessarily accept _multiple_ values, depending on the cmdlet's purpose.

For instance, `Add-Member`'s  `-MemberType` parameter, even though its type is the flag-based `System.Management.Automation.PSMemberTypes` type, only accepts _one_ enumeration value.

**Comment by chasewilson** [comment]
Great to remember, I'm testing each cmdlet you suggested before creating an issue, but if you see any problems with how we move forward, feel free to let me know.
