### ISSUE TITLE
Script Module PowerShellGet - Why would I want two versions installed? 

### ISSUE THREAD

**Issue by LivingTheDream33** [MicrosoftDocs/PowerShell-Docs#7361]
[Enter feedback here]
I've been having an issue with a few scripts and I'm trying to hunt down the issue. 
I've noticed that I have multiple version of the same  module installed and wanted to know if there is a necessary reason for that? My research show some people recommend run the "-force" optional switch when installing modules which I believe will apply multiple version to a PowerShell. Is this a good protocol to follow? 
Question 1 - Do I need multiple version of a module in PowerShell like PowerShellGet? I have Ver 1.0.0.1 and Ver 2.2.5.  
Question 2 - Are the versions typically rollup versions of the previous version or are cmdlets removed or added with different versions (MicrosoftTeams ver 2.0.0)? 

Do you have a site or resource that you can recommend for managing versions of PowerShell modules? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
PowerShell's module systems allows you to have multiple versions installed, side-by-side. The `Import-Module` cmdlet has a `-RequiredVersion` that can be used to load a specific version. It depends on your environment. It could be that there are compatibility issues in some scenarios where you want to load a different version of the module into your session. But if you do not specify a version, PowerShell loads the highest installed version by default.

You can safely delete older version if they are no longer needed. Each version of a module is a full replacement an older version. However, cmdlets and parameters can be added or removed in any new version of a module. If the module was installed using `Install-Module`, it can be removed using `Uninstall-Module`. If the module was installed some other way, you can manually delete it.

PowerShellGet is a special case. Version 1.0.0.1 shipped in Windows with PowerShell 5.1. You cannot remove that version or any of the other modules that ship in PowerShell 5.1.
