### ISSUE TITLE
Depth parameter is not supported for this cmdlet

### ISSUE THREAD

**Issue by HaloX69** [MicrosoftDocs/PowerShell-Docs#7368]
This documentation is incorrect.  It indicates that this cmdlet supports the Depth parameter, but this parameter is only supported in ConvertTo-Json.  Please correct this misleading information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d08ac-a648-7e0a-6af4-b2dc18a534bd
* Version Independent ID: 28f7f22d-c3a6-ea62-c77b-672d7e16fc80
* Content: [ConvertFrom-Json (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
You are looking at the documentation for PowerShell 7.1, which includes that parameter. That parameter is not available in PowerShell 5.1. Please see https://docs.microsoft.com/powershell/scripting/how-to-use-docs
