### ISSUE TITLE
Comment based help for PowerShell 7 classes

### ISSUE THREAD

**Issue by GenesisCoast** [MicrosoftDocs/PowerShell-Docs#7385]
Is it possible to update the documentation page to reference how the comment based help can be utilized to decorate PowerShell classes (PowerShel 7) with documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 208e74df-f0c4-2841-82f9-8c9ff22e8b31
* Version Independent ID: 3ae6b0ce-e9bb-a441-92b2-cf12402e1f97
* Content: [about_Comment_Based_Help - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hey @GenesisCoast, thanks for your feedback here. 

According to [this issue](https://github.com/PowerShell/PowerShell/issues/2225) in the PowerShell gallery, comment based help isn't accessible yet in the same way they are for function or cmdlets. 

You can still write help into classes the same way as you would a function, they're just comments, but as of right now, you would have to go look at your source code to access the help. 

If you wanted this to be accessible in a new version of PowerShell you might bring the issue to the attention of the PowerShell team and see if it would be something to add. 

I'll be closing this issue for now but feel free to respond and I can reopen if necessary. 

Have a great rest of your week!
