### ISSUE TITLE
Document use of universal packages

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#7387]
# Summary of the new document or enhancement

- List of articles that need to be updated:
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md

- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo:
https://github.com/PowerShell/PowerShell/pull/15109

- Link(s) to related issue(s) in the PowerShell/PowerShell repo:
https://github.com/PowerShell/PowerShell/issues/14848

## Description of what changed
everything will remain the same prior to 7.2 as this is a breaking change.

7.2 and later, the package name for all deb and RPM platforms will be the same.
repo names will still vary per distro, as other products may not be able to be so universal.

**Comment by sdwheeler** [comment]
@TravisEz13 We are going to need install instructions for this new package.

**Comment by TravisEz13** [comment]
installing from the repo will be the same for each distro, so it won't save a lot there.

installing from the package, the instructions will be more similar, except where there are workarounds or extra steps

**Comment by sdwheeler** [comment]
@TravisEz13 Can you update the notes on this issue? What are the workarounds or extra steps?

**Comment by TravisEz13** [comment]
right now, they are hypothetical.

**Comment by sdwheeler** [comment]
Fixed in #8148
