### ISSUE TITLE
Document IArgumentCompleterFactory and parameterized ArgumentCompleters

### ISSUE THREAD

**Issue by powercode** [MicrosoftDocs/PowerShell-Docs#7390]
# Summary of the new document or enhancement
 
https://github.com/PowerShell/PowerShell/pull/12605 adds support for parameterized argument completers.

This will be available in PowerShell 7.2.

By deriving from ArgumentCompleterAttribute and Implement IArgumentCompleterFactory, the derived attribute can use properties set on the attribute to control the IArgumentCompleter instance that is created.

This allows more generic implementations of completers.

The interface is really simple. 
It is only a single method.
```CSharp
IArgumentCompleter Create();
```

Examples of how this can be used are shown below:

```C#
[DirectoryCompleter(ContainingFile="pswh.exe", Depth=2)]

[DateCompleter(WeekDay='Monday', From="LastYear")]

[GitCommits(Branch='release')]
```

Details of requested document:

- Proposed title: Parameterized Argument Completers.
- Propose location in the TOC: 
- Target audience: Developers and advanced scripters
- Purpose or scenario:
  _or_
  Proposed changes/additions to existing article:
- List of related articles to link to: `IArgumentCompleter`

**Comment by sdwheeler** [comment]
@powercode does this work in scripts? Can you provide a scripted example?
