### ISSUE TITLE
Introduce an official term for the ability to assign to multiple variables simultaneously - destructuring assignments

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#7394]
The section heading states "Assigning multiple variables", but otherwise gives no name to the ability to do assignments such as:

```powershell
$first, $rest = 1..5  # -> $first = 1; $rest = 2..5
```

My suggestion is to officially introduce the term _destructuring assignment_ and to use it throughout the documentation.

([Wikipedia](https://en.wikipedia.org/wiki/Assignment_(computer_science)) mentions additional terms used across programming languages, but _destructuring assignment_ seems appropriate to me, given that even the simple case of `$a, $b = 1, 2` - called _parallel_ assignment in some languages - is technically a _destructuring_ in PowerShell, given that `1, 2` is an _array_.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c302a39f-9c93-64e1-ab5e-525e149a5a76
* Version Independent ID: feb83e02-9de2-4773-7614-25e6c4e14cd9
* Content: [about_Assignment_Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_assignment_operators?view=powershell-7.1#assigning-multiple-variables)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by vivere-dally** [comment]
Can you do something like this:
```js
const obj = [
    {'a': 1, 'b': 2},
    {'a': 2, 'b': 3}
];

for (const {a, b} of obj) {
    console.log(a);
    console.log(b);
}
```
in powershell?

**Comment by mklement0** [comment]
@vivere-dally, no, but in this case regular property access isn't really an inconvenience: `foreach ($obj in $objects) { $obj.a, $obj.b }`.
However, the ability to enumerate _parallel collections_ would be handy (`foreach ($elementA, $elementB in $collectionA, $collectionB) { ... }`, which currently isn't supported, but is proposed in https://github.com/PowerShell/PowerShell/issues/14732

**Comment by sdwheeler** [comment]
We already have suitable terminology for this. It is _multiple assignment_.  From section **7.11.1 Simple assignment** of the PowerShell Language Specification Version 3.0.

> As shown by the grammar, _expression_ may designate a comma-separated list of writable locations. This is known as _multiple assignment_. _statement_ designates a list of one or more comma-separated values. The commas in either operand list are part of the multiple-assignment syntax and do not represent the binary comma operator. Values are taken from the list designated by _statement_, in lexical order, and stored in the corresponding writable location designated by _expression_. If the list designated by _statement_ has fewer values than there are _expression_ writable locations, the excess locations take on the value $null. If the list designated by _statement_ has more values than there are _expression_ writable locations, all but the right-most _expression_ location take on the corresponding _statement_ value and the right-most _expression_ location becomes an unconstrained 1-dimensional array with all the remaining _statement_ values as elements.

**Comment by mklement0** [comment]
Good to know, but PowerShell users generally don't read language specifications.

And _multiple assignments_ isn't very descriptive, given that `$a = 1; $b = 2` can also rightfully be called that.

**Comment by mklement0** [comment]
A compromise would be _multi-assignment_, which is still recognizable as related to the specification, but avoids ambiguity.

**Comment by mklement0** [comment]
Thanks for tackling this so quickly, @sdwheeler, but I think it would help to at least _also_ mention "multi-assignment" as an official alias of sorts - to allow a more concise, less ambiguous term to be used when referring to the construct.

**Comment by sdwheeler** [comment]
@mklement0 I mention it in the change to about_Assignment_Operators which I link to in the new example in about_Variables.

**Comment by mklement0** [comment]
On a meta note: By now I'm used to non-engagement of specific arguments by those who make decisions. The best I can  do is lay out arguments for future readers.

It's great that:

* action was taken quickly.

* _an_ official term was chosen.

It's regrettably _what_ term was chosen:

* A term that only exists in the _spec_ is a great starting point, but, in its absence from user-facing documentation and in the absence of this term being widely known, it shouldn't be considered binding, _if a better alternative is available_ - the user-facing doc could then, on a one-time basis, simply mention how the chosen, better term relates to the spec.

* _Multiple assignment_ is an unfortunate term due to its generic, ambiguous nature, especially when _pluralized_: "PowerShell supports _multiple assignments_". Even in the singular it is awkward, given the expectation that the word _multiple_ is followed by a plural: "PowerShell supports _multiple assignment_." 
  * _Multi-assignment_ builds on that term while avoiding these ambiguities and making it clearer that a specific feature is being named.
  * _Destructuring assignment_ still strikes me as the best choice, both because it is technically apt in PowerShell, and because it is well known from other languages.

**Comment by sdwheeler** [comment]
I don't think _multi-assignment_ provides any less ambiguity and _destructuring assignment_ is overly complicated language. Personally, I like _parallel assignment_. 

Frankly, I don't think it needs an _official_ term, but it does need to be explained with examples.

**Comment by chasewilson** [comment]
@mklement0, You're probably already aware but from what I can find, **multiple assignment** seems to be a pretty consistent term for this action accross at least a few different languages, leading back to the term **assignment** in CS in general. 

Now, CS isn't my expertise and I'm open to discussions but if this is a common term across languages, is there a benefit to coming up with a term specifically for PowerShell?

**Comment by mklement0** [comment]
Thanks for engaging, @sdwheeler and @chasewilson.

_Multi-assignment_ makes it clear that this is a "thing", a specific concept rather than just the noun _assignment_ incidentally qualified with the adjective _multiple_.

To me, _destructuring assignment_, while polysyllabic, strikes a good balance between concision and expressiveness, and is also familiar from other languages (though [in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) it can do more than just destructure _collections_ - it also supports destructuring object properties).

_Parallel assignment_ to me is better than _multiple assignment_, and if the choice were limited to these, I'd definitely go with the former.

> Frankly, I don't think it needs an official term, but it does need to be explained with examples.

Given concepts and features a name that is _documented and therefore widely used and understood_ (which is what I mean by "official") is of vital importance: 

If a concept and feature that doesn't have a name at all in the documentation, or no _consistent_ name across various topics, the concept may never "gel" in users' minds, or the differing names may cause confusion.

That's why I've been pushing for introducing names for _member enumeration_, _delay-bind script blocks_ , _intrinsic members_, ... (the first 2 have now been introduced).

@chasewilson:

> but if this is a common term across languages

It is _one_ of the terms, but by no means the dominant one - presumably due its general vagueness, but also for suggesting a false opposite of the term "single assignment" (which isn't used in PowerShell - it refers to one-time initialization); to quote the linked Wikipedia article: "is sometimes called _multiple assignment_, though this is confusing when used with "single assignment", as these are not opposites."

> coming up with a term specifically for PowerShell?

Both _destructuring assignment_ (my preference) and _parallel assignment_ (my second preference) are established terms.

My proposal, _multi-assignment_, wouldn't be a _new_ term  as such - it is readily recognizable as related to _multiple assignment_, but _less ambiguous_ in my mind. 
The only reason I proposed it was because I assumed that there was a - to my mind unnecessary - commitment to the term used in the _spec_. (Again, a one-time comment along the lines of "This is called _parallel assignment_ (also known as _multiple assignment_ in the PowerShell language specification)." would be sufficient.

**Comment by mklement0** [comment]
P.S.: I'm warming up to the term _parallel assignment_: it seems to be widely used, and it avoids the ambiguity of _multiple assignment_.

It doesn't capture the de-structuring aspect, but, conversely, _destructuring assignment_ may be overselling what PowerShell does.

Ultimately, the feature can be used for two distinct purposes:

* (a) Make assigning values to multiple variables more concise:

```powershell
$a, $b = 1, 2
```

* (b) Partition a collection:

```powershell
$coll = 1..5

$first, $second, $rest = $coll    # -> $first = 1; $second = 2; $rest = 3, 4, 5
```

_Parallel assignment_ highlights (a), whereas _destructuring assignment_ highlights (b).

**Comment by sdwheeler** [comment]
@mklement0 Sounds like a good blog post for the [Community Blog](https://devblogs.microsoft.com/powershell-community/). We accept posts from the community 😄 .

**Comment by iRon7** [comment]
As _scripter_ rather than a _programmer_ (less familiar with terms as constructors etc.) and a non-native English person, [*destructing*](https://en.wikipedia.org/wiki/Destruction) sounds like you damaging something...

**Comment by mklement0** [comment]
@iRon7, it's _deSTRUCTURing_ (as in "structure"), not _destructing_, and it is the terminology used in [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment); an alternative to this somewhat stilted, used-in-technical-contexts-only term may be  _decomposing_ (a technical term used in chemistry), but due its association with decaying (rotting) matter, is probably not a good idea...

The chemistry term means "break down or cause to break down into component elements or simpler constituents", which is the gist of what such assignments do at least _technically_, which is why I was drawn to it initially.

That is, something like:

```powershell
$a, $b = 1, 2
```

_technically_ breaks the RHS _array_ `1, 2` into its elements and assigns the first to `$a`, and the second to `$b`.

In this simple case, where you're essentially combining two regular assignments _into a single statement_, users may not _conceive_ of the statement as performing this destructuring - just a way to assign two unrelated values to two variables _at once_.

This differs from the _express intent_ to break a collection into elements and subranges:

```powershell
$coll = 1..5
$a, $b, $rest = $coll # $a = 1, $b= 2, $rest = 3..5
```

What these two use cases do have in common is that _multiple_ variables are assigned to _as part of the same statement_.
(I'm aware of the irony of using the term _multiple_ here, but bear with me.)

For this reason, something like _parallel assignment_ or _simultaneous assignment_ is a better term.

As argued, the term _multiple assignment_ is vague, especially when pluralized, and is easily confused with (a) multiple assignment statements to different variables _in sequence_ or (b) repeated assignments to the _same_ variable over time.
My suggestion was to mitigate this potential for confusion with the alias _multi-assignment_, which makes it more evident that a distinct concept referring to a _single operation_ is being referenced.

**Comment by iRon7** [comment]
dyslexia 😳

**Comment by mklement0** [comment]
@sdwheeler, thanks for the pointer to the community blog.

It's good to know about in general, but with respect to the issue at hand I don't see the value of posting about it there, given that it sounds like the decision to stick with _multiple assignment_ has already been made.

Conversely, if the decision hasn't yet been made, this is the place to discuss it (and I think we've covered all angles now).

**Comment by sdwheeler** [comment]
We decided on _multiple assignment_. It was discussed internally with the product team.

**Comment by mklement0** [comment]
That is what I suspected, @sdwheeler, thanks for confirming it.
