### ISSUE TITLE
Document installation from repository for Fedora 33, 34 and RHEL 8

### ISSUE THREAD

**Issue by salehqt** [MicrosoftDocs/PowerShell-Docs#7399]
I figured it out myself and the updated commands are 

```
# Register the Microsoft signature key
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

# Register the Microsoft RedHat repository
curl https://packages.microsoft.com/config/rhel/8/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo

# Update the list of products
sudo dnf check-update

# Install a system component
sudo dnf install compat-openssl10

# Install PowerShell
sudo dnf install -y powershell

# Start PowerShell
pwsh
```

I tried it on Fedora 33 and it works. The only changes is to change **7** to **8**. The reference repo is here: https://packages.microsoft.com/config/rhel/8/

**Comment by sdwheeler** [comment]
These distributions are not currently supported. Please create a request for support of a new distribution in the PowerShell source repository. See https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ADistribution-Request for examples.
