### ISSUE TITLE
Page "Everything you wanted to know about ShouldProcess" missing info on Suspend

### ISSUE THREAD

**Issue by PavelSafronov** [MicrosoftDocs/PowerShell-Docs#7422]
# Documentation Issue

Page ("Everything you wanted to know about ShouldProcess")[https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess] has no information about the `[S] Suspend` option of the confirmation dialog.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [x] Learning PowerShell
  - [x] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Preview content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

Page ("Everything you wanted to know about ShouldProcess")[https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess] has no information about the `[S] Suspend` option of the confirmation dialog.

But, more than just this one page, there is no clear and concise explanation of the `[S] Suspend` option anywhere on the docs.microsoft.com site. This random non-Microsoft blog offers the clearest explanation of what `Suspend` actually does: https://itluke.online/2017/09/18/yesyes-to-all-no-no-to-all-suspend/

Please extend the official documentation to explain what `[S] Suspend` does, how it should be used, and pitfalls to avoid.

**Comment by chasewilson** [comment]
Hey @PavelSafronov, thanks for the feedback here. While this article might be related to the `-Confirm` option, it isn't the focus and it doesn't cover the options in depth. However, you can check out the [about_CommonParameters](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_commonparameters) article and you will find more information there. 

I hope this helps. I'll be closing this for now, but feel free to respond I'll be monitoring if we need to revisit.
