### ISSUE TITLE
Example 8 in the document sample code example is wrong and misleading

### ISSUE THREAD

**Issue by rajh24** [MicrosoftDocs/PowerShell-Docs#7442]
As per **Example 8** mentioned in a document,  Test-Path with white space or empty string will return false. 
![image](https://user-images.githubusercontent.com/29834569/113603682-da190900-9661-11eb-9ef4-3a878242afce.png)

But if you execute below statement on powershell you will get error instead of False as return value. 

`Test-Path -Path ''`

![image](https://user-images.githubusercontent.com/29834569/113603587-c077c180-9661-11eb-9309-de94f6eba8be.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9640c7af-621c-b9f7-5451-04073cfdc345
* Version Independent ID: 1ef1a1f1-1bb5-727e-edce-c4c15aa5a3d4
* Content: [Test-Path (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Test-Path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Test-Path.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment]
Hey @rajh24, thanks for the feedback here and for the PR!

However, it looks like you are reading the 7.1 version of the documentation but using PowerShell 5.1. If you view the [example in the 5.1 version](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-5.1#example-8--test-a-path-with-whitespace-as-the-value) of the documentation, it states that the empty string will throw an error. 

I'll be closing this and the PR for now., but if you feel there is more to discuss, I'll be monitoring this issue and will respond and ropen if necessary. 

Thanks again and feel free to put in more issues or PR's if you find a problem with the docs!
