### ISSUE TITLE
Error in "Example 2: Run a POST request"

### ISSUE THREAD

**Issue by xinfli** [MicrosoftDocs/PowerShell-Docs#7454]
1. Variable `$body` in the usage does not match the definition `$Body`
2. `$body` should be converted to JSON before usage, else it will raise error:
`
        {
            "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
            "title": "One or more validation errors occurred.",
            "status": 400,
            "traceId": "|95dddefe-4778e90966f83838.",
            "errors": {
                "$": [
                    "'s' is an invalid start of a value. Path: $ | LineNumber: 0  | BytePositionInLine: 0."
                ]
            }
        }
`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba16c42b-c730-73ca-3968-a1678d722212
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
@xinfli thanks for the feedback here. The example here is also an acceptable example depending on the API you are interacting with. Converting it to json might be required but a hashtable it also acceptable input.

As for the body not matching the definition, as it says in the **Body** Paramter description, when using a **POST** Method 
"the body is set as the value of the request body in the standard name=value format". 

I think this covers your issues but if there is more feel free to respond here. I'll be closing this for now but can reopen if needed. 

Thank you again and have a great rest of your day!
