### ISSUE TITLE
"No package powershell available" in the Microsoft RedHat Repository

### ISSUE THREAD

**Issue by ceztko** [MicrosoftDocs/PowerShell-Docs#7458]
If you try to install powershell following the guide as pointed in the [Centos](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation-via-package-repository-preferred---centos-7) or [RHEL](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation-via-package-repository-preferred---red-hat-enterprise-linux-rhel-7) 7 guide using the Microsoft RedHat Repository, which is recommend, you received a "No package powershell available" error, meaning that the `powershell` package is missing from the repository. A `powershell-preview` package is available, though, but it's actually outdated. A `powershell` package is regularly available in other linux repositories like the Ubuntu one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation-via-package-repository-preferred---centos-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by ceztko** [comment]
I am very sorry, what I tried wasn't exactly what it is written in the guide. I had the setup used to install .NET 5.0 SDK as described [here](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos#centos-7-). The following `Dockerfile` shows the issue:

```
FROM centos:7

RUN rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm \
    && yum -y install powershell
```

That can be tested with `docker build -t test - < Dockerfile`, produces `No package powershell available`. After noticing this problem with the above configuration, I actually attempted to follow the actual guide for powershell but I possibly mixed the results, so my bad for the wrong report. I debugged more and understood what is the problem with the above package. The problem seems to be that the it will install a **centos7** specific repository as found out inside the container:

```
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
baseurl=https://packages.microsoft.com/centos/7/prod
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
sslverify=1
```

Instead following the powershell installation guide will end installing the **rhel7** repository also for centos, as it follows:
```
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
baseurl=https://packages.microsoft.com/rhel/7/prod/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

So, centos7 repository seems to be broken for powershell, instead rhel7 one is fine, with the very confusing situation that centos7 repository still has other packages updated like .NET sdk 5.0, 3.1 and also supplies an outdated `powershell-preview` package. Is there any reason to still support a centos specific repository?

**Comment by TravisEz13** [comment]
we don't publish to the centos7 repository.

**Comment by ceztko** [comment]
Thank you for clarification. Since I will need to have all .net sdk 5.0, 3.1 and powershell packages installed my best option for now just is using the rhel7 repository which has everything. I wonder if MS could simplify its deploy and support a single repository for both variants, of course running unit tests on both system, like most third party software providers are doing. Thank you very much for your prompt reply and support.
