### ISSUE TITLE
Added tab completion for View parameter of Format-* cmdlets

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#7462]
# Summary of the new document or enhancement

- List of articles that need to be updated: Release notes
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/14513
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

Added tab completion for View parameter of Format-Custom, Format-List, Format-Table and Format-Wide cmdlets.

**Comment by sdwheeler** [comment]
There have been several new completers added during the 7.2 preview. Need to list all of the completers that have been added in the release notes. This is a big usability improvement.

**Comment by sdwheeler** [comment]
Information has been added to the 7.2 release notes (still in draft).
