### ISSUE TITLE
Any plan to address module name change?

### ISSUE THREAD

**Issue by cheong00** [MicrosoftDocs/PowerShell-Docs#7463]
# Documentation Issue
Currently the documentation is arranged according to corresponding name of PowerShell module. However if the module name for corresponding component is changed across OS versions, user will not be able to find the link to documentation using the old name, even if they changed the targeting OS version to view.

## Context of the issue

[The problem](https://docs.microsoft.com/en-us/answers/questions/353736/404-page-not-found-with-url-httpsdocsmicrosoftcome.html) is reported on Q&A forum.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): N

## Detailed description of the issue

Take the RDS component for example:
https://docs.microsoft.com/en-us/powershell/module/rdmgmt/get-rdserver
Apparently the corresponding module name for Win2012R2 was "[RemoteDesktop](https://techcommunity.microsoft.com/t5/ask-the-performance-team/step-by-step-instructions-for-installing-rds-session-deployment/ba-p/375569)", so the link was used to be the following:
https://docs.microsoft.com/en-us/powershell/module/remotedesktop/get-rdserver

We should add a "History" table on the [main module page](https://docs.microsoft.com/en-us/powershell/module/rdmgmt/) to list out older module names for search engines to be able to lookup the new page for help of older modules.

It would be great if we can add some redirects from old module name to current location (This will have benefit of updating search engines too. Currently search will display the "remotedesktop" link which will return 404 result. Have "link" tag with ["canonical" attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#attr-canonical) in redirect file will certainly help).

Or better, to have the module names on the menu reflect to the module name that should be at that time. (On "Windows Server 2012 R2 PowerShell", the module name should be displayed as "RemoteDesktop" instead of "RDMgmt")

**Comment by clhorkey** [comment]
The documentation isn't limited to just 2012.  I am running Windows 10 and also Server 2019 and get the same issues.  The question becomes do I need to update to Powershell 7.1?  When installing Server 2019 or Windows 10 you still get version 5.1.  Thank you.

**Comment by clhorkey** [comment]
@cheong00 Since I'm new to github and what goes on to get help in this area, thank you for your help.

**Comment by sdwheeler** [comment]
That content is not in this repository. The redirects should already be in place. If there are still problems they should be reported at https://github.com/MicrosoftDocs/windows-powershell-docs/issues

**Comment by cheong00** [comment]
Okay. Will create issue there.
