### ISSUE TITLE
Multiple Patterns can be specified as an array

### ISSUE THREAD

**Issue by MikeMM70** [MicrosoftDocs/PowerShell-Docs#7468]
[Enter feedback here]
I discovered that the -Pattern option can take an array (or comma separated list), matching any of the values, and would have found it useful to have in the help, maybe in an example. Just a humble suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c47ac90-710e-1fc2-76b6-a581cd3eb7d4
* Version Independent ID: 86cda1f5-a5bf-45bd-d7d4-aa1a16134c7d
* Content: [Select-String (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7.1&WT.mc_id=ps-gethelp)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Select-String.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by chasewilson** [comment]
Hey @MikeMM70, Thanks for the feedback here! 
This doesn't appear to be the behavior I'm getting in my example below. Would you mind sharing your example? 
Code:
```powershell
$ts = 'cat dog squirrel apple orange banana'
($ts | Select-String -Pattern 'cat', 'apple', 'test').Matches.Value
```

Output:
```Output
cat
```
Code:
```powershell
($ts | Select-String -Pattern 'cat', 'apple', 'test').Matches.Value
```
Ouput:
```Output

```

**Comment by MikeMM70** [comment]
I collected the output of ipconfig on some lab computers in a folder and was looking to see just the hostnames and MAC addresses for a Wake on Lan list.
`ls *.txt | % {$_.name;Select-String -Raw -Path $_ -Pattern "host","physical" -SimpleMatch}`

```
CR15S-ipconfig.txt
   Host Name . . . . . . . . . . . . : MJ02L3MK
   Physical Address. . . . . . . . . : 6C-0B-84-3E-87-C1
PC02-ipconfig.txt
   Host Name . . . . . . . . . . . . : MJ0597DL
   Physical Address. . . . . . . . . : 70-20-84-02-3D-9F
PC06-ipconfig.txt
   Host Name . . . . . . . . . . . . : MJ0597DN
   Physical Address. . . . . . . . . : 70-20-84-02-52-E8
PC09-ipconfig.txt
   Host Name . . . . . . . . . . . . : MJ0597DC
   Physical Address. . . . . . . . . : 70-20-84-02-52-CD
PC10-ipconfig.txt
   Host Name . . . . . . . . . . . . : MJ0597DJ
   Physical Address. . . . . . . . . : 70-20-84-02-29-16
PC11-ipconfig.txt
   Host Name . . . . . . . . . . . . : MJ0597DX
   Physical Address. . . . . . . . . : 70-20-84-02-3D-8F
```

It worked with and without the -simplematch parameter.

**Comment by chasewilson** [comment]
Ah I see what you are saying, The documentation is correct here.  [Example 7](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7.1&WT.mc_id=ps-gethelp#example-7--find-strings-that-do-not-match-a-pattern) shows that you can pass in an array and the parameter sections is documented as accepting a string array. `string[]`.

While it can be done this way and if you are have a gauranteed formatted output it will be ok, I would suggest using a regex pattern as if you do it with the array, it will only get the first match on any given string being evaluated even using the `-AllMatches` switch. With regex `(host|physical)` it will catch all matches in the string. 

for example:

```powershell
$ts = 'physical host'
$ts | Select-String -Pattern 'host', 'physical' -AllMatches
```
This will only match `host` as it's the array item to process the match

However with regex:

```powershell
$ts | Select-String -Pattern '(host|physical)' -AllMatches
```

it will match everything. If you remove the `AllMatches` switch, it will read the string from left to right for matches and isn't reliant on the order of the `-Pattern` array input.


I'll be closing this for now but feel free to respond if you have more feedback or feel differently. We can discuss and i can reopen if necessary.

**Comment by MikeMM70** [comment]
Sorry to reopen the ticket, but I wanted to thank you for your attention,
and apologize for missing the existing example that shows almost exactly
what I was talking about.

Michael M. Minor
