### ISSUE TITLE
-Source parameter is broken

### ISSUE THREAD

**Issue by MikeMM70** [MicrosoftDocs/PowerShell-Docs#7469]
[Enter feedback here]
-Source parameter on PowerShell 6 or above actually causes an error no matter what, and so does have an effect. I've submitted this as a bug for PowerShell, but was told I was wrong. Please at least update the documentation to reflect reality.

```
Test-Connection -Source 127.0.0.1 -ComputerName 8.8.8.8
Test-Connection: Cannot bind parameter 'Source' to the target. Exception setting "Source": "Expression must be writeable (Parameter 'left')"

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9a16637-8266-44fa-1fad-3e27d630e5f6
* Version Independent ID: 1cf2ccd2-f099-3f92-b698-36311baa0b81
* Content: [Test-Connection (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Test-Connection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Test-Connection.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by daxian-dbw** [comment]
@MikeMM70 This is a bug in `Test-Connection`. The error you see is confusing, because the `-Source` parameter was made a getter only (cannot be set), and thus the parameter binder fails. It should instead throw an error with better message, allowing the user to understand what happens.

**Comment by chasewilson** [comment]
@daxian-dbw, So it sounds providing a value to the `-Source` paramter will throw an error anyways but maybe a more informational one? 

In this case, it does have an effect and I should document the behavior as the param throwing an error instead of having no effect?
