### ISSUE TITLE
Dynamic ValidateSet Values

### ISSUE THREAD

**Issue by prboyer** [MicrosoftDocs/PowerShell-Docs#7470]
The documentation on [this page](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.1#dynamic-parameters) should be updated to make it clear that the interface
`public interface class IValidateSetValuesGenerator`
is only available on PS version 6.0+ per the documentation for the [namespace](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.ivalidatesetvaluesgenerator?view=pscore-6.0.0). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fdd3909-4005-b224-0395-364445d4d4b6
* Version Independent ID: 4eac80f8-61be-4d0f-d657-a007ba81cf53
* Content: [about_Functions_Advanced_Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.1#attributes-of-parameters)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hey @prboyer, thanks for the feedback here. I've created a new PR to add a note to all newer versions of PowerShell documentation if you want to take a look and leave feedback there as well. 

Thanks again and have a great day!
