### ISSUE TITLE
Missing UseNewRunspace parameter documentation

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#7475]
Seems a new parameter -UseNewRunspace has been added but has not been documented at all & should be documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07889270-80a5-d111-bad3-12d24ff9b753
* Version Independent ID: 7ba53b91-ed64-cc24-0cf0-a5dc3f3dc9d0
* Content: [ForEach-Object (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by chasewilson** [comment]
Hey @kilasuit, I'm sorry if there has been some confusion but the parameter appears to be documented [here](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md#-usenewrunspace). I dont' see any issues with it as of right not and I'll be closing this issue. Feel free to respond here and I'll be monitoring it. If we need to revist and reopen I have no problem doing that. 

Thanks and have a great day!

**Comment by kilasuit** [comment]
@chasewilson It may be documented in the backend here but the issue is not that it's not in documentation but that it's not showing as being documented on the docs.microsoft.com page [ForEach-Object](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.2#parameters)

**Comment by chasewilson** [comment]
Hey @kilasuit I apologize, you linked to the 7.2 documentation where it's documented. It's external as well. But it's not documented in 7.1 versioned docs for some reason. I'll reopen and create a PR.

**Comment by kilasuit** [comment]
It doesn't show for me on 7.2 documentation page - I don't know why though.

This is me searching for `-UseNewRunspace` on `https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.2`
![image](https://user-images.githubusercontent.com/6355225/114901070-581ca300-9e0c-11eb-97d3-4412eb754d07.png)

Which brings it up the only showing of it in the parameter sets in the top of the page
![image](https://user-images.githubusercontent.com/6355225/114901375-a5007980-9e0c-11eb-80f4-3c225ed418c9.png)

But I'd expect the detail of the parameter to show in the parameter help section between TimeoutSeconds & WhatIf, which as per the below, it isn't as per the below
![image](https://user-images.githubusercontent.com/6355225/114901576-d6794500-9e0c-11eb-896d-7433c1fab6c3.png)

**Comment by chasewilson** [comment]
@kilasuit  so it is actually documented in both correct places but it's not showing up for me in 7.1. Very odd because there are **3** places where `UseNewRunspace` is mentioned in that doc and only the syntax portion is showing up for you.

I'm not sure what's happening but we'll be investigating further and I'll let you know when we have a timeline for a fix.

**Comment by kilasuit** [comment]
If I search just `UseNewRunspace` this is what I get.
![image](https://user-images.githubusercontent.com/6355225/114903673-f01b8c00-9e0e-11eb-8e61-35f2baa02aa6.png)
which then shows it in this segment
![image](https://user-images.githubusercontent.com/6355225/114903731-fe69a800-9e0e-11eb-8166-c2572c146798.png)

So it's just the parameter help block that's missing, which if the content is cached anywhere (very likely) then the cache may need a flush to ensure that this gets picked up, which would be a doc's infrastructure team thing to look at
