### ISSUE TITLE
Getting 'Remove-Service' is not recognized error

### ISSUE THREAD

**Issue by paolovalladolid** [MicrosoftDocs/PowerShell-Docs#7486]
The page says to use Remove-Service to remove a Windows Service.  However when I do a Run As Administrator on Powershell, then attempt to run the command I get this error:

PS C:\users\valpao\source\repos> Remove-Service -Name AAAMonitorService
Remove-Service : The term 'Remove-Service' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Remove-Service -Name AAAMonitorService
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Remove-Service:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\users\valpao\source\repos> Remove-Service
Remove-Service : The term 'Remove-Service' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Remove-Service
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Remove-Service:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e45612-c582-93e5-5ec0-384e611a5c4a
* Version Independent ID: fb28372c-479d-c3bd-8f8a-f8c5523ac5cf
* Content: [Remove-Service (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-service?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Remove-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Remove-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
As the documentation states: "The Remove-Service cmdlet was introduced in PowerShell 6.0."

It is not available in Windows PowerShell 5.1.

**Comment by Korb** [comment]
#4510 ('Remove-Service' is not recognized as the name of a cmdlet)
