### ISSUE TITLE
Word typo 'thisby'

### ISSUE THREAD

**Issue by dholcomb-ms** [MicrosoftDocs/PowerShell-Docs#7487]
There is a typo on this page where it says 'thisby' but it should be "this by".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1410ff1-0ef0-07d0-1f3c-8754117c9d0e
* Version Independent ID: c1b0254c-cc4c-33c6-c83f-ac60ab282714
* Content: [What's New in PowerShell 7.0 - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-70?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Fixed
