### ISSUE TITLE
Out-File output is default encoded in unicode

### ISSUE THREAD

**Issue by tgill880** [MicrosoftDocs/PowerShell-Docs#7489]
System: Windows 10 20H2

Problem:
A JSON object written to a file using 
```
$my_json_string | ConvertTo-Json  | Out-File $my_json_file
```
was rejected by a C++ JSON library (nlohmann::json).

Discussion:
`Out-File` default encoding is `unicode` on my system (the documentation states default encoding is `utf8NoBOM`).

The first 2 bytes (BOM) of the created json file are `0XFF 0xFE`, ie, UTF-16, Little Endian. The JSON library only supports UTF-8.

My solution was simple: specify utf8 as the encoding format.

Please update the  documentation to specify the correct default encoding of `Out-File`. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d9da4-305f-d8a8-0aba-69482ce1d99e
* Version Independent ID: 6ca0aa0a-2b48-273f-cd95-831d08bef772
* Content: [Out-File (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Out-File.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Out-File.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The default output encoding for PowerShell 7.1 is `utf8NoBom`. You were reading the 7.1 documentation. The documentation for PowerShell 5.1 states that the default is `unicode`.
