### ISSUE TITLE
powershell linux

### ISSUE THREAD

**Issue by ChaosTheorX** [MicrosoftDocs/PowerShell-Docs#7490]
[Login in issues, github user listed is not me and I'm unsure why it linked there ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#paths)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by ChaosTheorX** [comment]
My issue is with logging in. Please see the log

**Comment by sdwheeler** [comment]
If you are having issues with GitHub you need to contact GitHub support.
