### ISSUE TITLE
Another terse example from MS 

### ISSUE THREAD

**Issue by thedavegray** [MicrosoftDocs/PowerShell-Docs#7494]
Would it really be so much trouble to put the permanent fix as well as the "current session"? 

"You can remove paths from the variable using similar methods: for example, $env:PSModulePath = $env:PSModulePath -replace "$([System.IO.Path]::PathSeparator)c:\\ModulePath" will remove the c:\ModulePath **path from the current session.**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfd2e74d-932f-8e43-dab5-82796a54077e
* Version Independent ID: 8a54a46b-715d-ab7d-f500-7dd41c29634c
* Content: [Modifying the PSModulePath Installation Path - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/modifying-the-psmodulepath-installation-path?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
We also accept pull requests if you would like to make a change to that article.
