### ISSUE TITLE
Alias is wrong:  Copy-Item alias is "copy" not "cf"

### ISSUE THREAD

**Issue by AndreMikulec** [MicrosoftDocs/PowerShell-Docs#7503]
Alias is wrong:  Copy-Item alias is "copy" not "cf"
```
Alias           copy -> Copy-Item
Alias           cp -> Copy-Item
Alias           cpi -> Copy-Item
```
The web page says the alias is "cf".  That not right.

```
PS C:\Users\AnonymousUser> cf "test.txt" "test2.txt"
cf : The term 'cf' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cf "test.txt" "test2.txt"
+ ~~
    + CategoryInfo          : ObjectNotFound: (cf:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
The alias "copy" works.
```

PS C:\Users\AnonymousUser> copy "test.txt" "test2.txt"
PS C:\Users\AnonymousUser> type test2.txt
Hello
PS C:\Users\AnonymousUser> type test.txt
Hello
PS C:\Users\AnonymousUser>
```

I am using the version of Poweshell that comes with the OS Build: 20H2.
```
PS C:\Users\AnonymousUser>  Get-Host | Select-Object Version

Version
-------
5.1.19041.906
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715b0ab7-e386-baf6-970b-d2a703501397
* Version Independent ID: 1eace7de-83aa-39a7-7a19-862e9e37b5f7
* Content: [Copy-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
That article does not list the aliases for `Copy-Item`.  It only lists the aliases for parameters. `cf` is the alias for the **Confirm** parameter.

```powershell
PS> (Get-Command Copy-Item | select -ExpandProperty Parameters).Values | select Name,Aliases

Name                Aliases
----                -------
Path                {}
LiteralPath         {PSPath, LP}
Destination         {}
Container           {}
Force               {}
Filter              {}
Include             {}
Exclude             {}
Recurse             {}
PassThru            {}
Credential          {}
Verbose             {vb}
Debug               {db}
ErrorAction         {ea}
WarningAction       {wa}
InformationAction   {infa}
ErrorVariable       {ev}
WarningVariable     {wv}
InformationVariable {iv}
OutVariable         {ov}
OutBuffer           {ob}
PipelineVariable    {pv}
WhatIf              {wi}
Confirm             {cf}
FromSession         {}
ToSession           {}
```
