### ISSUE TITLE
Pipeing into Get-ChildItem isn't clear described

### ISSUE THREAD

**Issue by AlfiCode** [MicrosoftDocs/PowerShell-Docs#7505]
[Enter feedback here]
It says:
You can pipe a string that contains a path to Get-ChildItem.
I miss an example because its's not clear how it works.
Until now it always says "Get-ChildItem: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input."

one of my tries:
(Get-ChildItem -Path $RootDir -Exclude $StrExcludeArray -Directory -Force).FullName | Get-ChildItem -Path $_ -Include "*.txt" -Recurse -Force

The first part returns some directory paths in an string array

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd63f6e7-f3f3-edbc-acf6-b52de6c0eab4
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment]
@AlfiCode Piping a string to the cmdlet works. 

Are you saying that this does not work or are you saying we need to add an example?

**Comment by AlfiCode** [comment]
Adding a good example would help a lot.
If it shows what I have to add  before the pipe when Get-ChildItem comes after.
My example didn't work when the result before was a string array (FullName of other Get-ChildItem).
Thanks, regards, Alfred

**Comment by sdwheeler** [comment]
In the simplest case it works:

```powershell
PS C:\temp> Get-ChildItem

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           3/16/2021  9:44 AM                save1
d----           4/20/2021 10:30 AM                save2
d----            4/2/2021  3:54 PM                testmod
-a---           3/18/2021 10:47 AM            146 test.ps1

PS C:\temp> (Get-ChildItem-Directory s*).Fullname | Get-ChildItem

    Directory: C:\temp\save1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           10/3/2019  3:47 PM                helpuri
d----           3/16/2021  1:57 PM                metadata-scripts
-a---          11/11/2019  4:58 PM           1968 cards.ps1
-a---           11/5/2019  5:07 PM          36669 flex.log
-a---           6/20/2019  3:30 PM         127779 new-fwlinks.xlsx
-a---           12/9/2020  7:18 PM           4258 repolist.txt
-a---           11/7/2019  4:28 PM           2121 test.help.txt
-a---           11/7/2019  4:28 PM           3284 test.md
-a---           11/5/2019  5:49 PM           1733 test.ps1

    Directory: C:\temp\save2

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           4/20/2021 10:30 AM            208 file.txt
-a---           4/20/2021 10:30 AM            331 file2.json
-a---           4/20/2021 10:30 AM            391 file2.md
-a---           4/20/2021 10:30 AM            269 file2.txt
```

It fails when you add parameters to the second `Get-ChildItem` on the pipeline. That is probably a bug. You can file an issue at https://aka.ms/psfeedback

**Comment by sdwheeler** [comment]
The **Filter** parameter works for your purpose.

```powershell
PS C:\temp> (dir -Directory s*).Fullname | dir -filter *.txt

    Directory: C:\temp\save1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           12/9/2020  7:18 PM           4258 repolist.txt
-a---           11/7/2019  4:28 PM           2121 test.help.txt

    Directory: C:\temp\save2

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           4/20/2021 10:30 AM            208 file.txt
-a---           4/20/2021 10:30 AM            269 file2.txt
```

**Comment by AlfiCode** [comment]
Great
And this example would help a lot at the description because for Get-ChildItem I couldn't find any pipe example.
Thanks, Alfred
