### ISSUE TITLE
Fine, but how to use a hashtable as one of more parameters in functions?

### ISSUE THREAD

**Issue by klawe** [MicrosoftDocs/PowerShell-Docs#7509]
Fine, but how to give over a hashtable as one of more parameters in functions?
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c51a14cf-e9db-6463-141c-2e6498e4e527
* Version Independent ID: a23755f9-7ded-991a-9675-57d3beb268ec
* Content: [Alles, was Sie schon immer über Hashtabellen wissen wollten - PowerShell](https://docs.microsoft.com/de-de/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md](https://github.com/MicrosoftDocs/PowerShell-Docs.de-de/blob/live/reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
This is covered in the article. See the section on splatting - https://docs.microsoft.com/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.1#splatting-hashtables-at-cmdlets
