### ISSUE TITLE
Powershell get for computers without it

### ISSUE THREAD

**Issue by jishua9** [MicrosoftDocs/PowerShell-Docs#7513]
the script provided to install powershellget for pcs without powershellget, actually requires powershellget to run

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9a0857-c533-6f44-6b85-455a6087ea04
* Version Independent ID: 7842b7ca-9019-cded-151d-dc9963518fd1
* Content: [Installing PowerShellGet - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/gallery/installing-psget.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/installing-psget.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by chasewilson** [comment]
Hey @jishua9, it does say that a computer with PowerShellGet installed is required to first use `Save-Module` (from PowerShellGet) to save it to the computer with PowerShellGet installed and then transfer that over to the computer without PowerShellGet.

If you want to do it entirely on a computer without it installed, you can do a manual download from the PowerShell Gallery but I believe the intent is to be able to get it to an enterprise environment. 

I'll be closing this issue for now  but will keep an eye out for your response if you feel there should be changes and can reopen as necessary
