### ISSUE TITLE
Unary Operators Documentation Missing

### ISSUE THREAD

**Issue by tykavanaugh** [MicrosoftDocs/PowerShell-Docs#7514]
## Context of the issue

- URL to the article (Docs or GitHub URL):
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/57fe83a11bff72c542e9942a332ce7b273b2a0a4/reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No

The documentation mentions unary operators such as "++" and references that other such operators exist but then provides no further explanation on where I can find that information.

**Comment by chasewilson** [comment]
@tykavanaugh, this is a good question and seems out of place since the other operators have full lists of thier own operators. As far as I'm aware, the only other one is to decrement (`--`)

I'll create a PR to get that in there but @sdwheeler, am I missing anything here with the unary operators?
