### ISSUE TITLE
not sure on the instructions.

### ISSUE THREAD

**Issue by deomaximo** [MicrosoftDocs/PowerShell-Docs#7518]
The instructions can use more clarification.  I downloaded osdsus.21.4.13.1.nupkg because it wouldn't run install-module osdsus.   I renamed the file with a .zip extension and unpacked it. Now what? run it from here? Isn't there a way to import this as a module? The steps is not clear and that's my feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63f6198-dbee-b117-aae5-36f3c8d62b8c
* Version Independent ID: 513a5710-4edc-9fbf-404d-ea9e8be384ac
* Content: [Manual Package Download - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download?view=powershell-7#installing-powershell-scripts-from-a-nuget-package)
* Content Source: [reference/docs-conceptual/gallery/how-to/working-with-packages/manual-download.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/working-with-packages/manual-download.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by sdwheeler** [comment]
See https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download#installing-powershell-modules-from-a-nuget-package

Yes, you can import the module from the location where you unpacked the files. If that location is not in your `$env:PSModulePath` then you import it using the full path to the `.PSD1` file.
