### ISSUE TITLE
Request for update

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/PowerShell-Docs#7532]
This page has not been updated in over 1 year. I find it difficult to believe that nothing has changed in the time period. Please update as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3782d9-a8e3-ffe1-852c-cd9fc6ca8b9a
* Version Independent ID: 94bd5dcb-ffbb-57b9-9b5e-a66ff4a5dd4e
* Content: [PowerShell 7 module compatibility - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/module-compatibility?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/whats-new/module-compatibility.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/module-compatibility.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
We will update this when we have new information.
