### ISSUE TITLE
Add more documentation about `temp:` drive introduced in 7.0

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#7533]
# Summary of the new document or enhancement

It's briefly mentioned in What's New https://docs.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.1#pstempdrive but should probably be part of some existing about topic, but don't see one about PSDrives in general.

**Comment by sdwheeler** [comment]
PSDrives and the TEMP: drive is covered in https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_filesystem_provider?view=powershell-7.1#detailed-description.

But I can punch it up a bit more.
