### ISSUE TITLE
Terminal wonder

### ISSUE THREAD

**Issue by manuelduarte077** [MicrosoftDocs/PowerShell-Docs#7543]
- I like it a lot, it was about time that they made us happy with something like that so wonderful
 - How can I tune it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6283a7ca-43a5-30ea-7d3f-148e1f8f249b
* Version Independent ID: fd3015e3-f15c-f8dc-1c17-8d5e277dac12
* Content: [Installing PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Exactly what are you trying to tune? Can you be more specific?

**Comment by sdwheeler** [comment]
If you are asking about the Windows Terminal, please refer to the Terminal documentation https://docs.microsoft.com/windows/terminal/.

**Comment by manuelduarte077** [comment]
Thank you very much, if it was to change the appearance of the terminal, install plugins things like that if you can, thanks for the link, I will review it 💯
