### ISSUE TITLE
Wrong Depth MaxValue

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/PowerShell-Docs#7552]
The parameter for Depth is defined as a value between 1 and [Int]::MaxValue. But Powershell throws an error for values greater 100.
Also the default depth of 2 seems a much too low choice. If I read in a Json-File, edit it and export it back, I would expect this to just work. But because of the default depth of 2, the output is most often not compatible/correct.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f961e27-450c-f283-9d92-e376a35c9052
* Version Independent ID: 2d459bd3-89d3-098a-c5e6-d4c4073dd035
* Content: [ConvertTo-Json (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-7.1&viewFallbackFrom=powershell-6)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment]
The documentation is correct as written. You can see in the source code what the accepted range is: https://github.com/PowerShell/PowerShell/blob/a95b2cb17fecc8640533420b3baa9aec0f3749cb/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs#L38

However, you are correct that the code limits this to 100 internally. So this is a bug that needs to be reported at https://aka.ms/psfeedback. 

As for the default of 2, you can file a feature request to change it at https://aka.ms/psfeedback. However, I believe that there were specific reasons for choosing that default. 

I can add a note about the limit of 100 to the docs.

**Comment by sdwheeler** [comment]
Created https://github.com/PowerShell/PowerShell/issues/15344 for the parameter validation bug.
