### ISSUE TITLE
Small typo in example.

### ISSUE THREAD

**Issue by clamb123** [MicrosoftDocs/PowerShell-Docs#7562]
https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7.1#cannot-index-into-a-null-array

PS> $empty = $null
**SP**> $empty[0]
Error: Cannot index into a null array.

Small typo in the above example.

**Comment by chasewilson** [comment]
Thanks for pointing this out! I went ahead and fixed it. Have a great weekend
