### ISSUE TITLE
How do you install package management without having it?

### ISSUE THREAD

**Issue by cdichter** [MicrosoftDocs/PowerShell-Docs#7576]
You're describing a package management, which is not installed by default, without saying how to install it.

I did eventually find a way to do it:
powershell.exe -NoLogo -NoProfile -Command '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Install-Module -Name PackageManagement -Force -MinimumVersion 1.4.6 -Scope CurrentUser -AllowClobber -Repository PSGallery'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564fb01c-3d10-eaa4-1157-c7308a613b6e
* Version Independent ID: d2a0d7e5-69ff-a3ea-9f37-ff1687a47b56
* Content: [PackageManagement Module - PowerShell](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/?view=powershell-7.1)
* Content Source: [reference/7.1/PackageManagement/PackageManagement.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PackageManagement/PackageManagement.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by chasewilson** [comment]
Hey @cdichter , thanks for the feedback here. 

As of PowerShell 5.0, PackagageManagement comes preinstalled with PowerShell. In your command above, you use `Install-Module` which means PowerShellGet is installed and PackageManagement is a dependency of PowerShellGet. 

This is also reference material and installation isn't covered in this type of documentation. If you want the latest version of PowerShellGet and PackageManagement, you can refer to [this article](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.1) here. 

I'll be closing this for now, feel free to respond if you have anymore feedback and I'll be monitoring. 

Thanks again and have a great rest of your week!
