### ISSUE TITLE
Useless instructions--- doesn't describe essential steps.

### ISSUE THREAD

**Issue by cdichter** [MicrosoftDocs/PowerShell-Docs#7577]
The steps are as follows:

1. Unblock the Internet-downloaded NuGet package (.nupkg) file, for example using Unblock-File -Path C:\Downloads\package.nupkg cmdlet.
2. Extract the contents of the NuGet package.
3. The .PS1 file in the folder can be used directly from this location.
4. You may delete the NuGet-specific elements in the folder.

** Step 2. Extract the contents of the NuGet package. ** doesn't say how to do that. The file extension doesn't imply how to do that, so Windows and its users don't know how to do that.

** Step 3. The .PS1 file in the folder can be used directly from this location. ** is wrong. There are no .ps1 files in that directory!

I renamed the file with .zip, and extracted it. 

The next 
** Extract the contents of the NuGet package. **

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63f6198-dbee-b117-aae5-36f3c8d62b8c
* Version Independent ID: 513a5710-4edc-9fbf-404d-ea9e8be384ac
* Content: [Manual Package Download - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download?view=powershell-7)
* Content Source: [reference/docs-conceptual/gallery/how-to/working-with-packages/manual-download.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/working-with-packages/manual-download.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by cdichter** [comment]
One essential step is:

Extract the contents of the NuGet package.

It doesn't say how to do that.
The file extension doesn't imply how to do that, so Windows and its users don't know how to do that.

**Comment by sdwheeler** [comment]
@cdichter I think if you read the article more closely you will find all of the information you need. At the top of the article we explain that the nupkg file is a ZIP file and even suggest renaming it to have the ZIP extension. You can use any ZIP extraction tool you want to extract the files, including the `Expand-Archive` cmdlet.

The PowerShell Gallery allows you to publish 2 kinds of packages: module packages and script packages. The instructions you quote above are talking about unpacking a script package, which contains PS1 file(s) in the root of the package.

For example, download the script package https://www.powershellgallery.com/packages/Get-WindowsAutoPilotInfo/3.5. You can  extract and inspect the contents to find the PS1 file.

```powershell
PS C:\Users\user1\Downloads> Expand-Archive .\get-windowsautopilotinfo.3.5.0.nupkg
PS C:\Users\user1\Downloads> dir .\get-windowsautopilotinfo.3.5.0\

    Directory: C:\Users\user1\Downloads\get-windowsautopilotinfo.3.5.0

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           5/13/2021  4:14 PM                _rels
d----           5/13/2021  4:14 PM                package
-a---           9/21/2020 10:45 AM            465 [Content_Types].xml
-a---           9/21/2020 10:45 AM           2160 Get-WindowsAutoPilotInfo.nuspec
-a---           9/21/2020  5:42 PM          16680 Get-WindowsAutoPilotInfo.ps1
```

**Comment by cdichter** [comment]
Do you really want people to have to read the entire article and memorize what they've learned to do a simple installation?

The top portion of the article is the wrong place to put knowledge needed for manual download. In the section on manual download section it doesn't mention any of that.

**Comment by sdwheeler** [comment]
There are 2 manual download sections. One for module packages and one for script packages.

**Comment by ld0614** [comment]
Hi @sdwheeler 

I appreciate that there are instructions for exactly how to extract a .nupkg file however I must admit that I completely missed it after several scans of the document despite looking for it.  I think that once found the content is good but might benefit from possibly a dedicated section or simply a note or warning box to highlight and draw the eye of users?
