### ISSUE TITLE
Bug or incorrect documentation with OutFile/PassThru parameters for Invoke-RestMethod

### ISSUE THREAD

**Issue by smarkwell** [MicrosoftDocs/PowerShell-Docs#7584]
When PassThru and OutFile is used in combination, only PassThru is obeyed for Invoke-RestMethod.  This doesn't match what the documentation claims.

> To send the results to a file and to the pipeline, use the Passthru parameter.

I am not sure if this is considered a bug or incorrect documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba16c42b-c730-73ca-3968-a1678d722212
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.1#parameters)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by smarkwell** [comment]
```
=====> PowerShell Integrated Console v2021.2.2 <=====

PS C:\Users\BLANK\code\scratch> (Get-Host).Version


Major  Minor  Build  Revision
-----  -----  -----  --------
2021   2      2      -1

PS C:\Users\BLANK\code\scratch> $PSVersionTable.PSVersion


Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      1      3

PS C:\Users\BLANK\code\scratch>
```

**Comment by sdwheeler** [comment]
@smarkwell Thanks for the report. You have found a bug. 
Please file an issue at https://aka.ms/psfeedback

**Comment by sdwheeler** [comment]
See related code bug: https://github.com/PowerShell/PowerShell/issues/15409

**Comment by smarkwell** [comment]
Since this is considered a bug of Powershell, and not a documentation issue, I'm going to close this issue.

**Comment by sdwheeler** [comment]
Reopening as we haven't decided about a documentation change yet.
