### ISSUE TITLE
missing reference library names

### ISSUE THREAD

**Issue by ct9** [MicrosoftDocs/PowerShell-Docs#7591]
[Enter feedback here]
This article is missing the include or reference library names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 965d0aca-e4bc-281e-f00c-059982c19933
* Version Independent ID: 3b5359cd-3897-c758-2f3e-7ed5d95e7573
* Content: [Cmdlet Attribute Declaration - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-attribute-declaration?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/cmdlet-attribute-declaration.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/cmdlet-attribute-declaration.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
@ct9 This article is explaining the syntax of the `Cmdlet` attribute. It is not meant to show a complete working example of how to write a cmdlet. For that information, see https://docs.microsoft.com/powershell/scripting/developer/cmdlet/how-to-write-a-simple-cmdlet.
