### ISSUE TITLE
Installation method should not matter

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/PowerShell-Docs#7593]
I have tested both ways of installing Google Chrome and then uninstalling it. 
It is annoying that installation method makes get-package() behave differently.

When I want to uninstall Chrome, I want to be able to access the UninstallString attribute regardless of how it was installed.
As of now that would be (get-package *chrome*).Meta.Attributes["UninstallString"];

Ideally I would want to use (get-package *chrome*).SilentUninstallString;

The interesting bit is that I can only get the UninstallString attribute for programs that are **not** installed as an MSI.

As it is I will have to detect how the program was installed in order to decide how to uninstall it. It should not really be necessary as long as the registry entry provides the necessary information about how to uninstall it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3755d90-721e-e9f7-41b3-2063234d0f28
* Version Independent ID: 51100c02-3f5f-98a9-6ba2-62049da4671e
* Content: [Get-Package (PackageManagement) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/get-package?view=powershell-7.1)
* Content Source: [reference/7.1/PackageManagement/Get-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PackageManagement/Get-Package.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@Tarjei-stavanger The PackageManagement module architecture was designed around an extensible provider model. The different providers are designed to support different installer methods. But you must have some knowledge of how the application was installed. 

This is for documentation feedback, not product feedback. Product feedback goes to https://github.com/PowerShell/PowerShellGetv2/issues. However, PowerShellGet and PackageManagement modules are no longer being developed. 

PowerShellGet v3 is a complete rewrite that will replace both of these older modules. It is currently in beta. You can read more about at on the PowerShell blog: https://devblogs.microsoft.com/powershell/powershellget-3-0-preview-10-release/.
