### ISSUE TITLE
Installing package provider NuGet ask me if I want to install NuGet

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/PowerShell-Docs#7596]
$quiet = install-packageprovider NuGet -Force;

I want to install NuGet quietly to avoid disturbing the user with weird prompts.
This is sabotaged by Powershell asking me if it should install NuGet.

What on earth possesses you prompt me for permission to install NuGet when I'm explicitly trying to install NuGet??????? I've even used -Force.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c56116-989f-5ea1-fc4f-b2a8ead129f6
* Version Independent ID: 3b920543-f348-a9a4-93b2-5b3dd01532e8
* Content: [Install-Package (PackageManagement) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-package?view=powershell-7.1)
* Content Source: [reference/7.1/PackageManagement/Install-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PackageManagement/Install-Package.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
This is for documentation feedback, not product feedback. Product feedback goes to https://github.com/PowerShell/PowerShellGetv2/issues. However, PowerShellGet and PackageManagement modules are no longer being developed.
