### ISSUE TITLE
Remap Ctrl+R to ReverseSearchHistory in EditMode vi

### ISSUE THREAD

**Issue by davetapley** [MicrosoftDocs/PowerShell-Docs#7600]
# Summary of the new document or enhancement

- List of articles that need to be updated: https://github.com/MicrosoftDocs/PowerShell-Docs/blob/57fe83a11bff72c542e9942a332ce7b273b2a0a4/reference/7.2/PSReadLine/About/about_PSReadLine.md
- New articles that need to be created: None
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PSReadLine/pull/2469
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PSReadLine/issues/2453

## Description of what changed

I am proposing to change the behavior of 

<kbd>ctrl</kbd>+<kbd>r</kbd>, <kbd>ctrl</kbd>+<kbd>s</kbd>, and <kbd>ctrl</kbd>+<kbd>g</kbd> in `EditMode vi`.

See https://github.com/PowerShell/PSReadLine/issues/2453

**Comment by sdwheeler** [comment]
Linked PR is over 100 days old. We can reopen this issue if the PR ever gets merged.
