### ISSUE TITLE
Test-Path $pshome\PowerShell.exe -NewerThan "July 13, 2009"  True

### ISSUE THREAD

**Issue by trollyanov** [MicrosoftDocs/PowerShell-Docs#7603]
For v7.1 Test-Path $pshome\Pwsh.exe -NewerThan "July 13, 2009"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46652fe-bdba-5622-676e-5147c58901d9
* Version Independent ID: 1ef1a1f1-1bb5-727e-edce-c4c15aa5a3d4
* Content: [Test-Path (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Management/Test-Path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Management/Test-Path.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by trollyanov** [comment]
and?

**Comment by sdwheeler** [comment]
Fixed. Will be live later today.
