### ISSUE TITLE
No details to indicate how to install the Microsoft.PowerShell.Utility module.

### ISSUE THREAD

**Issue by chuckb1300** [MicrosoftDocs/PowerShell-Docs#7605]
There does not appear to be any details to indicate how to install the Microsoft.PowerShell.Utility module.  Is this module still available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69826738-ef4e-b2e8-f92a-4552b6c36780
* Version Independent ID: c883591b-afaa-adbf-f8d3-98ed57e7621c
* Content: [Microsoft.PowerShell.Utility Module - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The modules listed here are included in PowerShell. They don't need to be installed. They may need to be imported, but they should auto-import the first time you use a cmdlet from the module.

**Comment by chuckb1300** [comment]
Interesting.  The show-markdown one missing.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sdwheeler** [comment]
You are reading the help for PowerShell 7.1. `Show-Markdown` was added in PowerShell 6.1, so it is not available in PowerShell 5.1.

See https://docs.microsoft.com/powershell/scripting/whats-new/cmdlet-versions.

**Comment by chuckb1300** [comment]
Ahh, thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
