### ISSUE TITLE
Remove Windows 10 from list of supported Windows Operating Systems

### ISSUE THREAD

**Issue by JeffSchwandt** [MicrosoftDocs/PowerShell-Docs#7622]
Windows 10 is included in the list of supported windows operating systems, however none of the downloads for Windows Management Framework 5.1 are compatible with Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6899bee9-ef7a-7447-0807-62ab30ae9606
* Version Independent ID: 6160bf0d-b5bb-003d-df4c-a42e590d3866
* Content: [Get started with Desired State Configuration (DSC) for Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/getting-started/wingettingstarted?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/dsc/getting-started/winGettingStarted.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/getting-started/winGettingStarted.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @mgreenegit
* Microsoft Alias: **migreene**

**Comment by sdwheeler** [comment]
WMF 5.1 comes preinstalled in Windows 10. That is why none of the WMF 5.1 download packages work. They are not intended for Windows 10.
