### ISSUE TITLE
Example 6: Use wildcards to create files in multiple directories

### ISSUE THREAD

**Issue by trollyanov** [MicrosoftDocs/PowerShell-Docs#7630]
[Enter feedback here]

Example 6: Use wildcards to create files in multiple directories
Get-ChildItem -Path C:\Temp\
Show me files in  Temp directory

Next, It doesn't work because I am in Powershell PS C:\Myusename>
New-Item -Path * -Name temp.txt -ItemType File | Select-Object FullName

Correct this command
**New-Item -Path C:\Temp\ * -Name temp.txt -ItemType File | Select-Object FullName**

Or indicate that I should be in PS C:\Temp\>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17b533e9-f53e-08ac-018e-a74ffb74d16a
* Version Independent ID: 609a9efd-598e-050b-c9b8-91402dcc8e87
* Content: [New-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Management/New-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Management/New-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by trollyanov** [comment]
yes or not?

**Comment by sdwheeler** [comment]
@trollyanov The example has been fixed. See the updated article.

**Comment by trollyanov** [comment]
thnx)
