### ISSUE TITLE
Get-Item -Path C:\PathWhichIsAHardLink | Format-Table -View childrenWithHardlink

### ISSUE THREAD

**Issue by trollyanov** [MicrosoftDocs/PowerShell-Docs#7633]
[Enter feedback here]
Example 8: Getting hardlink information
Get-Item -Path C:\PathWhichIsAHardLink | Format-Table -View childrenWithHardlink

Dont work -View childrenWithHardlink

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81374020-4957-76f8-fe3c-d0ed5c7d037a
* Version Independent ID: 166d361c-0734-7589-2a8f-d60446ce0d9b
* Content: [Get-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-item?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Management/Get-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Management/Get-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
It does work, but it doesn't show much. This only difference between the views is that the value of `Mode` shows the link attribute.

```
PS> Get-Item C:\Windows\System32\ntoskrnl.exe | Format-Table

    Directory: C:\Windows\System32

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/11/2021  5:07 PM       10848576 ntoskrnl.exe

PS> Get-Item C:\Windows\System32\ntoskrnl.exe | Format-Table -view childrenWithHardLink

    Directory: C:\Windows\System32

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---           5/11/2021  5:07 PM       10848576 ntoskrnl.exe
```

You can get the same information without a view.

```
PS> Get-Item C:\Windows\System32\ntoskrnl.exe | Format-List Name, Mode, ModeWithoutHardlink, LinkType

Name                : ntoskrnl.exe
Mode                : la---
ModeWithoutHardLink : -a---
LinkType            : HardLink
```

**Comment by trollyanov** [comment]
ok, thnx
