### ISSUE TITLE
Get-PSProvider | Where {$_.pssnapin -eq "Microsoft.PowerShell.Security"} not worked

### ISSUE THREAD

**Issue by trollyanov** [MicrosoftDocs/PowerShell-Docs#7646]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-psprovider?view=powershell-7.2
Example 3: Find snap-ins or module that added providers to your session

Not worked command
Get-PSProvider | Where {$_.pssnapin -eq "Microsoft.PowerShell.Security"}

**Comment by chasewilson** [comment]
@trollyanov, thanks for the feedback here. 

That's not the example that was in example 3 and you may not have that imported in your session. This is just example output and yours may be different based on what you have imported into your session. 

I'll be closing this for now but will monitor for your response if you feel there is something more to discuss

**Comment by sdwheeler** [comment]
Actually there are a couple things wrong with this example. One may be a bug.

**Comment by sdwheeler** [comment]
Microsoft.PowerShell.Security is a module, not a snap-in to that comparison will never work.

I have corrected the doc. Either of the following will work:

```powershell
Get-PSProvider | Where {$_.ModuleName -eq "Microsoft.PowerShell.Security"}
Get-PSProvider | Where {$_.Module.Name -eq "Microsoft.PowerShell.Security"}
```

The **PSProvider** object contains both **Module** and **ModuleName** properties. 

- **Module** is a **ModuleInfo** object so you need to compare to the **Name** property
- **ModuleName** is a string

**Comment by trollyanov** [comment]
Thank you)

**Comment by trollyanov** [comment]
But i have only this:

Name        Module PSSnapIn                 
----        ------ --------                 
Registry           Microsoft.PowerShell.Core
Alias              Microsoft.PowerShell.Core
Environment        Microsoft.PowerShell.Core
FileSystem         Microsoft.PowerShell.Core
Function           Microsoft.PowerShell.Core
Variable           Microsoft.PowerShell.Core

I dont have Microsoft.PowerShell.Security

**Comment by sdwheeler** [comment]
The example gets both snap-ins and modules.

```
Get-PSProvider | Format-Table Name, Module, PSSnapIn -AutoSize
```
