### ISSUE TITLE
Section on Empty null should mention coersions to $null

### ISSUE THREAD

**Issue by aaronla-ms** [MicrosoftDocs/PowerShell-Docs#7652]
I'm glad to see AutomationNull is well documented these days, in https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-null?view=powershell-7.1#empty-null . However, this article should also mention that AutomationNull gets coerced to $null when passed as a parameter, which is incredibly surprising. As a consequence, it effectively makes it impossible to safely refactor code dealing with non-collections, since factoring a chunk of code into a separate function will _always_ change the behavior of that code when dealing with non-collections.

Example:

> PS C:scratch> function Get-Nothing {}
> PS C:scratch> $nothing = Get-Nothing
> 
> PS C:scratch> $containempty = @(@())
> PS C:scratch> $containempty.count
> 0
> PS C:scratch> $containnothing = @($nothing)
> PS C:scratch> $containnothing.count
> 0
> PS C:scratch> $containnull = @($null)
> PS C:scratch> $containnull.count
> 1
> PS C:scratch> function ident($x){ return ,$x }
> PS C:scratch> $containidentnothing = @(ident $nothing)
> PS C:scratch> $containidentnothing.count
> 1

Note that `$containsidentnothing` does not behave like `$containsnothing` as one would expect, but instead behaves as `$containsnull`. This is because when AutomationNull is passed to ident, the value is coerced to `$Null` first, so `$x` = `$null`, not AutomationNull.

Remarks: for Powershell novices, the comma between `return` and `$x` is intentional. This is to suppress powershell's behavior to flatten collections into the output stream. Or, more accurately, it ensures the flattening _always_ runs, so the output stream will contain a single element, the value of $x.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3bb81f2-58bd-9729-01cb-ef5b80098015
* Version Independent ID: 53e31d8c-92e1-d484-f9d4-b79ded54c1d1
* Content: [Everything you wanted to know about $null - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-null?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-null.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-null.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
Hey @aaronla-ms, This is a great find and I'll go ahead and submit a PR that will be linked here to help clear that up. Feel free to put any more feedback you have in the upcoming PR .
