### ISSUE TITLE
Quickstart - Create a website with Desired State Configuration (DSC)

### ISSUE THREAD

**Issue by doubleddav** [MicrosoftDocs/PowerShell-Docs#7666]
[Enter feedback here]
I had to modify this code block to get this to work on server 2019, not sure if other Windows versions are affected (see below)

```
Configuration WebsiteTest {

    # Import the module that contains the resources we're using.
    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

    # The Node statement specifies which targets this configuration will be applied to.
    Node 'localhost' {

        # The first resource block ensures that the Web-Server (IIS) feature is enabled.
        WindowsFeature WebServer {
            Ensure = "Present"
            Name   = "Web-Server"
        }

        # The second resource block ensures that the website content copied to the website root folder.
        File WebsiteContent {
            Ensure = 'Present'
            SourcePath = 'c:\test\index.htm'
            DestinationPath = 'c:\inetpub\wwwroot'
        }
    }
}
WebsiteTest
```
**Changes:**

Add this line to the end
`WebsiteTest`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a7f7703-f646-0c64-15bb-f1fda1d4c15c
* Version Independent ID: 716f862b-7356-a9b8-156e-bc4916aac2c6
* Content: [Quickstart - Create a website with DSC - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/quickstarts/website-quickstart?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/dsc/quickstarts/website-quickstart.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/quickstarts/website-quickstart.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @mgreenegit
* Microsoft Alias: **migreene**

**Comment by mgreenegit** [comment]
It’s definitely required. Without a deeper discussion, I’m not sure why you would have seen the error on 2019.

**Comment by mgreenegit** [comment]
Also this example does not need to call the configuration at the end. In the instructions that follow, the script is dot-sourced and then the configuration is called.
