### ISSUE TITLE
Document PSDesiredStateConfiguration v3 differences 

### ISSUE THREAD

**Issue by anmenaga** [MicrosoftDocs/PowerShell-Docs#7689]
Need some sort of document that will describe:
1) historical aspect that PSDesiredStateConfiguration module v2 was shipped with PS releases until PS 7.2-Preview.7 (?)
    and for future PS releases should be installed from PS Gallery.
2) summarize differences between v2 and v3 and provide example installation commands for both.

**Comment by iSazonov** [comment]
It would be great to have short descriptions how work with DSC in 6.0 vs 7.1 vs 7.2 vs WinPS in `about_DSC` file.

**Comment by anmenaga** [comment]
This looks like a suitable location for this information:
https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/about/about_classes_and_dsc?view=powershell-7.1

**Comment by sdwheeler** [comment]
See related #7726

**Comment by sdwheeler** [comment]
Moved this issue to https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/issues/31
