### ISSUE TITLE
Somewhat minor Documentation Issue regarding "Everything you wanted to know about the if statement"

### ISSUE THREAD

**Issue by UberKluger** [MicrosoftDocs/PowerShell-Docs#7690]
# Documentation Issue

The section describing the interaction between `if` and the pipeline is potentially misleading, if not actually erroneous.
## Context of the issue

- URL to the article (Docs or GitHub URL):
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-if.md
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [X] Learning PowerShell
  - [X] PowerShell 101
  - [X] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

## Detailed description of the issue

In the **Pipeline** section, the statement

> Each script block is placing the results (of) the commands or the value into the pipeline.

could lead the reader to assume that an `if` statement can form (the first) part of a multi-command pipeline when this is not permitted.

     PS C:\windows\system32\windowspowershell\v1.0> if ($x){$x}else{$default}|foreach{"The value to be used is $_"}
     At line:1 char:26
     + if ($x){$x}else{$default}|foreach{"The value to be used is $_"}
     +                          ~
     An empty pipe element is not allowed.
         + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
         + FullyQualifiedErrorId : EmptyPipeElement

This occurs because (syntactically) the `if` is not part of the pipeline and so there is no initial command for it. Demonstration:

     PS C:\windows\system32\windowspowershell\v1.0> $x='This is a string in $x';$default='Default value'
     PS C:\windows\system32\windowspowershell\v1.0> if ($x){$x}else{$default} '5'|foreach{"The value to be used is $_"}
     This is a string in $x
     The value to be used is 5

Even in this case, the two results are not put into "**the**" pipeline. They are in fact completely separate commands:

     PS C:\windows\system32\windowspowershell\v1.0> $y=if ($x){$x}else{$default}'5'|foreach{"The value to be used is $_"}
     The value to be used is 5
     PS C:\windows\system32\windowspowershell\v1.0> $y
     This is a string in $x

I am not sure what the *exact* designation should be. A bare `if` statement behaves more like an expression but cannot be used directly as part of a larger expression:

     PS C:\windows\system32\windowspowershell\v1.0> if ($x){$x}else{$default}+" and a suffix"
     This is a string in $x
     Cannot convert value "and a suffix" to type "System.Int32". Error: "Input string was not in a correct format."
     At line:1 char:26
     + if ($x){$x}else{$default}+" and a suffix"
     +                          ~~~~~~~~~~~~~~~~
         + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
         + FullyQualifiedErrorId : InvalidCastFromStringToInteger
 
Here: `if` is a single command followed by an expression where the `+` is a unary operator (expecting a numeric operand).
Similarly:

     PS C:\windows\system32\windowspowershell\v1.0> ( if ($x){$x}else{$default} )
     if : The term 'if' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
     spelling of the name, or if a path was included, verify that the path is correct and try again.
     At line:1 char:2
     + (if ($x){$x}else{$default})
     +  ~~
         + CategoryInfo          : ObjectNotFound: (if:String) [], CommandNotFoundException
         + FullyQualifiedErrorId : CommandNotFoundException

I note that this article was transcribed from a personal blog entry where such simplifications might be considered valid in the context of describing the apparent effect of a particular command. I raise this issue because these descriptions have now achieved the status of "official documentation" and should probably be more precise or at least indicate where a particular behaviour deviates from the "generalised" description.

Of course, it is possible that this "issue" is invalid because the official definition of "the pipeline" includes the usages described in the document in question and my concept of what constitutes "the pipeline" is therefore incomplete.

**Comment by chasewilson** [comment]
@UberKluger Thanks for the feedback here. I think I agree with your point here. 
According to our own [about_Pipelines](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipelines?view=powershell-7.1#long-description) doc, PowerShell pipelines is specifically talking about passing out put down using the pipe `|`. 

I think we'll have to review this and rework this section. I'll keep you posted and when a review is submitted, you're more than welcome to provide feedback on that as well.
