### ISSUE TITLE
Misspelling in BiosSerialNumber

### ISSUE THREAD

**Issue by ydewk** [MicrosoftDocs/PowerShell-Docs#7693]
Hi there,

Seems to be a miss spelling in the following commandlet: get-computerinfo | select BiosSeralNumber

Guess it should be BiosSerialNumber, the one above is missing the " i ".

Windows 10 Enterprise Version: 21h1 (19043.1052)
Powershell: 
Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f34f49-90bf-d6c4-0acb-ff440fc30570
* Version Independent ID: b87a5d97-3540-e0ee-54e6-4353f18a4bb1
* Content: [Get-ComputerInfo (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-computerinfo?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-ComputerInfo.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-ComputerInfo.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The documentation does not reference the BIOSSerialNumber. You are correct that, in PowerShell 5.1, that property name is misspelled. This is a bug PowerShell 5.1. The bug has been fixed in newer versions of PowerShell.
