### ISSUE TITLE
Doesn't work on Azure AD users

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/PowerShell-Docs#7704]
[Enter feedback here]

This doesn't work on groups that contain Azure AD groups. 
```
Get-LocalGroupMember -Group "Administrators"
Get-LocalGroupMember : Failed to compare two elements in the array.
At line:1 char:1
+ Get-LocalGroupMember -Group "Administrators"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException
    + FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e680dd34-b877-94eb-7a69-c9279f3fc739
* Version Independent ID: 91e03223-25be-f177-b279-9199cc265137
* Content: [Get-LocalGroupMember (Microsoft.PowerShell.LocalAccounts) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/get-localgroupmember?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
I believe that it should work.  Please file an issue at https://aka.ms/psfeedback
