### ISSUE TITLE
get-error isn't recognised

### ISSUE THREAD

**Issue by shupershuff** [MicrosoftDocs/PowerShell-Docs#7705]
I think this may have been deprecated? get-error doesn't seem to be recognised as a cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340a3747-41d1-8a4d-6258-1ee763849077
* Version Independent ID: 5455e383-9cf8-d80a-4fd0-df5b0ff1d026
* Content: [Get-Error (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-error?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Get-Error.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Get-Error.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
`Get-Error` was introduced in PowerShell 7.0, so it is not available in PowerShell 5.1. You were reading the documentation for 7.1.

See https://docs.microsoft.com/powershell/scripting/how-to-use-docs to see how to switch your view to PowerShell 5.1.

See https://docs.microsoft.com/powershell/scripting/whats-new/cmdlet-versions to see which versions support which cmdlets.
