### ISSUE TITLE
Great resource!

### ISSUE THREAD

**Issue by jhaprakash26** [MicrosoftDocs/PowerShell-Docs#7706]
Each time i read these articles, i tend to discover something new which i can use in my day to day work. Must read for any aspiring PowerShell-scripter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51a14cf-e9db-6463-141c-2e6498e4e527
* Version Independent ID: a23755f9-7ded-991a-9675-57d3beb268ec
* Content: [Everything you wanted to know about hashtables - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Thanks, I am glad you find these useful.
