### ISSUE TITLE
-ReplyTo doesnt exist

### ISSUE THREAD

**Issue by Kav7** [MicrosoftDocs/PowerShell-Docs#7707]
Seems this parameter does not exist in 5.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3bffeb-411d-6ae8-c870-dea3ca8e0151
* Version Independent ID: c6c8dfc2-ec43-2231-908a-3a7ac67aeb0b
* Content: [Send-MailMessage (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Send-MailMessage.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
You are correct. But you are reading the PowerShell 7.1 documentation. The parameter exists in 7+
