### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by sbrcloudeon** [MicrosoftDocs/PowerShell-Docs#7711]
https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb = 404 Not Found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by mikefrobbins** [comment]
@sbrcloudeon Tested the URL from a non-Microsoft system and network with no issues.

![image](https://user-images.githubusercontent.com/6719572/122436164-38197500-cf5e-11eb-886b-c6088e3322f6.png)
