### ISSUE TITLE
Issue with MS repository - packages-microsoft-prod.deb

### ISSUE THREAD

**Issue by EricBergDE** [MicrosoftDocs/PowerShell-Docs#7713]
Currently the step: 
```
# Download the Microsoft repository GPG keys
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
```
is failing as the link gives a "404 Not Found"

Is this a known issue? Is there any workaround?

Thank you!

Cheers
Eric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#ubuntu-1804)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by zyjjp** [comment]
I see the same issue. Some days ago the download speed sometimes decreased dramatically (to like 5-10 minutes download time)  when accessed from some Azure West Europe servers. Now the link has completely stopped working.

**Comment by EricBergDE** [comment]
Yeah agree ... my last successful download was yesterday at 5pm CEST ... after this it always failed. 
I use it in a VMSS ... so it is regularly called ... now it fails

**Comment by sandroLuk** [comment]
Same here, all packages-microsoft-prod.deb files for ubuntu 16, 18 and 20 are down. Everything else in the repo seems to be reachable, but the debs return 404 https://packages.microsoft.com/config/ubuntu/18.04/

**Comment by mikefrobbins** [comment]
@EricBergDE Tested the URL from a non-Microsoft system and network with no issues.

![image](https://user-images.githubusercontent.com/6719572/122472259-f56b9300-cf85-11eb-81ad-344d3b50fa84.png)

If you continue to experience issues, I'd recommend reporting it as a regional outage as the documentation is accurate.
