### ISSUE TITLE
Is there an error in the document?

### ISSUE THREAD

**Issue by vered1234** [MicrosoftDocs/PowerShell-Docs#7720]
I am an early learner to PowerShell.

I have the following feedback:

1. It is not clear what is the difference between 'PowerShell 7' and 'Windows PowerShell'
2. The estimated read time for the on-line articles is total rubbish. 
3. There seems to be an clear error in one  place that I could see (see attached screen grab). If this is really an error in documentation, how can the reader be sure that there are not other errors is such a technical document? Is there no QA?
![image](https://user-images.githubusercontent.com/5228146/122663245-a69a4500-d1a1-11eb-9158-4180fcebeded.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc199c1f-4ae0-c474-f2d3-bad43022109c
* Version Independent ID: fe731c19-4f99-e680-f508-ec28126ac605
* Content: [about Comparison Operators - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
1. PowerShell 7 is built on .NET Core. Windows PowerShell is built on .NET Framework.
   We strive to maintain compatibilty, but there are some differences in the .NET versions
   that make that impossible. PowerShell 7 also has the Windows PowerShell Compatibility feature.
   See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility.

   See the following articles for information about the differences between Windows PowerShell and PowerShell (core).

   - https://docs.microsoft.com/powershell/scripting/install/migrating-from-windows-powershell-51-to-powershell-7
   - https://docs.microsoft.com/powershell/scripting/whats-new/cmdlet-versions
   - Release notes
     - https://docs.microsoft.com/powershell/scripting/whats-new/breaking-changes-ps6
     - https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6
     - https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-powershell-core-60
     - https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-powershell-core-61
     - https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-powershell-core-62
     - https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-powershell-70
     - https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-powershell-71

2. The read time is calculated by the documentation platform. Your reading time may vary. 
   I will forward your feedback to the platform engineering team.
   
3. Yes, you spotted an error. There are only 2 writers assigned to maintain this documentation 
   set of over 2900 files. We do the best we can and fix the problems when we find them.
