### ISSUE TITLE
Get-Counter -Counter "\Processor(_Total)\% Processor Time" -Continuous 

### ISSUE THREAD

**Issue by trollyanov** [MicrosoftDocs/PowerShell-Docs#7721]
[Enter feedback here]
command:
Get-Counter -Counter "\Processor(_Total)\% Processor Time" -Continuous

error: Get-Counter: The specified objects were not found on this computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1aedbbb-245d-4233-5fc3-432e81824d43
* Version Independent ID: 7fd17b39-0f00-39d5-ad46-fd143b4be0aa
* Content: [Get-Counter (Microsoft.PowerShell.Diagnostics) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-counter?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The example is correct. You are missing the `\` before the `%` character.

**Comment by trollyanov** [comment]
![123](https://user-images.githubusercontent.com/24922383/122681513-4b963b80-d1fd-11eb-9c77-a64cfc2c0777.jpg)

**Comment by trollyanov** [comment]
![new](https://user-images.githubusercontent.com/24922383/122681586-9e6ff300-d1fd-11eb-9554-b5dba7037806.jpg)
and this command too

**Comment by sdwheeler** [comment]
Apparently, performance counter names are localized. So the name of the counter on your system is different.
