### ISSUE TITLE
Add the answers to the "review" section

### ISSUE THREAD

**Issue by frenchiveruti** [MicrosoftDocs/PowerShell-Docs#7728]
Hello! 
I'm fairly new to powershell, but I'm eager to learn it, the problem I've come against is that currently the review section has no "answers" so I don't know if the solution I came up with is the correct one or not, a "spoiler" or covered "answers" section to the review section would be appreciated.  

In this particular case, the:
`What PowerShell commands exist for working with event logs?  `
Is the one giving me doubts. And I can't find an answer that satisfies me.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65418b6c-150b-3126-80cb-24e0b1f17972
* Version Independent ID: 61d0d0c0-12af-26d5-b3b0-ff102e04b5ab
* Content: [The Help System - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/02-help-system?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/ps101/02-help-system.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/ps101/02-help-system.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by chasewilson** [comment]
Hey @frenchiveruti , this is a good questions. This section of docs is directly from PowerShell 101 by Mike Robbins. We've tried to keep to the original formatting as much as possible. 

But, I hope I can help with your question. 

In the context of the doc "Help System", you should be able to discover commands using PowerShell. You can either use the `Get-Help` cmdlet, or the `Get-Command` cmdlet using the asterisk(`*`) as a wildcard. Such as `Get-Command -Name *EventLog*`

This will search all the available cmdlets that will contain the words surrounded by the wildcards (`EventLog`).

I hope this helps I'm closing this for now but feel free to respond if you need anything else and I'll be keeping an eye it. 

Good luck on your PowerShell journey and below are some resources to help you along the way. 

[Introduction to PowerShell - Microsoft Learn](https://docs.microsoft.com/en-us/learn/modules/introduction-to-powershell/)
[Write your first code with PowerShell - Microsoft Learn](https://docs.microsoft.com/en-us/learn/modules/powershell-write-first/)
[rPowerShell - Reddit](https://www.reddit.com/r/PowerShell/)

**Comment by frenchiveruti** [comment]
Thanks for the answer, I knew that it was based of PS101, and my suggestion was in a way of improving it, given that we have 'free unlimited space' to expand the content.  
If the decision is to keep it faithful to the source, fine then, I still think it would be nice to have the answers somewhere.  
Have a good one.
Francisco
