### ISSUE TITLE
Does this apply to PowerShell 7 or should it be removed for PS 7?

### ISSUE THREAD

**Issue by Darroll** [MicrosoftDocs/PowerShell-Docs#7734]
Does this apply to PowerShell 7 or should it be removed for PS 7?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114b8b70-1c63-21f3-9e6b-df616ef52ef5
* Version Independent ID: 1419e56e-ad6c-feae-939d-dd73e0475678
* Content: [DSC Script Resource - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/scriptResource?view=powershell-7.2)
* Content Source: [reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @mgreenegit
* Microsoft Alias: **migreene**

**Comment by mgreenegit** [comment]
This does apply to PowerShell 7. For now, only to Windows since the Script resource is implemented as script rather than class-based.

**Comment by chasewilson** [comment]
I believe the question is answered, thanks to @mgreenegit. I'll be closing this for now but if more is needed, I'll be happy to reopen the issue and go from there.
