### ISSUE TITLE
New-EventLog needs quotation marks around LogName

### ISSUE THREAD

**Issue by mcbsys** [MicrosoftDocs/PowerShell-Docs#7742]
I've found that if I follow the example to create an event log source, e.g. 

`New-EventLog –LogName Application –Source "IT Script"`

I get a bogus event log in the registry and am unable to write events. 

_The source 'IT Script' is not registered in log 'Application'. (It is registered in log '�?LogName Application �?Source'.)_ "

If I put quotation marks around "Application", the source is created correctly under the Application key in the registry and I am able to write events.

`New-EventLog –LogName "Application" –Source "IT Script"`

Blogged here with screen shots:

https://www.mcbsys.com/blog/2021/06/powershell-cant-write-event-after-creating-custom-source/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfed927-ad93-1ee4-9c23-2d53ab07a180
* Version Independent ID: b63cdcb8-0581-8479-ecc8-ee19e8973692
* Content: [New-EventLog (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-eventlog?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/New-EventLog.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/New-EventLog.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
Hey @mcbsys, thanks for the feedback here. 

I can't repro the issue on my local machine or a fresh 2016 datacenter server. Both tests resulted in log creation under the application log in the registry. 

I'm going to close this for now as this is the expected behavior.

However, if there is more to talk about, feel free to respond and I'll be monitoring to see if we need to reopen

**Comment by mcbsys** [comment]
Thanks for your reply. I'm testing on Win10 20H2. I think I finally found the issue, and you're right, it's not documentation. Somehow I got en dashes (Unicode 2013) into my code. The PowerShell GUI is smart enough to convert those to regular dashes when you paste a command into the blue window, so that works. But if you put this in a .ps1 file, preserving the en dashes, you should see the error:

`New-EventLog –LogName Application –Source "IT Script"`

PowerShell interprets `–LogName Application –Source "IT Script"` as the first, positional parameter, and creates a completely new event log here:

Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\â€LogName Application â€Source

If you update the .ps1 file to use normal dashes:

`New-EventLog -LogName Application -Source "IT Script"`

it creates the Source under Application, as expected:

Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\IT Script

**Comment by chasewilson** [comment]
ahh the actual logname makes sense then I was really confused why logname and source were involved but not I don't know why I didn't think of it in the first place. 

Glad you have it worked out!
