### ISSUE TITLE
Page content is outdated...

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#7749]
... yet the page is being referenced from the new-issue template in the source-code repo.

To give a few examples: only 6.0 is mentioned, native globbing is mentioned as missing, but has since been implemented, sample commands fail (`pwsh Set-Date 8/18/2016`), ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba18a094-43ba-5ae6-c744-dbe95fd6336d
* Version Independent ID: c8eefde4-7679-34c2-0491-5244b250d0ba
* Content: [Known Issues for PowerShell 6.0 - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/known-issues-ps6?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/whats-new/known-issues-ps6.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/known-issues-ps6.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
This article is correct for the 6.0 release for which it was written. It is included here for historical reference. I was unaware the Dev team was pointing to it as current reference. I had planned to create an updated version of the v6 release notes to summarize the current state. I guess that time has come.
