### ISSUE TITLE
Semicolon missing in code block

### ISSUE THREAD

**Issue by gmsaiful** [MicrosoftDocs/PowerShell-Docs#7750]
Correction of code block -
**Existing block:**
Get-CimInstance -Class Win32_LogicalDisk |
  Select-Object -Property Name, @{
    label='FreeSpace'
    expression={($_.FreeSpace/1GB).ToString('F2')}
  }

**Correct is:**
Get-CimInstance -Class Win32_LogicalDisk |
  Select-Object -Property Name, @{
    label='FreeSpace' ;
    expression={($_.FreeSpace/1GB).ToString('F2')}
  }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d073225d-0a14-b3e9-3ba6-771f31cfd2b6
* Version Independent ID: e0f8715c-ff38-fe9b-758e-472cd58947a9
* Content: [Selecting Parts of Objects Select Object - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/samples/selecting-parts-of-objects--select-object-?view=powershell-7.1#feedback)
* Content Source: [reference/docs-conceptual/samples/Selecting-Parts-of-Objects--Select-Object-.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Selecting-Parts-of-Objects--Select-Object-.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The semicolon is not required when the each key/value pair is on a separate line.
