### ISSUE TITLE
REcurse option mean to recurse....brilliant definition

### ISSUE THREAD

**Issue by Mikengk** [MicrosoftDocs/PowerShell-Docs#7753]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715b0ab7-e386-baf6-970b-d2a703501397
* Version Independent ID: 1eace7de-83aa-39a7-7a19-862e9e37b5f7
* Content: [Copy-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
If you have any actionable feedback or suggested changes, feel free to respond here. For now I'll be closing this issue and monitor for any response.
