### ISSUE TITLE
Test-Json documentation does not clearly state its limitations

### ISSUE THREAD

**Issue by hacst** [MicrosoftDocs/PowerShell-Docs#7760]
From the documentation it is not clear that Test-JSON is not able to validate all JSON and does not reject all invalid JSON.

As shown in https://github.com/PowerShell/PowerShell/issues/11384 it does not accept valid JSON like a JSON array:
```pwsh
'[1,2]' | Test-Json
Test-Json: Cannot parse the JSON.
False
```

It also does not reject all invalid JSON:
```pwsh
"{'problem':'Single quotes are not valid JSON'} // And comments like this are not valid JSON either" | Test-Json
True
```

JSON is a well defined format so there is not much nuance to validating it (see https://www.json.org). Personally both of these feel like important bugs but the issue linked above has been open since the end of 2019 through multiple releases. So if this behavior is actually intentional or accepted these restrictions should be documented clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9863594-6c07-c13e-1502-378edbb2b269
* Version Independent ID: 3749eef8-2406-df1d-2f3b-3e4a91c97225
* Content: [Test-Json (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/test-json?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Test-Json.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Test-Json.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@MicrosoftDocs/shiproom-psdocs Is this by design in Netwonsoft.Json?

**Comment by sdwheeler** [comment]
PowerShell uses the Newtonsoft.Json assemblies. Newtonsoft lists JSON comments and single-quote support as features. See https://www.newtonsoft.com/json.

As for the `'[1,2]' | Test-Json` fail, that is a bug that is being investigated. Waiting on feedback from the PowerShell committee to decide what should be done.
