### ISSUE TITLE
about_Functions_Advanced_Parameters page should at least mention ArgumentCompletions attribute

### ISSUE THREAD

**Issue by DJackman123** [MicrosoftDocs/PowerShell-Docs#7767]
This page talks about the ArgumentCompleter attribute, but doesn't say anything about the ArgumentCompletions attribute.  This is preferred over ArgumentCompleter when the list of values is static.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fdd3909-4005-b224-0395-364445d4d4b6
* Version Independent ID: 4eac80f8-61be-4d0f-d657-a007ba81cf53
* Content: [about Functions Advanced Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.1#argumentcompleter-script-block)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@MicrosoftDocs/shiproom-psdocs When was this attribute added? Need details to document it.

**Comment by DJackman123** [comment]
Not sure about that, but the [class doc page](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.argumentcompletionsattribute?view=powershellsdk-7.0.0) for the attribute says 6.2 and 7.0.  However, the [changelog for 6.0.0-beta8](https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/CHANGELOG/6.0.md#600-beta8---2017-10-05) has an item that mentions this attribute, and I found a [commit that added this attribute](https://github.com/PowerShell/PowerShell/commit/93dc591025b77088541cfd5a3eb6be1f41fea0cb#diff-dd1f41ead46dc2f7a1a0f9900f68fc0df1f6ea10f3a1d8cad177c4046f1c7928) on September 21, 2017.  So it was probably available in version 6.0.  I can say for sure that it's not supported in 5.x.
