### ISSUE TITLE
LiteralPath/Path explanation requires more information relating to processing fle system items with []

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/PowerShell-Docs#7775]
In the description of LiteralPath/Path, there is no explanation of processing file system items (files or diretories) that contain square brackets. This is one of the biggest problems in powershell especially for beginners, as I myself had all sorts of issues with many of the file system commands that need to work and handle these items. On discovering this gotchya, I have since simply learnt to avoid using the -Path parameter (using LiteralPath exclusively) and so far this has served me well. However, I do not think this is entirely correct, but I don't know why and have never found the real solution to this.

+ So, firstly, what feature of powershell is it that means that items including square brackets can't be processed by standard PS file system commands (Copy-Item, Move-Item, Rename-Item etc). I'm guessing there is a feature in processing file system paths relating to sqaure brackets. So what is this and can you link to a document that explains this.

+ The description of LiteralPath: "... (Use the Path parameter when wildcard characters are supported.)", seems to me to be inaccurate. If we are to support wildcards and hence should use Path, this breaks down when encountering file system paths with square brackets. So, does this mean that we can't supprt wildcards/Path if we need to also be able to process [] in paths? What is the rational explanation of this, or is this a bug/not currently catered for? If is is not supported, then this should be mentioned in this document and probably documented for ALL those file system commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcef1f95-0d09-039b-e743-7fde2e15ea22
* Version Independent ID: 299eff39-f42a-cf16-7a1f-8e6cd68adf57
* Content: [Resource Parameters - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/resource-parameters?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/resource-parameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/resource-parameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by chasewilson** [comment]
Hi @plastikfan, I see your issue here. If you take a look at PowerShell's definition of _Wildcard_ characters in [about_Wildcards](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.1), you'll see the the squarebrackets (`[]`) characters are defined as wildcard characters. 

It's not about the file system, it's about the interpreter and that's why the `-LiteralPath` parameter will work but not the `-Path` parameter unless you define escaper characters. 

I'll be closing this for now. However, feel free to respond here and I'll be monitoring and can reopen if necessary.

**Comment by plastikfan** [comment]
Ok, so the square brackets are wildcards. But what does that have to do with paths in the file system containing square brackets. These are 2 entirely different concepts, but the wild card implementation is breaking file system locations that contain [], and what's worse it's not documented here or in the about wildcards article you linked to. I still feel like work to document this still needs to be provided

**Comment by plastikfan** [comment]
Also, taking the second point made in my original request, it seems like we can never use the Path parameter, because any file system may contain items whose path contains square brackets. The Path parameter is not reliable in these situations and therefore can't be used, unless the user is sure that their filesytem is entirely free of items containing square brackets, but this is just not a reality.

**Comment by chasewilson** [comment]
Because both the `-Path` and `-LiteralPath` parameters specifiy that their purpose is based on how they interact with wildcard characters.

The `-Path` parameter interprets wildcard characters as wildcards unless escaped with escape characters.

The `-LiteralPath` parameter doesn't interpret wildcard characters and reads it as the literal path. 

PowerShell provides these parameters to include the flexibility for wide ranging results. If you know your environment contains these characters, options are provided for any scenario you need. If you need some flexibility while still defining spqcific characters, you can use escape characters with the `Path` param to call specific folders as well as wider results. If you need only specific, you can use `-LiteralPath`.

**Comment by plastikfan** [comment]
Ok. I have finally found the real answer to my question. And this is fundamentally what I was getting at which I don't think I made you understand.

I found this on stackoverflow: [Function to escape characters in paths](https://stackoverflow.com/questions/46037095/function-to-escape-characters-in-paths).

The article at [about_Wildcards](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.1), should really be referencing this: [WildcardPattern.Escape](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.wildcardpattern.escape?view=powershellsdk-7.0.0)

The main point I was trying to make, which I admit I may not have been that successful at is this:

*How do I write my file system code so that it can use the -Path parameter properly without encountering issues relating to square brackets. And the answer is, use WildcardPattern.Escape on ALL path references.*

This needs to be documented in ALL file system commands (Copy-Item, Rename-Item, Move-Item, etc ... actually all commands that have a -Path and -LiteralPath parameters).

Please can you action this (re-open this issue and fix), after all, I am just using this feedback facility for the purpose it was intended for; ie improving the documentation.

**Comment by plastikfan** [comment]
(PS, part of my mis-understanding of this issue, was me not realising the [] are wildcard characters in powershell. Up to this point, I thought wildcard was simply just '*' and nothing else).

**Comment by plastikfan** [comment]
Actually, I've given this a bit more thought and I realise now that the real issue, is that there shouldn't even be a LiteralPath option, rather, anytime a file system command is invoked which returns a path, it should return it already escaped. As far as I can see, there is no reason to not return pre-escaped paths without the user having to so this manually. The only reason why we need to do this manually is because of legacy/backward compatibility reasons.

I know you can't simply remove LiteralPath, that would be damaging, but instead all those functions should have an alternative, something like **EscapedPath** which would return an escaped path. From a users perspective this could replace the use of both **LiteralPath** and **Path**, thereby simplifying usage. I know this is not an issue for the docs team, so I'll take it up the PS code repo. I still would like to see the documentation updated to at least mention WildcardPattern.Escape.

**Comment by chasewilson** [comment]
Well there are valid reasons for allowing Path to accept wildcard characters. For instance, a very simple example:

```powershell
Get-ChildItem -Path [tb]est.csv -Recurse
```
This allows you to recurse through all child files and folders and get all csv's named `test.csv` or `best.csv` while avoiding files like `rest.csv`.

If you remove `-LiteralPath` and only allow literal characters, you lose _some_ dynamic ability in search. If there was no recourse for avoiding these wildcard characters, the argument could be made. However, when writing your code you do have a fairly easy solution to make, as an example, search and removal fairly easy:

```powershell
Get-ChildItem -LiteralPath C:\[Test]Folder -Filter [tb]est.csv -Recurse | Remove-Item -LiteralPath $_.FullName
```

this allows you to search your folders even with a typically wildcard character and remove them without any manipulation by a dotnet method. 

I hope this helps some.
