### ISSUE TITLE
Output type object?

### ISSUE THREAD

**Issue by er1k-peterson** [MicrosoftDocs/PowerShell-Docs#7784]
I came to this article trying to see what the result type of the Get-ChildItem results are. All the article says is that its output are of type Object. That seems amazingly useless. What are the properties of these objects it can return?

The doc examples suggest some of the properties may include Name, LastWriteTime, etc but these are not part of the result as far as I can tell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd63f6e7-f3f3-edbc-acf6-b52de6c0eab4
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by doctordns** [comment]
It is not that simple. Get-GhildItem is layered on top of PowerShell's Provider layer. Thus GCI returns different object types, depending on the provider you ultimately query.  The Cert provider vs the Function provider, for example. Secondly, in a lot of (most?) cases,  GCI returns an array of objects (an array if file objects where you query the filestoreprovider).  Strictly speaking that array itself is typed as Object, thus the document is accurate ( at one.level). 

For those very new to PowerShell this is a great learning opportunity. The properties you mention are present on the objects returned by the filestore provider. You can verify this as follows.

```powershell
# get some filestore provider objects 
$Files = GetChilditem -Path c:\Windows
#Verify type
$Files.GetType().Fullback
# verify properties
$Files | Get-member Name
```

**Comment by er1k-peterson** [comment]
It may not be a doc issue. I'm a web developer who normally doesn't work with powershell so I'm not really sure what to expect in powershell documentation.

I think to put something to the effect of what you explained above may be very useful though, that the result is provider-specific. Still, thanks for the helpful explanation.

**Comment by chasewilson** [comment]
Hey @er1k-peterson, thanks for the feedback here. @doctordns is correct here and we do mention this in the Description section:

"Locations are exposed to Get-ChildItem by PowerShell providers. A location can be a file system directory, registry hive, or a certificate store. For more information, see about_Providers."

This includes a link to the [about_Providers](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_providers?view=powershell-7.1) doc. We also use several examples to show the results of getting different objects from these providers. 

I think this covers the documentation section and hope it helps. I'll be closing this issue for now but feel free to respond here and I'll be monitoring. If I need to I'll reopen and can go from there.
