### ISSUE TITLE
Duplicate Sections

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftDocs/PowerShell-Docs#7791]
At the beginning of this page, it lists the core syntax 6 times.   I see no differences in the examples.

Cheers,
Jeff Smalley MCT
Chicagoville

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db37c0c4-39fa-96c1-bddc-ff78fad4e3b8
* Version Independent ID: 041a02c8-a27e-756f-9a9d-5432bf5a52ac
* Content: [Receive-Job (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/receive-job?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/Receive-Job.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/Receive-Job.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
Hey @JeffSmalley, Thanks for the feedback here. 

If you take a look, they are all different paramter sets. For example 

```powershell
# Parameter Set 1
-Job
-Location

# Parameter Set 2
-Job
-ComputerName
```

There are differences in syntax for every parameter set. I hope this helps. 

I'm closing this issue for now. Feel free to respond and I'll be monitoring.
