### ISSUE TITLE
`-is` and `-isnot` are implied to have case-[in]sensitive variants

### ISSUE THREAD

**Issue by kurtmckee** [MicrosoftDocs/PowerShell-Docs#7803]
# Documentation Issue

It appears that type comparison operators (`-is` and `-isnot`) are documented in two locations: about_comparison_operators and about_type_operators.

However, due to their inclusion in about_comparison_operators, I was under the impression that `-is` and `-isnot` would have explicit case-sensitive and case-insensitive variants, like `-cis` or `-iisnot`. This is because the about_comparison_operators document includes the text

```
To make a comparison operator case-sensitive, add a c after the -.
```

and 

```
To make the case-insensitivity explicit, add an i after -.
```

Would it be worthwhile to remove `-is` and `-isnot` from about_comparison_operators and document them only in about_type_operators? This could reduce duplication and the possibility of confusion about case-[in]sensitive variants of these operators.

## Context of the issue

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.1

- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Preview content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
It should be clear that case-sensitivity only applies to string comparisons. We will review the current documentation and make that clearer, if needed.
