### ISSUE TITLE
GREAT Information Page for where im at right now.

### ISSUE THREAD

**Issue by stsaxon** [MicrosoftDocs/PowerShell-Docs#7814]
I have been reading taking notes, watching videos and playing around with the shell for Powershell.  I have been writing some little small scripts just to get my feet wet. It's been years since I have programmed in any language. The last was Pascal in the early 90's. This page has taken me hours to cover like I wanted to and to make sure I covered all the links. More information than I thought was packed into this page. Love it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 991d5074-d056-f663-ffa9-42fdb0d95900
* Version Independent ID: 55d48d73-6fc4-29de-4cc1-c02bcb6a13d8
* Content: [Set-ExecutionPolicy (Microsoft.PowerShell.Security) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Thanks for the feedback. I am glad you are finding the docs helpful.
