### ISSUE TITLE
Install the latest PowerShell for new features and improvements!

### ISSUE THREAD

**Issue by MrinvIN** [MicrosoftDocs/PowerShell-Docs#7830]
i havre the same issue and im not able to download that
![Administrator_ Windows PowerShell 22-07-2021 12_00_50](https://user-images.githubusercontent.com/87579443/126598316-0199b185-b035-4063-8d2c-ac9bab7b85f5.png)

**Comment by sdwheeler** [comment]
What problem are you having? You haven't provided an error message or described a problem.
