### ISSUE TITLE
UseWindowsPowerShell Flag Missing Documentation

### ISSUE THREAD

**Issue by peoplesmeat** [MicrosoftDocs/PowerShell-Docs#7843]
The documentation for UseWindowsPowerShell just says 

`{{ Fill UseWindowsPowerShell Description }}`

Which makes me think that someone just forgot to fill out this documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d36d08-cdb0-08d2-6eba-7fad917791f6
* Version Independent ID: ccdd5a9c-5230-20de-db28-39e53a795ce3
* Content: [New-PSSession (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/New-PSSession.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Yep, we missed that. Thanks for bring it to our attention. The full detailed information can be found at: https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility
