### ISSUE TITLE
Set-NetFirewallRule -Name "WINRM-HTTP-In-TCP-PUBLIC" -RemoteAddress Any does not work on win10

### ISSUE THREAD

**Issue by renevaessen** [MicrosoftDocs/PowerShell-Docs#7849]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd586ba9-aea3-47b1-b98b-a216338dd84d
* Version Independent ID: 6e7337a1-09d4-7997-3186-ba8388c60551
* Content: [about Remote Requirements - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_requirements?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The name of the firewall rule can be different for different versions of Windows. Use `Get-NetFirewallRule` to see a list of rules.
