### ISSUE TITLE
Inquiry: reuseable code file naming conventions

### ISSUE THREAD

**Issue by Valtarien** [MicrosoftDocs/PowerShell-Docs#7851]
@mikefrobbins Upon committing to enter a comment, I was immediately taken to a new entry here. Forgive me if I do not take the time to search for similar or duplicate comments/feedback.

I only wanted to inquire about what naming conventions you (the article author and collaborators) and other knowledgeable individuals recommend for your file(s) containing your library of reuseable functions, and even other code snippets?

Thank you for your efforts and your time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f934b99-7214-c3d2-a197-d2f58df18b7c
* Version Independent ID: cb5bec10-7bfe-0421-509c-48525de3695b
* Content: [Functions - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/09-functions?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/ps101/09-functions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/ps101/09-functions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by sdwheeler** [comment]
@mikefrobbins Can you answer this? I think you have blog posts about this.

**Comment by sdwheeler** [comment]
There’s no one official PS style guide, but we do have a few others:
- Here is a [community guide](https://github.com/PoshCode/PowerShellPracticeAndStyle) that I’ve found to be pretty reliable but again, not official. 
- Azure PowerShell has  some [design guidelines](https://github.com/Azure/azure-powershell/tree/main/documentation/development-docs/design-guidelines) and best practices learned from developing lots of large modules. Some of it is Azure-specific, but it’s mostly generic
- PowerShell ScriptAnalyzer encodes some best practices as linting rules. The [PSSA](https://github.com/PowerShell/PSScriptAnalyzer) repo has instructions for getting started as well as documentation explaining the rules
- Some it may be a bit out-of-date, but we do have a developer guide for both [cmdlets](https://docs.microsoft.com/powershell/scripting/developer/cmdlet/cmdlet-overview) and [modules](https://docs.microsoft.com/powershell/scripting/developer/module/writing-a-windows-powershell-module)


I am fairly certain that @mikefrobbins also has some recommendations on his blog.

**Comment by mikefrobbins** [comment]
As a best practice, if you're adding all your functions to a monolithic PSM1 file (script module), name the PSM1 file the same name as the module. For example, `mymodule.psm1`. If you're storing one function per file, name the file the same as the function. For example, `myfunction.ps1`.

**Comment by sdwheeler** [comment]
@Valtarien You might also check out some of these posts
- https://mikefrobbins.com/2018/05/04/video-writing-award-winning-powershell-functions-and-script-modules/
- https://mikefrobbins.com/2016/05/26/video-powershell-toolmaking-with-advanced-functions-and-script-modules/
- https://mikefrobbins.com/2013/07/04/how-to-create-powershell-script-modules-and-module-manifests/

**Comment by Valtarien** [comment]
Thanks to both of you, @mikefrobbins and @sdwheeler for the good advice! Much appreciated!
