### ISSUE TITLE
Mention that a script block is usually sufficient as a calculated sort property

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#7854]
The topic only mentions _hashtables_, not also _mere script blocks_.

However, hashtables are only necessary if you need to control the sort order (ascending vs. descending) on a _per-property_ basis - which is not common.

That is, instead of:

```powershell
'aaa', 'aa' |  Sort-Object @{ Expression = { $_.Length }; Ascending = $true }
```

you can more simply write:

```powershell
'aaa', 'aa' |  Sort-Object { $_.Length }
```

Even if descending sorting is needed, a script block combined with the `-Descending` switch is sufficient, unless there are _multiple_ calculated properties that require a _mix_ of ascending and descending sorting.

In other words: Specifying a mere script block will _typically_ suffice, and should therefore be featured prominently in the topic, especially in `-Property`  parameter's description. (Currently, only example 8 shows the script-block technique.)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff7af27-47d8-506e-126e-f8764a72f8bb
* Version Independent ID: 4d53643b-68f8-5bd9-1552-d5cea633f284
* Content: [Sort-Object (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-gb/powershell/module/Microsoft.PowerShell.Utility/Sort-Object?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Sort-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Sort-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
Ok, so this is true but what would be the use case for the script block? You can define the property and order like this:

```powershell
'aaa','aa | Sort-Object -Property Length
```

The hashtable has the use case brings the value of multiple properties and orders whereas in the case for a scriptblock, the best practice should be to use standard params right?

I could see the value in clarifying that the hashtable's purpose is for multiple properties and orders and highlighting a scriptblock use case in example 6 (Sort text files by time span) if you think that would be a good course of action?

**Comment by mklement0** [comment]
The example wasn't meant to be real-world scenario, it was just meant to illustrate the syntax.

Yes, revising example 6 is a good idea.

Additionally, I think it's important for the `-Property` parameter description to discuss the script-block-only option too.

---

To provide another, more realistic example : sort a list of strings (such as file names) by an embedded sequence number:

```
'1_one', '2_two', '10_ten'  | Sort-Object { [int] ($_ -split '_')[0] }
```

**Comment by AltitudeApps** [comment]
> To provide another, more realistic example: sort a list of strings (such as file names) by an embedded sequence number:
> 
> ```powershell
> '1_one', '2_two', '10_ten'  | Sort-Object { [int] ($_ -split '_')[0] }
> ```

Good idea, but probably also a good idea to start with something which isn't already in sorted order:

```powershell
'1_one',  '10_ten', '2_two',  | Sort-Object { [int] ($_ -split '_')[0] }
```

**Comment by sdwheeler** [comment]
@AltitudeApps This is essentially what Example 8 is about.
