### ISSUE TITLE
Listing All Uninstallable Applications - Example not relevant to text

### ISSUE THREAD

**Issue by clamb123** [MicrosoftDocs/PowerShell-Docs#7870]
[Enter feedback here]

"There is no guarantee that these values are unique. In the following example, two installed items appear as "Windows Media Encoder 9 Series":"

and then the example filters for "Microsoft Silverlight"???

Not sure what to suggest as replacement, maybe "*office*" or "Microsoft Visual C++*" but neither exist on a standard Windows 10 install. You could use -like "Microsoft*" but the output would be massive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6302f6fb-6192-f43f-4ba4-85ebd79941b9
* Version Independent ID: e86062a7-1c61-92b4-407a-293990d30a06
* Content: [Working with Software Installations - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/samples/working-with-software-installations?view=powershell-5.1)
* Content Source: [reference/docs-conceptual/samples/Working-with-Software-Installations.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/samples/Working-with-Software-Installations.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@clamb123 These examples are very old. A lot has changed. We have considered retiring them because of this. We will take a look at updates but would welcome contributions of new samples. Especially for non-Windows platforms.
