### ISSUE TITLE
The last example for -NoEnumerate is meaningless

### ISSUE THREAD

**Issue by AltitudeApps** [MicrosoftDocs/PowerShell-Docs#7882]
The last example states:

> By default, the `Write-Output` cmdlet always enumerates its output. The NoEnumerate parameter suppresses the default behavior, and prevents `Write-Output` from enumerating output. The NoEnumerate parameter has no effect if the command is wrapped in parentheses, because the parentheses force enumeration. **For example, (`Write-Output 1,2,3`) still enumerates the array.**

Well, of course it does...   The `-NoEnumerate` flag was not specified.  It should **at least** read:  
>  For example, **`(Write-Output -NoEnumerate  1,2,3)`** still enumerates the array.

But wait, this isn't exactly accurate, either.  Both of the expressions:

- `(Write-Output -NoEnumerate  1,2,3)`
- `Write-Output -NoEnumerate  1,2,3`

evaluate to the following:  an object of type `Object[]`, with a `.Count` property of `3`.

The behavior of `-NoEnumerate` _appearing_ to have no effect when used within an expression operator, (meaning inside parentheses), is that this enumerable object of cardinality 3 is being delivered to the context of the calling scriptblock, where it then becomes part of the output stream for that scriptblock.  Since there is no use of `Write-Output` in the context of the calling scriptblock, there is obviously no use of the `-NoEnumerate` flag either, and therefore the array is enumerated.  

```
$petard.Hoist( $self )        # unexpected !
```

So, in fact, the statement:
> The NoEnumerate parameter has no effect if the command is wrapped in parentheses, because the parentheses force enumeration.

is simply wrong.

What it should say is something like:

> By default, the `Write-Output` cmdlet always enumerates its output. The NoEnumerate parameter suppresses the default behavior, and prevents `Write-Output` from enumerating output. **However, please note:**  The NoEnumerate parameter only applies to the expression in which it immediately appears.  If `Write-Output -NoEnumerate` is used in an expression which is part of a larger expression, the default behavior of `Write-Output` enumerating enumerable values will apply in the parent expression(s), and it will appear that `-NoEnumerate` is having no effect, unless `Write-Output -NoEnumerate` is _also_ used in those parent expressions.

### Examples to demonstrate:

```pwsh
# some initial setup to avoid typing the same thing over and over:

$sbDisplayStage1 = `
  {
    Write-Host "`nstage 1 item count: $($_.Count)";
    Write-Host "stage 1 item type:  $($_.GetType().Name)";
  }

$sbStage2 = `
  {
    $typename = $($_.GetType().Name)
    switch ( $typename ) {
      'Object[]' { $color = [consolecolor]::Green  }
      default  { $color = [consolecolor]::Red }
    }
    Write-Host "`n  stage 2 item count: $($_.Count)";
    Write-Host -fore $color "  stage 2 item type: $($_.GetType().Name)`n";
    "  item: : $_"
  }



Write-Host -fore Blue "Write-Output, straight up, not using -NoEnumerate:"

(1,2),(6,7,8) `
  |                     `
    Foreach-Object {
      . $sbDisplayStage1
      Write-Output  $_
      # enumerates the array, the default behavior
    } `
  | ForEach-Object `
      -Process $sbStage2


Write-Host -fore Blue "`n`nWrite-Output, using -NoEnumerate:"

(1,2),(6,7,8) `
  |                     `
    Foreach-Object {
      . $sbDisplayStage1
      Write-Output -NoEnumerate $_
      # does NOT enumerate the array
    } `
  | ForEach-Object `
      -Process $sbStage2



Write-Host -fore Blue "`n`nWrite-Output, using -NoEnumerate, but only within an expression"

(1,2),(6,7,8) `
  |                     `
    Foreach-Object {
      . $sbDisplayStage1
       (   Write-Output -NoEnumerate $_   )
           # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           # does NOT enumerate the array,
           # BUT:
      #^                                  ^
      # the expression in parenthesis evaluates to that array...
      # ... but remember, arrays are enumerable...
      # this enumerable object is added to the current scriptblock's
      # output stream ...
      # ... which by default always enumerates the enumerable !!
      # and we're back where we started
    } `
  | ForEach-Object `
      -Process $sbStage2


Write-Host -fore Blue "`n`nWrite-Output, using -NoEnumerate, at every level which contributes to the output stream:"


(1,2),(6,7,8) `
  |                     `
    Foreach-Object {

      . $sbDisplayStage1

      Write-Output -NoEnumerate (   Write-Output -NoEnumerate $_   )
      #            ^^^^^^^^^^^^                  ^^^^^^^^^^^^

      # if you want `-NoEnumerate` to "stick", you have to use it at
      # EACH and EVERY place where values are being contributed to the
      # output stream...
      # ... which means you must use `Write-Output` explicitly wherever
      # something is being put into the output stream, because without
      # using it explicitly there is no way to specify the `-NoEnumerate`
      # flag, and you end up getting the default behavior, which is
      # enumeration

      # Think of it this way:  `-NoEnumerate` is only good for a single
      # use, once it's been applied, it has been completely expended.
      # So you have to supply a fresh use of `-NoEnumerate` at every
      # single place where any value is being contributed to the output
      # stream.

    } `
  | ForEach-Object `
      -Process $sbStage2

```

If `Write-Output -NoEnumerate (   Write-Output -NoEnumerate $_   )` seems silly, consider it in the context of something a little more involved:

```pwsh
. {
    Write-Output -NoEnumerate `
      $(
          'a';
          'B';
          Write-Output -NoEnumerate 1,2,3
          'z'
      )
}
```
Versus:
```pwsh
. {
   # failed to use -NoEnumerate on the outer level, rendering the 
   # use of -NoEnumerate on the inner expression moot
    Write-Output  `
      $(
          'a';
          'B';
          Write-Output -NoEnumerate 1,2,3
          'z'
      )
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c943442f-ae92-5d64-9fa4-3421cc94623c
* Version Independent ID: f0d97751-59f2-7dcb-5c9c-11fa9e557e1b
* Content: [Write-Output (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-output?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Write-Output.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Write-Output.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
`-NoEnumerate` is only meaningful within the pipeline. Trying to see the **NoEnumerate** behavior in the console is problematic because PowerShell adds `Out-Default` to the end of the pipeline, which results in enumeration. But if you pipe `Write-Output -NoEnumerate` to another cmdlet, that cmdlet received the collection object, not the enumerated items of the collection.
