### ISSUE TITLE
Syntax errors/weird syntax on about_Functions

### ISSUE THREAD

**Issue by zxskyyy** [MicrosoftDocs/PowerShell-Docs#7885]
# Documentation Issue

Syntax errors on _**about_Functions**_ docs, more precisely on the parts when parameters are showed.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions?view=powershell-7.1
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [x] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [x] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No.

## Detailed description of the issue

I'm very, very new to VSCode. I was swooping through the docs, and while trying to figure out how to put a function together with the help of the "about_Functions" entry, I stumbled upon this function syntax:

![image](https://user-images.githubusercontent.com/65634520/127601211-137b9004-5f5f-4b07-bbea-c56992ca2156.png)

Despite looking like it made sense at first glance (Since it kinda looks like params in Java and Javascript), it still struck me as weird-looking and it gave me the red underlines when tried on VSCode, but I shrugged it off and went straight to the section of the entry that dives deeper into parameters. "Maybe that's a more complex implementation that I don't understand very well yet, I'll just look for the simpler version", I thought while scrolling down, but I was quickly proven wrong.

![image](https://user-images.githubusercontent.com/65634520/127601504-cdd67158-d6d3-423b-a95d-586b00875609.png)
![image](https://user-images.githubusercontent.com/65634520/127601516-b5bcca18-b97e-4fea-9e72-046e934371dc.png)

The same oddly placed square brackets are still there.

I decided to give it another shot in VSC. "Maybe the params before the curly brackets are a mistake on the author's behalf", I thought.

Again, I was proven wrong.

![image](https://user-images.githubusercontent.com/65634520/127603598-62a97550-c711-4d21-9d17-abbb828ce80d.png)

I can now confidently claim that there's an error in the parameter syntax!

**Comment by chasewilson** [comment]
I can seee where the confusion comes from here. In our reference docs, all of our cmdlet documentation has a syntax around how it's documented and can read about it in [about_Command_Syntax](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_command_syntax). The square brackets around a parameter in the documentation mean it is an optional addition. The square bracket preceding the comma and ending after parameter two are to indicate that that syntax is optional. 

A normal looking function will look like this:

```powershell
function Test-Function {
    param (
        [string]$TestParam1,
        [string]$TestParam2
    )

    Write-Output "$TestParam1 $TestParam2"
}
```

@sdwheeler, I do think there is room for a change here though. we indicate that at least one param is required in the `param` block but that's not the case. This function will run just fine:

```powershell
function Test-Function{
    param()

    Write-Output "No parameters needed"
}
```

Let me know what you think.
