### ISSUE TITLE
Invoke-WebRequest -URI help

### ISSUE THREAD

**Issue by trollyanov** [MicrosoftDocs/PowerShell-Docs#7890]
why doesn't it work?

$Response = Invoke-WebRequest -URI https://www.bing.com/search?q=how+many+feet+in+a+mile
$Response.InputFields | Where-Object {
    $_.name -like "* Value*"
} | Select-Object Name, Value

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5053dee-ceef-0af8-3abf-0d4c7ca2e51d
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
You are referencing the 7.1 doc version but I think you are using PowerShell 5.1. In the 5.1 doc, it lets you know to use the `-UseBasicParsing` parameter in the example so if you run it this way it should work:

```powershell
$Response = Invoke-WebRequest -URI https://www.bing.com/search?q=how+many+feet+in+a+mile -UseBasicParsing
$Response.InputFields | Where-Object {$_.name -like "*value*"} | select Name, value
```

```Output
name       value
----       -----
From Value 1
To Value   5280
```

I'm closing this for now but feel free to reach out if you have any more questions.

**Comment by trollyanov** [comment]
![image](https://user-images.githubusercontent.com/24922383/127721359-41b40e95-bdc3-4bfc-9d7c-1ef90473c653.png)

**Comment by trollyanov** [comment]
empty

**Comment by trollyanov** [comment]
This work:
$Response = Invoke-WebRequest -URI https://www.bing.com/search?q=how+many+feet+in+a+mile -UseBasicParsing
$Response.InputFields | Where-Object {$_.name -like "*submit*"} | Select-Object Name, submit

**Comment by sdwheeler** [comment]
The example works as written for us. It could be a difference of language. We are using en-us. Are you set to a different language?

What do you get from the following command?

```powershell
$Response.InputFields | Select-Object name, value
```

We get:

```
name       value
----       -----
q          how many feet in a mile
go         Search
qs         ds
form       QBRE
submit     Sign in
From Value 1
To Value   5280
```

**Comment by trollyanov** [comment]
name   value
----   -----
q      how many feet in a mile
go     Поиск
qs     ds
form   QBRE
submit Войти

**Comment by sdwheeler** [comment]
This is a language issue. The query result is different in other languages.
