### ISSUE TITLE
Is WINGET a supported method of installing PowerShell

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/PowerShell-Docs#7894]
This page describes how to install PowerShell and provides details about how to install PowerShell using Winget. Later in the document, it states that all the methods in this document are supported by Microsoft. 

Is winget fully supported, given it is only in preview and is a ways off being released?  :-)

Can we either improve the discussion of support in the winget section or indicate later that Winget is _not_ supported. 
Or do both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by AltitudeApps** [comment]
Yeah, the callout should say something like

> - Windows Package Manager and the winget tool are not installed by default in Windows 10.
> - Windows Package Manager and the winget tool are in public preview and may be substantially modified before they are generally available.
> - You may join the preview program by following the instructions on these pages:
> - https://github.com/microsoft/winget-cli#microsoft-store-recommended
> - https://docs.microsoft.com/en-us/windows/package-manager/winget/

(The information in the readme.md seems to be more up to date.)

The same concern applies the the MSIX package.  The "note:" callout says that it is unsupported, but that is almost immediately contradicted by the "Installation Support" section, which states, _"Microsoft supports the installation methods in this document. ..."_

The WinGet and MSIX sections might be better off together, in a section titled "Installation methods in preview (unsupported)"

**Comment by sdwheeler** [comment]
So there are two things to support here: the installation method and the installed instance of PowerShell. 

The winget installation method is still in preview, but the resulting installation should work without issue. The only difference is the location where PowerShell gets installed.

The MSIX installation methods via the Microsoft Store is supported. The installation of the MSIX package from GitHub is not fully supported. I don't remember the details but the Store installs the package slightly differently. Also, after installation, the instance of PowerShell has certain limitations.

We can be clearer about all of these caveats.
