### ISSUE TITLE
$PROFILE variable is pointing to the wrong location.

### ISSUE THREAD

**Issue by Luca715** [MicrosoftDocs/PowerShell-Docs#7897]
I am getting an error when starting powershell saying that the profile cannot be loaded because of the execution policy. The profile being loaded by powershell is stored in onedrive rather than the default location on the computer. Is there a way to reset how the $PROFILE variable is set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e5abcb-b1a4-ea80-a4a9-41beaf018fae
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about Profiles - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by AltitudeApps** [comment]
You have posted this to the repository dealing with the documentation for PowerShell.

You will have better luck posting to a discussion board, like https://github.com/PowerShell/PowerShell/discussions  or the PowerShell subreddit.   I think there is a PowerShell Discord server, too.

**Comment by sdwheeler** [comment]
There are known issues with having your Documents folder redirected to OneDrive. PowerShell does not work properly. You must remove your Documents folder from OneDrive sync and restore the contents back to the original location.
