### ISSUE TITLE
pwsh -file change

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#7904]
# Summary of the new document or enhancement

- List of articles that need to be updated: https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_pwsh
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/15859
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

On unix systems, `pwsh -file` will accept any arbitrary file and try to execute as a script.  This is to support shebang semantics like:

```powershell
#!/bin/pwsh
1+1
```

Where this file can be called `2` without any extension as long as it has the executable bit set.  However, on Windows where shebang is not supported, we want to have consistent behavior with WinPS so that only scripts ending with .ps1 is supported when using `-File` otherwise an error is returned.

**Comment by sdwheeler** [comment]
@SteveL-MSFT When was shebang support added?
