### ISSUE TITLE
Add a Windows mode to $PSNativeCommandArgumentPassing that allows some commands to use legacy argument passing

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#7907]
# Summary of the new document or enhancement

- List of articles that need to be updated:
  - reference/docs-conceptual/learn/experimental-features.md
  - reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/15408
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

- Update experimental article
- Add $PSNativeCommandArgumentPassing to about_Automatic_Variables
  - Note that this is experimental
  - Brief description and link to experimental article

**Comment by sdwheeler** [comment]
Closed by #7921

**Comment by ringerc** [comment]
Please consider updating this to explicitly note that `Start-Process -ArgumentList` is *not* affected by this change, and retains "Legacy" behaviour
