### ISSUE TITLE
Possible Mistake: Arrays appear to be "Object[]" when created, not "PSObject[]"

### ISSUE THREAD

**Issue by Alex-ABPerson** [MicrosoftDocs/PowerShell-Docs#7913]
## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7.1#array-types
- Is the issue specific to a platform: No

## Description of the issue

On the linked page, it says that new arrays are of type `PSObject[]`, but calling `GetType` on a newly created array type shows that it's `object[]`, not `PSObject[]`. Either PowerShell has some mega hack going on so it appears to be an `object[]` when it's not, or it's actually an `object[]` and this is a mistake.

It also states that everything inherits from `PSObject`, which as far I'm aware is definitely not true, so I assume both of these are meant to say `Object`, not `PSObject`.

**Comment by Alex-ABPerson** [comment]
If this is indeed a mistake I'll happily PR the change myself

**Comment by chasewilson** [comment]
This is actually correct. When PowerShell creats and object, it always starts out as a `PSObject` and is adjusted from there. you can see a [brief sentence in the language spec](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-04?view=powershell-7.1#46-type-extension-and-adaptation) to confirm it as well.

However, we always appreciate contributions and if you find anything in the docs, feel free to create another issue and submit a PR :)

**Comment by Alex-ABPerson** [comment]
And PowerShell really customizes the `GetType` to the point that _even the element type_ on an array appears to be `object` when it's really `PSObject`? I can understand the array itself being wrapped in a `PSObject`, I'm just surprised that the array is really a `PSObject[]`, and not an `object[]`, and it manages to hide that in `GetType`.

**Comment by Alex-ABPerson** [comment]
@chasewilson Another thing I observe is if I create a new `PSObject[]` via the static method `new`:

```powershell
$arr = [PSObject[]]::new(3)
```
And I call `GetType` on that, _then_ it says `PSObject[]`. That means it can't just be the `GetType` call hiding the `PSObject` away, because if _was_ a custom `GetType` hiding it, that would show as `object[]` as well.

These would have to match for them to be the same:
```powershell
$objArr = @(1, 2, 3)
$objArr.GetType()

$psArr = [PSObject[]]::new(3)
$psArr.GetType()
```
But they don't.

Are you **absolutely certain** the array is _actually_ a `PSObject[]` and not an `object[]`? 

I'm sure the array object itself is "wrapped" in a `PSObject`, and the `GetType` call on that wrapping `PSObject` passes through to the array. But on the actual array object _within that `PSObject`_, the element type _must be_ `object`. And there's no reason why it can't be, as `PSObject` inherits from `object`, so putting a `PSObject` into the array (which I assume is what really goes in every time you put something in) is still going to work.
