### ISSUE TITLE
Tittles of this section's pages

### ISSUE THREAD

**Issue by darugeri** [MicrosoftDocs/PowerShell-Docs#7927]
Hello,

Just as a question: Is it by design that all the page titles on this section are prefixed with "about_"? Seems a little odd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01044771-2f97-2a81-2e6c-c842cdd2ddc7
* Version Independent ID: f83b7011-1b36-45aa-93ff-e1b03536378d
* Content: [about CommonParameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Yes. The articles are available from Get-Help on the PowerShell command line.

**Comment by darugeri** [comment]
OK then. Thank you for the clarification. :)
