### ISSUE TITLE
.Count Returns Blank is only 1 them is found

### ISSUE THREAD

**Issue by MWPatterson2000** [MicrosoftDocs/PowerShell-Docs#7930]
When counting objects, if only 1 item is found it returns nothing, if empty it returns 0, 2 or more it returns the correct value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495ca3d5-75cc-ebe3-d894-66ef8fd53da1
* Version Independent ID: bbf70122-605e-d627-556f-5f368b34378b
* Content: [Measure-Object (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/measure-object?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Measure-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Measure-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by doctordns** [comment]
Not sure what you mean. Here I get a count, like this:

```powershell-console
PS C:\Foo> $s2 = @("have a ", "nice day")
PS C:\Foo> $s1 = 'have a nice day'
PS C:\Foo> $s2 = @("have a ", "nice day")
PS C:\Foo> $s1 | measure

Count             : 1
Average           :
Sum               :
Maximum           :
Minimum           :
StandardDeviation :
Property          :


PS C:\Foo> $s2 | measure

Count             : 2
Average           :
Sum               :
Maximum           :
Minimum           :
StandardDeviation :
Property          :
```

**Comment by chasewilson** [comment]
I can't repro the behavior either. I'll be closing this for now but will be monitoring for response. If you can give a specific example and the version of PowerShell you are using that would be helpful.

**Comment by sdwheeler** [comment]
```
PS> "Hello world".count
1
PS> "Hello world".Length
11
PS> (11).count
1
PS> (11).length
1
PS> "Hello world" | measure

Count             : 1
Average           :
Sum               :
Maximum           :
Minimum           :
StandardDeviation :
Property          :


PS> "Hello", "world" | measure

Count             : 2
Average           :
Sum               :
Maximum           :
Minimum           :
StandardDeviation :
Property          :
```

**Comment by MWPatterson2000** [comment]
Sorry did not clarify this enough.  I a reading into an array, then trying to get the count on the items in the array.

PS C:\Temp> $tempAR = Get-MsolUser -all | Where-Object {$_.UserType -ne "Member"} | Select-Object UserPrincipalName, UserType, WhenCreated
PS C:\Temp> $tempAR.Count
PS C:\Temp> $tempAR

UserPrincipalName                                     UserType WhenCreated
-----------------                                     -------- -----------
test_mwpatterson.com#EXT#@M365x767726.onmicrosoft.com    Guest 2021-06-24 20:00:15


PS C:\Temp> ($tempAR).count
PS C:\Temp>

If there are more than 2 or 0 it works, with only 1 it gives me blank

**Comment by sdwheeler** [comment]
Ok, that is a quirk of the `Get-MsolUser` cmdlet.
