### ISSUE TITLE
Why not use .Net calls instead of wevtutil.exe?

### ISSUE THREAD

**Issue by dennisl68-castra** [MicrosoftDocs/PowerShell-Docs#7932]
In the section `Where are DSC event logs?`
.Net calls are built into PoSH/PWSH and supports object handling.
Ouput and input to a commandline tool needs special formating and parsing

So why not replace 
`wevtutil.exe set-log "Microsoft-Windows-Dsc/Analytic" /q:true /e:true`

with
~~~~
$LogName = 'Microsoft-Windows-Dsc/Analytic'
$Log = New-Object System.Diagnostics.Eventing.Reader.EventLogConfiguration $LogName
$Log.IsEnabled = $true
$Log.SaveChanges()
~~~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e703ce51-7ae4-995b-247a-da22f75cfd2b
* Version Independent ID: 015f572d-bfde-b3b8-790d-33f596198122
* Content: [Troubleshooting DSC - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/dsc/troubleshooting/troubleshooting?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/dsc/troubleshooting/troubleshooting.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dsc/troubleshooting/troubleshooting.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @mgreenegit
* Microsoft Alias: **migreene**

**Comment by chasewilson** [comment]
I'm actually ok with this change since it appears that it's `wevtutil` doesn't appear to be supported or at least won't be in the future. @dennisl68-castra, would you be up for submitting a PR to fix this? If not, I can go ahead and take it. 

I do want to make sure this does what the section intends. @mgreenegit, do you know if the .NET method will accomplish the same thing as `wevtutil`?

**Comment by dennisl68-castra** [comment]
I'm in the middle of some other things right now.

I've used those line for enabling other logs on Windows, but I can't say if they do exactly the same thing as wevtutil.exe /q:true /e:true

**Comment by chasewilson** [comment]
@sdwheeler pointed out that the `wevtutil` isn't deprecated and our docs link out to an old version so I'll be updating the link to point to a new version of the docs but will also be adding your method pending confirmation it doesn't miss anything from the sections intent. 

No worries about not being able to take it on right now. We appreciate you catching this and taking your time to submit the issue. The future PR will link to this issue if you have any more feedback on the issue.
