### ISSUE TITLE
Documentation for parameters includes -Scope for version 5.1

### ISSUE THREAD

**Issue by TonyCurtisLives** [MicrosoftDocs/PowerShell-Docs#7933]
The documentation for version 5.1 includes the -Scope parameter. I have version 5.1 installed and receive this error when I include the -Scope parameter:

> Update-Module : A parameter cannot be found that matches parameter name 'Scope'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd534e69-b7d9-8562-c224-b6bb4a200b21
* Version Independent ID: da21d631-936e-8754-a4ba-6932276efd8f
* Content: [Update-Module (PowerShellGet) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-5.1)
* Content Source: [reference/5.1/PowershellGet/Update-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PowershellGet/Update-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by ThomasNieto** [comment]
Check to see which version of PowerShellGet you have. The inbox version is very old and doesn't have that parameter. Update PowerShellGet first and then reload PowerShell.

**Comment by TonyCurtisLives** [comment]
That was it. Thank you!
