### ISSUE TITLE
Error processing User drive in JEA session

### ISSUE THREAD

**Issue by aaronsssya** [MicrosoftDocs/PowerShell-Docs#7939]
# Documentation Issue
I reference to https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/whats-new/jea-improvements?view=powershell-5.1#constrained-file-copy-tofrom-jea-endpoints for MountUserDrive enabling.

## Context of the issue
I got the following error
```sh
Enter-PSSession : Processing the User drive threw an error Access to the path 'Microsoft\Windows\PowerShell\DriveRoots\XXXXXX' is denied..
At line:1 char:1
+ Enter-PSSession -ComputerName r3-XXXX -ConfigurationName JEAXXXXXX  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Enter-PSSession], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation

```

**Cmdlet reference & about_ topics**
- [X] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win):

**Comment by sdwheeler** [comment]
@aaronsssya Are you saying that there is an error in the documentation? If so, can you be more specific about what is wrong?

It looks like there is a problem with permissions for the user.  Has the user been granted access in the configuration? If you are looking for support, try posting your problem in a community support forum. 
For a list of community forums see: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by sdwheeler** [comment]
For more complete JEA documentation, see https://docs.microsoft.com/powershell/scripting/learn/remoting/jea/overview

**Comment by sdwheeler** [comment]
OK, that makes sense. RunAsVirtualAccountGroups and MountUserDrive are mutually exclusive. The drive feature does not work for the virtual accounts.
