### ISSUE TITLE
4th example - missing quotes

### ISSUE THREAD

**Issue by RandyInMarin** [MicrosoftDocs/PowerShell-Docs#7944]
[Enter feedback here]
Hi, the 4th example is missing the quotes in one line.  

$Example_code = '(Get-Help $Cmdlet_name).examples.example[($Example_number-1)].code'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33dc0ec6-bd45-4a71-cae0-fbd6164806a3
* Version Independent ID: 9d592d60-e29c-84e6-2e43-078e2a69fb97
* Content: [Invoke-Expression (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/Invoke-Expression.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Invoke-Expression.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@RandyInMarin I think you misunderstand the example. The command `(Get-Help $Cmdlet_name).examples.example[($Example_number-1)].code` is not the expression being invoked. That is getting the code from the first example in the help for `Get-EventLog` and storing it in the variable. Then, `Invoke-Expression` is running that example code.

@chasewilson We need to change the example to use a different cmdlet. `Get-EventLog` is only available in PS 5.1.

**Comment by RandyInMarin** [comment]
Okay, I think I see what you mean.  I should be getting just the command.  I get the command and the result.  This is what I see for `(Get-Help $Cmdlet_name).examples.example[($Example_number-1)].code`.  It has more than code.  $Example_code value I get is below.  

Get-EventLog -List

Max(K)   Retain   OverflowAction      Entries  Log
------   ------   --------------      -------  ---
15,168        0   OverwriteAsNeeded   20,792   Application
15,168        0   OverwriteAsNeeded   12,559   System
15,360        0   OverwriteAsNeeded   11,173   Windows PowerShell

**Comment by sdwheeler** [comment]
@RandyInMarin Correct. And that is another reason that we need to change Example 4. Chase has already fixed this in PR #7946. It will be live on this site in a few hours.
