### ISSUE TITLE
Confused naming

### ISSUE THREAD

**Issue by mamoorkhan** [MicrosoftDocs/PowerShell-Docs#7967]
Having the the name of the function to Export as Export is quite confusing here.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776b63c0-8820-a3fb-ec14-4efcc84c54bf
* Version Independent ID: 136bc0a1-d00b-560b-dd96-ecc359583c9e
* Content: [Export-ModuleMember (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/export-modulemember?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/Export-ModuleMember.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/Export-ModuleMember.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
@mamoorkhan thanks for the feedback here. We're removing the example after taking a look. The example is kind of confusing and doens't really highlight the cmdlet as reference material. 

Thanks again and have a good one!
