### ISSUE TITLE
Suggested Profile documentation change

### ISSUE THREAD

**Issue by swiftgeek75** [MicrosoftDocs/PowerShell-Docs#7984]
The Profile Files section isn't accurate. Specifically, the profile script locations for the current user aren't based on $home\Documents, but rather on ([Environment]::GetFolderPath("MyDocuments")). Documents folder isn't guaranteed to be in $home. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8685909d-23f6-4372-e6ff-1a418928d737
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about Profiles - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
I believe this is the default set up for a basic profile and user home directory. While you can cusomize it this is the standard for a user profile in Windows. 

I'm not sure I see a value in documenting edge cases here? 

Feel free to respond if you disagree. @sdwheeler, what's your take on it?

**Comment by swiftgeek75** [comment]
It's not an edge case if it covers all the cases.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
