### ISSUE TITLE
Potential Error in documentation for windows user Installed modules PSModulePath description

### ISSUE THREAD

**Issue by rennerom** [MicrosoftDocs/PowerShell-Docs#7988]
Documenation states "On Windows, the location of the user-specific CurrentUser scope is the `$HOME\Documents\PowerShell\Modules folder`

I think its supposed to be `$HOME\Documents\WindowsPowerShell\Modules`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6025398e-8980-f6c5-898c-20a039a00f7e
* Version Independent ID: 0e9c150c-ad17-86a9-f0e1-68c90cd93ead
* Content: [about PSModulePath - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
You were looking at the documentation for PowerShell v7.1. That is the correct path. 

If you change the version of the doc to PowerShell 5.1 the correct path `$HOME\Documents\WindowsPowerShell\Modules` is listed.

See https://docs.microsoft.com/powershell/scripting/how-to-use-docs

**Comment by rennerom** [comment]
Whoops, I could have sworn I made the issue on the 5.1 page. I was bouncing
back and forth between 5.1 and 7.1 to compare both, but I suppose I may
have been mistaken.

Though it looks like something was updated in 5.1? Hopefully my ticket
didn’t go to waste?

Thanks either way!

-Max

**Comment by sdwheeler** [comment]
@rennerom Yeah, I thought the 5.1 doc was correct but it looks like the 7.x content was synced to it in error. I fixed that. Thanks for the report.
