### ISSUE TITLE
Path to profile script is wrong

### ISSUE THREAD

**Issue by alzafacon** [MicrosoftDocs/PowerShell-Docs#8015]
Path is given as ___/PowerShell/___ but it should be ___/WindowsPowerShell/___

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e5abcb-b1a4-ea80-a4a9-41beaf018fae
* Version Independent ID: 3024e05f-28dd-4da5-fb1e-e62f99f7b253
* Content: [about Profiles - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Profiles.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Profiles.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
Hey @alzafacon. Thanks for the feedback here. The version you are referencing is for PowerShell 7.1 and referred to as PowerShell. Windows PowerShell is PowerShell 5.1 which would be [this doc here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1). 

I'm going to close this issue for now but feel free to reach out with any questions or concerns.
