### ISSUE TITLE
https://msdn.microsoft.com/198c1c94-2a06-457e-93ce-c0d910618e47 is a dead link

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/PowerShell-Docs#8032]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec47953-82d4-437a-1b93-27039eeac88e
* Version Independent ID: 032534d5-b1ee-93d7-c951-6b57e26a069f
* Content: [RunSpace09 Code Sample - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/prog-guide/runspace09-code-sample?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/prog-guide/runspace09-code-sample.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/prog-guide/runspace09-code-sample.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Unfortunately, that doc has been lost forever. I will just have to remove the reference to it.
