### ISSUE TITLE
Additional information needed for advance firewalls

### ISSUE THREAD

**Issue by penncomputers** [MicrosoftDocs/PowerShell-Docs#8033]
In addition to what this page shows for domains to trust connections with. It appears when running update-module * the module also connects to an IP belonging to cloudflarenet. I have observed this connection on IP: 104.16.248.249 network: 104.16.0.0/12 via HTTPS when using this command.

I don't see any information on this on the page provided and update-module is being blocked by our firewall resulting with the following error:

```
update-module
Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again 
later.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2038 char:13
+             Get-PSGalleryApiAvailability -Repository (Get-SourceName  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOper 
   ationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f89457b-839e-d865-be6e-5bc1690a0ce0
* Version Independent ID: 9ff93024-adda-659a-222e-260c1e346d79
* Content: [Troubleshooting cmdlets - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/getting-support/troubleshooting-cmdlets?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by sdwheeler** [comment]
There have been service outages for the PowerShell Gallery lately, so the error you received could have been related to one of those incidents.

As for the Cloudflare address. We do not use Cloudflare. That must be caused by a configuration that is unique to your environment.
