### ISSUE TITLE
Set-Clipboard, missing example.

### ISSUE THREAD

**Issue by francisco-lafe** [MicrosoftDocs/PowerShell-Docs#8044]
¿Can we get an example for setting the clipboard from a pipeline of an object? 
Say, for example, that I want the public IP address of my device in my clipboard, using:

`Invoke-WebRequest ifconfig.me/ip | Select-Object content`

What would be the next step to convert "Content" into a string and send it into Set-Clipboard?
I can't figure it out.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40f6939-affe-9e5f-8503-52ec5aa7b98d
* Version Independent ID: 0efcc112-2660-68d4-30ea-b6c633baa2a2
* Content: [Set-Clipboard (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-clipboard?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Set-Clipboard.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Set-Clipboard.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by francisco-lafe** [comment]
I managed to make it work but I don't know if it's the correct approach, as it's not a OneLiner:
`$ip = (Invoke-WebRequest ifconfig.me/ip | Select-Object content); $ip.Content|Set-Clipboard`

**Comment by sdwheeler** [comment]
The issue is not with `Set-Clipboard` but with how the data is deserialized from `Invoke-WebRequest`.

This might work for a one-liner: `Invoke-WebRequest ifconfig.me/ip).Content | Set-Clipboard`

**Comment by francisco-lafe** [comment]
I swear I've read PS 101, and I've never seen that you can run a ( ) wrapped command and just get the property you want.  
It should be somewhere on there. 
Thanks Sean, appreciated, this will solve a lot of my headaches haha.

**Comment by sdwheeler** [comment]
@francisco-lafe See also, https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_operators#special-operators
