### ISSUE TITLE
Document edit request: There is no link to GitHub for Powershell7 in the Japanese documentation, so I can't get to the installation package download page.

### ISSUE THREAD

**Issue by tsumita2929** [MicrosoftDocs/PowerShell-Docs#8058]
The English document has links to `latest` and `preview`, but the Japanese document doesn't, so I can't get to the GitHub page for Powershell7.

# [Japanese Document](https://docs.microsoft.com/ja-jp/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)
Windows に PowerShell をインストールするには、[最新][]のインストール パッケージを GitHub からダウンロードします。 最新の[プレビュー][] バージョンも確認できます。 リリース ページの [Assets] セクションまで下にスクロールします。 [Assets] セクションは折りたたまれている場合があります。その場合は、クリックして展開する必要があります。

# [English Document](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)
To install PowerShell on Windows, download the [latest](https://aka.ms/powershell-release?tag=stable] install package from GitHub. You can also find the latest [preview](https://aka.ms/powershell-release?tag=preview) version. Scroll down to the Assets section of the Release page. The Assets section may be collapsed, so you may need to click to expand it.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Windows への PowerShell のインストール - PowerShell](https://docs.microsoft.com/ja-jp/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/powerShell-Docs.ja-jp/blob/live/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@tsumita2929 Thank you for reporting the problem. We are working with our translation team to fix the problem.

There are working links further down the page under ZIP パッケージのインストール

**Comment by sdwheeler** [comment]
The links are now fixed.
