### ISSUE TITLE
Powershell command should have link to a "common parameters" page

### ISSUE THREAD

**Issue by kwalker360** [MicrosoftDocs/PowerShell-Docs#8064]
The command documented on this page includes "<Common Parameters>" in its syntax. I know there is a set of options that are supported by all powershell commands, but I don't use powershell often enough to have that page bookmarked or virtually memorized. Please add a link to the page for each command that takes me to the common parameters page. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18fcc4de-250d-4fb1-0a07-59c0b93d50f7
* Version Independent ID: 2e784abd-da8a-893a-d6f6-372fde7102dd
* Content: [Resolve-Path (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/resolve-path?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Resolve-Path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Resolve-Path.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
Hey @kwalker360 thanks for the feedback here. 

This is a duplicate issue and can find more information in [the original issue here](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4484). 

It is being worked on however and we're with you on hoping it gets resolved soon. 

I'm sorry about the confusion. I'll be closing this issue for now but feel free to respond if you have any more questions. 

Thanks and have a good one!

**Comment by kwalker360** [comment]
Great--thanks!
