### ISSUE TITLE
Invoke-RestMethod & Invoke-WebRequest: Add -HttpVersion parameter

### ISSUE THREAD

**Issue by hayhay27** [MicrosoftDocs/PowerShell-Docs#8065]
# Summary of the new document or enhancement

- List of articles that need to be updated:
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo:
https://github.com/PowerShell/PowerShell/pull/15853
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:
https://github.com/PowerShell/PowerShell/issues/12641

## Description of what changed

Added new parameter `-HttpVersion` that accepts http versions `1.0`, `1.1`, `2.0`, `3.0`

**Comment by sergeevabc** [comment]
Err… I need HTTP/2 in Powershell 7.2.* for Windows 7. Backport, if possible.
