### ISSUE TITLE
Script Throws Error

### ISSUE THREAD

**Issue by aspnerd** [MicrosoftDocs/PowerShell-Docs#8068]
The example script as shown does not execute. The error received is below:

```
`At line:15 char:1
+ workflow Test-Workflow
+ ~~~~~~~~~~~~~~~~~~~~~~
The function or workflow 'Test-Workflow' cannot be redefined.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : FunctionRedefinitionNotAllowed`
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f22b6b-0a8b-6621-400a-c35c61e106fd
* Version Independent ID: 87cc1dfa-5683-06f4-bb20-5e126e8fe2a7
* Content: [about Foreach-Parallel - PowerShell](https://docs.microsoft.com/en-us/powershell/module/psworkflow/about/about_foreach-parallel?view=powershell-5.1)
* Content Source: [reference/5.1/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/PSWorkflow/About/about_Foreach-Parallel.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@aspnerd I am not able to reproduce the error you received. The error must be specific to your environment. 

Also note that the example contains two different workflows. They happen to be use the same name. So if you are copying and pasting the code the `Test-Workflow` function is being defined and then redefined. The example is show two different ways to do parallel execution.

**Comment by aspnerd** [comment]
If they are two different examples, you should have them displayed as such. Not as one.

________________________
Jeff Taylor
***@***.******@***.***>
https://blog.reviewmydb.com

**Comment by chasewilson** [comment]
Hey @aspnerd, Sean has already split the example  after your original comment. You should see the update later today. 

Thanks for your feedback here and have a good one!

**Comment by aspnerd** [comment]
Great! Thanks!

________________________
Jeff Taylor
***@***.******@***.***>
https://blog.reviewmydb.com
