### ISSUE TITLE
Title includes underscores and section has about_ prefix

### ISSUE THREAD

**Issue by biltongza** [MicrosoftDocs/PowerShell-Docs#8069]
Looks a bit unprofessional including underscores in the title of the docs. Looks to be an issue with all of the docs in this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7ed88f-e000-f59b-b65b-7670c2e76b15
* Version Independent ID: 1c1d6e04-a3f5-d174-b6c6-68b9cdfdd6c0
* Content: [about Windows PowerShell Compatibility - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
This is by design. The same markdown source is used to build the web pages and the content for the console-based help system. The topic names are used by `Get-Help`.
