### ISSUE TITLE
Fix https://aka.ms/psverbs link that should redirect to PowerShell docs page

### ISSUE THREAD

**Issue by ByteJuggler** [MicrosoftDocs/PowerShell-Docs#8081]
Maybe nothing but I was going through a course which referenced opening https://aka.ms/psverbs -- this link resulted in a 404, but pointed to an older version of the below page.  So: It would be more seamless and better for continuity if such shortened URL's were kept working, e.g: Get https://aka.ms/psverbs to redirect to the below page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edfbab86-9144-1866-2765-938a5cc68ed7
* Version Independent ID: b4035200-8b55-c70c-7a29-4de085c87e1c
* Content: [Approved Verbs for PowerShell Commands - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment]
Thanks for reporting this. The Link was not owned by the PowerShell team and the owner has since left Microsoft. I was able to take ownership of it and fix it.
