### ISSUE TITLE
Mistake in "Example 2"

### ISSUE THREAD

**Issue by francisco-lafe** [MicrosoftDocs/PowerShell-Docs#8086]
Hello, in example two it reads:

```PowerShell
$IE1 = New-Object -COMObject InternetExplorer.Application -Property @{Navigate2="www.microsoft.com"; Visible = $True}
^^^^^^
# The following command gets the same results as the example above.
$IE2 = New-Object -COMObject InternetExplorer.Application`
$IE2.Navigate2("www.microsoft.com")`
$IE2.Visible = $True`
```
basically, IE2 and IE1 are the same thing or it's just a mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab59cd58-2187-417f-da42-7a58a525ff96
* Version Independent ID: 450c270f-b379-d576-bc73-e9f19d0ebb78
* Content: [New-Object (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-object?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Utility/New-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/New-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by doctordns** [comment]
$IE1 and $IE2 are, in effect the same.  they are two different ways to navigate to www.microsoft.com inside IE and make the window visible.

**Comment by francisco-lafe** [comment]
I see that I am a moron and didn't see the "New-Object" following the first $IE2
