### ISSUE TITLE
Example code error

### ISSUE THREAD

**Issue by jamacoe** [MicrosoftDocs/PowerShell-Docs#8101]
**In the last code example on this page, the 2nd code line from bottom (**ConvertTo-SecureString -AsPlainText -Force)**) is superfluous (as well as erroneous, because it ends with an unopened bracket).**

```
function Get-AllSQLDatabases {
    param(
        $SQLServer,
        [ValidateNotNull()]
        [System.Management.Automation.PSCredential]
        [System.Management.Automation.Credential()]
        $Credential = [System.Management.Automation.PSCredential]::Empty
    )

        $UserName = $Credential.UserName
        $Password = $Credential.GetNetworkCredential().Password

        $splat = @{
            UserName = $UserName
            Password = $Password
            ServerInstance = 'SQLServer'
            Query = "Select * from Sys.Databases"
        }

        Invoke-Sqlcmd @splat
}

$credSplat = @{
    TypeName = 'System.Management.Automation.PSCredential'
    ArgumentList = 'duffney',('P@ssw0rd' | ConvertTo-SecureString -AsPlainText -Force)
}
$Credential= New-Object @credSplat
ConvertTo-SecureString -AsPlainText -Force)

Get-AllSQLDatabases -SQLServer SQL01 -Credential $Credential
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5946302-744e-e37e-ab38-f9041bf393ce
* Version Independent ID: 3ae395c7-caa8-4655-a8a1-23dbda980ca6
* Content: [Add Credential support to PowerShell functions - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/add-credentials-to-powershell-functions?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/deep-dives/add-credentials-to-powershell-functions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/add-credentials-to-powershell-functions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
I see what happened in the edit. A fix is in the works.
