### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by jamac123** [MicrosoftDocs/PowerShell-Docs#8116]
In about_Parameters the section on Accepts Multiple Values it uses the command 
PS C:\test> Get-Service -servicename winrm, netlogon
and that works fine on my computer. But both in the documentation on this page for Get-Service as well as using 
PS C:\test> Get-Help Get-Service
on my computer, there is no -servicename parameter.  If it exists, why is it not documented? I see in the documentation [<CommonParameters>] but cannot find anywhere what they would be -- is -servicename one of the Common Parameters? (It seems a specific name for this command and not common for other commands, so how common can it be? Or is Common mean that for the 3 different syntax statements that are given? But wait, [-ComputerName <string[]>] is common for all 3 syntax statements.

Do you see the confusion I get from trying to learn from your documentation? Poor documentation only increases the aggravation of learning a new language. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef0cbc89-48a3-5126-998e-ccaf21ce1404
* Version Independent ID: 52b4131a-0ccb-3942-1b13-7b57faf329d5
* Content: [Get-Service (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-service?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@jamac123 It is documented. **ServiceName** is an alias for the `-Name` parameter.

```
PS> Get-Help Get-Service -Parameter Name

-Name <string[]>

    Required?                    false
    Position?                    0
    Accept pipeline input?       true (ByValue, ByPropertyName)
    Parameter set name           Default
    Aliases                      ServiceName
    Dynamic?                     false
    Accept wildcard characters?  false
```

**Comment by sdwheeler** [comment]
I updated about_Parameters to use the `-Name` instead of the alias.

**Comment by jamac123** [comment]
Thanks, Sean. I'm new, so I didn't think about alias.and that wasn't shown
in the Help. I'm learning, just so much to learn :-)
