### ISSUE TITLE
about_Quoting_Rules

### ISSUE THREAD

**Issue by 89z** [MicrosoftDocs/PowerShell-Docs#8122]
This page doesnt address external commands at all.

For example, with Bash you could run a command like this no problem:

~~~sh
curl 'http://gram.com/query/?query=f5&variables={"code":"CThvvO","reel":true,"first":50,"after":""}'
~~~

but PowerShell ignores that single quotes have been used, and just goes ahead and destroys the command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db77bdfc-0c1d-0821-489a-57ec13bb475d
* Version Independent ID: 61c4ba2e-b08d-089b-74bc-70d6306523e5
* Content: [about Quoting Rules - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
@89z This article is about how PowerShell interprets quoted strings.

The information you are looking for is in the about_Parsing article: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.1#passing-arguments-to-native-commands

**Comment by 89z** [comment]
@sdwheeler nope, that doesnt work at all:

~~~
PS C:\> curl --% 'http://gram.com/query/?query=f5&variables={"code":"CThvvO","reel":true,"first":50,"after":""}'

[1/4]: 'http://gram.com/query/?query=f5&variables=code:CThvvO' --> <stdout>
--_curl_--'http://gram.com/query/?query=f5&variables=code:CThvvO'
curl: (3) URL using bad/illegal format or missing URL

[2/4]: 'http://gram.com/query/?query=f5&variables=reel:true' --> <stdout>
--_curl_--'http://gram.com/query/?query=f5&variables=reel:true'
curl: (3) URL using bad/illegal format or missing URL

[3/4]: 'http://gram.com/query/?query=f5&variables=first:50' --> <stdout>
--_curl_--'http://gram.com/query/?query=f5&variables=first:50'
curl: (3) URL using bad/illegal format or missing URL

[4/4]: 'http://gram.com/query/?query=f5&variables=after:' --> <stdout>
--_curl_--'http://gram.com/query/?query=f5&variables=after:'
curl: (3) URL using bad/illegal format or missing URL
~~~

**Comment by sdwheeler** [comment]
Keep reading. There is a section that talks about quotes in the argument. You have to escape them.

Try this.

```
curl 'http://gram.com/query/?query=f5&variables={\"code\":\"CThvvO\",\"reel\":true,\"first\":50,\"after\":\"\"}'
```

It's not pretty but it should work. Note that this is a common complaint about how PowerShell handles parameters for native (external) commands. There is a new experimental feature in PowerShell 7.2 that is aimed at fixing this. You can read more about it at: https://docs.microsoft.com/powershell/scripting/learn/experimental-features?view=powershell-7.2#psnativecommandargumentpassing

**Comment by sdwheeler** [comment]
FYI - I notice that `gram.com` is not a valid site anymore. It redirects to `brandforce.com`.

**Comment by 89z** [comment]
@sdwheeler please dont suggest commands unless youve actually tested them:

~~~
PS C:\> curl 'http://gram.com/query/?query=f5&variables={\"code\":\"CThvvO\",\"reel\":true,\"first\":50,\"after\":\"\"}'

[1/4]: http://gram.com/query/?query=f5&variables="code":"CThvvO" --> <stdout>
--_curl_--http://gram.com/query/?query=f5&variables="code":"CThvvO"

[2/4]: http://gram.com/query/?query=f5&variables="reel":true --> <stdout>
--_curl_--http://gram.com/query/?query=f5&variables="reel":true

[3/4]: http://gram.com/query/?query=f5&variables="first":50 --> <stdout>
--_curl_--http://gram.com/query/?query=f5&variables="first":50

[4/4]: http://gram.com/query/?query=f5&variables="after":"" --> <stdout>
--_curl_--http://gram.com/query/?query=f5&variables="after":""
~~~

**Comment by 89z** [comment]
Also, why do I need to add blackslash escapes ON TOP OF single quoting? I thought the whole point of single quotes was "anything between the single quotes should be treated literally". PowerShell completely ignores that idea and does... something else.

**Comment by sdwheeler** [comment]
As I said, this is a common pain point that the PowerShell team is trying to address. They are testing the fix in the experimental feature.

I verified that the quoted and escaped URL is being passed to the external command correctly. However, I don't understand what your curl command is doing with the URL. It doesn't appear to be using the variables in the query string correctly.

**Comment by 89z** [comment]
> I verified that the quoted and escaped URL is being passed to the external command correctly.

@sdwheeler I dont think you know what youre talking about. I did my own testing, by starting a server and feeding it your command. Your command gets split into 4 pieces, because the code youve provided isnt valid. Heres the resultant 4 requests, directly printed from the local server:

~~~
GET /query/?query=f5&variables="code":"CThvvO" HTTP/1.1
Host: localhost:50342
Accept: */*
User-Agent: curl/7.78.0

GET /query/?query=f5&variables="reel":true HTTP/1.1
Host: localhost:50342
Accept: */*
User-Agent: curl/7.78.0

GET /query/?query=f5&variables="first":50 HTTP/1.1
Host: localhost:50342
Accept: */*
User-Agent: curl/7.78.0

GET /query/?query=f5&variables="after":"" HTTP/1.1
Host: localhost:50342
Accept: */*
User-Agent: curl/7.78.0
~~~

Again, please dont post commands unless youve tested them yourself first, as its just wasting my time.

**Comment by sdwheeler** [comment]
@89z - I am sorry you feel I am wasting your time. I am trying to help. Please tone down your responses.

I have tested your URL with PowerShell's `Invoke-WebRequest` cmdlet. It works as written without escaping because it is not an external command.

```
PS C:\temp> Invoke-WebRequest 'http://gram.com/query/?query=f5&variables={"code":"CThvvO","reel":true,"first":50,"after":""}' -Verbose
VERBOSE: GET http://gram.com/query/?query=f5&variables={"code":"CThvvO","reel":true,"first":50,"after":""} with 0-byte payload
VERBOSE: received -byte response of content type text/html

StatusCode        : 200
StatusDescription : OK
Content           :   <!doctype html>
                    <html>

                        <head>

                                <meta charset="utf-8">
                                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                                <meta name="viewport" content="width=device-width, initial-scale=1">
                                <me…
RawContent        : HTTP/1.1 200 OK
                    Date: Wed, 22 Sep 2021 15:37:59 GMT
                    Server: Apache/2.4.18
                    Server: (Ubuntu)
                    X-Frame-Options: SAMEORIGIN
                    Content-Security-Policy: frame-ancestors 'none'
                    Set-Cookie: PHPSESSID=n0e7q…
Headers           : {[Date, System.String[]], [Server, System.String[]], [X-Frame-Options, System.String[]],
                    [Content-Security-Policy, System.String[]]…}
Images            : {@{outerHTML=<img
                    src="https://files.efty.com/market/uploads/logo/9aaf316b71ec8727c651033a15c131f0.png"
                    class="img-responsive">; tagName=IMG;
                    src=https://files.efty.com/market/uploads/logo/9aaf316b71ec8727c651033a15c131f0.png;
                    class=img-responsive}, @{outerHTML=<img src="img/efty_market_themes/borgen/1.png">; tagName=IMG;
                    src=img/efty_market_themes/borgen/1.png}, @{outerHTML=<img
                    src="img/efty_market_themes/borgen/divider.png" class="img-responsive center-block" width="100%">;
                    tagName=IMG; src=img/efty_market_themes/borgen/divider.png; class=img-responsive center-block;
                    width=100%}}
InputFields       : {}
Links             : {@{outerHTML=<a href="https://www.brandforce.com"><img
                    src="https://files.efty.com/market/uploads/logo/9aaf316b71ec8727c651033a15c131f0.png"
                    class="img-responsive"></a>; tagName=A; href=https://www.brandforce.com}, @{outerHTML=<a
                    href="https://www.brandforce.com" title="www.brandforce.com">www.brandforce.com</a>; tagName=A;
                    href=https://www.brandforce.com; title=www.brandforce.com}, @{outerHTML=<a
                    href="https://www.brandforce.com/search/" title="">Domain overview</a>; tagName=A;
                    href=https://www.brandforce.com/search/; title=}, @{outerHTML=<a class="btn btn_buy" href="#"
                    id="srcoll_offer">Make an offer</a>; tagName=A; class=btn btn_buy; href=#; id=srcoll_offer}…}
RawContentLength  : 11007
RelationLink      : {}
```

I have tested the escaped URL using our testing tool to show what actually gets passed to an external command.

```
PS C:\temp> testexe -echoargs 'http://gram.com/query/?query=f5&variables={\"code\":\"CThvvO\",\"reel\":true,\"first\":50,\"after\":\"\"}'
Arg 0 is <http://gram.com/query/?query=f5&variables={"code":"CThvvO","reel":true,"first":50,"after":""}>
```

You can find the source code for this tool in the PowerShell source repo: https://github.com/PowerShell/PowerShell/tree/master/test/tools/TestExe

To me, it looks like your version of curl is breaking up the variables into 4 separate GETs.

**Comment by 89z** [comment]
I apologize, it appears part of the problem is specific to cURL. Not "my version" of cURL as you mentioned, but cURL in general. cURL interprets a URL such as this:

~~~
http://site.{one,two,three}.com
~~~

As three URLs [1]. In this case, workaround would be to URL encode the brace characters:

~~~
curl 'localhost:50342/query/?query=f5&variables=%7B"code":"CThvvO","reel":true,"first":50,"after":""%7D'
~~~

Then regarding the double quotes, those would need to be either backslash escaped, or also URL encoded. So the brace issue was due to a cURL problem (as seems no way to disable the brace splitting), but the double quote issue is still a PowerShell problem.

1. https://curl.se/docs/manpage.html

**Comment by 89z** [comment]
Actually, cURL does have an option for this [1]:

~~~
PS C:\> curl -g 'localhost:50342/query/?query=f5&variables={\"code\":\"CThvvO\",\"reel\":true,\"first\":50,\"after\":\"\"}'
GET /query/?query=f5&variables={"code":"CThvvO","reel":true,"first":50,"after":""} HTTP/1.1
Host: localhost:50342
Accept: */*
User-Agent: curl/7.78.0
~~~

So now, the only issue is the double quotes, which is a PowerShell issue.

1. https://curl.se/docs/manpage.html#-g

**Comment by sdwheeler** [comment]
We know that the double quotes are an issue. That is why the PowerShell team is testing this fix in the new version. All I can do is document the way to make it work using escape characters.

I am glad you figured out how to make cURL work for you.
