### ISSUE TITLE
about_Format.ps1xml missing <ListEntry> tag mention

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#813]
In this section

```
      The <ListControl> tag typically contains a <ListEntries> tag. The 
      <ListEntries> tag contains a <ListItems> tag. The <ListItems> tag 
      contains <ListItem> tags, which contain <PropertyName> tags. 
      The <PropertyName> tags specify the object property to be displayed at 
      the specified location in the list. If the view selection is defined 
      using a selection set, the <ListControl> tag can also contain an 
      <EntrySelectedBy> tag that contains one or more <TypeName> tags. These 
      <TypeName> tags specify the object type that the <ListControl> tag is 
      intended to display.
```

There is a `<ListEntry>` tag after `<ListEntries>` and before `<ListItems>`

**Comment by sdwheeler** [comment]
@SteveL-MSFT Can someone confirm the schema so we can get this documented properly?

**Comment by felixfbecker** [comment]
This is documented here: https://docs.microsoft.com/en-us/powershell/developer/format/listentries-element-for-listcontrol-format

Also, here's a schema in case it helps: https://github.com/PowerShell/PowerShell/blob/c6d309fc94d7a7b00b4aaffa6d8c2d097d60ca25/src/Schemas/Format.xsd

**Comment by SteveL-MSFT** [comment]
@sdwheeler I believe what @felixfbecker is pointing out is correct

**Comment by 1RedOne** [comment]
Do we need to update just the docs, or also update this within the source (updating the help for `about_Format.ps1xml`) as well?

I'm happy to tackle it, just not sure where all it needs to be fixed :beer: 👻

**Comment by SteveL-MSFT** [comment]
@1RedOne not sure which source you are referring to; can you provide a link?
