### ISSUE TITLE
Clarify and update the abstract warnings re `-Recurse` and `-Recurse` + `-Include`

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#8134]
The topic currently contains two abstract warnings:

> Because the `Recurse` parameter in `Remove-Item` has a known issue

This known issue - https://github.com/PowerShell/PowerShell/issues/8211 - is no longer one, now that the underlying WinAPI file-system function deletes items _synchronously_.

I suggest replacing this warning with one that says:

* the problem affects only _older_ Windows 10 and Windows Server versions (I'm unsure of the exact version numbers, but they're worth investigating and spelling out - personally I've found that the problem is fixed as of _at least_ Windows 10 20H2).

* the symptom is _intermittent, unpredictable_ failure to delete ("cannot be removed because it is not empty."), in case deletion of items in the subtree happens not to have completed yet.

* _retrying_ (eventually) solves the problem (assuming no unrelated problems, such as permission problems, prevent removing all content); to delete reliably, a loop solution is required (loop until removal succeeds).

---

> When it is used with the `Include` parameter, the `Recurse` parameter might not delete all subfolders or all child items. This is a known issue. As a workaround, try piping results of the `Get-ChildItem -Recurse` command to `Remove-Item`

* While the above, general `-Recurse` problem can also affect an `-Include`-modified call - as well as an `-Exclude`-modified one - piping from `Get-ChildItem` does _not_ help the problem.

* The only problem I'm aware of when combing `-Recurse` with `-Include` is the bug discussed in https://github.com/PowerShell/PowerShell/issues/16153: that is, trying to remove files selectively with `-Include` in the _current_ directory's subtree fails, but works when called from _outside_ it.

In other words: Combining `-Recurse` and `-Include` seems to work _in principle_, and I'm not sure a specific bug like that warrants mentioning in the documentation (see also below re bugs):

---

By contrast, what _is_ worth mentioning is that combining `-Recurse` with _`-Exclude`_ exhibits potentially surprising behavior with potentially destructive consequences. Since I presume that this behavior is _by design_ , a warning is called for:

Take the following example:

```powershell
Remove-Item ./sub -Recurse -Exclude *.txt
```

* The natural assumption - in analogy to `-Include *.txt` - is to assume that all files in all subdirectories are deleted, except `*.txt` files.

* What actually happens is that only `*.txt` files _directly_ located in `./sub` are exempt from deletion, whereas _all subdirectories are deleted as a whole_, even if they contain `*.txt` files.

The reason is that the `-Exclude` filter is applied to _directories too_, so that any subdirectory whose name doesn't match `*.txt` (which is unlikely) is subject to deletion.

---

This is the current list of `Remove-Item -Recurse`-related bugs I'm aware of - again, I don't think that these themselves necessarily warrant being called out in the documentation, but if they are, the warnings should be _specific_:

* https://github.com/PowerShell/PowerShell/issues/16153 (mentioned above)
* https://github.com/PowerShell/PowerShell/issues/9246
* Note that https://github.com/PowerShell/PowerShell/issues/3674 - mentioned in a [previously closed, related issue](https://github.com/PowerShell/PowerShell/issues/3674#issuecomment-299724921) - is neither a bug, nor do I believe it should be implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca41c7e-6796-5d87-0794-29fcaba7524c
* Version Independent ID: 0b18157a-a191-4733-90db-7dfceda2c99f
* Content: [Remove-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7.1&WT.mc_id=ps-gethelp)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
Ok, just to make sure I have your suggestions straight. 
- Update to remove warning about bug. 
  - Q: Is this for all versions of PowerShell in Windows where the version is high enough? 
  - Q: Do you or @sdwheeler have any suggestions on where to start to hunt down the version of Windows where the fix started? 
- Clarify the information for the recurse behavior when useing the **Exclude** Parameter? 

Thanks for bringing this out and look forward to seeing it fixed.

**Comment by mklement0** [comment]
Thanks, @chasewilson.

> Update to remove warning about bug

Specifically, I meant the `-Recurse` + `-Include` warning.

The _general_ `-Recurse` warning I suggest keeping but _rewording_, as described above.

> Q: Is this for all versions of PowerShell in Windows where the version is high enough?

Yes, my understanding is that the only thing that matters is the Windows version, not the PowerShell version. That is, the bug is also gone for Windows PowerShell for recent enough Windows versions.

> Do you or @sdwheeler have any suggestions on where to start to hunt down the version of Windows where the fix started?

Unfortunately, I have no reliable source; a hint is provided by the comments on [this SO question](https://stackoverflow.com/q/60424732/45375) - perhaps a Microsoft-internal source can help.





> Clarify the information for the recurse behavior when using the `Exclude` Parameter?

Yes, that's my suggestion, because the behavior is counterintuitive and potentially destructive.

**Comment by chasewilson** [comment]
@mklement0, follwo up question.

> - piping from Get-ChildItem does not help the problem.

do you mean that the `Get-ChildItem` command doesn't help with teh general recurse problem at all?

**Comment by mklement0** [comment]
In short: yes.

(If the `Get-ChildItem` call only outputs _files_, the recursive removal problem never arises.
If you were to pipe _directories_, the problem can arise - just as it can with `Remove-Item -Recurse -Include` alone with a pattern that matches directories.)

As stated, the only problem that is specific to the _combination_ of `-Recurse`  and `-Include` that I'm aware of is https://github.com/PowerShell/PowerShell/issues/3727. 

Other than that, I see no reason for the `Get-ChildItem` workaround (and another workaround that doesn't require `Get-ChildItem` is to simply navigate out of the target directory and target by its path) - at least as of PowerShell 7.1.4 / PowerShell Core 7.2.0-preview.9

But I don't know the history of this warning, so it's worth checking internally to make sure we're not missing anything.

**Comment by mklement0** [comment]
@chasewilson, I've created a more focused bug report at https://github.com/PowerShell/PowerShell/issues/16153 in lieu of https://github.com/PowerShell/PowerShell/issues/3727, and I've updated my previous comments accordingly.

**Comment by mklement0** [comment]
@chasewilson, to flesh out what the bug means in the context of the current warning and workaround:

Currently recommended:

```powershell
Get-ChildItem * -Include *.csv -Recurse | Remove-Item
```

What _should_ work, but doesn't, because of https://github.com/PowerShell/PowerShell/issues/3727:

```powershell
# !! Fails as of PowerShell Core 7.2.0-preview.9, due to #3727
Remove-Item . -Include *.csv -Recurse 
```

The simplest workaround is the same you'd need for the general `-Include` "quirk" of only operating on the _input path_'s name component in the absence of `-Recurse` (see https://github.com/PowerShell/PowerShell/issues/3304):

```powershell
# Workaround for #3727; also works in WinPS
Remove-Item * -Include *.csv -Recurse 
```

Given that it is probably common to attempt a filtered remove operation in the subtree of the _current_ directory, I suggest mentioning this workaround.

---

As an aside:

Note that the current workaround _needlessly_ applies this workaround (`Get-ChildItem *`, which does no functional harm, but can conceivably affect performance), because it isn't necessary due to the presence of `-Recurse`: 

`Get-ChildItem . -Include *.csv -Recurse | Remove-Item` would do, and therefore also _implicitly_ targeting the current directory:
`Get-ChildItem -Include *.csv -Recurse | Remove-Item`
