### ISSUE TITLE
Example 3 is not correct

### ISSUE THREAD

**Issue by Tarjei99** [MicrosoftDocs/PowerShell-Docs#8140]
I have discovered that there is different behaviour whether where-object -Property is used of whether a code block is used.

A code block will pass on $false or $null through the pipeline if it evaluates to false. Whereas -Property method will only pass on what evaluates to true.

I noticed when I was using get-childitem and filtering using where-object. Remove-Item was complaining about not being able to find the $false file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8bdd61a-ff6d-2d2d-fbbb-b5f40fd5618d
* Version Independent ID: dff1f69c-82c5-68dc-663d-f459f7c79cf3
* Content: [Where-Object (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/where-object?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/Where-Object.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/Where-Object.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
I don't think I understand the scenario. Can you provide an example the reproduces the problem?

**Comment by Tarjei99** [comment]
This is PowerShell 5.1

I'm in a hurry now, so this will be approximate.

Roughly (I've not checked the exact qualifier, but you get the drift) : 

1. list-childitem -path 'C:\Temp\*.xml' -file | where-object {$_.LastUpdate -lt (get-date).addmonth(-6) } | remove-item
2. list-childitem -path 'C:\Temp\*.xml' -file | where-object -Property LastUpdate -lt (get-date).addmonth(-6)  | remove-item

In 1. files that are not older than 6 months from todays date will be sent along the pipeline as $false or $null.
In 2. only positive matches will be sendt on.

**Comment by sdwheeler** [comment]
I know this example is approximate, but are you using `list-childitem` or `Get-ChildItem`? `list-childitem` is not a cmdlet that we created.

I am not able to reproduce your issue. Using `Get-ChildItem` in both examples returns the same results.

If you get rid of the `Remove-Item` you should see the list of matching files. If you are getting "False" mixed in with the results then the problem is in `list-childitem` or something else on your system.

**Comment by sdwheeler** [comment]
Here is my test:

```powershell
PS C:\temp\platyps\test> Get-ChildItem -Path *.md -File | Where-Object {$_.LastWriteTime -lt (Get-Date).AddDays(-14)}


    Directory: C:\temp\platyps\test


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          9/9/2021   1:20 PM            547 about_platyPS.md

PS C:\temp\platyps\test> Get-ChildItem -Path *.md -File | Where-Object -Property LastWriteTime -lt (Get-Date).AddDays(-14)


    Directory: C:\temp\platyps\test


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          9/9/2021   1:20 PM            547 about_platyPS.md
```
