### ISSUE TITLE
Windows 10 The term 'Get-WindowsFeature' is not recognized as a name of a cmdlet, function, script file, or executable program

### ISSUE THREAD

**Issue by trollyanov** [MicrosoftDocs/PowerShell-Docs#8141]
Hello.
In this 3 lessons use Get-WindowsFeature, but this cmdlet only in Windows Server.
I change 3 lessons Get-WindowsFeature -Name p* on Get-Process P* in my Windows 10.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b922acc-04e1-a08a-ff61-3abb4c4d8022
* Version Independent ID: ec82c5c6-2d59-f274-f043-e645493a5aa1
* Content: [Write-Information (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-information?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Utility/Write-Information.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Utility/Write-Information.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by doctordns** [comment]
Not sure of the issue here. Yes, Get-WindowsFeature is a cmdlet in the ServerManagement module.  The cmdlet does not exist in Windows 10.

**Comment by trollyanov** [comment]
I complete levels and execute codes in windows 10 just like other other people. And few people work and lessons on Windows Servers. The point is to write these examples then under windows server.

**Comment by sdwheeler** [comment]
The ServerManager module can be installed on Windows 10 but you must target a Windows Server machine. The examples are fine but the need to mention that they apply to Windows Server using the ServerManager module.
