### ISSUE TITLE
Descriptions for outcomes of different `Confirm` values are switched around

### ISSUE THREAD

**Issue by antonburger-advanced** [MicrosoftDocs/PowerShell-Docs#8156]
The descriptions here, of the impact of different `-Confirm` values, seem backwards, but I don't know if I'm misinterpreting something.

> In the default environment [...] specify `Confirm` or `-Confirm:$true` [...] *This bypasses `ShouldProcess` confirmation requests, even for high-impact operations*.

It doesn't bypass them - it *forces* confirmation requests.

Similarly:

> If `Confirm` is false or `-Confirm:$false` is specified, *the `ShouldProcess` call requests confirmation from the user*

It definitely doesn't.

> [...] and the `$ConfirmPreference` shell variable is ignored.

This is true, but it seems like it was meant to belong to the `Confirm:$true` paragraph (where it's also true). This would have made more sense to me:

> In the default environment, users can specify the `Confirm` parameter or `-Confirm:$true` so that confirmation is requested when the `System.Management.Automation.Cmdlet.ShouldProcess` method is called. The `$ConfirmPreference` shell variable is ignored.
>
> *[middle para about unspecified `Confirm` is fine and not relevant to this issue]*
>
> If `Confirm` is false or `-Confirm:$false` is specified, the `System.Management.Automation.Cmdlet.ShouldProcess` call does **not** request confirmation from the user. This bypasses `System.Management.Automation.Cmdlet.ShouldProcess` confirmation requests, even for high-impact operations.

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f39db4a5-f617-2b09-65e7-1b6ec14264e8
* Version Independent ID: 52e61b94-396a-b5aa-5b39-b79a0e74a8d3
* Content: [Users Requesting Confirmation - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/users-requesting-confirmation?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/users-requesting-confirmation.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/users-requesting-confirmation.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
> It doesn't bypass them - it forces confirmation requests.

You are correct. That is a poor choice of words.
