### ISSUE TITLE
Wrong service ssh named

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/PowerShell-Docs#8157]
Instead of `sudo service ssh restart` it should read `sudo service sshd restart`.
ALso, please clarify what "Windows Computer" means - I think it means the SSH host/server and not the windows client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e79ea6-1d79-6147-aa3e-362b04bc7528
* Version Independent ID: 8877b05f-1f52-8c75-2d7d-5100cc52c4cb
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
On Ubuntu, which this article uses for the example, `sudo service ssh restart` is a valid command. The `service` command in Linux runs scripts in /etc/init.d. On Ubuntu the script that controls the SSH service is named `ssh`. You can also run `sudo systemctl restart sshd.service`. That may cause less confusion for the reader.
