### ISSUE TITLE
version confusing: 7.2 or 7.1.4

### ISSUE THREAD

**Issue by lq3141** [MicrosoftDocs/PowerShell-Docs#8165]
This page make me very confusing, sometimes it talks about 7.2, sometimes it talks about 7.1.4. Weird. There's only 7.1.4 deliverable on GitHub. Where's the 7.2? 

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.1#installing-the-msi-package)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment]
7.2 is referenced in the doc as the preview version of PowerShell. 7.1 is currently the recommended version for production environments. 

@lq3141 does this answer your questions

**Comment by sdwheeler** [comment]
There are 3 versions of PowerShell active and available at any time. All are available for download from GitHub.

- Stable release: https://aka.ms/powershell-release?tag=stable
- Preview release: https://aka.ms/powershell-release?tag=preview
- LTS release: https://aka.ms/powershell-release?tag=lts

As @chasewilson said, 7.2-preview.10 is the current preview version. The current Stable release is 7.1.4. The current LTS release is 7.0.7.
