### ISSUE TITLE
Authoring composite DSC resources

### ISSUE THREAD

**Issue by LadyJaz** [MicrosoftDocs/PowerShell-Docs#8180]
# Documentation Issue

## Detailed description of the issue

Horrible documentation without code example!!!

https://docs.microsoft.com/en-us/powershell/scripting/dsc/resources/authoringresourcecomposite?view=powershell-7.1

**Comment by sdwheeler** [comment]
@LadyJaz Can you be more specific about your issue with this article? There are 5 code blocks in the article you linked to.

**Comment by LadyJaz** [comment]
There isn't any example code for download. I feel like it's a Hercules Poirot adventure. BTW this is a proper one https://www.youtube.com/watch?v=H_J4B32yWKE
