### ISSUE TITLE
PowerShell Dispose

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/PowerShell-Docs#8186]
Why do none of the examples that create PowerShell objects Dispose them? Is this one of those cases where Disposing objects is best ignored?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4724704d-95c7-4f0a-ed0d-5b829fb0ca1c
* Version Independent ID: 3f6965b5-7bf8-7770-257e-ba64bc970f78
* Content: [Windows PowerShell Host Quickstart - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/windows-powershell-host-quickstart?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/hosting/windows-powershell-host-quickstart.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/hosting/windows-powershell-host-quickstart.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The scope of this article is focused on the creation scenarios. The examples are just enough to illustrate the concepts. They are not full examples showing the complete lifecycle of the objects.

**Comment by martingbrown** [comment]
None of the other articles show the full lifecycle either. It makes it hard to know how to use the product. I guess we are expected to go read the PowerShell source code to find out?
