### ISSUE TITLE
Document manifest for PowerShell packages

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/PowerShell-Docs#8205]
# Summary of the new document or enhancement

- List of articles that need to be updated:
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo:
https://github.com/PowerShell/PowerShell/pull/16202

- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

All 7.2 packages should have a `_manifest\spdx_2.2\manifest.spdx.json` in them which has a sha1 and sha256 hash of all files.  This can be used to verify the integrity of a package.

the spec for the format is here:
https://spdx.github.io/spdx-spec/introduction/

**Comment by sdwheeler** [comment]
- What does the end user need to know about this manifest?
- How do they use it?
- Why do they care?
- Does it get installed on the system? If so, where?
