### ISSUE TITLE
More examples for this ValidatePattern docs

### ISSUE THREAD

**Issue by francisco-lafe** [MicrosoftDocs/PowerShell-Docs#8234]
> Options (System.Text.Regularexpressions.Regexoptions) Optional named parameter.

It would be nice to have examples of the "Options" for say, a case insensitive regex match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfe380d4-17fd-9850-6caf-79854fa4fd7f
* Version Independent ID: eaf9b582-ab99-8a52-65f7-f775f2937983
* Content: [ValidatePattern Attribute Declaration - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/validatepattern-attribute-declaration?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/developer/cmdlet/validatepattern-attribute-declaration.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/validatepattern-attribute-declaration.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment]
The regex options aren't really part of PowerShell. They are specific to the .NET `[regex]` class. The options are documented in the class documentation at https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options.
