### ISSUE TITLE
Remove-Item -Recurse -Confirm:$false -Force

### ISSUE THREAD

**Issue by pinigo-tr** [MicrosoftDocs/PowerShell-Docs#8245]
It will be useful to mention the below command in case Recurse is needed, otherwise it will prompt.

Remove-Item -Recurse -Confirm:$false -Force

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca41c7e-6796-5d87-0794-29fcaba7524c
* Version Independent ID: 0b18157a-a191-4733-90db-7dfceda2c99f
* Content: [Remove-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
That is a very dangerous example. From the documentation, you can infer that it is possible to do that but it is not recommended.
