### ISSUE TITLE
deploy to azure automation doesn't deploy to AzureUSGovernment

### ISSUE THREAD

**Issue by k3for** [MicrosoftDocs/PowerShell-Docs#8273]
https://www.powershellgallery.com/packages/Az.ManagedServiceIdentity/0.7.1 

We need a .zip file or working method to deploy these additional modules to sovereign clouds. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbaac00f-ad38-6e13-b1ed-91ede1a1f907
* Version Independent ID: f022dfac-d90b-9615-1f6f-1e160409ce17
* Content: [Deploy to Azure Automation - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/deploy-to-azure-automation?view=powershell-7)
* Content Source: [reference/docs-conceptual/gallery/how-to/working-with-packages/deploy-to-azure-automation.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/gallery/how-to/working-with-packages/deploy-to-azure-automation.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SydneyhSmith
* Microsoft Alias: **sysmith**

**Comment by SydneyhSmith** [comment]
Yep, PowerShell Gallery is not supported in air gapped systems. We would recommend users utilize private repositories where they can manage/verify packages, information about using PowerShellGet with private repos is documented here: https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-local-psrepositories?view=powershell-7.2
