### ISSUE TITLE
output format changed?

### ISSUE THREAD

**Issue by allanmo79** [MicrosoftDocs/PowerShell-Docs#8276]
Started to get some funny errors when running my azure function apps, after some debugging I noticed that the output from get-date had change from using ":" to "." is this on purpose?

**Ps version 5**
`
PS C:\Users\myname> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.65
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.65
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\Users\myname> get-date

Friday, October 29, 2021 **4:27:50** PM
`

**Ps version 7**
```
PS C:\Users\myname> $PSVersionTable                                              
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\myname> get-date

Friday, 29 October 2021 **16.28.00**
```

**Even if I try to format it, it dosnt respect my wishes:**

```
PS C:\Users\myname> get-date -Format "yyyy-MM-ddTHH:mm:ssZ"
2021-10-29T16.33.40Z
```

**Comment by sdwheeler** [comment]
Hi @allanmo79 
First, this is a product issue, not a documentation issue. Please file an issue at https://aka.ms/psfeedback.

Second, I can't reproduce this behavior. It could be date/time formatting is related to your system's Culture settings. Check those settings and include that information if you file a product issue.
