### ISSUE TITLE
Doesn't say which registry key to change

### ISSUE THREAD

**Issue by MalcolmAnderson** [MicrosoftDocs/PowerShell-Docs#8279]
Below it says, 
"To change the value of PSModulePath for every session in a Windows environment, edit the registry key storing the PSModulePath values. "

But it does not say *which* registry key to change.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6025398e-8980-f6c5-898c-20a039a00f7e
* Version Independent ID: 0e9c150c-ad17-86a9-f0e1-68c90cd93ead
* Content: [about PSModulePath - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
It's in the example. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_psmodulepath#modifying-psmodulepath-in-windows
