### ISSUE TITLE
Cannot locate package powershell

### ISSUE THREAD

**Issue by jordonedavidson** [MicrosoftDocs/PowerShell-Docs#8293]
Following the instructions for apt in Ubuntu (21.04) fails as the powershell package is not available in the specified repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f08cba0-0fc9-b8eb-022f-5db66edf8c4f
* Version Independent ID: 2405ca72-f9d4-24a5-12a9-304d18a656ce
* Content: [Installing PowerShell on Ubuntu - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/install-ubuntu.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/install-ubuntu.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Ubuntu 21.04 is an interim release and is not a supported version. See https://docs.microsoft.com/powershell/scripting/install/install-ubuntu#supported-versions

**Comment by jordonedavidson** [comment]
21.04 is explicitly listed in the documentation on https://docs.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.1

**Comment by sdwheeler** [comment]
Sorry, that's a typo. 21.04 is not officially supported so we don't have an apt package for it. You could probably install it using the Direct Download method, but that would not be officially supported.
