### ISSUE TITLE
Not enough details about the Filter parameter

### ISSUE THREAD

**Issue by bharatsuneja** [MicrosoftDocs/PowerShell-Docs#8306]
The doc doesn't have enough details/examples of the Filter parameter. What's the syntax/query language? Links to syntax/query language docs would be nice. 

On performance, are Filters the same as applying wildcards (e.g. c:\myfolder\*foo*.pdf") in the path statement, and using other parameters? Or are other parameters about the same as filtering the piped results (e.g. gci c:\myfolder\* -include pdf | where {$_.name -like "*foo*"}

Bharat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd63f6e7-f3f3-edbc-acf6-b52de6c0eab4
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
The documentation is complete. The description of the **Filter** parameter explains everything there is to know about the filter.
