### ISSUE TITLE
‎Example 3 does not work‎

### ISSUE THREAD

**Issue by thomasgi1** [MicrosoftDocs/PowerShell-Docs#8314]
Der Hash-Table-Eintrag $state['Result'] ist immer leer!

‎The hash table entry $state['Result'] is always empty!‎

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 114b8b70-1c63-21f3-9e6b-df616ef52ef5
* Version Independent ID: 1419e56e-ad6c-feae-939d-dd73e0475678
* Content: [DSC-Ressource „Script“ - PowerShell](https://docs.microsoft.com/de-de/powershell/scripting/dsc/reference/resources/windows/scriptresource?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md](https://github.com/MicrosoftDocs/powerShell-Docs.de-de/blob/live/reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @mgreenegit
* Microsoft Alias: **migreene**

**Comment by sdwheeler** [comment]
@mgreenegit - Can you verify Example 3?

**Comment by thomasgi1** [comment]
Additional information:

This is my test script:
```
Configuration ScriptTest
{
    param
    (
        [Version]
        $Version,

        [string]
        $FilePath
    )

    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

    Node localhost
    {
        Script UpdateConfigurationVersion
        {
            GetScript = {
                $currentVersion = Get-Content -Path $using:FilePath
                return @{ 'Result' = "$currentVersion" }
            }
            TestScript = {
                # Create and invoke a scriptblock using the $GetScript automatic variable, which contains a string representation of the GetScript.
                $state = [scriptblock]::Create($GetScript).Invoke()
                Write-Verbose -Message ("Result: $($state['Result'])")
                Write-Verbose -Message ("state: $($state | out-string)")

                if( $state['Result'] -eq $using:Version )
                {
                    Write-Verbose -Message ('{0} -eq {1}' -f $state['Result'],$using:version)
                    return $true
                }

                Write-Verbose -Message ('Version up-to-date: {0}' -f $using:version)
                return $false
            }
            SetScript = {
                Set-Content -Path $using:FilePath -Value $using:Version
            }
        }
    }
}


ScriptTest -OutputPath "c:\tmp\ScriptTest" -FilePath 'c:\tmp\abc.txt' -Version '1.1'

Start-DscConfiguration -Wait -Verbose -Force -Path "c:\tmp\ScriptTest"
```
Note the additional 'Write-Verbose' lines, which I added in order to look at the $state variable.

When starting it the first time without having a file 'abc.txt', it produces:
![dscscripttest1](https://user-images.githubusercontent.com/17226631/140775293-6dfdc98d-3022-4d6c-86fa-ac7fce8a9883.png)

I get always the same output as long as the file 'abc.txt' is missing. Thus, the SetScript is not executed.

If I create a file 'abc.txt' with the content 'x', then I get following output:
 
![dscscripttest2](https://user-images.githubusercontent.com/17226631/140775937-66ac6a49-1c30-469f-a259-88d2362bc0d3.png)

Although printing the whole hash table $state shows the correct value for the 'Result' member, I can't access the 'Result' member directly using $state['Result'].
However, now the SetScript was executed and the 'abc.txt' got updated. So, running the script a second time shows that the $state hash table contains the update value '1.1', but reading $state['Result'] still gives an empty string:
![dscscripttest3](https://user-images.githubusercontent.com/17226631/140776343-32c61657-4372-4be6-bbe3-dd697d177cc8.png)

**Comment by sdwheeler** [comment]
OK, I see your issue. Example 3 expect the file to exist. It says that in the opening description. The example doesn't handle the case you have where the file may not exist. You need to adjust to the code to handle that issue. Add a line to the `GetScript` that ensures that a value is always returned. For example:

```powershell
 Configuration ScriptTest
{
    param
    (
        [Version]
        $Version,

        [string]
        $FilePath
    )

    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

    Node localhost
    {
        Script UpdateConfigurationVersion
        {
            GetScript = {
                $currentVersion = Get-Content -Path $using:FilePath
                if ($null -eq $currentVersion) { $currentVersion = 'File not found.' }
                return @{ 'Result' = "$currentVersion" }
            }
            TestScript = {
                # Create and invoke a scriptblock using the $GetScript automatic variable, which contains a string representation of the GetScript.
                $state = [scriptblock]::Create($GetScript).Invoke()
                Write-Verbose -Message ("Result: $($state['Result'])")
                Write-Verbose -Message ("state: $($state | out-string)")

                if( $state['Result'] -eq $using:Version )
                {
                    Write-Verbose -Message ('{0} -eq {1}' -f $state['Result'],$using:version)
                    return $true
                }

                Write-Verbose -Message ('Version up-to-date: {0}' -f $using:version)
                return $false
            }
            SetScript = {
                Set-Content -Path $using:FilePath -Value $using:Version
            }
        }
    }
}
```

**Comment by thomasgi1** [comment]
That is only half of the problem. I already added that extra check to the GetScript. So, in my implementation the missing file is no longer a problem. But the more complicated problem is the fact that I cannot get the result from the GetScript using $state['Result'], even if the file is present and its content was read within the GetScript. As an experiment I added a Write-Verbose line to the GetScript:
```
GetScript = {
    $currentVersion = Get-Content -Path $using:FilePath
    if ($null -eq $currentVersion) { $currentVersion = 'File not found.' }
    $state = @{ 'Result' = "$currentVersion" }
    Write-Verbose -Message ("Result: $($state['Result'])")
    return $state
}
```
It prints the correct content of the file (in my case 'x' or '1.1'). However, exactly the same Write-Verbose line within the TestScript produces nothing. That is what the is issue is really about.

**Comment by sdwheeler** [comment]
OK, I figured out the issue. I don't know why accessing the hash using `$state['Result']` does not work but changing it to `$state.Result` fixes the issue.

```
Configuration ScriptTest
{
    param
    (
        [Version]
        $Version,

        [string]
        $FilePath
    )

    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

    Node localhost
    {
        Script UpdateConfigurationVersion
        {
            GetScript = {
                $currentVersion = Get-Content -Path $using:FilePath
                return @{ 'Result' = "$currentVersion" }
            }
            TestScript = {
                $state = ([scriptblock]::Create($GetScript).Invoke())
                Write-Verbose -Message ("Result: $($state.Result)")

                if( $state.Result -eq $using:Version )
                {
                    Write-Verbose -Message ('{0} -eq {1}' -f $state.Result,$using:version)
                    return $true
                } else {
                    Write-Verbose -Message ('Version up-to-date: {0}' -f $using:version)
                    return $false
                }
            }
            SetScript = {
                Set-Content -Path $using:FilePath -Value $using:Version
            }
        }
    }
}
```
