### ISSUE TITLE
Bad upgrade instructions for the mac

### ISSUE THREAD

**Issue by ALuckyGuy** [MicrosoftDocs/PowerShell-Docs#8321]
Your upgrade instructions state upgrading to 7.2 is accomplished by running the following:
`brew case upgrade powershell`

On my mac at least, this results in the following:
`Error: Unknown command: cask`

Instead I found the correct homebrew upgrade command to be:
`brew upgrade --cask powershell`

I've been using a mac all of 7 days so I'm new to the Mac and homebrew scene. Perhaps the provided instructions work on older versions of homebrew - I don't know - but with the latest version installed on mine, the command was incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4cf1731-09a2-5369-8bbd-77fcc0d136ec
* Version Independent ID: 272cd1f1-c4f5-4b86-01c9-4bfa64bd21aa
* Content: [What's New in PowerShell 7.2 - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-72?view=powershell-7.2)
* Content Source: [reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-72.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-72.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
I don't know what instructions you are looking at. The article linked to this issue has not install instructions. The [macOS setup article](https://docs.microsoft.com/powershell/scripting/install/installing-powershell-on-macos) uses `brew upgrade --cask powershell` syntax.

Can you double check the instructions and send me the link you have to the incorrect instructions?
