### ISSUE TITLE
link = ReparsePoint

### ISSUE THREAD

**Issue by sethwisdom** [MicrosoftDocs/PowerShell-Docs#8323]
In Example 1
Change this: "l (link)"
To: "l (link - ReparsePoint)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45deca10-c7f3-f2fd-5541-d505ae29b070
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.2)
* Content Source: [reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
That's not quite accurate. ReparsePoints are specific to Windows/NFTS. And not all "links" are ReparsePoints.

A Hardlink is not a ReparsePoint.

```
PS> dir C:\Windows\System32\ntoskrnl.exe | select mode,linktype,attributes

Mode  LinkType Attributes
----  -------- ----------
la--- HardLink    Archive

PS> Get-Item 'C:\Users\sewhee\OneDrive - Microsoft\' | select mode,linktype,attributes

Mode  LinkType                                 Attributes
----  --------                                 ----------
lar--          ReadOnly, Directory, Archive, ReparsePoint
```

On non-Windows systems there is no concept of ReparsePoints.
