### ISSUE TITLE
Can module developers utilize experimental features?

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/PowerShell-Docs#8326]
What's not clear is whether module developers can utilize experimental features in their own modules. Just running `Get-ExperimentalFeature` shows that first-party module Microosft.PowerShell.Utility does include:

```powershell
PrivateData = @{
  PSData = @{
    ExperimentalFeatures = @(
      @{
        Name        = 'Microsoft.PowerShell.Utility.PSManageBreakpointsInRunspace'
        Description = 'Enables -BreakAll parameter on Debug-Runspace and Debug-Job cmdlets to allow users to decide if they want PowerShell to break immediately in the current location when they attach a debugger. Enables -Runspace parameter on *-PSBreakpoint cmdlets to support management of breakpoints in another runspace.'
      }
      @{
        Name        = 'Microsoft.PowerShell.Utility.PSImportPSDataFileSkipLimitCheck'
        Description = 'Enable -NoLimit switch for Import-PowerShellDataFile to not enforce built-in hashtable limits'
      }
    )
  }
}
```

So is the experimental feature API stable enough for others to use? Seems like a great consistent way for otherwise GA'd modules to try out new things before GA'ing those features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685c4662-4f42-ddbf-8f9a-f79241f063df
* Version Independent ID: 976ee643-597a-6c5e-bee4-bb0b72fe3c5f
* Content: [Using Experimental Features in PowerShell - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.2)
* Content Source: [reference/docs-conceptual/learn/experimental-features.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/experimental-features.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Any module developer can add an experimental feature to their own module. They just need to follow the design pattern. [about_Experimental_Features](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_experimental_features) documents the details for implementing your own experiment.

Are they stable enough? They may be but there is a note of caution at the top of this article:

>Caution
>
>Experimental features aren't intended to be used in production since the changes are allowed to be breaking.
>Experimental features are not officially supported. However, we appreciate any feedback and bug reports. You
>can file issues in the GitHub source repository.

**Comment by heaths** [comment]
> Are they stable enough? The Experimental API to create a feature is stable.

Thanks. This is what I was referring to.

Could a link be added to https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_experimental_features ? Hadn't even thought to look for new content via `help about`, so any cross-linking opportunity seems like a win for education.

**Comment by sdwheeler** [comment]
It is cross-linked already.

**Comment by heaths** [comment]
You're right. I missed it because the bright red warning in dark mode really constrains the pupils (I realize this is a site style, but could probably be toned down). Had to search for "about_experimental_features" to find the link but, yes, it's there. Thanks.
