### ISSUE TITLE
Everything you want to know about try catch throw except for that one thing

### ISSUE THREAD

**Issue by julian-hansen** [MicrosoftDocs/PowerShell-Docs#8332]
throw "some message"

catch {
   access thrown text how exactly?
}

Not a complicated thing - pretty straight forward everywhere you see try / catch / throw - but not for MS. On the page that claims to give all the answers this one small commonly used detail is omitted. I grant it may be embedded somewhere in the text - but it is the age old gripe - make me read pages and pages of text to find that one small thing I need which is not that an uncommon request.

A simple 
try {
   throw "Oops"
} catch {
   Write-Host $Error[0]
}

Would have cleared this up nicely - but not a mention of it on the page - but this is the page that tells us EVERYTHING we need to know about try / catch / throw 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d17c2d6-c661-1ac1-0448-5ab8b93d3215
* Version Independent ID: c6fcadc7-ba97-bd14-6a24-45617b102b32
* Content: [Everything you wanted to know about exceptions - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-exceptions?view=powershell-7.2)
* Content Source: [reference/docs-conceptual/learn/deep-dives/everything-about-exceptions.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/deep-dives/everything-about-exceptions.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by doctordns** [comment]
Well - This is powershell, so. the details of the throw are in $error[0].  Like this:

````powershell
PS> Try {
      throw "opps"
     } Catch {
     "In catch"
      $Error[0] | get-error
     }
In catch

Exception             : 
    Type                        : System.Management.Automation.RuntimeException
    ErrorRecord                 : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : opps
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : RuntimeException
    WasThrownFromThrowStatement : True
    Message                     : opps
    HResult                     : -2146233087
TargetObject          : opps
CategoryInfo          : OperationStopped: (opps:String) [], RuntimeException
FullyQualifiedErrorId : opps
InvocationInfo        : 
    ScriptLineNumber : 2
    OffsetInLine     : 4
    HistoryId        : -1
    Line             : throw "opps"

    PositionMessage  : At line:2 char:4
                       +    throw "opps"
                       +    ~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
```
$Error always contains details of all the errors in this session (or since it was cleared). $Error[0] always contains the last terminating error.

**Comment by julian-hansen** [comment]
Thanks - I did eventually find that out - but not from the official docs. The point of the post was feedback on the Page in question - it claims to provide everything we need to know about try / catch / throw but leaves out the above. 

Reference docs are there to provide exactly that - a reference. They are not meant to be a tome that one studies to pass a university course. If the docs result in developers having to read pages of information and still not have an answer then they are not serving their purpose.

I personally would like to see a revolution in technical writing where reference docs are designed so that those who are new to the environment can find what they need but at the same time those with experience don't have to waste time wading through unnecessary text to find what they are looking for.

I feel in this case some examples at the beginning of the doc covering the most common situations (which in my view includes accessing the thrown error message) followed by a more detailed discussion would have been better.

**Comment by doctordns** [comment]
I am disappointed with this comment. As someone who has contributed here, I can say that we DO focus on what you suggest. I personally have added examples where I felt they are missing. In writing my last three PowerShell books, I have relied on docs.microsoft.com - and they are really very good taken as a whole.  I feel your comments are somewhat off base and not helpful - and as a contributor, I feel a bit offended.

The docs repo is open source. Rather than just demanding someone do something - just click on the edit button on the page, go to GitHub and make it better. It would have taken less time than this thread! ;-) I would have done just that, but Sean beat me to it. Please consider fixing issues you find rather than raising issues for others to fix.

With that, this issue can probably be closed.

**Comment by julian-hansen** [comment]
Can I ask why there is a link at the bottom of the document asking for feedback if the response is you are going to be disappointed with the comment?

Why ask for feedback?

Do you disagree that technical documentation should enable the reader to get to an answer as quickly as possible?

Do you disagree that the issue raised (how to access the thrown error content) is not contained in the document in question - a document the title for which says "Everything you want to know about try / catch / throw"?

"Please consider fixing issues you find rather than raising issues for others to fix."

The documentation was on docs.microsoft.com - which as far as I am concerned is a Microsoft resource and not a community one. My comments were directed at Microsoft (the company) please see it in that light.

**Comment by sdwheeler** [comment]
@julian-hansen Thank you for the feedback you provided. I updated that article yesterday to add the missing information. This why the issue closed.

Also note, this particular article was part of a series of blog posts by a community member, not "official" documentation. This is disclosed at the beginning of the article. 

The official documentation is at https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_try_catch_finally#accessing-exception-information. The information you wanted is in there.

**Comment by julian-hansen** [comment]
@sdwheeler,
Thanks for the feedback and updating the article. I was not aware that the articles are blogs - it is confusing when it seems to  be on an official MS url.

Appreciate the contribution made by you and the others - and apologies if my posts were overly critical - please put it down to frustration exacerbated by extreme pressure of an impossible deadline.
