### ISSUE TITLE
PowerShell packages for Ubuntu ARM64

### ISSUE THREAD

**Issue by jpawlowski** [MicrosoftDocs/PowerShell-Docs#8341]
Dear team!

I am looking forward to receiving the latest update of PowerShell version 7.2 for Linux on ARM64.
According to the documentation page, it should be available. However, it seems the [Package index](https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-arm64/) for Ubuntu 20.04 says otherwise. PowerShell is totally missing from there, even version 7.1 or 7.0 … nothing can be installed at the moment.
Is there something you can do about it?

Many thanks,
—Julian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8f86d8-9ea9-473e-4fb7-3998d1637bc1
* Version Independent ID: ec0c0b77-e107-cfb7-715d-b48682819518
* Content: [PowerShell on Arm-based systems - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/powershell-on-arm?view=powershell-7.2)
* Content Source: [reference/docs-conceptual/install/PowerShell-on-ARM.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/PowerShell-on-ARM.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
There is no ARM package specifically for Ubuntu. You have to use the [Install from binary archive](https://docs.microsoft.com/powershell/scripting/install/install-other-linux#binary-archives) method to install the ARM package.
