### ISSUE TITLE
Doc `exec` function

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#8349]
# Summary of the new document or enhancement

- List of articles that need to be updated: n/a
- New articles that need to be created: reference for `Switch-Process` cmdlet
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/16462
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/issues/4691

## Description of what changed

New `exec` function to allow native commands that expect `exec` to exist to work when pwsh is default shell.

**Comment by sdwheeler** [comment]
Doing research on built-in functions that are loaded in the initial session state. Some of these used to be documented. Most were removed. I am going to create a new about_Built-in_Functions article to document these.

**Comment by sdwheeler** [comment]
Since the implementation for `exec` is subject to change, I am separating this issue from the work to create the new about topic.

The about topic work is tracked in #8365.
