### ISSUE TITLE
copy of Subsystem powershell /usr/bin/pwsh -sshs -NoLogo dont execute

### ISSUE THREAD

**Issue by sjakob52** [MicrosoftDocs/PowerShell-Docs#8350]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e79ea6-1d79-6147-aa3e-362b04bc7528
* Version Independent ID: 8877b05f-1f52-8c75-2d7d-5100cc52c4cb
* Content: [PowerShell Remoting Over SSH - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7.2)
* Content Source: [reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Is there more to this issue? I don't understand what problem you are trying to describe. I need more information.

- What OS and version are you using? 
- What version of PowerShell?
- Can you attach your `sshd_config` file?
- What troubleshooting have you done?

**Comment by sjakob52** [comment]
Hej

I was not sure about this line: Subsystem powershell /usr/bin/pwsh -sshs
-NoLogo

Was it a command that could be executed in PowerShell...?

Thanks

Steen



Den søn. 14. nov. 2021 kl. 00.18 skrev Sean Wheeler <
***@***.***>:

**Comment by sdwheeler** [comment]
No, it is a configuration you need to add to the `sshd_config` file.
