### ISSUE TITLE
How to declare experimental feature for a module

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#8351]
# Documentation Issue

The doc doesn't mention how to declare experimental feature for a module.

Discovered in https://github.com/PowerShell/PowerShell/pull/16460#discussion_r748747733

See https://github.com/PowerShell/PowerShell-RFC/blob/master/Final/RFC0029-Support-Experimental-Features.md#module-experimental-feature for details on how an experimental feature is declared for module.

## Context of the issue

- URL to the article (Docs or GitHub URL): https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_experimental_features?view=powershell-7.2
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [x] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [x] Version 7.2 content
- [x] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):

**Comment by sdwheeler** [comment]
@iSazonov This is covered in https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_experimental_features. Is there more documentation needed?
