### ISSUE TITLE
Invoke-Command Documentation Issue

### ISSUE THREAD

**Issue by cr94523** [MicrosoftDocs/PowerShell-Docs#8359]
# Documentation Issue

PS 7.2 Invoke-Command Example  17 uses invalid parameter set

## Context of the issue

- URL to the article (Docs or GitHub URL):
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-7.2#example-17--access-a-network-share-in-a-remote-session
- 
- Issue affects the following content (check all that apply):

**Conceptual content**
- [ ] Overview and Install
- [ x] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ x] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.2 content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux):
Only able to try on Win 2019

## Detailed description of the issue

There isn't a valid parameter set for this command using...
$parameters = @{
  Session = $s
  ScriptBlock = { Get-Item \\Net03\Scripts\LogFiles.ps1 }
  Authentication = "CredSSP"
  Credential = "Domain01\Admin01"
}

**Comment by sdwheeler** [comment]
@cr94523 What exact error do you get?

**Comment by cr94523** [comment]
Simple message that the parameter set doesn't allow the combination shown
in the example. The combination of session, script block and credentials
isn't in the syntax list either.
