### ISSUE TITLE
Rename-Item example #2 error

### ISSUE THREAD

**Issue by babybirdhome** [MicrosoftDocs/PowerShell-Docs#8368]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-5.1&WT.mc_id=ps-gethelp

### Description of the documentation error

Example 2 of the help file for Rename-Item output contains error message rather than example output.

![image](https://user-images.githubusercontent.com/68442272/142324850-550c626a-cbf9-4967-bd92-5d71b1c02172.png)

### Suggested fix

The example given should use output from a successfully completed command rather than a command that failed due to the example using invalid parameters.

**Comment by sdwheeler** [comment]
You have old help installed. Run `Update-Help -Force` to get the new help content. The current help has a valid example.

**Comment by babybirdhome** [comment]
Hi **sdwheeler**. Thank you for responding to my report, but unfortunately that's not actually correct, I did an Update-Help and Update-Help -Force prior to filing my repot. See the screenshots below for multiple examples.

1. Including **@PSVersionTable** and **Update-Help -Force** (yes, I do have errors updating some of my offline help files, but those don't pertain to **Rename-Item** so can be ignored)
![image](https://user-images.githubusercontent.com/68442272/142520209-29d71d1a-d332-4cdb-a350-a4c25ee1ae36.png)

2. See the yellow highlighted areas below. From https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-5.1 
![image](https://user-images.githubusercontent.com/68442272/142520358-a64ebf81-59ae-470a-899b-c8ae41df63a9.png)

3. See the yellow highlighted areas below. Even from the online documentation for the latest LTS version 7.2 https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-7.2 for version 7.2 LTS 
![image](https://user-images.githubusercontent.com/68442272/142520460-7ebc5e70-5f03-4d63-a74c-c2ecdbffeb8a.png)

Let me know if there's anything else I can provide to help get these issues corrected.

**Comment by sdwheeler** [comment]
So I can see now that you have the updated help. Notice that it now includes the statement:

> Use the `Move-Item` cmdlet, instead.

There is an unfortunate bug in the PowerShell help system were `Get-Help`  does not show the introductory paragraph(s) before the code block. It only shows the paragraphs after the code block. So you are missing half of the description of the example.

**Comment by babybirdhome** [comment]
Ah, does that mean that **Rename-Item** is deprecated and has been replaced with **Move-Item**? It's quite confusing because the other 3 examples don't show errors - only Example 2 shows that.

If the output shown for Example 2 is intended, it's very confusing from a user perspective because none of the other examples shows anything like that. In particular it's this text that I believe/believed was the problem:

> Rename-Item : can't rename because the target specified represents a path or device name.
> At line:1 char:12
> + Rename-Item <<<<  -path project.txt -NewName d:\archive\old-project.txt
> + CategoryInfo          : InvalidArgument: (:) [Rename-Item], PS>  Move-Item -Path "project.txt" -Destination "d:\archive\old-project.txt"

**Comment by babybirdhome** [comment]
After a more careful reading, I now see where I was going wrong. I hadn't noticed this part before.

> This example attempts to rename the project.txt file in the current directory to old-project.txt in the D:\Archive directory. **The result is the error shown in the output.**

**Comment by sdwheeler** [comment]
No, it is not deprecated. It means that you cannot use `Rename-Item` to move a file. You must use `Move-Item`, which can rename and move a file in one step.

**Comment by babybirdhome** [comment]
Thank you for the clarification. I'm not accustomed to using a help function to show me examples of how to use a command/function/cmdlet that gives me an example of something I can't do - that's where my confusion came from. My fault - thanks again.
