### ISSUE TITLE
Document Stop-Process IncludeChildProcess Parameter

### ISSUE THREAD

**Issue by nickkimbrough** [MicrosoftDocs/PowerShell-Docs#8388]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

# Summary of the new document or enhancement
- List of articles that need to be updated:
  Stop-Process
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: Add exec cmdlet for bash compatibility PowerShell/PowerShell#16561
- Link(s) to related issue(s) in the PowerShell/PowerShell repo: ssh-copy-id fails if powershell is default shell PowerShell/PowerShell#15075
# Description of what changed
Stop-Process has a new parameter `IncludeChildProcess` that will allow users to recursively stop child processes.

### Proposed title

Document Stop-Process IncludeChildProcess Parameter

**Comment by sdwheeler** [comment]
The author closed the code PR without merging. Closing this issue.
