### ISSUE TITLE
syntax in example 9 is incorrect

### ISSUE THREAD

**Issue by pr3tender** [MicrosoftDocs/PowerShell-Docs#8394]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/developer/help/how-to-add-parameter-information?view=powershell-5.1

### Description of the documentation error

Example 9 has invalid xml syntax.

Opening and closing tags have mismatched case on "v/V" as below.  If copied, this results in invalid maml syntax.

```
<dev:possiblevalues>
  <dev:possiblevalue>
    <dev:value>Unknown</dev:value>
    <maml:description>
      <maml:para></maml:para>
    </maml:description>
  </dev:possiblevalue>
  <dev:possiblevalue>
    <dev:value>String</dev:value>
    <maml:description>
      <maml:para></maml:para>
    </maml:description>
  </dev:possibleValue>
</dev:possiblevalues>
```

### Suggested fix

update example to match case at open and closing tags:

I would suggest capitalizing the second word as below, to keep formatting uniform with the other node description pages.   Get-Help will work either way though.
```
<dev:possibleValues>
  <dev:possibleValue>
    <dev:value>Unknown</dev:value>
    <maml:description>
      <maml:para></maml:para>
    </maml:description>
  </dev:possibleValue>
  <dev:possibleValue>
    <dev:value>String</dev:value>
    <maml:description>
      <maml:para></maml:para>
    </maml:description>
  </dev:possibleValue>
</dev:possibleValues>
```

**Comment by sdwheeler** [comment]
Fixed in #8397
