### ISSUE TITLE
Document OpenSSH MSI Installer Command Line Parameters

### ISSUE THREAD

**Issue by tgauth** [MicrosoftDocs/PowerShell-Docs#8396]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new feature or changed behavior

New OpenSSH MSI installer for users to install future releases via command line: `msiexec /i openssh.msi` with the option to specify installing the SSH server, client, or both. 

@heaths - can you please provide the command line parameters, and any other relevant info?

### Link to related PR in PowerShell/PowerShell repo

PowerShell/openssh-portable#521 

### Link to related Issues in PowerShell/PowerShell repo

PowerShell/Win32-OpenSSH#1484

**Comment by sdwheeler** [comment]
This issue needs to be opened in https://github.com/MicrosoftDocs/windowsserverdocs-pr/issues.

The doc would go in https://github.com/MicrosoftDocs/windowsserverdocs-pr/tree/master/WindowsServerDocs/administration/OpenSSH. Probably need to review existing docs to see how this doc needs to be added.

**Comment by tgauth** [comment]
Ah, thanks! To clarify, the MSI installer will be used with OpenSSH GitHub releases, does this still need to be moved to the Windows server docs repo?

**Comment by heaths** [comment]
For now it takes standard Windows Installer properties on the command line like https://docs.microsoft.com/en-us/windows/win32/msi/addlocal. By default, both Client and Server features will install, but if someone just wanted to install the client they could do:

```powershell
msiexec /i openssh.msi REMOVE=Server
```

See https://docs.microsoft.com/windows/win32/msi/command-line-options for Windows Installer command line options. Would be worth linking to in the docs, IMO.

**Comment by sdwheeler** [comment]
After Shiproom discussion, the plan is that you should update the documentation in the Wiki. We will plan for how to migrate the Wiki articles to the Docs platform at a later date. Closing this issue.
