### ISSUE TITLE
`Test-Path` Example 8 is confusing

### ISSUE THREAD

**Issue by Hrxn** [MicrosoftDocs/PowerShell-Docs#8402]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-7.2#example-8--test-a-path-with-whitespace-as-the-value

### Description of the documentation error

Example 8 is somehow not really consistent, I think.

The description text of the example mentions that, in one case, the result returned should be `true`, and in the other case an error.

But the code box of the example does not really reflect that, in my opinion.

**Comment by sdwheeler** [comment]
Interesting, it has changed. In PS 5.1 

```
PS D:\temp\test> Test-Path ' '
True
PS D:\temp\test> Test-Path ''
Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:1 char:11
+ Test-Path ''
+           ~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand
```
