### ISSUE TITLE
(not a regular url troubleshooting issue: The Migrated docs require credentials to view, then denies permission after build  #8412 

### ISSUE THREAD

**Issue by ninmonkey** [MicrosoftDocs/PowerShell-Docs#8414]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/dsc/overview/overview?view=powershell-7.2

Normally I wouldn't post this here, but I think I went through all the other steps. 

### Description of the documentation error

This isn't a regular help request on broken urls, I've gone through all the steps. Maybe there's something more going on.

1. When the docs moved in #8412 , the new url **requires** you to login, the regular docs don't 
1. if you login, you then get a permission error
1. re-login: still a permission error
1. So I use the step **rebuild** 
1. a new permission error, redirects me to <https://review.docs.microsoft.com/_error/403>
1. After that, it says redirect issues to `teams`, 
1. That also gives permission errors

![image](https://user-images.githubusercontent.com/3892031/146096559-8f23d720-ccac-46bc-bcb9-9058a39b712e.png)

> [errorMessage=AuthstrapFailure&errorDescription=endpoints_resolution_error](https://teams.microsoft.com/error/oops?errorMessage=AuthstrapFailure&errorDescription=endpoints_resolution_error)

### re-build

![image](https://user-images.githubusercontent.com/3892031/146097521-7e20cda9-91e5-473a-9cd9-41207556f860.png)

- post-build error: <https://review.docs.microsoft.com/_error/403>

### Redirect reports to teams

This also doesn't work after logging in. 

![image](https://user-images.githubusercontent.com/3892031/146097395-f590ce49-a109-4a66-8e44-11aa4c9b7f26.png)

### Environment

Request Id: c4c3b576-4861-4701-bb13-72294faecf00
Correlation Id: 
Timestamp: 2021-12-14T23:38:32.624Z
App name: Open Publishing Build Prod
App id: 53bb1162-c37b-4176-8ddf-ce47964c3fcd
IP address: 
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered

### Suggested fix

Unknown

**Comment by sdwheeler** [comment]
I am not able to reproduce this problem. I tested from a non-Microsoft account on a non-Microsoft computer.
