### ISSUE TITLE
"help dir -full" missing info on how to show junction targets (shown with cmd dir command)

### ISSUE THREAD

**Issue by miobrado** [MicrosoftDocs/PowerShell-Docs#8423]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.2

### Description of the documentation error

In `cmd`, I am used to seeing junction targets when I execute `dir` command. With PowerShell, I understand `dir` is an alias for `Get-ChildItem`, it does not show the junction targets by default and the help for `Get-ChildItem` does not even mention junctions.

After some searching, I found out that `(Get-Item <junctionPath>).Target` shows the junction target I was looking for.

### Suggested fix

Consider adding a remark or an example in `Get-ChildItem` help explaining that unlike `dir` command, `Get-ChildItem` does not show junction targets, but they can be shown by expanding junction item's `Target` property: `(Get-Item <junctionPath>).Target`

**Comment by sdwheeler** [comment]
In PowerShell 5.1, the property is **Target**. In PowerShell 7 the property is **LinkTarget** but there is an alias of **Target**, so either work.

Also, the output in PowerShell 7.2 shows the junction.

Output in PowerShell 5.1. 
```
PS D:\> New-Item -ItemType Junction -Name tmp -Target $env:TEMP
PS D:\> dir | select name,*target

Name     Target
----     ------
tmp      {C:\Users\sewhee\AppData\Local\Temp}
```

Output in PowerShell 7.2. 
```
PS D:\> New-Item -ItemType Junction -Name tmp -Target $env:TEMP
PS D:\> dir | select name,*target

Name     Target                             LinkTarget
----     ------                             ----------
tmp      C:\Users\sewhee\AppData\Local\Temp C:\Users\sewhee\AppData\Local\Temp

PS D:\> dir 

    Directory: D:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l----          12/16/2021  9:29 AM                tmp -> C:\Users\sewhee\AppData\Local\Temp
```

**Comment by miobrado** [comment]
Thank you Sean! My suggestion was about improving the help docs, mentioning there how to resolve and display the junction target. That's why it was reported as a doc-bug. Any chance that the examples you presented appear in the `Get-ChildItem` help?

**Comment by sdwheeler** [comment]
@miobrado I understand. Yes, I can add the examples.
