### ISSUE TITLE
Unable to find package PowerShellStandard.Library with version (>= 7.2.0)

### ISSUE THREAD

**Issue by matt9ucci** [MicrosoftDocs/PowerShell-Docs#8429]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, Preview version

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/create-standard-library-binary-module?view=powershell-7.1#binary-module-setup

### Description of the documentation error

The command in the "Binary module setup" section causes the error:

```powershell
$ dotnet add package PowerShellStandard.Library --version 7.2.0
...
info :   CACHE https://api.nuget.org/v3-flatcontainer/powershellstandard.library/index.json
error: NU1102: Unable to find package PowerShellStandard.Library with version (>= 7.2.0)
error:   - Found 13 version(s) in nuget.org [ Nearest version: 7.0.0-preview.1 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

### Suggested fix

Set the latest version `7.0.0-preview.1` below:
```
dotnet add package PowerShellStandard.Library --version 7.0.0-preview.1
```

**Comment by sdwheeler** [comment]
@matt9ucci Thanks for this report, but his is a product issue, not a docs issue. 
Please file an issue at https://aka.ms/psfeedback.

**Comment by sdwheeler** [comment]
cc: @SteveL-MSFT

**Comment by matt9ucci** [comment]
@sdwheeler Thank you for your quick reply.
> but his is a product issue, not a docs issue.

Does that mean PowerShellStandard.Library v7.2.0 should be available for users but not released as NuGet?
According to the [PowerShell/PowerShellStandard](https://github.com/PowerShell/PowerShellStandard) repo, it seems that the development of v7.2.0 has not been done yet. It could take many more days.

**Comment by sdwheeler** [comment]
@matt9ucci I really don't know. That is a question for the product team (in the source repo). Depending on their answer, there may be documentation changes needed, but the questions starts there.

**Comment by matt9ucci** [comment]
> I really don't know.

If so, please roll back the doc. Nobody knows why [it had been updated from 7.0.0-preview.1 to 7.2.0 a month ago.](https://github.com/MicrosoftDocs/PowerShell-Docs/commit/25c256b66e8de433129c3460424115bcac802d7d#diff-165e4db44d7a32b251e6c597ee554abdec6bb7fcc00cc0bdfedb8904c4323599)
