### ISSUE TITLE
FullyQualifiedName parameter of Get-Module cmdlet 

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#8449]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-module?view=powershell-7.2

### Description of the documentation error

Documentation don't mention `FullyQualifiedName` parameter of `Get-Module` cmdlet supports:
1. Module name
2. Absolute path to the module
3. Relative path to the module. Important: the relative path is resolved to absolute path based on a path to the script file where the `using module` statement is.

### Suggested fix

1. Add the new information to the `FullyQualifiedName` parameter description
2. Add new script examples for the cases.

**Comment by sdwheeler** [comment]
I will add a note about support for:

1. Module name
2. Absolute path to the module
3. Relative path to the module

I don't want to add examples because the intended type is **ModuleSpecification[]**. Noting the other formats should be enough information.
