### ISSUE TITLE
Missing-Verb (format)

### ISSUE THREAD

**Issue by dogbytehurts** [MicrosoftDocs/PowerShell-Docs#8450]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-5.1

### Description of the documentation error

The seems to be a discrepancy between the output of the 'get-verb' .
I show a format verb, but there is no format verb in the table of approved verbs.
This applies to version 5.1 or 7.1, I have looked at both versions at the MS site.

Please forgive me and ignore this report if I have erred somehow.
I am not to familiar with MS or Power shell, in-process learning.

### Suggested fix

There are only two options, pick one.

**Comment by sdwheeler** [comment]
The `Format` verb is documented at https://docs.microsoft.com/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands#verb-naming-recommendations.

> Do not use the following reserved verbs or aliases. The PowerShell language or a rare few of its cmdlet uses these verbs under exceptional circumstances.
> - ForEach (foreach)
> - Format (f): Arranges objects in a specified form or layout
> - Group (gp): Arranges or associates one or more resources
> - Ping (pi)
> - Sort (sr)
> - Tee (te)
> - Where (wh)

Most of those verbs are not defined in the group collections of verbs. However, the following are:

```powershell
PS> get-verb foreach,format,group,ping,sort,tee,where

Verb   AliasPrefix Group      Description
----   ----------- -----      -----------
Format f           Common     Arranges objects in a specified form or layout
Group  gp          Data       Arranges or associates one or more resources
Ping   pi          Diagnostic Use the Test verb
```

We should consider adding them to the doc with the appropriate caveats.
