### ISSUE TITLE
Not quite everything about switch

### ISSUE THREAD

**Issue by UberKluger** [MicrosoftDocs/PowerShell-Docs#8452]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch

### Description of the documentation error

One possibly important point about the `$switch` automatic variable is not mentioned. It appears to have a default method `MoveNext()`. Thus, just referencing `$switch` will (silently) invoke `MoveNext()`. Whether or not this is by design, it should be part of the description, if for no other reason than to aid in script debugging. Actually, on further investigation, this might actually be a bug (implementation error) since `MoveNext()` is supposed to return a `bool` and indeed `$switch.movenext()` does return a bool but (as stated) `$switch` by itself (as a command) ***silently*** invokes `MoveNext()`. Any attempt to obtain the value of `$switch` returns the actual enumerator.

P.S. while trying stuff I discovered the following:
```
PS > switch('fred','joe','blat'){
>> 'fred' {
>> $switch.current;
>> $switch.movenext();
>> $switch.current;
>> $switch;
>> $switch.current;
>> $switch.movenext()
>> }}
fred
True
joe
blat
False

PS > switch('fred','joe','blat'){
>> 'fred' {
>> $switch.current;
>> $switch.movenext();
>> $switch.current;
>> ($switch);
>> $switch.current;
>> $switch.movenext()
>> }}
fred
True
joe
blat
False

PS > switch('fred','joe','blat'){
>> 'fred' {
>> $switch.current;
>> $switch.movenext();
>> $switch.current;
>> (iex '$switch');
>> $switch.current;
>> $switch.movenext()
>> }}
fred
True
joe
blat
False

PS > switch('fred','joe','blat'){
>> 'fred' {
>> $switch.current;
>> $switch.movenext();
>> $switch.current;
>> ($switch).current;
>> $switch.current;
>> $switch.movenext()
>> }}
fred
True
joe
joe
joe
True

PS > switch('fred','joe','blat'){
>> 'fred' {
>> $switch.current;
>> $switch.movenext();
>> $switch.current;
>> (iex '$switch').current;
>> $switch.current;
>> $switch.movenext()
>> }}
fred
True
joe
False
```
Somehow, `(iex '$switch')` silently invokes `MoveNext()` but in `(iex '$switch').current` it is invoking `MoveNext()` ***TWICE*** and then also returning the enumerator to allow access to `Current` (now $null). Weird.

### Suggested fix

 Either this (apparently) strange behaviour needs to be fixed (might already be, I am using PS 5.1.18362.145) or documented (no mention in the 5.1 version documentation either).

**Comment by sdwheeler** [comment]
Linking to #8454

**Comment by sdwheeler** [comment]
`$switch` is mentioned here: https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch#switch-automatic-variable
