### ISSUE TITLE
More you might want to know about switch

### ISSUE THREAD

**Issue by UberKluger** [MicrosoftDocs/PowerShell-Docs#8453]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch?view=powershell-5.1

### Description of the documentation error

The section describing matching against `$null` needs more detail. In particular, the very important detail that there are two types of $null, a scalar version represented by `$null` itself and an empty array version which is returned by pipelines that have no output (`System.Management.Automation.Internal.AutomationNull`). While a `$null` case selector can match the former, supplying the latter as the `switch` expression will not match (anything) because `switch` treats it as an empty array and so performs no comparisons at all (one big no-op). This information was obtained by testing a `$null` case selector against the result of `gi nonexistentfile*` and having no match (even to default). Luckily, the article "Everything you wanted to know about $null" was showing in the left side index. Reading this gave the answer to the problem. The interaction between `switch` and the empty array `$null` should be clearly stated. After all, it is something that I wanted to know about `switch`.

While it is true that `$null` as a case selector will only match a switch expression that is also `$null`, the reverse is not true. As I have noted elsewhere, it appears that the switch expression is cast to a string before being compared to the case selectors (except `$null` or a script block or maybe if both values are numeric). Thus, a switch expression of `$null` will also match an empty string ('') case selector. This transitive non-equivalence should be noted.

On that note, the example for matching empty string could be clarified,
```
switch ( '' )
{
    ''
    {
#       'Value is empty'
        'Value is empty (or maybe $null)'
    }
    default
    {
#       'value is a empty string'
        'value is neither an empty string nor $null'
    }
}

```Output
Value is empty (or maybe $null)
```

### Suggested fix

Apart from the empty string example given above, I leave other details to those who know a lot more about how it actually works. While I have enough experience to know when documentation is unclear, imprecise or doesn't cover a situation I have found, I do not think I have the skill level necessary to tell others (documentation readers) the precise way something works. I just draw your attention to some things I have found that are not explained by the current text.

**Comment by sdwheeler** [comment]
Linking to #8454
