### ISSUE TITLE
Change -NoLogo description if PR for reduced startup banner text is accepted

### ISSUE THREAD

**Issue by rkeithhill** [MicrosoftDocs/PowerShell-Docs#8476]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new feature or changed behavior

If PR [#16516](https://github.com/PowerShell/PowerShell/pull/16516) in the PowerShell repo is merged, then the startup banner text will no longer display a copyright banner - ever.  So, this [about_pwsh topic](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.2#-nologo---nol) should be updated to change this text from:
```text
-NoLogo | -nol
Hides the copyright banner at startup of interactive sessions.
```
to
```text
-NoLogo | -nol
Hides the banner at startup of interactive sessions.
```

Or maybe it should say `Hides the PowerShell version banner at startup ...`?

### List of articles that need to be updated

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.2#-nologo---nol

### Link to related PR in PowerShell/PowerShell repo

https://github.com/PowerShell/PowerShell/pull/16516

### Link to related Issues in PowerShell/PowerShell repo

https://github.com/PowerShell/PowerShell/issues/15644

**Comment by daxian-dbw** [comment]
Fixed by #16516
