### ISSUE TITLE
Powershell Assembly Load Contexts Sample Code Doesn't Compile

### ISSUE THREAD

**Issue by microalps** [MicrosoftDocs/PowerShell-Docs#8481]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2

### Description of the documentation error

1. AlcModuleAssemblyLoadContext does not handle if the file to load is not in the path. In this case it should return null and not LoadFromAssemblyPath. In my test, this was triggering an error about System.Runtime not being found.
2. AlcModuleResolveEventHandler OnRemove signature is incorrect and is missing the PSModuleInfo argument. See https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.imoduleassemblycleanup.onremove?view=powershellsdk-7.0.0#System_Management_Automation_IModuleAssemblyCleanup_OnRemove_System_Management_Automation_PSModuleInfo_

### Suggested fix

Add the following for #1
```c#
            if (!File.Exists(assemblyPath))
                return null;
```

Change the line with OnRemove to:
```c#
public void OnRemove(PSModuleInfo psModuleInfo)
```

**Comment by daxian-dbw** [comment]
Thanks @microalps! PR to fix this is out: #8539
