### ISSUE TITLE
Install-Module PassThru parameter does not exist (5.1)

### ISSUE THREAD

**Issue by Cirzen** [MicrosoftDocs/PowerShell-Docs#8492]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/PowershellGet/Install-Module?view=powershell-5.1

### Description of the documentation error

Documentation for Install-Module states that the cmdlet has a PassThru parameter. Listing the parameters via (Get-Command Install-Module).Parameters shows that this is not the case

### Suggested fix

Reference to PassThru parameter should be removed and the Output section corrected accordingly

**Comment by sdwheeler** [comment]
PowerShellGet 1.0.0.1 is deprecated. You need to upgrade to a newer version of PowerShellGet and PackageManagement. The documentation is for v1.1.x and higher.
