### ISSUE TITLE
Add/Update sample manifest to show all fields and possible values

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#8503]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, 7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-module-manifest?view=powershell-7.2#sample-module-manifest
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-7.2#examples

### Description of the documentation error

The sample manifest has a number of commented out properties and it would be useful to have a sample manifest that showed how each could be used.

### Suggested fix

Add a new sample or update existing one (happy for this to be assigned to me to fix)

**Comment by sdwheeler** [comment]
@kilasuit I would welcome your contribution.

**Comment by rybm** [comment]
Test comment for notification on assigned issues in repos I am not a member of
