### ISSUE TITLE
Page for FileInfo/DirectoryInfo

### ISSUE THREAD

**Issue by hammy275** [MicrosoftDocs/PowerShell-Docs#8505]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

Due to the addition of `ResolvedTarget` in issue https://github.com/PowerShell/PowerShell/issues/13366 and PR https://github.com/PowerShell/PowerShell/pull/16490, and the lack of any mention of PowerShell on the C# page for [`FileInfo`](https://docs.microsoft.com/en-US/dotnet/api/System.IO.FileInfo?view=net-6.0) and [`DirectoryInfo`](https://docs.microsoft.com/en-US/dotnet/api/System.IO.DirectoryInfo?view=net-6.0), it may make sense to create a separate page for these objects in the PowerShell documentation, so they may have the aforementioned `ResolvedTarget` property, which doesn't exist outside of PowerShell.

If this seems like too much, the aforementioned `FileInfo`/`DirectoryInfo` pages could be updated with the same information, noting their exclusivity to PowerShell.

### Proposed title

FileInfo/DirectoryInfo

### List of related articles to link to

https://docs.microsoft.com/en-US/dotnet/api/System.IO.FileInfo
https://docs.microsoft.com/en-US/dotnet/api/System.IO.DirectoryInfo

**Comment by sdwheeler** [comment]
The .NET API reference docs are autogenerated from comments in source code. Even if we update the comments in the source code the docs are not updated until the PowerShell team releases a new SDK.
