### ISSUE TITLE
Where is pwsh.exe when installed from Microsoft Store

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/PowerShell-Docs#8516]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

When having PowerShell 7 installed from Microsoft store, where is pwsh.exe and which path (example) should be used to configure sshd_config ?

### Proposed title

Where is pwsh.exe when installed from Microsoft Store

**Comment by hkusulja** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/issues/6217

**Comment by sdwheeler** [comment]
For any installed instance of PowerShell you can find the install location by inspecting the value of `$PSHOME`.

See also https://docs.microsoft.com/powershell/scripting/install/installing-powershell-on-windows#installing-from-the-microsoft-store

**Comment by hkusulja** [comment]
Ok, I suggest to update related documentation and mention the path for psw is in $PSHOME , like you did for Program Files.
