### ISSUE TITLE
Incorrect translations. Dont translate namespaces, names of classes, names of methods.

### ISSUE THREAD

**Issue by Kalyan00** [MicrosoftDocs/PowerShell-Docs#8519]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/ru-ru/powershell/scripting/developer/hosting/windows-powershell-host-quickstart?view=powershell-7.2#addscript

### Description of the documentation error

There are many translations of words that should not have been translated, including in titles.
Do not translate the names of methods, classes, properties and spaces:
* аддскрипт
* рунспацефактори
* сессионстатекмдлетентри

Such words do not exist in Russian. It's pointless and incomprehensible

... **аддскрипт**
Можно запустить существующий скрипт, вызвав метод System. Management. Automation. PowerShell. **аддскрипт** ...

... В следующем примере для создания пространства выполнения после создания объекта InitialSessionState по умолчанию мы используем System. Management. Automation. пространства. **рунспацефактори** ...

... Методы класса System. Management. Automation. пространства выполнения. **сессионстатекмдлетентри** используются для определения командлетов для начального состояния сеанса.  ...

**Comment by sdwheeler** [comment]
Thank you for reporting this problem. Our translation to Russian is machine translated, rather than human translated. Machine translation has limitations. But I can add hints to the document that will help avoid the problems you reported.
