### ISSUE TITLE
"You can place variables, aliases, functions, or PowerShell drives in one or more scopes". Can you?

### ISSUE THREAD

**Issue by AgostinoX** [MicrosoftDocs/PowerShell-Docs#8541]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.2

### Description of the documentation error

In the "long description", the first bullet sates:
"You can place variables, aliases, functions, or PowerShell drives in one or more scopes". 
How can you actually **place** a variable, alias etc. in multiple scopes?
You can only place it in a specific scope S1 and if a child scope S2 is generated from S1 it'll receive a **copy** of that variable.
That is, a variable is not present in multiple scopes. A copy of it will be present in any child scope.

Then there is a second option; from a child scope you can access directly the parent scope, e.g.:
myfunc() {
    $script:x = 20
}
$x=10
myfunc
Here myfunc accesses directly script's $x variable (and can even change it!). But in this case also, doesn't seem right to say that $x is "placed in multiple scopes"; i'd rather say that it's placed in the script scope and it's accesible from child scopes. 
So the "in one or more scopes" is not clear.

But even the "you can place" part is quite misleading because it implies that you do so by some explicit action that allows you to decide which additional scopes a variable should be placed in. Instead, you only decide the 'initial' scope, then it gets copied into its child scopes (that, as observed, do not even have the same variable but just a copy of it).
 
So if by that sentence you refer to these mechanisms (and not others) it seems like you're making it majorly unclear. 

### Suggested fix

If the observations I made are correct and you're not talking about some **other** mechanism, then the sentence is an attempt of rephrase something that has already been said.
Since this attempt of making things clearer ends up instead in greater confusion, then it would be better to just omit it. 
That is:

* An item is visible in the scope in which it was created and in any child scopes, unless you explicitly make it private. REMOVE THIS>>>You can place variables, aliases, functions, or PowerShell drives in one or more scopes.<<<

**Comment by sdwheeler** [comment]
You can declare variables, aliases, functions, and PowerShell drives in a scope outside of the current scope.
