### ISSUE TITLE
Would a New vs Add section improve the 'Approved Verbs for PowerShell Commands' document

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/PowerShell-Docs#8544]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, 7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.2#similar-verbs-for-different-actions

### Description of the documentation error

I'm creating a new PowerShell module and I'm a bit confused about when I should create Add-* 
CmdLets and when I should use New-* CmdLets. For instance there is a New-Item command and an Add-Type command, both these seem to be adding something new to a container. Also looking more widely at the Microsoft Windows modules you get commands like Add-DhcpServiceV4Reservation (which creates a brand new reservation in a scope), why isn't that New-DhcpServiceV4Reservation? Both these verbs appear to be paired with Remove-*

The [Approved Verbs for PowerShell Commands](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.3#similar-verbs-for-different-actions) page has a section that explains the differences between different verbs that are similar. I'd appreciate it if a section could be added pitting New vs Add please.

### Suggested fix

The docs are not incorrect as such, but have left me confused. As stated in the description I'd add a section titled New vs Add below the New vs Set section.

**Comment by sdwheeler** [comment]
I would say that `Add-Type` is not creating something new. It is adding an existing type (defined in a module or assembly) to the existing session. But I agree, cmdlets like `Add-DhcpServiceV4Reservation` should have used **New** instead. Modules not created by the PowerShell team have not been as consistent about the verbs they use. 

PowerShell does nothing to enforce these rules about verbs. These are guidelines.

There is some overlap between **Add** and **New**. I will try to add some guidance.
