### ISSUE TITLE
-MaskInput does not exist, but documentation says so.

### ISSUE THREAD

**Issue by nakano15** [MicrosoftDocs/PowerShell-Docs#8551]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/read-host?view=powershell-7.2

### Description of the documentation error

The examples lists the existence of -MaskInput command, but that command is not recognized, or even exists on 
powershell. Beside the absence of the command is disappointing, since -AsSecureString doesn't seems to provide any useful output.

### Suggested fix

Eithe remove -MaskInput from documentations, or make it exist on Powershell.

**Comment by sdwheeler** [comment]
You are looking at the help for PowerShell 7.2. The `-MaskInput` parameter was added in PowerShell 7.1.

**Comment by nakano15** [comment]
Didn't solved the problem. Thanks for nothing.

**Comment by sdwheeler** [comment]
I updated the documentation the #8551 to add a note that `-MaskInput` was added in PowerShell 7.1. That documentation will be live later today.

**Comment by nakano15** [comment]
Thank you.
