### ISSUE TITLE
Translation issued, keywords translated

### ISSUE THREAD

**Issue by ecki** [MicrosoftDocs/PowerShell-Docs#8560]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/de-de/powershell/scripting/developer/help/comment-based-help-keywords?view=powershell-7.2#feedback

### Description of the documentation error

The .EXAMPLE (and others) keyword in headings is translated to .BEISPIEL in German which does not work with Powershell. 

### Suggested fix

Guard all keywords from translation (also makes it clearer what is an actual literal statement to use in script comments)

**Comment by ecki** [comment]
BTW I lied in the prerequisite section

**Comment by sdwheeler** [comment]
Thanks for pointing this out. These pages are machine translated. I will see if I can protect those keywords.
