### ISSUE TITLE
Translated switch names 

### ISSUE THREAD

**Issue by ecki** [MicrosoftDocs/PowerShell-Docs#8562]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/de-de/powershell/scripting/developer/cmdlet/activity-parameters?view=powershell-7.2

### Description of the documentation error

The table contains standard Powershell switch names but (auto)translated to German.

### Suggested fix

Mark them as literal keywords so they don’t get translated.

**Comment by sdwheeler** [comment]
Thanks for pointing this out. These pages are machine translated. I will see if I can protect those keywords.
