### ISSUE TITLE
MT localization - [nl-nl] -ieq -ceq are not translated correctly

### ISSUE THREAD

**Issue by vivanwin** [MicrosoftDocs/PowerShell-Docs#8567]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/nl-nl/powershell/scripting/learn/deep-dives/everything-about-if?view=powershell-7.2

### Description of the documentation error

Paragraph -EQ does not translate properly

In the EN version of the docs it says:

> This operator (and others) has a few variations.
> 
> -eq case-insensitive equality
> -ieq case-insensitive equality
> -ceq case-sensitive equality

In the NL-NL version the `-ieq` and `-eq` are both translated as case-sensitive.

### Suggested fix

A possible better translation could be:

`-eq` hoofdletter ongevoelig gelijkheid
`-ieq` hoofdletter ongevoelig gelijkheid
`-ceq` hoofdletter gevoelige gelijkheid

in Dutch "gevoelig" means sensative, while "ongevoelig" means insensative

**Comment by sdwheeler** [comment]
Thanks for the report. I will see what I can do to get this fixed.

**Comment by sdwheeler** [comment]
This is being tracked internally at https://ceapex.visualstudio.com/CEINTL/_workitems/edit/555399
