### ISSUE TITLE
Create function in parent scope

### ISSUE THREAD

**Issue by Molochnikov** [MicrosoftDocs/PowerShell-Docs#8581]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.2

### Description of the documentation error

Documentstion states that:
You can declare variables, aliases, functions, and PowerShell drives in a scope outside of the current scope.

As far as i know There is no any command to create function in the parent scope from the child scope like for example New-Function -Scope 1

### Suggested fix

Add example please or remove functions from this statement

**Comment by sdwheeler** [comment]
This is documented in the article at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.2#using-scope-modifiers

The syntax for a scope modifier in a function is:

```
function [<scope-modifier>:]<name> {<function-body>}
```

For example, you could have a script that defines two functions.

```powershell
function loc {
    'This is a script local function.'
}

function global:glob {
    'This is a global function'
}

Get-Item function:loc, function:glob
```

When you run `Get-Item function:loc, function:glob` inside the script. It returns both functions. When you run the same command outside the script, it only returns the `glob` function.
