### ISSUE TITLE
Import-CSV limitation

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/PowerShell-Docs#8582]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-csv?view=powershell-7.2

### Description of the documentation error

The Import-CSV function appears to not be able to import data which contains fields which contains newlines.

At times, this is very annoying, so I think it would be useful to be documented.

BTW I have suggested that the Import-CSV function be amended to allow newlines in the fields if requested.

My use case : tools in www.firstresponderkit.org which produces query results which contains XML code with newlines. When copied to Excel this fails, so I'm going for a script that creates an excel file from the exported query result.

### Suggested fix

Mention it in the documentation.

**Comment by sdwheeler** [comment]
`Import-Csv` does import data containing newlines, as long as the data is in quotes. That is standard for CSV files.

Take for example the following example:

```powershell 
PS> Get-Content test.csv
Name, Address
"Alice", "123 Main St.
Anytown, PA"
"Bob", "456 Main St.
Anytown, PA"

PS> $c = Import-Csv .\test.csv
PS> $c[0].Address
123 Main St.
Anytown, PA
```

**Comment by sdwheeler** [comment]
See https://datatracker.ietf.org/doc/html/rfc4180
