### ISSUE TITLE
-MountUserDrive parameter description mentions wrong path

### ISSUE THREAD

**Issue by metablaster** [MicrosoftDocs/PowerShell-Docs#8583]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssessionconfigurationfile?view=powershell-7.2

### Description of the documentation error

`-MountUserDrive` describes that default path to be created is:
`$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\DriveRoots\`
however that's likely false, the correct path seems to be
`$env:SYSTEMROOT\System32\Microsoft\Windows\PowerShell\DriveRoots\<HOSTNAME>_<USERNAME>`

I'm not sure if that applies to Windows PowerShell only or to PS Core as well?

I figured that out from another github issue below:
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5969

### Suggested fix

Update `-MountUserDrive` description to point out correct default path for each edition of PowerShell.

**Comment by sdwheeler** [comment]
The docs are correct.

> For each user connecting to the endpoint, a folder is created with the name `$env:USERDOMAIN_$env:USERNAME`.

For computers in workgroups, the value of `$env:USERDOMAIN` is the hostname.

I added a note.

**Comment by metablaster** [comment]
I'm sorry to reopen but there have been misunderstanding.

the issue is not `$env:USERDOMAIN_$env:USERNAME` but rather `$env:SYSTEMROOT` (correct) vs `$env:LOCALAPPDATA` (incorrect)

I tested path creation and it is created in SYSTEMROOT no in LOCALAPPDATA.

**Comment by sdwheeler** [comment]
Investigating
