### ISSUE TITLE
Doesn't work with CRM servers

### ISSUE THREAD

**Issue by Ken-DBA** [MicrosoftDocs/PowerShell-Docs#8588]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ps-remoting-second-hop?view=powershell-7.2

### Description of the documentation error

The steps in the section "Resource-based Kerberos constrained delegation" contains the following command:

```
Invoke-Command -ComputerName $ServerB.Name -Credential $cred -ScriptBlock {
    klist purge -li 0x3e7
}
Followed by a test:
# Test kerberos double hop
Invoke-Command -ComputerName $ServerB.Name -Credential $cred -ScriptBlock {
    Test-Path \\$($using:ServerC.Name)\C$
    Get-Process lsass -ComputerName $($using:ServerC.Name)
    Get-EventLog -LogName System -Newest 3 -ComputerName $($using:ServerC.Name)
}
```

Neither of these work when `$ServerB` is a Microsoft Dynamics CRM server.  It would be nice to have commands that work with all servers.

### Suggested fix

Add additional steps needed to so the commands that connect to `$ServerB` work with Microsoft Dynamics CRM servers.

**Comment by sdwheeler** [comment]
This has nothing to do with Microsoft Dynamics CRM. It is something in your environment. This is not a documentation issue. If you need support getting this to work, open an incident through the appropriate support channels. See https://support.microsoft.com/contactus
