### ISSUE TITLE
"Word boundaries are defined by a configurable set of characters." --> Configurable Where?

### ISSUE THREAD

**Issue by uglycoyote** [MicrosoftDocs/PowerShell-Docs#8595]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

The existing doc [here ](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/d4fdf052a2b3af5780b6166ead7fee5f51d3be9e/reference/7.0/PSReadLine/About/about_PSReadLine.md) has a bunch of sections for various operations to move forward or back by a "word".

Each of these say "Word boundaries are defined by a configurable set of characters." 

It's unclear how to configure the configurable set of characters.  I have searched by google e.g. "psreadline configure word boundaries" but usually just end up back at the same page, and I cannot find any information about how to configure the word boundaries.

I suggest adding a section "How to Configure Word Boundaries" and hyperlinking the phrase above to the explanation of _**how**_ to configure them.

### Proposed title

How to Configure Word Boundaries

### List of related articles to link to

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/d4fdf052a2b3af5780b6166ead7fee5f51d3be9e/reference/7.0/PSReadLine/About/about_PSReadLine.md

specifically the sections about **Cursor Movement Functions,** such as **BackwardWord**

If you search in that doc, there are 9 occurrences of the phrase "word boundaries", none of which are an explanation of how to configure the configurable word boundaries.

**Comment by sdwheeler** [comment]
See [Get-PSReadLineOption](https://docs.microsoft.com/powershell/module/psreadline/get-psreadlineoption) and [Set-PSReadLineOption](https://docs.microsoft.com/powershell/module/psreadline/set-psreadlineoption).

It is configured in the **WordDelimiters** property.

```powershell
PS> Get-PSReadLineOption | Select-Object WordDelimiters

WordDelimiters
--------------
;:,.[]{}()/\|^&*-=+'"–—―
```

**Comment by uglycoyote** [comment]
Thanks @sdwheeler   for the amazingly fast response to to the question and improving the docs

The thing that got me down this route was that I set up Ctrl-LeftArrow/RightArrow to map to the `ShellBackwardWord`/`ShellForwardWord` commands which are supposed to stop at word boundaries, but when I am editing a path on the command line (e.g. `python .\foo\bar\qux`), it's skipping over the entire path with one press of Ctrl-LeftArrow whereas I would prefer if it stopped on each backslash.

When I do the ` Get-PSReadLineOption | Select-Object WordDelimiters` command I get `;:,.[]{}()/\|^&*-=+'"–—―` as the answer.  But functionality-wise it doesn't seem to care about the presence of these characters, it seems like it only considers spaces to be the split points between "words"

Do you know why the `ShellBackwardWord`/`ShellForwardWord` commands might be ignoring the `WordDelimiters`?

Or maybe my attempt to override the ctrl-leftarrow and ctrl-rightarrow keys with those commands is not working.  

I'm attempting to map them with the following in my `profile.ps1`

```
Set-PSReadLineKeyHandler -Key Ctrl+LeftArrow -Function ShellBackwardWord
Set-PSReadLineKeyHandler -Key Ctrl+RightArrow -Function ShellForwardWord
```

**Comment by uglycoyote** [comment]
>  the word boundaries are defined as tokens parsed by PowerShell,

Which I assume is a fixed definition, and not configurable?  

Sounds like there's no way to get it to do what I want to do then (stop on backslashes) short of a change to the PSReadline `movement.cs` or `word.cs` sources.  Perhaps I'll open an issue on the Powershell/PSReadLine repo then?  

Let me know if there's some other avenue for configuring this.

**Comment by uglycoyote** [comment]
Yes! you are right, I didn't realize there was a separate `BackwardWord` and had only seen the `ShellBackwardWord`.

So `BackwardWord` does obey the configurable `WordDelimiters`  then.   I have verified this by doing a `Set-PSReadLineOption -WordDelimiters .` and then it only stops on dots 

After realizing that `ShellBackwardWord` was not configurable via `WordDelimiters`, it looks like you removed the clarifications that you added (in this [diff](https://github.com/MicrosoftDocs/PowerShell-Docs/commit/3d416f611d96e33e7c78281a53c300fabcb9489f#diff-99f9a1717d9bd29d4157d62e9bc18950f6ea04c0e7acc268f47d6fa04ed5536a))

But you also removed the clarification from the `BackwardsWord`/`ForwardsWord` sections.  Maybe it makes sense to keep your extra docs on those sections explaining that they are tied to the `WordDelimiters` setting?   Just not for the `ShellBackwardsWord`/`ShellForwardsWord` which are not tied to `WordDelimiters`
