### ISSUE TITLE
in French: two Default values for USE-MU

### ISSUE THREAD

**Issue by jemmail** [MicrosoftDocs/PowerShell-Docs#8597]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/fr-fr/powershell/scripting/whats-new/what-s-new-in-powershell-72?view=powershell-7.2

### Description of the documentation error

In the french version, the USE-MU has two values, both are set as default value.
in the English Version, 1 is the default value

USE_MU – cette propriété a deux valeurs possibles :
1 (par défaut) – Accepte l’installation des mises à jour par le biais de Microsoft Update, WSUS ou Configuration Manager
0 (par défaut) – N’accepte pas l’installation des mises à jour par le biais de Microsoft Update, WSUS ou Configuration Manager

### Suggested fix

USE_MU – cette propriété a deux valeurs possibles :
1 (par défaut) – Accepte l’installation des mises à jour par le biais de Microsoft Update, WSUS ou Configuration Manager
0  – N’accepte pas l’installation des mises à jour par le biais de Microsoft Update, WSUS ou Configuration Manager

**Comment by sdwheeler** [comment]
Thanks for the report. I will forward this to our localization team.

**Comment by sdwheeler** [comment]
Fixed in TM now.
