### ISSUE TITLE
Missing Many Modules and needs updating

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/PowerShell-Docs#8598]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

This page is missing many Microsoft published modules. Please add - especially all of the cloud (Azure, M365) related ones.

### Proposed title

Missing Many Modules and needs updating

**Comment by sdwheeler** [comment]
If you are looking for compatibility information, Azure PowerShell is documented here: https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-7.2.0

They include the following note:

> PowerShell 7.0.6 LTS, PowerShell 7.1.3, or higher is the recommended version of PowerShell for use with the Azure Az PowerShell module on all platforms.

**Comment by danmyhre** [comment]
@sdwheeler  this page: https://docs.microsoft.com/en-us/powershell/scripting/whats-new/module-compatibility?view=powershell-7.2
