### ISSUE TITLE
Declaring Cmdlet Parameter Sets: The Need for Multiple ParameterSetName

### ISSUE THREAD

**Issue by Viajaz** [MicrosoftDocs/PowerShell-Docs#8603]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

Assume this scenario with this Cmdlet:
```powershell
Function Invoke-ParamTest {
    Param(
        [Parameter(Mandatory = $true)]
        [int]$A,

        [Parameter(Mandatory = $true, ParameterSetName = 'Beta')]
        [int]$B,

        [int]$C
    )
}
```

A user might assume the following is possible without having to be prompted to manually specify a value for Parameter `B`
```powershell
Invoke-ParamTest -A 1 -C 3
```

This is because there is only one Parameter Set defined for `Invoke-ParamTest` in the above example so it collects all the Parameters into one defined Parameter Set, `Beta`, as evident by `(Get-Command 'Invoke-ParamTest').ParameterSets`

This behaviour may not be immediately obvious, the documentation should be updated to guide users to define multiple explicit Parameter Sets to avoid this behaviour:
```powershell
Function Invoke-ParamTestCorrect {
    Param(
        [Parameter(Mandatory = $true, ParameterSetName = 'Alpha')]
        [int]$A,

        [Parameter(Mandatory = $true, ParameterSetName = 'Beta')]
        [int]$B,

        [int]$C
    )
}
```
-thus allowing:
```powershell
Invoke-ParamTestCorrect -A 1 -C 3
Invoke-ParamTestCorrect -B 2 -C 3
```

### Proposed title

Declaring parameter sets

### Proposed location in the TOC

N/A

### List of related articles to link to

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/7.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/live/reference/7.3/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

**Comment by sdwheeler** [comment]
The article clearly states:

> If no parameter set is specified for a parameter, the parameter belongs to all parameter sets.

So, in your example, `$A` and `$C` automatically belong to the **Beta** parameter set. This is by design.

**Comment by Viajaz** [comment]
@sdwheeler 
I know it's by design but I think it needs to be clearer that if one-and-only-one explicit ParameterSetName has been defined then all Parameters will be collected up in the only explicitly defined Parameter Set.
