### ISSUE TITLE
Misleading Keys.Clone() example for modifying hashtable while iterating

### ISSUE THREAD

**Issue by davetapley** [MicrosoftDocs/PowerShell-Docs#8605]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.2#iterating-hashtables

### Description of the documentation error

Last example in **BadEnumeration** section says:

> The trick to this situation is to clone the keys before doing the enumeration.
> ```pwsh
> $environments.Keys.Clone() | ForEach-Object {
>     $environments[$_] = 'SrvDev03'
> }
> ```

This is okay if `$environments` is defined inline, but will fail in cases where it comes from e.g. `Group-Object -AsHashTable`, because cloned keys are added as new keys, doubling the hashtable's size and adding 'duplicate' keys:

```pwsh
$files = Get-ChildItem -Path $PSHOME | Group-Object -Property { $_.Name } -AsHashTable
Write-Output $files.Keys.count # 35

$files.Keys.Clone() | ForEach-Object { $files[$_] = 'test' }
Write-Output $files.Keys.count # 70
```

### Suggested fix

For 5.1 use a new, separate hashtable, e.g:

```pwsh
$newEnvironments = @{}
$environments.GetEnumerator() | ForEach-Object {$newEnvironments[$_.key] = 'SrvDev03'}
```

---

Note that this appears to have been fixed in 7.x and so existing docs are fine.

[Repro here](https://gist.github.com/davetapley/16881224fbcd0fdc7cafb3beacef88f5).

**Comment by sdwheeler** [comment]
I did some more research. The behavior you described is an artifact of `Group-Object`. The keys in the hashtable created by `Group-Object` are somehow different. If you add the `-AsString` parameter, the keys work correctly.

```powershell
PS> $files = Get-ChildItem -Path $PSHOME | Group-Object -Property { $_.Name } -AsHashTable -AsString
PS> Write-Output $files.Keys.count
28
PS>
PS> $files.Keys.Clone() | ForEach-Object { $files[$_] = 'test' }
PS> Write-Output $files.Keys.count
28
```

This is an extreme corner case and since this behavior is fixed in PS 7+ I don't want to document it.
