### ISSUE TITLE
Make Measure-Object ignore missing properties unless running in strict mode

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#8618]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new feature or changed behavior

When using Measure-Object on an empty folder, the "Length" property is invalid. When in StrictMode, an error is thrown when the requested property is not found. The error message is also updated to include the specific property that is not found. The invalid property is simply ignored when not in StrictMode.

PR Context

Unless in StrictMode, missing properties are typically ignored by other commands, so the Measure-Object command should do the same. This pull-request updates the Measure-Object command to only throw a property not found error when in StrictMode and ignores the property not found when not in StrictMode. This functionality is now consistent with other PowerShell commands.

### List of articles that need to be updated

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/measure-object?view=powershell-7.3

### Link to related PR in PowerShell/PowerShell repo

https://github.com/PowerShell/PowerShell/pull/16589

### Link to related Issues in PowerShell/PowerShell repo

https://github.com/PowerShell/PowerShell/issues/14449

**Comment by michaeltlombardi** [comment]
@sdwheeler I have a quick draft of possible language for this in `7.3` (see below) but I think we might need to clarify if this is documentation _for_ `7.3` or if we actually need to document the previously non-idiomatic behavior for older versions.

It _seems_ to me at first glance like we should document previously non-idiomatic behavior in the affected versions instead of announcing idiomatic behavior in the fixed version.

## Drafted Tip for 7.3

```markdown
> [!TIP]
> Unless in **StrictMode**, `Measure-Object` will not throw a property not found
> error if the object(s) being processed are missing the property being
> measured. For example, if `Measure-Object` is called to sum the **Length** of
> objects in a folder and any of those objects is an empty folder (empty folders
> do not have a **Length** property), `Measure-Object` will ignore that object.
> If `Measure-Object` is instead run in **StrictMode**, it will throw the
> property not found error on that empty folder.
```

## Alternate Implementation for < 7.3

```markdown
> [!CAUTION]
> `Measure-Object` will throw a property not found error if the object(s) being
> processed are missing the property being measured. For example, if
> `Measure-Object` is called to sum the **Length** of objects in a folder and
> any of those objects is an empty folder (empty folders do not have a
> **Length** property), `Measure-Object` will throw the property not found error
> on that empty folder. Starting in PowerShell 7.3, `Measure-Object` ignores
> objects missing properties unless called in **StrictMode**.
```
