### ISSUE TITLE
translation of HashTable to Portuguese

### ISSUE THREAD

**Issue by canoas** [MicrosoftDocs/PowerShell-Docs#8631]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/pt-pt/powershell/scripting/learn/deep-dives/everything-about-pscustomobject?view=powershell-7.2

### Description of the documentation error

Hashtable is being translated to "Haxixe" (drug).

### Suggested fix

Better keep the classname as is, no translation. Or use "tabela de hash".  

search for other pages: https://www.google.com/search?q=haxixe+site%3Amicrosoft.com

**Comment by sdwheeler** [comment]
Thanks for reporting this. I will inform our translation team about this.

**Comment by sdwheeler** [comment]
This issue is being internall tracked at https://ceapex.visualstudio.com/CEINTL/_workitems/edit/567913

**Comment by sdwheeler** [comment]
This has been fixed by our Localization team.
