### ISSUE TITLE
Typo in powershell code "Named Parameters" 

### ISSUE THREAD

**Issue by dewitweb** [MicrosoftDocs/PowerShell-Docs#8640]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions?view=powershell-7.2#named-parameters

### Description of the documentation error

There is a typo in: 

function <name> {
  param ([type]$parameter1 [,[type]$parameter2])
  <statement list>
}

and

function <name> [([type]$parameter1[,[type]$parameter2])] {
  <statement list>
}

### Suggested fix

function <name> {
  param ([type]$parameter1,[type]$parameter2)
  <statement list>
}

and

function <name> [([type]$parameter1,[type]$parameter2]) {
  <statement list>
}

![Snag_929571a](https://user-images.githubusercontent.com/13225402/157414579-2029852e-caae-4568-a6df-0e93b1e40d40.png)

**Comment by sdwheeler** [comment]
The documentation is correct as written. The comma is inside the bracket because everything inside the square brackets is optional. If you only have one parameter then the comma is not needed. You only need the comma when you have an additional parameter.
