### ISSUE TITLE
Add info for $PSCmdlet.WriteError($PSItem)

### ISSUE THREAD

**Issue by kewlx** [MicrosoftDocs/PowerShell-Docs#8641]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

As a user I would like to know about non-terminating errors as well by using $PSCmdlet.WriteError() and not just terminating errors.

I took this from a [stackoverflow post](https://stackoverflow.com/questions/9294949/when-should-i-use-write-error-vs-throw-terminating-vs-non-terminating-errors/39949027#39949027):
The general idea behind non-terminating errors is to allow "fault-tolerant" processing of large input sets: failure to process a subset of the input objects should not (by default) abort the - potentially long-running - process as a whole, allowing you to inspect the errors and reprocess only the failed objects later - as reported via the error records collected in automatic variable $Error.

### Proposed title

$PSCmdlet.WriteError() inside try/catch

### Proposed location in the TOC

Under '$PSCmdlet.ThrowTerminatingError() inside try/catch'

### List of related articles to link to

https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-exceptions?view=powershell-7.2

**Comment by michaeltlombardi** [comment]
This proposal is covered under the more expansive #1583. Closing this as a duplicate to avoid tracking the work/suggested domain under multiple issues.
