### ISSUE TITLE
$PSModuleAutoloadingPreference is empty for me

### ISSUE THREAD

**Issue by baodad** [MicrosoftDocs/PowerShell-Docs#8645]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Core/Import-Module.md

### Description of the documentation error

I am troubleshooting module importing in my environment.  Here is my environment:

> Get-ComputerInfo.OsName is Microsoft Windows 11 Education
> Get-ComputerInfo.OsVersion is 10.0.22000
> Get-ComputerInfo.CsSystemType is x64-based PC
> Execution Policy is RemoteSigned
> LanguageMode is FullLanguage
> PSVersion is 7.2.1
> PSEdition is Core

Typing $ConfirmPreference, $DebugPreference, and $ErrorActionPreference all return default values.
But typing $PSModuleAutoloadingPreference into my environment returns nothing.

### Suggested fix

Some explanation about why $PSModuleAutoloadingPreference is not getting setting default value of 'All'. Why it is different from other preference variables.

**Comment by sdwheeler** [comment]
The `$PSModuleAutoloadingPreference` variable does not exist by default. The default behavior when the variable is not defined is the same as `$PSModuleAutoloadingPreference = All`.

> Why it is different from other preference variables.

Because that is the way it was implemented.

**Comment by sdwheeler** [comment]
@michaeltlombardi Need to update `microsoft.powershell.core/about/about_preference_variables.md` to include a note about the behavior of the variable.
