### ISSUE TITLE
Improper word order in French translation

### ISSUE THREAD

**Issue by Starmania** [MicrosoftDocs/PowerShell-Docs#8654]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, 7.3 (preview)

### Link to affected document:

https://docs.microsoft.com/fr-fr/powershell/scripting/learn/ps101/09-functions

### Description of the documentation error

The phrase "L' `param` instruction vous permet de définir un ou plusieurs paramètres." doesn't mean something

### Suggested fix

Replace by " L' instruction `param` vous permet de définir un ou plusieurs paramètres. "

**Comment by Starmania** [comment]
Also, where are others languages of the docs ? Are they auto-traducted ?

**Comment by sdwheeler** [comment]
@Starmania Thank you for the report. I have escalated this to our translation team.

**Comment by Starmania** [comment]
@sdwheeler , can we see advencement ? Just a read-access

**Comment by sdwheeler** [comment]
Please leave this issue open. I will close it when our localization team addresses the problem.

**Comment by sdwheeler** [comment]
This is fixed now.
