### ISSUE TITLE
Standardize "See also" in about help documents

### ISSUE THREAD

**Issue by michaeltlombardi** [MicrosoftDocs/PowerShell-Docs#8665]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, 7.3 (preview)

### Link to affected document

All `About_*` documents

### Description of the documentation error

The "See also" section of the document is inconsistent across the docset.

As a maintainer of the documents, I would like the `about_*` documents to use a consistent structure for the "See also" section so that there is one way to write them.

### Suggested fix

The section should:

1. Use an unordered list for each entry
2. The entries should be ordered alphabetically first by type (`about_*`, cmdlet, other), then noun (for cmdlets) or category (for `about_*`, such as the operators documents), then title.

**Comment by sdwheeler** [comment]
Closed by #8670
