### ISSUE TITLE
Wrong Translation of "Log" in Simplified Chinese

### ISSUE THREAD

**Issue by VaslD** [MicrosoftDocs/PowerShell-Docs#8681]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/zh-cn/powershell/scripting/whats-new/unix-support?view=powershell-7.2

### Description of the documentation error

In the logging section, the original (English) documentation reads:

> Logging
>
> On macOS, PowerShell uses the native os_log APIs to log to Apple's [unified logging system](https://developer.apple.com/documentation/os/logging). On Linux, PowerShell uses [Syslog](https://en.wikipedia.org/wiki/Syslog), a ubiquitous logging solution.

However the Chinese version reads:

> 日志记录
>
> 在 macOS 上，PowerShell 使用本机 os_log API 登录到 Apple [统一登录系统](https://developer.apple.com/documentation/os/logging)。 在 Linux 上，PowerShell 使用 [Syslog](https://en.wikipedia.org/wiki/Syslog) 这种通用登录解决方案。

...which incorrectly translates *log* and *logging* as **登录** (*sign in*), so the documentation coincidentally means:

> Logging
>
> On macOS, PowerShell uses the native os_log APIs to log on to Apple's [Single-Sign-On system](https://developer.apple.com/documentation/os/logging). On Linux, PowerShell uses [Syslog](https://en.wikipedia.org/wiki/Syslog), a universal log-in solution.

### Suggested fix

The correct translations for *log* and *logging* are **日志** (noun, lit. logbook) and **写日志** (verb, lit. write logs), a more formal/technical verb expression is **输出日志** (lit. print to logs).

I understand that the etymology of technical terms *log in* and *sign in* come from real-world analogy of writing down one's name in a visitor's logbook. While it may seem like a common mistake in English, in Chinese we have distinct definitions of **日志** (writing something down) and **登录** (putting down one's name in request of something). So as a rule of thumb, if the meaning of a phrase (technical or real-worldly) is not interchangeable with the meaning of the phrase "sign in (to a computer system, not a facility)", you cannot use the Chinese word **登录** for it.

Also note that I'm talking about Simplified Chinese (in PRC, Mandarin equivalent) ONLY. In Traditional Chinese (in Hong Kong and Taiwan) and Japanese, the word **登录** (and its traditional writing **登錄**) means something else entirely. Translations for those languages seem to be correct.

**Comment by sdwheeler** [comment]
Thanks for reporting this. I will send this to our translation team.

**Comment by sdwheeler** [comment]
This issue is being tracked internally at https://ceapex.visualstudio.com/CEINTL/_workitems/edit/577177

**Comment by sdwheeler** [comment]
The translation team fixed this.
