### ISSUE TITLE
Docs need to be clear for Add-Member and ForEach-Object -Parallel around script methods

### ISSUE THREAD

**Issue by vexx32** [MicrosoftDocs/PowerShell-Docs#8713]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, 7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-member?msclkid=b6e38c91b1fb11eca463cf2cb045622a&view=powershell-7.2

### Description of the documentation error

Also relevant articles that perhaps could be amended:

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.2
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_script_blocks?view=powershell-7.2

When decorating objects within a temporary runspace (such as the runspaces generated by ForEach-Object -Parallel) and attaching ScriptMethods to the object, then attempting to pass the objects back to another runspace and use the ScriptMethods, things don't work. Current behaviour as of the time of writing is to emit a NullReferenceException, but we may give a more useful error in future; see [the issue on PowerShell/PowerShell](https://github.com/PowerShell/PowerShell/issues/17077).

### Suggested fix

I think it's worth documenting that any objects decorated with ScriptProperties or ScriptMethods by Add-Member cannot be guaranteed to function correctly if they are run in a different runspace than the scripts were originally attached to them.

Strictly speaking the behaviour of a scriptblock will always be to attempt to run in its "home" runspace, regardless of where it's actually invoked. The problem in the linked issue arises specifically because ForEach-Object -Parallel creates temporary runspaces that it then disposes of, so there's no runspace for the scripts to execute in anymore.

It's worth mentioning that this behaviour _can_ work if the "home" runspace still exists, but may not have the desired behaviour if the script is dependent on external variables that are only present in the caller's runspace and not the "home" runspace.

I think it's worth mentioning this possibility in:

- The `Add-Member` article, particularly for the `ScriptProperty` and `ScriptMethod` parameters,
- The `ForEach-Object` article, around the `-Parallel` parameter and examples
- Possibly some of this info should also go into the `about_Script_Blocks` article as well

/cc @seeminglyscience, @daxian-dbw, and @JamesWTruher if y'all want to add any detail/corrections please do, this is correct as far as I can recall, but I'm not intimately familiar with the intricate details.

**Comment by sdwheeler** [comment]
@vexx32 Thanks for the great write up. This is exactly what I need to update the docs. It would have been difficult to get all of that reading through the source issue.
