### ISSUE TITLE
No packages in the Azure module dependencies tab

### ISSUE THREAD

**Issue by mkozikowsk** [MicrosoftDocs/PowerShell-Docs#8721]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://www.powershellgallery.com/packages/Azure/5.3.1

### Description of the documentation error

For the Azure package version 5.3.1, the entries in the dependencies tab are missing.
https://www.powershellgallery.com/packages/Azure/5.3.1[](https://user-images.githubusercontent.com/24301646/161772630-730fae94-021a-4b5d-b675-57eb4d3dcc9a.png)
image

Looking at previous versions there should be an entry for Azure.Storage.
I am using a script that uses these entries on the site, can I ask you to update this?

### Suggested fix

Dependencies
[Azure.Storage](https://www.powershellgallery.com/packages/Azure.Storage/) (>= 4.3.0)

**Comment by mikefrobbins** [comment]
@mkozikowsk I'm the docs writer for Azure PowerShell. I recommend logging this issue in [the Azure PowerShell source repo](https://github.com/Azure/azure-powershell/issues) for our engineering team to investigate.

**Comment by mkozikowsk** [comment]
@mikefrobbins thanks, I created a new issue in the suggested repo
https://github.com/Azure/azure-powershell/issues/17726
