### ISSUE TITLE
show more should be avoided because it hides information

### ISSUE THREAD

**Issue by PhmAnthony** [MicrosoftDocs/PowerShell-Docs#8729]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, 7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7.2

### Description of the documentation error

- The new "show more" should be avoided because it hides information that can be helpful. 
- I shouldn't have to click "show more" in order to see the "notes" link in the right panel.
- I really shouldn't have to click any user element in order to see needed information.

### Suggested fix

Get rid of the "show more" widget.

**Comment by sdwheeler** [comment]
@PhmAnthony Thanks for the feedback. I cannot control this feature. I will forward this to our platform team.

**Comment by sdwheeler** [comment]
Tracked by the platform team here: https://github.com/MicrosoftDocs/feedback/issues/3770
