### ISSUE TITLE
The -Scope parameter entry shown in Update-Module cmdlet doc, version 5.1, doesn't exist in that version.

### ISSUE THREAD

**Issue by ThubLives** [MicrosoftDocs/PowerShell-Docs#8744]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-5.1

### Description of the documentation error

The -Scope parameter doesn't seem to exist in Windows PowerShell 5.1, but the parameter appears in the docs under this version.  I don't know what version it first appeared in, but it does exist in PowerShell 7.2.

### Suggested fix

Remove the -Scope entry in the Parameters section under version 5.1.

**Comment by ThomasNieto** [comment]
Have you updated the PowerShellGet module? The version installed by default is outdated and doesn't match the online documentation.

**Comment by ThubLives** [comment]
It's not user-installed; it's the version shipped with Windows, which can't be user updated without an elevated PowerShell session.  Does this documentation not apply to the build shipped with Windows?

**Comment by ThomasNieto** [comment]
You can install the updated PowerShellGet module without elevated PowerShell session by using this command to install to the current user scope.

```powershell
Install-Module -Name PowerShellGet -Scope CurrentUser
```

**Comment by sdwheeler** [comment]
@ThubLives You must update PowerShellGet to a newer version. The documentation is for the supported version. For more information, see
- https://docs.microsoft.com/powershell/scripting/gallery/installing-psget
- https://devblogs.microsoft.com/powershell/when-powershellget-v1-fails-to-install-the-nuget-provider/

**Comment by ThubLives** [comment]
Based on this doc (https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget) an elevated is required.  Still, I tried it before I opened this issue:

```
> Install-Module -Name PowerShellGet -Scope CurrentUser
WARNING: Version '1.0.0.1' of module 'PowerShellGet' is already installed at 'C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1'. To install version '2.2.5', run Install-Module and add the
-Force parameter, this command will install version '2.2.5' in side-by-side with version '1.0.0.1'.
```

Adding the `-Force` parameter results in an error:
```
> Install-Module -Name PowerShellGet -Scope CurrentUser -Force
WARNING: The version '1.4.7' of module 'PackageManagement' is currently in use. Retry the operation after closing the
applications.
PackageManagement\Install-Package : The following commands are already available on this system:'fimo,inmo,pumo,upmo,Fi nd-Command,Find-DscResource,Find-Module,Find-RoleCapability,Find-Script,Get-InstalledModule,Get-InstalledScript,Get-PSR epository,Install-Module,Install-Script,New-ScriptFileInfo,Publish-Module,Publish-Script,Register-PSRepository,Save-Mod ule,Save-Script,Set-PSRepository,Test-ScriptFileInfo,Uninstall-Module,Uninstall-Script,Unregister-PSRepository,Update-M odule,Update-ModuleManifest,Update-Script,Update-ScriptFileInfo'. This module 'PowerShellGet' may override the
existing commands. If you still want to install this module 'PowerShellGet', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage
```

I just tried it on a clean VM without launching anything but the PowerShell console with `-NoProfile` and I get exactly the same message, so it's not _only_ my own, filthy system where I've been playing around with modules for ages.  So far, I'm inclined to believe that doc.

**Comment by ThomasNieto** [comment]
You need to also pass the -AllowClobber in addition to Force.

**Comment by ThubLives** [comment]
Okay, using `-Force` and `-AllowClobber` got me most of the way there, then `Remove-Module` and `Import-Module` got me to the finish line.  A bit of a chore, but usable in a script for unprivileged users.  Also, I'm not sure why Windows ships with versions of _any_ modules that are not supported.

In any case, should I be opening an issue against the [Installing PowerShellGet](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget) doc?

**Comment by sdwheeler** [comment]
@ThubLives This issue is sufficient for the docs. (I closed this in error). We will work on updating the docs to make it clearer. 

Unfortunately, updating the version of PowerShellGet in Windows is out of our control. Also, the PowerShell team is working on a complete rewrite of PowerShellGet that fixes a lot of these issues. You can try out the beta version. See https://www.powershellgallery.com/packages/PowerShellGet/3.0.12-beta
