### ISSUE TITLE
URLs to allow in firewall incomplete/location based

### ISSUE THREAD

**Issue by jurajbe** [MicrosoftDocs/PowerShell-Docs#8745]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started?view=powershell-5.1

### Description of the documentation error

URLs to whitelist are geo-located and firewall restricts them from proceeding

this url [psg-prod-eastus.azureedge.net](url) should be [onegetcdn.azureedge.net](url) or just [*.azureedge.net](url) as that's where the go.microsoft.link points and gets the providers from.

### Suggested fix

Change the requirement from [psg-prod-eastus.azureedge.net](url) to [onegetcdn.azureedge.net](url) or just [*.azureedge.net](url)

**Comment by SydneyhSmith** [comment]
Thanks for opening this issue, just chatted with our devs and it sounds like `*.azureedge.net` is the best option (rather than [psg-prod-eastus.azureedge.net](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/url) or [onegetcdn.azureedge.net](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/url))

**Comment by sdwheeler** [comment]
For now, I am adding the onegetcdn host. We should avoid wildcards because that would open access to other endpoints on azureedge.net that are not under our control.

**Comment by SydneyhSmith** [comment]
Thanks-- reviewed this with the team, if we would like to be more specific than the wildcard (which we of course would like to be)
the list is:
- psg-prod-eastus.azureedge.net
- psg-prod-centralus.azureedge.net
- onegetcdn.azureedge.net

cc:  @[alerickson](https://github.com/alerickson)

**Comment by sdwheeler** [comment]
Ok, I will add this to the currently open PR.
