### ISSUE TITLE
Edit example 5 "Property" parameter value to "NoteProperty."

### ISSUE THREAD

**Issue by tommymaynard** [MicrosoftDocs/PowerShell-Docs#8753]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2, 7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-member#example-5-copy-all-properties-of-an-object-to-another

### Description of the documentation error

Example 5 of `Add-Member` uses an incorrect parameter value for the **MemberType** parameter. Instead of `Property` it should be `NoteProperty`.

### Suggested fix

In example 5, change the **MemberType** parameter value from `Property` to `NoteProperty`.

**Comment by sdwheeler** [comment]
@tommymaynard There is a lot of things wrong with Example 5. The **MemberType** of `Property` will work but you end up copying only those properties of that type to the target object. There are many more **MemberTypes**. Using the value `Properties` would be a better choice. The target object a simple object only contains the values of the source object and none of the methods or dynamic qualities. Depending on the intent of the copy that may be OK, but it is not very useful.

I think we should remove the example and fix the example numbering.
