### ISSUE TITLE
The page is in the wrong language

### ISSUE THREAD

**Issue by endasil** [MicrosoftDocs/PowerShell-Docs#8756]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/sv-se/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

### Description of the documentation error

My OS language is english, my browser language is english, what language is most rational to show documentation in? Swedish, yes of course! ...?

### Suggested fix

Use the browser or OS language to decide what language to show so the user can get the language they actually choose.

**Comment by sdwheeler** [comment]
@endasil I am not sure what happened in your case. We do use the browser language to choose which language is displayed unless you clicked on a link that has the language id in the URL. If you notice the link you provided has `sv-se` in the path, which is the Swedish language. If you remove the language from the URL the site redirects you to the language of your browser.

```powershell
# With the language sv-se
PS> show-redirects.ps1 https://docs.microsoft.com/sv-se/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3 -showall | fl

requestURL : https://docs.microsoft.com/sv-se/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3
statusCode : 200
status     : OK
location   : https://docs.microsoft.com/sv-se/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

# Without any language
PS> show-redirects.ps1 https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3 -showall | fl

requestURL : https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3
statusCode : 301
status     : Moved Permanently
location   : /en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

requestURL : https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3
statusCode : 200
status     : OK
location   : https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3
```
