### ISSUE TITLE
Update PowerShell support on Ubuntu distro to reflect .NET support guidance

### ISSUE THREAD

**Issue by anamnavi** [MicrosoftDocs/PowerShell-Docs#8786]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.0, 7.1, 7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.2#ubuntu-linux

### Description of the documentation error

We need to update documentation for Linux setup docs. For Ubuntu distro version support .NET has issued guidance on which versions of .NET will be supported for their latest Ubuntu22.04 distro.

.NET 6.0 and newer (used by PowerShell 7.2 and newer) will be supported for Ubuntu22.04. 
.NET 3.1 and .NET 5.0 (used by PowerShell 7.0 and 7.1, respectively) will be supported up to Ubuntu20.04. This is because openSSL1.x is used for these .NET versions and OpenSSL3 will not be supported. So support for these .NET versions (and thus PowerShell versions) will end with Ubuntu20.04

### Suggested fix

Just need to update docs accordingly, thanks!

**Comment by sdwheeler** [comment]
See https://github.com/dotnet/docs/pull/29273 for reference
