### ISSUE TITLE
Provide details about changing default for comparison operators case sensitivity

### ISSUE THREAD

**Issue by agr** [MicrosoftDocs/PowerShell-Docs#8828]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.2#common-features

### Description of the documentation error

Common features section starts with the following sentence:

> By default, string comparisons are case-insensitive.

This seem to imply that there is a way to change the case-sensitivity behavior for, say, `-eq` operator.

Moreover, Powershell language specification 3.0 [section 7.8.1](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-07?view=powershell-7.2#781-equality-and-relational-operators) states:

> For two strings to compare equal, they must have the same length and contents, and letter case, if appropriate.

Which, if I read that correctly, requires case sensitive comparisons.

### Suggested fix

Either provide details regarding how to make string comparisons case-sensitive or rephrase to remove the ambiguity.

Not sure what to do about spec, but it seems it is pretty old and maybe irrelevant at this point.

**Comment by sdwheeler** [comment]
@agr It is documented in that article:

>By default, string comparisons are case-insensitive. The equality operators have explicit case-sensitive and case-insensitive forms. To make a comparison operator case-sensitive, add a `c` after the `-`. For example, `-ceq` is the case-sensitive version of `-eq`. To make the case-insensitivity explicit, add an `i` after the `-`. For example, `-ieq` is the explicitly case-insensitive version of `-eq`.

Also [section 7.8](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-07?view=powershell-7.2#78-comparison-operators) states the following:

> Some comparison-operators (written here as -op) have two variants, one that is case sensitive (-cop), and one that is not (-iop). The -op version is equivalent to -iop. Case sensitivity is meaningful only with comparisons of values of type string. In non-string comparison contexts, the two variants behave the same.

**Comment by agr** [comment]
Not sure what do you mean by "it is documented". When I read "By default, string comparisons are case-insensitive", I understand that there is a Powershell setting that controls whether `-eq` and its friends are case sensitive for strings or not. The quoted paragraph does not address that in any way.
