### ISSUE TITLE
about_Parsing indicates Get- will be prepended to Process, as Get-Process

### ISSUE THREAD

**Issue by tommymaynard** [MicrosoftDocs/PowerShell-Docs#8850]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.2, 7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing

### Description of the documentation error

The Note in the Long description of [about_Parsing](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing) is inaccurate. It says that `Get-` will be prepended to `Process`. This isn't correct, as `Process` is treated as an [input processing method](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_methods), unless it's _inside_ of an input processing method: `Begin`, `Process`, `End`. There may be other places where `Get-` is prepended, but _inside_ of an input processing method was at least one place it worked as described.

```
[PS7.2.3][C:\] process
>>
```
versus

```
[PS7.2.3][C:\] Process {Process | Select-Object -First 2}

NPM(K) PM(M) WS(M) CPU(s) Id SI ProcessName
------ ----- ----- ------ -- -- -----------
21 17.26 10.12 0.44 18784 1 AcrobatNotificationClient
20 7.42 19.58 1.64 18076 1 acrotray
```

### Suggested fix

- Remove the `Process` example and replace it with a `Service`/`Get-Service` example
- Add an fourth bullet used to explain that there are/may be places where this doesn't work as expected, such when used with Process

There's no way to include/outline every possible exception, as a module author could easily create and release a `Get-Begin` or `Get-End` command, so the new bullet/new information should be open-ended.

@sdwheeler You're welcome to assign this issue to me.

**Comment by sdwheeler** [comment]
@tommymaynard Oh, good catch. It doesn't work with process because process is one of the language keywords. See [about_Language_Keywords](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_language_keywords)

**Comment by sdwheeler** [comment]
Go ahead and include any other grammatical cleanup.
