### ISSUE TITLE
Add docs for Custom Remote Connections Feature

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#8889]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new feature or changed behavior

- Add Custom Remote Connections Feature ([#17011](https://github.com/PowerShell/PowerShell/pull/17011))

These changes open up the internal PowerShell remoting API so that custom connections can be created as PowerShell modules. This PR does not introduce any new functions, and instead selectively makes some previously internal APIs public so that third parties can create custom remote connections without modifying PowerShell core engine code. See the RFC for more details.

### List of articles that need to be updated

7.3 release notes

### Link to related PR in PowerShell/PowerShell repo

https://github.com/PowerShell/PowerShell/pull/17011

### Link to related Issues in PowerShell/PowerShell repo

https://github.com/PowerShell/PowerShell-RFC/blob/master/Archive/Draft/RFC0063-Custom-Remote-Connections.md

**Comment by sdwheeler** [comment]
@michaeltlombardi See https://github.com/PowerShell/PowerShell-RFC/pull/320/files#diff-3b32295c4bdc846b2ded35b330eb91e25fd1767f46cdcb22db7d4e6dfa7b7fbcR131-R137 for items are not supported.

**Comment by sdwheeler** [comment]
Cutting this item. We can revisit if the need for this documentation becomes important.

**Comment by JustinGrote** [comment]
Understand priorities must be made and this is a pretty niche developer future, so I'm glad you're focusing on those items with broader user impact.
