### ISSUE TITLE
Documentation Disagreement on Scopes for `New-Variable` and the use of `Private` 

### ISSUE THREAD

**Issue by StevenBucher98** [MicrosoftDocs/PowerShell-Docs#8908]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2, 7.3 (preview)

### Link to affected document

get-help new-variable -Parameter scope

### Description of the documentation error

[About Scopes ](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.2) specifies that `Private` is not a scope but `get-help new-variable -Parameter scope` it says 
```
-Scope <System.String>
    Specifies the scope of the new variable. The acceptable values for this parameter are:

    - `Global` - Variables created in the global scope are accessible everywhere in a PowerShell process. 
    - `Local` - The local scope refers to the current scope, this can be any scope depending on the context. 
    - `Script` - Variables created in the script scope are accessible only within the script file or module they are created in. 
    - `Private` - Variables created in the private scope cannot be accessed outside the scope they exist  in. 
 ```

### Suggested fix

Remove ` Private - Variables created in the private scope cannot be accessed outside the scope they exist  in. ` in the help of `New-Variable`.

**Comment by StevenBucher98** [comment]
Related issue https://github.com/PowerShell/PowerShell/issues/17459

**Comment by sdwheeler** [comment]
@StevenBucher98 We can't remove `Private` because it is one of the accepted values in the source code. What we need is an accurate description of the behavior when `Private` is used.

**Comment by StevenBucher98** [comment]
Makes sense, my stab at it is a better description like 
`- Private - Variables created in the private scope can only be accessed if specifically targetted in different scopes and cannot normally be accessed outside the scope it was created.`

**Comment by jhoneill** [comment]
> We can't remove `Private` because it is one of the accepted values in the source code. What we need is an accurate description of the behavior when `Private` is used.

Private appears to be ignored.  Although the source code accepts it you put in something else like "secret" 

```
 new-variable -Name one -Value "111" -scope secret
New-Variable: Cannot process argument because the value of parameter "Scope" is not valid. Valid values are "Global", "Local", or "Script", or a number relative to the current scope
```
The error doesn't list "Private" as an acceptable name, so I think it is OK to put a footnote saying "Private is ignored but does not produce an error". (And TBH the source code should create a warning) 

>    my stab at it is a better description like `- Private - Variables created in the private scope can only be accessed if specifically targetted in different scopes and cannot normally be accessed outside the scope it was created.`

AIUI there is no such thing as the private scope.  You can't create a scope with your own choice of name (e.g. "Secret" , "Private", "MyScope")  the only things allowed are the 3 reserved names, Global, Local, and Script and the numbers. I would add a footnote like `see about_Scopes for more detail on scopes. Note that although private, env and others are written like scopes, $env:temp indicates a PS drive and $Private:VarName indicates  a variable option.` 

I would add something explaining "a number relative to the current scope"
