### ISSUE TITLE
Doc on no longer supporting WSMan based remoting on non-Windows

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#8930]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

As part of https://github.com/PowerShell/PowerShell/issues/17390, the Committee has decided to remove support for WSMan based remoting on non-Windows as the client library that we depended upon no longer supports modern distros.  The error message when the user attempts to use WSMan will point to https://aka.ms/pswsmanremoting which will point to a newly created doc page covering:

- WSMan on non-Windows is no longer supported (still supported on Windows)
- SSH remoting is preferred
- Potentially use PSWsman community module to get it back

### Proposed title

WSMan based remoting no longer support on non-Windows

**Comment by sdwheeler** [comment]
- https://www.powershellgallery.com/packages/PSWSMan/2.3.0
- https://github.com/jborean93/omi

**Comment by SteveL-MSFT** [comment]
WSMan on non-Windows relies on https://github.com/Microsoft/omi which no longer supports PowerShell remoting.  One of the problems is that the OMI WSMan client was still dependent on OpenSSL 1.0 whereas distros have moved to OpenSSL 2.0 which is not backwards compatible.  At this point, there isn't really a distro that has the versions of dependencies needed for the OMI WSMan client to work, so PS7.3 will remove built-in support and users will need to install necessary libraries to make it work (like PSWSMan)
