### ISSUE TITLE
Powershell winget package is 'powershell', not 'Microsoft.PowerShell'

### ISSUE THREAD

**Issue by davetapley** [MicrosoftDocs/PowerShell-Docs#8934]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#winget

### Description of the documentation error

```PS C:\> winget search 'Microsoft.Powershell'
No app found matching input criteria.
```

### Suggested fix

```
PS C:\> winget search powershell
Failed when searching source; results will not be included: winget
Name                            Id           Version Source       
-------------------------------------------------------------     
PowerShell                      9MZ1SNWT0N5D Unknown msstore      
PowerShell Preview              9P95ZZKTNRN4 Unknown msstore      
PowerShell Conference Asia 2015 9WZDNCRD37D8 Unknown msstore   
```

**Comment by davetapley** [comment]
Related: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6302

**Comment by davetapley** [comment]
Also: https://github.com/MicrosoftDocs/windows-uwp/issues/3889

**Comment by sdwheeler** [comment]
@davetapley The packages with the IDs `9MZ1SNWT0N5D` and `9P95ZZKTNRN4` are the MSStore packages. That `PowerShell Conference Asia 2015` package is not PowerShell and not published by Microsoft.

The packages with the IDs starting with `Microsoft.PowerShell` are the MSI packages. They are the preferred packages.

```
PS> winget search Microsoft.PowerShell
Name               Id                           Version Source
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.2.4.0 winget
PowerShell Preview Microsoft.PowerShell.Preview 7.3.0.4 winget
```
