### ISSUE TITLE
Creating $PROFILE.AllUsersAllHosts Does not Work with PowerShell 7

### ISSUE THREAD

**Issue by ThomasMConnors** [MicrosoftDocs/PowerShell-Docs#8935]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.3 (preview)

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2

### Description of the documentation error

Example does not work for AllUsersAllHosts

if (!(Test-Path -Path $PROFILE.AllUsersAllHosts)) {
 New-Item -ItemType File -Path $PROFILE.AllUsersAllHosts -Force
}

Access to the path 'C:\Program Files\WindowsApps\Microsoft.PowerShellPreview_7.3.4.0_x64__8wekyb3d8bbwe\profile.ps1' is denied.

I tried to create the file with CMD as Admin. The directory is tightly locked down.

I also tried c:\program files\powershell\7 but also denied.

### Suggested fix

Do the AllUsersAllHosts and AllUsersCurrentHost need to be moved?

**Comment by sdwheeler** [comment]
@ThomasMConnors You are using the MSStore installed version of PowerShell. This is a known limitation for all MSStore applications. See https://docs.microsoft.com/powershell/scripting/install/installing-powershell-on-windows#known-limitations. `$PROFILE.AllUsersAllHosts` is in `$PSHOME`. You can't write to `$PSHOME` for MSStore applications. 

When you install using the MSI package `$PSHOME` is in `C:\Program Files\PowerShell\7-preview`. You can write to that location as long as you are running in an elevated session.
