### ISSUE TITLE
Enable the predictive intellisense by default in PSReadLine

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#8943]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new feature or changed behavior

Currently, the predictive intellisense feature is disabled by default in PSReadLine. The PR https://github.com/PowerShell/PSReadLine/pull/3351 is going to conditionally enable this feature by default.

- when VT is not supported, `PredictionSource` is set to `None` by default
- when VT is supported and it's running with PowerShell 7.2+, `PredictionSource` is set to `HistoryAndPlugin` by default
- when VT is supported and it's running with PowerShell prior to 7.2, `PredictionSource` is set to `History` by default

### List of articles that need to be updated

https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.2

### Link to related PR in PowerShell/PowerShell repo

- https://github.com/PowerShell/PSReadLine/pull/3351

### Link to related Issues in PowerShell/PowerShell repo

- https://github.com/PowerShell/PSReadLine/pull/3351

**Comment by sdwheeler** [comment]
Change has been merged but waiting for a release of PSReadLine before changing the documentation. We need to know what version of PSReadLine made this change available.

**Comment by ashemedai** [comment]
@sdwheeler Does that mean that the notice of `These articles document the current beta version of PSReadLine v2.2.0.` that is currently on the main `PSReadLine` page will then also be updated to reflect the new release? I was about to file an issue for it, given we have 2.2.2, 2.2.3 and 2.2.5 GA releases now, but that can easily be folded in with this. If not, happy to create a new issue/PR for it.

**Comment by daxian-dbw** [comment]
@sdwheeler The v2.2.6 release of PSReadLine was published: https://www.powershellgallery.com/packages/PSReadLine/2.2.6
