### ISSUE TITLE
CentOS 7 and Fedora have not reached End-of-Life

### ISSUE THREAD

**Issue by tjmoore** [MicrosoftDocs/PowerShell-Docs#8954]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2

### Description of the documentation error

Issue #8883 has removed Fedora and CentOS support stating they have both reached End-of-Life.

This is not correct.

CentOS 8 has been EOL'd, but CentOS 7 is still on maintenance support until June 30, 2024. https://endoflife.date/centos

Fedora has short term life cycles, but very much still active and the feed into CentOS and Red Hat. Fedora 35 & 36 are currently supported, with Fedora 37 due later in the year. https://endoflife.date/fedora https://en.wikipedia.org/wiki/Fedora_Linux_release_history

#8883 removes existing instructions for CentOS 7 and Fedora.

There's also no mention of CentOS Stream which replaces CentOS and is now upstream of Red Hat and downstream of Fedora (CentOS Stream 8 supported until 2024, 9 until 2027). https://www.centos.org/cl-vs-cs/

### Suggested fix

Restore CentOS 7 and Fedora instructions. Possibly add support for CentOS Stream.

**Comment by sdwheeler** [comment]
@tjmoore 
The PowerShell team no longer supports CentOS or Fedora. We never supported CentOS Stream. I believe the PowerShell team define end-of-life based on the Active Support dates, we have reached end-of-life for the versions that were supported. 

This is policy decision made by the PowerShell team. The docs were changed based on that policy.

I think you should be able to install the RPM packages (as described in the [RHEL](https://docs.microsoft.com/powershell/scripting/install/install-rhel) article) on Fedora or CentOS. The main point is that we don't support that. It probably works just fine. But we only document what we are prepared to support.

For further discussion with the PowerShell team, I suggest posting a message to the [Discussion board](https://github.com/PowerShell/PowerShell/discussions) in the PowerShell repository.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8954#issue-1282696789:~:text=Fedora%20has%20short%20term%20life%20cycles%2C%20but%20very%20much%20still%20active%20and%20the%20feed%20into%20CentOS%20and%20Red%20Hat.%20Fedora%2035%20%26%2036%20are%20currently%20supported%2C%20with%20Fedora%2037%20due%20later%20in%20the%20year.%20https://endoflife.date/fedora%20https://en.wikipedia.org/wiki/Fedora_Linux_release_history

@tjmoore, maybe [the Fedora DotNet SIG](https://fedoraproject.org/w/index.php?title=SIGs/DotNet&oldid=710014#Contact:~:text=%F0%9F%94%97-,Contact,-Public%20mailing%20list:) would be interested?
