### ISSUE TITLE
Documenting re-initialization of runspace pools 

### ISSUE THREAD

**Issue by zjalexander** [MicrosoftDocs/PowerShell-Docs#897]
Need to document the technique of having a runspace pool where each RS has a common initialization and then gets reinitialized after it gets used to run a command.  This is a common customer scenario and we don't appear to have any documentation for it.

**Comment by eslesar** [comment]
@zjalexander In C#, PS, or both?

**Comment by sdwheeler** [comment]
@zjalexander Can you provide more context for this? Where should this documentation go?
