### ISSUE TITLE
The 'Deploy' verb do not exist in Powershell v5.1

### ISSUE THREAD

**Issue by LaurentDardenne** [MicrosoftDocs/PowerShell-Docs#8970]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-5.1

### Description of the documentation error

The Deploy verb do not exist in Powershell v5.1
```Powershell
Get-Verb d*

Verb       Group
----       -----
Dismount   Data
Deny       Lifecycle
Disable    Lifecycle
Debug      Diagnostic
Disconnect Communications


### Suggested fix

Remove the verb ?

**Comment by sdwheeler** [comment]
Even though the version selector is set for PowerShell 5.1 it only affects the cmdlet reference content. The conceptual content is written for all versions. Version specific details are called out. In this case we document that the verb was added in PowerShell 6.

![image](https://user-images.githubusercontent.com/19415881/176561685-032804a0-8fb7-4d9a-b94a-9b0d2219a0f3.png)


![image](https://user-images.githubusercontent.com/19415881/176561685-032804a0-8fb7-4d9a-b94a-9b0d2219a0f3.png)
![image](https://user-images.githubusercontent.com/19415881/176561685-032804a0-8fb7-4d9a-b94a-9b0d2219a0f3.png)
![image](https://user-images.githubusercontent.com/19415881/176561685-032804a0-8fb7-4d9a-b94a-9b0d2219a0f3.png)
