### ISSUE TITLE
The example "Escape ('e)" does not work in my script.

### ISSUE THREAD

**Issue by inl1ner** [MicrosoftDocs/PowerShell-Docs#8984]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/de-de/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7.2

### Description of the documentation error

The example "Escape ('e)" does not work in my script:
```Powershell
$fgColor = 32                           # green
"`e[${fgColor}mGreen text`e[0m"
Output;
e[32mGreen texte[0m
PS C:\Windows\system32>
```

### Suggested fix

The example "Escape ('e)" should work according to the description

**Comment by sdwheeler** [comment]
The `` `e `` character was added in PowerShell 6. It does not work in PowerShell 5.1.
