### ISSUE TITLE
psg-prod-centralus.azureedge.net is not an active hostname and is documented as required 

### ISSUE THREAD

**Issue by AHelsby** [MicrosoftDocs/PowerShell-Docs#9018]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started?view=powershell-5.1#network-access-to-the-powershell-gallery
- https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started?view=powershell-7.2#network-access-to-the-powershell-gallery

### Summary

All versions of PowerShell docs.
Documentation states that psg-prod-centralus.azureedge.net is required, however that does not currently resolve

### Details

psg-prod-centralus.azureedge.net hostname needs updating or removing.

**Comment by sdwheeler** [comment]
@SydneyhSmith Can you verify the host names?

**Comment by SydneyhSmith** [comment]
We include both psg-prod-centralus.azureedge.net  and psg-prod-eastus.azureedge.net as these are our primary endpoint and our backup/failover endpoints...right now our primary is pointed to eastus so centralus is not active however if there is an issue with eastus, centralus will become active

**Comment by Absoblogginlutely** [comment]
Makes sense and thankyou. Should that be added to the docs to ensure you don't get asked this again?

**Comment by sdwheeler** [comment]
> Makes sense and thankyou. Should that be added to the docs to ensure you don't get asked this again?

Yes, that is the plan.
