### ISSUE TITLE
Package command examples mention NuGet even though they have nothing to do with NuGet Packages

### ISSUE THREAD

**Issue by donnie-msft** [MicrosoftDocs/PowerShell-Docs#9023]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershell-7.2#examples

### Summary

I work on the NuGet Client team. When I search the web for PowerShell functions we support for NuGet Packages, I find this set of docs pages for PowerShell. Every example on this page is calling out NuGet and packages, but its meaning is for NuGet "as a package provider". What NuGet really is here is a PowerShell Module provider implementation detail. There's no clarity here that when someone uses PS "Find-Package", for example, that it has nothing to do with a NuGet package (ie, `.nupkg`). 

### Details

Another example which is completely unrelated to NuGet is `Find-Package`.
NuGet's `Find-Package`: https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-find-package
PowerShell Gallery's `Find-Package`: https://docs.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershell-7.2

### Suggested Fix

Clarifying (even with small edits or notes) that this documentation is specific to PowerShellGallery and is for PowerShell Modules would go a long way to avoid customer confusion.

**Comment by sdwheeler** [comment]
@SydneyhSmith Do you have any comments here?

@donnie-msft I agree some clarifications would help. I would like to understand more about your cmdlets and see if we can help the SEO.

**Comment by SydneyhSmith** [comment]
Makes sense to me that we would want to add a note (or something else) to clarify that these examples use NuGet as a package provider rather than as a package type

**Comment by donnie-msft** [comment]
> I agree some clarifications would help. I would like to understand more about your cmdlets and see if we can help the SEO.

@sdwheeler  Thanks for looking into this. NuGet documents our PowerShell commands here https://docs.microsoft.com/en-us/nuget/reference/powershell-reference

Let me know if you're looking for something more specific.
