### ISSUE TITLE
`ConvertFrom-Json -AsHashtable` now uses ordered hashtable

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#9039]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

JSON typically has ordering to make it easier to read. Currently, a Hashtable does not preserve ordering so for complex JSON, the members are not where you would expect in terms of order. This change wraps OrderedDictionary into a OrderedHashtable that derives from Hashtable. This preserves existing compatibility with scripts that expect a Hashtable to be returned, but preserves the order of elements.

### Articles

- reference/7.3/Microsoft.PowerShell.Utility/ConvertFrom-Json

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/17405

### Related Source Issues

- https://github.com/PowerShell/PowerShell/issues/17404

**Comment by RokeJulianLockhart** [comment]
Can the user choose whether they want an ordered hashtable or not?

**Comment by sdwheeler** [comment]
@RokeJulianLockhart No. There is no option for that in the cmdlet.
