### ISSUE TITLE
Document how to zero-pad number using `-f`

### ISSUE THREAD

**Issue by jgarces-pd** [MicrosoftDocs/PowerShell-Docs#9044]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1, 7.0, 7.2, 7.3

### Summary

It would be nice if the documentation includes zero indexing usage, e.g., on Linux you can use:

```shell
for n in $(seq -f "%05g" 0 20)
do
    echo $n
done
```

And this will give you the following result:

```shell
00000
00001
00002
00003
00004
00005
00006
00007
00008
00009
00010
00011
00012
00013
00014
00015
00016
00017
00018
00019
00020
```

### Details

It would be nice if the documentation includes zero indexing usage, e.g., on Linux you can use:

```shell
for n in $(seq -f "%05g" 0 20)
do
    echo $n
done
```

And this will give you the following result:

```shell
00000
00001
00002
00003
00004
00005
00006
00007
00008
00009
00010
00011
00012
00013
00014
00015
00016
00017
00018
00019
00020
```

### Proposed Content Type

Cmdlet Reference, Concept

### Proposed Title

Zero Indexing Usage or Case Use

### Related Articles

- https://stackoverflow.com/a/8789815

**Comment by jgarces-pd** [comment]
I found a way, and would be great if can be documented; not sure if it is the optimal, but it works:

```powershell
PS C:\Users\rundeck> $count=1..10
>> foreach ($i in ($count| ForEach-Object {"{0:d4}" -f ($_)}))
>> { echo $i }
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
```

**Comment by sdwheeler** [comment]
The documentation for `-f` can be found here: https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_operators#format-operator--f

But it wouldn't hurt to a another simple example here.

The rules for formatting are defined by .NET, not PowerShell. See the [String.Format](https://docs.microsoft.com/en-us/dotnet/api/system.string.format) method and [Composite Formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting).
