### ISSUE TITLE
Invoke-Webrequest - example 2 broken

### ISSUE THREAD

**Issue by buchs** [MicrosoftDocs/PowerShell-Docs#9066]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.2

### Summary

Example 2 is broken

### Details

"Example 2: Use a stateful web service" shows that the $Session variable is indeed unset as the words indicate. But then proceeds to use $Session in the next statement. That clearly won't work. 
```
$ProfileResponse = Invoke-WebRequest 'https://www.contoso.com/profile/' -WebSession $Session
```
I'm not exactly sure, but I would guess something like this is required:
```
$ProfileResponse = Invoke-WebRequest 'https://www.contoso.com/profile/' -WebSession $LoginResponse.Session
```

**Comment by sdwheeler** [comment]
See the description of the **SessionVariable** parameter. `$Session` gets assign a value when the following command completes:

```powershell
$LoginResponse = Invoke-WebRequest 'https://www.contoso.com/login/' -SessionVariable 'Session' -Body $Body -Method 'POST'
```

Then the value of `$Session` is used for the **WebSession** value in the next command:

```powershell
$ProfileResponse = Invoke-WebRequest 'https://www.contoso.com/profile/' -WebSession $Session
```

I am not sure why you think the value of `$Session` is empty. The example shows only the code, not the output. But `$Session` should not be empty unless the command failed.

**Comment by buchs** [comment]
OK. When I see such commands as $VariableName alone, I think interactive use. And, I expect output would be shown in this case.
