### ISSUE TITLE
Installing PowerShellGet on older Windows systems doesn't tell you how to install on older systems.

### ISSUE THREAD

**Issue by brkdncr** [MicrosoftDocs/PowerShell-Docs#9077]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/scripting/gallery/install-on-older-systems

### Summary

This page starts by claiming it will explain how to Install PowerShellGet on older Windows systems and provides some pre-requisites.  It then provides instructions for computers that have PackageManagement Preview installed, which is a component that is no longer available to download.

The page stops there and doesn't explain how to install PowerShellGet on systems that don't have PackageManagement Preview installed.

### Suggested Fix

Steps to install PowerShell Get for older systems should be provided.

**Comment by sdwheeler** [comment]
The instructions are there at https://docs.microsoft.com/powershell/scripting/gallery/install-on-older-systems#for-computers-running-powershell-30-or-powershell-40

These instructions apply to computers that have the PackageManagement Preview installed **or don't have any version of PowerShellGet installed**.

This is just a copy-based installation. Use `Save-Module` from another computer to download the modules to folders then copy those folders to a location on the older computers. You need to make sure that the location you copied the folders is in the `$env:PSModulePath`.
