### ISSUE TITLE
Document Strict Header Parsing in Web Cmdlets

### ISSUE THREAD

**Issue by fMichaleczek** [MicrosoftDocs/PowerShell-Docs#9093]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.0, 7.2, 7.3

### Summary

As a user of Microsoft.PowerShell.Utility, when I use Invoke-WebRequest or Invoke-ResthMethod with any parameters like Headers, ContentType or UserAgent, I need a document which explains how "Strict Header Parsing" works in PowerShell

maybe one day, this blog ([link](https://get-powershellblog.blogspot.com/2017/11/powershell-core-web-cmdlets-in-depth.html)) will dissapear and we will lost the history.

A example should be enough, but WebCmdlet maybe need his own conceptual page.

### Details

Related Issues : 
- https://github.com/PowerShell/PowerShell/issues/5818#issuecomment-355973338
- https://github.com/PowerShell/PowerShell/issues/17855

Related Docs :
- https://github.com/MicrosoftDocs/PowerShell-Docs/pull/1387

The mecanism has been explain in the blog by the author of the Cmdlet : 
https://get-powershellblog.blogspot.com/2017/11/powershell-core-web-cmdlets-in-depth.html#L08

### Proposed Content Type

Cmdlet Reference, Concept

### Related Articles

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest

**Comment by michaeltlombardi** [comment]
Fixed by #9100
