### ISSUE TITLE
Add URI to -Online parameter

### ISSUE THREAD

**Issue by brajjan** [MicrosoftDocs/PowerShell-Docs#9114]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2#parameter-and-variable-validation-attributes

### Summary

Help URI should be added to Get-Help command

```
Get-Help about_Functions_Advanced_Parameters -Online
Get-Help:
Line |
  64 |      $help = Get-Help @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
```

**Comment by sdwheeler** [comment]
Unfortunately, `Get-Help -Online` doesn't support about_ topics. See https://github.com/PowerShell/PowerShell/issues/13550
