### ISSUE TITLE
New-WinEvent Lack of docs and Examples

### ISSUE THREAD

**Issue by theonesmitty** [MicrosoftDocs/PowerShell-Docs#9151]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.2

### Summary

I just discovered that *-EventLog no longer ships in later version of Posh.  The lack of documentation and examples is stunning.  With such a huge change one would really appreciate a simple example of writing an event to the Application log.  Unable to figure it out.  Please help

### Details

I just discovered that *-EventLog no longer ships in later version of Posh.  The lack of documentation and examples is stunning.  With such a huge change one would really appreciate a simple example of writing an event to the Application log.  Unable to figure it out.  Please help

### Proposed Content Type

Cmdlet Reference

### Proposed Title

New-WinEvent With more than one example for the general population

### Related Articles

NA

**Comment by sdwheeler** [comment]
The short answer is that there is not cmdlet in PowerShell 7.x to create events in the legacy logs like System, Application, Security, and others. `New-WinEvent` can create events for the new ETW-based logs.

You can still use Windows PowerShell 5.1 to create an event. And there is the command-line tool `eventcreate.exe`. You can run `eventcreate.exe` in a PowerShell 7.x script to create a new event.
