### ISSUE TITLE
ValidateSet Article In PowerShell Section Should Use PowerShell Code In Example

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/PowerShell-Docs#9159]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-validate-an-argument-set

### Summary

Please provide PowerShell code for examples in the PowerShell section of help articles.

### Details

For people learning PowerShell, or looking for PowerShell specific code, it would be simplest if the examples also reference PowerShell instead of C# code.

### Suggested Fix

Replace examples on PowerShell pages with PowerShell code instead of C# code.

**Comment by sdwheeler** [comment]
The doc you linked to is in the SDK documentation, which uses C# example by design.

The script version can be found at: https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters#validateset-attribute
