### ISSUE TITLE
The doc about how `$PSStyle.OutputRendering` works when PowerShell is redirected is unclear

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#9182]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.3
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2

### Summary

About `$PSStyle.OutputRendering`, the doc says:
> Host: This is the default behavior. The ANSI escape sequences are removed in redirected or piped output.

Within PowerShell, the stream redirection does remove the ANSI escape sequences when `$PSStyle.OutputRendering` is `Host`.
However, when the PowerShell itself is redirected, ANSI escape sequences are not removed even though the value of `$PSStyle.OutputRendering` is `Host`.

The behavior was changed by https://github.com/PowerShell/PowerShell/commit/3f1c03d4948354afd2e1d385e6aff82b07c7ef13 due to a security issue in pwsh 7.2.1 release. Later on, the default value of `$PSStyle.OutputRendering` is changed back to `Host`, but the PowerShell process redirection scenario is not re-enabled.

I'm not sure if the PowerShell process redirection scenario should be re-enabled, or this just needs doc update to call out that ANSI escape sequences are not removed when PowerShell itself is redirected, regardless of `PSStyle.OutputRendering`.

Need @SteveL-MSFT to clarify the intention.

### Details

![image](https://user-images.githubusercontent.com/127450/187321891-736fb5db-dc7e-4c05-95b7-402e38c3bbff.png)

**Comment by sdwheeler** [comment]
Based on discussions in Shiproom - This is by design. When you run a native executable the parent shell should not alter the output being redirected.

**Comment by daxian-dbw** [comment]
@sdwheeler It's not about the parent shell's behavior, it's about pwsh itself -- with the default value of `$PSStyle.OutputRendering` being `Host`, should it remove all ANSI sequences when the pwsh process's stdout is redirected?

**Comment by sdwheeler** [comment]
> should it remove all ANSI sequences when the pwsh process's stdout is redirected?

Steve's answer was "no" it shouldn't.
