### ISSUE TITLE
Exception return type of a cmdlet in documentation

### ISSUE THREAD

**Issue by williamoferreira** [MicrosoftDocs/PowerShell-Docs#9193]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershell-7.2

### Summary

I think it would be nice if the documentation also reported on thrown exceptions.

For example, I was reading about `Get-InstalledModule` [https://docs.microsoft.com/en-us/powershell/module/powershellget/get-installedmodule?view=powershell-7.2] to resolve a flow. I want to call an `Install-Module` if the module is not available. So which exception class `Get-InstalledModule` throws?

**Comment by sdwheeler** [comment]
@williamoferreira There are two issues around documenting exceptions.
1. In most cases the exceptions come from lower-level .NET methods used by the cmdlets. Most cmdlet code does not throw exceptions.
2. There is no way to discover the possible exceptions through reflection.
