### ISSUE TITLE
Document the alias `start` (for Start-Process) in the same way `gci` is documented (for Get-ChildItem)

### ISSUE THREAD

**Issue by b-long** [MicrosoftDocs/PowerShell-Docs#9210]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

Notice, `gci` is documented in the "Notes" section for `Get-ChildItem`: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.2#notes

### Summary

As a PowerShell newcomer, it isn't very clear (e.g. when reading code/documentation) how to get help for `start`.

One might not be aware that it is an alias, and one might not know how to find more information (e.g. `Get-Alias -Name start`) 

### Details

Notice, that `Get-ChildItem` contains this helpful note in [the Notes section](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.2#notes):

> Get-ChildItem can be run using any of the built-in aliases, `ls`, `dir`, and `gci`. For more information, see [about_Aliases](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_aliases?view=powershell-7.2).

### Suggested Fix

* One idea is to mimic the way that `gci` is documented, and _**just**_ update the `Start-Process` page, adding something like this to the Notes section:
   > Start-Process can be run using any of the built-in aliases, such as `start`. For more information, see [about_Aliases](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_aliases?view=powershell-7.2). 
* Another (more significant change), might be updating all pages where a command has an alias.
* Maybe linking to aliased commands to:
   * https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-aliases?view=powershell-7.2 , or
   * https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_aliases?view=powershell-7.2

**Comment by sdwheeler** [comment]
We need to document all the aliases listed at https://github.com/PowerShell/PowerShell/blob/2ec7aea2ec18d8729dfd9d57c321b05dc97a6737/src/System.Management.Automation/engine/InitialSessionState.cs#L4512-L4682 and any aliases exported by the module manifests.
