### ISSUE TITLE
Error when running Set-PSRepository

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/PowerShell-Docs#9218]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.2

> #### After installing PowerShellGet
> After you have installed the new version of PowerShellGet, you should open a new PowerShell session. PowerShell automatically loads the newest version of the module when you use a PowerShellGet cmdlet.
> 
> We also recommend that you register the PowerShell Gallery as a trusted repository. Use the following command:
> 
> ```powershell
> Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
> ```
> 
> For more information, see [Set-PSRepository](https://docs.microsoft.com/en-us/powershell/module/powershellget/set-psrepository?view=powershell-7.2).

### Summary

When running `Set-PSRepository -Name PSGallery -InstallationPolicy Trusted` get a Not Found error.  Did all the steps above, and this is with PowerShell 5.X.

### Details

```
PS C:\WINDOWS\system32> Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Microsoft.PowerShell.Management\Test-Connection : Not found
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:6146 char:22
+ ... connected = Microsoft.PowerShell.Management\Test-Connection -Computer ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-Connection], ManagementException
    + FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand
```

**Comment by michaeltlombardi** [comment]
Hi, @rconiv! This repository is for documentation. You seem to be looking for support, which we can't provide here.

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
