### ISSUE TITLE
Need to add doc for the new `NoRunspaceAffinity` attribute introduced to PowerShell class

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#9231]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.3

### Summary

This should apply to 7.4 and above versions.

See the code PR: 
- https://github.com/PowerShell/PowerShell/pull/18138

Make PowerShell class not affiliate with Runspace when declaring the `NoRunspaceAffinity` attribute.

By default, a PowerShell class is affiliated with the Runspace where it's created. This makes it not work in a parallel workflow, such as `ForEach-Object -Parallel` -- method invocations on the class would be marshalled back to the Runspace it was created, which could cause corruption to the state of that Runsapce or a deadlock. See https://github.com/PowerShell/PowerShell/issues/4003 and https://github.com/PowerShell/PowerShell/issues/3651 for examples.

With this PR, if the attribute `NoRunspaceAffinity` is declared for a PowerShell class, then the PowerShell class will not be affiliated with a particular Runspace/SessionState, and its method invocation (both instance and static) will use the default Runspace of the running thread and its current session state.

Of course, once declaring the attribute to the class, the class implementation should not depend on any states of a particular session state, because there is no guarantee the dependencies would be available at runtime.

### Proposed Content Type

About Topic

### Proposed Title

Should be an update to "about Class"

**Comment by sdwheeler** [comment]
After discussion in Shiproom, we decided that the ///-comment documentation is enough at this time. This is not intended to be used by end user/developers. This is internal to the engine.

**Comment by daxian-dbw** [comment]
> This is not intended to be used by end user/developers. This is internal to the engine.

The `NoRunspaceAffinity` attribute is intended to be used by end users to create a class that has no Runspace affinity, so that it can be used for parallel workflows.

This attribute is added solely for the pain points users run into when using PowerShell class in parallel workflows, such as `ForEach-Object -Parallel`. It will be helpful to have help doc about it to improve the discoverability of this feature.

**Comment by sdwheeler** [comment]
@daxian-dbw Ok, that is not what Steve thought. Can you provide some examples that we can build documentation around?

**Comment by daxian-dbw** [comment]
Here is one example. Please compare the execution of `Foo1` and `Foo2`.
- For `Foo1`, you will see different thread ids are reported, but the reported Runspace id is always the same, and you will see error about corrupted state being reported, such as `Global scope cannot be removed.`.
  - This is because the class is affiliated with Runspace where it's created, and it's always marshalled back to that Runspace for execution by all those different threads, which eventually corrupts the state of the Runspace.
- For `Foo2`, you will see different thread and different Runspace ids are reported, and there is no error.
  - This is because the class has no affinity for any Runspace, and it will run in the default Runspace of a particular thread.

```
# *****************************************
# Foo1: Class definition with Runspace affinity (default behavior)
# *****************************************
class Foo1 {
    static [object] Echo($val) {
        return [PSCustomObject]@{
            ThreadId = [Threading.Thread]::CurrentThread.ManagedThreadId
            RunspaceId = [runspace]::DefaultRunspace.Id
        }
    }
}

$cls = [Foo1]
while ($true) { 
    1..10 | ForEach-Object -Parallel {
        Start-Sleep -ms 100
        ($using:cls)::echo($_) 
    }
}
```

```
# *****************************************
# Foo2: Class definition with NoRunspaceAffinity attribute declared, no Runspace affinity
# *****************************************
[NoRunspaceAffinity()]
class Foo2 {
    static [object] Echo($val) {
        return [PSCustomObject]@{
            ThreadId = [Threading.Thread]::CurrentThread.ManagedThreadId
            RunspaceId = [runspace]::DefaultRunspace.Id
        }
    }
}

$cls = [Foo2]
while ($true) { 
    1..10 | ForEach-Object -Parallel {
        Start-Sleep -ms 100
        ($using:cls)::echo($_) 
    }
}
```

**Comment by kort3x** [comment]
this is the best thing ever.
that's all
