### ISSUE TITLE
May want to call out what to do to invoke a command that derives `PSCmdlet`

### ISSUE THREAD

**Issue by daxian-dbw** [MicrosoftDocs/PowerShell-Docs#9250]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.2

### Summary

As https://github.com/PowerShell/PowerShell/issues/18159 described:

> There's an official article describing how to invoke a Cmdlet from another cmdlet: https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.2
However, it does not describe any way to do the same for PSCmdlet, which I believe is a much more common request

The NOTE message in that page says:
> You can invoke only those cmdlets that derive directly from the [System.Management.Automation.Cmdlet](https://learn.microsoft.com/en-us/dotnet/api/System.Management.Automation.Cmdlet) class. You cannot invoke a cmdlet that derives from the [System.Management.Automation.PSCmdlet](https://learn.microsoft.com/en-us/dotnet/api/System.Management.Automation.PSCmdlet) class.

Maybe we should point to a reference about how to invoke `PSCmdlet` from another `PSCmdlet` here.

### Suggested Fix

See https://github.com/PowerShell/PowerShell/issues/18159#issuecomment-1258583500 and https://github.com/PowerShell/PowerShell/issues/18159#issuecomment-1260188171 (quoted here: "_Broadly speaking, the only practical way to do cmdlets calling cmdlets is to use the Pipeline API._")

**Comment by sdwheeler** [comment]
@daxian-dbw Do we have a doc that shows this? Can you provide an example?

**Comment by sdwheeler** [comment]
Per shiproom discussion @SteveL-MSFT is providing an example.
