### ISSUE TITLE
Switch test for $null and empty string

### ISSUE THREAD

**Issue by RobMahn** [MicrosoftDocs/PowerShell-Docs#9255]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch

I have not confirmed other versions, but assume this has always been the case.

### Summary

The documentation states:

> Notice that the empty string value doesn't match $null but $null matches both $null and an empty string.

Testing reveals that the case for an empty string also matches $null.  A switch statement cannot distinguish between an empty string and $null. 

### Details

Modify the given example like this:

```
$values = '', 5, $null
switch ( $values )
{
    ''      { "Value '$_' is an empty string" ; continue }
    $null   { "Value '$_' is `$null or an empty string" }
    default { "Value [$_] is not an empty string or `$null" }
}

```

The output shows that '' also matches $null and prevents testing for $null:

> Value '' is an empty string
> Value [5] is not an empty string or $null
> Value '' is an empty string
> 

### Suggested Fix

I you must distinguish between empty string and null, use this method:

```
$values = '', 5, $null
switch ( $values )
{
	{ $null -eq $_ }  { "Value '$_' is `$null" ; continue }
    ''      { "Value '$_' is an empty string" }
    default { "Value [$_] is not an empty string or `$null" }
}

```
The successful test output is:

> Value '' is an empty string
> Value [5] is not an empty string or $null
> Value '' is $null

**Comment by sdwheeler** [comment]
@RobMahn The example is written that way on purpose. Notice the next sentence.

> Notice that the empty string value doesn't match $null but $null matches both $null and an empty string.

**Comment by RobMahn** [comment]
Please look again.
"the empty string value doesn't match $null" is an incorrect statement.  My examples show that and empty string does indeed match $null.

And, it would be helpful to show how to manage the desired test to distinguish between $null and an empty string.
