### ISSUE TITLE
🎃 Hacktoberfest 2022

### ISSUE THREAD

**Issue by michaeltlombardi** [MicrosoftDocs/PowerShell-Docs#9257]
This is the meta-issue for [Hacktoberfest 2022][01] and the PowerShell content on [Learn][02]. For the month of October, we're focusing on providing a low-friction way for community members to contribute and collaborate on GitHub through enhancing the quality of documentation.

This Hacktober, we're focusing on the following quality areas:

- [Aliases](#aliases)
- [Formatting code samples](#formatting-code-samples)
- [Formatting command syntax](#formatting-command-syntax)
- [Link References](#link-references)
- [Markdown linting](#markdown-linting)
- [Spelling](#spelling)

<h2 id="project-tracking">Project Tracking</h2>

This Hacktober, we're tracking participation with the [PowerShell Docs Hacktoberfest][03] Github Project.

The project page has several views for the issues and PRs related to this effort:

- The [Open issues][04] view shows all open issues.
- The [Completed][05] view shows merged PRs.
- The [PowerShell][06] view shows open issues for documentation in the [PowerShell-Docs][aa], [PowerShell-Docs-DSC][ab], and [PowerShell-Docs-Modules][ac] repositories.
- The [Windows PowerShell][07] view shows open issues for documentation in the [windows-powershell-docs repository][ae].
- The [Azure PowerShell][08] view shows open issues for documentation in the [azure-docs-powershell repository][ad].
- The [Open PRs][09] view shows all open PRs.

<h2 id="aliases">Aliases</h2>

We're working through documenting the aliases for every cmdlet.

In the Notes section, add the information to the beginning of the section using this format:

   ```markdown
   PowerShell includes the following aliases for `<Cmdlet-Name>`:

   - All platforms:
     - `<alias>`
   - Linux:
     - `<alias>`
   - macOS:
     - `<alias>`
   - Windows:
     - `<alias>`
   ```

If there is more than one alias for a platform, add it on a separate line as a new list item. If a platform has no aliases, omit it from the list.

<h2 id="formatting-code-samples">Formatting code samples</h2>

All code samples should follow the [style guidelines][10] for PowerShell content. Those rules are repeated in abbreviated form here for convenience:

- All code blocks should be contained in a triple-backtick code fence (`` ``` ``).
- Line length for code blocks is limited to `90` characters except in About topics, where it's limited to `76` characters.
- Avoid using line continuation characters (`` ` ``) in PowerShell code examples.
  - Use splatting or natural line break opportunities, like after pipe (`|`) characters, opening braces (`}`), parentheses (`(`), and brackets (`[`) to limit line length.
- Only include the PowerShell prompt for illustrative examples where the code is not intended for copy-pasting.
- Don't use aliases in examples unless you're specifically documenting the alias.
- Avoid using positional parameters. Use the parameter name, even if the parameter is positional.

<h2 id="formatting-command-syntax">Formatting command syntax</h2>

All prose should follow the [style guidelines][11] for PowerShell content. Those rules are repeated here for convenience:

- Always use the full name for cmdlets and parameters. Avoid using aliases unless you're specifically demonstrating the alias.
- Property, parameter, object, type names, class names, class methods should be **bold**.
  - Property and parameter values should be wrapped in backticks (`` ` ``).
  - When referring to types using the bracketed style, use backticks. For example: `[System.Io.FileInfo]`
- PowerShell module names should be **bold**.
- PowerShell keywords and operators should be all lowercase
- Use proper (Pascal) casing for cmdlet names and parameters
- When referring to a parameter by name, the name should be **bold**. When illustrating the use of a parameter with the hyphen prefix, the parameter should be wrapped in backticks.
- When showing example usage of an external command, the example should be wrapped in backticks. Always include the file extension of the external command.

<h2 id="link-references">Link references</h2>

For maintainability and readability of the markdown source for our documentation, we're converting our conceptual documentation to use link references instead of inline links.

For example, instead of:

```markdown
The [Packages tab](https://www.powershellgallery.com/packages) displays all available packages in
the PowerShell Gallery.
```

It should be:

```markdown
The [Packages tab][01] displays all available packages in the PowerShell Gallery.
```

> **Note**
> When you replace an inline link, reflow the content to wrap at 100 characters. You can use the [reflow-markdown][12] VS Code extension to do this quickly.

At the bottom of the file, add a markdown comment before the definition of the links.

```markdown
<!-- Link references -->
[01]: https://www.powershellgallery.com/packages
```

Make sure that:

1. The links are defined in the order they appear in the document.
1. Every link points to the correct location.
1. The link reference definitions are at the bottom of the file after the markdown comment and are in the correct order.

<h2 id="markdown-linting">Markdown linting</h2>

For any article in one of the participating repositories, opening the article in VS Code displays linting warnings. Address any of these warnings you find, except:

- [MD022/blanks-around-headings/blanks-around-headers][13] for the `Synopsis` header in cmdlet reference documents. For those items, the rule violation is intentional to ensure the documentation builds correctly with PlatyPS.

Make now of the line lengths and use the [Reflow Markdown][12] extension to fix any long lines.

<h2 id="spelling">Spelling</h2>

Sometimes, despite our best efforts, typos and misspellings get through and end up in the documentation. These mistakes make documentation harder to follow and localize. Fixing these mistakes makes the documentation more readable, especially for non-English speakers who rely on accurate translations.

<h2 id="process">Process</h2>

You're encouraged to choose one or more of the quality areas and an article (or group of articles) to improve. Once you've decided what articles and content areas you want to work on, follow these steps:

1. Check this issue's history for issues filed for this effort to avoid duplicating efforts.
1. Open a new issue in the appropriate repository:
   - Open an issue in [MicrosoftDocs/PowerShell-Docs][14] for PowerShell reference and conceptual content.
   - Open an issue in [MicrosoftDocs/PowerShell-Docs-Dsc][15] for DSC content
   - Open an issue in [MicrosoftDocs/PowerShell-Docs-Modules][16] for Crescendo, PlatyPS, PSScriptAnalyzer, SecretManagement, and SecretStore content.
   - Open an issue in [MicrosoftDocs/azure-docs-powershell][17] for Azure PowerShell content.
   - Open an issue in [MicrosoftDocs/windows-powershell-docs][18] for Windows PowerShell module content.
1. Follow our [contributor's guide][19] to get setup for making your changes.
1. Submit your pull request. Prefix the title of your pull request with the jackolantern emoji (🎃). The content developers will review your work as soon as they can to help you get it incorporated.

[01]: https://hacktoberfest.com/participation/
[02]: https://learn.microsoft.com/powershell/
[03]: https://github.com/orgs/MicrosoftDocs/projects/15
[04]: https://github.com/orgs/MicrosoftDocs/projects/15/views/1
[05]: https://github.com/orgs/MicrosoftDocs/projects/15/views/2
[06]: https://github.com/orgs/MicrosoftDocs/projects/15/views/3
[07]: https://github.com/orgs/MicrosoftDocs/projects/15/views/4
[08]: https://github.com/orgs/MicrosoftDocs/projects/15/views/5
[09]: https://github.com/orgs/MicrosoftDocs/projects/15/views/6
[10]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide#markdown-for-code-samples
[11]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide#formatting-command-syntax-elements
[12]: https://marketplace.visualstudio.com/items?itemName=marvhen.reflow-markdown
[13]: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022
[14]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/new?template=00-hacktoberfest.yml&title=%F0%9F%8E%83+2022%3A+
[15]: https://github.com/MicrosoftDocs/PowerShell-Docs-Dsc/issues/new?template=00-hacktoberfest.yml&title=%F0%9F%8E%83+2022%3A+
[16]: https://github.com/MicrosoftDocs/PowerShell-Docs-Modules/issues/new?template=00-hacktoberfest.yml&title=%F0%9F%8E%83+2022%3A+
[17]: https://github.com/MicrosoftDocs/azure-docs-powershell/issues/new?template=00-hacktoberfest.yml&title=%F0%9F%8E%83+2022%3A+
[18]: https://github.com/MicrosoftDocs/windows-powershell-docs/issues/new?template=00-hacktoberfest.yml&title=%F0%9F%8E%83+2022%3A+
[19]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview#prepare-to-make-a-contribution
[aa]: https://github.com/MicrosoftDocs/PowerShell-Docs
[ab]: https://github.com/MicrosoftDocs/PowerShell-Docs-Dsc
[ac]: https://github.com/MicrosoftDocs/PowerShell-Docs-Modules
[ad]: https://github.com/MicrosoftDocs/azure-docs-powershell
[ae]: https://github.com/MicrosoftDocs/windows-powershell-docs

**Comment by sdwheeler** [comment]
Hacktoberfest is over but we will still take contributions based on this issue.
