### ISSUE TITLE
Translation is too eager: verbs are translated into Dutch

### ISSUE THREAD

**Issue by PatLuja** [MicrosoftDocs/PowerShell-Docs#9268]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.2#-verb
https://learn.microsoft.com/nl-nl/powershell/module/Microsoft.PowerShell.Management/Start-Process?view=powershell-7.2#-verb

### Summary

The translation into Dutch is a bit too eager. The verbs mentioned in this documentation have also been translated into Dutch. In this way, the source will not work without checking the English reference for the proper verbs.
Also, the word "Verbs" is translated differently in different places.
Furthermore, a dot is lost in the translation of an extension.

### Details

On the English page, you can see a nice overview of several verbs:
![image](https://user-images.githubusercontent.com/36623731/194034345-c37bc27a-5121-42b7-a811-3ee9a91e6caa.png)

The verbs in the overview have also been translated on the Dutch page, while they shouldn't. By the way: some are only half translated; like "PrintTo" became "afdrukkento".
![image](https://user-images.githubusercontent.com/36623731/194034597-61a6208e-6adf-432a-91ef-ebf825deb208.png)
For the instructions to work, the verbs themselves should be in English. Could you please add some tags to prevent these verbs from being translated?

Furthermore, the word "verbs" is correctly translated to "werkwoorden" (verbs) except in the overview where "termen" (terms) is used. This inconsistency might make reading confusing for Dutch readers.

And, in the translation of the extension ".cmd", the dot got lost. :-)

### Suggested Fix

Please, add some tags to the overview to prevent the verbs from being translated.
In the Dutch overview, change the heading "Termen" to "Werkwoorden".
And, correct the extension ".cmd" in the Dutch overview, please.

Thank you kindly.

**Comment by sdwheeler** [comment]
@PatLuja Thanks for the report. I can protect the verbs from being translated. For the "termen" problem I will have to forward this to our translation team to fix.
