### ISSUE TITLE
`Wait-Process` works cross-platform

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#9273]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/wait-process?view=powershell-7.2

### Summary

The docs are wrong that `Wait-Process` doesn't work on Linux and macOS, it is cross-platform compatible

### Suggested Fix

Remove the notice about incompatibility

**Comment by sdwheeler** [comment]
@SteveL-MSFT In what version did this change?
