### ISSUE TITLE
Documentation does not equate for different versions of modules

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#9288]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-7.2
https://learn.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-5.1

### Summary

[This issue](https://github.com/PowerShell/PowerShell/issues/18234) & general browsing of documentation shows that there is a need for documentation also to be module version searchable.

A key example is that `PowerShellGet` which has had significant amount of change over the years & people will be using older versions of the module than the current documentation references to and therefore will require that the documentation for that version is made readily available

### Suggested Fix

This isn't a simple fix & will need lots of effort to correct however users of microsoft created and supported modules that have their documentation published would expect to be able to look at the relevant information for the version of the module that they are using, and not just the latest one, which more often than not, is not the version they are using.

**Comment by sdwheeler** [comment]
@kilasuit Thanks for the issue. Unfortunately, we don't support PowerShellGet v1.0.0.1 that ships in Windows. You must upgrade to the current 2.x version.

See https://learn.microsoft.com/powershell/scripting/gallery/installing-psget

> Windows PowerShell 5.1 comes with version 1.0.0.1 of PowerShellGet preinstalled. This version of PowerShellGet has a limited features and doesn't support the updated capabilities of the PowerShell Gallery. To be supported, you must update to the latest version.
