### ISSUE TITLE
Doc new `-FuzzyMinimumDistance` parameter on `Get-Command`

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#9302]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

New `-FuzzyMinimumDistance` parameter allows filtering fuzzy results to be more or less accurate.  The distance is specifically for the Damerau Levenshtein Distance algorithm which indicates how many steps is the match from the original value.  So a lower distance is more accurate.  A distance of zero would be an exact match.

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/18261

### Related Source Issues

None

**Comment by sdwheeler** [comment]
@SteveL-MSFT Is this an experimental feature? Does it require the new subsystem? I assume this would be targeted for a 7.4 preview release.
