### ISSUE TITLE
PowerShell SDK: Creating out of process runspaces sample

### ISSUE THREAD

**Issue by Aculeo** [MicrosoftDocs/PowerShell-Docs#9306]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.2

### Summary

As a user of the PowerShell SDK I need a sample to create out of process runspaces so I can create runspaces with a different PowerShell version

### Details

There is no documentation for `RunspaceFactory.CreateOutOfProcessRunspace()`, but there are plenty of samples for the other methods. What I would like to understand is this:

**1) What are the supported scenarios?**
    For example, can this be used to run PowerShell 5.1 scripts from a PowerShell 7.2 host application? Because this is actually my use case (have to run PowerShell 5.1 scripts from a .NET 6 application, but I need the PSObjects so I cannot use `Process.Start()`). From what I can see it works, but I don't know if this is a good idea or if there are edge cases it does not support.
    Also, what about the other way around - running PS7 scripts from, a PS6 SDK?
**2) What is the parameter typeTable for?** There is no sample available for this method, and all I've seen is people using an empty array. I have no idea what is expected here. In fact just searching for this method on Google only returns me 75 results.
**3) And regarding PowerShellInstance parameter, what is the `bool useWow64` for?** What effect does this have on the scripts being executed?

### Proposed Content Type

Other / Unknown

### Proposed Title

Out of Process Runspaces

### Related Articles

Existing docs for runspaces: https://learn.microsoft.com/en-us/powershell/scripting/developer/hosting/creating-runspaces?view=powershell-7.2

**Comment by sdwheeler** [comment]
@daxian-dbw Can you comment on this issue?

**Comment by daxian-dbw** [comment]
> can this be used to run PowerShell 5.1 scripts from a PowerShell 7.2 host application?

Yes, it supports creating an out-of-process Runspace targeting Windows PowerShell 5.1. That's how the [Windows PowerShell Compatibility](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7.2) feature works in PowerShell Core.

> what about the other way around - running PS7 scripts from, a PS6 SDK?

This is not supported. For out-of-process Runspace, you can either targeting WinPS 5.1, or the same `pwsh.exe` that you are using.

> What is the parameter typeTable for?

The XML document for `typeTable` is missing for `CreateOutOfProcessRunspace`, but it's the same as in the `typeTable` parameter for [CreateRunspace](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.runspacefactory.createrunspace?view=powershellsdk-7.0.0#system-management-automation-runspaces-runspacefactory-createrunspace(system-management-automation-runspaces-runspaceconnectioninfo-system-management-automation-host-pshost-system-management-automation-runspaces-typetable-system-management-automation-psprimitivedictionary-system-string)).

BTW @sdwheeler, the doc is a little off regarding that parameter. It's XML doc is https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/ConnectionFactory.cs#L480-L489, but the rendering in the doc is wrong.

> And regarding PowerShellInstance parameter, what is the bool useWow64 for?

`useWow64` is only applicable when targeting WinPS 5.1, meaning it will use the 32-bit powershell process.

@sdwheeler The XML doc for the constructor of `PowerShellInstance` is missing. XML doc is available in code:
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/PowerShellProcessInstance.cs#L46-L54

**Comment by sdwheeler** [comment]
> The XML doc for the constructor of `PowerShellInstance` is missing. XML doc is available in code

@daxian-dbw There needs to be a `Documentation Needed` issue opened in the source code repo to fix the XML docs.

**Comment by daxian-dbw** [comment]
> just one weird issue we encountered is that an object sent into PS (with out of process run space) as an argument ended up being incomplete at it seems the serialization is only 1 level deep

Do you mean when sending the argument to the out-of-process session the serialization depth is too small?
If that's the case, then you need to increase the serialization depth on the client side, by running
```
Update-TypeData -TypeName <type-of-the-argument-you-work-with> -SerializationDepth 3 ## use 3 level depth maybe
```

If the serialization depth issue happens when data is sent from the remote end, then do the above on the remote side.

**Comment by daxian-dbw** [comment]
@sdwheeler The related XML docs will be updated with https://github.com/PowerShell/PowerShell/pull/18450.
