### ISSUE TITLE
Document that `Select-Object`, `Sort-Object` and `Group-Object` handle HashTable Properties in PowerShell 6+

### ISSUE THREAD

**Issue by KyleMit** [MicrosoftDocs/PowerShell-Docs#9311]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

* https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Select-Object
* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object

### Summary

There's new, undocumented behavior when using `Select-Object` against a hashtable, I believe beginning in v7

In v5, when selecting hashtable properties, you may only select properties that exist on the hashtable object itself.
In v7+, the hash table is converted to a `PSObject` first, so the properties are available to the select object method.

### Command

```ps1
@{Environment="Test"} | Select-Object -Property *
```

#### Output in PS5

```ps1
IsReadOnly     : False
IsFixedSize    : False
IsSynchronized : False
Keys           : {Environment}
Values         : {Test}
SyncRoot       : System.Object
Count          : 1
```

#### Output in PS7

```ps1
Environment
-----------
Test
```

### Command

```ps1
@{Environment="Test"} | Select-Object -ExpandProperty Environment
```

#### Output in PS5

```ps1
Select-Object : Property "Environment" cannot be found.
At line:1 char:25
+ @{Environment="Test"} | Select-Object -ExpandProperty Environment
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (System.Collections.Hashtable:PSObject) [Select-Object], PSArgumentException
+ FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand
```

#### Output in PS7

```ps1
Test
```

### Details

This behavior was introduced by this [section of code in `Mshexpression.cs`](https://github.com/PowerShell/PowerShell/blob/88ca29235c56d68d7d1b544a6d7994cbbcec267b/src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs#L161-L163):

```cs
// If the object passed in is a hashtable, then turn it into a PSCustomObject so
// that property expressions can work on it.
var wrappedTarget = IfHashtableWrapAsPSCustomObject(target, out bool wasHashtable);
```

* There was originally a PS issue:

    PowerShell/PowerShell/issues/6855
    
* Which was addressed via this PR:

    PowerShell/PowerShell/pull/6934

* Which was release in [**v6.1.0-preview.4**](https://github.com/PowerShell/PowerShell/releases/tag/v6.1.0-preview.4)
    
* Which got tagged as **Documentation Needed** which opened this issue:

    #3034
    
* Which was closed by this PR:

    #3565

### Suggested Fix

While the named scope of the issue/PR that made the changes was focused on `Measure-Object`, the changes also impacted `Sort-Object` and `Select-Object`.

It'd be nice to (retroactively) see this highlighted in the change notes as a point of reference for the introduction.

But also, just adding an example to the `Select-Object` and `Sort-Object` docs pages would be helpful as well

I can propose the changes via PR if this seems like the right course of action.  

Does it need to get updated for each of the existing versions of 7.X since the changes are being made retroactively?

* [`Select-Object.md` (**v7.0**)](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.0/Microsoft.PowerShell.Utility/Select-Object.md)
* [`Select-Object.md` (**v7.2**)](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md)
* [`Select-Object.md` (**v7.3** )](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Utility/Select-Object.md)

**Comment by michaeltlombardi** [comment]
@KyleMit Thanks so much for catching and reporting this! I'll get this addressed across all versions since this behavior change landed in 6x.
