### ISSUE TITLE
🎃 2022: Update Link References in docs-conceptual root Markdown files 

### ISSUE THREAD

**Issue by chadmando** [MicrosoftDocs/PowerShell-Docs#9314]
This issue's related to [Hacktoberfest 2022][01]. For more info, see the meta-issue below:

- MicrosoftDocs/PowerShell-Docs#9257

[01]: https://hacktoberfest.com/participation/

### Prerequisites

- [X] **Existing Issue:** Search the existing Hacktoberfest issues for this repository. If there's an issue that covers the quality area and articles you want to improve, pick a different quality area or article set. Don't file a new issue for the same work. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "🎃 2022: Command Syntax in Foo" instead of "🎃 2022: Foo"

### Quality Areas

Link References

### Article List

Limiting the scope to the markdown files in the /reference/docs-conceptual root based on this discussion:
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257#issuecomment-1276343704

Files to be addressed in this Issue:
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/discover-powershell.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/how-to-use-docs.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/overview.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/powershell-commands.md

**Comment by michaeltlombardi** [comment]
@chadmando thanks so much for filing this issue and volunteering to take care of this! Deeply appreciate your participation this Hacktoberfest! 🎃💜

**Comment by pankaj892** [comment]
@chadmando and @michaeltlombardi if I am not wrong I need to update the link references to the numerical format or is there more work to be done on those files ?
If its just updating link references I can take up this issue.

**Comment by sdwheeler** [comment]
@pankaj892 The idea of our Hacktoberfest workflow is that you create your own issue listing the files you are going to work. @chadmando should already be working on a PR for this.

Feel free to submit your own Hacktoberfest issue to work on some other content. There are a lot more articles in docs-conceptual that need links converted to link references.

**Comment by pankaj892** [comment]
@sdwheeler I am so sorry I thought this was an open issue and there was no one contributing to it currently. Sorry for the confusion.
