### ISSUE TITLE
PowerShell v7.3.x will not support Windows 7 from the next release

### ISSUE THREAD

**Issue by adityapatwardhan** [MicrosoftDocs/PowerShell-Docs#9322]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

We are removing support for Windows 7 from PowerShell 7.3.x. The lowest OS supported will be Windows 8.1, for both x64 and x86.

### Details

NA

### Articles

NA

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/18304

### Related Source Issues

No issue filed

**Comment by sdwheeler** [comment]
Fixed
