### ISSUE TITLE
Document new cd~

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#9329]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

New `cd~` created in related PR in addtions to `cd..` and `cd\`.

### Articles

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/18308

### Related Source Issues

- https://github.com/PowerShell/PowerShell/issues/17140

**Comment by sdwheeler** [comment]
Saving this text for a new PR when 7.4-preview is available.

```
## `cd~`

In the Windows CMD shell it is common to run the `cd` command without any spaces
between the command and the destination path. This function runs
`Set-Location ~` to change to the user's home folder.
```
