### ISSUE TITLE
Get-Command -Parameter CommandType: missing carriage return only on console view

### ISSUE THREAD

**Issue by Raton-Laveur** [MicrosoftDocs/PowerShell-Docs#9330]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/Get-Command.md

### Summary

Value `All` is not showing up on a new line in console view, though online version is correctly formatted. 

### Details

- `Get-Help Get-Command -Parameter CommandType` : -Alias and -All are showing up on the same bulleted section. -All should be shown on a new bullet point. 
-- See included screenshot

- Online version (https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-7.2&WT.mc_id=ps-gethelp&source=docs) ang GitHub view of section ParameterType are  correctly formatted with `- All` correcty showing up on a new line. 

### Suggested Fix

![Capture d’écran 2022-10-19 195338](https://user-images.githubusercontent.com/17532038/196767842-51d48214-ae87-4553-9a57-37ffc1afcf2e.png)

**Comment by sdwheeler** [comment]
This is a known issue with the tool that converts the markdown to MAML format. I think I can fix this but, ultimately the tool needs to be fixed. We are working on fixing the tool, but that release is still far away.
