### ISSUE TITLE
Calling PSCmdlet example has poor performance

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#9335]
> @sdwheeler In the article, the PowerShell class is used. From my tests, the invocation is quite slow that way. In the meantime, I found another way to invoke a PSCmdlet:
> 
> ```powershell
> function fn {
>     [CmdletBinding()]param()
>     $ss = $PSCmdlet.SessionState
>     $ss.InvokeCommand.InvokeScript($ss, [ScriptBlock]::Create('Get-Clipboard -Raw'))
> }
> ```
> 
> (it works the same from a C# binary cmdlet)
> 
> This way of invoking `Get-Clipboard` is about 5 times faster for me (2ms vs 10ms for the `PowerShell.Create` approach). Am I missing any downside of this approach?

The doc should be using `PowerShell.Create(RunspaceMode.CurrentRunspace)`. That's likely the problem you're hitting in your benchmark, because otherwise it spins up a new runspace for every invocation.

_Originally posted by @SeeminglyScience in https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9279#issuecomment-1285989979_

**Comment by SeeminglyScience** [comment]
I'm prepping a PR with changes there and a few other suggestions. Should be ready shortly
