### ISSUE TITLE
PowerShell Gallery Package Manifest: mixed keywords in script metadata descriptions

### ISSUE THREAD

**Issue by peetrike** [MicrosoftDocs/PowerShell-Docs#9340]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/powershell/scripting/gallery/concepts/package-manifest-affecting-ui#powershell-gallery-feature-elements-controlled-by-the-script-metadata
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/gallery/concepts/package-manifest-affecting-ui.md

### Summary

The descriptions of License and Project Site keywords have been misplaced.

In addition, this topic talks about license acceptance.  But license acceptance is [not supported](https://learn.microsoft.com/powershell/scripting/gallery/concepts/script-license-acceptance) under scripts.

### Details

`.LICENSEURI` is mentioned under **Project Site** and `.PROJECTURI` is mentioned in **License** description.

### Suggested Fix

Switch mixed keywords and remove **Require license acceptance** description (from script metadata)

**Comment by michaeltlombardi** [comment]
Thanks for submitting this bug, @peetrike!
