### ISSUE TITLE
WMF 4 404 Not Found

### ISSUE THREAD

**Issue by potatoqualitee** [MicrosoftDocs/PowerShell-Docs#9342]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/overview?view=powershell-7.2

https://support.microsoft.com/en-us/topic/description-of-wmf-4-0-for-windows-7-sp1-windows-embedded-standard-7-sp1-and-windows-server-2008-r2-sp1-e3c830c7-269a-8ae0-d7e9-5ab4a0c37484

### Summary

I am looking for WMF 4.0 and cannot find it. I had to resort to https://web.archive.org/web/20190122054112if_/https://download.microsoft.com/download/3/D/6/3D61D262-8549-4769-A660-230B67E15B25/Windows6.1-KB2819745-x64-MultiPkg.msu per the closed issue https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4233

People are recommending we download WMF 4 from random places, which seems more dangerous than a SHA-1 signed file https://learn.microsoft.com/en-us/answers/questions/653866/where-is-download-for-windows-management-framework.html

### Details

I'm hoping that opening this issue will resurface the importance of providing a valid link to WMF 4 so that the community doesn't have to resort to non-official sources.

### Suggested Fix

Add back the link or create a new one with SHA-256 signed file.

**Comment by sdwheeler** [comment]
We can't restore the SHA-1 package and we have tried getting the package resigned with SHA-256.
