### ISSUE TITLE
🎃 2022: Add Alias notes section for *-Alias cmdlets

### ISSUE THREAD

**Issue by ehmiiz** [MicrosoftDocs/PowerShell-Docs#9345]
This issue's related to [Hacktoberfest 2022][01]. For more info, see the meta-issue below:

- MicrosoftDocs/PowerShell-Docs#9257

[01]: https://hacktoberfest.com/participation/

### Prerequisites

- [X] **Existing Issue:** Search the existing Hacktoberfest issues for this repository. If there's an issue that covers the quality area and articles you want to improve, pick a different quality area or article set. Don't file a new issue for the same work. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "🎃 2022: Command Syntax in Foo" instead of "🎃 2022: Foo"

### Quality Areas

Aliases

### Article List

reference\5.1\Microsoft.PowerShell.Utility\Get-Alias.md
reference\5.1\Microsoft.PowerShell.Utility\Set-Alias.md
reference\5.1\Microsoft.PowerShell.Utility\New-Alias.md
reference\5.1\Microsoft.PowerShell.Utility\Import-Alias.md
reference\5.1\Microsoft.PowerShell.Utility\Export-Alias.md

**Comment by michaeltlombardi** [comment]
Resolved in #9344
