### ISSUE TITLE
Official Documentation on the .psd1 Powershell Data File Format

### ISSUE THREAD

**Issue by SeidChr** [MicrosoftDocs/PowerShell-Docs#9356]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.3

### Summary

Besides the description of how a module manifest has to look like, there seems to be hardly any documentation on how exactly the powershell data file needs to be formatted, and what mode is used when the files are loaded.

Trigger for this ticket was a thread in the powershell discord: https://discord.com/channels/180528040881815552/1034501153947385856

### Details

Please write some elaborate documentation for data files and how exactly the data is handled when they are imported using the several commands like Import-PowershellDataFile or Import-LocalizedData

### Proposed Content Type

About Topic

### Proposed Title

about_PowerShell_Data_Files

### Related Articles

- https://discord.com/channels/180528040881815552/1034501153947385856
- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-powershelldatafile?view=powershell-7.2
- https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_language_modes#restricted-language-restrictedlanguage
- https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/
- http://ramblingcookiemonster.github.io/PowerShell-Configuration-Data/

**Comment by sdwheeler** [comment]
Research notes

Import-PowerShellDataFile
- no code or expressions - constants only
- must be a hashtable

Import-LocalizedData
- Loaded in Constrained language mode
- Not required to be a hashtable
- Same as DATA sections

Import-Module
- Loaded in Restricted language mode
  - Allowed commands
    - Import-LocalizedData
    - ConvertFrom-StringData
    - Write-Host
    - Out-Host
    - Join-Path
  - Allowed variables
    - $PSScriptRoot
    - $PSEdition
    - $EnabledExperimentalFeatures
