### ISSUE TITLE
`Invoke-Command`: Example for SessionOption doesn't work

### ISSUE THREAD

**Issue by rileysea** [MicrosoftDocs/PowerShell-Docs#9357]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/powershell/module/microsoft.powershell.core/invoke-command#example-18-start-scripts-on-many-remote-computers

### Summary

Example 18 on the Invoke Command page is not valid.

```powershell
$parameters = @{
  ComputerName = (Get-Content -Path C:\Test\Servers.txt)
  InDisconnectedSession = $true
  FilePath = "\\Scripts\Public\ConfigInventory.ps1"
  ------>SessionOption = @{OutputBufferingMode="Drop";IdleTimeout=43200000}
}
Invoke-Command @parameters
```

Tested on PowerShell 5.1 & 7.2.5 for Windows 10.

The command does not accept the hashtable. You can see related correspondence on this StackOverflow post https://stackoverflow.com/questions/57930750/invoke-command-indisconnectedsession-sessionoption-and-idletimeout-one-liner

### Details

Error thrown:
```
    $parameters = @{
        ComputerName = $foo
        InDisconnectedSession = $true
        Scriptblock = $somescriptblock
        ThrottleLimit = 50
        SessionOption = @{OutputBufferingMode="Drop";IdleTimeout=300000}
    }
    Invoke-Command @parameters -verbose

Invoke-Command : The specified IdleTimeout session option 0 (seconds) is not a valid period.  Specify an IdleTimeout value that is greater than or equal to the minimum allowed 60 (seconds).
At C:\Users\....\somescript.ps1:85 char:5
+     Invoke-Command @parameters -verbose
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Command], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.InvokeCommandCommand
```

However, running this worked:
```
Invoke-Command -SessionOption (New-PSSessionOption -OutputBufferingMode "Drop" -IdleTimeout 300000)
```

### Suggested Fix

Remove example 18 from the documentation or clarify usage of a Hash Table for the `-SessionOption` parameter.

**Comment by sdwheeler** [comment]
This is actually a bug specific to **IdleTimeout** property when the cmdlet converts the hashtable passed to `-SessionOption`. The cmdlet is expecting **IdleTimeout** to be a `[TimeSpan]` object. For the conversion to work you must specific the integer value in ticks (ms * 1000). So the following should work:

```powershell
$parameters = @{
        ComputerName = $foo
        InDisconnectedSession = $true
        Scriptblock = $somescriptblock
        ThrottleLimit = 50
        SessionOption = @{OutputBufferingMode="Drop"; IdleTimeout=[timespan]::FromSeconds(300)}
    }
```

**Comment by rileysea** [comment]
> This is behaving as expected. The issue is that all time values in a **PSSessionOption** object are `[TimeSpan]` types. You must specify the **IdleTimeout** value in ticks (ms * 1000) or use a conversion method of the **TimeSpan** class for the conversion from hashtable to work.
> 
> ```powershell
> $parameters = @{
>         ComputerName = $foo
>         InDisconnectedSession = $true
>         Scriptblock = $somescriptblock
>         ThrottleLimit = 50
>         SessionOption = @{OutputBufferingMode="Drop"; IdleTimeout=[timespan]::FromSeconds(300)}
>     }
> ```

Thanks - so it was a data type issue. If that's the case, can you update the documentation then with the example you just posted so that customers are aware of that data type requirement?

**Comment by sdwheeler** [comment]
That's the plan.

**Comment by rileysea** [comment]
Right on, I appreciate the quick response @sdwheeler !
