### ISSUE TITLE
ExpandString: Add links to more information

### ISSUE THREAD

**Issue by krlinus** [MicrosoftDocs/PowerShell-Docs#9410]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-string-substitutions?view=powershell-7.2

### Summary

You have covered a scenario like this:

```
$mystring='embedding a variable $var1'
$var1=10
$ExecutionContext.InvokeCommand.ExpandString($mystring)
```

in the case of this:

```
$mystring='embedding a variable $var2'
$ExecutionContext.InvokeCommand.ExpandString($mystring)
```
it will print

```
embedding a variable 
```

What if I wanted it to leave the $var2 alone and not substitute with a blank? Is there an option, and if so could you please include that documentation?

A more general comment - is there a more specialized page for each of these topics that covers fully comprehensively? It would be nice to have a link as it would facilitate my learning

Thanks!

**Comment by michaeltlombardi** [comment]
I'm not sure I understand. Can you restate that for me with some additional information?

What I think you're asking is

> How can I write the string `'embedding a variable $var2'` to the output stream _without_ replacing the value of `$var2` with its actual value?
> 
> When I use `$ExecutionContext.InvokeCommand.ExpandString` and `$var2` is empty or undefined, I get the output `embedding a variable `.

If so, the way to do this is with control logic. Here's a snippet that uses your example:

```powershell
$mystring = 'embedding a variable $var2'

if (![string]::IsNullOrEmpty($var2)) {
  $ExecutionContext.InvokeCommand.ExpandString($mystring)
} else {
  "Unexpanded string: '$mystring'"
} 
```

This outputs:

```text
Unexpanded string: 'embedding a variable $var2'
```

Does that help?

> A more general comment - is there a more specialized page for each of these topics that covers fully comprehensively? It would be nice to have a link as it would facilitate my learning

You're right, this page could certainly be updated to include links to the referenced sections. Here's that list now, to help you in the meantime:

- Concatenation uses the [addition operator][01]
- Variable and command substitution follow the [quoting rules][02]
- Formatting uses the [format operator][03]
- Joining strings uses the [join operator][04] and references [`Join-Path][05], but you could also read about [`Join-String`][06]
- Arrays are documented in [About arrays][07]
- StringBuilder is a .NET class, with its [own documentation][08]
- Braces in strings is also covered in the [quoting rules][02]
- Token replacement uses the [replace operator][09]
- The `$ExecutionContext.InvokeCommand.ExpandString()` method has [.NET API reference documentation][10]

[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_arithmetic_operators#adding-and-multiplying-non-numeric-types
[02]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_quoting_rules
[03]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_operators#format-operator--f
[04]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_join
[05]: https://learn.microsoft.com/powershell/module/microsoft.powershell.management/join-path
[06]: https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/join-string
[07]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_arrays
[08]: https://learn.microsoft.com/dotnet/api/system.text.stringbuilder
[09]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_comparison_operators#replacement-operator
[10]: https://learn.microsoft.com/dotnet/api/system.management.automation.commandinvocationintrinsics.expandstring
