### ISSUE TITLE
-Disconnected parameter for Invoke-Command appears undocumented

### ISSUE THREAD

**Issue by wisemoth** [MicrosoftDocs/PowerShell-Docs#9423]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/Invoke-Command.md

### Summary

It appears that `invoke-command` has a `-Disconnected` parameter.  I was attempting to read how this might differ from the `InDisconnectedSession` parameter, but while the latter has documentation, the former appears not to.

### Details

```
> get-help Invoke-Command -Parameter indisconnectedsession

-InDisconnectedSession

    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           ComputerName, FilePathComputerName, Uri, FilePathUri
    Aliases                      Disconnected
    Dynamic?                     false
    Accept wildcard characters?  false
```

```
> get-help Invoke-Command -Parameter disconnected
Get-Help: No parameter matches criteria disconnected.
```

However, type `invoke-command -disc<press tab>` shows the parameter.

**Comment by wisemoth** [comment]
ie my eye was scanning through the `get-help` for `-Disconnected` and didn't see it.  I imagine this might have been discussed before, but could the `get-help` output actually show the alias'd parameters something like:
`-Disconnected : alias, see InDisconnectedSession`

**Comment by michaeltlombardi** [comment]
> I imagine this might have been discussed before, but could the `get-help` output actually show the alias'd parameters something like: `-Disconnected : alias, see InDisconnectedSession`

This seems like a really useful feature request, @wisemoth! Unfortunately, this repository is only for tracking work on the documentation itself, and an update to `Get-Help` will need to be [filed as a feature request][1] in the PowerShell/PowerShell repository.

I'm going to close this issue for now since the documentation content is correct.

[1]: https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Issue-Enhancement%2CNeeds-Triage&template=Feature_Request.yaml
