### ISSUE TITLE
Following documentation on installing PowerShell on Raspberry Pi not working 

### ISSUE THREAD

**Issue by mrasmussen72** [MicrosoftDocs/PowerShell-Docs#9430]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/install-raspbian?view=powershell-7.2

### Summary

Issue:
Following the steps outlined in
[Installing PowerShell on Raspberry Pi OS - PowerShell | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/scripting/install/install-raspbian?view=powershell-7.2)
Doesn’t result in a successful install of PowerShell.  Here are the steps I took to successfully install and run PowerShell on Raspberry Pi

1. Download the version that matches your architecture.  My RPi installation is arm64 so I had to find that.  The documents example is arm32, arm64 is tough to find, might make sense to make a note other architectures are available.  I see the releases link, but links to text, not actual links.
2. When installing the prerequisites there is a typo on the regular expression.  
   `^libssl1.0.[0-9]$` – this is the regular expression that’s currently in the docs, it should be `^libssl1.[0-9]$`
      
   if you run apt search `^libssl1.[0-9]$` you will see the correct results.
3. After I unpack powershell-7.3.0-linux-arm64.tar.gz into the newly created PowerShell directory, I see the file pwsh but I am not able to execute it.  If I run
   ```sh
   chmod +x ~/powershell/pwsh
   ```
4. then start PowerShell with
   ```sh
   sudo ~/powershell/pwsh
   ```
5. I then see the PowerShell prompt and I can run things like Get-Command.

### Details

the summary contains all details.

**Comment by sdwheeler** [comment]
`sudo` is not needed unless you want to run with elevated permissions. The need to run `chmod` is a regression that is being investigated.

**Comment by sdwheeler** [comment]
See related bugs:
- https://github.com/PowerShell/PowerShell/issues/18510
- https://github.com/PowerShell/PowerShell/issues/18495

Thisis only affecting tar.gz deployments. The fix is to use `chmod`. This will be fixed in the next release.
