### ISSUE TITLE
`exec` is now a function and not an alias

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#9444]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/switch-process?view=powershell-7.3
- https://github.com/PowerShell/PowerShell/pull/18567
### Summary

To fix an issue with the `exec` built-in, it needed to be changed from an alias to a function.  The current docs reference `exec` as an alias and should be changed to a function.

**Comment by sdwheeler** [comment]
`exec` is now a function that wraps `Switch-Process`.

**Comment by sdwheeler** [comment]
Closed by #9600 9600
