### ISSUE TITLE
Add documentation for using scripts installed by `Install-Script`

### ISSUE THREAD

**Issue by totkeks** [MicrosoftDocs/PowerShell-Docs#9462]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.0, 7.2, 7.3

### Summary

As a user of `PowerShellGet`, I need a document about using scripts installed by `Install-Script`, so that I can easily use them.

### Details

I was looking for a way to store my scripts that my profile uses, but that also provide value when used standalone.
What I found was that there is a predefined path in `$PSGetPath.CurrentUserScripts`, but it does not behave similarly to the `$env:PSModulePath`, in that installed scripts are not auto-located in that directory to be used in the command line.

What I would imagine is a documentation or an example configuration of certain environment variables or profile fragments, that allow me to use those scripts from the command line after installing them via `Install-Script` or manually placing them in the `$PSGetPath.CurrentUserScripts` directory.
It should behave similarly to `Install-Module` which detects all available modules in the system.

While typing I had the thought that it might be enough to just add the `$PSGetPath.CurrentUserScripts` to my `$env:Path` to have those scripts available. But even this simple solution would be helpful if documented nearby the `Install-Script` cmdlet or the top level module `PowerShellGet`.

### Proposed Content Type

Cmdlet Reference

### Related Articles

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.3

**Comment by michaeltlombardi** [comment]
@totkeks are you looking for more detailed information than covered in the [examples for `Install-Script`][01] that show using [`Get-InstalledScript`][02]?

With the **Microsoft.PowerShell.Commands.PSRepositoryItemInfo** object you get back from `Get-InstalledScript`, you can see the **InstalledLocation** property and use it to run the script like any other:

```powershell
Get-InstalledScript | Select-Object Name, InstalledLocation
```

If you're looking for functionality to more readily manage installed scripts, I think you'll want to [file an issue][03] with the PowerShell team.

[01]: https://learn.microsoft.com/powershell/module/powershellget/install-script#example-1-find-a-script-and-install-it
[02]: https://learn.microsoft.com/powershell/module/powershellget/get-installedscript
[03]: https://aka.ms/psfeedback

**Comment by ohadschn** [comment]
@michaeltlombardi as far as I can tell, the `PSGetPath` variable isn't documented at all...
