### ISSUE TITLE
Add an `about_` document describing enumeration in general

### ISSUE THREAD

**Issue by SeeminglyScience** [MicrosoftDocs/PowerShell-Docs#9467]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1, 7.0, 7.2, 7.3

### Summary

Something that very commonly comes up with folks new to PowerShell is implicit output enumeration and unwrapping. It would be nice to have a high level document that explains that it happens, and explains how PowerShell makes it easy to not care if you have a scalar, an array, or nothing.

### Details

Some bullet points worth covering:

- Mechanics of unwrapping scalars and grouping output
    - `$a = & { @(10) }` <- `$a` will be 10, not an array with a single item
    - `$a = if ($true) { 10; 20; @(30, 40) }` <-- `$a` will be a single flattened array with the items `10`, `20`, `30`, and `40`
- When enumeration occurs
    - Command output (including `& { }`, functions, cmdlets, etc)
    - statement assignment (e.g. `$a = if ($true) { @(10) }`)
    - sub/array expression (`$()` and `@()`
- How the PowerShell makes it less important if you have an array vs a scalar
    - Both can be passed via the pipeline
    - Scalars can be indexed (`$a = 10; $a[0]` does not throw)
    - `.Count` engine intrinsic property
    - Member access enumeration
    - `foreach` and `switch` handle both scalars and arrays (ty @Szeraax!)

### Proposed Content Type

About Topic

### Proposed Title

about_Implicit_Enumeration

### Related Articles

- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/884b5bf28b1cdd53ec426aa408bb93c9007a5a3a/reference/7.3/Microsoft.PowerShell.Core/About/about_Arrays.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/884b5bf28b1cdd53ec426aa408bb93c9007a5a3a/reference/7.3/Microsoft.PowerShell.Core/About/about_Pipelines.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/884b5bf28b1cdd53ec426aa408bb93c9007a5a3a/reference/7.3/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md

**Comment by sdwheeler** [comment]
I believe that this all covered in [about_Arrays][01] and [about_Member-Access_Enumeration][02]. If not, what is missing? 

[01]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_arrays
[02]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_member-access_enumeration

**Comment by sdwheeler** [comment]
@SeeminglyScience This seems like a deep dive topic not an about_ topic. All the information you cited is covered in the existing documents. There is just not one document that summarizes it all.

**Comment by SeeminglyScience** [comment]
Bits and pieces are in a few documents for sure. I'll definitely defer to you on what type of document it should be, as long as there's a good place to send folks to.

**Comment by sdwheeler** [comment]
The real question is "What problem are you trying to solve with a new document?"

If you can come up with a compelling problem that needs solving then we can think about creating a new document.
