### ISSUE TITLE
Document PSObject.Properties order guarantees (specifically when deserialized by ConvertFrom-XXX)

### ISSUE THREAD

**Issue by ohads-MSFT** [MicrosoftDocs/PowerShell-Docs#9472]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

1. https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-member?view=powershell-7.3
2. https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.psobject.properties?view=powershellsdk-1.1.0
3. https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.3

### Summary

It appears that `PSObject.Properties` enumeration order is guaranteed to be consistent with the order in which the properties were added to the object (specifically via `Add-Member`), however this fact does not seem to be documented anywhere.

Specifically, this order seems to be deliberately maintained when deserializing (for example [ConvertFrom-Json](https://github.com/PowerShell/PowerShell/blob/20f0b6e3bd6b357def7a0e0c135150f9b61755f6/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs#L331)) but again, undocumented as far as I can tell. Ironically, since PowerShell 7.3 the docs do mention the returned HashSet is guaranteed to be ordered, but no reference is made to the resulting PSObject property order (which presumably has been ordered since day one).

### Suggested Fix

Add order guarantees to the linked documentation pages (and possibly others if applicable, e.g. other ConvertFrom-XXX CmdLets).

**Comment by sdwheeler** [comment]
@ohads-MSFT I think you are confusing property enumeration of an object with item enumeration of a collection. 

A hashtable is an unordered collection. The change we made in PowerShell 7.3 for `ConvertFrom-Json` was to use an ordered dictionary when converting JSON to a hashtable. This guarantees that the key-value pairs in the hashtable are ordered as written in the JSON.

Members of an object are always ordered. This is not specific to PowerShell but it is how the underlying .NET object model works.

**Comment by ohads-MSFT** [comment]
@sdwheeler 

> Members of an object are always ordered. This is not specific to PowerShell but it is how the underlying .NET object model works.
By the "underlying .NET object model" are you referring to `PSObject`? Because again, nothing is mentioned about the order in the docs: https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.psobject.properties?view=powershellsdk-1.1.0

Also, even if the above were documented, nothing says that order would be the same as the order in the JSON document (or XML, or any other `ConvertFrom-XXX`)...

**Comment by sdwheeler** [comment]
> By the "underlying .NET object model" are you referring to `PSObject`?

No, the order of properties for any object in .NET is guaranteed to be the order you declared or added them. 

When you use `ConvertFrom-Json` to convert to a PSObject, the key-value pairs become properties of the object, so they are guaranteed to be ordered as written in the JSON. When you use `ConvertFrom-Json` to convert to a hashtable, the key-value pairs are not guaranteed to be ordered (unless you use the `[ordered]` type).

All of the other `ConvertFrom-xxx` formats are ordered types.

**Comment by ohads-MSFT** [comment]
> No, the order of properties for any object in .NET is guaranteed to be the order you declared or added them.

I'm not sure what you mean, to the extent that .NET objects even have order, it is not guaranteed: 
https://learn.microsoft.com/en-us/dotnet/api/system.type.getproperties?view=net-6.0
> The [GetProperties](https://learn.microsoft.com/en-us/dotnet/api/system.type.getproperties?view=net-6.0) method does not return properties in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which properties are returned, because that order varies.
 
At any rate, I do not think the above is relevant, because the underlying .NET object in question is `PSObject`, which managed its properties as a `PSMemberInfoCollection` collection: https://github.com/PowerShell/PowerShell/blob/c0da3c42f2afab7e5b840585ccfe6e25caa66119/src/System.Management.Automation/engine/MshObject.cs#L755

Looking at the latter's `PSMemberInfoInternalCollection` implementation, it does seem to maintain order, but again this fact is not documented anywhere as far as I can tell.

> When you use `ConvertFrom-Json` to convert to a PSObject, the key-value pairs become properties of the object, so they are guaranteed to be ordered as written in the JSON. 

Again, where is this documented? Even if I accept `PSObject` property order is maintained according to `Add-Member` order, I cannot be certain that the underlying `ConvertFrom-Json` implementation iterates over the JSON in the order it is written and then calls Add-Member in that order - that is an implementation detail that can easily not hold in an arbitrary implemetation...

> All of the other `ConvertFrom-xxx` formats are ordered types.

`ConvertFrom-Csv` for example seems to return a `PSObject` so my documentation requests is relevant for it as well.

**Comment by sdwheeler** [comment]
> I'm not sure what you mean, to the extent that .NET objects even have order, it is not guaranteed

I stand corrected. I had assumed this was guaranteed in .NET. 

I spoke with the developers about this. The members of a PSObject are stored in an ordered collection. So the order of definition is maintained when converted to a PSObject.

`ConvertFrom-Json` does iterate over the JSON object in order as written. Prior to PowerShell 7.3, when using the **AsHashtable**, the resulting hashtable was not ordered. Beginning PowerShell 7.3, the code was changed to use an ordered hashtable so that the order would be maintained.

**Comment by ohads-MSFT** [comment]
@sdwheeler I agree on both accounts, but the fact remains that neither is documented. Specifically:
1. The docs for neither `PSObject.Properties` nor `PSMemberInfoCollection<T>` say anything about order. 
2. The docs for `Add-Member` are even worse, because they mislead the reader to think order is **not** guaranteed. In [Example 5: Create a custom object](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-member?view=powershell-7.3#example-5-create-a-custom-object) they add an ordered dictionary using the `NotePropertyMembers` parameter, whose documentation again says nothing about the order of properties in the resulting PSObject (regardless of their order in the input collection). Then, when they print the object's properties, they use `Get-Member` which apparently sorts the properties, breaking the order of the original ordered dictionary! Had the example used `$Asset.PSObject.Properties`, the order guarantee would have at least been implied (though still not explicit as I would have liked)...
3. The docs for `ConvertFrom-Json` (and all the other `ConvertFrom-XXX`) say nothing about order. The docs should be explicit about the fact that they do _"iterate over the JSON/CSV/etc. object in the order it written"_. Again, this is simply not an undocumented assumption the user can make - we just saw it break above with `Get-Member`.

**Comment by ohads-MSFT** [comment]
@sdwheeler @michaeltlombardi thank you so much, this looks great!

In case you own the PS SDK docs too, ideally they could be updated as well (but for sure this PR covers the most important parts): https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.psobject.properties?view=powershellsdk-7.2.0

**Comment by sdwheeler** [comment]
Those docs are generated from ///-comments in the PowerShell source code. The changes need to be made there.

**Comment by ohads-MSFT** [comment]
@sdwheeler so should I open a separate issue on the PS (non-docs) repo?

**Comment by sdwheeler** [comment]
@ohads-MSFT Yes, please.

**Comment by mklement0** [comment]
Related:

* #9519
