### ISSUE TITLE
In the 'Approved Verbs' list Show is said to be paired with Hide while it's not

### ISSUE THREAD

**Issue by aguzev** [MicrosoftDocs/PowerShell-Docs#9474]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.3#:~:text=This%20verb%20is%20paired%20with%20Hide.

### Summary

'Approved Verbs' page states: *__Show__ Makes a resource visible to the user. This verb is paired with Hide. __Hide__ Makes a resource undetectable. For example, a cmdlet whose name includes the Hide verb might conceal a service from a user. This verb is paired with Show.*

Most `Show-` cmdlets display an object on screen. `Show-Command` even allows editing a command. 

Only `Show-VirtualDisk` is paired with `Hide-VirtualDisk`, and it does not display any object to the user. In contrast to most `Show-` cmdlets, `Show-VirtualDisk` has a side effect, which is not intuitive to an active user of `Show-Command`.

### Suggested Fix

The 'Approved Verbs' should not describe `Show-` as the counterpart to `Hide-`. `Hide-` needs another counterpart since the semantics of `Show-Command` is already widely adopted.

**Comment by sdwheeler** [comment]
@aguzev The documentation is correct as written. PowerShell does not enforce the semantics for how the verbs are used. The Approved List is a guideline that, unfortunately, hasn't been implemented consistently.

**Comment by aguzev** [comment]
> PowerShell does not enforce the semantics for how the verbs are used. The Approved List is a guideline that, unfortunately, hasn't been implemented consistently.

PowerShell does not, PSScriptAnalyzer produces a warning.

**Comment by michaeltlombardi** [comment]
> > PowerShell does not enforce the semantics for how the verbs are used. The Approved List is a guideline that, unfortunately, hasn't been implemented consistently.
> 
> PowerShell does not, PSScriptAnalyzer produces a warning.

PSScriptAnalyzer produces that warning because (by default) it's configured to warn you about practices that don't match best practices, like the approved verb list.
