### ISSUE TITLE
Missing related content

### ISSUE THREAD

**Issue by andresgarcia0313** [MicrosoftDocs/PowerShell-Docs#9482]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

On the website:

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-printer?view=powershell-7.2

Please add information on how to configure the print size or the link to the example with which it is done in powershell

### Summary

On the website:

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-printer?view=powershell-7.2

Please add information on how to configure the print size or the link to the example with which it is done in powershell

### Details

On the website:

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-printer?view=powershell-7.2

Please add information on how to configure the print size or the link to the example with which it is done in powershell

### Suggested Fix

On this site 
https://learn.microsoft.com/en-us/powershell/module/printmanagement/?view=windowsserver2022-ps

on this site I found change the size but I did not find define the margins of the string variable to print

**Comment by sdwheeler** [comment]
The purpose of this article is to document the capabilities of the `Out-Printer` cmdlet. The cmdlet does not have any way to configure the print job. The resulting print job uses the default settings of the printer defined in the Print Server. The cmdlets in the **PrintManagement** module may not have then ability to change the setting you want either. That can be dependent on the print driver. You may be able to change them using WMI, but that still depends on what the print driver exposes to WMI.
