### ISSUE TITLE
Add a warning to Windows PowerShell commands that have been removed

### ISSUE THREAD

**Issue by SeeminglyScience** [MicrosoftDocs/PowerShell-Docs#9502]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Utility/Convert-String.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Get-ControlPanelItem.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Show-ControlPanelItem.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Disable-ComputerRestore.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Enable-ComputerRestore.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Get-ComputerRestorePoint.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Reset-ComputerMachinePassword.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Test-ComputerSecureChannel.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Complete-Transaction.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Get-Transaction.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Undo-Transaction.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/077a56ecf1c6d532d07c71b3685fbae79c3148bf/reference/5.1/Microsoft.PowerShell.Management/Use-Transaction.md

### Summary

While these documents already only appear in the documentation for 5.1 (and included in the list of breaking changes for PSv6), it would be nice to make it clear that they've been explicitly removed with an alert box.

**Comment by sdwheeler** [comment]
This information belongs in the release notes where we have it. 
- https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell
- https://learn.microsoft.com/powershell/scripting/whats-new/cmdlet-versions

These cmdlets are still available for use in PS7 via the WindowsCompatibilty feature.

**Comment by krzydoug** [comment]
> These cmdlets are still available for use in PS7 via the WindowsCompatibilty feature.

Are you sure? I am getting 

![image](https://github.com/MicrosoftDocs/PowerShell-Docs/assets/26283595/21c217f4-b10b-4d6b-946a-a34dbcac2fab)
