### ISSUE TITLE
Parameters position in `Get-Verb` docs is reversed

### ISSUE THREAD

**Issue by santisq** [MicrosoftDocs/PowerShell-Docs#9522]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-verb?view=powershell-7.3#parameters

### Summary

[__Parameters__ section on `Get-Verb` docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-verb?view=powershell-7.3#parameters) are showing incorrected `Position` for `-Verb` and `-Group` parameters.

### Details

Looking at cmdlet's help we can see the following (showing reversed `Position`):

```powershell
Get-Help Get-Verb -Parameter * | Select-Object Name, Position

name  position
----  --------
Group 0
Verb  1
```

Yet, if we `ProxyCommand.Create` we can see the following `param` block (`Position` for parameters is in the correct order):

```powershell
param(
    [Parameter(Position=0, ValueFromPipeline=$true, ValueFromPipelineByPropertyName=$true)]
    [string[]]
    ${Verb},

    [Parameter(Position=1, ValueFromPipeline=$true, ValueFromPipelineByPropertyName=$true)]
    [ValidateSet('Common','Communications','Data','Diagnostic','Lifecycle','Other','Security')]
    [string[]]
    ${Group}
)
```

### Suggested Fix

Reverse the order of the params position, the doc should show `-Group` in `Position: 1` and `-Verb` in `Postion: 0`.

**Comment by ninmonkey** [comment]
`Get-Help`'s output also does not match the actual [get-verb attributes](https://github.com/PowerShell/PowerShell/blob/bdea7735985d5c73048a90823b866a44e5d35136/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs#L21-L35) . Maybe the docs are generated off of `Get-Help`'s metadata.

```ps1
# 7.3.0
Get-Command Get-Verb | Get-Help -Parameter * | ft name, position
$paramInfo = (gcm get-verb).Parameters
@{ 
    Verb =  $ParamInfo.Verb.attributes.position
    Group = $paramInfo.group.attributes.position
}
```
```
name  position
----  --------
Group 0
Verb  1

Name  Value
----  -----
Verb  0
Group 1
```
