### ISSUE TITLE
Get-WinEvent -FilterHashTable ProviderName array has an undocumented max length in PowerShell 5.1

### ISSUE THREAD

**Issue by tydaeus** [MicrosoftDocs/PowerShell-Docs#9536]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-5.1#-filterhashtable

### Summary

Current documentation for `Get-WinEvent` `-FilterHashTable` parameter's `ProviderName` property makes no mentions of limitations on the provided `string[]`.

In PowerShell 5.1 on Windows 10, and likely in other versions, running `Get-WinEvent` with the `-FilterHashTable` parameter's `ProviderName` property set to a `string[]` with more than 22 elements results in an error specifying "Get-WinEvent : No events were found that match the specified selection criteria."

### Details

Given:
- `$providers` - a list of 23 or more valid event provider names, with `$provider[0]` having logged at least one event in the last 10,000

``` PowerShell
Get-WinEvent -FilterHashTable @{ 'ProviderName' = $providers[0..21] } -MaxEvents 10000
# output will be as expected

Get-WinEvent -FilterHashTable @{ 'ProviderName' = $providers[0..22] } -MaxEvents 10000
# Error displays: Get-WinEvent : No events were found that match the specified selection criteria....
```

I have not tested to determine whether PowerShell versions other than 5.1 or OS other than Windows 10 is affected. I have not tested whether the maximum array length differs if the length of the provider names differs. When I encountered the issue, `$providers[0..21]` was 387 characters long, and `$providers[0..22]` was 408 characters long (measured by joining without spaces).

### Suggested Fix

- The **ProviderName** key can accept a maximum of 22 string values. If additional string values are provided, `Get-WinEvent` will throw an error error specifying "Get-WinEvent : No events were found that match the specified selection criteria."

**Comment by sdwheeler** [comment]
@tydaeus I was not able to reproduce your problem. I created a list of 38 providers and had no problems. My list was 963 characters long.

```
PS> $providers.Count
38

PS> ($providers -join '').length
963

PS> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  608
```

I suggest you try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
