### ISSUE TITLE
reassign $PSBoundParameters and remove some items is not best practice that could make beginers get confused.

### ISSUE THREAD

**Issue by sakesun** [MicrosoftDocs/PowerShell-Docs#9569]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.3#splatting-with-arrays

### Summary

    #Call the Test1 function with $b and $c, but not with $a
    $LimitedParameters = $PSBoundParameters
    $LimitedParameters.Remove("a") | Out-Null
    Test1 @LimitedParameters

Removal of $LimitedParameters member will also effect $PSBoundParameters

### Suggested Fix

Better make a clone of $PSBoundParameters before removal

    #Call the Test1 function with $b and $c, but not with $a
    $LimitedParameters = $PSBoundParameters.Clone()
    $LimitedParameters.Remove("a") | Out-Null
    Test1 @LimitedParameters

**Comment by sdwheeler** [comment]
@sakesun That won't work. You get the following error:

```
Method invocation failed because [System.Management.Automation.PSBoundParametersDictionary] does not contain a method named 'Clone'.
```
