### ISSUE TITLE
about_DesiredStateConfiguration doc

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/PowerShell-Docs#9582]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1, 7.0, 7.2, 7.3

### Summary

A doc detailing what DSC is

### Proposed Content Type

About Topic

### Proposed Title

about_DesiredStateConfiguration

**Comment by kilasuit** [comment]
@michaeltlombardi this would be a good one for you!

**Comment by michaeltlombardi** [comment]
@kilasuit, to be sure I understand, you're wanting an about topic in the core PowerShell content? I'm not sure this document would be useful here. How do you imagine someone discovering and using this content in the console? How does this provide value over the extant DSC documentation in that doc set?

**Comment by sdwheeler** [comment]
FYi - https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_desiredstateconfiguration?view=powershell-5.1

**Comment by kilasuit** [comment]
@sdwheeler thanks for sharing that doc which I didn't see when coming to the docs naturally. I've updated the issue as that doc (or one more applicable) it is not visible for most coming to the docs for 7.2 /7.3 and I feel that it should be

**Comment by kilasuit** [comment]
@sdwheeler I get that but what I would expect to see is a thinner doc for any version past 5.1 (supported or not) that points to those DSC docs.

Similarly like I would expect as time goes on we would have more doc's overall, no doc's get removed between versions, but instead are slimmed down if that feature isn't available. A few examples include DSC, workflows or use of COM objects or anything else.
