### ISSUE TITLE
User needs execute permission on pwsh file to run Powershell on Raspberry PI

### ISSUE THREAD

**Issue by steveflynn** [MicrosoftDocs/PowerShell-Docs#9584]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/install-raspbian?view=powershell-7.3

### Summary

After following the instructions to install Powershell 7.3 on Raspberry PI, attempting to run pwsh would return a Permission Denied error.

### Details

The user did not have the required execute permission for the pwsh file.

### Suggested Fix

At the end of the installation issue the following command to grant execute permissions to pwsh

sudo chmod 744 pwsh

**Comment by sdwheeler** [comment]
This is a bug in the `.tar.gz` package that is being fixed in the next release.

**Comment by sdwheeler** [comment]
This is a bug in the `.tar.gz` package that is being fixed in the next release.
