### ISSUE TITLE
Lack of the Move-Item on the "Working with files and folders" page

### ISSUE THREAD

**Issue by runbing** [MicrosoftDocs/PowerShell-Docs#9604]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/samples/working-with-files-and-folders?view=powershell-7.3

### Summary

The page "Working with files and folders" should include Move-Item.

### Details

This page explains how to work with files and folders. Manipulation includes listing files (Get-ChildItem), copying files (Copy-Item), creating files (New-Item), and removing files (Remove-Item), but there is no manipulation of moving files ([Move-Item](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/move-item?view=powershell-7.3)). Is it necessary to include this?

### Suggested Fix

Add the manipulation of moving files ([Move-Item](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/move-item?view=powershell-7.3)) to [this page](https://learn.microsoft.com/en-us/powershell/scripting/samples/working-with-files-and-folders?view=powershell-7.3).

**Comment by sdwheeler** [comment]
@runbing Thanks for the feedback. Those articles in the samples area are very old. We don't intend to make any changes there. The cmdlet reference for [Move-Item](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/move-item) has plenty of examples.
