### ISSUE TITLE
Typo in "Discover Powershell" second paragraph, first sentence.

### ISSUE THREAD

**Issue by jasonekey** [MicrosoftDocs/PowerShell-Docs#9605]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/discover-powershell?view=powershell-7.3

### Summary

In the first sentence of the second paragraph, there is a missing word, "it."
"The thing that makes PowerShell unique is that accepts and returns .NET objects," should read: 
"The thing that makes PowerShell unique is that >it< accepts and returns..."

**Comment by ehmiiz** [comment]
volunteer to fix!

**Comment by sdwheeler** [comment]
@ehmiiz Go for it!
