### ISSUE TITLE
No Documentation to Explain How-To Permanently Set PowerShell Language Mode (Machine Policy or Per User)

### ISSUE THREAD

**Issue by HJLBX** [MicrosoftDocs/PowerShell-Docs#9615]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.3

### Summary

Us out here in userland need official Microsoft documentation on how to permanently set PowerShell language mode (machine policy or per user without using Device Guard, MDAC and similar). There are ways to do it, and the PowerShell Team needs to publish them.

This applies to all versions of PowerShell 5+.

### Details

Objective:

I have a standalone workstation running a Windows Pro version with PowerShell 5+ installed. I simply want to permanently enable Constrained Language or NoLanguage mode.

I do not want to use Active Directory, Device Guard, Microsoft Defender Application Control, Just Enough Administration, Intune or other Windows management solutions to enforce the PowerShell language mode. I want to enforce the PowerShell language mode locally, and again permanently (not per session).

Of course a user can enforce language mode by creating a PowerShell profile script, but that can be easily bypassed by an attacker or malware that launches PowerShell with the -noprofile switch.

Why does Microsoft make this so difficult?

This is a configuration\usability problem, as well as a security issue, with PowerShell that has plagued us users for well over a decade.

Reality:

Microsoft provides no official documentation (learn.microsoft) on how to enforce PowerShell language mode permanently and locally. What is available online is a hodge-podge of outdated and incorrect information that is nothing but a hindrance and waste of time & effort. Examples (the first explanation at learn.microsoft PowerShell forum is all wrong - they did not even answer the question which was "How do I enforce Constrained Language Mode permanently and locally (the person that asked the question is a home user) - and provided by non-Microsoft party, the second is by PowerShell Team but gives obsolete infos [_PSScriptPolicy variable]), 

https://learn.microsoft.com/en-us/answers/questions/647121/proedures-to-enforce-windows-powershell-to-run-in.html

https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/

If Microsoft software restriction policy (SRP) is enabled, then this registry key and value determine the PowerShell language mode, however the key values for each of the four language modes is not published by Microsoft:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\safer\CodeIdentifiers\DefaultLevel 

DefaultLevel value is different for each PowerShell language mode, but the values are not published by Microsoft.

There are other methods that can be implemented locally to permanently enforce PowerShell language mode - and PowerShell Team needs to publish these solutions.

### Suggested Fix

It is not acceptable for Microsoft to say "We do not want users doing that."

**Comment by HJLBX** [comment]
> @HJLBX Thanks for your feedback! We'll investigate and update as appropriate.

Thank you Mr Robbins. I have great respect for your work.

**Comment by sdwheeler** [comment]
@PaulHigin Can you comment on this issue?

**Comment by PaulHigin** [comment]
No need to comment.  Just need to add documentation about language modes.

**Comment by PaulHigin** [comment]
What I mean is that language modes have been created for different purposes, and are useful in specific contexts.  We should definitely document language modes, and I can help with that.

**Comment by sdwheeler** [comment]
@HJLBX The short answer is that Language modes apply to sessions. Languages modes get set when you use a system application control policy (Applocker or WDAC) or create a session configuration for remote sessions.

I am updating the documentation with more details.

**Comment by HJLBX** [comment]
> @HJLBX The short answer is that Language modes apply to sessions. Languages modes get set when you use a system application control policy (Applocker or WDAC) or create a session configuration for remote sessions.
> 
> I am updating the documentation with more details.

Thank you.

There are also ways to set language mode without use of AppLocker and WDAC. Such methods have been discussed by Microsoft personnel before.

Is this to be included in documentation?
