### ISSUE TITLE
Is it explicitly described about how to enter a multi-line command?

### ISSUE THREAD

**Issue by songyuc** [MicrosoftDocs/PowerShell-Docs#9618]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

I have known that a multi-line command of Powershell can be separated with the backtick (`), but it seems to have not been explicitly described in the documentation.

### Details

Could you please help add this content to the documentation?

### Articles

- reference/7.3/microsoft.powershell.core/about/about_special_characters.md

### Related Source Pull Requests

None

### Related Source Issues

None

**Comment by sdwheeler** [comment]
This needs to be added to the about_Special_Characters article. However, it is considered bad form to use the backtick for line continuation. In most cases, you can find other places where PowerShell allows for natural line breaks, such as after opening braces and parentheses, after pipe characters, after commas in an array, or within a hashtable definition.

For long command lines that use a lot of parameters with long names or values you should use splatting. See [about_Splatting](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_splatting) for more information.

**Comment by sdwheeler** [comment]
For a good reference, see https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style-Guide/Code-Layout-and-Formatting.md#maximum-line-length

**Comment by songyuc** [comment]
Hi, @michaeltlombardi,
it seems strange that I cannot find the relevant content of "Line continuation" on this online documentation [page](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.3) currently.
