### ISSUE TITLE
get-hotfix description is unclear about scope of updates covered

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/PowerShell-Docs#9622]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-hotfix?view=powershell-7.3

### Summary

Initial description states that cmdlet will include hotfixes/updates from various sources; but Note at bottom implies it does not cover those same sources.

### Details

The basic description of the cmdlet includes this statement:

"The updates can be installed by Windows Update, Microsoft Update, Windows Server Update Services, or manually installed."

The Notes https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-hotfix?view=powershell-7.3#notes include this statement: 

"The Win32_QuickFixEngineering [WMI class](https://learn.microsoft.com/en-us/windows/desktop/WmiSdk/retrieving-a-class) represents a small system-wide update, commonly referred to as a quick-fix engineering (QFE) update, applied to the current operating system. This class returns only the updates supplied by Component Based Servicing (CBS). These updates are not listed in the registry. Updates supplied by Microsoft Windows Installer (MSI) or the [Windows Update](https://update.microsoft.com/) site are not returned by Win32_QuickFixEngineering."

I cannot find any clear statement in the document as to whether get-hotfix is using the Win32_QuickFixEngineering WMI class and is therefore affected by its limitations, but the inclusion of the note implies that it is.  

If the information in the Note applies to get-hotfix, than the initial description appears to wrong or at least misleading (I would assume that "manually installed" would include MSI).  If the information in the note does NOT apply to get-hotfix, that should be clearly stated.

**Comment by sdwheeler** [comment]
`Get-Hotfix` uses the **Win32_QuickFixEngineering** WMI class so those limitations apply. We will fix the opening paragraph.
