### ISSUE TITLE
Out of date information on PowerShell Support Lifecycle  

### ISSUE THREAD

**Issue by szabolevo** [MicrosoftDocs/PowerShell-Docs#9631]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.3

### Summary

Some details are out of date or missing in [PowerShell Support Lifecycle](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.3) documentation, specifically around architecture and ARM support. In some cases the documentation is not in line/sync with [PowerShell on ARM](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-on-arm?view=powershell-7.3) documentation

### Details

Details of sections in [PowerShell Support Lifecycle](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.3) documentation that needs to be updated:
1. **macOS**: High Sierra is still mentioned under supported architecture table, though it's no longer supported (as the PS version support table correctly shows)
2. **Alpine Linux**: "_PowerShell hasn't been tested on Alpine using Arm processors._" - this statement is not specific enough to be in line with [PowerShell on ARM](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-on-arm?view=powershell-7.3) documentation, where for PS v7.0/7.1, Alpine v3.10+/v3.11+ are respectively listed as supported on Arm64
3. **Raspberry Pi**: Missing details on version and architecture support. [Installing PowerShell on Raspberry Pi](https://learn.microsoft.com/en-us/powershell/scripting/install/install-raspbian?view=powershell-7.3) documentation references **arm32** versions of linux binaries, suggesting this is the architecture that is tested/supported. Raspberry is built on Debian 10+, which is supported by the relevant .Net/PS versions for both arm32/arm64. The documentation should be more clear about whether **arm64** version of Raspberry Pi is tested/supported, and if yes then for which OS version

### Suggested Fix

1. **macOS**: High Sierra should be removed from the supported architecture table
2. **Alpine Linux**: If current versions of Alpine are indeed not tested on current versions of PS then no change is needed on document.  If it has been tested for either current versions then the architecture table should be updated accordingly
3. **Raspberry Pi**: Add version and architecture support tables for Raspberry Pi, just like for the other OSes, clearly stating what is and what isn't tested&supported

**Comment by sdwheeler** [comment]
Need to update based on our test matrix and add info for 7.4-p1.
