### ISSUE TITLE
Out of date information in "PowerShell on ARM processors" documentation

### ISSUE THREAD

**Issue by szabolevo** [MicrosoftDocs/PowerShell-Docs#9632]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-on-arm?view=powershell-7.3

### Summary

Details of supported PowerShell versions and platforms are out of date in [PowerShell on ARM](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-on-arm?view=powershell-7.3) documentation. 

### Details

 - **PowerShell 7.0 and 7.1:** tables are still present, though those versions are no longer supported on any platform
 - **Raspberry Pi:** missing from the tables, though there are **arm32** install steps documented in [Install PowerShell on Raspberry Pi OS](https://learn.microsoft.com/en-us/powershell/scripting/install/install-raspbian?view=powershell-7.3) documentation
 - **Ubuntu:** missing 22.04, though it's listed in [PowerShell Support Lifecycle](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.3) documentation
 - **Windows 11:** missing from the platform tables, though it's listed in [PowerShell Support Lifecycle](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.3) documentation

**Comment by szabolevo** [comment]
Related to #9631

**Comment by sdwheeler** [comment]
Our support policy for Arm processors starts with the .NET support policy. We can't support anything that is not supported by .NET. However, the policy for PowerShell is further limited to the platforms we test.

We have tested and support the following:
- Arm64 on the supported versions of Windows
- Arm32 on Ubuntu 18.04, 20.04, and 22.04
- Arm32 on Raspberry Pi
- Arm64 on macOS running M1 hardware

**Comment by sdwheeler** [comment]
Need to update based on our test matrix and add info for 7.4-p1.
