### ISSUE TITLE
Update Powershell links for Ubuntu 22.10

### ISSUE THREAD

**Issue by corticalstack** [MicrosoftDocs/PowerShell-Docs#9634]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

Page needs updating to provide links for Ubuntu 22.10
https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.3

### Summary

Page needs updating to provide links for Ubuntu 22.10

**Comment by sdwheeler** [comment]
Ubuntu 22.10 is an interim release. As stated in our docs, we only support LTS releases. You can probably make it work with the existing packages, we just don't document the versions that we don't support.
