### ISSUE TITLE
Selecting which version of PowerShell is to be used when remotely accessing PowerShell.

### ISSUE THREAD

**Issue by jacbar01** [MicrosoftDocs/PowerShell-Docs#9635]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.3

### Summary

I haven't found anywhere anything that would address the issue of selecting the version of PowerShell being accessed remotely, typically with invoke-command -computername or enter-PSSession.

### Details

Some context: I have a Windows 2022 Datacenter Server, Core Edition, with Windows PowerShell 5.1 installed by default. When I enter-pssession to this server I get a session opened to PS 5.1, nothing bad about it.

Now, I have also installed Microsoft PowerShell 7.3.x, but when I enter-pssession I still get PS 5.1. I would like to either chose the default version of PowerShell or state which version I want whenever I open a remote session to my server. I cannot find any documented way to do it.

### Proposed Content Type

About Topic

**Comment by ehmiiz** [comment]
Just a comment on how I do this:
WinRM based remoting -> 5.1
SSH based remoting -> 7.+
This way you can be very specific of versioning, port, etc:

https://learn.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core

**Comment by sdwheeler** [comment]
See [WS-Management (WSMan) Remoting in PowerShell](https://learn.microsoft.com/powershell/scripting/learn/remoting/wsman-remoting-in-powershell-core). This article explains how to enable remoting. The script to enable remoting adds session configurations for the current version. The configurations are named endpoints for a specific version of PowerShell. When you use `New-PSSession` or `Enter-PSSession` you add the **ConfigurationName** parameter to specify the name of the Session Configuration you want to connect to.

On my system, I have PowerShell 7.3.1 installed with remoting enabled. I have the following Session Configurations:

```powershell
PS> Get-PSSessionConfiguration | Select-Object Name, PSVersion

Name                                     PSVersion
----                                     ---------
microsoft.powershell                     5.1
microsoft.powershell.workflow            5.1
microsoft.powershell32                   5.1
microsoft.windows.servermanagerworkflows 3.0
PowerShell.7                             7.0
PowerShell.7.3.1                         7.0
```
