### ISSUE TITLE
A Steppablepipeline might make a difference

### ISSUE THREAD

**Issue by iRon7** [MicrosoftDocs/PowerShell-Docs#9654]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1, 7.2, 7.3, 7.4

### Summary

The [steppablepipeline class](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.steppablepipeline?view=powershellsdk-7.3.0) is poorly described and quiet unknown, yet it could make quiet a difference with respect to [PowerShell scripting performance considerations](https://learn.microsoft.com/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations), in some use cases, it could even compete against multi-threading cmdlets.
Sometime ago, I requested for an [`#18054` idiomatic (friendly) steppablePipeline](https://github.com/PowerShell/PowerShell/issues/18054) and that is correctly closed as the syntax is not the issue but simply the fact that it (to my opinion) lacks a kind of "*Everything you wanted to know about the steppablepipeline*" document.

### Details

See: [What good does a SteppablePipeline](https://stackoverflow.com/a/73074477/1701026)

### Proposed Content Type

About Topic

### Proposed Title

Everything you wanted to know about the steppable pipeline

### Related Articles

* [Faster way of getting rows from a csv file and outputting to a different csv file](https://stackoverflow.com/a/74997412/1701026)
* [What is the best way to structure an advanced multi-threaded Powershell function to work both on the pipeline as well as non-pipeline calls?](https://stackoverflow.com/a/73646440/1701026)
* [Split CSV with powershell](https://stackoverflow.com/a/73671591/1701026)

**Comment by sdwheeler** [comment]
@iRon7 Thanks for the suggestion. The [steppablepipeline class](https://learn.microsoft.com/dotnet/api/system.management.automation.steppablepipeline) documentation is in the ///-comments in the source code. If the API docs need improvement you need to open an [issue][1] in the source code repository.

I like the idea of an "Everything you wanted to know about the steppable pipeline" article. I would welcome a PR if you are interested.

[1]: https://aka.ms/psfeedback

**Comment by iRon7** [comment]
@sdwheeler,

The referral to the API docs was only meant as an additional argument for better documenting the steppable pipeline for PowerShell scripters.
I am not native English and I have only little knowledge of C#, meaning I do not have in-depth technical knowledge of the steppable pipeline myself.
Anyways, I will try to draft a PR for this.

**Comment by iRon7** [comment]
---
description: The PowerShell pipeline explained from the begging to the end.
ms.custom: contributor-iRon7
ms.date: 01/27/2022
title: Mastering the (steppable) pipeline
---
# Mastering the (steppable) pipeline

Before stepping into the *steppable* pipeline, it is essential that you have a good understanding of how *and when* exactly items are processed by a [cmdlet](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-overview) in the pipeline. The PowerShell pipeline might just look like a syntactical sugar but it is a lot more than that. In fact, it really *acts* like a pipeline were each item flows through and is handled by each cmdlet one-at-a-time.
In comparison to the legacy CMD pipes, PowerShell able to stream *objects* through the pipeline. 

## One-at-a-time `process`
The explanation below elaborations on the **one-at-a-time processing** section of the [About pipelines](/powershell/module/microsoft.powershell.core/about/about_pipelines) document.
A good analogy of the pipeline is a physical assembly line where each consecutive line station could be compared with a PowerShell cmdlet. At a specific station and time, some something is done to one item while the next item is prepared  at the prior station. E.g. at a station, a component is soldered at the item while the next item is already being unpacked at the prior station. Items iterate through the pipeline like:

**Iteration: `n`**

```Console
 item 3  --> item 2  --> item 1
Station 1 | Station 2 | Station 3
```
**Iteration: `n + 1`**

```Console
 item 4  --> item 3  --> item 2
Station 1 | Station 2 | Station 3
```
Cmdlets act like stations in the assembly line, taken a simple example:

```PowerShell
Get-Content .\Input.txt | Foreach-Object { $_ } | Set-Content .\Output.txt
```
In this example the `Foreach-Object { $_ }` cmdlet does nothing else than:
* picking up each item from the pipeline that has been output by the prior cmdlet `Get-Content .\Input.txt`
* placing it back on the pipeline as an input for the next cmdlet `Set-Content .\Output.txt`.

To visualize the order of the items that go through the `Foreach-Object { $_ }` cmdlet you might use the `Trace-Command` cmdlet but that might overwhelm you with data. Instead, using two simple `ForEach-Object` (alias `%`) test commands show you exactly where your measure points are and what goes in and come out the specific cmdlet in between.
1.  `%{Write-Host 'In:' $_; $_ }`
2.  `%{Write-Host 'out:' $_; $_ }`

Notice that `...; $_ }` in the end of the command will place the current item back on the pipeline.
In the MVCE (minimal complete verifiable example) below, the cmdlet at the start of the pipeline  (`Get-Content .\Input.txt`) has been replaced with 4 hardcoded input items (`1,2,3,4`)  and the cmdlet at the end of the pipeline  (`Set-Content .\Output.txt`) with`Out-Null` which simply purges the actual output of the pipeline so that only the two test cmdlets produce an output.

```PowerShell
1,2,3,4 | %{Write-Host 'In:' $_; $_ } | Foreach-Object { $_ } | %{Write-Host 'Out:' $_; $_ } | Out-Null
```
This shows the following output:
```Console
In: 1
Out: 1
In: 2
Out: 2
In: 3
Out: 3
In: 4
Out: 4
```
This proves that each item (e.g. `Out: 1`) is ejected from the `Foreach-Object { $_ }` command prior the next item (`In: 2`)  is injected into it.
As you can imaging, this conserves memory as there are only a few items in the pipeline at a certain time.

## Chocking the pipeline
The previous section explains how a cmdlet would perform if correctly implemented for the middle of a pipeline but there are a few statements that might "**choke**" the pipeline, meaning that the items are no longer processed **one-at-the-time** but somewhere piled up in memory and eventually processed **all-in-once**. This happens for:

* **Assigning the pipeline to a variable**, e.g.:
```PowerShell
$Content = Get-Content .\Input.txt | Foreach-Object { $_ }
$Content | Set-Content .\Output.txt
```

* **Using parentheses**, e.g.:
```PowerShell
(Get-Content .\Data.txt | Foreach-Object { $_ }) | Set-Content .\Data.txt
```

* **Some specific cmdlets might choke the pipeline due to their nature**
In general, a well defined cmdlet should write single records to the pipeline (see also [Strongly Encouraged Development Guidelines](/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines)). Yet this is not always possible, take e.g. the `Sort-Object` cmdlet which is supposed to sort the object which might result is a new list where the last item ends up first. To determine what item comes first, you will need to wait for the very last item to be able to release the first one. This will be visual from the simple test commands used before:
```PowerShell
1,2,3,4 | %{Write-Host 'In:' $_; $_ } | Sort-Object | %{Write-Host 'Out:' $_; $_ } | Out-Null
```
This shows the following output:
```Console
In: 1
In: 2
In: 3
In: 4
Out: 1
Out: 2
Out: 3
Out: 4
```

Note that in general you should try to avoid chocking the pipeline, but their are few exceptions where it might be even required to chock the pipeline. E.g. where you want to read and write back to the same file as in the above "using parenthesis" example. This is because in a smooth pipeline, each item is process one-at-the-time, meaning that the `Get-Content` and `Set-Content` both concurrently processing an item in the pipeline which will result to an expecting error:

>  The process cannot access the file '.\Data.txt' because it is being used by another process.  

In this situation, chocking the pipeline and reading all the files first, will avoid the above error.

### Heavy objects
PowerShell objects are optimized for the pipeline in a way that all the information to be able to process an object as a single item are included. Meaning not just the value of the item but also properties as the name and the type of the item.
As a comparison, take the `DataTable` object, which is a .Net object by itself. The header of `DataTable` object contains the column (property) names and types where each row in the `DataTable` only contains the value of each column. If you convert a `DataTable` into a list of PowerShell objects, like:
```PowerShell
$Data = $DataTable | Foreach-Object { $_ }
```
The memory usage will considerably increase because each `PSNoteProperty` has an overhead of 48 bytes even if you item value is just a few bytes. Anyways, this shouldn't be an issue if you stream your object through the pipeline as there will only be a few object in the pipeline at a certain time.

### Missing properties
A limitation of the PowerShell pipeline is that even each object in the pipeline contains all the member (including properties) information about the current item ( named `$PSItem` or just `$_`). It still might not be enough to define a unified output headers for all the object that might follow.
Consider the following two objects being converted to a Csv list:
```PowerShell
$a = [pscustomobject]@{ name='John'; address='home'}
$b = [pscustomobject]@{ name='Jane'; phone='123'}
$a, $b |Format-Table
```
Results
```Console
name address
---- -------
John home
Jane
```
Notice that there is no `phone` column, meaning that the `phone='123'` property is missing from the results. This is actually due to the one-at-a-time processing: at the moment the `Format-Table` cmdlet receives object `$a` it is supposed to process it immediately by writing it to the console and release it in order to be able to process any following items. The issue is that the `Format-Table` cmdlet is yet unaware of the next object `$b` (which isn't even instantiated and not even exist yet in the pipeline) but the initial output is already written to the console.
In other words, a cmdlet written for one-at-a-time processing bases its output on the first object received from the pipeline. This also implies that if you change the order of the items in the pipeline (e.g. with `$a,  $b  Sort-Object | Format-Table`) properties might reappear and/or disappear.  

### Processing blocks
As you might have noticed, some actions, like outputting a header, are only required only ones. As in the analogy with the assembly line, heating up a soldering gun is only required ones when the pipeline is started, cleaning up the station is only required when the pipeline is completed. Similar time consuming ("expensive") actions could be required for a cmdlet as e.g. open and closing a file. These actions are respectively defined in the `Begin` - and  `End` block of a cmdlet. The actual processing is defined in the `Process` block of cmdlet.
A well defined pipeline PowerShell cmdlet might look like this:
```PowerShell
function MyCmdlet {
    [CmdletBinding()] param(
        [Parameter(ValueFromPipeLine = $True)][String] $InputString
    )
    Begin {
        $Stream = [System.IO.StreamWriter]::new("$($Env:Temp)\My.Log")
    }
    Process {
        $Stream.WriteLine($_)
    }
    End {
        $Stream.Close()
    }
}
```
Using the above cmdlet example with the command like `1..9 | MyCmdlet`, the log file is *only opened once* at the start of the pipeline, than each item in the pipeline is process one-at-a-time and at the end the log file is closed (*once*).
Note that when there are no `Begin`, `Process` and  `End` processing blocks defined in a function, the content of the function is assigned to the `End` block. See also: [about Functions Advanced Methods](/powershell/module/microsoft.powershell.core/about/about_functions_advanced_methods)

A similar pipeline can be created with the common [`Foreach-Object`](/powershell/module/microsoft.powershell.core/foreach-object) cmdlet using the `-Begin`, `-Process` and `-End` parameters to define the corresponding process blocks:
```PowerShell
1..9 | Foreach-Object -Begin {
    $Stream = [System.IO.StreamWriter]::new("$($Env:Temp)\My.Log")
} -Process {
    $Stream.WriteLine($_)
} -End {
    $Stream.Close()
}
```

### Performance
With the above explanation of the pipeline, you might understand now why you shouldn't wrap cmdlet pipeline in other pipeline, like:
```PowerShell
1..9 | ForEach-Object {
    $_ | MyCmdlet
}
```
Wrapping a cmdlet pipeline into another (`ForEach-Object`) pipeline is very expensive because you're also invoking the `begin` and `end` block of `MyCmdlet` which will open and close the concerned log file for each specific item instead of only once (at the beginning and the end of the pipeline). The performance degradation appears with native cmdlets along with `Export-Csv -append` and `Add-Content`. See also [PowerShell scripting performance considerations](/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations#avoid-wrapping-cmdlet-pipelines)

## The steppable pipeline
Unfortunately, it is not always possible to create a single syntactical pipeline as you might e.g. need different branches for different parameters, as output paths, along the road. Consider a very large `csv` file which you want to cut in smaller batch files. The obvious approach is:
```PowerShell
$BatchSize = 10000
Import-Csv .\MyLarge.csv | ForEach-Object -Begin { $Index = 0 } -Process {
    $BatchNr = [math]::Floor($Index++/$BatchSize)
    $_ | Export-Csv -append .\Batch$BatchNr.csv
}
```
But as stated this before, this will open and close each output file (`.\Batch$BatchNr.csv` ) 10,000 times where it only needs to be opened and closed once per output file. So, the solution here is to use a steppable pipeline which lets you independently define the processing blocks for the required output stream:
```PowerShell
$BatchSize = 10000
Import-Csv .\MyLarge.csv | ForEach-Object -Begin { $Index = 0 } -Process {
    if ($Index % $BatchSize -eq 0) {
        $BatchNr = [math]::Floor($Index++/$BatchSize)
        $Pipeline = { Export-Csv -notype -Path .\Batch$BatchNr.csv }.GetSteppablePipeline()
        $Pipeline.Begin($True)
    }
    $Pipeline.Process($_)
    if ($Index++ % $BatchSize -eq 0) { $Pipeline.End() }
} -End { $Pipeline.End() }
```
Every 10,000 (`$BatchSize`) entries, the modules (`%`) is zero and a new pipeline is created for the expression `{ Export-Csv -notype -Path .\Batch$BatchNr.csv }`.
* The `$Pipeline.Begin($True)` invokes the `Begin` block of the steppable pipeline  which opens an new `csv` file named `.\Batch$BatchNr.csv` and writes the headers to the file
* The `$Pipeline.Process($_)` invokes the `Process` block of the steppable pipeline using the current item (`$_`) which is appended to the `csv` file
* The `$Pipeline.End()`invokes the `End` block of the steppable pipeline which closes the `csv` file named `.\Batch$BatchNr.csv` which holds a total of 10,000 entries.
<sub>(Note that it is important to end the pipeline but there is no harm in invoking the `$Pipeline.End()` multiple times.)</sub>

It is a little more code, but if you measure the results you will see that in this situation the later script is more that 50 times faster than the one with the wrapped cmdlet pipeline.

### Multiple output pipelines
With the steppable pipeline technique, you might even have multiple output pipelines open at ones. Consider that for the very large `csv` file in the previous example, you do not want batches of 10,000 entries but divide the entries over 26 files based on the first letter of the `LastName` property:
```PowerShell
$Pipeline = @{}
Import-Csv .\MyLarge.csv | ForEach-Object -Process {
    $Letter = $_.LastName[0].ToString().ToUpper()
    if (!$Pipeline.Contains($Letter)) {
        $Pipeline[$Letter] = { Export-CSV -notype -Path .\$Letter.csv }.GetSteppablePipeline()
        $Pipeline[$Letter].Begin($True)
    }
    $Pipeline[$Letter].Process($_)
} -End {
    foreach ($Key in $Pipeline.Keys) { $Pipeline[$Key].End() }
}
```
**Explanation:**
* `Import-Csv .\MyLarge.csv | ForEach-Object -Process {`
  processes each (One-at-a-time) item of the `csv` file
* `$Letter = $_.LastName[0].ToString().ToUpper()`
  Takes the first character of the `LastName` property and puts that in upper case.
* `if  (!$Pipeline.Contains($Letter))  {`
  If the pipeline for the specific character doesn't yet exist:
  * Open a new steppable pipeline for the specific letter:`{  Export-CSV  -notype -Path .\$Letter.csv }.GetSteppablePipeline()`
  * And invoke the `Begin` block: `.Begin($True)` which creates a new `csv` file with the concerned headers
* `foreach  ($Key in $Pipeline.Keys)  {  $Pipeline[$Key].End()  }`
  Closes all the existing steppable pipelines (aka `csv` files)


### See also
* [About pipelines](/powershell/module/microsoft.powershell.core/about/about_pipelines)
* [Cmdlet Overview](/powershell/scripting/developer/cmdlet/cmdlet-overview)
* [Strongly Encouraged Development Guidelines](h/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines)
* [About Functions Advanced Methods](/powershell/module/microsoft.powershell.core/about/about_functions_advanced_methods)
* [PowerShell scripting performance considerations](/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations)

**Comment by sdwheeler** [comment]
@iRon7 - This is a great start. To take this as an article in our documentation, I would want to edit it quite a bit. But with some minor edit, it would make a great blog post for our [PowerShell Community blog](https://devblogs.microsoft.com/powershell-community/). The process for submitting to is similar to submitting to our docs, but simpler. Once it is published as a blog I could then rework the content to create a new article that would fit into our docs better.

Would you be interested in that? Take a look at our blog [Contributor guide](https://github.com/PowerShell/Community-Blog/blob/main/Docs/README.md).

Do you participate in the PowerShell [Discord](https://aka.ms/psdiscord) or [Slack](https://aka.ms/psslack) forums? Or do you have a teams account? If so, I am happy to get in a live session with you to help you through the submission process.

**Comment by iRon7** [comment]
@sdwheeler,
Thanks for the feedback.
I have gone through most of the [PowerShell Community blog](https://devblogs.microsoft.com/powershell-community/) process and submitted a minor issue (https://github.com/PowerShell/Community-Blog/issues/110) with a minor merge request to familiarize myself.
After that I have created u new `2023\01\Mastering-The-Steppable-Pipeline.md` document in VSCode, commit and did a pull request at the blog site (and signed the CLA).

Btw, I am not using Discord or Slack but we might do a live session with Teams (if still required).
(I presume that from this point, somebody will review my pull request and give me feedback on my purposed document)

Thanks,
Ronald

**Comment by iRon7** [comment]
The document is currently available at: [Mastering the (steppable) pipeline](https://devblogs.microsoft.com/powershell-community/mastering-the-steppable-pipeline/)
Not sure whether the intent is to eventually migrate it to a **Microsoft learn** document or not.
@sdwheeler, thanks for the efforts, I leave it up to you to close or keep this issue open/suspended for a while.

**Comment by sdwheeler** [comment]
@iRon7 - I will close this for now, but eventually we will probably rework your blog post into a doc. Thanks again for the blog post.
