### ISSUE TITLE
Array.Where - Document WhereOperatorSelectionMode enum

### ISSUE THREAD

**Issue by KyleMit** [MicrosoftDocs/PowerShell-Docs#9705]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

* https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-7.3#where

### Summary

The `Array.Where` method allows passing a `WhereOperatorSelectionMode mode`

Which seems to take the same values as the [`System.Management.Automation.WhereOperatorSelectionMode` Enum](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.whereoperatorselectionmode?view=powershellsdk-7.3.0)

Can this be linked in the documentation? The reason being I'd prefer to use a library constant than a magic number or magic string like this:

```ps1
$mode = [System.Management.Automation.WhereOperatorSelectionMode]::First
(1..9).Where({ $_ -gt 3}, $mode)
```

### Details

I believe the enum is from here 

https://github.com/PowerShell/PowerShell/blob/1d34ad8b/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs#L2499

Also [this page](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.whereoperatorselectionmode?view=powershellsdk-7.3.0) is missing the `Split` field

**Comment by sdwheeler** [comment]
All of this information is in the existing docs. You can use the enum value by name as a string.

```
(dir).where({$_.extension -eq '.json'},'Last')
```

`Split` is listed in https://learn.microsoft.com/dotnet/api/system.management.automation.whereoperatorselectionmode. It is just out of order for some reason.

![image](https://user-images.githubusercontent.com/19415881/212960702-88777734-1324-4c62-a70c-8d2e2e5c9943.png)

**Comment by KyleMit** [comment]
I was wondering if https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays#where could explicitly link to https://learn.microsoft.com/dotnet/api/system.management.automation.whereoperatorselectionmode
