### ISSUE TITLE
Native argument passing on Windows default changes

### ISSUE THREAD

**Issue by JamesWTruher** [MicrosoftDocs/PowerShell-Docs#9739]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

Change https://github.com/PowerShell/PowerShell/pull/18706 adds a new `PSWindowsNativeCommandArgPassing` experimental feature. When this feature is enabled:

* On Windows
  * `$PSNativeCommandArgumentPassing` = `Windows`
* Non-Windows
  * `$PSNativeCommandArgumentPassing` = `Standard`
 
When this feature is disabled:
 
* On Windows
  * `$PSNativeCommandArgumentPassing` = `Legacy`
* Non-Windows
  * `$PSNativeCommandArgumentPassing` = `Standard`

Additionally, new telemetry metric will be added for native command execution to inform the mode being used.

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/18706

### Related Source Issues

- https://github.com/PowerShell/PowerShell/pull/18706

**Comment by floh96** [comment]
Summary is outdated see https://github.com/PowerShell/PowerShell/pull/18706#issuecomment-1542841013

**Comment by sdwheeler** [comment]
> Summary is outdated see [PowerShell/PowerShell#18706 (comment)](https://github.com/PowerShell/PowerShell/pull/18706#issuecomment-1542841013)

Updated the description.
