### ISSUE TITLE
Incorrect install location listed

### ISSUE THREAD

**Issue by castortech** [MicrosoftDocs/PowerShell-Docs#9753]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

### Summary

The documented install location doesn't match reality

### Details

Documentation states: 
"PowerShell 7.3 is installed to $env:ProgramFiles\PowerShell\7"

My Windows 10 system is showing after starting it:
"C:\ProgramFiles\WindowsApp\Microsoft.PowerShell_7.3.1.0_x64....."

**Comment by sdwheeler** [comment]
> My Windows 10 system is showing after starting it:
> "C:\ProgramFiles\WindowsApp\Microsoft.PowerShell_7.3.1.0_x64....."

That is the location when you install from the Microsoft Store.

When installing from Winget or using the MSI package, PowerShell is installed to `$env:ProgramFiles\PowerShell\7`.

**Comment by castortech** [comment]
This was the location when installing via Winget, not the Microsft Store, and if that is the case those subtleties should be part of the documentation

**Comment by castortech** [comment]
This "winget install --id Microsoft.Powershell --source winget" as documented a paragraph or so above on the same page.

**Comment by sdwheeler** [comment]
That is not possible. If you installed the `--source winget` it can only be the MSI package. You must have installed the MS Store version at some point. Check the shortcut you are using to start PowerShell. It must be pointing to the MS Store location.

**Comment by sdwheeler** [comment]
Did you install on an Arm64 system? If so, winget installs the MS Store package because that is the only package available to winget for Arm64.

**Comment by sdwheeler** [comment]
@castortech After more investigation, this is a bug in winget manifest for PowerShell 7.3.1. After the manifest was originally published, a change was made to list the MS Store (MSIX) package as the source for x86 and x64 systems. We are reverting that change.
