### ISSUE TITLE
Add example of turning off `$psnativeCommandUseErrorActionPreference` when using robocopy

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#9768]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.3, 7.4

### Summary

The new `$psnativeCommandUseErrorActionPreference`  feature depends on an exe's exit code to determine success (zero) or failure (non-zero).  However, the popular `robocopy` command seems to use non-zero as success codes, so this breaks this feature.  We don't have any plans to change how this feature detects failure, so instead we recommend having an explicit example in the docs showing how to selectively turn off this feature when using robocopy and then turning it back on for the rest of the script.

### Details

https://github.com/PowerShell/PowerShell/issues/18944

### Proposed Content Type

Cmdlet Reference

**Comment by sdwheeler** [comment]
See https://learn.microsoft.com/windows-server/administration/windows-commands/robocopy#exit-return-codes
