### ISSUE TITLE
Document using EscapeSingleQuotedStringContent API to prevent script injection

### ISSUE THREAD

**Issue by PaulHigin** [MicrosoftDocs/PowerShell-Docs#9773]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

5.1, 7.2, 7.3, 7.4

### Summary

We should document the `EscapeSingleQuotedStringContent` API and how it should be used to prevent script injection with single quoted arguments.  We should also have a general article (blog?) about script injection and mention the 'Script injection hunter for PSScriptAnalyzer.

### Proposed Content Type

About Topic

**Comment by sdwheeler** [comment]
@PaulHigin Do you have a draft you can share?

**Comment by sdwheeler** [comment]
Resources
- https://devblogs.microsoft.com/powershell/powershell-injection-hunter-security-auditing-for-powershell-scripts/
- https://learn.microsoft.com/dotnet/api/system.management.automation.language.codegeneration.escapesinglequotedstringcontent

**Comment by sdwheeler** [comment]
Thanks @PaulHigin. I will work on getting this added to the docs.
