### ISSUE TITLE
winget still shows version 7.3.1

### ISSUE THREAD

**Issue by TimTheinAtTabs** [MicrosoftDocs/PowerShell-Docs#9781]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#install-powershell-using-winget-recommended

### Summary

Your document states that after typing the command:
`winget search Microsoft.PowerShell`
then I should see version 7.3.2, but I still see 7.3.1.
When should I see the version stated in the document?

**Comment by sdwheeler** [comment]
There is a PR to update the winget package - https://github.com/microsoft/winget-pkgs/pull/95225

It should be merged soon.
