### ISSUE TITLE
No "PowerShellStandard.Library" package for supported SDK (6.0.405 longterm) found

### ISSUE THREAD

**Issue by PrismaComputer** [MicrosoftDocs/PowerShell-Docs#9783]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/create-standard-library-binary-module?view=powershell-7.1#binary-module-setup

### Summary

When I try to configure a new project, I stuck here:

`winget install Microsoft.DotNet.SDK.6`
`[...]`
`dotnet new globaljson --sdk-version 6.0.405`
`[...]`
`dotnet add package PowerShellStandard.Library --version 7.0.0-preview.1`
`[...]`
`error: There are no versions available for the "Microsoft.PowerShell.SDK" package.`

The documentation says:
"I use (SDK) 2.1.4, but you should have at least 2.0.0 until you continue"
SDK 6.0.405 is definitely higher than 2.0.0.

I would choose another SDK, but all other SDKs are outdated.
I would choose another documentation, but I found no other.
What now?

**Comment by sdwheeler** [comment]
@PrismaComputer I am not able to reproduce the problem, but I am using a newer SDK.

```
PS> dotnet --version
7.0.102

PS> dotnet new globaljson --sdk-version 7.0.102
The template "global.json file" was created successfully.

PS> dotnet add package PowerShellStandard.Library --version 7.0.0-preview.1
  Determining projects to restore...
  Writing C:\Users\user\AppData\Local\Temp\tmp99B1.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'PowerShellStandard.Library' into project 'D:\temp\MyModule\src\MyModule.csproj'.
info : Restoring packages for D:\temp\MyModule\src\MyModule.csproj...
info :   GET https://www.nuget.org/api/v2/FindPackagesById()?id='PowerShellStandard.Library'&semVerLevel=2.0.0
info :   OK https://www.nuget.org/api/v2/FindPackagesById()?id='PowerShellStandard.Library'&semVerLevel=2.0.0 234ms
info :   GET https://www.nuget.org/api/v2/package/PowerShellStandard.Library/7.0.0-preview.1
info :   GET https://api.nuget.org/v3-flatcontainer/powershellstandard.library/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/powershellstandard.library/index.json 126ms
info :   OK https://www.nuget.org/api/v2/package/PowerShellStandard.Library/7.0.0-preview.1 464ms
info : Installed PowerShellStandard.Library 7.0.0-preview.1 from https://www.nuget.org/api/v2 with content hash vd2iKiQjgB/Lh3270aMgdq/NdVq/qNHsLM8P7k/oD3hALG1UOzePa62TOSK6RlQClfXW1xI9Y1e+haHlUkF3PA==.
info : Package 'PowerShellStandard.Library' is compatible with all the specified frameworks in project 'D:\temp\MyModule\src\MyModule.csproj'.
info : PackageReference for package 'PowerShellStandard.Library' version '7.0.0-preview.1' added to file 'D:\temp\MyModule\src\MyModule.csproj'.
info : Writing assets file to disk. Path: D:\temp\MyModule\src\obj\project.assets.json
log  : Restored D:\temp\MyModule\src\MyModule.csproj (in 2.16 sec).
```

**Comment by PrismaComputer** [comment]
> @PrismaComputer I am not able to reproduce the problem, but I am using a newer SDK.
Which does not mean, that there is no problem. Using SDK 6 over 7 is a quite normal decision, because it's longtern.
