### ISSUE TITLE
Allow using a folder path in WebCmdlet's OutFile parameter

### ISSUE THREAD

**Issue by CarloToso** [MicrosoftDocs/PowerShell-Docs#9788]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### Summary

When you use -OutFile with a folder path, the file name is taken from the Content-Disposition or the resolved Uri.
You cant use the -Resume switch if -OutFile targets a folder path (error)

### Articles

- https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/invoke-webrequest
- https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/invoke-restmethod

### Related Source Pull Requests

- https://github.com/PowerShell/PowerShell/pull/19007
- https://github.com/PowerShell/PowerShell/pull/19385

### Related Source Issues

- https://github.com/PowerShell/PowerShell/issues/11671

**Comment by mklement0** [comment]
@CarloToso, I'm glad to see that this is finally getting implemented, but let me point out two things:

* [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) may not be used _often_ (I can't speak to that), but it is definitely used, including on GitHub, and both `curl` and `wget` support it, albeit on an _opt-in_ basis (`-J` and `--content-disposition`)

* > the file name is taken from the resolved Uri.
  * Worth clarifying that it is the _last_ URI segment that is used, and that
  * it seems to be the _ultimately-redirected-to_ URI whose last segment is used, correct?
    * Contrast this with `curl` uses the _input_ URI's last segment with `-O` (either approach is defensible).
