### ISSUE TITLE
Using dynamic help: mention how to enable Alt-based keyboard shortcuts on macOS

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#9811]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/learn/shell/dynamic-help.md

### Summary

While it is true that <kbd>Alt</kbd>-based keyboard shortcuts do not work on macOS _by default_, it is easy to configure the terminal applications (the built-in Terminal.app and popular third-party alternative iTerm2.app) to support them.

This is worth mentioning as an alternative to resorting to <kbd>Ctrl</kbd>-based redefinitions.

See https://github.com/PowerShell/PSReadLine/issues/1075#issuecomment-1412449026

**Comment by sdwheeler** [comment]
@mklement0 We are working on some documentation about keybindings for non-Windows platforms. I will make sure to include this information.
