### ISSUE TITLE
`-Stream` and `-Recurse` from `Remove-Item` should be in different Parameter Sets

### ISSUE THREAD

**Issue by santisq** [MicrosoftDocs/PowerShell-Docs#9822]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7.3#syntax

### Summary

[__Syntax__](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7.3#syntax) section of `Remove-Item` documentation shows that `-Stream` and `-Recurse` can be used together when they actually can't.

### Details

This issue was noted in [this SO question](https://stackoverflow.com/questions/75442886/remove-alternative-data-stream-using-powershell/75443083). Please let me know if more details are needed.

```powershell
$folder = New-Item .\test -ItemType Directory
Set-Content $folder -Value 'hello world' -Stream test
Remove-Item $folder -Stream test -Recurse

# Errors with:
# Remove-Item: A parameter cannot be found that matches parameter name 'Stream'.
```

### Suggested Fix

Remove `-Stream` from the Parameter Sets being displayed in the doc and add a new Parameter Set with the available Parameters for `-Stream`.

**Comment by sdwheeler** [comment]
We have to show those parameters in the same parameter set because that is how the cmdlet is defined. But `-Stream` is a dynamic parameter that comes from the **FileSystem** provider. We can document that they don't work together.

**Comment by santisq** [comment]
thank you for the fast response @sdwheeler, awesome work <3
