### ISSUE TITLE
Get-Date example error

### ISSUE THREAD

**Issue by Dd2019-git4test** [MicrosoftDocs/PowerShell-Docs#9827]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Date?view=powershell-7.3&viewFallbackFrom=powershell-3.0

### Summary

Function in an example 
$timestamp = Get-Date -Format o | ForEach-Object { $_ -replace ":", "." }
New-Item -Path C:\Test\$timestamp -Type Directory
on a page 
https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Date?view=powershell-7.3&viewFallbackFrom=powershell-3.0

work incorrect, when UTC on PLUS zone, because missed replace function for PLUS symbol

### Details

PS C:\> $timestamp = Get-Date -Format o | ForEach-Object { $_ -replace ":", "." }
$timestamp
2023-02-15T13.40.28.9927886+07.00

### Suggested Fix

use another example

**Comment by sdwheeler** [comment]
@Dd2019-git4test What error are you getting? In my tests, I can create a directory that has a `+` character in the name.

**Comment by sdwheeler** [comment]
@Dd2019-git4test What error are you getting? In my tests, I can create a directory  that has a `+` character in the name.

**Comment by Dd2019-git4test** [comment]
I could not reproduce today, and I have already rewritten that part of my code. Apparently he hurried to write a ticket before rechecking
