### ISSUE TITLE
AccessDBProvider samples should have their own source repo pages

### ISSUE THREAD

**Issue by aldosa** [MicrosoftDocs/PowerShell-Docs#9855]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/developer/prog-guide/accessdbprovidersample02-code-sample?view=powershell-7.3 and related sections.

### Summary

The big purple note in most pages on samples make a reference to the .NET Framework and PowerShell SDK for older versions is not relevant. 

### Details

I don't think it serves purpose to have **version 7.3 and counting!** documentation referencing these SDKs (for Windows Server 2012 and other obsolete Windows and PS versions), since no one is going to download that SDK just to get at the hard copy of the samples. 

I am referring to this:

### Suggested Fix

Please remove the below notices in the newer documentation and possibly take the trouble to add a dedicated repo or section with samples. While you're at it would you kindly check these demos still run in the target version?

This simple consideration on your part would make the documentation that much easier to follow and prevent people from getting distracted looking at irrelevant links.

**Comment by sdwheeler** [comment]
The sample content in the Legacy SDK docs is not being maintained. However, all of the code samples can be found in https://github.com/MicrosoftDocs/powershell-sdk-samples.

**Comment by aldosa** [comment]
Don't follow. The documentation I'm alluding to is for PowerShell 7.3 and similar. My point is exactly that: the link you list above should replace the link in the current documentation since it is for a legacy product. Why not refer to it directly instead of spend time requesting a fix?

**Comment by sdwheeler** [comment]
The version selector controls what cmdlet reference appears in the Table of Contents under the **Reference** node. It does not affect the docs above that. The code samples in the **Windows PowerShell Programmer's Guide** is part of the **Legacy PowerShell SDK** documentation. 

Much of those docs apply to any version of PowerShell but it was written for Windows PowerShell starting in the Windows PowerShell 3.0 timeline. We are no longer maintaining these samples and don't guarantee that they will work in the current version of PowerShell.

The install article has a link to the code repository, see [Installing the Windows PowerShell SDK](https://learn.microsoft.com/powershell/scripting/developer/installing-the-windows-powershell-sdk#installing-windows-powershell-30-sdk-for-windows-8-and-windows-server-2012).

**Comment by aldosa** [comment]
Appreciate you taking the time to explain that @sdwheeler. It seems the github docs still have similar issues to the MSDN documentation they replaced. If at some point that can be fixed I'm sure many people would benefit. Use case for Bing chatbot?

**Comment by aldosa** [comment]
Thank you for taking the time to reply, Sean. It’s good to be reminded there are people behind those systems.
