### ISSUE TITLE
Cannot use browser text search on documentation pages to search for keyboard shortcuts like "CTRL+C"

### ISSUE THREAD

**Issue by Ryan-Roberts-Unity** [MicrosoftDocs/PowerShell-Docs#9866]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.3

### Summary

I was on [this pwsh documentation page ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.3)and I wanted to search/find for all instances of "CTRL+C". A number of instances exist on the page but due to the webpage formatting it doesn't allow for direct searching of them: 
![image](https://user-images.githubusercontent.com/115487345/222492819-54ef02b6-c315-4607-ae7a-87fd3e1a8f06.png)

Workaround: instead search on "ctrl" and hope there aren't many (as there luckily is in this case):
![image](https://user-images.githubusercontent.com/115487345/222492941-d73759db-28f3-44d2-b6a7-a822ef30f158.png)

### Suggested Fix

Keep the visual formatting but don't modify the underlying text, keep it as either "ctrl+c" or "Ctrl + C"

**Comment by sdwheeler** [comment]
@Ryan-Roberts-Unity Thanks for the feedback. The publishing platform doesn't have the ability to create the visual formatting without marking up the original source text. Using the workaround you described is the best option.

**Comment by Ryan-Roberts-Unity** [comment]
@sdwheeler Is there a github repository for the publishing platform so this feedback can be revisted there?

**Comment by sdwheeler** [comment]
@Ryan-Roberts-Unity Not a public one. There is a feedback button at the top of the page.

![image](https://user-images.githubusercontent.com/19415881/223173935-9d1b6217-6d19-4de0-b225-08d16f3deeea.png)

Your comments there will get directed to the platform team.

**Comment by Ryan-Roberts-Unity** [comment]
Thanks, left this feedback there.
