### ISSUE TITLE
Undocumented Parameter for Sort

### ISSUE THREAD

**Issue by mscott3** [MicrosoftDocs/PowerShell-Docs#9869]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://www.bing.com/search?q=powershell+sort&cvid=84329310e9d64abba92380da9ffa9bcc&aqs=edge..69i57.1789j0j1&FORM=ANNAB1&PC=U531&ntref=1

### Summary

I recently discovered that the Sort pipeline operator will accept a script block that returns the sort key.
I can find no documentation of this feature. 

### Details

I've carefully reviewed the linked documentation, and can find no reference to my ability to do this:

     @("five-5", "two-2", "one-1", "twelve-12") | sort { [int]($_.split('-')[1]) }

resulting in:

     one-1
     two-2
     five-5
     twelve-12

That is a pretty significant capability that should be documented (  I stumbled across it in a StackOverflow post ).
Further, you can leverage this capability to allow for multi-key sorting using Tuples.  Since Tuples compare piecewise, your key block can simply throw the keys in a Tuple in the sort order and you have achieved a multi-key sort.  
For example:

     $data = @( 
        @{ vendor="Oracle"; product="JRE"; ver=8}, 
        @{vendor="Oracle"; product="JDK"; ver=8}, 
        @{vendor="Azul"; product="JDK"; ver=11}, 
        @{vendor="Azul"; product="JDK"; ver=17}, 
        @{vendor="Oracle"; product="JRE"; ver=11} 
    )
    $data | sort {[tuple]::Create($_.product, $_.ver, $_.Vendor) } | foreach {" $($_.product) $($_.ver) $($_.vendor)"} 

yielding:

    JDK 8 Oracle
    JDK 11 Azul
    JDK 17 Azul
    JRE 8 Oracle
    JRE 11 Oracle

### Suggested Fix

Include the above examples in the documentation.

**Comment by sdwheeler** [comment]
@mscott3 This is documented. What you call the "Sort pipeline operator" is the `Sort-Object` cmdlet. In your examples, the script block gets bound to the `-Property` parameter. See the documentation for the parameter at: https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/sort-object#-property

Here is the relevant text:

> Valid keys for a hash table are as follows:

> 
> - expression - `<string>` or `<script block>`
> - `ascending` or `descending` - `<boolean>`

> 
> For more information, see [about_Calculated_Properties](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_calculated_properties).

The about_Caluclated_Properties article has examples for [Sort-Object](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_calculated_properties#sort-object).
