### ISSUE TITLE
Remove-Alias: invalid example

### ISSUE THREAD

**Issue by 4cq2** [MicrosoftDocs/PowerShell-Docs#9876]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

links

### Summary

here:

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.2/Microsoft.PowerShell.Utility/Remove-Alias.md

I see this:

~~~
Get-Alias | Where-Object { $_.Options -NE "Constant" } | Remove-Alias -Force
~~~

but this command has a problem. the `where-object` clause is serving no purpose here, as you can omit it:

~~~
Get-Alias | Remove-Alias -Force
~~~

the reason is because it only accounts for constant, when it should account for read-only as well:

~~~
> Get-Alias % | remove-alias
remove-alias : Alias was not removed because alias % is constant or read-only.
~~~

here:

~~~
> Get-Alias % | % { $_.options }
ReadOnly, AllScope
~~~

so either the `where-object` clause should be fixed to include `ReadOnly` as well, or it should simply be removed.

**Comment by sdwheeler** [comment]
@4cq2 The point of the example is to show how to remove a filtered list of aliases. The fact that you may not have any **Constant** doesn't matter. If you do have a **Constant** alias, `Remove-Alias` will fail. For example:

```powershell
PS> New-Alias -Name foo -Value Get-ChildItem -Option Constant
PS> Remove-Alias foo -Force

Remove-Alias: Alias was not removed because alias foo is constant or read-only.
```
