### ISSUE TITLE
Refer to hashtable lookup table

### ISSUE THREAD

**Issue by iRon7** [MicrosoftDocs/PowerShell-Docs#9899]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations

### Summary

The use of a hashtable lookup as defined in [Everything you wanted to know about hashtables](https://learn.microsoft.com/powershell/scripting/learn/deep-dives/everything-about-hashtable) at [As a lookup table](https://learn.microsoft.com/powershell/scripting/learn/deep-dives/everything-about-hashtable#as-a-lookup-table) could be a real game changer if it concerns the performance of a script. Yet it is nowhere mentioned in this document.

### Suggested Fix

It might help others if there would be a "hashtable lookup" section or at least a referral to this the Hashtable document.

**Comment by sdwheeler** [comment]
@iRon7 how does hashtable lookup affect performance?

**Comment by iRon7** [comment]
> how does hashtable lookup affect performance?

I will supply an example tomorrow.

**Comment by iRon7** [comment]
@sdwheeler,

I have created a purpose for a  **Use a HashTable to lookup values or objects** section here: https://github.com/iRon7/PowerShell-Docs/blob/iRon7---HashTable-Performance/reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md#use-a-hashtable-to-lookup-values-or-objects
Should I do a PR on this?

**Comment by iRon7** [comment]
@sdwheeler,

I did a PR as I do not want to get too far behind (and get you attention)
Please not that I am quiet new to your processes, so don't hesitate to come back to be if I did something wrong in the process.

**Comment by michaeltlombardi** [comment]
@iRon7 do you have some time to chat? It looks like you've created a pull request in your repository to merge our changes onto yours. I think what you want to do instead is:

1. Open your repository locally.
2. Open git in the terminal at the root of your repository.
3. Add our repository as an upstream with git, like:

   ```sh
   git remote add upstream https://github.com/MicrosoftDocs/PowerShell-Docs.git
   ```

4. Rebase your work on ours - this will ensure your changes are up-to-date for your PR:

   ```sh
   git fetch --all --prune
   git rebase upstream/main
   ```

5. Create a working branch for your changes locally, like:

   ```sh
   git checkout -b gh-9899
   ```

6. Push your new working branch:

   ```sh
   git push -u origin gh-9899
   ```

7. [Open a pull request in our repository][01] to have us review your changes.

I'm also happy to hop on a call and help you through this process!

[01]: https://github.com/MicrosoftDocs/PowerShell-Docs/compare

**Comment by iRon7** [comment]
@michaeltlombardi,
Thank you for your reply.
I am happy if to chat and get some guidance here.
What would be the easiest?
Teams?

**Comment by iRon7** [comment]
I am indeed not in discord.

But I have opened a Teams meeting right now:

https://teams.microsoft.com/l/meetup-join/19:meeting_NTI2YjNkYzAtYTg3My00NzIwLWJkZGItNDQxNjM1YWYzZTc3@thread.v2/0?context=%7B%22Tid%22:%2217e5b8a2-85d0-485e-ab75-e9a0a6adbf17%22,%22Oid%22:%223fbcdb7c-a49b-4afe-be98-dea45ec00e37%22%7D
