### ISSUE TITLE
Why offer a KB article what goes against best practices and doesn't list alternative method  

### ISSUE THREAD

**Issue by molderog** [MicrosoftDocs/PowerShell-Docs#9907]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/samples/working-with-software-installations?view=powershell-7.3#listing-windows-installer-applications
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa394378(v=vs.85)

### Summary

This has been going on 10+ plus years where MS documents the usage of Win32_Product and just adds a disclaimer to the page.  What is the purpose of the KB if people are not supposed to use it?

The listed **[KB article 974524](https://support.microsoft.com/help/974524).**  list the alternative Win32Reg_AddRemovePrograms but its only available to computers with  SSCM.    What is the alternative for non-SCCM environment?

I have seen multiple commercial products use Win32_Product causing havoc when its trying inventory or query for software.

Just like SQL a SELECT statement should not have side effects. 

### Suggested Fix

Either provide an alternative for all PCs or better yet remove the unwanted side effect of performing a repairs.

**Comment by sdwheeler** [comment]
The alternative to using **Win32Reg_AddRemovePrograms** is to search the Uninstall key in the registry as shown in the *Working with software installations* article.

The following example returns information similar to **Win32Reg_AddRemovePrograms**.

```powershell
dir HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall | 
    ForEach-Object { 
        Get-ItemProperty -Path Uninstall:$_ -Name DisplayName, InstallDate, UninstallString, Publisher, DisplayVersion -ea SilentlyContinue | 
        Select-Object DisplayName, InstallDate, @{n='ProdID'; e={$_.UninstallString -replace 'MsiExec.exe /.'}}, Publisher, DisplayVersion
}
```
