### ISSUE TITLE
PowerShell 5 feedback sends users to PowerShell 7 repo, even for non 5 only features (e.g. ISE)

### ISSUE THREAD

**Issue by jhoneill** [MicrosoftDocs/PowerShell-Docs#9939]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-gb/powershell/scripting/windows-powershell/ise/exploring-the-windows-powershell-ise 

### Summary

Pressing F1 in the Windows PowerShell ISE takes the user via a "go" Link to 

https://learn.microsoft.com/en-gb/powershell/scripting/windows-powershell/ise/exploring-the-windows-powershell-ise?view=powershell-7.3

This version is wrong and if the user wants to provided feedback on the ISE they are sent to the PowerShell 7 repo which cannot deal with ISE matters.  Even changing the version to 5.1 still sends the user to report their issue as a V7 one

### Details

The Powershell 7 hierarchy on learn has Windows PowerShell branches which do not apply to V7

All unqualified links seem to go to the latest version which is not correct for Windows PowerShell ISE matters. 

All PowerShell 5 feedback directs to PowerShell 7

### Suggested Fix

The GO link from the ISE should point to the PowerShell 5 hierarchy explicity

PowerShell 5 specific topics should not be listed when the version selected is PowerShell 7

PowerShell 5 specific topics should direct users to the correct places for feed back

**Comment by sdwheeler** [comment]
For this docset, the version selector only affects the cmdlet reference. This is by design for this docset.

I have updated the GO link to use the 5.1 version selector.

**Comment by jhoneill** [comment]
@sdwheeler  thanks for doing that; but the we still have the problem that if someone presses F1 in the ISE and scrolls to the bottom of the page the _Submit feedback for this product_ link goes to the PowerShell 7 repo.
