### ISSUE TITLE
PSH Code That Preserves PSModulePath When Installing WMF 5 Over WMF 3 on Win7/Server 2008 R2 (possibly integrate into Install-WMF5.1.PS1?)

### ISSUE THREAD

**Issue by DarwinJS** [MicrosoftDocs/PowerShell-Docs#994]
I am one of the packagers that maintains the PowerShell package on Chocolatey.

I am very thankful that WMF 5.1 allows direct installation on Win 7 / Server 2008 R2.

The installation instructions and install helper Install-WMF5.1.PS1 are discussed here: https://msdn.microsoft.com/en-us/powershell/wmf/5.1/install-configure whose source is here: https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.1/install-configure.md

These instructions include manual steps to avoid losing the PSModulePath when installing WMF 5.1 over WMF 3 on Win7 / Server 2008 R2.  One of the benefits of a meta-packager (my term) like Chocolatey is that some of these challenges can be handled (or attempted at least).

I believe I have successfully created a chocolatey package that uses PowerShell code to preserve the PSModulePath.

Since the PowerShell team has already written a PowerShell based wrapper for installing on Win 7 / Server 2008 R2 - the changes I made could be propagated to the current wrapper script.

Here is a brief description of what the code does taken from the source and chocolatey release notes:

1. The custom parts of the PSModulePath are backed up to BackupPSModulePath
2. A fix up script that appends those values to the PSModulePath is written to:
     %WINDIR%\Temp\psmodulepathfixup.ps1
3. A scheduled task is setup to run the fix up script on the next reboot and remove itself from scheduled tasks.

If you find that number 3 does not work correctly, then you can use  number 1 or number 2 with some of your own automation to recover from the situation.

Design Goals / Implementation Details:
- installing on servers (where the problem must be fixed with a single reboot and no user login) - is handled by using an "onstart" scheduled task that self-deletes.
- schtasks.exe is used since *scheduledtask* CMDLets are not available on WMF 3.
- preserves all paths without expanding environment variables (so should work on non-standard windows folder installs).
- backs up path customizations to an environment variable (BackupPSModulePath)
- leaves it's fix up script in %WINDIR%\temp
- during reboot it **dynamically appends** the customized paths to whatever path the WMF 5.1 installer put down

My code is here: https://github.com/IntelliTect/Chocolatey.Packages/blob/master/PowerShell/v5.1/tools/ChocolateyInstall.ps1#L109-L178

Obviously the Chocolatey specific install commands would need to be replaced with calls to wusa.exe.

I could also do a pull request if "Install-WMF5.1.PS1" is on github somewhere.

**Comment by zjalexander** [comment]
cc @KrishnaV-MSFT and @JKeithB for WMF 5.1 issue

**Comment by sdwheeler** [comment]
@JKeithB - can you comment on this issue?

**Comment by DarwinJS** [comment]
@sdwheeler - I originally submitted this 18 months ago.  I don't have a direct need for this - so if there is not other customer demand - not a priority for me.
