### ISSUE TITLE
PSModulePath  CurrentUser scope is not $HOME\Documents\WindowsPowerShell\Modules

### ISSUE THREAD

**Issue by RobMahn** [MicrosoftDocs/PowerShell-Docs#9946]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath?view=powershell-5.1

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath?view=powershell-7.3

Unverified functionality, but the documentation is the same on other versions.

### Summary

The documentation says, "On Windows, the location of the user-specific CurrentUser scope is the $HOME\Documents\WindowsPowerShell\Modules folder."

"$HOME\Documents" is actually the location of the Documents Library as defined in:
reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -v Personal

**Comment by sdwheeler** [comment]
The information as written is correct for all versions.

However, I did tweak some of the wording to improve the readability.

**Comment by RobMahn** [comment]
I don't see how the CurrentUser scope can be using $HOME.

This is from my V5 Powershell:

PS C:\> $HOME
**C:**\Users\RobMa

PS C:\> $env:PSModulePath -split ';'
**D:**\Users\RobMa\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules

PS C:\> reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -v Personal

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
    Personal    REG_EXPAND_SZ    **D:\Users\RobMa\Documents**
