### ISSUE TITLE
Clarify when the call operator executes the command as a powershell script or as an external command

### ISSUE THREAD

**Issue by rgl** [MicrosoftDocs/PowerShell-Docs#9974]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.3#call-operator-

### Summary

Please clarify when the call operator (`&`) executes the command as a powershell script (as an internal session/sub-shell) or as an external command.

For me, its somewhat ambiguous when powershell will do one of those.

It could mean that its looking for the file extension? e.g. *.ps1 (and *.psm1, and which more?) are always interpreted as a powershell script?

What about other OSes like Linux where its normal to ignore the file extensions and delegate that decision to the OS (e.g. to let it handle things like the `#!/bin/bash` shebang)?

**Comment by sdwheeler** [comment]
@rgl The call operator executes any executable file. That can be a PowerShell script (`.ps1` file) or and external command. The `.ps1` extension is the only PowerShell file type that PowerShell considers executable.

You don't need to use the call operator to run an executable unless you are using an expression. For example, you used a string expression when the executable file is in path that contains spaces or you want to build the full command line from strings.

```
& 'C:\Program Files\Pandoc\pandoc.exe'
```

or 

```
$pandocExe = 'C:\Program Files\Pandoc\pandoc.exe'
$pandocArgs = @(
    '--from=gfm',
    '--to=plain+multiline_tables',
    '--columns=79',
    "--output=.\plaintext.txt",
    '--quiet'
)
Get-Content .\plaintext.md | & $pandocExe $pandocArgs
```

On non-Windows systems, the shebang header only applies to other shells. This allows shells like bash to see a `.ps1` file as an executable file.

**Comment by rgl** [comment]
Sorry, I didn't provide enough context. This plea for clarification comes after I was caught by surprise by the fact that powershell, when using the following syntax, executes the powershell script in the same process instead of creating a new external powershell process to execute script there (that fact lead me to unknown/unexpected side-effects, like not loading the already loaded modules):

```powershell
c:\script.ps1 # or &c:\script.ps1
```

The only clarification that I would like to see in the documentation is what logic powershell uses to decide whether to execute the file as a powershell script (in the same process) or as an external command.

If the only thing that triggers that behavior is the file extension being `.ps1`, please document it as such in the call operator page.

The phrase you've used is somewhat ambiguous to me (especially when talking about unix like oses, which have an explicit way to set a file as "executable"):

>  The .ps1 extension is the only PowerShell file type that PowerShell considers executable.

I would put it (if true) as:

>  The `.ps1` extension is the only PowerShell file type that is considered as a script. PowerShell will execute it in the current process, in a new script scope.

**Comment by sdwheeler** [comment]
> set a file as "executable" by using `chmod +x` (the shebang is not enough)

Yes, I know you must set the mode for executable in Unix. My point is that PowerShell does not use shebang. That only works in Unix shells like bash, csh, zsh, etc. the shebang comment in the script file tell Unix which program to use to execute the script. You can configure use `#!/opt/microsoft/powershell/7/pwsh` in a PowerShell script to make it executable from bash.
