### ISSUE TITLE
The large quantity of examples is good, but an example involving a _boolean_ would be welcome

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [MicrosoftDocs/PowerShell-Docs#9981]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_switch?view=powershell-7.3

### Summary

It would be good were the documentation page to make clear whether the following will work (i.e. will parse and will give the outcome that the programmer is likely to expect).

```
switch ( $myBoolean)
{
    $true { <do something> }
}
```

### Suggested Fix

Give an example of the type that I presented above.

**Comment by sdwheeler** [comment]
Yes, this will work but why wouldn't you just use an `if` statement?

**Comment by LinuxOnTheDesktop** [comment]
Thank you for the information. Your query though seems besides the point. But the answer in my case was: to make the code more readable (for, I had many nested conditionals; admittedly, that was itself a problem and I have in fact refactored).

**Comment by sdwheeler** [comment]
We believe that using the `switch` statement for boolean evaluation is an anti-pattern we don't want to encourage or document.
