### ISSUE TITLE
REGEXP implemented standard info

### ISSUE THREAD

**Issue by inoperable** [MicrosoftDocs/PowerShell-Docs#9983]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-7.3
- https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference

### Summary

No clear information about implemented **REGEXP** standard.

Is it POSIX? BRE? ERE? PERL/PCRE? 

Great that you send the users to a document of .NET implementation, 
but I can't find a clear information what STANDARD is implemented.
.NET implementation is not a standard at all... 

### Details

NONE

### Suggested Fix

Place a one line information of what exact standard is implemented

**Comment by sdwheeler** [comment]
PowerShell uses the .NET implementation for regular expressions. Any documentation about standards belongs in that documentation. .NET is a standard.

**Comment by inoperable** [comment]
Standard defined by whom/what?

**Comment by inoperable** [comment]
Maybe referencing this link into the docs isn't a bad idea. This more or less explains how the implementation works
with some version differences -> https://www.regular-expressions.info/dotnet.html
