### ISSUE TITLE
Wrong description for Multiselection

### ISSUE THREAD

**Issue by a455047** [MicrosoftDocs/PowerShell-Docs#9994]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.3#multiselection

### Summary

incorrect statement and code for Multiselection
$environments[@('QA','DEV')]
$environments[('QA','DEV')]
$environments['QA','DEV']

it will be error

### Details

this is wrong code with "Multiselection
Generally, you think of a hashtable as a key/value pair, where you provide one key and get one value. PowerShell allows you to provide an array of keys to get multiple values...... In this example, I use the same lookup hashtable from above and provide three different array styles to get the matches. This is a hidden gem in PowerShell that most people aren't aware of."
https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.3#multiselection

real outcome:
PS F:\> $environments[@('QA','DEV')]
>> $environments[('QA','DEV')]      
>> $environments['QA','DEV']        
InvalidOperation: Cannot index into a null array.
InvalidOperation: 
Line |
   2 |  $environments[('QA','DEV')]   
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~   
     | Cannot index into a null array.
InvalidOperation: 
Line |
   3 |  $environments['QA','DEV']     
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~     
     | Cannot index into a null array.
     
     

### Suggested Fix

update documentation

**Comment by sdwheeler** [comment]
@a455047 It works for me:

```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> $environments = @{
      Prod = 'SrvProd05'
      QA   = 'SrvQA02'
      Dev  = 'SrvDev12'
  }
PS> $environments[@('QA','DEV')]
SrvQA02
SrvDev12
PS> $environments[('QA','DEV')]
SrvQA02
SrvDev12
PS> $environments[('QA','DEV')]
SrvQA02
SrvDev12
```
