### ISSUE TITLE
Recommend `List<T>` instead of `ArrayList` in Performance Considerations doc

### ISSUE THREAD

**Issue by santisq** [MicrosoftDocs/PowerShell-Docs#9997]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

- https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations?view=powershell-7.3#array-addition

### Summary

[__Array addition__](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations?view=powershell-7.3#array-addition) section of our performance considerations doc should recommend the use of a `List<T>` instead of an `ArrayList`.

### Details

The documentation rightfully recommends the use of a mutable collection while in need to add new elements to them, however its recommending the use of an `ArrayList` instead of a `List<T>`. From a performance perspective the use of a `List<T>` might not be very noticeable in PowerShell, but they bring quality of life changes such as `void` `.Add` method or coercion of the added items:

```powershell
$list = [System.Collections.Generic.List[System.IO.DirectoryInfo]]::new()
$list.Add($pwd.Path)
```

Its also worth noting that the `.Add` method having a return value on `ArrayList` often brings questions from new folks coming to PowerShell, an example of the most recent SO question closed by me:

- https://stackoverflow.com/questions/75972680/array-of-objects-are-twice-after-return

Finally, the [.NET Docs](https://learn.microsoft.com/en-us/dotnet/api/system.collections.arraylist?view=net-8.0#remarks) already do recommend the use of `List<T>`:

![image](https://user-images.githubusercontent.com/23342410/231010754-06d4560d-629d-4d18-bd5b-a2fbe7cfc5b5.png)

### Suggested Fix

Update the doc recommending to use `List<T>` instead of `ArrayList` when in need to use a mutable collection.

As aside, stating that arrays have a fixed capacity might be better phrased than arrays being immutable, though this is personal opinion.

For instance, `System.Array` doc states in [Remarks](https://learn.microsoft.com/en-us/dotnet/api/system.array?view=net-8.0#remarks):

> Unlike the classes in the [System.Collections](https://learn.microsoft.com/en-us/dotnet/api/system.collections?view=net-8.0) namespaces, [Array](https://learn.microsoft.com/en-us/dotnet/api/system.array?view=net-8.0) has a __fixed capacity__. To increase the capacity, you must create a new [Array](https://learn.microsoft.com/en-us/dotnet/api/system.array?view=net-8.0) object with the required capacity, copy the elements from the old [Array](https://learn.microsoft.com/en-us/dotnet/api/system.array?view=net-8.0) object to the new one, and delete the old [Array](https://learn.microsoft.com/en-us/dotnet/api/system.array?view=net-8.0).

As for contributing to the doc, I have written this test some time ago to help folks visualize how addition to arrays and lists scale in PowerShell, could be helpful to others if you consider its worth adding it (or a simplified version of it):

```powershell
$tests = @{
    'PowerShell Explicit Assignment' = {
        param($count)

        $result = foreach($i in 1..$count) {
            $i
        }
    }
    '.Add(..) to List<T>' = {
        param($count)

        $result = [Collections.Generic.List[int]]::new()
        foreach($i in 1..$count) {
            $result.Add($i)
        }
    }
    '+= Operator to Array' = {
        param($count)

        $result = @()
        foreach($i in 1..$count) {
            $result += $i
        }
    }
}

5000, 10000, 25000, 50000, 75000, 100000 | ForEach-Object {
    $groupresult = foreach($test in $tests.GetEnumerator()) {
        $totalms = (Measure-Command { & $test.Value -Count $_ }).TotalMilliseconds

        [pscustomobject]@{
            CollectionSize    = $_
            Test              = $test.Key
            TotalMilliseconds = [math]::Round($totalms, 2)
        }

        [GC]::Collect()
        [GC]::WaitForPendingFinalizers()
    }

    $groupresult = $groupresult | Sort-Object TotalMilliseconds
    $groupresult | Select-Object *, @{
        Name       = 'RelativeSpeed'
        Expression = {
            $relativespeed = $_.TotalMilliseconds / $groupresult[0].TotalMilliseconds
            [math]::Round($relativespeed, 2).ToString() + 'x'
        }
    }
}
```

Results:

```
CollectionSize Test                           TotalMilliseconds RelativeSpeed
-------------- ----                           ----------------- -------------
          5000 PowerShell Explicit Assignment              0.56 1x
          5000 .Add(..) to List<T>                         7.56 13.5x
          5000 += Operator to Array                     1357.74 2424.54x
         10000 PowerShell Explicit Assignment              0.77 1x
         10000 .Add(..) to List<T>                        18.20 23.64x
         10000 += Operator to Array                     5411.23 7027.57x
         25000 PowerShell Explicit Assignment              1.39 1x
         25000 .Add(..) to List<T>                        47.14 33.91x
         25000 += Operator to Array                    26168.67 18826.38x
         50000 PowerShell Explicit Assignment              3.49 1x
         50000 .Add(..) to List<T>                        97.38 27.9x
         50000 += Operator to Array                   129537.09 37116.64x
         75000 PowerShell Explicit Assignment             14.59 1x
         75000 .Add(..) to List<T>                       243.47 16.69x
         75000 += Operator to Array                   247419.68 16958.17x
        100000 PowerShell Explicit Assignment             14.85 1x
        100000 .Add(..) to List<T>                       177.13 11.93x
        100000 += Operator to Array                   473824.71 31907.39x
```

**Comment by iRon7** [comment]
> As aside, stating that arrays have a fixed capacity might be better phrased than arrays being immutable, though this is personal opinion.

Whether arrays have a fixed capacity it not, is (afaik) not the (only) cause of the performance degradation:

```PowerShell
$tests = @{
    'PowerShell Explicit Assignment' = {
        param($count)

        $result = foreach($i in 1..$count) {
            $i
        }
    }
    '.Add(..) to List<T>' = {
        param($count)

        $result = [Collections.Generic.List[int]]::new()
        foreach($i in 1..$count) {
            $result.Add($i)
        }
    }
    '+= Operator to Array' = {
        param($count)

        $result = @()
        foreach($i in 1..$count) {
            $result += $i
        }
    }
    '+= Operator to List<T>' = {
        param($count)

        $result = [Collections.Generic.List[int]]::new()
        foreach($i in 1..$count) {
            $result += $i
        }
    }
}

5kb, 10kb, 100kb | ForEach-Object {
    $groupResult = foreach($test in $tests.GetEnumerator()) {
        $ms = (Measure-Command { & $test.Value -Count $_ }).TotalMilliseconds

        [pscustomobject]@{
            CollectionSize    = $_
            Test              = $test.Key
            TotalMilliseconds = [math]::Round($ms, 2)
        }

        [GC]::Collect()
        [GC]::WaitForPendingFinalizers()
    }

    $groupResult = $groupResult | Sort-Object TotalMilliseconds
    $groupResult | Select-Object *, @{
        Name       = 'RelativeSpeed'
        Expression = {
            $relativeSpeed = $_.TotalMilliseconds / $groupResult[0].TotalMilliseconds
            [math]::Round($relativeSpeed, 2).ToString() + 'x'
        }
    }
}
```

```
CollectionSize Test                           TotalMilliseconds RelativeSpeed
-------------- ----                           ----------------- -------------
          5120 PowerShell Explicit Assignment              0.18 1x
          5120 .Add(..) to List<T>                         1.01 5.61x
          5120 += Operator to Array                      203.34 1129.67x
          5120 += Operator to List<T>                    204.92 1138.44x
         10240 PowerShell Explicit Assignment              0.90 1x
         10240 .Add(..) to List<T>                         3.21 3.57x
         10240 += Operator to Array                     2234.18 2482.42x
         10240 += Operator to List<T>                   2362.94 2625.49x
        102400 PowerShell Explicit Assignment              4.26 1x
        102400 .Add(..) to List<T>                        26.59 6.24x
        102400 += Operator to Array                   135177.03 31731.7x
        102400 += Operator to List<T>                 143488.63 33682.78x
```
These results let me conclude that the `+` /  `+=` operator (related to the `op_Addition` method) is in fact the common cause.

**Comment by iRon7** [comment]
Oops, I missed this behavior: using the `+` or `+=` operator changes the type back to an array:
```PowerShell
$a = [Collections.Generic.List[int]]::new()
$a.PSTypeNames
System.Collections.Generic.List`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
System.Object
```
```PowerShell
$a += 1
$a.PSTypeNames
System.Object[]
System.Array
System.Object
```
